== Prefacio

Después de una labor de más de veinticinco años,
finalmente sale a la luz pública esta historia,
compilación a la que fui inducido por la consideración de que el levantamiento e incremento
de esta sociedad religiosa (de la que en esta obra he dado una descripción detallada),
es, de hecho, algo tan raro y maravilloso,
que creo que poco se encontrará en historias modernas que pueda compararse con ella.
En el momento de la publicación de esta historia, en el año 1717,
los llamados Cuáqueros se han convertido en un gran pueblo, bajo una muy pesada opresión,
tal como se menciona aquí, la cual no sucedió por algún poder humano,
ni porque tomaran armas,
sino por su inofensivo comportamiento y ejercicio de la
paciencia--pues portar armas y resistir al malvado luchando,
siempre lo han considerado abominable y contrario a la doctrina de nuestro Salvador.
Por tanto, los que no tenían rey, príncipe, ni potentado para protegerlos,
y quienes al principio no tenían entre ellos ningún hombre de renombre,
ni de educación superior,
sino que confiando en su integridad y poniendo su confianza sólo en Dios,
finalmente han triunfado sobre la malicia de sus opositores, al sufrir (a tal punto,
que fue a expensas de las vidas de muchos de ellos)
bajo la violenta opresión de altos y bajos,
y la oposición de los educados y no educados.

Todo esto me pareció tan maravilloso,
después de mucha búsqueda y de descubrirlo mediante una asidua diligencia,
que resolví hacer un relato al respecto,
a pesar del gran trabajo que pronto percibí que iba a requerir esta obra.
A esto se debe agregar, que cuando consideré que varios autores,
tanto alemanes como otros,
habían publicado libros y relatos llenos de groseras falsedades acerca de este pueblo,
me sentí más estimulado a establecer en el orden debido
lo que sabía del asunto (por el bien de mis compatriotas^
footnote:[William Sewel era oriundo de Holanda y su lengua nativa era el holandés.]),
porque parece ser de poco provecho, que cuando algo es bien conocido por nosotros,
mantengamos ese conocimiento sólo para nosotros y no lo impartamos a otros.

Entonces, por más difícil que la encontré y habiendo ya iniciado, resolví continuar,
y así lo hice, aunque a menudo me detuve por varios acontecimientos y por otros trabajos.
Pues durante esta labor no sólo tuve que traducir varios voluminosos libros al holandés,
además de [.book-title]#Kennet`'s Antiquities of Rome,#^
footnote:[Antigüedades de Roma de Kennet.]
sino también escribir varios tratados de importancia,
entre ellos mi gran diccionario __English and Low Dutch.__^
footnote:[Inglés y Holandés Bajo]
A pesar de todos estos impedimentos,
continuamente reanudaba el trabajo por intervalos tan frecuentes,
que casi la he escrito tres veces para completarla,
pues al tener dudas de algunas cosas y encontrar otras defectuosas,
tuve que escribir a Inglaterra para obtener mejor
información. Y habiéndola recibido finalmente,
después de muchos esfuerzos y largos escritos,
varias veces me vi obligado a dejar de lado parte
de mi descripción anterior y hacer una nueva,
lo cual sucedió tan a menudo, que si no me hubiera apoyado en una incansable aplicación,
la dificultad de la labor (que era mucho mayor en Holanda,
que si la hubiera escrito en Inglaterra) me habría hecho renunciar.
Pero continué, y así terminé esta historia tal como aparece ahora.

Y no estoy libre de sospechas,
de que fui preparado por el Señor para realizar una obra como esta;
pues he hecho uso de varios sucesos extraordinarios,
que había anotado antes de pensar alguna vez en escribir tal historia.
Incluso, cuando estuve en Inglaterra en mis años de juventud,
copié varios fragmentos y cartas de manuscritos que están insertados en esta historia,
y que difícilmente pueden ser hallados en otro lugar.

Recibí de mis conocidos en Inglaterra, narraciones impresas de muchos sucesos notables,
y de muchos fragmentos auténticos en manuscrito.
De esto y a partir de mi propia colección de asuntos conocidos por mí,
he compilado la mayor parte de esta historia.
Pero en cuanto a la vida y memorias de George Fox,
quien es extensamente tratado en esta obra, las tomé principalmente de su diario;
y la mayor parte de otros sucesos, o las vidas y memorias de otros,
las he tomado de obras de autores fallecidos,
y de la abundancia de pequeños libros publicados de forma impresa,
no mucho después de que sucedieran las cosas que no han
sido contradichas por nada que yo pudiera encontrar.

Por tanto, me he esforzado por no afirmar nada,
sino aquello de lo que podía hablar con total confianza, lo cual,
en cuanto a algunas circunstancias,
habría sido aún más difícil después de que hubieran pasado algunos años,
pues al escribir esta obra ahora (y no después),
el tiempo me dio la oportunidad de informarme de muchas
cosas de las que algunos ancianos tenían aún recuerdos,
y que después de su fallecimiento habrían sido enterradas en el olvido.

No puedo dejar de reconocer públicamente,
la extraordinaria amabilidad y diligencia de mi bien amado y muy estimado amigo,
Theodore Eccleston, de Inglaterra, quien me ha suministrado abundancia de materiales,
que no sólo fueron muy útiles,
sino también absolutamente necesarios para la compilación de esta obra.
De él recibí información sobre este relato y he intercambiado multitud de cartas.
Y así, por una larga y continua correspondencia,
llegué a familiarizarme con muchas cosas y circunstancias,
que después de algunos años habría sido más difíciles de obtener.

Agregado a esto, he descrito varias cosas que son bien conocidas por mí,
de las que pocos, además de mí mismo,
durante estos treinta o cuarenta años tenían mejor conocimiento.
He mencionado también varios casos extraordinarios,
que anoté de boca de personas fidedignas que han estado muertas por muchos años,
y que no pensé que publicaría de forma impresa en algún momento.
Mientras tanto, tuve en cuenta lo que parecía digno de ser dejado en el registro,
y reuní una gran cantidad de libros en los que estaban relatados
muchos de los sucesos mencionados en esta historia.
He hecho uso de tales relatos y descripciones,
sin usar todo lo que era verdaderamente extraordinario,
pues no ha sido por falta de material que esta historia no es una obra más larga,
ya que podría haberla hecho tres veces más grande
si hubiera tenido en mente hacerla así. Pero,
así como yo no estaba dispuesto a extender mi trabajo más allá
de lo que mi fuerza y salud con toda probabilidad me permitirían,
tampoco quise sobrecargar a mi lector con muchas cosas de similar naturaleza;
pero me he esforzado por avivar su apetito mediante la variedad de material, y por eso,
a veces he entremezclado la parte seria con una anécdota agradable.

Sin embargo,
no me he sentido obligado a tomar nota de cada caso extraño
de los que han sucedido entre los llamados Cuáqueros,
pues han sido hallados entre ellos algunos que hicieron cosas extrañas,
las cuales no eran aprobadas por los de esta sociedad.
Y si alguno, inclinado por la pasión humana,
comete algún exceso que es desaprobado por sus compañeros miembros de la iglesia,
tal acto no debe ser obligatoriamente imputado a las personas con las
que él hace profesión. Entre tales se reconoce el caso de Hester Biddle,
de quien Croese hace mención cerca del final de su historia.
Pues, aunque esto le fue dicho a él a partir del relato que dio ella en Amsterdam,
sin intención alguna de que él lo publicara,
ese fue un caso extraño del que ella misma debe ser responsable,
ya que la experiencia ha enseñado,
que a veces la imaginación obra tan poderosamente en la mente,
que uno se siente obligado a hacer una cosa que es mejor no hacer.

Aun así, es cierto que los hombres que temen a Dios pueden equivocarse,
y debido a la ignorancia,
hacer algo que otros podrían correctamente juzgar que no es recomendable.
También puede suceder que algunos, por un temor piadoso, hayan omitido lo que otros,
no menos piadosos, no habrían descuidado.
Y aunque algunos entre los Cuáqueros, al principio de su ascenso,
por temor a transgredir el mandamiento de Cristo:
"`Pero vosotros no queráis que os llamen Rabí; porque uno es vuestro Maestro,
el Cristo,`" cuando hablaban con personas en autoridad
las llamaban '`Amigos,`' otros de la misma persuasión,
no se han visto obligados a denegarles a los magistrados su título distintivo de magistratura.
Y si alguno, por alguna razón especial,
no ha dado una respuesta completa o directa a una pregunta, otros de la misma sociedad,
no han considerado esto como un patrón a imitar.
Porque al principio, los valientes más conocidos entre este pueblo,
no eran hombres notables o estudiados, aunque de gran coraje,
de tal manera que a veces su firmeza inamovible exasperaba mucho a sus enemigos,
pues tenían temor de hacer u omitir algo que juzgaban desagradaría a Dios,
lo cual a menudo ha sido etiquetado con el odioso nombre de testarudez y terquedad.
Pero ellos han soportado esto pacientemente,
creyendo que era su deber mantenerse inamoviblemente ocupados de su profesión cristiana,
y frecuentar sus asambleas religiosas.

Es cierto, ha habido algunos entre los Cuáqueros,
que fueron extremadamente audaces en demostrarles
a sus enemigos su proceder y conducta malvadas,
pero esta ha sido una característica peculiar en muchos hombres piadosos,
de quienes existen ejemplos en el [.book-title]#Libro de los Mártires;#^
footnote:[Escrito por John Foxe en 1563.]
es decir, que algunos de ellos les hablaron a sus
perseguidores de su maldad en términos muy claros.

No se puede negar,
que a veces se han encontrado personas entre esta sociedad con un comportamiento extraño,
quienes con el transcurso del tiempo abrazaron opiniones extrañas e ideas perversas.
Pero eso no es cosa nueva,
ya que esto también ha sucedido entre los de otras persuasiones,
aunque ninguno de ellos admitiría que fuera como consecuencia o efecto de su doctrina.
Encontramos en la Sagrada Escritura, que incluso en la iglesia primitiva había apóstatas,
ya fuera porque mantenían una doctrina extraña (como los Nicolaítas^
footnote:[Apocalipsis 2:6, 15]),
o porque dejaban el camino recto al encontrarlo demasiado estrecho para ellos,
y al igual que Demas,^
footnote:[2 Timoteo 4:10]
se enamoraban de nuevo de este mundo y entraban en el camino ancho.
Por tanto, ahora, no más que entonces, puede argumentarse a partir de esto,
que el exceso al que algunos se lanzaron fue efecto de la doctrina que abandonaron.

Dado que en esta historia también se mencionan algunas predicciones, y que algunos,
que están predispuestos por prejuicios, quizás las vean frívolas,
al imaginar que los Cuáqueros pretenden tener el espíritu de profecía,
responderé como sigue: Aunque entre miles de ellos,
puede que haya habido uno que proféticamente predijo algo,
y que después sucedió verdaderamente, aun así,
muchos otros de la sociedad no presumieron tener ese don más que el don de ser predicador,
al no ser llamados a esa obra.
Ahora, aunque algunos han mantenido la falsa opinión,
de que poder predecir cosas futuras era una capacidad
que los Cuáqueros se atribuían a sí mismos,
debido a su doctrina de que los cristianos deben ser guiados por el Espíritu de Dios,
decir eso es una opinión muy siniestra y absurda,
porque lo que ellos dicen con respecto a la dirección y guía del Espíritu de Dios,
concuerda con la doctrina del apóstol que dice:
"`Porque todos los que son guiados por el Espíritu de Dios, éstos son hijos de Dios.`"
Esta también fue la doctrina de los primeros reformadores.
¿Qué debemos pensar entonces, de los que no quieren ser guiados por este Espíritu,
y en su lugar, llaman esta doctrina con el odioso nombre de "`entusiasmo`"^
footnote:[En este tiempo, la palabra __entusiasmo__ hacía referencia
al fanatismo o emocionalismo religioso.]? El mismo apóstol también nos dice:
"`Y si alguno no tiene el Espíritu de Cristo, no es de él.`" Y también dice:
"`Pero a cada uno le es dada la manifestación del Espíritu para provecho.`"
Pero, a partir de esto,
no hay forma de deducir que el espíritu de profecía sea dado a todos, ni tampoco,
que aunque le placiera a Dios revelarle a alguien algo que aún está por venir, el tal,
está dotado con dicho espíritu profético y puede
predecir cosas futuras en cualquier momento.

Ha habido muchos hombres piadosos entre otras persuasiones
cristianas que predijeron cosas notables,
las cuales realmente sucedieron después; tales como (entre muchos otros) James Usher,^
footnote:[Autor de [.book-title]#Annals of the World,#
(Anales del Mundo) y de muchas otras bien conocidas obras protestantes.]
arzobispo de Armagh y primado de Irlanda,
quien predijo la rebelión de Irlanda cuarenta años antes de que sucediera,
junto con la guerra civil, las miserias que ocurrieron en Inglaterra,
y otras cosas que se cumplieron.
Esto nos lleva a no rechazar como frívola, la predicción que él hizo,
de la pavorosa persecución que caería sobre todas las iglesias protestantes,
por parte de los católicos romanos.
Pues, aunque uno de sus amigos en una ocasión se opuso a él,
dado que Gran Bretaña e Irlanda ya habían sufrido profundamente,
y había razones para esperar que los juicios de Dios habían pasado, él,
aun así respondió:

No se engañen con tales esperanzas,
porque les aseguro que todo lo que han visto no ha sido más que el comienzo de dolores,
comparado con lo que todavía está por venir sobre las iglesias protestantes de Cristo,
que pronto caerán bajo una persecución más aguda
que la que alguna vez haya estado sobre ellas.
Por tanto, asegúrense de no ser hallados en el atrio externo,
sino como adoradores en el templo delante del altar,
pues Cristo medirá a todos los que profesan Su nombre y se llaman a sí mismos Su pueblo;
y a los adoradores externos, Él los dejará fuera para ser pisoteados por los gentiles.
El atrio externo es el cristiano formal,
cuya religión radica en la realización de deberes externos del cristianismo,
sin tener una vida interna, ni poder de fe y amor que los una a Cristo.
Pero los adoradores dentro del templo y delante del altar,
son los que realmente adoran a Dios en espíritu y en verdad;
son aquellos cuyas almas son Su templo,
donde Él es honrado y adorado en los más internos pensamientos de sus corazones,
y ellos sacrifican sus deseos y afectos viles, sí,
su propia voluntad a Él. A estos Dios los esconderá
en el hueco de Su mano y bajo la sombra de Sus alas.

Si alguno en la actualidad hablara de esta manera,
es probable que muchos que se creen buenos cristianos,
condenarían esto como mero entusiasmo.
Pero el mencionado obispo, todavía tiene tanta reputación entre los eruditos,
y ha obtenido tanta estima por sus escritos,
que sus palabras son probablemente de más peso entre muchos,
que las de otros hombres piadosos.
Es por esto que yo, estaba dispuesto a citarlas y a revivir su memoria, para quizás,
poder causar alguna impresión sobre la mente de algunos.
Porque esta es una verdad innegable,
que ninguna actuación externa será de utilidad para
los que no adoren a Dios en espíritu y en verdad;
porque Dios busca a tales adoradores,
en concordancia con lo que ha dicho nuestro Salvador.
Además: "`No todo el que me dice: Señor, Señor, entrará en el reino de los cielos.`"
No, y cuando alguno en aquel día le diga a Él: "`Señor,
¿no profetizamos en tu nombre?,`" Él les dirá: "`Nunca os conocí; apartaos de mí,
hacedores de maldad.`"

Como sin ninguna duda,
muchos casos extraordinarios relatados en esta historia les proporcionarán
placentero entretenimiento a los lectores curiosos,
de igual manera los encontrarán instructivos.
Porque no sólo nos encontraremos con ejemplos de verdadera piedad y amor al prójimo,
de santos triunfando en sus propios lechos de muerte,
y con notables ejemplos de pecadores verdaderamente arrepentidos a la hora de la muerte,
sino que también encontraremos una gran cantidad de pruebas de comportamiento pacífico.
Pues los llamados Cuáqueros, nunca han conspirado contra el gobierno,
ni se han entrometido en prácticas de traición o rebeliones,
y por muy oprimidos que estén,
siempre se han mantenido callados y nunca han opuesto resistencia,
sino que con inofensiva paciencia, han soportado la más fuerte opresión y las heridas,
y así, finalmente han vencido.
Porque estar sujetos a la magistratura siempre ha sido uno de sus principios,
y han mostrado en todo momento que eran personas realmente obedientes,
sometiéndose a las autoridades superiores en todo lo que podían hacer con buena consciencia.
Y cuando se les requería algo,
que por un respeto reverencial a Dios no se atrevían a hacer u omitir,
han mostrado su obediencia sufriendo,
sin oponer resistencia ni unirse a otros que se inclinaban a ello.

Muchos se han ocupado de representar a los Cuáqueros con colores odiosos,
y de escribir grandes falsedades con respecto a ellos,
intentando atribuirles doctrinas que ellos nunca aprobaron,
y presentando como justicia farisea su conducta honesta y vida religiosa,
aun cuando Cristo y Sus discípulos fervientemente recomendaron esa vida de piedad.
Porque, ¿qué significan esas palabras de nuestro Salvador: "`Sed, pues,
vosotros perfectos,
como vuestro Padre que está en los cielos es perfecto,`" sino que debemos esforzarnos,
al máximo de nuestro poder, por llevar una vida virtuosa y piadosa?
El apóstol Pablo dice: "`No os conforméis a este siglo,
sino transformaos por medio de la renovación de vuestro entendimiento.`"
Y el apóstol Pedro, de acuerdo con esto dice: "`Como hijos obedientes,
no os conforméis a los deseos que antes teníais estando en vuestra ignorancia; sino,
como aquel que os llamó es santo,
sed también vosotros santos en toda vuestra manera
de vivir,`" todo lo cual claramente implica,
que un cristiano debe ser muy estricto y cuidadoso en su conducta;
de este juicio fueron también los primeros reformadores.
Pero aunque los Cuáqueros se han esforzado por alinear
sus vidas y conductas con su profesión cristiana,
esto todavía ha generado envidia, rencor y malicia contra ellos.
Entre el clero ha habido los que (con la intención de hacerlos odiosos),
no titubearon en presentarlos como papistas^
footnote:[Personas cuya lealtad era hacia el Papa y la Iglesia Católica Romana.]
disfrazados, a pesar de que estos eran algunos de sus más grandes enemigos.

No he relatado nada en esta obra, sino lo que creí que era incuestionablemente cierto,
porque preferí pasar de largo cualquier cosa que me parecía dudosa,
pues nunca he sido de un temperamento tan crédulo,
como para confiar fácilmente en algo sin el debido examen.
Porque es un hecho,
que a menudo vemos que las altas imaginaciones hacen que
las personas crean cosas que están lejos de ser ciertas.
Pero, por otro lado,
tampoco debemos rechazar como falso todo lo que parezca extraño o inusual,
dado que la experiencia nos convence de lo contrario, a saber,
que a veces hemos visto algo, que de no ser porque lo vimos con nuestros propios ojos,
difícilmente lo habríamos creído. Por tanto,
no he rechazado como falso lo extraordinario o inusual,
siendo que me lo contaron personas de credibilidad o lo confirmaron testigos presenciales.
Así, pues, aunque mi lector se encuentre con sucesos muy extraordinarios,
sigue siendo cierto,
que me he esforzado hasta lo último por no relatar nada sino lo
que (después de una cuidadosa investigación) me pareció verdadero,
o al menos muy probable.
Sin embargo, he pasado silenciosamente por alto,
algunos casos que no cuestioné que fueran verdaderos,
para que nadie piense que soy demasiado crédulo.

En cuanto a las transacciones de asuntos estatales, las tomé principalmente
de [.book-title]#The History of the Rebellion and the Civil Wars in England,#^
footnote:[Historia de la Rebelión y de las Guerras Civiles en Inglaterra]
escrita por Edward Earl de Clarendon, y de [.book-title]#Memoirs of Edward Ludlow.#^
footnote:[Memorias de Edward Ludlow]
Sin embargo, me pareció digno de entregar a la posteridad por medio de mi pluma,
algunas pocas cosas relacionadas con asuntos estatales que no mencionan ellos,
ni ninguna otra historia pública que yo conozca.

En cuanto a mi estilo, sé que no es impresionante.
No pretendo ser elegante en la lengua inglesa, pues al ser extranjero,
y nunca haber estado en Inglaterra,
sino por un espacio de diez meses hace aproximadamente cincuenta años,
no debe esperarse que escriba en inglés tan bien como en holandés, mi lengua nativa.
Por tanto, si mi pluma ha sido algunas veces culpable de un belgicismo,^
footnote:[Palabra,
expresión o frase que es exclusiva de los idiomas de las regiones belgas.]
le ruego a mi lector que me disculpe.

Lo que los envidiosos puedan juzgar de esta obra me importa poco,
al saber bien que los más eminentes autores han estado expuestos a la envidia,
y han sido despreciados por las censuras de los críticos pedantes.
Independientemente de lo que piensen, de esto estoy seguro,
de que mi principal objetivo ha sido relatar muchos sucesos inusuales,
no sólo para complacer a mi lector, sino para llevarlo también a la virtud.
Pensaré que mis esfuerzos están bien recompensados,
si tengo el placer de haber contribuido con ello, y si no,
al menos tendré la satisfacción de que según mi capacidad,
me he esforzado por beneficiar a otros y edificar
a mis compañeros mortales en eso que es bueno;
lo cual no puedo sino pensar que agrada a Dios.
Si he realizado algo bueno,
el honor y la gloria de eso le pertenecen Al que es el Dador
de "`toda buena dádiva;`" es únicamente de Él,
que he recibido toda mi habilidad para hacer cualquier cosa buena.
En conclusión, deseo del lector discreción y un juicio imparcial.
