== Capítulo I

Que la maravillosa obra de reforma era pequeña y de muy poca importancia en su inicio,
y que a pesar de eso ha estado avanzado con notable progreso,
creo que no será negado por nadie que haya leído la historia de su primer
levantamiento con atención y debida consideración. Pues Dios,
el iniciador y autor de esta gloriosa obra, actuando paso a paso y gradualmente,
usó en ella una sabiduría y prudencia tan notables,
que (cuando cada circunstancia es debidamente considerada,
en lugar de censurar alguna parte de ella) nos veremos obligados a exclamar:
"`¡Sólo Tú, oh, Señor,
conoces los tiempos y estaciones correctas para abrir los
ojos de las personas y hacerlas aptas de Tu verdad!`"

Si miramos los primeros comienzos y no retrocedemos más allá de John Huss,
encontraremos que aunque en muchas cosas él estaba considerablemente iluminado,
continuaba en varios errores evidentes;
porque si bien es cierto,
tenía una clara visión de las vanas doctrinas del purgatorio, orar a imágenes, adorarlas,
etc., se informa de él que favorecía la invocación a los santos, los siete sacramentos,
escuchar la confesión y otros dogmas de la Iglesia de Roma.
Sin embargo,
la bondad cristiana nos constriñe a creer (aunque encontramos
escritores protestantes que le niegan el apelativo de mártir),
que por su muerte, la cual sufrió en las llamas en Constanza, Alemania,
el 6 del mes llamado Julio, en el año 1415, fue una sacrificio aceptable para Dios.
La mente tranquila y quieta con la que sufrió la muerte puede apreciarse en lo siguiente:
Al ver a un hombre del campo cargando muy celosamente leña para quemarlo,
dijo con un rostro sonriente: "`¡Oh santa sencillez!`"
Y después de que el fuego fue encendido, cantó con gozo en las llamas,
al tener su mente firmemente fija en Dios.
Pues él había sido fiel en la medida de su entendimiento,
y no había enterrado su talento en la tierra, sino que lo había aumentado,
pues demostró ser un celoso promotor de esa pequeña
iluminación que le plació a Dios otorgarle.
Esta pequeña medida de luz fue, sin ninguna duda,
suficientemente grande en esa lamentable noche de tinieblas,
cuando la idolatría había cegado universalmente a la humanidad, a la cual,
moralmente hablando,
le habría sido imposible entender la proclama de una religión completamente reformada.
Pero es evidente que las personas más sobrias y discretas de esa época,
fueron capaces de entender la doctrina y los sermones de este honesto hombre.

Para dar una perspectiva más clara de este asunto, consideremos lo siguiente:
Si un hombre hubiera sido mantenido encerrado por un largo tiempo en una prisión oscura,
en la que no podía ver la luz del sol ni de la luna,
y repentinamente se le hubiera permitido salir a la claridad del mediodía,
él no sólo habría sido incapaz de soportar el brillo de la luz del día,
sino que también (si hubiera tratado de abrir sus ojos a
la fuerza) habría estado en peligro de perder su vista,
y de caer en una condición peor de la que estaba antes.
Sin embargo, si hubiera sido llevado al aire libre en el momento del anochecer,
él poco a poco habría aprendido a distinguir los objetos,
y habría llegado a tener la facultad de ver todo correctamente en un día despejado.

De acuerdo con esto, en los reinados del Rey Enrique VIII y de la sangrienta Reina María,
la prueba principal en Inglaterra era,
si un hombre admitía o no la presencia corporal de Cristo en el sacramento;
el que la negaba, tenía que ser quemado como hereje.
Asimismo, en los Países Bajos, para llevar a un hombre a la hoguera,
era suficiente que confesara que había sido rebautizado.
Así, pues, en aquellos días,
parece que el Señor levantó hombres celosos para testificar principalmente,
contra la idolatría de la hostia y el error del bautismo infantil, para así,
gradualmente derribar la gran estructura de las inventos humanos.

Ahora, por más pequeños que hayan sido los inicios de esta gran obra de reforma,
con el paso del tiempo se fue incrementando,
y a menudo se vieron extraordinarios ejemplos de
las operaciones del poder y Espíritu de Dios.

Encuentro que en el año 1513, un tal John Le Clere, de Meaux, Francia, estando en Metz,
Lorrain, fue colmado de tal celo contra la idolatría,
que hizo pedazos las imágenes de una capilla,
las cuales habrían de ser adoradas al día siguiente de manera muy solemne.
Al ser tomado prisionero por ese hecho y cruelmente torturado hasta la muerte,
estaba tan notablemente fortalecido (incluso para el asombro de los espectadores),
que en el clímax de los tormentos, cuando era desgarrado con pinzas al rojo vivo,
dijo (del Salmo 115): "`Sus ídolos son plata y oro, obra de manos de hombres.`"

No menor fue el celo de un tal Aymond a Vie, encarcelado en Francia por el año 1541,
porque había predicado el evangelio con coraje.
Aunque había sido advertido de que huyera, no lograron persuadirlo,
y dijo con una mentalidad heroica: "`Preferiría nunca haber nacido,
que cometer un acto tan bajo, porque es deber del buen pastor no huir del peligro,
sino permanecer en él, para que no se dispersen las ovejas.`"
Él fue torturado cruelmente para que delatara los nombres de sus compañeros creyentes,
pero ningún tormento, por grande que fuera,
pudo obtener por la fuerza el nombre de ninguno.
Sufrió la muerte valientemente por el testimonio de Jesús,
al sentirse muy poderosamente fortalecido por el Espíritu de Dios,
el cual obraba tan gloriosamente en los mártires de aquellos tiempos,
que los de Merindol, Provenza, dijeron: "`El Espíritu Santo es un maestro infalible,
por cuya inspiración todos los cristianos reciben el conocimiento de la verdad.
Este Espíritu mora en ellos, los regenera en una nueva vida,
mata al viejo hombre en ellos, y hace que vivan para toda buena obra,
consolándolos en las tribulaciones y fortaleciéndolos en las adversidades,`" etc.

De los piadosos profesantes de Meaux, encontré mencionado en el año 1546,
que aunque un gran número de ellos, hombres y mujeres,
fueron hechos prisioneros por unos pocos, nunca opusieron resistencia,
sino que se mostraron inofensivos, sin tristeza por el dolor y cantando con gozo.
Dios obró tan poderosamente en Gabriel Beraudin, quien fue ejecutado en Chambery, Savoy,
en el año de 1550, que después de que el verdugo le cortó la lengua,
habló inteligiblemente a las personas y proclamó alabanzas a Dios de manera milagrosa.

Claude Morier, quien fue quemado muy cruelmente en Lyons, Francia,
escribió mientras estaba en su celda: "`Oremos a nuestro Padre celestial continuamente,
para que Él forme en nosotros un corazón limpio, nos dé un nuevo corazón,
y guíe nuestra voluntad por medio de las direcciones de Su Espíritu.`"

Es muy notable también, que Godfried de Hammelle, un año después de esto,
estando encarcelado en Tournay, en los Países Bajos,
después de que se le dijo que el apóstol en su epístola a los Efesios
había llamado al matrimonio '`sacramento,`' dijo en una carta,
que aunque al principio eso lo había desconcertado,
el Señor no lo había dejado por mucho tiempo en esa dificultad,
sino que por medio de Su Espíritu le había puesto en la mente,
que la palabra ahí no era "`sacramento,`" sino "`misterio.`"
Pues los mártires de aquellos tiempos no titubeaban
en profesar (en concordancia con los cristianos primitivos),
que los hijos de Dios debían ser guiados por Su Espíritu.

Peter Schryver, quemado en Lyons alrededor del año 1552, escribió desde prisión, que él,
tras haber oído la palabra pura de Dios predicada, creyó en ella,
porque el Espíritu de Dios le había dado testimonio (o evidencia)
de ella en su corazón y se la había confirmado,
y que no había podido cuestionarla en lo más mínimo.
También contó en su carta, que una vez, después de que había orado a Dios,
se había sentido tan refrescado por la virtud de Su Espíritu y tan fortalecido,
que aunque se sentaba en un lugar desagradable y oscuro,
aún sentía tal consolación y gozo, que eso había vencido todo dolor y angustia.
"`No,`" dijo, "`el más pequeño consuelo y gozo que siento ahora en mis cadenas,
supera todos los gozos que alguna vez tuve en mi vida,
pues el Espíritu Santo me hace recordar ahora,
las misericordiosas promesas que son hechas a los que sufren por causa de Su nombre.`"
Y cuando le preguntaron cómo sabía que lo que él afirmaba era la palabra pura de Dios,
respondió diciendo, que concordaba con la doctrina de los profetas y apóstoles,
y con la de Jesucristo, y que el Espíritu Santo le había dado evidencia veraz de ella.
En su carta a John Chambon (cuya maravillosa conversión en prisión fue
una notable prueba de la verdad de su dichos) habla muy especialmente,
de la morada del Espíritu de Dios en el hombre,
diciendo que el Padre celestial estaba cerca de él
y que por Su Espíritu habitaba en su corazón.

Que esta también era la doctrina de Juan Calvino,
se muestra en sus cartas a dicho hombre y a sus compañeros de prisión, donde dice:
"`No duden de que la voluntad de Dios, en esas cosas en las que usará sus servicios,
les dará ese poder, por medio del cual la obra iniciada en ustedes será perfeccionada,
para eso que Él ha prometido hacer.
Tenemos muchos ejemplos y casos de esa excelente fe, mediante la cual claramente sabemos,
que Dios nunca les ha fallado en nada a los que han
sido conducidos y guiados por Su Espíritu.
Confíen firmemente, hermanos, que cuando sea necesario,
llegarán a ser tan fuertes y firmes que no desmayarán bajo ninguna carga de tentaciones,
por grandes y pesadas que sean.
La lucha está a la mano, a la que el Espíritu Santo nos exhorta, no sólo a ir,
sino incluso a que corramos con toda prontitud de mente.`"
Muchos otros excelentes testimonios de eminentes
hombres de aquellos tiempos podrían ser mostrados,
y es muy extraordinario también, que Peter Bergier,
estando prisionero en Lyons en el año 1553, y luego sufriendo la muerte,
clamara en medio de las llamas: "`¡Veo los cielos abiertos!`"

Ahora,
que la doctrina de ser enseñados por el Espíritu de Dios
era generalmente aceptada por los mártires de aquellos tiempos,
lo sabemos por muchos de sus escritos.
Denis Peloquin, quemado en el mismo año en Vile Franche, dijo en su confesión,
que era el Espíritu Santo el que daba testimonio en su consciencia,
de que los libros del Antiguo y Nuevo Testamento eran la Sagrada Escritura.
Cuando a Lewis de Marsac,
quien fue ejecutado con fuego en Lyons aproximadamente al mismo tiempo,
se le preguntó cómo sabía que las Sagradas Escrituras eran el evangelio, dijo:
"`Dios me lo ha enseñado por Su Espíritu.`"
Y cuando se le preguntó además, si era su deber obligatorio leer las Sagradas Escrituras,
y quién lo había instruido con respecto a ellas,
respondió que Dios por medio de Su Espíritu lo había efectuado,
y que sin Su gracia e iluminación de Su Espíritu,
no habría podido comprender ni entender algo del evangelio.
Juan Calvino también les escribió a los anteriormente mencionados Peloquin y Marsac:
"`Dios hará que la confesión que hagan conforme a
la medida del Espíritu que Él les ha dado,
produzca un mayor fruto de edificación,
que todas las otras que pudieran ser trasmitidas por ustedes.`"
Y a Matthew Dymonet, encarcelado en Lyons, le escribió:
"`Sométete modestamente a las guías del Espíritu de Dios;
responde con toda moderación y discreción, cumpliendo con la regla de las Escrituras:
'`Creí, por lo cual hablé.`' No dejes que esto te impida hablar libre y sinceramente,
pues estoy persuadido de que Aquel que prometió darnos una
boca y la sabiduría que los adversarios no pueden resistir,
nunca te abandonará.`"

Podría contar más ejemplos similares de las operaciones
del Espíritu de Dios en Sus testigos,
si tuviera esa intención, pero aquí sólo doy un pequeño esbozo,
de la sinceridad y de los principios de aquellos
que sólo llegaron a los inicios de la Reforma.
Tampoco puedo estimar ese tiempo superior que el de los albores del día,
porque los ojos de la mayoría de los hombres celosos de ese entonces,
todavía estaban muy nublados por la bruma que cubría
entonces la iglesia y el prejuicio de la vieja levadura,
pues no discernieron todas las cosas con plena claridad.
Porque uno vio el error de una cosa, y otro de otra,
pero la pasión humana obraba demasiado fuerte, y por tanto,
también se juzgaron unos a otros, como es abundantemente mencionado en la historia.

Si analizamos esto correctamente,
entonces parece muy absurdo pensar que la Reforma fue llevada
a la perfección en aquel momento (aunque en el pasado había
sido en gran medida desarrollada por algunos hombres notables,
como Lutero, Melancthon, Ecolompadio, Calvino, Menno y otros),
porque incluso encontramos que esos reformadores,
al principio no tenían una visión tan clara de muchas
cosas como la tuvieron después. Por tanto,
dado que Inglaterra es el principal escenario,
en el que se implementaron las cosas que intento describir, volveré mi rostro hacia allí,
para tener un panorama general del principio y progreso de la Reforma ahí.

Pasando por Wickliffe y otros, comienzo con Thomas Cranmer,
quien (debido a su vida sincera y buena,
y al ser promovido por el Rey Enrique VIII al puesto de
Arzobispo de Canterbury) hizo todo lo que estaba en su poder,
para reformar los errores que se habían deslizado en la Iglesia de Roma.
Por tanto, en el año 1536, exhortó al Rey, quien lo amaba mucho,
a proceder a una reforma,
diciendo que nada en la religión debía ser determinado sin pruebas claras de las Escrituras,
y luego propuso que se investigaran los siguientes puntos: Si había un purgatorio,
si los santos fallecidos debían ser invocados,
y cómo debían ser consideradas las imágenes;
pues comenzó a parecer que varias cosas eran errores,
por los que algunas personas no mucho antes habían sufrido la muerte.

Un tiempo después, Thomas Cromwel, ministro principal del reino y gran amigo de Cranmer,
publicó algunas demandas en nombre del Rey,
en las que se requería que todos los miembros de la iglesia dejaran de recomendar imágenes,
reliquias o peregrinaciones, y que en su lugar le enseñaran al pueblo el Padre Nuestro,
el Credo y los Diez Mandamientos en inglés. Este fue un
gran paso hacia la traducción de la Biblia al inglés,
la cual al ser promovida también por Cranmer, el año siguiente salió impresa,
y por orden del Rey se le exigió al clero poner Biblias en sus iglesias,
para que todos los que pudieran, leyeran las Sagradas Escrituras en su lengua materna.
Cranmer, no contento con esto, en el año 1539,
obtuvo permiso para que todas las personas pudieran tener una Biblia en sus casas.
No obstante, y a pesar de todo,
él siguió afirmando la presencia corporal de Cristo en la hostia,
hasta el año 1549. En el reinado de Eduardo VI, cuando los tiempos eran más libres,
él fue persuadido por Nicholas Ridley (un celoso reformador y después
mártir bajo la Reina María) a investigar mejor esa doctrina,
y descubrir lo absurdo de ella;
después de lo cual Cranmer no sólo se opuso y suprimió esta superstición,
sino también muchas otras.
Es probable que si se le hubiera dado la oportunidad,
habría reformado aún más. Sin embargo, no se puede dejar de preguntar, cómo,
el que parece haber sido un hombre de un temperamento manso,
pudo dar su voto para quemar a los que él consideraba herejes.
Como en el caso de John Nicholson (alias Lambert),
que en el reinado de Enrique VIII negó la presencia corporal de Cristo en el sacramento;
y bajo el reinado de Eduardo VI,
los casos de Joan Bocher y George Parr.
Bocher, por negar que Cristo había tomado la carne de la virgen María,
y Parr por no creer en la deidad de Cristo.
De esto podemos ver lo que puede realizar un celo
fuerte por la religión. Pero no hay duda,
de que él había llegado a ser de otro entendimiento, cuando en el año 1556,
bajo el sangriento reinado de la Reina María,
también se vio obligado a padecer el mismo destino de ser quemado vivo.

Ahora bien, aunque después de su muerte,
los obispos bajo la Reina Isabel estaban contentos con la reforma hecha por Cranmer,
en el año 1568,
le agradó a Dios levantar a otras personas para que testificaran
públicamente contra muchas de las supersticiones que quedaban.
Y aunque Coleman, Burton, Hallingham y Benson fueron encarcelados por orden de la Reina,
ganaron muchos seguidores y adquirieron el nombre de Puritanos.
A fin de evitar esto,
el Arzobispo redactó algunos artículos de fe para que fueran firmados por los clérigos,
pero se topó con gran oposición en dicha empresa.
Pues Robert Brown,
un joven estudiante de Cambridge (de quien luego se tomó prestado el nombre Brownistas),
y Richard Harrison, un maestro, publicaron algunos libros en el año 1583,
en los que mostraban cuán contaminada seguía la Iglesia
de Inglaterra con los errores católicos.
Esto tuvo tal efecto, que los ojos de muchas personas fueron abiertos,
las cuales mantuvieron tan valientemente esa doctrina que creían que era verdad,
que algunas de las más celosas entre ellas (a saber, Henry Barrow,
John Greenwood y John Penry, alrededor del año 1593),
fueron ejecutadas debido a su testimonio.
Se cree que esto fue hecho más por instigación del clero, que por el deseo de la Reina,
pues un tiempo después ella le preguntó al Dr. Reynolds, su opinión de esos hombres,
especialmente de Barrow y Greenwood, a lo cual respondió:
"`No servirá de nada que muestre mi juicio con respecto a ellos,
siendo que ya fueran ejecutados.`"
Pero luego de que la Reina lo presionara aún más, dijo:
"`Estoy convencido de que si ellos hubieran vivido,
habrían sido dos de los instrumentos más valiosos para la
Iglesia de Dios que se levantaron en esta época.`"
Ante lo cual la Reina suspiró y no dijo más. Pero después,
cuando cabalgaba por el lugar donde habían sido ejecutados y recordó su muerte,
le preguntó al Conde de Cumberland, que había estado presente cuando sufrieron,
qué tipo de final habían tenido.
Él respondió: "`Un final muy piadoso; ellos oraron por su Majestad y por el Estado.`"
Además, un tal Philips, famoso predicador,
que había visto la preparación de Barrow para la muerte, dijo: "`Barrow, Barrow,
que mi alma esté con la tuya.`"

Después de la muerte de la Reina Isabel, cuando Jacobo I había ascendido al trono,
los seguidores de esos hombres sufrieron mucho por
haberse separado de la Iglesia de Inglaterra.
Pero es muy notable,
que incluso los de esa persuasión (muchos de los cuales en el reinado del Rey Carlos I,
se fueron a Nueva Inglaterra para evitar la persecución de los obispos),
luego se convirtieran en crueles perseguidores de personas piadosas,
mediante flagelación inhumana, etc., y eventualmente,
ejecutaran a algunos en manos de verdugos.
Esto es, en realidad,
una prueba clara de que aquellos en quienes permanecía tal amargura
(aunque no siempre había producido los mismos frutos abominables),
no habían llegado aún a una reforma perfecta,
porque aunque el vástago de las tradiciones e instituciones
humanas había sido sacudido fuertemente en algunas ocasiones,
aún quedaba gran parte de la vieja raíz. Por tanto, le agradó a Dios,
quien generalmente ilumina a los hombres poco a poco,
hacer aún más claro el descubrimiento de Su verdad,
la que en algunos lugares ya había enviado sus rayos a la humanidad,
en un tiempo cuando muchas personas piadosas estaban buscando celosamente,
una mayor manifestación de la voluntad de Dios.
Estos eran conscientes,
de que a pesar de todo lo que externamente guardaban de la práctica religiosa,
todavía había una pared divisoria por la que el alma
estaba impedida a vivir en perfecta paz con su Creador.

Por aquel tiempo había en Inglaterra muchas sociedades cristianas separadas,
y entre el resto estaban los que eran llamados Buscadores,
quienes al principio parecían ser un pueblo prometedor,
pero su fin mostró que el fundamento sobre el que estaban no era la Roca de las Edades,
porque muchos de ellos pronto perdieron su integridad original.
Fue así,
como las personas que empezaron a prestarle atención a la convicción divina en la consciencia,
y en consecuencia,
les predicaron a otros la doctrina de la luz interior
con la que Cristo había iluminado a todos los hombres,
comenzaron a incrementarse en número (al final del reinado de Carlos I),
y se convirtieron en una sociedad separada entre los hombres, y con el paso del tiempo,
se les impuso de manera despectiva el nombre Cuáqueros.
Y al descubrir que en la mayoría de los países de Europa
han sido acusados de muchos y exagerados disparates,
tanto en lo que se refiere a la vida como a la doctrina,
he planeado describir imparcialmente, y de acuerdo con la verdad, los primeros inicios,
el levantamiento, y también el progreso de este pueblo,
y extender el relato de su incremento y tratos,
hasta donde mi tiempo de vida y libertad me lo permitan.

Entro en una obra, la cual, al consistir en muchos sucesos extraordinarios,
en su inicio parece dura y difícil, y en el proceso, a menudo triste y terrible.
Porque entre múltiples adversidades, no sólo nos toparemos con injurias amargas,
burlas despectivas, abusos groseros y golpes sangrientos de la chusma tonta,
sino también con severas persecuciones, duros encarcelamientos, penosos destierros,
inmisericordes despojos de bienes, crueles flagelaciones, amputaciones de orejas,
asfixias en cárceles, y ejecuciones en manos de verdugos por orden de los magistrados.
Y después de un tiempo de calma y descanso, severa persecución otra vez,
hasta que los furiosos promotores de dicha persecución finalmente se cansaban
y desistían de su dañina labor por un tiempo--más por no saber qué hacer,
que por misericordia.
Entre todos estos vaivenes, se han visto casos notables de genuina piedad, amor sincero,
veracidad de corazón, extraordinaria mansedumbre, singular paciencia, ardiente celo,
inquebrantable valor, inconmovible firmeza, incluso entre el sexo femenino,
que aunque el más frágil,
aún en los ataques más duros mostró un espíritu más que varonil, a tal punto,
que pocas edades han ofrecido ejemplos de virtud más poderosos para ser vistos.

Encuentro, que el primero en ser directamente alcanzado en su mente de esta manera,
fue un joven llamado George Fox, nacido en Drayton, Leicestershire,
en el mes llamado Julio, del año 1624,
de padres que eran miembros de la iglesia pública o Iglesia de Inglaterra (según
lo que me parece a partir de un documento redactado por orden de él,
durante su vida, a solicitud mía y que me fue enviado).
Su padre era Christopher Fox, tejedor de oficio,
un hombre honesto y de una vida tan virtuosa,
que sus vecinos solían llamarlo Christer el justo.
Su madre era María Lago, una mujer recta y del linaje de los mártires.
Este George Fox, incluso desde su infancia,
estaba dotado de una gravedad y sobriedad de mente que raramente se ve en niños;
y la aversión que le producía ver que las personas mayores
se conducían superficial y descuidadamente era tal,
que se decía a sí mismo en el interior: "`Si alguna vez llego a ser un hombre,
de seguro no seré así de descuidado.`"
Mientras tanto, sus padres se esforzaban por formarlo,
como lo hacían con sus otros niños, en la forma común de adoración,
contribuyendo en esto especialmente su madre, quien era notable por su piedad.

Sin embargo,
desde niño se veía que él era de un estado mental diferente al de sus hermanos;
era más religioso, retirado, quieto y firme, y además, observador más allá de su edad,
como se desprende de las respuestas que daba y de
las preguntas que hacía con respecto a asuntos religiosos,
para asombro de los que lo oían. Al ver su madre
este extraordinario temperamento y piedad,
que brillaban a través de él desde tan temprano,
y que ni siquiera se involucraba en juegos infantiles,
no creyó necesario molestarlo con respecto a una forma de adoración en particular,
sino que se condujo indulgente con él. Mientras tanto,
él aprendió a leer bastante bien y a escribir lo suficiente,
como para que después le sirviera para dar a conocer lo que quería decirles a otros.
Cuando tenía once años, se esforzaba por vivir una vida pura y justa,
y ser fiel en todas las cosas, tanto internamente para Dios,
como externamente para el hombre;
porque el Señor mediante Su buen Espíritu le había
mostrado que él debía guardar Su palabra siempre,
y que no debía cometer excesos al comer o beber.
Y así, conforme seguía creciendo en virtud,
algunos de sus parientes querían que se formara en
las escuelas para que se hiciera sacerdote,
pero otros sugerían lo contrario, y entonces,
fue colocado como aprendiz de un zapatero que también negociaba con lana y ganado.
En el empleo de su maestro experimentaba mucho deleite con las ovejas,
y era muy hábil en lo que concierne a ellas,
ya que era un empleo que se adaptaba muy bien a su mente, por tanto,
ser pastor era (como un renombrado autor dice),
"`un justo símbolo de su posterior ministerio y servicio.`"
Se desempeñaba tan diligentemente en su ocupación y la cuidaba tan bien,
que su maestro tuvo éxito en su negocio mientras George estuvo con él.
George a menudo usaba en sus tratos la expresión "`en verdad,`" y luego
se mantenía tan estrictamente apegado a ella,
que las personas que lo conocían decían: "`Si George dice,
'`en verdad,`' no hay forma de alterarlo.`"

Ahora bien, aunque mi plan no es hacer una descripción de los asuntos de estado,
encuentro necesario mencionar algo de los principales
acontecimientos históricos en Inglaterra,
tanto como estos tengan relación con los asuntos de la iglesia,
para que mi historia no parezca una obra incompleta.
Por tanto, diré brevemente,
que por esta época aparecieron los inicios de una guerra civil en Inglaterra,
en la que la religión tuvo algo de participación,
pues los obispos empezaron a introducir varias novedades,
al hacer que se construyeran barandillas alrededor de la mesa de
la comunión (lo que entonces era llamado el altar mayor),
y exigir que quienes se acercaran a ella se inclinaran tres veces,
y que en cada inclinación se pronunciara el nombre de Jesús.
Tales ceremonias aumentaron con el paso del tiempo,
y los predicadores que eran verdaderamente religiosos
y hablaban principalmente para edificar,
fueron despreciados y puestos de lado,
porque los obispos buscaban promover especialmente tales ritos,
dado que favorecían el papado^
footnote:[A lo largo de esta historia, __papado__ se refiere a las doctrinas,
prácticas y ceremonias asociadas con el Papa o sistema papal; es decir,
con el catolicismo romano.]. Esto no sólo fue hecho en Inglaterra,
pues en Escocia también se hicieron esfuerzos para introducir el episcopado^
footnote:[El episcopado se refiere al gobierno de la iglesia por una jerarquía
de obispos nombrados por el estado.]. Esto provocó un gran revuelo entre la gente,
el cual finalmente desembocó en una insurrección que, en general,
se creía que era por el bien de la religión, e hizo que algunos gritaran en las calles:
"`¡A tus tiendas, oh, Israel!`"
Debido a que el Parlamento era de la opinión de que el Rey Carlos
I estaba usurpando sus privilegios (lo que ellos no iban a permitir),
el príncipe, exasperado,
reunió un ejército y plantó su estandarte en el castillo de Nottingham,
donde fue derribado la misma tarde del 25 del mes llamado Agosto de 1642.
Pero antes de eso, el Rey había tomado posesión de algunos lugares fortificados,
y el Parlamento por otro lado, también había logrado obtener territorio en su poder.
Un tiempo después,
se peleó una batalla entre los de la monarquía y los del Parlamento cerca de Edge Hill,
en Warwickshire, en la que ninguna de las partes prevaleció significativamente.

Por ese tiempo, George Fox, se esforzaba más y más por llevar una vida piadosa,
habiendo llegado a los diecinueve años, y sucedió que en una feria, un primo suyo y otro,
vinieron a él y le preguntaron si quería tomarse una jarra de cerveza^
footnote:[En aquellos días, la mayoría de la gente, incluso los niños,
bebía un tipo de cerveza de bajo contenido de alcohol (llamada "`small beer`"),
porque se consideraba que el agua no estaba limpia.]
con ellos.
Puesto que tenía sed, dijo que sí, y fue con ellos a una posada,
pero después de que cada uno se había servido un vaso y se lo había tomado,
empezaron a brindar^
footnote:[Tomar a la salud u honor de otro.]
y decían: "`El que no brinde debe pagar la cuenta.`"
Esto entristeció mucho a George,
al ver que personas que profesaban ser religiosas se comportaran de esa manera,
y levantándose para irse, metió la mano en su bolsillo,
tomó una moneda de plata que valía cuatro peniques, y la puso sobre la mesa diciendo:
"`Si va a ser así, yo los dejo,`" y se fue.
Cuando terminó su negocio regresó a su casa, pero esa noche no fue a la cama,
sino que oró y clamó fervientemente al Señor,
y le pareció que sus súplicas eran respondidas por el Señor de la siguiente manera:
"`Tú ves cómo los jóvenes van tras la vanidad, y los mayores tras lo terrenal, por tanto,
debes abandonar a todos, tanto a jóvenes como a mayores, y ser un extraño para ellos.`"
Esto, que él tomó como una amonestación divina,
causó una impresión tan poderosa en su mente,
que resolvió romper toda comunión con la familia y toda conversación con jóvenes y mayores,
e incluso, decidió dejar a sus parientes y vivir una vida separada y retirada.

El 9 de Setiembre del año 1643, partió para Lutterworth, donde estuvo algún tiempo;
de ahí se fue para Northampton, donde también se quedó un tiempo;
luego pasó a Newport-Pagnel, en Buckinghamshire, y después de quedarse por un tiempo ahí,
se fue para Barnet, donde llegó el mes llamado Junio del año 1644.

Mientras tanto, él llevaba una vida solitaria,
ayunaba a menudo y leía las Sagradas Escrituras diligentemente,
de modo que algunos profesantes^
footnote:[A lo largo de esta historia,
la palabra __profesantes__ se refiere a los que profesan fe en Cristo.]
se fijaron en él y buscaron conocerlo.
Pero él, al percibir pronto que ellos no poseían lo que profesaban,
tuvo miedo de ellos y rehuyó su compañía. En ese tiempo cayó en una gran tentación,
casi hasta la desesperación, y estaba en gran angustia;
a veces se quedaba en su aposento,
y a menudo caminaba solo esperando en el Señor. En
ese estado vio cómo había sido tentado Cristo.
Cuando veía su propia condición se preguntaba: "`¿He estado alguna vez así antes?`"
Entonces, empezó a pensar si había hecho mal con sus parientes,
debido a que los había abandonado,
y recordaba su tiempo pasado examinando si había perjudicado a alguien.
Y así, crecieron más y más las tentaciones,
y como Satanás no pudo ejecutar su plan sobre él de esa manera,
le tendió trampas para arrastrarlo a cometer algún pecado,
por medio del cual llevarlo a la desesperación. En
ese entonces tenía alrededor de veinte años,
y continuó por largo tiempo en esa condición, de la que ansiosamente quería ser libre,
lo que hizo que acudiera a muchos sacerdotes en busca de consuelo,
pero no lo encontró en ellos.

En ese miserable estado se fue a Londres,
con la esperanza de encontrar algún alivio entre los grandes profesantes de la ciudad,
pero al llegar ahí, vio que estaban muy oscurecidos en sus entendimientos.
Él, por ese entonces, tenía un tío en Londres, un tal Pickering, bautista,
y aunque los de esa persuasión eran tiernos en ese momento,
no pudo decidirse a darles a conocer su pensamiento, ni unirse a ellos,
porque vio donde estaban todos; jóvenes y viejos.
Y aunque algunos de los principales querían que se quedara, él tenía miedo,
y por tanto regresó a su hogar,
pues habiendo entendido que sus padres y parientes estaban preocupados por su ausencia,
prefirió volver adonde ellos para no entristecerlos.
Después de haber llegado a Leicestershire, sus parientes querían que se casara,
pero él prudentemente les dijo que no era más que un muchacho y que debía adquirir sabiduría.
Otros deseaban que se uniera a las tropas auxiliares de las fuerzas del Parlamento,
el cual, para entonces, había entrado en guerra civil contra el Rey,
y con sus destacamentos había derrotado el ejército
del Rey bajo el Príncipe Rupert ese año,
y había conquistado la ciudad de York.
Pero que George se enlistara como
soldado estaba tan en contra de su mente,
que lo rechazó y se fue a Coventry,
donde tomó una habitación en la casa de un profesante y se quedó ahí por un tiempo,
pues en ese pueblo había muchas personas que se esforzaban por vivir religiosamente.
Después de un tiempo volvió a su propio condado y se quedó ahí alrededor de un año,
bajo grandes penas y tribulaciones, y saliendo a caminar solo muchas noches.

Natanael Stevens, el sacerdote de Drayton (el pueblo natal de George),
a menudo iba adonde él, y George adonde el sacerdote.
Cuando Stevens lo visitaba, algunas veces llevaba con él a otro sacerdote,
y entonces George les hacía preguntas y razonaba con ellos.
Una vez Stevens le preguntó por qué Cristo había clamado en la cruz: "`Dios mío,
Dios mío, ¿por qué me has desamparado?`"
Y por qué había dicho: "`Si es posible, pase de mí esta copa; pero no sea como yo quiero,
sino como tú.`" A esto George respondió así:
"`Los pecados de toda la humanidad estaban sobre Cristo en ese momento,
las iniquidades y transgresiones de todos los hombres con las que era herido,
lo cual Él debía llevar y ser una ofrenda por ellos, como hombre;
pero no murió como Dios.
Y así, al morir por todos los hombres y probar la muerte por cada hombre,
fue una ofrenda por los pecados de todo el mundo.`"
Cuando George Fox dijo esto,
estaba en alguna medida consciente de los sufrimientos
de Cristo y de lo que Él había atravesado.
Su respuesta complació tanto al sacerdote,
que dijo que esa había sido una respuesta muy buena y completa,
y una que no había escuchado antes.
También elogiaba y le hablaba muy bien a otros de George Fox;
y de lo que George decía en conversaciones privadas con él,
Stevens predicaba los Primeros-días de la semana, por lo que no le caía bien a George.

Después de un tiempo, fue adonde un anciano sacerdote en Mansetter, Warwickshire,
y razonó con él sobre la causa de la desesperación y las tentaciones,
pero dado que el anciano ignoraba por completo la condición de George,
lo invitó a fumar tabaco y a cantar salmos.
Pero George le dijo que no era amante del tabaco, y que en cuanto a los salmos,
no estaba en condiciones de cantar.
Luego, el sacerdote lo invitó a regresar y que entonces le contaría muchas cosas.
Pero cuando George regresó el sacerdote estaba enojado y malhumorado,
porque le habían disgustado las palabras anteriores de George.
Y fue tan indiscreto,
que les había repetido a sus sirvientes lo que George
le había contado de sus penas y aflicciones,
de modo que llegó a saberse hasta entre las que ordeñaban;
y se afligió George por haberle abierto su mente a tal hombre,
diciéndose que todos eran unos miserables consoladores.
Luego oyó hablar de un sacerdote que vivía cerca de Tamworth,
quien era considerado un hombre de experiencia, por lo que fue adonde él,
pero encontró que era como un barril vacío y hueco.

Después de oír hablar de un tal Dr. Cradock de Coventry, fue adonde él también,
y le preguntó que de dónde surgían las tentaciones y la desesperación,
y cómo se formaban las tribulaciones en el hombre.
El sacerdote, en lugar de responder,
le preguntó quiénes eran el padre y la madre de Cristo.
George le dijo: "`María era Su madre y se suponía que era hijo de José,
pero Él era el Hijo de Dios.`"
Mientras caminaban juntos en el jardín del Dr. Cradock, sucedió que George volviéndose,
puso un pie al costado de un '`lecho de flores,`' lo que molestó tanto a este
maestro que se enfureció como si su casa estuviera ardiendo en llamas.
En consecuencia, toda su conversación se perdió y George se fue triste,
peor que como había llegado,
al no encontrar a nadie que pudiera alcanzar su condición.
Después de esto se fue a ver a un tal Macham,
un sacerdote de gran estima, pero este no era más hábil que los otros,
y quería darle medicina a George y sangrarlo^
footnote:[En ese tiempo, hacer una __sangría__ era una práctica común entre los médicos,
y se creía que prevenía y curaba toda clase de enfermedades y dolencias.],
pero no pudieron sacarle una gota de sangre, ni de los brazos, ni de la cabeza;
su cuerpo parecía estar seco por las penas, el dolor y la tribulación. En ese tiempo,
las aflicciones sobre él eran tan verdaderamente grandes,
que hubiera deseado no haber nacido,
para no haber contemplado la vanidad y la maldad de los hombres; o haber nacido ciego,
para nunca haberlas visto; o sordo, para nunca haber oído palabras vanas y malignas,
o el nombre del Señor blasfemado.
Y cuando llegaba el tiempo llamado Navidad, mientras otros festejaban y se divertían,
él iba de casa en casa buscando viudas pobres y les daba dinero.
Y cuando era invitado a un matrimonio (como sucedió en algunas ocasiones),
no iba a ninguno, pero al día siguiente, o poco después, visitaba a los recién casados,
y si eran pobres, les daba algo de dinero.
Pues él tenía suficiente, tanto para evitar ser carga para otros,
como para ayudar con algo a los necesitados.

Mientras que la mente de George Fox estaba así de atribulada,
el estado de Inglaterra también estaba atravesando una gran agitación,
pues el Parlamento estaba a favor de la eliminación de todos
los obispos y de la introducción del Directorio Presbiteriano;
lo cual, no se había podido realizar aún. Sin embargo, William Laud,
Arzobispo de Canterbury, había sido obligado a hincarse ante el bloque^
footnote:[Es decir, arrodillarse ante el bloque de madera para ser decapitado.],
y el poder del Rey por ese tiempo estaba muy debilitado.
Ese verano cerca de Naseby, no muy lejos de Leicester,
el ejército del Rey fue vencido por un ejército de tropas sin entrenamiento,
cerca de seis mil hombres fueron tomados prisioneros
(entre los cuales había muchos altos oficiales),
y su gabinete, y fue incautada una gran cantidad de cartas de mucha importancia.

Pero, dado que una descripción circunstancial de estos
asuntos de estado no está dentro de mi plan,
volveré a George Fox, quien al principio del año 1646,
cuando iba hacia Coventry y entraba por la puerta, un pensamiento se levantó en él,
acerca de la creencia que decía que todos los cristianos eran creyentes,
tanto protestantes como católicos.
Y le fue revelado que los verdaderos creyentes eran los
que habían nacido de Dios y habían pasado de muerte a vida,
y que nadie es correctamente llamado creyente salvo estos,
aunque muchos otros dijeran que eran creyentes.
En otro momento, mientras caminaba en un campo la mañana del Primer-día,
le fue dado a conocer en su entendimiento,
que ser educado en Oxford o Cambridge no era suficiente
para que un hombre fuera constituido ministro de Cristo.
Él se maravilló ante esto, porque esa era una creencia común de la gente,
pero él tomó esto como una revelación divina y se admiró de la bondad del Señor,
al creer entonces que los ministros ordinarios no eran como ellos pretendían ser.
Esto lo indispuso a seguir yendo a la "`iglesia,`" como se decía,
a oír al sacerdote Stevens, creyendo que él realmente no se beneficiaría de ese modo.
Y por tanto, en lugar de ir ahí,
se iba solo a los huertos o a los campos con su Biblia
(la que estimaba por encima de todos los libros),
buscando así ser edificado en soledad.
Sus parientes estaban muy angustiados por esto, pero él les preguntó:
"`¿No les dijo el apóstol Juan a los creyentes,
que ellos no necesitaban que ningún hombre les enseñara,
porque la unción les enseñaba todas las cosas?,`"
y aunque ellos sabían que eso era de las Escrituras,
y que era cierto, aun así se dolían porque él no iba a oír al sacerdote con ellos,
sino que se separaba de la forma de adoración de ellos.
Pues él ya veía que un verdadero creyente era algo diferente de lo que ellos consideraban,
y que ser educado en las universidades no calificaba
a un hombre para ser ministro de Cristo.
Por tanto, vivía solo, sin unirse a nadie, ni siquiera a los disidentes^
footnote:[Los disidentes eran personas cristianas, que por diversas razones,
no estaban de acuerdo con la religión del estado ni se conformaban a ella.],
sino que se había convertido en un extraño para todos,
confiando completamente en el Señor Jesucristo.

Un tiempo después le fue revelado,
que el Dios que hizo el mundo no habitaba en templos hechos por manos.
Y aunque al principio esto le pareció extraño,
debido a que tanto los sacerdotes como la gente solían
llamar a sus iglesias '`lugares pavorosos,
tierra santa y templos de Dios,`' aun así le fue directamente mostrado,
que el Señor no habitaba en esos templos que el hombre había erigido,
sino en los corazones de las personas,
y que Su pueblo era el templo en el que Él habitaba.
Esto le fue manifestado cuando caminaba en los campos hacia la casa de uno de sus parientes.
Cuando llegó,
le dijeron que el sacerdote Natanael Stevens había estado
ahí y que había dicho que tenía temor por Fox,
porque estaba yendo tras nuevas luces.
Eso lo hizo sonreír,
porque en ese entonces entendía el verdadero estado de los sacerdotes.
Pero no dijo nada de esto a sus parientes, quienes,
aunque veían que algo más que la forma común de adoración era requerido,
ellos continuaban ahí,
y se sentían afligidos porque él no iba también a oír a los sacerdotes.
Sin embargo, él les decía que había una unción en el hombre para enseñarle,
y que el Señor mismo le enseñaba a Su pueblo.
Para ese entonces él tenía grandes revelaciones con
respecto a las cosas escritas en el libro de Apocalipsis,
y cuando hablaba de ellas,
los sacerdotes y profesantes decían que ese era un libro sellado.
Pero a esto él respondía que Cristo podía abrir los sellos,
y que las cosas contenidas en ese libro tenían mucho que ver con nosotros,
ya que las cartas de los Apóstoles habían sido escritas a los santos de aquellos tiempos,
pero que el libro de Apocalipsis hablaba de cosas por venir.

En aquellos días, había personas con ideas muy extrañas en Inglaterra y en otras partes,
que sostenían que las mujeres no tenían alma.
Cuando se encontraba con algunas de ellas, él no podía evitar reprenderlas,
ya que las Escrituras (como les decía claramente) afirmaban lo contrario,
pues la bendita virgen María había dicho: "`Engrandece mi alma al Señor;
y mi espíritu se regocija en Dios mi Salvador.`"
También se encontró con unas personas que confiaban mucho en los sueños,
y él les dijo que a menos que pudieran distinguir entre sueño y sueño,
sus observaciones no serían más que confusión, ya que había tres tipos de sueños;
los sueños que a veces eran causados por la multitud de asuntos,
los que durante la noche eran susurrados por Satanás,
y los que Dios le hablaba al hombre.
Ahora bien,
debido a que esas personas tenían más necesidad de
un claro discernimiento que de buena voluntad,
eventualmente salieron de esas imaginaciones,
y al final se convirtieron en compañeros creyentes de la Verdad con él. Sin embargo,
a pesar de que él tenía grandes revelaciones en su entendimiento,
con frecuencia venían sobre él grandes aflicciones y tentaciones,
de modo que cuando era de día, deseaba que fuera de noche, y cuando era de noche,
deseaba que fuera de día. No obstante,
su entendimiento estaba tan abierto en medio de todas esas tribulaciones,
que podía decir con David: "`Un día emite palabra a otro día,
y una noche a otra noche declara sabiduría,`" pues incluso durante las
tribulaciones tenía grandes revelaciones de muchos lugares en las Escrituras.

En cuanto a los asuntos de estado, las cosas continuaban en agitación, pues el Rey,
después de que su ejército fue vencido, había huido a los escoceses,
y ellos lo habían entregado de vuelta a los ingleses,
a quienes él ya no podía dictarles leyes, pero estaba dispuesto a recibirlas.
Los eclesiásticos también estaban en desacuerdo,
pues los Independientes (varios de los cuales también se sentaban en el Parlamento),
empezaron a decir que la diferencia entre el episcopado (contra
el que habían peleado de manera conjunta) y el presbiterado,
sólo era de nombre y de unas pocas circunstancias externas;
al ver que las personas de consciencia tierna podían esperar ser menos
oprimidas por los presbiterianos de lo que habían sido por los episcopales.
Este temor no era vano ni infundado,
pues el tiempo que siguió lo ha demostrado abundantemente.

Pero regresemos a George Fox,
quien al principio del año 1647 se sintió movido a ir a Derbyshire,
y al llegar encontró a algunas personas amables con las que tuvo muchas conversaciones.
Luego, pasando más allá del condado Peak, encontró más personas amables,
y también a otras que habían sido influenciadas por ideas vacías y altaneras.
Viajando a Nottinghamshire, se encontró con personas tiernas,
y entre ellas estaba una tal Elizabeth Hooton, de quien se hablará más en su momento.
Tuvo algunas reuniones y conversaciones con estas personas,
pero sus tribulaciones y tentaciones continuaban.
Él ayunaba mucho,
y a menudo salía a caminar por lugares solitarios llevando su Biblia con él,
y se sentaba en árboles huecos y lugares solitarios hasta que llegaba la noche.
Frecuentemente caminaba en la noche lleno de tristeza,
rodeado de muchas penas en el tiempo de estas primeras obras del Señor en él.

Durante todo ese tiempo, nunca se unió a alguien en profesión religiosa,
sino que se entregó a la disposición del Señor,
tras haber abandonado no sólo toda mala compañía, sino también a su padre,
a su madre y a todos los otros parientes.
Por tanto, viajaba arriba y abajo como un extraño en la tierra,
en cualquier dirección que se inclinara su corazón.
Cuando llegaba a un pueblo tomaba una habitación,
y a veces se quedaba un mes (unas veces más, otras veces menos),
porque le daba miedo quedarse mucho tiempo en un solo lugar, pues al ser un joven tierno,
quería evitar ser lastimado por una interacción demasiado familiar con ellos.

Ahora bien, aunque pueda parecer que no es conveniente para la seriedad de mi obra,
que mencione el tipo de ropas que usaba él en estos primeros años de su peregrinación,
no estimo absurdo comentar aquí,
que es verdad lo que cierto autor llamado Gerard Croes dice de George,
que él se vestía de cuero.
Pero esto no era (como añade el mencionado autor), porque él no pudiera,
o no quisiera olvidar su antiguo trabajo con cuero, sino, en parte,
por la sencillez de esa vestimenta,
y porque ese tipo de ropa era fuerte y necesitaba poco arreglo o reparación,
lo cual era conveniente para el que no tenía un lugar de residencia estable,
y en todas partes buscaba vivir en estado solitario.
Pues al mantenerse como un extraño, buscaba la sabiduría celestial,
y se esforzaba por obtener conocimiento del Señor,
por ser destetado de las cosas externas, y confiar entera y únicamente en el Señor.

Aunque sus angustias eran grandes, no eran tan continuas,
sino que tenía algunos descansos, y a veces era llevado a tal gozo celestial,
que al admirar el amor de Dios en su alma decía con el salmista: "`¡Tú, Señor,
conviertes un campo fructífero en árido desierto,
y un árido desierto en campo fructífero!`"
En ese momento tenía poca estima por los sacerdotes,
porque claramente entendía que ser entrenado en las universidades,
e instruido en idiomas, artes liberales y ciencias similares,
no era suficiente para que una persona se convirtiera en ministro del evangelio.
Por un tiempo miró más hacia los disidentes; sin embargo,
tal como había abandonado a los sacerdotes, dejó también a los predicadores separados,
porque veía que entre todos ellos no había nadie que pudiera
darle una palabra adecuada a su condición. Y entonces,
cuando todas sus esperanzas en ellos y en todos los hombres se habían ido,
oyó (según lo que él mismo relata) una voz que decía: "`¡Hay uno, es decir, Jesucristo,
que puede darte una palabra adecuada a tu condición!`"
Cuando oyó esto su corazón saltó de alegría,
y le fue mostrada la razón por la que no había nadie
en la tierra que pudiera ayudarlo en su condición,
a saber, para que él le diera toda la gloria al Señor exclusivamente,
y para que solo Jesucristo tuviera la preeminencia.

Luego, sabiendo por experiencia que Cristo ilumina al hombre y le da gracia, fe y poder,
sus deseos en pos del Señor y su celo por el conocimiento
puro de Dios se hicieron más fuertes,
de modo que deseaba crecer en ello sin la ayuda de ningún hombre, libro o escrito.
Y aunque él era un diligente lector de las Sagradas Escrituras,
las cuales hablan mucho de Dios y de Cristo, él sólo Lo conocía por revelación,
en la medida que Aquel que tenía la llave se revelaba.
Por tanto, no entró en comunión con ninguna sociedad de personas,
pues sólo veía corrupción por todo lado,
lo cual hizo que se esforzara por mantener comunión sólo con Cristo.
Cuando estaba en las más grandes tentaciones, casi al borde de la desesperación,
se le mostró que Cristo había sido tentado por el mismo diablo,
pero que Él lo había vencido y lo había herido en la cabeza, y por tanto,
que a través del poder, luz, gracia y Espíritu de Dios,
él podría vencer también. Así lo asistió el Señor en las más profundas miserias y penas,
y halló que Su gracia era suficiente, de manera que,
aunque todavía tenía algunos deseos de ir tras la ayuda de los hombres,
su sed era principalmente ir en pos del Señor, el Creador de todo,
y de Su Hijo Jesucristo,
porque nada podía darle algún consuelo excepto el Señor mediante Su poder.
Él claramente vio que el mundo entero no habría sido de provecho para él,
aunque hubiera poseído la herencia de un rey.

En esta condición su entendimiento le fue más y más abierto,
de modo que vio cómo había pasado la muerte a todos los hombres en Adán,
y cómo por medio de Cristo, quien gustó la muerte por todos los hombres,
podían ser obtenidas una liberación de dicha muerte y una entrada al reino de Dios.
Sin embargo, las tentaciones continuaban, de manera que se empezó a preguntar,
si sería que él había pecado contra el Espíritu Santo.
Esto trajo gran perplejidad y tribulación sobre él por muchos días; sin embargo,
él seguía rindiéndose al Señor. Un día,
después de que había salido a caminar solo y había regresado a casa,
fue extremadamente consciente del amor de Dios hacia él,
de modo que no podía evitar admirarlo.
Aquí le fue mostrado que todo debía ser hecho en y por Cristo;
que Él conquista y destruye al tentador, al diablo y todas sus obras;
que todas esas tribulaciones y tentaciones eran buenas para él, para la prueba de su fe.
Esto trajo como efecto, que aunque a veces su mente era muy ejercitada,
él todavía era sostenido por una creencia secreta, y su alma,
mediante una esperanza firme (que era para él como un ancla),
era mantenida ilesa en el mundo depravado,
nadando sobre las furiosas olas de tentaciones.
Después de esto, (como relata él de sí mismo) un fuego puro apareció en él,
y vio que la aparición de Cristo en el corazón era
como fuego purificador y como jabón de lavadores.
Le fue dado un discernimiento espiritual,
por medio del cual vio qué cubría su mente y qué la abría.
Descubrió que lo de la carne no podía permanecer en la paciencia,
porque esta no podía rendirse a la voluntad de Dios,
ni entregarse a la muerte de la cruz, la cual es el poder de Dios.
Por otro lado,
percibió que habían sido los gemidos del Espíritu los que habían abierto su entendimiento,
y que debía esperar en Dios en ese Espíritu para obtener redención.

Por este tiempo oyó de una mujer en Lancashire que había ayunado veintidós días,
y fue a verla.
Pero al llegar allí vio que ella estaba bajo una tentación,
y después de decirle lo que sentía en su mente, la dejó y fue a Duckenfield y Manchester,
donde se quedó por un tiempo entre los profesantes de ese lugar,
y les declaraba la doctrina que ya para entonces creía firmemente que era verdad.
Algunos fueron convencidos,
y recibieron la enseñanza divina e interna del Señor y la tomaron como su regla^
footnote:[Eso que debía gobernar o tener autoridad en el
corazón y vida de un creyente.]. Por lo que pude encontrar,
este fue el inicio de la predicación de George Fox, la cual,
según lo que se me ha informado de manera fidedigna,
en aquellos primeros años consistía principalmente en unas pocas,
poderosas y penetrantes palabras,
para aquellos cuyos corazones ya estaban en alguna
medida preparados para poder recibir esta doctrina.
Me parece que estas personas, entre las que estaba la ya mencionada Elizabeth Hooton,
fueron las primeras que, por medio de una predicación simple o débil,
llegaron a ser sus compañeros creyentes,
aunque había algunas otras que habían sido convencidas directamente por el Señor,
como lo había sido George Fox,
y que se habían percatado de que debían prestar diligente atención
a las enseñanzas de la gracia de Dios que les había aparecido.
Y así, sucedió que estas personas, inesperadamente y sin darse cuenta,
se encontraron con compañeros creyentes, con quienes no estaban familiarizados antes,
tal como será plenamente relatado más adelante.

Retornando a George Fox;
los profesantes de aquellos tiempos se enfurecieron porque
algunos de sus seguidores le prestaban atención a su predicación,
pues ellos no soportaban que se hablara de la perfección y de una vida santa y sin pecado,
como un estado que puede ser alcanzado aquí. No mucho tiempo después viajó a Broughton,
en Leicestershire, y ahí asistió a una reunión de los Bautistas,
a la que habían llegado también algunas personas de otras naciones.
Esto le dio la oportunidad de predicar entre ellos la doctrina de la verdad,
y no en vano, porque él había recibido grandes revelaciones de las Escrituras.
Y debido a que un poder especial de la obra del Señor
había comenzado a levantarse en aquellas partes,
varios fueron alcanzados en sus mentes,
de modo que fueron convencidos y vueltos de las tinieblas a la luz,
en parte por su predicación y en parte por razonar con algunos.
Sin embargo, él mismo a veces estaba bajo grandes tentaciones,
sin encontrar a nadie a quien pudiera abrirle su condición, sino al Señor únicamente,
ante quien clamaba noche y día pidiéndole ayuda.

Después de un tiempo regresó a Nottinghamshire,
y ahí le plació al Señor mostrarle que la naturaleza
de aquellas cosas que eran dañinas afuera,
también se encontraba adentro, en las mentes de los hombres malvados;
y que la naturaleza del perro, del cerdo, de la víbora, de Caín, Ismael, Esaú, Faraón,
etc., estaban en los corazones de muchas personas.
Pero como esto lo entristeció, clamó al Señor diciendo: "`¿Por qué debo sentirme así,
dado que nunca he sido adicto a cometer esos males?`"
Y le fue respondido en el interior:
"`Es necesario que experimentes algo de todas las condiciones,
¿de qué otra manera podrías hablarles a todas las condiciones?`"
También vio que había un océano de tinieblas y muerte, pero igualmente,
un océano infinito de luz y amor, y que este fluía sobre el océano de tinieblas;
en todo lo cual, percibió el infinito amor de Dios.
Alrededor de ese tiempo, sucedió que mientras caminaba por el pueblo de Mansfield,
por un costado de la '`casa del campanario`'^
footnote:[Los primeros Amigos usaban el término '`casa del campanario`' ('`steeplehouse`'
en inglés) para referirse a grandes casas o edificios de iglesias,
generalmente usadas por la Iglesia de Inglaterra.], le fue dicho en el interior:
"`Eso que la gente pisotea debe ser tu comida.`"
Y al decírsele, le fue revelado que eso que la gente pisoteaba era la vida de Cristo,
y que ellos se alimentaban unos a otros con palabras,
sin ver que de ese modo la sangre del Hijo de Dios era pisoteada.
Y aunque al principio le pareció extraño,
que él debía alimentarse de lo que pisoteaban los profesantes altivos,
le fue claramente revelado cómo podía ser.

Luego, muchas personas de lejos y de cerca llegaron a verlo,
y aunque él a veces les hablaba y les descubría asuntos religiosos,
aún temía ser arrastrado por ellas.
Ahora bien, la razón por la que las personas acudían a él en masa podría haber sido,
en parte, por lo siguiente: Un tal Brown, sobre su lecho de muerte,
dijo muchas cosas notables con respecto a George Fox a modo de profecía, y entre otras,
dijo que el Señor lo haría un instrumento para la conversión de las personas.
Y con respecto a otros que entonces eran sólo apariencia,
dijo que ellos no llegarían a nada; lo cual se cumplió con el tiempo,
aunque este hombre no vivió para verlo, porque no se recuperó de su enfermedad.
Pero después de que fue enterrado, George Fox cayó en tal condición,
que no sólo se veía como un cadáver, sino que a muchos que llegaron a verlo,
les parecía como si realmente hubiera estado muerto;
muchos lo visitaron por alrededor de catorce días,
y se asombraban al verlo tan alterado de semblante.

Finalmente, sus penas y tribulaciones empezaron a desaparecer,
y lágrimas de gozo cayeron de sus ojos,
de modo que habría podido llorar noche y día con lágrimas de alegría,
en quebrantamiento de corazón. Y para dar cuenta
de su condición a aquellos que son capaces de comprenderla,
usaré sus propias palabras: "`Vi,`" dice él, "`lo que no tenía fin,
y cosas que no pueden ser pronunciadas, y la grandeza e infinitud del amor de Dios,
el cual no puede ser expresado con palabras.
Por el glorioso poder eterno de Cristo,
fui llevado a través del propio océano de tinieblas y muerte,
y a través y sobre el poder de Satanás. Fui llevado incluso,
a través de esa oscuridad que cubría todo el mundo,
que lo encadenaba todo y que encerraba todo en la muerte.
Y el mismo poder eterno de Dios que me llevó a través de esas cosas,
fue el que después sacudió la nación, a los sacerdotes, profesantes y personas.
Entonces, yo podría decir, que había estado en la Babilonia espiritual,
la Sodoma espiritual, el Egipto y la tumba espirituales,
pero que por medio del poder eterno de Dios, había salido de ahí,
había sido llevado sobre eso, y había sido llevado del poder de eso al poder de Cristo.
Vi que la cosecha estaba blanca y que la semilla de Dios yacía abundante en la tierra,
tan espesa como si fuera trigo sembrado externamente,
pero que no había nadie para recogerla; y por eso lloré hasta las lágrimas.`"
Luego se divulgó la noticia en el extranjero,
de que George Fox era un joven que tenía un espíritu de discernimiento, por tanto,
muchos profesantes, sacerdotes y personas acudían a él,
de modo que su ministerio se incrementó; pues al haber recibido grandes revelaciones,
él les hablaba de las cosas de Dios y era escuchado por muchos con atención,
quienes al irse difundían su fama.
Entonces llegó el tentador y lo atacó de nuevo,
acusándolo de haber pecado contra el Espíritu Santo, pero George no pudo ver en qué,
y entonces recordó la condición de Pablo,
de cómo después de haber sido tomado al tercer cielo
y haber visto cosas que no era lícito pronunciar,
le fue enviado un mensajero de Satanás para que lo abofeteara,
a fin de que él no se exaltara a sí mismo.
Así, George Fox, con la ayuda del Señor, también superó esa tentación.

Entonces el año 47 de ese siglo llegó a su fin,
y los asuntos de estado en Inglaterra se volvieron cada vez más nublados y más complicados,
pues el Rey,
que ya no se sentía seguro en Hampton Court (adonde había sido llevado por el ejército),
se retiró a la Isla de Wight.
El Parlamento seguía insistiendo en la abrogación del episcopado,
y buscaba ser el dueño de las fuerzas militares.
Como el Rey no estaba dispuesto a ceder a esto, fue mantenido bajo custodia,
y el Parlamento ya no lo consideraba un soberano a quien se le debiera obediencia.

Bajo estos problemas domésticos,
las mentes de muchas personas estaban preparadas para recibir
un camino y una doctrina de la piedad más internos,
y fue en el año 1648, que varias personas buscando al Señor,
se convirtieron en compañeros creyentes y entraron en sociedad con George Fox.
Estos comenzaron a tener grandes reuniones en Nottinghamshire,
las cuales eran visitadas por muchos.
Por ese tiempo se celebró una reunión de sacerdotes y profesantes en la casa de un juez,
y George Fox también acudió,
y los escuchó conversar acerca de cómo el apóstol Pablo había dicho:
"`Yo no conocí el pecado sino por la ley; porque tampoco conociera la codicia,
si la ley no dijera:
No codiciarás.`" Y dado que ellos sostenían que esto hablaba de la ley externa,
George Fox les dijo: "`Pablo dijo esto después de haber sido convencido,
pues él ya tenía la ley externa y había sido criado en ella,
incluso cuando estaba en el deseo de persecución.
Pero aquí Pablo habló de la ley de Dios en su mente,
a la que él servía, contra la cual la ley en sus miembros hacía guerra.`"
Estas palabras hallaron tanta aceptación,
que aquellos de los sacerdotes y profesantes que eran más moderados cedieron,
y concordaron en que no era la ley externa sino la interna,
la que mostraba la pasión interna,
de la cual el apóstol hablaba ahí. Después de esto fue de nuevo a Mansfield,
donde había una gran reunión de profesantes y de otras personas, y estando entre ellos,
y movido a orar,
apareció un poder tan extraordinario y se apoderó
de los corazones de algunos en una forma tan notable,
que incluso parecía que la casa se sacudía. Y después de que él había orado,
algunas de las autoridades empezaron a decir:
"`Esto se asemeja a los días de los Apóstoles,
cuando en el día de Pentecostés la casa donde se encontraban fue sacudida.`"

No mucho después de esto, hubo otra gran reunión de profesantes,
a la que George Fox también acudió, y oyéndolos conversar sobre la sangre de Cristo,
exclamó entre ellos: "`¿Acaso no ven la sangre de Cristo?
Deben verla en sus corazones, para rociar sus corazones y consciencias de obras muertas,
para servir al Dios vivo.`"
Esta doctrina sorprendió a estos profesantes,
que buscaban conocer la sangre de Cristo únicamente fuera de ellos,
sin pensar que debía ser sentida internamente.
Pero un cierto capitán, cuyo nombre era Amos Stoddard, fue profundamente alcanzado,
y viendo que ellos se esforzaban por derrotar a G. Fox con muchas palabras, dijo:
"`¡Qué hable el joven! ¡Escuchen al joven hablar!`"
Y después de conocer mejor a G. Fox,
tuvo la oportunidad de ser más instruido en el camino de la piedad,
de la que llegó a ser un fiel seguidor.

Un tiempo después, G. Fox regresó a Leicestershire, su propio condado,
donde varias personas tiernas fueron convencidas
por su predicación. Al pasar de ahí a Warwikshire,
se encontró con una gran compañía de profesantes, que se había reunido en un campo,
donde oraban y exponían las Escrituras.
Ahí le dieron una Biblia, la cual él abrió en Mateo 5,
donde Cristo exponía algunas partes de la ley.
De este pasaje G. Fox aprovechó para explicarles el estado interno y externo del hombre,
y conforme esto que declaraba empezó a ganar terreno en algunos,
cayeron en una fiera disputa entre ellos y se separaron.

Luego oyó de una gran discusión a realizarse en Leicester,
en la que estaban involucradas personas de varias persuasiones (tales como Presbiterianos,
Independientes, Bautistas y Episcopales).
Se fijó la reunión en la '`casa del campanario`' y George F. fue ahí,
donde se había reunido una gran cantidad de personas,
algunas de las cuales hablaban en las bancas y el sacerdote en el púlpito.
Al fin, después de mucha discusión, una mujer comenzó a hacer una pregunta:
"`¿Qué es ese nacimiento del que habla el apóstol Pedro,
ser "`renacidos de simiente incorruptible, por la palabra de Dios,
que vive y permanece para siempre?`"
En lugar de responder la pregunta, el sacerdote le dijo:
"`No permito que una mujer hable en la iglesia,`" aunque
antes había dado libertad de que cualquier persona hablara.
Esto encendió el celo de G. Fox, y dando un paso al frente le preguntó al sacerdote:
"`¿Llamas a este lugar (señalando la '`casa del campanario`') '`iglesia`',
o llamas '`iglesia`' a esta mezcla de personas?`"
Pero el sacerdote en lugar de responder, le preguntó qué era la iglesia.
G+++.+++ Fox le dijo:
"`La iglesia es '`la columna y baluarte de la verdad,`' hecha de piedras vivas,
miembros vivos, una casa espiritual, de la que Cristo es la cabeza;
pero Él no es cabeza de una mezcla de personas, o de una casa hecha de cal,
piedras y madera.`"
Esto causó tal conmoción,
que el sacerdote bajó de su púlpito y otros salieron de sus bancas,
y el debate se arruinó. Pero G. Fox se fue a una gran posada
y ahí debatió con sacerdotes y profesantes de todo tipo,
manteniendo lo que había dicho antes hasta que todos se fueron.
Sin embargo, varios fueron convencidos ese día,
y entres esos la mujer que había hecho la pregunta.

Después de esto, G. Fox regresó a Nottinghamshire y fue al Valle de Beavor,
donde les predicó del arrepentimiento a las personas.
Permaneció allí algunas semanas y pasó por varios pueblos,
de modo que muchos fueron convencidos de la verdad de su doctrina.
Por ese tiempo, una mañana mientras estaba sentado junto al fuego,
una nube vino sobre él y una tentación lo acosaba.
Mientras estaba sentado quieto, le fue sugerido:
"`Todas las cosas se originan por naturaleza.`"
Por un rato estuvo en un estado bastante nublado, pero como continuó sentado quieto,
la gente de la casa no percibió nada.
Al fin, una esperanza viva se levantó en él y también una voz que dijo:
"`Hay un Dios vivo,
el Creador de todas las cosas,`" e inmediatamente la nube y la tentación se desvanecieron,
por lo que su corazón se alegró y alabó al Señor.

No mucho después de eso,
se topó con algunas personas que sostenían la dañina idea de que no había Dios,
y que todas las cosas se originan por naturaleza.
Pero razonando con ellos, los confundió tanto,
que algunos se vieron obligados a confesar que había un Dios vivo.
Entonces comprendió que había sido bueno para él haber sido tratado bajo aquella nube.
Luego tuvo grandes reuniones en aquellos lugares,
y como el poder divino estaba obrando en esa parte del país, muchos fueron reunidos.
Después, al llegar a Derbyshire, hubo una gran reunión de sus amigos en Eaton,
donde muchos de ellos empezaron a predicar la doctrina de la verdad,
y más tarde fueron movidos para que también declararan la verdad en otros lugares.

Llegando a Mansfield por ese tiempo,
oyó que en un pueblo aproximadamente a ocho millas de distancia,
iba a realizarse una reunión de jueces para deliberar acerca de la contratación de sirvientes.
Sintiendo una obligación en su mente,
fue y los exhortó a no oprimir a los sirvientes en sus salarios,
sino a hacer lo correcto y justo con ellos;
e igualmente amonestó a los sirvientes a cumplir sus tareas y a servir con honestidad.
Ellos recibieron su exhortación amablemente.
También se sintió movido a ir a varias cortes y '`casas
del campanario`' en Mansfield y otros lugares,
advirtiéndoles a dejar de lado la opresión, el engaño y otros males.
Después de oír en Mansfield de un hombre en ese condado que todos los días estaba borracho,
que era un conocido proxeneta y también un poeta,
fue adonde él y lo reprendió fuertemente por sus caminos malignos.
Esto impresionó tanto al hombre, que dirigiéndose después a George Fox le dijo,
que él se había sentido tan afectado cuando le había hablado,
que apenas le habían quedado fuerzas.
Este hombre fue tan plenamente convencido,
que se volvió de su maldad y se convirtió en un hombre honesto y sobrio,
para el asombro de los que lo conocían antes.
Así avanzó la obra del ministerio de G. Fox,
y asimismo muchos fueron vueltos de las tinieblas a la luz;
y muchas reuniones de sus amigos, que se habían incrementado en número desde el año 1646,
ya estaban establecidas en varios lugares.

George Fox había llegado entonces,
a una condición completamente diferente de la que había vivido anteriormente,
no sólo porque experimentaba una renovación de corazón y restauración de la mente,
sino también, porque la virtud de las cosas creadas le había sido revelada;
de modo que empezó a meditar si debía practicar la medicina para el bien de la humanidad.
Pero Dios tenía otro servicio para él:
Le fue mostrado que tenía que entrar a una labor espiritual,
y que aquellos que continuaran fieles al Señor podrían alcanzar
un estado en el que la inclinación pecaminosa estaría sometida.
Además, le fueron reveladas las tres grandes profesiones en el mundo, a saber, medicina,
teología y derecho.
Vio cómo los médicos carecían de la sabiduría de Dios,
por medio de la cual habían sido hechas las cosas creadas, y por tanto,
no conocían sus virtudes.
Vio cómo los abogados en general, carecían de equidad y justicia, y por tanto,
estaban fuera de la ley de Dios, la cual fue puesta sobre la primera transgresión,
y sobre todo el pecado,
y estaba en concordancia con el Espíritu de Dios que estaba oprimido en el hombre.
Vio cómo los sacerdotes, en su mayor parte, estaban fuera de la verdadera fe,
de la cual Cristo es el autor,
y la que purifica el corazón y hace que el hombre tenga acceso a Dios.
De modo que estos médicos, abogados y sacerdotes, que pretendían curar el cuerpo,
establecer la propiedad de las personas y curar el alma,
carecían del verdadero conocimiento y sabiduría que debían poseer.
Sin embargo,
él sentía que había un poder divino por medio del cual todos podrían ser reformados,
si sólo recibieran y se inclinaran ante este.

También vio, que aunque los sacerdotes se equivocaban,
aun así no eran los más grandes engañadores mencionados en las Escrituras.
Que los más grandes engañadores eran aquellos que como Caín, habían oído la voz de Dios;
y que como Coré, Datán y Abiram y su compañía,
habían salido de Egipto y cruzado el Mar Rojo,
y habían alabado a Dios a las orillas del mar.
Eran aquellos, que habiendo llegado tan lejos como Balaam,
podían hablar la palabra de Dios, tras haber oído Su voz y conocido Su Espíritu,
para que pudieran ver la estrella de Jacob y la hermosura de las tiendas de Israel,
contra las cuales ningún encantamiento podía prevalecer.
Él vio que estos que habrían podido hablar mucho de su experiencia divina, y aun así,
se habían apartado del Espíritu de Dios y se habían rebelado,
eran los grandes engañadores, más allá, por mucho, de los sacerdotes.
También vio cómo la gente, en general,
leía las Escrituras sin tener un verdadero sentido de ellas;
pues muchos exclamaban contra Caín, Ismael, Esaú, Coré, Balaam, Judas, etc.,
sin considerar que la naturaleza de estos todavía estaba en ellos, y por eso,
siempre les aplicaban a otros esa naturaleza en la que ellos mismos todavía vivían.

Por este tiempo el Señor también le reveló,
que todo hombre era alumbrado por la divina luz de Cristo,
y vio que los que creían en Su luz,
salían de la condenación y llegaban a ser hijos de la luz,
pero los que la aborrecían y no creían en ella, eran condenados por ella,
aunque hicieran profesión de Cristo.
Todo esto lo vio en las revelaciones puras de la luz.
También vio que Dios le había concedido una medida de Su Espíritu a todos los hombres,
y que por medio de esta, ellos podían llegar a servir y adorar verdaderamente al Señor;
y que Su gracia, que trae salvación^
footnote:[Tito 2:11]
y les ha aparecido a todos los hombres, era capaz de llevarlos al favor de Dios.

En cierto momento, mientras caminaba por los campos, entendió que le fue dicho:
"`Tu nombre está escrito en el Libro de la Vida del Cordero,
quien era antes de la fundación del mundo.`"
Esto él lo tomó como la voz del Señor y creyó que era verdad.
Luego se sintió poderosamente movido a salir al mundo,
el cual era como un desierto con cardos y espinos; y luego encontró,
que el mundo se inflamaba contra él y hacía un ruido
como grandes y furiosas olas del mar,
porque cuando fue a proclamar el día del Señor entre los sacerdotes, profesantes,
magistrados y personas, todos eran como un mar revuelto.
Y así fue enviado a volver a las personas de las tinieblas a la luz,
para que pudieran recibir a Cristo Jesús,
pues vio que a todos los que Lo recibieran en Su luz,
Él les daría el poder de ser hechos hijos de Dios.
Por tanto, debía volver a las personas a la gracia de Dios y a la Verdad en el corazón,
para que por medio de esta gracia fueran enseñados y obtuvieran salvación;
ya que Cristo había muerto por todos los hombres y era propiciación para todos,
habiendo '`alumbrado a todo hombre`'^
footnote:[Juan 1:9]
con Su divina y salvadora luz,
y dado "`a cada uno la manifestación del Espíritu para provecho`"^
footnote:[1 Corintios 12:7]. Cuando el Señor lo envió a predicar el evangelio eterno,
lo hizo con alegría,
y se esforzaba por rescatar a las personas de sus propios caminos y llevarlas a Cristo,
el camino nuevo y vivo; rescatarlas de sus iglesias,
las que el hombre había hecho y congregado, y llevarlas a la iglesia en Dios,
la asamblea general registrada en el cielo, de la que Cristo es la cabeza;
rescatarlas de los maestros del mundo, hechos por el hombre,
y llevarlas a aprender de Cristo, quien es el camino, la verdad y la vida,
y de quien el Padre dijo: "`Este es Mi Hijo amado,
a Él oíd;`" y rescatarlas de la adoración del mundo,
y llevarlas al Espíritu de Dios en lo íntimo, para que en Este adoraran al Padre,
quien busca que los tales Lo adoren.

También encontró que el Señor le había prohibido
quitarse el sombrero ante cualquier hombre,
de cualquier clase social;
encontró que se le requería que hablara de "`tú`" y de "`ti`"
con todo hombre y mujer sin hacer acepción de personas^
footnote:[En la década de 1600,
se puso de moda (como un medio para mostrar honor o adulación),
usar el "`usted`" o "`ustedes`" para dirigirse a las personas de mayor estatus social,
mientras que el "`tú`" y "`ti`" estaban reservados para sirvientes, niños,
o personas de baja posición social o económica.
Los primeros Amigos se apegaron a lo que entonces se consideraba "`lenguaje
simple,`" y usaban el "`tú`" y el "`ti`" con toda persona y sin distinción,
y el "`ustedes`" para dos o más.]; encontró que no debía decirle,
"`Buenos días`" ni "`Buenas noches`" a la gente,
ni podía inclinarse o arrastrar su pierna ante nadie^
footnote:[Los saludos normales entre compañeros en aquel momento,
implicaban arrastrar el pie derecho hacia atrás a lo largo del suelo,
e inclinarse mientras se quitaban el sombrero, y luego dirigirse uno al otro,
con títulos como "`su Señoría,`" "`su Eminencia,`"
etc.]. Esto era algo tan inusual para con la gente,
que hizo que muchas personas de todas las persuasiones
y profesiones se enfurecieran contra él,
pero mediante la ayuda del Señor fue llevado sobre todo,
y muchos llegaron a ser compañeros creyentes y se volvieron al Señor en poco tiempo.
Es casi inexplicable la rabia y la furia que se levantaron, los golpes, pellizcos,
palizas y encarcelamientos que padecieron estos creyentes,
además del peligro que corrían algunas veces de perder sus vidas,
por asuntos tan pequeños; así de insensato es el hombre en su estado natural.
Pues no sirvió de nada que se dijera,
que el '`honor del sombrero`' era un honor de abajo,
el cual el Señor pondría en el polvo; que era un honor que buscaba el orgulloso,
que no buscaba el honor que viene únicamente de Dios;
que era un honor inventado por los hombres en la caída, y por tanto,
se ofendían si no se les daba.
Aun cuando Cristo había dicho: "`¿Cómo podéis vosotros creer,
pues recibís gloria los unos de los otros,
y no buscáis la gloria que viene del Dios único?`"
Todas estas razones encontraron poca acogida entre los sacerdotes, magistrados y otros,
pues injurias amargas,
malos tratos y abusos vergonzosos se convirtieron rápidamente
en la suerte y porción de los que (por asunto de consciencia)
no podían seguir más las costumbres comunes de la época.
Pues aunque se alegaba que quitarse el sombrero era algo pequeño,
algo que nadie debía considerar un asunto de escrúpulos^
footnote:[La palabra __escrúpulos__ aparece a menudo a lo largo
de esta historia como sustantivo y como verbo.
Es usada para hablar de un sentimiento de duda o vacilación con
respecto a la moralidad o decencia de un curso de acción.],
fue increíble ver la gran perturbación que causó este pretendido
asunto pequeño entre las personas de todo tipo,
pues incluso aquellos que deseaban ser vistos como humildes y mansos,
pronto mostraron de qué espíritu eran, cuando este honor mundano les fue negado.
Pero todo esto sirvió para fortalecer más y más a
los compañeros creyentes en su comportamiento sencillo,
y para hacerlos vivir fielmente a la convicción de sus consciencias,
sin hacer acepción de personas.

Mientras tanto, los problemas de la tierra continuaban.
Dejamos al Rey en el año 1647 en la Isla de Wight, habiendo sido, efectivamente,
despojado de la corona.
Un tiempo después de esto, el Duque de York (segundo hijo del Rey),
que entonces tenía catorce años, huyó a Holanda disfrazado con ropa de mujer.
Su hermano mayor, el Príncipe de Gales, que había huido a Francia dos años antes,
llegó a Hellevoetsluis en Holanda,
y partió de ahí con algunos hombres de guerra ingleses, cuyos comandantes eran del Rey,
a los Downs en Inglaterra, con la intención de tomar los barcos procedentes de Londres.
También dio a conocer mediante la divulgación de una declaración,
que había llegado para liberar a su padre.
Para entonces, también se había iniciado una negociación entre el Rey y el Parlamento,
y parecía que había algunas esperanzas de llegar a un acuerdo,
pero el ejército (principal instrumento para derribar el poder real) se opuso a este,
al pedir justicia contra todos los que habían perjudicado al país,
sin excepción. Esto rompió el tratado y varios miembros
sospechosos fueron retirados del Parlamento,
y el Rey fue llevado a Windsor, cerca del tiempo llamado Navidad.
A partir de ese momento, se resolvió no enviarle más delegaciones,
ni recibir ninguna de él, quien para entonces ya no era llamado Rey,
sino únicamente Carlos Estuardo; un muy extraño giro en los asuntos de estado,
y una poderosa evidencia de la inconsistencia de estos.
Pero las cosas no se detuvieron ahí,
porque se determinó llevar a Carlos Estuardo a juicio,
y el Parlamento nombró como jueces al General Thomas Fairfax y a Oliver Cromwell,
Teniente General, junto con más de cien personas.
El Rey fue conducido de Windsor a St. James, y de ahí,
fue llevado a Westminster Hall para que compareciera ante
aquellos que habían formado el tribunal de justicia,
donde fue procesado como culpable de alta traición por haber iniciado
una guerra contra el Parlamento y el pueblo de Inglaterra.
Pero él no reconoció la legalidad de esa corte, ni reconoció su autoridad, y dijo:
"`Yo no fui nombrado por las personas, ellas son mías por herencia.`"
Y al no estar dispuesto a responder al cargo, el 27 del mes llamado Enero,
fue sentenciado a muerte como tirano, traidor,
asesino y enemigo público de la Mancomunidad.

Pero antes de que se pronunciara la sentencia,
el Rey deseaba que se le permitiera hacer una proposición a ambas Cámaras del Parlamento,
en la Cámara pintada,
en la que planeaba proponer su propia renuncia (como se dijo después),
y que se le diera acceso al trono a su hijo el Príncipe de Gales;
pero la petición fue denegada por el Tribunal.
Ahora, aunque el mencionado Príncipe de Gales,
considerando el peligro que corría su padre,
había solicitado ayuda a los Estados Generales de las Provincias Unidas en la Haya,
y aunque estas enviaron a dos Embajadores del Parlamento,
que llegaron a Londres el mismo día que la fatal sentencia fue pronunciada,
y aunque luego estuvieron con Fairfax y Cromwell y otros comandantes,
y uno de ellos tuvo una audiencia ante el Parlamento para interceder por la vida del Rey,
aun así, todo resultó en vano.
El 30 del mencionado mes,
el Rey fue llevado a un cadalso levantado frente a la casa de banquetes,
y su cabeza fue cercenada de su cuerpo.
El mismo día el Parlamento ordenó que se publicara un aviso,
en el que se declaraba que se consideraría traición
el esfuerzo por promover al Príncipe de Gales,
Carlos Estuardo II, como Rey de Inglaterra;
o a cualquier otra persona como gobernador principal de la misma.
Y luego, después de haber abolido la Cámara de los Lores,
asumieron para sí mismos el gobierno principal de la nación,
con el título de '`Parlamento de la Mancomunidad de Inglaterra.`'

Tan pronto como las noticias de la muerte de Rey llegaron a Escocia, Carlos II,
Príncipe de Gales, fue proclamado Rey de Gran Bretaña en Edimburgo,
con tal de que (antes de asumir la autoridad real) les diera satisfacción sobre
algunos asuntos relacionados con religión. Y aunque esto desagradó a los ingleses,
los escoceses afirmaron que bien podían hacerlo,
porque los ingleses habían hecho lo mismo,
después de la muerte del fallecido padre del Rey en el año 1625.

Dejemos los asuntos de estado y regresemos a G. Fox, quien en el año 1649,
estaba muy aplicado en declarar abiertamente contra todo tipo de pecado.
Por tanto,
no sólo acudía a los tribunales clamando por justicia y
exhortando a los jueces y magistrados a que hicieran justicia,
sino que también les advertía a los que tenían casas públicas de entretenimiento,
que no dejaran que las personas tomaran más de lo que les hacía bien.
También testificaba contra las velas a los muertos, festejos en mayo, juegos,
espectáculos,
mediante lo cual las personas eran conducidas a la vanidad y sacadas del temor de Dios;
pues los días apartados como feriados,
eran usualmente los días cuando el Señor era más deshonrado.
Cuando entraba en los mercados,
también declaraba contra la comercialización engañosa y les advertía
a todos que trataran con justicia y hablaran la verdad,
y testificaba contra los artistas timadores que ejecutaban trucos en sus escenarios.
Cuando se ofrecía la ocasión,
les advertía a los maestros y maestras que enseñaran
a sus niños a tener en cuenta el temor del Señor,
y les decía que ellos mismos debían ser ejemplos y modelos
de virtud para los niños. Pero era muy pesado para él,
cuando oía sonar la campana para llamar a la gente a reunirse en la '`casa
del campanario,`' porque le parecía que era como una campana de mercado,
que reunía a las personas para que el sacerdote dispusiera su mercancía para la venta.

Un Primer-día de la semana en la mañana,
yendo con algunos de sus amigos a Nottingham para celebrar una reunión ahí,
y habiendo visto desde la cima de una colina la gran '`casa del campanario`' del pueblo,
sintió que le era requerido que declarara contra ese templo de ídolos
y los adoradores ahí. No les dijo nada de esto a los que estaban con él,
sino que continuó con ellos a la reunión,
donde después de algún tiempo los dejó y se fue a la '`casa del campanario.`' Ahí,
el sacerdote tomó como texto las palabras del apóstol en 2 Pedro 1:19,
"`Tenemos también la palabra profética más segura,
a la cual hacéis bien en estar atentos como a una antorcha que alumbra en lugar oscuro,
hasta que el día esclarezca y el lucero de la mañana salga en vuestros corazones.`"
Y luego le dijo a la gente que esta "`palabra profética más segura`" eran las Escrituras,
por medio de las cuales debían probarse todas las doctrinas, religiones y opiniones.
Cuando G. Fox oyó esto, sintió un poder muy fuerte y un celo de Dios obrando en él,
que lo hizo exclamar: "`¡Oh, no!
Esa palabra no son las Escrituras, sino el Espíritu Santo,
por medio del cual los hombres santos de Dios escribieron las Escrituras,
y por el que se deben probar todas las opiniones, religiones y juicios.
Este era el que conducía a toda verdad y el que daba el conocimiento de la misma.
Porque los judíos tenían las Escrituras, y sin embargo,
resistieron al Espíritu Santo y rechazaron a Cristo,
a la Estrella resplandeciente de la Mañana, y lo persiguieron a Él y a Sus apóstoles;
y aunque se encargaron de juzgar la doctrina de ellos por las Escrituras,
se equivocaron al juzgar y los juzgaron incorrectamente,
porque lo hicieron sin el Espíritu Santo.`"
Mientras hablaba de esta manera, llegaron los oficiales,
se lo llevaron y lo pusieron en una prisión sucia y maloliente.
Por la noche fue llevado ante el alcalde, los concejales y alguaciles del pueblo,
y mientras lo interrogaban les dijo que el Señor lo había movido a entrar en la '`casa
del campanario.`' Y aunque el alcalde al principio parecía irritado e inquieto,
con el tiempo se calmó. Sin embargo, después de algo de conversación,
G+++.+++ Fox fue enviado de regreso a la prisión. Pero tiempo después,
el jefe de alguaciles John Reckless lo mandó a llamar a su casa, y cuando G. Fox entró,
la esposa del alguacil lo recibió en el pasillo y tomándolo de la mano dijo:
"`La salvación ha llegado a nuestra casa,`" pues su sermón
en la '`casa del campanario`' había asombrado tanto a muchos,
que no podían sacarse de sus oídos el sonido.
Y no sólo esta mujer fue afectada, sino también el esposo de ella,
los niños y sirvientes, y todos fueron cambiados por el poder del Señor.

Y así, George Fox alojado en la casa del alguacil, tuvo largas reuniones ahí,
a las que acudieron algunas personas de cierta condición en el mundo,
y que fueron notablemente alcanzadas en sus mentes por un poder invisible.
John Reckless que era uno de este número,
envió a llamar a otro alguacil y a una mujer con la que ambos habían comerciado,
y le dijo en presencia del otro alguacil,
que ellos la habían perjudicado cuando habían tratado con ella, y que por tanto,
debían hacerle restitución. Reckless exhortó al otro alguacil a hacer lo mismo,
estando él mismo consciente de que este era un deber indispensable,
pues un poderoso cambio se había operado ya en él y su entendimiento había sido abierto.
El siguiente día de mercado, mientras caminaba con G. Fox en la recámara,
en sus pantuflas, dijo:
"`Debo ir al mercado y predicarle arrepentimiento a la gente;`" y así,
calzado con sus pantuflas entró al mercado y a varias calles predicando arrepentimiento.
Algunos otros del pueblo también fueron movidos a hablarles al alcalde,
a los magistrados y a las personas, y los exhortaban a que se arrepintieran.
Pero los magistrado no pudieron soportar esto, y para desahogar su cólera sobre G. Fox,
lo mandaron a buscar a la casa del alguacil y lo recluyeron en la prisión común,
donde lo mantuvieron hasta que llegó la sesión de la corte.
Él debía comparecer ante del juez,
pero debido a que el alguacil tardó mucho tiempo en recogerlo,
cuando G. Fox llegó a la sala de sesiones el juez ya se había levantado.
Sin embargo, el juez estaba un poco disgustado y dijo:
"`Yo habría amonestado al joven (es decir, G. Fox),
si hubiera sido llevado delante de mí.`" Por tanto,
fue llevado de regreso a la prisión. Mientras tanto,
un poder tan maravilloso había irrumpido entre sus amigos, que muchos estaban asombrados,
e incluso varios de los sacerdotes fueron suavizados y reconocieron
el poder del Señor. Finalmente G. Fox fue puesto en libertad,
después de haber estado prisionero por largo tiempo,
y entonces viajó como antes en la obra del Señor.

Al llegar a Mansfield-Woodhouse,
encontró a una mujer trastornada bajo el cuidado de un doctor,
atada y con el cabello suelto.
El doctor estaba intentando sangrarla, pero no pudo obtener sangre,
lo que hizo que G. Fox pidiera que la soltaran; y después de que la soltaron,
él le habló y le mandó en el nombre del Señor que estuviera callada y quieta.
Esto produjo tal efecto en ella que se quedó quieta,
de modo que su mente se fue calmando y se sanó,
y después recibió la doctrina de la verdad y continuó en ella hasta su muerte.

Mientras G. Fox estaba en ese lugar,
fue movido a ir a la '`casa del campanario`' y declararles
la verdad al sacerdote y a las personas,
pero mientras lo hacía, la gente se abalanzó sobre él, lo golpearon y casi lo asfixian,
porque lo golpearon e hirieron cruelmente con sus manos, biblias y bastones.
Luego lo sacaron a rastras, y aunque apenas podía sostenerse en pie,
lo pusieron en el cepo, donde permaneció sentado varias horas,
y durante ese tiempo algunos llegaron con látigos y amenazaron con azotarlo.
Después de un rato, lo llevaron delante de los magistrados, a la casa de un caballero,
quien al ver cuán cruelmente había sido tratado,
lo dejó en libertad después de muchas amenazas.
Pero una multitud grosera lo apedreó hasta las afueras de la ciudad,
y aunque apenas podía caminar, con mucha dificultad se alejó del pueblo como una milla,
donde se topó con algunas personas que le dieron algo para aliviarlo,
porque estaba herido internamente.
Pero le plació al Señor sanarlo pronto,
y algunas personas fueron convencidas de la verdad ese día que él la había
declarado en la '`casa del campanario,`' por lo que se regocijó.

De Nottinghamshire se fue a Leicestershire, acompañado por varios de sus amigos,
y llegando a Barrow, conversó con algunos Bautistas.
Uno de ellos dijo: "`Lo que no es de fe, es pecado.`"
Fox le preguntó: "`¿Qué es fe, y cómo es obrada en el hombre?`"
Pero ellos apartándose de ese tema, empezaron a hablar de su bautismo en agua,
lo que le dio oportunidad a G. Fox y a sus amigos de preguntar:
"`¿Quién bautizó a Juan el Bautista, quién bautizó a Pedro y al resto de los Apóstoles?`"
Pero ellos guardaron silencio ante esas preguntas,
y después de otro rato de conversación se fueron.
El siguiente Primer-día de la semana,
G+++.+++ Fox y los que estaban con él llegaron a Bagworth,
y fueron a la '`casa del campanario,`' y después de que terminó el sacerdote,
se ocuparon en hablar con las personas.

Al irse de ahí oyó que en Coventry había unas personas que estaban en prisión por religión,
y cuando iba de camino a la cárcel, tal como lo relata él,
"`la palabra del Señor vino a mí diciendo: Mi amor siempre está contigo,
y tú estás en Mi amor.`"
Por medio de esto fue abrumado con un sentido del
amor de Dios y fortalecido en su hombre interior.
Pero al llegar a la cárcel un gran poder de tinieblas lo golpeó,
porque halló que los que estaban encarcelados por religión eran unos blasfemos,
que habían llegado a tal grado de engaño que afirmaban que eran dioses.
Ellos se esforzaron por sustentar esta maligna opinión en las Escrituras,
aplicando mal lo que le fue dicho al Apóstol Pedro cuando una sábana bajó delante de él,
a saber: "`Lo que Dios limpió, no lo llames tú común o inmundo.`"
También usaron las palabras del Apóstol Pablo con respecto
a la reconciliación de Dios con todas las cosas;
tanto las cosas del cielo como las de la tierra.
G+++.+++ Fox estaba enormemente afligido ante esta blasfemia y les dijo
que esas Escrituras no servían de nada al propósito de ellos.
Y viendo que ellos decían que eran dioses,
les preguntó si sabían si llovería al día siguiente.
Ellos respondieron diciendo: "`No podemos decirlo,`" entonces él les dijo:
"`Dios puede decirlo.`"
También les preguntó si ellos creían que iban a estar siempre en esa condición,
o si iban a cambiar.
Otra vez respondieron: "`No podemos decirlo.`"
G+++.+++ Fox les dijo que Dios podía decirlo y que Él no cambia.
Esto los confundió y los derribó por un rato,
y después de reprenderlos por sus expresiones blasfemas se fue.
No mucho después de esto, uno de estos '`ranters,`' cuyo nombre era Joseph Salmon,
entregó un documento de retractación, por el que fueron puestos en libertad.

De Coventry, G. Fox se fue a Atherstone, donde, tras entrar en la capilla,
les declaró a los sacerdotes y al pueblo que Dios
había venido para enseñar a Su pueblo Él mismo,
y a rescatarlos de todos sus maestros hechos por el hombre, para que oyeran a Su Hijo.
Y aunque unos pocos se enfurecieron, en general estuvieron bastante tranquilos,
y algunos fueron convencidos.
Después de este servicio, se fue a Market-Bosworth,
y al llegar al lugar público de adoración encontró a Natanael Stevens predicando,
quien (como ya se ha dicho) era el sacerdote del pueblo donde G. Fox había nacido.
Cuando G. Fox aprovechó la ocasión para hablar,
Stevens le dijo a la gente que él estaba loco y que no debían oírlo,
aunque antes le había dicho al Coronel Purfoy con respecto a G. Fox:
"`Nunca se ha cultivado una planta así en Inglaterra.`"
Entonces la gente que había sido provocada por el sacerdote,
cayó encima de G. Fox y sus amigos, y los apedrearon hasta sacarlos del pueblo.
Sin embargo, esto obró en la mente de algunos,
de modo que sus corazones fueron suavizados.

Y viajando así llegó a Twy-Cross,
donde les habló a los funcionarios de impuestos y les advirtió
que tuvieran cuidado de oprimir a los pobres.
Estando en ese pueblo fue a visitar a su aposento,
a un hombre rico que había estado enfermo por mucho
tiempo y que había sido desahuciado por los médicos.
Después de decirle algunas palabras fue movido a orar junto a su cama,
y el Señor escuchó su oración, y el hombre enfermo fue sanado.
Pero después de que G. Fox había bajado las escaleras y estaba
hablando con algunos que estaban allí en una habitación,
un criado entró con una daga desenvainada y amenazó con apuñalarlo.
Pero George, mirando fijamente al hombre le dijo: "`¡Ay de ti,
pobre criatura! ¿Qué harás con tu arma carnal?
No es más que una paja para mí.`" Entonces el criado se detuvo y se fue furioso,
y cuando más tarde su señor se enteró de esto lo despidió de su servicio.
Más adelante este hombre fue muy amable con los Amigos,
y cuando G. Fox regresaba a ese pueblo, él y su esposa iban a verlo.

Después de esto se fue a Derbyshire,
donde sus compañeros creyentes estaban creciendo en fuerza divina.
Y al llegar a Chesterfield, se encontró que un tal Britland era el sacerdote ahí,
quien había sido parcialmente convencido de la doctrina de la verdad,
había hablado mucho en favor de ella y había visto más allá de la mayoría de los sacerdotes.
Él había obtenido la casa parroquial, después de que el sacerdote de ese pueblo muriera.
Entonces, G. Fox hablándoles a él y al pueblo,
se esforzó por sacarlos de la enseñanza del hombre y llevarlos a la enseñanza de Dios,
y aunque el sacerdote no era capaz de oponerse,
llevaron a George ante el alcalde y lo amenazaron con enviarlo a la casa de corrección.
Pero tarde en la noche los oficiales y los vigilantes lo sacaron del pueblo.

Con respecto a los asuntos de estado,
ya se ha dicho que Carlos II fue proclamado rey por los escoceses,
pero estando todavía en Holanda,
le enviaron ahí la petición de que aprobara el Pacto Presbiteriano,
y que aboliera el Episcopado en Escocia,
y deseaban que quitara también a ciertos señores de su servicio.
Pero los que fueron enviados,
sólo recibieron del joven Rey una respuesta en términos generales,
que los obligó a regresar a casa, donde los dejaremos,
para ver mientras tanto cómo le estaba yendo a G. Fox,
quien había sido echado de Chesterfield (como se
ha dicho) y había llegado a Derby en 1650.

Ahí se quedó en la casa de un médico,
cuya esposa estaba convencida de la verdad que él predicaba.
Sucedió, que mientras estaba caminando en su habitación, oyó sonar la campana,
y le preguntó a la mujer de la casa por qué había sonado.
Ella le dijo que iba a haber un gran sermón ese día,
y que muchos de los oficiales del ejército, sacerdotes y predicadores iban a estar ahí,
así como también un coronel que era predicador.
Entonces se sintió movido a ir a esa congregación,
y se esperó hasta que terminara el servicio para
hablar lo que él creía que el Señor requería de él;
y las personas se quedaron muy calladas.
Pero llegó un oficial,
lo cogió de la mano y dijo que él y los otros dos que lo acompañaban,
debían ir ante los magistrados.
Cerca de la primera hora de la tarde fueron llevados ante ellos,
y le preguntaron a George por qué había ido ahí, a lo cual,
después de responder que Dios lo había movido a hacerlo, añadió,
que Dios no habitaba en templos hechos con manos, y que todas las predicaciones,
bautismo y sacrificios de ellos no los santificarían jamás,
sino que debían mirar a Cristo en ellos y no a los hombres,
porque Cristo es el que santifica.
Entonces, al ver que ellos hablaban sin cesar,
él les dijo que no debían discutir de Dios ni de Cristo, sino obedecerle.
Pero esta doctrina les desagradó tanto, que a menudo lo metían y sacaban de la sala,
y algunas veces le decían burlonamente que había sido "`atrapado en un éxtasis.`"
Finalmente, le preguntaron si él estaba santificado y él respondió:
"`Sí.`" Le preguntaron si no tenía pecado, a lo cual respondió:
"`Cristo mi Salvador ha quitado mi pecado y en Él no hay pecado.`"
Luego, les preguntaron a él y a sus compañeros cómo sabían que Cristo habitaba en ellos.
G+++.+++ Fox dijo: "`Por Su Espíritu que nos ha dado`"^
footnote:[1 Juan 3:24]. Les preguntaron tentadoramente, si alguno de ellos era Cristo,
pero él respondió: "`No, nosotros no somos nada, Cristo es todo.`"
Por último, le preguntaron: "`Si un hombre roba, ¿no es pecado?`"
A lo que él respondió con las palabras de las Escrituras: "`Toda injusticia es pecado.`"
Y así, cuando se cansaron de interrogarlo,
lo entregaron a él y a otro hombre a la casa correccional en Derby por seis meses,
como "`blasfemos,`" tal como aparece en la siguiente orden judicial.

[.embedded-content-document.letter]
--

[.salutation]
Al Señor de la Casa Correccional en Derby, Saludos.

Le hemos enviado junto con esta orden a George Fox,
de Mansfield en el condado de Nottingham, y John Fretwell,
de Staniesby en el condado de Derby, campesino,
traídos delante de nosotros en el presente día,
y acusados de pronunciar y exponer varias opiniones
blasfemas contra una ley reciente del Parlamento,
los cuales, tras ser interrogados por nosotros, han confesado.
Por tanto, esta orden requiere que usted, inmediatamente después de la vista,
reciba a los mencionados George Fox y John Fretwell bajo su custodia,
y los mantenga de forma segura por un período de seis meses, sin fianza,
o hasta que se encuentre suficiente seguridad de que serán de buen comportamiento,
o sean liberados por una orden de nosotros.
No debe fallar en esto.
Dado bajo nuestras manos y sellos, este día 30 de Octubre, de 1650.

[.signed-section-signature]
Gervas Bennet, Nathaniel Barton.

--

Estando George Fox encerrado, como se ha dicho,
los sacerdotes se levantaron en sus púlpitos para predicar
la inevitabilidad del pecado durante todo el tiempo de vida,
y se esforzaron por persuadir a la gente de que era una doctrina errónea,
afirmar la posibilidad de ser libres del pecado en esta vida,
tal como lo sostenían los "`Cuáqueros.`"
Porque este era el término que entonces era usado (a manera de
insulto) para referirse a G. Fox y a sus compañeros creyentes,
y puesto que este nombre ha continuado desde ese tiempo hasta el presente,
no podemos pasar en silencio su primer surgimiento.
Hasta ese momento,
aquellos que profesaban que la luz de Cristo alumbra
en el corazón del hombre y reprende el pecado,
no eran inapropiadamente llamados Profesantes de la Luz o Hijos de la Luz.
Pero Gervas Bennet,
uno de los jueces de paz que había firmado la ya mencionada orden judicial,
cuando oyó que George Fox le ordenaba a él y a los que estaban a su alrededor que "`temblaran
ante la Palabra del Señor,`" tomó esta importante reprensión con una mente tan despreocupada,
que se aprovechó de la ocasión para desdeñosamente llamar a Fox y a sus amigos "`Cuáqueros`"^
footnote:[La palabra "`cuáquero`" es un anglicismo
que proviene de la palabra inglesa Quaker,
que significa temblar.]. Este nuevo e inusual apelativo fue adoptado con tanto entusiasmo,
y se esparció tan rápidamente entre el pueblo, que no sólo los sacerdotes de ese lugar,
sino los de toda Inglaterra,
no usarían otro nombre para referirse a los Profesantes de la Luz.
Y no se detuvo ahí, el nombre rápidamente alcanzó los países vecinos y reinos adyacentes,
a tal punto, que los mencionados Profesantes de la Luz,
para distinguirlos de otras sociedades religiosas,
han sido llamados por ese nombre en inglés,
aunque suena muy extraño en los oídos de algunas naciones extranjeras,
y ha dado también ocasión para muchas historias tontas.

Ahora bien, en aquellos primeros tiempos,
entre los muchos partidarios de esta persuasión,
había algunos que habían sido anteriormente personas de una vida tosca y viciosa.
Cuando estos fueron aguijoneados en el corazón,
y se arrepintieron verdaderamente con un dolor real por sus anteriores transgresiones,
sucedió que algunos no sólo estallaron en llanto en las reuniones,
sino que también fueron afectados con un asombro mental tan inusual,
que se percibieron temblores en sus cuerpos.
Algunas personas son naturalmente más afectadas por pasiones en la mente que otras,
porque incluso la ira puede afectar a algunos hombres
tan violentamente que los hace temblar,
y otros pueden temblar por temor.
Por tanto, no es de extrañar que algunos fueran golpeados con los terrores de Dios,
de manera tal, que los hicieran temblar.
Pero cuando hombres envidiosos vieron esto,
aprovecharon la ocasión para propagar la mentira de que
los Profesantes de la Luz realizaban su adoración con temblores.
Sin embargo,
ellos mismos nunca han afirmado que el temblor del
cuerpo sea una parte esencial de su religión,
sino que ocasionalmente han dicho lo contrario,
aunque no negaron ser de los que tiemblan delante de Dios,
y no dudaron en decir que todas las personas debían hacerlo;
aunque no buscaban alentar un temblor corporal.

Hemos visto que un tal Fretwell fue entregado con G. Fox a la casa correccional,
pero este hombre no permaneció fiel en su testimonio,
y obtuvo (por mediación del carcelero) el permiso
de la justicia para ir a ver a su madre,
y así consiguió su libertad.
Luego se esparció el relato,
de que él había dicho que G. Fox lo había hechizado y engañado.

Para entonces, George Fox se había convertido en objeto de odio de muchas personas,
pues todos los magistrados,
sacerdotes y profesantes estaban enfurecidos contra él. Y el carcelero,
a fin de encontrar algo con que atraparlo, algunas veces le preguntaba cosas tontas,
tal como,
si la puerta estaba cerrado o no--pensando sacarle una respuesta repentina y sin pensar,
con la que pudiera acusarlo de pecado.
Pero G. Fox se mantuvo muy vigilante y prudente y no pudieron aprovecharse
de él. Poco después de que fue entregado se sintió movido a escribirles
a los sacerdotes y a los magistrados de Derby.

Ahora, ya que G. Croese en el principio de su historia,
presenta a George Fox como una persona totalmente incapaz,
no sólo de escribir legiblemente,
sino también de expresar con claridad su pensamiento por escrito,
y que por eso siempre estaba obligado a emplear a otros
para que expresaran lo que quería decir inteligentemente,
no se sale de mi propósito decir,
que esto es más que de lo que cualquier hombre puede probar.
Porque aunque no puede negarse que él no era un escritor elegante,
ni tenía buena ortografía, es cierto que sus caracteres eran tolerables,
su escritura legible y el tema que trataba era muy inteligente,
aunque su estilo no era como el de un lingüista hábil.
Y aunque a veces sí empleó a otros, porque no era un escritor rápido,
estos eran en general muchachos jóvenes que no se
habrían atrevido a alterar sus palabras ni frases,
ni habrían sido lo suficientemente hábiles como para refinar su estilo.
Esto no lo escribo de oídas, sino que lo he visto varias veces.
Y si es cierto lo que el mismo autor dice,
que la escritura de G. Fox era poco más que una vaga colección de pasajes de las Escrituras,
podrá verse más adelante en esta historia,
en la que el lector encontrará muchos de sus escritos.
La siguiente es la primera de sus cartas que me encuentro,
la que él escribió a los sacerdotes de Derby, desde la casa correccional,
donde ciertamente no tenía la conveniencia de un escriba.

[.embedded-content-document.letter]
--

Oh, amigos, fui enviado para decirles,
que si ustedes hubieran recibido el evangelio gratuitamente,
gratuitamente lo ministrarían, sin dinero o precio;
pero hacen comercio y venta de lo que los profetas y apóstoles han hablado, y por tanto,
corrompen la verdad.
Ustedes son los hombres que "`llevan cautivas a las
mujercillas,`" los que "`siempre están aprendiendo,
y nunca pueden llegar al conocimiento de la verdad.`"
Ustedes tienen "`apariencia de piedad, pero negarán la eficacia de ella.`"
Y así como Janes y Jambres resistieron a Moisés, ustedes resisten la verdad,
al ser "`hombres corruptos de entendimiento,
réprobos en cuanto a la fe,`" pero no continuarán más allá,
porque su necedad será manifestada a todos los hombres, como fue manifestada la de ellos.
Además, el Señor me envió a decirles que Él busca frutos.
Ustedes me preguntaron si la Escritura era mi regla;
pero no es la regla de ustedes para gobernar sus vidas,
sino sólo para hablarla en palabras.
Ustedes son los hombres que viven en placeres, orgullo y liviandad,
en saciedad de pan y abundancia de ociosidad; miren si este no es el pecado de Sodoma.
Lot recibió a los ángeles, pero Sodoma tenía envidia.
Ustedes muestran la naturaleza vana,
y se paran en los pasos de los que crucificaron a mi Salvador
y se burlaron de Él. Ustedes son sus hijos,
porque muestran sus frutos.
Ellos tenían los principales lugares en las asambleas, igual que ustedes.
A ellos les encantaba que los llamaran Rabinos, igual que ustedes.

[.signed-section-signature]
G+++.+++ Fox

--

[.offset]
Lo que escribió a los magistrados que lo enviaron a prisión fue, a este efecto:

[.embedded-content-document.letter]
--

[.salutation]
Amigos,

Me veo forzado, en tierno amor por sus almas,
a escribirles y suplicarles que consideren lo que hacen,
y lo que requieren los mandamientos de Dios.
¿No requiere Él justicia y misericordia,
romper todo yugo y dejar ir libres a los quebrantados?
Pero, ¿quién pide justicia, o ama misericordia, o lucha por la verdad?
¿Acaso no "`se ha vuelto atrás el derecho,
y la justicia permanece lejos`"? ¿Acaso no "`ha tropezado en la plaza la verdad,
y la rectitud no puede entrar`"? ¿No sucede que "`el
que se aparta del mal es hecho presa`"? ¡Oh,
consideren a tiempo lo que hacen y presten atención a quien encarcelan!
Porque los magistrados están puestos para castigar a los
hacedores de maldad y elogiar a los que hacen bien.
Ahora, yo les ruego, a tiempo, que presten atención a lo que hacen,
porque ciertamente el Señor vendrá y pondrá de manifiesto
tanto a los que edifican como lo edificado;
y si es del hombre, fallará, pero si es de Dios, nada lo derrocará. Por tanto,
deseo y oro que ustedes presten atención, y tengan cuidado con lo que hacen,
para que no sean hallados peleando contra Dios.

[.signed-section-signature]
G+++.+++ Fox

--

George Fox, tras haber descargado su consciencia, continuó esperando con paciencia,
dejándole el resultado a Dios.
Y después de un tiempo,
se sintió constreñido a escribirles a los jueces que lo habían metido en prisión,
a fin de colocar sus obras delante de ellos,
y que así pudieran llegar a una debida consideración de las mismas.
Uno de ellos (ya mencionado) era el juez Bennet, el otro, llamado Natanael Barton,
era tanto juez como coronel, y también predicador.
A estos les escribió como sigue:

[.embedded-content-document.letter]
--

[.salutation]
Amigos,

Ustedes hablaron del buen camino antiguo, del que habló el profeta +++[+++Jeremías],
pero los profetas clamaron contra las abominaciones que ustedes defienden.
Si conocieran el poder de Dios, no perseguirían el buen camino.
El que habló del buen camino estaba puesto en el cepo, y el pueblo gritaba,
"`¡Llévenselo y pónganlo en el cepo!,`" por hablar la verdad.
¡Oh, pueblo necio, que tiene ojos pero no ve, oídos pero no oye,
y no tiene entendimiento! "`¿No me temen?, dice el Señor,
¿no tiemblan delante de mi presencia?`"
¡Oh, el orgullo y las abominaciones de ustedes son odiosos ante los ojos de Dios:
Ustedes (que son predicadores) tienen el lugar principal en las
asambleas y son llamados por los hombres '`Maestro,`' como todos
los que se oponían y todavía se oponen a mi Salvador y Hacedor;
y les cierran el reino de los cielos a los hombres, no entran,
ni permiten que otros entren!
Por tanto, ustedes recibirán la más grande condenación,
los que tienen sus lugares y caminan en sus pasos.
Ustedes pueden decir, que si hubieran vivido en los días de los profetas o de Cristo,
no los habrían perseguido; con lo cual, testifican contra sí mismos,
testifican que son hijos de ellos, viendo que persiguen el camino de la verdad hoy.
¡Oh, consideren que hay un juez verdadero,
que le dará a cada uno de ustedes una recompensa según sus obras! ¡Oh,
presten atención de donde están,
ustedes que defienden las abominaciones contra las
que clamaron los verdaderos profetas! ¡Oh,
vengan y siéntense en el polvo! ¡El Señor viene con poder,
y derribará a todos los que están exaltados, para que sólo Él sea exaltado!

--

Habiéndoles escrito en conjunto, después de un tiempo le escribió a cada uno por separado.
Al juez Bennet le escribió así:

[.embedded-content-document.letter]
--

[.salutation]
Amigo,

Tú que profesas a Dios y a Cristo en palabras, examina cómo lo sigues.
Quitar cargas, visitar a los que están en prisión, mostrar misericordia,
cubrir tu propia carne, darle tu pan al hambriento--estos son los mandamientos de Dios.
Aliviar a los huérfanos,
visitar a las viudas en sus aflicciones y guardarte sin
mancha del mundo--esta es la religión pura delante de Dios.
Pero si tú profesas a Cristo y todavía sigues la codicia,
la avaricia y la mentalidad terrenal, lo niegas con tu vida,
te engañas a ti mismo y a otros, y buscas usarlo como un pretexto.
¡Ay de ustedes hombres avaros y hombres ricos,
lloren y aúllen por la miseria que vendrá! ¡Tengan
cuidado de prestarse para la avaricia y la extorsión;
Dios prohíbe estas cosas! ¡Ay del hombre que codicia injusta ganancia,
para poner en alto su nido y cubrirse con prenda sobre prenda! ¡Oh,
no ames lo que Dios prohíbe, porque "`eres esclavo de aquel a quien obedeces,
ya sea del pecado para muerte,
o de la obediencia para justicia`"! Piensa en Lázaro y el hombre rico,
uno hacía cada día banquete con esplendidez, el otro era mendigo.
¡Mira si no eres el hombre rico!
No te engañes, Dios no puede ser burlado.
Las malas conversaciones corrompen las buenas costumbres.
Despierta a justicia, y no peques.

[.signed-section-signature]
G+++.+++ Fox

--

[.offset]
Para el juez Barton sus palabras fueron:

[.embedded-content-document.letter]
--

[.salutation]
Amigo,

Tú que predicas a Cristo y las Escrituras en palabras,
cuando alguien busca vivir según las palabras que has dicho,
y llega a tener la vida de las Escrituras, entonces esos que hablan de las Escrituras,
pero no conducen sus vidas de acuerdo a ellas, persiguen a los que sí lo hacen.
Piensa en los profetas, en Jesucristo y en Sus apóstoles,
y en todos los hombres santos de Dios; lo que ellos hablaron era de la vida,
pero los que no tenían la vida (sino sólo las palabras),
persiguieron y encarcelaron a los que vivían en la vida de la que ellos habían retrocedido.

[.signed-section-signature]
G+++.+++ Fox

--

Ahora, a pesar de que el alcalde de Derby no firmó la orden de la corte,
sí le había tendido una mano al resto para enviar a G. Fox a prisión,
y por eso le escribió de la siguiente manera:

[.embedded-content-document.letter]
--

[.salutation]
Amigo,

Tú estás sentado en un lugar para hacer justicia,
pero al encarcelar mi cuerpo has hecho lo contrario a la justicia, según tu propia ley.
¡Oh, ten cuidado de agradar más a los hombres que a Dios,
porque esa es la forma de los escribas y fariseos;
ellos buscaban la alabanza de los hombres más que la de Dios.
Recuerda quien dijo: "`Fui forastero, y no me recogisteis; estuve en la cárcel,
y no me visitasteis.`"
¡Oh, amigo, tu envidia no es contra mí, sino contra el poder de la verdad!
Yo no tengo envidia hacia ti, sino amor.
¡Oh, ten cuidado de la opresión: "`Porque he aquí, viene el día ardiente como un horno,
y todos los soberbios y todos los que hacen maldad serán estopa;
aquel día que vendrá los abrasará, ha dicho Jehová de los ejércitos,
y no les dejará ni raíz ni rama.`"
Amigo, si el amor de Dios estuviera en ti,
tú amarías la verdad y oirías la verdad hablada, y no encarcelarías injustamente.
El amor de Dios soporta, sufre, no envidia a nadie.
Si el amor de Dios hubiera quebrantado tu corazón, mostrarías misericordia,
pero tú muestras lo que gobierna en ti.
Todo árbol muestra su fruto, tú muestras tus frutos abiertamente.
Porque las borracheras, las palabrotas, el orgullo y la vanidad gobiernan entre ustedes,
desde el maestro hasta el pueblo.
¡Oh, amigo, hay un clamor en tus calles por la misericordia,
el verdadero juicio y la justicia! ¡Opresión, inmisericordia, crueldad, odio, orgullo,
placeres, desenfreno y llenura están en tus calles, pero los pobres no son considerados!
Presta atención: ¡Ay de la corona de orgullo! ¡Ay de los que toman vino en tazones,
mientras que el pobre está listo a perecer! ¡Recuerda a Lázaro y al hombre rico,
uno hacía cada día banquete con esplendidez, el otro era mendigo! ¡Oh, amigo,
considera estas cosas, porque ellas están cerca,
y mira si no estás en el estado del hombre rico!

--

[.offset]
A los de la Corte de Derby les escribió la siguiente exhortación.

[.embedded-content-document.letter]
--

Me siento movido a escribirles, que tengan cuidado de oprimir al pobre en sus cortes,
o de poner cargas pesadas sobre la gente pobre, cargas que ellos no pueden llevar.
Tengan cuidado del juramento falso, o de hacer que la gente jure lo que no pueden cumplir.
El Señor dice que vendrá para juicio, y que será pronto testigo contra los hechiceros,
contra los que juran mentira,
contra los idólatras y contra los que oprimen a la viuda y al huérfano.
Por tanto, presten atención a todas estas cosas rápidamente.
Los juicios del Señor son verdad, todos justos, y Él se deleita en la misericordia.
Así, pues, amen la misericordia, querido pueblo, y consideren el tiempo.

--

[.offset]
A los que hacían sonar la campana de la '`casa del campanario`' en Derby,
llamada San Pedro, les escribió:

[.embedded-content-document.letter]
--

[.salutation]
Amigos,

Tengan cuidado de los placeres y valoren su tiempo ahora mientras lo tienen,
y no lo gasten en placeres o cosas mundanas.
Puede llegar el tiempo en que dirán que tuvieron tiempo, pero ya pasó. Por tanto,
miren el amor de Dios ahora, mientras tienen tiempo,
pues este los lleva a detestar todas las vanidades y placeres mundanos.
¡Oh, piénselo, el tiempo es precioso!
Teman a Dios y regocíjense en Aquel que hizo el cielo y la tierra.

--

Mientras G. Fox estaba en prisión allí,
varios de los profesantes fueron a conversar con él,
y al percibir que iban para abogar por el pecado y la imperfección^
footnote:[Es decir,
para contender por la necesidad de continuar en pecado durante toda esta vida.],
les preguntó si ellos eran creyentes y tenían fe.
Y al decir ellos "`Sí,`" les preguntó: "`¿En quién?`" A lo que respondieron:
"`En Cristo.`"
Entonces les dijo: "`Si ustedes son verdaderos creyentes en Cristo,
han pasado de muerte a vida, y si han pasado de la muerte,
entonces han pasado del pecado que trae la muerte.
Y si su fe es verdadera, les dará victoria sobre el pecado y el diablo,
purificará sus corazones y consciencias (porque la
verdadera fe se guarda en una consciencia pura),
los llevará a agradar a Dios y les dará acceso a Él de nuevo.`"
Pero ellos no podían soportar un lenguaje como este,
porque decían que no podían creer que alguien pudiera
ser libre del pecado en este lado de la tumba.
A esto él respondió: "`Entonces, dejen de hablar de las Escrituras,
de las palabras de hombres santos, cuando ustedes mismos abogan por la impiedad.`"
En otro momento,
otro grupo de profesantes llegó y al descubrir que también abogaban por el pecado,
les preguntó si tenían esperanza.
A lo que ellos respondieron: "`Sí, claro que tenemos esperanza.`"
Entonces les preguntó: "`¿Qué esperanza tienen?
¿Es Cristo en ustedes la esperanza de gloria?
¿Los purifica así como Él es puro?`"
Pero ellos no soportaban oír que él hablara de ser puros aquí, por tanto,
también los exhortó a que dejaran de hablar de las Escrituras,
las cuales eran las palabras de hombres santos.
"`Porque los hombres santos que escribieron las Escrituras,`" les dijo,
"`abogaban por la santidad de corazón, vida y conducta aquí,
pero dado que ustedes abogan por la impureza y el pecado, que son del diablo,
¿qué tienen que ver ustedes con las palabras de esos hombres santos?`"

Entonces, el guarda de la prisión, quien también era un orgulloso profesante de religión,
estaba muy enfurecido contra G. Fox,
y hablaba malvadamente de él. Pero le plació al Señor golpearlo un día,
de modo que estaba bajo gran angustia mental.
Mientras G. Fox caminaba en su cámara, oyó un clamor de dolor,
y quedándose quieto para escuchar, oyó al guarda decirle a su esposa: "`Esposa,
he visto el día del juicio y vi a George allí,
y tenía miedo de él porque le he hecho mucho mal;
he hablado mucho contra él a los ministros, profesantes y jueces,
en tabernas y cervecerías.`" Después de esto, hacia el anochecer,
el guarda subió a la cámara de G. Fox y le dijo: "`He sido como un león contra ti,
pero ahora vengo como un cordero,
y como el carcelero que llegó donde Pablo y Silas temblando.`"
Y deseaba quedarse en la cámara, a lo que G. Fox respondió:
"`Estoy en tu poder y puedes hacer lo que te plazca.`"
Pero el guarda le dijo: "`No, deseo tener tu permiso, y desearía estar siempre contigo,
pero no tenerte como prisionero.`"
G+++.+++ Fox no dispuesto a negarle su deseo, consintió y le permitió quedarse en su cámara.
Entonces el hombre le contó todo lo que había en su corazón,
y le dijo que él creía que era cierto lo que George
había dicho de la verdadera fe y esperanza,
y se preguntaba por qué el hombre que estaba con él no se había mantenido en la verdad;
"`Porque,`" dijo él, "`ese hombre no tenía razón, pero tú eres un hombre honesto.`"
Él también le confesó,
que en los momentos en los que G. Fox le había pedido que lo dejara ir,
para hablarle la palabra del Señor a la gente,
su negativa había puesto el peso de eso sobre él,
de manera que se había encontrado bajo gran angustia,
al sentirse desconcertado y casi perturbado por un tiempo.
La mañana siguiente,
el guarda fue a los jueces y les contó que él y su
casa habían sido atormentados por causa de G. Fox.
A lo que el juez Bennet dijo, que los tormentos estaban sobre ellos también por retenerlo.
Entonces, para deshacerse de él, los jueces le dieron permiso de caminar una milla.
Pero George percibió el propósito de los jueces,
y le dijo al carcelero que si ellos le decían cuán lejos era una milla,
él en algunas ocasiones se tomaría la libertad de caminar;
pues él creía que ellos pensaban que se marcharía, y de hecho,
el carcelero le dijo después que eso era lo que intentaban.
Pero G. Fox le indicó que no tenía en mente obtener su libertad de esa manera.
Entonces permaneció en prisión y fue visitado por la hermana del carcelero,
quien estaba tan afectada por lo que le había dicho,
que bajó y le dijo a su hermano que ese Cuáquero era una persona inocente,
que no hacía mal a nadie, sino sólo bien; y que deseaba que él fuera tratado cortésmente.

Ahora,
ya que por su restricción él no tenía la oportunidad
de viajar para declarar la doctrina de la verdad,
con el fin de descargar su consciencia, escribió el siguiente documento y lo envió,
para abrir el entendimiento de las personas en el camino
de la verdad y dirigirlas al verdadero maestro en ellas.

[.embedded-content-document.letter]
--

El Señor le muestra al hombre sus pensamientos y descubre todas las operaciones
secretas en él. Un hombre puede ser llevado a ver sus malos pensamientos,
su mente dispersa y sus vanas imaginaciones,
y puede esforzarse por mantener los pensamientos bajos y contener su mente,
pero no puede vencerlos, ni mantener su mente internamente vuelta al Señor. Ahora,
en este estado y condición, sométanse al Espíritu del Señor que muestra estas cosas,
y tal sumisión los llevará a esperar en el Señor,
y Aquel que las ha puesto de manifiesto las destruirá. Por tanto,
permanezcan en la fe del Señor Jesucristo (quien es el autor de la verdadera fe) y obedézcanlo,
porque Él descubrirá la raíz de las lujurias,
de los malos pensamientos y de las vanas imaginaciones; y cómo se engendran,
conciben y crecen; y luego, cómo se dan a luz y cómo opera cada miembro malvado.
Él pondrá al descubierto cada semilla a partir de su propia naturaleza y raíz.

Así, pues, atiendan la fe de Cristo y la unción que está en ustedes,
para ser enseñados por ella, la cual descubrirá todo lo que está obrando en ustedes.
En la medida que Él les enseñe, así obedezcan y arrepiéntanse,
de lo contrario no crecerán en la fe, ni en la vida de Cristo,
donde se recibe el amor de Dios.
Ahora bien, el amor engendra amor, su propia naturaleza e imagen,
y cuando la misericordia y la verdad se encuentran, ¡qué alegría hay!
La misericordia triunfa en el juicio,
y el amor y la misericordia soportan el juicio del mundo con paciencia.
Eso que no puede soportar el juicio del mundo, no es el amor de Dios,
porque el amor soporta todas las cosas y está por encima del juicio del mundo,
pues el juicio del mundo es necedad.
Y aunque el juicio y la práctica del mundo es echar toda la inmundicia
del mundo sobre los santos (la inmundicia que está entre ellos mismos),
su juicio es falso.
Las vírgenes castas siguen a Cristo el Cordero, el que quita el pecado del mundo,
pero las que son del espíritu que no es casto,
no seguirán a Cristo el Cordero en Sus pasos,
sino que Lo desobedecerán en Sus mandamientos.
Así, la mente carnal se ocupa de la carne, habla carnalmente y su conocimiento es carnal,
no espiritual; olor de muerte y no del Espíritu de vida.

Algunos hombres tienen la naturaleza de los cerdos; revolcarse en el lodo.
Algunos hombres tienen la naturaleza de los perros; morder tanto a las ovejas,
como morderse unos a otros.
Algunos hombres tienen la naturaleza de los leones; rasgar, devorar y destruir.
Algunos hombres tienen la naturaleza de los lobos;
desgarrar y devorar los corderos y ovejas de Cristo.
Algunos hombres tienen la naturaleza de la serpiente (ese antiguo adversario);
aguijonear y envenenar.
El que tiene oído para oír, oiga y aprenda estas cosas en su interior.
Algunos hombres tienen la naturaleza de otras bestias y criaturas; no les importa nada,
sino las cosas terrenales y visibles, y se alimentan fuera del temor de Dios.
Algunos hombres tienen la naturaleza del caballo;
hacen cabriolas y se jactan en su fuerza, y son rápidos en hacer el mal.
Algunos hombres tienen la naturaleza de los robles altos y robustos;
florecen y se extienden en su sabiduría y fuerza,
y son fuertes en el mal que debe perecer y ser quemado.
Así, el mal es uno en todos, pero obra de muchas maneras.
Cualquier cosa externa a la que la naturaleza del hombre o de la mujer sea adicta,
el maligno se adaptará y satisfará su naturaleza y apetito,
para mantener su mente en sus propias invenciones y en la creación, lejos del Creador.

Por tanto, no permitan que sus mentes se alejen de Dios, porque si lo hacen,
será manchada, envenenada y corrompida; y si la mente se aleja del Señor,
es difícil traerla de nuevo.
Por tanto, tengan cuidado del enemigo y manténganse en la fe de Cristo.
Ocúpense de lo que es eterno e invisible y de Aquel
que es el Creador y Movedor de todas las cosas,
porque "`lo que se ve no fue hecho de cosas visibles`"^
footnote:[Hebreos 11:3 (NBLA)], pues lo visible tapa la vista invisible en ustedes.
Pero en la medida que el Señor (que es invisible),
les revela y derriba la mente carnal en ustedes por medio de Su poder y Espíritu invisibles,
en esa medida las cosas invisibles e inmortales son traídas a la luz en ustedes.
¡Por tanto, ustedes que conocen la luz caminen en la luz!
Porque hay hijos de las tinieblas que hablarán de la luz y de la verdad,
y no caminarán en ellas.
Los hijos de la luz aman la luz y caminan en la luz,
pero los hijos de la tinieblas caminan en las tinieblas y odian la luz.
En ellos las lujurias terrenales y la mente carnal ahogan la semilla de fe,
esto trae opresión sobre la semilla y la muerte se extiende sobre ellos.
Póngale atención al Espíritu puro del Dios eterno,
el cual les enseñará a usar las cosas creadas en su lugar correcto y juzgará el mal.

¡A Ti, oh Dios, sea toda la gloria y la honra,
a Ti que eres Señor de todo lo visible e invisible! ¡A Ti sea toda la alabanza,
a Ti que sacas de lo profundo para llevar a Ti! ¡Oh poderoso Dios,
Tú eres digno de toda gloria!
Porque el Señor que lo creó todo y le da vida y fuerza a todo,
está sobre todo y es misericordioso con todo.
Por tanto, Tú que lo has hecho todo y estás sobre todo,
¡a Ti sea toda gloria! ¡En Ti está mi fuerza, mis refrigerios y vida,
mi gozo y mi alegría, mi regocijo y mi gloria para siempre!
Vivir y caminar en el Espíritu de Dios es gozo, paz y vida;
pero la mente que se dirige hacia la creación, o hacia cualquier cosa visible,
y se aleja del Señor, experimenta muerte.
Entonces, cuando la mente entra en la carne y en la muerte, el acusador se mete,
y la ley del pecado y muerte entra en la carne; seguidamente,
la vida sufre bajo la ley del pecado y muerte, y como resultado, hay angustia y fallas.
Ya que lo bueno es encerrado y la justicia propia colocada en la cima,
el hombre obra en la ley externa, y como no puede justificarse por esa ley,
es condenado por la luz; y no puede salir de este estado,
excepto permaneciendo en la luz, descansando en la misericordia de Dios,
y creyendo en Aquel de quien fluye toda misericordia.
Porque descansar en el Señor Jesús trae paz.

Este es el camino estrecho que conduce a Aquel que es la vida,
pero pocos permanecerán en él. Por tanto,
manténganse en la inocencia y sean obedientes a la fe en Él. Tengan cuidado de
conformarse al mundo y de razonar con '`carne y sangre,`' porque eso trae desobediencia,
y en seguida,
se levantan imaginaciones y cuestionamientos para
atraer la desobediencia a la verdad en Cristo.
Pero la obediencia a la fe destruye las imaginaciones, los cuestionamientos,
los razonamientos y todas las tentaciones en la carne, las bofetadas,
las miradas hacia las cosas externas, y la búsqueda de las cosas del pasado.
No mantenerse en la vida y luz,
y no crucificar la voluntad corrupta por medio del poder de Dios,
hace que la naturaleza del mal crezca en el hombre,
entonces vendrá agobio y el hombre se manchará con esa naturaleza.
Pero el monte de Esaú será asolado y se convertirá en un desierto,
donde yacen los chacales, pero Jacob, el segundo nacimiento,
será fructífero y se levantará. Porque Esaú es odiado y no debe ser señor, pero Jacob,
el segundo nacimiento, el cual es perfecto y sencillo,
será señor porque es amado por Dios.

[.signed-section-signature]
G+++.+++ Fox

--

[.offset]
Casi al mismo tiempo les escribió a sus amigos el siguiente documento:

[.embedded-content-document.letter]
--

¡El Señor es Rey sobre toda la tierra!
Por tanto, todas las personas alaben y glorifiquen a su Rey en verdadera obediencia,
en rectitud y en la belleza de la santidad.
¡Oh, reflexionen,
porque en la verdadera obediencia se conoce al Señor y se recibe
entendimiento de Él! Presten atención y mediten en silencio,
en humildad de mente, y oirán al Señor hablarles en sus mentes.
Su voz es dulce y agradable, Sus ovejas oyen Su voz y no escucharán otra.
Cuando ellas oyen Su voz se regocijan, son obedientes y cantan de gozo.
¡Oh, los corazones de ellas están llenos de triunfo eterno!
Ellas cantan y alaban al eterno Dios de Sión,
y ningún hombre les quitará su gozo jamás. ¡Gloria al Señor Dios para siempre!

--

Debido a que muchos que habían sido convencidos de la verdad,
se desviaron por la persecución que se levantó,
escribió las siguientes líneas para alentar a los fieles:

[.embedded-content-document.letter]
--

¡Vengan, benditos del Señor y regocíjense juntos,
manténganse en unidad y unanimidad de espíritu!
Triunfen sobre el mundo; gócense en el Señor,
reinando sobre el mundo y sobre todas las cosas que alejan de Él, para que en claridad,
justicia, pureza y gozo sean preservados para el Señor. ¡Oh, escuchen,
presten atención al llamado del Señor y salgan del mundo,
y manténganse fuera de él para siempre! ¡Vengan, ustedes los justos,
canten juntos el cántico del Señor, el cántico del Cordero,
el que nadie puede aprender sino los redimidos de la tierra y del mundo!

--

Mientras G. Fox estaba en la casa de corrección en Derby, llegaron a verlo sus parientes,
y dolidos por su encarcelamiento fueron a los jueces
(por cuya orden había sido puesto ahí),
y querían que fuera liberado,
ofreciendo garantía de cien libras (y otros en Derby de cincuenta libras cada uno),
de que él ya no volvería a declarar contra los sacerdotes
ahí. Pero al ser llevado delante de los jueces,
él no consintió en que alguien diera garantía por él,
debido a que él se creía inocente de cualquier mal comportamiento.
Entonces el juez Bennet se levantó furioso,
y cuando G. Fox se arrodilló para orar al Señor para que perdonara al juez,
Bennet corrió hacia él y lo golpeó con ambas manos, gritando: "`¡Llévatelo, carcelero;
llévatelo!`"
Después de lo cual fue llevado nuevamente a la prisión y mantenido ahí,
hasta que expiraran los seis meses de su reclusión. Sin embargo,
ahora él tenía la libertad de caminar una milla,
de lo cual hizo uso cuando sentía la libertad.
Algunas veces iba al mercado y a las calles,
y exhortaba a las personas a que se arrepintieran,
y de vez en cuando visitaba a los prisioneros en sus reuniones
religiosas los Primeros-días. Pero entonces,
al requerir los jueces fianzas por su buen comportamiento,
vino sobre él escribirles de nuevo como sigue:

[.embedded-content-document.letter]
--

[.salutation]
Amigos,

Examinen qué hay en ustedes que encarcela;
examinen quién es la cabeza en ustedes y vean si algo en ustedes no los acusa.
Reflexionen, ustedes deben ser llevados a juicio.
Piensen en Lázaro y el hombre rico, uno hacía cada día banquete con esplendidez,
el otro era mendigo; y viendo que ustedes tienen tiempo ahora, valórenlo,
mientras lo tienen.
¿Ustedes querían que yo les diera garantía de mi buen comportamiento?
Yo ya estoy obligado al buen comportamiento,
y clamo por el buen comportamiento de todas las personas,
para que se vuelvan de las vanidades y placeres, de la opresión,
y de todos los engaños de este mundo;
y llegará el momento en que ustedes lo confesarán. Por tanto,
tengan cuidado con los placeres, engaños y orgullo.
No miren al hombre, sino al Señor; porque Él dice: "`Mirad a mí, y sed salvos,
todos los términos de la tierra.`"

--

[.offset]
No muchos después les escribió de nuevo, diciendo:

[.embedded-content-document.letter]
--

[.salutation]
Amigos,

¿Ustedes querían que yo les diera garantía de mi buen comportamiento,
que no me emborrachara, que no usara palabrotas, ni peleara,
adulterara y cosas semejantes?
El Señor me ha redimido de todas esas cosas,
y el amor de Dios me ha llevado a aborrecer todo libertinaje y vanidad;
¡bendito sea Su nombre!
Los que son borrachos, pendencieros y usan palabras soeces,
tienen su libertad sin ser encarcelados, pero ustedes han puesto su ley sobre mí,
a quien ni ustedes, ni ningún otro, pueden justamente acusar de tales cosas;
¡alabado sea el Señor!
No puedo acudir al hombre por mi libertad, sino sólo al Señor,
quien tiene los corazones de todos los hombres en Su mano.

--

[.offset]
Después de un tiempo, al no encontrar su espíritu libre de ellos,
les escribió de nuevo como sigue:

[.embedded-content-document.letter]
--

[.salutation]
Amigos,

Si supieran quien me envió, me habrían recibido;
porque el Señor me envió para advertirles de las aflicciones que vendrán sobre ustedes,
y para pedirles que acudan al Señor y no al hombre.
Pero cuando les conté mi experiencia, lo que el Señor había hecho por mí,
sus corazones se endurecieron y me mandaron a prisión,
donde me han mantenido muchas semanas.
Si el amor de Dios hubiera quebrantado sus corazones, entonces verían lo que han hecho.
Pero ustedes no me habrían encarcelado, si mi Padre no se los hubiera permitido,
y por Su poder seré liberado, porque Él abre y cierra.
¡A Él sea toda la gloria! ¿De qué manera me he comportado mal,
como para que alguien tenga que dar garantía por mí? Ni las promesas de los hombres,
ni sus garantías, harían ningún bien para guardar mi corazón,
si no tuviera el Guía interno para mantenerme en la vida recta para Dios.
Pero creo en el Señor,
que a través de Su fuerza y poder seré preservado de la impiedad y los deseos mundanos.
La Escritura habla de recibir a los extranjeros, pero ustedes los encarcelan.
Mientras estén en autoridad, tengan cuidado de la opresión y juramentos,
injusticia y regalos o recompensas, porque Dios aborrece esas cosas.
Pero amen la misericordia, el juicio y la justicia verdaderos,
porque en ellos se deleita el Señor. No escribo con odio hacia ustedes,
sino para mantener mi consciencia limpia.
Tengan cuidado de cómo gastan el tiempo.

--

[.offset]
También les escribió de nuevo a los sacerdotes de Derby en esta forma:

[.embedded-content-document.letter]
--

[.salutation]
Amigos,

Ustedes profesan ser los ministros de Jesucristo en palabras,
pero por sus frutos muestran cuál es su ministerio.
Cada árbol muestra su fruto; el ministerio de Jesucristo consiste en misericordia y amor,
liberar a los que están atados,
sacar de la esclavitud y dejar libres a los que están cautivos.
Ahora amigos, si las Escrituras son su regla,
¿dónde está su ejemplo para encarcelar por religión?
¿Tienen algún mandamiento de Cristo para esto?
Si esa vida que profesan estuviera en ustedes,
caminarían en los pasos de aquellos que pronunciaron las palabras de la Escritura.
Pero no es judío el que lo es externamente, cuya alabanza proviene de los hombres,
sino que es judío el que lo es internamente, cuya alabanza proviene de Dios.
Pero si ustedes construyen sobre las palabras de los profetas y apóstoles,
y pervierten sus vidas,
recuerden entonces las aflicciones que Jesucristo habló contra los tales.
Aquellos que hablaron las palabras de los profetas, pero negaron a Cristo,
profesaron un Cristo por venir, pero si ellos Lo hubieran conocido verdaderamente,
no lo habrían crucificado.
Los santos que fueron cambiados por el amor de Dios,
fueron llevados por este a caminar en amor y misericordia,
porque '`el que habita en amor, habita en Dios.`' Pero donde gobiernan la envidia,
el orgullo y el odio,
todavía gobierna la naturaleza del mundo y no la naturaleza de Jesucristo.
No escribo con odio hacia ustedes,
sino sólo para que se pesen y vean cómo pasan su tiempo.

--

Tras haber despejado su consciencia para con los sacerdotes,
no mucho después vino sobre él la inquietud de escribirles de nuevo a los jueces,
lo cual hizo como sigue:

[.embedded-content-document.letter]
--

Me siento movido a advertirles,
que tengan cuidado de darles paso a sus propias voluntades.
Amen la cruz y no satisfagan sus mentes en la carne,
sino valoren su tiempo mientras lo tengan.
Caminen conforme a lo que conocen, en obediencia a Dios,
y entonces no serán condenados por lo que no conocen,
sino únicamente por lo que conocen y no obedecen.
Consideren el tiempo, pésense y vean dónde están y a quién le sirven.
Porque si blasfeman contra Dios y toman Su nombre en vano, si juran y mienten,
si le dan paso a la envidia, odio, codicia, pasiones, placeres, libertad carnal,
o cualquier otro vicio, tengan por seguro entonces, que le sirven al diablo.
Pero si le temen al Señor y le sirven a Él, aborrecerán todas esas cosas.
El que ama a Dios no blasfemará contra Su nombre,
pero donde hay oposición a Dios y se le sirve al diablo,
tal profesión es triste y miserable.
¡Oh, valoren su tiempo y no amen lo que Dios prohíbe: mentira, ira, malicia, envidia,
odio, pasiones, codicia, opresión, glotonería, borracheras,
prostitución y toda injusticia!
Así, pues, reflexionen y no se equivoquen,
"`las malas conversaciones corrompen las buenas costumbres.`"
No se equivoquen, Dios no será burlado con vanas palabras,
porque "`la ira de Dios se revela desde el cielo contra toda impiedad.`"
Por tanto, obedezcan eso que los convence de todo mal y les dice que no deben hacer mal.
Esto los conducirá al arrepentimiento y los mantendrá en el temor del Señor. ¡Oh,
miren las misericordias de Dios y aprécienlas, y no las vuelvan libertinaje! ¡Oh,
vuelvan sus ojos al Señor y no a las cosas terrenales!

--

Además de esto, le escribió la siguiente carta a Natanael Barton,
quien (como se dio a entender antes) era tanto juez como predicador.

[.embedded-content-document.letter]
--

[.salutation]
Amigo,

¡No te escondas ni te tapes!
Hay un Dios que conoce tu corazón y te descubrirá; en verdad, Él ve tu camino.
"`¡Ay de los hijos que se apartan, dice Jehová...para cobijarse con cubierta,
y no de mi espíritu!`"^
footnote:[Isaías 30:1]
¿Actúas contra le ley y luego la desechas?
Tú descuidas la misericordia y el juicio verdadero,
pero mira lo que se habló en contra de los que hacen así. Mi Salvador dijo:
"`Estuve enfermo y en la cárcel, y no Me visitasteis;
tuve hambre y no Me disteis de comer; fui forastero y no Me recogisteis.`"
Y cuando dijeron: "`Señor, ¿cuándo te vimos en la cárcel, y no te servimos?,`" etc.
Él respondió: Por "`cuanto no lo hicisteis a uno de estos más pequeños,
tampoco a Mí lo hicisteis.`"
Amigo, tú me has encarcelado por dar testimonio de la vida y del poder de la verdad,
y sin embargo, profesas ser un ministro de Cristo.
Pero si Cristo te hubiera enviado, sacarías de la prisión y de la esclavitud,
y recogerías al forastero.
Tú has sido descuidado en la tierra, tú has vivido suntuosamente,
y has alimentado tu corazón como en el día de la matanza.
"`Tú le has dado muerte al justo`"^
footnote:[Santiago 5:6]. ¡Oh,
mira donde estás y cómo has pasado tu tiempo! ¡Acuérdate de ti mismo,
y ahora mientras tienes tiempo, valóralo;
no menosprecies la misericordia gratuita de Dios, ni desprecies la paciencia de Dios,
lo cual es para salvación! Ten en cuenta eso en ti
que te convence de pecado y no te deja jurar,
ni mentir, ni tomar el nombre de Dios en vano.
Tú sabes que no debes hacer ninguna de estas cosas,
aunque has aprendido a hacer lo que te condenará. Por tanto,
obedece la luz que te convence del mal,
abandona tus pecados y mira las misericordias de Dios,
y aprecia Su amor al perdonarte hasta ahora.
El Señor dice: "`Mirad a mí, y sed salvos,
todos los términos de la tierra,`" y "`dejaos del hombre,
cuyo aliento está en su nariz.`"
Amigo, valora tu tiempo y examina a quién sirves,
porque "`sois esclavo de aquel a quien obedecéis, sea del pecado para muerte,
o sea de la obediencia para justicia.`"
Si sirves a Dios y le temes, no blasfemarás contra Su nombre, no maldecirás, no jurarás,
ni tomarás Su nombre en vano.
No sigas en pos de placeres, libertades carnales, prostitución, embriaguez, ira, malicia,
venganza, imprudencia, vanidad, orgullo, glotonería, avaricia, opresión, codicia,
bromas tontas y vanas canciones, porque Dios ciertamente prohíbe estas cosas,
junto con toda injusticia.
Si tú profesas fe en Dios, y sin embargo haces alguna de estas cosas,
Lo tomas como un manto y le sirves al diablo.
Reflexiona en tu interior y no ames lo que Dios aborrece.
El que ama a Dios, guarda Sus mandamientos.
El diablo te dirá que es difícil guardar los mandamientos de Dios,
pero fácil guardar los suyos y vivir en toda injusticia e impiedad,
convirtiendo la gracia de Dios en libertinaje.
"`Deje el impío su camino, y vuélvase a Mí,`" dice el Señor,
"`y tendrá de él misericordia.
Vuélvase, ¿por qué habría de morir?,`" dice el Señor. ¡Aúllen, ustedes los grandes,
porque las plagas están siendo derramadas sobre ustedes! ¡Aúllen, ustedes los opresores,
porque la recompensa y la venganza vienen sobre ustedes!
'`¡Ay de los que codiciosamente juntan una casa a otra,
y acercan una heredad a otra, para que el pobre no pueda obtener más terreno,
y ellos puedan habitar solos en medio de la tierra!`'^
footnote:[Isaías 5:8]
Estas cosas han llegado a oídos del Señor de los ejércitos.

--

Ya se ha dicho que en algunas ocasiones, tanto G. Fox como algunos de sus amigos,
fueron movidos a predicar la doctrina de la verdad.
En este año también sucedió que Elizabeth Hooton (de quien ya se ha hecho mención),
a partir de una verdadera experiencia de la obra del Señor en ella,
también fue movida a predicar públicamente el camino de salvación a otros,
siendo la primera mujer predicadora (según he sido informado),
entre los que ya eran generalmente llamados por el nombre Cuáqueros.
Sin embargo, he encontrado en un libro holandés, impreso en Dordt en el año 1647,
llamado [.book-title]#History of the Troubles in England,#
que entre varias otras persuasiones religiosas,
también había mujeres que predicaban en grandes reuniones en Londres,
y que eran escuchadas por muchos con gran satisfacción; de modo que,
la predicación de una mujer no era algo tan novedoso como lo habría sido de otra manera.

Se dice que en el año anterior, algunos Comisionados Escoceses,
tras haber estado con Carlos II en Holanda, regresaron a Escocia, y aunque el Rey,
al principio parecía reacio a consentir el Pacto Presbiteriano,
al no ver otra forma clara para llegar al trono escocés, cambió de opinión. Luego,
dirigiéndose a Escocia,
hizo su entrada a Edimburgo por la puerta donde estaban colgadas las partes descuartizadas^
footnote:[James Graham, conde de Montrose, fue ahorcado, decapitado y descuartizado,
y las partes de su cuerpo clavadas en la puerta de Dundee.]
del Conde de Montrose, que habiendo intentado someter a los escoceses poco antes,
había sido golpeado con sus fuerzas, tomado prisionero y ejecutado.
El joven Rey, que entonces había llegado a Escocia,
parecía dispuesto a cumplir todo lo posible para congraciarse, no sólo con los escoceses,
sino también con los ingleses de ser posible.
Y por esta razón, emitió la siguiente declaración en su corte en Dumfermling,
fechada 16 de Agosto de 1650, el segundo año de su reinado:

[.embedded-content-document.address]
--

Aunque su Majestad, como hijo obediente,
está obligado a honrar la memoria de su padre y a tener en estima la persona de su madre,
desea humillarse y afligirse profundamente delante de Dios,
porque su padre prestó atención a consejos malvados,
se opuso a la Obra de Reforma y a la Liga y Pacto Solemnes (por la que
mucha sangre del pueblo del Señor ha sido derramada en estos reinos),
y también por la idolatría de su madre.

--

Aquí el Rey confesó abiertamente que la casa de su padre era culpable de grandes crímenes,
y claramente indicó que la nación había sido perjudicada
por el comportamiento de su padre,
y parecía prometer enmiendas si llegaba a ser restaurado.
Entre tanto, al ver Inglaterra que era probable que los escoceses avanzaran contra ellos,
el Parlamento le dio órdenes al General Fairfax de ir allí con un ejército.
Pero Fairfax se mostró indispuesto a ir,
principalmente (como se creía) debido al consejo de su esposa,
quien había escuchado el consejo de los predicadores presbiterianos--al
pensar estos que contribuirían a su propio establecimiento,
si los de su propia persuasión en Escocia no se resistían. Pero el Parlamento,
muchos de cuyos miembros eran independientes, no se desanimó,
sino que al ver que Fairfax había renunciado voluntariamente,
resolvió establecer en su lugar a Oliver Cromwell,
como general de las fuerzas de la nación. Una vez hecho esto,
Cromwell fue enviado con un ejército a Escocia y
derrotó a los escoceses no lejos de Edimburgo,
por lo que la ciudad se rindió a él no mucho después.

Ese año nació en Holanda, el 14 del mes llamado Noviembre, William III,
Príncipe de Orange, cuya madre era hija del fallecido Rey Carlos I. Este príncipe,
por un extraño giro de las asuntos humanos, ha sido llevado al trono de Inglaterra,
y al presente, mientras yo escribo esto, es Rey de Gran Bretaña.
