== Capítulo II

[.section-date]
1650--1652

[.chapter-synopsis]
* Convencimiento de un soldado
* Los trabajos de G. Fox en varios lugares
* Injusticia de la pena de muerte por robo
* Cartas de G. Fox a diferentes individuos
* Convencimiento de R. Farnsworth, J. Nayler y W. Dewsbury
* G. Fox predica en varios '`casas del campanario`'
* Varios sacerdotes son convencidos y se convierten en Cuáqueros
* El ejército del rey es derrotado en Worcester
* Convencimiento general
* Crueldad infligida a G. Fox en Patrington
* G. Fox viaja a Nottinghamshire, Lincolnshire y Yorkshire
* Convencimiento de Francis Howgill y John Audland
* Convencimiento de Edward Burrough
* Swarthmore
* Convencimiento de la familia del juez Fell
* Aumento de predicadores entre los Cuáqueros.

Apenas había comenzado el año 1651,
cuando los escoceses decidieron coronar a su nuevo rey a pesar de su derrota,
lo cual hicieron (después de que este juró mantener el Pacto
Presbiteriano) al principio del mes llamado Enero.
Pero dejando esto por ahora, regresemos a George Fox,
a quien dejamos en la casa de corrección en Derby.

Por esta época, un soldado fue adonde él y le dijo,
que después de haber estado en la casa del campanario oyendo al sacerdote,
una angustia extremadamente grande había caído sobre él,
y que luego una voz (que él tomó ser la del Señor) le había dicho:
"`¿Acaso no sabes que mi siervo está en prisión?
Ve a él para pedirle dirección.`" G. Fox le dijo,
refiriéndose a la condición del soldado:
"`Eso que te muestra tus pecados y te aflige por ellos, también te mostrará tu salvación;
porque Aquel que le muestra al hombre su pecado, es el mismo que lo quita.`"
Mientras le hablaba así,
el entendimiento del soldado empezó a abrirse con respecto a la verdad,
y fue consciente de las misericordias de Dios,
lo que lo hizo hablar con valentía en los cuarteles, entre los soldados y otros,
demostrando con las Escrituras lo que él creía que era la verdad.
También decía que su coronel (que yo considero que era Barton),
estaba tan ciego como Nabucodonosor,
por encarcelar al siervo del Señor. Esto encolerizó mucho a su coronel,
y en la batalla de Worcester,
cuando el ejército del rey y el ejército del Parlamento estaban cerca uno del otro,
y dos soldados del rey desafiaron a dos del Parlamento a pelear contra ellos,
el mencionado coronel escogió a este soldado y a otro para responder
al desafío. Y aunque su compañero murió en el encuentro,
él logró hacer retroceder a sus dos enemigos hasta '`un tiro de mosquete`' del pueblo,
sin siquiera disparar una bala, y así regresó victorioso.
Pero después de haber visto la falsedad de los oficiales,
y cuán maravillosamente lo había preservado el Señor,
y habiendo llegado a ser consciente de que pelear era ilícito para un verdadero cristiano),
depuso las armas y empezó a pelear bajo el estandarte del Príncipe de Paz,
al entrar en la guerra espiritual.

Para entonces,
el tiempo de reclusión de G. Fox en la casa de corrección estaba a punto de terminar,
y como se habían levantado muchos soldados nuevos,
los comisionados querían poner a Fox como capitán sobre ellos,
y los soldados gritaban que no querían a nadie más que a él. Entonces,
se le ordenó al guarda de la casa de corrección,
que lo llevara delante de los comisionados y soldados al mercado,
y ahí le ofrecieron el ascenso (como ellos lo llamaban),
preguntándole si él tomaría las armas por la Mancomunidad contra Carlos II. G. Fox,
que nunca había sido un combatiente (aunque es evidente que era audaz y valiente),
les dijo que no podía hacerlo,
porque él sabía muy bien de dónde se levantan todas las guerras (a saber,
de las pasiones de los hombres, según la doctrina del apóstol Santiago),
y que él vivía en la virtud de esa vida y poder que
le quitaban el motivo de todas las guerras.
Los comisionados, para adularlo,
le dijeron que ellos le habían ofrecido el cargo con amor y amabilidad,
debido a su virtud, pero él, no haciendo caso de esas palabras aduladoras, respondió:
"`Si este es el amor y la amabilidad de ustedes, yo los pisoteo bajo mis pies.`"
Esta audaz respuesta rápidamente mostró cuán superficial
era la pretendida amabilidad de ellos,
porque los encolerizó tanto que dijeron: "`¡Llévatelo, carcelero,
y mételo en el calabozo entre los pillos y delincuentes!`"
En consecuencia,
G+++.+++ Fox fue metido en un lugar maloliente e infestado de piojos entre treinta delincuentes,
en el que no había cama, y fue mantenido ahí casi otro medio año,
excepto por los momentos en los que se le permitía caminar en el jardín
(porque ellos creían que él no huiría). Estando en esa repugnante prisión,
se decía entre la gente que él nunca saldría, pero confiando en Dios,
él creía lo contrario, pues el Señor le había mostrado (según lo que él relata),
que él no debía ser movido de ese lugar aún, porque había una obra que debía cumplir.

Mientras tanto, afuera se corrió la voz de que él estaba en el calabozo en Derby,
y sus parientes fueron a verlo de nuevo, pues estaban muy intranquilos por esto,
y pensaban que era una gran vergüenza para ellos que él estuviera en la cárcel.
Además, ser encarcelado por religión era algo extraño en ese tiempo.
Algunos lo consideraban loco, porque sostenía la posibilidad de la pureza,
justicia y perfección en esta vida.
Entre otros que llegaron a verlo, también lo visitó un soldado de Nottingham que le dijo:
"`Tu fe está en un hombre que murió en Jerusalén, y nunca hubo tal cosa.`"
Esto entristeció tanto a G. Fox, que le dijo:
"`¡Qué! ¿Acaso no sufrió Cristo fuera de las puertas
de Jerusalén por los profesantes judíos,
los principales sacerdotes y Pilato?`"
"`No,`" dijo el soldado, "`Él no sufrió allí externamente.`"
Entonces G. Fox le preguntó si no había judíos,
principales sacerdotes y un hombre llamado Pilato, externos.
Esto desconcertó un poco al soldado, de modo que no pudo negarlo.
Entonces George le dijo: "`Tan ciertamente como había un principal sacerdote,
había judíos y estaba Pilato, así de cierto sufrió Cristo allí externamente bajo ellos.`"
Sin embargo, esta imprudente persona insistió en que ninguno de los profetas,
apóstoles u hombres santos de Dios, habían sufrido algo externamente,
sino que todos sus sufrimientos habían sido internos.
Entonces G. Fox citó como ejemplos muchas de las vidas de los profetas y apóstoles,
cómo habían sufrido y en manos de quién habían sufrido,
confundiendo así sus tontas imaginaciones.
Sin embargo, era tal la malicia de algunos en ese tiempo,
que se levantó una calumnia entre el pueblo que decía,
que los Cuáqueros negaban al Cristo que había sufrido y muerto en Jerusalén. Esto,
en realidad, es una evidencia notable de la credulidad de algunas personas,
que confían en cualquier historia (por falsa que sea),
cuando se relaciona con los que han llegado a ser objeto de odio.

Durante el tiempo de su encarcelamiento,
estuvo muy afligido en su mente por la manera en que los magistrados procedían,
debido a que los hombres eran ejecutados por robar ganado, dinero, etc.
Y estaba más angustiado,
porque tales prácticas eran incluso contrarias a la ley de Dios en el antiguo pacto.
Por tanto, les escribió a los jueces la siguiente carta:

[.embedded-content-document.letter]
--

Me siento movido a escribirles,
que tengan cuidado de estar ejecutando hombres por robar ganado, dinero, etc.,
porque los ladrones bajo la ley debían hacer restitución, y si no tenían los medios,
debían ser vendidos por el valor de su robo.
Presten atención a las leyes de Dios en las Escrituras y al Espíritu que las dio,
y dejen que estas sean su regla al ejecutar juicio.
Muestren misericordia, para que puedan recibir misericordia de Dios, el Juez de todos.
Tengan cuidado de estar recibiendo regalos y recompensas, y toda forma de orgullo,
porque Dios prohíbe tales cosas y ellas ciegan los ojos de los sabios.
No escribo para darle libertad al pecado; Dios lo ha prohibido.
Pero escribo para que juzguen según Su ley y para que muestren misericordia,
porque Él se deleita en el juicio verdadero y en la misericordia.
Les ruego que presten atención a estas cosas y que valoren su tiempo ahora que lo tienen,
teman a Dios y sírvanle, pues Él es fuego consumidor.

--

Mientras G. Fox estaba en prisión entre los delincuentes,
lo afligía oír el lenguaje sucio que usaban,
y a menudo los reprendía por sus malas palabras y por el mal comportamiento entre ellos.
De hecho,
muchos estaban asombrados de que se mantuviera tan
protegido en medio de esta malvada compañía,
sin ser contaminado por su conducta,
sino que el temor de Dios prevalecía tanto en su corazón,
que no se le pudo acusar de ninguna mala palabra o acción,
en todo el tiempo que estuvo ahí. Sin embargo,
al ver que era peligroso conversar con este grupo tan corrupto,
expuso ante los jueces lo dañino que era para los
prisioneros permanecer por mucho tiempo en la cárcel,
pues al hablar libremente de sus malas obras, aprendían maldad unos de otros;
y que por tanto, debía hacerse justicia rápida.

Mientras estaba confinado ahí,
había una mujer joven en la cárcel porque le había robado algo de dinero a su señor,
y cuando descubrió que ella iba a ser juzgada por su vida,
les escribió al juez y al jurado con respecto a ella,
mostrándoles cuán contrario era a la ley de Dios ejecutar personas por robo,
y que era un deber obligatorio mostrar misericordia.
Pero a pesar de haberles escrito de esa manera,
ella fue condenada a muerte y se le preparó una tumba.
Tras oír esto, G. Fox le escribió unas pocas palabras a la gente diciendo:
"`Una advertencia para que todas las personas tengan cuidado de la codicia,
teman al Señor y valoren su tiempo mientras lo tienen,
para que así puedan evitar la maldad.`"
Cuando la mujer fue llevada a la ejecución en el tiempo señalado,
él dio este escrito para que fuera leído en la horca.
Y cuando ya estaba en la escalera, con la cara cubierta y lista para ser ahorcada,
fue indultada y regresada de nuevo a prisión, donde después fue convencida de la verdad,
tal como era sostenida por G. Fox y sus amigos.

En la cárcel había también detenido un hombre malvado, del que se decía que era mago.
Este hombre amenazó a G. Fox y al carcelero diciendo,
que levantaría al diablo y derribaría la casa;
y esto hizo que el carcelero tuviera miedo.
Pero G. Fox fue donde él y le dijo: "`Ven, veamos qué puedes hacer.
¡Has lo peor que puedas hacer!
El diablo ya está suficientemente levantado en ti, pero el poder de Dios lo encadena.`"
Ante esta resuelta declaración, el hombre se escabulló.

Ahora bien, a fin de deshacerse de G. Fox, los jueces resolvieron hacerlo un soldado,
y viendo que él no aceptaría voluntariamente una comandancia,
Bennet envió alguaciles para ofrecerle el pago por adelantado.
Pero George les dijo que él había sido sacado de la guerra externa,
y que estaba muerto a ella.
Y aunque los comisionados le ofrecieron una y otra vez dinero, él no lo quiso.
Esto los enfureció tanto, que fue recluido en aislamiento.^
footnote:[Dependiendo de la severidad del crimen (o de otras consideraciones atenuantes),
a los prisioneros a menudo se les otorgaban ciertas
libertades durante su tiempo de encarcelamiento.
A algunos se les permitía continuar en sus oficios, visitar a sus familias,
o caminar a pueblos cercanos para comprar artículos de primera necesidad.
Los "`prisioneros en aislamiento,`" eran despojados de todas esas libertades,
y generalmente, eran confinados a una celda todo el tiempo.]
A raíz de esto,
G+++.+++ Fox les escribió a los jueces y a los que estaban involucrados en su encarcelamiento,
las siguientes líneas:

[.embedded-content-document.letter]
--

Ustedes que están sin Cristo,
y que sin embargo usan las palabras que Él y Sus santos han dicho,
consideren cómo ni Él ni Sus apóstoles encarcelaron a alguien alguna vez.
Mi Salvador es misericordioso incluso con los inmisericordes y rebeldes,
y los saca de la prisión y de la esclavitud.
Sin embargo, los hombres oprimen y aprisionan, cuando la mente carnal gobierna.
Mi Salvador dice: "`Amad a vuestros enemigos...haced bien a los que os aborrecen,
y orad por los que os ultrajan y os persiguen.`"
Porque el amor de Dios no persigue a nadie, sino que ama a todos,
donde quiera que esté. Todo aquel que aborrece a su hermano es un homicida.
Ahora, ustedes profesan ser cristianos, y uno de ustedes es un ministro de Jesucristo,
sin embargo, me han encarcelado y yo soy un siervo de Jesucristo.
Los apóstoles nunca encarcelaron a nadie, más bien ellos fueron encarcelados.
Tengan cuidado de estar hablando de Cristo en palabras y negándolo en vida y poder.
¡Oh, amigos, el encarcelamiento de mi cuerpo es para satisfacer sus voluntades;
pero tengan cuidado de estarles dando paso a sus voluntades,
porque eso les hará daño! Si el amor de Dios hubiera quebrantado sus corazones,
ustedes no me habrían encarcelado; no obstante, mi amor es para ustedes,
como para todos mis prójimos.
Esto ha sido escrito para que ustedes puedan sopesarse y ver cómo están.

--

Por esta época,
entregó el siguiente documento a los que habían sido convencidos de la verdad,
para mostrarles el engaño del mundo, y cómo los sacerdotes habían engañado al pueblo:

[.embedded-content-document.letter]
--

Cristo fue odiado siempre,
y los justos fueron odiados por causa de Él. Examinen quiénes eran los que los odiaban.
"`El que había nacido según la carne perseguía al que había nacido según el Espíritu,
así también ahora.`"
Revisen quiénes eran los principales oponentes de Cristo.
¿Acaso no eran los hombres grandes y eruditos, los principales del pueblo,
los gobernantes y maestros que profesaban la ley y los profetas,
y que decían que buscaban al Cristo?
De hecho, ellos buscaban un Cristo externamente glorioso,
para sostener en alto su propia gloria externa,
pero Cristo habló contra las obras del mundo, contra los sacerdotes, escribas y fariseos,
y contra su profesión hipócrita.
El asalariado es extraño a Cristo, pero los siervos de Jesucristo son hombres libres.

Los falsos maestros siempre ponían cargas sobre el pueblo,
y los verdaderos siervos del Señor hablaban contra ellos.
Jeremías habló contra los asalariados diciendo:
"`Cosa espantosa es hecha en la tierra...¿Qué, pues, haréis cuando llegue el fin?`"
Pues el pueblo y los sacerdotes estaban entregados a la codicia.
Pablo habló contra los que buscaban su propia ganancia a costa del pueblo,
y exhortó a los santos a alejarse de los codiciosos y orgullosos,
quienes amaban los placeres más que a Dios, y tenían '`apariencia de piedad,
pero negaban el poder.`' Y dice:
"`Porque de éstos son los que se meten en las casas y llevan cautivas a las mujercillas,
siempre están aprendiendo, y nunca pueden llegar al conocimiento de la verdad;
hombres corruptos de entendimiento, réprobos en cuanto a la fe;
y de la manera que Janes y Jambres resistieron a Moisés,
así también éstos resisten a la verdad; mas no irán más adelante;
porque su insensatez será manifiesta a todos.`"
Moisés abandonó los honores y placeres que pudo haber disfrutado.

El apóstol vio en su tiempo,
como entraba esta corrupción (la que ahora se ha
extendido sobre el mundo) que tiene forma de piedad,
pero que niega el poder.
Pregúntenle a cualquiera de sus maestros, si es posible vencer las corrupciones y pecados.
Ninguno de ellos lo cree; ellos dicen que en tanto el hombre esté aquí,
debe llevar consigo el cuerpo de pecado.
Y así se mantiene el orgullo, toda injusticia, y ese honor y autoridad que Cristo niega,
aunque hay multitud de maestros, muchísimos maestros,
y una copa de oro llena de abominaciones.
Pablo no predicó por un salario,
sino que trabajó con sus manos para ser ejemplo a todo el que lo sigue.
¡Oh, pueblo, consideren quién es el que sigue a Pablo!
Ahora hay muchos, como dijo el apóstol, que '`se entremeten en lo que no han visto,
vanamente hinchados por su propia mente carnal;`' y como
declaran las Escrituras de algunos de los antiguos,
'`ellos van por el camino de Caín (quien fue un asesino), y por el camino de Balaam,
que codició el salario de la injusticia.`' El profeta Miqueas
también clamó contra los jueces que juzgaban por cohecho,
contra los sacerdotes que enseñaban por precio,
y contra los profetas que profetizaban por dinero, y que aun así,
se apoyaban en el Señor diciendo: "`¿No está el Señor entre nosotros?`"

--

También les escribió una seria exhortación a los magistrados de Derby,
para que consideraran a quienes encarcelaban.

[.embedded-content-document.letter]
--

[.salutation]
Amigos,

Deseo que consideren a tiempo,
que los magistrados están designados para castigar
a los malhechores y elogiar a los que hacen bien.
Pero cuando el Señor les envía Sus mensajeros,
para advertirles de las aflicciones que vendrán sobre ustedes (a menos que se arrepientan),
los persiguen, los meten en prisión y dicen: "`Tenemos una ley,
y por nuestra ley podemos hacerlo.`"
Ustedes en realidad se justifican delante de los hombres, pero Dios conoce sus corazones.
Él no será adorado con sus formas y profesiones externas,
ni con sus espectáculos de religión. Por tanto, ustedes que hablan de Dios,
examinen si están sujetos a Él, porque los que hacen Su voluntad son hijos Suyos.
"`Qué pide Jehová de ti: solamente hacer justicia, y amar misericordia,
y humillarte ante tu Dios,`" y ayudar a las viudas y a los huérfanos;
pero en lugar de esto, ustedes oprimen al pobre.
¿Acaso no juzgan sus jueces por cohecho, y sus sacerdotes enseñan por precio?
Viene el tiempo cuando Aquel que ve todas las cosas, descubrirá todos sus secretos.

Deseo que reflexionen en estas cosas y que escudriñen las Escrituras,
y vean si alguna persona del pueblo de Dios encarceló alguna vez a otra por religión,
aunque ellas fueron encarceladas.
Y deseo que examinen lo que está escrito,
que cuando la iglesia está reunida pueden "`profetizar todos,
uno por uno,`" para que todos puedan oír, todos puedan aprender y todos sean consolados.
Y luego, "`si algo le fuere revelado a otro que estuviere sentado, calle el primero.`"
Así era en la verdadera iglesia y así debe ser.
Pero no es así en las asambleas de ustedes hoy,
porque el que enseña por precio puede hablar y nadie puede contradecirlo.
Además,
observen la libertad que les fue dada a los apóstoles (incluso entre los judíos incrédulos),
cuando después de la lectura de la ley y los profetas,
los principales de la sinagoga les decían: "`Varones hermanos,
si tenéis alguna palabra de exhortación para el pueblo, hablad.`"
Deseo que examinen esto con tranquilidad y no luchen contra el Señor,
porque Él es más fuerte que ustedes.
¡Oh, amigos, pongan estas cosas en el corazón y no las tomen como cosas livianas!
Les escribí en amor, para que se ocupen de la ley de Dios y de sus propias almas,
y para que hagan como hicieron los hombres de Dios.

--

Durante su encarcelamiento ahí, se encontró bajo gran prueba y lucha de espíritu,
debido a la maldad de ese pueblo,
porque aunque algunos habían sido convencidos de la doctrina de la verdad,
en general eran personas endurecidas.
Y viendo que la visitación del amor de Dios pasaba de ellos,
lloró y escribió el siguiente lamento.

[.embedded-content-document.letter]
--

¡Oh, Derby!
Así como corren las aguas cuando se levantan las compuertas,
pasa de ti la visitación del amor de Dios; por tanto, mira dónde estás. ¡Oh, Derby!
Mira cuál es tu fundamento y reflexiona antes de que seas completamente abandonada.
El Señor me movió dos veces a venir y clamar contra el engaño y vanidad que hay en ti,
y a advertirles a todos que miren al Señor y no al hombre.
El ay es contra la corona de orgullo, contra la embriaguez y los vanos placeres,
y contra los que hacen profesión religiosa en palabras,
pero son altivos y arrogantes en mente, y viven en la opresión y la envidia.
¡Oh, Derby!
Tu profesión y predicación apestan delante del Señor. Profesas un sábado en palabras,
y te reúnes vistiéndote con ropa elegante y elevando tu orgullo.
Tus mujeres "`caminan con cuello erguido, y con ojos desvergonzados,`" etc.,
contra lo cual clamó el profeta de antaño. Tus asambleas
son odiosas y una abominación para el Señor,
porque el orgullo es puesto en alto y reverenciado, y la codicia abunda.
El que actúa perversamente es honrado,
de modo que el engaño en uno permite el engaño en otro, y sin embargo,
profesas a Cristo en palabras.
¡Oh, Derby!
Ver cómo es deshonrado Dios en ti, me rompe el corazón.

--

Después de que había escrito esto,
percibió que su encarcelamiento allí no continuaría mucho tiempo más,
porque los magistrados se estaban inquietando más y más por causa de él,
y no podían acordar qué hacer con él. Algunos querían enviarlo
al Parlamento y otros estaban a favor de desterrarlo a Irlanda.
Al principio, lo llamaban engañador y blasfemo, y después,
cuando les sobrevinieron los juicios de Dios,
decían que él era un hombre honesto y justo.
Pero que ellos hablaran bien o mal, no significaba nada para él,
porque una cosa no lo levantaba, ni la otra lo derribaba.
Finalmente, lo sacaron de la cárcel, hacia comienzos del invierno del año 1651,
después de haber sido prisionero en Derby casi un año--seis meses en la casa de corrección,
y el resto del tiempo en la cárcel común y en el calabozo.

Puesto en libertad se fue a Leicestershire, y a medida que avanzaba tenía reuniones,
predicando tan eficazmente que varios fueron convencidos.
Después se fue a Nottinghamshire de nuevo y de ahí a Derbyshire,
donde tras visitar a sus amigos pasó a Yorkshire,
y llegando a Doncaster y a otros lugares, predicó el arrepentimiento.
Después de esto llegó a Balby,
donde Richard Farnsworth y varios otros fueron convencidos por
su predicación. Al llegar luego a las inmediaciones de Wakefield,
James Nayler y William Dewsbury se acercaron a él
y aceptaron la verdad de la doctrina que él sostenía,
y estos tres hombres se convirtieron en ministros del evangelio con el tiempo.
Por cierto,
debo decir que William Dewsbury fue uno de los que
ya habían sido directamente convencidos de la verdad,
como sucedió con G. Fox, y que después de ir a G. Fox,
se encontró en unidad con él. Otro de estos fue George Fox, el más joven,
de quien se hablará más adelante.

Pero regreso al otro George Fox, quien al llegar cerca de Selby, pasó de ahí a Beverly,
donde entró en la '`casa del campanario,`' y después de que terminó el que predicaba,
George Fox le habló a la congregación diciendo,
que ellos debían volverse a Cristo Jesús como su maestro.
Esto causó temor entre la gente y el alcalde habló con él,
pero nadie se metió con él. En la tarde fue a otra
'`casa del campanario,`' a unas dos millas de distancia,
donde después de que el sacerdote terminó, le habló a él y a las personas,
mostrándoles el camino de vida y verdad,
y el verdadero fundamento de la elección y la condenación.
El sacerdote dijo que no podía disputar,
pero G. Fox le dijo que él no había ido a disputar, sino a hablar la verdad,
para que todos pudieran conocer a la única Semilla a quien pertenecía la promesa,
tanto en hombres como en mujeres.
Allí su predicación agradó tanto al auditorio,
que se le pidió que regresara otro día y les predicara,
pero él los encomendó a su maestro Jesucristo, y se fue.

Al día siguiente llegó a Crantsick, a la casa del capitán Pursloe,
quien lo acompañó a la casa del juez Hotham,
y en la conversación con G. Fox le dijo que él había conocido
este principio de luz y vida por más de diez años,
y que estaba contento de que el Señor lo declarara abiertamente entre la gente.
Mientras G. Fox estaba ahí,
una influyente mujer de Beverly llegó a hablar con el mencionado juez de algunos negocios,
y en la conversación ella le contó que el día de reposo anterior (como lo llamó ella),
un ángel o espíritu había llegado a la iglesia en Beverly,
y les había hablado cosas maravillosas de Dios,
para el asombro de todos los que estaban ahí. Y que cuando había terminado se había ido,
y que ellos no sabían de dónde había llegado y hacia dónde se había ido.
Y que eso había asombrado a todos, tanto a sacerdotes como a profesantes,
y a los magistrados del pueblo.
Esto lo contó después el juez Hotham,
y G. Fox le dijo que él era el que había estado ese
día en la '`casa del campanario`' de Beverly,
y había declarado la verdad allí.

El siguiente Primer-día de la semana,
el capitán Pursloe fue donde G. Fox y ambos fueron a la '`casa
del campanario,`' donde G. Fox (cuando el sacerdote había terminado)
les habló tanto al sacerdote como a la gente,
y los dirigió adonde podían encontrar a su maestro, el Señor Jesucristo--es decir,
internamente, en sus corazones.
Su predicación produjo tal efecto,
que algunos recibieron la doctrina de la verdad y continuaron en ella.
En la tarde fue a otra '`casa del campanario,`' aproximadamente a tres millas,
donde predicaba uno que tenía el título de doctor.
Él usó el texto de Isaías 55, "`A todos los sedientos: Venid a las aguas;
y los que no tienen dinero, venid, comprad y comed.
Venid, comprad sin dinero y sin precio, vino y leche.`"
G+++.+++ Fox se quedó hasta que terminó el sacerdote,
y sabiendo muy bien qué tipo de maestro era, se encendió con tal celo que le dijo:
"`¡Baja, engañador!
Le pides a la gente que venga libremente y tome el agua de vida gratuitamente,
y sin embargo, tú les quitas trescientas libras al año. ¿No te sonrojas de vergüenza?
¿Acaso hicieron eso el profeta Isaías y Cristo,
los que dijeron esas palabras y las dieron de gracia^
footnote:[Es decir, gratuitamente.
"`Gratuitamente habéis recibido, gratuitamente dad.`"
(Reina Valera 1602 Purificada)]? ¿No les dijo Cristo a Sus ministros,
quienes fueron enviados a predicar: '`De gracia recibisteis,
dad de gracia`'?`" El sacerdote, asombrado, se alejó rápidamente,
y así le dio a G. Fox tanto tiempo como quería para hablarles a las personas.
Él, entonces, las dirigió a la luz y gracia de Dios,
y al Espíritu de Dios en el interior de ellas,
para que fueran enseñadas e instruidas por Él. Después de descargarse entre las personas,
regresó a la casa del juez Hotham esa noche, quien abrazándolo le dijo:
"`Mi casa es tu casa,`" y también le indicó que él
estaba enormemente contento de la obra del Señor,
y de que Su poder fuera revelado.

De ahí G. Fox atravesó el condado y en la noche llegó a una posada,
donde le preguntó a la mujer de la casa si tenía algo de comida.
Pero como le habló con "`ti`" y "`tú,`" lo miró con extrañeza.
Luego le preguntó si tenía algo de leche, y ella le respondió:
"`No.`" Pero creyendo que ella hablaba falsamente,
y viendo una mantequera en la habitación, pensó en probarla más,
y le preguntó si tenía algo de crema, pero ella dijo que no tenía. Entonces,
un niño pequeño que jugaba junto a la mantequera,
metió las manos en ella y tirando hacia abajo, derramó toda la crema al suelo.
Por tanto, la mujer quedó como mentirosa,
y sorprendida cogió al niño y lo azotó con dureza.
Pero George la reprendió por su mentira, y saliendo de la casa se fue,
y esa noche se acostó en un montón de heno bajo la lluvia y la nieve.
El día siguiente llegó a York, y el Primer-día de la semana fue a la catedral.
Cuando el sacerdote terminó,
dijo que tenía algo del Señor Dios que decirles al sacerdote y a la gente:
"`Entonces;`" dijo uno de los profesantes,
"`habla rápido;`" porque hacía mucho frío. G. Fox les dijo:
"`Esta es la palabra del Señor Dios para ustedes: Ustedes viven en palabras,
pero Dios Todopoderoso busca frutos entre ustedes.`"
Tan pronto como salieron estas palabras de su boca,
fue rápidamente sacado y lanzado por las escaleras.
Pero él se levantó otra vez sin daño y se fue a su alojamiento.
Sin embargo, varias de las personas fueron tan alcanzadas,
que se convencieron de la verdad.

Después de terminar su servicio en York, se fue de ahí,
y el día siguiente llegó a Burraby, y al ir a cierta reunión,
donde también estaba el sacerdote,
tuvo oportunidad de declarar la verdad y muchos fueron convencidos.
El sacerdote mismo confesó la verdad de lo que se había dicho,
aunque él no llegó a vivir por ella.
El día siguiente llegó a Cleveland, donde tuvo una reunión y algunos fueron convencidos.
El Primer-día de la siguiente semana fue a la '`casa
del campanario,`' y cuando el sacerdote terminó,
él dirigió a la gente a su maestro interior, a Cristo Jesús, quien los había comprado.
Entonces, el sacerdote se le acercó y tuvo una pequeña conversación con él,
pero pronto fue silenciado.

De ahí se fue a Stath,
donde tuvo grandes reuniones y muchos recibieron la verdad que él predicaba,
entre quienes estaba Philip Scarth,
un sacerdote que después llegó a ser ministro del evangelio entre los llamados Cuáqueros.
Este pueblo había comenzado a incrementarse en número
en aquellos lugares y realizaba grandes reuniones.
Sucedió ahí, que cierto sacerdote escocés, mientras caminaba con G. Fox,
le hizo muchas preguntas con respecto a la luz y el alma;
y de todas recibió completa respuesta.
Pero después de que se separaron, dicho sacerdote escocés se encontró con Philip Scarth,
y quebrando su bastón contra el suelo dijo enojado:
"`¡Si alguna vez me encuentro con George Fox de nuevo,
tendré su vida o él tendrá la mía!`" Y añadió: "`¡Apuesto mi cabeza,
de que George Fox será derribado en el término de un mes!`"
Sin embargo, lo maravilloso, es que después de algunos años,
este mismo sacerdote escocés llegó a ser parte del pueblo llamado Cuáqueros,
y más tarde G. Fox lo visitó en su casa.
No muy diferente a esta historia, es la de una mujer importante entre los Independientes,
que influenciada por los prejuicios contra G. Fox,
dijo que ella voluntariamente habría ido a verlo colgado.
Pero cuando lo oyó predicar,
fue tan alcanzada y convencida de la verdad que él declaraba,
que llegó a ser parte de sus amigos.
Él a menudo tenía oportunidad de hablar con los sacerdotes, los cuales,
a veces se escondían cuando se enteraban de su llegada;
porque para ellos era algo terrible cuando les decían:
"`El hombre con pantalones de cuero ha llegado.`"
Porque, de hecho, esa era su ropa en aquellos días, no por superstición,
sino porque la ropa de cuero (al ser fuerte),
era adecuada para alguien que viajaba tanto como él.

Al llegar a Malton tuvo grandes reuniones,
pero se consideraba algo extraño que un hombre predicara en casas,
y muchos no se atrevían a asistir por temor a sus parientes.
Por tanto,
a menudo se le pedía que viniera y predicara en las iglesias (como eran
llamadas comúnmente las '`casas del campanario`'). Uno de los sacerdotes,
llamado Boyes (quien había aceptado a G. Fox tanto que lo llamaba hermano),
lo invitó a predicar en su '`casa del campanario,`'
pero G. Fox tenía poca inclinación hacia eso,
porque tanto los sacerdotes como el pueblo, llamaban esos lugares de culto,
"`La Casa de Dios;`" aunque el apóstol les había dicho a los atenienses:
"`Dios no habita en templos hechos con manos.`"
Por eso, él se esforzaba por alejar a las personas de tales supersticiones,
y hacerlas entender que Dios y Cristo debían morar en sus corazones,
para que sus cuerpos pudieran ser hechos templos de Dios.

Sin embargo, una vez entró a la '`casa del campanario`' en Malton,
donde el sacerdote les estaba predicando a no más de once oyentes,
pero después de que en el pueblo se supo que G. Fox estaba ahí, pronto se llenó de gente.
Y cuando el sacerdote terminó,
le pidió al sacerdote que había invitado a George Fox que lo llevara al púlpito,
pero G. Fox le mandó a decir que no había necesidad de subir al púlpito.
El sacerdote, no satisfecho con la negativa, mandó a llamarlo otra vez,
pues quería que él subiera al púlpito: "`Porque,`" dijo él,
"`es un mejor lugar para ser visto por las personas.`"
Pero G. Fox respondió que él podía ser visto y oído suficientemente bien donde estaba,
y que no había ido ahí a apoyar tales lugares, ni los diezmos obligatorios,
ni el comercio religioso.
Esto creó cierto disgusto,
y alguien sugirió que estos eran los falsos profetas
que iban a llegar al final de los tiempos.
Pero ese comentario entristeció a muchas personas, y algunas comenzaron a murmurar.
Con lo cual, G. Fox se subió a un asiento alto y les pidió a todos silencio,
y dado que se había hablado algo acerca de los falsos profetas,
él le expuso a la audiencia la marca de los falsos profetas,
les mostró que ya habían llegado,
y que estaban fuera de los pasos de los verdaderos profetas,
de Cristo y de Sus apóstoles.
También dirigió a las personas a su maestro interno, a Cristo Jesús,
quien los volvería de las tinieblas a la luz.
Y tras haberles aclarado varias Escrituras, los dirigió al Espíritu de Dios en ellos,
por medio del cual podrían llegar a Dios y saber quiénes eran los falsos profetas.
Después de haber tenido mucho tiempo para predicarles a las personas,
se fue sin ninguna molestia.

Después de algún tiempo llegó a Pickering,
donde los jueces realizaban sus sesiones de la corte en la '`casa
del campanario,`' y el juez Robinson era el presidente.
Al mismo tiempo G. Fox tuvo una reunión en la escuela,
donde muchos sacerdotes y profesantes llegaron y le hicieron varias preguntas,
las cuales fueron respondidas a su satisfacción,
de modo que muchas personas (y entre esas,
cuatro jefes de alguaciles) fueron convencidas ese
día. Le fue llevada la noticia al juez Robinson,
de que su sacerdote, a quien él amaba más que al resto, había sido superado y convencido.
Una vez que terminó la reunión se fueron a una posada, y el mencionado sacerdote,
que actuaba muy amablemente, quería pagar la cena de G. Fox,
pero él no se lo permitió. Entonces le ofreció su '`casa del campanario`' para que predicara,
pero George se rehusó, diciéndoles al sacerdote y a las personas,
que él había ido ahí para sacarlos de esas cosas y llevarlos a Cristo.

A la mañana siguiente, fue con los cuatro jefes de alguaciles a visitar al juez Robinson,
quien los recibió en la puerta de su casa de habitación. G. Fox
le dijo que no podía honrarlo con el honor de los hombres,
a lo que el juez dijo que él no lo deseaba.
Luego entraron y G. Fox le habló acerca de la condición
de los falsos profetas y la de los verdaderos profetas,
y también de la elección y de la condenación,
demostrando que la condenación estaba en el primer nacimiento y la elección en el segundo;
porque las promesas de Dios pertenecían al segundo,
y el juicio de Dios estaba contra el primero.
Todo esto le agradó tanto al juez Robinson, que no sólo confesó que era verdad,
sino que cuando otro juez que estaba presente se opuso ligeramente,
le informó de su opinión; y le dijo a G. Fox cuando se separaban:
"`Es muy bueno que ejerzas el don que Dios te ha dado.`"
Luego llevó aparte a los cuatro jefes de alguaciles y quería darles dinero para G. Fox,
diciéndoles: "`Quiero que no se le cobre nada en este condado,`" pero le respondieron,
que ellos mismos no habían logrado que recibiera dinero.
G+++.+++ Fox se fue de ahí y el sacerdote Boyes se fue
con él. Pero este año ya está llegando a su final,
así que echemos un corto vistazo a los asuntos de estado, para ver cómo van.

Ya ha sido mencionado que Carlos II había sido coronado rey por los escoceses,
pero después de que él y sus fuerzas fueron vencidos por Cromwell,
marchó con un nuevo ejército hacia Inglaterra y tomó Worcester sin oposición. No obstante,
en el mes de Septiembre, sus fuerzas fueron tan completamente desbandadas por Cromwell,
que el rey Carlos (para evitar que lo tomaran prisionero después
de la batalla) se escondió en un roble hueco un día entero,
y después, disfrazado como un sirviente y haciéndose llamar William, atravesó el condado,
y escapó de Inglaterra a través de muchos peligros,
y llegó a la costa de Normandía en Francia.

Aquí dejaremos al rey y regresaremos a G. Fox,
quien al llegar con el sacerdote Boyes a un pueblo y oír las campanas sonar,
preguntó para qué sonaban.
Y le dijeron que era para que él predicara en la '`casa
del campanario.`' Cuando llegó a la '`casa del campanario,`'
vio que las personas estaban reunidas en el jardín del lugar,
y el sacerdote que lo acompañaba quería que entrara, pero él dijo que no era necesario.
A las personas les pareció extraño que él no quisiera
entrar en lo que ellos llamaban la casa de Dios,
pero poniéndose de pie en el jardín les declaró,
que él no había ido para sostener sus idolatrados templos, ni sus sacerdotes,
ni sus diezmos, ni sus ceremonias judías ni paganas,
y que el terreno sobre el que se alzaban sus templos,
no era más santo que cualquier otro.
Les dijo que la razón por la que los apóstoles entraban
en las sinagogas y en el templo judío,
era para sacar a las personas de ese templo, de las ofrendas y diezmos,
y de los sacerdotes codiciosos de la época,
y que aquellos que se convertían y creían en Cristo,
después se reunían en casas de habitación. Añadió, que todos los que predicaban a Cristo,
la Palabra de vida, debían predicarlo de gracia,
tal como lo hicieron los apóstoles y como Cristo les mandó;
y que el Señor Dios del cielo y de la tierra lo había enviado a él a predicar de gracia,
y a sacar a las personas de los templos externos hechos con manos, donde no habita Dios,
para que así,
pudieran experimentar sus cuerpos convertidos en templos de Dios y de Cristo.
Además, les dijo que ellos debían dejar todas sus ceremonias supersticiosas,
tradiciones y doctrinas de hombres,
y no atender a los maestros del mundo que tomaban diezmos y salarios altos,
que predicaban por sueldo y profetizaban por dinero,
a quienes ni Dios ni Cristo habían enviado, según su propia confesión;
porque ellos confesaban que nunca habían oído la voz de Dios.
Y que por eso, las personas debían ir al Espíritu y gracia de Dios en ellas mismas,
y a la luz de Jesús en sus propios corazones,
y que así llegarían a experimentar a Cristo (como su maestro
gratuito) trayéndoles salvación y revelándoles las Escrituras.
Esta predicación tuvo tal efecto,
que muchos de ellos declararon que habían sido convencidos de la verdad.

De este lugar se fue a otro pueblo,
y el sacerdote Boyes fue con él. Muchos profesantes acudían a él,
pero él se sentaba en silencio delante de ellos por varias horas;
lo que hizo que a menudo le preguntaran al sacerdote: "`¿Cuándo va a comenzar?
¿Cuándo va a hablar?`"
A esto el sacerdote les respondía:
"`Esperen;`" y les decía que las personas esperaban
en Cristo un largo tiempo antes de que Él hablara.
Entonces, aunque G. Fox, mediante el silencio,
quería que el hambre de palabras de las personas quedara insatisfecha,
finalmente se sentía movido a hablar, y lo hacía tan efectivamente,
que muchos eran alcanzados y había un convencimiento general entre ellos.

Se fue de ahí, y el sacerdote continuó con él, así como varios otros.
Sobre la marcha, algunas personas llamaron al sacerdote y le dijeron: "`Señor Boyes,
te debemos dinero por diezmos, por favor ven y tómalo.`"
Pero él levantando las manos les dijo: "`Tengo suficiente y no voy a recibir nada;
pueden dejárselo;`" y alabó al Señor porque tenía suficiente.
Al fin llegaron a la '`casa del campanario`' de este sacerdote en el páramo,
y entrando delante de George, mantuvo abierta la puerta del púlpito;
pero G. Fox le dijo que no entraría ahí. La '`casa del campanario`' estaba muy adornada,
y él les dijo al sacerdote y a las personas,
que la bestia pintada tenía una casa pintada.
Entonces,
les habló acerca del surgimiento de todas esas casas y de sus formas supersticiosas,
y les dijo, que así como el fin de los apóstoles,
cuando entraban en los templos y sinagogas, no era sostener esas cosas,
sino llevar a las personas a Cristo, la sustancia,
su venida tampoco tenía el propósito de sostener esos templos, sacerdotes y diezmos,
sino sacar a las personas de esas cosas y llevarlas a Cristo, la sustancia.
Además, les declaró cuál era la verdadera adoración, la que Cristo había establecido;
también distinguió a Cristo, el verdadero camino, de todos los falsos caminos,
exponiéndoles las parábolas y volviéndolos de las tinieblas a la luz verdadera,
para que mediante esta, se vieran, vieran sus pecados y vieran a Cristo su Salvador,
y así, creyendo en Él, pudieran ser salvos de sus pecados.

Después de esto se fue a la casa de un tal Birdet, donde tuvo una gran reunión,
y el sacerdote Boyes todavía lo acompañaba,
tras abandonar su '`casa del campanario.`' Luego se devolvió a Crantsick,
al capitán Pursloe y al juez Hotham, que lo recibieron amablemente y contentos,
porque la verdad se había esparcido y muchos la habían recibido.
El juez Hotham dijo:
"`Si Dios no hubiera levantado este principio de luz y vida que predica G. Fox,
la nación habría sido invadida por el Ranterismo,^
footnote:[Los Ranters eran un grupo un tanto extraño e inconformista,
que surgió a mediados de los 1600,
y que recibieron su nombre debido a sus discursos y prácticas extravagantes.
Algunos de ellos parecen haber sido verdaderos buscadores de la verdad,
quienes (en palabras de William Penn) "`no se mantuvieron
en la humildad ni el temor de Dios,
y ante la abundancia de revelación, se exaltaron por encima de la medida;
y por no mantener sus mentes en una humilde dependencia en Aquel
que les abrió el entendimiento para ver grandes cosas en Su ley,
se quedaron en sus propias imaginaciones, y al mezclarlas con esas revelaciones divinas,
dieron a luz un nacimiento monstruoso, para escándalo de los que temían a Dios.`"
Los Ranters a menudo interrumpían las reuniones religiosas establecidas, con gritos,
cantos, tocando instrumentos o haciendo otros ruidos fuertes.]
y ni todos los jueces de la nación, con todas sus leyes, lo habrían podido detener.`"

Ahora, aunque G. Fox encontró buen recibimiento, no se estableció ahí,
sino que se mantuvo en continuo movimiento, yendo de un lugar a otro,
para engendrar almas para Dios.
Yo no intento relatar todo lo que le sucedió,
pero haré una corta mención de lo más importante.

Luego, llegando a Patrington hacia el anochecer, caminó a través del pueblo,
y encontrándose al sacerdote en la calle,
le advirtió a él y a las personas que se arrepintieran y se volvieran
al Señor. Cuando la gente se reunió alrededor de él,
les declaró la palabra de vida, dirigiéndolos a la Palabra interna, es decir,
a la luz con la que ellos eran alumbrados.^
footnote:[Juan 1:9]
Después se fue a una posada (porque estaba oscuro) y pidió alojamiento,
pero se lo negaron, entonces pidió un poco de comida o leche, pero también se lo negaron.
Tras ser rechazado, salió del pueblo y unos tipos rudos que lo seguían le preguntaron:
"`¿Qué noticias hay?`"
Y su respuesta fue:
"`Arrepiéntanse y teman al Señor.`" Después de haber
recorrido una distancia considerable del pueblo,
llegó a otra casa donde pidió algo de comida, bebida y alojamiento por su dinero,
pero no le permitieron quedarse ahí. Entonces, se fue a otra casa,
pero se topó con el mismo rechazo.
Para ese momento había oscurecido tanto, que ya no podía ver el camino,
pero percibiendo que había una zanja,
encontró un poco de agua y se refrescó. Luego cruzó la zanja y como estaba cansado,
se sentó entre unos arbustos de aulaga hasta que se hizo
de día. Cuando se levantó y había atravesado unos campos,
un hombre con un báculo lo alcanzó y lo acompañó a un pueblo,
donde este hombre incitó al pueblo,
al alguacil y al jefe de alguaciles antes de que saliera el sol.
Viendo la multitud,
G+++.+++ Fox les advirtió del día del Señor que venía sobre todo pecado y maldad,
y los exhortó a arrepentirse, pero lo agarraron y lo llevaron de regreso a Patrington,
asegurándolo con alabardas, picos, varas, etc.
Cuando llegaron a dicho pueblo, todo estaba alborotado,
y mientras el sacerdote y los alguaciles se preguntaban qué hacer con él,
G+++.+++ Fox aprovechó la oportunidad para exhortar al pueblo al arrepentimiento,
y para predicarles la palabra de vida.
Por fin, un hombre solícito lo llamó a su casa, donde tomó leche y comió pan,
después de no haber comido por varios días.

Luego lo llevaron donde un juez, a unas nueve millas de distancia,
y cuando estaban cerca de la casa del juez, un hombre se acercó cabalgando,
y le preguntó si él era el hombre que había sido detenido.
G+++.+++ Fox le preguntó: "`¿Por qué?,`" y el otro le dijo:
"`Por ninguna mala intención.`" Entonces, al decirle que era él,
el hombre se alejó cabalgando hacia donde el juez.
Los hombres que custodiaban a G. Fox dijeron:
"`Ojalá que el juez no esté borracho cuando lleguemos donde él, porque por lo general,
está borracho desde temprano.`"
Cuando G. Fox fue llevado delante de él,
y no se quitó el sombrero y le habló de _"`tú,`"_ el juez
le preguntó al hombre que había llegado cabalgando antes,
si G. Fox estaba confundido o loco.
Pero el hombre dijo: "`No,
es principio de él comportarse así.`" Como G. Fox no estaba dispuesto
a dejar pasar una oportunidad sin amonestar a las personas a la virtud,
advirtió al juez a que se arrepintiera,
y le pidió que viniera a la luz con la que Cristo lo había alumbrado,
para que por medio de ella pudiera ver sus malas palabras y obras,
y así se volviera a Cristo Jesús mientras tenía tiempo; el tiempo que él debía valorar.
"`Sí, sí,`" dijo el juez, "`la luz de la que se habla en el tercer capítulo de Juan.`"
G+++.+++ Fox quería que se ocupara de ella y la obedeciera, y entonces,
cuando el juez puso su mano sobre G. Fox,
fue derribado por el poder del Señor y todos los guardas quedaron atónitos.
Entonces el juez se llevó a G. Fox con él a un salón, junto con los otros hombres,
y quería ver qué cartas o informes tenía en sus bolsillos;
pues parece que ellos sospechaban que era un enemigo de la Mancomunidad.
Entonces G. Fox se sacó los bolsillos y mostró que no tenía cartas;
lo que hizo que el juez dijera:
"`Por su ropa veo que él no es un vagabundo,`" y lo puso en libertad.
Después G. Fox regresó a Patrington con el hombre que se había
adelantado cabalgando cuando lo llevaban a ver al juez,
pues vivía en ese pueblo.
Al llegar a su casa, quería que G. Fox se fuera a la cama o se recostara sobre ella,
y él lo hizo para que ellos pudieran decir que lo habían visto en una cama, o sobre una,
pues se había esparcido el tonto rumor, de que él no se recostaba en ninguna cama.
No hay duda de que este rumor se había levantado,
porque en ese tiempo él a menudo pasaba la noche al aire libre.

Cuando llegó el Primer-día de la semana,
fue a la '`casa del campanario`' y les declaró la
doctrina de la Verdad al sacerdote y a las personas,
y no fue maltratado.
Poco después, tuvo una gran reunión en la casa del hombre donde se quedaba,
y muchos fueron convencidos ese día de la verdad que él predicaba,
y estaban extremadamente apenados porque no le habían dado alojamiento,
cuando había estado ahí antes.
De ahí viajó a través del condado,
advirtiéndoles a las personas de los pueblos y aldeas que se arrepintieran,
y se volvieran a Cristo Jesús su maestro.

El Primer-día de la semana fue a la casa de un tal coronel Overton,
y tuvo una gran reunión con la gente principal de ese condado,
en la que les expuso muchas cosas de las Escrituras que ellos nunca habían oído antes.
Al llegar a Patrington de nuevo,
entendió que un sastre y unos jóvenes desalmados de ese pueblo,
habían sido los causantes de que él fuera llevado delante del juez.
Este sastre le pidió perdón,
pues tenía temor de que G. Fox se quejara de él. Los alguaciles
también tenían miedo de que él les causara problemas,
pero él los perdonó a todos y los exhortó a que se
volvieran al Señor y enmendaran sus vidas.
Ahora bien, lo que los hacía tener más temor,
era que no había pasado mucho tiempo en la '`casa del campanario`' en Oram,
cuando un profesante le dio un empujón en el pecho y le dijo: "`¡Sal de la iglesia!`"
A lo que G. Fox respondió: "`¿Llamas a esta '`casa del campanario,`' iglesia?
La iglesia son las personas a quienes Dios ha comprado con Su sangre; no esta casa.`"
Pero al oír el juez Hotham del abuso de este hombre contra G. Fox,
envió una orden judicial y lo obligó legalmente a comparecer a los tribunales.
Este juez estaba tan deseoso de mantener la paz,
que le había preguntado a G. Fox antes si alguna persona lo había maltratado;
pero al estimar su deber perdonar a todos, George no le dijo nada.

De Patrington fue a varias casas de hombres ricos, advirtiéndoles que se arrepintieran;
algunos lo recibieron amablemente y otros lo insultaron.
Recorriendo así el condado,
por la noche llegó a otro pueblo donde quería alojamiento y comida,
ofreciendo pagar por eso;
pero no querían alojarlo a menos que fuera donde el alguacil a pedirle permiso,
lo cual según ellos, era la costumbre con los extranjeros.
Pero él les dijo que esa costumbre era para personas sospechosas de crímenes,
y no para él, que era un hombre inocente.
Y así,
después de exhortarlos al arrepentimiento y a que
le prestaran atención al día de su visitación,
y de dirigirlos a la luz de Cristo y al Espíritu de Dios, se fue.
Cuando oscureció divisó un almiar, y fue y se sentó debajo de él hasta la mañana.
Al día siguiente llegó a Hull, donde amonestó a las personas a volverse a Cristo Jesús,
para que pudieran recibir la salvación. Y como estaba muy cansado por viajar a pie,
consiguió alojamiento ahí esa noche.

De ahí se fue a Nottinghamshire, donde visitó a sus amigos, y luego pasó a Lincolnshire,
e hizo lo mismo.
Y al llegar a Gainsborough,
donde uno de sus amigos había estado predicando en el mercado,
encontró que todo el pueblo y la gente estaban alborotados; en parte,
porque cierto hombre había levantado una falsa acusación,
diciendo que G. Fox había dicho que él era Cristo.
Al entrar en la casa de un hombre amistoso, la gente se apresuró detrás de él,
de modo que la casa pronto se llenó; entre esos estaba el falso acusador,
quien dijo abiertamente delante de todas las personas,
que G. Fox decía que él era Cristo, y que tenía testigos para probarlo.
G+++.+++ Fox se encendió con celo, se paró en la mesa y les dijo a las personas,
que '`Cristo estaba en ellas, a menos que estuvieran reprobadas`'^
footnote:[2 Corintios 13:5], y que él había dicho que era Cristo,
el poder eterno de Dios, el que hablaba en él en ese momento, pero no que él era Cristo.
Esto fue de satisfacción general, excepto para el falso acusador.
Por tanto, G. Fox lo llamó y le dijo que él era un Judas,
y que el fin de Judas sería el de él,
y que esa era la palabra del Señor para él. Las mentes de
las personas se fueron calmando y partieron pacíficamente.
Pero fue muy notable, que poco tiempo después este Judas se ahorcó,
y se clavó una estaca en su tumba.
Ahora, aunque esto fue algo bien conocido en el condado,
algunos sacerdotes esparcieron el rumor de que un cuáquero se había ahorcado en Lincolshire,
y que le habían atravesado una estaca.
Pero esta malvada calumnia prevaleció tan poco,
que muchas personas en Lincolshire fueron convencidas de la verdad predicada por G. Fox.

Después de esto se fue a Yorkshire,
y llegando a Warnsworth fue a la '`casa del campanario,`'
pero no encontró aceptación. Y cuando lo expulsaban,
fue fuertemente golpeado con bastones y le arrojaron terrones de tierra y piedras;
sin embargo, los exhortó al arrepentimiento y a volverse a Cristo.
En la tarde fue a otra '`casa del campanario,`' pero
el sermón terminó antes de que llegara,
así que les predicó del arrepentimiento a las personas que aún no se habían ido,
y las dirigió a su maestro interior, Cristo Jesús. De ahí se fue a Doncaster,
donde él había predicado anteriormente en el mercado,
pero en esa ocasión entró a la '`casa del campanario`' el Primer-día de la semana,
y cuando el sacerdote terminó, él empezó a hablar,
pero fue rápidamente sacado y llevado a rastras delante de los magistrados,
que lo amenazaron de muerte si alguna vez regresaba.
A pesar de todo, G. Fox les exhortó que se ocuparan de la luz de Cristo en ellos,
y les dijo: "`Dios ha venido a enseñar a Su pueblo, ya sea que lo oigan o no.`"
Después de un rato, al ser puestos en la calle él y los amigos que lo acompañaban,
fueron apedreados por la violenta multitud.
Cuando un posadero que además era alguacil vio esto, se acercó y los metió en su casa,
pero una de las piedras alcanzó a George en la cabeza,
de modo que la sangre corría por su rostro.

El siguiente Primer-día G. Fox fue a Tickhill,
donde entró en la '`casa del campanario`' y encontró al
sacerdote y al principal de la parroquia en el presbiterio.
Ellos le cayeron encima tan pronto les comenzó a hablar,
y el clérigo lo golpeó en la cara con su Biblia tan violentamente,
que la sangre le chorreaba sobremanera.
Entonces la gente lo lanzó fuera de la '`casa del campanario,`' golpeándolo,
tirándolo al suelo y arrastrándolo por la calle,
de modo que quedó cubierto de sangre y tierra, y le quitaron el sombrero.
Cuando G. Fox se levantó de nuevo,
les habló a las personas y les mostró cómo deshonraban el Cristianismo.
Un tiempo después,
el sacerdote pasó cerca de una reunión de Amigos y burlonamente los llamó
"`Cuáqueros,`" pero G. Fox estaba hablando con tal autoridad y temor,
que el sacerdote cayó temblando, lo que provocó que una de las personas dijera:
"`¡Miren como tiembla y se sacude el sacerdote, se está convirtiendo en un Cuáquero!`"
Cuando unos jueces sobrios se enteraron de cómo habían
sido insultados G. Fox y sus amigos,
fueron a investigar el asunto.
El clérigo tenía miedo de que le cortaran una mano por haberlo golpeado en la iglesia,
pero G. Fox, como un verdadero cristiano, lo perdonó y no compareció en su contra.

Hasta ahora, G. Fox ha sido el único mencionado como predicador del arrepentimiento,
pero otros de su persuasión empezaron a predicar públicamente también; a saber,
Thomas Aldam, Richard Farnsworth, y poco después William Dewsbury.
Esto causó tal revuelo,
que el sacerdote de Warnsworth obtuvo de los jueces
una orden judicial contra G. Fox y Thomas Aldam.
El alguacil que llegó con dicha orden, cogió a Thomas Aldam y lo llevó a York,
y G. Fox fue con él veinte millas.
Pero aunque el alguacil tenía una orden judicial contra G. Fox también,
no se metió con él, diciendo que no estaba dispuesto a molestar a forasteros,
pero que Thomas Aldam era su vecino.
Por este tiempo,
Richard Farnsworth entró en una muy importante '`casa
del campanario,`' en o cerca de Wakefield,
donde habló tan poderosamente que la gente estaba asombrada.
El sacerdote de ese lugar, cuyo nombre era Marshal,
difundió la calumniosa noticia de que G. Fox llevaba botellas con él,
y que hacía que la gente bebiera de ellas, con lo cual lograba que lo siguieran.
También dijo que cabalgaba sobre un caballo negro,
y que era visto sobre el caballo en un condado,
y al mismo tiempo en otro a sesenta millas.
Pero esas horribles mentiras estaban tan lejos de volverse una ventaja para el sacerdote,
que más bien alejaron a muchos de sus oyentes de él,
pues era bien conocido que G. Fox no tenía caballo en ese momento, y que viajaba a pie.

Después, no lejos de Bradford,
G+++.+++ Fox entró a una '`casa del campanario,`' donde
el sacerdote tomó su texto de Jeremías 5:31,
"`Mi pueblo así le gusta,`" dejando por fuera las palabras anteriores,
"`Los profetas profetizan falsamente, los sacerdotes gobiernan por su cuenta.`"
Al no estar dispuesto a dejar pasar esto desapercibido,
G+++.+++ Fox les mostró a las personas el engaño del sacerdote, y dirigiéndolos a Cristo,
el verdadero maestro interior, les declaró que Dios había venido a enseñar a Su pueblo,
y alejarlo de los maestros y asalariados del mundo,
para que pudiera recibir gratuitamente de Él;
concluyendo su predicación con una advertencia del
día del Señor que venía sobre toda carne.
Se fue de ahí sin mucha oposición,
y por un tiempo viajó con Richard Farnsworth,
con quien una vez había pasado una noche en campo
abierto sobre una cama que habían hecho de helechos.

Luego, después de separarse de R. Farnsworth,
llegó a Wentzerdale y entró en la '`casa del campanario,`' y después del sermón,
le habló a la gente en los mismos términos que solía usar en ocasiones similares,
y no encontró mucha oposición ahí. Así, fue de lugar en lugar,
encontrándose a menudo con sucesos extraños;
pues algunos de sus oyentes eran más tontos que serios, otros muy rudos,
o incluso peligrosos para su vida.
Pero él confiaba en Dios,
creyendo realmente que Dios lo había enviado a predicar arrepentimiento,
y a exhortar a la gente a una verdadera conversión.

Viajando así, llegó cerca de Sedbergh.
Ahí asistió a una reunión en la casa del juez Benson,
donde se reunían personas que se habían separado del culto público.
Su predicación en ese lugar produjo tal complacencia en general,
que la mayoría de los oyentes fueron convencidos
de la Verdad declarada por él. Por tanto,
el número de sus compañeros creyentes se incrementó tanto,
que ya tenían reuniones por sí solos en muchos lugares del condado.

En ese momento se realizaba una feria en Sedbergh,
y G. Fox declaró el día del Señor en toda ella,
y luego se fue al jardín de la '`casa del campanario,`' donde una gran
cantidad de personas se acercaron a él. Ahí predicó por varias horas,
mostrando que el Señor había venido a enseñar a Su pueblo,
y a sacarlo de los caminos y maestros del mundo, para llevarlo a Cristo,
el verdadero maestro, y el verdadero camino a Dios.
Además, les mostró el decadente estado de los sacerdotes y maestros modernos,
y exhortó a las personas a salir de los templos hechos con manos,
y esperar hasta recibir el Espíritu del Señor,
para que pudieran conocerse como los templos de Dios.
Ninguno de los sacerdotes (varios de los cuales estaban
presentes) habló contra lo que él había declarado,
pero un capitán dijo: "`¿Por qué no entras en la iglesia?,
este no es un lugar adecuado para predicar.`"
G+++.+++ Fox le dijo que él no aprobaba su iglesia.
Entonces se puso de pie un tal Francis Howgill, que era un predicador,
y aunque nunca antes había visto a G. Fox, estaba muy afectado por sus palabras,
tanto así, que le respondió al capitán y pronto lo silenció:
"`Este hombre habla con autoridad y no como los escribas.`"
Después de esto,
G+++.+++ Fox les explicó a las personas que el terreno y la casa de esa
edificación no eran más santos que cualquier otro lugar,
y que la casa no era la iglesia, sino las personas, de quien Cristo era la cabeza.
Luego los sacerdotes fueron a él, y él les advirtió que se arrepintieran,
por lo que uno de ellos dijo que estaba loco.
Pero a pesar de lo que dijo, muchos fueron convencidos ese día,
y entre ellos estaba un tal capitán Ward.

El siguiente Primer-día en la mañana, G. Fox llegó a la capilla de Firbank,
en Westmoreland,
donde el mencionado Francis Howgill y un tal John Audland habían estado predicando.
En ese momento la capilla estaba tan llena de personas, que muchos no podían entrar,
y Howgill dijo después,
que había creído que G. Fox se había asomado dentro de la capilla,
y que su espíritu estuvo a punto de desfallecer; pero G. Fox no se asomó. Sin embargo,
Howgill había sido tan alcanzado cuando lo había oído predicar
en el jardín de la '`casa del campanario`' en Sedbergh,
que se sintió, por decirlo así, frenado, y por tanto,
rápidamente le puso fin a su sermón,
pensando (al igual que otros) que G. Fox quería predicar ahí ese día,
como en efecto hizo.
Tras haberse refrescado a mediodía con un poco de agua de un arroyo,
fue y se sentó en lo alto de una gran roca al lado de la capilla,
intentado tener una reunión ahí. Las personas se sorprendieron ante esto,
porque ellos consideraban la llamada '`iglesia`' un lugar santo,
requisito para la adoración. Pero G. Fox les dijo después,
que el terreno sobre el que él estaba era tan bueno
como el de la '`casa del campanario,`' y que además,
Cristo mismo había predicado en una montaña y también a la orilla del mar.

Luego en la tarde, la gente y varios de sus predicadores se reunieron alrededor de él,
entre estos, Francis Howgill y John Audland.
G+++.+++ Fox empezó a predicar ante este auditorio, el cual se estima en más de mil personas,
y les habló cerca de tres horas, dirigiendo a todos al Espíritu de Dios en ellos,
para que así pudieran ser vueltos de las tinieblas a la luz, y del poder de Satanás,
bajo el cual habían estado, a Dios.
Les dijo que por medio de eso podrían convertirse en hijos de la luz,
y podrían ser llevados a toda verdad por el Espíritu de Verdad, y así,
experimentar y entender las palabras de los profetas y apóstoles de Cristo,
y llegar a conocer a Cristo como su maestro para instruirlos,
como su consejero para dirigirlos, como su pastor para alimentarlos,
como su obispo para supervisarlos,
y como su profeta para revelarles los misterios divinos.
Y que de ese modo, sus cuerpos serían preparados,
santificados y hechos templos adecuados para morada de Dios y de Cristo.
Además, explicó los profetas, las figuras y sombras,
y dirigió a sus oyentes a Cristo la sustancia.
También les explicó las parábolas y dichos de Cristo,
y les mostró la intención y alcance de los escritos de los apóstoles,
los cuales son epístolas para los elegidos.
Luego, también les habló del estado de apostasía,
presente desde los días de los apóstoles,
explicando cómo los sacerdotes habían tomado las Escrituras
sin estar en el Espíritu que las había dado,
y cómo eran hallados en los pasos de los falsos profetas,
y de los escribas y fariseos de la antigüedad, contra los que los verdaderos profetas,
Cristo y Sus apóstoles habían declarado; a tal punto,
que nadie que ya era guiado por el Espíritu de Dios podía aceptarlos.

Mientras G. Fox estaba predicando,
muchas personas mayores entraron en la capilla y miraban por las ventanas,
pensando que era algo extraño ver a un hombre predicar en una colina
y no en la llamada '`iglesia.`' Cuando él percibió esto dijo:
"`La '`casa del campanario`' y el terreno sobre el que está,
no son más santos que esta colina, y esos templos,
que son llamados '`las terribles casas de Dios,`' no fueron
establecidos por mandato de Dios ni de Cristo;
ni sus sacerdotes fueron constituidos como lo fue el sacerdocio de Aarón;
ni sus diezmos fueron designados por Dios como lo fueron
aquellos entre los judíos. Pero Cristo ha venido,
y les ha puesto fin al templo y a la adoración, a sus sacerdotes y a sus diezmos,
y por tanto, todos deben oírlo a Él. Porque Cristo dijo:
'`Aprended de mí.`' Y Dios dijo de Él: '`Este es mi Hijo amado,
en quien tengo complacencia;
a él oíd.`'`" En conclusión dijo que el Señor Dios lo había enviado
a predicar entre ellos el evangelio eterno y la Palabra de Vida,
y a sacarlos de todos los templos, diezmos, sacerdotes y rudimentos del mundo,
que habían sido levantados desde los días de los apóstoles,
y que habían sido establecidos por aquellos que se habían desviado
del Espíritu y poder en los que se encontraban los apóstoles.
Así les predicó G. Fox,
y como en ese momento su ministerio estaba acompañado con un poder muy convincente,
y por tanto, alcanzó los corazones de las personas,
muchos (incluyendo a todos los maestros de esa congregación,
que eran muchos) fueron convencidos de la Verdad que les había sido declarada.

Después que terminó la reunión, G. Fox fue a la casa de John Audland,
quien junto con Francis Howgill y otros,
habían sido verdaderamente ganados por su efectiva predicación. Y como
estos habían sido celosos predicadores entre los de su anterior persuasión,
no pasó mucho tiempo,
antes de que se convirtieran en publicadores de la doctrina que habían abrazado,
debido al ministerio de G. Fox.
Y estos estaban tan lejos de aprobar su antiguo servicio,
que devolvieron el dinero que habían recibido por
su predicación en la parroquia de Colton,
en Lancashire, pues habían resuelto dar de gracia lo que habían recibido de gracia.
Aquí haré un pequeño paréntesis,
para decir algo con respecto a estos dos excelentes hombres.

John Audland era un hombre joven, de buen parecer y de muy hermosas cualidades.
Cuando sólo tenía diecisiete o dieciocho años era muy religioso,
y un celoso escudriñador de las Sagradas Escrituras,
y al tener un buen entendimiento y una fuerte memoria,
obtuvo una gran cantidad de conocimiento bíblico,
y se convirtió en un eminente maestro entre los Independientes,
con un auditorio muy numeroso.
Pero cuando escuchó predicar a G. Fox, fue tan alcanzado en el corazón,
que conforme pasaba el tiempo empezó a ver el vacío de su gran conocimiento literal,
y que '`toda su justicia era como trapos de inmundicia.`'
Esto lo llevó a un estado de aflicción,
porque ahora veía que toda su profesión y sabiduría
no podían llevarlo a la verdadera felicidad.
Pero el Señor, que '`no quiebra la caña cascada,
ni apaga el pábilo que humea,`' se apiadó de él en su estado de profunda humillación,
y lo sostuvo una vez más por medio de Su poder,
y con el tiempo llegó a estar preparado para el servicio al que Dios lo había designado.

Por su parte, Francis Howgill también era un hombre religioso, quien,
habiendo visto las supersticiones de la iglesia Episcopal,
la había dejado y se había dedicado a los Independientes.
Pero aunque él había sido formado en la universidad para ser ministro,
y llegó a ser un maestro entre los Independientes, y era celoso en virtud,
todavía se sentía insatisfecho, al descubrir que a pesar de todo su ayuno,
oración y buenas obras,
la raíz del pecado permanecía en él. Y aunque la doctrina común
era que Cristo había tomado la culpa del pecado sobre Sí mismo,
esta no lo satisfacía, porque su consciencia le decía:
"`Sois esclavos de aquel a quien obedecéis.`"^
footnote:[Romanos 6:16]
Al aumentar así en entendimiento,
se le hizo claro que el propio Señor (según lo que
los profetas habían predicho) enseñaría a Su pueblo,
y le pareció además, que ese momento estaba cerca.
Tiempo después, como ya se ha dicho,
sucedió que él estaba presente en una ocasión que G. Fox estaba predicando,
y cuando lo oyó decir que "`la luz de Cristo en el hombre era el
camino a Cristo,`" creyó que esta era la palabra de verdad,
y vio cuán ignorante había sido de la sustancia de la verdadera religión. Entonces,
al someterse a las reprimendas de esa luz interior, vio la inutilidad de toda su labor,
por lo que la angustia y la tristeza se apoderaron de él,
y un juicio cayó sobre todas sus acciones anteriores.
Al rendirse en este estado, diciendo dentro de sí mismo: "`Tu, oh Dios,
eres justo en todos Tus juicios,`" le plació al Señor, a su debido tiempo,
llenar su corazón de gozo y hacerlo ministro de Su Palabra eterna.
Pero apenas entró en ese servicio,
tanto los sacerdotes como los magistrados que lo habían amado antes,
se convirtieron en sus enemigos.
Y era tan grande la envidia que se encendió contra él,
que fue encerrado en un asqueroso lugar en Appleby, en Westmoreland,
y lo mantuvieron prisionero ahí por algún tiempo.

Regresemos ahora a G. Fox, quien al llegar a Kendal,
tuvo una reunión en el ayuntamiento del pueblo.
Ahí declaró la palabra de vida,
mostrándoles a las personas cómo podían llegar al conocimiento salvador de Cristo,
y a tener el entendimiento correcto de las Sagradas Escrituras,
explicándoles qué era eso que los quería conducir
en el camino de la reconciliación con Dios.
Esto tuvo tal efecto, que varios se convencieron de la verdad proclamada por él,
y otros se sentían tan atraídos por él, que cuando se fue a Under-Barrow,
varias personas lo acompañaron.
Tuvo grandes razonamientos con algunas de estas,
especialmente con un tal Edward Burrough, quien,
aunque era un hombre joven de extraordinarias habilidades
naturales y conocimientos adquiridos,
no fue capaz de resistir los eficaces dichos de G. Fox.
Y como este Burrough se convirtió en un eminente hombre entre los llamados Cuáqueros,
al estar dotado de suficiente coraje y entendimiento para vencer a sus opositores,
e incluso, quebrar corazones de piedra,
mencionaré aquí un poco de su origen y cualidades.

Nació en la baronía de Kendal, en Westmoreland,
de padres que tenían una buena reputación por sus vidas honestas y virtuosas.
Fue bien educado y formado en la educación que ese condado ofrecía.
Su conocimiento y entendimiento pronto superaron su edad,
pues siendo sólo un muchacho tenía el espíritu de un hombre,
y en su juventud estaba dotado de sabiduría por encima de sus iguales.
Además, era muy religioso,
y frecuentemente conversaba con los que eran apreciados por la piedad y una vida bondadosa.
No estaba inclinado a los placeres ordinarios de la juventud,
sino que le deleitaba ejercitarse en la lectura de la Sagrada Escritura,
en la que estaba bien versado.
Por sus padres fue formado en el culto Episcopal, sin embargo,
cuando sólo tenía doce años, a menudo iba a las reuniones de los Presbiterianos,
porque su doctrina (en muchas cosas) parecía acercarse más a la verdad,
que la de la iglesia nacional; por lo que se convirtió en seguidor de los Presbiterianos,
aunque era injuriado por sus conocidos.

Cuando tenía casi diecisiete años, y era cada vez más consciente de sus propia condición,
a menudo era golpeado por el terror.
Una vez, cuando estaba orando, oyó, por decirlo así, una voz que le dijo:
"`Tú eres ignorante de Dios; tú no sabes dónde está Él,
ni qué es Él. ¿Para qué sirve tu oración?`" Esto lo llevó a tal preocupación,
que comenzó a prestarle diligente atención a su vida,
por lo que no sólo se abstenía de todas las vanidades,
sino que a veces (cuando se ofrecía la ocasión) reprendía
a otros por su vana conducta y maldad.
Por esta razón era ridiculizado y despreciado por muchos; sin embargo,
él continuó viviendo religiosamente,
y en ocasiones sintiendo dulces refrescamientos en su alma.
Pero aunque tenía la Verdad en su comprensión,
todavía carecía del conocimiento real y por experiencia de esta,
por lo que se volvía a oscurecer y perdía lo que una vez había poseído. Y luego,
siendo demasiado propenso a halagarse, a veces se consolaba con el dicho:
"`Al que Dios ama una vez, lo ama para siempre.`"
Pero se cansó de oír a los sacerdotes,
porque vio que no poseían lo que les hablaban a otros, y con el tiempo,
empezó a cuestionar su propia experiencia.
Tras haber llegado muchas veces a un punto muerto, casi parecía perdido.

En esta condición estaba cuando escuchó a G. Fox predicar,
y después discutió con él. Pero le plació al Señor abrir su entendimiento,
para que percibiera (como lo relata él mismo) que estaba "`en el estado pródigo,
sobre la cruz de Cristo,^
footnote:[Es decir, no bajo ella, soportando su juicio, sino por encima de ella,
pisoteándola.]
y no en el temor puro del Señor.`" Convencido así,
entró en la sociedad de los menospreciados Cuáqueros,
aunque ahora era rechazado por sus parientes,
y por un celo ciego fue echado de la casa de su padre.
Esto lo soportó pacientemente y continuó fiel en la doctrina que había abrazado.
Con el paso del tiempo avanzó tanto en el verdadero conocimiento,
que se convirtió en un eminente ministro del evangelio.
¡Pero, oh, qué adversidades no padeció! Injurias, calumnias, bofetadas,
golpes con una vara fueron a menudo su suerte;
velas y ayunos fueron muchas veces su porción;
y frecuentemente experimentó encarcelamientos, grandes peligros y riesgo de vida.
Pero nada hizo que este campeón se achicara;
siempre fue laborioso y rara vez se tomaba tiempo para descansar.
En su predicación era muy oportuno y elocuente en su discurso,
y tenía la expresión (según lo que un distinguido autor relata,
quien lo conocía desde su juventud) de un docto orador,
capaz de explicarse al entendimiento y consciencia de todos los
hombres con quienes se reunía. También fue un gran escritor,
y muchas veces entabló disputas con los de otras persuasiones,
sin escatimar esfuerzo donde pensaba que podía servirle al Señor y a la iglesia.
Suficiente, por ahora, con respecto a Edward Burrough.

Regresemos ahora a G. Fox, a quien dejamos en Under-Barrow,
donde tuvo una gran reunión en la capilla (con el consentimiento de los habitantes),
y en la que muchos fueron convencidos y recibieron
la verdad predicada por él. De ahí se fue a Lancashire,
y tras hablar en las '`casas del campanario`' de algunos lugares, pasó a Ulverstone,
y luego a Swarthmore, a la casa de Thomas Fell, un juez de Gales,
donde con frecuencia llegaban muchos sacerdotes.
En ese momento el juez estaba fuera, ocupado en el ejercicio de su cargo,
y su esposa Margaret también había salido de la casa ese día. Mientras tanto,
G+++.+++ Fox se reunió ahí con el sacerdote William Lampitt, quien era un orgulloso nocionista^
footnote:[Es decir,
uno cuya religión se mantenía sólo en nociones y opiniones doctrinales.]
y estaba lleno de palabras.
Pero G. Fox pronto percibió que este sacerdote no poseía lo que profesaba,
y se opuso a él valientemente.
Antes de que fuera de noche, Margaret Fell regresó a la casa,
y escuchó de sus hijos que Lampitt y Fox habían discrepado, lo que la molestó un poco,
porque en ese momento ella tenía en gran estima a los sacerdotes,
y admiraba especialmente a Lampitt.
Esa misma noche G. Fox razonó con ellos ahí,
y les declaró la Verdad a ella y a su familia.
Al día siguiente Lampitt regresó, y G. Fox discutió con él en presencia de Margaret Fell,
quien empezó a discernir claramente al sacerdote.

El día siguiente había sido destinado para ayunar,
y Margaret fue con sus hijos a la '`casa del campanario`' en Ulverstone,
habiéndole pedido previamente a G. Fox que fuera con ella.
Pero G. Fox le respondió que él debía hacer lo que le ordenara el Señor,
así que la dejó y caminó hacia los campos,
donde después se sintió fuertemente movido a ir a la '`casa
del campanario.`' Cuando llegó las personas estaban cantando,
pero las palabras que cantaban, según su perspectiva,
eran completamente inapropiadas para sus estados.
Después que terminaron, él se puso de pie sobre una banca y pidió permiso para hablar.
El sacerdote le dio su consentimiento y G. Fox empezó con esta Escritura:
"`Pues no es judío el que lo es exteriormente,
ni es la circuncisión la que se hace exteriormente en la carne;
sino que es judío el que lo es en el interior,
y la circuncisión es la del corazón.`" Y así continuó,
y dijo que Cristo era la luz del mundo y que había
alumbrado a cada hombre que venía a este mundo,^
footnote:[Juan 1:9 (RV160P)]
y que por esa luz ellos podrían ser reunidos con Dios, etc.
Margaret Fell, de pie en su banca, se maravillaba ante esta doctrina,
pues no había escuchado algo así antes.
Mientras tanto G. Fox continuó, y abriendo las Escrituras dijo:
"`Estas son las palabras de los profetas, de Cristo y de los apóstoles;
lo que ellos hablaban también lo disfrutaban y lo poseían,
habiéndolo recibido del Señor. Pero,
¿con qué propósito hablan los hombres de las Escrituras,
si no van al Espíritu que las dio?
Ustedes dirán: '`Cristo dice esto y los apóstoles dicen esto,`' pero,
¿qué puedes decir _tú,_ oh hombre, con respecto a esto?
¿Son ustedes hijos de la luz?
¿Caminan en la luz?
Lo que hablan, ¿lo poseen internamente de parte de Dios?`"

Luego declaró que Dios había venido para enseñar a Su pueblo por medio de Su Espíritu,
y para sacarlos de sus iglesias, de sus religiones y de sus propias formas de adoración, etc.
Estas palabras alcanzaron tan efectivamente a la mencionada Margaret,
que ella se sentó en su banca de nuevo,
y llorando amargamente clamó en su espíritu al Señor diciendo:
"`Todos somos ladrones! ¡Todos somos ladrones!
Hemos tomado las Escrituras en palabras, y no sabemos nada de ellas en nosotros mismos.`"
G+++.+++ Fox continuando, declaró contra los falsos profetas,
y les dijo que su forma de culto no era más que hablar de las palabras de otros hombres,
mientras que ellos mismos estaban fuera de la vida y del
Espíritu en los que estaban aquellos que las dieron.
Entonces un juez de paz llamado John Sawrey gritó: "`¡Sáquenlo!`"
Pero Margaret Fell les dijo a los oficiales:
"`¡Déjenlo en paz! ¿Por qué no puede hablar él también como cualquier otro?`"
El sacerdote Lampitt (probablemente para agradarla) dijo: "`¡Déjenlo hablar!`"
Luego de hablar un rato, G. Fox fue finalmente sacado por los alguaciles,
de acuerdo con la orden del juez Sawyer;
y entonces les habló a las personas en el cementerio.

En la noche llegó de nuevo a la casa del juez Fell,
donde aprovechó la oportunidad de hablarles a los sirvientes y a los de la familia,
la mayoría de los cuales fueron tan efectivamente convencidos por él,
que abrazaron la Verdad que él predicaba.
Entre estos también estaba William Caton, de quien diremos más en lo sucesivo.
Margaret Fell, que en el interín había regresado a la casa, estaba tan impactada,
que escasamente sabía qué hacer con su esposo que estaba fuera de la casa,
porque ella claramente percibía que lo que G. Fox predicaba, era verdad.

El siguiente Primer-día, G. Fox fue a la '`casa del campanario`' en Aldenham,
donde después que el sacerdote terminó,
les habló a las personas y las amonestó para que
regresaran al Señor. De ahí se fue a Ramside,
donde había una capilla en la que un tal Thomas Lawson
(que era un distinguido sacerdote) solía predicar.
Al darse cuenta de la llegada de G. Fox,
Lawson predicó en la mañana y le dijo a la gente que G. Fox iba a llegar en la tarde,
por lo que muchas personas se reunieron.
Cuando llegó,
vio que no había un lugar más conveniente para hablar con la gente que la capilla,
y por tanto, entró. El sacerdote Lawson, dispuesto a darle completa oportunidad a G. Fox,
no subió al púlpito, sino que le cedió todo el tiempo.
G+++.+++ Fox declaró la doctrina de la Verdad tan poderosamente, que muchos la recibieron,
entre ellos el propio sacerdote, quien dejó de predicar por un salario,
y con el paso del tiempo,
llegó a predicar gratuitamente al Señor Jesucristo y Su glorioso evangelio.
Esto, sin embargo, no le impidió ejercitarse en el conocimiento de las plantas,
en el que llegó a ser tan experimentado, que era, como se ha dicho,
uno de los más hábiles botánicos en Inglaterra.

Ahora regreso a G. Fox,
quien después de haber realizado su servicio en los alrededores de Ramside,
llegó a Briercliffe,
donde encontró algunas personas que le dijeron que ellas no podían
disputar con él. Pero él les mandó que temieran al Señor,
y que no hablaran las palabras de Dios de manera frívola,
sino que hicieran las cosas requeridas por Él. Además,
les dijo que ellas debían ocuparse de la luz de Cristo,
y prestarle atención a Su Espíritu en sus corazones, mediante lo cual,
verían sus pensamientos, palabras y acciones perversas.
Porque esta luz (les dijo) les mostraría sus pecados, y al seguirla,
también verían que su Salvador Cristo Jesús podía salvarlas del pecado.
Dijo, que el primer paso hacia la paz era quedarse quietas en la luz,
la cual les mostraría sus pecados y transgresiones.
Que por medio de esta, ellas verían que estaban en la caída del viejo Adán,
en tinieblas y muerte, ajenos del pacto de la promesa y sin Dios en el mundo;
que así verían que Cristo, quien había muerto por ellas,
era su Salvador y Redentor y su camino al Padre.
Después de que G. Fox dijo estas cosas,
se fue a una capilla recién construida cerca de Gleaston,
en la que nadie había predicado aún. Ahí llegó una gran cantidad de personas,
a quienes les predicó y muchas fueron convencidas.

De ahí regresó a Swarthmore nuevamente, porque Margaret Fell,
que estaba llena de temor y esperando que su esposo regresara a casa,
deseaba que G. Fox llegara.
Pues algunas de las personas influyentes de ese condado,
tras haberse reunido con su esposo,
le habían informado que un gran desastre le había sucedido a la familia,
y que los Cuáqueros, quienes eran brujos, los habían desviado de su religión,
y que él debía llegar y enviarlos lejos,
o todo el condado se arruinaría. Sin ninguna duda,
este fue un mensaje muy difícil para el juez Fell, y llegó a la casa muy molesto.
Uno puede fácilmente imaginar en qué condición se encontraba su esposa,
al estar temerosa de disgustar a su esposo u ofender a Dios.

En ese momento Richard Farnsworth y James Nayler estaban en su casa,
y ella quería que ellos le hablaran a su esposo,
lo cual hicieron muy moderada y sabiamente.
Y aunque al principio el juez estaba disgustado,
después de escucharlos hablar estaba más satisfecho.
Viendo que ellos hacían preparativos para irse, ella les pidió que se quedaran,
porque esperaba a G. Fox esa noche,
y quería una oportunidad en la que tanto G. Fox como R. Farnsworth y J.
Nayler le hablaran a su esposo y lo persuadieran más de sus principios.
Una vez preparada la cena, el juez Fell y su esposa Margaret se sentaron a la mesa,
y mientras estaban sentados,
un extraordinario poder embargó a Margaret y obró tanto sobre su mente,
que el juez estaba impactado de asombro y no sabía qué pensar de eso.
Pero él permaneció callado y tranquilo, y los niños se quedaron tan serios y quietos,
que no pudieron tocar los instrumentos musicales que estaban aprendiendo.

G+++.+++ Fox llegó en la noche,
y Margaret le preguntó al juez Fell que estaba sentado en el salón,
si podía entrar y el juez respondió que sí. Entonces George
entró sin ningún cumplido y luego comenzó a hablar,
ante lo cual toda la familia (junto con James Nayler y Richard
Farnsworth) entró en la habitación. Hablando con ellos,
les declaró cuál era la práctica de Cristo y sus apóstoles en sus días,
les mostró cómo había entrado la apostasía desde entonces,
y cuál era la práctica de los sacerdotes modernos en la apostasía.
También le respondió al juez Fell todas las objeciones,
y lo satisfizo tan completamente con las Escrituras,
que el juez quedó convencido en su entendimiento.
Luego le preguntó si él era el mismo George Fox,
a quien el juez Robinson había elogiado tanto entre muchos de los hombres del Parlamento.
G+++.+++ Fox le respondió, que él había estado con los jueces Robinson y Hotham en Yorkshire,
y que habían sido muy corteses y amables con él;
que ellos habían sido convencidos en sus entendimientos por el Espíritu de Dios,
de que la luz de la que él daba testimonio era la Verdad,
y que ellos habían visto más allá de lo que habían visto los sacerdotes
de la nación. Todo esto satisfizo tanto al juez Fell,
que se quedó muy callado esa noche y se fue a la cama.

La mañana siguiente, Lampitt, el sacerdote de Ulverstone,
llegó a la casa y caminando con el juez en el jardín,
le habló mucho para hacerle odiosa la doctrina de los Cuáqueros,
después de haberles dicho a otros también,
que G. Fox sostenía conceptos extraños. Pero el juez
Fell había visto tanto la noche anterior,
que el sacerdote tuvo poca aceptación. Cuando Lampitt entró en la casa de nuevo,
G+++.+++ Fox le habló fuertemente y le preguntó cuándo le había
hablado Dios y lo había llamado a predicarle a la gente.
Al sacerdote no le gustaron las preguntas y en poco tiempo se marchó. Mientras tanto,
algunos estaban hablando de cuántas personas habían sido
convencidas de la Verdad declarada en esos lugares,
y de que no sabían dónde conseguir un lugar para reunirse,
entonces el juez Fell les propuso por su propia voluntad: "`Se pueden reunir en mi sala,
si lo desean.`"
Así, el siguiente Primer-día hubo una reunión en su casa, una muy grande;
esta fue la primera reunión del pueblo llamado Cuáqueros en Swarthmore,
la cual se realizó allí hasta el año 1690,
cuando se construyó una nueva casa de reuniones ahí. El juez Fell,
al no estar dispuesto a ser visto en esta reunión,
ese día se fue a la '`casa del campanario,`' y nadie
fue con él sino su secretario y su mozo de cuadra.
Sin embargo,
con el paso del tiempo llegó a estar tan favorablemente
inclinado a la doctrina de los llamados Cuáqueros,
que, aunque no entró públicamente en su sociedad, los amaba,
y varios años antes de su muerte dejó de frecuentar la '`casa de campanario.`"

Después de quedarse unos días en la casa del juez Fell,
G+++.+++ Fox se fue a Lancaster y ahí predicó en el mercado.
El siguiente Primer-día tuvo una gran reunión en la calle entre los soldados,
a quienes les declaró la Verdad,
y en la tarde fue a la '`casa del campanario,`' pero mientras
hablaba y dirigía a las personas al Espíritu de Dios,
fue sacado y apedreado por la calle.

Luego de viajar por algún tiempo y de predicar en
algunos lugares (a veces con ruda oposición),
regresó a Swarthmore, donde,
en una discusión con varios sacerdotes en la casa del juez Fell,
G+++.+++ Fox les preguntó si alguno de ellos había escuchado
alguna vez la voz de Dios o de Cristo,
mandándoles ir y declararles la palabra del Señor a las personas.
Ninguno de ellos respondió afirmativamente, sin embargo, uno dijo:
"`Yo puedo hablar de mi experiencia tanto como tú.`"
Pero G. Fox le dijo que una cosa era la experiencia,
y otra muy distinta,
ir con un mensaje y tener la palabra del Señor como la tenían los profetas y apóstoles.
Entonces, un anciano sacerdote, cuyo nombre era Thomas Taylor,
francamente confesó delante del juez Fell, que él nunca había oído la voz de Dios,
ni la de Cristo, pero que él hablaba de sus propias experiencias,
y de las experiencias de los santos en épocas anteriores.
Esto confirmó aún más al juez Fell, en la opinión que ya se había formado,
que los sacerdotes no eran lo que pretendían ser,
pues él anteriormente pensaba (como la generalidad del pueblo lo
hacía) que los sacerdotes de esos días eran enviados por Dios.
En ese momento,
las palabras de G. Fox operaron tan profundamente en el mencionado Thomas Taylor,
que fue convencido y viajó con él a Westmoreland.
Al entrar a la '`casa del campanario`' de Crossland, la boca de T. Taylor fue abierta,
de modo que declaró entre la gente cómo había sido él antes de ser convencido,
y al igual que un escriba docto, sacó cosas nuevas y viejas de su tesoro,
y les mostró a las personas la manera en que los
sacerdotes estaban fuera del camino correcto.

Entonces una gran ira se levantó entre los sacerdotes,
y comenzaron a provocar persecución tanto como podían,
pues no sólo Thomas Taylor empezó a predicar el evangelio gratuitamente,
sino que varios otros, a saber, John Audland, Francis Howgill, John Camm,
Edward Burrough, Richard Hubberthorn, Miles Halhead y otros,
aparecieron como celosos predicadores entre los llamados Cuáqueros,
declarando a menudo en las '`casas del campanario`' y mercados la doctrina que profesaban;
por lo que el número de los amigos empezó a aumentar considerablemente.
