== Capítulo III

[.section-date]
1652--1654

Mientras tanto, G. Fox regresó a Lancashire y fue a Ulverstone,
donde Lampitt (antes mencionado) era sacerdote.
Entonces,
viendo él que el pueblo llamado Cuáqueros había establecido
reuniones y que las realizaban en casas privadas,
dijo que ellos habían abandonado el templo,
e iban en pos de las casas de los becerros de oro de Jeroboam;
aunque anteriormente había predicado de un pueblo por venir,
que aceptaría las enseñanzas de Dios,
y que tanto hombres como mujeres declararían el evangelio.
G+++.+++ Fox le dijo que las casas enormes y antiguas^
footnote:[Construidas y usadas en primer lugar por la Iglesia Católica Romana.]
(que ellos llamaban iglesias) eran más parecidas a las casas de
los becerros de Jeroboam (aunque los hombres se esforzaran por
persuadir a la gente de que esos edificios eran la casa de Dios),
considerando que Cristo es la cabeza de la iglesia,
y que nunca fue llamado '`cabeza de una casa vieja,`'
y que el apóstol hablando de Cristo dijo:
"`La cual casa somos nosotros.`"^
footnote:[Hebreos 3:6]
Esto me recuerda cómo algunos soldados del Parlamento,
observando las palabras del patriarca Jacob sobre las puertas de algunas
'`casas del campanario,`' cuando Dios se le había aparecido en sueños:
"`Este lugar no es otra cosa que casa de Dios,
y puerta del cielo,`" no pudieron soportar ver ese
burdo engaño escrito sobre estos edificios,
y por tanto,
borraron las palabras "`de Dios`" y "`del cielo,`" de modo que sólo quedaron:
"`Este lugar no es otra cosa que la casa,
y esta es la puerta.`" Ciertamente,
el celo de estos hombres fue más razonable que la imaginación de aquellos que piensan,
que en los días del evangelio un edificio de cal
y piedra debería ser llamado la casa de Dios.
También parece una práctica tonta llamar a una casa provista de campanario '`iglesia,`'
pero negarle el nombre a las casas donde se congregan los disidentes,
llamándolas sólo por el nombre de '`casas de reunión.`' Sin embargo,
este engaño ha mantenido la estima de esas enormes casas y la de los sacerdotes.
Y para no perder ganancia en los entierros,
ellos se han esforzado por mantener a la gente en la creencia
de que el terreno de esos edificios es santo;
todo lo cual le dio al pueblo llamado Cuáqueros motivo para llamar esos edificios,
'`casas del campanario.`'

Al llegar G. Fox a la '`casa del campanario`' donde el sacerdote Lampitt estaba predicando,
John Sawrey (el juez) se le acercó y le dijo: "`Si hablas de acuerdo a las Escrituras,
puedes hablar.`"
G+++.+++ Fox le dijo que efectivamente hablaría de acuerdo a las Escrituras,
y que las usaría para probar lo que tenía que decir.
Pero luego Sawrey se contradijo diciendo que no hablaría,
e incitó a la gente contra G. Fox, por lo que le cayeron encima, lo derribaron,
lo patearon y lo pisotearon.
Finalmente Sawrey se acercó,
lo apartó de la gente y lo condujo fuera de la '`casa del
campanario,`' ordenándoles a los alguaciles que lo azotaran.
Entonces fue arrastrado fuera del pueblo y entregado a la ira de una multitud violenta,
que lo golpeó tan terriblemente con varas y bastones,
que a la postre se desmayó y cayó sobre el suelo mojado.
Pero recuperándose de nuevo y encontrándose fortalecido por un poder inmediato,
se levantó, y extendiendo sus brazos dijo en voz alta: "`¡Golpeen de nuevo;
aquí están mis brazos, mi cabeza y mis mejillas!`"
Entonces, un albañil le dio un golpe tan fuerte en el dorso de la mano con su bastón,
que la mano quedó deformada, y el brazo estaba tan entumecido que no lo pudo retraer,
de modo que algunas de las personas gritaron:
"`¡Le ha echado a perder la mano para siempre!`"
Pero siendo sostenido por el amor de Dios, se quedó quieto,
y después de un rato sintió un poder fortalecedor tan extraordinario,
que instantáneamente recuperó la fuerza en su mano y en su brazo.

Esto hizo que la gente discutiera entre sí,
y algunos le dijeron a G. Fox que si les daba dinero, ellos lo protegerían del resto.
Pero en lugar de hacer eso, les mostró la falsedad de su Cristianismo,
y les dijo que ellos parecían más judíos y paganos que verdaderos cristianos,
y que sus frutos eran una evidencia del infructuoso
ministerio de los sacerdotes de ellos.
Luego se sintió movido a regresar a Ulverstone y entrar al mercado del lugar.
Mientras iba, un soldado se reunió con él y le dijo: "`Señor, veo que eres un hombre,
y estoy avergonzado y afligido de que hayas sido lastimado así.`" Pero G. Fox le dijo:
"`El poder del Señor está sobre todos.`"
Y esto lo experimentó en verdad, porque cuando caminó entre la gente en el mercado,
nadie pudo tocarlo en ese momento, aunque algunos de sus amigo fueron lastimados.
Y luego, cuando G. Fox vio al soldado entre la gente con su espada desenvainada,
le rogó que la guardara si quería acompañarlos;
pues el soldado quería alejarlo de la multitud para que nadie le hiciera daño. Sin embargo,
unos pocos días después de esto,
siete hombre cayeron sobre este soldado y lo golpearon cruelmente,
debido a que él había participado con G. Fox y sus amigos.

Habiendo realizado su obra en Ulverstone, G. Fox regresó a Swarthmore,
donde encontró a varios de sus amigos vendando las heridas y contusiones
que habían recibido por los oyentes del sacerdote Lampitt.
Para entonces, los sacerdotes empezaron a profetizar que en el término de medio año,
todos los Cuáqueros serían reprimidos y habrían desaparecido.
Pero calcularon mal, porque sucedió con este pueblo como sucede con los árboles,
que crecen mejor cuanto más podados son.

G+++.+++ Fox manteniéndose en continuo movimiento, fue con James Nayler a Walney Island,
donde tuvieron una primera reunión en un pueblito llamado Cockan,
en la que un hombre se le acercó con una pistola y lo apuntó con ella,
pero no la disparó. Entonces G. Fox le habló con gran celo,
y el hombre estaba tan impactado que temblaba de temor y se fue.
La mañana siguiente G. Fox subió a un bote para dirigirse a la casa de James Lancaster,
y tan pronto como llegó a tierra, unos cuarenta hombres armados con bastones,
palos y cañas de pescar cayeron sobre él, golpeándolo y apaleándolo,
y esforzándose por empujarlo de regreso al mar.
Cuando intentó seguir adelante lo derribaron y quedó atontado, y cuando volvió en sí,
vio a la esposa de James Lancaster arrojándole piedras a la cara,
y que su esposo estaba sobre él para protegerlo de los golpes y de las piedras;
pues la gente había persuadido a esta mujer de que G. Fox había hechizado a su esposo,
y le habían prometido matarlo cuando llegara ahí. Pero el Señor,
mediante Su invisible poder, lo guardó maravillosamente,
de modo que no pudieron quitarle la vida.
Al fin se levantó, pero fue golpeado de nuevo en el bote.
Viendo esto, James Lancaster se acercó, se metió y empujó el bote hacia el agua.
Cuando llegaron al otro lado,
vieron cómo el perverso grupo había caído sobre James Nayler gritando:
"`¡Mátenlo! ¡Mátenlo!`"
Porque mientras habían golpeado a G. Fox, no les había importado Nayler,
quien estaba caminado hacia un campo.

Al volver a Cockan, G. Fox no encontró mejor recibimiento,
porque la gente se le acercó con rastrillos,
mayales y bastones para mantenerlo fuera del pueblo, y gritaban: "`¡Mátenlo;
golpéenlo en la cabeza!`"
Pero fue preservado vivo, y después de haber sido muy maltratado,
lo llevaron a una distancia considerable del pueblo y lo dejaron.
Entonces James Lancaster regresó para encargarse de James Nayler.
Mientras tanto, G. Fox llegó a una zanja que tenía agua y se lavó la sangre y el barro,
después de lo cual, caminó aproximadamente tres millas a la casa de un tal Thomas Hutton,
pero estaba tan lastimado, que apenas podía hablar;
sólo les dijo dónde había dejado a James Nayler.
Con lo cual, Thomas Hutton y Thomas Lawson (el sacerdote antes mencionado,
que en ese momento se alojaba en la casa de Hutton),
tomaron cada uno un caballo y se fueron a buscar a James Nayler,
y al encontrarlo lo llevaron esa noche ahí.

Al día siguiente, después de oír lo que le había sucedido a G. Fox,
Margarita Fell le envió un caballo,
pero él estaba tan lastimado que no podía soportar
el movimiento del caballo sin mucho dolor.
Cuando llegó a Swarthmore,
los jueces Sawrey y Thompson extendieron una orden judicial contra G. Fox,
pero cuando el juez Fell regresó a la casa la hizo ineficaz,
y envió órdenes judiciales a Walney Island para aprehender a todos los alborotadores;
por lo que algunos de ellos huyeron del condado.
Sin embargo, lo más destacable es, que la esposa de James Lancaster,
que se había comportado tan malvadamente,
después se arrepintió profundamente de su maldad
y llegó a ser una de las amigas de G. Fox.

El juez Fell quería que G. Fox le hiciera un relato de lo que le había sucedido,
pero él estaba reacio,
y dijo que esas personas no podían hacer algo diferente por el espíritu en que estaban,
y que ellos manifestaban los frutos del ministerio de sus sacerdotes.
Esto hizo que el juez le dijera después a su esposa:
"`G. Fox habló de esas cosas como si no le preocuparan en absoluto.`"

El motivo por el que una orden judicial había sido emitida contra él,
obedecía un plan que los sacerdotes habían ideado para quitarle la vida,
porque ellos habían esparcido un rumor de que en una reunión él había blasfemado;
y a fin de apoyar ese engaño, habían incitado testigos falsos.
Al llegar el momento de las sesiones de la corte en Lancaster,
G+++.+++ Fox fue con el juez Fell,
quien en el camino le dijo que nunca había sido llevado ante él un asunto como ese,
y que no sabía qué hacer en un caso así. Pero G. Fox le dijo:
"`Cuando Pablo fue llevado delante de los gobernantes,
y los judíos y sacerdotes lo estaban acusando de muchas falsedades,
él se mantuvo tranquilo todo ese rato hasta que terminaron, y cuando finalizaron,
el gobernador Félix le hizo señas para que hablara por sí mismo.
Así puedes hacer conmigo,`" le dijo G. Fox.

Cuando llegaron a las sesiones de la corte en Lancaster,
unos cuarenta sacerdotes comparecieron contra él,
y estos habían elegido a un tal Marshal (sacerdote de Lancaster) para que fuera su portavoz,
y los testigos que habían provisto eran un joven sacerdote y los hijos de dos sacerdotes.
Cuando los jueces se ubicaron y oyeron todos los
cargos de los sacerdotes y testigos--que eran,
que G. Fox había dicho que Dios enseñaba el engaño,
y que la Escritura no era más que un partida de mentiras--entonces
interrogaron a los testigos bajo juramento.
Pero estos hombres estaban tan confundidos y tan perdidos,
que uno de ellos (al no poder responder directamente a lo
que se le había preguntado) dijo que el otro podía responder,
lo que provocó que los jueces dijeran:
"`¿Has jurado y ahora dices que otro puede responder?
Parece que no escuchaste esas palabras por ti mismo, aunque lo has jurado.`"
Entonces varias personas en la corte declararon,
que ellas habían oído a uno de los hijos de los dos sacerdotes decir,
que si él tuviera poder haría que George negara su profesión y le quitaría la vida.
El sacerdote joven, que también era testigo,
confesó que él no se habría entrometido en el asunto,
si el otro sacerdote no hubiera insistido en que lo hiciera.

Después de que se oyeron todas las acusaciones,
varios hombres de reputación en el condado afirmaron ante la corte,
que G. Fox no había dicho en la reunión ninguna de las palabras de las que se le acusaban;
pues la mayoría de los hombres serios de ese lado del condado,
que en ese momento estaban en las sesiones,
habían estado en la reunión en la que los testigos
juraron que él había dicho las mencionadas blasfemias.
El coronel West, que era juez de paz y estaba sentado en el estrado,
estaba muy complacido con esos testimonios,
y (habiendo estado por mucho tiempo físicamente débil) dijo que
él había bendecido al Señor porque lo había sanado ese día;
y agregó,
que él nunca había visto tantas personas sobrias
y buenos semblantes juntos en toda su vida.
Y luego, volviéndose a G. Fox le dijo: "`George, si tienes algo que decirle a la gente,
puedes declararlo libremente.`"
Entonces él empezó a hablar, pero el sacerdote Marshal,
el portavoz de los otros sacerdotes, en seguida abandonó la sala.
Ahora bien, lo que G. Fox declaró fue,
que las Sagradas Escrituras habían sido dadas por el Espíritu de Dios,
y que todas las personas debían ir primero al Espíritu de Dios en sí mismas, para que,
por medio de Este,
pudieran conocer a Dios y a Cristo (de quienes habían aprendido los profetas y apóstoles),
y también conocer las Sagradas Escritura.
Que así como el Espíritu de Dios había estado en los que dieron las Escrituras,
así debía estar en los que quieren llegar a conocer y entender las Escrituras.
Y que es por medio de este Espíritu,
que ellos podían tener comunión con el Padre y con el Hijo, y unos con otros;
pero que sin este Espíritu, nunca podrían conocer a Dios, ni a Cristo, ni las Escrituras,
ni tener verdadera comunión unos con otros.

Apenas había dicho estas palabras,
cuando alrededor de media docena de sacerdotes estallaron en cólera, y uno de ellos,
cuyo nombre era Jackus, dijo que el Espíritu y la letra eran inseparables.
Esto hizo que G. Fox respondiera: "`Entonces cualquiera que tenga la letra,
también tiene al Espíritu,
y podría comprar al Espíritu junto con la letra de la Escritura.`"
A lo que el juez Fell y el coronel West añadieron, que de acuerdo a esa posición,
un hombre podría llevar al Espíritu en su bolsillo, como lleva las Escrituras.
Además, el juez le pidió a Jackus que probara lo que había dicho.
Pero al hallarse atrapado, trató de negarlo,
y algunos otros sacerdotes trataron de disfrazar sus palabras con un significado inventado.
Pero los jueces no permitieron ningún otro significado,
más que el simple sentido de las palabras.
Viendo que los testigos no estaban de acuerdo,
y percibiendo que habían sido puestos por la envidia de los sacerdotes,
pusieron en libertad a G. Fox,
y después de que el juez Fell les habló a los jueces Sawrey y Thompson
con respecto a la orden judicial que habían extendido contra él,
demostrando que tendía a alentar disturbios como los ocurridos en Walney Island,
él y el coronel West otorgaron una anulación para detener la ejecución de dicha orden.

Así, pues, G. Fox fue absuelto en una sesión abierta,
y muchas personas se regocijaron y se convencieron
de la Verdad declarada por él ese día en la corte;
entre esos, un tal juez Benson y el alcalde de Lancaster, cuyo nombre era Ripan.
También un tal Thomas Briggs,
quien anteriormente había sido muy hostil y opositor de los llamados Cuáqueros.
Este mismo Briggs después se convirtió en un fiel ministro del evangelio entre ellos,
y permaneció así hasta el fin de sus días.

G+++.+++ Fox se quedó todavía unos días en Lancaster,
pero no es mi intención relatar todos los sucesos con los que él y sus amigos se toparon,
porque exponer en detalle todos estos acontecimientos es una obra que
requeriría más tiempo y fuerza de lo que se puede esperar de mí. Por tanto,
sólo intento describir lo que me parece más destacable,
aunque también han sucedido muchas cosas notables de las cuales
no he podido ser completamente informado en cuanto a circunstancia,
nombre, lugar, tiempo, etc.
Pero tal vez, esto le dé a algún otro autor en Inglaterra después de mí,
la oportunidad de publicar tales descubrimientos que causen asombro a su posteridad.
Porque los grandes maltratos por los que G. Fox pasó,
fueron también la porción de muchos otros de sus amigos, especialmente los predicadores,
que en ese año eran más de veinticinco.
Y en casi todos los lugares adonde llegaron, encontraron oposición,
y se convirtieron (por así decirlo) en presa de la multitud maleducada.
Pero ni las palizas, ni las bofetadas, ni las apedreadas de la chusma rabiosa,
ni las cárceles y azotes que sufrieron por parte de los magistrados,
fueron capaces de detener el progreso de la verdad
que ellos les predicaban a las personas en los mercados,
calles y '`casas del campanario.`' Incluso,
muchos de los que se habían enfurecido como lobos, después llegaron a ser como corderos,
y sufrieron pacientemente de otros lo que ellos mismos, en un celo ciego,
habían perpetrado anteriormente.

Y así, los llamados Cuáqueros, mediante una firme y duradera paciencia,
han superado las mayores dificultades,
y finalmente se han convertido en un pueblo numeroso,^
footnote:[En el momento de este escrito, que fue alrededor del año 1715.]
muchos no valorando sus propias vidas,
cuando se encontraban una oportunidad de servirle a Dios.
Y aunque, en virtud de ello, sus enemigos los han acusado de terquedad y obstinación,
ellos dócilmente se han rendido a lo que les suceda,
sabiendo bien que ser acusados ha sido siempre la porción
de aquellos que han sufrido por el testimonio de la verdad.
Tampoco han podido ser acusados de resistencia o de oponerse a sus perseguidores,
pues en algunas ocasiones, un simple hombre ha conducido a muchos de ellos a prisión;
ni siquiera han abandonado sus asambleas religiosas,
por abrasadora que sea la persecución. Parece que
esta era la práctica de los primeros cristianos también,
por lo que Cipriano, que murió como mártir, le escribió a Demetrio:
"`Ellos pudieron haberse resistido, y eso hasta la sangre,
pero no habían aprendido así a Cristo.`"
Pero que no piense mi lector,
que esto que he descrito han sido los mayores sufrimientos de este inofensivo pueblo,
porque creo que han sido cien veces más de lo que mi pluma es capaz de mencionar.
Pero ahora, retomo el hilo de mi relato.

El hecho de que G. Fox fuera absuelto por el tribunal, como se ha dicho,
hizo que los sacerdotes se inquietaran al oír que se difundía la noticia
de que los Cuáqueros habían ganado ese día. Para vengarse de esto,
lograron que unos jueces envidiosos se les unieran,
y en la siguiente sesión de la corte en Lancaster
se quejaron contra G. Fox ante el juez Windham,
el cual quedó tan convencido,
que le ordenó al coronel West (que era secretario de la sesión de la corte)
que emitiera una orden judicial para aprehender a G. Fox.
Pero el coronel West le habló al juez de la inocencia de G. Fox,
y declaró audazmente en su defensa.
Al sentirse ofendido por esto,
el juez le ordenó de nuevo que escribiera la orden o se retirara de su asiento.
Entonces el coronel le dijo claramente que no lo haría,
sino que ofrecería todos sus bienes y también su cuerpo por G. Fox.
Así, fue detenido el juez.
Pero cuando G. Fox llegó a Lancaster esa noche,
escuchó que una orden judicial iba a ser emitida contra él, por tanto,
juzgó que era mejor mostrarse abiertamente que hacer que sus adversarios lo buscaran.
Y así, se fue a las habitaciones del juez Fell y del coronel West,
y tan pronto como entró ambos se sonrieron, y el coronel le dijo: "`¡Qué,
¿has entrado en la boca del dragón?!`" Pero G. Fox no se dejó intimidar,
ni era de los que retrocedían ante el peligro.
Así que se quedó unos días en el pueblo,
y caminó para arriba y para abajo sin que nadie lo molestara o lo interrogara.

Mientras tanto, sus amigos no dejaban de sufrir,
porque toda la villanía o insolencia que podía ser pensada contra ellos,
algunos la juzgaban insuficiente para afligirlos.
Por esta época, Richard Hubberthorn y varios otros,
fueron sacados de una reunión por unos hombres malvados,
y llevados a cierta distancia en los campos,
donde fueron atados y dejados en medio de la temporada de invierno.

G+++.+++ Fox, que para entonces había regresado a Swarthmore,
les escribió varias cartas a los magistrados y sacerdotes
que habían levantado persecuciones en los alrededores.
La carta para el juez Sawrey fue muy fuerte y de esta manera:

[.embedded-content-document.letter]
--

[.salutation]
Amigo,

Tú fuiste el primero en comenzar toda la persecución en el norte.
Tú fuiste el primero en incitar a los hombres contra
la semilla justa y contra la verdad de Dios.
Tú fuiste el primero en fortalecer las manos de los
malhechores contra el inocente e inofensivo;
y no prosperarás. Tú fuiste el primero en incitar a los que golpean, apedrean, persiguen,
ponen en el cepo, se burlan y encarcelan, en la parte norte;
y también a los que insultan, calumnian, son detractores, acusan falsamente y alborotan.
¡Esta ha sido tu obra y esto lo has suscitado tú! Por tanto,
tus frutos declaran tu espíritu.
En lugar de despertar un '`limpio entendimiento`' en las personas,
has estimulado el entendimiento malvado, malicioso y envidioso,
y has participado con el perverso.
Tú has hecho que las mentes de las personas se vuelvan envidiosas,
a lo largo y ancho del condado; esta ha sido tu obra.
Pero Dios ha acortado tus días, te ha puesto límites y establecido tus fronteras,
ha quebrantado tus colmillos, expuesto tu religión al simple y a los niños,
y sacado a la luz tus hechos.

¡Cómo ha caído tu morada y se ha convertido en morada de demonios! ¡Cómo se ha perdido
tu belleza y tu gloria marchitado! ¡Cómo le has servido a Dios con tus labios,
aunque tu corazón está lejos de Él! ¡Cómo ha demostrado
tu enseñanza tener la marca de los falsos profetas,
cuyo fruto se declara a sí mismo!
Tendrás la recompensa según tus obras.
No puedes escapar; el justo juicio del Señor te descubrirá,
y el testigo de Dios en tu consciencia le responderá.
¡Cómo has hecho que el pagano blasfeme,
yendo con la multitud a hacer el mal,
uniéndose mano a mano con el malvado! ¡Cuán exaltado
e inflado estás de orgullo! ¡Y sin embargo,
cómo has caído en vergüenza, y te has cubierto con lo que has provocado y producido!

¡Qué John Sawrey no coja las palabras de Dios en su boca,
hasta que se haya reformado! ¡Qué no coja Su nombre en su boca,
hasta que se haya separado de la iniquidad!
Tú tienes apariencia de piedad, pero no el poder,
y has hecho de los que están en el poder, objeto de tu escarnio,
refranes y conversación en tus fiestas.
El condado a tu alrededor ha olido tu mal olor, John Sawyer,
y todos los que temen a Dios se han avergonzado y
afligido ante tu comportamiento no cristiano.
En el día de la rendición de cuentas lo sabrás, es decir,
en el día de tu condenación. Te has remontado y has puesto tu nido en alto,
pero nunca llegaste más alto que las aves del aire.
Pero ahora, has corrido entre las bestias de presa y has caído en tierra,
de modo que lo terrenal y la codicia te han tragado.

[.signed-section-signature]
G+++.+++ Fox

--

Esta carta fue en verdad fuerte, pero G. Fox se sintió movido por el Señor a escribirla.
Y es notable que este juez Sawrey, quien fue el primero en perseguir en aquellas partes,
luego se ahogó, y por tanto, no murió de una muerte natural.
También le escribió al sacerdote William Lampitt, y otra carta a otros,
para reprenderlos por su maldad.

Un tiempo después de esto fue a Westmoreland, donde se intentó hacerle daño,
pero fue prevenido por el juez Benson y algunos otros.
Al llegar a Grayrigg, tuvo una reunión ahí donde llegó un sacerdote a oponerse,
diciendo primero que las Escrituras eran la palabra de Dios.
A esto G. Fox dijo: "`Ellas son las palabras de Dios, pero no son Cristo,
quien es la Palabra.`"
Y cuando instó al sacerdote a que probara lo que había dicho,
el sacerdote se sintió perdido y se fue pronto.

El año está llegando a su fin, y tras encenderse una guerra entre Inglaterra y Holanda,
el rey Carlos II (entonces en el exilio),
les pidió permiso a los holandeses para ser recibido en su fuerza naval como voluntario,
sin ningún comando; pero esto fue rechazado cortésmente por los Estados Generales.
Mientras tanto,
Oliver Cromwell se esforzaba por obtener la autoridad suprema en Inglaterra,
especialmente porque había percibido que algunos miembros
del Parlamento (que estaban celosos por su creciente grandeza),
procuraban contrariarlo en su plan.
Esto le hizo trabajar para obtener la disolución del Parlamento.
Pero como las cosas no avanzaban tan rápido como él quería,
resolvió arbitrariamente cesarlo.
Y así, entrando en la casa el mes llamado Abril de 1653,
y tras censurarlos groseramente por el mal uso de su autoridad,
e insistiendo en que sin su disolución el reino no estaría a salvo, etc.,
finalmente proclamó: "`¡Ustedes no son el Parlamento!`"
Luego les ordenó a unos mosqueteros que entraran,
hizo que los miembros salieran de la casa y ordenó que cerraran las puertas.
Así le puso fin a una asamblea que había estado en ejercicio cerca de trece años.

Pero lo sorprendente es, que G. Fox no mucho antes de esto,
estando en Swarthmore y oyendo al juez Fell y al juez Benson conversar sobre el Parlamento,
les dijo: "`Antes de que pasen dos semanas el Parlamento será disuelto,
y el presidente de la Cámara será sacado de su silla.`"
Y así realmente sucedió, porque cuando el Parlamento fue disuelto,
el presidente de la Cámara no estaba dispuesto a salir de su silla,
y dijo que no bajaría a menos que lo forzaran.
Esto hizo que el general Harrison le dijera: "`Señor,
le tiendo mi mano,`" y luego tomándolo de la mano,
el presidente bajó. Esto concordó con lo que G. Fox había predicho,
e hizo que el juez Benson le dijera al juez Fell,
que ahora veía que George era un verdadero profeta.

Para entonces, en Cumberland eran difundidas ampliamente grandes amenazas,
de que matarían a G. Fox si alguna vez regresaba.
Cuando G. Fox lo escuchó, fue allí, pero nadie le hizo daño. Luego volvió a Swarthmore,
donde estaba el juez Anthony Pearson en ese momento, y declaró tan eficazmente la verdad,
que el juez Pearson se convenció,
y no mucho después entró en la sociedad de los despreciados Cuáqueros.

Después, G. Fox regresó a Cumberland,
y en la '`casa del campanario`' de Bootle encontró a un sacerdote de Londres predicando,
quien había reunido todas las Escrituras en las que pudo pensar,
que hablaban de falsos profetas, anticristos y engañadores,
y todas las aplicó a los Cuáqueros.
Pero después que terminó,
George empezó a hablar y volvió todas las Escrituras sobre el sacerdote;
este se disgustó y dijo que G. Fox no debía hablar.
Pero G. Fox le dijo que su reloj de arena se había agotado,^
footnote:[En este tiempo,
los sacerdotes usaban un reloj de arena para medir la duración de su sermón.]
y dado que ya había terminado, ahora el tiempo estaba disponible para él,
como también lo había estado para el sacerdote (que
era un extraño ahí también). Habiendo dicho esto,
continuó y mostró quienes eran los falsos profetas
y con qué marcas los identificaban las Escrituras;
y luego dirigió a las personas a Cristo su maestro.
Cuando terminó,
el sacerdote del lugar les dio un discurso a las personas
en el jardín de la '`casa del campanario`' diciendo:
"`Este hombre ha reunido para sí a todos los hombres y mujeres honestos en Lancashire,
y ahora viene aquí a hacer lo mismo.`"
A lo cual G. Fox replicó: "`¿Qué te quedará entonces?
¿Y quién quedará con los sacerdotes, sino los que son como ellos?
Porque si los honestos son los que han recibido la Verdad y se han vuelto a Cristo,
entonces deben ser los deshonestos los que te siguen a ti y son tal como
tú.`" Luego se intercambiaron unas palabras sobre los diezmos,
y G. Fox les dijo que Cristo le había puesto fin al sacerdocio de diezmos,
y que había enviado a Sus ministros a dar gratuitamente,
así como ellos había recibido gratuitamente.

De ahí se fue para Cockermouth,
donde él había concertado una reunión. Al llegar
encontró a James Lancaster hablando bajo un árbol,
que estaba tan lleno de personas que corría el peligro de quebrarse.
G+++.+++ Fox miró alrededor buscando un lugar donde pararse,
pues la gente estaba esparcida de arriba a abajo.
Finalmente, una persona se le acercó y le preguntó si no quería entrar en la iglesia,
y no viendo otro lugar más conveniente para hablarle a la gente,
le dijo que sí. Con lo cual, la gente se apresuró a entrar de golpe,
y la casa se llenó tanto de personas que le costó mucho entrar.
Cuando se acomodaron,
G+++.+++ Fox se puso de pie sobre un asiento y predicó cerca de tres horas,
y varios cientos fueron convencidos ese día de la verdad de esta doctrina.

De ahí se fue a otros lugares, en particular a Brigham,
donde predicó en la '`casa del campanario`' con no menos éxito.
Después de llegar a cierto lugar y mirar a una mujer desconocida para él,
le dijo que ella había llevado una vida lasciva, a lo cual ella respondió,
que muchos podían hablarle de sus pecados externos,
pero nadie podía hablar de sus pecados internos.
Él le dijo que el corazón de ella no era recto delante del Señor, y esto la tocó tanto,
que después se convenció de la verdad de Dios.

Al acercarse a Coldbeck, a un pueblo-mercado, tuvo una reunión en la cruz^
footnote:[Un monumento con una cruz que se colocaban antiguamente en los mercados,
para infundir la devoción.]
del mercado, y algunos recibieron la verdad predicada por él. De ahí se fue a Carlisle,
donde el maestro de los Bautistas, junto con la mayoría de sus oyentes,
llegaron a la abadía donde G. Fox tenía una reunión. Después de la reunión,
el maestro Bautista (que era un nocionista y un hombre
vanidoso) se acercó a él y le preguntó:
"`¿Qué es lo que debe ser condenado?`"
G+++.+++ Fox le contestó: "`Eso que habla en ti debe ser condenado.`"
Esto detuvo su boca.
Y luego George le explicó los estados de elección y condenación de tal modo,
que dijo que él nunca había oído algo así en toda su vida,
y después llegó a convencerse de la Verdad también.

Luego subió al castillo de Carlisle entre los soldados,
quienes al golpe del tambor convocaron la guarnición. Él predicó entre
ellos dirigiéndolos a la medida del Espíritu de Cristo en ellos,
por medio de la cual podrían ser vueltos de las tinieblas a la luz,
y del poder de Satanás a Dios.
También les advirtió que no hicieran violencia a ningún hombre.
Después de descargar su consciencia, nadie se opuso a él,
excepto algunos sargentos que luego se convencieron.
El '`día de mercado,`' entró al mercado,
aunque lo habían amenazado con un trato violento si iba a ese lugar.
Pero deseando obedecer más a Dios que al hombre, no se intimidó,
y yendo a la cruz declaró que el día del Señor vendría
sobre todos los caminos y las obras engañosas,
y sobre todo comercio engañoso, y que ellos debían dejar toda estafa y engaño,
mantener el sí y el no, y hablar la verdad los unos a los otros.

El siguiente Primer-día,
G+++.+++ Fox entró en la '`casa del campanario`' y cuando el sacerdote terminó,
él comenzó a predicar.
Después de que el sacerdote se fue, el magistrado le pidió que se fuera,
pero él continuó,
diciéndoles que él había llegado para hablar la palabra
de vida y salvación del Señor entre ellos.
Y habló tan poderosamente que la gente temblaba y se sacudía,
y algunas pensaron que la '`casa del campanario`' también se estaba sacudiendo; de hecho,
algunos temieron que les cayera sobre sus cabezas.
Mientras tanto, algunas mujeres habían hecho un gran alboroto,
y finalmente la gente ruda de la ciudad se levantó y entró
a la '`casa del campanario`' con bastones y piedras,
por lo que el gobernador mandó algunos mosqueteros para apaciguar el tumulto.
Estos tomaron a G. Fox por la mano de manera amistosa, y lo sacaron.
Entonces se fue a la casa de un teniente donde tuvo una reunión muy tranquila.

Al día siguiente los jueces y magistrados lo mandaron a llamar,
para que se presentara delante de ellos en el ayuntamiento,
donde tuvo una larga conversación sobre religión,
mostrándoles que aunque ellos eran grandes profesantes del
Cristianismo (tanto Presbiterianos como Independientes),
todavía no poseían lo que profesaban.
Pero después de un largo interrogatorio lo mandaron a prisión por blasfemo,
hereje y engañador, y allí permaneció hasta que se celebró la sesión de la corte.
Para entonces todo el mundo decía que lo iban a ahorcar; de hecho,
el alguacil superior Wilfrey Lawson estaba tan ansioso de que le quitaran la vida,
que dijo que él en persona llevaría a G. Fox a la ejecución.

Esto causó tal revuelo en aquella zona,
que incluso las mujeres de clase alta llegaron a verlo,
como alguien que estaba a punto de morir.
Pero cuando el juez y los magistrados estaban ideando cómo darle muerte,
el secretario del juez formuló una pregunta que los desconcertó y confundió a sus abogados,
de modo que no fue llevado a juicio como se esperaba (el cual, no obstante,
era contrario a la ley).
No obstante, era tal la envidia contra él,
que se le ordenó al carcelero que lo pusiera entre los ladrones,
asesinos y algunas mujeres malas, y este grupo perverso estaba tan cubierto de piojos,
que por poco se comen a una mujer hasta matarla.
Pero lo que empeoraba aún más el encarcelamiento, era que no había letrina,
y en ese repugnante lugar estaban hacinados hombres y mujeres, contra toda decencia.
Sin embargo, estos prisioneros, a pesar de lo muy depravados que eran,
se encariñaron mucho de G. Fox, y le prestaban tanta atención a su sano consejo,
que algunos se llegaron a convertir.
Pero el ayudante del carcelero le hizo todo el daño que pudo.
Una vez,
cuando G. Fox estaba cerca de las barras para recibir
la comida que sus amigos le habían llevado,
el carcelero le cayó encima a golpes con un gran garrote gritándole:
"`¡Aléjate de la ventana!,`" aunque estaba suficientemente lejos de ella.
Pero mientras el carcelero lo golpeaba estaba tan lleno de gozo, que comenzó a cantar,
lo que hizo que el otro se enfureciera aún más,
por lo que se fue a buscar a un violinista, pensando molestarlo de esa manera.
Pero mientras el violinista tocaba, G. Fox empezó a cantar un himno en voz tan fuerte,
que ahogó el sonido del violín con su voz,
y el violinista quedó tan confundido que se vio obligado a rendirse y seguir su camino.

No mucho después de esto,
la esposa del juez Benson se sintió movida a comer solamente lo
que comería con G. Fox en las barras de la ventana del calabozo.
Y después, ella misma fue encarcelada en York cuando esperaba un hijo,
por haberle hablado (según parece) celosamente a un sacerdote.
Y cuando llegó el momento de su parto, no se le permitió salir,
sino que dio a luz en prisión.

Mientras G. Fox estaba en el calabozo en Carlisle, llegó a verlo un tal James Parnell,
un jovencito de unos dieciséis años,^
footnote:[A partir de sus propios escritos, es evidente que previo a este encuentro,
James Parnell ya había experimentado una conversión real de corazón,
pues cuando tenía unos catorce años,
había sido llevado a ver el formalismo de los sacerdotes y se había separado de la acostumbrada
forma de adoración para sólo esperar en el Señor. De modo que,
por medio de esta entrevista con George Fox,
él fue sólo convencido de que la Verdad que Fox predicaba,
era la misma hacia la cual él había sido llevado por el Espíritu de Verdad.]
y fue tan efectivamente alcanzado por las palabras de G. Fox,
que se convenció de la verdad de sus afirmaciones.
Y a pesar de su juventud,
el Señor hizo rápidamente de este joven un poderoso ministro del evangelio,
mostrándose con su pluma y con su lengua como un celoso promotor de la religión,
aunque padeció duros sufrimientos por este motivo, tal como será mencionado en el futuro.

En este tiempo hubo muchos otros que llegaron a ser celosos predicadores del arrepentimiento,
al no permitirse ser obstaculizados por ninguna adversidad.
Entre estos estaba el ya mencionado Thomas Briggs, quien recorrió muchas ciudades,
pueblos y aldeas con el siguiente mensaje: "`Arrepiéntanse, arrepiéntanse,
porque el poderoso y terrible día del Señor Dios de poder está apareciendo,
en el que ningún hacedor de iniquidad permanecerá delante de Aquel '`de ojos
muy limpios para ver el mal.`' Porque Él no quiere la muerte de ningún pecador,
y si se arrepienten y vuelven a Él, Él los perdonará abundantemente.`"
En algunas ocasiones,
que T. Briggs entró en los mercados y en las '`casas
del campanario,`' fue cruelmente lastimado.
Una vez, estando en la '`casa del campanario`' de Warrington, en Lancashire,
estaba diciendo una pocas palabras después de que el sacerdote había terminado,
cuando fue violentamente golpeado en la cabeza;
después de lo cual un hombre lo cogió del cabello y lo golpeó contra una piedra,
y le arrancó un mechón de cabello.
Sobre lo cual dijo suavemente, mientras levantaba su cabello del suelo:
"`Ni un pelo de mi cabeza caerá al suelo sin el permiso de mi Padre.`"

En otro momento, después de hablarle a un sacerdote en Cheshire,
mientras continuaba su viaje, este hizo saber que se sentía muy ofendido por él,
así que uno de sus oyentes, en supuesta venganza por esa pretendida ofensa,
golpeó a Thomas en la cabeza y lo derribó. Pero levantándose
de nuevo y volviendo su rostro hacia el que lo había golpeado,
recibió otro golpe en los dientes y empezó a sangrar abundantemente,
ante lo cual algunos de los testigos no pudieron evitar gritar en contra.
Pero no mucho después de esto, el hombre que lo había golpeado cayó enfermo,
y cuando estaba muriendo, exclamó sobre su lecho de muerte:
"`¡Ojalá no hubiera golpeado al Cuáquero!`"

Unas vez, cuando pasaba por Salisbury llamando a los habitantes al arrepentimiento,
este Thomas fue aprendido y llevado delante de varios jueces
que le exigieron que prestara el juramento de lealtad,^
footnote:[Este era un juramento que había sido establecido en 1606 por el rey Jacobo I,
por medio del cual se les exigía a los ciudadanos que juraran lealtad al rey de Inglaterra,
y abdicar de todo poder o política que el Papa o la Iglesia
de Roma pudieran reclamar para deponer al rey.]
bajo el pretexto de que era un Jesuita.
Pero Thomas diciendo que no podía jurar porque Cristo había ordenado:
"`No juréis en ninguna manera,`"^
footnote:[Mateo 5:34]
fue enviado a prisión donde fue mantenido un mes.
También subió y bajó por las calles de Yarmouth proclamando el terrible día del Señor,
para que todos se arrepintieran y temieran Al que había hecho el cielo,
la tierra y el mar.
Y al ser seguido por una gran multitud de personas toscas,
se dio la vuelta y les habló tan poderosamente y con palabras tan penetrantes,
que se alejaron corriendo por temor.
Al final, llegó un oficial y lo cogió, pero como lo llevaba amablemente,
él tuvo la oportunidad de seguir predicándole a la gente y de descargar su consciencia.

Cuando llegó a Lynn y exhortó a la gente al arrepentimiento,
le echaron encima un gran perro mastín,
pero el perro se le acercó y se comportó amistosamente con él. Así recorrió muchos lugares,
pasando a veces por cinco o seis pueblos en un día;
y aunque se desenvainaron espadas contra él, o se levantaron hachas para derribarlo,
él siguió adelante, y hablaba con un poder tan terrible,
que incluso algunos que no habían visto su rostro,
fueron alcanzados por el poder que lo acompañaba y se convirtieron.
Cuando llegó a Clayzons, en Gales,
viendo el alguacil que muchos lo escuchaban atentamente,
incitó a la gente grosera y gritó: "`¡Mátenlo,
mátenlo!,`" como si hubiera sido un perro rabioso.
Allí le lanzaron piedras tan grandes, que se asombró de que no lo mataran;
pero fue preservado por un poder tan grande,
que la piedras (según su relato) habían sido para él como una nuez o un frijol.
Él se topó con muchos otros encuentros rudos,
pero fue preservado maravillosamente en los más grandes peligros;
lo cual lo fortaleció mucho en la creencia de que Dios, quien lo salvaba milagrosamente,
requería de él este servicio.
También fue a América, y murió a una edad muy avanzada,
después de haber trabajado más de treinta años al servicio del evangelio.

Entre los primeros predicadores celosos de los llamados Cuáqueros,
había uno llamado Miles Haldead,
quien además fue el primero de su persuasión en ser encarcelado en Kendal.
Una vez, mientras iba para Swarthmore a visitar a sus amigos y asistir a su reunión,
se topó con la esposa del juez Thomas Preston en el camino,
y debido a que él paso al lado de ella tranquilamente, sin la forma habitual de saludar,
ella se ofendió tanto que le ordenó a su criado que regresara y lo golpeara;
lo cual hizo.
Ante esto, Miles se encendió con celo y le dijo: "`¡Tú,
orgullosa Jezabel! ¿No le permites a un siervo del Señor pasar a tu lado tranquilamente?`"
Entonces ella extendió su mano como si lo fuera a golpear,
y luego lo escupió en la cara diciendo: "`Tus palabras no me tocan.`"
Miles le dijo de nuevo: "`¡Tú, orgullosa Jezabel,
que endureces tu corazón y con tu rostro insolente te opones al Señor y a Su siervo,
el Señor contenderá contigo en Su tiempo,
y pondrá delante de ti las cosas que has hecho hoy!`"
Y así, se separó de ella y se fue a Swarthmore.

Unos tres meses después de esto, Miles se sintió movido a ir y hablar con ella,
y cuando llegó a Houlker Hall preguntó por la esposa de Thomas Preston.
Entonces ella llegó a la puerta y Miles,
que no la reconoció inmediatamente (tal vez porque estaba vestida diferente),
le preguntó si ella era la mujer de la casa, y ella respondió: "`No,
pero si desea hablar con la Sra.
Preston, le pediré que venga.`"
Luego entró y volviendo con otra mujer dijo: "`Aquí está la Sra.
Preston.`"
Pero se le mostró a Miles que ella era la mujer que buscaba, y le dijo: "`Mujer,
¿cómo te atreves a mentir delante del Señor? Tú eres la mujer con la que vine a hablar.`"
Y como ella se quedó en silencio, sin decir una palabra, él prosiguió:
"`Escucha lo que el siervo del Señor tiene que decirte: Mujer,
no endurezcas tu corazón contra el Señor, porque si lo haces, Él te cortará en Su ira.
Por tanto, toma la advertencia a tiempo y teme al Señor Dios del cielo y de la tierra,
para que puedas terminar tus días en paz.`"
Después de decir esto se fue,
y ella (sin saber por quién) fue impedida de hacerle algún daño a Miles.
Pero a pesar de esta advertencia ella continuó igual,
pues sucedió que años después de esto, cuando G. Fox era prisionero en Lancaster,
ella fue a verlo y le gritó muchas palabras insultantes,
diciendo (entre otras cosas) que debían cortarle la lengua y ahorcarlo.
Un tiempo después el Señor la cortó y murió, y según lo que se informó,
en una miserable condición.

Pero antes de dejar a esta mujer,
debo añadir que unos tres años después de que ella
le ordenara a su criado golpear a Miles,
sucedió que mientras él cabalgaba desde Swarthmore, cerca de Houlker Hall,
se topó con una persona que le dijo: "`Amigo,
tengo algo que decirte y que ha estado sobre mí todo este tiempo.
Yo soy el hombre que hace tres años te golpeó muy severamente, por orden de mi ama;
por lo que he estado muy afligido,
más que por cualquier otra cosa que haya hecho en toda mi vida.
Porque en verdad, ha estado en mi corazón noche y día,
que hice mal al golpear a un hombre inocente, que no me había herido ni lastimado.
Te ruego que me perdones,
y deseo que el Señor me perdone para poder tener paz y tranquilidad en mi mente.`"
Entonces Miles respondió: "`Amigo, desde ese momento hasta hoy,
verdaderamente nunca he tenido nada en mi corazón contra ti, ni tu ama, sino amor.
El Señor los perdona.
Deseo que esto no se te tome en cuenta,
pues no sabías lo que hacías.`" No dijo más y siguió su camino.

En una ocasión, viajando en Yorkshire, llegó a Skipton,
donde al declarar la palabra de verdad fue tan seriamente lastimado y golpeado,
que lo dieron por muerto.
Sin embargo, el poder del Señor lo sanó de todas sus heridas,
y en el término de tres horas estaba sano y salvo de nuevo,
para asombro de los que lo habían lastimado y convencimiento de muchos que lo vieron.
Entonces se fue a Bradford, Leeds y Halifax,
donde también declaró la doctrina de verdad entre las personas,
pero no sin encontrarse con gran persecución.

De ahí llegó a Doncaster,
y el Primer-día de la semana fue a la '`casa del
campanario,`' donde después de que terminó el culto,
les habló al sacerdote y a las personas.
Pero en lugar de escuchar lo que decía,
cayeron sobre él con gran furia y lo expulsaron del pueblo, y como estaba muy malherido,
lo dieron por muerto otra vez.
Sin embargo, antes de que saliera de su casa,
había sido firmemente convencido de que el Señor lo preservaría en todos los peligros.
Y le sucedió según su creencia,
porque se levantó de nuevo y se fue a la casa de un amigo, donde se acostó en una cama.
Pero poco tiempo después, se sintió fuertemente movido a ir a cierta capilla,
y ahí declarar la palabra del Señor,
sintiendo también una seguridad interna de que si se rendía y lo hacía,
el Señor lo sanaría de sus contusiones.
Entonces se levantó como pudo y bajó las escaleras con gran dificultad,
sosteniéndose de las paredes para no caerse.
Y al salir de la casa empezó a curarse poco a poco,
y cuando finalmente entró en la capilla, habló según fue movido,
y después que se descargó, regresó a la casa de la que había salido,
y el Señor lo sanó de todas sus heridas y lesiones.

De ahí se fue a York y habló con el alcalde y con otros gobernantes de esa ciudad.
Luego cruzando Yorkshire,
entró en varias '`casas del campanario`' para exhortar a la gente,
y aunque encontró grandes dificultades, fue sostenido por una mano invisible.
Sintiéndose libre de ese condado, regresó a su casa en Mount-joy, en Underbarrow,
en el condado de Westmoreland.
Pero sus frecuentes viajes eran una prueba tremendamente grande para su esposa,
quien pasó el primer año después de su cambio muy
afligida en su mente (pues no era de su persuasión),
y a menudo decía con descontento: "`Desearía haberme casado con un borracho,
entonces podría encontrar a mi esposo en la taberna; pero ahora no sé dónde está.`"

Al cabo de un año le plació al Señor visitarla.
Ella tenía un hijo pequeño, de unos cinco años, al que amaba extraordinariamente,
al punto de considerarlo su único deleite y consuelo.
Pero sucedió que este amado niño murió,
y un tiempo después de esto ella le contó a su esposo lo siguiente: "`Miles,
tengo algo que decirte.
Una noche estando en la cama, llorando y lamentándome, oí una voz que decía:
'`¿Por qué estás tan descontenta con respecto a tu esposo?
Yo lo he llamado y escogido para Mi obra; Mi mano derecha lo sostendrá. Por tanto,
conténtate y agrádate en que él Me sirva,
y Yo te bendeciré a ti y a tus hijos por causa de él;
te bendeciré en todo lo que emprendas.
Pero si no te contentas, sino que guardas rencor y murmuras,
y te quejas contra Mí y contra Mi siervo, a quien Yo he escogido para que haga Mi obra,
traeré sobre ti una prueba más grande.`' Estas palabras
estaban frescas en mi mente noche y día,
y a menudo me decía a mí misma:
'`¿Cuál podría ser una mayor prueba que la ausencia de mi esposo?`' Sin embargo,
yo no estaba contenta.
Todo el gozo que yo tenía, o podía encontrar, estaba en nuestro pequeño niño,
quien a veces, cuando me veía llorar y lamentándome, me abrazaba y me decía:
'`Querida madre, por favor conténtate,
porque mi padre regresará a casa dentro de poco.`' Este niño a menudo me consolaba así,
y sin embargo, yo no estaba contenta.
No mucho después, le plació al Señor quitarme a mi único hijo,
mi mayor alegría. Entonces la voz que yo había oído vino fresca a mi mente,
y al darme cuenta de que esa era la prueba que el Señor traería sobre mí si no me contentaba,
golpeé mi pecho y dije dentro de mí:
'`Yo soy la causa por la que el Señor se llevó a mi pequeño hijo.`' Entonces,
un gran temor se apoderó de mí y dije: '`¡Oh, Señor, mi Dios!
Dame el poder para estar contenta de entregar a mi
esposo voluntariamente para que haga Tu voluntad,
no sea, oh, Señor, que me quites a todos mis hijos.`' Desde ese momento,
nunca más me he atrevido a oponerme a ti en la obra del Señor,
por temor a que los juicios de Dios caigan sobre mí y mis hijos.`"
Esto fortaleció y animó mucho a Miles.

Un tiempo después de esto, mientras caminaba en su jardín,
se sintió movido a ir la capilla de Stanley, en Lancashire.
Y aunque esperaba encontrarse con un duro recibimiento ahí,
no consultó con '`carne y sangre,`' sino que fue a la mencionada capilla.
Al llegar, no le permitieron entrar,
sino que cerraron violentamente la puerta contra él. Entonces,
él se quedó caminando en el jardín hasta que terminó el culto, y cuando salió la gente,
cayeron sobre él con gran furia,
y un tal capitán William Rawlinson lo cogió de los brazos y hombros,
y llamó a otro hombre para que lo cogiera de los pies y las piernas,
y ambos lo lanzaron por encima de un muro,
por cuya caída quedó tan lastimado que tuvo gran dificultad para regresar a la casa.
En el camino le fue dicho internamente,
que debía estar contento con lo que le había sucedido ese día,
y que si era fiel en lo que el Señor le pedía, Él lo sanaría de nuevo.
Al llegar a la casa, esperó en el Señor para conocer Su voluntad.
En el término de seis días y en este estado de rendición,
fue movido a ir a la '`casa del campanario`' en Windermere, y le fue dicho:
"`No temas el rostro de ningún hombre; habla la palabra del Señor libremente,
y entonces serás sanado de nuevo de todas tus contusiones.`"
Por tanto,
fue a la mencionada '`casa del campanario,`' y tras hablarles la palabra
del Señor al sacerdotes y a las personas sin recibir ningún daño,
fue sanado ese día de sus dolorosas lesiones.

Tiempo después, movido de nuevo por el Señor, fue a Furness en Lancashire,
a la casa del capitán Adam Sands,
donde encontró reunido a un gran número de profesantes y al sacerdote Lampitt predicando.
Pero tan pronto entró Miles, Lampitt se calló, y como se mantuvo así un rato,
el capitán Sands le dijo: "`Señor, ¿qué te sucede?
¿No te encuentras bien?`"
A lo que el sacerdote respondió: "`Estoy bien, pero no hablaré más,
en tanto ese demonio mudo esté en la casa.`"
"`¡Un demonio mudo!,`" dijo el capitán,
"`¿dónde está?`" "`Ese,`" dijo el sacerdote señalando con su mano,
"`el que está de pie ahí.`" Entonces el capitán dijo:
"`Ese hombre está en silencio y no te ha dicho nada.
Te ruego, señor, que continúes en el nombre del Señor;
y si él te incomoda o molesta en mi casa, lo enviaré al castillo de Lancaster.`"
Pero el sacerdote dijo de nuevo:
"`No predicaré mientras ese demonio mudo esté en la casa.`"
Entonces el capitán le dijo a un tal Camelford, otro sacerdote: "`Por favor señor,
ponte de pie y ejercita tu don, y veré que no seas perturbado.`"
Pero este sacerdote respondió como el otro:
"`No hablaré en tanto ese demonio mudo esté en la casa.`"
Entonces algunas personas exclamaron: "`¡El Señor te reprenda,
Satanás! ¡El Señor te reprenda,
Satanás! ¿Qué clase de espíritu es este que detiene la boca de nuestros ministros?`"
Entonces el capitán se acercó a Miles, y tomándolo de la mano lo sacó de la casa.
En todo ese tiempo él no había dicho una palabra,
pero vio el cumplimiento de lo que se le había mostrado antes,
que un poder invisible confundiría por medio de él la sabiduría de los sacerdotes,
sin siquiera decir una palabra.
Este sacerdote Camelford, mucho antes de esto, había agitado la chusma contra G. Fox.
El otro, es el mismo Lampitt que ya ha sido mencionado,
a quien Margarita Fell había estimado mucho antes de conocer a G. Fox.

Un tiempo después de este suceso, Miles fue a Newcastle, y ahí les dijo al alcalde,
a los gobernantes y sacerdotes del pueblo,
que la ira de Dios estaba encendida contra ellos,
porque les habían cerrado el reino de los cielos a los hombres; y no entraban ellos,
ni les permitían entrar a los que lo deseaban.
Por causa de esto fue encarcelado.
Pero el alcalde estaba muy angustiado y mandó a llamar
al alguacil (porque ellos habían entregado a Miles),
y cuando este llegó le dijo:
"`No hemos hecho lo correcto al enviar a un inocente a prisión. Ven, dejémoslo libre.`"
El alguacil dio su consentimiento y Miles fue puesto en libertad.
Él entonces declaró la palabra del Señor en aquella región y muchos fueron
convencidos de la verdad expuesta por él. Ahora dejo a Miles Halhead,
quien más adelante será mencionado de nuevo.

Por esta época, en el verano,
el general Oliver Cromwell había convocado un nuevo Parlamento,
compuesto mayormente (como han dicho algunos) por miembros de su propia elección;
pues había cierto número de personas de cada condado y ciudad de Inglaterra,
Escocia e Irlanda,
nominadas por el consejo de oficiales y convocadas para reunirse en Westminster.
Cromwell, mediante una comisión firmada por él y los oficiales,
entregó en las manos de estas la autoridad suprema de la nación.
Pero la autoridad de esta asamblea duró escasamente medio año,
como se mencionará más adelante.

A este Parlamento le fue dado el informe,
de que había una persona encarcelada en Carlisle que iba
a morir por asuntos de religión. Este era G. Fox,
a quien dejamos mucho tiempo en el calabozo en Carlisle, y al que regresamos ahora.
Ante esto,
el Parlamento hizo que se enviara una carta al alguacil
y a otro magistrado con respecto a él. Y G. Fox,
sabiendo que había sido vergonzosamente presentado como blasfemo,
entregó un documento en el que desafiaba a aparecer en público
a todos los que habían encontrado falla en su doctrina,
ya que estaba dispuesto a poner a prueba cualquier cosa que él hubiera dicho.
También les escribió una carta importante a los jueces de Carlisle,
en la que claramente les mostraba la injusticia de
sus tratos y el horrible mal de la persecución,
como algo que siempre había sido obra de la iglesia falsa.

Ya se ha hecho mención de los jueces Benson y Pearson;
estos habían solicitado permiso en más de un ocasión para visitar a G. Fox en prisión,
pero siendo que se les había negado, escribieron una carta a los magistrados,
sacerdotes y personas de Carlisle,
en la que enfáticamente describían la maldad de la persecución,
y lo que sería la recompensa de los perseguidores.
También mostraron que estos perseguidores eran peor
que los paganos que habían puesto a Pablo en prisión,
porque ellos no le habían impedido a ninguno de sus amigos o conocidos visitarlo.
Sin embargo,
al final Anthony Pearson tuvo la oportunidad de entrar con
el gobernador al calabozo donde estaba retenido G. Fox,
y encontraron el lugar tan mal y con un olor tan nauseabundo,
que el gobernador les gritó a los magistrados que era una vergüenza
permitirle al carcelero tratar a G. Fox de esta manera.
Y luego, llamando a los carceleros al calabozo,
les mandó que establecieran una fianza por buen comportamiento,
y puso al ayudante del carcelero (que había sido muy cruel
con G. Fox) en el calabozo junto con él. Entre tanto,
aquellos que habían encarcelado a G. Fox comenzaron a asustarse,
y aún más porque el Parlamento había tomado nota de estas acciones;
no mucho después George Fox fue liberado.

Estando en la casa de un tal Thomas Bewly, cerca de Colbeck, en Cumberland,
llegó un maestro Bautista para disputar con él. Pero este
hombre descubrió que lo que G. Fox decía era tan eficaz,
que se convenció de la verdad de ello.
Por ese entonces había un hombre llamado Robert Widders,
que fue movido a ir a la '`casa del campanario`' de Colbeck,
y el maestro Bautista fue con él. Cuando llegaron a la '`casa del campanario,`'
Widders empezó a hablarle al sacerdote que estaba predicando,
un tal Hutton,
pero unas personas maleducadas lo arrojaron al piso y lo arrastraron hasta el jardín,
donde lo empujaron y lo golpearon hasta que empezó a sangrar abundantemente por la boca,
y él quedó como muerto por un rato.
Pero una mujer se le acercó, le levantó la cabeza y al fin recobró su aliento.
Al maestro Bautista que lo acompañaba,
le habían quitado la espada y lo golpearon con ella.
Sin embargo, esto no lo asustó, ni lo desanimó, y no sólo dejó de usar espada,
sino que también renunció voluntariamente a la herencia de una renta de diezmos.

El mismo día que este predicador fue atacado con su propia
espada (el cual era el primer día de la semana),
varios amigos de G. Fox, entre ellos William Dewsbury,
fueron a varias '`casas del campanario,`' y por este
medio el número de amigos se incrementó en esos lugares;
a pesar de que en ese momento Dewsbury fue tan violentamente
golpeado por la gente que casi lo matan,
pero el poder del Señor lo sanó.

Pero volvamos a Robert Widders,
que después de recuperarse del duro trato con el que se había topado anteriormente,
se sintió tan animado y fortalecido en su tarea,
que el mismo día por la tarde se fue a la '`casa
del campanario`' de Ackton a siete millas.
Ahí habló con el sacerdote Nichols y lo llamó enemigo de Cristo, y le dijo además,
que la mano del Señor estaba contra él. Entonces William Briscoe, un juez de Crofton,
le ordenó al alguacil que sujetara a Robert, lo cual él hizo,
y lo llevó a la casa del sacerdote.
Estando allí fue interrogado por el juez y el sacerdote empezó a adularlo,
ante lo cual Robert le dijo que el espíritu de persecución
se alojaba en él. Pero el sacerdote le dijo:
"`No, yo no soy esa clase de hombre.`"
Sin embargo, poco después el sacerdote le dijo al juez,
que Robert había robado el caballo en el que había llegado,
y que él podía encontrar en su corazón convertirse en verdugo de Robert,
y hacerlo con sus propias manos.
Esto hizo que Robert dijera:
"`¿Acaso no te dije que el espíritu de persecución se alojaba en ti?`"
Entonces el mencionado juez escribió una orden judicial
para enviar a Robert a la cárcel de Carlisle,
y después de darle la orden al alguacil,
le preguntó a Robert por cuál autoridad o poder había
llegado a seducir y a hechizar al pueblo.
Robert respondió: "`Yo no vine a seducir ni a hechizar al pueblo,
pero vine en ese poder que hará que tú y todos los poderes de la tierra,
se inclinen y dobleguen ante él, a saber, el gran poder de Dios.`"
Mientras Robert hablaba,
el temor del Señor se apoderó del juez y lo golpeó de tal manera,
que pidió la orden judicial de nuevo,
la tomó de la mano del alguacil y le permitió a Robert seguir su camino.

Estando libre, no dejó de visitar las '`casas del campanario`' de vez en cuando,
por lo que algunas veces fue encarcelado y otras veces fue salvado asombrosamente.
Una vez, acercándose a Skipton, en Yorkshire,
en la '`casa del campanario,`' le habló fuertemente a un sacerdote llamado Webster,
pues sabía que el sacerdote había sido parcialmente
convencido de la doctrina de la luz interior,
pero que por desobedecerla, se había vuelto atrás otra vez.
También le habló a la gente y al juez Coats,
pidiéndoles que le prestaran atención a la Palabra de Dios
en el corazón que divide entre lo precioso y lo vil.
Después de haberse descargado,
se fue a un lugar adonde algunos de sus amigos se habían reunido,
pero no había pasado mucho tiempo, cuando unos jinetes y oficiales llegaron,
lo cogieron y se lo llevaron ante el mencionado juez.
Al interrogarlo,
el juez le dijo que había quebrantado la ley al molestar al ministro y a las personas,
y que él podía enviarlo a prisión en el castillo de York.
Robert respondió: "`Envíame a la cárcel ahí, si te atreves;
porque yo apelo al testigo de Dios en tu consciencia.`"
Pero como este juez era un hombre moderado, dijo: "`Ni me atrevo,
ni quiero,`" y cogiendo a Robert de la mano,
le dijo que podía tomarse su tiempo para irse.

Relatar todo lo que le sucedió a Robert Widders sería demasiado tedioso, por tanto,
sólo diré que, como era muy celoso al hablarles a los sacerdotes,
sufrió mucho en sus posesiones,
porque por razones de consciencia se negó a pagarles diezmos a los sacerdotes.
Por tal motivo, le fue quitado en varias ocasiones el valor de 143 libras,
además de lo que sufría por las multas a las reuniones y por los llamados
"`domingos de chelines,`" que también ascendía a una considerable suma.
Y esto no sólo le sucedió a él, sino que fue la porción de muchos cientos, no,
quizás miles de personas de su persuasión. Por esta razón no me
comprometo a relatar todo lo que se pueda mencionar de esto,
pues eso estaría más allá de mi alcance.

No obstante, por lo que se ha dicho,
puede verse por cuales medios crecieron en número
los llamados Cuáqueros en aquellos primeros tiempos.
Por un lado, el Señor había levantado muchos predicadores celosos, y por otro,
en ese tiempo había una gran cantidad de personas en Inglaterra,
que después de buscar en todas las sectas,
no pudieron encontrar en ninguna parte satisfacción para sus almas hambrientas.
Y estas, entendiendo ya que Dios mediante Su luz estaba muy cerca de sus corazones,
empezaron a prestarle atención a ella,
y pronto encontraron que esta les daba mucha más victoria sobre la corrupción
de sus mentes (bajo la cual había gemido por mucho tiempo),
que toda la adoración en la voluntad del yo que habían realizado
con celo por muchos años. Y además de los que habían sido preparados
así para recibir la más grande manifestación del camino de vida,
había también muchos de una vida libertina,
que habiendo sido punzados hasta el corazón y ganados por
la paciencia cristiana de los despreciados Cuáqueros,
se volvieron tan celosos en hacer el bien,
como anteriormente lo habían sido en hacer el mal.

Tal vez algunos piensen que era muy atrevido por parte de ellos,
que fueran con tanta frecuencia a las '`casas del
campanario,`' y les hablaran a los sacerdotes.
Pero sin importar lo que alguien pueda juzgar con respecto a esto,
es cierto que esos maestros generalmente no producían los frutos de piedad,
como era bien sabido por aquellos que habían sido sacerdotes,
y que voluntariamente habían renunciado a sus ministerios
para seguir a Cristo en el camino de Su cruz;
estos eran algunos de los más celosos contra esa
sociedad en la que habían ministrado anteriormente.
Sin embargo,
ellos no eran partidarios de usar un lenguaje fuerte contra ningún maestro que,
según su conocimiento, le temiera verdaderamente a Dios,
sino que eran dirigidos a apuntar principalmente a los que sólo eran ricos en palabras,
y no producían verdaderos frutos cristianos, ni obras de justicia.
De ahí, que un tal Thomas Curtis,
que anteriormente había sido capitán en el ejército del Parlamento,
y después había ingresado a la sociedad del pueblo llamado Cuáqueros,
le escribió las siguientes palabras a Samuel Wells,
sacerdote de Banbury y perseguidor de los de esa persuasión: "`Para vergüenza tuya,
recuerda que yo sé que eres escandaloso.
Que sé cuán a menudo te has sentado anochecer tras anochecer a jugar cartas,
y que algunas veces pasaste noches completas jugando, y que en algunas ocasiones,
querías persuadirme a que yo jugara contigo por dinero.
Sin embargo,
en ese tiempo eras llamado por el mundo "`ministro,`" y ahora te has convertido en perseguidor,
etc.`"
Por tanto, nadie debe extrañarse,
del porqué los llamados Cuáqueros consideraban a estos maestros como "`asalariados.`"
Que había un gran número de este tipo,
se demuestra claramente cuando el rey Carlos II fue restaurado,
pues aquellos que anteriormente habían clamado contra el
Episcopado y su liturgia calificándola como falsa e idólatra,
luego se convirtieron en traidores y se pusieron la sobrepelliz^
footnote:[La prenda blanca usada por el clero Episcopal en Inglaterra.]
para mantenerse en posesión de sus vidas y beneficios.
Pero al hacerlo, estos hipócritas perdieron no pocos de sus oyentes,
porque esto les abrió los ojos a muchos,
y comenzaron a investigar en la doctrina de los despreciados Cuáqueros,
y vieron que ellos tenían un fundamento más seguro,
y que era eso lo que los hacía permanecer firmes contra la furia de la persecución.

Retomemos ahora el hilo de los eventos que tienen que ver con George Fox;
quien viajando por muchos lugares en el norte de Inglaterra,
tenía grandes reuniones en todas partes, si bien, de vez en cuando enfrentaba oposición,
algunas veces por lenguas, otras por manos.
En Derwentwater, en Northumberland, entró en una disputa acerca de la perfección,
y para probar su punto dijo que Adán y Eva habían sido perfectos antes de la caída,
que todo lo que Dios había hecho era perfecto,
y que la imperfección había venido por el diablo y la caída, pero que Cristo,
que había venido para destruir las obras del diablo, dijo: "`Sed perfectos.`"
Ante esto, uno de los profesantes respondió que Job había dicho,
'`¿Será el hombre mortal más limpio que su Hacedor?
Los cielos no están limpios ante Su vista.
Dios notó necedad en sus ángeles.`' Pero G. Fox le mostró su error,
y le dijo que no había sido Job el que había dicho eso,
sino uno de los hombres que contendían contra él. Entonces algunos profesantes
insistieron en que el cuerpo externo era el cuerpo de pecado y muerte,
pero G. Fox replicó que tanto Adán como Eva tenían un cuerpo externo
antes de que el cuerpo de pecado y muerte entrara en ellos,
y que el hombre todavía tendría cuerpo,
cuando el cuerpo de pecado y muerte fuera quitado de nuevo,
y ellos fueran renovados a la imagen de Dios por Cristo Jesús.

Así G. Fox encontraba servicio en casi todas partes,
y pasando a Hexham tuvo una gran reunión en la cima de una colina,
a la que el sacerdote del lugar había amenazado con llegar y oponerse,
pero no llegó. Continuando con su viaje llegó a Cumberland,
donde tuvo una reunión con muchos miles de personas en una colina cerca de Langlands.
En otra ocasión,
entró en la '`casa del campanario`' de Brigham antes de que llegara el sacerdote,
y les declaró la verdad a las personas, y cuando llegó el sacerdote,
este comenzó a oponerse, pero pronto se cansó y al final se fue.

Puesto que para entonces,
había varios más que también predicaban la doctrina de la
luz interior de Cristo que convence al hombre de pecado,
el número de profesantes de la luz se incrementó grandemente.
Al principio se había dicho que ellos serían destruidos en poco tiempo,
pero ahora los sacerdotes empezaron a decir que se empobrecerían unos a otros.
Porque después de las reuniones, muchos de ellos con un largo camino por delante,
se quedaban en las casas de los amigos durante el viaje,
y algunas veces había más personas que camas para alojarlos,
de modo que algunos tenían que dormir sobre montones de heno.
Esto hizo que algunos de la iglesia nacional temieran que tal hospitalidad causara pobreza,
y que cuando esos amigos se hubieran comido las provisiones de los demás,
necesitarían ser mantenidos por las parroquias, y por tanto,
que llegarían a ser una carga para ellos.

Pero resultó ser todo lo contrario, porque estas personas fueron las más bendecidas,
y aumentaron enormemente sin caer en la pobreza.
Esto me hace pensar en lo que una de las hijas del juez Thomas Fell me contó una vez,
a saber, que su padre,
en una ocasión que regresó a la casa con sus sirvientes
después de haber estado de viaje en el exterior,
encontró el cobertizo tan lleno de caballos de extraños que le dijo a su esposa:
"`Este es el camino a la ruina, porque pronto nos quedaremos sin heno.`"
Pero a esto Margaret respondió amigablemente, que ella no lo creía,
que cuando el año llegara a su fin no tendrían menos por haber compartido.
Y así resultó, porque ese año la reserva de heno que tenían era tan grande,
que vendieron una gran parte de lo que tenían en abundancia.
Así se verificó el proverbio, que '`la caridad no empobrece.`'

La verdad de esto también fue experimentada por el pueblo llamado Cuáqueros,
porque aunque al principio muchas personas eran tímidas y no querían
tratar con ellos porque no se conformaban a los saludos comunes,
y le hablaban a una persona usando el
"`__Ti__`" y el "`__Tú__`" en lugar del "`__Usted,__`" etc.,
de manera tal,
que algunos que eran comerciantes perdieron a todos sus
clientes y apenas podían obtener dinero para comprar pan;
con el tiempo esto cambió,
cuando las personas descubrieron por experiencia que podían confiar más en la
palabra de esta gente que en la palabra de los de su propia persuasión. De ahí,
que cuando alguien llegaba al pueblo y necesitaba algo, a menudo preguntaba:
"`¿Dónde hay un vendedor de telas, o un sastre, o un zapatero que sea Cuáquero?`"
Pero esto exasperó tanto a algunos otros, que empezaron a exclamar:
"`¡Si dejamos a estos Cuáqueros en paz,
nos van a quitar de las manos el comercio de la nación!`" Ahora bien,
la causa de que el comercio de ellos se incrementara así fue,
que se descubrió que eran honestos en sus tratos;
pues la integridad brillaba entre ellos por encima de muchos otros.
En efecto, el temor de Dios era lo que los llevaba a esta práctica,
y se exhortaban mutuamente a ello de vez en cuando.
G+++.+++ Fox también les escribió una epístola general como sigue:

[.embedded-content-document.epistle]
--

[.letter-heading]
Para todos ustedes, Amigos en todas partes, dispersos en el exterior:

En la medida de la vida de Dios en ustedes, esperen la sabiduría de Dios,
es decir, de Aquel de quien esta proviene.
Todos ustedes que son bebés de Dios, esperen la comida viva del Dios vivo,
a fin de ser nutridos para vida eterna de la única fuente de la que mana la vida.
Así todos podrán ser guiados y caminar ordenadamente; siervos en sus lugares,
hombres y mujeres jóvenes en sus lugares, y gobernantes de familias; para que todos,
en sus respectivos lugares adornen la Verdad en sus propias medidas de ella.
Mantengan sus mentes vueltas al Señor Jesús, de quien proviene la verdad,
para que sean de olor grato para Dios y sean ordenados y gobernados en sabiduría,
y puedan ser corona y gloria unos a otros en el Señor. Ninguna contienda, ni amargura,
ni egoísmo aparezca entre ustedes, sino condenen todas esas cosas con la luz,
en la cual está la unidad.

Que cada individuo vele y se ocupe de ordenar y gobernar su propia familia,
para que esta sea gobernada en justicia y sabiduría,
con el temor y pavor del Señor puestos en los corazones de todos,
para que todos puedan recibir los secretos del Señor
y convertirse en mayordomos de Su gracia,
para dispensar a todos según tengan necesidad.
Así todos serán guardados en el sentido del discernimiento correcto,
para que nada contrario a la vida pura de Dios brote en ustedes, ni entre ustedes,
sino que todo lo que sea contrario a ella sea juzgado.
De esta manera, todos podrán vivir en la luz, en la vida y en el amor,
y todo lo que es contrario a la luz, vida y amor será llevado a juicio,
y por medio de la luz será condenado.
Así, no habrá árboles sin fruto entre ustedes,
sino que todos serán cortados y condenados por la luz, y echados en el fuego,
para que todos puedan llevar y producir fruto para Dios,
y crecer fructíferos en Su conocimiento y en Su sabiduría. Que nadie parezca
ser algo en palabras más allá de lo que es en la vida que dio las palabras.
De esta manera nadie será como los higos prematuros,
o como esos árboles cuyo fruto se marchita; pues estos andan por el camino de Caín,
lejos de la luz, y por tanto, son condenados por la luz.
Que nadie entre ustedes se gloríe por encima de su medida,
porque al hacerlo se excluyen a sí mismos del reino de Dios.
Pues el orgullo y las contiendas se levantan en la parte jactanciosa,
la cual es contraria a esa luz que conduce al reino de Dios,
y que otorga tanto una entrada en él,
como un entendimiento para saber lo que le pertenece.

No se hagan ninguna imagen o semejanza,
sino esperen en la luz que traerá condenación sobre la parte que quiere hacer imágenes,
pues esa parte oprime al Justo.
No presenten su ojo o su carne a la lujuria,
porque la vanagloria de la vida descansa sobre eso
que los mantiene fuera del amor del Padre,
y sobre esto permanecen Sus juicios y Su ira.
Porque donde los hombres buscan el amor del mundo y la corona mortal, ahí entra el mal,
lo cual está maldito y produce espinos y abrojos.
Ahí reina la muerte, y la tribulación y la angustia están sobre cada alma,
y se oye la lengua egipcia; todo lo cual es condenado por la luz.
Ahí está esa tierra que debe ser removida (según es vista por medio de la luz),
sacudida de su lugar y eliminada por el poder.
Por tanto,
todos ustedes cuyas mentes están vueltas a esta luz (que
trae condenación sobre todas esas cosas antes mencionadas,
que son contrarias a la luz),
esperen en el Señor Jesús la corona que es inmortal y que no se desvanece.

[.signed-section-signature]
G+++.+++ F.

--

La epístola fue enviada para ser leída en las reuniones de sus amigos.
No mucho después, cierto sacerdote de Wrexham, en Gales, cuyo nombre era Morgan Floyd,
envió a dos miembros de su congregación al norte de Inglaterra,
para que investigaran qué tipo de personas eran los Cuáqueros.
Al llegar estos dos ahí, fueron convencidos de la doctrina de ellos y la abrazaron,
y luego, después de quedarse un tiempo, regresaron a casa.
Uno de estos era llamado John ap-John,
un hombre que continuó fiel y se convirtió en ministro del evangelio que había recibido;
pero el otro se apartó de su convicción después.

Veamos ahora brevemente los asuntos de estado en Inglaterra.
Ya hemos visto cómo el poder de Cromwell había llegado a ser tan grande,
que se aventuró a disolver el Parlamento y convocar otro en su lugar.
Pero antes de que terminara el año,
este Parlamento renunció al poder y lo entregó en manos de Cromwell,
de quien lo habían recibido.
Así él, con su consejo de oficiales de campo,
se vio de nuevo en posesión del gobierno supremo.
Y no pasó mucho tiempo antes de que este consejo declarara,
que a partir de ese momento el gobierno principal
de la nación debía ser confiado a una sola persona,
y esa persona debía ser Oliver Cromwell,
general en jefe de todas las fuerzas en Inglaterra, Escocia e Irlanda.
Que su título debía ser '`Lord Protector de la Mancomunidad`' de Inglaterra,
Escocia e Irlanda, y de todos los dominios que le pertenecen a esta.
Y que él debía tener un consejo de veintiún personas para asistirlo en el gobierno.

Habiéndose establecido así el asunto, se les ordenó a los comisionados del Gran Sello,
al alcalde mayor y a los concejales de Londres,
que debían asistir a Cromwell y a su consejo el 16 de Diciembre en Westminster-hall.
Una vez ahí,
Cromwell se quitó el sombrero mientras se leían los términos
del gobierno (por los que fue declarado Lord Protector).
Luego, el mayor-general Lambert se arrodilló y le presentó una espada envainada,
representando la espada civil.
Cromwell aceptó la espada y luego se quitó la suya,
para indicar que ya no gobernaría con la espada militar.
Dicho documento escrito en pergamino, contenía los siguientes detalles:
Que el protector debía convocar un Parlamento cada tres años;
la primera reunión del Parlamento debía ser el 13 de Septiembre siguiente;
él no podía disolver un Parlamento antes de que se hubiera reunido cinco meses;
los proyectos de ley que se le presentaran para su
consentimiento debían tener la fuerza de leyes,
si no los confirmaba en el plazo de veinte días;
debía tener un consejo no mayor de veintiún personas, ni menor de trece;
inmediatamente después de su muerte, el consejo debía escoger otro protector;
ningún protector después de él podía ser general en jefe del ejército;
debía estar en poder del protector hacer la guerra y la paz.
Mientras se leía el documento, Cromwell tenía su mano sobre una biblia,
y después juró que realizaría todo lo que estaba especificado en este.
Una vez hecho esto, se puso el sombrero en la cabeza,
mientras todos los otros permanecían descubiertos.
Luego los comisionados le entregaron el sello y el alcalde de Londres la espada;
todo lo cual él restauró de nuevo con una exhortación a usarlos bien.
Después de esto, el general Lambert llevó la espada delante de él al palanquín^
footnote:[Especie de andas para llevar en ellas a personas importantes.]
real, en el que fue llevado a Whitehall, donde fue proclamado protector,
lo que también se hizo en la ciudad de Londres.
A partir de entonces, fue atendido como un príncipe y nombró caballeros,
como solían hacer los reyes.
De esta manera Cromwell, por un muy extraño y sorprendente giro de los asuntos mundiales,
se encontró instalado en el palacio,
del que él y sus seguidores habían expulsado al rey Carlos I.
