== Capítulo IV

[.section-date]
1654

[.chapter-synopsis]
* Un convencimiento general
* Aumento de ministros
* Primeros Cuáqueros en Londres
* F. Howgill y el protector
* Primera reunión establecida en Londres
* Persecución de los Cuáqueros en Bristol
* El protector y la libertad de consciencia
* Crueldades practicadas en Bristol
* R. Hubberthorn convencido
* G. Whitehead convencido
* El bárbaro abuso contra Elizabeth Heavens y Elizabeth Fletcher en Oxford
* Notable relato de Barbara Blaugdone
* M. Halhead y J. Lancaster en Irlanda y Escocia
* G. Fox en Yorkshire y Lincolnshire
* G. Fox disputa con el sacerdote Stevens
* G. Fox enviado prisionero a Londres
* Su conversación con el protector
* Transacciones públicas
* J. Crook convencido
* Relato de W. Caton
* Luke Howard convencido
* Relato de S. Fisher.

Al principio del año 1654, al verse investido con la autoridad suprema de la nación,
Oliver Cromwell exigió el juramento de fidelidad,
tanto de los soldados como de los demás. Esto les ofreció
una oportunidad conveniente a los que entre los soldados
habían sido convencidos de la doctrina de los llamados Cuáqueros,
para dejar el servicio militar, porque cuando se les solicitaba el juramento,
declaraban que en obediencia al mandamiento de Cristo no podían jurar;
después de lo cual eran despedidos.
Entre estos estaba John Stubbs, un hombre con habilidades no sólo en Latín,
Griego y Hebreo, sino también en idiomas orientales.
Él fue convencido por G. Fox, cuando George estaba en prisión en Carlisle,
y posteriormente se convirtió en un fiel ministro del evangelio.
Pero había entre los soldados algunos que habían sido convencidos en su opinión,
pero no continuaron firmes e hicieron el juramento requerido.
No mucho después, marchando hacia Escocia y pasando por una guarnición ahí,
les dispararon a algunos de ellos (pensando que eran enemigos),
por lo que varios murieron.

Al ver G. Fox las iglesias de sus amigos establecidas en el norte,
se fue de Swarthmore (donde había estado desde principios de este año) a Lancaster,
y de ahí a Synder-hill-green, donde tuvo una gran reunión con miles de personas,
entre quienes había muchas de renombre.
Un gran número de los presentes se convencieron,
por lo que muchos entraron en la comunión de los llamados Cuáqueros.
Por esta época Ambrose Rigge también se unió a este pueblo;
quien desde su juventud se había inclinado a la piedad,
y después de oír a G. Fox predicar, se convenció de la verdad de su doctrina,
la recibió y se convirtió en profesante de ella,
aunque por esa razón fue expulsado por sus padres y parientes.

Hemos visto el primer surgimiento de estos Cristianos
(llamados Cuáqueros) en el norte de Inglaterra,
y cómo aumentaron bajo la opresión de la persecución,
de modo que en la mayoría de los lugares de esas regiones se fijaron reuniones.
Queda por relatar cómo se extendieron aún más.

En ese entonces se habían levantado entre ellos unos sesenta ministros de la palabra,
los cuales habían salido al servicio del evangelio,
para volver a las personas (dondequiera que encontraran
oportunidad) de las tinieblas a la luz,
y del poder de Satanás a Dios.
De estos, Francis Howgill y Edward Burrough fueron a Londres;
John Camm y John Audland a Bristol; Richard Hubberthorn y George Whitehead a Norwich;
Thomas Holmes a Gales, y otros fueron por otros caminos.
G+++.+++ Fox, sabiendo bien que esta era una obra pesada,
les escribió una extensa epístola a esos ministros,
en la que los amonestaba a la prudencia,
aconsejándolos a experimentar en sí mismos la Semilla
de Dios que hiere la cabeza de la serpiente,
a experimentar el poder de Dios y la cruz de Cristo,
a recibir sabiduría de Dios mediante la luz,
y a no apresurarse o correr en sus propias voluntades, sino continuar en paciencia.

Primero mencionaré algo de los acontecimientos en Londres,
donde Edward Burrough y Francis Howgill,
con Anthony Pearson (quien había sido juez de paz) llegaron a principios del verano.
Howgill y Pearson fueron los primeros del pueblo llamado
Cuáqueros en tener una reunión en esa gran ciudad,
donde predicaron en la casa de un tal Robert Dring, en Watling-street.
Edward Burrough, según lo que se me ha informado,
ese día estaba en una asamblea de una sociedad separada.
También me dijeron que Ruth, la esposa de William Crouch, comerciante en Londres,
había dicho que un poco antes de ese momento,
se habían reunido unas pocas personas en la misma casa,
de las cuales ella era una y Anne Downer (que luego se casó con George Whitehead).
También se dice que una tal Isabella Buttery (y otra mujer),
habiendo repartido algunos libros en Londres,
entre ellos uno de G. Fox llamado __"`The Way to the Kingdom,`"__^
footnote:[El Camino al Reino]
se había reunido con ese pequeño grupo,
en el que sólo había dos o tres hombres (uno de los
cuales era el ya mencionado Amos Stoddard,
que anteriormente había sido oficial militar),
y que en algunas ocasiones había pronunciado unas pocas palabras
en esa pequeña reunión. Pero las cosas empezaron a cambiar cuando
Francis Howgill y Edward Burrough llegaron a Londres,
porque ellos aprovecharon todas las oportunidades que pudieron para predicar el evangelio.

En Londres se acostumbra en la época de verano,
cuando se acerca la noche y los comerciantes dejan de trabajar,
que muchos jóvenes de contextura robusta,
se reúnan en los campos para probar su habilidad y fuerza en la lucha; generalmente,
una gran cantidad de personas se paran en círculo para mirar.
Sucedió que Edward Burrough pasó por el lugar donde estaban luchando,
y de pie entre los espectadores vio cómo un sujeto fuerte
y hábil ya había arrojado al suelo a otros tres,
y estaba esperando a un cuarto campeón, si es que alguno se atrevía a entrar.
Finalmente, como no hubo alguien suficientemente audaz para intentarlo,
E+++.+++ Burrough entró en el espacio de pelea, y al mirar al luchador con un semblante serio,
el hombre se sorprendió mucho,
porque en lugar de un antagonista pavoneándose,
se encontró con un joven sobrio y solemne.
Todos estaban atónitos ante esta escena,
esperando ansiosamente saber cuál sería el resultado de este combate; sin embargo,
E+++.+++ Burrough estaba enfocado en una pelea completamente diferente.
Pues después de haber peleado contra la maldad espiritual
que una vez había prevalecido sobre él,
y haber vencido en alguna medida por la gracia de Dios,
ahora se esforzaba por pelear contra la misma en otros,
y por volverlos de la maldad de sus caminos.
Con esa intención les comenzó a hablar muy seriamente a los espectadores,
y alcanzó los corazones con un poder tan penetrante,
que fue oído por esta variedad de personas con no menos atención que admiración,
pues el discurso procuraba volverlos de las tinieblas a la luz,
y del poder de Satanás a Dios.
Él luchó con palabras convincentes,
mostrando que Dios no se había quedado sin testimonio,
sino que le había dado al hombre una medida de Su gracia,
y que había alumbrado a todos con la luz de Cristo.
De esta forma predicó celosamente,
y aunque muchos consideraron eso como una rareza, de todos modos tuvo efecto,
ya que algunos fueron convencidos de la Verdad.
Pues Burrough era una quebrador de corazones de piedra, y por eso,
no fue injustamente llamado (por cierto autor) "`hijo
del trueno,`" aunque en su debido momento,
también pronunciaba palabras de consuelo a los que
tenían un corazón quebrantado y un espíritu contrito.

Sin embargo, tronar contra el pecado y la iniquidad era su talento peculiar, tanto,
que una vez predicando muy celosamente en una reunión,
y percibiendo que había algunas almas contritas que
necesitaban alimento espiritualmente refrescante,
se le oyó decir, que aunque la predicación de ese momento no era leche para bebés,
los iba a recordar pronto y les iba a ministrar a ellos también,
pero que en ese momento debía trillar a la ramera.
De hecho, él era uno de esos valientes cuyo arco nunca volvía atrás,
ni su espada regresaba vacía de la matanza de los poderosos,
porque el Señor bendijo su poderoso ministerio con un éxito muy glorioso.
En realidad, él fue un instrumento tan excelente en la mano de Dios,
que incluso algunos hombres poderosos y eminentes,
fueron alcanzados hasta el corazón por el poder de la palabra de vida que él predicaba.
Y aunque carbones de fuego, por decirlo así,
salían de su boca para consumir cardos y espinos, y al pasar por sendas apartadas,
hollaba abrojos y cizañas silvestres,
su sana doctrina goteaba como aceite de gozo sobre los espíritus de los dolientes
en Sion. De ahí que Francis Howgill no dijera injustamente de él cuando murió:
"`¿Desgastarán los días, los meses o los años tu nombre como si no hubieras existido?
¡Oh, no! ¿Acaso no vivirán en generaciones por venir tus nobles y valientes actos,
y las poderosas obras que realizaste a través del
poder de Aquel que te separó desde el vientre?
¡Oh, sí! Los niños que todavía no han nacido te tendrán en sus bocas,
y tus obras testificarán de ti en las generaciones que aún no existen.`"

El mencionado Howgill, también un hombre eminente y elocuente,
estando entonces en Londres,
fue a la corte a comunicarle a Oliver Cromwell lo que estaba en su mente.
Y después de hablarle, creyó conveniente expresarse más por escrito,
tal como lo hizo en la siguiente carta:

[.embedded-content-document.letter]
--

Amigo, el Señor me movió a ir a ti, a declarar la palabra del Señor,
y a tratar claramente contigo tal como me fue ordenado; no para pedirte algo,
sino para declarar lo que el Señor me había revelado con respecto a ti.
Y cuando entregué lo que me había sido ordenado,
te preguntaste si era la palabra del Señor o no,
y buscaste eludirla mediante tu razón. Ya hemos esperado algunos días,
pero como no he podido hablar contigo de nuevo,
fui movido a escribirte y aclarar mi consciencia, y luego dejarte.

Por tanto, oye la palabra del Señor. Así dice el Señor:
"`Te escogí entre las naciones cuando eras pequeño ante tus propios ojos,
y derribé las montañas y los poderes de la tierra delante de ti,
los cuales habían establecido la maldad como ley.
Los abatí, quebranté los yugos y rompí las ataduras del opresor,
y los hice inclinarse delante de ti; y los hice como una llanura delante de ti,
para que pasaras sobre ellos y pisaras sus cuellos.`"
Pero así dice el Señor: "`Tu corazón ya no es recto delante de Mí. Tomas consejo,
pero no de Mí. Estás estableciendo la paz,
pero no por medio de Mí. Estás implementando leyes,
pero no por medio de Mí. Mi nombre no es temido, ni Soy buscado,
sino que estableces tu propia sabiduría. ¡Qué! ¿He derribado
a todos los opresores y quebrantado sus leyes,
y ahora tú estás a punto de establecerlas de nuevo,
y vas a edificar nuevamente lo que he destruido?
¿Me limitarás tú? ¿Me pondrás fronteras en cuanto a cuándo, dónde,
cómo y por medio de quiénes Me declararé y publicaré Mi nombre?
Romperé tu cordón y removeré tu estaca, y Me exaltaré en tu derrocamiento.`"

Por tanto, esta es la palabra del Señor para ti, sea que la oigas o la rechaces:
"`Si no quitas todas esas leyes que se han hecho con respecto a la religión,
por medio de las cuales el pueblo que es amado a Mis ojos es oprimido,
no serás establecido,
sino que así como has pisoteado a Mis enemigos por medio de Mi poder,
serás pisoteado por Mi poder y sabrás que Yo soy el Señor.
Porque Mi evangelio no será establecido por tu espada,
ni por tu ley, sino por Mi fuerza, Mi poder y Mi Espíritu.`"
Para ti esta es la palabra del Señor: "`No limites al Espíritu eterno,
por medio del cual publicaré Mi nombre, en cuanto a cuándo, dónde y cómo lo haré;
porque si lo haces, serás como polvo delante del viento.
La boca del Señor lo ha dicho y Él cumplirá Su promesa.
Porque esto es lo que busco de tus manos, dice el Señor:
Suelta las cargas de opresión y deja ir libres a los quebrantados.
¿Acaso no hay muchos encerrados en prisión, algunos están en cepos,
algunos han sido apedreados, y algunos han sido tratados vergonzosamente?
Algunos han sido juzgados como blasfemos por los que no conocen al Señor,
y por medio de esas leyes que han sido hechas por la voluntad del hombre,
y que no están en la voluntad de Dios.
Algunos sufren ahora debido a que no pueden sostener los tipos y sombras,
porque para ellos esto sería negar que Cristo vino en la carne.
Algunos han sido encerrados en prisión porque no juraron,
y porque permanecen en la doctrina de Cristo.
Algunos, por declarar abiertamente contra el pecado en los mercados,
han sufrido como malhechores.
Si tú permites que ellos sufran así por esas leyes, y lo consideras justicia,
visitaré por esas cosas,
dice el Señor. Quebrantaré el yugo de sus cuellos y traeré liberación de otro modo,
y tú sabrás que Yo soy el Señor.`"

Un siervo de la Verdad,
movido por el Señor a declarar y a escribir esto por el bien de Jesús,
y un amante de tu alma llamado,

[.signed-section-signature]
Francis Howgill.

[.signed-section-context-close]
El último día del Primer mes, cerca de la hora novena; esperando en James`'s Park,
en Londres.

--

Cómo fue recibido esto por él, no lo sé; pero esto he entendido,
que algunos de los siervos de Cromwell (y entre estos un tal Theophilus Green, y Mary,
después la esposa de Henry Stout),
fueron tan alcanzados por el discurso de Francis Howgill,
que luego de un tiempo entraron en la sociedad de los llamados Cuáqueros.

En la carta o discurso arriba mencionado,
encontramos que se hizo mención de leyes hechas en relación a la religión.
No creo que esto se refiera a alguna nueva ley hecha por el propio Cromwell,
sino a las que habían sido hechas en el pasado,
las cuales él pudo haber alterado si hubiera estado dispuesto a hacerlo;
tal como sucedió luego,
pues muchas leyes penales fueron abrogadas bajo el
reinado del rey William y de la reina María,
como se dirá en su momento.
Porque no encuentro que en tiempos de Cromwell se hicieran leyes que obligaran
a las personas a asistir al culto de la iglesia pública o nacional.
Pero a pesar de ello,
en ese tiempo los llamados Cuáqueros eran encarcelados por rehusarse a jurar,
o por no pagar diezmos para mantener a los sacerdotes.
Además,
eran azotados como vagabundos por predicar en los mercados o en otros lugares públicos;
o eran multados por no quitarse sus sombreros delante de
los magistrados (pues eso era llamado desacato a la magistratura).
Y cuando por motivo de consciencia se rehusaban a pagar tales multas,
el despojo de bienes o los encarcelamientos se convertían en su porción. Y así,
siempre se encontraba una excusa para perseguirlos,
y a la maldad nunca le faltaban pretextos para fastidiarlos.
También sucedía a menudo,
que los principales de varias sectas cristianas se
oponían a Edward Burrough y Francis Howgill,
por lo que se suscitaban disputas,
lo cual muchas veces les dio ocasión a algunos de los oyentes de
abrazar la doctrina que era sostenida por Burrough y Howgill;
esto enfurecía tanto a sus enemigos,
que esparcían calumnias y algunas veces los tachaban de brujos.

Mientras tanto, el pueblo llamado Cuáqueros se incrementó a tal punto en Londres,
que empezaron a tener reuniones fijas, la primera de las cuales fue en Aldersgate Street,
en la casa de Sarah Sawyer.
La primera mujer de esta sociedad que predicó públicamente en Londres,
fue Anne Downer (ya mencionada), quien después se casó con un tal Greenwell,
y luego de enviudar, con el paso del tiempo se casó con George Whitehead,
como ya ha sido apuntado.
Otra de las reuniones de este pueblo en Londres, se realizaba en la casa de un tal Bates,
en Tower Street, y otra en la casa de Gerard Robert, en Thomas Apostles;
hasta que la iglesia se hizo tan grande,
que una casa conocida por el nombre de "`Bull and Mouth,`" en Martin`'s le Grand,
cerca de Aldersgate,
fue alquilada como '`casa de reunión.`' Como este
edificio le había pertenecido a un hombre rico,
tenía un gran salón en el que cabían muchas personas,
por lo que era muy conveniente como lugar de reunión.

En ese entonces,
se habían escrito y repartido una gran cantidad de libros contra los Cuáqueros,
escritos por los sacerdotes y maestros de varias sectas,
en los que los tildaban de seductores y falsos profetas; pues estos sacerdotes,
al darse cuenta de que muchos de sus oyentes los habían abandonado,
no dejaron piedra sin remover para detener la deserción.
Pero el resultado no respondió a sus esperanzas,
porque Burrough y Howgill no permitieron que estos escritos quedaran sin respuesta,
sino que expusieron la malicia y las cosas absurdas escritas por esos escritores.

Dejándolos ocupados en esta obra, nos dirigiremos hacia Bristol,
para observar el esfuerzo de John Audland y Thomas Airey,
quienes habían llegado a la ciudad en el mes llamado julio de este
año. Al entrar en las reuniones de los Independientes y Bautistas,
encontraron oportunidad de predicar la Verdad allí,
y también tuvieron ocasión de hablarles a otros,
de modo que muchos recibieron su testimonio.

De ahí ellos se fueron a Plymouth, en Devonshire, y luego a Londres,
donde se encontraron con John Camm, pero después de una corta estadía ahí,
John Audland regresó a Bristol con John Camm,
donde encontraron una puerta abierta para su ministerio.
Entre los que habían recibido su testimonio estaba Josiah Cole, George Bishop,
Charles Marshal y Barbara Blaugdone, de quienes se hablará más en su momento.
No había pasado mucho tiempo antes de que F. Howgill y E. Burrough,
tras haber reunido una iglesia en Londres, llegaran también a Bristol, donde a la sazón,
estaba empezando a aparecer la persecución abiertamente,
pues los magistrados les habían ordenado salir de la ciudad y de los alrededores.
Ante esto respondieron, que ellos no habían llegado en la voluntad del hombre,
y que cuando Aquel que los había movido a llegar, los moviera a salir, le obedecerían;
que si ellos eran culpables de la transgresión de alguna ley,
estaban dispuestos a sufrir por ello, pero que como ingleses nacidos libres,
estaban libres de la transgresión de alguna ley;
y que si eran expulsados de la ciudad por medio de la violencia,
estaban listos a sufrirla y no se resistirían, etc.
Pero entonces los sacerdotes, especialmente un tal Ralph Farmer,
empezaron a incitar y a enfurecer a la gente,
y a incendiar a la ciudad (por decirlo así).

Cuando John Camm y John Audland cruzaban un puente
camino a Brislington (a unas dos millas de Bristol),
donde tenían la intención de tener una reunión,
fueron asaltados por la chusma de la ciudad y por
varios aprendices de la parroquia de Ralph Farmer,
los cuales se habían reunido ahí, al ser avisados de la llegada de ellos.
La chusma abusó violentamente de ellos con golpes, patadas y gritando continuamente:
"`¡Derríbenlos! ¡Mátenlos! ¡Cuélguenlos ahora mismo!`"
Así fueron conducidos de regreso y forzados a entrar a la ciudad de nuevo,
escapando por poco con sus vidas.
Pero el tumulto no cesó, porque se les oyó decir a algunos de la multitud,
que la chusma encontraría más protección de los magistrados
que esos extranjeros Camm y Audland.
Pero los oficiales de la guarnición,
pensando que era injustificable permitir tal tumulto (ya que no les faltaba
razón de temer que los monárquicos o cómplices del rey Carlos,
se pudieran apoderar de tal oportunidad para levantar una insurrección),
hicieron que tres de los cabecillas fueran capturados.
Pero esto provocó tal revuelo,
que al día siguiente más de quinientas personas (según se creía) se reunieron
de manera sediciosa y lograron la libertad de sus compañeros.
Esto hizo que la turba alborotadora se volviera más audaz y descarada,
especialmente tras oír que los magistrados les habían ordenado
a John Camm y John Audland que salieran de la ciudad.

Entonces,
la desenfrenada multitud no dudaba en entrar violentamente
a las casas de los llamados Cuáqueros en Bristol,
bajo la pretensión de impedir planes de traición. Y cuando algunos con celo les
decían a los sacerdotes que esos eran los frutos de la doctrina de ellos,
los revoltosos incitaban al pueblo aún más,
e inducían a los magistrados a encarcelar a algunos de los llamados Cuáqueros.
Esto instigó a la chusma a tal grado,
que esta pensaba tener plena libertad de usar toda
clase de insolencia contra dicho pueblo--golpeándolos,
apaleándolos, empujándolos, y a menudo pisándolos hasta que derramaran sangre;
pues ellos se habían convertido en presa de todos los insolentes,
como un pueblo que estaba fuera de la protección de la ley.
Esto empezó a causar disturbios en la ciudad,
y algunos han dicho (y con toda razón) que los jóvenes
aprendices que estaba activos en esa obra,
no se habrían atrevido a dejar sus empleos si sus señores no les hubieran dado permiso.
Y cierta persona les informó al alcalde y a los concejales bajo juramento,
que había oído a un aprendiz decir,
que ellos en realidad tenían permiso de sus señores y eran animados a actuar así.

Entonces se dictó una orden de la corte,
según la cual los alguaciles tenían que hacer un
registro diligente dentro de sus diversos distritos,
en busca de todos los extranjeros y personas sospechosas;
y que toda persona debía ser advertida de no estar
presente en ningún tumulto u otra asamblea ilegal,
ni de reunirse en grupos o multitudes en las calles,
so pena de ser castigada de acuerdo a la ley.
Pero esta orden no sirvió de mucho,
porque los grupos tumultuosos y los disturbios continuaron, y en una ocasión,
mientras se leía una proclama en nombre del protector
en la que se exigía que todos se marcharan,
se oyó a algunos de los alborotadores decir:
"`¡¿Por qué nos hablan en nombre del protector?
Que nos hablen en nombre del rey Carlos!`"
Mientras tanto, los llamados Cuáqueros eran mantenidos en prisión,
y claramente parecía que la orden contra las asambleas ilegales
había sido dirigida contra las reuniones de ellos.
Y aunque los magistrados pretendían que ellos debían responder ante el protector,
si dejaban en paz a los Cuáqueros sin perturbar sus reuniones (las cuales en ese tiempo,
en la mayoría de los casos, se celebraban en silencio,
y nada se decía excepto cuando de vez en cuando alguno
de sus ministros de fuera las visitaban),
aun así,
esto no concordaba del todo con el discurso que el protector
dio en el Parlamento el 12 del mes llamado septiembre,
en la cámara pintada, donde dijo las siguientes palabras:

[.embedded-content-document]
--

"`¿Acaso no es fundamental la libertad de consciencia en la religión? Puesto
que existe libertad para que el magistrado supremo ejercite su consciencia,
erigiendo cualquier forma de gobierno eclesial que le satisfaga establecer,
¿por qué no les debería dar esa libertad a otros?
La libertad de consciencia es un derecho natural, y aquel que la quiera tener,
debe también darla.
De hecho, esta ha sido la vanidad de nuestros conflictos, cada secta dice:
'`Dame libertad de consciencia,`' pero cuando se le da,
luego no se la quiere ceder a nadie más. ¿Dónde está
nuestra sabiduría? Ciertamente esto debe ser recíproco.
El magistrado tiene su supremacía y puede establecer la religión de acuerdo a su consciencia.
Y les puedo decir, y lo digo,
que todo el dinero en la nación no habría tentado a los hombres
a luchar por la causa con la que se habían comprometido,
si no hubieran tenido esperanzas de libertad de consciencia--más
de la que tenían del Episcopado,
o habrían tenido de un Presbiterio escocés, o de un inglés, si hubieran dado tales pasos,
o hubieran sido tan agudos y rígidos como amenazaron
ser cuando se establecieron la primera vez.
Digo que esto es fundamental; así debe ser.
Es por nosotros y por las generaciones venideras.`"

--

Cromwell habló más confirmando estas cosas; y en realidad, habría sido un hombre noble,
si realmente hubiera ejecutado lo que afirmó aquí con argumentos vinculantes.
Pero aunque entonces parecía desaprobar el comportamiento del Presbiterio
(porque en ese momento estaba a favor de la Independencia),
después de un tiempo empezó a cortejar a los Presbiterianos,
y estos entonces lo adulaban desde el púlpito como
su preservador y restaurador de la iglesia,
y permitió que los Cuáqueros fueran perseguidos bajo su gobierno,
aunque pretendía no saberlo,
cuando fácilmente habría podido detener la persecución. Sin embargo,
por ponerle atención a la adulación del clero, finalmente perdió su reputación,
incluso entre aquellos con quienes había luchado por la libertad común. Y así, al final,
después de su muerte,
parece que trajo sobre sí mismo la maldición que
había pronunciado en el mencionado discurso,
si alguna vez se apartaba de permitir la libertad de consciencia.
Pues en dicha ocasión dijo además, que la libertad era un fundamento del gobierno,
y que había costado mucha sangre obtenerla, incluso al punto de arriesgarlo todo.
Y en conclusión dijo:
"`Yo estaría más dispuesto a ser lanzado a la tumba y ser enterrado con infamia,
que dar mi consentimiento a la eliminación deliberada de tal gobierno.`"
Quién no conoce la infamia que le sobrevino después,
cuando en el reinado de Carlos II su cadáver fue exhumado y enterrado cerca de las horcas,
como será mencionado en su debido lugar.^
footnote:[Su cuerpo fue colgado con cadenas en Tyburn, Londres,
y después fue arrojado a un pozo.
Su cabeza fue cortada y expuesta en un poste fuera de Westminster Hall hasta 1685.]

Ahora regreso a Bristol,
donde varios seguían en prisión sin que se les hubiera concedido algún tipo de libertad,
e incluso eran culpados de lo que ellos habían negado enfáticamente ser culpables.
Entre estos,
un tal John Worring estaba acusado de haber llamado demonio al sacerdote Samuel Grimes;
pero Worring lo negó,
aunque no dudó en decir que podía probar algo similar con las propias palabras del sacerdote.
Y cuando se le preguntó cómo lo probaría,
respondió que el sacerdote había declarado en la
reunión que él pecaba en todo lo que hacía,
y que si él pecaba en todo,
entonces lo mismo era cierto en su predicación como en otras cosas,
y que las Escrituras sostienen: "`El que practica el pecado es del diablo.`"
Puede suponerse fácilmente que esta respuesta no les agradó a los seguidores del sacerdote,
y por tanto,
Worring y algunos otros fueron mantenidos en prisión. Entre
estos prisioneros estaba también Elizabeth Marshall,
quien en la '`casa del campanario,`' después de que John
Knowls despidió a las personas con la llamada bendición,
le habló a él diciendo: "`Esta es la palabra del Señor para ti:
Te exhorto a que te arrepientas y a que prestes atención a la luz de Cristo en tu consciencia.`"
Y cuando las personas, por orden de los magistrados en ese momento presentes,
cayeron sobre ella golpeándola violentamente con bastones y palos, ella gritó:
"`¡El día poderoso del Señor está cerca,
en el que Él infundirá terror sobre los malvados!`"
En algún momento antes de esto,
ella le había hablado también al sacerdote Ralph Farmer (antes mencionado) en la '`casa
del campanario,`' después de que él había terminado su sermón y la oración,
y le dijo: "`Esta es la palabra del Señor para ti: Ay, ay, ay,
del Señor para los que toman la palabra del Señor en sus bocas,
y el Señor no los ha enviado.`"

[.offset]
Un buen rato después de esto, los magistrados emitieron la siguiente orden judicial:

[.embedded-content-document.legal]
--

[.signed-section-context-open]
Ciudad de Bristol

[.salutation]
A todos los alguaciles dentro de esta ciudad, y para cada uno de ellos.

Ya que se nos ha informado que John Camm y John Audland, dos extranjeros,
a quienes se les ordenó salir de esta ciudad,
en desacato a la autoridad han regresado para perturbar la paz pública; por tanto,
se emiten estas órdenes para pedirles y mandarles que los detengan
inmediatamente y los traigan delante de nosotros para interrogarlos,
de acuerdo a la ley.
Dado el 22 de enero de 1654.

[.signed-section-closing]
Firmado,

[.signed-section-signature]
William Cann, Richard Vickirs, asistente de alcalde Joseph Jackson, Henry Gibbs,
Gabriel Sherman, John Lock.

--

Camm y Audland se habían marchado de la ciudad antes de esa fecha,
sin nunca haber recibido una orden (como dice la orden judicial) de salir de la ciudad,
ni de los propios magistrados, ni de nadie más a sus órdenes;
aunque sí se les había obligado hacerlo a Francis Howgill y Edward Burrough.
Como esta orden judicial resultó ineficaz,
los magistrados hicieron que se escribiera otra con estas palabras:

[.embedded-content-document.legal]
--

[.signed-section-context-open]
Ciudad de Bristol

[.salutation]
A los alguaciles de la paz del distrito de +++_________+++ y a cada uno de ellos.

Ya que se nos ha informado bajo juramento,
que ciertas personas de la orden Franciscana de Roma han llegado últimamente a Inglaterra,
y bajo el concepto de Cuáqueros han reunido a varias multitudes de personas en Londres;
y considerando que ciertos extranjeros, bajo el nombre de John Camm, John Audland,
George Fox, James Nayler, Francis Howgill, Edward Burrough y otros desconocidos,
han venido recientemente a esta ciudad, y de igual manera,
bajo el concepto de Cuáqueros han reunido multitudes de personas
tras ellos y ocasionado grandes disturbios entre nosotros;
y dado que por dicha información nos parece muy probable y muy sospechoso,
que estas personas que han llegado últimamente sean algunas de las que llegaron de Roma,
como se ha dicho; por tanto,
se emite esta orden en nombre de su alteza el señor protector para pedirles y mandarles,
que hagan una búsqueda diligente de los mencionados extranjeros en sus distritos,
o de cualquiera de ellos, y de toda persona sospechosa,
que los detengan y los traigan delante de nosotros
para interrogarlos y tratarlos de acuerdo a la ley.
No fallen en esto.
Dado el 25 de enero de 1654.

[.signed-section-closing]
Firmado,

[.signed-section-signature]
John Gunning, alcalde William Cann, Gabriel Sherman, Joseph Jackson, Henry Gibbs,
John Lock, George Hellier, Richard Vickirs.
Gabriel Sherman.

--

Los magistrados firmaron y pusieron sus sellos, y el concejal Sherman,
para asegurarse de que su nombre estuviera entre ellos, lo escribió dos veces.
Ahora bien,
incluso un niño podría percibir cuán frívola era la pretensión
de que estos hombres eran de la orden Franciscana,
pues los Cuáqueros se habían multiplicado tanto para ese momento en el norte de Inglaterra,
que ya no podían ser considerados un pueblo desconocido.
Y en cuanto a George Fox y James Nayler, aún no habían estado en Bristol, y por tanto,
era absurdo buscarlos ahí. Pero se pensó conveniente
etiquetar a los Cuáqueros con nombres odiosos,
so pretexto de perseguirlos como perturbadores de la paz pública.
Esto quedó claro en el caso de Thomas Robertson y Josiah Cole,
quienes estando en la '`casa del campanario`' en Nicholas,
y quedándose quietos sin decir una palabra hasta que el
sacerdote Hazzard terminó y despidió a las personas,
fueron muy rudamente tratados.
Porque cuando Thomas estaba a punto de levantar su voz,
incluso cuando la palabra estaba todavía en su boca,
fue golpeado en la cabeza por muchos, así como también su compañero,
aunque él ni siquiera había intentado hablar.
Pero Thomas, después de haberse recuperado un poco de un pesado golpe,
empezó a hablar de nuevo y les dijo a las personas:
"`Tiemblen delante del Señor y la palabra de Su santidad.`"
Pero esto les encendió tanto su ira,
que estos dos hombres fueron sacados apresuradamente de la '`casa del
campanario,`' y con gran rabia fueron conducidos ante el alcalde,
quien los mandó a la prisión Newgate.

No mucho después de esto, un tal Jeremy Hignel,
estando en su tienda atendiendo su vocación,
fue buscado y llamado por el alcalde y los concejales
para que se presentara delante de ellos.
Cuando llegó, el alcalde le preguntó si sabía dónde estaba,
él respondió que sí. Entonces el alcalde le preguntó: "`¿Dónde?`"
Él respondió: "`En la presencia del Señor.`" El alcalde le dijo,
"`¿Acaso no estás en la presencia de los jueces del Señor?`" Su respuesta fue:
"`Si ustedes son los jueces del Señor, entonces sí.`" Sobre esto,
sin que se dijeran más palabras en ese momento, uno de los concejales dijo:
"`Vemos lo que es él; llévenlo a la prisión de Newgate.`"
Pues dado que J. Hignel no se había quitado el sombrero, se concluyó que era Cuáquero,
y se consideró que esto era causa suficiente para enviarlo a prisión. Por tanto,
fue llevado inmediatamente a Newgate,
donde el guarda de la prisión lo recibió sin una orden de la corte,
y lo mantuvo encerrado por diecinueve días, sin permitir que nadie se acercara a él,
salvo su esposa.

No fue mejor el trato que le dieron a Daniel Wastfield, quien,
al ser llamado por el alcalde, se presentó ante él y el concejal Vickirs.
El alcalde le dijo: "`Wastfield,
ven aquí,`" y cuando se acercó al alcalde le preguntó en tres ocasiones diferente:
"`¿Qué eres tú?`"; aunque él lo conocía lo suficiente,
pues lo había llamado por su nombre como se dijo antes.
Wastfield respondió: "`Soy un hombre.`"
"`Pero, ¿cuál es tu nombre?,`" le dijo el alcalde.
"`Mi nombre es Daniel Wastfield,`" respondió. Entonces
el alcalde le dijo a uno de sus oficiales:
"`Cójanlo y llévenlo a Newgate, porque él vino a menospreciar la justicia.`"
Ante esto Wastfield replicó: "`No,
vine aquí en obediencia a tu orden;`" porque el alcalde había enviado a buscarlo,
como se ha dicho.
Por tanto, fue llevado sin una orden de la corte,
pues el alcalde dijo que su palabra era una orden de la corte;
y fue mantenido encerrado durante treinta y tres días. No
se permitió que nadie se le acercara salvo sus sirvientes,
a pesar de que era viudo y había sido obligado a
dejar su casa y su negocio al manejo de ellos;
y un niño suyo había muerto y había sido enterrado durante su encarcelamiento,
y no se le había permitido verlo.

Los magistrados, tras haber iniciado la persecución,
se volvieron más enérgicos con el tiempo,
al punto de que varios otros fueron encarcelados; entre estos Christopher Birkhead.
Este hombre había permanecido tranquilo en la '`casa
del campanario`" en Nicholas con su sombrero puesto,
y cuando el sacerdote Ralph Farmer le preguntó para qué estaba ahí, respondió:
"`Estoy en obediencia a la ley justa de Dios en mi consciencia;
y no he ofendido la ley de Dios,
ni la ley de la nación. '`Cosa espantosa y fea es hecha en la tierra...`'^
footnote:[Jeremías 5:30-31, "`Cosa espantosa y fea es hecha en la tierra;
los profetas profetizaron mentira, y los sacerdotes dirigían por manos de ellos;
y mi pueblo así lo quiso.
¿Qué, pues, haréis cuando llegue el fin?`"]`" Habría hablado más,
pero fue detenido con golpes y empujones, y fue llevado a prisión.

Después de esto los magistrados fueron muy incitados
a la persecución por el mencionado Ralph Farmer.
Algunos de sus oyentes, que eran muy osados, no dudaban en escribirle fuertes cartas,
y después de su sermón, hablarle de su comportamiento indigno cara a cara;
y aquellos que hicieron esto fueron enviados a prisión. Finalmente,
estos prisioneros fueron llevados a juicio,
y puesto que no se podía probar que ellos hubieran transgredido alguna ley,
algunos de los magistrados parecían inclinados a dejarlos en libertad,
si declaraban que ellos estaban arrepentidos de lo que habían hecho.
Entre estos estaba William Foord, a quien no se pudo acusar de algo sustancial,
excepto de que era uno del pueblo llamado Cuáqueros.
Al preguntársele si estaba arrepentido de lo que había hecho,
él lo negó y fue enviado a prisión de nuevo.
También había entre estos una mujer llamada Temperance Hignel,
quien al decirle al sacerdote en la '`casa del campanario,`'
después de que él había terminado su sermón:
"`¡Ay del Señor Dios para ti,
Jacob Brint!,`" fue golpeada y lastimada tan violentamente
que la sangre le corría por el rostro.
Estando en la prisión cayó enferma,
y cuando vieron que la vida de ella estaba en peligro,
fue sacada en una canasta y murió tres días después.
La razón que ella dio cuando estaba en prisión,
del porqué le había hablado de esa manera al sacerdote fue, que él tenía escasos oyentes,
salvo los que eran maldicientes, borrachos, golpeadores, peleadores, escarnecedores,
etc., y que por tanto, su ministerio era en vano,
al ser un predicador por ganancia que no llevaba buenos frutos.

No sé con certeza cuánto fueron mantenidos en prisión los otros; sin embargo,
fue un tiempo bastante largo, ya que George Bishop,
Dennis Hollister (quien anteriormente había sido miembro del Parlamento) y otros tres,
pusieron por escrito en conjunto todas estas transacciones,
y las enviaron a los magistrados con la esperanza de que así pudieran
ver el mal de la persecución. Pero como esto resultó en vano,
las dieron impresas cinco meses después,
para que todo el mundo supiera cómo trataba el pueblo de Bristol a sus habitantes,
lo cual llegaba a tal grado, que un autor escribió:
"`¿Se ha escuchado alguna vez de tal tiránica iniquidad y crueldad en esta nación? O,
¿se habrían aventurado a hacerla los ministros bajo el rey Carlos?
¿No era Stafford un transgresor menor en comparación con estos?`"
Y aunque el arzobispo Laud había sido decapitado,
no se pudo probar que los Episcopales hubieran perseguido tan ferozmente,
como lo hicieron estos supuestos afirmadores de la libertad de consciencia, quienes,
habiendo obtenido el poder, oprimieron más que aquellos a quienes habían expulsado.
Esto hizo que los perseguidos (algunos de los cuales habían luchado
anteriormente por la libertad común) se pusieran más fuertemente
en contra de los que estaban entonces en autoridad.

Ahora me volveré de Bristol hacia Norwich,
donde habían ido Richard Hubberthorn y George Whitehead.
Sucedió aquí que Richard Hubberthorn,
tras hablarle al sacerdote en el jardín de la '`casa del
campanario`' y no quitarse el sombrero ante los magistrados,
fue encarcelado en el castillo, donde fue mantenido gran parte del año siguiente.
Durante el tiempo que estuvo ahí, escribió varias epístolas de exhortación a sus amigos;
mientras tanto,
la predicación de su compañero George Whitehead estaba teniendo tal efecto,
que se estableció una reunión de los amigos en esa ciudad.

Antes de continuar,
sería conveniente dar cuenta de algunas características de estas dos personas.
Richard Hubberthorn nació en el norte de Lancashire y descendía de padres muy honestos.
Su padre era un propietario rural de buena reputación entre los hombres,
y Richard era su único hijo, quien desde joven estaba inclinado a la piedad.
Tras crecer hasta ser un hombre, se convirtió en oficial del ejército del Parlamento,
y por un celo por la piedad, a veces les predicaba a sus soldados.
Pero después, cuando entró en la sociedad de los llamados Cuáqueros,
dejó su empleo militar y testificó públicamente contra este,
porque ahora se había convertido en un soldado bajo otro estandarte--el de Cristo Jesús,
Príncipe de Paz; en el que ya no peleaba con la espada externa (como antes),
sino con la espada del Espíritu, la cual es la palabra de Dios.
Tenía un excelente don en su ministerio,
y aunque su voz no era tan fuerte como la de otros,
era un hombre de rápido entendimiento y muy edificante en su predicación.

G+++.+++ Whitehead (quien mientras escribo esto, todavía vive^
footnote:[George Whitehead nació en 1636 y murió en 1723.]) recibió una buena educación,
y cuando aún era un joven instruía a otros en literatura;
y continuó con ese llamado por un tiempo más,
después de que había sido convencido de la Verdad
que predicaban los profesantes de la luz.
Pero antes de este cambio, era un diligente oyente de los maestros del mundo,
y solía frecuentar la '`casa del campanario`' de Orton, en Westmoreland.
Sin embargo, cantar los salmos de David llegó a ser algo tan gravoso para él,
que a veces no podía unirse a esa costumbre, porque veía que, en general,
las condiciones de David no eran aplicables a los estados de una multitud mixta,
y se descubría a sí mismo corto de lo que se cantaba.
Esta consideración lo llevó a tal angustia,
que a menudo no se atrevía a cantar los salmos que los sacerdotes les daban a sus oyentes,
por temor a mentirle a Dios.
También comenzó a ver que las vidas y prácticas de
los sacerdotes no concordaban con su doctrina,
porque ellos hablaban contra el orgullo y la codicia, y aun así, vivían en esas cosas.
Esto hizo que fuera a oír a algunos de los que se habían separado de la iglesia nacional,
y que habían entrado en una forma de piedad más plausible; pero pronto vio,
que aunque había una diferencia en la parte ceremonial,
y que tenían una forma de palabras más verdadera que los sacerdotes,
todavía eran de los que corrían antes de ser enviados por Dios,
hablándole paz a esa naturaleza en él, en la que no sentía verdadera paz.
Y cuando tenía alrededor de diecisiete años, en el año 1652,
escuchó por primera vez la doctrina de la Verdad predicada
por los que eran llamados Cuáqueros en oprobio.
El testimonio de ellos obró tan poderosamente en su mente,
que lo recibió y entró en comunión con ellos.
Y luego descubrió,
que para crecer en la verdadera sabiduría y llegar
a ser sabio en el conocimiento de Dios,
debía convertirse en un necio para esa sabiduría con la
que se había estado alimentando del árbol del conocimiento,
sin tener derecho (en ese estado) al árbol de la vida.
Y así, continuando en fidelidad, le plació al Señor ordenarlo ministro del evangelio;
en cuyo servicio se desempeñó bien,
para el convencimiento de muchos otros y la edificación de la iglesia.

Pero dejémoslo ahora, y vayamos y veamos lo que estaba sucediendo en Oxford en 1654.
A finales del mes llamado junio llegaron dos mujeres,
cuyos nombres eran Elizabeth Heavens y Elizabeth Fletcher.
Estas les hablaban a las personas en las calles y
exhortaban a los estudiantes en la universidad,
quienes perversamente respondieron al celo de ellas empujando
violentamente a Elizabeth Fletcher contra una lápida,
y luego arrojándola a una tumba.
La maldad de estos creció a tal punto,
que las ataron juntas y las sumergieron bajo un chorro de agua de un surtidor.
Y luego de que estaban totalmente mojadas al bombear agua sobre ellas,
las arrojaron a una zanja con lodo, a través de la cual arrastraron a Elizabeth Fletcher.
Como E. Fletcher era una mujer joven y había sido tan cruelmente lastimada,
permaneció en una condición dolorosa hasta su muerte,
la cual ocurrió no mucho después. Al tiempo de ese rudo encuentro,
un Primer-día ella y su compañera entraron en la '`casa del campanario`' en Oxford,
y cuando el sacerdote terminó, ellas comenzaron a amonestar a las personas a la piedad.
Pero como había dos jueces presentes,
ordenaron que las pusieran bajo custodia y las llevaran a la prisión de Bocardo,
donde sólo había delincuentes.

Los jueces querían que los magistrados se reunieran por este motivo,
pero el alcalde no quería entrometerse,
y dijo que los que las habían encerrado trataran con ellas de acuerdo a la ley,
si habían transgredido alguna; y añadió, que él no tenía nada que decir contra ellas,
sino que les proporcionaría comida, ropa o dinero si tenían necesidad.
Sin embargo, después llegó a la asamblea donde estaban siendo interrogadas las mujeres,
a la que también había acudido el vicerrector de la universidad,
quien las culpó de haber blasfemado el nombre de Dios,
de haber hecho afrenta al Espíritu de Dios y deshonrado la gracia de Cristo.
Luego, al preguntarles si leían las Escrituras,
ellas respondieron que sí. Entonces les preguntaron
si eran o no obedientes al poder del magistrado,
a lo cual respondieron que ellas eran obedientes al poder de Dios,
y que se sujetaban a cualquier poder que fuera de Dios por motivos de consciencia.
"`Bien,`" dijo el vicerrector, "`ustedes profanan la palabra de Dios,
y me temo que no conocen a Dios, aunque hablan mucho de Él.`" Luego fueron retiradas,
y se concluyó que había suficiente causa para encerrarlas y castigarlas,
y acordaron que se redactara una orden para que fueran azotadas fuera de la ciudad.
Cuando la orden fue escrita, se le presentó al alcalde para que la sellara,
pero él se negó y dijo que no estaba dispuesto a hacerlo.
Entonces uno de los jueces dijo,
que era derecho de la ciudad que se redactara una
orden y se sellara con el sello del despacho,
si algún vagabundo era cogido dentro de la jurisdicción y libertades de la misma;
pero el alcalde también se negó. Esto hizo que algunos de ellos dijeran:
"`Si no lo haces, lo haremos nosotros.`"
Entonces se acordó que las mujeres fueran azotadas severamente,
lo cual se realizó la mañana siguiente,
aunque con mucha indisposición por parte del verdugo; y el alcalde no tuvo nada que ver.

Pero dejo a estas mujeres y me vuelvo a otra, una tal Barbara Blaugdone,
de quien ya se ha dicho que era una de las que habían recibido
la Verdad por medio del ministerio de John Audland y John Camm.
Ella se había inclinado a la piedad desde su juventud y era maestra
de niños. Pero al entrar a la sociedad de los llamados Cuáqueros,
se volvió sencilla,^
footnote:[Ella dejó de vestirse de acuerdo a la moda y comenzó
a usar el mismo lenguaje sin importar la clase social.]
tanto al hablar como al vestir, y en consecuencia,
le fueron quitados los niños a los que enseñaba.
Algunas veces iba a las '`casas del campanario`' y daba testimonio contra sus formalismos,
por lo que fue puesta en prisión y mantenida ahí la cuarta
parte de un año. Después llevó una vida de gran autonegación,
y se abstuvo de toda carne, vino y cerveza, y sólo tomó agua por el lapso de un año;
durante el cual creció y prosperó en verdadera piedad.
Sucedió, que una vez regresando de una reunión de la casa de George Bishop, en Bristol,
un rufián atravesó su ropa con un cuchillo (o algún
instrumento cortante) al costado de su abdomen,
el cual, si hubiera entrado un poco más la habría matado.
Entonces se fue para Marlborough,
donde exhortó a la gente en las '`casas del campanario`' y en otros lugares,
a temer a Dios, por lo que fue llevada a prisión por espacio de seis semanas,
y ahí ayunó varios días y noches.
Cuando fue liberada, fue a ver a Isaac Burges, el hombre que la había encerrado,
y al hablar con él, fue verdaderamente convencido de la Verdad,
pero no se rindió para tomar la cruz.
Sin embargo,
después fue muy cariñoso con los amigos de ella y
se mantuvo al lado de ellos en todas las ocasiones,
y nunca más persiguió a ninguno de ellos.
Estando en Bristol un tiempo después de esto, Isaac Burges fue a la casa de ella,
donde confesó que él sabía que su doctrina era Verdad,
pero que no podía tomar la cruz para caminar de esa manera.

Tiempo después ella fue a Moulton, Barnstable y Bediford, en Devonshire,
y en todos estos lugares su porción fue una prisión. También
fue a ver a un hombre que después fue el conde de Bath,
un lugar donde ella anteriormente había pasado mucho tiempo en cosas vanas,
pero que ahora había sido movida a visitar,
para llamar a esta familia a que dejara su vanidad.
Ella pidió hablar con la señora de la casa, pero uno de los sirvientes que la conocía,
le ordenó que fuera a la puerta trasera y que su señora saldría por ahí e iría
al jardín. Cuando Barbara llegó a la puerta le soltaron un gran perro mastín,
el cual corrió ferozmente hacia ella como para atacarla,
pero repentinamente se volvió y se fue llorando y cojeando;
a través de lo cual ella vio claramente que la mano
del Señor la había preservado de ese peligro.
Luego llegó la señora y estuvo tranquila,
escuchó lo que Barbara dijo y le dio las gracias por su exhortación; sin embargo,
no la invitó a entrar, a pesar de que Barbara a menudo se había alojado ahí,
y había comido y bebido en su mesa.

Luego se fue a Great Torrington,
y entrando en la '`casa del campanario`' le dijo algo a la gente a modo de exhortación;
pero como no tuvo suficiente oportunidad de descargar su consciencia,
fue a su alojamiento y empezó a escribir.
Después del mediodía llegaron los alguaciles y le quitaron lo que había escrito,
y le ordenaron que los acompañara a su lugar de culto.
Ella respondió que ellos no le permitirían hablar ahí,
que ella no conocía ninguna ley que la obligara a ir ahí dos veces en un día,
y que todos sabían que ella había estado ahí por la mañana.
Como no estuvo dispuesta a ir, el alcalde la mandó a llamar al día siguiente.
Cuando ella llegó,
encontró que era un hombre moderado y que estaba reacio a enviarla a prisión,
pero el sacerdote (que estaba presente) estaba muy ansioso
y dijo que ella debía ser azotada como un vagabundo.
Entonces Barbara le ordenó que probara en dónde había pedido ella un pedazo de pan,
pero él dijo que ella había quebrantado la ley por hablar en la iglesia de ellos.
Este sacerdote presionó tanto al alcalde,
que al final lo hizo escribir una orden judicial y enviarla a la prisión de Exeter,
que estaba a veinte millas de distancia.
Ella permaneció ahí por algún tiempo, hasta que llegó la sesión de la corte,
pero no fue llevada a juicio.
Y después de que las sesiones habían finalizado,
la hicieron alojarse una noche con una gran compañía
de gitanos que estaban entonces en prisión.

Al día siguiente el alguacil llegó con un oficial de la iglesia que la llevó a un cuarto,
y la azotó hasta que le corría la sangre por la espalda,
aunque ella nunca se estremeció por un golpe,
sino que cantó en voz alta y se regocijó de haber sido considerada digna de sufrir
en el nombre del Señor. Esto hizo que el oficial de la iglesia dijera:
"`¿Estás cantando?
Yo te haré llorar pronto;`" y la azotó tan fuerte, que al verlo una tal Ann Speed,
empezó a llorar.
Pero Barbara estaba fortalecida por un poder poco común y más que humano,
por lo que después declaró que si ella hubiera sido azotada
hasta la muerte en el estado en que se encontraba entonces,
no se habría aterrorizado o abatido.
Al ver el alguacil que toda la ira del hombre no podía moverla,
le ordenó que dejara de golpearla,
y luego se le permitió a Ann Speed que tratara sus heridas.
Al día siguiente fue liberada de la prisión junto con todos los gitanos,
y el oficial de la iglesia la siguió dos millas fuera del pueblo,
pero tan pronto como la dejó,
ella regresó y fue a la prisión a ver a sus amigos que estaban prisioneros,
y después de visitarlos se marchó a su casa en Bristol.

Pero en el camino, cuando llegaba a Bediford, fue detenida y llevada al ayuntamiento,
y registrada para ver si tenía un cuchillo o unas tijeras en su poder.
Al día siguiente fue llevada ante el alcalde,
quien al discutir mucho con ella tuvo consciencia de la verdad que ella le hablaba;
al final, él le abrió dos puertas, una justo al lado de la otra,
y le dijo que le daba a escoger qué camino seguir, si regresar a la cárcel o ir a casa.
Barbara le dijo que escogía la libertad en lugar de las cadenas, y se fue a su casa.
El alcalde cogió su caballo y la siguió, y tras alcanzarla en la carretera,
quería que ella cabalgara a su lado;
pero cuando se topaban en el camino con alguien que él conocía, aflojaba el paso,
pero tan pronto como los pasaban, se acercaba de nuevo a ella.
Así cabalgó tres o cuatro millas con ella y conversaron todo el camino,
y cuando se separaron,
ella se arrodilló y oró por él. Todo ese tiempo él estuvo muy serio, y posteriormente,
se volvió un hombre muy firme y sobrio.
Ella le escribió una vez, pero no mucho después de eso él murió.

Tras llegar a la casa, fue movida a ir a Basingstoke,
para intentar obtener la libertad de dos de sus amigos, a saber,
Thomas Robinson y Ambrose Rigge,
que habían sido detenidos en la primera reunión que
sus amigos habían tenido ahí. Pero cuando llegó,
le negaron la entrada a la prisión. Como tenía una
carta de John Camm para estos dos hombres,
la puso en el hueco de la puerta,
y luego fue a ver al alcalde para pedirle la libertad de ellos.
El alcalde le dijo que si él veía la carta que ella les había traído,
serían puestos en libertad.
Ella respondió: "`La verás;`" y se fue a buscarla.
Después de leerla, el alcalde le dijo que sacaría a sus hermanos,
pero que no podía dejarlos salir en ese momento; sin embargo,
no pasó mucho tiempo antes de que sus amigos obtuvieran su libertad.

Ahora, dejando a Barbara por un tiempo, regresamos a Miles Halhead.
En el primer mes de este año en curso,
Miles fue movido a ir a Irlanda y declarar la palabra del Señor ahí;
y hablando de esto con James Lancaster y Miles Bateman,
ellos rápidamente decidieron hacerle compañía. Así que se fueron a Irlanda,
donde proclamaron la Verdad en las ciudades, pueblos,
aldeas y delante de los magistrados, según se ofrecía la ocasión;
y su testimonio fue recibido por muchos.
Después de que habían descargado sus consciencias, regresaron a Inglaterra,
donde Miles pronto se sintió movido a ir a Escocia.
En su camino, se encontró con su amigo James Lancaster,
quien se sintió muy libre de acompañarlo, y ambos se fueron a Escocia.
Pero ellos no fueron los primeros de los llamados Cuáqueros en ese país,
porque Christopher Fell, George Wilson y John Grave habían estado ahí antes,
de modo que una pequeña iglesia formada por los de
su comunión ya había sido plantada en ese reino,
antes de que Miles Halhead llegara.
Y un tal Alexander Hamilton,
un año antes de que cualquier Cuáquero apareciera en Escocia,
había establecido una reunión en Drumbowy y en Heads; y cuando esos hombres llegaron ahí,
él recibió el testimonio de ellos, junto con su esposa Joan, James Gray,
James Miller y otros.
También encuentro que Escocia había sido visitada
tempranamente por Catherine Evans y Sarah Cheevers,
dos notables mujeres de quienes se va a relatar algo extraordinario a su debido tiempo.

Pero regreso a J. Lancaster y a M. Halhead, quienes, habiendo llegado a Dumfries,
fueron a la '`casa del campanario`' del pueblo el Primer-día,
donde vieron a muchas personas reunidas, aullando y llorando,
y haciendo gran lamentación, como si hubieran sido tocadas por un sentido de sus pecados.
Miles permaneció en silencio hasta que terminó el culto, pero luego,
afligido por el engaño e hipocresía de ellos, habló según fue movido.
Pero se topó con gran oposición,
pues muchas de las personas estaban tan enfurecidas
que lo echaron a él y a su compañero del pueblo,
cerca de la orilla de un gran río;
y se intentó que las mujeres del pueblo los apedrearan.
Pero estos hombres lo evitaron al vadear el río.

Habiendo pasado de manera segura el agua, fueron a Edinburgh y a Leith,
donde se quedaron cerca de diez días. Durante ese tiempo,
cada vez que se presentaba la ocasión, Miles les hablaba a las personas,
y también a las guarniciones, capitanes y oficiales del ejército,
los cuales estaban muy afectados y confesaron que
el Señor había sido muy bueno con ellos.
Porque el mensaje de Miles fue,
que la ira del Señor estaba encendida contra ellos por no haber
cumplido las promesas que Le habían hecho en el día de su angustia,
cuando sus enemigos los tenían acorralados por todos lados.
Pues el Señor los había liberado y les había dado victoria,
pero ellos Le habían devuelto mal por bien,
y habían cometido violencia contra los que Él había
enviado a declarar Su palabra entre ellos.
Después de declararles todas estas cosas ampliamente, Miles se fue a Glasgow y Stirling,
donde también habló según era movido, y regresó a Inglaterra.

Pero antes de dejar Escocia puedo decir,
que así como al principio había reuniones en Drumbowy y Heads,
no pasó mucho tiempo antes de que se establecieran también en Garshore,
Edinburgh y Aberdeen.
Me parece que los primeros predicadores escoceses
de los llamados Cuáqueros fueron William Osborn,
Richard Ree, y el ya mencionado Alexander Hamilton.
De dicho Hamilton puedo mencionar un suceso inusual: Después de que él,
su esposa y su hermana se separaron de la sociedad de los Independientes,
Thomas Charters (un maestro de esa secta en Kilbride, no lejos de Drumbowy),
viendo que no podía hacer volver a Hamilton y a su familia,
los amenazó con la excomunión y fijó el día para hacerlo,
y le avisó a Hamilton con unos días de anticipación. Hamilton le advirtió que se abstuviera,
o de lo contrario la ira de Dios se apoderaría de él. Pero Charters respondió:
"`No es más que Alexander Hamilton el que habla así.`"
Pero Hamilton contestó en presencia de muchos testigos,
que no era sólo él,
sino que lo que él había dicho era del Señor. Pero Charters persistió en lo que intentaba,
y dos días antes del tiempo señalado,
mientras caminaba en el jardín de la '`casa del campanario`' donde pastaba su caballo,
se acercó para acariciarlo,
pero el caballo se encabritó y pateó a Charters tan violentamente por un costado,
que murió dos días después,
aproximadamente a la misma hora en que él había fijado la excomunión.
No sé con certeza si esto sucedió en el año que ahora describo;
pero fue dentro de este año, o cerca de él.

Este año Miles Halhead llegó a Berwick, en Northumberland,
y fue a ver al alcalde de dicho pueblo, y le habló en su tienda diciéndole: "`Amigo,
oye lo que el siervo del Señor tiene que decirte.
Deja de perseguir a los siervos del Señor,
a quienes Él envía en amor a este pueblo de Berwick,
para mostrarles el camino que lleva a la vida eterna.
Te exhorto, oh hombre, que no toques al ungido del Señor,
ni hagas daño a ninguno de Sus profetas,
no sea que provoques contra ti la ira del Dios eterno y vivo.`"
Este lenguaje audaz ofendió tanto al alcalde que envió a Miles a prisión,
donde permaneció unas diez semanas, y después fue llevado a las sesiones de la corte.
Ahí se redactó una acusación contra él y se leyó en audiencia pública,
pero él negó el contenido de la misma; sin embargo, dijo:
"`No niego lo que le he dicho al alcalde de este
pueblo;`" y luego relató lo que le había dicho.
Sobre esto, el registrador^
footnote:[Se trataba de una persona con conocimientos
jurídicos nombrada por el alcalde y los concejales,
para registrar los procedimientos de sus tribunales;
estos registros se consideraban la prueba de hecho más importante.]
dijo: "`Señores, por lo que entiendo por sus propias palabras,
si él no puede probar que el alcalde del pueblo es un perseguidor,
a mi juicio él ha agraviado al alcalde.`"
A esto Miles respondió:
"`Si el alcalde de este pueblo de Berwick se atreve a decir en la presencia del Señor,
cuya presencia está aquí, que él no es un perseguidor,
sino que la naturaleza perseguidora está muerta en él,
yo acataré la sentencia de la corte.`"
Entonces el secretario de la corte dijo: "`Señor alcalde,
si usted afirma que no es perseguidor,
sino que la naturaleza perseguidora está muerta en usted,
él está dispuesto a acatar la sentencia de la corte.`"
A esto el alcalde respondió: "`No sé qué hacer.
Desearía no haberlo visto nunca.
Les suplico que lo dejen ir, y que no nos preocupemos más por él.`"

Entonces Miles dijo:
"`Yo probaré que este alcalde es el más grande perseguidor del pueblo o del condado.
En una ocasión anterior,
fui enviado a la prisión de este pueblo por algunos
de los jueces que están ahora en esta corte;
¡pero tú, oh hombre, los has superado a todos!
Porque me encerraste y me mantuviste prisionero por cerca de diez semanas,
por hablarte en privado en tu propia tienda.
Ahora apelo al registrador de este pueblo de Berwick, ya que soy un inglés nacido libre,
según la ley de esta nación, ¿fue mi encarcelamiento legal o no?`"
Entonces el registrador del pueblo se puso de pie y dijo:
"`No es legal que un ministro de la ley encarcele a un hombre por motivo propio.`"
Entonces la corte exclamó: "`¡Sáquenlo!`"
En ese momento,
el sacerdote del pueblo se puso de pie y le pidió
a la corte que le hicieran a Miles una pregunta.
Ante esto Miles dijo: "`El Señor conoce tu corazón, oh hombre,
y en este momento ha revelado tus pensamientos a Su siervo; por tanto,
ahora también conozco tu corazón, sumo sacerdote, y la pregunta que deseas hacerme.
Si prometes delante de la corte que te conducirás honestamente conmigo,
si te digo la pregunta que deseas hacerme, no sólo te diré la pregunta,
sino que también la responderé.`" El sacerdote dijo que lo haría. Entonces Miles prosiguió:
"`Tu pregunta es la siguiente:
Deseas saber si yo reconozco al Cristo que murió en Jerusalén o no.`"
El sacerdote maravillado dijo: "`Cierto, esa es mi pregunta.`"
Miles dijo: "`Conforme a mi promesa, la responderé delante de la corte.
En la presencia del Señor Dios del cielo, no reconozco a otro Cristo,
sino Aquel que murió en Jerusalén y que dio testimonio
de la buena profesión delante de Poncio Pilato,
que Él era la luz y el camino que guía al hombre caído fuera del pecado y del mal,
y lo lleva al eterno Dios; bendito sea para siempre.`"
No se le hicieron más preguntas, sino que se le ordenó al carcelero que se lo llevara.
Sin embargo, en el lapso de un corto tiempo la corte dio la orden de que lo liberaran.
Entonces se fue a Newcastle y regresó a su esposa e hijos en Mount-joy,
donde lo dejaremos por un tiempo y regresaremos a G. Fox,
a quien habíamos dejado en Synder-hill-green.
De ahí viajó arriba y abajo en Yorkshire, hasta Holderness,
visitando a sus amigos y encontrando las iglesias en un estado floreciente.
Relatar todo lo que le sucedió ahí estaría fuera de mi alcance.

Luego, atravesando los condados, llegó a Lincolnshire,
donde el alguacil de Lincoln llegó a una reunión donde estaba él,
y por un rato hizo gran contienda.
Pero al final,
el poder del Señor alcanzó de tal manera al alguacil que fue convencido de la Verdad,
junto con varios otros que también se le habían opuesto.
Mientras G. Fox estaba en ese condado,
la iglesia de sus amigos se incrementaba y muchos recibían la doctrina que él predicaba,
y entre estos estaba un tal Sir Richard Wrey, con su hermano y la esposa del hermano.
Estos dos últimos continuaron firmes hasta que murieron,
pero Sir Richard encontró este camino tan estrecho, que después se apartó,
pues en ese momento la persecución cayó tan fuerte sobre los llamados Cuáqueros,
que nadie podía permanecer en su sociedad,
sino los que estaban dispuesto a arriesgarlo todo.

Entonces G. Fox se fue a Derbyshire,
y entrando a Nottinghamshire junto con el mencionado
alguacil de Lincoln que viajaba con él,
llegaron al condado Peak.
Ahí tuvieron una reunión en la casa de Thomas Hammersley,
a la que se metieron varios '`ranters`' y le hicieron
oposición. Cuando él los reprendió por jurar,
dijeron: "`Abraham, Jacob y José juraron.`"
Pero aunque G. Fox no negó esto, dijo: "`Cristo, quien dijo: '`Antes que Abraham fuese,
yo soy,`' dice: '`No juréis en ninguna manera.`' Cristo,
quien le puso fin a los profetas,
y también al antiguo sacerdocio y a la dispensación de Moisés,
y reina sobre la casa de Jacob y de José dice:
'`No juréis en ninguna manera.`' Dios,
cuando introdujo al Primogénito al mundo dice:
'`Adórenle todos los ángeles de Dios,`' a saber, a Cristo Jesús, quien dice:
'`No juréis en ninguna manera.`'
En cuanto a la excusa que los hombres dan para jurar,
diciendo que es una manera de poner fin a su discordia, Cristo (quien dice:
'`No juréis en ninguna manera`') destruye al diablo y sus obras,
quien es el autor de la discordia, pues esa es una de sus obras.
Y Dios dijo: '`Este es mi Hijo amado, en quien tengo complacencia; a él oíd.`' Por tanto,
el Hijo debe ser oído y Él prohíbe jurar.
Y el apóstol Santiago, quien oyó al Hijo de Dios, Lo siguió y Lo predicaba a Él,
también prohíbe todo juramento.`"
Así prevaleció G. Fox y muchos fueron convencidos ese día. Y es notable,
que a este Thomas Hammersley, al ser convocado a servir como jurado,
se le permitió servir sin juramento.
Y cuando entregó el veredicto (pues era el presidente del jurado),
el juez declaró que él había sido juez muchos años,
y que nunca había oído un veredicto más recto,
que el que había entregado el Cuáquero en ese momento.

G+++.+++ Fox viajando, llegó a Swanington, en Leicestershire,
donde se iba a celebrar una reunión general,
a la que muchos de sus amigos acudieron procedentes de varias partes;
entre estos John Audland y Francis Howgill, de Bristol; y Edward Burrough, de Londres.
Después de esto, G. Fox llegó a Twycross, y algunos '`ranters`' ahí,
cantaron y danzaron delante de él,
pero él los reprendió tan severamente que algunos fueron
alcanzados y se volvieron hombres modestos y sobrios.

Luego George se fue a Drayton, su lugar de nacimiento, a visitar a sus parientes.
Ahí, Nathaniel Stevens, el sacerdote, junto con otro sacerdote, lo mandaron a llamar.
Después de estar tres años fuera, G. Fox no sabía nada del propósito de ellos,
pero al final fue al jardín de la '`casa del campanario,`' donde
los sacerdotes habían reunido una gran cantidad de personas.
Ellos deseaban que él entrara a la '`casa del campanario,`'
pero George les preguntó que qué haría ahí. Le respondieron:
"`Mr. Stevens no puede soportar el frío.`" A esto G. Fox respondió:
"`Él puede soportarlo tan bien como yo.`"
Pero al final, él y su compañero Richard Farnsworth entraron en una gran sala,
donde entablaron una disputa con los sacerdotes,
acerca de cuán contraria era su práctica de la de Cristo y Sus apóstoles.
Los sacerdotes les preguntaron dónde estaban prohibidos, o se les habían puesto fin,
a los diezmos; con lo cual, G. Fox les mostró el capítulo 7 de la epístola a los Hebreos,
donde no sólo los diezmos, sino el sacerdocio que tomaba los diezmos,
habían sido acabados;
y que la ley había sido llevada a un fin y anulada por lo que había
constituido el sacerdocio y había ordenado el pago de los diezmos.
Además, conociendo la condición de Stevens, expuso su manera de predicar,
mostrando que él (como el resto de los sacerdotes)
aplicaba las promesas de Dios al primer nacimiento,
el cual debía morir, cuando en realidad, las promesas eran para la semilla,
no para muchas semillas, sino para la única semilla, Cristo,
quien era Uno en varón y hembra.
Porque todos tenían que nacer de nuevo, antes de poder entrar al reino de Dios.
Entonces Stevens dijo que él no debía juzgarlo así. Pero G. Fox le dijo:
"`el que es espiritual juzga todas las cosas.`"^
footnote:[1 Corintios 2:15]
Stevens confesó que esa era una escritura, y añadió: "`Pero ciudadanos,
este es el asunto: G. Fox ha llegado a la luz del sol,
y ahora piensa apagar mi luz de estrella.`"
A esto G. Fox replicó: "`Yo no sofocaría la menor medida de Dios en ningún hombre,
mucho menos apagaría su luz de estrella, si esta fuera la verdadera luz de estrella,
la luz del Lucero de la Mañana.
Pero si tú tienes algo de Cristo, o de Dios, debes decirlo gratuitamente,
y no tomar diezmos de las personas por predicar;
considerando que Cristo les mandó a Sus ministros que dieran gratuitamente,
lo que habían recibido gratuitamente.`"
Pero Stevens dijo que él no cedería a eso.

Esta disputa, finalizada por el momento,
fue retomada una semana después por ocho sacerdotes, en presencia de muchas personas.
Cuando ellos vieron que G. Fox se mantenía inquebrantable, dijeron de manera aduladora:
"`¡Oh, qué gran hombre habría sido, si no hubiera sido Cuáquero!`"
Después la disputa se reanudó en el jardín de la '`casa del campanario,`'
donde G. Fox les mostró con abundantes Escrituras,
que aquellos que no predicaban si no era por un salario o diezmos,
no le servían al Señor Jesucristo sino a sus propios vientres.
Esto lo trató con tal profundidad, que uno de los profesantes dijo: "`¡George,
qué! ¿Nunca terminarás?`" A esto respondió, que terminaría pronto.

Entonces interrumpieron la reunión y el sacerdote Stevens quería que G. Fox,
junto con su padre y madre, se apartara con él y le hablara en privado.
Aunque sus parientes cedieron, George estaba reacio a hacerlo; sin embargo,
para que no se dijera que era desobediente a sus padres,
aceptó. Pero muchas de las personas que deseaban escuchar, se acercaron a ellos.
Entonces Stevens dijo que si él estaba fuera del camino correcto,
que George orara por él, y que si George estaba fuera del camino correcto,
él oraría por George.
Además, quería darle a George una forma establecida de palabras con las cuales orar.
A lo que G. Fox replicó: "`Parece que no sabes si estás en el camino correcto o no,
pero yo sé que estoy en el camino eterno, Cristo Jesús, del que tú estás fuera.
Y quieres darme una forma establecida de palabras para que ore,
aunque niegas el libro común de oraciones, al igual que yo.
Si quieres que ore por ti con una forma establecida de palabras,
¿no es eso negar la doctrina y práctica de los apóstoles de orar
por el Espíritu según da palabras y expresión?`" Aquí,
aunque algunas personas se rieron,
otras que eran serias y sobrias fueron convencidas de la Verdad,
y los sacerdotes fueron tremendamente sacudidos.
Oyendo estas cosas,
el padre de George (aunque oyente y seguidor de los sacerdotes) quedó tan satisfecho,
que golpeó su bastón contra el suelo y dijo: "`Verdaderamente veo,
que si un hombre se mantiene firme en la Verdad, esta lo confirmará.`"

G+++.+++ Fox no se quedó mucho tiempo en Drayton, sino que se fue a Leicester,
y de ahí a Whetstone,
donde se iba a celebrar una reunión. Pero antes de que comenzara la reunión,
llegaron unos diecisiete soldados del regimiento del coronel Hacker,
lo cogieron bajo custodia y lo llevaron a dicho coronel,
donde también estaban sus comandantes y capitanes.
Ahí tuvo una gran conversación con ellos acerca de los sacerdotes, y acerca de reuniones;
porque en ese momento había un rumor de un complot contra Cromwell.
George habló mucho sobre la luz de Cristo,
la cual alumbra a todo hombre que viene a este mundo.
Oyendo el coronel lo que decía George, le preguntó:
"`¿Fue la luz de Cristo la que hizo que Judas traicionara a su maestro,
y la que después lo llevó a ahorcarse?`"
G+++.+++ Fox le dijo: "`No; ese fue el espíritu de tinieblas que odia a Cristo y Su luz.`"
Entonces el coronel le dijo a George que podía irse a la casa y mantenerse ahí,
y no salir a reuniones; pero George le dijo que él era inocente,
libre de toda conspiración, y que se oponía a todas esas obras.
Entonces Needham, el hijo del coronel, dijo: "`Padre,
este hombre ha tenido dominio demasiado tiempo; es hora de eliminarlo.`"
G+++.+++ Fox le preguntó:
"`¿Por qué? ¿Qué he hecho o a quien he agraviado desde que
era niño? ¿Quién puede acusarme de algún mal?`"
El coronel le preguntó si se iría a la casa y se quedaría ahí. G. Fox respondió,
que si él prometía irse a la casa y hacer de su casa una prisión para sí mismo,
implicaría que él era culpable de algo, y que si luego iba a las reuniones,
dirían que había roto su orden.
Y que por tanto, él continuaría yendo a las reuniones según se lo ordenara el Señor,
y que no se podía someter a sus demandas.
Y tras añadir que él y sus amigos eran un pueblo pacífico, el coronel dijo: "`Bien,
entonces mañana por la mañana, a las seis en punto,
te enviaré con el capitán Drury (unos de los que guardaba su vida) a mi señor protector.`"

La mañana siguiente, a la hora señalada, G. Fox fue entregado al capitán Drury.
Antes de que salieran,
Fox le pidió al capitán que lo dejara hablar de nuevo con el coronel; por tanto,
fue llevado al lado de la cama del coronel,
quien nuevamente le pidió que se fuera a la casa y no acudiera a más reuniones.
Pero G. Fox le dijo que no podía someterse a eso,
sino que debía tener libertad para servirle a Dios e ir a las reuniones.
"`Entonces,`" dijo el coronel, "`debes ir delante del protector.`"
Con lo cual Fox se arrodilló al lado de su cama,
y le pidió al Señor que perdonara al coronel, ya que, según su juicio,
el coronel era como Pilato (pues el coronel estaba siendo provocado por los sacerdotes),
aunque se lavara las manos de la culpa.
En consecuencia, George le dijo: "`Cuando llegue el día de tu miseria y prueba,
recuerda lo que te he dicho.`"
En verdad,
estaba muy lejos de la mente de Needham (quien deseaba que G. Fox fuera "`eliminado`"),
pensar que un día le sucedería lo mismo a su padre de manera humillante, en Tyburn.
Pero lo que sucedió después,
cuando el coronel fue condenado como unos de los jueces del rey Carlos I,
será relatado en su debido lugar.

Después de que G. Fox dejó al coronel Hacker,
el capitán Drury lo llevó prisionero a Londres,
donde fue a dar cuenta de Fox al protector.
Al regresar donde G. Fox,
le dijo que el protector le exigía que prometiera no empuñar
una espada o un arma contra él o el gobierno actual,
que lo escribiera con las palabras que él considerara buenas,
y pusiera su mano sobre ello.
Teniendo en cuenta eso, a la mañana siguiente G. Fox le escribió una nota al protector,
dirigiéndola a Oliver Cromwell, en la que declaraba en presencia de Dios,
que él rechazaba el uso o manejo de una espada carnal, o de cualquier arma externa,
contra él o cualquier hombre;
que él había sido enviado por Dios para dar testimonio
contra toda violencia y contra las obras de las tinieblas,
para volver a las personas de las tinieblas a la luz,
apartarlos del motivo de la guerra y pelea, y llevarlos al evangelio pacífico;
y apartarlos de ser malhechores,
para quienes la espada de los magistrados debía ser un terror.^
footnote:[Romanos 13:3]
Cuando terminó de escribir esto le puso su nombre, se lo dio al capitán Drury,
y él se lo entregó a Oliver Cromwell.

Después de un tiempo, el capitán regresó a The Mermaid, cerca de Charing-cross,
donde era mantenido G. Fox, y lo llevó a Whitehall y lo presentó ante el protector,
cuando este no se había vestido aún, pues era bastante temprano.
Cuando George entró dijo:
"`Paz sea en esta casa,`" y le pidió al protector que se mantuviera
en el temor de Dios para que pudiera recibir sabiduría de Él,
y para que por medio de esta pudiera ser ordenado y ordenar
todas las cosas bajo su mano para la gloria de Dios.
También conversó mucho con él acerca de religión,
y durante ese tiempo Cromwell se condujo muy moderadamente,
pero dijo que G. Fox y sus amigos disputaban con los ministros, es decir,
con sus maestros.
G+++.+++ Fox le dijo que él no contendía con ellos,
que eran ellos los que contendían con él y sus amigos.
"`Pero,`" continuó, "`si reconocemos a los profetas, a Cristo y a Sus apóstoles,
no podemos sostener a dichos maestros, profetas, o pastores, contra los que los profetas,
Cristo y los apóstoles declararon,
sino que debemos declarar contra ellos por el mismo poder y Espíritu.`"

Además, le demostró que los profetas,
Cristo y los apóstoles habían predicado gratuitamente,
y que habían declarado contra los que no predicaban gratuitamente,
sino que lo hacían por ganancia deshonesta,
y contra los que adivinaban por dinero o enseñaban por precio,
pues eran codiciosos y avaros, como los perros mudos que nunca se sacian;
y que aquellos que tenían el mismo Espíritu que tenían Cristo,
los profetas y los apóstoles,
no podían hacer otra cosa más que declarar contra todos esos; es decir,
como lo habían hecho ellos.
También dijo que toda la llamada Cristiandad tenía las Escrituras,
pero que carecían del poder y del Espíritu que tenían los que las habían dado;
y que esta era la razón por la que ellos no estaban en comunión con el Hijo,
ni con el Padre, ni con las Escrituras, ni unos con otros.
Mientras hablaba de esta manera, Cromwell dijo varias veces: "`Muy bueno.`"
"`Es verdad.`"

G+++.+++ Fox conversó más con él, pero al ver que la gente entraba, retrocedió un poco,
y mientras se volvía, Cromwell lo cogió por la mano y con lágrimas en sus ojos dijo:
"`Ven de nuevo a mi casa, porque si tú y yo pasamos una hora juntos al día,
nos acercaremos uno al otro;`" y añadió,
"`no te deseo más mal del que le deseo a mi propia alma.`"
A esto G. Fox replicó, que si él lo hacía, perjudicaría su propia alma.
Luego le pidió que le prestara atención a la voz de Dios,
para que pudiera permanecer en Su consejo y obedecerlo, y que si lo hacía,
eso lo guardaría de la dureza de corazón, pero que si no oía la voz de Dios,
su corazón se endurecería. Esto alcanzó al protector tanto, que dijo: "`Cierto.`"

Luego G. Fox salió, y el capitán Drury le dijo mientras lo seguía,
que el señor protector había dicho que estaba en libertad y que podía ir donde quisiera;
sin embargo, fue llevado a un gran salón,
donde los caballeros del protector iban a cenar.
George les preguntó por qué había sido llevado ahí,
y ellos le dijeron que lo había ordenado el protector, que él podía cenar con ellos.
Pero George les pidió que le dijeran al protector, que él no comería un bocado de su pan,
ni bebería un sorbo de su bebida.
Cuando Cromwell escuchó eso dijo: "`Ahora veo que ha surgido y se ha levantado un pueblo,
que no puedo ganar ni con regalos, ni con honores, ni con oficios, ni con lugares;
pero con las otras sectas y pueblos sí puedo hacerlo.`"
En respuesta a eso le fue dicho,
que los Cuáqueros habían abandonado todo lo que era de ellos,
y que no era probable que buscaran tales cosas de él.

Fue notable, que el capitán Drury, quien,
durante el tiempo que G. Fox estuvo bajo su custodia,
a menudo se había burlado de él por el apodo "`Cuáqueros`"
(el cual fue usado por primera vez por los Independientes,
en referencia a los profesantes de la luz), después se acercara y le contara,
que estando acostado en su cama para descansar durante el día,
un repentino temblor se había apoderado de él,
las rodillas le pegaban entre sí y su cuerpo se sacudía tan fuertemente,
que no se podía levantar de la cama; que había sido tan sacudido,
que no le había quedado suficiente fuerza para levantarse.
Al sentir que el poder del Señor estaba sobre él,
se cayó de la cama y clamó al Señor diciendo,
que nunca más volvería a hablar contra los Cuáqueros,
ni contra nadie que temblara ante la palabra de Dios.

Los acontecimientos específicos que le sucedieron
a G. Fox cuando fue puesto en libertad en Londres,
los pasaré de largo.
Tuvo grandes reuniones ahí, y la multitud de personas eran tan grande,
que difícilmente podía ir y volver de las reuniones debido a la muchedumbre.
Mientras tanto, el número de sus amigos se incrementó enormemente,
y algunos que pertenecían a la corte de Cromwell también fueron convencidos
de la Verdad predicada por él. Por ese tiempo escribió varios artículos,
uno de los cuales era contra el orgullo, la ropa llamativa y las modas del mundo.

No hallo que en ese tiempo hubiera persecución por parte de los magistrados en Londres,
pero en otros lugares sí. En ese año, Anne, la esposa de John Audland,
entró a la '`casa del campanario`' en Banbury y dijo
(después de que el sacerdote había terminado),
que los que se oponen a la doctrina de Cristo,
"`aunque digan que '`el Señor vive,`' aún hablan falsedad,`" según
Jeremías 5:2. Por esto fue encarcelada y culpada de blasfemia,
y dos muchachos que juraron contra ella dijeron,
que ella había dicho que el Señor no vivía. Así,
prevalecían las falsas acusaciones y la persecución era encubierta de esa manera.

El año estaba llegando a su fin, y Cromwell aseguró la paz con los Países Bajos;
parece que se esforzó por eliminar los problemas en el extranjero,
para aclarar las cosas en casa.
Al haberse esparcido un rumor de un complot contra él (como ya se ha insinuado),
y a fin de estar más seguro del Parlamento,
hizo que un guarda se apostara a la puerta del Parlamento,
para mantener fuera a cualquier miembro que rehusara firmar un documento,
en el que debía prometer serle fiel al señor protector,
y no alterar el gobierno tal como estaba establecido.
Pero varios de los miembros no quisieron firmar ese documento,
diciendo que era una violación a los privilegios
del Parlamento y que los privaba de su libertad.
Por lo tanto, esos eran mantenidos fuera,
pero otros que subscribieron dicho papel eran admitidos.
Sin embargo, esta asamblea, al no actuar a satisfacción de Cromwell,
fue disuelta por él después de sesionar sólo cinco meses.
Mientras tanto, el joven rey Carlos, que vivía en el exilio,
había dejado Francia y llegado a Colonia, en el Rin, donde se quedó por algún tiempo.

Ahora regreso a Londres, donde dejamos a G. Fox.
Él estaba trabajando continuamente en dicha ciudad, cumpliendo su deber en todas partes,
tanto de boca como de pluma, sin perder el tiempo.
Como había comisionados asignados para interrogar a los ministros,
les escribió un documento en el que les aconsejaba
examinar si ellos eran de los que los profetas,
Cristo y los apóstoles desaprobaban,
y de los que '`adulaban a las personas para obtener provecho,`'^
footnote:[Judas 1:16] etc.
Se quedó en Londres hasta el año 1655, y después de haber descargado su consciencia,
se fue a Bedfordshire y llegó a la casa de John Crook, un juez de paz,
donde había una gran reunión. Muchos fueron convencidos de la Verdad que él declaró,
entre los cuales estaba John Crook;
por esta causa pronto fue despedido de su cargo de juez.

Mientras G. Fox estaba en Bedfordshire, también estaba Alexander Parker,
uno de los primeros ministros entre los llamados Cuáqueros.
Pero los voy a dejar allí, para hablar a continuación de William Caton, quien,
como se ha dicho ya, vivía con la familia del juez Fell.
Cuando él tenía aproximadamente catorce años,
su padre logró que viviera con dicha familia, y su comportamiento era tan agradable,
que se le permitió ser el compañero del hijo del juez,
tanto de noche como de día. W. Caton comía como él comía, y lo acompañaba a cazar,
disparar y pescar, participando del mismo placer con él en todo,
y viviendo en tranquilidad y abundancia.
De modo que tenía motivos para alegrarse de que la Providencia
hubiera echado su suerte en tan notable familia,
no sólo por el juez Fell,
sino porque su esposa Margaret y sus hijas también eran personas reconocidas.
Al vivir en tan selecta compañía, William Caton creció en piedad,
y era muy celoso en cumplir con sus devociones privadas,
permaneciendo a menudo en la alcoba incluso después de que
el hijo del juez (su compañero de habitación) había bajado,
para poder derramar su corazón más libremente delante
de Dios en oración. Al llegar a los quince años,
diligentemente escribía los puntos principales de las conferencias a las que asistía,
porque los miembros de la familia que podían repetir sermones y parafrasearlos,
eran tenidos en alta estima.
Sin embargo, William Caton descubrió que lo que él repetía de esa manera,
no satisfacía el hambre y la sed de su alma inmortal.

Después de un tiempo, él y el hijo del juez,
que habían estado aprendiendo juntos Latín en la familia (pues un sacerdote los instruía),
fueron trasladados a una escuela en Hawkshead,
pero William encontró la compañía de sus compañeros de escuela
mucho menos deseable que la de la familia del juez.

En el año 1652, aproximadamente a mitad del verano,
G+++.+++ Fox llegó por primera vez a la casa del juez Fell
en Swarthmore (como se dijo en su momento).
Y aunque W. Caton se sorprendió de su no conformación a los saludos ordinarios,
esto no le impidió prestarle atención a la doctrina que él predicaba,
que en sustancia era, estar atentos a la luz con la que Cristo nos había alumbrado,
la cual, al resplandecer en nuestros corazones nos convence del pecado y del mal.
Esto lo alcanzó de tal manera,
que a su debido tiempo empezó a sujetarse a ese convencimiento interior,
por el que llegó a ser mucho más recatado en su conducta y a no permitirse tanta libertad,
como estaba acostumbrado a hacer; porque aunque él en ninguna forma era extravagante,
ya veía que el verdadero Cristiano debe destetarse de toda vanidad,
y que las diversiones comunes de la juventud eran desagradables para Dios.
Esto lo percibió claramente,
pues el Testigo de Dios lo había despertado y lo reprendía por todo lo
que era contrario a la verdadera seriedad y sobriedad de mente.
Él no había terminado la escuela aún, pero,
aunque estaba bastante avanzado en su aprendizaje,
la composición de versos en Latín se había convertido en una carga para él,
porque no podía entregarles a sus pensamientos la
misma libertad para inventar que le daban los demás,
ni tampoco podía seguir dándole al maestro de la escuela el cumplido del sombrero,^
footnote:[Es decir, quitarse el sombrero e inclinarse.]
como lo había hecho antes (esto lo escuché de su propia boca).
Uno podría fácilmente suponer, que se había visto en un aprieto por causa de esto,
pero Margaret Fell, viendo que él anhelaba ser libre de la escuela,
hizo que se quedara en la casa,
donde fue empleado por ella para escribir y enseñarles a sus hijos.
Cuando tenía unos diecisiete años, se fortalecía más y más en la lucha espiritual,
y su corazón a menudo se llenaba de gozo,
debido a la misericordiosa y amorosa bondad de Dios para con él.

Así, al avanzar en piedad,
a menudo era movido a ir a los lugares de culto público y a los mercados,
a llamar a las personas al arrepentimiento;
en esas ocasiones los golpes y las bofetadas eran su porción,
y debido a su juventud muchos lo despreciaban.
Sin embargo, no desmayó, y pronto,
al estimar su deber entregarse al ministerio del evangelio,
deseaba ser liberado de su servicio.
El juez Fell no estaba muy dispuesto a separarse de él,
pero su esposa Margaret (aunque antes no había podido renunciar a él),
al creer que el Señor requería el servicio de W. Caton,
no sólo renunció voluntariamente a él,
sino que también prevaleció sobre su esposo para que lo dejara ir,
pues no deseaba su libertad para servirles a otros hombres,
sino para entrar al servicio del Señor y proclamar el evangelio eterno.
A finales del año 1654, teniendo dieciocho años, se despidió de la familia,
lo cual no estuvo exento de mutuo derramamiento de lágrimas al separarse.

Entonces fue a visitar a sus amigos en Lancashire, Yorkshire, Derbyshire y Warwickshire,
de ahí a Norwich, y así a Wellingborough, en Northamptonshire,
donde tuvo oportunidad de declarar la Verdad de Dios en
la '`casa del campanario.`' Después de eso viajó a Cambridge,
visitó a sus amigos ahí y luego regresó a Norwich,
donde visitó a sus amigos en prisión y tuvo grandes reuniones en dicha ciudad.
Luego se fue a Londres,
donde fue muy amablemente recibido por los de la familia de la fe,
y el Primer-día estuvo en dos '`casas del campanario.`'
En una de esas tuvo gran libertad de hablar,
siendo, en verdad, muy persuasivo en el discurso;
y en la tarde tuvo libertad de predicar la Verdad, sin oposición o contradicción,
en la reunión de los que disentían del culto público.
Muchos fueron añadidos a la fe,
porque en ese momento había doce hermanos ministrando en Londres,
la mayoría de los cuales habían descendido del Norte de Inglaterra.
Entre estos estaba el ya mencionado John Stubbs, con quien William viajó a Kent,
y al llegar a Dover, donde eran completos extraños y no conocían a nadie en el pueblo,
se alojaron en una posada.

John Stubbs fue el Primer-día a una reunión de los Bautistas,
y William Caton a la '`casa del campanario,`' donde se le concedió poca libertad;
sin embargo,
en el jardín tuvo más oportunidad para descargar su consciencia ante la gente.
En la tarde subió al castillo,
donde los Independientes realizaban su adoración. Poco después,
él y John Stubbs fueron a la reunión de los Bautistas,
donde había un gran número de personas y muchas comenzaron
a ser afectadas por el testimonio de ellos,
y se unieron a este.
Esto causó tal revuelo, que fueron llevados ante los magistrados,
quienes los interrogaron y ordenaron que nadie los hospedara,
so pena de enfrentar cierta pena; con lo cual, fueron echados de su alojamiento.

Pero un tal Luke Howard, un zapatero, que ya había oído a W. Caton en Londres,
y después en el jardín de la casa del campanario en Dover,
aunque lo había valorado poco en Londres y le había dicho a su compañero:
"`Sé más de lo que él pueda decirme,
o más de lo que él o yo seamos capaces de cumplir;`" en ese momento
estaba tan afectado por el testimonio de William Caton,
que lo invitó a él y a John Stubbs a su casa,
donde los recibió. No mucho después de eso tuvieron una reunión ahí,
y él oyó el testimonio de sus invitados con no menos satisfacción de la
satisfacción con la que el antiguo Agripa escuchó el discurso del apóstol,
cuando le dijo: "`Por poco me persuades a ser cristiano.`"^
footnote:[Hechos 26:28]
Pues Luke Howard no había llegado aún tan lejos,
como para resolver unirse a los llamados Cuáqueros; pero aun así,
tal era su amor por ellos,
que cuando el alcalde del pueblo envió a cuatro alguaciles a su casa,
con la orden de que los entregara para que fueran sacados del pueblo,
él se rehusó hacerlo, confiando en su derecho como hombre libre de la sociedad.
Así que cerró las puertas y dejó fuera de su casa a los alguaciles,
y les dijo por la ventana de la tienda,
que el alcalde no tenía autoridad legal para sacar a los hombres de su casa,
ni de enviarlos fuera de la ciudad, ya que no había ninguna citación pública para ellos.
Por tanto, W. Caton y J. Stubbs se quedaron algunos días más en su casa,
y él se fortaleció tanto por el ministerio de ellos, que se les unió en la profesión,
y también ofreció su casa como lugar de reunión para sus amigos.

Entonces William Caton y John Stubbs dejaron el pueblo y fueron a Folk-stone,
y de ahí a Hithe; en ambos lugares encontraron oportunidad de predicar la Verdad.
Después de unos días de estadía, se fueron a Romney,
y luego a Lydd.
Ahí, fue cuando Samuel Fisher, tanto por el ministerio de ellos,
como por el de Ambrose Rigge y Thomas Robinson (quienes
también habían salido en el servicio del evangelio),
fue convencido y acercado a su sociedad.

Samuel Fisher era un hombre formado en literatura,
que había estudiado diligentemente en la Universidad, y aunque entonces era joven,
era de conducta piadosa y le disgustaban muchas de
las ceremonias y costumbres habituales de las escuelas.
Cuando terminó sus estudios ahí, fue ordenado sacerdote de la iglesia de Inglaterra,
y cierto hombre rico lo tomó como su capellán;
a partir de eso recibió un salario de la parroquia de Lydd,
estimado en unas doscientas libras al año. Pero después
de haber sido empleado por un tiempo,
llegó a ver que el bautismo infantil era una institución humana,
y que predicar a cambio de un salario era ilícito.

Ahora, es notable que el anteriormente mencionado Luke Howard,
algún tiempo antes de conocer a los llamados Cuáqueros,
no estaba satisfecho con respecto al canto de los salmos de David en la adoración pública,
y esto intranquilizó tanto al maestro de quien había sido aprendiz,
que este logró que Samuel Fisher, como ministro erudito,
llegara y conversara con él para tratar de convencerlo.
Al llegar Samuel Fisher, Luke Howard le dijo: "`Dios es Espíritu,
y debe ser adorado en Espíritu y en Verdad, por todos los que lo adoren aceptablemente.`"
Además dijo: "`Es contrario a la Verdad,
que un hombre orgulloso cante las palabras de David que dicen,
que '`su corazón no se había envanecido, ni sus ojos se habían enaltecido,
ni se había preocupado por cosas demasiado profundas para él,`'^
footnote:[Salmo 131:1]
cuando dicho hombre vive en orgullo; algo que Dios resiste.`"
Y añadió:
"`Creo que es muy inapropiado que un hombre cante
que '`ríos de agua han descendido de sus ojos,
porque no han guardado su ley,`'^
footnote:[Salmo 119:136]
cuando no ha experimentado verdadera pena ni arrepentimiento por sus propios pecados.`"

Estos comentarios de Luke Howard,
contra los acostumbrados cantos en los servicios de adoración de ellos,
tuvieron tal influencia sobre Samuel Fisher,
que a partir de ese momento dejó de dar los estados que David expresaba en los salmos,
para que las personas cantaran.
Con el tiempo,
al estar cada vez más intranquilo de seguir con una
tarea que era una carga para su consciencia,
decidió dejar su ministerio,
fue al obispo y renunció al encargo que había recibido de él para predicar.
Luego, arrojándose a la providencia de Dios, tomó una granja y se volvió pastor,
por medio de lo cual mantenía a su esposa e hijos en una paz mucho mayor que antes.

Tras separarse de la iglesia Episcopal se fue a los Bautistas,
y se convirtió en un maestro celoso entre ellos.
Fue por ese tiempo, que William Caton y John Stubbs llegaron a Lydd,
a quienes Samuel Fisher recibió en su casa, recordando que las Escrituras exhortan:
"`No os olvidéis de la hospitalidad, porque por ella algunos, sin saberlo,
hospedaron ángeles.`"^
footnote:[Hebreos 13:2]
William Caton fue a la reunión de los Independientes y Stubbs a la de los Bautistas,
donde Fisher predicaba entonces.
Al tener la oportunidad de hablar,
Stubbs declaró la Verdad tan claramente que Samuel Fisher (estando muy
afectado por ella) empezó a parafrasearla con excelencia de palabras.
Dejando ese lugar, William Caton y John Stubbs fueron a otro pueblo del condado,
pero no mucho después regresaron a Lydd y encontraron
a Samuel Fischer en comunión con ellos.
Pues había sucedido que su compañero George Hammond,
había vituperado tan violentamente a los llamados Cuáqueros en un sermón,
que Samuel Fishel no pudo estar tranquilo hasta que se puso de
pie en la reunión y dio testimonio contra los insultos de Hammond,
diciéndole: "`Querido hermano, tú eres muy cercano a mí y me eres muy querido,
pero la Verdad está más cerca y me es más querida.
Es esta Verdad y el evangelio eterno lo que ellos sostienen.`"
Y diciendo más palabras en ese sentido,
abiertamente defendió la doctrina de los injuriados Cuáqueros.
Eso enojó tanto a Hammond, que cayendo en una rabia aún mayor dijo:
"`¡Nuestro hermano Fisher también ha sido hechizado!`"
Pero Fisher no devolvió insulto por insulto, sino que continuó con paciencia en la fe.
Este fue el que después escribió un libro llamado [.book-title]#Rusticus ad Academicos,#
en el que a menudo confundía a los sacerdotes con sus propias armas;
pues él era muy diestro en eso, y estaba tan bien versado en los poetas antiguos,
que de vez en cuando (con las palabras de ellos) les daba fuertes golpes a sus adversarios,
permitiéndose algunas veces la libertad del profeta Elías contra los profetas de Baal.
También escribió un documento en hebreo para los judíos, en cuyo idioma era muy hábil.
