== Capítulo 6

[.section-date]
1656

Al principio del año 1656, G. Fox fue de Londres a Surry, Chichester, Portsmouth y Poole,
donde William Baily, un maestro Bautista, y algunos otros,
fueron convencidos por el ministerio de G. Fox y
entraron a la sociedad de los llamados Cuáqueros.
Este Baily después se convirtió en un ministro eminente.
De Poole se fue a Southampton y Dorchester,
donde quería reunirse con los Bautistas en su lugar de reunión, pero como le fue negado,
les envió un mensaje diciendo que si lo deseaban podían ir a su posada.
Muchos de ellos llegaron, junto con su maestro,
y trabaron una conversación sobre el bautismo en agua.
G+++.+++ Fox les preguntó si ellos podían decir que habían
sido enviados por Dios a bautizar personas,
como había sucedido con Juan;
y si ellos tenían el mismo Espíritu y poder que tenían los apóstoles.
Ellos respondieron que no.
Entonces Fox les preguntó: "`¿Cuántos poderes hay?
¿Hay más poderes que el poder de Dios y el poder del diablo?`"
Ellos dijeron: "`No hay ningún otro poder además de esos dos.`"
"`Entonces,`" dijo G. Fox,
"`si ustedes no tienen el poder de Dios que tenían los apóstoles,
actúan por el poder del diablo.`"
Sus palabras tuvieron tal efecto,
que muchos personas importantes fueron convencidas esa noche.
Pero a la mañana siguiente cuando se estaba yendo,
algunos de los Bautistas empezaron a sacudirse el
polvo de los pies detrás de él. "`¿Qué,`" les dijo,
"`en el poder de las tinieblas?
¡Nosotros, los que estamos en el poder de Dios,
sacudimos el polvo de nuestros pies contra ustedes!`"

Dejando Dorchester, llegó a Weymouth, donde al preguntar por las personas sobrias,
cerca de ochenta de ellas se reunieron en la casa del sacerdote,
y la mayoría se volvió a Jesucristo, quien los había alumbrado con Su luz divina,
por medio de la cual fueron reprendidos por sus pecados.
Había en ese tiempo en el pueblo un oficial que cabalgó
con G. Fox unas siete millas fuera del pueblo.
Este oficial era de un carácter tan alegre y tan dado a la risa,
que G. Fox habló muy seriamente con él de eso varias veces,
pero había llegado a ser tan habitual para él,
que se reía de casi todo lo que veía. Sin embargo,
G+++.+++ Fox lo amonestó a la seriedad y al temor del Señor,
y le habló de nuevo sobre eso cuando se separaron.
La siguiente vez que George lo vio,
el capitán le contó que cuando le había hablado al momento de separarse,
el poder de Dios lo había impactado tanto,
que antes de llegar a la casa estaba suficientemente serio y había dejado de reírse.
En efecto, él se convirtió en un hombre serio y bueno, y al ser convencido de la Verdad,
murió en la verdadera profesión de esta.

Por un asunto de brevedad,
no pretendo mencionar todos los lugares por los que G. Fox pasó, y mucho menos,
hablar de todo lo que le ocurrió. En Kingsbridge tuvo buen servicio,
y luego regresó a su posada al anochecer.
Había allí muchas personas tomando,
y fue movido a ir entre ellos y dirigirlos a la luz con la que Cristo,
el hombre celestial, los había alumbrado;
por medio de dicha luz podrían ver todos sus malos caminos, palabras y hechos,
y también a Jesucristo su Salvador.
Pero esta conversación no le gustó al posadero,
al ver que esto impediría que sus huéspedes tomaran,
y oyendo que G. Fox hablaba mucho de la luz, tomó una candela y dijo: "`Ven,
aquí hay luz para que entres en tu habitación.`"

Al día siguiente G. Fox se fue a Plymouth y de ahí a Cornwall, y viajando por el condado,
llegó a Market-Jew.
Ahí, mientras estaba en una posada,
se topó con algunos problemas de parte de los magistrados.
Él había escrito un documento para mostrar que el Señor
había venido para enseñarle a Su pueblo por medio de Jesucristo, etc.
Este documento accidentalmente había llegado a las manos de Peter Ceely,
un mayor del ejército, que también era juez de paz en Ives,
adonde G. Fox llegó. Ahí Edward Pyot y William Salt (que estaban
viajando con G. Fox) fueron arrastrados ante el mencionado mayor,
mientras Fox bajaba a lo orilla del mar.
Pero al oír esto, George los siguió y también llegó a la casa del juez,
donde se presentó el mencionado documento.
Allí le preguntaron si él admitía haberlo escrito.
Él dijo: "`Sí.`" Entonces el mayor le presentó el juramento de repudio,
por lo que G. Fox metió su mano en el bolsillo y
sacó la respuesta que le había dado al protector.
Un sacerdote que estaba presente encontró una falta en su cabello,
que en ese entonces estaba bastante largo, y pidió que se lo cortaran;
pero G. Fox le dijo que él no tenía ningún orgullo en él.
Luego Fox y sus compañeros fueron puestos bajo custodia,
y con una guardia de jinetes fueron enviados a prisión
con la siguiente orden de la corte:

[.embedded-content-document.legal]
--

[.blurb]
=== Peter Ceely, uno de los jueces de paz de este condado, al guarda de la cárcel de su alteza en Launceston, o a su representante legítimo en ese nombre, saludos:

Le mando por medio de los portadores de esta carta, a Edward Pyot, de Bristol,
a George Fox, de Drayton and Clay, en Leicestershire, y a William Salt, de Londres,
las ciudades que ellos declaran ser sus lugares de habitación,
que andan bajo el concepto de Cuáqueros y que ellos mismos se reconocen como tales.
Estos han esparcido documentos que tienden a perturbar la paz pública;
no pueden proporcionar ninguna razón legítima para haber venido a estos lugares;
son personas completamente desconocidas; no tienen pases para sus viajes en el condado;
rehúsan dar garantías de buen comportamiento, según la ley estipulada para ese efecto;
rehúsan tomar el juramento de repudio, etc.
Por tanto, esta orden es, en el nombre de su alteza, el señor protector,
para ordenarle y darle instrucciones, para que cuando los mencionados Edward Pyot,
George Fox y William Salt sean llevados ante usted los reciba,
y en la prisión de su alteza ya mencionada,
los asegure hasta que por el debido proceso de la ley sean liberados.
No falle, porque responderá a lo contrario bajo su propio riesgo.

Firmada y sellada en St. Ives, el 18 de Enero de 1656.

[.signed-section-signature]
P+++.+++ Ceely.

--

Por esta orden se ve bajo qué extraños pretextos
fueron encerrados en prisión los llamados Cuáqueros,
pues las razones tal como son mencionadas en ella,
se podrían encontrar y acusar en cualquier momento.
Así, pues, G. Fox y sus compañeros fueron llevados a través de Redruth,
Falmouth y Bodmin, a Launceston.
En el camino sufrieron grandes maltratos, tanto de los soldados que los conducían,
como de otros, con la complicidad del capitán Keat;
pero no detendré a mi lector con todos esos detalles.
Al llegar a Launceston, Keat entregó a los prisioneros al carcelero.
Muchos estaban muy enfurecido contra ellos, y esperaban que estos prisioneros
(que hablaban de "`ti`" y de "`tú`" a todos, y no se quitaban el sombrero ante nadie)
fueran condenados a la horca, si no le rendían ese respeto a la corte.
Sin embargo,
muchas personas amistosas de varias partes del condado llegaron a visitarlos,
pues transcurrieron cerca de nueve semanas desde el momento
en que fueron encerrados hasta la sesión de la corte,
de modo que muchos tuvieron oportunidad de hablar con ellos,
lo cual produjo un efecto tan bueno,
que varios fueron convencidos de la verdad de la doctrina que ellos sostenían.

En el momento de la sesión de la corte,
una gran cantidad de personas llegaron de lejos y de cerca,
para oír el juicio de los Cuáqueros,
quienes siendo custodiados por soldados y por los hombres del alguacil hacia la corte,
tuvieron muchas dificultades para atravesar la multitud que llenaba las calles;
y hasta las puertas y ventanas estaban llenas de personas que los miraban.
Cuando entraron a la corte, después de que se hizo silencio, G. Fox dijo:
"`Paz sea entre ustedes.`"
El juez Glyn, quien en ese entonces era presidente del Tribunal de Inglaterra,
le dijo al carcelero: "`¿Quiénes son estos hombres que has traído a la corte?`"
"`Prisioneros,
mi señor,`" dijo él. "`¿Por qué no se quitan los
sombreros?,`" les preguntó el juez a ellos.
Como no dijeron nada en respuesta, el juez les dijo de nuevo:
"`Quítense los sombreros;`" y como continuaron en silencio, el juez dijo:
"`La corte les ordena quitarse los sombreros.`"
Entonces G. Fox empezó a hablar y dijo: "`¿Cuándo alguna vez un magistrado, rey o juez,
desde Moisés hasta Daniel,
le ordenó a alguien quitarse el sombrero cuando estaba ante ellos en sus cortes;
ya fuera entre los judíos (el pueblo de Dios) o entre los paganos?
Si la ley de Inglaterra ordena algo así, muéstrame la ley escrita o impresa.`"
El juez cada vez más enojado dijo:
"`¡No cargo mis libros de derecho en mi espalda!`" "`Pero,`" dijo G. Fox,
"`¿está impresa en algún libro de estatutos, para que yo pueda leerla?`"
Ante esto el juez dijo: "`¡Saquen a este bribón! ¡Le voy a dar un escarmiento!`"
Entonces los prisioneros fueron sacados y puestos entre los ladrones,
pero poco después el juez le dijo al carcelero: "`Tráelos de nuevo.`"
Hecho esto, dijo: "`Veamos, ¿dónde se dice que de Moisés a Daniel tuvieran sombreros?
Respóndeme; ¡ya te tengo!`"
G+++.+++ Fox replicó: "`Puedes leer en el tercer capítulo de Daniel,
que tres jóvenes fueron arrojados a un horno ardiente, por orden de Nabucodonosor,
con sus mantos, pantalones y gorros puestos.`"
Este simple ejemplo lo detuvo; de modo que al no tener nada más que decir,
gritó de nuevo: "`¡Carcelero, llévatelos!`"
Por tanto, fueron llevados y siendo arrojados entre los ladrones,
los retuvieron ahí por un rato, y finalmente fueron trasladados a prisión otra vez;
pero en la tarde fueron llevados nuevamente a la corte.

G+++.+++ Fox, viendo a los miembros del jurado presentes,
les dio un documento que él había escrito contra el acto de jurar.
Este documento pasó del jurado a los jueces, y ellos se lo presentaron al juez;
este le pidió al secretario que le diera a G. Fox el documento,
y luego le preguntó si ese "`documento sedicioso`" era de
él. George solicitó que lo leyeran en audiencia pública,
para que él pudiera oírlo, y si era de él,
lo reconocería y lo respaldaría. El juez quería que
G+++.+++ Fox lo cogiera y lo mirara en sus propias manos,
pero él volvió a pedir que fuera leído,
para que todos en la corte oyeran y juzgaran si había o no sedición en él;
porque si la había, él estaba dispuesto a sufrir por eso.
Finalmente, el secretario de la sesión de la corte lo leyó en voz alta,
y cuando terminó G. Fox dijo: "`Es mi documento y lo reconozco;
y ustedes también deberían, a menos que nieguen la Escritura.
Porque, ¿acaso no es lo que dice la Escritura,
y las palabras y órdenes de Cristo y los apóstoles,
lo que todo verdadero Cristiano debe obedecer?`"

Entonces dejaron ese tema de lado,
y el juez hablando otra vez sobre los sombreros de los prisioneros,
le pidió al carcelero que se los quitara.
Los prisioneros preguntaron la razón por la que habían
permanecido en prisión por esas nueve semanas,
viendo que nada era objetado contra ellos, excepto lo que concernía a sus sombreros.
"`Y en cuanto a quitarnos los sombreros,`" dijo G. Fox,
"`ese es un honor que Dios pondrá en el polvo,
aunque ustedes hagan mucho ruido al respecto.
Porque el honor que es de los hombres, y que los hombres buscan unos de otros,
es la marca de los incrédulos.
Pues Cristo dijo: '`¿Cómo pueden creer,
los que reciben honor unos de otros y no buscan el
honor que viene del único Dios?`' Y también dijo:
'`Gloria no recibo de los hombres.`' Y todos los
verdaderos Cristianos deben ser de Su mente.`"
Entonces el juez dio un discurso acerca de cómo él
representaba a la persona del señor protector,
y cómo el protector lo había nombrado presidente del Tribunal de Inglaterra, etc.
Al oír esto, los prisioneros le pidieron que les hiciera justicia,
por el encarcelamiento ilegal que habían sufrido por nueve semanas.

Pero en lugar de esto, se leyó contra ellos una acusación tan llena de falsedades,
que G. Fox pensó que la acusación era contra algunos de los ladrones,
pues contenía una acusación que decía,
que ellos habían entrado a la corte por la fuerza de las armas y de manera hostil;
aunque la verdad era, que habían sido llevados como prisioneros.
Esto hizo que George dijera que todo era falso,
y clamaron por justicia por su encarcelamiento ilegal,
habiendo sido capturados en su viaje sin ninguna causa, por el mayor Ceely.
Entonces el mencionado Peter Ceely,
quien como juez de paz también estaba sentado en el tribunal, le dijo al juez:
"`Puede que te complazca, mi señor, escucharme.
Este hombre (señalando a G. Fox),
se apartó conmigo y me dijo cuán útil podría serle yo para su plan,
y que en una hora podía levantar cuarenta mil hombres, envolver la nación en sangre,
y así traer al rey Carlos.
Yo le habría ayudado a salir del condado, pero no quiso irse.
Y si te place, mi señor, tengo un testigo que lo jurará.`" Entonces llamó a su testigo,
quien sin ninguna duda, había sido sobornado.
Pero el juez, percibiendo la evidente mentira, no se apresuró a interrogar al testigo.
Entonces G. Fox le pidió al juez que se complaciera en permitir
que se leyera la orden de la corte en su contra,
en la que estaba indicado el pretendido crimen por
el que él había sido encerrado en prisión;
pero el juez dijo que no sería leída. G. Fox que seguía insistiendo que se leyera, dijo:
"`Debería ser leída, porque si he hecho algo digno de muerte o de cadenas,
entonces que todo el condado lo sepa.`"
Viendo que ellos no la leerían, le dijo a uno de sus compañeros de prisión:
"`Tú tienes una copia de ella, léela.`"
"`No será leída,`" dijo el juez; "`carcelero, llévatelo.
Veré si él o yo será el amo.`"

Luego se llevaron a G. Fox y después de un rato fue llamado de nuevo.
Él todavía pedía que se leyera su orden de la corte,
y como las personas estaban ansiosas de que fuera leída,
le pidió a su compañero de prisión que la leyera.
Una vez hecho, G. Fox le dijo al juez y a los jueces:
"`Tú que dices que eres el presidente del Tribunal de Inglaterra,
y ustedes que son jueces, saben, que si yo hubiera dado garantías,
habría podido ir adonde hubiera querido, y habría podido llevar a cabo el plan,
si hubiera tenido uno, del que el mayor Ceely me ha acusado.
Y si yo le hubiera dicho esas palabras a él, las que él ha declarado,
entonces ustedes podrían juzgar si por un caso así,
se habrían podido tomar fianzas o garantías.`"

Luego dirigiendo su discurso al mayor Ceely, le dijo: "`¿Cuándo o dónde te llevé aparte?
¿No estaba tu tribunal lleno de personas rudas,
y no estabas tú tan rudo como cualquiera de ellas durante nuestro interrogatorio,
de modo que pedí un alguacil, u otro oficial,
para que las personas se mantuvieran respetuosas?
Y si tú eres mi acusador, ¿por qué te sientas en el tribunal?
No puedes sentarte en ese lugar, porque los acusadores no se sientan con los jueces;
debes bajar, quedarte a mi lado y mirarme a la cara.
Además, quiero preguntarles al juez y a los jueces:
¿Es culpable o no el mayor Ceely de la traición de la que me acusa,
al ocultarla tanto tiempo como lo ha hecho?
¿Entiende él su posición, ya sea como soldado o como juez de paz?
Porque él les dice aquí,
que yo me aparté con él y que le dije el plan que tenía en mente,
y cuán útil podría ser él para dicho plan--que yo podía
levantar cuarenta mil hombres en el lapso de una hora,
que traería al rey Carlos y envolvería la nación en sangre.
Además, él declaró que él me habría ayudado a salir del condado,
pero que yo no había querido, y por tanto,
que me había encerrado en prisión por carecer de garantías de buen comportamiento,
tal como declara la orden judicial.
Ahora, ¿no ven claramente,
que el mayor Ceely es culpable de ese plan y de la traición de la que habla,
y que se ha hecho cómplice de esta,
al desear que yo saliera del condado y demandarme fianza,
además de no acusarme de la supuesta traición hasta ahora, ni descubrirla?
Pero yo niego y aborrezco sus palabras, y soy inocente de su diabólico plan.`"

Viendo el juez claramente por medio de esto, que Ceely,
en lugar de atrapar a G. Fox se había atrapado a sí mismo, dejó el asunto por completo.
Pero Ceely, se levantó de nuevo y le dijo al juez: "`Si se complaciera mi señor,
en escucharme: Este hombre me atacó y me dio un golpe tan fuerte,
como nunca había sentido en mi vida.`"
G+++.+++ Fox sonriendo ante esto, dijo: "`Mayor Ceely,
¿eres tú juez de paz y mayor de una tropa de jinetes,
y le dices al juez en presencia de la corte y del condado, que yo, que soy un prisionero,
te ataqué y te di un golpe tan fuerte, como nunca habías sentido en tu vida?
¡Qué! ¿No te avergüenzas?
Yo te pregunto, mayor Ceely, ¿dónde te ataqué y quién es tu testigo?
¿Quién estaba presente?`"
A esto Ceely dijo que había sucedido en el jardín del castillo,
y que el capitán Bradden estaba presente cuando G. Fox lo había atacado;
y luego quiso que el juez le permitiera presentar a su testigo.
George llamó a Ceely nuevamente a bajar del tribunal,
diciéndole que no era adecuado que el acusador se sentara como juez sobre el acusado.
Ceely dijo entonces: "`El capitán Bradden es mi testigo.`"
Esto hizo que G. Fox le dijera al capitán Bradden (que estaba presente en la corte):
"`¿Me has visto tú atacar a este hombre y golpearlo como dice él?`" Bradden no respondió,
únicamente inclinó su cabeza.
G+++.+++ Fox quería que él hablara, si sabía de algo así,
pero únicamente inclinó su cabeza de nuevo.
"`No,`" dijo G. Fox, "`habla y deja que la corte y el condado escuchen,
y no dejes que la inclinación de cabeza sirva como respuesta.
Si he hecho eso, que la ley se imponga sobre mí. No le temo a los sufrimientos,
ni a la muerte misma; pues soy un hombre inocente con respecto a todas sus acusaciones.`"
Pero Bradden no quiso testificar de eso.
El juez, al encontrar que esas trampas eran insostenibles, gritó: "`¡Llévatelo,
carcelero!,`" y multó a cada prisionero con veinte marcos^
footnote:[Equivalente a trece chelines y cuatro peniques.]
por no quitarse el sombrero,
y dijo que tenían que permanecer en prisión hasta que pagaran la multa;
y así fueron llevados de regreso a la cárcel.

En la noche el capitán Bradden llegó con siete u ocho jueces para ver a los prisioneros,
y siendo muy corteses, dijeron que ellos no creían que el juez, ni nadie en la corte,
creyeran las acusaciones que el mayor Ceely había hecho contra G. Fox.
Bradden dijo, que el mayor Ceely tenía la intención de quitarle la vida a G. Fox,
si hubiera podido conseguir otro testigo.
"`Pero, capitán Bradden,`" dijo G. Fox,
"`¿por qué no testificaste a mi favor o en mi contra,
siendo que el mayor Ceely te presentó como testigo, de que tú me habías visto atacarlo?
Y cuando quise que hablaras a favor mío o en contra, según lo que habías visto o sabías,
tú no quisiste hablar.`"
A esto Bradden contestó: "`Cuando el mayor Ceely y yo pasábamos a tu lado,
mientras caminabas en el jardín del castillo, él se quitó el sombrero ante ti y dijo:
'`¿Cómo está, Sr. Fox?
Soy su sirviente, señor.`' Entonces tú le dijiste: '`Mayor Ceely,
ten cuidado con la hipocresía y el corazón corrupto,
porque ¿cuándo me convertí en tu señor y tú en mi sirviente?
¿Meten los sirvientes a sus amos en prisión?`' Este
fue el gran golpe que él dice que le diste.`"
Al oír G. Fox esto, recordó que cuando ellos estaban pasando,
en efecto Ceely había dicho las palabras citadas,
y que él le había dado la respuesta tal como fue mencionada.
Ahora estaba claro que George no se había equivocado en sus palabras,
viendo cómo Ceely había manifestado abiertamente su hipocresía y corrupto corazón,
cuando se quejó de esto ante el juez en la audiencia pública,
haciendo que todos creyeran que G. Fox lo había golpeado externamente con su mano.
Un informe de este juicio se difundió en el exterior,
y muchas personas (algunas de ellas de gran importancia en el mundo) de lejos y de cerca,
llegaron a verlo a él y a sus amigos en prisión,
lo que inclinó a muchos al convencimiento.

Estando instalados en prisión en un confinamiento del que
no era probable que fueran a ser liberados pronto,
se negaron a darle al carcelero siete chelines por semana por cada uno de ellos,
así como por sus caballos,
con lo que él de alguna manera había tratado de extorsionarlos.
Pero en esta ocasión, se volvió tan malvado, que los puso en un lugar sucio y apestoso,
donde se solían poner a las personas condenadas por brujería y asesinato.
Este lugar era tan absolutamente vil, que se observó que pocos de los que entraban en él,
salían de nuevo sanos;
porque no había letrina y el excremento que los prisioneros
con el paso del tiempo habían depositado ahí,
no se había sacado por muchos años. Así pues, todo era como lodo,
y en algunos lugares la profundidad alcanzaba la parte alta de los zapatos;
y el carcelero no les permitía limpiarlo,
ni les dejaba tener camas o paja para acostarse.

Por la noche,
unas amables personas del pueblo les llevaron una candela y un poco de paja,
de la que quemaron un poco para quitar el hedor.
Los ladrones se acostaban en el piso de arriba de sus cabezas,
y el carcelero principal tenía una habitación al lado de ellos,
también arriba de sus cabezas.
Al parecer el humo subió a la habitación donde estaba acostado él,
y esto lo enfureció tanto,
que tomó el cubo de excrementos de los ladrones y lo vació
a través de un hueco sobre las cabezas de ellos,
por lo que quedaron tan salpicados, que era repugnante tocarse a sí mismos,
o unos a otros; además, el hedor se incrementó tanto, que por ello y el humo,
corrieron el peligro de asfixiarse.
Sin embargo, nada de eso satisfizo la rabia de este cruel carcelero,
y los maldijo tan horriblemente y los llamó con apodos tan terribles,
como nunca antes habían oído algo así. Como resultado de eso,
se vieron obligados a permanecer de pie toda la noche,
pues no se podían sentar porque el lugar estaba asqueroso.
Así los mantuvo un gran rato antes de dejarlos limpiar,
o permitirles que trajeran algo de comida,
además de lo que ellos obtenían a través de la reja.
Ni siquiera esto se podía hacer sin dificultad, pues en una ocasión,
el carcelero demandó a una joven en la corte del pueblo,
por irrumpir en la prisión llevándoles un poco de comida; tal vez,
debido a que ella había doblado un poco una barra de la reja que estaba quebrada,
para pasar un pequeño plato a través de ella.
No es tan sorprendente que este carcelero fuera tan terriblemente malvado, ya que,
según fueron informados ellos, él había sido ladrón,
y por ese motivo habían sido quemados tanto en la mano como en el hombro,
él y su ayudante, y sus respectivas esposas que habían sido quemadas en la mano.^
footnote:[En este tiempo,
quemar la piel (marcación) era una forma común de castigo para varias tipos de crímenes,
y también servía como una marca indeleble que permanente y públicamente
manifestaba los antecedentes criminales de la persona.]
No era de extrañar entonces,
que los prisioneros sufrieran de la forma más dolorosa de personas tan malvadas;
pero lo más sorprendente era, que el coronel Bennet, un maestro Bautista,
tras comprar la cárcel y las tierras pertenecientes al castillo,
hubiera colocado a este hombre ahí como carcelero principal.

Se hablaba mucho, de que en ese calabozo había espíritus que rondaban y caminaban ahí,
y que muchos habían muerto en él;
pensando algunos en aterrorizar a los prisioneros con tales historias.
Pero G. Fox les dijo que si todos los espíritus y demonios del infierno estuvieran ahí,
él estaba sobre ellos en el poder de Dios y no temía tal cosa, pues Cristo,
el Sacerdote de ellos (quien había herido la cabeza del diablo),
santificaría las paredes y la casa para ellos,
tal como el sacerdote tenía que limpiar la lepra
de las paredes y de las casas bajo la ley.

Llegado el tiempo de las sesiones en Bodmin,
los prisioneros redactaron un documento con el relato de sus sufrimientos,
y lo enviaron allí. Al leerlo,
los jueces dieron la orden de que la puerta de Doomsdale
(así era llamado el calabozo) fuera abierta,
y que tuvieran libertad de limpiarlo y comprar su comida en el pueblo.
Tras obtener esta libertad,
ellos escribieron a Londres y le pidieron a Anne
Downer (una joven ya mencionada en esta historia),
que llegara, comprara y preparara la comida para ellos,
lo cual ella estuvo muy dispuesta a hacer.
De hecho, ella les fue muy útil,
y también era una buena escritora y podía tomar notas en taquigrafía.
Luego le enviaron un relato de sus sufrimientos al protector,
quien a su vez envió una orden al gobernador de Pendennis
Castle para que investigara el asunto.
En esta ocasión Hugh Peters, uno de los capellanes del protector,
le dijo que ellos no podían hacerle a George Fox un mayor
servicio para la propagación de sus principios en Cornwall,
que encarcelarlo ahí. Esto no era del todo falso,
porque él era visitado muy frecuentemente,
y muchos habían sido vueltos de las tinieblas a la luz;
a pesar de que el alcalde de Launceston era un fiero perseguidor,
arrojando en prisión a todo el que podía, e incluso,
registrando a mujeres serias y respetables en busca de cartas.

Las cosas no eran mucho mejor en Devonshire,
porque muchos de los llamados Cuáqueros que viajaban por el condado,
eran capturados y azotados bajo el pretexto de que eran vagabundos.
Sí, incluso unos sastres, que se dirigían a la fábrica con sus telas,
y otros hombres respetables, fueron detenidos y azotados.
Y Henry Pollexsen, que había sido juez de paz durante casi cuarenta años,
fue arrojado a la cárcel bajo el pretexto de ser Jesuita.

Mientras tanto, Edward Pyot,
que había sido capitán y era un hombre que tenía un buen
entendimiento de las leyes y derechos de la nación,
le escribió una larga carta al señor presidente del Tribunal, John Glyn,
en la que claramente le exponía sus tratos ilegales,
y le preguntaba si lo que él había dicho,
"`si se quitan los sombreros los escucharé y les haré justicia,`" no era una revocatoria
a las leyes que habían sido hechas para mantener los derechos y la justicia.
En la carta también se mencionaron muchos otros detalles, entre esos,
el "`ataque`" de G. Fox contra el mayor Ceely.
G+++.+++ Fox mismo escribió varios documentos en los que exponía claramente la odiosa persecución.

Entre los que llegaron a visitarlo, estaba Thomas Lower,
un doctor en medicina de Londres; quien, mientras escribo esto, todavía vive.
Él hizo muchas preguntas con respecto a asuntos religiosos,
y recibió respuestas tan satisfactorias de G. Fox,
que después dijo que sus palabras eran como rayos de luz que lo atravesaban,
y que nunca había conocido hombres tan sabios en toda su vida, etc.
De esta manera se convenció de la Verdad y entró
en la comunión de los despreciados Cuáqueros.
Mientras G. Fox seguía en prisión,
uno de sus amigos fue a ver a Oliver Cromwell y ofreció cambiar de lugar con él,
cuerpo por cuerpo, y permanecer en la prisión de Doomsdale,
si él lo permitía y dejaba a G. Fox en libertad.
Pero Cromwell le dijo que no podía hacerlo, porque era contra la ley;
y luego se volvió a los de su consejo y dijo:
"`¿Cuál de ustedes haría tanto por mí si yo estuviera en la misma condición?`"

Por tanto, G. Fox continuó en la cárcel,
y pasó un buen rato antes de que él y sus compañeros de prisión fueran liberados.
Sin embargo, el año siguiente el malvado carcelero recibió la recompensa de sus acciones,
porque fue removido de su posición,
y por algunos actos perversos él mismo fue arrojado en la cárcel,
y su actitud fue tan ingobernable ahí,
que el carcelero que lo sucedió lo metió en Doomsdale, asegurado con grilletes, golpeado,
y obligado a recordar cómo había abusado de aquellos buenos hombres que él,
perversamente y sin ninguna causa, había lanzado en aquel asqueroso calabozo.
Sin embargo, él sufría merecidamente por su maldad,
y la misma medida que había usado para otros, ahora era usada en él, etc.
Y así, este malicioso tipo,
quien habría podido hacerse rico si se hubiera comportado cortésmente,
se hizo muy pobre y así murió en prisión.

Aproximadamente al mismo tiempo que G. Fox fue liberado, Cromwell convocó un Parlamento,
que se reunió para la primera sesión en la cámara pintada en Westminster,
el 17 del mes llamado Septiembre.
Samuel Fisher tuvo la oportunidad de entrar a esta asamblea,
donde escuchó el discurso del protector,
en el que Cromwell dijo que él no conocía a ningún hombre
que hubiera sufrido un encarcelamiento injusto en toda Inglaterra.
Y S. Fisher, después de que tuvo la oportunidad de ponerse de pie,
dijo que tenía una palabra del Señor para el protector, el Parlamento y el pueblo,
y comenzó así:

[.embedded-content-document]
--

El peso de la palabra del Señor Dios del cielo y de la tierra vino sobre mí,
el día 22 del pasado mes, y ahora recae sobre mí declararla en Su nombre,
a ti Oliver Cromwell, protector (así llamado) de estas tres naciones, Inglaterra,
Escocia e Irlanda; a todos ustedes también,
los que han sido escogidos de entre varios lugares de estas
naciones para ocupar un escaño en el Parlamento hoy,
con el fin de considerar las cosas concernientes a la mancomunidad; y de igual modo,
a las tres naciones mismas, y a todo el pueblo de ellas,
cuyos gobernantes y representantes son ustedes.
Y como seguramente ustedes no se consideran demasiado altos, ni demasiado grandes,
ni demasiado buenos para que el Señor les hable,
ni tampoco desean caer bajo la culpa del pecado de decirles "`a los videntes: No veáis;
y a los profetas: No nos profeticéis lo recto, decidnos cosas halagüeñas,
profetizad mentiras,`"^
footnote:[Isaías 30:10]
les pido a todos, en nombre del Dios vivo, que sin interrupción ni oposición,
sea que les guste o no, permanezcan quietos y escuchen, y cuando yo haya finalizado,
pueden hacer conmigo lo que el Señor les permita,
siendo que ninguna ley de equidad condena a un hombre antes de ser escuchado,
especialmente cuando habla por una razón tan elevada, como en nombre del Dios del cielo.

--

Apenas había hablado así, cuando alguien gritó: "`¡Un Cuáquero, un Cuáquero; bájenlo;
que no hable!,`" aunque el protector y los hombres
del Parlamento permanecían quietos y tranquilos.
Pero algunos otros, entre los que se encontraban dos jueces de paz,
no tuvieron tanta paciencia.
Sin embargo, Fisher, como relató después,
creía que el protector y los hombres del Parlamento le habrían dado audiencia,
si los otros no lo hubieran despreciado e ignorado--algunos decían
que Cromwell ya había hablado mucho y estaba muy acalorado y cansado,
y que él, +++[+++Fisher]
debería avergonzarse por hacer que el protector se quedara más tiempo.
Así fue interrumpido Fisher,
y el protector y los hombres del Parlamento se levantaron y se fueron.

Como se le prohibió a Fisher hablar, publicó más tarde su discurso en forma impresa,
tal como había intentado pronunciarlo,
aunque ni una sílaba de este había sido escrita antes.
Era bastante largo y contenía una dura reprimenda contra
la hipocresía de los que bajo una apariencia de piedad,
hacían largas oraciones y mantenían ayunos, a pesar de que vivían en orgullo,
pompa y lujo, y persiguiendo a los que realmente eran personas piadosas.
Al protector le dijo, que a menos que quitara a los malvados de delante de él,
a todas la voces aduladoras y a los falsos acusadores,
su trono nunca sería establecido en justicia.
En la introducción de su discurso impreso decía,
que antes de que le sobreviniera esa carga,
le había rogado a Dios que lo dispensara de entregar ese mensaje,
pues pensaba que no se habría podido escoger una persona más indigna que él. Sin embargo,
que sin importar lo que había hecho, no había podido ser liberado de ella;
que aunque había pasado toda una semana en ayuno, lágrimas y súplicas,
durante ese tiempo de abstinencia había sentido una
provisión diaria y un refrescamiento en su espíritu;
por lo que finalmente se había rendido por completo para
hacer lo que creía que el Señor le estaba pidiendo,
y que luego había sentido que todos los temores a los ceños
fruncidos de los hombres le habían sido quitados.
Varios otros discursos que intentó pronunciar en el Parlamento,
pero que no pudo porque se lo impidieron, los publicó en forma impresa posteriormente.

En la última parte de este año, sucedió que al llegar Humphrey Smith a Evesham,
en Worcestershire, fue interrumpido por el alcalde Edward Young en una reunión;
este hombre había dicho que él acabaría con las reuniones de los Cuáqueros,
o de lo contrario, sus huesos debían yacer en el barro.
Tras esta resolución, en la mañana de un Primer-día del mes llamado Octubre,
entró a una de las reuniones de los Cuáqueros, en la casa donde estaba H. Smith;
y varias personas después de ser rudamente lastimadas,
fueron llevadas a prisión. Por la tarde se celebró una reunión en la calle,
y algunos del pueblo llamado Cuáqueros (por orden
del mencionado alcalde) fueron puestos en cepos,
y otros, de los que el mencionado H. Smith era uno,
fueron encerrados en un oscuro calabozo.
Y aunque el alcalde había dicho entonces que esa era una "`asamblea
ilegal,`" y que si ellos se reunían en las casas él no los molestaría;
aun así, el siguiente Primer-día,
al ver que uno iba a una reunión que estaba citada en una casa, lo puso en prisión.

Humphrey Smith y sus amigos tenían unos lechos y ropa de cama que les habían mandado,
pero el alcalde hizo que se los quitaran,
y después cuando algunas personas les llevaron algo de paja para acostarse,
el carcelero no lo permitió. Cuando uno llegó y pidió
permiso para sacar los excrementos de ellos,
el alcalde lo negó, y ordenó que ese hombre fuera puesto en el cepo.
El lugar donde ellos estaban no tenía 3,5 metros cuadrados,
y el hueco para tomar aire era de unos 10 centímetros de ancho, de modo que,
incluso durante el día tenían que encender una candela para alumbrarse,
cuando podían obtener una.
Fueron mantenidos ahí más de catorce semanas, con sus excrementos en la misma habitación;
esto dio como resultado que uno de ellos se enfermara por el hedor, y muy a su pesar,
el carcelero dijo que si ellos hubieran sido ladrones o asesinos,
él habría podido concederles más libertad,
pero que no se atrevía a hacerlo por causa del alcalde.
James Wall, uno de los prisioneros, era un ciudadano del mismo pueblo y comerciante,
y aun así el alcalde le prohibió a la esposa de James tener un puesto en el mercado,
el que había tenido por muchos años. Ella fue a verlo por esto,
y él empezó a ridiculizarla diciendo: "`He escuchado que tu esposo te lastima.`"
Entonces ella respondió: "`Mi esposo nunca me ha lastimado;
en cuanto a la profesión religiosa que él tiene ahora, por un tiempo no pude aceptarla,
pero viendo ahora cuán perseguida es, me hace reconocerla,
porque el camino de Dios siempre ha sido perseguido.`"
Al oírla hablar así,
el alcalde le dijo que no podía tener un puesto en el mercado ni por cinco libras.

Cerca de un mes después,
Margaret Newby y Elizabeth Courton llegaron a ese pueblo
y tuvieron una reunión en la casa de Edward Pitwayes;
pero al ir a visitar a los prisiones por la tarde,
el propio alcalde las trató violentamente,
e hizo que fueran puestas en los cepos con sus piernas
extendidas a una yarda una de la otra.
Él no permitió que tuvieran un bloque donde sentarse, aunque ellas lo había solicitado.
No obstante, queriendo ser visto como alguien que tenía algo de recato,
le pidió al alguacil que buscara un bloque y lo pusiera entre sus piernas,
mientras pronunciaba algunas expresiones indecentes.
Se les mantuvo en esa postura por espacio de quince horas, y luego,
durante la noche helada fueron sacadas del pueblo,
sin permitirles ir a ningún lugar a refrescarse.
En cuanto a Humphrey Smith y los que estaban con él,
fueron dejados en prisión un buen rato más.

Alexander Parker estaba este año en Radnor, en Gales,
y dando testimonio allí contra el sacerdote Vavasor Powel,
también predicaba la doctrina de la Verdad según se presentaba la ocasión. Creo
que fue por este tiempo que Ambrose Rigge y Thomas Robinson llegaron a Exeter.
De ahí se fueron a Bristol y después a Basingstoke, en Hampshire.
Aquí, después de mucha dificultad, lograron fijar una reunión,
pero antes de que se reunieran todas las personas,
el sacerdote principal junto con los magistrados,
llegaron e hicieron que se los llevaran y luego les presentaron el juramento de repudio.
Pero al negarse a jurar por un asunto de consciencia, fueron enviados a prisión,
donde el carcelero clavó tablas sobre la ventana y los privó de luz,
ni tampoco les permitía tener una candela en la noche.
Ahí los mantuvieron cerca de la cuarta parte de un año,
sin nada más que un poco de paja para acostarse.
Pero su sufrimiento tuvo tal efecto,
que algunos de los habitantes al ver estos tratos irracionales,
empezaron a investigar la doctrina sostenida por los sufrientes,
y se convencieron de la verdad de la misma.
Cuando finalmente fueron liberados,
Robinson fue a Portsmouth donde predicó el arrepentimiento.
Un tiempo después llegó Ambrose Rigge,
y en cierto sentido cosechó lo que Robinson había sembrado,
aunque no pasó mucho tiempo antes de que lo sacaran del pueblo.
Pero al regresar en el lapso de un corto tiempo,
encontró oportunidad de tener una reunión ahí,
y por su predicación algunos se convencieron de la verdad y la abrazaron.

De ahí se fue a la isla de Wight,
donde otros también recibieron la doctrina que él sostenía.
Después de una corta estadía regresó a Sussex,
donde realizó un gran servicio.
Viajando por todo el condado, llegó a Weymouth y Melcombe-Regis,
donde al hablar contra el sacerdote en la '`casa del campanario,`'
fue capturado y encerrado en un calabozo repugnante,
en el que no había nada para acostarse salvo algo de paja sucia y una piedra para sentarse.
Tampoco había letrina, pero en el suelo había una pila de excremento,
donde era forzado a aliviar sus necesidades.
Sin embargo,
había una abertura en la parte superior del calabozo y por
ella podía ver a las personas caminar por las calles,
y desde su cueva subterránea,
aprovechó la oportunidad para predicarles a los que pasaban, con tal poder y eficacia,
que su doctrina entraba en los corazones de los oyentes y ahí se clavaba.
Esta forma de predicar se volvió común en ese tiempo en Inglaterra, y yo mismo,
en mi años de juventud, he sido testigo presencial de eso.
He oído a los prisioneros levantar sus voces, de modo tal,
que podían ser oídos fácilmente en las calles,
lo que hacía que las personas que pasaban se quedaran quietas y
prestaran atención a lo que era dicho por estos celosos predicadores.
Y aunque a estos hombres y mujeres a menudo se les impedía tener reuniones,
era imposible detener la fuente de la que fluían sus palabras.
Así sucedió también con Ambrose Rigge,
quien puesto en libertad después de un encarcelamiento de once semanas,
viajó de arriba a abajo otra vez.
Sin embargo, en muchos de los lugares adonde llegaba, una prisión era su porción,
a veces incluso, cuando no se le podía acusar de nada,
salvo de que había "`salido de su lugar de residencia;`"
pues el Parlamento había hecho una ley que decía,
que todos aquellos que salían de su lugar de residencia
y no podían dar un "`motivo satisfactorio`" de sus asuntos,
debían ser tomados como vagabundos.
Bajo este pretexto,
muchos de los que viajaban a los mercados con sus mercancías eran capturados en el camino,
porque si parecían que eran Cuáqueros (lo cual se
podía ver fácilmente si no se quitaban el sombrero),
entonces no hacía falta un pretexto para encerrarlos en prisión.

Ambrose Rigge continuó viajando y también llegó a
visitar a sus amigos en prisión en Southampton.
Esto encolerizó tanto al alcalde, Peter Seal,
que sin ningún interrogatorio hizo
que fuera atado al poste de los azotes en el mercado,
donde fue severamente azotado por el verdugo;
luego fue puesto dentro de una carreta y sacado del pueblo en un clima nevado y helado.
El alcalde también lo amenazó diciéndole que si alguna vez regresaba,
sería azotado de nuevo y le quemaría una "`V`" en el hombro, indicando _vagabundo._
A pesar de eso, fue movido por el Señor a regresar,
y el alcalde estaba muy deseoso de que se ejecutara la amenaza sobre él,
pero los otros magistrados no lo consintieron;
no mucho después el alcalde murió de una diarrea sanguinolenta.^
footnote:[Es decir, disentería.]
Este relato me llevó un poco más allá del curso del tiempo,
pero ahora dejo a Ambrose Rigge por un rato, con la intención de mencionarlo después.

Este año William Caton fue de nuevo a Escocia, y después de regresar, viajó a Bristol,
de ahí a Plymouth y continuó a Londres.
De ahí viajó nuevamente a Holanda, donde William Ames y John Stubbs habían estado,
y encontró que entre los ingleses en Amsterdam algunos
habían recibido la doctrina que ellos predicaron,
aunque después se volvieron de ella.
Luego Caton arribó a Dort y de ahí viajó a Rotterdam,
donde por falta de un intérprete que entendiera inglés,
tuvo que hacer uso del latín. Pero le dolió enormemente
encontrarse ahí con algunos espíritus rebeldes,
quienes, habiendo sido convencidos en alguna medida por William Ames, corrían,
bajo la denominación de los Cuáqueros, en extremos tanto de palabra como por escrito.
Conozco a algunas de estas personas,
y también he visto algunos de los libros que han publicado,
en los que bajo la pretensión de "`sencillez,`" no se encuentra una letra mayúscula,
ni siquiera en los nombres propios, o en los nombres de los mismos autores.
Y como corrieron hacia otras extravagancias,
no es de extrañar que los magistrados los encerraran en Bedlam.^
footnote:[Un asilo para enfermos mentales.]

El cabecilla de estas personas era un tal Isaac Furnier,
quien anteriormente (según lo contado por mi tío,
que lo había visto) había vivido como otro Diógenes.^
footnote:[Diógenes (450-323 A.C.) fue el filósofo antisocial y ascético que vivía
en un barril y rechazaba todas las normas de comportamiento civilizado.]
Y luego, al entrar en los llamados Cuáqueros,
hizo un elemento de santidad usar el lenguaje más franco que se le ocurriera,
sin importar cuán absurdo e irregular fuera.
En resumen, él se comportaba de tal forma,
que los Cuáqueros ortodoxos rechazaron su sociedad.
Fue él, según tengo entendido, el autor del ridículo dicho:
"`Mi espíritu testifica;`" el cual,
aunque no era aprobado ni usado por los verdaderos Cuáqueros,
ha sido tan esparcido entre la gente en los Países Bajos,
que constantemente se ha afirmado que los Cuáqueros solían
decirlo por cualquier cosa que pretendían hacer.

El Dr. Galenus Abrahams una vez me contó, que este hombre,
al llegar a su puerta y encontrar su nombre escrito
en el poste de la puerta (como es habitual en Holanda),
tomó su cuchillo y raspó las letras "`Dr.`" que significan doctor.
En esa ocasión el doctor le preguntó por qué había hecho eso, y su respuesta fue:
"`Porque el Espíritu así me lo testificó.`" Y cuando se le preguntó,
si él habría apuñalado al doctor con el cuchillo,
en el caso de que ese espíritu lo hubiera movido a hacerlo,
respondió (como el doctor me lo afirmó): "`Sí.`" Pero sea o no cierta esa anécdota,
lo cierto es, que este Isaac Furnier era un hombre apasionado e inestable,
a quien los verdaderos Cuáqueros no reconocían como uno de ellos,
aunque él había traducido muchos de sus libros del inglés al holandés,
y había predicado entre ellos.
Al final los dejó,
y al convertirse en Católico Romano cayó en una vida depravada y libertina.

Ahora regreso a William Caton,
que al llegar a Amsterdam no encontró mucha más satisfacción ahí que en Rotterdam,
pues varios profesantes altamente vanidosos,
que parecían aprobar la doctrina predicada por los Cuáqueros,
estaban más dispuestos a encargarse ellos mismos de enseñar,
que de recibir instrucción de otros.
Por tanto, W. Caton no se quedó mucho tiempo en Amsterdam, sino que regresó a Rotterdam,
de ahí se fue a Zealand y llegó a Middleburgh.
Él estaba acompañado por cierto joven,
quien fue a algunos de los lugares de reunión en esa ciudad y fue detenido.
Caton, entendiendo que su amigo había sido encerrado, fue a visitarlo,
y cuando los oficiales se dieron cuenta de que él era el acompañante,
lo encarcelaron también. Después de haber estado en prisión algunos días,
y estando débiles de cuerpo, se ordenó que los enviaran a Inglaterra; por tanto,
fueron llevados en una carreta a la orilla del mar,
conducidos por una guardia de soldados para protegerlos de la multitud ruda,
y subidos a bordo de un barco de guerra.
Aquí Caton sufrió grandes dificultades, pues los marineros eran tan hostiles,
que no le permitían usar un trozo de tela de vela para cubrirse,
sino que lo obligaban a acostarse sobre las tablas desnudas en un clima muy frío y tormentoso.
Pero a pesar de este maltrato,
sintió que su fuerza se incrementaba y experimentó las misericordias de Dios.
Llegó a Londres en Noviembre, donde fue recibido amablemente por los hermanos,
y después de una estadía ahí, se fue a Hampshire, Surry, Sussex y Kent.

No mucho antes de esto, G. Fox había llegado a Exeter,
donde James Nayler estaba en prisión, y le habló a modo de reprimenda.
Nayler menospreció la corrección de G. Fox, aunque ofreció besarlo,
pero George no quiso permitirlo, diciendo,
que dado que Nayler se había vuelto contra el poder de Dios,
no podía recibir su muestra de bondad.
Las cartas que los magistrados encontraron en el bolsillo de Nayler en Bristol,
parecen indicar que los Cuáqueros habían encontrado
faltas en él y que lo habían reprendido por su altivez,
antes de que se lanzara a ese acto extravagante que tanto ruido causó en el mundo,
y que ahora se ha mezclado con muchas mentiras y giros falsos.
Por tanto, he creído que vale la pena inquirir cuidadosamente en esto,
para dar un relato verdadero de los hechos.

James Nayler nació alrededor de 1616, en la parroquia de Ardesley,
cerca de Wakefield en Yorkshire, y sus padres eran personas honestas.^
footnote:[Su padre era un granjero de buena reputación,
que tenía una finca decente (según las normas del condado
donde vivía) en la cual trabajaba diligentemente.
J+++.+++ Nayler tenía una buena educación en inglés y escribía bien.
Cuando tenía unos veintidós años se casó y luego se trasladó a la parroquia de Wakefield,
donde continuó hasta que estallaron las guerras en 1641.
Entonces entró en el ejército y fue soldado durante ocho o nueve años,
primero bajo el mando de lord Fairfax,
y más tarde fue intendente bajo el mando del general de división Lambert,
hasta que estando en Escocia,
quedó incapacitado por una enfermedad y regresó a su casa alrededor de 1649.
--Reporte de J. Whiting.]
Nayler sirvió en el ejército del Parlamento,
siendo intendente en las tropas del general de división Lambert en Escocia.
En ese entonces era miembro de los Independientes, y después, en el año 1651,
entró en la comunión de los llamados Cuáqueros.^
footnote:[Él y Thomas Goodair fueron convencidos por George Fox, cerca de Wakefield,
alrededor del año 1651; y casi al mismo tiempo, también Richard Farnsworth, Thomas Aldam,
William Dewsbury y su esposa.
A principios del año siguiente, cuando estaba en el campo arando,
meditando en las cosas de Dios,
oyó una voz que le pedía que saliera de su parentela y de la casa de su padre,
y se le dio la promesa de que el Señor estaría con él;
por lo que se regocijó mucho de haber escuchado la voz de Dios,
a quien había confesado desde niño y se había esforzado por servir.
Cuando regresó a la casa hizo los preparativos para irse,
pero luego por no ser obediente, la ira de Dios vino sobre él,
de modo que muchos estaban asombrados y se pensó que iba morir.
Pero luego se dispuso, y al salir con un amigo, sin pensar entonces en un viaje largo,
se le ordenó ir al Oeste, sin saber qué iba a hacer allí,
pero cuando llegó se le dio lo que debía declarar.
Así continuó, sin saber un día lo que tenía que hacer al siguiente;
y la promesa de Dios (que Él estaría con él),
la veía cumplida cada día.--__Colección de escritos de J. N.__]
Era un hombre de excelentes habilidades naturales,
y al principio se desenvolvió bien entre sus amigos, tanto en palabra como por escrito,
de modo que muchos llegaron a recibir la Verdad por su ministerio.

James Nayler llegó a Londres a finales de 1654 o a principios de 1655,
y encontró establecida una reunión de Amigos en la ciudad,
por la obra de Edward Burrough y Francis Howgill.
Ahí predicó en una forma tan notable, que muchos admirando su gran don,
empezaron a estimarlo por encima de sus hermanos;
esta excesiva estima no le trajo ningún bien a él
y dio lugar a algo de discordia en la sociedad.
La tensión se elevó a tal punto, que algunas mujeres atrevidas y sin consideración,
de quienes Martha Simmons era la principal,
tenían la osadía de disputar abiertamente con Francis
Howgill y Edward Burrough mientras predicaban,
y así perturbaban las reuniones,^
footnote:[Podemos suponer que la práctica de estas mujeres era
en cierto modo como la que le dio ocasión al apóstol Pablo de decir:
'`Callen vuestras mujeres en las iglesias,
porque no les está permitido hablar.`' 1 Corintios 14:34.
Esta prohibición de hablar,
debe referirse al discurso voluntario, en forma de razonamiento o discusión,
y no a aquellos momentos en los que se tenía un impulso o carga inmediata de profetizar,
pues el apóstol, en la misma epístola,
ha definido la profecía como '`hablar a los hombres para edificación,
exhortación y consolación.`' 1 Corintios 14:3. Y en el capítulo 11 también
hizo mención expresa de la oración y la profecía de las mujeres,
junto con los hombres.]
con lo cual, ellos que eran predicadores verdaderamente excelentes,
no dudaron (según su deber) en reprender esta indiscreción.
Pero estas mujeres se disgustaron tanto,
que Martha y otra mujer fueron y se quejaron con James Nayler,
a fin de encolerizarlo contra F. Howgill y E. Burrough, pero esto no sucedió,
porque él se mostró temeroso de juzgar a sus hermanos como ellas lo deseaban.
En ese momento Martha se dejó llevar por una emoción, una especie de gemido o llanto,
y exclamando amargamente con una voz chillona y afligida decía: "`¡Esperaba juicio,
y he aquí vileza; justicia, y he aquí clamor!`"^
footnote:[Isaías 5:7]
Así lloró, en voz alta, y en una forma tan apasionada y triste,
que dicho lamento entró y traspasó a J. Nayler, y lo hundió en tanto dolor y tristeza,
que quedó muy abatido y desconsolado en espíritu.
Entonces el temor y la duda se apoderaron de él, de modo que su entendimiento se nubló,
se confundió y se perdió en su juicio,
y luego se alejó de sus mejores amigos porque no aprobaban su conducta;
pues él le había empezado a dar oído a alabanzas lisonjeras de algunas personas caprichosas,
a las cuales debió haber aborrecido y reprendido.
Pero su dolorosa caída debe permanecer como una advertencia,
incluso para los que han sido dotados con grandes dones,
a fin de que no se atrevan a ser exaltados, no sea que caigan también;
más bien deben esforzarse en continuar en verdadera humildad,
en lo único que un Cristiano puede ser mantenido a salvo.

Hannah Stranger,
a quien conozco muy bien y tengo razones para creer que es una mujer de grandes imaginaciones,
en ese tiempo le escribió varias cartas muy extravagantes,
llamándolo el eterno Hijo de Justicia, Príncipe de Paz, el unigénito Hijo de Dios,
el más hermoso de diez mil, etc.
En las cartas de Jane Woodcock, John Stranger y otros,
había expresiones de similares extravagancias, y las mencionadas Hannah Stranger,
Martha Simmos y Dorcas Erbury llegaron a tal nivel de locura,
que en la prisión de Exeter se inclinaron delante de Nayler y besaron sus pies;
pero en cuanto a lo que ha sido divulgado con respecto a un supuesto pecado de fornicación,
no pude encontrar nada (aunque fui muy inquisitivo en el
asunto) que lo incriminara de eso en lo más mínimo.^
footnote:[En una declaración pública de retractación,
impresa después de que fue liberado de prisión y se reconcilió con la Sociedad de Amigos,
James Nayler escribió las siguientes palabras en referencia a su acusación:
"`Está en mi corazón confesar ante Dios y ante los hombres,
mi insensatez y ofensa de aquel tiempo.
Aunque también,
se habían levantado muchas cosas contra mí en ese día (para
quitarme la vida y traer escándalo sobre la Verdad),
de las que no soy culpable en absoluto;
tales como la acusación de que cometí adulterio con algunas de
las mujeres que llegaron con nosotros desde la prisión de Exeter,
y con las que estaban conmigo en Bristol la noche anterior a mi sufrimiento
ahí. Con respecto a estas dos acusaciones estoy limpio delante de Dios,
quien me guardó en ese día, tanto en pensamiento como en obra,
en lo que se refiere a todas las mujeres, como un niño; Dios es mi testigo.
Esto lo menciono en particular (al oír de algunos que no
dejan de criticar la Verdad de Dios y al pueblo con ella),
para que la boca del enemigo sea cerrada de hablar mal,
aunque esto no toque mi consciencia.`"
Colección de Escritos de James Nayler, pág. 54]
Aun así, él ya se había dejado llevar mucho y se había vuelto aún más desmedido,
pues después de ser liberado de esa prisión,
cabalgando hacia Bristol a principios de Noviembre,
acompañado por las mencionadas mujeres y varias otras personas,
y pasando por los suburbios de Bristol,
un tal Thomas Woodcock caminaba con la cabeza descubierta delante de él^
footnote:[En ese momento,
quitarse el sombrero (o ir "`con la cabeza descubierta`") era una señal de honor y respeto;
una que usaban los Cuáqueros sólo en sus solemnes acercamientos al Señor en oración.]
y una de las mujeres conducía su caballo, y Dorcas,
Martha y Hannah extendían sus bufandas y pañuelos delante de él mientras el grupo cantaba:
"`Santo, santo, santo es el Señor Dios de los ejércitos; hosanna en las alturas.
Santo, santo, santo es el Señor Dios de Israel.`"
Así cantaban estos locos mientras caminaban por el barro y la tierra,
y entraron a Bristol,
donde fueron interrogados por los magistrados y encerrados en prisión;
y no mucho después Nayler fue llevado a Londres para ser interrogado por el Parlamento.
Se puede saber qué sucedió ahí por la impresión que se hizo del juicio,
la cual el Parlamento se complació en publicar.^
footnote:[Pero lo excesivo de la sentencia que los miembros del Parlamento dictaron,
junto con otras circunstancias,
proveen suficiente razón para suponer que el relato de lo sucedido no fue tomado imparcialmente,
y fue publicado para justificar su crueldad.
Con respecto a esta publicación, John Whiting escribió:
"`Algunas de sus respuestas fueron suficientemente inocentes, otras no muy claras,
y otras fueron agravadas por sus adversarios; él negó algunas de ellas,
otras las admitió. Ellos informaron lo peor, y en algunas cosas,
más de lo que era cierto, aumentando o disminuyendo según se inclinaban.
Faltaba mucho de lo que él había hablado con el comité,
quienes estaban arrancándole palabras y pervirtiéndolas de la manera que podían,
esforzándose por sacarle palabras para atraparlo y quitarle la vida.
Para mostrar la confusión en que se encontraban cuando él estaba frente a ellos,
le mandaron que se arrodillara y se quitara el sombrero ante ellos,
aunque una parte de la acusación contra él era que
algunos se habían arrodillado ante él.`"]
Creo que James Nayler tenía su entendimiento nublado
durante todo el curso de estos eventos.
Pero a pesar de lo grave de su caída, le plació a Dios en Su infinita misericordia,
levantarlo de nuevo y llevarlo a un arrepentimiento tan sincero,
que él (como podemos ver en lo que sigue) aborreció no sólo todo este asunto,
sino que también manifestó su gran pesar con desgarradoras expresiones,
las cuales fueron publicadas, como se mostrará en su debido lugar.

Lo que se ha dicho de los extraños sucesos en la prisión de Exeter,
y de su cabalgata a Bristol, no fue negado por él ni por el resto del grupo,
cuando fueron interrogados por el comité del Parlamento,
quienes dieron su reporte el 5 de Diciembre, y que la casa aprobó al día siguiente.
Este asunto,
que había sido tratado tanto en las mañanas como en las tardes
(con mucha oposición por parte de muchos de los miembros del Parlamento
que no aprobaban la severidad usada contra él),
se planteó por duodécima vez el 16 de diciembre,--que
hizo que un ingenioso autor dijera después,
que para muchos era asombroso que un asunto tonto como este,
mantuviera a muchos hombres sabios trabajando durante tanto tiempo.
Pero el día 17, después de un largo debate, llegaron a esta resolución:

[.embedded-content-document.legal]
--

"`James Nayler, el próximos Jueves será puesto en el cepo, con su cabeza en el cepo,
en el jardín del palacio de Westminster, durante un lapso de dos horas,
y luego será azotado por el verdugo mientras lo transportan por las calles de Londres,
de Westminster a Old Exchange.
Allí también será puesto en el cepo, con su cabeza en el cepo, por un lapso de dos horas,
entre las once y la una del Sábado siguiente,
llevando en cada lugar un papel con la descripción de sus crímenes.
Luego, en Old Exchange,
se le perforará la lengua con un hierro candente y se le estigmatizará su frente con
la letra B. Después será enviado a Bristol y transportado en y a través de dicha ciudad,
en el lomo de un caballo con su rostro viendo hacia atrás,
y allí también será públicamente azotado el siguiente día de mercado.
De ahí será enviado a la prisión en Bridewell, Londres,
no se le permitirá relacionarse con ninguna persona,
y será sometido a trabajos forzados hasta que sea liberado por el Parlamento.
Durante este tiempo se le prohibirá usar pluma, tinta y papel,
y no tendrá asistencia sino la que él gane con su trabajo diario.`"

--

Pasó mucho tiempo antes de que ellos pudieran acordar la sentencia,
porque aunque suponían que se había cometido blasfemia,
su lengua no parecía propiamente culpable de ello,
dado que nunca se probó que él hubiera dicho palabras blasfemas.^
footnote:["`En las sesiones de la corte en Lancaster,
el sacerdote consiguió que algunos juraran blasfemia contra
George Fox (la cual era la acusación común en aquellos días),
pero fue absuelto,
por lo que los sacerdotes se enfurecieron y en seguida enviaron
una petición al consejo de estado contra George Fox y James Nayler,
quienes respondieron lo mismo en un libro llamado [.book-title]#Saul`'s Errand to Damascus.#
Después de esto, J. Nayler fue perseguido en varios lugares, fue golpeado,
apedreado y cruelmente tratado por los sacerdotes y sus rudos seguidores,
y estuvo en peligro de vida.
Después, por instigación del sacerdote,
él y Francis Howgill fueron encerrados en la cárcel
de Appleby y juzgados por una acusación de blasfemia,
al decir que '`Cristo estaba en él,`' según Colosenses 1:27, '`Cristo en vosotros,
la esperanza de gloria.`' En otro momento,
fue nuevamente acusado de blasfemia por afirmar en un libro que '`la justificación
es por el don de la Justicia de Dios,`' lo que él probó con Romanos 5,
y así detuvo sus bocas y descargó su consciencia.
Por esto podemos ver lo que esta generación, que era justa a sus propios ojos,
llamaba __blasfemia.__`"--Relato de John Whiting.]
En realidad, muchos pensaban que era una sentencia muy severa,
para ser ejecutada sobre alguien cuyo crimen parecía más proceder de un
entendimiento nublado que de una deliberada intención de maldad.

Ahora bien, aunque varias personas de diferentes persuasiones religiosas,
movidas por la compasión hacia Nayler (por ser un hombre
que se había dejado llevar por tontas imaginaciones),
habían hecho peticiones al Parlamento en su favor,
se resolvió no leerlas hasta que la sentencia contra él fuera pronunciada.

Vivía entonces en Londres un tal Robert Rich, comerciante (un hombre muy temerario),
quien le escribió una carta al Parlamento en la que intentaba demostrar qué era blasfemia.
El 15 de Diciembre se entregaron varias copias a miembros específicos,
y en la que se le dio al moderador, estas palabras estaban escritas en la parte inferior:
"`Si los que se sientan en los escaños del Parlamento me dieran libertad de hablar,
me presento a su puerta listo a demostrar a partir de las Escrituras de Verdad,
que nada de lo que ha dicho o hecho James Nayler es blasfemia,`" etc.

Después de que concluyó el juicio,
el Parlamento resolvió autorizar al presidente de la Cámara para
que emitiera sus órdenes a los alguaciles de Londres y Middlesex,
al alguacil de Bristol y al gobernador de Bridewell,
a fin de que se ejecutara dicho juicio.
Pero algunos se estaban cuestionado si esta autorización era suficiente,
a menos que el protector concordara con el asunto; pero Cromwell no quiso entrometerse.
Tras acordarse el asunto, J. Nayler fue llevado al estrado,
y cuando el presidente de la Cámara, sir Thomas Widdrington,
estaba a punto de pronunciar la sentencia antes mencionada,
Nayler dijo que él no conocía su delito.
A lo cual el presidente respondió: "`Conocerás tu delito por tu castigo.`"
Después de que la sentencia fue pronunciada,
aunque J. Nayler la soportó con gran paciencia,
en un momento pareció que iba a decir algo, pero le fue negada la libertad.
Sin embargo, se le escuchó decir con una mente serena:
"`Le ruego a Dios que no les tome en cuenta esto.`"

El 18 de Diciembre, J. Nayler sufrió parte de la sentencia,
y después de haber permanecido por dos horas completas con la cabeza en el cepo,
fue desnudado y azotado detrás de una carreta desde
el jardín del palacio hasta Old Exchange,
recibiendo trescientos diez azotes.
El verdugo le habría dado uno más,
pero su pie resbaló y el golpe cayó sobre su propia mano,
lo cual le provocó un fuerte dolor.
Todo esto Nayler lo soportó con tanta paciencia y tranquilidad,
que asombró a muchos de los espectadores,
a pesar de que su cuerpo estaba en una condición muy lamentable.
También tenía muy heridos sus pies por los pisotones de los caballos,
en los que se podían ver las marcas de sus cascos.
Rebecca Travers, una persona sobria y respetable, y quien lavó sus heridas,
dijo en un certificado que fue presentado ante el Parlamento y luego impreso:
"`Desde sus hombros hasta cerca de su cintura,
no había el espacio de una uña libre de azotes y sangre.
Su brazo derecho estaba gravemente herido, y sus manos muy lastimadas por cortes,
de modo que sangraban y estaban hinchadas.
A primera vista,
la sangre y las heridas en su espalda apenas se veían
debido a la gran cantidad de tierra que las cubrían,
hasta que fue lavado.`"
De hecho, su castigo fue tan severo,
que algunos juzgaban que su sentencia habría sido
más benigna si lo hubieran ejecutado en el momento.
Parece que, efectivamente,
había un grupo que al no poder prevalecer lo suficiente
en el Parlamento para sentenciarlo a muerte,
se esforzó al máximo de su fuerza para hundirlo bajo el peso de su castigo.
El 20 de Diciembre era el día designado para ejecutar la otra parte de la sentencia,
es decir, la perforación de su lengua y estigmatización de su frente,
pero debido a que la crueldad con que había sido
azotado lo había llevado a una condición muy frágil,
muchas personas importantes, movidas por la compasión,
le presentaron al Parlamento una solicitud en su favor,
y entonces le aplazaron su castigo una semana.

Durante ese intervalo, varias personas le presentaron otra solicitud al Parlamento,
en la que estaban estas palabras:

[.embedded-content-document.legal]
--

"`La moderación y clemencia que ustedes mostraron
en el aplazamiento del castigo de James Nayler,
en consideración a la condición de su cuerpo,
ha refrescado los corazones de muchos miles en estas ciudades,
que no han tenido ninguna participación en sus actos.
Por tanto, humildemente les pedimos su perdón,
quienes nos sentimos constreñidos a comparecer delante de
ustedes con esta petición (sin atrevernos a hacer otra cosa),
solicitándoles que remitan la parte restante de su castigo contra J. Nayler,
dejándolo en manos del Señor y en las soluciones del nuevo pacto que Él ha santificado.
Estamos persuadidos de que encontrarán que un rumbo
de amor y tolerancia será más efectivo para rescatarlo,
y dejará un sello de su amor y ternura sobre nuestros espíritus.`"

--

Esta petición presentada en la barra de la casa por
unas cien personas en nombre de la totalidad,
fue respectivamente leída y debatida por ellos;
pero los solicitantes pensaron que era probable que
su petición no produjera el efecto deseado,
así que se consideraron obligados por el deber y la consciencia,
a dirigirse al protector para que él remitiera la parte restante de la sentencia, quien,
en seguida, envió una carta al Parlamento, lo que provocó cierto debate en la casa.
Sin embargo,
viendo que el día de la ejecución de la parte restante de la sentencia se acercaba,
los solicitantes se dirigieron por segunda vez al protector.
De hecho,
fue muy notable que tantos habitantes que no pertenecían
a la sociedad de los llamados Cuáqueros,
se mostraran tan interesados en el asunto.
Para mí, esto parece haber salido de la mera compasión hacia la persona de James Nayler,
a quien ellos consideraban como alguien que había caído en un error por descuido,
en lugar de ser culpable de blasfemia deliberada;
porque entonces no habría merecido tanta compasión.

Pero a pesar de todas estas humildes peticiones,
los predicadores públicos (parece) se opusieron tanto a Cromwell,
que no pudo resolver ponerle un alto a la ejecución prevista.
Cinco de esos ministros, cuyos nombres me parecen que son Carly, Manton, Nye,
Griffith y Reynolds,
el 24 de Diciembre fueron donde Nayler por orden del Parlamento (según se dijo),
para hablar con él sobre las cosas por las que estaba detenido,
y no permitieron que ningún amigo o cualquier otra persona
estuviera presente en la habitación. Cierta persona imparcial
o neutral deseaba fervientemente que esto fuera permitido,
pero le fue negado.
Sin embargo, este hombre, que llegó a la prisión después de la conferencia,
le preguntó a Nayler cuál había sido el asunto de la reunión.
Nayler le respondió que él les había dicho a los ministros,
que veía que ellos tenían la intención de hacerlo
sufrir (aunque inocente) como si fuera un malhechor,
y que por eso,
le habían negado la presencia a cualquiera que pudiera
ser un juez imparcial entre ellos y él;
y por esa razón, no iba a decir nada,
a menos que lo que pasara entre ellos fueran anotado y le dieran una copia para guardarla,
o dejarla con el carcelero, después de que ellos la hubieran firmado.
Que ellos habían consentido a eso, y luego le habían hecho varias preguntas,
cuyas respuestas las habían puesto por escrito.
Que le habían preguntado si él lamentaba las blasfemias de las que era acusado,
y si se retractaba y renunciaba a las mismas.
A lo cual él había respondido: "`¿Cuáles blasfemias?
Nómbrenlas.`"
Pero como ellos no habían sido capaces de citar una en particular, él había continuado:
"`¿Ustedes quieren que yo me retracte y renuncie,
y no saben de qué?`" Después le habían preguntado si él creía que había un Jesucristo,
y había respondido que él creía que lo había,
y que Jesús había hecho Su morada en su corazón y espíritu,
y que por el testimonio de Él sufría en ese momento.
Y en seguida uno de los predicadores había dicho:
"`Yo creo en un Jesús que nunca ha estado en el corazón
de ningún hombre,`" pero él había respondido,
que no conocía a ese Cristo,
porque el Cristo del que él testificaba llenaba el cielo y la tierra,
y habitaba en los corazones de los creyentes.

Entonces le habían preguntado la razón por la que les había
permitido a esas mujeres que le rindieran culto y lo adoraran.
A lo que él había respondido: "`Rechazo toda reverencia ante la criatura,
pero si ellas veían el poder de Cristo, dondequiera que estuviera,
y se inclinaban ante él, ¿quién soy yo para resistir o contradecirlo.`"^
footnote:["`Lo más que encuentro en su interrogatorio, ya sea en Bristol o en Londres,
ante el comité del Parlamento, según se publicó en el informe de ellos,
es que James Nayler había reconocido que Cristo estaba en él, pero nunca que era Cristo;
y que él había tomado el honor que le habían dado, no para él,
sino para Cristo en él--lo cual, sin embargo,
era más de lo que ningún hombre debía recibir, porque cuando el discípulo amado, Juan,
había caído ante los pies del ángel para adorarlo, él (aunque un ángel) le había dicho:
'`Mira, no lo hagas; yo soy consiervo tuyo,
y de tus hermanos que tienen el testimonio de Jesús. Adora a Dios.`' Apocalipsis
19:10. Pero el alegato de que J. Nayler había recibido eso para sí mismo,
como criatura, lo negó rotundamente (ver Juicio, pág. 15),
al decir que no podía haber algo más abominable que
tomar del Creador y dárselo a la criatura,
etc.`"
--John Whiting.]
Posteriormente les había preguntado a los ministros:
"`¿Por tanto tiempo han profesado las Escrituras
y ahora tropiezan con lo que ellas exponen?`"
Con lo cual, ellos habían querido que él les diera un ejemplo de las Escrituras,
en el que se veía que tal práctica había sido llevada a cabo.
Y él les respondió: "`¿Qué piensan de la sunamita,
cuando se postró a los pies de Elías y se inclinó delante de él.
Así como también de varios que se mencionan en las Escrituras,
tales como Abigail ante David, y Nabucodonosor ante Daniel?`"
Ante esto ellos se habían detenido un rato y finalmente habían dicho:
"`Eso no fue más que un acto de cortesía o reconocimiento.`"
Él les dijo: "`Así podrían interpretar el acto de esas mujeres,
si sus ojos no fueran malos, al ver que el acto externo es uno y el mismo.`"
Entonces,
al darse cuenta de que ellos estaban buscando arrancarle
palabras que sirvieran a su propósito,
les había dicho: "`¡Cuán pronto han olvidado ustedes las obras de los obispos,
y ahora se encuentran en lo mismo, tratando de atrapar al inocente!`"
Con lo cual,
ellos se habían levantado y con amargura de espíritu habían quemado lo que habían escrito,
y lo habían dejado con algunas expresiones de lamento.
Y que cuando se estaban yendo,
él les había pedido que el Parlamento le enviara por escrito
las preguntas que ellos querían que él respondiera,
y que permitieran que él les devolviera las respuestas por escrito también.

Parece que Nayler, aunque todavía bajo cierta nube,
estaba un poco más claro en su entendimiento que antes,
pero como se encontró con enemigos feroces, no se detuvo la ejecución de su sentencia,
sino que se realizó el 27 de Diciembre.
Robert Rich, aquel hombre temerario de quien ya se ha mencionado algo,
estuvo ese día en la puerta del Parlamento,
desde las ocho de la mañana hasta casi las once,
gritándoles a los hombres del Parlamento cuando pasaban por ahí. A uno,
a quien juzgó inocente le dijo: "`¡El que habita en amor, habita en Dios,
porque Dios es amor!`"
A otro, de quien pensó que estaba siendo movido por la envidia le dijo:
"`El que aborrece a su hermano es un asesino,
y el que odia a su hermano es un homicida.`"
En ese momento, algunos pensaban que Nayler no debía sufrir más castigo,
porque muchas personas honorables se había acercado
al Parlamento y al protector en su nombre,
pero como Rich sabía cómo estaba el caso,
le decía a la gente que un inocente iba a sufrir,
y a algunos hombres del Parlamento les gritó,
que él estaba limpio de la sangre de todos los hombres,
y que deseaba que ellos también lo estuvieran.
Después Rich se fue a Exchange y se subió al cepo,
donde sostuvo a Nayler de la mano mientras le quemaban
la frente y le perforaban la lengua;
estaba muy afectado por los sufrimientos de Nayler, porque luego le lamió las heridas,
buscando (por lo que parece) aliviarle el dolor.
Luego lo tomó de la mano y lo ayudó a bajar del cepo.
Fue muy notable, que aunque ahí había muchos miles de personas, estaban muy calladas,
y muy pocas lo insultaron o le arrojaron algo.
Cuando Nayler estaba siendo quemado, la gente tanto delante como detrás de él,
y a ambos lados, permanecieron unánimes con la cabeza descubierta,
aparentemente movidos por la compasión y buena voluntad hacia él.

No obstante, muchos de sus enemigos estaban gozosos,
al ver que entre los Cuáqueros sólo unos pocos se habían puesto
del lado de Nayler (como Robert Rich y personas similares),
mientras que los Cuáqueros en general hablaban contra él y sus actos;
porque aquellos que esperaban ver la caída de los Amigos,
manifestaban abiertamente que las cosas ya caminaban según lo deseaban,
viendo que los Cuáqueros (según dijeron) estaban divididos entre ellos.
Sin embargo, el tiempo mostró que esta supuesta división pronto llegó a su fin,
y que esos adivinos y agoreros se habían pasado de la raya.
No estoy informado de cómo se ejecutó la sentencia de Nayler en Bristol,^
footnote:["`Él fue enviado a Bristol y azotado en el centro de la calle Thomas,
sobre el puente, en la calle High y en el centro de la calle Broad,
todo lo cual lo soportó con asombrosa paciencia,
según lo relatado por un testigo presencial.
Luego fue enviado por Tower Lane, por el camino de regreso a Newgate,
y de ahí a Bridewell, Londres, de acuerdo a la sentencia.`"--John Whiting.]
pero por una carta de un tal Richard Snead, un anciano de casi ochenta años,
tengo entendido que Nayler había escrito una carta a los magistrados de Bristol,
en la que desaprobaba y condenaba arrepentido su conducta ahí.^
footnote:[Después de que Nayler fue puesto en libertad, fue a Bristol,
donde en una reunión pública hizo confesión de su delito y su anterior caída,
y habló de una manera tan poderosa y tierna que la concurrencia rompió en llanto,
de modo que hubo pocos ojos secos (según lo relatado por algunos presentes en ese momento),
y muchos se inclinaron en sus mentes y se reconciliaron
con él.--De los relatos de John Whiting.]
Después de esto fue llevado a Bridewell, Londres (de acuerdo con su sentencia),
donde continuó encerrado en prisión cerca de dos años,
durante los cuales llegó a un verdadero arrepentimiento de su transgresión;
y tras obtener permiso para usar pluma y tinta,
escribió varios libros y documentos en los que condenaba su error,
los cuales fueron publicados en forma impresa.
Después de su liberación, escribió varios otros,
uno de los cuales a modo de retractación, es como sigue:

[.embedded-content-document.paper]
--

Gloria al Dios Todopoderoso, quien gobierna en los cielos,
y en cuyas manos están todos los reinos de la tierra;
quien levanta y derriba a Su voluntad;
quien tiene maneras de confundir la exaltación de los hombres,
de castigar a Sus hijos y de hacerles saber a los
hombres que son como hierba delante de Él. Ciertamente,
Sus juicios están por encima de los juicios más altos de los hombres,
Su piedad alcanza la miseria más profunda,
y el brazo de Su misericordia se extiende hasta el
fondo para sacar al prisionero del pozo,
y salvar a los que confían en Él,
de la gran destrucción que el hombre vanidoso trae sobre sí mismo por causa de su insensatez.
Pues Él ha liberado mi alma de las tinieblas,
ha abierto camino para mi libertad de la prisión, y me ha redimido de la gran cautividad.
Él divide el mar delante de Él y remueve de Su camino las montañas,
el día que decide liberar al oprimido de la mano
del que es demasiado poderoso para él en la tierra.
¡Qué su nombre sea exaltado para siempre y que toda carne
tema delante de Aquel cuyo aliento es vida para los Suyos,
pero fuego consumidor para el adversario!

En cuanto al Señor Jesucristo,
Su dominio eterno está sobre la tierra y Su reino
por encima de todos los poderes de las tinieblas;
es decir, el Cristo de quien las Escrituras declaran que era, es y ha de venir,
y es la luz del mundo para todas las generaciones.
De Su venida yo testifico con el resto de los hijos de la luz,
aquellos que son engendrados de la Semilla inmortal;
pues Su verdad y virtud brillan hoy en el mundo,
siendo el Salvador de todo aquel que cree en Él para justicia y vida eterna.
Él ha sido la roca de mi salvación,
y Su Espíritu le ha dado tranquilidad y paciencia a mi alma en profunda aflicción,
por amor de Su nombre.
¡Alabado sea Él para siempre!

¡Pero condenada sea para siempre toda falsa adoración con la que
alguien haya idolatrado mi persona en la noche de mi tentación,
cuando el poder de las tinieblas se había levantado sobre mí! ¡Condenado
sea el lanzamiento de sus vestidos en el camino,
sus inclinaciones y cantos, y el resto de sus extravagantes acciones,
que de alguna manera tendieron a deshonrar al Señor,
o a desviar las mentes de la medida de Jesucristo en ellos,
para mirar la carne (que es como hierba),
o atribuirle a algo visible lo que le pertenece a Cristo Jesús! ¡Condeno todo aquello,
por medio de lo cual el nombre puro del Señor ha sido en alguna
forma blasfemado a través de mí en el tiempo de mi tentación,
o por medio de lo cual los espíritus de los que verdaderamente
aman al Señor Jesús en todo el mundo,
de cualquier profesión, han sido afligidos!
Confieso esta ofensa, la cual ha sido aflicción de corazón,
de la que el enemigo de la paz del hombre en Cristo
ha obtenido ventaja en la noche de mi prueba,
para agitar ira y ofensas en la creación de Dios--algo
que la sencillez de mi corazón no pretendía,
el Señor lo sabe;
quien en Su infinito amor hoy me ha dado poder sobre ella para condenarla.

Y con respecto a la carta que me envió John Stranger
a Exeter cuando estaba en prisión y que decía:
"`Tu nombre no será más James Nayler, sino Jesús,`" a mi juicio,
fue escrita desde la imaginación; y un temor me asaltó cuando la vi por primera vez,
así que la guardé en mi bolsillo con la intención de que nadie la viera.
Pero me la encontraron y la divulgaron,
lo que la sencillez de mi corazón nunca aprobó. Así que también niego
haber recibido el nombre de Cristo Jesús en lugar de James Nayler,
o habérmelo adjudicado,
porque ese nombre es para la Semilla prometida a todas las generaciones;
el que tiene al Hijo, tiene el nombre, el cual es Su vida y poder,
la salvación y la unción, en cuyo nombre son bautizados todos los hijos de luz.
Por tanto, confieso delante de los hombres el nombre de Cristo,
cuyo nombre ha sido para mí una torre fuerte de noche
y de día. Este es el nombre de Jesucristo,
que yo confieso, el Hijo y el Cordero, la Semilla prometida,
dondequiera que hable en varón y hembra; pero el que no tiene al Hijo en él,
no tiene la vida, ni puede tenerlo idolatrando mi persona,
o la persona de cualquier carne.

Y todos aquellos espíritus desenfrenados y extravagantes,
que luego se reunieron a mi alrededor en ese tiempo de tinieblas,
y todos sus descabellados actos y malvadas palabras contra el honor de Dios,
Su Espíritu puro y Su pueblo--niego ese espíritu malo, junto con su poder y sus obras.
Y en la medida que por falta de juicio le haya dado ventaja
a ese espíritu malo para que se levante en alguno,
en esa medida acepto la vergüenza de ello,
porque antes tenía poder sobre ese espíritu en juicio y discernimiento,
dondequiera que se levantara.
Esta oscuridad se apoderó de mí por falta de vigilancia y obediencia al ojo puro de Dios,
y por no ocuparme diligentemente de la reprensión de la vida,
la cual condena al espíritu adúltero.
Así tomó ventaja el adversario, quien siempre busca devorar,
y tras ser tomado cautivo de la verdadera luz,
empecé a caminar en la noche en la que nadie puede trabajar,
como un ave errante apta para presa.
De seguro que, si el Señor de todas mis misericordias no me hubiera rescatado,
yo habría perecido; porque era como un hombre destinado a la muerte y destrucción,
y no había nadie que pudiera liberarme.
Todo esto lo confieso,
para que Dios sea justificado en Su juicio y magnificado en Sus infinitas misericordias,
pues no abandonó a Su cautivo en la noche,
aun cuando Su Espíritu era diariamente provocado y contristado; y en su lugar,
me ha liberado para dar gloria a Su nombre para siempre.

Está en mi corazón confesar ante Dios y ante los hombres,
mi insensatez y ofensa de aquel tiempo.
Aunque también,
se habían levantado muchas cosas contra mí en ese día (para
quitarme la vida y traer escándalo sobre la Verdad),
de las que no soy culpable en absoluto;
tales como la acusación de que cometí adulterio con algunas de
las mujeres que llegaron con nosotros desde la prisión de Exeter,
y con las que estaban conmigo en Bristol la noche anterior a mi sufrimiento
ahí. Con respecto a estas dos acusaciones estoy limpio delante de Dios,
quien me guardó en ese día, tanto en pensamiento como en obra,
en lo que se refiere a todas las mujeres, como un niño; Dios es mi testigo.
Esto lo menciono en particular (al oír de algunos que no
dejan de criticar la Verdad de Dios y al pueblo con ella),
para que la boca del enemigo sea cerrada de hablar mal,
aunque esto no toque mi consciencia.

Con respecto al informe de que yo levanté a Dorcas Erbury de la muerte física, lo niego,
y condeno ese testimonio por estar fuera de la Verdad;
aunque no niego el poder que da vida a los muertos, el cual es la Palabra de vida eterna.
Esto lo digo,
para que llegue tan lejos como la ofensa contra el Espíritu de Verdad se haya extendido,
y para que se retiren todas las cargas de la Verdad; para que la Verdad,
la verdadera luz,
y todos los que caminan en ella sean absueltos y las obras de las tinieblas sean condenadas;
y también, para que todos los que todavía están en tinieblas no actúen en la noche,
sino que pongan sus mentes en Dios,
quien habita en la luz y no tiene comunión con los hacedores de iniquidad.
Pues si yo hubiera hecho esto cuando las tinieblas vinieron por primera vez sobre mí,
y no hubiera sido guiado por otros,
no habría corrido contra la Roca para ser quebrantado
(la Roca que me había llevado por mucho tiempo,
de la que había bebido mucho, y de la que ahora bebo en medida).
¡A Él sea toda la gloria, y toda lengua Lo confiese Juez y Salvador y Dios sobre todo,
bendito para siempre!

--

Nayler le agregó a esto,
una exhortación al lector sobre cómo comportarse
si en algún momento llegaba a ser tentado a pecar,
y una advertencia a no confiar demasiado en dones, sabiduría y conocimiento;
luego concluyó con las siguientes palabras:

[.embedded-content-document.paper]
--

Estas cosas las aprendí en las profundidades y en secreto, cuando estaba solo,
y ahora las declaro abiertamente en el día de Tu misericordia,
oh Señor. ¡Gloria al Altísimo para siempre,
Al que hasta ahora me ha hecho libre para alabar Su justicia y Su misericordia;
y al Dios eterno, invisible, puro y que está sobre todo, sean el temor,
la obediencia y la gloria para siempre.
Amén!

[.signed-section-signature]
James Nayler

--

Él escribió otro documento en el que relata ampliamente,
cómo había llegado a caer por falta de vigilancia,
después de que había obtenido una gran medida de victoria
sobre el poder de Satanás por la gracia de Dios,
cuando caminaba diariamente en temor;
porque él había trabajado fielmente en el ministerio
del evangelio por algunos años. Pero lo notable es,
que aunque él solía atravesar con gran audacia toda oposición,
al llegar a la ciudad de Londres (justo previo a su caída), entró en ella con gran temor,
como nunca antes había experimentado en otro lugar,
al prever en el espíritu (como relata él) que algo le iba a suceder ahí,
pero no sabía qué:

[.embedded-content-document.paper]
--

Sin embargo,
yo en ese momento tenía (continúa él) la misma presencia
y poder que había experimentado antes,
en cada lugar o servicio al que había sido guiado por el Espíritu;
y al mantenerme en esa vida nunca había regresado sin la victoria en el Señor Jesucristo.
Pero al no tener cuidado de permanecer puro en todas las cosas,
de mantenerme humilde ante los movimientos de esa vida sin fin,
y de ser guiado por Él en todas las cosas internas y externas, y en su lugar,
al darle paso al razonamiento con respecto a algunas
cosas que en sí mismas no tenían aparente maldad,
mi mente fue arrastrada poco a poco tras bagatelas, vanidades y personas,
lo cual se afianzó en la parte de los afectos.
Así fue sacada mi mente de la constante vigilancia y del temor puro,
en el que yo había sido engendrado una vez.
Y tras haber perdido en gran medida mi propia guía, habiendo caído sobre mí la oscuridad,
busqué un lugar donde estar solo para llorar y clamar delante del Señor,
para poder encontrar Su rostro y recobrar mi condición.

Pero para entonces, mi adversario,
que había esperado durante mucho tiempo su oportunidad,
había entrado y se movía en todos los sentidos, de modo que no pude esconderme,
y recibí varios mensajes, unos verdaderos y otros falsos, como he visto desde entonces.
Y así, sabiendo que unos eran ciertos (a saber, que yo había perdido mi condición),
dejé entrar los falsos también,
y dejando ir lo poco que quedaba de la verdadera luz en mí,
me entregué por completo a ser conducido por otros,
cuya obra era en ese momento separarme de los hijos de luz,^
footnote:[Es decir, la Sociedad de Amigos.]
la cual fue hecha; aunque varios de ellos hicieron mucho para prevenirla,
y en amor tierno trabajaron mucho para ayudarme.
Y después de que fui sacado de ellos,
el Señor Dios de mi vida envió a varios de Sus siervos con Su palabra tras de mí,
pidiéndome que regresara, todo lo cual fue rechazado.
Sí, mi provocación contra el amor puro de Dios en ese
tiempo de tentación era sumamente grande;
sin embargo,
Él no me dejó. Y después de que me entregué bajo el poder de mi
adversario y las tinieblas se habían levantado sobre mí,
él prevaleció de manera tal,
que todas las cosas fueron vueltas y pervertidas contra mi correcto ver, oír o entender;
únicamente tenía una esperanza y fe secretas en mi Dios,
a quien había servido anteriormente,
de que Él me llevaría a través y hasta el final de esto,
y que yo vería de nuevo el día de mi redención de debajo de todo ello.
Esto tranquilizaba mi alma en mi más grande tribulación.

--

[.offset]
El autor entonces,
exhortando seriamente a otros que podían caer también en gran tentación,
concluye con estas palabras:

[.embedded-content-document.paper]
--

¡Al que ha salvado mi alma de la muerte hasta ahora, y ha levantado mis pies del pozo,
sea la gloria por los siglos de los siglos! ¡Que toda alma atribulada confíe en Él,
pues Su misericordia permanece para siempre!

[.signed-section-signature]
James Nayler

--

Que él llegó a una recuperación perfecta después de haber sido tan engañado,
parece quedar claro por la siguiente acción de gracias a Dios por Sus misericordias,
la cual también publicó después de su caída:

[.embedded-content-document.paper]
--

¡Mi corazón te alaba, oh mi Dios!
No permitas que Te olvide; que olvide lo que Tú has sido para mí en la noche,
por medio de Tu presencia en el día de prueba.
Cuando era acosado en las tinieblas, cuando había sido echado como un ave errante,
cuando era asaltado por fuertes tentaciones, Tu presencia me preservaba en secreto,
y en ese estado abatido Te sentía cerca de mí. Cuando las inundaciones intentaban arrastrarme,
Tú les ponías un límite hasta el que debían pasar.
Cuando mi camino atravesaba el mar y pasaba bajo las montañas, Tu presencia me acompañaba.
Cuando el peso de las colinas estaba sobre mí, Tú me sostenías, de lo contrario,
me habría hundido bajo la tierra.
Cuando me sentía completamente desamparado,
cuando la tribulación y la angustia estaban sobre mí día y noche,
y la tierra se había quedado sin fundamento;
cuando yo continuaba en el camino de ira y había cruzado las puertas del infierno;
cuando todos los consuelos estaban lejos y el que es mi enemigo había tomado dominio;
cuando había sido echado al pozo y era como alguien destinado a la muerte;
cuando estaba entre las piedras de molino y me sentía aplastado por el peso del adversario;
como un padre, Tú estabas conmigo, sí, la roca de Tu presencia estaba conmigo.
Cuando las bocas de los leones rugían contra mí y
el temor se apoderaba de mi alma en el pozo,
entonces yo te invocaba en la noche y mis clamores eran fuertes delante de Ti todos
los días. Tú me respondías desde Tu habitación y me liberabas desde Tu morada diciendo:
"`Yo te pondré sobre todos tus temores y levantaré tus pies sobre
la cabeza de opresión.`" Entonces yo creía y era fortalecido,
y Tu palabra era mi salvación.

Tú peleabas por mí cuando yo luchaba con la muerte,
y cuando las tinieblas querían encerrarme,
Tu luz brillaba sobre mí y Tu bandera se posaba sobre mi cabeza.
Cuando mi obra estaba en el horno y yo pasaba a través del fuego,
no fui consumido por Ti, aunque las llamas subían sobre mi cabeza.
Cuando contemplaba las espantosas visiones y estaba entre los espíritus feroces,
Tu fe me sostenía; de lo contrario, habría caído por el miedo.
Yo te veía y creía, y así el enemigo no podía prevalecer.

Cuando miro hacia atrás Tus obras, me asombro, y no veo fin a Tus alabanzas.
¡Gloria, gloria a Ti, dice mi alma;
que mi corazón siempre esté lleno de acción de gracias!
Mientras Tus obras permanezcan, ellas manifestarán Tu poder.
Luego colocaste el fundamento de la tierra y me guiaste bajo las aguas,
y en lo profundo me mostraste maravillas y Tu creación del mundo.
Me guiaste a salvo con Tu mano, mientras me mostrabas las columnas de la tierra.
Luego los cielos dieron lluvias, fueron cubiertos de tinieblas,
sus poderes fueron sacudidos y Tu gloria descendió. Sí,
Tú llenaste de alegría las partes bajas de la tierra
y se abrieron los manantiales de los valles,
y Tu lluvia descendió abundantemente, de modo que la tierra se llenó de virtud.
Hiciste brotar Tu planta y el alma sedienta se volvió como un huerto regado.
Entonces me sacaste del pozo y me colocaste a la vista de mis enemigos.
Proclamaste libertad para el cautivo y llamaste a mis conocidos
cerca de mí. Aquellos para quienes había sido una maravilla,
me miraron, y en Tu amor obtuve favor de los que me habían abandonado.
Entonces la alegría se tragó la pena y abandoné todas mis dificultades, y dije:
"`Cuán bueno es que el hombre sea probado en la noche, para que conozca su insensatez;
para que toda boca se quede en silencio en Tu mano,
hasta que hagas que el hombre se conozca a sí mismo, hayas matado al jactancioso,
y le muestres la vanidad que aflige a Tu Espíritu.`"

[.signed-section-signature]
James Nayler

--

Esto claramente parece ser una pieza poética,
ya que el autor hace uso de expresiones alegóricas en todo momento,
para indicar la gran angustia y tribulación bajo las que había estado,
al declarar cómo los poderes de las tinieblas habían prevalecido en él,
al punto de contristar al Espíritu de Dios,
poner una piedra de tropiezo en el camino del sencillo,
y hacer que se hablara mal del camino de la Verdad.

El odio de sus enemigos era de lo más feroz, porque previo a su caída,
él había demostrado clara y abiertamente el deber de los gobernantes,
predicadores y abogados; pues en cierto libro publicado por él en 1653,
con el fin de exhortarlos al arrepentimiento,
les escribe a los gobernantes de la siguiente manera:

[.embedded-content-document]
--

Oh gobernantes del pueblo,
que están establecidos para juzgar entre un hombre y su prójimo,
¿no deberían juzgar ustedes en nombre de Dios y no en el del hombre?
¿No deberían ser ustedes hombres temerosos de Dios y aborrecedores de la codicia,
que no juzgan por regalos y recompensas?
¿No deberían aprobar y animar ustedes a los que hacen bien,
y ser terror para los que hacen mal?
La justicia es así. El que es de Dios y lleva Su espada,
vuelve el filo de ella contra todo pecado y maldad, injusticia y opresión;
así establece la justicia y el juicio en las puertas,
para que el pobre sea liberado del que es demasiado fuerte para él,
y para que la causa del huérfano, de la viuda y del extranjero no caiga.
Un gobernante como este tiene un oído abierto a los clamores del pobre y desamparado,
del que tiene poco dinero y pocos amigos;
a fin de que el pobre no tenga miedo de comparecer en una buena causa,
contra el más grande opresor de la nación. ¿Y no
deberían juzgar sin hacer acepción de personas,
o sin buscar respeto, adoración u honor de los hombres,
sino sólo para promover la rectitud, equidad y justicia que es de Dios,
para que así sean honrados por el Señor? Porque la
verdadera humildad es honor y el que honra al Señor,
será honrado.
Tales hombres han sido honrados en todas las edades,
aunque ellos nunca han buscado honor de los hombres.

--

[.offset]
Esto y mucho más les escribió a los gobernantes; y a los predicadores les escribió así:

[.embedded-content-document]
--

Ustedes que dicen ser los maestros de la nación,
¿cuánto tiempo pasará antes de que miren sus propios caminos?
¿No hay entre ustedes toda forma de inmundicia, de la que deberían sacar al pueblo?
¿No hay entre ustedes embriaguez, glotonería, prostitución y diversión,
al sentarse a comer y beber, y al levantarse a regocijarse; al jurar, mentir, murmurar,
acusar falsamente, criticar, calumniar, contender, luchar y envidiar?
En efecto, ¿no son los mejores de ustedes dados al orgullo y a la codicia,
la cual es idolatría;
"`saciedad de pan y abundancia de ociosidad`"? ¿No son ustedes
asalariados que enseñan a las ovejas sólo para quitarles la lana?
¿No contienden por el dinero de sus propios oyentes,
y los demandan ante la ley por él--incluso a los que no pueden satisfacer
sus demandas sin pecar contra la luz en sus propias consciencias,
y así pecar contra Dios?
¿No son ustedes amargos perseguidores de cualquiera
que llegue a poner al descubierto su lascivia,
y huyen a los magistrados para que los apoyen en
sus propios caminos (los caminos "`de la bestia`"),
y detengan la boca de todos a los que Dios ha enviado para testificar contra ustedes?
Y muchas más obras de esta naturaleza hay entre ustedes,
que el Dios puro que todo lo ve ha mostrado a Su pueblo, y por lo tanto,
ellos salen de ustedes, para no participar con ustedes de sus pecados y plagas.

--

[.offset]
En el mismo escrito también los abogados recibieron un golpe:

[.embedded-content-document]
--

Ustedes abogados,
¿no deberían defender la causa de la equidad entre
hombre y hombre por el bien de la equidad,
sin considerarse a ustedes mismos o a otros, sino sólo a la verdad misma?
¿Acaso no se derrumba la causa de la justicia si una parte
no tiene suficiente dinero para satisfacer sus demandas,
las cuales muchas veces son exorbitantes?
Ustedes, que deberían instruir al pueblo en los caminos de la verdad y de la paz,
¿no le enseñan por medio de su sabiduría a mentir y a contender?
¿No les aconsejan a sus demandantes que declaren cosas que no son ciertas,
y hagan que las pequeñas ofensas parezcan muy grandes mediante explicaciones falsas?
Porque ustedes dicen:
"`Podemos declarar lo que queramos y probar lo que podamos;`" pero
de antemano saben que apenas una cosa de cada diez puede probarse,
y que tampoco es cierta.
¿Es esta la manera de reparar los portillos y preservar
la paz y la verdad entre las personas?
¡Oh miserable caída de Dios,
cuando la ley que debería preservar la paz es usada para agravar las ofensas,
y así agrandar las diferencias! ¿No se deleitan ustedes en pescar en aguas
turbulentas?--porque cuanto mayor es la disensión entre las personas,
mayor es la ganancia de ustedes.
¿No están llenos sus monederos y sus propiedades levantadas sobre la ruina de las personas?
La ley, tal como se usa ahora, es apenas útil para cualquier otro fin,
excepto el del envidioso, que tiene mucho dinero para vengarse de su pobre prójimo,
que tal vez, nunca le ha hecho mal.

--

[.offset]
Les escribió mucho más a los abogados, para incitarlos a hacer justicia,
y luego se dirigió a la gente en general con las siguientes palabras:

[.embedded-content-document]
--

Pueblo de la nación, ¿cuándo dejarás de provocar al Señor por medio de tus pecados?
¿Dónde está tu Redentor, a quien has profesado por tanto tiempo en palabras y formas?
¿Das testimonio de Él en tus obras?
¿De qué te ha redimido Él? Porque Él dice:
"`¿Por qué me llaman Señor y no hacen lo que digo?`"
¿Es Él tu Señor, y sin embargo, sigues siendo siervo de toda forma de inmundicia?
A pesar de que has visto Sus maravillas en esta nación,
rebasas con creces lo sucedido antes, en orgullo, codicia, embriaguez, juramentos,
envidia, riñas, murmuraciones, calumnias, acusaciones falsas, egoísmo,
engaño en todo tipo de mercancía y comercio, medidas y pesos alterados,
hablando cosas que no son ciertas.
¿Cuántos falsos juramentos y vanas palabras se usan
en los tratos en tus mercados y al aire libre,
sin que nadie se sonroje o avergüence?
Sí, ver y oír esto es suficiente para romper el corazón
de cualquiera que conozca al Dios puro,
porque el engaño ha llegado a tal grado, que nadie puede confiar en su hermano.
Aunque mentir, jurar y perjurar abunda en la nación,
¿todavía confiesas ser miembro de Jesucristo?
¿Tiene Jesucristo un cuerpo como ese?
No, todo el que es miembro del cuerpo, es de un corazón y un alma.

Tú hablas de la comunión de los santos,
pero ¿han tenido alguna vez los santos una comunión como esta--profesar
un Redentor y permanecer como siervos del diablo y de sus propios deseos?
¿Qué redención es la que testificas?
En tanto el pecado (la pared intermedia entre Dios y tú) permanezca intacto en tu voluntad,
beberás, jurarás, mentirás y cometerás adulterio,
al satisfacer tus propios deseos en todas las cosas, y aun así dirás: "`Estoy redimido.`"
¿Redimió Jesucristo alguna vez a un pueblo así,
o mora en un pueblo así? Aquellos a quienes Él ha redimido,
los ha hecho libres de la servidumbre del pecado,
al separarlos del pecado y reconciliarlos con Dios,
de quien habían caído por causa del pecado: pues Dios y el pecado no pueden morar en uno.
A estos Él les dice: "`Sed santos, porque yo soy santo.`"
Él es el "`Cordero de Dios que quita el pecado del mundo,`" ahora dime,
¿cómo es quitado el pecado de ti,
cuando el reino de las tinieblas gobierna por completo
en ti y te lleva a las obras y caminos de las tinieblas?
¿Estás reconciliado con Dios y tienes comunión con Él? ¿No
eres aún extraño para Él y adoras a un Dios desconocido?
"`Todo aquel que peca, no le ha visto, ni le ha conocido,`"^
footnote:[1 Juan 3:6]
y así adora (aunque no sabe qué) en formas y superstición.

--

Así escribió James Nayler antes de su caída, pero por los engaños de Satanás,
aceptó el honor idólatra de los que él debió haber reprendido rápidamente;
y estaba tan atontado en su entendimiento,
que imaginaba que la inclinación y postración delante de él no era por su persona,
sino por Cristo.
Con esta opinión falsa se cegó por un tiempo,
hasta que le plació a Dios compadecerse de él y darle nuevamente luz,
después de que había sufrido un castigo inaudito por su transgresión,
como ya se ha relatado.
Y debido a que su pasada predicación contra la injusticia
había caído muy severamente sobre toda clase de personas,
en la que demostraba claramente y sin disfraz el deber cristiano de los gobernantes,
predicadores y abogados, el odio de sus enemigos era más fiero.
En realidad, varios que llevaban mucho tiempo enojados con él,
se aprovecharon de su crimen para vengarse bárbaramente de él,
haciéndolo sufrir un castigo cruel que en ninguna forma era proporcional
a su transgresión. Pero esta bárbara crueldad fue tan notoria,
que los habitantes más sobrios la detestaron,
por lo que presentaron la mencionada petición al Parlamento,
solicitando el descargo de parte del castigo,
de la que el primer firmante fue el coronel Scroop, el gobernador de Bristol.

Mientras él estaba en la casa de corrección,
escribió varios artículos manifestando su pesar y arrepentimiento por su crimen,
algunos de los cuales ya han sido insertados,
pero la siguiente carta hasta ahora llega a mi mano.
Es una carta a sus amigos, escrita con su propia mano:

[.embedded-content-document.letter]
--

[.salutation]
Queridos hermanos,

Mi corazón está roto en este día por la ofensa que
les he ocasionado a la verdad y al pueblo de Dios,
y especialmente a ustedes, que me siguieron con tierno amor,
buscándome en fidelidad a Dios,
y cuyo amor rechacé. Pues estaba atado en aquello de lo que no podía salir,
hasta que la mano de Dios me sacó; Cuyo amor confieso ahora.
Les ruego que perdonen la manera con la que yo perversamente les pagué su amor
ese día. Dios conoce mi dolor por eso (ya que he sido capaz de verlo),
pues nunca debí ofender al Espíritu de Dios en ninguno o rechazar Su consejo.
Y ahora, ese artículo que ustedes han visto pesa mucho sobre mí,
y temo en gran manera ofender más o hacer algo incorrecto,
por medio de lo cual la inocente Verdad o el pueblo de Dios sufran,
o desobedecer en esto.

A menos que el Señor los mantenga alejados de mí,
les ruego que no dejen que nada más les impida venir a mí,
para que yo pueda recibir la ayuda de ustedes en el Señor. En las misericordias de Jesucristo,
se los ruego, como si esta fuera su propia condición; no me olviden.

Les ruego que hablen con Henry Clarke o con cualquier otro a quien yo haya ofendido;
y por el poder de Dios y en el Espíritu de Jesucristo,
estoy dispuesto a confesar mi ofensa,
para que el amor de Dios se levante en todos los corazones como antes, si es Su voluntad,
pues Él es el único que puede remover lo que se interpone en el camino.
No pretendo encubrir nada; Dios es mi testigo en esto.

--

[.offset]
Él también escribió otras confesiones de sus faltas en ese tiempo, en una de las cuales,
entre otras, encuentro estas palabras:

[.embedded-content-document.letter]
--

En cuanto a ustedes, tiernas plantas de mi Padre, que han sufrido debido a mí o conmigo,
en lo que el Señor ha permitido que se haga conmigo
en este tiempo de gran tribulación y tentación:
Que el Todopoderoso Dios de amor,
que ha contado cada suspiro y puesto cada lágrima en Su odre,
se los recompense mil veces en sus pechos, en el día de necesidad,
cuando sean tratados y tentados.
Y mientras tanto, que Él cumpla nuestro gozo con Su amor, el cual ustedes buscan.
El Señor sabe que nunca estuvo en mi corazón hacerlos llorar;
el sufrimiento de ustedes es el más grande dolor que alguna vez me haya sobrevenido,
pues ustedes son inocentes en esto.

--

[.offset]
Cuando había terminado esta carta y puesto su nombre, escribió la siguiente posdata:

[.embedded-content-document.letter]
--

Les ruego (a todos los que puedan) recibir esto como
desearían ser recibidos por el Señor;
y en cuanto a los demás,
que el Señor me dé paciencia para sufrir hasta que Él repare la brecha.

--

[.offset]
Mientras estaba en Bridewell,
le escribió al Parlamento que lo había castigado como blasfemo,
para hacerle saber su verdadera opinión acerca de Jesucristo.

[.embedded-content-document.letter]
--

Sólo a Jesucristo (el Emanuel,
de cuyos sufrimientos declaran las Escrituras) confieso delante de los hombres.
Por Su causa he negado todo lo que era estimado para mí en este mundo,
a fin de poder ganarlo a Él, y ser hallado en Él y no en mí. Procuro servirle sólo a Él,
en espíritu, alma y cuerpo, noche y día, según la medida de gracia que obra en mí,
para que en mí Él sea glorificado, sea por la vida o por la muerte.

Pero atribuirle este nombre, poder y virtud a James Nayler,
o a lo que tuvo un principio y debe regresar al polvo,
o para que eso sea exaltado o adorado, para mí es gran idolatría,
y con el Espíritu de Jesucristo en mí, es condenado; cuyo Espíritu conduce a la humildad,
mansedumbre y paciencia.

Por tanto, habiendo recibido una oportunidad, estoy dispuesto con presteza,
en el temor de Dios el Padre y en honor a Jesucristo,
y con el fin de quitar todas las ofensas de cada corazón sencillo,
a declarar esto ante todo el mundo, sin malicia ni engaño, al encontrar diariamente,
que mi trabajo es buscar la paz en la verdad con todos los hombres, en dicho Espíritu.

[.signed-section-signature]
James Nayler

--

Después de esto,
al enterarse de que algunos lo habían perjudicado
por algo que él le había dicho al comité del Parlamento,
y entender la manera en que los hombres habían pervertido sus palabras,
escribió un documento en el que además hacía una
declaración acerca de su creencia en Cristo,
Sus sufrimientos, muerte, etc.
También denunció un artículo que alguien había publicado en forma anónima,
bajo el título __James Nayler`'s Recantation,__^
footnote:[Es decir, '`Retractación de James Nayler.`']
en el que se habían pervertido mucho sus palabras.

[.embedded-content-document.paper]
--

Con respecto +++[+++escribe él]
a la publicación de ese artículo llamado _James Nayler`'s Recantation,_
declaro que no fue escrito por mí, ni con mi conocimiento, y que no conozco, en absoluto,
al hombre que lo ha hecho.
Sé que fue hecho fuera de la Verdad y contra la Verdad, y por maldad hacia mí,
quienquiera que sea.
¡Qué el Señor Dios de mi vida, quien me ha preservado con vida en toda angustia,
vuelva esto para bien y perdone el mal!
Sin embargo, reconozco la medida de verdad que hay en este artículo,
porque después de que fui puesto en el hoyo en Bridewell,
me enteré de que ciertas personas que pretendían estar de mi lado,
habían realizado muchas actos absurdos.
Estas fueron afanosamente incitadas en aquel momento,
y con mucha violencia y actos indecorosos entraban
en las reuniones del pueblo del Señor llamado Cuáqueros,
con el propósito de entorpecer sus reuniones pacíficas.
Y sin embargo,
tomaban frecuentemente el nombre puro y santo de Dios y de Cristo en sus bocas,
por lo que el nombre del Señor fue muy deshonrado y Su Espíritu puro afligido,
porque causaban mucho desorden en muchos lugares de la nación para la deshonra de Jesucristo,
por lo cual sentí la ira de Dios.
Pero cuando comprendí que ellos tenían cierta influencia a través de mí,
usé todos los medios que pude para declarar contra ese espíritu maligno,
que bajo el nombre de Dios y de Cristo, estaba contra Dios y Cristo,
y contra Su verdad y Su pueblo.
Hace aproximadamente un año y medio escribí algo en rechazo a esos espíritus,
que me parece que el autor de ese artículo ha visto,
al que él le añadió los pensamientos de su propio corazón,
y así publicó su obra de tinieblas, y el pueblo no sabe qué hacer con eso.

Por tanto,
reconozco ese artículo hasta donde testifica contra esos espíritus inmundos y alborotadores,
y contra todas las acciones con las que el nombre
de Dios era deshonrado y Su Espíritu afligido.
Pero niego,
cuando sugiere que yo negué al Señor Jesucristo y
Su verdad que me llamó a salir del mundo,
o a Su pueblo a quien Él llamó a la luz.
Porque en la paciencia y tribulación de Jesucristo,
y con todos aquellos que tienen el poder de testificar hoy
contra todas las perversidades de este mundo presente,
soy uno en corazón y alma al máximo de mi fuerza,
hasta la venida del Señor Jesús sobre todo.
¡Qué el trono de mansedumbre y verdad sea puesto
encima de toda enemistad y engaño! Y ahora,
en la fe y poder de Cristo, me rindo para vivir o morir, para sufrir o regocijarme,
según el deseo de Dios, así sea, sin murmuración.

[.signed-section-signature]
James Nayler

--

Es innegable, que James Nayler sufrió un gran dolor y profunda humillación mental,
y por tanto, debido a que Dios perdona las transgresiones del arrepentido,
las borra y no las recuerda más,
los amigos de James Nayler no pudieron hacer otra cosa más que perdonar su crimen,
y así recibir de nuevo en su sociedad a la oveja perdida.
Y tras obtener su libertad,
se comportó como un verdadero Cristiano--honesto e intachable en conducta,
y soportando pacientemente el oprobio de sus anteriores ofensas.
