== Capítulo 5

[.section-date]
1654--1655

[.chapter-synopsis]
* W. Caton y J. Stubbs viajando juntos, son cruelmente azotados
* Van a Zelanda y Holanda
* Regresan y se adentran en Escocia
* Obra y crueles sufrimientos de J. Parnel
* Muerte de J. Parnel
* E. Burrough y F. Howgill en Irlanda
* W. Ames convencido
* E. Burrough y F. Howgill desterrados de Irlanda
* Bárbara Blaugdone en Irlanda
* Circunstancias extraordinarias de su visita en Irlanda
* M. Halhead va a Londres
* Su carta a su esposa
* Encarcelamiento de M. Halhead y T. Salthouse
* Encarcelamiento de G. Whitehead, R. Clayton y J. Harwood
* Notable conversación entre W. Dewsbury y el juez Atkins
* El temor de G. Fox con respecto a J. Nayler
* Notable relato de J. Lilburn
* Complot de los de la realeza contra Cromwell.

Pero antes de decir más de Fisher, regreso a William Caton y John Stubbs.
Estos fueron de Lydd a Ashford, Tenterdeu, Cranbrook y Staplehurst,
donde encontraron personas abiertas y de corazón tierno que abrazaron su doctrina,
y que querían darles dinero; sí, incluso los querían forzar,
pero no quisieron tomar nada.
Pues así como habían recibido gratuitamente, gratuitamente daban,
y les dijeron a las personas que no buscaban lo de ellos, sino a ellos.
De ahí viajaron a Maidstone,
donde John Stubbs acudió al lugar público de adoración
y William Caton a la reunión de los Independientes.
Stubbs fue detenido en la '`casa del campanario,`'
y al día siguiente Caton fue sacado de su posada,
y ambos fueron enviados a la casa de corrección,
donde los registraron y les confiscaron el dinero, tinteros, biblias, etc.
Después los desnudaron, y con sus cuellos y brazos asegurados en el cepo,
fueron terriblemente azotados.
En realidad, fue una dura sentencia, especialmente para un joven como William Caton;
pero fueron sostenidos por una mano invisible.

Después de esto, se usaron medios para obligarlos a trabajar,
y se les dijo que el que no trabajara,
no comería. Pero ellos no se sintieron libres de consentir a tales demandas,
porque las estimaban injustas, al no ser culpables de la infracción de alguna ley.
Por tanto, los dejaron sin comida por algunos días,
y sólo se les permitía un poco de agua una vez al día. Mientras tanto,
los delincuentes que estaban ahí les querían dar algo de su pan; incluso,
las mujeres de la casa (movidas por compasión) querían darles algo secretamente,
pero ellos no se sintieron libres de aceptar ninguna de las dos cosas.
Cuando la noticia de esta crueldad se difundió en el pueblo,
muchos empezaron a ofenderse por eso,
de modo que un oficial fue enviando a restituirles
algunas de las cosas que les habían quitado,
y luego ellos compraron comida con su propio dinero.
No mucho después fueron separados y trasladados por oficiales fuera del pueblo;
uno a un extremo del pueblo, y el otro al otro extremo.

Finalmente William Caton llegó a Londres, donde encontró a su compañero John Stubbs,
pero después de llegar,
les vino del Señor regresar al pueblo del que habían sido expulsados,
lo que no fue una prueba pequeña para ellos.
Sin embargo,
se rindieron y se entregaron a lo que creían que era la voluntad del Señor. Entonces,
cuando regresaron, la Providencia ordenó que nadie se entrometiera con ellos,
aun cuando a fin de ser más vistos,
fueron a la '`casa del campanario`' el Primer-día. También fueron a Canterbury,
donde tuvieron bastante libertad de declarar la Verdad
en las reuniones de los Bautistas e Independientes;
y algunos, al ser convencidos, recibieron el testimonio de ellos.
De la misma manera estuvieron en Sandwich,
donde W. Caton tuvo algo de servicio en la '`casa del campanario`' de los holandeses.

Ya estaba cerca el solsticio de verano, y Caton se sintió movido a ir a Calais,
en Francia.
Con ese propósito fue a Dover, y de ahí navegó a Calais,
donde al llegar a su lugar principal de adoración,
su espíritu se afligió y se cargó mucho por la gran idolatría que estaba en boga ahí;
pues vio que algunos estaban adorando frente a sus ídolos mudos,
y no pudo aliviar su espíritu por no hablar el idioma.
Después de caminar un rato por el pueblo,
su presencia fue notada por los principales hombres de la ciudad,
quienes deseando hablar con él, bajaron en persona al puerto para buscarlo,
y entendiendo que estaba a bordo del barco,
lo llamaron a tierra y lo llevaron a una gran casa,
donde habían llegado varios para verlo y escucharlo.
Como había un escocés que traducía para él,
tuvo una muy buena oportunidad de declarar la Verdad entre ellos.
Y luego de que había descargado su consciencia, le permitieron marcharse tranquilamente.

Poco después regresó a Inglaterra y encontró a su compañero John Stubbs en Dover;
y como estaba sobre Stubbs ir a Holanda, William Caton se sintió libre de acompañarlo.
Con esa intención se fueron juntos a Yarmouth,
pero no pudieron encontrar un pasaje para Holanda, y por tanto, se fueron más al norte.
Eventualmente llegaron a Swarthmore,
y Caton encontró a sus amigos muy contentos de verlo, especialmente a Margaret Fell,
quien había sido como una madre para él. Después de una
corta estadía ahí y de que habían descansado completamente,
se fueron a Shields, donde oyeron de un barco con destino a Flanders,
pero al tener poca inclinación a ir allí, poco después regresaron a Yarmouth,
donde encontraron un barco con rumbo a Flushing, en Zealand.
Atravesaron el océano en la nave y llegaron a salvo al mencionado pueblo.
El Primer-día fueron a la congregación de los ingleses y escoceses,
donde muchos se maravillaron de ellos por su no conformación;
pero después de que comenzaron a hablar se levantó un gran revuelo,
y fueron sacados rápidamente de la casa.

El mismo día se fueron a Middleburg antes de que terminara el culto vespertino ahí,
y uno de ellos comenzó a hablar cuando el sacerdote ya había terminado.
Pero lo detuvieron de inmediato,
pues al principio el sacerdote pensó que habían llegado a mendigar; sin embargo,
al darse cuenta de lo contrario, él y otros fueron de lo más violentos con ellos.
Después de eso, el sacerdote los mandó a llamar a su casa y discutió con ellos un rato,
pero al ser de mente altiva, Caton y Stubbs encontraron poca acogida.
Tras una corta estadía en el pueblo, se embarcaron hacia Rotterdam, en Holanda,
donde después de unos pocos días en la ciudad,
consiguieron hacer una reunión en la casa de un comerciante inglés. Pero al ver
que el hombre que interpretaba para ellos no traducía sus palabras correctamente,
parecía no satisfacer a los oyentes.
Después de algún tiempo regresaron a Zealand, y de ahí otra vez a Inglaterra;
tras llegar W. Caton viajó a Swarthmore, donde fue recibido con alegría. Luego,
al sentir algunas persuasiones de ir a Escocia, fue a Bishoprick,
donde halló a su compañero John Stubbs de nuevo, con quien viajó a Escocia.
Llegaron a Berwick-upon-Tweed a principios del mes llamado diciembre.
William Caton fue a la gran asamblea pública, y cuando el sacerdote terminó,
se subió en un asiento y empezó a hablar, mientras el sacerdote se apresuraba a salir.
Ahí habló con gran audacia y tuvo bastante libertad para declarar la Verdad,
pero cuando terminó fue tomado y llevado ante los magistrados,
quienes ordenaron que lo expulsaran del pueblo; y así se hizo.
John Stubbs ese día estaba en una reunión de los Bautistas,
y realizó algo de obra ahí. No mucho después, W. Caton (después de vagar arriba y abajo,
y de no encontrar a nadie que lo alojara por su dinero)
regresó y entró de nuevo al pueblo,
y la guardia le permitió pasar libremente.

Luego ambos viajaron a Edinburgh, en Escocia,
donde encontraron los asuntos de la iglesia un tanto desordenados,
por la infidelidad de algunos de los que habían sido convencidos de la Verdad.
Pero el ministerio de Caton y Stubbs fue tan efectivo entre ellos,
que fueron llevados a un mejor orden de nuevo;
y así edificaron la iglesia según sus propias habilidades.
La reunión se celebró en la casa de William Osborn,
quien había sido teniente-coronel y que después se
convirtió en un celoso ministro del rebaño de Cristo.
Mientras Caton estaba ahí, una vez fue a la '`casa del campanario`' principal,
y cuando el sacerdote terminó, les habló a las personas.
Pero la multitud se reunió rápidamente y no le permitió decir mucho, sino que lo sacó,
y cuando salió a la calle encontró una guardia de soldados,
quienes con las espadas desenvainadas, lo conducían a los lugares donde deseaba estar.
Por ese mismo tiempo también estuvo con el general Monck,^
footnote:[El general George Monck (1608-1670) fue un soldado y político inglés,
y figura clave en la restauración de la monarquía del rey Charles II en 1660.]
quien se comportó moderadamente y lo escuchó. Luego John
Stubbs regresó a Inglaterra y William Caton fue a Stirling,
donde fue llevado delante del gobernador, que al principio parecía orgulloso,
pero cuando Caton (que eran un joven de conducta mansa) le habló un poco,
se tranquilizó y serenó. Luego fue a la casa del capellán inglés,
quien fue amable con él.

De Edinburgh fue a Glasgow,
y al entrar en la gran catedral después de que había terminado el servicio,
tuvo cierta libertad para hablarle a la multitud en el jardín,
pues la gente violenta fue mantenida en calma por los soldados ingleses,
quienes eran hombres moderados;
de modo que tuvo un muy buen servicio ahí. También fue a Douglas,
donde sus servicios fueron parecidos,
tanto en la '`casa del campanario`' como en otros lugares.
Así, habiéndose descargado en Escocia, regresó a Inglaterra y fue de nuevo a Swarthmore,
donde fue recibido con gran amor como antes.

Dejándolo ahí, regreso otra vez a George Fox, a quien dejamos en Bedfordshire.
De ahí se fue por Londres a Kent, y llegó a Romney,
no mucho después de que William Caton y John Stubbs
estuvieran allí. Ahí tuvo una gran reunión,
a la que también llegó Samuel Fisher, y en la que hubo un gran convencimiento ese día,
de modo que muchos fueron vueltos a la luz de Cristo.
Después de la reunión la esposa de Samuel Fisher dijo:
"`Ahora podemos discernir entre la carne y el espíritu,
y diferenciar la enseñanza espiritual de la carnal.`"

De ahí G. Fox se fue a Dover y Canterbury, y luego a Sussex, y así a Reading,
donde tuvieron una gran reunión y muchos fueron convencidos ese
día. A esta reunión también llegó George Bishop de Bristol,
quien al ser capitán, llevaba entonces una espada,
aunque con el tiempo la dejó por completo.

G+++.+++ Fox se fue de ahí y pasó a Londres,
donde lo dejaremos por un tiempo e iremos a echarle
un vistazo a la vida y sucesos de James Parnell,
quien nació en Retford, en Nottinghamshire, y se formó en escuelas de literatura.
Este joven comenzó a trabajar en el ministerio del evangelio a una edad muy temprana,
habiendo sido convencido por G. Fox cuando aún no tenía dieciséis años;^
footnote:[Esto ocurrió en 1653, mientras George Fox estaba en prisión en Carlisle,
en cuyo diario encontramos la siguiente declaración:
"`Mientras yo estaba en el calabozo en Carlisle, James Parnell,
un jovencito de unos dieciséis años vino a verme y quedó convencido.`"
Antes de esto, James Parnell no había tenido ninguna interacción con los Amigos,
aunque las personas con las que él había estado asociado antes en adoración religiosa,
habían sido llevadas muy cerca a los principios de ellos.
Por lo que encontramos en los escritos de Parnell,
es evidente que antes de ese momento él ya había
experimentado una conversión real de corazón,
había sido llevado a ver el formalismo de los sacerdotes,
y se había separado de la forma acostumbrada de adoración, para sólo esperar en el Señor;
de modo que, por la entrevista con George Fox,
fue meramente convencido de que la Verdad que Fox predicaba,
era la misma a la que él había sido dirigido por el Espíritu de Verdad.]
no obstante, al abrazar la Verdad fue despreciado y rechazado por sus parientes.
Aunque bajo de estatura, estaba dotado de grandes habilidades,
y a donde quiera que llegara, no temía llamar a la gente al arrepentimiento.
Después de ser prisionero en Cambridge por causa de su celoso testimonio,
fue echado del pueblo como un vagabundo,
pero pronto regresó y discutió con los estudiantes de la universidad; sin embargo,
se topó con un recibimiento rudo y malo por parte de ellos.

Al principio de ese año llegó a Essex, teniendo entonces unos dieciocho años de edad,
y predicó el evangelio en varias partes del condado, tales como Felsted, Stebbing,
Witham, Coggeshall, Halsted y otros lugares,
y muchos recibieron la palabra por su ministerio.
A mediados del verano llegó a Colchester,
y ahí predicó el evangelio el Primer-día en la '`casa del campanario,`' después de que
había terminado el sermón. Luego predicó en una gran reunión fijada con ese propósito,
y después discutió con el profesor del pueblo y otro sacerdote en la escuela francesa--todo
esto en un día. Muchos fueron convencidos de la Verdad predicada por él,
entre estos también estaba Stephen Crisp, de quien se dirá más en su momento.
James Parnell pasó esa semana en dicho pueblo predicando,
exhortando y discutiendo para el convencimiento de muchos;
aunque otros se enfurecían a tal punto,
que su piadoso celo a menudo era recompensado con golpes.
Una vez, saliendo de la '`casa del campanario`' de Nicholas,
fue golpeado por un hombre con un gran bastón que le dijo:
"`¡Toma esto por amor de Cristo!`"
A esto Parnell respondió mansamente: "`Amigo,
lo recibo por amor de Jesucristo!`" Él soportó muchos
otros abusos graves sin mostrar ningún ardor o rabia,
de modo que era un modelo real de paciencia y mansedumbre.

Después de trabajar en el evangelio cerca de diez días en Colchester, fue a Coggeshall,
donde se proclamó un ayuno para el 12 del mes llamado julio,
para "`orar contra los errores del pueblo llamado Cuáqueros.`"
Cuando James Parnell llegó,
entró en la '`casa del campanario`' y permaneció
quieto hasta que el sacerdote bajó del púlpito.
Ahora bien, como este sacerdote Sammes, que era de los Independientes,
había gritado fieramente contra los Cuáqueros, llamándolos engañadores, etc.,
Parnell estimó su deber decir algo en respuesta a esto.
Las primeras palabras que dijo fueron: "`Este es el orden de la verdadera iglesia,
'`que todos hablen uno por uno, y si algo le fuere revelado a otro que estuviere sentado,
calle el primero.`'`"^
footnote:[1 Corintios 14:30-31]
Luego empezó a hablar en nombre de los llamados Cuáqueros,
pero el sacerdote interrumpiendo le preguntó, qué objetaba en su contra.
A esto J. Parnell respondió, que había injuriado al pueblo llamado Cuáqueros,
que había dicho que ellos estaban edificados sobre un fundamento de arena,
y que los había llamado agitadores.
"`Pero,`" dijo, "`te probaré que el fundamento de ellos no es arena,
y que tú eres un falso profeta.`"
Después de que dijo algunas palabras más,
algunos lo acusaron de no reconocer ninguna iglesia.
Él dijo que eso era falso.
Entonces le preguntaron qué iglesia reconocía. Él respondió: "`La iglesia en Dios.`"
Entonces el sacerdote Willis se puso de pie y le dijo que él no
decía más que tonterías. Pero Parnell quiso que nombrara una palabra
de las que había dicho que fuera una tontería. Willis dijo:
"`Decir,
'`la iglesia en Dios.`'`" Entonces Parnell sacó su biblia y leyó 1 Tesalonicenses 1:1,
donde el apóstol escribe "`a la iglesia en Dios Padre.`"
En ese momento el sacerdote estaba perdido,
y Parnell le dijo que él había blasfemado al decir que la iglesia en Dios era una tontería.
Entonces el sacerdote Stellum se levantó y acusó a Parnell con mentiras y calumnias,
y sin permitirle responder a esas acusaciones, subió al púlpito y empezó a orar.
Pero como Parnell no se había quitado el sombrero,
los magistrados lo llamaron para que se lo quitara.
A lo cual él respondió: "`¿Por qué no le ordenan al sacerdote que se quite su capa?`"
Y añadió,
que en lugar de estar sujeto a las voluntades de ellos prefería salir de la reunión,
y salió.

No mucho después,
el juez Dionysius Wakering lo siguió y lo golpeó con su mano en la espalda,
diciendo que lo arrestaba en nombre del señor protector.
Parnell, sin saber que él era un magistrado,
le preguntó que dónde estaba su orden de la corte.
Wakering le dijo que él tenía una, pero no le mostró ninguna.
Fue llevado donde se habían reunido cuatro jueces y seis o siete sacerdotes.
Luego el juez Wakering le quitó el sombrero a Parnell y lo tiró,
y le hicieron preguntas con respecto a muchas cosas; todas las cuales respondió,
junto con las preguntas frívolas que le hicieron sólo para atraparlo.
Al fin, fue encerrado en la cárcel común de Colchester,
donde no se le permitió a ninguno de sus amigos visitarlo.
Cuando llegó el momento de las sesiones de la corte en Chelmosford, él,
junto con varios delincuentes y asesinos,
fue sujetado a una cadena y llevado así cerca de dieciocho millas a través del condado,
permaneciendo encadenado noche y día.

Cuando fue presentado en la corte ante el juez Hills,
el carcelero le quitó el sombrero y lo tiró al suelo.
Luego el secretario leyó su acusación y le preguntó si era culpable.
Parnell dijo que negaba toda culpabilidad y pidió ver a sus acusadores.
El juez le dijo que los vería,
pero que primero debía declararse "`culpable`" o "`no culpable.`"
Parnell dijo que no era culpable.
Luego fue llamado un jurado de doce hombres (cuyo presidente era un borracho),
y fue llamado también el sacerdote Willis, quien hizo su juramento contra él,
junto con otros dos jueces.
Las acusaciones eran,
que él había entrado en la iglesia parroquial de Great Coggeshall de manera revoltosa,
que se había puesto de pie y le había dicho al ministro
que él blasfemaba y hablaba falsamente,
y que había usado muchas otras palabras de reproche contra él. Además,
se alegó que él no había podido dar buena cuenta del último lugar donde se había instalado,
ni nada con respecto a su vida y conducta, y por tanto, parecía ser una persona ociosa.
Finalmente, fue acusado de desacato a la magistratura y al ministerio.

A todo esto Parnell respondió,
que él no había entrado a la '`casa del campanario`' de manera revoltosa,
sino que lo había hecho tranquilamente y solo;
porque al ser seguido por varios muchachos que habrían entrado después de él,
les había pedido que se adelantaran,
en lugar de entrar de manera desordenada y haber ocasionado algún disturbio.
No negó que le había dicho al sacerdote Willis,
que había blasfemado al decir que la iglesia en Dios era una tontería,
pero que no aceptaba ser un vagabundo o una persona ociosa.
Además, que no le parecía inapropiado llamar a un juez injusto, injusto;
a un perseguidor, perseguidor; a un engañador, engañador.
Así defendió Parnell su causa.
Sin embargo, el juez le dijo al jurado que si no lo encontraban culpable,
el pecado caería sobre sus cabezas;
condenando así al prisionero antes de que el jurado hubiera considerado el caso.
Entonces Parnell empezó a hablar a fin de informarles acerca de su motivo,
pero el juez no se lo permitió, aunque un miembro del jurado quería que continuara.

Después de deliberar,
el jurado no tenía nada de que culparlo (excepto un documento
en el que él había respondido la orden de la corte,
aunque ya había admitido que ese documento era su escrito).
Sin embargo,
el juez y el secretario se esforzaron por sacarle algunas palabras al presidente,
algo que los otros miembros del jurado no consintieron,
ni él tampoco estaba dispuesto a cumplir plenamente con sus intenciones.
Parnell había sido obligado a retirarse de la corte y cuando fue llamado de nuevo,
el juez le impuso una multa de unas cuarenta libras,
por desacato a la magistratura y al ministerio; "`pues,`" dijo él,
"`el señor protector me ha encargado que castigue a las
personas que desacatan al magisterio o al ministerio.`"
Con lo cual, James Parnell fue llevado de regreso a la prisión,
la cual estaba en las ruinas de un viejo castillo, construido, según se informa,
en la época de los antiguos romanos.^
footnote:[El Castillo de Colchester es un castillo normando,
construido en la segunda mitad del siglo XI. Hasta el día de hoy (enero 2020),
el castillo está en pie, y actualmente se usa para albergar el Museo Colchester,
con su gran colección de exhibiciones romanas.]
Ahí debía ser mantenido hasta que se pagara la multa,
y se le ordenó al carcelero que no dejara que ninguna "`persona
inestable`" (refiriéndose así a sus amigos) lo visitara.

El carcelero estaba muy dispuesto a cumplir con esta orden,
ya que no le permitía a nadie que lo visitara excepto los que abusaban de él. Su esposa,
que era una malvada arpía, no sólo hacía que su sirviente lo golpeara,
sino que ella misma varias veces lo golpeó violentamente con sus manos,
y juró que lo mataría. Ella también ordenó que otros prisioneros
le quitaran la comida que le llevaban sus amigos,
y que no lo dejaran usar la '`cama nido`' que le habían llevado para que se acostara;
de este modo era forzado a acostarse en las frías y húmedas piedras.
Después fue metido en un hueco en la pared,
un espacio que se parecía mucho al horno de un panadero,
pues las paredes de ese edificio eran excesivamente gruesas, como yo mismo he visto,
habiendo estado en el hueco donde este piadoso joven terminó sus días,
como será dicho luego.
Estando confinado en dicho hueco en la pared y siendo
la escalera 1,82 metros más corta (pues según recuerdo,
el hueco estaba a cerca de 3,65 metros del suelo),
él tenía que subir y bajar por una cuerda en la pared resquebrajada,
para recoger su comida, o por otras necesidades.
Porque aunque sus amigos querían darle una cuerda
y una canasta en la cual subir su comida,
tal era la maldad de sus custodios que no lo permitieron.

Al continuar en ese hueco húmedo, sus extremidades se fueron entumeciendo,
y en una ocasión,
mientras subía por la escalera con la comida en una
mano y había llegado a lo alto de la misma,
al tratar de alcanzar la cuerda con su mano libre, falló y cayó sobre las piedras,
y se hirió tan fuertemente la cabeza y su cuerpo quedó tan lastimado,
que se creyó que estaba muerto.
Entonces, lo pasaron a un hueco que estaba debajo del otro,
pues había dos hileras de huecos abovedados en la pared.
Este hueco era llamado '`el horno,`' y era tan pequeño
que el horno de cualquier panadero era más grande,
aunque no estaba tan alto del suelo.
Ahí apenas había aire, pues la puerta estaba cerrada y no tenía ventana,
ni siquiera un agujero.
Recuperado un poco de la caída, no le permitían salir a tomar aire fresco,
aunque estaba muy agotado por falta de aliento.
Y aunque algunos de sus amigos (a saber,
William Talcot y Edward Grant) le ofrecieron al juez
Henry Barrington pagar la fianza de cuarenta libras,
y otro (cuyo nombre era Thomas Shortland) ofreció
intercambiar cuerpo por cuerpo en lugar de Parnell,
para que él tuviera la libertad de ir a la casa de
W+++.+++ Talcot y regresar cuando se hubiera recuperado;
esto les fue negado.
De hecho, eran tan inflexibles con él,
que cuando se deseó que sólo caminara unas pocas veces en el patio de la prisión,
por ningún medio se lo concedieron.
Una vez, que estaba la puerta del hueco abierta,
salió y caminó un poco en un patio estrecho entre dos altos muros,
pero esto enfureció tanto al carcelero,
que cerró el agujero y lo dejó en el patio toda la noche,
siendo la época más fría del invierno.
Este duro encarcelamiento lo debilitó tanto,
que después de diez u once meses cayó enfermo y murió. En el momento
de su partida estaban con él Thomas Shortland y Ann Langley,
y fue uno de ellos (que a menudo lo había visitado),
quien mucho tiempo después me llevó al hueco donde él había muerto.

Muchas de las cosas relatadas aquí las obtuve de la boca de testigos presenciales,
quienes vivían en ese pueblo.
Cuando se aproximaba la muerte, Parnell dijo: "`Aquí muero en la inocencia.`"
Un poco después se le oyó decir:
"`Ahora debo irme;`" y volviendo su cabeza a Thomas le dijo: "`Debo morir esta muerte.
Thomas, he visto grandes cosas; no me retengas aquí, déjame ir.`"
Luego dijo de nuevo: "`¿Me retendrán?`" A lo que Ann respondió: "`No, querido,
no te retendremos.`"
Él a menudo había dicho que una hora de sueño lo curaría de todo;
y las últimas palabras que se le oyeron decir fueron: "`Me voy;`" luego se estiró,
durmió cerca de una hora y respiró por última vez.
Así, este valiente soldado del Cordero conquistó a través de los sufrimientos.
Pero fue tan grande la maldad y envidia de sus perseguidores,
que para encubrir la culpa y la vergüenza,
esparcieron entre la gente el rumor de que por excesivos ayunos y posteriores
glotonerías había acortado sus días. Pero esta era una mentira perversa,
pues aunque era cierto que unos días antes de su última enfermedad no había tenido apetito,
cuando empezó a comer de nuevo, no había tomado más que un poquito de leche,
tal como fue declarado por testigos fidedignos.
Durante su encarcelamiento,
Parnell les escribió varias edificantes epístolas a sus amigos.

Al continuar con el relato de Parnell sin interrumpirlo, avancé un poco en el tiempo,
pero ahora retrocediendo un poco,
veamos las acciones de Edward Burrough y Francis Howgill.
Ellos llegaron juntos a Irlanda en el verano del año 1655,
y se quedaron ahí más de seis meses.
Pasaron cerca de tres meses en Dublín sin ser molestados, si bien,
no dejaron pasar ninguna oportunidad para declarar la doctrina de la Verdad.
Henry Cromwell, hijo del protector, era en ese tiempo el '`diputado de Irlanda,`'^
footnote:[Gobernador en jefe de Irlanda, designado por la corona inglesa.]
y en nombre de él fueron devueltos de Cork (donde habían ido) a Dublín;
porque dado que varios habían recibido el testimonio de
ellos y se habían unido a la doctrina que predicaban,
se resolvió no dejarlos permanecer más tiempo en Irlanda.
Según se me dijo,
fue en este momento y por el ministerio de Burrough y Howgill
que William Ames entró en la sociedad de los llamados Cuáqueros.
Él era un maestro Bautista y un oficial militar, quien siendo de una vida estricta,
había mantenido a sus soldados bajo severa disciplina.
Recuerdo que solía decirnos,
que cuando un soldado bajo sus colores era encontrado
culpable de alguna inmoralidad un Primer-día,
al momento lo ataba del cuello y los talones.
Pero después de entrar en la sociedad de los despreciados Cuáqueros, y con el tiempo,
haberse convertido en un ministro entre ellos,
no pasó mucho antes de que fuera echado en prisión;
acerca de lo cual se dirá más en adelante.

Ahora bien,
Edward Burrough y Francis Howgill fueron desterrados de Irlanda,
pero el mismo día que fueran echados,
Barbara Blaugdone llegaba ahí. Ella había salido
de Inglaterra en un barco con destino a Cork,
pero debido al mal tiempo fue llevada a Dublín. Cuando la tempestad se hizo muy fuerte,
los marineros dijeron que ella era la causa de la tormenta por ser Cuáquera,
y conspiraron para lanzarla por la borda.
Consciente del plan, ella le dijo al capitán lo que sus hombres habían planeado hacer,
y añadió, que si él se los permitía, la sangre de ella le sería demandada de sus manos.
Entonces él les ordenó que no se metieran con ella.
La tormenta continuó, y siendo el Primer-día,
ella subió a la cubierta al sentirse movida a hablarles
a los marineros a modo de exhortación y orar por ellos;
porque el sacerdote de ellos (que estaba asustado
como el resto) no podía decir nada entre ellos.
Después de decir lo que estaba en ella, concluyó con una oración,
y toda la tripulación del barco se quedó muy quieta y sosegada,
diciendo que estaban más agradecidos con ella que con su propio sacerdote,
porque ella había orado por ellos, pero él, por temor,
no había podido abrir su boca para hablarles.
Finalmente, llegaron a Dublín a salvo y sin ningún daño, lo cual era realmente extraño,
e hizo que el capitán de la nave dijera que él nunca
había estado en una tormenta como esa,
sin haber tenido alguna pérdida.

Después de desembarcar fue a la casa del diputado,
pero la gente le dijo que no le permitirían hablar con él,
porque el día anterior había desterrado de la nación a dos amigos de ella.
Entonces se reunió con el secretario y le pidió que la ayudara a hablar con el diputado.
Él le respondió que no creía poder hacerlo.
Ella entonces le preguntó,
si sería tan amable de subir y decirle al diputado que abajo
había una mujer que deseaba hablar con él;
que si él se rehusaba, ella lo tomaría como respuesta.
El secretario subió,
y en poco tiempo un hombre llegó a buscarla y la llevó a una habitación privada,
y después de permanecer ahí un rato, salió un hombre de la cámara del diputado,
y todos los que lo acompañaban estaban sin sombrero,
porque ellos sabían que ella nunca había visto al diputado.
Pero ella discernió que ese hombre era un sacerdote,
y que había aparecido con el sombrero puesto para engañarla.
Cuando la habitación estuvo casi llena de gente,
le preguntaron por qué no le daba su mensaje a su señor. Pero ella respondió:
"`Cuando vea al señor de ustedes, entonces le daré mi mensaje a él.`"

Poco después de esto,
el diputado apareció y se sentó en un sofá. Entonces Barbara se puso de pie,
y hablándole lo que estaba en su mente,
le pidió que tuviera cuidado de no ser hallado peleando contra Dios,
oponiéndose a la Verdad y persiguiendo al inocente.
Y al igual que Gamaliel, le pidió que los dejara en paz, porque si eso era de Dios,
permanecería en pie, pero si era del hombre, caería. Además,
le dijo que la enemistad no residía tanto en él mismo,
sino que era incitado a ella por los magistrados y los sacerdotes malvados,
pero que el pueblo de Dios Le era tan querido hoy, como lo ha sido siempre,
y que el que lo tocaba, tocaba la niña de Sus ojos.
"`Pero hoy,`" dijo ella, "`en tu nombre y por tu poder,
se le ha hecho mucho daño al pueblo de Dios en toda la nación,
y esto pesará sobre ti al final.`"
También le dijo que los maestros de las personas las hacían errar,
y que él conocía la condición de los sacerdotes.
Al tocar ese tema, el diputado le dijo al sacerdote que estaba al lado:
"`¡Esto es para ti, Mr. Harrison!`"
Ella habló con tal poder que hizo que el diputado se sintiera muy inquieto,
y cuando terminó,
él le preguntó al sacerdote qué tenía que decir con respecto a lo que ella había hablado.
Él dijo que todo era muy cierto y muy bueno,
y que él no tenía nada que decir contra ello, si lo que ella había dicho,
era lo que verdaderamente había querido decir.
Entonces ella le dijo al sacerdote, que el Espíritu de Dios era la verdad,
y que siempre hablaba conforme a lo que quería decir,
y que lo que quería decir era verdadero.
Que los hombres de mentes corruptas pervertían las Escrituras
al poner sus propias imaginaciones y conceptos sobre ellas,
y así engañaban a las personas,
pero que los santos hombres de Dios habían escrito y dado las Escrituras
según habían sido inspirados por el Espíritu Santo,
y que por lo tanto, no eran de interpretación privada,
ni podían ser entendidas sino por el mismo Espíritu que las había dado.
Después de haber hablado así, se fue y regresó a la casa de un tal capitán Rich,
donde se alojaba.
Cuando el capitán llegó a la casa,
le contó que el diputado estaba tan triste y melancólico
después de que ella había hablado con él,
que no había podido ir a jugar a los bolos, ni hacer ningún otro pasatiempo.

Después de haber realizado su servicio en Dublín, Barbara se fue a Cork,
donde tenía algunos parientes y conocidos;
pero sus sufrimientos en esos lugares fueron grandes,
porque fue encarcelada en casi todos los lugares a los que fue,
pues había sido movida a acompañar a sus conocidos a varias
'`casas del campanario,`' a fin de declarar la verdad.
Sin embargo, dondequiera que su boca era abierta, ahí algunos recibían su testimonio.
Una vez, se sintió movida a hablar en un mercado,
donde un carnicero juró que le cortaría la cabeza,
y al levantar su cuchillo para hacerlo, una mujer se acercó por detrás,
le cogió los brazos y lo detuvo,
hasta que algunos soldados llegaron y rescataron a Barbara.
Muchos de sus familiares, a quienes ella conocía muy bien, le empezaron a temer,
porque algunas veces ella hablaba con tal poder en sus casas que los hacía temblar.
Algunos decían que ella era una bruja, y al alejarse corriendo,
hacían que los sirvientes la sacaran de la casa.

Después de un tiempo regresó a su casa en Bristol,
pero no había pasado mucho antes de que fuera movida a ir a Irlanda de nuevo;
y al llegar cerca de Dungarvon, el barco zozobró cerca de la orilla.
El capitán y los pasajeros subieron a un bote,
salvo un hombre y una mujer que fueron arrastrados, y Barbara,
que todavía estaba en el camarote,
por poco se ahoga por las olas que golpeaban contra ella; sin embargo,
al final pudo subir a la cubierta.
Mientras tanto, el capitán había llegado a la orilla,
y desde allí la llamó diciendo que si ella saltaba,
él y otro se aventurarían a entrar al agua para salvarla.
Acordado así, se metieron hasta el cuello y cuando ella saltó la cogieron;
pero al saltar quedó enredada en las cuerdas y fue alejada de ellos otra vez.
Sin embargo, en ese momento una ola envolvió y golpeó el barco hacia afuera,
lo cual resultó en la preservación de ellos,
porque si hubiera golpeado al barco hacia dentro, podría haber matado a los tres.
Pronto la cogieron de nuevo y la llevaron a la orilla.
De ahí Barbara se fue a Dublín, donde al entrar en la corte de justicia,
les habló a los jueces y los exhortó a la justicia.
Pero lo tomaron tan mal que fue puesta en prisión,
donde tenía que acostarse en el suelo sobre un poco de paja, y cuando llovía,
el excremento del retrete corría debajo de ella.
Como fue acusada en la corte, le exigieron que se declara "`culpable`" o "`no culpable.`"
Ella respondió que no había ninguna culpa en la consciencia de
nadie por lo que se había hecho en obediencia al Señor Dios.
Pero por no responder con las palabras específicas que le habían exigido,
la enviaron de regreso a prisión, donde sufrió mucho.
Entre tanto, sucedió un hecho extraordinario que no puedo pasar en silencio.

En ese tiempo estaban en prisión un posadero y su familia, acusados de asesinato.
Ahora bien, el hermano del que había sido asesinado o estaba perdido,
no podía heredar cierta tierra a menos que probara que su hermano estaba muerto,
y para eso, llevó a un tipo a la prisión,
quien dijo que él probaría que el hombre había sido
asesinado en tal posada y enterrado bajo una pared.
Así acusó al posadero y a su esposa, al criado y a la criada de ellos, y a un herrero,
de ser los culpables de dicho asesinato;
y estos ya estaban en prisión. Cuando Barbara oyó eso,
encontró los medios para ir donde ese hombre sin escrúpulos y le preguntó,
que cómo había podido ocultar por tanto tiempo ese asesinato, cuando según la ley,
él era tan culpable como cualquiera de ellos, si lo que decía era cierto.
Ante esta pregunta el hombre empezó a temblar tan fuertemente,
que le chocaban las rodillas, y confesó que nunca antes había visto a esas personas,
ni en su vida había estado en ese lugar, ni sabía nada del asunto,
sino que había sido llevado por el hombre que deseaba heredar la tierra,
y que lo había persuadido a actuar como testigo del asesinato.
Otros prisioneros oyeron también la confesión,
y Barbara le envió al diputado la petición,
de que enviara a su sacerdote para que oyera dicha confesión.
El sacerdote llegó y el hombre confesó ante él,
lo mismo que le había confesado a Barbara, y en una ocasión,
también confesó lo mismo ante el juez.
Pero después se comió sus palabras; pues el hombre que lo había inducido a testificar,
llegaba todos los días y lo hacía tomar copiosamente,
e hizo que el carcelero encerrara a Barbara para que ella no pudiera
acercarse a él. Entonces ella les escribió al posadero,
a su esposa y al criado, y también le escribió al juez Pepes,
diciéndole que se acercaba el día de su muerte en el que debía dar cuenta de sus actos,
y que por lo tanto, debía tener cuidado de no condenar a inocentes,
al tener sólo un testigo, en cuya boca se habían encontrado tantas mentiras,
y todos los otros decían que eran inocentes.
A pesar de todo eso,
el juez Pepes continuó y condenó a todos los acusados y al acusador también,
por estar consciente del crimen.
En eso llegó un sacerdote a hablar con la criada que había sido condenada,
que estaba en la misma cárcel de Barbara, pero ella no quiso verlo, aduciendo: "`No,
él no puede hacerme ningún bien, he terminado con el hombre para siempre; pero Dios,
Tú sabes que soy inocente de lo que me acusan.`"
Y así fueron ahorcados, el testigo primero,
probablemente por temor a que cambiara la confesión
después de que viera ahorcados a los otros.

Ahora, algunos amigos de Barbara, a saber, sir William King,
el coronel Fare y la señora Brown, oyendo que ella estaba en prisión, fueron a verla,
y después fueron al juez Pepes para pedirle que la dejara en libertad.
Pero cuando llegaron donde él, les dijo que él temía por su vida.
Ellos se rieron al oírlo y le dijeron que ellos conocían a Barbara desde niña,
y que no estaba en ella hacer daño. Y estando todos muy ansiosos por obtener su libertad,
al final la consiguieron.
Después Barbara fue a la '`casa del campanario`' donde estaba el juez,
y descargó su consciencia ante él; y el juez, al regresar a la casa,
se acostó y murió esa noche.
La noticia de su repentina muerte se esparció por todo lado,
e hizo que la gente dijera que Barbara había sido una verdadera profetisa para él.

Entonces se fue a Limerick, donde fue puesta en prisión, pero después de un tiempo,
al ser liberada, se embarcó de nuevo para Inglaterra.
En el mar fue robado todo lo que tenía por un pirata, quien, al subir a bordo,
se llevó al capitán de la nave hasta que le pagara
cierta suma de dinero por el barco y los bienes.
Sin embargo, ella llegó a salvo a Inglaterra,
viajando siempre por su cuenta y pagando lo que necesitaba.

Ahora la dejo y regreso a Miles Halhead, quien, al principio de este año,
mientras seguía el arado, se sintió movido a ir a Londres.
Pasando por York y Hull en su camino, y de ahí a través de Lincolnshire y Leicestershire,
llegó a la ciudad de Londres, de la que después de una estancia,
se fue a Bristol con Thomas Salthouse, y así a Exeter y Plymouth,
donde sufrió mucha persecución y fue encarcelado cerca de
un año. En ese tiempo le escribió una carta a su esposa,
que creo que vale la pena insertar aquí. Y es como sigue:

[.embedded-content-document.letter]
--

[.salutation]
Anne Halhead,

Mi querido corazón; mi tierno amor en el Señor Jesucristo te saluda a ti y a mis hijos.
Mi alma, mi alma se derrama en amor hacia ustedes todos los días,
y el aliento de mi alma ante mi Padre es por ustedes,
para que se mantengan en el temor del Señor y en Su consejo diariamente,
y que así puedan llegar al reposo y a la paz que están guardados
para todos los que Le temen y caminan en obediencia a la luz,
con la que Jesucristo los ha alumbrado.
Así, pues, mi querido corazón, te declaro en la presencia del Dios vivo,
que es Señor del cielo y de la tierra, y ante los hombres y los ángeles,
que no hay otro camino que lleve a la paz y al reposo eterno,
sino el camino de la obediencia a la luz que viene de Jesucristo; y de esa luz,
tú has recibido una medida.
Por tanto, mi querido corazón, sé fiel al Señor en lo que te es dado a conocer,
para que puedas llegar a experimentar la verdadera paz y el verdadero reposo,
porque '`lo que ojo no ha visto, ni oído ha oído, ni ha subido en corazón de hombre,
es lo que está guardado para los que Le temen.`'

Mi querido corazón,
habiendo encontrado paz y reposo eterno para mi alma de parte del Señor,
soy movido por el Señor en amor a tu alma,
a mostrarte el camino que conduce a la paz y al reposo eterno; el camino que es Cristo,
quien es la luz y el camino que lleva al Padre, de quien viene toda la luz.
De esa luz que viene de Cristo, doy testimonio que tú has recibido una medida.
Por tanto, en el querido amor, te exhorto a caminar en obediencia a tu medida,
la cual has recibido del Señor. Y en la presencia del Señor Dios te declaro,
que caminar en obediencia a dicha luz que viene de Cristo,
es el camino que conduce al reposo y a la paz eternos.
Así, pues, conforme te ocupas del bien eterno de tu alma,
sé fiel a la luz que viene de Cristo, la cual da testimonio contra la mentira,
el juramento, el hablar vanamente y toda clase de maldad.
Mi querida esposa, en querido amor por tu alma,
la cual es más preciosa que todo el mundo, te he mostrado el camino.
Si caminas en él, él te conducirá al pacto eterno de vida y paz.
Así, mi querida esposa, en amor, en el amor y en la presencia del Dios vivo,
he descargado mi consciencia ante ti, como un verdadero y fiel esposo para ti,
deseando tu bien y bienestar eterno como los míos propios; el Señor Dios es mi testigo.

Querida, recuérdales mi querido amor a todos mis amigos y compatriotas según la carne;
porque a todos ustedes les deseo bien y bienestar eterno,
y que todos lleguen a creer en la luz en sus propias consciencias,
con la que Jesucristo los ha alumbrado; la luz que da testimonio contra la mentira,
el juramento y toda clase de maldad.
Esta es la luz de Cristo, y caminar en obediencia a dicha luz,
es el camino que saca del pecado y del mal,
y lleva al eterno y bendito para siempre Dios.
El que actúa contrario a esa luz en su propia consciencia, se condena.
Entonces, queridos amigos, mientras tengan tiempo, valórenlo.

[.signed-section-closing]
Tu esposo y un amante de tu alma,

[.signed-section-signature]
Miles Halhead

[.signed-section-context-close]
Wiltshire, 7 del Tercer mes de 1655.

--

Este año también escribió la siguiente epístola a sus compañeros creyentes.

[.embedded-content-document.epistle]
--

Queridos y amados amigos y hermanos del norte, y también del sur de Inglaterra,
la tierra de nuestro nacimiento,
a quienes el Señor Dios del cielo y la tierra ha
llamado y escogido en el día de Su amor eterno,
para que Le sirvan en la verdad y la justicia,
y han recibido la Verdad del Señor en el amor de esta,
para que no sólo crean en Su nombre, sino que también sufran cadenas,
prisiones y duras sentencias por la Palabra de Dios y el testimonio de Jesús.

Queridos amigos y amados hermanos, mis oraciones al Señor Dios del cielo y de la tierra,
y el deseo de mi alma, es que todos habiten juntos como hijos de un solo Padre,
en el vínculo eterno de amor y unidad del Espíritu;
que todos crezcan en la eterna y viva Verdad de Dios,
y sean colocados sobre la roca y fundamento seguro;
que las puertas del infierno y de la muerte no prevalezcan contra ustedes;
que todos sean guardados y preservados en paz y reposo
bajo la sombra de las alas del Todopoderoso,
ahora en el día de la prueba y en la hora de oscuridad,
cuando el infierno ha abierto su boca y la furia del mar ha echado sus orgullosas olas,
hasta inundar las costas.

¡Gloria, gloria,
y eternas y vivas alabanzas sean dadas para siempre
al Señor Dios de todos los hijos de la luz,
y al Cordero, quien ha encontrado un lugar de reposo al que pueden huir todos Sus amados,
Sus corderos, bebés e hijos de la luz, en el tiempo de angustia y necesidad;
en el que nadie puede atemorizarlos, ni quitarles su paz,
mientras permanecen fieles Al que es nuestro camino, nuestra luz, nuestra vida,
nuestra fuerza, y eterna porción para siempre!

Mis queridos amigos y hermanos, les suplico en querido y tierno amor,
que caminen como hijos amados, fieles Al que los ha llamado con un llamamiento digno,
y los ha amado desde el principio con amor eterno, para que todos sus amigos,
vecinos y los hombres del mundo que ven sus vidas unidas al temor,
confiesen y reconozcan, para el honor y la gloria del Señor vivo,
que el Dios a quien sirven y temen es el único Dios verdadero de Israel.
Aquí se convierten en olor fragante para el vivo y eterno Dios,
y en dulce y fragante olor para todos los hijos de la luz;
y el Señor Dios no les negará ninguna cosa buena.
La boca del Señor Dios de los Espíritus lo ha dicho,
cuyas promesas son sí y amén para Su propia semilla por siempre.

[.signed-section-signature]
Miles Halhead

Entregado el 14 del Sexto mes de 1655,
cuando estaba encarcelado en la prisión de la ciudad de Exeter, en Devonshire,
por el testimonio de Jesús y la palabra de Dios.

--

La razón principal por la que él estaba encarcelado ahí era, porque Thomas Salthouse,
con quien Miles viajaba,
le había preguntado a George Brooks (un sacerdote que pertenecía a la fragata Nightingale,
quien había dicho muchas palabras buenas a favor de la doctrina de los Cuáqueros),
si él vivía la vida de la que hablaba.
Y había agregado: "`El que no entra por la puerta, sino que sube por otra parte,
es ladrón y salteador (como dijo Cristo).`"
Pues Thomas creía (y no sin buena razón,
como será mostrado luego) que las alabanzas de este sacerdote no eran
mejor que las de la esclava poseída por un espíritu de adivinación,
que había dicho con respecto a Pablo y a Silas:
"`Estos hombres son siervos del Dios Altísimo,
quienes os anuncian el camino de salvación.`"^
footnote:[Hechos 16:16-17]

Ahora bien, lo que Thomas Salthouse le dijo al sacerdote, fue llamado lenguaje ofensivo,
más aún, porque cuando el sacerdote estaba hablando de la trinidad,
Thomas le preguntó que dónde se hallaba esa palabra en las Escrituras.
Y dijo:
"`No conozco ninguna Escritura que hable de las tres '`personas`' de la '`trinidad`';
pero los tres de los que hablan las Escrituras son el Padre, el Hijo y el Espíritu Santo,
y estos tres son uno.`"^
footnote:[Los primeros Amigos no negaban a los "`Tres que
son Uno,`" como algunos han afirmado equivocadamente.
Sólo objetaban conscientemente,
el uso de nombres no bíblicos para la Deidad (como
"`tres personas individuales`" o "`trinidad`"),
sintiéndose más cómodos apegándose al lenguaje de las Escrituras,
cuando hablaban de misterios tan celestiales e importantes.]
De ahí,
que Thomas Salthouse y Miles Halhead fueran acusados de negar a los "`Tres que son Uno.`"
Pero como sus perseguidores fueron incapaces de probar esa acusación en la corte,
pensaron en algo más para atraparlos; a saber,
se les pidió que tomaran el juramento de repudio al Papa.
El alcalde de Plymouth ya les había pedido ese juramento,
la primera vez que fueron detenidos, y como se negaron a jurar,
los enviaron a la prisión de Exeter.
Y ahora, al ser llevados a juicio, cuando se les pidió dicho juramento,
respondieron de esta manera:

"`En la presencia del eterno Dios y ante todo este pueblo, negamos,
con tanto aborrecimiento como cualquiera de ustedes, al Papa,
su supremacía y la doctrina del purgatorio;
y de todo lo que está mencionado en dicho juramento,
nos declaramos voluntariamente en contra.
No nos negamos a jurar por alguna culpa que esté sobre nosotros,
sino en obediencia al mandamiento de Cristo que dice:
'`No juréis en ninguna manera.`' Y no caeremos bajo la condenación de un juramento,
por la libertad del hombre exterior.`"

Y así, al negarse a jurar,
simplemente para no ofender el mandamiento de nuestro Salvador,
fueron enviados de regreso a prisión,
como hombres que clandestinamente se habían unido al Papa.
Esta misma trampa ha sido usada durante muchos años,
con el fin de perseguir a los llamados Cuáqueros.
Al día siguiente los prisioneros fueron llevados de nuevo ante el tribunal,
y les preguntaron:
"`¿Confesarán que agraviaron a George Brooks cuando lo llamaron ladrón;
se arrepentirán de eso y le darán satisfacción?`" Miles Halhead respondió:
"`Uno de nosotros no le dijo una palabra a él; por tanto,
me niego a darle satisfacción o arrepentirme por algo que no dije.
Y lo que se dijo +++[+++por Thomas Salthouse], no es como ustedes lo dicen; por tanto,
no mentiremos para ganar nuestra libertad,
ni confesaremos que nos arrepentimos de lo que nunca dijimos.`"

Entonces la corte los multó con cinco libras a cada uno,
y fueron enviados a la casa de corrección hasta que pagaran
y encontraran garantías del buen comportamiento de ellos.
Y por negarse a prestar el juramento,
la corte los amenazó con enviar al norte la orden de que confiscaran sus bienes.
Así, pues, fueron regresados a prisión,
y lo que sigue fue lo que se registró en el reporte oficial de dichas medidas:

[.embedded-content-document.legal]
--

[.signed-section-context-open]
10 de julio de 1655.

Thomas Salthouse y Miles Halhead, por palabras ofensivas contra George Brooks, clérigo,
quienes se negaron a ser juzgados por el condado, multados con 5 libras por persona,
encerrados en Bridewell hasta el pago y se encuentren garantías de su buen comportamiento.`"

--

Lo que se dice aquí de su negativa a ser juzgados por el condado, es una notoria falsedad.
En cuanto a encontrar garantías,^
footnote:[Una suma de dinero pagada por la persona
imputada o por alguna otra parte interesada,
garantizando el buen comportamiento del acusado hasta su
comparecencia en las siguientes sesiones de la corte,
o algún otro período de tiempo establecido.
Similar a la fianza.]
eso parecía de poca importancia, porque aunque la garantía se había ofrecido antes,
cuando habían sido tomados prisioneros (por dos amigos
llamados Robert Cary y Arthur Cotton),
no se aceptó. Por su parte,
el alcalde John Page tuvo la osadía de afirmar que ellos se habían rehusado a dar garantías,
como aparecerá en la orden de la corte por la que
fueron enviados a la cárcel común en Exeter,
de la que a continuación se ofrece una copia fiel:

[.embedded-content-document.legal]
--

[.salutation]
Condado de Devon,

John Page, comerciante, alcalde del distrito de Plymouth, en el condado mencionado,
y uno de los jueces de paz de su alteza en dicho distrito,
al guarda de la cárcel de su alteza en el castillo de Exon,
o a su legítimo representante en esa parte, saludos.

Le envío junto con el portador de esta orden, a Thomas Salthouse,
última residencia en Dragglibeck, en el condado de Lancaster, granjero; y Miles Halhead,
última residencia en Kendal, en el condado de Westmoreland;
recientemente detenidos aquí como perturbadores de la paz pública,
y por varios otros delitos graves,
contra la reciente proclama que prohíbe molestar a los ministros
y a otros cristianos en sus asambleas y reuniones,
y contra la orden de su alteza el señor protector y su consejo recientemente emitida,
contra duelos,
desafíos y toda provocación. Estos se han negado a dar suficiente garantía de
su comparecencia personal a las siguientes sesiones generales de la paz,
que se celebrarán en el condado de Devon, y mientras tanto,
de tener buen comportamiento para con su alteza el señor protector y todo su leal pueblo.
Por tanto, esta orden se emite en nombre de su alteza,
para ordenarte que cuando los mencionados Thomas Salthouse
y Miles Halhead sean llevados delante de ti,
los detengas y encierres hasta que por el debido proceso de la ley,
sean liberados de ahí. Por esto, no falles en tu responsabilidad.
Entregado bajo mi mano y sello, en Plymouth, el día 28 de mayo,
del año de nuestro Señor Dios, 1655.

[.signed-section-signature]
John Page, alcalde.

--

Por medio de esto se puede ver,
bajo que frívolos pretextos era encarcelado el pueblo llamado Cuáqueros; es decir,
por una ordenanza hecha contra los duelos, etc.
Y en cuanto a que se negaron a dar garantía, la falsedad de esto,
así como de otras acusaciones, aparece en el siguiente certificado:

[.embedded-content-document.legal]
--

Nosotros, cuyos nombres están aquí suscritos testificamos,
que los varios detalles en la respuesta dada por nuestros amigos, son verdaderos;
que ellos no perturbaron en ninguna forma la paz pública,
ni estuvieron en ninguna otra reunión (aparte de la señalada
por nosotros) para molestar a ningún ministro,
ni a otros Cristianos en sus asambleas y reuniones;
que mientras estuvieron entre nosotros, no fueron culpables de ningún desafío,
duelo o provocación en lo más mínimo.
En cuanto a su negativa a dar garantía, dos de nosotros,
cuyos nombres son Robert Cary y Arthur Cotton,
el día anterior a que fueran enviados a prisión le dieron garantía al alcalde,
contrayendo la obligación de la comparecencia de ellos en las siguientes sesiones,
pero el secretario del pueblo la anudó al día siguiente,
pretendiendo que no podía ser según la ley.

[.signed-section-signature]
Ralph Fogg, Thomas Faulkener, Arthur Cotton, Nicholas Cole, Robert Cary, John Martindale,
Richard Smith, Richard Lepincote, Anthony Todde, John Harris padre y John Harris hijo.

--

Ahora bien, a qué altura había llegado la confianza del mencionado alcalde Page,
al decir que Thomas Salthouse y Miles Halhead habían rechazado dar garantía,
y no sólo eso, sino que esa era la causa de su confinamiento,
también se muestra en la siguiente carta que le escribió al general Desborough,
para excusar su proceder contra él.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Plymouth, 1 de junio, 1655

[.salutation]
Muy honorable general Desborough,

El capitán Hatsell me ha comunicado lo que usted
le escribió en referencia a esos dos hombres,
Thomas Salthouse y Miles Halhead, de quienes y de cuyos encarcelamientos,
su señoría había oído algo de algunas personas de este lugar,
y recibido la copia de una carta que ellos me enviaron.
Por medio de las copias adjuntas de sus interrogatorios,
su señoría verá parte de la causa de su encarcelamiento,
la cual fue su negativa a dar garantía de su comparecencia a las siguientes
sesiones generales que se celebrarán en el condado de Devon;
siendo ellos, como yo concibo,
transgresores de la reciente ordenanza de su alteza el señor protector y su consejo,
emitida contra los duelos, desafíos y toda provocación,
y de la última proclama de su alteza contra los Cuáqueros;
y como todavía se negaban a dar garantía de su comparecencia como se dijo antes,
el pasado martes fueron llevados de aquí a la cárcel de Exon.

En efecto, señor, la postura de ellos no era apropiada en hombres,
mucho menos en Cristianos;
además de su desprecio a la autoridad durante el tiempo que estuvieron en prisión,
nunca buscaron a Dios por medio de la oración,
ni desearon una bendición sobre las provisiones que recibieron,
o dieron gracias por ellas.
Hace unos dos meses, estos mismos hombres fueron apresados por el coronel Cupplestone,
principal alguacil de nuestro condado,
y después del día catorce de detención fueron enviados por él a Taunton,
por no haber demostrado ninguna razón por la que habían venido a estas partes.
Ellos son Cuáqueros de profesión religiosa,
pero granjeros por vocación. Uno de ellos es de Lancashire, el otro de Westmoreland.
Hace unos tres meses dejaron a sus familias, parientes y vocaciones, según dicen ellos,
y no trabajan, ni se emplean en sus vocaciones para procurarse un medio de vida,
sino que deambulan de un lado a otro,
declarando sus perversas opiniones y manifestando sus prácticas irregulares,
violando la paz y perturbando a las buenas personas.
De hecho, señor, sostienen muchas opiniones tristes,
destructivas para la verdadera religión y el poder de la piedad.

Por medio de la presente, según mi deber,
le he dado a su señoría un informe de lo que pasó aquí con relación a esos hombres.
Podría decir mucho más con respecto al interrogatorio y conversación con ellos,
pero me temo haber abusado ya de la paciencia de
su señoría con la lectura de estas líneas,
y humildemente deseo su excusa por haberle dado este problema.
Reconozco con gratitud sus continuos favores para con este lugar,
por los que estamos muy agradecidos.
Deseo que su señoría mantenga su opinión de nosotros,
como personas que no deseamos hacer algo impropio como Cristianos,
y como personas que desean el bienestar y la paz de esta mancomunidad y gobierno,
y que yo siempre trataré de mostrarme como,

El más humilde siervo de su señoría, (por mí y mis hermanos),

[.signed-section-signature]
John Page, alcalde.

--

Es probable que el general Desborough haya quedado insatisfecho con esta carta, porque,
investigando el asunto, dejó que otros tuvieran una copia de dicha carta,
de modo que Thomas y Miles escribieron una respuesta.
Un tiempo después, Giles Calvert la distribuyó públicamente en forma impresa en Londres,
junto con otros escritos relacionados con esta.
Ahora bien,
en cuanto a lo que se dice en la carta sobre la proclama de su alteza contra los Cuáqueros,
fue una burda mentira, porque en dicha proclama los Cuáqueros no fueron mencionados;
la proclama era contra toda perturbación a los Cristianos en sus asambleas.
Además,
los llamados Cuáqueros juzgaban que el artículo 37 de la
legislación del gobierno les permitía su adoración pública,
el cual decía, que todo el que profesara fe en Dios por medio de Jesucristo,
no sería impedido de, sino protegido en,
la profesión de la fe y el ejercicio de su religión,`" etc.

En cuanto al desprecio a la autoridad que el alcalde les imputaba, no era más que,
por un asunto de consciencia, ellos no podían quitarse el sombrero ante los magistrados,
ni darle dicho honor a ningún otro hombre, sino sólo a Dios.
Y en cuanto a lo que se dijo,
de que todo el tiempo que habían estado en prisión nunca habían buscado a Dios en oración,
etc., no era más que el hecho de que ellos no seguían la manera formal de orar,
pues ellos realmente eran hombres religiosos,
que a menudo oraban a Dios y Le daban gracias.
Y aunque en la carta fueron presentados como hombres muy perversos y vagabundos,
que habían dejado su vocación y deambulaban de un lado a otro por el condado,
era bien sabido que eran hombres honestos, que viajaban a caballo,
que se quedaban en las posadas más respetables y que pagaban
por cualquier cosa que recibieran ahí. Por tanto,
después de que recibieron una copia de la mencionada carta,
le escribieron al alcalde John Page una larga carta,
mostrándole sus abominables falsedades,
y diciéndole que ellos habían sido movidos varias veces,
tanto en prisión como fuera de la prisión,
a orar y dar gracias por las bendiciones de Dios
que recibían. Y en la conclusión de la carta indicaron,
que no deseaban regresar maldición por maldición, "`sino,`" dijeron,
"`en el espíritu de amor y mansedumbre exhortar a todos
al arrepentimiento y al temor de ofender al Señor.`"

Ahora,
con respecto a las palabras ofensivas de Thomas Salthouse
contra el sacerdote George Brooks,
por las que ellos habían sido multados, ya se ha dicho lo que fueron.
Sin embargo, este Brooks tenía una vida libertina y era un tipo degenerado,
quien por sus borracheras no sólo había sido expulsado de
los barcos de la marina en los que había servido como sacerdote,
sino que también, en una ocasión en el barco Nightingale,
fue vergonzosamente expuesto con un "`quarter can`"^
footnote:[El editor de esta historia no ha podido determinar el significado del término
"`quarter can,`" pero cree que era algún tipo de marca distintiva o estigmatización,
colocada sobre el culpable de cierto tipo de conducta, en este caso,
la embriaguez pública.]
alrededor de su cuello, tal como aparece en los siguientes testimonios:

[.embedded-content-document]
--

Anteriormente se me solicitó que explicara la razón por la que el señor George Brooks,
capellán de la fragata bajo mi mando, había sido puesto en tierra.
Primero, porque era un hombre entrometido y perturbaba a toda la tripulación del barco.
Segundo,
porque cuando bajaba a tierra su práctica común era abusar de la creación de Dios,
de manera tal, que terminaba ebrio y fuera de sí. De hecho,
él abusaba de todos los que estaban en su compañía con lenguaje ofensivo,
además del maltrato a sí mismo y a la buena creación,
y todos los días me llegaban quejas sobre él, tanto de abordo como de tierra.
Por tanto, sabiendo que es un tipo libertino y no apto para el empleo, lo puse en tierra,
y lo admitiré ante cualquiera que me llame para interrogarme.
Certifico con mi firma,

[.signed-section-signature]
Robert Vessay.

--

[.embedded-content-document]
--

El señor Brooks estuvo anteriormente conmigo en el Nightingale,
y encontré que era muy holgazán y que estaba continuamente borracho,
lo cual hizo que yo en una ocasión le pusiera un "`quarter can`" alrededor de su cuello;
lo cual suscribe,

[.signed-section-signature]
John Jeffery, Capitán del Nantwich.

--

[.embedded-content-document]
--

La persona arriba mencionada la he visto borracha en tierra;
en testimonio de lo cual he puesto mi mano,

[.signed-section-signature]
Richard Potter, Capitán de la fragata Constant Warwick.

--

De evidencias como estas, parece que no faltaba razón de que él y los sacerdotes como él,
fueran algunas veces tratados sin rodeos.
Pero regreso a M. Halhead;
él continuó prisionero muchos meses antes de que fuera liberado.

Mientras tanto, sucedió que George Whitehead, Richard Clayton y John Harwood,
al llegar el 30 del mes llamado julio a Bures, en Suffolk, fueron encarcelados.
Richard Clayton había pegado un papel en la puerta de la '`casa
del campanario,`' que contenía las siguientes preguntas:

[.embedded-content-document.paper]
--

¿Es correcto establecer a tales ministros,
a los que '`buscan su propio provecho;`' como lo desaprueba el profeta Isaías,
en Isaías 56:11, y como lo desaprueba el profeta Jeremías, en Jeremías 5,
y de quienes también se hace mención en Ezequiel 34 y Miqueas 3;
a los ministros que son llamados por los hombres '`maestros,
y que aman los principales lugares en las asambleas,`'
como lo desaprueba Cristo en Mateo 23,
y lo desaprueba el apóstol Pedro, en 2 Pedro 2,
y también lo desaprueba el apóstol Pablo en Filipenses 3? Cuando
aquellos que están establecidos no le '`permiten a otro que está
sentado hablar cuando algo le es revelado,`' 1 Corintios 14:30,
sino que en su lugar lo envían a prisión,
¿acaso no es esto el establecimiento de un espíritu de persecución,
que limita al Espíritu de Dios y '`menosprecia la profecía,`'^
footnote:[1 Tesalonicenses 5:20]
y no se atreve a '`examinar todas las cosas`'?^
footnote:[1 Tesalonicenses 5:21]
¿Es correcto pedirles a los que se burlan, escarnecen, se emborrachan, juran y persiguen,
que canten las condiciones de David mencionadas en los Salmos?
Y si ahora se establecen hombres que toman diezmos,
a pesar de que el apóstol ha dicho que '`el sacerdocio
ha cambiado y la ley también,`' Hebreos 7:13,
¿acaso no es este el establecimiento de hombres que no trabajan en la viña del Señor?

--

La gente llegó a leer el papel que había sido puesto.
George Whitehead, que estaba ahí,
aprovechó la oportunidad y les dijo unas pocas palabras a las personas,
y las exhortó a volverse de las vanidades y maldades en las que vivían,
al Señor. Y cuando G. Whitehead y sus compañeros de viaje se estaban yendo,
llegó un alguacil, los detuvo y los llevó delante de Herbert Pelham, un juez de paz.
Este juez les hizo varias preguntas vanas y se comportó rudamente,
y Whitehead le empezó a hablar acerca de su furia,
pero Pelham dijo que no lo había mandado a llamar para que predicara.
Y como no pudo acusarlos de la transgresión de ninguna ley,
los envió al alguacil Thomas Walgrave, juez de paz de Smallbridge, en Suffolk.

Cuando llegaron a la casa del juez,
Richard Clayton fue el primero en ser interrogado con respecto a su nombre y condado,
y dónde había estado.
Las mismas y otras frívolas preguntas le fueron hechas a George Whitehead.
Tras llegar el juez Pelham, ambos jueces consultaron entre sí qué hacer en ese caso,
y no mucho después Thomas Walgrave le preguntó a G. Whitehead,
si él trabajaría en los campos de heno.
Pero George se negó a estar sujeto a tales capataces,
pues ya estaba sujeto al llamado que Dios le había designado,
y en el que siempre había cubierto sus propios gastos.
La conclusión del interrogatorio que les hicieron fue, que Richard Clayton fuera azotado,
bajo el pretexto de haber pegado un "`papel sedicioso`" en la puerta de la '`casa
del campanario;`' y que George Whitehead y John Harwood fueran encarcelados.

Fue por este tiempo que William Dewsbury y varios otros de sus amigos,
fueron puestos en la prisión de Northampton.
Pues sucedió, que cuando él estaba caminando por las calles de Wellingborough,
el sacerdote Thomas Andrews lo llamó con estas palabras: "`¡Deja de engañar al pueblo,
no sea que las plagas de Dios caigan sobre ti!`"
A esto Dewsbury respondió: "`¿Dices que yo engaño al pueblo?
Pon de manifiesto en qué lo he engañado.`"
Entonces Andrews dijo: "`Tú dices que no hay pecado original.`"
A esto Dewsbury replicó: "`¿Tú me oíste decir eso?`"
Pero el sacerdote, no queriendo responder la pregunta, se fue.
Después Dewsbury entró a la '`casa del campanario`' en dicho pueblo,
y después que terminó el sermón,
le demandó al sacerdote que probara delante de la
gente la acusación que le había hecho públicamente,
a saber, que él había dicho que no había pecado original.
Sin embargo, el sacerdote no quiso responder, sino que se fue.
También se informó que Dewsbury había dicho:
"`Los sacerdotes predican por un sueldo y el pueblo así lo quiere,
pero ¿qué harán al final?`"
Sin embardo, no encuentro que esto haya sido realmente así.

Dewsbury, después de ser enviado a prisión y mantenido ahí por más de medio año,
fue finalmente llevado a su juicio en Northampton, con varios otros prisioneros;
sus amigos.
Y al ser llevados al estrado, el juez Atkins le dijo al carcelero:
"`¿Sueles presentar a los prisioneros en la corte de esta manera?
¡Mereces ser multado con diez libras por traerlos
delante de la corte con sus cabezas cubiertas!`"
El carcelero respondió: "`Si me lo ordenas, les quitaré sus sombreros.`"
El juez dio la orden y el criado del carcelero se
los quitó. Luego el juez le dijo a Dewsbury:
"`¿Para qué estás aquí?`" Dewsbury respondió:
"`La orden de la corte expresará el motivo por el cual fui encerrado,
pero el guarda de la cárcel me negó una copia de la misma.`"

La siguiente pregunta del juez fue: "`¿Cuál es tu nombre?`"
Y la respuesta fue: "`Desconocido para el mundo.`"
"`Déjanos escuchar,`" dijo el juez, "`qué nombre es ese que el mundo no conoce.`"
"`Es,`" dijo Dewsbury, "`conocido en la luz,
y nadie puede conocerlo sino aquel que la tiene;
pero el nombre por el que el mundo me conoce es William Dewsbury.`"
Luego el juez le dijo: "`¿De qué condado eres?`"
Dewsbury respondió: "`De la tierra de Canaán.`" "`Esa está muy lejos,`" replicó el juez.
"`No,`" dijo Dewsbury, "`pues todos los que moran en Dios están en la ciudad santa,
la Nueva Jerusalén, la que desciende del cielo,
donde el alma reposa y disfruta del amor de Dios en Jesucristo,
en quien está la unión con el Padre de luz.`"
A esto el juez contestó: "`Eso es cierto; pero ¿estás tú avergonzado de tu condado?
¿Es denigrante para ti haber nacido en Inglaterra?`"
"`No,`" dijo Dewsbury,
"`soy libre de declarar que mi nacimiento natural fue en Yorkshire,
a nueve millas de York, hacia Hull.`"
Entonces el juez dijo:
"`Ustedes pretenden ser hombres extraordinarios y
tener un extraordinario conocimiento de Dios.`"
A lo que Dewsbury respondió:
"`Nosotros testificamos que la obra de regeneración es una obra extraordinaria,
producida en nosotros por el Espíritu de Dios.`"
"`Pero,`" dijo el juez,
"`los apóstoles trabajaron con sus propias manos en sus vocaciones.`"
"`Ellos tenían,`" respondió Dewsbury, "`vocaciones en el mundo, algunos eran pescadores,
Pablo hacía tiendas; pero cuando fueron llamados al ministerio de Cristo,
dejaron sus oficios para seguir a Cristo,
adonde Él los condujera por medio de Su Espíritu a predicar la palabra.
Y yo también tenía una vocación en el mundo como tenían ellos,
y en esa permanecí hasta que el Padre reveló a Su Hijo en mí,
y me llamó del oficio que yo tenía en el mundo a predicar la Palabra eterna,
la cual Él me ha dado a conocer en la gran obra de regeneración.`"

El juez preguntó:
"`¿Por qué no te quedaste en tu propio condado y
les enseñaste a las personas en esos lugares?`"
"`Ahí me quedé,`" contestó Dewsbury,
"`hasta que fui llamado de ahí a ir adonde me dirigiera el Espíritu del Señor;
porque todos los que son guiados por el Espíritu de Dios, son hijos e hijas de Dios,
y los que no tienen el Espíritu de Cristo, no son de Él.`" A esto el juez dijo:
"`Dices bien; pues debemos concluir en amor,
que todos en este lugar tienen al Espíritu de Dios en ellos.
Pero ¿cómo sabes que eres guiado por el Espíritu de Dios?`"
"`Los que tienen el Espíritu de Dios,`" replicó Dewsbury, "`son conocidos por sus frutos.
El que cree en Jesucristo y es guiado por Su Espíritu, tiene el testimonio en sí mismo.`"
"`Eso es cierto`" dijo el juez, "`no obstante,
veo por tu conducta que lo que hizo mi hermano Hale en la última sesión de la corte,
al requerir fianza por el buen comportamiento de ustedes, podía hacerlo con justicia;
porque ustedes están en contra de los magistrados y ministros.`"
Pero Dewsbury contestó: "`Pon de manifiesto en qué estamos en contra de ellos.`"

Entonces el juez le dijo al secretario: "`Robert Guy,
qué tienes en contra de estos hombres?`"
Entonces él hizo un relato de lo que Dewsbury le había dicho al sacerdote Andrews en
la '`casa del campanario.`' Luego Dewsbury hizo un relato del asunto en cuestión,
de cómo habían sucedido las cosas, y de que no se había violado ninguna ley de la nación;
entonces el juez reanudó: "`Pero al ser encontrados deambulando en el condado,
violan la ley; porque hay una antigua ley que dice,
que si alguno sale de su lugar de residencia para
viajar en el país sin la certificación de algún juez,
debe ser tomado como vagabundo.`"
A esto Dewsbury dijo: "`Si existe una ley así, léenosla.
Pero, si tal ley existe, sabes en tu consciencia que es contraria a las Escrituras,
porque los apóstoles y ministros de Cristo iban y venían por el país,
predicando la Palabra de vida eterna,
y cada día eran añadidos a la iglesia los que habían de ser salvos;
y el número de los santos y hermanos se incrementaba diariamente.
La ley que está en vigor ahora en esta nación,
permite que todo el que profesa fe en Jesucristo tenga libertad
de caminar en la fe que es según las Escrituras.`"
A esto el juez dijo: "`Tienes una lengua elocuente y estás orgulloso de ella.`"
"`Niego el orgullo,`" replicó Dewsbury, "`pero testifico la Verdad,
la que juzgará todo orgullo y atormentará a todo el que vive en él,
hasta que sea destruido.`"
Entonces el juez les habló a los otros prisioneros, y aunque se comportó con moderación,
no pudo resolver ponerlos en libertad.
Por tanto, continuaron en prisión,
aunque ya habían sido prisioneros por más de veintinueve semanas.

Uno de los prisioneros era John Huchin,
a quien sólo podían acusar de haber entrado a la '`casa del campanario`' en Wellingborough,
y quedarse pacíficamente en silencio.
Sin embargo, antes de que terminara la mitad del sermón,
el sacerdote Andrews ordenó que se lo llevaran.
Esto lo hizo el guarda de la iglesia, Henry Hensnan, y se lo llevó a una cervecería,
donde el alguacil le dijo que si prometía no volver a la iglesia por la tarde,
sería liberado.
Pero al negarse a hacer tal promesa, aunque en ese momento lo dejaron en paz,
unos días después un alguacil llegó a la tienda de su amo donde estaba trabajando,
y se lo llevó sin mostrarle una orden judicial.

Otro de los prisioneros era Michael Pattison,
quien había estado en la misma '`casa del campanario`'
y se había mantenido pacíficamente en silencio.
Entonces, cuando el sacerdote Andrews terminó y la gente se había ido, le dijo: "`Amigo,
¿puedes atestiguar que lo que has hablado aquí delante de la gente
es la palabra del Señor?`" Pero esto ofendió tanto al sacerdote,
que les ordenó a los oficiales que se llevaran a Michael,
y el alguacil John Brown lo hizo.

Thomas Goodyear era también uno de los prisioneros.
Cuando llegó a Northampton para visitar a sus amigos en la prisión del lugar,
el carcelero le negó la entrada,
y al encontrarse con el alcalde y algunos concejales en las calles,
les habló sobre la persecución. Pero
uno de los concejales le quitó el sombrero y le dijo,
que él le enseñaría mejores modales que pararse y
hablar delante del alcalde con el sombrero puesto.
Entonces le exigieron garantías de buen comportamiento, pero él les dijo,
"`Yo estoy obligado al buen comportamiento por la ley justa de Dios.`"
Así, al rehusarse a buscar garantías,
fue capturado en la calle y enviado a prisión sin
una orden de la corte o una investigación más detenida.
Pero no detendré a mi lector más tiempo con estos prisioneros,
porque si yo relatara todos los sucesos de esta naturaleza que han llegado a mi conocimiento,
y los pretextos irracionales bajo los cuales fueron perpetrados,
incluso encerrando en prisión a muchos que aún no habían
entrado en plena comunión con los llamados Cuáqueros,
tendría que escribir mucho más de lo que sería capaz de hacer,
aunque mi vida fuera considerablemente alargada.

Encuentro entre mis papeles de ese tiempo, los nombres de aproximadamente cien personas,
quienes, por no pagar diezmos a los sacerdotes y negarse a jurar,
sufrieron o bien la confiscación de su ganado y bienes, o encarcelamiento.
Thomas Aldam, por no pagarle diezmos a Thomas Rookby, sacerdote de Warnsworth,
fue encerrado en York en 1652, donde fue mantenido más de dos años y medio,
y además le quitaron trece vacas y dos caballos.

Pero dejando de lado multitud de casos similares, vuelvo a G. Fox,
a quien dejamos en Londres.
Él, después de tener varias reuniones grandes ahí, se fue a Colchester,
donde con dificultad pudo visitar a James Parnell
en prisión. De Colchester se fue a Ipswich,
y así pasó a Norwich y Yarmouth, encontrando obra a dondequiera que iba.

Viajando más lejos hacia Lynn en compañía de Richard Hubberthorn,
mientras estaban en la cama en una posada del camino,
llegaron un alguacil y unos oficiales que habían
sido enviados por un juez de paz con un griterío,^
footnote:[Un griterío era una convocatoria pública en la que todos
los ciudadanos y transeúntes eran llamados a detener a un criminal.]
a buscar a dos jinetes con ropa gris que cabalgaban sobre caballos grises,
alegando que una casa había sido asaltada esa noche.
Ahora, aunque Fox y Hubberthorn dijeron que eran hombres honestos e inocentes,
una guardia con alabardas^
footnote:[Una alabarda es una gran hacha de batalla con una lanza en la punta.]
y picos fue puesta sobre ellos esa noche,
y en la mañana fueron llevados ante un juez de paz a unas cinco millas.
El juez se enfureció porque ellos no se quitaron los sombreros ante él,
pero G. Fox le dijo: "`He estado ante el protector y él no se ofendió por mi sombrero;
¿por qué entonces, deberías ofenderte tú por eso,
que no eres más que uno de sus sirvientes?`"
El juez, después de interrogarlos,
les dijo que no creía que ellos fueran los hombres que habían irrumpido en la casa,
pero declaró que lamentaba no tener nada más contra ellos.
Pero G. Fox le dijo: "`No debes lamentarte por no tener mal contra nosotros,
sino más bien alégrate.`"
El juez, aunque estaba siendo incitado por el alguacil a que los enviara a prisión,
los dejó ir.
Una vez en libertad, G. Fox viajó a Lynn y de ahí a Sutton, donde tuvo una gran reunión,
a la que llegaron muchas personas de otros lugares,
y también la esposa del alcalde de Cambridge.
Muchos cientos fueron convencidos de la verdad que él predicaba.
De ahí pasó a Cambridge, y aunque los estudiantes fueron excesivamente rudos,
se puso a salvo en una posada.
En la oscuridad de la noche llegó el alcalde del pueblo y lo llevó a su casa,
de donde se enviaron a buscar a algunas personas amigables,
con las que tuvo una reunión. La mañana siguiente partió del pueblo y regresó a Londres,
y ahí se quedó algún tiempo.

En este año salió el juramento de repudio contra el rey Charles,
por lo que le escribió al protector, informándole que muchos de sus amigos,
quienes no podían jurar por asuntos de consciencia, sufrían mucho por ese motivo.

De Londres se fue a Leicestershire,
y llegando a Whetstone (donde anteriormente había sido hecho
prisionero por el coronel Hacker) tuvo una gran reunión,
a la que llegaron la esposa de Hacker y el mariscal de él, y ellos, además de muchos más,
fueron convencidos por medio del ministerio de G. Fox.
Saliendo de ahí y pasando por varios lugares, regresó a Londres,
donde al conocer a James Nayler y poner sus ojos sobre él,
se sintió afectado por un temor con respecto a él,
al tener la sensación de que una gran calamidad estaba por sucederle.

Este año Edward Burrough le escribió una carta al protector,
en la que le decía que el litigio del Señor estaba contra
él porque no había sido fiel a la obra de Dios,
sino que había escogido un tipo de descanso y de tranquilidad
cimentados en una montaña altiva de orgullo y vanagloria,
habiéndose erigido para ser adorado y exaltado en su propio poder,
sin darle gloria y honor a Dios.
Además,
que él no había cumplido los votos que le había hecho al Señor en el día de angustia,
sino que había permitido que dolorosa opresión, crueldad y tiranía actuaran en su nombre,
mediante injustos encarcelamientos y persecución al pueblo del
Señor. También le dijo que el Señor traería sus juicios sobre él,
a menos que se arrepintiera.
Sin embargo, aunque Burrough le habló con mucha valentía a Cromwell en su carta,
no encontramos que él se enojara por causa de ella.
No obstante, le prestaba demasiada atención a las adulaciones de aquellos maestros, que,
tras entrar en la posesión de los Episcopales,
lo exaltaban como su ídolo por medio de sus aplausos.
Y como Cromwell consideraba que los sacerdotes fortalecían su autoridad sobre el pueblo,
le hacía un guiño a la dolorosa persecución que llevaban
a cabo contra los llamados Cuáqueros.

Mientras tanto,
había muchas personas descontentas que pensaban que era
injusto que Cromwell forzara a los miembros del Parlamento,
a estar de acuerdo con no hacerle cambios al gobierno entonces establecido,
pues él no permitía que nadie ocupara un escaño en el Parlamento sin haber
prometido mediante un escrito que no se opondría al gobierno en curso.
Esto dio oportunidad que incluso algunos que habían sido distinguidos amigos suyos,
lo censuraran duramente.

Entre estos estaba el teniente coronel John Lilburn, un hombre extraordinariamente audaz,
muy rígido e inflexible,
y que más de una vez se había mostrado defensor público de las libertades del pueblo.
Por esta causa había sido procesado por la ley; una vez en el año 1645,
cuando fue encarcelado por traición, pero luego fue liberado; y otra vez, en el año 1649,
cuando,
habiendo publicado varios libros para exponer al público
el poder arbitrario que según él se ejercía en el gobierno,
fue confinado en la Torre de Londres, y tras cerca de siete meses de encierro,
acusado de alta traición. Pero defendió su causa tan vigorosamente,
que aunque se estaba usando una fuerte persuasión
para hacer que el jurado lo declarara culpable,
prevaleció tanto, que al final fue nuevamente puesto en libertad;
aunque encuentro que una vez fue azotado por un crimen que se le había imputado,
de lo cual se glorió públicamente.
Y cuando Cromwell usurpó el poder supremo,
Lilburn audazmente lo acusó de falsedad y tiranía,
tanto por medio de la boca como por escrito.
Entonces Cromwell,
previendo que si este hombre continuaba exponiendo
así sus actos no podría mantener su crédito y autoridad,
ordenó que fuera puesto bajo custodia y que fuera acusado de alta traición. Lilburn,
acusado de esta manera, compareció ante la corte,
y se condujo con tal intrepidez y defendió su causa de manera tal,
que parecía abogar más por la libertad de su país que por su propia vida.

Luego, después de responder valientemente a lo que se le objetaba,
insistió en que lo que él había hecho no sólo no era alta traición,
sino que por el estado en que estaba el gobierno,
no podía cometerse alta traición contra él; y por tanto,
que todos los verdaderos ingleses estaban obligados a oponerse
a la tiranía que estaba siendo ejercida contra ellos.
También dijo,
que en una ocasión había tenido el favor de Cromwell y que habría
podido obtener gran ascenso si sólo se hubiera quedado callado,
pero que al considerar que eso era ilícito, ahora se había decidido quitarle la vida;
lo cual no temía, porque defendía una buena causa.
Así de osado fue el alegato de Lilburn, y defendió su causa con tan fuertes argumentos,
que el jurado lo declaró inocente,
a pesar de los esfuerzos de los jueces de lo contrario.

Ahora bien, aunque de acuerdo a la ley, él debía ser puesto en libertad,
Cromwell no lo consintió, sino que lo mantuvo encarcelado.
Y debido a que él en verdad le temía a Lilburn,
como una persona que podía debilitar su gobierno,
ordenó que lo llevaran de una prisión a otra,
hasta que al final lo confinaron en el castillo de Dover.
En ese pueblo vivía Luke Howard, mencionado anteriormente,
quien tuvo oportunidad de hablar con Lilburn sobre religión,
y le dio razones tan convincentes de su profesión,
que persuadieron a Lilburn de recibir la Verdad;
como él mismo lo implica en la carta que le escribió a su esposa,
quien después de visitarlo en la prisión,
primero le escribió a él la siguiente exhortación:

[.embedded-content-document.letter]
--

[.salutation]
Querido,

Mantén un espíritu sobrio y paciente en tu interior, el cual,
estoy segura que encontrarás que es más fuerte para recuperarte,
de lo que ha sido todo tu agudo coraje.
Espero que Dios esté haciendo tal obra en ti y en mí,
como para hacer que nos examinemos más de lo que hemos hecho.

--

Estas palabras fueron tan aceptables para Lilburn,
que las repitió al principio de la carta que le escribió a ella, y le respondió así:

[.embedded-content-document.letter]
--

¡Oh, mi querido amor!
Ya he entrado profundamente en mi parte de esto.
¡Ojalá el gran poder de Dios también te permita entrar y asimismo atravesar la tuya,
y acompañarme mano a mano eficaz, alegre y voluntariamente!
Eso te haría mucho más afable,
hermosa y agradable a mis ojos (aunque estuvieras vestida
de harapos) de lo que podrías ser para mí retrocediendo,
o deteniéndote donde estabas la última vez que te vi,
aunque allí hubieras estado completamente vestida con ricos y brillantes diamantes terrenales,
y en la más grande prosperidad terrenal.
Lamento que estés presionada por dinero, pero vivir de Dios por fe,
en la profundidad de las estrecheces, es la condición real de un Cristiano.
¡Ojalá que tu espíritu pueda alcanzar esto,
según el deseo de tu carta y el actual estado de mi propio espíritu!
Ahora me contento con comer pan, queso y un poco de cerveza liviana para ahorrar dinero.
Y en cuanto a mi libertad,
acerca de lo cual estás tan abatida y desgastada (como tu carta me lo da a conocer),
puedo decirte que en mi presente ánimo de espíritu,
estoy realmente listo a decir con Pedro (ante la
vista de la gloriosa transfiguración de Cristo):
'`Es bueno para mí estar aquí.`' Pues aquí en el castillo de Dover,
a través de la amorosa bondad de Dios,
he encontrado un conocimiento de Dios y de mí mismo más claro, sencillo y evidente,
y una experiencia de Sus misericordiosas manifestaciones a mi alma,
como nunca antes había tenido en toda mi vida,
incluso mayor que mi gloriosa y alegre condición bajo los obispos.
Y ahora puedo decir, sumisamente y de todo corazón,
que la voluntad del Padre sea hecha en mí, por mí y para mí;
en cuya voluntad te dejo a ti y a los tuyos, a todos tus y mis amigos, y me despido,
descansando en la fuerza de un amor verdadero y renovado,

[.signed-section-signature]
John Lilburn

Desde el castillo de Dover, el lugar de la presente,
disfrutada y agradable dispensación del eterno y perpetuo amor de Dios a mi alma.

[.signed-section-context-close]
4 del Décimo mes, 1653.

--

Mientras Lilburn estaba prisionero ahí,
parecía que Oliver Cromwell estaba dispuesto a liberarlo,
si firmaba una declaración expresando que nunca desenvainaría una espada contra su gobierno.
Pero Lilburn,
que aún no estaba completamente convencido de que abstenerse del
uso de una espada carnal era deber de un verdadero Cristiano,
se negó. Porque aunque George Fox había firmado tal declaración,
pensó que no era apropiado para él,
siendo que aún no aprobaba por completo este aspecto de autonegación. Sin embargo,
al continuar fielmente en la medida de conocimiento que ya había alcanzado,
con el paso del tiempo llegó a ser tal defensor de la verdadera vida Cristiana,
que en un documento (que de acuerdo a su deseo fue entregado
en forma impresa) se expresó con las siguientes palabras:

[.embedded-content-document.paper]
--

Ahora tengo al fiel y verdadero Testigo en mi propia alma.
En efecto, el Señor se ha convertido dentro de mí en el maestro de mi alma,
y me capacita para caminar en una medida de Sus caminos y senderos puros.
Sí, y Él ha llegado a ser para mí un maestro tan claro en mi interior,
que con confianza creo que mi "`maestro interior
nunca más será quitado,`" sino que es y será,
como una continua voz que dice a mis oídos: "`Este es el camino, andad por él.`"^
footnote:[Isaías 30:20-21]
Por medio de esta enseñanza divina, soy enseñado diariamente a morir al pecado,
y conducido por ella al poder vivo,
para ser levantado y capacitado para vivir en una medida pura de justicia.
Mediante esta enseñanza interna y espiritual, repito, soy llevado al poder en Cristo,
por el que puedo testificar, y lo hago en el presente documento, de que ya estoy muerto,
o crucificado, a las verdaderas razones y motivos reales de todas las guerras externas,
luchas con espadas carnales, y ajetreos y combates carnales.
Por tanto, ahora creo confiadamente,
que de aquí en adelante nunca más usaré una espada temporal,
ni me uniré a los que la usan.
Esto lo declaro aquí solemnemente, no para evitar en lo más mínimo la persecución,
ni por algún fin político propio,
ni para la más mínima satisfacción de los deseos carnales de alguno de mis grandes adversarios,
ni para satisfacer el deseo carnal de mi pobre, débil y afligida esposa; sino que,
por los movimientos y apremios especiales de Dios sobre mi alma ahora,
estoy en verdad y justicia, obligado a declarar así,
para quitarles a mis adversarios todas sus cubiertas de hojas de higuera,
o excusas para mantenerme en este injusto cautiverio.
Por tanto, si todavía debo ser un prisionero sufriente,
que de hoy en adelante sea por la Verdad como está en Jesús,
la Verdad que yo testifico ser verdaderamente profesada
y practicada por el pueblo de Dios llamado Cuáqueros,
que es grato olor de Cristo.

A esta declaración presente, la cual anhelo de todo corazón que se publique,
y por la que sé que puedo dar mi vida con alegría y seguridad,
si fuera llamado a testificar la verdad de la misma, suscribo mi nombre,

[.signed-section-signature]
John Lilburn.

[.postscript]
====

Desde mi cautiverio inocente, y en todos los sentidos sin causa, en el castillo de Dover,
el lugar de la plácida y feliz morada de mi alma,
donde he encontrado real y sustancialmente lo que
mi alma por muchos años ha buscado diligentemente,
y con un anhelo insatisfecho ha tenido sed de disfrutar;
el presente Primer-día de la semana, 4 del Tercer mes de 1655.

====

--

Parece bastante claro, que Lilburn no creía que la declaración le procuraría su libertad;
y no supuso mal, porque Cromwell murió antes de que fuera finalmente liberado.
Después de que Lilburn fue puesto en libertad,
continuó firme en la doctrina de la Verdad que había abrazado,
hasta que murió en Londres en el año 1660.
Siendo que avancé en el tiempo, retrocedo un poco,
y pretendo dar en la secuela una descripción más oportuna de la muerte de Cromwell.

Así concluyo este capítulo del año 1655,
en el que hubo un complot de los de la realeza contra Cromwell,
quienes ya se había levantado en algunos lugares en Nottinghamshire,
y hacia el oeste de la ciudad de Salisbury.
El joven rey (Charles) había salido de Colonia y llegado a Zealand,
para estar más cerca en el caso de que el atentado tuviera éxito.
Pero no había llegado el momento para que él reinara,
pues los monárquicos pronto se vieron obligados a cederle paso al poder de Cromwell,
y al ser aplastado el complot, el rey Charles regresó a Colonia.
Mientras tanto, a fin de aumentar su reputación en el exterior,
Cromwell mandó una flota al mando del almirante Penn,^
footnote:[Sir William Penn (1621-1670), fue un almirante y político inglés,
que ocupó un escaño en la Cámara de los Comunes de 1660 a 1670;
también fue el padre de William Penn, el fundador de Pensilvania.]
a West Indies, y otra al mando del almirante Blake, al Mar Mediterráneo.
