== Capítulo 7

[.section-date]
1656--1657

[.chapter-synopsis]
* "`La historia de los fanáticos`"
* Respuesta de J. Nayler
* Muerte de J. Nayler
* M. Fisher y A. Austin van a Nueva Inglaterra
* El abuso bárbaro contra ellas
* Leyes hechas para impedir que los Cuáqueros fueran a Nueva Inglaterra
* Entrevista entre el protector y G. Fox y E. Pyot
* Cartas de advertencia de E. Burrough al protector
* Notable conferencia entre C. Birkhead y una congregación inglesa en Middleburg, Zelanda
* Viajes de W. Ames y W. Caton
* Convencimiento de los padres del autor
* G. Fox y el gobernador de Tenby
* Cuáqueros excomulgados en Escocia
* G. Fox viaja por Escocia
* Severidades contra los Cuáqueros en Nueva Inglaterra
* Notables incidentes de los viajes de G. Robinson a Jerusalén.

Cuando el rey Carlos II había ascendido al trono,
un hombre llamado Richard Blome publicó un libro titulado,
[.book-title]#The Fanatic History,#footnote:[Es decir,
_Historia de los Fanáticos._]
del que se decía que había sido publicado con la
aprobación de los llamados teólogos ortodoxos,
y dedicado por él al rey.
El libro atacaba principalmente a los Cuáqueros,
y estaba repleto de una gran cantidad de historias falsas,
junto con un relato muy exagerado de la caída de James Nayler.
Dado que Nayler estaba vivo para entonces,
cogió la pluma y respondió a las mentiras que contenía el libro
y que estaban relacionadas con él. Y como Richard Blome,
en su dedicación al rey había dicho:
"`Si su majestad no extiende su mano real de poder rápidamente para detenerlos,
pues son muy numerosos y seductores, y en poco tiempo,
esparcirán su veneno sobre la mejor parte de su reino,
lo que nadie sino una autoridad real puede sofocar;`"
Nayler respondió con las siguientes palabras:

[.embedded-content-document.paper]
--

¿Qué ha sucedido con tus armas espirituales?
¿No les han hablado tus maestros a las personas de
la fuerza de la Verdad y del poder de la piedad?
¿Has perdido ambos y ahora recurres al brazo de la carne,
para que los errores (como los llamas) sean sofocados,
o de lo contrario tu esperanza se pierde y te falle la fe?
¿Se despojaron alguna vez los ministros de Cristo de las
armas espirituales y recurrieron al brazo de la carne,
o a un arma carnal, para detener a los seductores?
Yo digo, no.
Los ministros de Cristo nunca lo hicieron,
sino que lucharon y vencieron la maldad espiritual con armas espirituales;
cortaron herejías, blasfemias y adoración falsa con armas espirituales;
y recorrieron el mundo limpiando las iglesias de Cristo
de todas esas cosas y derribándolas delante de ellos,
porque en realidad, nadie podía resistir el Espíritu por el que ellos hablaban.
Pero, los falsos sacerdotes y los falsos adoradores clamaban
a los gobernantes y al pueblo (como tú ahora) diciendo:
"`¡Ayúdennos, o todo será invadido,
porque estos que trastornan al mundo han llegado aquí!`"^
footnote:[Hechos 17:6; 21:28]
Y luego, la multitud grosera corría sobre ellos y se abalanzaba con varas y puños,
y asaltaba las casas que los hospedaban, tal como hacen ustedes,
y así los arrastraban delante de los gobernantes,
los ponían en prisión y a menudo los azotaban.
¿Es este tu clamor pidiendo ayuda contra un pueblo tan despreciable (según tu consideración)?
¡Qué! ¿Han predicado y luchado ustedes fuera de toda esperanza y fe,
de modo que ahora deben recibir ayuda repentina del rey,
o todo está perdido y es arrasado?
En verdad puede decirse entonces, que ustedes han sido malos atalayas y pastores ociosos.

Considerando que tú dices que tu libro es de gran importancia,
y por eso presumes haber nombrado al rey Carlos patrocinador del mismo,
y luego pides perdón por tu presunción; yo digo,
tú en verdad necesitas su perdón. Porque la esencia
de tu libro se compone de falsas acusaciones,
recogidas de libros escritos anteriormente contra nosotros,
todas las cuales han sido refutadas con respuestas claras e impresas varias veces.
A estas viejas acusaciones les has añadido unas cuantas nuevas,
tan falsas como las antiguas, y has espiado las fallas de unos pocos,
que se han lamentado delante de Dios por pecar y por darles
oportunidad a los enemigos de Dios de blasfemar.
Y en todo esto has incluido muchas cosas que fueron hechas y dichas por otros,
que no son de nuestra sociedad, ni lo fueron nunca.

En cuanto a los cargos que tienes contra James Nayler,
por la eterna misericordia de mi Dios,
todavía tengo existencia entre los vivos y aliento para responder por mí mismo,
a pesar de las intenciones de muchos espíritus crueles y sanguinarios,
que en el día de mi calamidad persiguieron mi alma
hasta la muerte (tanto como estaba en su poder),
cuando el adversario se había levantado sobre mí
y yo fui hecho una señal para una generación apóstata.
Estos se regocijaron contra este pedazo de polvo y tuvieron
poca piedad hacia el que había caído en sus manos;
en aquel momento Dios fue justo al entregarme por
causa de mi desobediencia (por un tiempo,
como un padre), para corregirme.
Sin embargo, estos no debieron haber buscado agravar las cosas contra mí,
como lo haces tú ahora, pues ese fue un día de profunda angustia,
que puso dolor sobre mi alma, y el Dios misericordioso lo vio, quien,
aunque en ese momento estaba disgustado conmigo,
aun así Sus pensamientos no eran echarme para siempre,
sino extender misericordia como sucede hoy.
¡Gloria eterna sea dada a Su nombre desde mi alma liberada!

Pero, oh hombre, u hombres, quienquiera que seas tú,
cuya obra es reunir los fallos del pueblo de Dios en el tiempo de su tentación,
o en la noche de su prueba, y agravarlos,
añadiéndoles la maldad y las mentiras maliciosas de tu propio corazón,
como has hecho en tu libro,
para así criticar la eterna y santa Verdad de Dios--yo te digo,
un espíritu maligno te ha puesto a trabajar,
y no haces más que mostrarte enemigo de Dios y de Sus hijos.
Porque es de gran tristeza para nosotros,
que alguno haya dado razones para que se hable contra la Verdad;
y ha sido angustia de alma para todo el pueblo de Dios que siempre ha amado la justicia,
cuando causan así el gozo del malvado,
o alimentan al hombre que vigila la iniquidad y se sustenta de maldad.
Sin embargo, sepan esto los que son de ese linaje, Dios no desechará a Su pueblo,
y aunque a veces Lo provocan a corregirlos,
incluso delante de sus adversarios (lo cual es una señal para ellos),
aun así Su enojo es sólo por un momento, y Su favor volverá como corrientes de vida.

Pero eso que era y es la tristeza de mi corazón,
fue la ventaja que tomó el enemigo en el tiempo de mi tentación,
contra el nombre de Cristo, Su Verdad y Su pueblo despreciado,
la cual ahora persigues con odio y mentiras,
al decir que se sospechaba que yo había tenido una mujer en la
cama conmigo la noche antes de mi sufrimiento en Bristol.
Pero en cuanto a esto, y de varias otras cosas falsas que has escrito en tu libro,
estoy limpio delante del Señor, de modo que no me afectan.
Y sólo busco a Dios, para en Su tiempo, ser limpiado de todas las ofensas ante Su vista,
el Único que conoce mi corazón en este asunto y en Cuya presencia puedo decir,
que nada es más odioso y gravoso para mi alma que algo de
la gloria o adoración que pertenece a Dios o a Cristo,
sea dada a carne y sangre, ya sea en mí o en otros.
En cuanto a qué me sucedió en ese tiempo, muchos hablan, pero pocos saben;
de modo que llevo el juicio de los tales, deseando que nadie, al juzgarme,
se condene ante los ojos de Dios, pues Sus consejos son grandes y profundos,
y el fin de Su obra es indescifrable, hasta que Él los revele.

A pesar de que yo o cualquier otro todavía puede
ser dejado sólo para ser tratado en la noche,
o alguno de nosotros caer completamente,
o cualquier otra cosa que no es correcta ante los
ojos de Dios ser hecha por algún hombre o mujer,
en vano recoges el pecado y vigilas la iniquidad
con el fin de arrojar eso sobre la luz de Cristo.
Pues la luz de Cristo es la que condena el pecado en toda mente alumbrada.
Sé por el Espíritu de Jesús, el cual he recibido y obra en mí, que tu obra no es Su obra,
ni es de Su semilla.
Tú no estás en Aquel que ama a Sus enemigos,
sino que el antiguo acusador de los hermanos es el que obra fuertemente en ti.
Y en esa luz que tú censuras,
se te ve como el hombre que fabrica mentiras y lleva
'`calumnias para derramar sangre.`' (Ezequiel 22:9)

--

Esto y mucho más escribió James Nayler para responder
a las mentiras de las que era acusado,
y para mostrar que la culpa de su crimen no debía ser en
ninguna forma atribuida a la doctrina que él profesaba,
como muchas personas envidiosas afirmaban en esos tiempos; a saber,
que su caída era consecuencia de la doctrina de que los hombres
deben prestarles atención a la gracia salvadora de Dios,
a la unción interna,
o a la luz con la que todo hombre que viene al mundo es iluminado por Dios.^
footnote:[James Nayler fue un hombre altamente favorecido
por Dios con un buen grado de gracia,
la cual habría sido suficiente para él, si se hubiera mantenido en sus enseñanzas.
Mientras lo hizo, fue ejemplar en piedad y gran humildad,
fue poderoso en palabra y doctrina, y por tanto,
un instrumento en la mano de Dios para volver a muchos de las tinieblas a la luz,
y del poder de Satanás al poder de Dios.
Pero él, pobre hombre, se exaltó sobremanera por la abundancia de revelación,
y en dicha exaltación se desvió de la gracia y del Espíritu Santo de Dios,
quien había sido suficiente maestro para él. Entonces,
la ceguera se apoderó de él y se dejó estimar por
encima de lo que debía. Aquí se resbaló y cayó,
pero no de manera irrecuperable, pues le plació al Dios de infinita misericordia,
darle en el día de su aflicción una visión y un sentido de sus extravíos y caída,
y también un lugar de arrepentimiento.
Y él, con el pródigo, se humilló por su transgresión,
y le suplicó a Dios con verdadera contrición de alma,
que perdonara sus ofensas por medio de Jesucristo.
Yo creo firmemente que Dios lo perdonó, porque Él perdona al verdaderamente arrepentido.
Su pueblo lo recibió con gran gozo, porque el que se había descarriado de Dios,
regresaba a la casa del Padre,
y el que se había separado de ellos por causa de su iniquidad,
por medio del arrepentimiento y abandono de ella,
regresaba a la unidad de la fe y a la santa comunión con ellos en el evangelio de Cristo.
Y por este medio testifico,
que considero una señal particular del reconocimiento de Dios a Su pueblo,
traer de regreso a la unidad con ellos,
a un hombre que había caído tan peligrosamente como sucedió con James Nayler.
¡Aquí que nadie insulte, sino que preste atención, no sea que en la hora de tentación,
también se aparte! ¡Ni nadie diga con jactancia:
Dónde está tu Dios! ¡Ni nadie blasfeme suponiendo que Su
gracia no es suficiente para un hombre en tentación,
porque el tentado puede apartarse o descuidar la enseñanza de ella!
Ya que las transgresiones de David y de Pedro se
produjeron al apartarse de este guía infalible,
el Espíritu Santo;
y sólo por medio de Él se produciría su recuperación.`"
--Joseph Wyeth en [.book-title]#A Switch for the Snake.#]

Después de su recuperación, también escribió muchos documentos y cartas edificantes.
Y cuando la persecución en Nueva Inglaterra ardía ferozmente,
y fueron enviadas desde ahí dos cartas a Inglaterra--una a nombre de John Endicott,
gobernador de Boston,
y la otra a nombre de Richard Bellingham--en defensa de sus acciones,
argumentando que la persecución de los Cuáqueros era lícita y necesaria,
estas fueron ampliamente respondidas por James Nayler,
que mostró cuán poco acuerdo había entre sus crímenes de
persecución y el nombre con el que se habían hecho llamar,
es decir, Independientes.
Porque con este nombre ellos querían que se supiera que eran independientes de todo,
excepto del Espíritu de Jesucristo, de quien pretendían únicamente depender.
Y sin embargo, ahora se veía claramente que se sostenían de un brazo carnal.
También les escribió algunos artículos a los miembros del Parlamento y a los gobernantes,
para que controlaran las vanidades que eran cometidas públicamente,
enmendaran sus faltas,
aliviaran a los oprimidos y tuvieran cuidado del mantenimiento de la libertad.

Finalmente murió en Huntingdonshire,^
footnote:[Después de su caída y recuperación,
J+++.+++ Nayler fue un hombre de gran autonegación y muy vigilante de sí mismo.
Por fin, al salir de la ciudad de Londres, a finales del mes Ocho de 1660,
se dirigió al norte,
con la intención de volver a casa con su esposa e hijos en Wakefield, en Yorkshire.
En el camino un Amigo de Hertford lo vio sentado al lado de la calzada,
en un estado de ánimo muy serio y pesado; este hombre lo invitó a su casa,
pero Nayler se rehusó indicando que era su mente seguir adelante.
Llegó a pie a Huntingdonshire,
y mientras atravesaba el pueblo otro Amigo lo observó en tal estado celestial,
que parecía como si hubiera sido redimido de la tierra, y fuera un extranjero en ella,
buscando un mejor país y herencia.
Pero se enfermó unas millas después de Huntingdon,
tras haber sido robado en el camino y dejado atado, según se dijo.
No se sabe con certeza si recibió alguna herida personal,
pero al anochecer un campesino lo encontró en el campo,
y fue llevado o fue a la casa de un Amigo en Holm, no lejos de King`'s Rippon,
donde Thomas Parnell, un doctor en medicina, lo fue a visitar.
Cuando se le preguntó si debían ser enviados a llamar
algunos amigos de Londres para que lo vieran,
dijo: "`No;`" pero expresó su atención y amor por ellos.
Cuando lo movieron en la cama dijo: "`Ustedes han refrescado mi cuerpo,
que el Señor refresque sus almas.`"
No mucho después partió de esta vida en paz con el Señor,
alrededor del mes Nueve de 1660, a la edad de 44 años,
y fue enterrado en el cementerio del antes mencionado Thomas Parnell,
en King`'s Rippon.`" --[.book-title]#Relato de John Whiting.#]
a fines de 1660, con casi 44 años de edad.
Aproximadamente dos horas antes de su muerte,
dijo las siguientes palabras en presencia de varios testigos:

[.embedded-content-document.testimony]
--

Hay un Espíritu que siento en mí, el cual se deleita en no hacer mal,
ni en vengar ningún mal, sino en soportar todas las cosas,
con la esperanza de disfrutar Lo suyo al final.
Su esperanza es sobrevivir a toda ira y conflicto, y fatigar toda exaltación y crueldad,
o cualquier cosa que sea de una naturaleza contraria a la Suya.
Él ve hasta el final de todas las tentaciones.
Así como no tiene mal en Sí mismo,
tampoco concibe ninguno en pensamiento contra alguien más. Si es traicionado, lo soporta;
porque Su fundamento y Su manantial es la misericordia y el perdón de Dios.
Su corona es la mansedumbre, su vida es el amor eterno no fingido.
Él toma Su reino con súplica y no con contienda, y lo guarda con humildad.
Sólo en Dios se regocija, aunque nadie más considere o reconozca Su vida.
Es concebido en la tristeza y dado a luz sin que nadie lo compadezca;
no murmura en la angustia ni en la opresión. Nunca
se regocija sino a través de los sufrimientos,
porque el gozo del mundo lo asesina.
Lo encontré solo, abandonado.
Tengo comunión en Él con los que vivieron en cuevas y lugares desolados en la tierra,
quienes a través de la muerte obtuvieron esta resurrección y vida santa y eterna.

[.signed-section-signature]
James Nayler.

--

Este fue el último testimonio de J. Nayler, o sus últimas palabras; y así dio prueba,
de que aunque había errado, esperaba con gran confianza una feliz resurrección.^
footnote:[Hay un pasaje en el libro llamado
[.book-title]#The Complete History of England,# vol. iii, página 201,
que dice que James Nayler murió sin frutos,
ni siquiera con signos de arrepentimiento.
Cómo llegó el autor de este libro a tal información, no podemos decirlo,
pero no nos cabe duda de que es un error evidente,
del que el lector imparcial a estas alturas, está ampliamente convencido.]
Así concluyo la historia de J. Nayler, y dejándolo ya,
el tiempo me llama a Nueva Inglaterra.

En el mes llamado Julio del presente año,
llegaron Mary Fisher y Ann Austin frente a las costas de Boston,
antes de que fuera hecha cualquier ley contra los Cuáqueros.
No obstante, ellas fueron muy maltratadas, porque antes de que llegaran a tierra,
el representante de la corte-gobernador,
Richard Bellingham (el gobernador estaba fuera de la ciudad), envió oficiales a bordo,
quienes buscaron en sus baúles y cofres,
y les quitaron los libros que encontraron y se los
llevaron a tierra (que eran como unos cien),
después de ordenar que la mujeres fueran mantenidas prisioneras a bordo del barco.
Luego, por orden del consejo,
los mencionados libros fueron quemados en el mercado por un verdugo.
Después, el representante-gobernador hizo traer a tierra a las mujeres,
y por una orden de la corte las envió a prisión como Cuáqueras,
con la única prueba de que una de ellas hablando con él,
había usado "`tú`" en lugar de "`usted;`" ante lo cual dijo,
que él no necesitaba más evidencia porque veía que ellas eran Cuáqueras.
Entonces fueron recluidas en aislamiento,^
footnote:[Dependiendo de la severidad del crimen (o de otras consideraciones atenuantes),
a los prisioneros a menudo se les otorgaban ciertas
libertades durante su tiempo de encarcelamiento.
A algunos se les permitía continuar en sus oficios, visitar a sus familias,
o caminar a pueblos cercanos para comprar artículos de primera necesidad.
Los "`prisioneros en aislamiento,`" eran despojados de todas esas libertades,
y generalmente, eran confinados a una celda todo el tiempo.]
y se dio la orden de que nadie podía visitarlas sin permiso,
y se impuso una multa de cinco libras para el que se acercara o hablara con ellas,
incluso por la ventana.
Se les decomisaron sus plumas, tinta y papel,
y no se les permitió tener la luz de una candela por la noche.
Lo que es más, fueron desnudadas bajo el pretexto de saber si eran brujas,
aunque en la búsqueda no se halló sobre ellas ninguna señal más que de su inocencia;
en dicha búsqueda fueron tan bárbaramente abusadas, que el pudor me prohíbe mencionarlo.
Y se clavó una tabla frente la ventana de la cárcel,
para que nadie pudiera comunicarse con ellas.

Al ver que no se les proporcionaba comida,
ni se concedía libertad para enviarles provisiones, Nicholas Upshal,
uno que había vivido por mucho tiempo en Boston y que era miembro de la iglesia allí,
estaba tan preocupado por esto, que le compraba la comida de ellas al carcelero,
por una tarifa de cinco chelines a la semana, para que no murieran de hambre.
Después de haber estado por unas cinco semanas prisioneras, William Chichester,
capitán de un velero, fue obligado a llevarlas de vuelta a Inglaterra,
o a perder cien libras, y se le ordenó que no permitiera a ninguno hablar con ellas.
Después,
fueron llevadas a bordo y el carcelero se quedó con sus
camas (que habían sido sacadas del barco) y sus Biblias,
como pago de sus honorarios.

Este fue el recibimiento con el que se toparon los Cuáqueros al principio en Boston,
y aquellos del pueblo que afirmaban, que por un asunto de consciencia,
habían escogido las tierras yermas de América,
antes que las tierras bien cultivadas de la vieja Inglaterra.
Posteriormente, sin embargo,
cuando les habían quitado las vidas a los llamados Cuáqueros,
a fin de excusar sus crueles actos,
no dudaron en decir que al principio ellos no habían
hecho uso del castigo contra los Cuáqueros.

Apenas un mes después de la llegada de las mencionadas mujeres a Boston,
también llegaron Christopher Holder, Thomas Thirstone, William Brend, John Copeland,
Mary Prince, Sarah Gibbons, Mary Whitehead y Dorothy Waugh;
estos fueron encerrados de la misma manera que las anteriores,
y después de casi once semanas de estadía, fueron enviados de regreso.
Robert Locke, capitán de un barco,
fue obligado a llevar a estas ocho personas de regreso por su cuenta,
y a no desembarcarlas en ningún otro lugar que no fuera Inglaterra,
después de haber estado prisionero hasta que se comprometió a hacerlo.

El gobernador John Endicott, cuya sed de sangre se verá en lo que sigue,
después de haber regresado a casa les dijo:
"`Tengan cuidado de no quebrantar nuestras leyes eclesiales,
porque de seguro serán colgados con una cuerda.`"
Y cuando quisieron una copia de dichas leyes, se les negó;
lo que hizo que algunas personas dijeran: "`¿Cómo sabrán entonces cuando transgredan?`"
Pero Endicott se mantuvo rígido, habiendo dicho antes cuando estaba en Salem,
y oído cómo habían sido tratadas Ann Austin y Mary Fisher en Boston:
"`Si yo hubiera estado ahí, las habría azotado.`"
Luego se promulgó una ley que les prohibía a los
capitanes de barcos llevar Cuáqueros a esa jurisdicción,
y les prohibía a los Cuáqueros llegar so pena de ser encerrados
en la casa de corrección. Cuando se publicó esta ley,
Nicholas Upshal, ya mencionado,
no pudo abstenerse de mostrarles a los perseguidores lo poco razonable de sus procedimientos,
advirtiéndoles que tuvieran cuidado de no ser hallados peleando contra Dios,
y de esa manera, atraer un juicio sobre la tierra.
Pero esto fue tomado tan mal, que aunque él era un miembro de su iglesia,
de buena reputación y un hombre de conducta intachable,
fue multado con veintitrés libras y encarcelado por no asistir a la iglesia,
y luego lo desterraron de su jurisdicción. Esta multa fue exigida con tanta severidad,
que Endicott dijo: "`No bajaré su multa un '`groat.`'^
footnote:[Moneda de plata que se usaba en el pasado en Inglaterra y Escocia,
equivalente a cuatro peniques.]`" Y aunque N. Upshal era un anciano débil,
no le dieron más que un mes para su mudanza,
de modo que se vio forzado a salir en invierno.

Al llegar finalmente a Rhode Island, se encontró con un príncipe indígena de la región,
quien habiendo entendido cómo había sido tratado Upshal, se portó amablemente con él,
y le dijo que si vivía con él, le haría una casa acogedora.
Además le dijo: "`¿Qué Dios tienen los Ingleses,
que se tratan unos a otros así por su Dios?`"
Pero esto no fue más que el principio de la persecución en Nueva Inglaterra,
la cual se acaloró tanto con el tiempo,
que algunos de los Cuáqueros fueron ejecutados en la horca,
como será relatado a su debido tiempo.

Ahora regreso a la Vieja Inglaterra, donde dejamos a G. Fox en Exeter,
de donde se fue a Bristol.
Allí tuvo una gran reunión en un huerto, y como había algunos miles de personas,
y muchos estaban muy ansiosos por verlo,
se puso de pie sobre una gran piedra que había en el lugar,
y quitándose su sombrero estuvo un rato en silencio, para dejar que la gente lo mirara.
Ahí se encontraba un Bautista de nombre Paul Gwyn,
quien comenzó a encontrar fallas en el cabello de G. Fox, y por fin le dijo a la gente:
"`Sabios de Bristol, me sorprenden ustedes,
que estén de pie aquí y escuchen a un hombre hablar y afirmar cosas que no puede probar.`"
Ante esto G. Fox le preguntó a la gente, si ellos lo habían escuchado hablar antes,
o si lo habían visto antes.
Y les pidió que tomaran nota de qué tipo de hombre era Paul Gwyn,
quien tan descaradamente decía que él hablaba y afirmaba lo que no podía probar,
cuando ni Gwyn ni ellos lo habían escuchado o visto antes; y por lo tanto,
que un espíritu mentiroso,
envidioso y malicioso hablaba en él. Luego G. Fox
pidiéndole a Gwyn que estuviera en silencio,
comenzó a predicar, y se extendió algunas horas sin ser molestado.

Después de esta reunión, G. Fox partió de Bristol, y pasando por Wiltshire,
en Marlborough, y por otros lugares, regresó a Londres.
Acercándose a Hyde Park, vio que el protector iba en su carruaje,
y cuando se aproximaba al costado del vehículo,
algunos de los guardaespaldas querían alejarlo,
pero el protector intervino y se los prohibió. Cabalgando al lado del carruaje,
G+++.+++ Fox le habló acerca de los sufrimientos de sus amigos en la nación,
y le mostró cuán contraria era esa persecución a Cristo y Sus apóstoles,
y al Cristianismo.
Al llegar a la puerta del St. James`'s Park, G. Fox dejó a Cromwell,
quien al separarse le pidió que fuera a su casa.
Al día siguiente Mary Sanders (después Stout),
una de las doncellas de la esposa de Cromwell, fue al alojamiento de G. Fox y le contó,
que cuando su señor había llegado a la casa, le había dicho que le daría buenas noticias,
y que cuando ella le había preguntado cuáles eran,
él le había respondido que G. Fox había llegado a la ciudad;
a lo que ella había respondido, que efectivamente esas eran buenas noticias.
No mucho después, G. Fox y Edward Pyot fueron a Whitehall,
y allí le hablaron a Cromwell acerca de los sufrimientos de sus amigos,
y lo dirigieron a la luz de Cristo,
quien "`alumbra a todo hombre que viene a este mundo.`"
A esto Cromwell dijo: "`Esa es una luz natural;`" pero ellos le mostraron lo contrario,
diciendo que esa luz era divina y espiritual, y que procedía de Cristo,
el hombre espiritual y celestial.
Además,
G+++.+++ Fox le pidió al protector que pusiera su corona a los pies de
Jesús. Y mientras G. Fox estaba de pie junto a la mesa,
Cromwell se acercó y se sentó al lado de la mesa junto a él,
y dijo que así estaría a la misma altura de G. Fox.
Luego continuó hablando de manera superficial, pero después se puso tan serio,
que cuando llegó donde su esposa y otras personas,
dijo que nunca antes se había despedido de los Cuáqueros con tanto afecto.

Después de haber visitado las reuniones de sus amigos en Londres y sus alrededores,
G+++.+++ Fox se fue y viajó por casi toda Inglaterra, no sin muchos sucesos,
los cuales por un asunto de brevedad, dejaré de lado.
Finalmente regresó a Londres, llegando a su fin este año.

En el Parlamento que había convocado Cromwell,
se promulgó una ley que rechazaba el título de rey para Carlos Estuardo II,
y al llegar el año 1657, se le otorgaron subvenciones a Cromwell.
En ese entonces había un plan secreto en marcha para convertirlo rey, del cual,
aunque expresó su disgusto, no parecía totalmente opuesto,
porque en una ocasión hablando con el general Fleetwood y el coronel Desborough,
empezó a bromear con ellos acerca de la palabra "`monarquía,`"
diciendo que no era más que una pluma en la gorra de un hombre,
y se preguntaba por qué los hombres no complacerían
a los niños y les permitirían jugar con su sonajero.
Pero estos hombres le expresaron claramente que el asunto les disgustaba,
y le dijeron que aquellos que lo habían puesto ahí,
no eran verdaderos enemigos de Carlos Estuardo II, y que si él aceptaba ese título,
infaliblemente acarrearía la ruina sobre él. Ahora bien,
aunque no se opuso a ellos abiertamente,
no vaciló en decirles que eran un par de tipos fastidiosos,
y los dejó. También se relata,
que el general de división Lambert le dijo a Cromwell que si aceptaba la corona,
no podría asegurarle el ejército.

Por tanto, al frustrarse el plan,
y al ver Cromwell que el asunto no marchaba tan fácilmente, rechazó el título de rey,
y al confirmarlo el Parlamento en su título de protector,
se acordó que en adelante el Parlamento debía consistir
en una cámara baja y en otra cámara;
y que el protector debía nombrar un sucesor en el gobierno.
Ahora que estaba solemnemente establecido en su autoridad,
se erigió un trono para ese propósito en Westminster Hall,
y vestido con una túnica púrpura forrada con piel de armiño,
se le presentaron el cetro y la espada, e hizo el juramento de gobernar fielmente.
Luego Cromwell convocó un nuevo Parlamento, que consistía en dos cámaras, a saber,
la Cámara de los Comunes y otra Cámara, como la llamaban ellos.
Muchos miembros que antes habían sido excluidos,
ocuparon nuevamente un lugar en la Cámara de los Comunes;
se creía que más de cien miembros de dicha Cámara eran enemigos de Cromwell,
y la autoridad de la Cámara Alta empezó a ser cuestionada por algunos,
debido a que estaba llena de muchos de sus títeres,
algunos de los cuales eran de bajo rango.
Este asunto continuó en la Cámara de los Comunes a tal punto,
que Cromwell pronto disolvió el Parlamento,
e hizo que el general de división Lambert renunciara a su cargo.

Edward Burrough, quien a menudo le escribía a Cromwell,
al oír del plan de hacerlo rey le escribió una carta,
en la que encuentro que después de haberle dicho al protector
que él había recibido muchas advertencias del Señor,
le habla así:

[.embedded-content-document.letter]
--

Yo, como uno que ha obtenido misericordia del Señor y
a quien le ha sido encomendada Su palabra,
siendo movido por Él, por este medio en Su presencia te advierto una vez más,
a que temas delante de Él y diligentemente Lo escuches y Lo busques con todo tu corazón,
para que conozcas Su voluntad y Su consejo con respecto a ti, y lo hagas,
y halles favor ante Su vista y vivas.
Hoy es el día en que Su mano se extiende hacia ti para hacerte una bendición,
o para dejarte una maldición para siempre; los días de tu visitación están cerca del fin,
cuando Dios no te llamará más, ni te oirá cuando en el día de tu angustia Lo llames.
Si rechazas el consejo del Señor, sigues los deseos de tu propio corazón,
los deseos de los hombres y no quieres tener a la luz del mundo--Jesucristo--para
que sólo Él te gobierne y te enseñe (quien condena todo el mal),
de cierto el mal caerá sobre ti, si no amas la luz en ti que lo condena; y así,
no escaparás de los juicios de Dios, ni del día de Su última visitación con venganza.

Por tanto, considera y presta atención a mis palabras, y acepta este consejo.
Deja que este te mueva a la mansedumbre, a la humildad y al temor delante del Señor;
sabiendo con certeza que Él cambia los tiempos y las cosas,
derriba y levanta a quien quiere,
y que fue Él quien te levantó de un estado bajo y te colocó sobre todos tus enemigos.
Aquel día, cuando fuiste levantado,
cuando el temor del Señor estaba delante de tu rostro,
tu corazón estaba hacia Él y eras pequeño a tus propios ojos,
te iba bien y el Señor te bendecía. En ese tiempo, ni una sola vez se pensó acerca de ti,
que las manos de los impíos se fortalecerían contra los justos debajo de ti,
ni que serían impuestas sobre los justos cargas y opresiones dolorosas y crueles,
ni que en tu nombre y bajo tu dominio se actuaría contra ellos,
como ha sucedido en estos tres años. Esta--tu permisibilidad de estas cosas--es tu transgresión,
y no le has retribuido bien al Señor por Su bondad hacia ti, ni cumplido Su voluntad,
al permitir que fueran hechas estas cosas bajo tu dominio y en tu nombre,
contra las que el Señor te levantó y habría derribado,
si hubieras sido fiel hasta el final.

De nuevo, reflexiona y no dejes que tu corazón se exalte, ni sea altivo,
sino teme continuamente, sabiendo que tú no permaneces por ti mismo, sino por Otro,
y que Él es capaz de humillarte y entregarte a la voluntad de tus enemigos cuando quiera.
Considera cuán maravillosamente te ha preservado el Señor algunas veces,
y lo hace hasta hoy,
de las conspiraciones asesinas y políticas arteras de hombres malvados,
que buscan tu mal,
y se regocijarían con tu caída y desolación de tu familia y país. ¿Acaso no han puesto,
y siguen poniendo, trampas a tus pies, para que seas cortado de entre los hombres,
mueras tristemente y seas considerado maldito?
Sin embargo, Él te ha preservado hasta hoy y ha estado cerca para guardarte,
aunque tú apenas lo has sabido.
El fin del Señor es el amor hacia ti en todas estas cosas, y aun así,
te probará un poco más para que Le des la gloria.
¡Ojalá se abra tu corazón para ver Su mano, y para que vivas para Él y mueras en Él,
en paz!
Ten cuidado, no sea que menosprecies Su amor, y la dureza de corazón se apodere de ti;
porque serás encerrado en tinieblas,
entregado a los deseos de tus enemigos y abandonado al consejo de los hombres traidores,
que buscan exaltarte con lisonjas para poder derribarte y destruirte mejor.

Pero ahora, reflexiona, y deja que entre en tu corazón, que a pesar de todo esto,
no le has respondido al Señor, sino más bien, le has faltado a Él,
has escogido tu propio camino y tu propia gloria, en lugar del camino y la gloria de Él,
y no has cumplido Su propósito al levantarte.
Porque no has soltado las ataduras de crueldad, no has liberado al oprimido,
no has quitado la opresión de la espalda de los pobres, no has regulado las leyes,
ni permitido la libertad de consciencia.
Por el contrario, estos dominios están llenos de cruel opresión,
y los pobres gimen por todas partes bajo la pesada mano de injusticia.
Los necesitados son pisoteados y los oprimidos claman por liberación,
y están cerca de desfallecer en busca de la verdadera justicia y juicio.
El orgulloso se exalta a sí mismo contra el pobre,
y el altivo y rebelde desprecia al manso de la tierra,
y aquellos que se han separado de la iniquidad se han convertido en presa de los opresores.
Muchos sufren injusta y lamentablemente,
porque no pueden jurar en esta o aquella ocasión,
aunque en todos los casos dicen la verdad y obedecen los mandamientos de Cristo.
Muchos de estos son pisoteados con multas injustas impuestas sobre ellos,
y esto se debe a la corrupción de algunos que gobiernan bajo tu mando,
y no gobiernan para Dios como deberían. Algunos sufren largos y tediosos encarcelamientos,
y otros crueles azotes y abusos,
muchas veces en peligro de perder sus vidas en manos de malvados,
sólo por reprobar el pecado y clamar contra las abominaciones
de la época (contra las que las Escrituras también testifican),
en las calles y otros lugares.
Algunos han sido enviados a prisión después de haber sido capturados en las calles,
sin que se les haya acusado de ningún mal.
Otros han sido sacados de las reuniones pacíficas, y azotados y enviados a prisión,
sin que hayan transgredido ninguna ley, justa o injusta.
Algunos han sufrido mucho en prisión,
en manos de los crueles carceleros y sus sirvientes, al ser golpeados, amenazados,
inmovilizados con grilletes,
e impedidos de recibir las visitas de sus amigos para suplir sus necesidades;
otros han muerto en las prisiones, cuyas vidas no eran estimadas para ellos,
y cuya sangre será contada contra ti algún día.

Algunos han sufrido duras crueldades,
porque no podían reverenciar a las personas y hacer
una inclinación con su sombrero o rodilla;
y de estas crueldades no puedes ser completamente excusado ante los ojos de Dios,
porque son llevadas a cabo en tu nombre y bajo tu poder.
Reflexiona, amigo, y despierta al verdadero juicio,
y deja que el Señor examine tu corazón;
ten presente estas cosas para que puedas ser un instrumento para eliminar toda carga,
y al fin cumplir la voluntad de Dios.
¡Oh, despierta, despierta, y busca la gloria del Señor y no la tuya propia!
Si los hombres quisieran darte honores y altos títulos y tronos principescos,
no los tomes; porque lo que te exalta y te honra en el mundo,
te entregará al mundo y te derribará ante los ojos del mundo.
Esta es la palabra de Dios para ti:
¿Qué? ¿Será toda la nación hombres perjuros y tú serás causa de ello?
¿Transgredirás al edificar de nuevo lo que has destruido?
Presta atención a mis palabras y entiende mi discurso; no seas exaltado por el hombre,
no sea que el hombre te traicione.
Trata favorablemente y alivia al oprimido.
No te jactes, porque aunque el Señor te ha usado en Su mano, puede arrojarte de Su mano,
como se arroja una vara al fuego, si así lo quisiera.
Si Lo honras, Él te honrará, de lo contrario puede, sí,
y te confundirá y te hará tan débil como agua delante de Él.

Su amor respira para ti a través de mi corazón. Él desea tu felicidad,
si tú no la desprecias voluntariamente al exaltarte a ti mismo,
buscar tu propia gloria y endurecer tu corazón contra el clamor del pobre.
Me sentí movido a poner esto delante de ti con un corazón compasivo, yo que soy tu amigo,
no con adulación, sino con un corazón recto; te deseo lo mejor en el Señor.

[.signed-section-signature]
Edward Burrough.

--

Lo que Edward Burrough menciona en la primera parte de esta carta,
sobre las penosas cargas y opresiones que estaban puestas sobre los justos,
parece referirse principalmente a los diezmos con
los que los sacerdotes extorsionaban a los Cuáqueros,
de modo que muchos habían sido reducidos a la pobreza.
La crueldad de esto no era desconocida por Cromwell,
porque cuando estaba a punto de pelear contra sus enemigos, cerca de Dunbar, en Escocia,
dijo en su oración a Dios, que si al Señor le placía liberarlo en ese momento,
él quitaría la gran opresión de los diezmos.
Pero él nunca cumplió esa promesa,
sino que se dejó llevar por las adulaciones de sus maestros.
Por tanto,
fue por una gran razón que Edward Burrough puso esta penosa opresión delante
de él. Una copia de dicha carta (de la que sólo una parte está insertada aquí
para evitar la redundancia) fue entregada en las manos de Oliver Cromwell,
el tercer mes de este año. El siguiente mes Edward Burrough habló con él acerca de esto,
y Cromwell le dijo que, en efecto,
toda la persecución y crueldad estaba contra su designio,
y que no era culpable de esas persecuciones que actuaban
injustamente sobre los amigos de Burrough.
Esto hizo que Edward B. le escribiera de nuevo y le dijera:

[.embedded-content-document.letter]
--

Piensa cuál es la razón, el por qué lo que dices que deseas que no se haga, ya está hecho.
¿Acaso no es para complacer a los hombres?
¿No manifiestas así que estás más dispuesto a complacer
a los falsos maestros y a los hombres malvados de esta nación,
que a reconocer al pueblo de Dios aliviándolos y
relevándolos de sus crueles cargas y opresiones,
impuestas sobre ellos por hombres injustos?
Porque una palabra de tu boca,
o un gesto de tu rostro en disgusto a estas crueles e injustas persecuciones,
ataría las manos de muchos hombres sanguinarios.
Por tanto, reflexiona: Tú no estás limpio ante los ojos del Señor Dios,
de estas maldades que son ejecutadas bajo tu poder y en tu nombre.
Porque tú sabes de algunos en esta ciudad, y en otros lugares,
a quienes todos reconocen como hombres justos,
que sufren encarcelamientos y la pérdida de sus libertades,
porque no pueden jurar por un asunto de consciencia,
y que muchos otros en esta nación están sufriendo cruel trato por similares motivos;
es decir, por hacer el bien y no el mal.
Tú podrías quitar esta opresión y aliviar los injustos sufrimientos,
con una simple palabra de tu boca o pluma.

Y con respecto a la luz de Cristo (en la que tropiezas),
por medio de la cual todo hombre que viene al mundo es alumbrado, en resumen digo:
Esta luz te es dada de Dios, y tú debes reconocerla como tú único maestro,
por medio de ella recibir del Padre y ser guiado por ella en todas las cosas,
si es que quieres heredar el reino de Dios.

El reino de Cristo está siendo establecido por medio de Su propio poder,
y todos deben inclinarse y sujetarse a dicho reino.
Él no necesita nada de tu política, ni de la fuerza de tu brazo para hacerlo avanzar;
sin embargo, no desea que tú resultes ser un enemigo abierto de este, al hacer,
o permitir que se haga,
crueldad e injusticia contra los que el Señor está
redimiendo del mundo y sujetando a Su reino,
y te vuelvas como aquellos que no quieren entrar, ni permiten que otros entren.
¡Por tanto, levántate de tu sueño y no duermas en la gloria y honor de este mundo.
No te dejes vencer por los placeres de este mundo,
ni por los títulos lisonjeros de los hombres.
No le hagas guiños a la crueldad y opresión que ejecutan algunos que se refugian
debajo de ti y hacen de tu nombre un manto de maldad contra los rectos!

Reflexiona, digo, recapacita y cambia tu mente y tu corazón;
no sea que habiendo olvidado a Dios y Sus muchas liberaciones,
seas excluido y contado para destrucción. Deseo que el Señor
te dé un entendimiento más perfecto de Sus caminos y juicios,
y que luches por la corona inmortal mediante la mansedumbre y justicia,
aliviando a los oprimidos,
mostrando misericordia por el pobre y eliminando
toda carga que está puesta sobre el inocente.
Este es el deseo del que es tu amigo y no quiere que seas coronado con deshonra,
al permitir que el pueblo de Dios sea oprimido en tu nombre,
lo cual ciertamente será tu derrocamiento si no lo eliminas,
volviendo y aliviando al oprimido.

[.signed-section-signature]
E+++.+++ Burrough.

--

Esta carta le fue entregada a Oliver Cromwell el cuarto mes,
y el siguiente mes Edward Burrough le escribió de nuevo,
diciéndole que el buen nombre "`protector`" era abusado
y alterado por la gran opresión que se ejecutaba en su nombre;
y que en lugar de protección, se ejecutaba y se cubría bajo ella una gran injusticia.
Además, que cuando varios jueces de paz y otros oficiales de confianza bajo su mando,
habían mostrado aprobación del pueblo llamado Cuáqueros,
habían sido expulsados de sus puestos,
aunque no se habían negado a servir a Cromwell y a la Mancomunidad,
ni se había probado contra ellos infidelidad a sus cargos.

Edward Burrough le escribió otra carta a Cromwell en Septiembre,
en la que le indicaba que él tenía muchos enemigos,
algunos de los cuales se estaban esforzando por destruirlo por cualquier medio,
sin considerar el peligro que podrían correr en el intento.
Y que, debido a que él continuaba oprimiendo a través de la tiranía o permitiéndola,
el Señor podría levantar al perverso para ser una plaga para la maldad,
y permitir que los opresores derrocaran las opresiones.
Le dijo que había otros (a saber,
los hombres de la Quinta Monarquía) que secretamente murmuraban contra él y lo envidiaban,
no siendo amigos de su gobierno,
y alegando haber sido expulsados y rechazados sin una causa justa.
"`Y en cuanto a nosotros,`" le dijo,
"`¿cómo podemos mencionarte en nuestras oraciones a Dios,
si no es para ser liberados de ti,
pues diaria e injustamente sufrimos por ti o debido a ti?
O,
¿cómo podemos ser amigos de ese gobierno bajo el
cual diariamente sufrimos cosas tan duras y crueles,
como la pérdida de nuestra libertad y propiedades,
y estamos en peligro de muerte también?`"

A principios de este año Christopher Birkhead llegó a Zealand, tras estar en Rochelle,
Francia.
Aquí, después de hablar y escribir contra la religión Católica,
fue encarcelado e interrogado por el obispo; algunos lo habrían hecho quemar,
pero el juez penal lo absolvió. Al final del mes llamado Febrero llegó a Middleburgh,
en Zealand, y fue a la congregación inglesa,
y cuando el predicador William Spanke había predicado tres cuartos de hora, dijo:
"`Amigos, el apóstol dice que todos podemos profetizar, uno por uno;
que dos o tres profetas pueden hablar y los demás juzgar;
y que si algo le es revelado a otro que está sentado, que el primero se calle.`"^
footnote:[1 Corintios 14:29-30]
Esta manera de hablar causó un gran revuelo en la congregación, y más,
porque él estaba en el lugar donde las mujeres estaban acostumbradas a sentarse.
Por tanto,
fue aprehendido por orden de los magistrados e interrogado
en presencia de algunos de los predicadores públicos.

Cuando le preguntaron cuál era su nombre, respondió que su nombre, según la carne,
era Christopher Birkhead.
Luego le preguntaron si tenía otro nombre.
Su respuesta fue: "`Sí, escrito en el libro de la vida del Cordero.`"
Cuando le preguntaron cuál era ese nombre, respondió:
"`Nadie lo conoce sino el que lo tiene.`"
Ante lo cual fue dicho: "`Pues, si lo tienes, dínoslo.`"
"`No,`" replicó él, "`léanlo, si han visto el libro del Cordero abierto;
a mí me está prohibido decirlo.`"
Luego, el maestro inglés, Spanke,
le preguntó si él había visto el libro del Cordero abierto.
Y él respondió: "`Sí.`" La siguiente pregunta fue, si él lo había abierto.
"`No,`" dijo Birkhead, "`el Cordero lo hace.`"
Entonces Spanke le preguntó si su nombre en el libro
del Cordero no era Jesús. "`No,`" dijo Birkhead,
"`ese es el nombre del Cordero.`"
Spanke le hizo otras preguntas para atraparlo,
y después fue interrogado por los magistrados con respecto al lugar de su domicilio,
su vocación u oficio, etc.
Luego le preguntaron a Spanke qué tenía que decir contra C. Birkhead,
entonces relató lo sucedido en la congregación. Le
hicieron varias preguntas con respecto a esto,
pero como C. Birkhead no entendía holandés,
y conocía el idioma francés de manera imperfecta,
objetó que no podía responder plenamente por sí mismo como deseaba.

También le preguntaron si alguien más había llegado
con él. Y le fue ordenado decir la verdad.
A lo que él dijo, que Dios no le permitía mentir.
Entonces uno de los predicadores dijo que todos los hombres eran mentirosos.
A esto Birkhead replicó, que aunque todos los hombres eran mentirosos,
él conocía la liberación de la mentira.
Y al ser fuertemente afirmado que todos los hombres eran mentirosos,
Birkhead aprovechó para preguntarle a Spanke si él era un mentiroso.
Quien sin dudarlo respondió: "`Sí.`" Entonces Birkhead le dijo sin rodeos:
"`Entonces tú eres de tu padre el diablo.`"
Ahora bien,
como el asunto de James Nayler había ocasionado extraños
informes de los Cuáqueros en todas partes,
y Birkhead, por desconocimiento del idioma,
no podía responder cada objeción muy claramente, su ofensa, indudablemente,
se agravó aún más, y la conclusión fue,
que él tenía que ser confinado en la casa de corrección. Pero después
de algún tiempo fue liberado por intercesión de Heer Newport,
embajador de los Estados Generales de Inglaterra.

Creo que en este año, un tal George Baily llegó a Francia,
fue detenido y murió allí en prisión,
tras haber testificado celosamente contra el papado
y hablado audazmente contra la adoración de imágenes.

El regreso de William Ames este año a Amsterdam (y con él un tal Humble Thatcher,
de quien nunca supe que hubiera estado verdaderamente en comunión con los Cuáqueros),
causó cierta sospecha.
Pues Ames, que anteriormente había tenido un empleo militar,
era un hombre extraordinariamente valiente,
y parece que por esa época fue puesto un artículo
en la puerta de la casa de reunión inglesa,
aunque Ames declaró que no sabía nada de eso o quién era el autor.
Además, por ese tiempo,
el extraño asunto de James Nayler estaba siendo difundido en el extranjero
por medio de un libro publicado en forma impresa en Amsterdam,
junto con algunos otros panfletos que estaban llenos
de varias falsedades y abominables mentiras;
de modo que no es extraño que los magistrados, temiendo algún daño,
enviaran a llamar a Ames y Thatcher para que se presentaran delante de ellos,
y les ordenaran salir del pueblo en el término de veinticuatro horas.
No obstante, estando persuadidos de su propia inocencia, no obedecieron la orden.

Al comparecer de nuevo delante de los magistrados al día siguiente,
y no quitarse sus sombreros,
parece que dieron la impresión de que no reconocían la autoridad de los
magistrados (pues los Cuáqueros eran acusados por esto en la prensa pública,
y eran comparados con el tumultuoso grupo de los hombres de la Quinta Monarquía,
o con los Anabaptistas en Münster de la época anterior.^
footnote:[La Rebelión Anabaptista en Münster,
1534-1535]) Así que fueron mantenidos bajo custodia por algunos días,
y luego fueron conducidos de noche a través de la
puerta Regulars y desterrados de la ciudad.
Pero Williams Ames, al juzgar que no había cometido ningún mal,
al día siguiente regresó a la ciudad y pasó por el
gran mercado llamado '`la represa.`' Se informa,
que algunos magistrados viéndolo desde las ventanas de los tribunales,
caminar por la calle dijeron: "`Miren, ahí está el Cuáquero;
si nosotros tuviéramos la intención de martirizar hoy,
aquí tendríamos una oportunidad para hacerlo.`"
Parece, sin embargo, y no sin razón,
que fue considerado más seguro hacerle un guiño a esto,
porque aunque se esparcían por todo lado extraños reportes de los Cuáqueros,
no había prueba de su mal comportamiento ahí. Mientras tanto,
Ames se quedó un tiempo en el pueblo,
y la doctrina que él predicaba encontró una pequeña acogida,
incluso entre algunos de los universitarios.

Fue por este tiempo, que mis padres, Jacob Williamson Sewel,
de Utrecht (ciudadano libre y cirujano en Amsterdam), y su esposa Judith Zinspernning,
nacida en este pueblo, ambos miembros de la iglesia Flemish Baptists ahí,
fueron convencidos de la Verdad predicada por William Ames; ella,
después de haber tenido directas revelaciones,
que si alguna vez llegaba a ser una hija de Dios,
debía prestarle atención a esta luz que reprendía el pecado.
Ellos, con dos o tres más, fueron los primeros Cuáqueros ortodoxos en Amsterdam;
digo ortodoxos,
porque recuerdo muy bien el extraño tipo de gente que en ese tiempo acudía en masa a
las reuniones de los Cuáqueros en dicho país. Pero estas personas caprichosas,
al no ser sinceras de corazón,
sino más inclinadas a las novedades que a la verdadera piedad,
con el tiempo percibieron que no eran consideradas por los Cuáqueros.
También fueron contradichas por Ames y otros, por lo que finalmente,
después de muchos actos de extravagancia, dejaron a los Cuáqueros.

En la primera parte de este año, William Caton también llegó a Amsterdam.
Antes de salir de Inglaterra, había tenido una reunión en el lado este de Sussex,
el día llamado Martes de Carnaval,
en el que nunca antes había estado ninguno de sus amigos.
Pero la gente ahí, siendo ese día más grosera que de ordinario,
llegó a la casa con tambores, en una forma tan salvaje,
que parecía que querían derribarla.
Caton salió y les preguntó qué querían, ellos respondieron:
"`Cuáqueros,`" a lo cual él les respondió que él era uno.
Entonces les habló tan claramente y con tanto poder,
que el temor cayó sobre ellos y se retiraron con vergüenza y confusión.

Poco después se fue a Londres y de ahí a Holanda,
y habiendo llegado sano y salvo a Rotterdam, continuó hacia Amsterdam,
donde llegó justo a tiempo para detener la
indisciplina de algunos espíritus obstinados,
entre quienes, una mujer inglesa llamada Anne Garghil, no era la menos terca.
En realidad, la indisciplina de ella creció con el tiempo a tal grado,
que no permitía que William Ames predicara pacíficamente en la reunión,
sino que ponía sus manos violentamente sobre él; así que finalmente,
para deshacerse de ella,
Ames le pidió a un marinero inglés que estaba presente que se la llevara,
lo cual fue hecho efectivamente.
Todavía recuerdo bien, cuán altiva era y continuó siendo esa mujer.
William Caton también consiguió que se imprimieran algunos libros en Amsterdam,
a fin de evitar reportes perversos y maliciosos con respecto a los Cuáqueros;
luego fue con W. Ames a Zutphen en Gerderland, donde al encontrarse sólo con oposición,
regresó a Amsterdam, y de ahí, por Leyden y Hague, a Rotterdam; de allí fue a Zealand,
donde escribió el libro llamado [.book-title]#The Moderate Enquirer Resolved,#^
footnote:[Es decir, _Respuestas para el Buscador Sincero._]
tanto en latín como en inglés,
el cual luego fue traducido inadecuadamente al holandés. Después de una estadía,
Caton regresó de nuevo a Inglaterra y llegó a Londres,
donde la sociedad de sus amigos estaba en una condición próspera,
y muchos se estaban añadiendo a la iglesia.

En esta ciudad dejamos a G. Fox.
Aquí escribió varios artículos para abrir el entendimiento
de las personas y para la edificación de sus amigos.
De ahí viajó a Kent, Sussex y Surry, y al llegar a Basingstoke,
aunque las personas allí eran rudas, tuvo una reunión tranquila en el lugar; no obstante,
en la posada tuvo un problema con el posadero, que era un borracho.
Después llegó a Portsmouth, Exeter, Bristol y Gales, donde muchos fueron a oírlo.
En Brecknock estaba acompañado por Thomas Holmes,
quien fue el primer Cuáquero en predicar la doctrina de la luz interior en Gales,
y por John-ap-John,
quien tres años antes había sido enviado por un sacerdote al norte de Gales,
para investigar qué tipo de personas eran los Cuáqueros.
Ahí tuvo una gran reunión en el jardín de la '`casa
del campanario,`' donde había un sacerdote,
un tal Walter Jenkin, que había sido juez, y otro juez.
Allí predicó con tanta eficacia que muchos fueron convencidos,
y después de la reunión fue con Jenkin a la casa del otro juez, quien le dijo:
"`Hoy le has dado una gran satisfacción a las personas y
respondido todas las objeciones que tenían en sus mentes.`"
En Leominster tuvo una gran reunión, en la que el sacerdote Tombs puso oposición,
al decir que la luz de la que hablaba G. Fox no era más que la luz natural;
pero G. Fox afirmó lo contrario diciendo,
que él no había hablado de una luz diferente de la que había dado
testimonio Juan--"`La Palabra que estaba al principio con Dios,
La cual era Dios,
y que era la verdadera luz que alumbra a todo hombre que viene al mundo.`"

Al llegar G. Fox de este lugar a Tenby, mientras cabalgaba por la calle,
un juez de paz salió y le pidió que desmontara y se quedara en su casa, lo cual hizo.
El Primer-día de la semana tuvo una reunión ahí,
a la que llegaron el alcalde y su esposa, y varias otras personas importantes del pueblo.
John-ap-John, quien estaba en ese momento con G. Fox,
dejó la reunión y se fue a la '`casa del campanario,`'
y fue arrojado en prisión por el gobernador.
La mañana siguiente el gobernador envió a uno de sus oficiales a la casa del juez de paz,
para que buscara a G. Fox.
Esto afligió al alcalde y al juez, por lo que fueron donde el gobernador,
y poco tiempo después, G. Fox también fue con el oficial, y entrando dijo:
"`La paz sea en esta casa.`"
y antes de que el gobernador pudiera interrogarlo,
él le preguntó por qué había enviado a prisión a su amigo.
El gobernador respondió: "`Por estar con su sombrero puesto en la iglesia.`"
"`¿Por qué?,`" continuó G. Fox,
"`¿acaso no tenía el sacerdote dos gorras sobre su cabeza, una negra y otra blanca?`"
"`Estas son cosas frívolas,`" dijo el gobernador.
"`¿Por qué entonces enviaste a mi amigo a prisión por cosas tan frívolas?`"
dijo G. Fox.
Entonces el gobernador le preguntó si él creía en
la elección y la condenación?`" "`Sí,`" dijo él,
"`y tú estás en la condenación.`"

Esto enfureció tanto al gobernador que le dijo a G. Fox
que lo enviaría a prisión hasta que probara esto.
G+++.+++ Fox, para nada falto de palabras le dijo: "`Te lo probaré rápidamente,
si confiesas la verdad.`"
Entonces Fox le preguntó si la ira, furia,
rabia y persecución no eran señales de condenación. Porque
el nacido de la carne persigue al nacido del Espíritu;
y Cristo y Sus apóstoles nunca persiguieron ni encarcelaron a nadie.
Este sermón impactó tanto al gobernador,
que confesó justamente que él tenía demasiada ira,
precipitación y pasión en él. Esto hizo que G. Fox le dijera: "`Esaú,
el primer nacimiento, está levantado en ti, y no Jacob, el segundo nacimiento.`"
Esto alcanzó al hombre a tal punto, que confesó la Verdad,
y luego invitó a G. Fox a cenar con él y dejó a su amigo en libertad.
G+++.+++ Fox partió del pueblo con gran satisfacción,
y en varios otros lugares de Gales le ocurrieron algunos hechos inusuales;
y aunque la gente era ruda, algunos fueron convencidos.

Finalmente llegó a Lancaster, donde en la posada se encontró con el coronel West,
quien se alegró mucho de verlo.
Luego fue a Swarthmore, donde escribió algunas epístolas y otros artículos.
Después de haber permanecido ahí por unos días, se fue a otros lugares en el norte,
y luego a Escocia.
Ahí, viajando de pueblo en pueblo,
encontró gran oposición de parte de algunos sacerdotes,
porque en una asamblea habían redactado varios artículos, o maldiciones,
para que fueran leídas en sus '`casas el campanario,`' la primera de las cuales era:
"`Maldito el que dice que todo hombre tiene una luz
dentro de él suficiente para conducirlo a la salvación;
y que todo el pueblo diga: '`Amén.`'`" Un pastor independiente,
predicando un día contra los Cuáqueros y la luz, llamándola '`luz natural,`' la maldijo,
y cayó como muerto en su púlpito.
La gente lo sacó, y arrojándole agua fuertemente, lo volvieron a la vida,
pero quedó como desconectado, y uno de sus oyentes dijo,
que desde ese momento nunca recuperó sus sentidos.

G+++.+++ Fox llegó en Octubre a Edinburgh, donde fue citado a comparecer ante el consejo,
quienes, con cierta cortesía,
le dijeron que debía salir de Escocia en el término de una semana a partir de ese día;
contra lo cual no sólo habló sino que también escribió. Mientras G. Fox estaba en Escocia,
sus amigos ahí estaban siendo llevados a una gran estrechez; pues,
tras haber sido excomulgados por los maestros Presbiterianos,
se mandó que nadie debía comprar o vender, comer o beber, con ellos.
Sucedió entonces,
que algunos de los llamados Cuáqueros que compraban pan y otras provisiones de sus vecinos,
encontraron que muchos que estaban asustados por las maldiciones de sus sacerdotes,
corrían a buscarlas de nuevo.
Pero el coronel Ashton, un juez de paz, le puso alto a estas acciones,
y después de ser convencido de la Verdad, estableció una reunión en su casa,
declaró la Verdad, y vivió y murió en ella.

Luego G. Fox viajó por casi toda Escocia,
y tuvo algunas buenas oportunidad para declarar el evangelio,
siendo escuchado a menudo con satisfacción por los soldados ingleses;
pero los escoceses generalmente prestaban poca atención. También fue entre los montañeses,
que era un pueblo malicioso.
Al regresar finalmente a Leith,
el posadero le dijo que el consejo había entregado órdenes para capturarlo,
porque él no había salido del país después de que habían
expirado los siete días. Algunos otros le dijeron lo mismo,
a quienes él les dijo:
"`¿Por qué me hablan de sus órdenes de aprehensión
contra mí? Si hubiera un carro lleno de ellas,
no les haría caso, porque el poder del Señor está sobre todos ellos.`"
De Leith se fue a Edinburgh de nuevo, y llegó a la posada donde se había alojado antes,
y ningún hombre se metió con él. Alexander Parker y Robert Widders también estaban ahí,
y decidió ir con Parker a Johnston,
de cuyo pueblo había sido sacado un tiempo antes por soldados.
Entró a Johnston, justo cuando estaban subiendo el puente levadizo,
y los oficiales y soldados nunca lo interrogaron.

Al llegar a la casa del capitán Davenport, de la que lo habían sacado antes,
encontró allí muchos oficiales,
quienes levantando sus manos se asombraron de que hubiera regresado,
pero él les dijo que el Señor Dios lo había enviado nuevamente entre ellos.
Entonces los Bautistas le enviaron una carta a modo de desafío,
en la que le decían que ellos conversarían de nuevo con él al día siguiente.
Y él les envió el mensaje de que se reuniría con ellos en cierta casa,
como a media milla del pueblo, a tal hora.
Porque pensó que si se quedaba en el pueblo para hablar, ellos,
con el pretexto de conversar con él,
podrían haber incitado a las personas para que lo sacaran del pueblo otra vez,
como habían hecho antes.
A la hora señalada se dirigió al lugar, acompañado por el capitán Davenport y su hijo,
y ahí permaneció unas horas, pero ningún Bautista llegó,
por lo que la intención de ellos fue adecuadamente descubierta.
Desilusionado, regresó a Edinburgh otra vez, y por decirlo así,
atravesó el pueblo '`metiéndose en la boca de león.`'

Al día siguiente, que era el Primer-día, fue a la reunión en la ciudad,
y muchos oficiales y soldados llegaron, y todo estuvo tranquilo.
Al día siguiente se fue a Dunbar,
donde caminando con uno o dos amigos en el jardín de la '`casa del campanario,`'
se encontró con uno de los hombres importantes del pueblo,
y le pidió a uno de sus amigos que le dijera que
alrededor de la novena hora de la mañana siguiente,
iba a haber una reunión ahí del pueblo de Dios, llamado Cuáqueros,
de la que él quería que avisara a la gente del pueblo.
A esto el hombre dijo, que ellos iban a tener una conferencia ahí a la novena hora,
pero que se podía realizar una reunión allí a la octava hora, si así lo deseaban.
G+++.+++ Fox pensando que esto no era inconveniente, le pidió que diera la noticia.
Y así, por la mañana llegaron muchos, tanto pobres como ricos,
y un '`capitán del caballo`'^
footnote:['`Capitán del caballo`' es el rango de un oficial de la Caballería Británica;
dicho capitán está a cargo de una compañía de jinetes y su contingente de apoyo.]
que estaba acuartelado en el pueblo, llegó también con sus soldados.
G+++.+++ Fox le predicó a este grupo,
y después de un tiempo llegó el sacerdote y entró en la '`casa del campanario`';
sin embargo,
como G. Fox y su amigo estaban en el jardín de la '`casa
del campanario,`' la mayoría de la gente se quedó con ellos;
de modo que el sacerdote, al tener unos pocos oyentes, acortó el servicio y salió,
permaneció un rato y oyó a G. Fox, y luego se fue.
Esta fue la última reunión que tuvo en Escocia,
y luego entendió que su labor no había sido en vano,
sino que el número de creyentes había aumentado.
Entonces partió de Dunbar y llegó a Berwick, en Northumberland, y de ahí a Newcastle,
donde lo dejaremos por un tiempo, y regreso a Nueva Inglaterra.

Hemos visto antes,
que allí se había promulgado una ley para impedir
que los Cuáqueros entraran en Massachusetts Bay Colony.
Encuentro que las primeras que llegaron después de esto fueron, Anne Burden, una viuda,
cuyo motivo para haber ido, era cobrar unas deudas en aquellos lugares que le debían;
y Mary Dyer, de Rhode Island,
quien antes de llegar no sabía nada de lo que había
sido hecho allí con respecto a los Cuáqueros.
Estas dos fueron encarceladas, y cuando William Dyer (el esposo de Mary) se enteró,
llegó de Rhode Island, y no pudo obtener su liberación sin pasar por muchas angustias,
al ser obligado, so pena de castigo, a no alojarla en ningún pueblo de la colonia,
ni permitir que nadie hablara con ella.^
footnote:[Esto es una muestra evidente de que William Dyer no era
entonces miembro de la sociedad de los llamados Cuáqueros,
porque de lo contrario, no se habría sometido a tal obligación,
ni habría podido evitar ser encerrado en prisión.]

En cuanto a Anne Burden, aunque estaba enferma,
estuvo en prisión alrededor de un cuarto de año. Mientras estaba bajo esta restricción,
algunos personas de corazón tierno habían cobrado sus deudas
por un valor de unas treinta libras en bienes,
y cuando finalmente la iban a enviar lejos,
ella quería tener la libertad de detenerse en Barbados, de camino a Inglaterra,
porque sus bienes no eran aptos para Inglaterra.
Ahora bien, a pesar de lo razonable de su petición,
el capitán del barco estaba obligado a llevarla directo
a Inglaterra sin los bienes por los que ella había ido ahí,
excepto por el valor de seis chelines,
que un hombre honrado le había dado por una vieja cuenta.
Cuando el capitán del barco les preguntó a los magistrados
quién pagaría el pasaje de ella,
le mandaron que cogiera de los bienes de ella tanto como correspondiera al pasaje.
Pero él era demasiado honesto para hacerlo,
estando persuadido de que ella no dejaría que perdiera,
aunque él no podía obligarla a pagar, sabiendo que ella se iba en contra de su voluntad.
Sin embargo, a pesar de todo esto, ella le pagó en Londres.
Después de que ella se marchó a Inglaterra,
cuando el que tenía la confianza de su esposo quiso trasladar sus bienes a Barbados,
esta gente codiciosa le cobró el valor de seis libras
y diez chelines por el pasaje de ella a Inglaterra,
por el que ellos no habían pagado nada, y luego siete chelines más,
por un bote de alquiler que la había llevado a bordo,
aunque el capitán del barco le había ofrecido al gobernador llevarla en su propio bote.
Y además de esto, tomaron catorce chelines para el carcelero,
a pesar de que ella no le debía nada.
Ahora bien,
aunque esta viuda había hecho un viaje tan largo para recuperar algo de lo que le debían,
para aliviarse ella y aliviar a los niños huérfanos de padre,
después de tres años no le había llegado nada a sus manos;
y nunca supe si ella había logrado conseguir algo desde entonces.

La siguiente de los Cuáqueros que llegó a Boston fue Mary Clark, quien,
después de dejar a su esposo, John Clark, un sastre comerciante,
con sus hijos en Londres,
llegó para advertirles a estos perseguidores que desistieran de su iniquidad.
Pero después de que había entregado su mensaje,
fue recompensada sin piedad con veinte azotes en su espalda desnuda,
con un látigo de tres cuerdas,
y mantenida prisionera por casi doce semanas en la temporada de invierno.
Las cuerdas de estos látigos eran comúnmente del grosor del dedo meñique de un hombre,
y cada una tenía nudos al final; y el palo a veces era tan largo,
que el verdugo usaba ambas manos para golpear con más fuerza.

Los siguientes en llegar fueron Christopher Holder y John Copeland,
quienes había sido desterrados antes; y cuando llegaron a Salem,
un pueblo de la misma colonia, Holder habló unas pocas palabras en la reunión de ellos,
después de que el sacerdote había terminado.
Pero fue halado hacia atrás por el cabello,
y le metieron un guante y un pañuelo en su boca, y así fue echado junto con su compañero.
Al día siguiente fueron transportados a Boston,
donde cada uno recibió treinta azotes con un látigo de tres cuerdas anudadas,
y el verdugo, aparentemente,
medía su distancia y recogía sus golpes con la mayor fuerza
que podía. Esto les cortó la carne con tanta crueldad,
que una mujer que estaba presente cayó como muerta.
Luego fueron encerrados en prisión, donde el carcelero los mantuvo tres días sin comida,
ni siquiera un trago de agua, y no se le permitió a nadie que fueran a hablar con ellos.
Así fueron mantenidos en prisión nueve semanas,
teniendo que acostarse sobre tablas sin colchón o paja,
y sin un fuego en la fría temporada de invierno.
Samuel Shattock de Salem,
quien se había esforzado para evitar que le metieran el
guante y el pañuelo a Christopler Holder en la boca,
para que no se ahogara, también fue llevado a Boston y encarcelado,
hasta que dio una fianza de veinte libras para comparecer
en las siguientes sesiones de la corte,
y se le mandó que no fuera a ninguna reunión de los Cuáqueros,

La carrera de esta crueldad no se detuvo aquí,
pues Lawrence Southick y su esposa Cassandra,
miembros de la iglesia pública de Salem (y una pareja anciana y sobria),
después de haberles dado hospitalidad a los mencionados C. Holder y J. Copeland,
fueron encarcelados y enviados a Boston.
Una vez que Lawrence fue liberado, su esposa fue mantenida prisionera siete semanas,
y luego multada con cuarenta chelines por poseer
un artículo de exhortación escrito por Holder y Copeland.

El siguiente en llegar de Inglaterra,
estando bajo la carga del Señor de ir a esa tierra de persecución, fue Richard Dowdney,
quien fue capturado en Dedham y llevado a Boston,
un condado en el que nunca había estado.
Sin embargo, ellos no lo perdonaron, sino que le dieron treinta azotes también,
como a los dos hombres anteriores.
Y después de veinte días de cárcel, fue enviado lejos junto con Holder y Copeland,
después de haber sido amenazados con cortarles las orejas si regresaban.
Estos crueles tratos afectaron tanto a muchos habitantes,
que algunos se retiraron de las asambleas religiosas públicas,
y al reunirse por su cuenta en silencio los Primeros-días de la semana,
fueron multados con cinco chelines semanales y enviados
a prisión. A los primeros que les tocó la suerte de esto,
fueron los mencionados Lawrence y Cassandra Southick, y su hijo Josiah,
a quienes llevaron a Boston.
Allí fueron enviados a la casa de corrección (a pesar de la vejez de los padres),
y azotados con cuerdas en la estación más fría del año. También
les quitaron el valor de cuatro libras y trece chelines,
por no asistir a la iglesia.

Dejo Nueva Inglaterra por un tiempo y cambio de dirección. En este año,
aproximadamente a finales del verano,
cierto joven llamado George Robinson se sintió movido a viajar
a Jerusalén. Para ello abordó un barco con destino de Livorno,
en Italia, donde después de estar cerca de dos semanas,
siendo visitado diariamente por ingleses y otros,
se fue en un barco francés hacia St. John D`'Acre, anteriormente llamada Ptolemaida,
una ciudad en Asia que limita con el mar Mediterráneo, cerca de Palestina.
De ahí, después de estar alojado por unos ocho días en la casa de un comerciante francés,
se fue en una nave con destino a Jafa o Jope.
Lo que le ocurrió en el camino con algunos turcos,
quienes le demandaban un tributo irrazonable, lo pasaré de lado; pero en esa ocasión,
cierto armenio que vio su comportamiento manso dijo,
que él era un buen Cristiano y se portó muy amablemente
con él. Después de arribar a Jafa,
fue a Ramot, pero como los frailes de Jerusalén habían oído de su llegada,
dieron órdenes de detenerlo, lo que fue hecho como corresponde.
Después de haber estado encerrado alrededor de un día, llegó un anciano turco,
un hombre de gran reputación, y lo llevó a su casa y lo hospedó cortésmente.
Después de cuatro o cinco días llegó de Jerusalén un fraile irlandés,
con quien entabló una conversación de asuntos religiosos,
en la que el fraile se comportó amablemente al principio,
pero después le dijo que esa no era la razón por la que había ido a verlo,
sino que había sido enviado por sus hermanos, los frailes en Jerusalén,
para plantearle unos asuntos: 1. Si prometía que al llegar a Jerusalén,
visitaría los lugares sagrados como lo hacían otros peregrinos.
2+++.+++ Si pagaría tanto dinero como solían hacerlo los peregrinos.
3+++.+++ Si se vestiría con cierto atuendo como era usual con los peregrinos.
4+++.+++ Que no debía hablar nada contra las leyes de los turcos.
5+++.+++ Que cuando llegara a Jerusalén, no debía hablar nada de religión.

Como no estuvo dispuesto a cumplir con dicha promesa,
fue llevado por el fraile irlandés (con una guardia a caballo
y hombres a pie que había llevado con él) de regreso a Jafa.
Ahí se le obligó a embarcarse en una nave con destino a St. John D`'Arce,
donde después de llegar un comerciante francés llamado Surrubi,
lo llevó a su casa y lo alojó alrededor de tres semanas.
Este hombre lo hospedó muy amablemente,
y algunas veces dijo que había sido obra del Señor: "`Porque,`" dijo él,
"`cuando mis propios compatriotas vienen a mí, significa poco,
pero a ti te recibo de buena gana.`"

Después de mucha dificultad,
Robinson tuvo oportunidad (por la ayuda de dicho comerciante
francés que era un anciano) de regresar a Jafa.
De ahí continuó su viaje a pie, y en el camino se encontró con tres hombres,
dos de ellos iban montados en asnos y el otro iba a pie.
Estos le pidieron dinero, mientras uno lo apuntaba con una pistola en el pecho,
y otro le metía las manos en sus bolsillos y sacaba algunas cosas.
Robinson permitió todo eso sin oposición;
el hombre que había sacado sus cosas se las devolvió, y luego uno de los tres,
tomándolo de la mano, lo condujo un poco en su camino de manera amigable, y lo dejaron.

Finalmente llegó a Ramot, donde su presencia fue rápidamente notada,
y dos que pertenecían a los frailes lo agarraron y se lo llevaron apresuradamente.
Luego dos turcos lo tomaron de los frailes,
y uno tomándolo de un brazo y el otro del otro brazo,
lo llevaron a la mezquita o templo turco.
Así, al entrar inocentemente, muchas personas entraron en masa,
y también algunos sacerdotes musulmanes, quienes, tras sentarlo,
le preguntaron si él se convertiría a la religión Musulmana.
Pero al ver que se negaba, lo presionaron más,
haciéndole grandes promesas y diciéndole que no tenía
que temer lo que los Cristianos le pudieran hacer.
Sin embargo,
él respondió que no podía volverse a la religión
de ellos aunque le ofrecieran el mundo entero.
Pero ellos continuaron luchando,
y querían que él levantara uno de sus dedos como señal de que los aceptaba.
Un hombre le pidió que dijera: "`Cristo es malo;`" pero él respondió,
que él sabía que era bueno y que él era Su siervo.
Entonces algunos dijeron enfurecidos, que si no se volvía a su religión debía morir.
A esto replicó, que él prefería morir que volverse a la religión de ellos,
y se le respondió, que efectivamente debía morir.
Y así, por orden de ellos,
el verdugo lo arrastró al lugar donde se esperaba que fuera
quemado hasta la muerte con estiércol de camello.
Ahí lo sentaron en el suelo como una oveja entre lobos.
Mientras estaba sentado con su mente vuelta al Señor,
los turcos empezaron a discutir entre ellos, y mientras discrepaban, un anciano turco,
sobrio e importante, se acercó a él y le dijo, que si él se volvía de su religión o no,
no moriría. Luego fue llevado delante de los sacerdotes de nuevo y le preguntaron:
"`¿Te volverás de tu religión?`" Él respondió:
"`No.`" Entonces ellos registraron en un libro que no era Católico Romano,
sino de otra religión, porque aunque él había negado ser Católico,
había admitido que era Cristiano.

Como los turcos estaban más tranquilos,
el mencionado anciano les ordenó a sus sirvientes que llevaran a Robinson a su casa,
donde fue hospedado de manera amigable,
y pronto se dio cuenta de que los frailes habían conspirado contra él,
porque no había entrado a la mezquita por su propia voluntad,
sino que había sido llevado; sin embargo,
el cielo lo preservó. Después de estar cuatro o cinco días en la casa del anciano turco,
llegó una guardia de jinetes contratados por los frailes, para llevarlo a Gaza,
porque ellos habían hablado previamente contra él, con el '`bashaw`'^
footnote:[Un hombre de alto rango u oficio en países bajo el dominio turco.]
de ese lugar.
Pero cuando Robinson llegó, las cosas dieron un giro inesperado para ellos,
ya que como los turcos le habían dado a conocer al
'`bashaw`' los malvados planes de los frailes,
este no sólo los hizo pagar una multa considerable,
sino que también les ordenó que transportaran a Robinson
a salvo a Jerusalén. Mientras estuvo en Gaza,
fue visitado por muchos turcos, griegos y armenios; estos últimos,
al oír que era Cristiano y que había escogido morir antes que volverse de su religión,
se volvieron muy cordiales, al igual que los turcos,
y también los judíos se mostraron moderados con él. Luego,
según la antes mencionada orden del '`bashaw,`' fue llevado a Jerusalén,
y ahí por indicación de los frailes, fue llevado a su convento,
donde al principio se mostraron aparentemente amorosos con él. Uno de
ellos confesó que ya tenían señal evidente de que él era un buen Cristiano,
porque había atravesado persecución y sufrimiento,
y las cosas que se habían dicho en su perjuicio, resultaron ser falsas.
Robinson le dijo al fraile que él y sus hermanos habían sido la causa de sus sufrimientos,
y habían resistido su llegada a Jerusalén. A esto otro replicó,
que el fraile inglés les había escrito informándoles mal,
y los había hecho hacer lo que habían hecho,
y que ahora querían que él pasara por alto esas cosas,
viendo que había llegado de manera tan milagrosa: "`Porque,`" (continuó el fraile),
"`fue obra del Señor llevarte a través de esto,
y puedes alabar a Dios por haberte preservado.`"

A la mañana siguiente llegó un fraile donde él y le preguntó,
si él se convertiría en un niño obediente e iría a visitar los lugares sagrados,
según la costumbre de ellos.
Él le respondió: "`No.`" Entonces el fraile le dijo:
"`Mientras que otros dan grandes sumas de dinero para verlas, tú las verías gratis.`"
Pero Robinson contestó: "`No los visitaré a tu modo,
porque al hacerlo pecaría contra Dios.`"
Esto no le agradó al fraile,
pero le dijo que ellos lo honrarían tanto como honraban
a cualquier inglés que llegaba ahí,
si se conformaba a ellos.
Pero Robinson continuó inamovible y dijo que no se conformaría,
y que en cuanto al honor de ellos, no le importaba.
Entonces el fraile se enojó y dijo que ellos lo harían
un ejemplo para todos los ingleses que llegaran.
A lo que Robinson replicó: "`Escojo tu deshonra en lugar de tu honra.`"
Al ver el fraile que no podía prevalecer, se fue enojado,
y al poco tiempo volvió. Esta vez estaban presentes otros frailes,
y uno le preguntó si visitaría la iglesia de ellos, el santo sepulcro y Belén,
junto con el resto de los lugares sagrados como lo hacían otros peregrinos.
Pero él les dijo que en ese momento no tenía razón para visitarlos,
y que no los visitaría del todo a la manera de ellos, es decir, para adorarlos.
Entonces uno le dijo:
"`¡Cómo puedes ser un siervo de Dios y no ir a visitar
los lugares donde moraron los hombres santos de Dios!`"
A lo cual él contestó, que ellos,
bajo la pretensión de servir a Dios visitando los
lugares donde moraban los hombres santos,
se oponían al camino y resistían la vida en la que
los hombres santos de Dios habían vivido y caminado.
Entonces uno de los frailes dijo: "`¿Para qué nos predicas?`"
Y él respondió,
que él deseaba que ellos se apartaran de las malas prácticas en las que vivían,
porque de lo contrario, la ira del Todopoderoso se encendería contra ellos.
Pero a ellos no les gustó para nada ese discurso, y le dijeron:
"`Si no vas a visitar los mencionados lugares, debes pagar veinticinco dólares,^
footnote:[Moneda que circulaba en varios países de Europa,
diferente al dólar actual de Estados Unidos.]
según la costumbre de los que los visitan, porque se les debe pagar a los turcos,
ya sea que los visites o no.
Pero si los visitas, nosotros lo pagaremos por ti.`"
A esto él indicó, que no podía someterse a términos tan irrazonables.

Entonces lo llevaron delante de una autoridad turca del lugar,
quien le hizo varias preguntas, a todas las cuales les dio respuestas sobrias.
Y mientras estaban discutiendo acerca de la adoración de los Cristianos,
el turco también le preguntó la razón por la que había llegado a Jerusalén. Él le respondió,
que le había sido encomendado por el Señor Dios del cielo y de la tierra que fuera allí;
que el grande y tierno amor de Dios se había manifestado al visitarlos,
y que Sus compasivas misericordias eran tales,
que Él deseaba reunirlos en el '`día de Su congregación.`' Este
era el mensaje que Robinson creía tener del Señor para declararles,
ya fuera que lo oyeran o lo rechazaran.
Después escribió que tras haber aliviado su consciencia,
había encontrado gran paz para con el Señor, y por tanto,
había engrandecido Su glorioso nombre,
pues había ido con él y lo había preservado en muchas pruebas.
Porque los frailes, que habían pretendido hacerle daño,
recibieron la orden de los turcos de llevarlo sano y salvo, y libre de cargos, a Ramla.
Aquí lo dejo, porque no encuentro cómo regresó a casa,
pero me parece que él volvió a salvo, por el relato que publicó después de sus viajes.
