== Capítulo 8

[.section-date]
1657--1659

[.chapter-synopsis]
* G. Fox y el hombre a punto de fundar un Colegio para hacer Ministros
* Reunión anual de Bedfordshire
* Disputa entre Jesuitas y Cuáqueros
* Cartas al protector sobre los Amigos y sus sufrimientos
* Lady Claypole
* Discurso de Fox sobre los "`ayunos`"
* Muchos Amigos se ofrecen a ir a la cárcel en lugar de sus hermanos
* Se anuncia la disolución del Parlamento
* Cartas de E. Burrough al protector y a su familia
* Muerte de O. Cromwell
* R. Cromwell proclamado protector
* Exposición de los sufrimientos de los Amigos por parte de E. Burrough
* Gran persecución
* Restauración prevista
* Funeral de Cromwell
* R. Cromwell renuncia al protectorado
* Barbaridades contra los Amigos en Nueva Inglaterra
* Leyes crueles
* W. Brend y W. Leddra en Boston
* Trato inhumano contra W. Brend
* Comparación de los Cuáqueros con los lobos
* Corte de orejas a los Cuáqueros.

Finalizado el año, vuelvo a G. Fox, a quien dejamos en Newcastle.
Mientras estaba ahí, él y Anthony Pearson, visitaron a algunos de los concejales,
y entre ellos uno llamado Ledger,
que (al igual que los sacerdotes) se había jactado de que
los Cuáqueros no llegarían a las grandes ciudades,
sino que sólo vivirían en los campos como mariposas.
G+++.+++ Fox quería tener una reunión entre ellos, pero no accedieron a ello.
Por lo tanto, le preguntó a Ledger, si ellos no habían llamado a sus amigos mariposas,
al decir que ellos no llegarían a las grandes ciudades.
"`Pero,`" le dijo,
"`ya hemos entrado en tu ciudad y ustedes no quieren acudir a una reunión con nosotros,
¿quiénes son las mariposas ahora?`"
Al no obtener permiso para una reunión pública,
G+++.+++ Fox gestionó una pequeña reunión entre sus amigos y algunas personas amistosas,
en Gateside.

Viajando de ahí y atravesando Northumberland y Bishoprick, llegó a Durham,
adonde había llegado un hombre para fundar una universidad,
con el fin de formar ministros para Cristo,
según dijo él. G. Fox entabló una conversación con este hombre y le dijo,
que enseñarles a los hombres hebreo, griego, latín y las siete artes,
no era la manera de formar ministros para Cristo.
Porque las lenguas habían comenzado en Babel,
y para los griegos que hablaban griego como su lengua materna,
la predicación de la cruz había sido insensatez.
Para los judíos que hablaban hebreo como su lengua materna,
Cristo había sido una piedra de tropiezo.
En cuanto a los romanos, que hablaban latín, habían perseguido a los cristianos;
y Pilato, uno de los gobernadores romanos, había puesto el hebreo,
griego y latín por encima de Cristo cuando lo crucificó. Y que así,
las lenguas que habían comenzado en Babel,
habían sido puestas por encima de Cristo la Palabra.
Y que el apóstol Juan, que había predicado la Palabra que estaba en el principio,
había dicho, que la bestia y la ramera tenían poder sobre los idiomas y lenguas,
y que ellas eran como aguas, y se encontraban en la Babilonia espiritual,
pues habían comenzado en Babel;
y que los perseguidores de Cristo habían puesto lenguas sobre Él,
cuando había sido crucificado por ellos.
"`¿Piensas,`" le dijo G. Fox al hombre,
"`formar ministros para Cristo por medio de estas lenguas naturales y confusas,
que surgieron en Babel, que son admiradas en Babilonia y fueron colocadas sobre Cristo,
la vida, por un perseguidor?`"
El hombre, un poco desconcertado por esto admitió muchas cosas dichas por G. Fox.
Luego, le mostró además,
que el propio Cristo había formado a Sus discípulos y les había dado dones,
y les había pedido que oraran al Señor de la mies, que enviara obreros.
Le mostró que Pedro y Juan,
aunque indoctos e ignorantes en lo que se refiere al aprendizaje escolar,
habían predicado a Cristo la Palabra, la cual estaba en el principio antes que Babel.
Que Pablo también había sido hecho apóstol, no de hombre, ni por un hombre,
sino por Jesucristo, quien es el mismo hoy, y así Su evangelio,
como era en aquel día. Este discurso tuvo tal efecto
en el hombre que se volvió muy amoroso,
y después de reflexionar en el asunto más a fondo, nunca fundó su pretendida universidad.

De Durham G. Fox pasó a Nottingham, donde recogió de nuevo a un pueblo disperso,
que después de casi ochos años de haber sido convencido de la Verdad,
había sido desviado por un tal Rice Jones.
De ahí se fue a Warwichshire, y atravesando Northamptonshire y Leicestershire,
llegó a Bedfordshire, y por tanto, a la casa de John Crook,
donde se celebró una reunión general anual que duró tres días. Muchos
de los amigos de G. Fox de la mayor parte de la nación acudieron a ella,
de modo que las posadas de los pueblos de los alrededores se llenaron.
También llegó William Caton, quien después de que terminó la reunión,
se fue con Thomas Salthouse (su antiguo compañero
de servicio en la casa del juez Fell) a Westmoreland,
Cumberland y Swarthmore, en Lancashire.
En dicha reunión general,
G+++.+++ Fox dio un largo discurso acerca de los varios estados de los hombres,
pero les dio instrucción, especialmente, a los ministros de la palabra,
exhortándolos en general a ser cautos en sus puestos.

Después que terminó la reunión,
llegó un grupo de jinetes con un alguacil para detener a G. Fox,
que en ese momento caminaba en el jardín de John Crook,
y aunque cuando llegaron a la casa alguien les dijo que G. Fox estaba allí,
estaban tan confundidos que no entraron al jardín a buscarlo, sino que se fueron sin él.

Partiendo de ahí llegó a Londres, donde oyó que un Jesuita,
que había llegado con el embajador de España,
había desafiado a todos los Cuáqueros para discutir
con ellos en la casa del conde de Newport.
G+++.+++ Fox le hizo saber entonces, por medio de algunos de sus amigos,
que ellos lo encontrarían ahí, con lo cual,
el Jesuita envió un mensaje diciendo que él se reuniría
con los doce hombres más sabios y más eruditos que tuvieran.
Un poco después envió un mensaje diciendo, que se reuniría con sólo seis; y después,
envió un mensaje otra vez, en el que decía que deseaba que sólo llegaran tres.
Entonces G. Fox fue a la mencionada casa con Edward Burrough y Nicholas Bond,
y les pidió que entraran y entablaran la discusión con el Jesuita,
mientras él caminaba en el jardín, y que él entraría después de ellos.
Él les aconsejó que formularan la siguiente pregunta: Si la iglesia de Roma,
tal como era en ese momento,
no había apostatado del estado de la verdadera iglesia que existía en los tiempos primitivos,
de la vida y doctrina, y del poder y Espíritu en los que estaban aquellos creyentes.
Entonces, después de que le plantearon la pregunta,
el Jesuita afirmó que la iglesia de Roma en ese momento,
estaba en la virginidad y pureza de la iglesia primitiva.

Para entonces G. Fox había entrado,
y le estaban preguntando al Jesuita si ellos tenían
al Espíritu Santo derramado sobre ellos,
como lo habían tenido los apóstoles.
Él dijo: "`No.`" Entonces G. Fox dijo:
"`Si ustedes no tienen el mismo Espíritu Santo derramado sobre ustedes,
ni el mismo poder y Espíritu que tenían los apóstoles,
entonces han apostatado del poder y Espíritu en los que estaba la iglesia primitiva.`"
Y le preguntó al Jesuita, qué Escrituras tenían para levantar conventos para monjas,
y abadías y monasterios para hombres, para rezar usando cuentas, rezarles a las imágenes,
hacer cruces, prohibir carnes y matrimonios,
ejecutar a un pueblo por religión. "`Si ustedes están en la práctica de la iglesia primitiva,
en su pureza y virginidad,`" le dijo Fox,
"`entonces veamos por medio de las Escrituras si ellos practicaban tales cosas.`"
Porque se había acordado mutuamente,
que tanto el Jesuita como los Cuáqueros debían probar con las Escrituras lo que dijeran.

Entonces el Jesuita dijo que había "`una palabra escrita y una no escrita.`"
Lo que hizo que G. Fox le preguntara,
a qué le llamaba él palabra '`no escrita.`' Él respondió:
"`La palabra escrita son las Escrituras,
y la '`no escrita`' es la que los apóstoles dijeron de manera oral,
que son todas las tradiciones que practicamos.`"
Entonces G. Fox le pidió que probara eso con las Escrituras,
y el Jesuita apeló a las palabras del apóstol en 2 Tesalonicenses
2:5. "`¿No os acordáis que cuando yo estaba todavía con vosotros,
os decía esto?`"
"`Es decir,`" dijo el Jesuita, "`les hablaba de conventos, monasterios,
ejecutar por religión, rezar usando cuentas, rezarles a las imágenes,`" etc.
Él afirmó que esta era la palabra '`no escrita`' de los apóstoles,
la que ellos hablaban entonces,
y la que había sido continuada por la tradición hasta el tiempo presente.

Luego G. Fox quiso que leyera esa escritura de nuevo,
para que viera cómo había pervertido las palabras de los apóstoles,
dado que el apóstol estaba hablando ahí de lo que había dicho antes,
y no era una palabra '`no escrita,`' sino que estaba escrita allí; a saber,
que el hombre de pecado, el hijo de perdición,
sería revelado antes de que el grande y terrible día de Cristo viniera,
del que él estaba escribiendo.
Y que por lo tanto,
Pablo no les estaba hablando de ninguna de las cosas que la iglesia de Roma practicaba.
Además,
que el apóstol en el tercer capítulo de la misma epístola le había hablado a la iglesia,
que había oído que entre ellos había algunas personas que andaban desordenadamente,
entrometiéndose en lo ajeno y que no trabajaban en nada;
con respecto a las cuales él les había mandado por
su palabra '`no escrita,`' cuando estaba entre ellos,
que si alguno no trabajaba, que tampoco comiera; lo cual, entonces,
les mandaba de nuevo en su palabra escrita en esta epístola, 2 Tesalonicenses 3.

Al no encontrar el Jesuita otra prueba de la escritura
para la tradición de la iglesia de Roma,
dejó caer el punto y se dirigió al sacramento del altar,
y para probar la realidad de este, comenzó con el cordero pascual,
el pan de la proposición, y así llegó a las palabras de Cristo:
"`Este es mi cuerpo,`" y a lo que les escribió el apóstol a los corintios.
A partir de esto concluyó, que después de que el sacerdote consagraba el pan y el vino,
estos se volvían inmortales y divinos, y que el que los recibía,
recibía a Cristo completo.
A esto G. Fox dijo, que el mismo apóstol les había dicho a los corintios,
después de que estos habían tomado el pan y el vino en memoria de la muerte de Cristo,
que ellos serían condenados si Cristo no estaba en ellos;
pero que si el pan que habían comido era Cristo,
Él necesariamente estaba en ellos después de que habían comido.
Además,
que si el pan y el vino que los corintios comían y bebían era el cuerpo real de Cristo,
cómo entonces tenía Cristo un cuerpo en el cielo.
También le indicó al Jesuita,
que tanto los discípulos en la cena como los corintios después,
tenían que comer el pan y beber el vino _en memoria_ de Cristo,
y anunciar Su muerte hasta que Él viniera,
lo cual claramente probaba que el pan y el vino que tomaban no era Su cuerpo.
Porque si ellos hubieran comido el cuerpo real de Cristo,
entonces Él habría llegado y habría estado presente allí. Y que habría sido incorrecto
hacer tal cosa "`en memoria de Él,`" si Él hubiera estado presente,
tal como habría sido,
si el pan y el vino que ellos comían y bebían hubieran sido Su cuerpo real.
En cuanto a las palabras de Cristo: "`Este es mi cuerpo,`" G. Fox le dijo:
"`Cristo se llama a Sí mismo vid, puerta, y es llamado en las Escrituras roca; por tanto,
¿es Cristo una roca, o una puerta, o una vid externa?`"
"`Oh,`" dijo el Jesuita, "`esas palabras deben ser interpretadas.`"
"`De igual manera,`" dijo G. Fox, "`las palabras de Cristo: '`Este es mi cuerpo.`'`"

Habiendo detenido la boca del Jesuita,
hizo la siguiente propuesta al ver que él decía que
el pan y el vino eran inmortales y divinos,
y eran el propio Cristo, y que cualquiera que los recibiera recibía a Cristo completo;
dijo que debía fijarse una reunión entre algunos Católicos,
según determinaran el Papa y sus cardenales, y algunos de los llamados Cuáqueros.
"`Y luego,`" dijo él, "`traigan una botella de vino y una hogaza de pan,
dividan en dos partes, y que ellos consagren la parte que deseen.
Luego, que tanto el pan y el vino consagrados como los no consagrados,
sean puestos en un lugar seguro, con una cuidadosa vigilancia sobre ellos,
y que se pruebe entonces si el pan y el vino consagrados no perderán su calidad--esto es,
que el pan se secará y se llenará de moho,
y el vino se corromperá y se amargará--al igual y tan pronto como los no consagrados;
porque por este medio la verdad de este asunto puede ser puesto de manifiesto.
Y si el pan y el vino consagrados no cambian, sino que retienen su sabor y calidad,
este puede ser un medio para atraer a muchos a su iglesia.
Pero si cambian, se corrompen y pierden su calidad,
entonces ustedes deben confesar y abandonar su error, y no derramar más sangre por esto,
como ha sido hecho, especialmente en los días del reinado de María.`"

A esto el Jesuita hizo esta réplica: "`Que se tome un trozo de tela nuevo,
se corte en dos pedazos y se hagan dos vestidos de ella,
y se ponga uno de ellos sobre la espalda del rey David, y la otra sobre un mendigo,
y tanto un vestido como el otro se gastarán.`" "`¿Es esta tu respuesta?,`" dijo G. Fox.
"`Sí,`" dijo el Jesuita.
"`Entonces,`" dijo Fox, "`por esto el grupo puede estar satisfecho,
de que el pan y el vino consagrados no son Cristo.
¿Dices entonces que el pan y el vino consagrados,
los que ustedes les han dicho a las personas que son inmortales y divinos,
y el verdadero cuerpo y la verdadera sangre de Cristo,
se desgastarán o corromperán como el otro?
Entonces debo decirte, que Cristo sigue siendo el mismo hoy que ayer,
y nunca se corrompe; y es la comida celestial de los santos de todas las generaciones,
a través de la cual todos tienen vida.`"
A esto el Jesuita no respondió más, sino que dejó caer el asunto,
porque percibió que los presentes veían su error y que no había podido defenderlo.

Luego G. Fox le preguntó,
por qué la iglesia de Roma perseguía y ejecutaba personas por religión.
El Jesuita respondió que no era la iglesia la que lo hacía,
sino los magistrados.
G+++.+++ Fox le preguntó si esos magistrados no eran considerados y llamados Cristianos.
"`Sí,`" dijo él. "`¿Son ellos miembros de la iglesia?,`" le preguntó Fox.
"`Sí,`" dijo el Jesuita.
Entonces G. Fox dejó que la gente juzgara,
si la iglesia de Roma perseguía y ejecutaba personas o no,
por religión. Luego se separaron;
habiendo sido puesta de manifiesto la sutileza del
Jesuita por la simplicidad de G. Fox y sus amigos.

Mientras G. Fox estaba en Londres, sus amigos, tanto en Inglaterra como en Irlanda,
estaban bajo grandes sufrimientos,
lo que hizo que él le escribiera al protector sobre esto.
Y debido a que se hablaba mucho de hacer rey a Cromwell,
fue donde él y le advirtió de los peligros que acompañarían eso, que si él no lo evitaba,
traería vergüenza y ruina sobre él y su posteridad.
Parece que Cromwell tomó bien este consejo y se lo agradeció; sin embargo,
G+++.+++ Fox le escribió de nuevo con respecto a lo mismo de la siguiente manera:

[.embedded-content-document.letter]
--

[.salutation]
Oh, protector,

Tú que has probado el poder de Dios,
el cual muchas generaciones antes que tú no conocieron,
desde los días que se apostató de los apóstoles; ten cuidado de no perder Su poder,
sino mantén fuera de tu cabeza la realeza, la que el mundo te quiere dar.
Mantén bajo tus pies todas las coronas terrenales,
no sea que te cubras con ellas y pierdas así el poder de Dios.
Cuando los hijos de Israel se salieron del don de Dios dentro de ellos,
desearon tener reyes como las otras naciones, y como tenían los transgresores; por tanto,
Dios les dio uno,
pero ¿qué hicieron después? Y cuando los hombres
querían coger a Cristo y hacerlo rey por la fuerza,
se escondió de ellos.
Se escondió de aquello que quería hacerlo rey,
a Aquel que era el rey interno de los judíos. ¡Oh, Oliver, ten cuidado,
no vaya a ser que te arruines a ti mismo corriendo hacia las cosas que se desvanecen,
es decir, hacia las cosas de este mundo que cambian!
¡Sujétate y sé obediente al Señor Dios!

[.signed-section-signature]
George Fox

--

Por este tiempo G. Fox le volvió a escribir otra carta a Oliver Cromwell,
en la que le señalaba que si él se hubiera mantenido
fiel y hubiera denunciado todo el engaño,
habría hecho muchas cosas poderosas.
Y también le aconsejó, que no despreciara a los hombres sobrios y de corazón veraz,
sino que se ocupara de la ley de Dios y de permanecer en Su temor y pavor;
que tuviera cuidado de las adulaciones y que apreciara su tiempo ahora que lo tenía.

Como la señora Claypole, la hija más estimada de Cromwell,
estaba enferma y muy atribulada de mente,
de modo que nadie de los que la habían ido a ver le habían podido brindar algún consuelo,
G+++.+++ Fox la visitó con la siguiente carta:

[.embedded-content-document.letter]
--

[.salutation]
Amiga,

Quédate quieta y tranquila en tu propia mente y espíritu de tus propios pensamientos,
y entonces sentirás a la Semilla de Dios volver tu mente al Señor Dios,
de quien viene la vida,
por medio de la cual puedes recibir Su fuerza y poder
para disipar todas las tormentas y tempestades violentas.
Esta Semilla es la que lleva al corazón a la paciencia, a la inocencia, a la sobriedad,
a la quietud, a la seriedad, a la tranquilidad, a Dios y Su poder.
Por tanto,
ocúpate de esta Semilla--esta es la palabra del Señor para ti--para que
puedas sentir la autoridad de Dios y saber que tu fe está en Ella,
la cual derribará lo que te atribula.
Porque esto es lo que mantiene la paz y levanta al Testigo en ti que ha sido transgredido,
para experimentar a Dios con Su poder y vida, quien es Dios de orden y paz.

Cuando estás en la transgresión de la vida de Dios en tu propio ser,
la mente vuela en el aire y la criatura es introducida en la noche,
la naturaleza se sale de su curso y una vestidura vieja lo cubre todo.
Así,
tu naturaleza es desviada de su curso y llega a arder por completo en la transgresión;
y esto desfigura la gloria de la primera imagen.
Por tanto, aquieta durante un tiempo tus propios pensamientos, tu propia investigación,
búsqueda, deseos e imaginaciones, y fija la mirada en la Semilla de Dios en ti,
para que Ella pueda levantar tu mente a Dios y colocarla en Dios,
y encuentres así la fuerza de Él, y lo encuentres a Él como un Dios cercano,
una ayuda presente en el tiempo de dificultad y necesidad.
Tras llegar a la Semilla de Dios, la que ha sido transgredida, Ella te mantendrá humilde,
y el Dios humilde te enseñará Su camino, el cual es paz; a estos Él exalta.

Ahora, como esta Semilla de Dios en ti ha sido transgredida, ve a Ella,
para que mantenga tu mente baja ante el Señor Dios, y así negarte a ti misma,
pues tú debes ser guardada de tu propia voluntad que es terrenal;
entonces sentirás el poder de Dios,
el cual traerá la naturaleza a su curso y te permitirá ver la gloria de la primera imagen.
Aquí recibirás la sabiduría de Dios (la cual es Cristo,
por la que todas las cosas fueron hechas y creadas),
para que por medio de ella puedas ser preservada y ordenada para la gloria de Dios.
Aquí llegarás a recibir y sentir al Médico capaz,
que reviste a las personas con su sano juicio,
por medio del cual le pueden servir a Dios y hacer Su voluntad.
Porque toda distracción, rebeldía y confusión está en la transgresión,
y la transgresión debe ser derribada antes de que la Semilla
de Dios (contra la que se ha transgredida) sea levantada,
mediante la cual la mente es sazonada y aquietada,
y un correcto entendimiento del Señor es recibido.
Así entran Sus bendiciones y son experimentadas sobre todo lo que es contrario,
en el poder del Señor Dios,
el cual levanta a la Semilla de Dios en el interior y da un sentimiento en pos de Dios,
y con el tiempo da dominio.

Por tanto,
mantente en el temor del Señor Dios--esta es la palabra del Señor
Dios para ti--porque todas estas cosas te suceden para tu bien
y para el bien de los que se preocupan por ti,
para hacer que se conozcan a sí mismos y conozcan su propia debilidad,
y puedan conocer la fuerza y poder del Señor y confiar en Él. Por tanto,
que el tiempo pasado sea suficiente para todos los
que en cualquier cosa se han levantado en transgresión,
fuera del poder del Señor;
porque Él puede derribar y humillar al poderoso y hacerlo caer en el polvo.
Por tanto, manténganse todos humildes en Su temor,
para que puedan recibir los secretos de Dios y Su sabiduría,
y conocer la sombra del Todopoderoso y sentarse bajo ella en todas las tempestades,
tormentas y calores.
Porque Dios es un Dios cercano, y el Altísimo gobierna en los hijos de los hombres.

Así, pues, no mires lo que la luz pone de manifiesto y descubre (tal como tentaciones,
distracciones, confusiones); no mires las tentaciones, confusiones, corrupciones,
sino mira la luz que las descubre y las pone de manifiesto.
Y con la misma luz te sentirás sobre ellas y podrás recibir poder para oponerte a ellas.
La misma luz que te deja ver el pecado y la transgresión, te dejará ver el pacto de Dios,
el cual borra tu pecado y transgresión, te da victoria y dominio sobre ellos,
y te lleva al pacto con Dios.
Porque al mirar el pecado, la corrupción y la distracción, eres absorbida por eso,
pero al mirar la luz que los descubre, verás sobre eso.
Esto te dará victoria y encontrarás gracia y fuerza; este es el primer paso para la paz.
Esto te traerá salvación,
y por medio de esta luz verás el principio y la gloria
que estaban con el Padre antes de que el mundo comenzara;
así llegarás a conocer a la Semilla de Dios,
que es la heredera de la promesa de Dios y del mundo que no tiene fin--la Semilla que
hiere la cabeza de la serpiente que impide que las personas se acerquen a Dios.
Así sentirás el poder de la vida indestructible, el poder de Dios que es inmortal,
que eleva el alma inmortal al Dios inmortal, en quien esta se regocija.
Por tanto, en nombre y poder del Señor Jesucristo, que el Dios Todopoderoso te fortalezca.

[.signed-section-signature]
G+++.+++ Fox

--

Cuando se le leyó esta carta a la mencionada dama, se le aquietó un poco la mente,
pero después de esto vivió poco tiempo.
Y así, Oliver Cromwell se topó con dificultades casi continuas,
pues el descontento contra él aumentaba cada vez más.

Ahora, dado que los Protestantes en el valle de Lucerna, y otros lugares,
estaban siendo muy perseguidos, surgió una declaración del protector para hacer un ayuno,
y otra declaración para hacer una colecta para alivio de las iglesias Protestantes afligidas.
En esta ocasión,
G+++.+++ Fox escribió el siguiente artículo para mostrar
qué tipo de ayuno es el que Dios requiere y acepta.

[.embedded-content-document.paper]
--

A los jefes y gobernantes de esta nación,
que han presentado una declaración para guardar un
día de solemne ayuno y humillación por la persecución,
según dicen, de muchas personas más allá de los mares que profesan la religión reformada,
la cual, dicen, les ha sido transmitida desde sus antepasados.

La profesión de la religión reformada puede ser, ciertamente,
transmitida de generación en generación, y así ser mantenida por la tradición,
y en esa parte del hombre en la que la profesión y la tradición son mantenidas,
es guardado también el día de humillación; todo lo cual está en la voluntad del hombre.
Este no es el ayuno que manda el Señor,
"`inclinar la cabeza como un junco por un día,`" y al día siguiente
seguir en la misma condición en la que se estaba el día anterior.
Le hablo a la luz de Jesucristo en sus consciencias,
la que testifica de Dios día a día y da testimonio contra todo pecado y persecución,
cuya medida de gracia de Dios, si son guiados por ella, no limita a Dios a un día,
sino que lleva al ayuno que el Señor demanda: "`¿No es más bien el ayuno que yo escogí,
desatar las ligaduras de impiedad, soltar las cargas de opresión,
y dejar ir libres a los quebrantados, y que rompáis todo yugo?`"
Isaías 58:6-7. Este es el ayuno que demanda el Señor,
y no se halla en tiempos específicos, ni en las tradiciones de los hombres,
sino en lo que estaba antes de que los tiempos existieran, en lo que saca del tiempo,
y en lo que será cuando el tiempo ya no exista.
Y los que '`enseñan como doctrina los mandamientos de hombres,`'
son los que siempre han perseguido la vida y el poder,
cuando estos han llegado.

Ahora bien, que ustedes tomen en consideración la triste persecución,
tiranía y crueldad ejecutada sobre aquellos,
a quienes ustedes llaman sus hermanos Protestantes,
y contribuyan y administren para las necesidades externas de ellos, es bueno en su lugar,
y nosotros lo reconocemos y vemos bueno administrar para las necesidades de otros,
y hacerles bien a todos.
Y nosotros, que hemos sido víctimas de una ley proveniente del Papa,
estamos dispuestos a unirnos y a contribuir con ustedes
para atender las necesidades externas de ellos.
Porque:
"`De Jehová es la tierra y su plenitud,`" quien es
bueno con todos y misericordioso con todos,
y desea que todos sean salvos y lleguen al conocimiento de la Verdad.

Pero, entretanto hacen esto y le prestan atención a la crueldad,
tiranía y persecución de otros,
vuelvan sus ojos hacia sí mismos y vean lo que ustedes están haciendo en casa.
Le hablo a la luz de Jesucristo en las consciencias de todos ustedes,
la cual no puede mentir, equivocarse o dar falso testimonio,
sino que siempre da testimonio de Dios y clama que se ejecute equidad,
justicia y rectitud.
Vean lo que están haciendo,
ustedes que profesan las Escrituras que fueron entregadas por los santos en luz,
aquellos que moraban en la luz y en la vida de ellas.
Porque a los que hoy son testigos de la misma luz,
de la misma vida y del mismo poder que entregó las
Escrituras (las que ustedes profesan de palabra),
a estos ustedes persiguen; a estos ustedes arrastran fuera de sus sinagogas y mercados;
a estos ustedes golpean, ponen en el cepo y encarcelan.
Ahora, dejen que el don de Dios en sus consciencias, que es justo, recto y equitativo,
examine y pruebe si ustedes tienen algún ejemplo o precedente para realizar esta persecución,
la que muchos en esta nación sufren hoy, que son personas inofensivas e inocentes,
y que caminan en obediencia a Dios y al hombre.
Y aunque ustedes consideran que el camino de la Verdad
en el que ellos andan es "`herejía,`" con todo,
en dicho camino ellos siempre buscan tener una consciencia
libre de ofensa contra Dios y contra el hombre,
como se lee que hicieron los santos de antaño (Hechos
24:14-16). Estos no injurian a nadie,
ni dan una razón justa de ofensa, sino que hablan la verdad en Cristo,
y sus consciencias les dan testimonio de que no mienten.
Sin embargo, por esto sufren bajo ustedes,
los que profesan en palabra lo mismo por lo que ellos sufren.

Consideren ahora si en alguna época o generación se ha perseguido como ustedes persiguen.
Porque ustedes profesan a Jesucristo, quien revela al Padre, y sin embargo,
persiguen a los que dan testimonio de la revelación
del Padre por medio de Jesucristo a ellos.
Ustedes profesan a Jesucristo,
quien es la luz del mundo "`que alumbra a todo hombre que viene a este mundo,`"^
footnote:[Juan 1:9]
y sin embargo, persiguen a los que dan testimonio de esta luz.
Ustedes profesan que la Palabra se ha hecho carne, y sin embargo,
persiguen a los que dan testimonio de ello.
Ustedes profesan que el que "`no confiesa que Jesucristo ha venido en carne,
es el anticristo,`"^
footnote:[1 Juan 4:3]
y sin embargo,
persiguen a los que confiesan que Él ha venido en carne y los llaman anticristos y engañadores.
Ustedes profesan que el reino de Cristo ha venido, y sin embargo,
persiguen a los que experimentan Su venida.
Ustedes profesan que Jesucristo es la resurrección y la vida, y sin embargo,
persiguen a los que Lo experimentan como tal.

Pero si dicen: "`¿Cómo sabremos si estas personas que dicen ser testigos de estas cosas,
lo son o no lo son?`"
Yo respondo, vuelvan sus mentes a la luz con la que Cristo Jesús los ha alumbrado,
la cual es una en todos.
Y si ustedes caminan en la luz, tendrán la luz de la vida,
y entonces sabrán y verán lo que han hecho,
que han perseguido al Señor de gloria (en Su pueblo), en quien está la vida,
y cuya vida es la luz de los hombres.
No los volvemos a ninguna otra brújula, sino a la que está en sus propias consciencias,
y ahí encontrarán la verdad de lo que les hemos declarado y de lo que damos testimonio,
según las Sagradas Escrituras.
Y cuando los libros de consciencias sean abiertos y todo sea juzgado a partir de ellos,
entonces serán testigos de que somos de Dios y de que nuestro testimonio es verdadero,
aunque ahora tapen sus oídos y '`endurezcan sus corazones,
entre tanto se dice hoy.`' Entonces sabrán lo que han hecho y contra quien han transgredido,
y verán que ningún otro perseguidor,
en ninguna época o generación que haya existido antes de ustedes,
transgredió jamás esa luz y medida de Dios hecha manifiesta,
de la manera en que ustedes lo han hecho.
Porque aunque Cristo y los apóstoles fueron perseguidos en sus tiempos,
aun así los judíos (en su mayor parte) no sabían que Él era el Cristo cuando
vino (a pesar de que tenían las Escrituras que profetizaban de Él),
ni tampoco creían que había sido levantado de nuevo,
cuando los apóstoles predicaron Su resurrección. Pero ustedes dicen
que creen que Él ha venido y dicen que creen en Su resurrección,
y sin embargo, persiguen a los que testifican que Él ha venido en carne.
A los que son sepultados con Él en el bautismo,
a los que son conformados a Su muerte y conocen el poder de Su resurrección,
a esos ustedes persiguen.
A esos ustedes arrastran delante de los magistrados
y permiten que sean golpeados en sus sinagogas;
a esos ustedes hacen que sean azotados,
que sean puestos en cepos y que sean vergonzosamente tratados y echados en prisión--como
atestiguan ante sus rostros muchas cárceles en esta nación hoy.

Por tanto,
consideren honestamente lo que están haciendo mientras
toman nota de las crueldades de otros,
no sea que pasen por alto las propias.
De hecho,
hay una diferencia en muchas cosas entre la religión
Católica y esa que ustedes llaman Protestante,
pero en esta persecución de ustedes no hay diferencia.
Porque dicen que el fundamento de la religión de ustedes está cimentado en las Escrituras,
y sin embargo,
persiguen a los que hoy están en la misma vida en
la que estaban los que hablaron las Escrituras;
ustedes mismos están bajo la mera profesión de las palabras que ellos hablaron,
y de eso serán testigos un día. Y así, tienen una profesión y una forma, y sin embargo,
persiguen a los que están en la posesión, vida y poder.
Por tanto, vuelvan sus mentes a la luz de Jesucristo en sus consciencias,
la que los escudriña y prueba.
Permanezcan quietos y esperen recibir la ley justa,
la que está en concordancia con ese don de Dios en la consciencia,
el cual se está levantando y dando testimonio hoy
contra toda impiedad e injusticia de los hombres.

Nuestro regocijo está en el testimonio de nuestras consciencias,
que con sencillez y piadosa sinceridad (no con sabiduría carnal,
sino por la gracia de Dios) nos hemos conducido en el mundo;
no adulterando la palabra de Dios con engaño, sino, en la manifestación de la Verdad,
recomendándonos a toda consciencia humana delante de Dios.
Y si nuestro Evangelio está encubierto, está encubierto entre los que se pierden,
y por mantener el misterio de la fe en una consciencia pura, es que sufrimos.
Porque es loable,
si debido a la consciencia hacia Dios uno soporta injustamente aflicción y sufrimiento.
En esto está nuestro gozo y regocijo, en tener una buena consciencia,
a pesar de que se hable malvadamente de nosotros como malhechores;
porque los que falsamente acusan nuestra buena conducta en Cristo serán avergonzados,
la cual, no sólo es la eliminación de la inmundicia de la carne,
sino también la respuesta de una buena consciencia
hacia Dios mediante la resurrección de Jesucristo.

Por tanto, les digo de nuevo, vuelvan sus mentes a la luz eterna de Jesucristo,
a la que examina y prueba todos los corazones, y vean lo que están haciendo,
no sea que mientras profesan las Escrituras, persigan la vida,
la luz y el poder que las entregó. Porque la piedra
que fue cortada sin manos de la montaña,
está golpeando ahora los pies de la imagen--la gran profesión
que está establecida y permanece en la voluntad del hombre.
Y ahora esa luz es hecha manifiesta, a la cual todos deben responder,
y en la que todos deben comparecer ante el tribunal de Cristo,
'`para que cada uno reciba según lo que haya hecho mientras estaba en el cuerpo,
sea bueno o sea malo.`'

[.signed-section-signature]
G+++.+++ Fox

--

Mientras muchos de sus amigos estaban en ese momento en cárceles y calabozos,
otros de ellos fueron al Parlamento y ofrecieron quedarse en las mismas prisiones,
en lugar de sus hermanos,
para que los que estaban en prisión no perecieran en calabozos apestosos,
ni sus perseguidores trajeran sangre inocente sobre sus propias cabezas por esto.
Pero esto no se pudo obtener;
porque algunos miembros del Parlamento amenazaron a estos compasivos hombres con azotarlos
si no desistían. Y debido a que el Parlamento que se reunía en ese momento,
estaba compuesto mayormente de aquellos que, pretendiendo ser más religiosos que otros,
en realidad eran los más grandes perseguidores de los que eran verdaderamente piadosos,
G+++.+++ Fox no pudo dejar esta hipocresía sin reprensión y les escribió las siguientes líneas:

[.embedded-content-document.letter]
--

Oh, amigos, no se oculten ni se cubran;
hay un Dios que conoce sus corazones y que los descubrirá. Él ve su camino:
"`¡Ay del que se cobija con cubierta, y no con mi Espíritu!`"^
footnote:[Isaías 30:1], dice el Señor. ¿Actúan contra la ley y luego se excusan?
Ustedes descuidan la misericordia y el juicio verdadero.
Miren lo que mi Salvador dijo contra tales: '`Estuve enfermo y no me visitaron;
tuve hambre y no me dieron de comer; fui forastero y no me acogieron;
estuve en prisión y no me visitaron.`' Pero ellos le dijeron:
'`¿Cuándo te vimos en prisión y no te visitamos?`'
'`En cuanto no lo hicieron a uno de estos pequeños,
tampoco me lo hicieron a mí.`'^
footnote:[Mateo 25:43-45]
Amigos, ustedes encarcelan a los que están en la vida y poder de la Verdad,
y sin embargo, profesan ser ministros de Cristo.
Pero si Cristo los hubiera enviado,
sacarían a las personas de la prisión y de la esclavitud, y recibirían a los forasteros.
'`Ustedes han vivido sobre la tierra en deleites y lujos;
han engordado sus corazones como en día de matanza.
Ustedes han condenado y dado muerte al justo, y él no les ha hecho resistencia.`'^
footnote:[Santiago 5:5-6]

[.signed-section-signature]
G+++.+++ F.

--

G+++.+++ Fox no era el único que se afligía con dicha hipocresía,
sino que otros de sus amigos también declaraban celosamente contra ella.
Una vez, cierta mujer entró a una sesión de este Parlamento con una jarra en su mano,
y quebrándola delante de ellos les dijo:
"`Así serán quebrados en pedazos;`" lo cual sucedió
no mucho después. Y debido a que Oliver Cromwell,
cuando los grandes sufrimientos de los amigos de G. Fox fueron puestos delante de él,
no quería creerlo,
esto les dio oportunidad a Thomas Aldam y Anthony Pearson de pasar por todas,
o la mayoría, de las cárceles en Inglaterra,
consiguiendo copias de los encarcelamientos de sus amigos bajo las manos de los carceleros,
y así poner el peso de dichos sufrimientos sobre O. Cromwell.
Pero una vez hecho esto,
al darse cuenta de que él todavía no estaba dispuesto a dar la orden para que los liberaran,
Thomas Aldam se quitó la gorra de su cabeza y rasgándola en pedazos le dijo a Cromwell:
"`Así será rasgado tu gobierno y tu casa.`"

Hacia el comienzo de este año,
Edward Burrough le escribió una carta a O. Cromwell y a su consejo,
quejándose y advirtiéndoles contra la persecución,
al ser la que atraería la ira de Dios contra ellos.
Varias copias de dicha carta fueron entregadas a Oliver y a su consejo,
y algunos meses después E. Burrough le escribió la siguiente carta:

[.embedded-content-document.letter]
--

[.letter-heading]
Al protector

[.salutation]
Amigo,

Mi vida te saluda y te desea bien a ti en el Señor, y muy especialmente,
que tu preciosa alma sea redimida de la muerte a Dios,
y así viva y encuentre reposo y habitación en Él cuando este mundo ya no exista.

Ahora,
en vista de que hay un clamor general entre los maestros y personas de esta nación,
y tú mismo algunas veces has objetado, que el pueblo llamado Cuáqueros está equivocado,
engañado, en un error, etc.; entonces,
a fin de que tú y otros resuelvan esto con respecto a nosotros,
te pido que pongas todas tus objeciones y dudas en una posición clara,
o dejes que los más sabios de tus maestros lo hagan por ti.
Que cualquier cosa que objetes contra nosotros, o de la que tengas dudas,
o con la que tropieces, ya sea con respecto a nuestras doctrinas o prácticas,
que sea expresado con palabras sencillas, en puntos de vista o consultas,
y si Dios lo permite,
se dará suficiente respuesta para eliminar todos los escrúpulos de consciencias,
y confundir todos los sutiles alegatos y evasivas.
Para que de este modo, seas siempre y por completo, inexcusable de cualquier duda,
no hables contra nosotros,
ni permitas que el mal sea hecho o dicho contra nosotros por tal motivo.

Me siento movido a manifestar y a enviarte esto, para que quedes satisfecho,
para que todas las cosas sean juzgadas y puestas
de manifiesto ante los ojos de todos los hombres,
para que todo juicio apresurado y falsa suposición,
que se aloja en los corazones de muchos, sean confundidos y derribados,
para que todas las cosas salgan a la luz y sean llevadas al verdadero juicio,
y para que lo que se demuestre que es la Verdad sea reconocido y no se persiga más.
Porque nosotros estamos dispuestos a ser puestos de manifiesto ante todos los hombres,
y si se objeta algo contra nosotros que no podamos responder
o resolver suficientemente ante los hombres sobrios,
entonces nuestros enemigos serán más libres de criticarnos
y tendrán algo más para exaltarse sobre nosotros.
Pero si toda razón de tropiezo es eliminada con nuestras respuestas,
en concordancia con las Escrituras, y de esta manera nuestros principios,
prácticas y doctrinas son vindicadas,
entonces que todos los maestros y todos nuestros adversarios cierren sus bocas,
dejen de mordernos y maldecir contra nosotros, y de acusarnos ante ti.
Ojalá se cierre tu oído para que no creas mentiras contra el inocente;
y ojalá ningún hombre sufra en tu dominio bajo la crueldad de hombres con tales motivos.

Me alegraré de recibir una respuesta de esto; y mientras tanto, y siempre,
soy amante de tu alma, pero un testigo contra toda opresión.

[.signed-section-signature]
E+++.+++ B.

[.signed-section-context-close]
Esto fue entregado en sus manos en Hampton Court, el mes Cuatro de 1658.

--

Nunca entendí que algo de importancia siguiera esta carta,
pero cerca de dos meses después, le escribió otra carta a Cromwell,
la cual le fue entregada en Hampton Court, el sexto mes.

[.embedded-content-document.letter]
--

[.letter-heading]
Al protector

[.salutation]
Amigo,

Conoce que hay un Dios que hace todo lo que quiere.
Todo el poder está en Su mano y lleva a cabo el consejo
de Su propio corazón. Él gobierna en los reinos de los hombres,
derriba y establece, mata y da vida, cambia los tiempos,
las estaciones y los gobiernos al llevar a nada los consejos de los hombres.
Porque todo el poder en la tierra y en el cielo está en Él,
todas Sus obras son rectas y todos Sus caminos equitativos,
y tú y toda la humanidad son como barro en la mano del alfarero.
Él honra y exalta como le place, y arruina, quiebra en pedazos y deshonra cuando quiere.
Por tanto, sé humilde y mantén el corazón bajo delante de Él,
porque Él es el poder supremo que somete todas las cosas bajos Sus pies.
Si Él hiere, ¿quién puede sanar?
Si Él mata, no hay nadie que pueda dar vida.
Conoce, por tanto, que el Señor Dios Todopoderoso hace esto,
en cuyas manos están las fuentes de la vida y de la muerte;
que Él puede derribarte y levantarte, puede herirte y restaurarte,
puede llevarte a la destrucción y decirte: "`Vuelve.`"

Sé fiel en lo que el Señor te llama y tendrás tu recompensa.
Busca Su honra y Él te honrará. Deja que tu mente esté en el Señor en todas las cosas,
y siente Su palabra, poder y presencia en ti, para que extinga todo lo que es contrario,
y entonces seas bendecido en esta vida y en la vida por venir.
Pero si continúas en tu opresión, el Señor te golpeará repentinamente.

[.signed-section-closing]
De un amigo para ti en el Señor,

[.signed-section-signature]
E+++.+++ B.

--

Que el Señor, en concordancia con esta predicción, repentinamente golpeó a Cromwell,
el tiempo lo probó, porque no vivió más de un mes después de recibir esta carta.
Y me parece, por varias circunstancias, que E. Burrough lo amaba tiernamente,
y que fue su deseo ardiente por el bienestar eterno del protector,
lo que motivó este lenguaje sencillo.

G+++.+++ Fox también le escribió diciendo, que debido a su maldad,
era probable que el Señor levantara a los monárquicos contra él,
para que fueran instrumentos de ejecución de Su ira;
tal como Cromwell mismo había sido una vez instrumento del derrocamiento de ellos.
Y muy poco tiempo antes de su muerte,
G+++.+++ Fox fue a Hampton Court para hablar con él acera de los sufrimientos de sus amigos.
Con esta intención fue,
y se encontró a Cromwell entrando a caballo al parque Hampton Court,
y antes de llegar a él (de acuerdo a su relato) percibió
una ráfaga de muerte contra Cromwell,
y cuando se le acercó se veía como un muerto.
Y así, después de que G. Fox había expuesto los sufrimientos de sus amigos delante de él,
y le había hecho una advertencia, Oliver le pidió que fuera a su casa;
después de lo cual G. Fox fue a Kingston, y al día siguiente regresó a Hampton Court.

Pero allí le dijeron que el protector estaba enfermo,
y el Dr. Harvey le dijo a George que los doctores
no querían que hablara con él. Así murió,
y George no vio a Oliver Cromwell de nuevo, quien desde la muerte de su hija,
la señora Claypole, había estado mal y padecía de un tumor maligno en un pie, el cual,
cuando sus médicos se esforzaron por eliminar, se movió hacia su corazón (según se dijo);
y luego siendo presa de una fiebre violenta, se fue debilitando más y más. Sin embargo,
sus predicadores se esforzaron por ocultarle el peligro en que estaba,
y se informa que el Dr. Goodwin, uno de sus capellanes,
en una oración durante el tiempo de su enfermedad, hizo uso de la siguiente expresión:
"`Señor, no te pedimos su recuperación, porque eso ya nos lo has concedido y asegurado,
sino su pronta recuperación.`" Mientras el protector estaba enfermo,
Edward Burrough les escribió la siguiente carta a su esposa e hijos.

[.embedded-content-document.letter]
--

[.salutation]
Amigos.

Recuerden que ustedes fueron levantados por el Señor de un estado bajo,
y que cuando Él así lo desee, también puede humillarlos y derribarlos.
Él les dio el palacio de los príncipes y los expulsó de la presencia de ustedes.

Oh, recuerden esto, cada uno de ustedes, y acudan al testigo de Dios en el interior;
sean humildes, mansos y dóciles, y dejen que el temor del Señor esté en sus corazones.
Sean de espíritu tierno, ejercitando sus mentes en la pureza, santidad y justicia.
No se exalten ni se enaltezcan en sus corazones con el orgullo,
la vanagloria y los honores de este mundo,
no sea que el Señor los derribe y haga de su nombre y posteridad un oprobio,
como lo ha hecho con muchos antes de ustedes.
Y ciertamente, si caminan en los mismos pasos, hacen las mismas cosas,
son culpables de las mismas abominaciones,
y permiten que los hijos y siervos del Señor sean perseguidos (como son perseguidos hoy,
algunos hasta la muerte), ¿los perdonará el Señor? No,
Él les hará sentir Su mano de juicio y los abatirá con dolor.
Los afligirá en Su ira y los golpeará con Su vara más y más,
hasta que aprendan Su temor y se aparten de todas sus iniquidades.
El Señor desfigurará la gloria de ustedes, les quitará la corona,
y les hará saber que Él es Señor, y que hace todo lo que quiere.

Por tanto, humíllense bajo la mano de Dios,
examinen sus corazones y echen fuera las abominaciones que afligen al Espíritu del Señor;
y no permitan que el pueblo del precioso rebaño del
Señor sea devorado y hecho presa del malvado.
Porque es debido a esto que la vara de aflicción viene sobre ustedes,
y puede que repentinamente los quiebre en pedazos.
Pero tengan en cuenta a la Semilla de Dios en ustedes, la cual está oprimida,
y esperen conocer el poder del Señor que los redimirá del pecado y de la muerte,
los reconciliará con Dios y los llevará a la comunión con Él,
para que disfruten paz y reposo para sus almas,
y sean hechos herederos de la herencia de una vida indestructible.
Esto los haría verdaderamente honorables, y sería de más satisfacción, gozo,
contentamiento y verdadero regocijo para ustedes,
que todas las coronas y glorias mundanas,
porque todas esas cosas se gastarán y serán consumidas, y los dejarán miserables.
Recuerden que ya están advertidos por el Señor Dios,
por quien me siento movido a escribirles esto con amor tierno hacia todos ustedes;
y un día serán testigos de que así es.

Con respecto a los llamados Cuáqueros, son tenidos por viles a los ojos de los hombres,
y al ser despreciados por todos son echados de todo poder y lugar de la nación;
y también son vituperados, perseguidos y encarcelados,
con toda clase de maldades e injusticias, injustamente cometidas y dichas contra ellos,
por hombres malvados y corruptos en autoridad--sin embargo,
estos son hijos y siervos del Dios vivo, y son muy amados por Él,
y tan queridos para Él como la niña de Sus ojos.
Su poder y presencia están con ellos,
y está cerca el tiempo en el que el Señor hará caer a sus perseguidores,
y a sus enemigos inclinarse y temblar,
aunque ahora sufren injustamente y son pisoteados
como si no merecieran un lugar sobre la tierra.
Sin embargo, padecen por causa de la justicia y porque manifiestan la imagen del Padre,
y no por hacer mal; ¿acaso no recaerán los sufrimientos de ellos sobre ustedes?
Porque muchos cientos de ellos han sufrido crueles y grandes atrocidades,
y algunos han perdido la vida, aunque no por el protector,
pero sí en nombre de él. Y alrededor de un centenar en el presente permanecen en huecos,
calabozos y prisiones, a lo largo y ancho de la nación,
algunos de los cuales están enfermos, próximos a la muerte,
cuyos sufrimientos claman venganza y el Señor oye el clamor.
Por tanto, sálvense ustedes, y dejen que el inocente sea liberado,
que se rompan las crueles ataduras de opresión,
que quede libre y sin persecución el ejercicio de una consciencia pura.
Entonces el Señor apartará Su ira y cesará de herirlos con Su vara;
y les dará paz y los bendecirá, si llegan a ser guiados por Su Espíritu a toda la Verdad.

Y aunque estos inocentes corderos de Cristo sufren así bajo el presente poder,
no son enemigos de ustedes, sino amigos de sus personas y familias, y los compadecen,
los aman y les desean bien en el Señor. Ellos desean
que ustedes se arrepientan y sean sanados,
e incluso, que sus corazones se abran para recibir refrigerio para sus almas,
que sean establecidos en justicia y verdad sobre todos sus enemigos,
y que no sean confundidos, ni que su posteridad sea puesta en oprobio,
el cual se apresura hacia ustedes.
Y aunque nuestro amor sea despreciado,
y nos consideren odiosos antes sus ojos y nos miren con escarnio, con todo,
soportamos todas estas cosas con paciencia,
deseando verdaderamente su regreso y arrepentimiento, y no su destrucción.

Pero si estos dolorosos sufrimientos de los pobres
corderos del Señor continúan bajo el presente poder,
esto los destruirá a ustedes, los deshará, los quebrantará y los confundirá;
y el Señor no dejará de herirlos con Su vara de dura reprensión. ¡Oh,
si supieran cuántos cientos han sufrido y sufren actualmente! ¡Cómo han
sido torturados los cuerpos de algunos con cepos y crueles azotes! ¡Cómo
algunos yacen enfermos sobre el piso de apestosos huecos y calabozos,
o en el mejor de los casos, sobre un poquito de paja; diez, a menudo más,
permanecen en una sola celda acinados,
y algunas veces no se les permite a sus propios amigos
que los visiten con lo necesario! ¡Oh,
si sus ojos contemplaran y sus corazones percibieran la enorme crueldad
que algunos de los queridos siervos del Señor y sus fieles amigos experimentan,
les dolerían sus corazones y sus espíritus temblarían!
Y todo esto es hecho en el nombre y bajo la autoridad del "`protector.`"

Por tanto, ¿cómo no lo va a acusar y afligir el Señor a él y a su familia?
Él les dará a conocer que hay un Dios que puede hacer lo que quiera,
y que la vida y la muerte están en Sus manos,
y que todas las criaturas son como barro en la mano del alfarero.
Él gobierna en los reinos de los hombres, y derriba uno y establece otro,
según Su beneplácito.
Así, pues, si el amor de Dios les es negado,
es por desobediencia a Él y transgresión. Por tanto,
sean obedientes a Él y amen Sus caminos y Sus juicios,
para que Él los haga más felices con una corona inmortal que no se desvanece.
Y recuerden una vez más,
que el Señor los ha advertido por medio de un amigo de ustedes en el Señor.

[.signed-section-signature]
E+++.+++ Burrough.

[.signed-section-context-close]
Escrito el 1 de septiembre de 1658

--

Oliver Cromwell fue arrebatado inesperadamente por la muerte; sin embargo,
el día antes de su fallecimiento fue entregada esta carta a sus parientes.
No fue hasta el último momento de su vida,
que él nombró a su hijo Richard como su sucesor.
Y cuando la muerte lo miró a la cara, el remordimiento no se quedó atrás, pues,
según lo que relata Ludlow,
Cromwell parecía estar preocupado principalmente por las
críticas que (dijo él) lanzarían los hombres sobre su nombre,
al pisotear sus cenizas cuando muriera.
En este estado de ánimo dejó esta vida, como a las dos de la tarde del 3 de septiembre,
con casi cincuenta y cinco años.

Al ser llevadas las noticias de su muerte a los que se habían reunido para orar por él,
un tal Sterry se puso de pie y dijo: "`¡Estas son buenas noticias;
porque si él fue de gran utilidad para el pueblo de Dios cuando estaba entre nosotros,
ahora lo será mucho más,
tras haber ascendido al cielo para interceder por
nosotros!`" ¡Qué horrible adulación! Así la llamaría,
aunque hubiera sido el más grande santo sobre la tierra; de lo quedó muy corto,
a pesar de que estuvo dotado con algunas virtudes sobresalientes.
El día de su muerte fue notable por una de las más terribles tempestades,
no sólo en Inglaterra, sino también en los Países Bajos,
en la que por la violencia del viento fueron arrancados
árboles del suelo y se perdieron muchos barcos.
"`Él era,`" dice Edward, conde de Clarendon,
"`una de esas personas a las que ni siquiera sus enemigos podían denigrar sin alabarlo.`"
He oído a hombres imparciales decir,
que al principio de sus logros él en verdad había sido un excelente hombre,
pero que después de que había llegado a una posición alta,
pronto había perdido ese celo por el bienestar público,
por el que al principio parecía haber sido motivado.

El cuerpo del difunto fue puesto en Somerset House,
y en una sala iluminada únicamente con candelas de cera,
yacía el cuerpo ricamente adornado.

Después de su muerte, Richard, el hijo mayor de Oliver,
fue proclamado protector de la Mancomunidad;
a quien Edward Burrough le escribió una carta dirigida a: "`Richard Cromwell,
escogido para ser protector y magistrado principal,
etc.,`" en la que le hizo un relato de los sufrimientos más crueles de sus amigos,
y hablando de los gobernantes dice así:

[.embedded-content-document.letter]
--

En cuanto a la magistratura, fue ordenada por Dios para ser pavor,
terror y límite para los malhechores,
para ser defensa y alabanza para todos los que hacen bien,
y para condenar a los culpables y justificar a los inocentes.
Pero hoy, el ejercicio de la magistratura en esta nación está degenerado,
y algunos que están en autoridad son muy corruptos,
y no consideran la ley justa y pura de Dios para juzgar sólo por ella.
En su lugar, oprimen al pobre con la injusticia,
y alteran las buenas leyes de Dios y de los hombres para un fin y uso incorrecto,
abusando de la autoridad y volviendo la espada contra el justo, con lo cual,
el verdadero juicio es echado atrás,
y a través de la corrupción de los hombres en autoridad,
se hace sufrir injustamente al inocente por causa de la justicia.

Si tú supieras lo que hemos sufrido en este sentido,
se te traspasaría el corazón. Pues es frecuente que algunos
de los jueces y magistrados envíen a un hombre a prisión,
le impongan una gran multa y lo lancen a un calabozo
o hueco entre ladrones y asesinos por una larga temporada,
por ningún otro delito o violación de alguna ley,
sino por no poder quitarse su sombrero ante ellos,
respetar sus personas mediante el sombrero o doblando la rodilla.
Muchos otros que temen a Dios sufren,
porque debido a un asunto de consciencia no pueden jurar sobre un libro,
besándolo y colocando las manos sobre él, porque Cristo dice:
"`No juréis en ninguna manera,`" aunque no se niegan
a hablar y a decir la verdad en todas las cosas,
como ante la presencia de Dios y de todos los hombres.
Y muchos otros sufren porque se sienten movidos a clamar contra
el pecado y a declarar contra las iniquidades de la época,
en maestros, gobernantes y personas, ya sea en un mercado,
'`casa del campanario,`' camino u otro lugar, según son movidos por Dios.
Y otros más, porque por consciencia no pueden pagar diezmos,
ni dar dinero ni salarios para mantener a un sacerdote, o falso maestro,
de quien no reciben beneficio;
o para mantener una '`casa del campanario`' en la que adora el mundo con vanas tradiciones,
y no en el espíritu y poder de Dios.
Muchos han sido sacados de reuniones pacíficas, en la que estaban esperando en el Señor;
algunos han sido sacados de sus posadas o casas de amigos;
y muchos han sido cogidos en el camino, cuando viajaban en sus legítimos negocios;
y algunos en sus propios llamados y labores.
Por estas razones, por la envidia de hombres malvados,
y sin ninguna justa convicción de la transgresión de alguna ley,
ni de ningún juicio o interrogatorio legítimo,
cientos de hombres justos completamente inocentes,
han sido enviados a prisión donde permanecen muchos meses y algunos por años,
o han sido azotados, o puestos en cepos, o gravemente maltratados,
por los crueles ejecutores de la envidia e injusticia de los hombres malvados.
Sí, amigo, es difícil expresar y demasiado extenso declarar,
cuántos de los siervos del Señor han sufrido y sufren gran injusticia en estas naciones,
a través del abuso del buen gobierno,
y de la caída de la magistratura de su perfecto estado y lugar,
en el que fue ordenada por Dios al principio.

--

Esta reconvención, aunque larga y poderosa, no tuvo el efecto deseado,
pues la persecución continuó sin que él la detuviera.
Porque los eclesiásticos lo adulaban llamándolo no sólo su "`Josué,`"
sino que los predicadores de Suffolk decían en sus discursos de él,
__"`Sol occubuit, nox nulla secuta est.`"__
Es decir: "`Aunque nuestro sol se ha puesto, la noche no ha llegado.`"

Por este tiempo se publicó un artículo llamado, __"`The Church Faith;`"__^
footnote:[La Fe de la Iglesia.]
y G. Fox habiendo obtenido una copia de dicho artículo antes de que se publicara,
escribió una respuesta, de modo que, cuando apareció el libro de la fe de la iglesia,
también apareció su respuesta.
Esto encolerizó tanto a algunos hombres del Parlamento,
que uno de ellos le dijo a G. Fox que ellos debían llevarlo a Smithfield.^
footnote:[Smithfield era un distrito del centro de Londres,
en el que muchos herejes y políticos rebeldes bien conocidos habían
sido quemados públicamente en la hoguera a lo largo de varios siglos.]
A esto respondió, que él estaba sobre sus fuegos y no les temía, y preguntó además,
si todo el pueblo había estado sin fe durante mil seiscientos años,
que ahora los sacerdotes debían crearles una.
Y que, dado que Jesucristo era el autor de la fe de los apóstoles,
de la fe de la iglesia en los tiempos primitivos y de la fe de los mártires;
¿no deberían todas las personas poner sus ojos en Él como autor y consumador de su fe,
y no en los sacerdotes?
No se ofreció nada sustancial en respuesta a esto,
pero los sacerdotes llamaron a los amigos de G. Fox "`enredaderas de casas,`"
porque se reunían en casas y no apoyaban los templos de los sacerdotes.
Un tal mayor Wiggan,
que estaba presente cuando G. Fox les habló a los hombres del Parlamento, dijo:
"`Cristo ha quitado la culpa del pecado,
pero ha dejado el poder del pecado en nosotros.`"
G+++.+++ Fox le dijo que esa era una doctrina extraña,
porque Cristo había venido a destruir al diablo y sus obras, y el poder del pecado,
y así limpiar a los hombres del pecado.

En este momento había una gran persecución,
tanto encarcelando como desarticulando reuniones.
Muchos murieron en prisión, pues los sacerdotes hablaban mal de los Cuáqueros,
y así encendían no poco la insolencia de la chusma,
la que no dudaban en lanzar petardos en las reuniones,
arrojarles huevos podridos a los que se habían reunido,
golpear tambores y teteras para hacer un ruido espantoso,
y lastimar gravemente a las personas con golpes y violentos empujones.

Un día en que había una reunión cerca de Londres,
la chusma golpeó y maltrató a unas ochenta personas
que salían de la ciudad para reunirse allí,
arrancándoles sus abrigos y sus capas de sus espaldas,
y lanzándolos en zanjas y estanques.
El siguiente Primer-día después de esto, G. Fox, aunque en ese momento estaba muy débil,
fue allí, y predicando con una biblia en su mano,
le mostró a la gente grosera sus frutos y los de sus maestros,
y cuán contrarias eran esas insensatas acciones a
la doctrina contenida en las Sagradas Escrituras.
Luego,
muchos de sus amigos encarcelados fueron llevados
a Londres para ser juzgados por el comité,
donde sir Henry Vane, como presidente,
no les permitía entrar a menos que se quitaran sus sombreros.
Pero dado que muchos de ellos habían sido encarcelados por "`desacato,`" (como
era llamada la negativa a quitarse los sombreros delante de los magistrados),
otros decían que no se debía esperar que cumplieran entonces, y así,
por mediación de algunos que persuadieron a H. Vane,
finalmente fueron admitidos dentro de la corte,
donde defendieron su causa tan bien que varios fueron liberados.

Los sufrimientos se hicieron cada vez más agudos,
y G. Fox escribió las siguientes líneas para animar a sus amigos:

[.embedded-content-document.epistle]
--

Mis queridos amigos, esparcidos por todas partes, en la cárcel o fuera de la cárcel,

No teman a causa de las noticias de sufrimientos.
No dejen que los atemoricen los espías malvados de la buena tierra,
si les dicen que las murallas son altas y que los hijos de Anac están en la tierra;
porque las murallas de Jericó cayeron al sonido de los cuernos de carnero,
y los que habían llevado la mala noticia perecieron en el desierto.
Sino permanezcan en la fe, paciencia y esperanza,
teniendo la Palabra de Vida para guardarlos, la cual está más allá de la ley;
y teniendo el juramento de Dios (Su pacto, Cristo Jesús),
que divide las aguas y las detiene en un montón. Manténganse firmes en esto,
y verán que todas las cosas obran para bien a los que aman a Dios,
y triunfarán cuando lleguen los sufrimientos, sean del tipo que sean.
Mantengan puesta su fe, su escudo, su yelmo, su armadura,
y así estarán listo para saltar una montaña, una muralla o una colina,
y caminar a través de las aguas profundas, aunque sean montones sobre montones.
Porque los espías malvados de la buena tierra pueden predicar dificultades,
pero Caleb (que significa corazón) y Josué (que significa
salvador) triunfarán sobre todo.

[.signed-section-signature]
G+++.+++ Fox

--

En ese tiempo había una gran discordia entre los que estaban al frente del gobierno,
y G. Fox relata que él previó entonces el retorno del rey; y por tanto,
cuando algunos espíritus atrevidos, que frecuentaban las reuniones de sus amigos,
deseaban comprar Somerset House para mantener reuniones allí, él los disuadió de hacerlo.
También se acercó a él una mujer, que según dijo,
había recibido una revelación con respecto a la restauración del rey Carlos,
tres años antes de que llegara, y dijo que ella debía ir a él para declararlo.
Pero G. Fox le aconsejó que se guardara para sí misma dicha revelación,
dado que si iba con un mensaje así, sería considerado traición.

Ya se ha descrito que el cuerpo de Oliver Cromwell
fue puesto en Somerset House para que fuera visto;
pero después, una efigie o imagen de él que estaba en ese lugar,
era acompañada por trompetistas que tocaban frente a dicha imagen.
Esta vanidad afligió tanto a G. Fox, que les escribió a los responsables diciendo:
"`¡Oh, amigos, qué están haciendo! ¡Qué pretenden al tocar trompetas delante de
una imagen! ¿No pensará toda persona sobria que están locos?`"
Un tiempo después de esto, se celebró con gran pompa el funeral de Oliver Cromwell,
el cual no concordó en absoluto con la condición en la que él estuvo alguna vez,
pues hubo un tiempo en que él habría aborrecido los
honores idólatras que ahora le mostraban a su imagen.

El 23 de noviembre, día de este pomposo funeral,
Edward Burrough entró cabalgando a Londres desde Kingston,
sin saber nada de lo que estaba sucediendo ahí. Mientras entraba en Charing-cross,
vio una gran multitud de personas agolpada,
que las calles estaban llenas hasta donde podía ver,
y que había una gran cantidad de personas mirando desde las ventanas,
balcones y techos de las casas.
También se encontró con guardias de jinetes y lacayos que detuvieron su caballo,
y le dijeron que no podía seguir por ese camino.
Sin embargo, no sabía cuál era el asunto,
hasta que finalmente observó que la imagen de Cromwell ricamente adornada,
iba a ser llevada por esa vía hacia Westminster.
Cuando advirtió esto, fue como si una flecha le hubiera perforado el pecho,
y debido a esta idolatría sintió tal fuego encendido en él, que por decirlo así,
fue llenado de la indignación del Señor, Cuya furia corrió a través de él y clamó:
"`¡Plagas, plagas y venganza contra los autores de esta abominación!`"
Y al considerar que toda esta idolatría pecaminosa
estaba relacionada con el funeral de Oliver Cromwell,
Burrough dijo dentro de sí:
"`¡Ay de él, quien en otro tiempo fue un gran instrumento en la mano
del Señor para derribar muchas imágenes idólatras! ¿No movió
el Señor en otro tiempo su corazón contra todas estas cosas?
Sus hijos, oficiales, soldados y ejército, ¿no derribaron todas las imágenes,
cruces y todo material papista dondequiera que lo hallaron?
¿Qué terrible y abominable obra es esta?
¿Han hecho ahora una costosa imagen de él? ¿Y los que fueron una vez sus soldados,
ahora la custodian y vigilan, y sus hijos y oficiales la siguen,
y una multitud de habitantes de Londres admiran y contemplan una imagen de él? ¡Esto
es triste y una gran lástima! ¡Qué cambio ha tomado lugar en tan corto tiempo!`"

Ahora, bien,
dado que la persecución de los amigos de E. Burrough (a pesar de
todo lo que él le había escrito a Richard Cromwell) no cesó,
y al descubrirse que todas las exhortaciones y advertencias habían sido rechazadas,
el mes llamado diciembre,
E+++.+++ Burrough le escribió las siguientes líneas a Richard y su consejo:

[.embedded-content-document.letter]
--

[.letter-heading]
Al protector y su consejo:

El Señor Dios pronto te dará a conocer que nosotros somos Su pueblo,
aunque seamos contados como ovejas para el matadero.
No obstante, si endurecen sus corazones y no se arrepienten,
nuestro Rey de justicia los quebrará en pedazos.
Y aunque Su amor no los persuada,
ni las suaves guías de nuestro Dios tengan espacio en ustedes,
Sus juicios los despertarán,
y Su pesada mano de indignación reposará sobre sus consciencias,
y serán esparcidos y destrozados en pedazos.

[.signed-section-signature]
E+++.+++ Burrough

--

Cuán pronto se cumplió está predicción, lo veremos en el siguiente año;
porque no fue sino unos pocos meses después de la entrega de esta carta,
cuando Richard depuso el gobierno.

Mientras tanto, volveremos a considerar la persecución en Nueva Inglaterra.
Como ya se ha dicho,
se había impuesto una multa de cinco chelines a la semana por no asistir a la iglesia,
como era llamaba.
Y así, de tiempo en tiempo,
se hallaban oportunidades para hacer uso de la crueldad
contra los habitantes de Nueva Inglaterra,
aunque no fueran de los llamados Cuáqueros que llegaban del extranjero.
William Shattock, un zapatero de Boston, fue arrastrado a la casa de corrección,
por ser encontrado un Primer-día en su casa y no en lugar público de adoración. Ahí,
de primera entrada, fue cruelmente azotado, y luego fue obligado a trabajar,
mientras su esposa e inocentes hijos se empobrecían por causa de su ausencia.
En el ínterin el representante de la corte-gobernador, Richard Bellingham,
no dudó en decirle a la esposa de William,
que dado que él era pobre y no podía pagar los cinco
chelines por semana por no asistir a la iglesia,
lo mantendrían en prisión. Así se verificó el dicho de Salomón,
"`mas la misericordia de los impíos es crueldad.`"^
footnote:[Proverbios 12:10. Traducción literal de la KJV]
Bellingham también se esforzó por persuadir a esta mujer,
de que lo que había hecho su esposo era para deshacerse de ella, y por tanto,
le aconsejó que lo repudiara.
Así, los perseguidores empezaron a estar muy ocupados,
porque quitar bienes y azotar cruelmente se convirtió casi en un trabajo diario,
que era ejecutado sin importar la edad o el sexo; relatar todo excedería mis límites.

Dos mujeres, llamadas Sarah Gibbons y Dorothy Waugh,
que habían llegado a Boston y habían dicho unas pocas palabras en el lugar
público de reunión después de que había terminado el sermón,
fueron llevadas a la casa de corrección,
donde tres días antes de que las azotaran y tres días después de azotarlas,
no les dieron de comer, aunque habían ofrecido pagarla.
Después, cuando Sarah le preguntó al gobernador, John Endicott,
si eso era justicia o equidad,
agregando que por causa de eso todos podrían ver que Dios estaba con ellas,
pues habían sido preservadas sin comida,
y que si ellas perecían su sangre caería pesadamente
sobre los que eran responsables de ello;
él respondió, que no le importaba.

No mucho después, Hored Gardner, habitante de Newport, en Rhode Island,
llegó a Weymouth con su bebé lactante y una joven que lo cargaba.
De este lugar, por ser Cuáquera, fue llevada apresuradamente a Boston,
donde tanto ella como la joven fueron azotadas con un látigo de tres nudos.
Después de ser azotada,
la mujer se arrodilló y oró al Señor pidiéndole que perdonara a los perseguidores,
lo cual alcanzó tanto a una mujer que estaba allí, que dijo: "`De seguro,
ella no habría podido hacer eso si no hubiera sido por el Espíritu del Señor.`"

¡Pero,
cuándo terminaría si describiera todos los latigazos
infligidos a los llamados Cuáqueros en aquellas partes!
Porque en ese momento se había promulgado una ley que le proporcionaba
continuo trabajo a los perseguidores allí. El contenido de dicha ley era,
que cualquier habitante que directa o indirectamente
hiciera que algún Cuáquero entrara en esa jurisdicción,
debía pagar cien libras y ser enviado a prisión,
y ahí permanecer hasta que la pena fuera pagada por completo.
Y cualquiera que los alojara, sabiendo que eran Cuáqueros,
debía pagar cuarenta chelines por cada hora de alojamiento o encubrimiento,
y luego ser enviado a prisión hasta que la pena fuera pagada plena y satisfactoriamente.
Y además, que toda y cada una de las personas que se levantaran ahí entre ellos,
debían ser juzgados y sufrir el mismo castigo que
la ley estipulaba para los que llegaban del exterior;
a saber, por la primera transgresión, si era hombre,
se le cortaba una de sus orejas y se le obligaba a trabajar en la casa de corrección,
hasta que fuera enviado lejos por su propia cuenta.
Por la segunda transgresión,
se le cortaba la otra oreja y era mantenido en la casa de corrección, como se dijo antes.
Si era mujer, por la primera transgresión se le azotaba severamente,
y al igual que el hombre, era mantenida en prisión como se dijo.
Por la segunda transgresión, era tratada como la primera vez.
Y por la tercera transgresión, tanto a hombres como a mujeres,
se les perforaba la lengua con un hierro candente,
se les mantenía en la casa de corrección y eran obligados a trabajar,
hasta que fueran enviado lejos por su propia cuenta.

En la última parte del mes Cinco, sucedió que William Brend y William Leddra,
después de estar en Salem, llegaron a Newbury.
Allí, en la casa de un tal Robert Adams, tuvieron una reunión con el sacerdote,
en presencia del capitán Gerish, quien había prometido que no sufrirían;
pero después que terminó la reunión,
el capitán no quería dejarlos ir a menos que prometieran salir pronto del pueblo.
Reacios a cumplir con esta condición, continuaron su camino cuando se les mandó a llamar,
y el capitán Gerish cabalgando detrás de ellos, les ordenó regresar,
pero como se rehusaron,
él los obligó a hacerlo y los envió de regreso a Salem con un alguacil.
Ahí, los llevaron ante los magistrados y les preguntaron si eran Cuáqueros,
a lo que respondieron, que eran de los que eran llamados así en desdén. A continuación,
se objetó contra ellos que mantenían errores peligrosos.
Y cuando preguntaron cuáles eran esos errores,
se les dijo que ellos no sólo negaban que Cristo había sufrido en la cruz en Jerusalén,
sino que también negaban las Sagradas Escrituras.
Esto lo contradijeron con valentía,
y dijeron que no reconocían a ningún otro Jesús que
no fuera el que había sufrido la muerte en Jerusalén,
y que también reconocían las Escrituras.

Ahora bien, a pesar de que no se pudo objetar nada contra eso,
fueron llevados a la casa de corrección, pues según la ley promulgada en Boston,
eran de los que no tenían permitido entrar en esas partes.
Unos días después fueron llevados a Boston, y al siguiente mes,
los llevaron a la casa de corrección para que trabajaran ahí. Pero
al no estar dispuestos a someterse a esa irrazonable demanda,
el carcelero, que buscaba obtener ganancia del trabajo de sus prisioneros,
no les dio comida, aunque habían ofrecido pagar por ella.
Pero él les dijo que no deseaba su dinero sino su trabajo.
Y así, los dejó sin comida cinco días,
y con un látigo de tres cuerdas le dio veinte azotes a cada uno.
Una hora después de eso les dijo que podían salir,
si le pagaban al oficial que los sacaría del condado.
Pero al juzgar ellos que era absurdo pagar para ser desterrados, se negaron hacerlo;
sin embargo,
dijeron que si la puerta de la prisión estaba abierta se irían voluntariamente.

Al día siguiente el carcelero se acercó a William Brend, un hombre de edad avanzada,
y le puso grilletes, con la nuca y los talones tan juntos,
que no quedaba más espacio entre ellos que el necesario para que la cerradura los sujetara.
Así lo mantuvo desde la cinco de la mañana hasta después de las nueve de la noche;
un espacio de dieciséis horas.
La mañana siguiente lo llevó al molino a trabajar, pero como Brend se rehusó,
el carcelero tomó una cuerda cubierta con brea de casi una pulgada de grosor,
y con toda la fuerza que pudo le dio veinte golpes en la espalda y brazos,
de modo que la cuerda se destrenzó. Luego se fue,
y regresó con otra cuerda más gruesa y fuerte,
y le dijo a Brend que lo haría someterse a la ley del condado y trabajar.
Brend juzgó que eso no sólo era irrazonable en el más alto grado,
dado que él no había cometido ningún mal,
sino que estaba completamente incapacitado para trabajar;
pues en ese momento no tenía fuerzas por falta de
comida (después de haber estado cinco días sin comer),
por haber sido azotado, y recientemente golpeado sin piedad con una cuerda.
Pero este inhumano carcelero no se rindió,
sino que comenzó a golpear de nuevo con su cuerda
cubierta con brea sobre ese cuerpo ya lastimado;
y echando espuma por la boca como un loco,
le asestó con violencia noventa y siete golpes más,
según lo relatado por otros prisioneros que lo contemplaron
con compasión. Si su fuerza y su cuerda no le hubieran fallado,
le habría dado más, pues también lo amenazó con golpearlo más a la mañana siguiente.
Pero un poder superior, que le pone límites incluso al mar más embravecido, y ha dicho:
"`Hasta aquí llegarás, y no pasarás adelante,`" también limitó a este tipo despiadado,
quien fue lo suficientemente descarado como para decir sus oraciones matutinas.

Puede ser fácilmente imaginado,
la terrible condición en la que quedó el cuerpo de Brend por los golpes,
quien debido a lo muy caluroso del clima,
no tenía más que una delgada túnica sobre su camisa.
Su espalda y brazos estaban heridos y negros,
y la sangre le colgaba como en bolsas bajo sus brazos;
su carne estaba tan profundamente golpeada,
que no se podía ver la marca de un golpe en particular,
pues todo se había vuelto como gelatina.
Así, con su cuerpo tan cruelmente torturado, se acostó sobre las tablas,
tan extremadamente debilitado, que sus miembros naturales se empezaron a descomponer,
su fuerza disminuyó bastante y su cuerpo se enfrió. Parecía, por decirlo así,
una lucha entre la vida y la muerte.
Sus sentidos se detuvieron, y durante un tiempo no tuvo la capacidad de ver,
sentir u oír, hasta que finalmente prevaleció el poder divino,
la vida se abrió paso a través de la muerte,
y el aliento del Señor fue soplado en sus fosas nasales.

Ahora bien,
la conmoción de esta crueldad se esparció entre la gente del pueblo y provocó tal clamor,
que el gobernador envió a su cirujano a la prisión para que viera qué se podía hacer.
Pero el cirujano encontró el cuerpo de Brend en tan deplorable condición,
que sin esperanza dijo,
que su carne se pudriría desde los huesos antes de que las partes heridas pudieran sanarse.
Esto exasperó tanto a la gente, que los magistrados, para evitar un tumulto,
colocaron un documento en la puerta de su casa de reunión,
y arriba y abajo de las calles, por decirlo así,
para mostrar su disgusto de esta abominable y bárbara crueldad,
diciendo que el carcelero debía ser juzgado en la próxima corte.
Pero el documento fue retirado pronto por instigación del sumo sacerdote, John Norton,
quien al ser desde el principio un fiero promotor de la persecución dijo sin dudar:
"`William Brend se esforzó por maltratar nuestras
ordenanzas evangélicas hasta dejarlas llenas de moretones;
y si él ha sido golpeado hasta quedar lleno de moretones,
no es más que la justicia sobre él, y yo compareceré a favor del que hizo esto.`"
Por tanto, no es de extrañar que estos exigentes e intolerantes magistrados,
que deseaban ser considerados eminentes en piedad, fueran tan crueles en su persecución,
dado que su principal maestro los alentaba perversamente a hacerlo.

Entre tanto, le plació a Dios sanar milagrosamente a William Brend y mantenerlo con vida.
Sin embargo,
al parecer los corazones de estos perseguidores se endurecieron aún más por esto,
porque para mostrarse seguidores obedientes de su maestro,
dieron la orden de que si los Cuáqueros que estaban
bajo su custodia se rehusaban a trabajar,
el carcelero los debía azotar dos veces por semana--la primera vez con diez latigazos,
la siguiente vez con quince, y así cada vez con tres más, hasta que trabajaran.
Esto se ejecutó en cuatro personas, dos de las cuales eran William Leddra y John Rouse,
quienes serán mencionado más adelante.
Para mantener al ensañado carcelero dentro de los límites debidos,
se le ordenó que cada vez buscara dos alguaciles que presenciaran la ejecución. Pero,
cuán poca moderación se pretendía realmente con esta orden,
y que esta no era más que un chiste,
se muestra en el hecho de que el carcelero les dio quince latigazos a cada uno,
después de que se negaron a trabajar la primera vez, y así,
a menudo le sumaba cinco azotes al número.

Sucedió por esta época, que algunas personas del pueblo llamado Cuáqueros que vivían ahí,
al ser llevados delante de los magistrados,
exigieron saber cómo identificaban ellos a un Cuáquero, a lo cual Simon Broad-street,
uno de los magistrados, respondió: "`Ustedes lo son,
porque entraron con el sombrero puesto.`"
Esto hizo que el otro replicara, que era horrible hacer leyes tan crueles como azotar,
cortar orejas y perforar lenguas, por no quitarse el sombrero.
Entonces,
uno que estaba sentado en el banquillo dijo que los Cuáqueros blasfemaban en sus reuniones.
Ante esto, uno de los otros le pidió que hiciera ver las blasfemias que ellos sostenían,
y que si así era, ellos podrían ser convencidos.
Y añadió, que harían bien en enviar a algunos hombres a sus reuniones,
para que oyeran y dieran cuenta de lo que era hecho y dicho ahí,
y no juzgar algo que no conocían. "`Pero,`" dijo el general de división Denison,
"`si ustedes se reúnen y dicen cualquier cosa, podemos concluir que blasfeman.`"
¡Un silogismo muy extraño, en verdad!
No mejor fue el argumento de Charles Chauncy, profesor en jefe de la universidad,
que en un sermón en Boston argumentó de la siguiente manera,
para demostrar que la persecución era legal:
"`Supongamos que atrapan seis lobos en una trampa,
y no pueden probar que mataron ovejas o corderos,
y ahora que los tienen no ladran ni muerden.
No obstante, como tienen claras marcas de ser lobos, deben matarlos.`"
Una expresión vil, comparar así a un hombre con una bestia;
porque Dios le dijo a Noé claramente: "`El que derramare sangre de hombre,
por el hombre su sangre será derramada.`"
Sin embargo,
estos perseguidores pensaron que había suficiente peso en
este argumento para llamar a los Cuáqueros lobos;
y al ver a uno que no se había quitado el sombrero ante los hombres,
lo consideraron suficiente razón para decir: "`¡Derríbenlo, es un lobo!`"

Y si no era el sombrero, entonces encontraban fallas en algo más; porque en Salem,
doce personas fueron multadas con cuarenta libras y diecinueve chelines,
por no asistir a la iglesia; y a otros se les extorsionó con mucho dinero,
porque sus esposas se ausentaban de la adoración pública.
William Marston, de Hampton,
fue multado con diez libras por poseer dos libros en su casa, a saber, __Resurrection,__^
footnote:[Resurrección.] de John Lilburn; y __Mighty Day of the Lord,__^
footnote:[El Poderoso Día del Señor.]
de William Dewsbury.
Así, estas personas hacían lo que querían,
sin ninguna consideración de las leyes en la Vieja Inglaterra;
y cuando en una ocasión varios prisioneros apelaron a las leyes de Inglaterra,
el gobernador John Endicott y su representante de la corte, Bellingham, gritaron:
"`¡No apelen a Inglaterra! ¡No apelen a Inglaterra!`"
De hecho,
ellos parecían no temerles a las repercusiones de lo que les hacían a los Cuáqueros,
por lo que había dicho el general de división Denison en audiencia pública:
"`Este año irán y se quejarán con el Parlamento,
el siguiente enviarán a unos hombres para ver cómo van las cosas,
y el tercero se cambiará el gobierno.`"
Así, sin preocuparse por la Vieja Inglaterra,
les negaron a los prisioneros la petición de ser juzgados por un jurado,
según las leyes de ese reino.
Al ver que los gobernantes trataron esto así de arbitrariamente,
el carcelero de la casa de corrección hizo lo mismo,
porque cuando algunos de sus prisioneros se mostraron dispuestos a trabajar,
con tal que sus familias recibieran algo de la ganancia, él no quería permitirlo,
a menos que le pagaran ocho peniques por cada doce que ganaran,
y cuando se rehusaron hacerlo recurrió al poste de azotes.

Pero para continuar;
en el año anterior se hizo mención de John Copeland y Christopher Holder.
Estos hombres llegaron a Dedham en el sexto mes, y se alojaron ahí una noche;
pero al día siguiente fueron capturados por un alguacil que los llevó a Boston,
donde al ser llevados delante del gobernador, les dijo con rabia:
"`De seguro se les cortarán las orejas.`"
No mucho después de esto, John Rouse llegó de nuevo a Boston,
y fue capturado también y enviado a prisión. El 17 de septiembre, él,
con Christopher Holder y John Copeland,
fueron llevados ante los magistrados del tribunal,
donde el representante de la corte-gobernador les dijo, que por haber regresado,
en desacato a los magistrados y ministros, para seducir a la gente,
debían saber que cualquier cosa que les sucediera--ya fuera la pérdida de las orejas,
o de sus vidas--la sangre de ellos caería sobre sus propias cabezas.
Al negar ellos eso y decir que el Señor los había enviado, el gobernador Endicott dijo:
"`Ustedes son más enemigos de nosotros que los que vienen abiertamente;
ya que bajo el pretexto de paz, vienen a envenenar al pueblo.`"

Cuando les pidieron la prueba de que el Señor los había enviado,
respondieron que una prueba de que el Señor los había enviado,
era que habían recibido el tipo de recibimiento que Cristo les
había dicho a Sus discípulos que les darían por causa de Su nombre;
a saber, azotes, etc.
A esto, el general de división Denison dijo: "`Entonces,
cuando los malhechores son azotados, sufren por causa de Cristo.`"
Entonces John Rouse, cuyo padre era teniente coronel en Barbados dijo:
"`Si fuéramos malhechores,
los juicios de Dios serían más pesados sobre nosotros que los que sufrimos por ustedes.`"
A lo que el mayor Denison respondió: "`Mr. Rouse (pues puedo llamarte así,
tras oír que tu padre es un caballero),
¿qué juicio de Dios piensas que podría ser mayor que el que está ahora sobre ti:
ser expulsado de la casa de tu padre,
e ir de aquí para allá como un vagabundo en compañía
de engañadores...a menos que busques una soga?`"
Rouse dijo: "`No fui expulsado de la casa de mi padre,
sino que en obediencia al Señor la dejé,
y cuando el Señor me muestre que tengo libertad para dejar esta tierra,
regresaré a ella.`"
Entonces Endicott llamó al secretario para que leyera la ley,
quien leyó esta cláusula en ella: que si alguien que había sufrido por la ley,
presumiera regresar, se le debía cortar una de sus orejas.

Se dijeron unas palabras más, entre esas Endicott dijo:
"`Los Cuáqueros no tienen con qué probar su comisión,
sino el espíritu que está dentro de ellos, y ese es el diablo.`"
Y cuando uno de los prisioneros dijo: "`Hemos visto algunas de sus leyes,
que tienen muchas escrituras en los márgenes,
pero ¿qué ejemplo tienen de la Escritura para cortar orejas?`"
Endicott preguntó: "`¿Qué Escritura hay para colgar?`"
A lo que Denison dijo burlonamente: "`Sí, deberían ser crucificados.`"
Entonces Endicott llamó a los tres prisioneros por nombre, y dijo con gran pasión:
"`Es la sentencia del tribunal, que a cada uno el verdugo le corte la oreja derecha.`"
Luego fueron llevados a la cárcel, y el 16 de septiembre,
el representante del oficial llegó, dejando entrar a tantos como pensó oportuno,
y cuando las puertas fueron cerradas y trancadas, dicho oficial leyó la siguiente orden:

[.embedded-content-document.legal]
--

Al oficial general o a su representante:
Tienes que llevar contigo al verdugo y dirigirte a la casa de corrección,
donde lo verás cortar la oreja derecha de John Copeland, Christopher Holder y John Rouse,
Cuáqueros; en ejecución de la sentencia del tribunal de ayudantes,
por el incumplimiento de la ley titulada Cuáqueros.

[.signed-section-signature]
Edward Rawson, _Secretario._

--

Entonces, los prisioneros fueron llevados a otra habitación,
donde John Rouse le dijo al oficial:
"`Nosotros hemos apelado al magistrado principal de Inglaterra.`"
A lo que el oficial respondió, que él no tenía nada que ver son eso.
C+++.+++ Holder dijo: "`Una ejecución como esta debería ser hecha públicamente,
y no en privado; porque esto es contrario a las leyes de Inglaterra.`"
Pero el capitán Oliver replicó:
"`La hacemos en privado para cerrarte la boca y que
no puedas ganar la simpatía de la gente.`"
Entonces el verdugo cogió a C. Holder,
y cuando le apartó el cabello y estaba a punto de cortarle la oreja,
el oficial les volvió la espalda, lo que hizo que Rouse dijera: "`¡Vuélvete y mira;
pues esa fue tu orden!`"
Entonces el oficial, aunque lleno de miedo, se volvió y dijo: "`¡Sí, sí, miremos!`"
Rouse, que era más valeroso que su perseguidor, sufrió lo mismo,
así como también el tercero.
Y luego dijeron: "`A los que lo hacen en ignorancia,
deseamos desde nuestros corazones que el Señor los perdone;
pero a los que lo hacen maliciosamente, que nuestra sangre caiga sobre sus cabezas;
estos experimentarán en el día de la rendición de cuentas,
que cada gota de nuestra sangre será tan pesada para ellos como una piedra de molino.`"
Posteriormente, estas tres personas fueron azotadas de nuevo,
pero como esta práctica se ha vuelto tan común en Nueva Inglaterra,
que parece como si fuera un juego, no detendré a mi lector con ella.

La persecución que había llegado entonces al corte de orejas, no se detuvo ahí,
sino que aumentó y no cesó antes de llegar a la eliminación de vidas.
Pero lograr esto resultó muy difícil,
porque había muchas personas honestas que aborrecían tal crueldad.
No obstante, John Norton y los otros sacerdotes,
les pidieron a los magistrados que hicieran que la
corte emitiera una ley para desterrar a los Cuáqueros,
so pena de muerte.
Esto animó a los magistrados,
porque dado que los que impulsaron este malvado asunto habían sido los eclesiásticos,
no se tuvo ningún escrúpulo para continuar con esta obra sanguinaria.
El tribunal de magistrados votó para que esta ley
fuera puesta en ejecución por un tribunal del condado,
el cual estaba compuesto de tres magistrados,
en el que dos de tres tendrían la autoridad plena de colgar a una persona a su antojo,
sin haber sido juzgada por un jurado;
algo de lo que no se oía hablar en la Vieja Inglaterra,
pero que sirvió para el propósito de Norton y sus compañeros predicadores.

Ahora bien,
el tribunal en el que se aprobó esta ley estaba integrado por veinticinco personas,
y cuando fue sometida a votación fue aprobada;
el presidente y otros once votaron en contra, pero trece votaron a favor,
de modo que un voto la aprobó. Esto afligió tanto a un tal
Wozel cuando lo oyó (que había estado ausente por enfermedad),
que llegó al tribunal y llorando de pena (al pensar
que su ausencia había causado que tal ley pasara),
dijo que si él hubiera sabido, se habría arrastrado hasta ahí de rodillas,
antes de permitir que se aprobara.
Pero lo que dijo resultó en vano, porque ya habían pasado el Rubicon,^
footnote:[Es decir, se había pasado la encrucijada o punto de no retorno.]
y se había obtenido lo que había sido fervientemente deseado.
Sin embargo, hubo un gran desacuerdo en la corte, y los doce que habían votado en contra,
resolvieron presentar sus disconformidades a dicha ley;
cuando los otros vieron y creyeron que tantas dificultades debilitarían su ley,
admitieron la siguiente adición: Que serían juzgados por un jurado especial;
aunque una ley en firme decía, que nadie podía ser sentenciado a muerte, ni desterrado,
sino por un jurado especial _y_ un tribunal de asistentes,
y que dicho tribunal debía estar conformado por siete magistrados como mínimo.
Pero entonces se resolvió enjuiciar a los Cuáqueros hasta la muerte, y todos sus juicios,
cuando llegaba el momento, eran sólo una cuestión de si eran o no Cuáqueros,
lo cual era determinado por su ingreso a la corte con los sombreros puestos,
y si habían sido desterrados o no del país anteriormente.
Ahora bien, a fin de emprender este sanguinario asunto,
el siguiente acto fue realizado en un tribunal general, celebrado en Boston,
el 20 de octubre de este año de 1658.

[.embedded-content-document.legal]
--

[.letter-heading]
Acto realizado en el tribunal general, celebrado en Boston el 20 de octubre, 1658.

Mientras exista una secta peligrosa (comúnmente llamada Cuáqueros),
surgida recientemente,
que de palabra y por escrito ha publicado y mantenido
muchas doctrinas peligrosas y horrorosas,
y se encarga de cambiar y alterar las loables costumbres de nuestra nación,
como el respeto civil a iguales, o reverencia a los superiores,
cuyos actos tienden a socavar el gobierno civil y a destruir el orden de las iglesias,
al negar todas las formas establecidas de adoración
y retirarse de la comunión ordenada de la iglesia,
permitida y aprobada por todos los profesantes ortodoxos de la Verdad,
y que en su lugar y en oposición a ello, frecuentemente se reúnen por su cuenta,
introduciéndose en las mentes de los simples,
o de los que están menos inclinados al orden y gobierno de la iglesia y de la Mancomunidad,
por lo que muchos de nuestros habitantes han sido infectados,
a pesar de todas las leyes anteriormente hechas (por la
experiencia de sus intrusiones arrogantes y atrevidas,
que tenían como fin esparcir sus principios entre nosotros),
que prohibían su entrada a esta jurisdicción,
estos no han sido disuadidos de sus impetuosos intentos
de socavar nuestra paz y ponernos en peligro de ruina.

Para evitarlo, esta corte ordena y promulga que toda persona (o personas),
de la maldita secta de los Cuáqueros, que no sea habitante de esta jurisdicción,
pero sea hallada dentro de ella,
sea aprehendida sin una orden judicial (donde no haya un magistrado a mano),
por cualquier alguacil, comisario u hombre escogido, y trasladada de alguacil a alguacil,
hasta el siguiente magistrado, quien deberá enviar a dicha persona a prisión,
donde permanecerá sin fianza hasta la siguiente sesión del tribunal de asistentes,
en la que tendrá un juicio legal.
Y al ser condenada por pertenecer a la secta de los Cuáqueros,
será sentenciada al destierro bajo pena de muerte.

Todo habitante de esta jurisdicción que sea condenado
por pertenecer a la mencionada secta,
ya sea, por haber asumido,
publicado o defendido las horrorosas opiniones de los Cuáqueros; o promovido motines,
sediciones o rebeliones contra el gobierno;
o asumido sus prácticas absurdas y destructivas, a saber,
negarle el respeto civil a iguales y a superiores,
retirarse de nuestras asambleas eclesiales, y en su lugar,
reunirse con frecuencia por su cuenta, en oposición al orden de nuestra iglesia;
o haberse unido (o aprobado a cualquier Cuáquero
conocido) a los principios y prácticas de los Cuáqueros,
que son opuestas a las opiniones ortodoxas recibidas de los piadosos;
o haberse esforzado por distanciar a otros del gobierno
civil y de las órdenes de las iglesias;
o condenado la práctica y procedimientos de esta corte contra los Cuáqueros,
manifestando de esta manera su conformación a aquellos cuyos designios
son derrocar el orden establecido en la iglesia y el estado;
el habitante que sea declarado culpable ante dicho tribunal de asistentes,
de la manera ya mencionada, será enviado a prisión por un mes, y luego,
a menos que escoja voluntariamente abandonar esta jurisdicción,
dará fianza por su buen comportamiento y comparecerá en la siguiente sesión de la corte.
Si continúa obstinado y rehúsa retractarse y reformarse de las opiniones mencionadas,
será condenado al destierro bajo pena de muerte; y cualquier magistrado,
a partir de la información que se le proporcione de alguna persona así,
lo hará detener y lo enviará a prisión, según su criterio,
hasta que comparezca al juicio, como ya se mencionó.

--

Aquí termina este sanguinario acto,
más parecido a los decretos de la Inquisición Española
que a las leyes de una magistratura cristiana reformada,
constituida por aquellos que,
para evitar la persecución (que no era más que una
pequeña multa por no asistir al culto público),
habían abandonado la Vieja Inglaterra.
Este acto fue respondido por Francis Howgill,
y dicha respuesta fue publicada en forma impresa,
en la que claramente se mostró que el acto tenía
el lenguaje de los antiguos judíos y paganos perseguidores.
En lo que sigue, veremos la sangrienta ejecución de esto sobre algunas personas.
