== Capítulo 10

[.section-date]
1660

A principios de este año E. Burrough escribió la siguiente carta
al Parlamento que entonces tenía el poder en sus manos otra vez.

[.embedded-content-document.letter]
--

[.salutation]
Amigos,

Todos estos derrocamientos y casi asombrosos cambios,
fueron efectuados por la justicia de la mano del Señor. Ustedes
están ahora de nuevo en la cúspide del gobierno y sobre el trono,
y me atrevo a decir que es del Señor,
por el Señor y que Él lo ha hecho en contra de las expectativas de muchos.
Y cuál es Su fin en todo esto,
es algo que permanece en Él. Pero estoy seguro de que una de las causas es,
que ustedes ejecuten parte de Su ira sobre esa generación
traidora de hombres hipócritas y engañosos;
me refiero a algunos que son del ejército.
No necesito decirles, cuántos de ellos fueron levantados de un estado bajo,
y en lugar de servirle a la nación, se convirtieron en sus señores y opresores.
Estos han abusado de la misericordia del Señor hacia ellos,
y se han exaltado a sí mismos, y así, se convirtieron en grandes opresores,
y tan perjudiciales para la nación, como lo fueron siempre los que los precedieron.
Algunos de ellos cogieron los diezmos y las propiedades de sus enemigos,
y luego siguieron al espíritu malo en ellos; sin embargo,
el Señor fue paciente y les dio un día,
y puso en sus manos la oportunidad de hacer el bien,
pero también descuidaron servirle a Dios y a la nación, y se prefirieron a sí mismos.
Y a causa de la ambición y orgullo de algunos de ellos,
el Señor les permitió hacer esta última ruptura sobre ustedes,
la cual fue una gran traición a los ojos del pueblo,
para que la medida de ellos llegara al colmo,
y Él pudiera darles a ustedes ocasión contra ellos
y permitirles llenarse de indignación hacia ellos,
para hacerlos pedazos; y lo que ustedes les hacen a algunos de ellos,
al echarlos y afligirlos, no es más que ejecutar el designio de Dios en esto.
Porque ellos se han disfrazado por mucho tiempo en esta nación, profesando más que otros,
y sin embargo, haciendo menos; por tanto, su caída es ya.
Y Dios los ha considerado a ustedes lo suficientemente duros de corazón y crueles,
como para ser ejecutores adecuados de la venganza sobre tales hombres,
como lo he mencionado.

Pero ahora, con respecto a ustedes y a su presente estado,
ya que actualmente están en posición y poder, tengo algo que decirles:
Aunque ellos hayan caído y ustedes todavía estén de pie,
y tengan un poco de tiempo después de ellos, les digo lo siguiente:
No se gloríen de su caída, ni se gloríen como si fueran a estar de pie para siempre;
porque ellos no eran más pecadores que ustedes,
ni ustedes un poco más justos que algunos de ellos;
pero ustedes están tan seguros de caer como cayeron ellos,
con no menos medida de deshonra y aflicción que la que les sobrevino a ellos.
Ustedes están en su última hora y me atrevo a decir,
que Dios espera mucho más de ustedes,
que ser ejecutores de justicia sobre hombres tan pecadores como ustedes mismos.
Así que no se gloríen de los que han caído, sino sepan que su tiempo también es corto,
y la caída de ustedes puede resultar en su destrucción,
y la de ellos en hacerlos mejores y más refinados.
Y si Dios los ha escogido a ustedes para ejecutar alguna parte de Su ira sobre ellos,
a causa de la maldad, Él, sin ninguna duda,
encontrará instrumentos para ejecutar Su ira sobre ustedes,
o bien lo hará con Sus propias manos; porque no se propone perdonarlos,
porque sus pecados claman tan fuerte como los de otras personas,
y la opresión es tan grande bajo ustedes, como bajo aquellos a quienes ustedes condenan.
Deseo, si hay hombres buenos entre ustedes,
que los que son sabios consideren y tengan en cuenta la mano del
Señor en y a través de todas estas cosas que han sucedido;
porque Dios está trabajando así como ustedes.
Él está buscando establecer un reino al igual que ustedes,
y Su gobierno y el de ustedes no pueden permanecer juntos.
Él les hará saber que Él es más fuerte y que Su gobierno es de más fuerza,
y que el reino de ustedes no puede permanecer en lugar del Suyo.

Por eso les digo, ¡presten atención! ¡Sean sabios,
para que algunos de ustedes sean perdonados!
No sean demasiado celosos en sus caminos, ni demasiado furiosos en sus procedimientos;
sino hagan a los demás lo que quieren recibir de otros,
y del Señor también. No vayan más allá de su comisión;
porque ustedes han tenido permiso de Dios de azotar a los hipócritas,
y de ser un juicio sobre esa hipócrita y aparentemente
religiosa generación de hombres antes mencionados,
que muchas veces, por decirlo así,
se han burlado de Dios y pretendido amarlo con sus labios,
cuando sus corazones anhelaban el propio honor y los tesoros de este mundo.
Yo les digo, la hora y el permiso que ustedes tienen ahora son para ese fin;
no para perseguir al pueblo del Señor, ni para destruir la herencia de Dios.
Sin embargo, si extienden su poder hacia esa obra,
y persiguen al inocente sin ninguna causa,
y hacen guerra contra el Cordero y Sus seguidores,
y promulgan leyes y las ejecutan para la opresión de los santos del Altísimo,
están yendo más allá de su comisión; porque Dios no los ha llamado para eso,
sino para ser instrumentos en otra causa.
Los hijos de Sión confían en el Dios vivo y no temen el terror de los hombres poderosos,
ni pueden ser atemorizados por el rugido del mar,
ni por la amenaza actual de los paganos, porque Dios está con ellos.

Les digo, el siervo del Señor ha reflexionado y considerado todos estos procedimientos,
y ha visto el estado actual de las cosas,
y no hay visión de Dios para ustedes de paz y consuelo,
ni de un gobierno feliz y duradero tal como están ahora.
Si algún profeta les predice eso, habla lo que no ha recibido del Señor,
sino la visión de su propio corazón y los engaña a ustedes y a sí mismo.
Porque ustedes no están establecidos sobre un fundamento correcto,
ni actúan por un espíritu correcto que pueda gobernar verdaderamente para Dios,
sino que el espíritu de ira y furia está puesto en ustedes,
para la obra a la que han sido llamados.
Y no sé cómo amonestarlos para que no persigan al pueblo de Dios.
Porque puede ser que ustedes deban colmar su medida de maldad con ello,
para que Dios los quebrante perpetuamente; sin embargo,
el juicio será menor si no lo hacen.
Pero si lo hacen,
el Señor aprovechará la ocasión contra ustedes para herirlos y nunca serán sanados,
y según aflijan a otros, así y mucho más les será hecho por parte del Señor.

Por tanto, consideren lo que les he dicho;
porque esta es la visión del Todopoderoso para ustedes, la cual no quedará sin cumplir.
Y lo que hagan, deben hacerlo apresuradamente,
porque el tiempo es corto y Dios someterá el poder de ustedes pronto,
y rápidamente exaltará Su reino y Su poder sobre sus cabezas,
y los hará a ustedes y a la nación conocer que Él es Dios, y que todo poder está con Él,
y que Él puede hacer lo que quiera.
En realidad, sólo Él tiene derecho a reinar,
y es la porción de Sus hijos poseer el reino con
Él. ¡Qué toda la tierra y todos los poderes de esta,
se inclinen y tiemblen ante de Él! ¡Qué sus corazones
no sean decididos y rebeldes contra Él,
porque Él puede molerlos hasta el polvo, y hundirlos en confusión y miseria,
como se hunde una piedra en el mar!

[.signed-section-signature]
E+++.+++ Burrough

--

Esta fue dirigida a las manos del presidente del Parlamento,
y fue entregada a William Lenthal como corresponde,
y se adjuntó con las siguientes líneas:

[.embedded-content-document.letter]
--

[.salutation]
Amigo,

Te encomiendo que presentes ante la casa la carta adjunta,
y te esfuerces sinceramente por leerla en la asamblea;
ya que es de especial interés para todos ustedes.
Y en el nombre del Señor, y por Su Espíritu,
los exhorto a no ser negligentes en este asunto, como si no tuviera valor para ustedes;
lo pongo sobre ustedes, ya que, de lo contrario, responderán en el terrible día de Dios,
cuando el Rey de Justicia los juzgue a ustedes y a toda la humanidad.

[.signed-section-signature]
E+++.+++ Burrough

[.signed-section-context-close]
24 del mes Once de 1659.

--

Este Parlamento ordenó que cerca de mil quinientos
oficiales militares fueran dados de baja,
y pusieron a otros en sus puestos.

Por este tiempo George Fox el joven,
también les escribió una carta al Parlamento y al ejército, que decía lo siguiente:

[.embedded-content-document.letter]
--

El día de ustedes se ha convertido en tinieblas; el sol se ha puesto sobre ustedes.
Han tenido un gran día y se les ha dado poder para hacer la voluntad de Dios;
pero han abusado del poder y despreciado su día; se han negado hacer la obra del Señor,
y han buscado servirse a sí mismos y no al Señor. Por tanto,
el día en el que habrían podido trabajar para Dios
en justicia y rectitud les ha sido quitado;
y la espesa y oscura noche de confusión ha venido sobre ustedes,
en la que andan a tientas, tropiezan y no pueden trabajar.
El decreto ha salido y está sellado contra ustedes, y no puede ser revocado.
Ustedes no son los hombres (tal como están) en quienes Dios aparecerá
para obrar la liberación de Su pueblo y de Sus criaturas;
y sin embargo, la liberación vendrá, pero no según las expectativas del hombre.
Pero en cuanto a ustedes, han rechazado el consejo del Señor y afligido a Su Espíritu,
y Él los ha soportado por mucho tiempo.
Sí, ustedes se han apartado del Señor, y Su presencia se ha apartado de ustedes.
En efecto, Él ha labrado con ustedes, y si hubieran sido fieles hasta el final,
Él los habría honrado y prosperado, y eso les habría sido suficiente recompensa.
Ustedes eran Su hacha, pero se han jactado contra Él. Por lo tanto,
así como han golpeado, talado y quebrado a otros, así deben ser ahora golpeados,
talados y quebrados;
porque ustedes han provocado gravemente al Señor. Si Él permitiera que
el árbol que han talado cayera sobre ustedes y quebrara parte de ustedes,
sería justo.

¡Oh, pueblo traidor, voluntarioso, orgulloso y egoísta,
que ha despreciado el consejo del Señor y no ha querido aceptar advertencia,
aunque haya enviado entre ustedes a Sus profetas y siervos, temprano y tarde,
a algunos de los cuales ustedes han encarcelado y ultrajado! ¿Qué harán ahora?
¿A quién acudirán en busca de ayuda,
siendo que se han apartado del Señor y se están despedazando, rasgando,
mordiendo y devorando unos a otros por fines orgullosos, ambiciosos y egoístas?
Tomen nota de esto; si ustedes ahora construyeran de nuevo lo que una vez destruyeron,
eso no será capaz de esconderlos o protegerlos de la ira del Cordero,
y esa manera por la que piensan fortalecerse a sí mismos,
sólo los hará mucho más débiles y ayudará a adelantar su
propia destrucción. Ustedes ahora no son más que una vara,
así que recuerden su fin, el cual se precipita rápidamente.
Porque ahora vendrá brecha sobre brecha, insurrección sobre insurrección,
derrocamiento sobre derrocamiento, montón sobre montón, división sobre división,
hasta que Él llegue a reinar, Aquel cuyo es el derecho.
Todas las naciones deben inclinarse delante de Él, de lo contrario,
Él las quebrantará con Su vara de hierro.

Los que confían o se apoyan en ustedes en busca de ayuda,
es como si se apoyaran en una caña frágil, que no es capaz de ayudarse a sí misma,
ni a otros.
De hecho, ustedes han sido llamados a hacer muchas cosas buenas,
pero no han querido llevar a cabo la obra que Dios quería que fuera realizada,
y por eso han venido estas cosas sobre ustedes.
Por tanto, tiemblen y teman delante del Señor,
ustedes que han sido como robles fuertes y cedros altos,
porque su fuerza les fallará ahora y serán débiles, como el más débil de los hombres.
Pero si aún creyeran en la luz y verdaderamente se
sometieran a los justos juicios de Dios,
muchos de ustedes podrían llegar a experimentar la
salvación de sus almas en el día del Señor;
aunque (debido a sus graves rebeliones) muchos de sus cuerpos vayan
a ser desechados y considerados indignos de ser obreros del Señor.

Todavía hay un pequeño remanente entre ustedes por el que mi alma respira,
que puede ser aventado; y si estos aceptan los juicios del Señor,
se niegan verdadera y completamente y siguen Sus indicaciones,
Él sanará sus rebeliones y los purgará, para que sean instrumentos en Su mano.
Pero aquellos que continúen con ustedes en los pecados de ustedes,
ciertamente participarán con ustedes de los juicios de ustedes.

La vara del malvado no descansará siempre sobre la espalda de los justos; no obstante,
así como es probado el oro, serán probados ellos,
para que sean blancos y sin mancha delante del Cordero.
Pero Dios vengará la causa de ellos, y entonces el ay será para todos sus opresores.
Luego la majestad y la gloria del Señor llenarán a Su pueblo largamente pisoteado,
y serán el pavor de las naciones; el celo del Señor de los ejércitos hará esto.

[.signed-section-signature]
George Fox, _el joven._

[.signed-section-context-close]
Mes Once de 1659

--

Esta carta se imprimió y se le entregó una copia a cada hombre del Parlamento,
antes de que el general Monck y su ejército entraran en Londres.
Cuán pronto se cumplieron las predicciones contenidas en esta carta,
así como también las de E. Burrough del año anterior,
cuando muchos de los grandes fueron colgados y descuartizados,^
footnote:[Una forma de castigo para los culpables de traición,
en la que primero se colgaba al culpable por el cuello casi al punto de muerte,
luego eran castrados, destripados, decapitados y descuartizados en cuatro piezas.
Los restos a menudo eran expuestos en un lugar famoso del país,
tal como el puente de Londres, para que sirviera como advertencia a los demás.]
lo veremos en lo que sigue.

El general Monck había salido entonces de Escocia a Londres,
con parte del ejército que él comandaba,
y tras hacer grandes cambios entre los oficiales,
puso a los que creía que no eran enemigos de Carlos Estuardo.
Porque, a pesar de que Monck hablaba de su resolución de ser veraz y fiel al Parlamento,
y de promover el interés de la Mancomunidad, pronto se vio que su objetivo era otro;
aunque no había dudado en decirle a Edmund Ludlow: "`Debemos vivir o morir,
por y con la Mancomunidad;`" y a otros les había declarado que
él se opondría al máximo al establecimiento de Carlos Estuardo.
Mientras tanto, ordenó todo de manera tal,
que muchos miembros del Parlamento que habían sido
excluidos hacía mucho tiempo por no estar calificados,
volvieran a sesionar en dicha asamblea; y estos hicieron que sir George Booth,
que estaba confinado en la Torre por haber llevado
a cabo un intento de establecer a Carlos Estuardo,
fuera puesto en libertad.
La ciudad de Londres tampoco estaba en condiciones de oponerse a Monck,
porque él hizo que las puertas y postes de la ciudad fueran derribadas,
y los monárquicos se habían vuelto entonces tan audaces,
que imprimieron una lista con los nombres de los jueces que habían condenado a muerte
al rey Carlos I. Algunos de estos hombres fueron detenidos mientras que otros huyeron.
El general Lambert también fue enviado a la Torre, y Monck,
cuya autoridad había aumentado,
envió a llamar a los señores que hasta el año 1648 se habían sentado en el Parlamento,
y les pidió que regresaran a la casa donde solían sentarse en el pasado.

En este giro de cosas llegó G. Fox a Londres,
cuando estaban derribando las puertas de la ciudad.
Entonces él les escribió un documento a los que se hundían,
y les dijo que se estaban cumpliendo las profecías
que habían sido dichas con respecto a ellos,
y que aquellos que solían llamar a los Cuáqueros "`fanáticos`"
y "`cabezas de chorlito,`" ahora parecían más bien mareados,
y andaban fugitivos o vagabundos.

De Londres G. Fox se fue a Sussex, y de ahí a Dorsetshire.
En Dorchester tuvo una gran reunión por la noche en la posada donde estaba alojado,
a la que llegaron muchos soldados que se portaron bastante corteses.
Pero también llegaron los alguaciles y oficiales del pueblo,
con el pretexto de buscar a un Jesuita cuya cabeza, decían, estaba afeitada.
Por tanto, le quitaron el sombrero a G. Fox,
pero al no encontrar ninguna calva en su cabeza, se marcharon avergonzados.
Esta reunión fue de buen servicio entre los soldados y otros, y afectó a la gente,
quienes fueron vueltas al Señor Jesucristo.

Luego pasó a Somerstshire,
donde las reuniones de sus amigos eran con frecuencia perturbadas.
Una vez llegó un hombre perverso, quien teniendo una piel de oso sobre su espalda,
hizo feas bromas en la reunión, y sentándose frente a la persona que predicaba,
sacaba la lengua de su boca;
así divirtió a sus malvados seguidores y provocó un gran trastorno
en la reunión. Pero cuando este hombre regresaba de la reunión,
un notable juicio lo alcanzó, porque había un "`hostigamiento de toros`"^
footnote:[Un espectáculo sangriento que consistía
en enfrentar a un toro enfurecido contra otro animal,
normalmente un perro o un oso.]
en el camino y se quedó para mirarlo; y al llegar al alcance del hombre,
el toro empujó su cuerno bajo la barbilla del hombre, en su garganta,
y obligó que la lengua saliera de su boca y colgara de la misma manera
que antes la había sacado en son de burla en la reunión. Y el toro,
atravesando la cabeza del hombre con su cuerno, lo hizo balancearse de manera terrible.

Viajando por Somersetshire, G. Fox llegó a Devonshire y se adentró en Cornwall,
hasta que llegó a Land`'s End.
Mientras estaba en Cornwall, hubo grandes naufragios cerca de Land`'s End.
Ahora bien, era costumbre en ese condado,
que en tales ocasiones tanto ricos como pobres salieran
a coger todo lo que pudieran del naufragio,
sin preocuparse por salvar las vidas de las personas.
Esta costumbre prevaleció tanto,
que en algunas partes del condado llamaban a los naufragios "`gracia de Dios.`"
Esto afligió mucho a G. Fox,
al considerar que estos supuestos Cristianos se comportaban
mucho peor que los paganos en Malta,
quienes cortésmente habían recibido a Pablo y a los
otros que habían sufrido un naufragio con él,
y les habían hecho un fuego.
A raíz de esta consideración,
se sintió movido a escribirles un documento a los magistrados,
a los sacerdotes y a otros, tanto de alto como de bajo rango,
en el que les mostraba la maldad de sus actos y los reprendía por esas acciones codiciosas,
mostrándoles cómo estaban listos a pelear unos contra otros por el botín, y luego,
a gastar lo que obtenían en tabernas o cervecerías,
dejando a los que habían escapado de ahogarse, mendigando por todo el condado.
Por lo tanto, los exhortó seriamente a hacer por otros lo que habrían hecho por sí mismos.

Este documento fue enviado a todas las parroquias de los alrededores,
y después de haber tenido muchas reuniones en Cornwall,
en las que varias personas importantes fueron convencidas de la Verdad predicada por él,
se fue a Bristol,
donde las reuniones de sus amigos eran sumamente perturbadas por los soldados.
Al oír esto, quiso que George Bishop, Thomas Gouldney, Thomas Speed y Edward Pyot,
fueran a ver al alcalde y a los concejales,
y les pidieran que dejaran que sus amigos se reunieran en el ayuntamiento,
siempre y cuando no fueran los días cuando el alcalde
y los concejales tuvieran asuntos en él;
y que por ese uso ellos les darían veinte libras
al año para que fueran distribuidas entre los pobres.

Estas personas se asombraron de esta propuesta,
y dijeron que el alcalde y los concejales pensarían que estaban locos,
porque el alcalde y el comandante de los soldados
se habían unido para perturbar sus reuniones.
Pero G. Fox los animó de tal manera,
que al final consintieron en lo que quería. Al llegar donde el alcalde,
lo encontraron bastante moderado, más allá de las expectativas,
y cuando le expusieron el asunto, les dijo: "`De mi parte, podría consentirlo,
pero no soy más que uno.`"
Así, pues, lo dejaron en un estado de ánimo cordial; y cuando regresaron,
G+++.+++ Fox quiso que también fueran a ver al coronel que comandaba a los soldados,
y le informaran de la ruda actitud de ellos y cómo perturbaban las reuniones.
Pero las cuatro personas mencionadas, se mostraron reacias a ir.
La mañana siguiente, que era Primer-día de la semana,
se celebró una reunión en un huerto, a la que llegaron muchas personas;
y después de que G. Fox había predicado bastante rato, llegaron varios soldados toscos,
algunos con espadas desenvainadas y otros borrachos,
y entre estos había uno que se había atado con un juramento
de cortar y matar al hombre que estuviera hablando.
Pero cuando llegó,
y se abría paso entre la multitud a empujones y estaba a dos yardas de G. Fox,
se detuvo ante las cuatro personas antes mencionadas y se puso a discutir con ellas,
y al final volvió a envainar su espada.
Al día siguiente fueron y hablaron con el coronel,
y después de enterarlo de cuán perjudiciales habían sido sus soldados,
él los mandó a llamar, y cortó y acuchilló a algunos de ellos.
Pero cuando le contaron a G. Fox, culpó a sus cuatro amigos,
creyendo que ellos habrían podido evitar las heridas de los soldados,
si hubieran ido a ver al coronel cuando él lo había querido.
Sin embargo, esto tuvo tal efecto,
que la reunión se mantuvo sin disturbios por un buen tiempo.

G+++.+++ Fox también celebró después una reunión general en la casa de Edward Pyot,
cerca de Bristol, a la que asistieron varios miles de personas;
y acudieron tantos de Bristol,
que algunos dijeron que la ciudad se veía desnuda y todo estaba tranquilo.

Pero en otros lugares, por esta época, las cosas no estaban tan tranquilas,
porque los soldados bajo el comando del general Monck,
a menudo eran muy rudos al perturbar las reuniones.
Pero cuando se presentó una queja delante de él,
quien para entonces estaba en Westminster, demostró que no toleraría tales maldades,
y en ese sentido, hizo algo mejor que lo que habían hecho otros generales,
porque dio la siguiente orden.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
St. James`'s, 9 de Marzo, 1659-60

Ordeno que todos los oficiales y soldados se abstengan
de perturbar las reuniones pacíficas de los Cuáqueros,
ya que ellos no hacen nada perjudicial contra el Parlamento o la Mancomunidad de Inglaterra.

[.signed-section-signature]
George Monck.

--

Monck,
que por mucho tiempo se había declarado a favor de
una mancomunidad y en contra de un rey,
empezó a quitarse la máscara,
porque los antiguos señores ya habían vuelto a tomar
sus lugares en la Cámara de los Pares,
de la que habían sido apartados por muchos años. Y por consejo del general Monck,
Carlos Estuardo (quien por varios años había vivido en Colonia,
y tras hacer un viaje a España, había llegado de ahí a Bruselas por Francia),
se dirigió a Breda, en Holanda.
Y estando ya resuelto en Inglaterra que lo llamarían y restaurarían,
dio la siguiente declaración en Breda,
para persuadir a los que todavía se resistían a reconocerlo.

[.embedded-content-document.epistle]
--

Carlos, por la gracia de Dios, rey de Inglaterra, Escocia, Francia e Irlanda,
defensor de la fe, etc., a todos nuestros amados súbditos, de cualquier grado o calidad,
saludos.

Si la locura y confusión general que se ha extendido por todo el reino,
no despierta en todos los hombres un deseo y anhelo de que esas heridas
(que por muchos años se han mantenido sangrando) sean vendadas,
todo lo que podamos decir será inútil.
No obstante, después de este largo silencio, hemos pensado que es nuestro deber declarar,
cuánto deseamos contribuir con ello;
y dado que nunca renunciamos a la esperanza de obtener, a su debido tiempo,
la posesión del derecho que Dios y la naturaleza han hecho nuestro deber,
lo hemos hecho nuestra diaria petición a la Divina Providencia, para que Él,
en compasión hacia nosotros y nuestros súbditos,
y después de tanta miseria y sufrimientos, perdone,
y nos ponga en tranquila y pacífica posesión de eso que es nuestro derecho,
con tan poco derramamiento de sangre y daño para nuestro pueblo como sea posible.
Tampoco deseamos disfrutar lo que es nuestro,
más de lo que nos gustaría ver a todos nuestros súbditos
disfrutar lo que por ley es de ellos,
por medio de una completa y total administración de justicia en todo el país,
y extendiendo nuestra misericordia donde se necesite y desee.

Y con el fin de que el temor al castigo no incite a nadie,
que tenga consciencia de lo pasado,
a perseverar en la culpa en el futuro oponiéndose a la paz y felicidad
de su país en el restablecimiento tanto del rey,
como de los pares y del pueblo, y de sus derechos justos, antiguos y fundamentales;
por la presente declaramos que concedemos un perdón libre y general, el cual,
previa solicitud, estamos listos a afirmar bajo nuestro gran sello de Inglaterra,
para todos nuestros súbditos, de cualquier grado o calidad,
que dentro de los cuarenta días después de publicado el mismo,
se acoja a esta nuestra gracia y favor, y mediante un acta pública declare que lo hace,
y que regresa a la lealtad y obediencia de los buenos súbditos;
exceptuando únicamente a las personas que en lo sucesivo,
sean exceptuadas por el Parlamento.
Exceptuando sólo a estos, que todos nuestros súbditos, por muy culpables que sean,
confíen en la palabra del rey, solemnemente dada por medio de la presente declaración,
que ningún delito cometido contra nosotros, o contra nuestro soberano padre,
antes de la publicación de esta, será jamás juzgado, o alguno de ellos cuestionado,
para el menor perjuicio de ellos, ya sea en sus vidas, libertades o propiedades;
o en la medida que esté en nuestro poder, en perjuicio de sus reputaciones,
mediante algún reproche o término de distinción del resto de nuestros súbditos.
Deseamos y ordenamos que en lo sucesivo, todas las notas de discordia,
separación y diferencia de partidos,
sean completamente abolidas entre todos nuestros súbditos,
a quienes invitamos y llamamos a una perfecta unión entre sí, bajo nuestra protección,
para el restablecimiento de nuestros justos derechos, y los de ellos,
en un Parlamento libre, por medio del cual, tras la palabra del rey, seremos asesorados.

Y debido,
a que la pasión y falta de caridad de la época ha
producido varias opiniones en materia de religión,
por las que los hombres ahora están involucrados
en partidos y animosidades unos contra otros (quienes,
cuando en adelante se unan en una conversación libre, tal vez se entiendan mejor),
declaramos libertad para las consciencias tiernas,
y que ningún hombre sea molestado o cuestionado por
diferencias de opinión en asuntos de religión,
que no perturban la paz del reino.
Y estamos dispuestos a aprobar para estos un acta del Parlamento, que,
tras una madura deliberación, se nos ofrezca para la plena concesión de esta indulgencia.

Y debido a que en la continua confusión de tantos años, y tantas y grandes revoluciones,
han sido hechas muchas concesiones y compras de propiedades, a y por muchos oficiales,
soldados y otros, que entonces poseía la misma,
y que pueden estar sujetos a acciones legales sobre varios títulos,
estamos igualmente dispuestos a que todas esas diferencias,
y todas las cosas relacionadas con tales concesiones, ventas y compras,
sean resueltas en el Parlamento,
que es el que mejor puede estipular para la justa
satisfacción de todos los hombres interesados.

Y declaramos además, que estaremos dispuestos a aprobar cualquier acta,
o actas del Parlamento, para los fines antes mencionados,
y para la plena satisfacción de todas las obligaciones financieras
adeudadas a los oficiales y soldados del ejército,
bajo el comando del general Monck,
y que serán recibidos en nuestro servicio con tan
buena paga y condiciones como las que disfrutan ahora.

Dado bajo nuestro signo y sello en nuestra corte en Breda, el día 14 de Abril de 1660,
en el duodécimo año de nuestro reinado.

--

El original de esta declaración fue enviada a la Cámara de los Lores,
y un duplicado fue enviado a la Cámara de los Comunes,
el cual fue copiado y enviado en una carta al general Monck,
al consejo de estado y a los oficiales del ejército.
Acto seguido, el Parlamento resolvió preparar una respuesta;
y tanto en la Cámara de los Lores como en la Cámara de los Comunes,
se votó proclamar al rey Carlos en Whitehall y en Londres,
como el legítimo soberano de estos reinos, lo cual fue hecho el 8 del mes llamado mayo.

Ahora bien, el rey,
quien fue invitado por los españoles a regresar a
Bruselas y por los franceses a llegar a Calais,
escogió, ante la apremiante invitación de los Estados Generales de las Provincias Unidas,
ir por el camino de Holanda.
Y así se fue, con los yates de los Estados hasta Rotterdam,
y de ahí en carruajes hasta La Haya, donde tras estar unos días,
se embarcó en Schevenningen hacia Inglaterra,
e hizo su entrada en Londres en el aniversario de su cumpleaños. Y así
vemos a Carlos II restaurado (quien no mucho después fue coronado),
no por espada, sino por la maravillosa mano del Señor.

Por esta época G. Fox el joven llegó a Harwich,
donde fue sacado de una reunión y encarcelado bajo
el pretexto de haber provocado un tumulto.
Pero a fin de darle al lector una verdadera perspectiva del asunto,
debo devolverme un poco.

Unos cuatro años antes de este tiempo,
llegaron al mencionado pueblo algunas personas de los llamados Cuáqueros,
y una de ellas dijo unas pocas palabras a manera de exhortación a la gente que
venía de la '`casa del campanario;`' y continuando,
él y los que lo acompañaban fueron a una posada.
Cuando el alcalde se enteró, los mandó a llamar y les ordenó salir del pueblo,
lo que hicieron al cabo de un corto tiempo;
pero en la noche regresaron y se alojaron en la posada,
y al día siguiente se fueron pacíficamente.
No mucho después de esto,
se le ordenó a la mujer que administraba la posada presentarse ante los magistrados,
quienes la amenazaron con quitarle su licencia,
a menos que prometiera no alojar más a tales personas.
Pero aunque ellos estaban ansiosos de mantener fuera a los Cuáqueros, resultó ineficaz,
porque parece que algunos de los que oyeron lo que
se había dicho en la calle fueron tan alcanzados,
que llegaron a ser obedientes a las enseñanzas internas del Señor,
a las que habían sido dirigidos.
Y así se abrió el camino para que se iniciaran las reuniones en el pueblo,
por lo que el número de los de esa sociedad se empezó a incrementar.
Y debido a que estos no podían seguir cumpliendo
con los entierros supersticiosos de la época,
compraron un pedazo de terreno en el cual enterrar a sus muertos.
Pero esto se topó con gran oposición, y en una ocasión,
cuando varios llegaron a enterrar un cadáver,
este fue tomado por la fuerza y puesto a la orilla del mar,
donde tras permanecer sobre el suelo parte de dos días y una noche,
algunos lo cubrieron en secreto con piedras pequeñas.

En el mes llamado mayo,
G+++.+++ Fox el joven llegó a Harwich para predicar la
Verdad allí. Cuando el alcalde del pueblo,
cuyo nombre era Miles Hubbard, se enteró,
detuvo a varios que iban para la reunión. Luego, una multitud ruda,
al ver a la gente reunida,
se insolentó y empezó a hacer un ruido espantoso
frente a la casa donde se celebraba la reunión,
y algunos de ellos eran partidarios de derribar la casa.
Al oír G. Fox el ruido mientras predicaba,
le entró un celo y con gran poder fue impulsado a decir: "`¡Ay,
ay de los gobernantes y maestros de esta nación, que permiten una impiedad como esta,
y no procuran suprimirla!`"
Algunos que lo oyeron hablando así, fueron y se lo dijeron a los magistrados, tal vez,
no con las palabras exactas que fueron pronunciadas por él. Cuando llegaron los oficiales,
el alcalde les ordenó a los alguaciles que tomaran bajo custodia a dicho G. Fox,
quien al enterarse de eso dijo: "`Si yo he hecho algo digno de muerte o de prisión,
no rechazaré ninguna de las dos cosas;
pero quiero que me muestren qué ley he transgredido;
lo que ustedes deberían hacer antes de enviarme a prisión,
para que yo sepa por qué razón estoy siendo enviado
ahí.`" Pero el alcalde le dijo que lo sabría después;
y así fue llevado a prisión.

Robert Grassingham, que era constructor de barcos para el almirantazgo en ese puerto,
estaba en la reunión de la que G. Fox fue sacado,
y en amor fue libremente junto con él a prisión. Esto pareció agradarle al alcalde,
a quien algunos días antes se le había oído decir con respecto a Grassingham:
"`Si yo pudiera sacarlo del pueblo, sabría qué curso seguir con los otros Cuáqueros.`"
Un tiempo después del encarcelamiento de G. Fox,
se le envió al carcelero una orden judicial,
en la que el prisionero era culpado de provocar un
tumulto en dicho pueblo y perturbar la paz.
Esta orden judicial estaba firmada por Miles Hubbard, alcalde,
Anthony Wollward y Daniel Smith;
y estos magistrados enviaron una notificación de lo que habían hecho al Parlamento,
bajo el pretexto de que así no caerían en desgracia.
Cuando el Parlamento recibió esta información, emitió la siguiente orden:

[.embedded-content-document.legal]
--

[.signed-section-context-open]
Lunes 21 de Mayo, de 1660.

Se le ha informado a la Cámara que dos Cuáqueros, es decir,
George Fox y Robert Grassingham, últimamente han provocado disturbios en Harwich,
y que el citado George Fox, quien pretende ser predicador,
en la última predicación allí pronunció palabras
recriminatorias contra el gobierno y el ministerio,
hasta casi causar un motín, y ha sido encerrado ahí por el alcalde y los magistrados:

Se ordena, por tanto,
que los citados George Fox y Robert Grassingham sea inmediatamente puestos bajo custodia,
y que el alguacil del condado de Essex los reciba
y les dé ayuda para transportarlos como corresponde,
y entregarlos a cargo del sargento de armas que asiste esta Cámara.

Se ordena también,
que se les dé el agradecimiento de esta Cámara al alcalde y a los magistrados de Harwich,
por su cuidado en este asunto.

[.signed-section-signature]
William Jessop

[.signed-section-context-close]
Secretario de la Cámara de los Comunes del Parlamento.

--

Por esto,
parecía que los magistrados de Harwich tenían amigos especiales en el Parlamento.
Robert Grassingham, estando en libertad, se había ido a Londres,
y cuando esta orden llegó a Harwich,
G+++.+++ Fox fue entregado al alguacil de Essex y a sus hombres.
Estos fueron con él a Londres, y en el camino se encontraron con Grassingham,
que estaba regresando de Londres a Harwich,
en cumplimiento de una orden que había recibido del
comisario del almirantazgo y de la marina,
para reparar una de las fragatas del rey.
Pero, a pesar de que Grassingham le mostró la orden al alguacil,
fue llevado de regreso a Londres con Fox,
y entregado a la custodia del sargento de armas que asistía la Cámara,
quien los envió a Lambeth House.
Después de estar ahí unas tres semanas,
escribieron una carta a la Cámara de los Comunes en la que
hacían un recuento de la manera en que habían sido encarcelados,
y querían que ellos y sus acusadores fueran llevados cara a cara delante del Parlamento,
diciendo que si podían probar algo en contra de ellos digno de castigo,
ellos no lo rechazarían;
y que consideraban injusto e irrazonable que un hombre fuera
sacado de una reunión pacífica y enviado a prisión,
sin ser interrogado,
sólo por declarar contra las maldiciones y perversidades de la gente tosca y ruda,
y contra los que permitían tal impiedad y no trataban de suprimirla.

Este era el contenido principal del documento,
que ellos adjuntaron a un carta para el presidente
de la Cámara de los Comunes con estas palabras:

[.embedded-content-document.letter]
--

[.letter-heading]
Para el Presidente de la Casa de los Comunes

[.salutation]
Amigo,

Deseamos que comuniques esta carta adjunta a la Cámara de los Comunes,
ya que son unas pocas palabras para ellos, inocentes, justas y razonables;
y aunque no están en el lenguaje elocuente de la sabiduría del hombre,
sí lo están en la verdad que es honorable.
Somos amigos de la justicia y la verdad, y de todos los que son hallados en ellas.

[.signed-section-signature]
Robert Grassingham, George Fox.

--

Sin embargo, el presidente no entregó el documento,
bajo el pretexto de que no estaba dirigido con el título ordinario:
"`A la Honorable Casa de los Comunes.`"
Por tanto, con la ayuda de sus amigos,
consiguieron imprimirla para que cada miembro del Parlamento pudiera tener una copia.
Ahora bien,
después de que ellos habían estado cerca de catorce
semanas en Lambeth gate-house sin haber sido interrogados,
uno de los miembros del Parlamento movió este asunto en la Cámara;
con lo cual se emitió la siguiente orden:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Jueves, 30 de Octubre de 1660.

Se ordena que George Fox y Robert Grassingham,
quienes en virtud de una orden anterior de esta Cámara,
fueron puestos bajo custodia por el sargento de armas
que asiste esta Cámara por unos disturbios en Harwich,
sean inmediatamente soltados y puestos en libertad,
tras pagar primero una fianza por sí mismos.

[.signed-section-signature]
William Jessop

[.signed-section-context-close]
Secretario de la Cámara de los Comunes.

--

Poco después de que se emitió esta orden,
el sargento de armas envió a su secretario para exigirles a los
prisioneros los honorarios y el alquiler de la habitación,
pidiéndoles cincuenta libras por los honorarios y diez chelines a la semana como alquiler.
Pero como no se les había imputado ningún mal,
no pudieron decidirse a satisfacer esa irrazonable exigencia,
sino que ofrecieron pagar dos chelines y seis peniques por semana,
aunque la habitación en la que habían permanecido
era la habitación más alta de una torre elevada,
y todas las ventanas estaban sin vidrios hasta que ellos lograron arreglarlas,
sin ningún cargo para el sargento.
Así las cosas, la causa de ellos le fue mencionada al consejo privado del rey,
pero todavía iba a pasar un buen rato antes de que fueran soltados;
pues se usaron varias evasivas para mantenerlos bajo custodia.

Mientras G. Fox estaba prisionero, escribió un pequeño libro al que llamó,
"`__A Noble Salutation to king Charles Stuart,__`"^
footnote:[Un Noble Saludo al Rey Carlos Estuardo.]
en el que le mostraba cómo habían sido las cosas en Inglaterra, a saber:
Que el partido de su padre había despreciado a los
que se presentaban en armas contra ellos,
por su aspecto poco impresionante; pues eran comerciantes, labradores,
sirvientes y similares;
despreciables instrumentos de los que Dios se servía
para derribar la altivez de los demás. Pero que luego,
cuando los del partido a favor del Parlamento habían alcanzado el éxito y prevalecido,
y habían ocupado el lugar de los que habían conquistado,
cayeron en el mismo orgullo y opresión contra lo que ellos habían clamado en los otros;
y muchos de ellos se convirtieron en mayores opresores y perseguidores
de lo que habían sido los del partido del rey.
Además,
el autor exhortaba al rey a observar la mano del
Señor en su restauración. "`Por tanto,`" decía él,
"`que ningún hombre te engañe,
persuadiéndote de que estas cosas han sucedido así porque el reino era tu derecho propio,
y porque te había sido retenido contra todo derecho;
y porque los llamados monárquicos son más justos
que los que ahora han caído debajo de ti.
Porque yo claramente te declaro, que este reino y todos los reinos de la tierra,
son propiamente del Señor. Y debes saber esto, que fue la mano justa de Dios,
la que le quitó el reino a tu padre y a ti, para dárselo a otros;
y que es también la mano justa del Señor,
tomarlo de nuevo de ellos y ponerlos a ellos debajo de ti;
si bien algunos se excedieron en su comisión contra tu padre,
cuando fueron traídos como una vara contra ustedes.
Y será bueno para ti, que no llegues a ser culpable de las mismas transgresiones.`"

El autor además exhortó al rey a considerar,
que su actual posición no estaba exenta de peligro debido a la inestabilidad del pueblo,
una gran parte del cual era desleal.
Porque en un momento dado, ellos habían jurado a favor de un rey y un Parlamento,
pero poco después habían jurado contra un rey, un único líder y una Cámara de Lores;
y luego, habían vuelto a jurar a favor de un único líder.
Que un tiempo después de esto, habían ensalzado de nuevo un Parlamento,
y que cuando Oliver Cromwell había expulsado al Parlamento y se había erigido,
los sacerdotes habían orado por él y afirmado que su autoridad era justa.
Y que cuando él había muerto,
ellos habían adulado a su hijo Richard y llamado blasfemamente a su padre,
'`la luz de sus ojos y el aliento de sus narices;`' y le dijeron a Richard que Dios
lo había dejado a él para que continuara la gloriosa obra que su padre había comenzado.
Sí, que algunos sacerdotes habían comparado a Oliver con Moisés y a Richard con Josué,
quien debía llevarlos a la tierra prometida.
Y que así, ellos habían adulado continuamente a los que estaban al mando.
Y que cuando George Booth había levantado una revuelta,
y ellos habían pensado que iba a haber un cambio,
algunos de los sacerdotes habían clamado contra el Parlamento
y maldecido a todos los que no habían salido contra ellos;
pero que cuando Booth había sido apresado,
entonces muchos empezaron a pedir el Parlamento y a excusarse diciendo,
que ellos no habían metido mano en ese levantamiento.

A continuación, el autor expone la maldad de los que, con excesiva bebida y embriaguez,
pretendían mostrar su lealtad al rey; y también relata,
cómo habiendo predicado en Harwich contra la grave maldad del pueblo,
había sido arrastrado a prisión en nombre del rey.
Finalmente, exhorta al rey a tener cuidado de buscar venganza, y a mostrar misericordia.

Este documento, que no era pequeño, pues ocupó varias páginas, fue entregado por escrito,
por medio de Richard Hubberthorn, en la mano del rey en Whitehall,
y no mucho después fue publicado en forma impresa por el autor.

Por esta época,
uno de los más eminentes monárquicos formuló varias preguntas a los Cuáqueros,
deseando que las respondieran y que dirigieran sus respuestas con este sobrescrito:
"`__Tradite hanc amico Regis,__`" es decir, "`Entregad esto al amigo del rey.`"
Porque se había visto claramente,
que varias de sus predicciones se habían llegado a cumplir,
de las cuales las de Edward Burrough no eran las menos.
Y por tanto,
algunos (según parece) pensaban que por medio de
los Cuáqueros podrían obtener algún conocimiento,
sobre si se podía esperar alguna estabilidad del gobierno del rey.
Por estas preguntas,
parecía que el autor de ellas era un hombre de entendimiento y de cierta moderación;
y aunque yo no sé quién era, no dejo de pensar que Edward Hyde,
conde de Clarendon y alto canciller, podría haber sido el autor de estas.
La tendencia de estas preguntas era, principalmente,
saber cuál era el juicio de los Cuáqueros con respecto al derecho del rey a la corona,
si alguna vez habían previsto su regreso,
y si podían juzgar si su reinado y gobierno serían bendecidos o no.
Además, se preguntaba si él podía justamente perdonar o vengarse,
y si podía permitir la libertad de consciencia a toda clase de personas, etc.

Edward Burrough respondió las preguntas,
y publicó su respuesta de manera impresa dirigiéndola al rey y a los monárquicos.
En ella mostraba que en algunos de sus escritos,
ya se había dado a entender que ellos tenían algunas
expectativas de la restauración del rey,
y que la llegada del rey al trono era razonable y justa,
al haberse llevado a cabo por el propósito del Señor. También
afirmaba que su reinado y gobierno podían ser bendecidos,
o no, según cómo se condujera él;
que podía perdonar justamente a sus enemigos y a los de su padre,
porque aunque él y su padre pudieran haber sido ofendidos,
por mucho que habían recurrido a la espada para resolver su controversia con la nación,
la espada se había vuelto contra ellos,
y que esa espada con la que habían pensado permanecer,
había sido por la que habían caído. Y que,
¿a quién culparían entonces por lo que les había sucedido,
viendo cómo la espada que ellos habían elegido, había sido la que los había destruido?
Sin embargo, el autor indicó que esto no se refería a la muerte del rey;
ya que eso era otro caso.

A la pregunta,
si la culpa de las grandes aflicciones sufridas por el rey por varios años,
por parte de los súbditos de su propia nación,
recaía sobre todos los súbditos en general, o sobre algunos,
o sobre algunas personas en particular que eran más culpables que otros;
E+++.+++ Burrough respondió:

[.embedded-content-document.address]
--

En la medida que sus sufrimientos hayan sido injustos,
la culpa de estos no recae sobre todos los súbditos en general,
sino sobre algunos más que sobre otros.
Estos son fáciles de distinguir de los otros,
si se considera quiénes fueron los que levantaron la guerra contra el rey en esta nación;
quiénes predicaron y pidieron la guerra primero,
y la prosiguieron contra el padre del rey;
quiénes expulsaron a los obispos y prelados de sus puestos,
tomaron sus rentas y beneficios, y se volvieron hombres tan corruptos,
codiciosos y egoístas, tan orgullosos y ambiciosos, perseguidores tan injustos,
como alguna vez lo fueron los hombres que ellos habían expulsado.
Si se considera también,
quiénes han adquirido grandes propiedades en la nación y honores mundanos,
y se han levantado de la nada por estas guerras y por los sufrimientos de ustedes;
y quiénes tomaron las propiedades y títulos de sus
enemigos y pretendieron liberarlos de toda opresión,
pero no lo han hecho, sino que más bien, han continuado la vieja opresión,
mientras se pelean entre ellos acerca de quién debe gobernar y quién debe ser grande.

En cuanto a nosotros, los llamados Cuáqueros,
estamos libres de la culpa de todos los sufrimientos del rey.
Nosotros no hemos expulsado a otros, ni tomado sus puestos de grandes beneficios,
ni hemos hecho guerra con armas carnales contra nadie, desde que somos un pueblo.
No hemos roto juramentos ni compromisos, ni prometido libertad ni liberación,
y luego por fines egoístas y riquezas terrenales,
no hemos traicionado (como han hecho otros) lo que hemos prometido hacer.
Parece que en muchos detalles estamos limpios de los sufrimientos de él,
porque nosotros al igual que él, hemos sido un pueblo sufriente,
por causa del mismo espíritu que lo ha hecho sufrir, el cual, ha sido mucho más cruel,
perverso e injusto contra nosotros, que lo que ha sido contra él,
aunque nuestra persecución ha sido de otra forma.
Sin embargo, lo que ellos han hecho contra nosotros lo perdonamos libremente,
y quisiéramos que ustedes sigan el mismo ejemplo.
Y si pudieran acusarlos de muchas cosas, igual nosotros,
pero este no es el momento para acusarse unos a otros, sino para perdonarse mutuamente,
y así vencer a sus enemigos.
Cuando ellos obtuvieron la victoria, no se reformaron,
sino que se convirtieron en opresores,
y fueron crueles con todos los que no decían ni hacían como ellos.
Y por esta causa el Señor los ha derribado y justamente permitido,
que otros los traten como ellos trataron a otros.

Sin embargo, aún debo decir, y es mi juicio,
que había una gran opresión e irritación bajo el gobierno
del último rey y de los obispos que estaban bajo su poder,
con las que fue ofendido el Señor,
y muchas buenas personas fueron oprimidas así. Y por esta causa,
el Señor pudo y justamente levantó a algunos,
para que se opusieran y lucharan contra las opresiones e injusticias,
y presionaran en busca de la reforma de todas las cosas.
Y no puedo negar, sino reconocer,
a esa Semilla de sinceridad que los llevó a oponerse a las crueldades
y a presionar en busca de la reforma en algunas cosas;
aunque muchos pronto la perdieron y buscaron complacerse,
olvidando la causa que decían defender.

--

Esta no es más que una pequeña parte de las preguntas, y de la respuesta a las mismas;
lo cual, E. Burrough concluyó con una audaz exhortación al rey a temer y honrar al Señor.

Ahora regresemos de nuevo a G. Fox el mayor, a quien dejamos cerca de Bristol;
de ahí se fue a Gloucester, Worcester, Drayton (el lugar de su nacimiento) y Yorkshire.
En ese condado, se celebraba en ese momento, la reunión anual en Balby, en un huerto,
donde se habían reunido miles de personas.
En York, a unas treinta millas de distancia, se dio aviso de esta reunión,
y una tropa de jinetes llegó desde ahí. G. Fox estaba
predicando en la reunión sobre un taburete,
cuando dos trompetistas llegaron cabalgando,
haciendo sonar sus instrumentos muy cerca de él.
Entonces el capitán le pidió a George que bajara,
porque había llegado, dijo él, para dispersar la reunión. Pero G. Fox le dijo al capitán,
que él sabía que estas eran personas pacíficas,
y que si él se preguntaba si estaban reunidos de manera hostil,
podía hacer una búsqueda entre ellos,
y que si encontraba una espada o una pistola en alguno de los presentes,
el tal podía sufrir el castigo.
Pero el capitán le dijo a G. Fox que él debía verlos dispersos,
porque había cabalgado toda la noche con el propósito de dispersarlos.
G+++.+++ Fox le preguntó:
"`¿Qué honor es para ti cabalgar con espadas y pistolas
entre tantos hombres y mujeres desarmados?
Pero si te quedas quieto y en silencio,
la reunión no se prolongará más de dos o tres horas; y cuando se termine,
así como se reunieron pacíficamente, así se separarán. Porque como puedes observar,
la reunión es tan numerosa que los condados de los alrededores no pueden alojarlos,
así que ellos tienen la intención de salir hacia sus casas esta noche.`"

Pero el capitán no podía quedarse tanto tiempo.
Entonces G. Fox le pidió, que si él no podía quedarse para ver el final de la reunión,
que dejara una docena de sus soldados.
A esto el capitán dijo que les permitiría una hora más;
y dejó seis soldados allí y luego se fue con su tropa.
Cuando se había ido, los soldados que se quedaron les dijeron a los que estaban reunidos,
que se podían quedar hasta la noche, si lo deseaban.
Estos no quisieron hacerlo, sino que se separaron unas tres horas después,
sin causar ningún disturbio.
Pero si los soldados hubieran tenido el mismo carácter de su capitán,
tal vez la reunión no hubiera terminado tan tranquilamente.
Porque este capitán era un hombre temerario,
que le había dicho a G. Fox en una ocasión en Escocia,
que él obedecería las órdenes de sus superiores, incluso si fueran crucificar a Cristo;
y que incluso, él ejecutaría las órdenes del gran Turco contra los cristianos,
si estuviera bajo su comando.

De ahí, G. Fox se fue para Skipton,
donde se celebraba la reunión general sobre los asuntos de la iglesia.
Porque muchos de sus amigos estaban sufriendo mucho en ese tiempo,
pues les habían quitado sus bienes, y algunos habían sido llevados a la pobreza,
por lo que era necesario proveer para ellos.
Esta reunión se había celebrado por varios años;
porque cuando los jueces y capitanes habían llegado a interrumpirla,
y habían visto los libros y las cuentas de las colectas para el socorro de los pobres,
y cómo se cuidaba que un condado ayudara a otro y proveyera para los pobres,
habían elogiado la práctica y se habían alejado con amor.
En algunas ocasiones llegaban hasta doscientas personas
pobres que pertenecían a otras sociedades,
y se esperaban ahí hasta que la reunión hubiera terminado,
y luego los Amigos les enviaban a pedir a los panaderos pan,
y le daban a cada una de ellas una hogaza de pan, sin importar cuántos fueran;
porque ellos habían sido enseñados a hacer el bien a todos,
aunque mayormente a los de la familia de la fe.

G+++.+++ Fox se fue de ahí a Lancaster, y luego a Swarthmore,
donde fue arrestado en la casa de Margaret Fell (que para entonces era viuda,
pues el juez Fell, su esposo, había fallecido unos dos años antes).
Ahora bien, algunos imaginaban que habían logrado una gran hazaña;
porque uno dijo que él no creía que mil hombres hubieran podido arrestar a G. Fox.
Ellos lo condujeron a Ulverstone,
donde lo retuvieron toda la noche en la casa del alguacil,
y se colocó una guardia de quince o dieciséis hombres para que lo vigilaran,
algunos de los cuales se sentaron en la chimenea,
por temor a que Fox se escapara por ella.
A la mañana siguiente fue llevado a Lancaster,
pero fue muy maltratado a lo largo del camino, y tras llegar al pueblo,
fue llevado a la casa de un juez cuyo nombre era Henry Porter,
y quien había entregado la orden judicial contra él. G. Fox le preguntó a Porter,
por qué y por orden de quién había enviado su orden judicial,
y se quejó ante Porter del maltrato que había recibido
de los alguaciles y de los otros oficiales;
porque ellos lo habían puesto sobre un caballo detrás de la silla,
para que no tuviera nada de qué sujetarse,
y habían golpeado maliciosamente al caballo para hacerlo patear,
galopar y arrojar al jinete.
Pero Porter no quiso tomar nota de eso y le dijo a G. Fox que tenía una orden;
pero no le permitió verla, porque no revelaría los secretos del rey.
Después de que se intercambiaron muchas palabras, fue llevado a la prisión de Lancaster.

Estando ahí preso en la cárcel común, quiso que dos de sus amigos,
uno de los cuales era Thomas Green, el otro Thomas Cummings,
un ministro del evangelio (con quien yo estaba muy familiarizado),
fueran donde el carcelero y le pidieran una copia de su orden judicial.
Ellos fueron, pero el carcelero les dijo que no podía darles una copia; sin embargo,
se las mostró para que la leyeran, y según recordaban,
los asuntos imputados contra G. Fox declaraban que él era una persona
de la que generalmente se sospechaba que perturbaba la paz de la nación,
que era enemigo del rey y principal defensor de la secta de los Cuáqueros; y que él,
junto con otros de su opinión fanática,
se había esforzado últimamente por levantar insurrecciones en esas partes del país,
y envolver a todo el reino en sangre.
Por esta razón se le había ordenado al carcelero que lo mantuviera bajo custodia,
hasta que fuera liberado por orden del rey y del Parlamento.
No es de extrañar que el carcelero no quisiera dar una copia de su orden judicial,
pues contenía casi tantas falsedades como palabras.
G+++.+++ Fox entonces escribió una defensa,
en la que respondía ampliamente a todas esas falsas acusaciones.
Y Margaret Fell, al considerar el daño que le habían hecho a ella,
al sacar a G. Fox de su casa,
escribió la siguiente información y la envió fuera del condado.

[.embedded-content-document.letter]
--

[.offset]
A todos los magistrados,
con respecto a la injusta captura y encarcelamiento de George Fox en Lancaster:

Les informo a los gobernadores de esta nación, que Henry Porter, alcalde de Lancaster,
envió una orden judicial con cuatro alguaciles a mi casa,
para lo cual no tenía ni autoridad ni orden.
Ellos registraron mi casa y capturaron a George Fox en ella,
quien no era culpable de la violación de ninguna ley,
o de alguna ofensa contra nadie en esta nación. Después de que
lo habían apresado y llevado delante del mencionado Henry Porter,
se le ofreció una fianza por lo que pidiera por su comparecencia,
para responder a lo que se le pudiera imputar, pero él (contrario a la ley,
si lo había apresado legalmente) no aceptó ninguna fianza y lo encarceló apresuradamente.
Después de estar en prisión,
se exigió una copia de su orden judicial (lo que no debe negarse a ningún prisionero),
para que él pudiera ver lo que se le imputaba, pero esta le fue negada.
Él no pudo obtener una copia, sólo se les permitió a sus amigos leerla.
Todo lo que allí se le imputaba era completamente falso;
él no era culpable de ninguno de los cargos en la orden,
como será demostrado y puesto de manifiesto a la nación. Por tanto,
que los gobernadores lo consideren.
Este asunto me concierne, por cuanto él fue aprehendido en mi casa; y si él es culpable,
yo también lo soy.
Así que deseo que esto se investigue.

[.signed-section-signature]
Margaret Fell.

--

Después de esto,
Margaret decidió ir a Londres para hablar con el rey acerca de este asunto;
y cuando Porter se enteró, dijo que él también iría, y así lo hizo.
Pero debido a que él había sido un hombre celoso
a favor del Parlamento y en contra del rey,
varios de los asistentes a la corte real, le hicieron recordar los saqueos de sus casas.
Y esto le preocupó tanto, que dejó la corte rápidamente y regresó a su casa,
y luego habló con el carcelero para idear una forma de liberar a G. Fox.
Pero Porter se había excedido en su orden judicial,
al ordenar que G. Fox fuera mantenido prisionero hasta que
fuera liberado por una orden del rey o del Parlamento.
G+++.+++ Fox también le envió una carta y le recordó cuán
feroz había sido él contra el rey y su partido,
aunque ahora deseaba ser considerado celoso a favor del rey.
Y entre otros pasajes, le recordó cómo,
cuando había defendido el castillo de Lancaster por el Parlamento contra el rey,
había sido tan rudo y feroz contra los que estaban a favor del rey,
que les había dicho que no les dejaría ni perro ni gato,
si no traían provisiones a su castillo.

Una tal Anne Curtis llegó a ver a G. Fox, y tras comprender cómo había sido recluido,
también resolvió ir a ver al rey y hablar al respecto; porque su padre,
que había sido alguacil de Bristol,
había sido ahorcado cerca de su propia puerta por intentar traer al rey.
Por esta razón tenía la esperanza de ser admitida en la
presencia del rey para hablar con él. Al llegar a Londres,
ella y Margaret Fell fueron juntas a ver al rey, quien,
cuando entendió de quien era hija Anne, la recibió amablemente.
Después de informar al rey del caso de G. Fox,
ella quería que él tuviera a bien enviar por él y oír su caso por él mismo.
El rey le prometió que lo haría,
y les ordenó a sus secretarios que enviara una orden para traer a G. Fox.
Pero pasó mucho tiempo antes de que esa orden fuera ejecutada,
porque se buscaron muchas excusas,
al ponerle objeciones a la redacción de la orden del rey,
y por medio de otros artilugios,
por lo que el hacer llegar a G. Fox a Londres fue retardado cerca de dos meses.
De modo que, al continuar prisionero escribió varios documentos,
y entre el resto estaba este:

[.embedded-content-document.letter]
--

[.letter-heading]
Para el Rey

[.salutation]
Rey Carlos,

Tú no entraste a esta nación por la espada, ni por una victoria de guerra,
sino por el poder del Señor; y ahora, si tú no vives en ese poder,
no prosperarás. Y si el Señor te ha mostrado misericordia y te ha perdonado,
y tú no muestras misericordia y perdón, el Señor Dios no oirá tus oraciones,
ni las de los que oren por ti.
Y si tú no detienes la persecución y a los perseguidores,
y no eliminas todas las leyes que sostienen la persecución sobre religión,
y persistes en ellas y mantienes la persecución,
esto te hará tan ciego como los que te han precedido.
Porque la persecución siempre ha cegado a los que han corrido a ella,
y a estos derriba Dios, mediante Su poder, y trae salvación a Sus oprimidos.
Y si llevas la espada en vano, y dejas la embriaguez, los juramentos, los juegos,
las festividades de mayo, con violinistas,
tambores y trompetas para ser tocados en ellos,
donde tales abominaciones y vanidades son alentadas o quedan impunes--tal
como la colocación de postes de mayo,
con la imagen de la corona en la cúspide de ellos,
etc.--entonces la nación se volverá rápidamente como Sodoma y Gomorra,
y será tan mala como el antiguo mundo,
que afligió al Señor hasta que Él lo derrocó. Así te derrocará
Él si estas cosas no son evitadas de golpe.
Nunca ha habido tanta maldad en libertad antes de ahora, como la que hay en este día;
como si no hubiera terror, ni espada de la magistratura, lo cual no adorna a un gobierno,
ni es para alabanza de los que hacen bien.
Nuestras oraciones son para los que están en autoridad,
para que bajo ellos podamos vivir una vida piadosa, en la que tengamos paz;
y para que no seamos llevados a la impiedad por ellos.
Por tanto, escucha y considera, y haz el bien en tu tiempo, mientras tienes poder.
Sé misericordioso y perdona, este es el camino para vencer y obtener el reino de Cristo.

[.signed-section-signature]
G+++.+++ Fox

--

El alguacil de Lancaster seguía rehusándose a trasladar a G. Fox,
a menos que se comprometiera y pagara por el sellado de la escritura,
y por los gastos de su transporte a Londres.
Pero él no quiso hacerlo.
Entonces, al consultar cómo transportarlo,
primero se propuso mandar una partida de jinetes con él; pero H. Porter les dijo,
que si Fox era un hombre como ellos lo habían descrito,
necesitaba enviar una o dos tropas completas de jinetes para vigilarlo.
Pero al considerar que esto les supondría una gran carga,
decidieron mandarlo resguardado sólo por el carcelero y algunos agentes judiciales.
Después de considerarlo más a fondo, descubrieron que esto también sería costoso,
entonces le dijeron a G. Fox, que si pagaba una fianza para estar en Londres cierto día,
tenía permiso de subir con algunos de sus propios amigos.
G+++.+++ Fox les dijo, que él no pagaría ninguna fianza, ni daría ningún dinero,
pero que si ellos lo dejaban subir con uno o dos de sus amigos,
él subiría y estaría en Londres cierto día, si el Señor lo permitía. Así, finalmente,
cuando vieron que no podían persuadirlo,
el alguacil consintió en que subiera con algunos de sus amigos,
sin ningún otro compromiso que su palabra,
para comparecer ante los jueces de Londres cierto día,
si el Señor lo permitía. Entonces lo dejaron salir de prisión, y después de una estadía,
se fue con Richard Hubberthorn y Robert Withers para Londres,
donde llegó el día que algunos de los jueces del rey Carlos
I fueron colgados y descuartizados en Charing Cross.
Porque en ese momento se estaba cumpliendo en ellos,
lo que Edward Burrough y otros habían predicho claramente.

A la mañana siguiente,
G+++.+++ Fox y los que estaban con él fueron a la cámara del juez Thomas Mallet,
quien se estaba poniendo su toga roja para dictar sentencia contra más jueces del rey,
por lo que Fox le dijo que podía regresar en otro momento.
Y así lo hizo, acompañado por el esquire^
footnote:[En Inglaterra, este título se otorga a los hijos menores de los nobles,
a los funcionarios de los tribunales del rey y de la casa, a los consejeros de la ley,
a los jueces de paz, mientras están en comisión, a los alguaciles y a otros caballeros.]
Marsh.
Cuando regresó a la cámara del juez,
encontró ahí también al señor presidente del Tribunal de Justicia Foster,
y les entregó la acusación que había contra él. Pero cuando ellos leyeron las
palabras "`él y sus amigos estaban envolviendo en sangre a la nación,`" etc.,
golpearon la mesa con sus manos.
G+++.+++ Fox les dijo que él era el hombre contra el que se formulaba la acusación,
pero que él era tan inocente de cualquier cosa como un niño recién nacido,
que él mismo les había traído la acusación,
y que algunos de sus amigos habían venido con él, sin ninguna guardia.
Antes de esto, a los jueces no les había importado el sombrero de G. Fox, pero entonces,
al ver que lo tenía puesto, le preguntaron por qué estaba de pie con su sombrero puesto.
Él les dijo que no lo hacía por desprecio a ellos.
Entonces le ordenaron a uno que se lo quitara,
y habiendo llamado al alguacil del tribunal de rey, le dijeron:
"`Debes tomar a este hombre y asegurarlo, pero debes dejar que tenga una habitación,
y no lo pongas entre los prisioneros.`"
Pero el alguacil dijo que su casa estaba tan llena,
que no podía decir dónde darle una habitación, excepto entre los prisioneros.
Entonces, el juez Foster le dijo a G. Fox:
"`¿Comparecerás mañana a las diez en punto al tribunal del rey, en Westminster?`"
"`Sí,`" dijo él, "`si el Señor me da fuerzas.`"
En ese momento dicho juez le dijo al otro: "`Si él dice '`sí`' y lo promete,
puedes tomar su palabra.`"

Así fue despedido en ese momento,
y al día siguiente se presentó ante el tribunal del rey a la hora señalada,
acompañado por Richard Hubberthorn, Robert Whiters,
y por el funcionario Marsh ya mencionado.
Y siendo llevado al centro de la corte, miró alrededor y dirigiéndose al pueblo dijo:
"`La paz sea con ustedes.`"
Entonces la acusación contra él fue leída,
y al llegar a la parte que decía que él y sus amigos
estaban envolviendo a la nación en sangre,
que estaban levantado una nueva guerra, que él era un enemigo del rey, etc.,
los que estaban en el tribunal levantaron sus manos.
Entonces, extendiendo sus brazos, G. Fox dijo:
"`Yo soy el hombre contra el que se hace esta acusación,
pero soy tan inocente como un niño con respecto a esos cargos,
y nunca he adoptado posturas a favor de la guerra.
¿Piensan ustedes que si yo y mis amigos fuéramos hombres como los que declara la acusación,
yo la habría traído a Londres contra mí mismo?
O, ¿que a mí se me habría permitido venir con sólo uno o dos de mis amigos?
Porque si fuera un hombre como esta acusación establece,
yo tendría que haber sido custodiado por una o dos tropas de jinetes.
Pero el alguacil y los magistrados de Lancashire,
consideraron adecuado dejarme a mí y a mis amigos venir por nosotros mismos,
casi doscientas millas, sin ninguna guardia,
y podemos estar seguros de que ellos no lo habrían hecho,
si me hubieran considerado un hombre así.`"

Entonces el juez le preguntó, si la acusación debía ser archivada, o qué haría con ella.
Y él respondió: "`Ustedes son los jueces, y son capaces, espero, de juzgar este asunto;
por tanto, hagan con ella según deseen.`"
Los jueces dijeron que ellos no lo acusarían porque
no tenían nada contra él. A raíz de lo cual,
el funcionario Marsh se levantó y les dijo a los jueces:
"`Es la voluntad del rey que G. Fox sea puesto en libertad,
ya que no ha venido ningún acusador contra él.`" Entonces ellos le preguntaron,
si él llevaría el asunto delante del rey y del consejo.
Y él respondió: "`Sí, de buena gana.`"
Acto seguido, lo enviaron al rey, quien al leer esto y considerar todo el asunto,
satisfecho de la inocencia de G. Fox,
le ordenó a su secretario que enviara la siguiente orden al juez Mallet para su liberación:

[.embedded-content-document.legal]
--

Es la voluntad de su majestad,
que des la orden de soltar y poner en plena libertad a George Fox,
preso desde hace tiempo en la cárcel de Lancaster, y mandado aquí por un __hábeas corpus.__
Esta señal de voluntad de su majestad, será suficiente garantía para ti.
Fechado en Whitehall, el 24 de Octubre de 1660.

[.signed-section-signature]
Edward Nicholas

[.signed-section-context-close]
Para sir Thomas Mallet, caballero, uno de los jueces del tribunal del rey.

--

Cuando esta orden fue entregada al juez Mallet,
él inmediatamente envió su orden judicial al alguacil del tribunal del rey,
para que liberara a G. Fox; dicha orden fue la siguiente:

[.embedded-content-document.legal]
--

En virtud de la orden judicial que recibí esta mañana del honorable sir Edward Nicholas,
caballero, uno de los principales secretarios de su majestad,
de soltar y liberar a George Fox, preso desde hace tiempo en la cárcel de Lancaster,
y desde ahí traído aquí por un __hábeas corpus,__ y puesto ayer bajo tu custodia;
yo por la presente, te pido que tú, como corresponde,
sueltes y pongas en liberta al mencionado prisionero, George Fox: para lo cual,
esta será tu orden y descargo.
Firmado por mí el 25 de Octubre, del año de nuestro Señor Dios, 1660.

[.signed-section-signature]
Thomas Mallet.

[.signed-section-context-close]
A sir John Lenthal, caballero, alguacil del tribunal del rey, o para su representante.

--

G+++.+++ Fox, tras haber estado prisionero por más de veinte semanas,
fue puesto en libertad honorablemente por una orden del rey.
Después de que fue sabido que había sido liberado,
varios envidiosos y perversos se perturbaron, y el terror se apoderó del juez Porter,
porque temía que G. Fox se aprovechara de la ley contra él por su injusto encarcelamiento,
y provocara así su ruina.
Y en efecto,
G+++.+++ Fox fue alentado por algunas autoridades a que pusiera a Porter y al resto como ejemplos.
Pero George dijo que se los dejaría al Señor; si el Señor los perdonaba,
él no se molestaría con ellos.

Por este tiempo, Richard Hubberthorn tuvo oportunidad de hablar con el rey,
y de tener una larga conversación con él, la que poco después publicó en forma impresa.
Al ser admitido en la presencia del rey, le hizo un relato del estado de sus amigos,
y dijo: "`Desde que el Señor nos llamó y nos unió para ser un pueblo,
para caminar en Su temor y en Su verdad,
siempre hemos sufrido y hemos sido perseguidos por los poderes que han gobernado,
y hemos sido hechos presa por apartarnos de la iniquidad.
Y cuando no se nos podía acusar de la violación de alguna ley justa,
entonces promulgaban leyes a propósito para atraparnos;
y así se prolongaron injustamente nuestros sufrimientos.`"

[.discourse-part]
__Rey:__ Es verdad, los que han gobernado sobre ustedes han sido crueles,
y han profesado mucho que no han hecho.

[.discourse-part]
__R+++.+++ Hubberthorn:__ Y de igual manera, los mismos sufrimientos abundan ahora,
con mayor crueldad y en muchas partes de esta nación. Como por ejemplo, en Thetford,
Norfolk, donde Henry Fell, mientras estaba ministrando al pueblo,
fue sacado de la reunión y azotado, y enviado fuera del pueblo,
de parroquia en parroquia, hacia Lancashire.
El principal motivo de su acusación, según se indica en su pase +++[+++que fue mostrado el rey]
fue, que se había negado a tomar el juramento de lealtad y supremacía. Así, pues,
debido a que por un asunto de consciencia no podemos jurar,
sino que hemos aprendido a obedecer la doctrina de Cristo que dice:
"`No juréis en ninguna manera,`" se aprovecha la ocasión contra nosotros para perseguirnos.
Y es bien sabido que no hemos jurado por ninguno, ni contra ninguno,
sino que hemos mantenido la verdad; y nuestro sí ha sido sí, y nuestro no ha sido no,
en todas las cosas, lo cual es más que el juramento de los que están fuera de la verdad.

[.discourse-part]
__Rey:__ Pero, ¿por qué no pueden jurar ustedes?
Porque un juramento es algo común entre los hombres para cualquier compromiso.

[.discourse-part]
__R+++.+++ Hubberthorn:__ Sí, es manifiesto y lo hemos visto por experiencia;
y es tan común entre los hombres jurar y comprometerse a favor o en contra de cosas,
que no se les presta la debida atención, ni se teme romper el juramento.
Por tanto, lo que nosotros hablamos en la verdad de nuestros corazones,
es más de lo que ellos juran.

[.discourse-part]
__Rey:__ Pero, ¿no pueden prometer delante del Señor la esencia del juramento?

[.discourse-part]
__R+++.+++ Hubberthorn:__ Sí, lo que afirmamos, lo podemos prometer delante del Señor,
y ponerlo a Él como nuestro Testigo en ello; pero nuestra promesa no ha sido aceptada,
sino que se ha insistido en la ceremonia de juramento,
sin el cual todas las otras cosas han sido consideradas sin efecto.

[.discourse-part]
__Rey:__ Pero, ¿cómo podemos saber nosotros por las palabras de ustedes,
que cumplirán lo que dicen?

[.discourse-part]
__R+++.+++ Hubberthorn:__ Probándonos; porque no se sabe si los que juran son leales,
excepto probándolos.
Y así nosotros,
porque aquellos que nos han probado han encontrado que somos más fieles en nuestra promesas,
que otros en sus juramentos; y a los que todavía nos probarán, les pareceremos igual.

[.discourse-part]
__Rey:__ Te ruego que me digas, ¿cuál es el principio de ustedes?

[.discourse-part]
__R+++.+++ Hubberthorn:__ Nuestro principio es:
"`Jesucristo es la verdadera luz que alumbra a todos los hombres que vienen al mundo,
para que todos los hombres a través de Él,
puedan creer,`" y que todos tienen que obedecer y seguir esta luz,
en la medida que la hayan recibido, para que puedan ser conducidos a Dios,
a la justicia y al conocimiento de la verdad, y ser salvados.

[.discourse-part]
__Rey:__ Todos los Cristianos confiesan esto como verdad, y el que lo niega no es Cristiano.

[.discourse-part]
__R+++.+++ Hubberthorn:__ Pero muchos lo han negado, tanto en palabras como en escritos,
y se han opuesto a nosotros en esto;
y se han publicado más de cien libros en oposición a este principio.

[.small-break]
'''

Entonces, algunos de los señores que estaban junto al rey dijeron,
que nadie negaría que todos son alumbrados.
Y uno de los señores preguntó, que desde cuando éramos llamados Cuáqueros,
y si nosotros aprobábamos ese nombre.

[.discourse-part]
__R+++.+++ Hubberthorn:__ Este nombre nos fue dado en desprecio y escarnio, hace doce años;
pero algunos ya vivían en esta verdad antes de que se nos diera ese nombre.

[.discourse-part]
__Rey:__ ¿Cuánto tiempo ha pasado desde que tú aceptaste este juicio y camino?

[.discourse-part]
__R+++.+++ Hubberthorn:__ Han pasado cerca de doce años desde que acepté esta verdad,
según la manifestación de la misma.

[.discourse-part]
__Rey:__ ¿Reconoces el sacramento?

[.discourse-part]
__R+++.+++ Hubberthorn:__ En cuanto a la palabra '`sacramento,`' no la leo en la Escritura;
pero reconozco el cuerpo y la sangre de Cristo, y que sin sangre no hay remisión.

[.discourse-part]
__Rey:__ Bien, eso es; pero, ¿no crees que se les ordena a todos recibirlo?

[.discourse-part]
__R+++.+++ Hubberthorn:__ Creemos, según está escrito en la Escritura,
que Cristo en Su última cena tomo pan y lo partió, y lo dio a Sus discípulos,
y también tomó la copa y la bendijo, y les dijo:
"`Todas las veces que hagan esto (es decir, todas las veces que partieran el pan),
anuncian la muerte del Señor hasta que Él venga;`" y nosotros creemos que lo hicieron;
"`y partiendo el pan en las casas,
comían juntos con alegría y sencillez de corazón.`"
Y Cristo vino de nuevo a ellos según Su promesa,
después de lo cual dijeron: "`Porque siendo muchos,
somos un solo pan...porque todos participamos de aquel mismo pan.`"^
footnote:[1 Corintios 10:17; RV1602P]

[.discourse-part]
__Amigo del rey:__ Entonces uno de los amigos del rey dijo: "`Es verdad,
porque así como muchos granos hacen un solo pan, así ellos, siendo muchos miembros,
eran un solo cuerpo.`"
Y otro de ellos dijo: "`Si ellos son el pan, entonces deben ser partidos.`"

[.discourse-part]
__R+++.+++ Hubberthorn:__ Hay una diferencia entre ese pan que Él partió en Su última cena,
con la que debían anunciar, como señal, Su muerte hasta que Él viniera,
y este del que se dice, que ellos siendo muchos, eran un solo pan; porque aquí,
ellos habían llegado más a la sustancia y a hablar más espiritualmente,
según la habían llegado a conocer en el Espíritu.

[.offset]
Entonces los amigos del rey dijeron: "`Es cierto, él no ha dicho más que la verdad.`"

[.discourse-part]
__Rey:__ ¿Cómo sabes que eres inspirado por el Señor?

[.discourse-part]
__R+++.+++ Hubberthorn:__ Según leemos en las Escrituras,
'`la inspiración del Omnipotente da entendimiento,`' por Su inspiración
nos es dado un entendimiento de las cosas de Dios.

[.offset]
Entonces, uno de los señores dijo:
"`¿Cómo sabes que ustedes son conducidos por el verdadero Espíritu?`"

[.discourse-part]
__R+++.+++ Hubberthorn:__ Lo sabemos, porque el Espíritu de Verdad reprende al mundo de pecado,
y nosotros fuimos reprendidos de pecado por Él. También,
porque somos apartados del pecado y llevados a la justicia y obediencia de la verdad,
por cuyos efectos sabemos que es el verdadero Espíritu;
porque el espíritu de maldad no lleva a tales cosas.

[.offset]
Entonces el rey y sus señores dijeron que eso era verdad.

[.discourse-part]
__Rey:__ Bien, ustedes pueden estar seguros de esto,
que ninguno sufrirá por sus opiniones o religión, mientras vivan pacíficamente;
tienen la palabra del rey en esto.
Y también he hecho una declaración con el mismo propósito,
que nadie los agravie o abuse de ustedes.

[.discourse-part]
__Rey:__ ¿Cómo reconocen ustedes a los magistrados, o a la magistratura?

[.discourse-part]
__R+++.+++ Hubberthorn:__ Así reconocemos a los magistrados: Cualquiera que sea puesto por Dios,
ya sea el rey como supremo, o cualquiera otro que haya sido puesto en autoridad por Él,
que son para el castigo de los malhechores y alabanza de los que hacen el bien,
a esos nos someteremos, y ayudaremos en las cosas justas y sociales,
tanto con el cuerpo como con el patrimonio.
Y si cualquier magistrado hace lo que es injusto, declararemos contra eso,
pero nos someteremos a él en paciente sufrimiento,
y no nos rebelaremos contra ninguno mediante insurrecciones, complots y maquinaciones.

[.discourse-part]
__Rey:__ Es suficiente.

[.offset]
Luego uno de los señores preguntó: "`¿Por qué se reúnen,
siendo que cada uno de ustedes tiene la iglesia en su interior?`"

[.discourse-part]
__R+++.+++ Hubberthorn:__ Según lo escrito en las Escrituras, la iglesia está en Dios;
1 Tesalonicenses 1:1. Y los que temían al Señor,
se reunían a menudo en el temor del Señor; y para nosotros es provechoso,
somos edificados y fortalecidos en la vida de la Verdad.

[.discourse-part]
__Rey:__ ¿Cómo llegaron a creer por primera vez que las Escrituras eran la verdad?

[.discourse-part]
__R+++.+++ Hubberthorn:__
Yo he creído desde niño que las Escrituras son la declaración de la verdad,
cuando sólo tenía un conocimiento literal,
una educación natural y tradición. Pero ahora sé que las Escrituras son verdaderas,
por la manifestación y operación del Espíritu de Dios que las cumple en mí.

[.discourse-part]
__Rey:__ ¿De qué manera se reúnen y cuál es el orden en sus reuniones?

[.discourse-part]
__R+++.+++ Hubberthorn:__
Nosotros nos reunimos en el mismo orden en el que el pueblo Dios lo hacía,
esperando en Él. Si alguno tiene una palabra de exhortación de parte del Señor,
puede decirla,
o si alguno tiene una palabra de represión o amonestación.
Conforme al don que cada uno haya recibo,
así se ministran unos a otros, se edifican unos a otros; por medio de lo cual,
se ministran unos a otros un crecimiento en el conocimiento de la verdad.

[.discourse-part]
__Uno de los señores:__ Entonces todavía no saben tanto como pueden saber, pero,
¿hay un crecimiento para ser experimentado?

[.discourse-part]
__R+++.+++ Hubberthorn:__ Sí, crecemos diariamente en el conocimiento de la Verdad,
en nuestro ejercicio y obediencia a ella.

[.discourse-part]
__Rey:__ ¿Ha ido alguno de tus amigos a Roma?

[.discourse-part]
__R+++.+++ Hubberthorn:__ Sí, hay uno en prisión en Roma.

[.discourse-part]
__Rey:__ ¿Por qué lo enviaron ahí?

[.discourse-part]
__R+++.+++ Hubberthorn:__ Nosotros no lo enviamos,
pero encontró algo en su espíritu de parte del Señor,
por lo que fue llamado a ir y declarar contra la superstición e idolatría,
lo cual es contrario a la voluntad de Dios.

[.discourse-part]
__Amigo del rey:__ Había dos de ellos en Roma, pero uno murió.

[.discourse-part]
__Rey:__ ¿Ha estado alguno de tus amigos con el gran Turco?

[.discourse-part]
__R+++.+++ Hubberthorn:__ Algunos de nuestros amigos han estado en ese país.

[.small-break]
'''

Se hablaron otras cosas con respecto a la libertad de los siervos del Señor,
que fueron llamados por Él a Su servicio,
para que no hubiera limitaciones de parroquias o lugares,
sino según los guiara el Señor en Su obra y servicio por medio de Su Espíritu.

Después de que el rey le prometió a Richard Hubberthron una y otra vez,
que sus amigos no sufrirían por sus opiniones o religión, se separaron en amor.
Pero aunque el rey parecía un príncipe de buen carácter,
con el paso del tiempo otras personas lo engañaron,
y parece que olvidó lo que solemnemente había prometido dando su palabra de rey.

Ahora, debido a que en esta conversación se hizo mención de Roma,
diré de paso que un tal John Perrot y John Love, después de llegar a Leghorn, en Italia,
fueron interrogados por la Inquisición,^
footnote:[La Inquisición, también conocida como Santa Inquisición,
fue una institución dedicada a la investigación, condena y castigo de la herejía,
que estaba vinculada con la Iglesia católica.]
y respondieron tan bien que fueron despedidos.
Después que llegaron a Venecia, a Perrot se le permitió ver al duque en su palacio,
donde habló con él y le dio algunos libros;
y de ahí se fue con su compañero de viaje a Roma.
Allí dieron testimonio de manera tan pública contra la idolatría que ahí se comete,
que fueron tomados bajo custodia.
John Love murió en la prisión de la Inquisición,
y aunque se dijo que había ayunado hasta morir,
algunas monjas han dicho que fue ejecutado de noche,
por temor a que molestara a la iglesia de Roma.
Sea como fuere, murió en sinceridad de corazón, y por tanto,
fue más feliz que John Perrot,
quien aunque en ese momento quizás estaba en un buen estado de ánimo,
después se volvió un gran apóstata,
tras haber permanecido mucho tiempo prisionero en Roma y finalmente obtenido su libertad.
Él era un hombre de grandes habilidades naturales, pero,
al no continuar en verdadera humildad se desbordó en exorbitantes imaginaciones,
de lo cual se hablará más adelante.

Por este tiempo Samuel Fisher y John Stubbs también estaban en Roma,
donde hablaron con algunos de los cardenales,
y testificaron contra las supersticiones católicas.
También repartieron algunos libros entre los frailes,
algunos de los cuales confesaron que el contenido de los libros era verdadero;
"`pero,`" dijeron, "`si nosotros reconociéramos esto públicamente,
podemos esperar ser quemados por ello.`"
Sin embargo, Fisher y Stubbs se fueron libres y regresaron a casa sin ser molestados.

El caso de Mary Fisher, una doncella,
y una de las primeras llamadas Cuáqueras en llegar a Nueva Inglaterra,
no puede dejarse pasar en silencio.
Habiendo llegado a Esmirna, para de ahí irse a Adrianópolis,
fue detenida por el cónsul inglés y mandada de regreso a Venecia,
desde donde se fue a Adrianópolis por otro camino,
y llegó en el momento en que el sultán Mahomet IV
acampaba con su ejército cerca de dicha ciudad.
Ella fue sola al campamento y consiguió que alguien fuera a la tienda del gran visir,^
footnote:[Un consejero o ministro político de alto rango.]
y le dijera que una mujer inglesa había llegado y tenía
algo que declararle al sultán de parte del gran Dios.
El visir le mandó a decir que la mañana siguiente
le procuraría una oportunidad para ese propósito.
Entonces ella regresó a la ciudad, y a la mañana siguiente volvió al campamento,
donde fue llevada delante del sultán,
quien estaba rodeado de sus hombres importantes de
la manera que solía recibir a un embajador.
Él le preguntó por medio de sus intérpretes (de los cuales había tres con él),
si era cierto lo que se le había dicho,
que ella tenía algo que decirle de parte del Señor Dios.
Ella respondió: "`Sí.`" Entonces él le pidió que continuara hablando,
y como ella no se apresuró a hablar, sino que estaba meditando mucho lo que iba a decir,
él supuso que ella tenía temor de expresar su opinión delante de todos,
y por eso le preguntó si deseaba que algunos de ellos
se hicieran a un lado antes de que hablara.
Ella respondió: "`No.`" Él entonces le pidió que dijera la palabra del Señor para ellos,
y que no temiera, porque ellos tenían buenos corazones, y podían oírla.
También le encargó que dijera la palabra que tenía que decir de parte del Señor,
y que no dijera ni más ni menos, porque ellos estaban dispuestos a oírla,
fuera la que fuera.
Entonces ella dijo lo que tenía en mente.

Los turcos la escucharon con mucha atención y seriedad hasta que terminó;
y luego el sultán le preguntó si tenía algo más que decir.
Ella le preguntó si él había entendido lo que le había dicho; y él respondió: "`Sí,
cada palabra;`" y añadió, que lo que ella había dicho era verdad.
Entonces, él quería que ella se quedara en el país,
diciendo que ellos no podían dejar de respectar a
alguien que se había tomado tantas molestias,
para llegar hasta ellos desde Inglaterra con un mensaje del Señor Dios.
También le ofreció una guardia para que la llevaran a Constantinopla,
donde tenía la intención de ir.
Pero como ella no aceptó el ofrecimiento, le dijo que era un viaje muy peligroso,
especialmente para alguien como ella;
y estaba maravillado de que ella hubiera llegado tan lejos a salvo; diciendo también,
que le había hecho el ofrecimiento por respeto y amabilidad, y que por nada del mundo,
quería verla sufrir el menor daño en sus dominios.

Al no tener ella algo más que decir,
los turcos le preguntaron qué pensaba ella de Mahoma, el profeta de ellos.
Ella respondió cautelosamente que no lo conocía, pero que a Cristo, el verdadero profeta,
el Hijo de Dios, quien era la luz del mundo y alumbraba a todo hombre que viene al mundo,
sí lo conocía. Y con respecto a Mahoma dijo,
que ellos podían juzgar si él era verdadero o falso,
según las palabras y profecías que había dicho; agregando:
"`Si la palabra que un profeta dice se cumple,
entonces sabrán que el Señor ha enviado a ese profeta; pero si no se cumple,
entonces sabrán que el Señor nunca lo mandó.`" Los turcos confesaron que eso era cierto,
y Mary, tras haber presentado su mensaje, partió del campamento hacia Constantinopla,
sin una guardia, donde llegó sin el menor daño o burla.
Y así, regresó a salvo a Inglaterra.

Con respecto a Catherine Evans y Sarah Cheevers, dos mujeres,
que en este momento estaban en la prisión de la Inquisición en Malta,
y no fueron liberadas hasta después de tres años de confinamiento,
en los que sufrieron las más penosas privaciones,
tengo la intención de hablar más adelante, cuando llegue el momento de su liberación;
y entonces me propongo hacer una descripción amplia y muy notable al respecto.

Mientras tanto, regreso a los asuntos de Inglaterra,
donde el gobierno estaba entonces bastante alterado.
Muchos de los jueces del fallecido rey habían sido colgados y descuartizados;
entre esos estaba el coronel Francis Hacker, de quien se ha dicho,
que unos seis años antes de esta época, había tomado prisionero a George Fox.
Pero ahora, él mismo estaba en prisión,
acusado no sólo de ser uno de los que había mantenido al rey prisionero,
sino también de haber firmado la orden de ejecución del rey,
y de haberlo conducido al cadalso.
A todas estas acusaciones y demás, dijo poco,
excepto que había hecho lo que le habían ordenado sus superiores,
y que él se había esforzado por servir a su país. Pero esto no le sirvió de nada,
porque en Octubre fue condenado por alta traición, y colgado y descuartizado.
Uno o dos días antes de su muerte, Margaret Fell lo visitó en prisión,
y cuando le recordó lo que había hecho anteriormente
contra "`los inocentes,`" se acordó de ello,
y dijo que él sabía bien a quién se refería, y que por ello tenía angustia.
Porque G. Fox (quien lo había comparado con Pilatos) le había pedido,
cuando llegara el día de su miseria y prueba, que recordara lo que él le había dicho.
Y aunque el yerno de Hacker, Needlam,
no había dudado en decir entonces que era "`tiempo de cortar a
G+++.+++ Fox,`" ahora había llegado a ser la suerte del propio Hacker,
al ser cortado en Tyburn donde fue colgado.

Ese fue el fin de muchos,
quienes no sólo eran culpables de la muerte del rey y de
ejecutar a otros que habían apoyado al rey Carlos II,
sino también de haber transgredido contra Dios al perseguir a personas piadosas.
Estos habían sido advertidos con frecuencia, y se les había dicho varias veces,
que Dios escucharía el clamor de las viudas y de los huérfanos
que habían sido cruelmente oprimidos por ellos.
Y que así como habían hecho botín de los bienes de
aquellos que en desprecio llamaban Cuáqueros,
así sería traído sobre ellos temor y temblor,
y sus propiedades se convertirían en botín para otros.
Ya se ha mostrado con qué claridad había predicho esto Edward Burrough;
y para no mencionar a otros,
sólo diré que un tal Robert Huntington entró una
vez a la '`casa del campanario`' en Brough,
cerca de Carlisle, envuelto en una sábana blanca y con una soga al cuello,
para mostrarles a los Presbiterianos e Independientes de allí, que el sobrepelliz^
footnote:[La vestimenta litúrgica blanca usada por la Iglesia Anglicana.]
iba a ser introducido de nuevo, y que algunos de ellos no escaparían de la soga.
Por muy descabellado que se dijera entonces que había sido este acto,
el tiempo probó que había sido una predicción del
inminente desastre de los crueles perseguidores,
porque cuando el rey Carlos ascendió al trono,
sus más fieros enemigos fueron despachados del camino.

En el Parlamento que sesionaba en ese momento,
se les permitió presentarse ante la Cámara de los Lores a algunos de los llamados Cuáqueros,
donde dieron las razones por las que ellos no podían asistir al culto público, jurar,
ni pagar diezmos; y fueron escuchados con sobriedad.
El rey también se mostraba moderado por esta época, ya que, por solicitud de algunos,
especialmente de Margaret Fell,
puso en libertad a unos setecientos del pueblo llamado Cuáqueros,
que habían sido encarcelados bajo el gobierno de Oliver y Richard Cromwell.
Este indulto pasó fácil, porque los que estaban entonces en el mando,
habían sufrido también bajo el gobierno anterior; y durante un breve período de tiempo,
parecía que había cierta inclinación a conceder libertad de consciencia.
Pero justo en este tiempo, sucedió algo que detuvo la concesión de tal libertad;
aunque esta había avanzado tanto,
que se había redactado una orden para permitirles a los Cuáqueros
el libre ejercicio de su adoración. Cuando sólo faltaban la firma
y el sello para la aprobación de esta orden,
los hombres de la Quinta Monarquía se levantaron en insurrección. En ese
tiempo había un gran número de este alborotador pueblo en Inglaterra,
quienes,
al percibir que sus extravagantes opiniones eran incompatibles
con el gobierno de la realeza que había tomado poder entonces,
decidieron que no podían permanecer sentados mientras el gobierno, que aún era nuevo,
se asentara y estableciera plenamente.
Tal vez,
también tenían la intención de liberar a algunos de los jueces del fallecido rey,
que todavía estaban encarcelados,
porque entre estos prisioneros se encontraba sir Henry Vane, quien,
habiendo sido uno de los jefes del partido de la mancomunidad,
también se decía que era uno de los líderes de los hombres de la Quinta Monarquía.

Esta gente hizo su levantamiento durante la noche, lo que causó tal agitación,
que los soldados del rey dieron la alarma tocando los tambores.
Las tropas entrenadas aparecieron armadas, y todo era un alborotado,
y tanto la chusma como los soldados hicieron grandes daños
durante varios días. Y aunque eran completamente inocentes,
los Cuáqueros se convirtieron en el objeto de la furia de sus enemigos,
y muchos fueron sacados a rastras de sus pacíficas reuniones y llevados a prisión.

Por ese tiempo George Fox estaba en Londres, alojado en Pall-Mall.
Por la noche,
una compañía de soldados llegó y tocó a la puerta del lugar donde se encontraba;
cuando abrieron la puerta, se precipitaron dentro de la casa y lo agarraron.
Uno de estos, que había servido anteriormente bajo el Parlamento,
llevó su mano al bolsillo de G. Fox y le preguntó si tenía una pistola.
G+++.+++ Fox le dijo: "`Tú sabes que yo no porto pistola;
¿por qué me haces la pregunta sabiendo que soy un hombre pacífico?`"
Otros subieron corriendo a los aposentos y encontraron al esquire Marsh,
antes mencionado, en la cama, quien aunque tenía acceso a los aposentos privados del rey,
por amor a G. Fox había llegado y se había alojado donde
él lo hacía. Cuando los soldados bajaron de nuevo,
dijeron: "`¿Por qué debemos llevarnos a este hombre con nosotros?
Dejémoslo en paz.`"
"`Oh no,`" dijo el soldado del Parlamento,
"`es uno de los jefes y uno de los principales cabecillas.`"
Ante esto, los soldados se lo llevaron.
Pero el esquire Marsh, al enterarse de eso,
mandó a llamar al hombre que comandaba el grupo y le pidió que dejara a G. Fox en paz,
ya que él lo vería en breve por la mañana, y entonces podrían llevárselo.

Temprano en la mañana llegó una compañía de hombres a pie a la casa,
y uno de ellos desenvainó su espada y la sostuvo sobre la cabeza de G. Fox,
lo cual le hizo preguntar: "`¿Por qué desenvainas tu espada contra un hombre desarmado?`"
Ante esto, uno de sus compañeros, avergonzado,
le ordenó al soldado que guardara su espada,
y poco después llevaron a George a Whitehall.
Al salir vio que algunos de sus amigos se dirigían a la reunión,
pues era el Primer-día. Él había tenido la intención de ir,
si no se lo hubieran impedido, pero como ya no estaba en su poder hacerles compañía,
elogió la audacia de ellos y los animó a perseverar en ella.
Cuando llegó a Whitehall, al ver que los soldados y las personas eran sumamente rudas,
empezó a exhortarlos a la piedad, pero algunas personas influyentes que pasaban por ahí,
y que le tenían envidia, dijeron: "`¿Qué? ¿Lo dejan predicar?
¡Pónganlo dentro de un lugar donde no tenga tanta libertad!`"
Así, pues, fue puesto en tal lugar, y los soldados lo vigilaban; pero G. Fox les dijo,
que aunque ellos podían confinar su cuerpo y encerrarlo,
no podían detener a la Palabra de vida.
Entonces,
algunos le preguntaron qué era él. Él les dijo que era un predicador de la justicia.
Después de mantenerlo dos o tres horas, el esquire Marsh habló con el señor Gerard,
quien llegó y les mandó que pusieran en libertad a G. Fox.
Cuando fue soltado, el alguacil le exigió los honorarios.
Pero G. Fox le dijo que no podía darle nada, y le preguntó:
"`¿Cómo puedes exigir honorarios de un hombre que es inocente?`"
Sin embargo, le dijo que, en su propia libertad, le daría dos peniques,
con los que él y los soldados podrían comprar algo para tomar.
Pero ellos exclamaron contra tal idea, lo que hizo que él dijera: "`Si no aceptan,
es elección de ustedes, pero yo no puedo darles honorarios.`"
Entonces pasó a través de los guardias y llegó a una posada,
donde varios de sus amigos en ese momento estaban prisioneros bajo un guardia,
y al anochecer fue a la casa de uno de sus amigos.

Esta insurrección de los hombres de la Quinta Monarquía
causó grandes disturbios en la nación;
y aunque los Cuáqueros no tenían nada que ver con esas personas escandalosas,
cayeron bajo grandes sufrimientos por causa de ellos.
Hombres y mujeres fueron arrastrados de sus casas y llevados a prisión,
y algunos hombres enfermos fueron sacados de sus camas por la fuerza;
entre ellos estaba un tal Thomas Pachyn, quien estando con fiebre,
fue sacado por los soldados de su cama y llevado a prisión, donde murió.

Mientras esta persecución se extendía por toda la nación,
Margaret Fell fue a ver al rey y le dio cuenta de cómo eran tratados sus amigos,
a pesar de que no estaban involucrados, en forma alguna,
con la insurrección y los disturbios mencionados;
porque varios miles de ellos habían sido arrojados en prisión. El rey
y el consejo se preguntaron cómo habían obtenido ellos esa información,
pues se había dado orden estricta de interceptar todas las cartas,
de modo que ninguna podía pasar por Londres sin ser registrada.
Pero a pesar de esto, se divulgó tanto el número de los encarcelados,
que Margaret Fell fue por segunda vez a ver al rey y a su consejo,
y los puso al tanto de los graves sufrimientos de sus amigos.
Entonces G. Fox escribió una carta de consolación a sus sufridos amigos;
y también publicó en forma impresa una declaración contra toda sedición,
conspiración y pelea,
en la que manifestaba que ellos eran un pueblo inofensivo
que negaban toda guerra y lucha,
y que no podían hacer uso de la espada externa, ni de otras armas carnales.
Esta declaración les fue presentada al rey y a su consejo, y tuvo tal efecto,
que el rey emitió una proclama de que ningún soldado podía registrar ninguna casa,
excepto con un alguacil.
Y cuando más tarde,
algunos de los hombres de la Quinta Monarquía fueron condenados a muerte por su insurrección,
abiertamente declararon que los llamados Cuáqueros no habían tenido ninguna participación,
o conocimiento de su plan.
Esta y otras evidencias hicieron que el rey,
al ser continuamente importunado al respecto,
emitiera una declaración de que los Cuáqueros debían
ser puestos en libertad sin cobro de honorarios.

Muchos de los predicadores Presbiterianos empezaron a conformarse,
y con el fin de mantener sus beneficios,
se unieron a los Episcopales y no dudaron en ponerse la sobrepelliz.
Pero esto dio pie a que muchos de sus oyentes, que no querían ajustarse a los tiempos,
los abandonaran y se unieran a los llamados Cuáqueros.
Otros predicadores, que eran un poco más firmes,
hicieron uso de su dinero para obtener la libertad de no conformarse,
aunque cuando todavía estaban bajo el gobierno de Cromwelll,
no les habían permitido libertad de consciencia a otros.
Un tal Hewes, que era un eminente sacerdote en Plymouth en los días de Oliver Cromwell,
cuando se concedía cierta libertad de consciencia,
le pedía a Dios que pusiera en los corazones de los principales magistrados de la nación,
que eliminaran la maldita "`tolerancia.`"
Pero este mismo Hewes, cuando se le preguntó, después de la llegada del rey,
si consideraba entonces la tolerancia maldita, sólo respondió moviendo su cabeza.

Ahora bien, aunque muchos de los Cuáqueros, como se ha dicho,
fueron liberados de prisión, aun así sufrieron mucho en sus asambleas religiosas.
Una vez, una compañía de irlandeses llegó a Pall-Mall cuando G. Fox estaba ahí,
pero la reunión ya se había disuelto y George se había retirado a su aposento.
Pero al oír a una de esas personas groseras, que era coronel,
decir que él "`mataría a todos los Cuáqueros,`" G. Fox bajó y le dijo:
"`La ley decía ojo por ojo, diente por diente;
pero tú amenazas con matar a todos los Cuáqueros,
aunque ellos no te hayan hecho daño.`" Y añadió: "`Aquí te mostraré el evangelio:
Aquí está mi cabello, aquí está mi mejilla,
y aquí está mi hombro,`" volviéndolo hacia él para que pudiera golpearlo si así lo deseaba.
Esto sorprendió tanto al coronel,
que él y sus compañeros se quedaron asombrados y dijeron: "`Si este es tu principio,
según dices ahora, nunca hemos visto algo igual en nuestras vidas.`"
A lo que G. Fox dijo: "`Lo que soy en palabras, lo soy en la vida.`"
Entonces el coronel se comportó cordialmente;
aunque cierto embajador que había permanecido fuera y luego había entrado,
dijo que el coronel irlandés era un hombre tan temerario,
que no se había atrevido a entrar junto con él, por temor a que hiciera un gran daño.

A pesar de estos encuentros rudos,
algún freno fue puesto a la fiera corriente de persecución; porque el rey,
recién instalado en el trono, mostraba cierta inclinación a la clemencia.
Pero esta tranquilidad no duró mucho, y no fue más que un corto período de reposo,
porque los eclesiásticos,
quienes al parecer eran instigados por los partidarios del papado,
continuaban siendo envidiosos y deseando una oportunidad de mostrar su malicia.
Un ejemplo de lo cual ya se ha visto tras la insurrección
de los hombres de la Quinta Monarquía,
y en lo que sigue lo veremos más claramente.
Porque, aunque en ese momento no parecían perseguir por motivos de consciencia, aun así,
en nombre de "`la justicia`" se hicieron uso de leyes para perseguir disidentes,
que habían sido promulgadas anteriormente para la supresión del papado,
y para proteger el reino contra Jesuitas y otros papistas traidores.

Para que se sepa qué leyes eran estas,
y para que se vea también el uso irracional que se ha hecho de ellas, las expondré aquí,
o las resumiré; para que así se vean más claramente los torpes medios que se usaron,
y cuán malévolamente fueron ejecutadas las leyes.
Puede que algunas veces entrelace entre los resúmenes,
algunas observaciones o el relato de un caso,
que aunque no esté colocado en su tiempo correspondiente,
puede ser útil para dar una verdadera noción de las cosas.
Ahora paso a estas leyes.

En el año 27 del rey Enrique VIII se promulgó una ley para el pago de los diezmos,
porque dicho rey había dado o vendido muchas capillas y abadías a laicos,
y estos no tenían derecho (como los sacerdotes pretendían tener) a citar
ante los tribunales eclesiásticos a los que no pagaban diezmos.
Debido a esto, se dispuso una ley,
por virtud de la cual un juez de un tribunal eclesiástico podía ayudar los laicos.
En dicha ley se decía,

[.embedded-content-document.legal]
--

Si el juez de un tribunal eclesiástico presenta un
reclamo ante dos jueces de paz (__quorum unus__),
por cualquier incumplimiento,
o cualquier delito cometido por el demandado en cualquier pleito que dependa de diezmos,
dichos jueces enviarán a prisión al acusado,
y permanecerá ahí hasta que pague una fianza garantizando
delante de ellos la comparecencia ante el juzgado,
o de otra manera, conferir la debida obediencia a los procesos, procedimientos,
decretos y sentencias de dicha corte.

--

Por esta ley, que supuestamente todavía está en vigor,
muchas personas honestas han sufrido y han sido mantenidas en prisión por largo tiempo;
porque,
al rehusarse a pagar una fianza por el pago de diezmos--que por razones de consciencia
no podían dar a los ministros que vivían de una manutención forzosa,
y que según juzgaban ellos,
no eran de beneficio para el pueblo--estaba en poder de los sacerdotes
retenerlos en prisión hasta que la supuesta deuda fuera pagada.
Esto ha sido juzgado tan irrazonable por los perseguidos,
que algunos han continuado en prisión por años,
prefiriendo morir en la cárcel que mantener a tales predicadores pagándoles diezmos.

Ahora bien, los llamados Cuáqueros nunca han ofrecido resistencia,
sino que el sufrimiento y la paciencia han sido siempre sus armas,
aunque han sido acosados casi continuamente, con leyes que no se hicieron contra ellos.
Y han sido especialmente molestados con el juramento de supremacía,
que fue hecho al principio del gobierno de la reina Isabel, que dice así:

[.embedded-content-document.legal]
--

Yo, +++_______+++, testifico y declaro plenamente en mi consciencia,
que su alteza el rey es el único y supremo gobernador de este reino,
y de todos los otros dominios y países de su alteza,
así como de todas las cosas o causas espirituales o eclesiásticas.
Y que ningún príncipe, prelado, estado o potentado extranjero, tiene, o debe tener,
ninguna jurisdicción, poder, superioridad, preeminencia o autoridad,
eclesiástica o espiritual, dentro de este reino.
Por tanto, renuncio y abandono completamente todas las jurisdicciones, poderes,
superioridades y autoridades extranjeras,
y prometo que de ahora en adelante mantendré fe y verdadera lealtad a su alteza el rey,
a sus herederos y legítimos sucesores; y en mi poder,
ayudaré y defenderé todas las jurisdicciones, privilegios,
preeminencias y autoridades concedidas o pertenecientes a su alteza el rey,
sus herederos y sucesores, o unidas y anexadas a la corona imperial de su reino.
Con la ayuda de Dios y el contenido de este libro.

--

En el primer año de la reina Isabel,
se hizo una ley para uniformar la oración común y el servicio de la iglesia,
con la siguiente cláusula:

[.embedded-content-document.legal]
--

Toda persona acudirá a su iglesia parroquial, o en caso de imposibilidad, a alguna otra,
todos los domingos y días festivos,
so pena de ser castigada con las '`censuras de la iglesia,`'^
footnote:[Una censura eclesiástica es una sentencia de condena,
o pena infligida a un miembro de una iglesia por mala conducta,
por la que se le priva de la comunión de la iglesia,
o se le prohíbe ejercer el oficio sacerdotal.]
y también de perder doce peniques,
que serán recaudados por los guardias de la iglesia ahí, para uso de los pobres,
embargados de los bienes del infractor.

--

Ahora, como la mencionada ley no era estrictamente obedecida, no sólo por los papistas,
sino también por otros que aspiraban a una reforma mayor,
y no podían cumplir más con los ritos de la iglesia de Inglaterra,
en el año 23 de Isabel, se hizo una ley más severa, con la siguiente cláusula:

[.embedded-content-document.legal]
--

// lint-disable mid-word-non-letter `c2`
Toda persona que no asista a la iglesia, de acuerdo con el estatuto de 1 Eliz. c2,^
footnote:[Entiéndase: Año 1 del reinado de Elizabet, cláusula 2.]
perderá veinte libras por cada mes que incumpla.
Y si se niegan a hacerlo por un período de doce meses,
una vez que se haya presentado la prueba de ello ante el tribunal del rey,
un juez del tribunal del condado donde estas vivan,
las obligará con dos garantías de 200 libras como mínimo, al buen comportamiento,
de las que no se librarán hasta que asistan a la
iglesia de acuerdo con el mencionado estatuto.

--

Parece que esta ley no se consideró suficientemente severa; por tanto,
en el año 29 de la mencionada reina, se hizo otra ley con la siguiente cláusula:

[.embedded-content-document.legal]
--

La reina puede embargar todos los bienes,
y dos tercios de las tierras y arrendamientos de todo infractor
que no asista a la iglesia como se ha dicho,
equivalentes a la suma adeudada hasta entonces,
por la falta de pago de las veinte libras al mes; y anualmente después de eso,
según la tasa de veinte libras al mes,
por el tiempo que se nieguen a asistir a la iglesia
// lint-disable mid-word-non-letter `c1`
de acuerdo con el estatuto de 23 Eliz. c1.^
footnote:[Entiéndase: Año 23 del reinado de Elizabet, cláusula 1.]

--

A raíz de estas leyes muchos fueron perseguidos.
Pero en el apogeo de estos procedimientos, George Whitehead, Gilbert Latey y otros,
le rogaron al rey Carlos II en nombre de sus amigos,
lo que dio como resultado que el rey ordenara que
se detuvieran dichos procedimientos en varios condados.
Sin embargo,
posteriormente se continuó con la acción de esta ley hasta después de su muerte,
tanto en lo que se refiere al encarcelamiento, como a la incautación de bienes.
También se hicieron uso de otras leyes antiguas,
porque en el año 35 del reinado de Isabel,
cuando los papistas conspiraron algunas veces contra la reina,
se promulgó una ley que contenía la siguiente cláusula:

[.embedded-content-document.legal]
--

Si alguna persona mayor de dieciséis años es condenada,
por haberse ausentado de la iglesia por más de un mes, sin ninguna causa legítima;
u oponerse a la autoridad de la reina en causas eclesiásticas;
o frecuentado conventículos,^
footnote:[Asamblea secreta reunida con el propósito de conspirar contra el gobierno.]
o persuadido a otros a hacerlo, bajo el pretexto del ejercicio de la religión;
será encarcelada y permanecerá ahí hasta que se conforme,
y abiertamente se someta a lo que se prescriba en adelante.
Y si dentro de los tres siguientes meses después de la condena,
se rehúsa a conformarse y someterse, dejará el reino.
Y si tal ofensor se niega a salir, o habiéndose ido como corresponde,
regresa sin la licencia de la reina,
será declarado delincuente y no disfrutará del beneficio del clero.
Pero si antes de que se le pida salir, se somete,
no se le impondrán las penas antes mencionadas.

--

Aunque se puede suponer que esta ley se hizo principalmente contra los papistas,
aun así algunos de los llamados Cuáqueros fueron procesados por esto,
y eso por sus vidas.
Porque aunque ellos hubieran estado dispuestos a salir del reino, estos,
que por un asunto de consciencia no podían jurar del todo,
no se habrían podido comprometer a hacerlo mediante un juramento.
Y siendo esto bien conocido, sucedió en una ocasión que un tal William Alexander,
de Needham, en Suffolk, estando acusado con varios más de este acto, se le preguntó:
"`¿Culpable o no culpable?`"
Como no se apresuró a responder, el juez dijo:
"`¿Por qué no te declaras culpable o no culpable?`"
A lo que Alexander respondió: "`¿Qué nos aconsejas que declaremos?`"
El juez (que generalmente era considerado un hombre severo) dijo:
"`¿Me pides un consejo?`"
"`Sí,`" dijo Alexander.
"`Entonces,`" replicó el juez, "`lo tendrán; les aconsejo que se declaren no culpables.`"
Así que los prisioneros se declararon no culpables.
Entonces el juez les dijo a los fiscales:
"`Ahora ustedes deben probar que estos hombres nunca
han estado en sus propias iglesias parroquiales,
ni en ninguna otra iglesia o capilla, pues de lo contrario,
no están comprendidos por esta ley, la cual es una ley perversa.`"
Así prosiguió el juez su discurso,
hasta liberar a Alexander y a sus amigos de la severa imputación;
porque los fiscales no pudieron demostrarlo con pruebas, como lo exigía la ley.
Un tal William Bonnet, había estado mucho tiempo en prisión, en Edmondsbury, Suffolk,
por esta ley; y también un tal Richard Vickris, cerca de Bristol.
Pero ahora regreso.

Después de la muerte de la reina Isabel, cuando Jacobo I había ascendido al trono,
los papistas continuaron con sus malvados planes,
de los cuales '`la conspiración de la pólvora`' puede servir como ejemplo.^
footnote:['`La conspiración de la pólvora`' fue un intento
fallido de asesinato contra el rey Jacobo I,
por un grupo de Católicos ingleses de provincias, liderado por Robert Catesby.
El plan consistía en hacer explotar la Cámara de los Lores,
durante la Apertura de Estado del Parlamento, el 5 de Noviembre de 1605,
como preludio a una revuelta popular en las Tierras Medias, durante la cual,
la hija de nueve años de Jacobo, Elizabeth,
iba a ser instalada como jefa de estado católica.]
Por lo tanto, para reprimir a estas malvadas personas y descubrirlas mejor,
en el tercer año del reinado de Jacobo I se promulgó una ley,
en la que se incluía el siguiente juramento,
que debían hacer los papista no-conformistas:

[.embedded-content-document.legal]
--

Yo, +++______+++, verdadera y sinceramente reconozco, profeso,
testifico y declaro en mi consciencia delante de Dios y del mundo,
que nuestro soberano señor rey Jacobo I, es el legítimo y correcto rey de este reino,
y de todos los otros dominios y países de su majestad.
Y que el papa, ni por sí mismo, ni por ninguna autoridad de la iglesia, o sede de Roma,
ni por ningún otro medio, con ningún otro, tiene poder o autoridad para deponer al rey,
o para disponer de alguno de los reinos o dominios de su majestad;
o para autorizar a cualquier príncipe extranjero a invadir,
o molestarlo a él o a sus países;
o para liberar a cualquiera de sus súbditos de su lealtad y obediencia a su majestad;
o para dar licencia o permiso a cualquiera de ellos para portar armas, levantar tumultos,
presentar cualquier violencia o daño contra la persona real de su majestad,
estado o gobierno, o contra cualquiera de los súbditos de su majestad,
dentro de los dominios de su majestad.

También juro desde mi corazón,
que a pesar de cualquier declaración o sentencia de excomunión o privación,
hecha u otorgada, o por hacer u otorgar, por el papa o sus sucesores,
o por cualquier autoridad derivada o que pretenda derivarse de él o su sede,
contra el mencionado rey, sus herederos o sucesores;
o cualquier absolución a los mencionados súbditos de su obediencia;
yo guardaré fe y verdadera lealtad a su majestad, sus herederos y sucesores,
y los defenderé a él y a ellos hasta el límite de mi poder,
contra todas las conspiraciones y atentados que sean
hechos contra su persona o la de ellos,
su corona y dignidad, por razón o pretexto de cualquier sentencia o declaración,
o de otra manera.
Me esforzaré por revelar y dar a conocer a su majestad, sus herederos y sucesores,
todas las traiciones y conspiraciones traidoras de las que yo sepa u oiga contra él,
o cualquiera de ellos.

Juro, además, desde mi corazón, que aborrezco, detesto y rechazo como impía y hereje,
esta condenable doctrina y posición,
de que los príncipes que son excomulgados o privados por el papa,
pueden ser depuestos o asesinados por sus súbditos o cualesquiera otros.
Y creo, y en mi consciencia estoy resuelto, que ni el papa, ni ninguna persona,
tiene poder para absolverme de este juramento, o cualquier parte de este,
el cual reconozco con buena y plena autoridad que me ha sido ministrado legítimamente;
y renuncio a todo indulto y dispensa en contra de dicho juramento.
Reconozco todas estas cosas clara y sinceramente,
y lo juro de acuerdo con las palabras expresadas por mí,
y de acuerdo con el claro y común sentido y entendimiento de las mismas palabras,
sin ningún equívoco, ni evasión mental, ni ninguna reserva secreta.
Hago este reconocimiento y confesión de corazón, de buena gana y de verdad,
sobre la verdadera fe de un Cristiano.
Qué Dios me ayude.

--

Este juramento, comúnmente llamado _juramento de lealtad,_
fue posteriormente llamado _la prueba._
Y aunque la introducción de este se hace mención de '`la conspiración de la pólvora,`'
y se indica que este juramento fue ideado para descubrir papistas,
aun así,
muchos de los llamados Cuáqueros han sufrido por ello durante muchos años.
Porque aunque ellos no se negaban a declarar su lealtad al rey,
era bien conocido que no jurarían nada,
y se utilizaba este juramento continuamente como una trampa para encarcelarlos.
Ahora bien, el castigo establecido contra estos no-conformistas era un __premunire;__^
footnote:[__Premunire__ era una sentencia legal concebida para privar de derechos
a los que se rehusaban a jurar formalmente lealtad al rey de Inglaterra.
Los que estaban bajo la sentencia premunire eran considerados traidores
a su país. Perdían todo derecho a la propiedad y a las posesiones,
se les quitaba la protección del rey, y a menudo se les encarcelaba de por vida.]
y no es fácil de expresar,
cuán gravemente han sido oprimidos muchos Cuáqueros por este motivo, sin embargo,
daré algunos ejemplos en lo que sigue.
Desde entonces, se han promulgado otras leyes severas para la persecución,
como se verá a su debido tiempo.

A finales de este año,
Edward Burrough escribió una epístola consoladora
a sus compañeros en el ministerio del evangelio,
que no puedo dejar de insertar aquí,
porque muestra muy palpablemente cuán valiente era él en el servicio de la Verdad;
dicha epístola es como sigue:

[.embedded-content-document.epistle]
--

Queridos y amados hermanos en la relación celestial y bendito nacimiento inmortal,
en el que somos los queridos hijos de nuestro Padre;
mi saludo se extiende a todos ustedes,
estando perfectamente unido con ustedes en sufrimientos y alegrías, en fe y paciencia,
es decir, en todas las cosas que hacen y sufren en el nombre del Señor nuestro Dios.
Mi alma los saluda y los abraza, y fervientemente les desea paz, amor y unidad,
y el incremento de toda buena dádiva en todos ustedes;
porque soy completamente uno con ustedes.
Si reciben de la plenitud de nuestro Padre, soy refrescado; si se gozan, yo me alegro;
si sufren y están agobiados, yo voluntariamente participo con ustedes.
Todo lo que es de ustedes, sea libertad o prisiones, vida o muerte,
yo participo de lo mismo.
Y todo lo que disfruto, también es de ustedes; porque somos de un mismo nacimiento,
de una misma semilla, de un mismo linaje, es decir,
de la generación de Aquel que no tiene principio de días, ni fin de vida,
que es sumo sacerdote, constituido según el poder de una vida indestructible.
Y así como Él fue bendecido por el Padre, así lo somos nosotros,
porque somos del mismo nacimiento y partícipes de Su naturaleza,
y Él vive en nosotros y nosotros en Él.

Bien, mis queridos compañeros, no necesito multiplicarles las palabras,
como si no supieran estas cosas; porque, ¿qué sé yo que ustedes no?
O, ¿qué puedo decir, sino que ustedes saben lo mismo?
Sin embargo, ténganme paciencia,
porque mi corazón está muy lleno y mi alma está dispuesta a derramarse,
para expresar una vez más un poco de lo que abunda en mi corazón; porque el amor,
el perfecto amor, el amor con el que somos amados por el Padre,
llena mi corazón en este momento hacia todos ustedes, desde el menor hasta el mayor.
En realidad, no experimento nada más que amor hacia ustedes,
y no me cabe duda de que en el mismo amor ustedes reciben este mi saludo,
el cual brota de la fuente de amor que en este momento está abierta en mi corazón.

Ahora, amados míos, las actuales reflexiones de mi corazón,
son muy numerosas en lo que respecta al gran amor
del Padre que hasta ahora se nos ha mostrado.
Todos sabemos cómo nos llamó Él por medio de Su gracia,
y volvió nuestros corazones de las vanidades y caminos
impíos de este mundo y nos santificó por Su palabra,
y puso Su imagen sobre nosotros, y nos llamó por Su nombre, y nos redimió para Él,
y nos dio el testimonio de Su Santo Espíritu en nuestros propios corazones,
para que fuéramos Su pueblo y Él fuera nuestro Dios.
Él nos enseñó, nos instruyó, nos alimentó, nos dio paz y reposo en Él,
y nos liberó de la esclavitud del pecado y la corrupción,
y de Su terror debido al pecado.
Quitó nuestras transgresiones, las borró y dejó de castigarnos,
y nos llevó a la tierra de reposo, en la que fluyen misericordia, paz,
conocimiento y todas las cosas buenas.
Esto lo hizo nuestro Señor Dios, por nosotros, en los días de nuestra infancia; o sea,
nos llamó cuando todavía estábamos en nuestros pecados y nos limpió de ellos.
Y cuando éramos extraños a Él, se dio a conocer a nosotros;
y cuando éramos totalmente ignorantes, nos dio conocimiento;
y cuando no éramos un pueblo,
nos levantó y nos hizo dignos de ser llamados por Su nombre.
Y de esta manera, nos amó el Padre, y mostró Su amor para con nosotros.
Ustedes saben esto, tal como yo, y la consideración de esto me lleva a expresarlo así.

De nuevo, cuando Él había obrado así por nosotros, y mostrado Su amor para con nosotros,
le plació llamarnos a Su obra; para volver y convertir a otros al camino de vida.
Él puso Su Espíritu en nosotros, nos dio dones de conocimiento y expresión,
nos armó con sabiduría, fuerza y valor,
y nos preparó en todos los sentidos para la obra y servicio en que nos ha llevado.
Él, digo, nos ha preparado para Su obra, nos ha llamado a ella,
y nos ha llevado gozosamente en ella,
y todo esto ha sido por Su amor gratuito y poder infinito;
y lo que hemos sido y lo que hemos hecho, ha sido únicamente del Señor y no de nosotros,
es decir, de Su amor, para que nosotros nos maravillemos.
Porque, ay, ¿qué éramos sino niños, y no profetas ni hijos de profetas?
Y nuestra educación, ¿era adecuada para estas cosas, para realizar tal llamado?
Por tanto, es el Señor y sólo Él,
quien ha efectuado Su propio propósito a través de nosotros y por medio de nosotros,
como instrumentos pobres de nosotros mismos, pero muy excelentes por Él.

Pero, ¡oh!, Él nos ha prosperado poderosamente en Su obra,
y hemos visto un glorioso efecto de nuestras labores, viajes y testimonios.
Sí, el Señor ha estado con nosotros en abundancia y Su brazo nos ha rodeado,
y con frecuencia,
nos ha dado grandes victorias sobre los sabios y entendidos de este mundo.
Él ha hecho que Su propia palabra sea a menudo muy poderosa en nuestras bocas,
para herir las consciencias de nuestros enemigos; y ha bendecido nuestro testimonio,
para confundir la sabiduría de este mundo y reunir a muchos
para Él. Él ha ido delante de nosotros con Su autoridad,
y ha estado siempre con nosotros en Su propia obra; y nuestros testimonios,
labores y viajes han sido muy preciosos y agradables para el Señor,
y para todo Su pueblo.
El efecto de esto hace que mi alma se regocije,
porque el Señor ha estado con nosotros y nos ha prosperado
hasta llegar a ser un gran pueblo,
quien ha recibido nuestro testimonio y lo ha aceptado para su salvación.
Y sólo al Señor le pertenece la gloria de todo esto.

Y por estos ocho años y más,
la mano del Señor nos ha llevado a través de grandes esfuerzos y viajes en Su servicio,
y muchos peligros, persecuciones y aflicciones nos han acompañado todo este tiempo.
Ustedes saben que el Señor nos ha librado muchas
veces de las manos de los que nos habrían destruido,
que hemos sido librados una y otra vez de los peligros y dificultades,
y que el Señor ha sido una ayuda presente para nosotros en el tiempo de nuestra tribulación.
Porque la conspiración del malvado y el propósito de los hombres impíos,
han sido quebrantados a menudo para nuestro bien, es decir,
muchas veces hemos sido librados de la trampa que se nos ha tendido,
y hemos visto a nuestros enemigos caer delante de
nosotros a la mano derecha y a la izquierda,
al sabio en su sabiduría mundana y al necio en su necedad.
Dios ha cortado a menudo tanto a profesantes como a profanos,
en sus deseos y esfuerzos por nuestra destrucción,
y hemos sido maravillosamente preservados hasta hoy.
¡Todo esto lo atribuyo al infinito amor y poder del Señor Dios,
quien es bendito para siempre!

A través de todas estas cosas todavía estamos vivos,
y el Señor no nos ha fallado hasta esta hora, sino que Él vive y camina en nosotros,
y Su testimonio está con nosotros (es decir,
el sello de Su buen Espíritu en nuestros corazones),
declarando que somos Sus hijos y siervos.
Sí, muchas señales nos confirman que somos Su pueblo.
Y la gran opresión con la que nos hemos topado no nos ha frenado,
sino que a través de ella hemos crecido y prosperado hasta este día. Y
con respecto a las cosas de las que hemos testificado estos años,
no tengo duda de que nuestro Dios las cumplirá,
ni podrá ser sacudida mi confianza por lo que sucede o pueda suceder,
porque el anticristo tiene que caer.
Dios confundirá el ministerio y el culto falsos, los caminos y las doctrinas falsas,
y derribará el poder y las iglesias falsos,
y la verdad y la justicia reinarán. Dios reunirá a Su pueblo más y más,
y aparecerán días gloriosos.
Él exaltará Su reino sobre la tierra y derrocará el reino del hombre de pecado.
Toda opresión cesará y los opresores no existirán más,
y Dios liberará a Su pueblo y ellos serán felices en este mundo y para siempre.
Estas cosas las hemos profetizado día a día,
y mi fe ha sido constante e inamovible en que Dios efectuará estas cosas en Su tiempo.
Porque el Señor nunca me ha engañado, sino que lo que ha dicho de seguro sucederá.

Por lo tanto, hermanos, tengamos esperanza y paciencia,
y vivamos en la palabra de paciencia; no seamos débiles,
como si el Señor nos hubiera olvidado o no estuviera consciente de nosotros;
o como si Él no fuera a realizar lo que ha testificado por medio de nosotros.
Porque Dios no es hombre para que mienta, ni un hombre dado a cambiar.
Sino levanten sus cabezas,
porque el Señor está con nosotros (incluso en nuestras mayores
tribulaciones y aflicciones) y cumplirá Su propósito,
porque Él es poderoso para salvar a Su pueblo y destruir a Sus enemigos.

Es cierto,
en este momento parece que las puertas del infierno están abiertas contra nosotros,
y que somos un pueblo susceptible de ser tragado por nuestros enemigos;
parece que inundaciones de maldad se desbordan y
que las olas del gran mar están vacías de misericordia.
La esperanza de nuestros adversarios es extinguirnos
como pueblo y destruirnos de la faz de la tierra,
y las manos de nuestros perseguidores están muy exaltadas hoy,
como si todo lo que hemos hecho para el Señor, mediante nuestros esfuerzos y viajes,
ya no tuviera ningún efecto.

Pues bien, queridos hermanos, aunque fuera así,
nuestro Dios puede librarnos y confundir a nuestros adversarios;
y nosotros podemos apelar a nuestro Dios y exponer nuestra causa delante de Él.
Porque Él sabe que nuestros sufrimientos y aflicciones son completamente injustos,
desiguales y perversos,
y que nuestros perseguidores nos afligen por su envidia
y sin que nosotros les hayamos dado alguna razón justa.
Dios sabe, los ángeles y los santos saben,
que nosotros hoy somos un pueblo perseguido por causa de la religión,
y que nuestra aflicción actual no es ningún castigo justo,
ni de la justicia de Dios ni de la justicia de los hombres.

Porque Dios nos ha dado el testimonio de Su Espíritu eterno,
de que no hay ira en Él hacia nosotros.
¡Sea Su ira para Sus enemigos, pero para nosotros sean gozo y paz para siempre!
Si el Señor nos exculpa y justifica, ¿quién nos condenará entonces?
Él no nos imputa ninguna culpa,
como si por nuestras malas acciones fuéramos la causa
de estos nuestros sufrimientos actuales,
o como si esto hubiera venido sobre nosotros como castigo de la mano de Dios.
Yo digo que no es así;
estos sufrimientos actuales no se deben a la ira de Dios hacia nosotros,
porque Su amor es para nosotros.
Porque le podemos decir a todo el mundo (y Dios mismo defenderá nuestra causa),
¿a quién hemos perjudicado o hecho mal?
¿Qué mal le hemos hecho a la persona de algún hombre?
¿De quién hemos tomado o codiciado falsamente los bienes?
¿Contra quién hemos concebido maldad?
Que el Señor mismo sea el juez entre nosotros y nuestros perseguidores en este asunto;
porque a Él le consta que nosotros deseamos el bien para todos, y ningún daño para nadie,
y sin embargo, somos tratados como malhechores.
El Dios del cielo es testigo en nuestras consciencias de que nosotros no conspiramos,
ni maquinamos,
ni agitamos en pensamiento o palabra el daño de la persona de ningún hombre,
sino que caminamos justamente para con todos,
al ser nuestro principio hacer con los demás lo que
queremos que los demás hagan con nosotros.
Y nosotros, podemos reclamar nuestra causa delante de nuestro Dios,
y Él abogará nuestra causa ante nuestros enemigos.
Este es el estado actual de nuestro caso:
Lo que sufrimos en este momento es únicamente por la causa de Dios,
por la justicia y por el testimonio de Jesús que sostenemos.
Por tanto, encomendemos nuestra causa al Dios del cielo, y si morimos, es por Él,
y si vivimos, es para Él; y no busquemos venganza contra nuestros enemigos,
sino dejemos que el Señor contienda con ellos.

Y, muy amados,
espero que no sea necesario que yo los exhorte a
ser pacientes y fieles en este nuestro día de prueba,
sabiendo que la causa por la que somos probados es muy excelente.
Es la causa de Dios y no la nuestra;
y espero que todos ustedes tengan el testimonio de Su Espíritu en sus consciencias,
verificando la verdad de la causa por la que sufrimos.
Y al tener esta evidencia no debemos dudar de Dios,
ni avergonzarnos delante de los hombres,
en la medida que cada uno sienta la evidencia del Espíritu de Dios dando testimonio,
de que sufrimos por causa de la justicia y por el nombre de Jesucristo.

Por tanto, queridos hermanos,
levanten sus cabezas y estén seguros de que somos del Señor,
y de que somos probados por Su causa;
que Él juzgará y se vengará de nuestros perseguidores en Su tiempo,
y que nosotros seguiremos siendo un pueblo cuando
los egipcios se hallen muertos a la orilla del mar.
Cuando el mar embravecido se seque, este mismo pueblo estará a salvo, porque,
¿acaso no ha hecho el Señor excelentes cosas por nosotros?
¿No nos ha conducido y bendecido hasta hoy?
¿No nos ha preservado a través de muchas tribulaciones y peligros hasta ahora?
¿No nos ha mostrado infinito amor y favor hasta esta hora?
¿Permitirá ahora que seamos destruidos y dejemos de ser un pueblo?
De seguro que no.
¿Les concederá Él a nuestros enemigos el deseo de sus corazones
de cortarnos para que puedan blasfemar Su nombre?
De seguro que no.
Y si le placiera al Señor que algunos de nosotros
sellemos nuestro testimonio con nuestra sangre,
buena es la voluntad del Señor; no la nuestra, sino que se haga Su voluntad.
Porque el testimonio que hemos dado todos estos años
ha sido tan excelente en sus frutos y efectos,
que su finalización merece el mejor sello posible con el que podamos firmarlo,
que es ciertamente, la sangre de nuestro corazón. Y sin embargo, aunque sea así,
mi confianza es segura,
de que la obra del Señor prosperará y nuestro testimonio será glorioso para siempre,
y que este pueblo nunca dejará de ser un pueblo.

Y no sé de nada que nos quede por hacer este día, sino encomendarnos a la mano del Señor,
viviendo en la Semilla de Dios, en la que nuestra elección es segura.
Acordémonos los unos de los otros y oremos unos por otros;
exhortemos a todos los hijos de nuestro Padre a la fidelidad y paciencia,
mientras tengamos tiempo.
Digo, caminemos para la gloria del Señor guardando la fe
y una buena consciencia hasta nuestro fin.
Porque nuestro testimonio nunca morirá,
ni nuestros recuerdos perecerán cuando dejemos de ser;
y aunque suframos ahora la pérdida de la vida y de todo lo que tenemos,
aun así los efectos de ello serán gloriosos en las edades por venir,
y nuestros actuales sufrimientos acelerarán la gloria
de la obra de Dios a lo largo y ancho del mundo.
Reciban esto como mi saludo para todos ustedes.

Han pasado ocho días desde que dejé Irlanda,
donde serví al Señor por seis meses completos,
durante los cuales Él me llevó con mucha fidelidad y diligencia en Su servicio,
para confirmación de muchos en la verdad de Dios, y para la conversión de otros.
Y debido a que la presencia del Señor estaba conmigo, tuve un tiempo muy precioso,
y fui maravillosamente preservado a través de muchos peligros y pruebas.
Viajé cerca de dos mil millas de un lado a otro en esa tierra,
y tuve libre paso en las principales ciudades y pueblos,
hasta que mi obra para el presente había terminado completamente ahí,
teniendo más tiempo del que podía esperarse para
aclarar mi consciencia ante todas las personas.
Sería demasiado largo mencionar cada asunto en particular
en el que percibí la eminente mano de Dios conmigo;
además de muchas cosas que observé con respecto al
estado actual de las cosas que no mencionaré;
porque, ¿qué tenemos que ver nosotros con los asuntos de los reinos mundanos?
Pero en cuanto a los Amigos,
estaban bien ahí. Crecen y se incrementan en las bendiciones y plenitud del Padre,
y cuando me vine todo estaba tranquilo y muy pocos estaban en prisión,
aunque supongo que las noticias de las cosas tal
como están aquí les producirán los mismos sufrimientos.
Pero espero que sean audaces y valientes por la verdad,
dando sus testimonios mediante sufrimientos fieles, hasta que se terminen estas cosas.

Así permanezco en la vida y en la muerte, y cuando ya no esté, en el recuerdo eterno,
el querido hermano y compañero de ustedes,
haciendo y sufriendo por el nombre del Señor y Su verdad.
Estoy bien, y en libertad hasta el momento.

[.signed-section-signature]
E+++.+++ B.

[.signed-section-context-close]
11 del mes Doce de 1660.

--
