== Capítulo 9

[.section-date]
1659--1660

[.chapter-synopsis]
* W. Caton en Holanda
* W. Ames en Alemania
* W. Ames confinado en Bedlam
* Sufrimientos de 218 Amigos presentados ante el Parlamento
* Ciento sesenta Amigos se ofrecen a permanecer en la cárcel en lugar de sus hermanos
* Notable profecía de E. Burrough
* E. Burrough y S. Fisher en Dunkerque
* Controversia con los frailes
* R. Cromwell se retira a la vida privada
* Intrigas de los oficiales militares para retener el Poder
* Mensaje de E. Burrough a los gobernantes de Inglaterra
* Carta a los Caballeros
* Continuación de la persecución en Nueva Inglaterra
* Instancias de espantosa crueldad
* Sufrimientos de R. Hodshone
* Prohibición bajo pena de Muerte
* Juicio y ejecución de W. Robinson y M. Stevenson
* Mary Dyer.

En la primera parte del año 1659, había una gran discordia,
y aparecieron varias facciones entre el pueblo de Inglaterra;
pues algunos se unieron al protector Richard,
otros a los principales miembros del Parlamento Largo; y los monárquicos,
que también eran un partido.
G+++.+++ Fox, que estaba preocupado por el temor de que personas jóvenes o inmaduras,
que a veces estaban entre sus amigos,
se vieran arrastradas por algunos de estos intereses,
escribió una epístola advirtiéndoles que debían tener cuidado,
y que no se entrometieran en ninguna conspiración,
sino que consideraran que su lucha era la espiritual,
y que no necesitaban del todo el uso de armas carnales.

Por este tiempo regresó a Holanda William Caton,
y al encontrar en Amsterdam algunas personas maliciosas que se esforzaban por
meter en problemas a sus compañeros creyentes e incitar a la chusma contra ellos,
para que los magistrados tuvieran oportunidad de considerar a los Cuáqueros como alborotadores,
les aconsejó a los de dicha persuasión que fueran cautos, y evitaran de esta manera,
tanto como fuera posible, la inminente tormenta.
Para ello, se pensó adecuado,
que sus reuniones religiosas de los primeros días de la
semana no se celebraran siempre en un mismo lugar,
sino que a veces se celebraran en una casa, y en otras ocasiones en otra.
A veces se celebraba una reunión en un callejón del muro del pueblo,
cerca de Regulars Gate,
donde vivían varios ingleses (por lo que se llamaba English Alley,
y todavía tiene ese nombre).
A este lugar llegaba un grupo muy grosero, que cometía actos de gran insolencia.
En una ocasión anterior, cuando William Caton estaba en Holanda,
tuvo un encuentro extraordinario en dicho lugar, a tal punto,
que estuvo en peligro de muerte, pues algunas personas malvadas,
al no atreverse a ejecutar sus intenciones en la casa donde estaba,
lo sacó a empujones por la puerta; pero una mujer lo metió en su casa de un jalón,
y quedó a salvo, aunque al principio no sabía si estaba entra amigos o enemigos.
Todavía recuerdo bien este incidente,
pues en ese momento yo estaba con mis padres en esa perturbada reunión.

Ahora bien, Caton al ser una persona discreta y juiciosa,
y entendiendo que algunos de sus amigos ahí tenían
más celo temerario que verdadera sabiduría,
aconsejó a los más moderados de ellos,
que cambiaran con frecuencia el lugar de las reuniones.
Al principio, se celebraba una reunión en la llamada calle St. John;
después en Eland`'s Graff, en un callejón, en la casa de un tal Richard Langham;
también en Angelier`'s Graff, en la casa de mi padre;
en algún momento después en English Alley arriba mencionado; también fuera del pueblo,
cerca del río Amstel, en Cooper`'s Lane;
de donde se movió la reunión en la primera parte
del año (si mi memoria no me engaña) a Dyers`' Lane.

Después de cierta estadía en Holanda, William Caton regresó a Inglaterra.
Creo que fue este año, que William Ames fue a Alemania,
donde después de haber entrado en Palatinate, fue a Heidelberg,
y llegó a la corte del príncipe elector, Charles Lodowick, quien lo trató amablemente,
incluso en su propia mesa,
y no parecía ofenderse por el sombrero de Ames que lo mantuvo puesto,
aunque los señores y otros que estaban en el grupo estaban con la cabeza descubierta.
El barón de Helmont, que también estaba en esa corte, solía contar después,
que en una ocasión que Ames caminaba con su sombrero
puesto cerca del príncipe en su jardín,
los cortesanos le habían preguntado al príncipe si
debían interrogar a Ames por esa falta de cortesía,
pero que el príncipe había dicho: "`No, yo me lo esperaba.`"
En otra ocasión, el príncipe hizo que su capellán y Ames comieran con él,
con el propósito (al parecer) de que Ames, de quien sabía que era un hombre audaz,
encontrara la oportunidad de amonestar a su capellán;
pues dicho capellán permitía que su bufón llegara a las comidas
e hiciera sus trucos mientras él permanecía en silencio.
Pero Ames, que amaba la sobriedad y era contrario a tales bromas,
efectivamente aprovechó la oportunidad para reprobar dichos actos vanos.
No obstante, dirigió su reproche principalmente al capellán, quien,
debido a su silencio ante el lascivo comportamiento del bufón,
fue comparado con un perro silencioso; lo cual pareció complacer al príncipe.

Mientras William Ames estaba en la región de Palatinate,
conoció a los Bautistas de Kriesheim, un pueblo no lejos de Worms,
y encontró tal acogida entre esa gente,
que algunas de las familias que recibieron la doctrina predicada por él,
dieron testimonio público de ella ahí,
y así continuaron hasta la fundación de Pennsylvania en América,^
footnote:[A mediados de la década de 1680.]
donde fueron unánimemente, no (al parecer) sin una notable dirección de la Providencia;
pues no mucho después de esto se produjo una guerra en Alemania,
y la región de Palatinate fue completamente devastada por los franceses,
y miles de personas fueron despojadas de sus posesiones y reducidas a la pobreza.

Pero volviendo a Ames; cuando algunos de Palatinate empezaron a escuchar su predicación,
se impuso una multa sobre aquellos que lo habían hospedado,
pero cuando se le informó de esto al príncipe elector, revocó la multa,
y aunque algunos del consistorio^
footnote:[En la Iglesia Romana, consejo de cardenales con o sin el Papa.]
mandaron a llamar a Ames,
el príncipe les ordenó amablemente que no se metieran con él. La hermana del príncipe
también se comportó con él muy amablemente y recibió sus exhortaciones favorablemente.

Un año después de esto, Ames regresó a la región de Palatinate con John Higgins,
y al visitar al príncipe elector,
escuchó del capitán de la guardia del príncipe que
el príncipe estaba muy contento con su regreso.
Poco después, Higgins le entregó un libro de G. Fox y una carta de Ames a dicho príncipe,
quien estaba tan complacido con ella,
que le pidió a Higgins que se lo agradeciera a Ames en su nombre,
diciéndole además que él y su familia acogían la visita de ellos muy amablemente,
y que realmente creían que lo que ellos hablaban era en amor por sus almas.

Varios años después de esto,
otros amigos de Ames de Inglaterra visitaron al mencionado príncipe elector,
y siempre los recibió amablemente.
William Ames, que estuvo varias veces en Alemania, no sólo fue a Hamburgo,
sino que también viajó a través de Bohemia hasta Dantzic, y de ahí a Polonia.
En Hamburgo y Dantzic se topó con algunos que recibieron la Verdad que él predicaba,
pero en Polonia la gente era demasiado tosca y altiva para tener aceptación entre ellos.

En la primera parte de este año, estando W. Ames en Rotterdam, Holanda,
fue confinado en Bedlam;^
footnote:[Un manicomio.]
de lo cual, por haber causado una gran revuelo, haré un breve relato aquí. En Moordrecht,
una villa cerca de Gouda, vivía en ese tiempo un tal Martin Martinson,
un tonelero de oficio.
Este hombre, tras aprobar la doctrina predicada por Ames en Rotterdam y otros lugares,
comenzó a afirmarla como verdad,
y al verse que él y algunos de sus vecinos sobrios a veces se reunían en su casa,
se levantó una gran conmoción en el pueblo, tanto así,
que algunas veces sufrió rudos tratos por parte del pueblo.
En una ocasión que Ames llegó a Moordrecht y asistió a la reunión en la casa de Martin,
la chusma malvada cometió grandes insolencias.
Y al irse de ahí para cruzar el agua hacia Gouwerek,
fue seguido por una multitud alborotada, tanto de jóvenes como de mayores,
con un grito horrible de "`¡Temblor, Temblor,
Temblor!,`" y fue atacado con piedras y terrones
hasta que llegó al bote que lo iba a transportar.

Cuando el predicador de Gouwerek oyó el alboroto, llegó al bote y preguntó qué pasaba,
y por qué la gente hacía tanto ruido.
Ames respondió: "`Parece que no se le ha enseñado mejor a la gente.`"
A esto el predicador respondió:
"`Ellos usualmente no hacen tal conmoción contra la gente honesta,
pero creo que tú eres un lobo engañador, que viene entre las ovejas para seducirlas,
y por eso gritan así.`" "`Pruébalo,`" replicó Ames.
"`No te conozco,`" dijo el predicador.
"`Entonces,`" le respondió Ames,
"`aprende mejores modales antes de llamar a alguien que no conoces, lobo y engañador.`"
Ames continuó su camino, y poco después le escribió desde Rotterdam a Martin Martinson,
y le pidió que fuera donde el predicador y le solicitara
que fijara una hora para probar que Ames era un lobo engañador.
Pero el predicador se mostró reacio a hacerlo; sin embargo,
a fin de deshacerse de Martin, finalmente le dijo: "`Ven, te lo probaré ahora.`"
Pero Martin replicó: "`Yo no he venido para esto;
eso debe ser hecho delante de William Ames,`" e insistiendo en eso, el predicador dijo:
"`Bien, que venga el próximo Domingo antes del mediodía, después del sermón;
entonces lo probaré públicamente delante de toda la gente.`"

Martin le envió un mensaje de esto a Ames, pero las cosas se manejaron de tal modo,
que la proyectada prueba se anuló,
porque el predicador de Gouwerek fue a ver a su colega
en Moordrecht y le consultó qué hacer en este caso;
y Ames, que había llegado a Moordrecht el primer día del mes llamado marzo,
y último de la semana, aunque era tarde en la noche,
había sido visto y reconocido por algunos que cometieron gran violencia
contra la casa de Martin a la que Ames había entrado.
Al día siguiente se informó que algunos hombres del alguacil de Gouda,
habían llegado a Gouwerek para aprehender a Ames cuando llegara ahí;
y de Moordrecht llegaron los hombres del alcalde con el mismo propósito; y así,
tomaron prisionero a Ames y lo llevaron a Rotterdam,
donde fue encerrado en Bedlam como si hubiera sido un loco.
Una semana después, Martin, por haber celebrado reuniones en su casa,
donde no habían llegado más de ocho personas,
fue también capturado en su casa por los hombres del alcalde y llevado a Rotterdam,
donde fue encerrado con Ames.
Quiénes eran los instigadores de este asunto es bastante claro, aunque yo no los mencione.

Después de que Ames había estado un poco más de tres semanas en Bedlam,
el representante-gobernador de la casa fue el 27 del mes adonde él y Martin por la noche,
y les dijo: "`Si yo estuviera en sus lugares,
saldría.`" Esto hizo que Ames le preguntara si él les permitiría hacerlo.
El representante les respondió, que él no les estorbaría. Entonces Ames replicó:
"`No seré considerado un hombre que se escapó de la cárcel.`"
El representante respondió: "`No,
¿por qué serías considerado así? Puedes salir libremente;
no hay nada cerrado y la puerta estará abierta para ti,
porque los gobernantes piensan que no deberías permanecer aquí.`" Entonces Ames dijo:
"`Bien, entonces, tengo la intención de salir mañana.`"

Al día siguiente la esposa de Martin llegó a ver a su esposo,
pero el representante le dijo que él tenía una orden por escrito del alcalde que decía,
que en lugar de dejar que la esposa de Martin lo viera,
él dejaría que Martin y Ames salieran juntos.
Y así, 28 del mes por la mañana, los dejaron salir.
Pero ellos se quedaron en Rotterdam,
con la intención de no salir de la ciudad antes de
haberle avisado al alcalde de su salida,
para no dar oportunidad a que se dijera que habían
escapado de prisión. Y no en vano fueron tan cautelosos,
porque al día siguiente, por la mañana, el representante fue donde ellos y les dijo:
"`Les pido que no me metan en problemas, porque soy un hombre viejo;
el alcalde ha estado conmigo y me ha preguntado por ustedes,
y yo le respondí que ustedes habían salido; pero él se lo tomó muy mal.
Así, pues, les pido que le digan a él que ustedes salieron sin mi conocimiento.`"
Pero esto no se podía esperar de Ames, a quien conocí muy bien, porque creo de verdad,
que él habría preferido morir que decir una mentira;
porque en este caso él estaba sin ninguna duda en la misma mente
en la que estaba Christian Languedul (un tío de mi abuela materna),
quien, estando en Antwerp (junto con otros mártires),
fue llevado a la hoguera para ser quemado y gritó sin inmutarse:
"`¡Si nosotros hubiéramos dicho una sola vez una mentira,
nos habríamos librado de esto!`"
Pero de vuelta a Ames;
él le dijo al representante que él tenía la intención de ir y hablar con el alcalde,
y que si le disgustaba la salida de ellos, podía meterlos de nuevo donde habían estado,
porque ellos no querían que los llamaran fugitivos.

Entonces ambos fueron donde el alcalde y le contaron de qué manera habían salido,
diciéndole además, que ellos no querían que se dijera que eran fugitivos.
"`Ese nombre,`" dijo el alcalde,
"`es el que habrían recibido si se hubieran ido de la ciudad,
porque el representante me dijo que ustedes habían salido al quebrar una ventana.`"
Después de un intercambio de palabras, añadió:
"`No tengo nada que objetar contra sus vidas ni conductas,
ya que sólo he oído buenos informes de ustedes, ni tampoco busco perseguirlos; pero,
¿estarían dispuestos a regresar a Bedlam?`"
Ames respondió: "`Estamos aquí delante de ti, puedes hacer con nosotros lo que quieras.
Si deseas que regresemos ahí, lo haremos.`"
Al indicar el alcalde que ese era su deseo,
dijo que ellos podían ir y caminar en los jardines hasta que llegara otra orden.
Así, el 31 del mes, fueron encerrados de nuevo en huecos separados.
Entonces Ames le dijo al representante que el alcalde les había dicho,
que él había sido informado por el representante,
que ellos había salido al quebrar una ventana.
Pero el representante negó haber dicho eso.
Ellos permanecieron detenidos ahí por un tiempo y fueron visitados con frecuencia,
a menudo, por personas que no buscaban más que burlarse de ellos.
Entre estas un cierto clérigo, que llegó tan lejos como para decir,
que Ames era un engañador porque usaba botones de estaño,
para hacerle creer a las personas que eran de plata.
Mientras Ames estuvo confinado ahí, escribió algunos documentos que publicó después,
y entre ellos estaba una contestación a la respuesta que había dado un tal Jacob Koelman,
a ochenta y tres preguntas formuladas por dicho Ames.
Cuando finalmente fueron puestos en libertad, Ames viajó a Alemania,
como ha sido dicho antes, y de ahí regresó a su país nativo,
y después de un tiempo regresó a Holanda, al igual que William Caton.

Ahora regreso a Inglaterra,
donde se publicó de forma impresa un relato de los sufrimientos del pueblo llamado Cuáqueros,
el cual al ser presentado al Parlamento, se le entregó al presidente Thomas Bampfield.
Este contenía un relato de más de ciento cuarenta personas,
todas especificadas por nombre, que por celebrar reuniones, rehusar hacer un juramento,
no quitarse el sombrero, no pagar los diezmos, o viajar por todo el país,
habían sido capturados y encarcelados.
Muchos habían sido despojados de sus bienes, y veintiuno de estos habían muerto,
bien por enfermedades en prisión, bien por violentos maltratos.
Entre estos estaba un tal Richard Sale, de West Chester, quien siendo alguacil,
hizo comparecer ante él a un ministro del pueblo llamado Cuáqueros,
con una orden que lo declaraba vagabundo, cuya conducta convenció tanto al alguacil,
que le dio la libertad.
Y como el mencionado Sale llegó a ver cómo los sacerdotes
y las personas estaban extremadamente oscurecidas,
realizó un acto extraordinario para mostrarles por medio de una señal,
que ellos necesitaban ser alumbrados; a saber,
entró en pleno día con una linterna y una candela encendida a la '`casa
del campanario,`' durante el sermón. Pero esto fue resentido a tal grado,
que por orden del alcalde fue puesto en prisión,
y arrojado a un hueco llamado Little Ease.
Este hueco era muy estrecho, y no podía contener bien su cuerpo;
y fue introducido con tal violencia, que su cuerpo quedó herido y él escupía sangre.
Poco después de esto se enfermó gravemente,
su cuerpo se hinchó (debido a lo apretado que estaba
dentro del hueco) y murió con gran dolor.

En el antes mencionado recuento impreso,
también se mostraba que en los últimos seis años cerca de dos mil personas,
por ser Cuáqueras, habían sufrido en sus cuerpos y posesiones.
A este relato se le añadió un documento firmado por más
de ciento sesenta personas (varias de las cuales yo conocía),
en el que le ofrecían al Parlamento ponerse en el lugar de sus hermanos confinados,
ya fuera en prisiones, casas de corrección o mazmorras,
siendo que algunos estaban encadenados y que otros yacían enfermos sobre un poco de paja,
y se declaraban listos a intercambiar lugares con ellos por verdadero amor,
para que pudieran salir y no morir por los sufrimientos,
como ya había sucedido con muchos; para evitarlo,
estaban dispuestos a asumir los sufrimientos de sus hermanos y dar sus vidas por ellos.
Debajo de sus nombres añadieron: "`Si hubiéramos sido de la raza de Esaú,
habríamos desfallecido antes de este tiempo; y si hubiéramos sido de la progenie de Caín,
habríamos peleado con su arma.
Pero este nunca fue, ni es ahora,
el camino de los justos y escogidos desde la fundación del mundo,
de los cuales somos nosotros.`"
Este documento fue entregado al Parlamento en el mes llamado abril,
pero no encuentro que se haya aceptado el ofrecimiento,
ni que se haya hecho algo por liberar a los prisioneros.

Por esta época,
Edward Burrough publicó también un documento que contenía
una predicción muy sorprendente de lo que sucedió después,
cuando el rey Carlos II fue puesto en el trono.
En este dice, que en el primer mes, mientras viajaba en Warwickshire,
sus meditaciones estaban centradas en el Señor,
y al considerar los injustos y deplorables sufrimientos que habían
sido infligidos al pueblo del Señor durante esos pocos años,
un clamor lo había atravesado: "`¡El Señor será vengado,
el Señor será vengado de sus enemigos, y Él vengará la causa de Su pueblo!`"
Este clamor lo golpeó profundamente, y por ello,
su corazón se quebrantó y su espíritu se derritió delante del Señor,
y le pareció que se le decía: "`Escríbeles a los gobernantes y adviérteles una vez más,
de la recompensa e indignación que están a punto de caer sobre ellos; es decir,
de la justa recompensa que recibirían por todas sus acciones.
Según han hecho, así les será hecho.
Así como han buscado destruir la generación de los justos,
así serán destruidos de la faz de la tierra.
Así como han juzgado y condenado injustamente al inocente,
así serán condenados y justamente juzgados por el Señor. Así como han
arrojado los cuerpos de los pobres corderos de Cristo en prisión,
y han sido una trampa para ellos, así serán atrapados y llevados en cautiverio.
Así como han hecho que los bienes y posesiones del inocente se arruinen,
y los han hecho presa, así también la maldición del Señor arruinará sus bienes.
En efecto, así como han hecho ellos, les será hecho; y así como han medido a otros,
serán medidos de nuevo.`"
"`Entonces,`" dijo E. Burrough, "`vi cerca una gran miseria y desolación, o sea,
vi la espada del Señor que los debía matar.
Contemplé que estaba lista para la matanza, y en la consciencia de estas cosas,
una tristeza cayó sobre mi espíritu al considerar
la desolación y el juicio que estaban cerca,
a punto de ser ejecutados sobre los crueles opresores.`"
Por esto, les escribió lo siguiente:

[.embedded-content-document.paper]
--

Por tanto, a todos ustedes gobernantes,
y a todos los que han pisoteado la herencia de Dios,
y a todos los que han desatendido las muchas advertencias que han recibido, les digo,
en el poder del Señor Dios, en Su dominio y por Su Espíritu:
Esta es una advertencia más para ustedes de parte del Señor,
de que estas cosas ciertamente deben suceder y ser cumplidas en su tiempo;
ningún hombre será capaz de liberar a su hermano,
sino que cada uno llevará su propia carga y beberá su propia copa preparada
para él. Y aunque esto ha sido considerado una cosa liviana entre ustedes,
y han despreciado la reprensión y continuado sin temor,
aun así el Señor los ha perdonado, y no ha ejecutado rápidamente el juicio sobre ustedes,
sino que ha esperado que regresen.
Sin embargo, no han aceptado el trato del Señor hacia ustedes al perdonarlos,
y por tanto, Sus juicios serán mayores sobre ustedes.

Vengan ahora al Testigo en sus propias consciencias
y díganme qué mal ha hecho este pueblo.
El bien de quién han tomado o qué han buscado de ustedes.
En qué han sido ellos una carga para ustedes,
sino en reprender sus iniquidades y desear su redención. Si sólo
consideraran esto y confesaran la Verdad en sus consciencias,
¿no les diría esta que ellos han sufrido pacientemente
todas las cosas que ustedes cruelmente les han impuesto?
¿No han caminado pacíficamente para con ustedes, y andado humilde,
mansa y justamente entre sus vecinos?
¿No han sido ellos mansos e inocentes como corderos,
y como ovejas delante de los trasquiladores?
¿Han ofendido a alguien?
¿Han buscado derrocar el gobierno, o han buscado alguna vez venganza contra sus enemigos?
¿Qué daño le han hecho a una persona o propiedad, excepto a Satanás y su reino?
¿No han buscado reformar y rescatar a los impíos de sus caminos?
¿No se han compadecido y orado por sus enemigos?
¿No han caminado en todas las cosas con buena consciencia
hacia el Señor y hacia todos los hombres?
Sí, mis amigos, en el día del Señor,
cuando el Testigo en sus consciencias no sea limitado, sino que hable claramente,
y cuando el Juez imparcial aparezca en Su trono, entonces admitirán estas cosas.

Por tanto, les digo: Reciban el juicio del Señor para que los purifique, de lo contrario,
el juicio los destruirá. Vengan y sean más sabios,
a fin de que algunos de ustedes sean como un tizón
arrancado del fuego y salvado de ser consumido;
porque la visitación del Señor se acerca a su fin,
cuando Su amorosa bondad se cerrará para ustedes y Su paciencia se volverá furia.
Él hará que ustedes sepan que nosotros somos Su pueblo, con quienes se han portado así;
sí, lo sabrán repentinamente.
¡Oh, qué les diré!
Porque el profundo sentido de esto permanece sobre mi corazón cuando considero,
que en todas las edades el Señor ha vengado la causa de Su pueblo,
y cuando el tiempo de sus sufrimientos había expirado,
rompía las ataduras de iniquidad y los liberaba.
Así Lo hizo con el Israel de antaño; muchas veces Su manera de tratar con Su pueblo fue,
abatirlo por medio de los sufrimientos y levantarlo de nuevo en gloria;
y permitir que los enemigos se gloriaran sobre ellos por un tiempo,
para que Él pudiera derribarlos.
Y así lo hizo en Inglaterra, en el caso de los obispos y sus perseguidores,
contra el pobre pueblo en ese entonces llamado Puritanos.
¿No confundió Él a ese grupo perseguidor y liberó a Su pueblo?
¿Acaso no es Él, el mismo hoy?
¿No efectuará Él la misma obra este día? Sí, sin ninguna duda, y hará mucho más,
en la medida que la manifestación de la Verdad sea
más clara de lo que era en los días de ellos,
y en la medida que los gobernantes y el pueblo de
esta nación rechacen un testimonio más claro,
que el testimonio de los Católicos en los días de la reina María,
o el de los obispos y prelados en los días de ellos.
Porque el Señor ha mirado los sufrimientos de Su pueblo y ha dicho:
"`Suficiente;`" pues los ha probado y hallado fieles,
y todo esto ha sido permitido para probarlos, no para destruirlos.
Y así como Él los ha preservado en paciencia y paz a través de todo,
así les dará corazones para que caminen de manera digna de su liberación.
Y así como han abundado en paciencia en sus sufrimientos,
así abundarán en alabanzas eternas en el día de su liberación,
cuando el Señor quebrante el yugo de los oprimidos y libere a Su pueblo interna y externamente.
Entonces cantarán al Señor sobre todos sus enemigos,
quienes serán atormentados y confundidos en el doloroso disgusto del Señor;
porque la recompensa de ellos viene y su recompensa será como su obra,
y Él les dará dolor y angustia, en lugar de gozo.

Pero, de nuevo, cuando consideraba la longanimidad,
paciencia y tolerancia del pueblo inocente del Señor bajos todos sus sufrimientos,
y miraba su inocencia y su justicia,
y el espíritu de santidad con el que el Señor los ha bendecido, mi corazón se alegraba.
Y mi gozo era mayor cuando contemplaba su inocencia y lo irreprensible de su causa,
mediante lo cual la injusticia de sus sufrimientos se hacía más evidente.
Y cuando miraba y contemplaba cómo se incrementaban bajo todos sus sufrimientos,
y cómo convertía el Señor todas estas cosas para
el bien de ellos y para derrota de sus enemigos,
y cómo por la forma en que sus enemigos intentaban
destruirlos para que no fueran un pueblo,
el Señor los incrementaba maravillosamente para que fueran un gran pueblo;
porque a través de todo esto han crecido en vida y poder, en fuerza y número,
y así han sido animados a seguir al Señor con más celo y valentía;
en la consideración de esto me regocijé y magnifiqué al Señor,
porque había hecho surgir Su alabanza, incluso a través de la maldad del impío,
y porque había incrementado a Su pueblo y lo había
exaltado a través de la crueldad de todos sus enemigos.
Cuando consideraba cómo el Señor les ha dado dominio y cómo
ha llevado sus vidas a reinar sobre todos sus enemigos,
estas cosas eran de alegría para mí. Al mirar retrospectivamente
en las edades y ver que no había habido nada,
que no había habido un pueblo por generaciones que hubiera crecido y se
hubiera levantado a través de toda oposición como ha sucedido con este,
es una señal y un testimonio de que somos del Señor, y que estas cosas son sólo de Él,
para Él y por Él, para que Él sea alabado por los siglos de los siglos.

Además, cuando considero cómo ha llevado a cabo el Señor esta obra entre Su pueblo,
que no ha sido por nada del hombre, ni por el brazo de la carne,
sino que en pura inocencia y sencillez se ha realizado;
que no ha sido por la sabiduría de este mundo, ni por hombres en lugares de honor,
ni de poder en las naciones, porque este pueblo ha carecido de todas esas cosas;
y que lo que son ahora, ha sido a través de la oposición de todo esto,
pues ellos no han tenido a ninguno de los grandes hombres
de la tierra a su lado para defenderlos ni establecerlos,
sino que todos han estado contra ellos; y que de hecho,
opresión y tiranía han sido ejecutadas sobre ellos,
en lugar de alguna aprobación o justificación de los hombres en autoridad externa;
entonces, puede ser verdaderamente dicho, que no hay nada del hombre en esta obra,
sino que toda es del Señor y por Su propio poder;
y que el inicio y realización de estas cosas han sido de
manera contraria a todas las falsas sectas y falsas iglesias.
Porque sabemos que todas las sectas en esta nación se han levantado y se han establecidas,
a través del consentimiento de los hombres que tienen un lugar y poder;
y que el surgimiento y caída de todas las iglesias falsas han dependido del hombre,
de la sabiduría de este mundo y de la autoridad de los poderes de la tierra.
En la medida que los poderes de la tierra se han colocado al lado de ellas,
así han sido erigidas; y en el disgusto de la autoridad, han sido derribadas.
Pero en cuanto a este pueblo,
ellos han sido levantados por el Señor y establecidos por Él,
aún en contra de todos los hombres.

Por tanto, que todos los perseguidores se inclinen delante del Señor,
y que todos los santos caminen humildemente ante Su vista,
y continúen en esa vida inocente en la que han comenzado.
Que nunca olviden las misericordias del Señor y lo que Él ha llevado a cabo,
quien ha manifestado grandes cosas y hará aún más,
para la confusión de todos Sus enemigos y alabanza de Su pueblo escogido.
Todos ustedes santos sobre la tierra,
miren al Señor continuamente y no se vuelvan a ídolos,
sino que el Señor sea el gozo de ustedes para siempre.

[.signed-section-signature]
E+++.+++ B.

--

No mucho después de la publicación de este documento, en el mes llamado mayo,
Edward Burrough y Samuel Fisher fueron de Dover a Dunkirk,
donde había una guarnición inglesa.
La noticia de la llegada de ellos se esparció rápidamente por el pueblo.
Como el gobernador Lockhart no estaba ahí, su representante, el coronel Alsop,
con el consejo de oficiales, envió a buscarlos;
y cuando llegaron les preguntaron qué asunto los
había llevado ahí. Ellos respondieron a esto,
y a la mañana siguiente indicaron por escrito, que habían ido a visitar a los Jesuitas,
frailes, sacerdotes y a otros Católicos,
para mostrarles los errores de sus caminos y la falsedad de su adoración, etc.,
ya que habían sido llamados a predicar el evangelio eterno a las naciones.
Estuvieron algunas horas conversando con el mencionado representante y los oficiales,
y fueron tratados con amabilidad; pero el representante dijo, sin embargo,
que sería peligroso para ellos permanecer en el pueblo,
y por eso les pidió que se fueran.
A esto ellos respondieron, que si él lo deseaba, no podían recibir tal deseo,
y que si se los ordenaba, no podían obedecer su orden en ese caso,
porque no podían irse del pueblo a menos que fuera por la voluntad de Dios,
según la cual habían llegado ahí. Después de mucho razonar los dejaron ir,
y al día siguiente fueron a ver a los frailes Capuchinos,
y tuvieron una conversación con los principales de ellos en su jardín,
acerca de la luz de Cristo con la que todo hombre es alumbrado.
También les dijeron que el poderoso día del Señor estaba cerca de ellos,
y que el Señor había venido a buscarlos y a probarlos, y que Él talaría sus caminos,
adoraciones y obras idólatras.
Al día siguiente Burrough les escribió algunas preguntas
a los frailes y monjas del pueblo y alrededores,
que les fueron enviadas en Latín. La introducción dice así:

[.embedded-content-document.letter]
--

El poderoso día del Señor ha llegado, y viene sobre ustedes y sobre todo el mundo.
Despierten, despierten, los que duermen en la tierra,
porque el terrible Dios se está levantando para pleitear contra ustedes,
y darle a todo el mundo la copa de Su feroz indignación, por causa de sus idolatrías,
hipocresías y abominaciones que han corrompido la tierra,
y han subido delante de Él y lo han provocado.
El clamor de los justos que han sido golpeados y llevados a la muerte,
ha entrado en los oídos del Altísimo, y Su espada, que es la Palabra de Su boca,
se ha despertado para herir y destruir a todos Sus enemigos.
El día de la visitación a ustedes ha llegado,
en el que el Señor los escudriña y prueba para recompensarlos;
y esta es la palabra del Señor para ustedes.

Por tanto, soy movido por el Señor a plantearles algunas preguntas,
para la prueba de sus espíritus y caminos; de las cuales solicito su respuesta,
para que todas las cosas puedan ser llevadas a la luz y al verdadero juicio,
y que ustedes sean juzgados justamente, y para que por el Espíritu del Señor,
sean absueltos o condenados de acuerdo con sus obras.

--

Estas preguntas se referían, en parte, a las órdenes^
footnote:[Hermandades religiosas reconocidas por la iglesia Católica.]
de frailes y monjas, si una cosa así existía en la iglesia en los días de los apóstoles;
y con respecto a la adoración y a las ceremonias Católicas,
se demandaba prueba de su legitimidad a partir de las Sagradas Escrituras.
Después de la entrega de estas preguntas a los Capuchinos,
Edward Burrough y Samuel Fisher también fueron a los frailes de otras órdenes,
y entraron en conversaciones con ellos,
pero sus sencillas palabras contra los ritos y ceremonias idólatras no encontraron entrada.
Después de una estancia en el pueblo, habiendo ido al seminario de los Jesuitas,
entraron en discusión con su principal rector,
y después de una conferencia de aproximadamente tres horas, él se cansó,
y alegando tener otros asuntos, dijo que no se quedaría más con ellos;
y así se separaron.
Ellos le preguntaron al rector si él aceptaría más conversaciones en otro momento,
pero él se rehusó. Burrough después le escribió una carta, cuyo inicio es así:

[.embedded-content-document.letter]
--

Amigo, tu sabiduría y tu conocimiento son terrenales y sensuales,
y por eso no puedes conocer las cosas del reino de Dios.
+++[+++Y concluyó con esta pregunta:]
¿Qué es esa ramera que se ha sentado sobre multitudes?
¿Qué es esa copa de oro en su mano?
¿Qué son las abominaciones y fornicación de las que está llena su copa,
que ha hecho que reyes y pueblos beban?

--

Pero ni estas preguntas ni las otras fueron respondidas.
Burrough y Fisher también visitaron a las monjas; y ellas,
hablándoles a través de una reja,
les preguntaron si ellos eran de la orden de los llamados Cuáqueros,
y al percibir pronto que sí lo eran,
les dijeron que no podían escucharlos y se fueron enseguida.
Edward Burrough también les escribió algunas proposiciones a los Jesuitas,
sacerdotes y frailes,
en las que particularmente describía la tiranía de la iglesia de Roma,
en su verdadera naturaleza;
y estas proposiciones les fueron enviadas en latín.
Ellos permanecieron todavía unos días en el pueblo,
y tuvieron varias reuniones entre los soldados ingleses.
Burrough también les escribió a ellos y les pidió que fueran fieles al Señor,
y que no buscaran sus propios fines, sino el honor de Dios.
También les mostró cuál era su deber en su puesto militar, y les dijo:
"`¿Qué saben ustedes,
si el Señor tiene una buena obra para que hagan si son fieles a Él? Sé,
que la obra del Señor es hacer a los hombres verdaderamente religiosos,`" dijo él,
"`sin embargo, Él puede obrar a través de ustedes para derribar las zarzas y los espinos,
las rocas y collados que se han establecido contra el Señor.`" También les aconsejó,
que si en algún momento una obra así llegaba a ser su suerte, no fueran ambiciosos,
ni vanagloriosos,
sino que se empeñaran en buscar la anulación de la
inquisición católica y de sus crueles leyes.
Y les encargó a los oficiales que no fueran tiranos ni opresores con los soldados pobres,
sino cariñosos y mansos, y ejemplos de toda bondad para con ellos.
Y luego agregó: "`Y así, al no tener pecado sobre sus consciencias,
enfrentarán a sus enemigos con valentía, y no le temerán a la muerte,
sino que estarán dispuestos a ofrecer sus vidas por una buena causa.`"
Pero para que nadie pensara que estaba a favor de portar armas,
sino a favor de ser inofensivos y de no oponer resistencia,
también les dijo que el Señor tenía una obra más honorable, es decir,
destruir el reino del diablo y el terreno de las guerras.
Y que había que buscar una victoria más honorable, a saber, la victoria sobre el pecado, etc.

Burrough y Fisher, una vez enviados a llamar por el gobernador Lockhart,
encontraron a muchos oficiales con él, y después de una amistosa conversación,
ellos les aconsejaron moderación y temor de Dios, y así se separaron.
Y después de haber cumplido su servicio en el pueblo, regresaron a Inglaterra.

No mucho después de esto,
Burrough dio a conocer las mencionadas preguntas en forma impresa,
y también escribió un documento para el Parlamento,
en el que exhortaba a los miembros de esa asamblea
a temer a Dios y a no oprimir a las personas honestas,
sino a liberarlas de la opresión y tiranía;
no fuera a ser que el Señor cayera sobre ellos repentinamente y los hiciera pedazos.

Al encontrarse que el poder del protector Richard Cromwell ya estaba declinando,
fue convencido por los oficiales del ejército a que disolviera este Parlamento,
el cual había comenzado a investigar cómo se empleaban los subsidios;
y por dirección de algunos de los principales republicanos,
el Parlamento Largo fue llamado de nuevo.
Este Parlamento creó un comité de seguridad para
detener a los que perturbaban el orden público,
y para hacer cambios entre los oficiales militares,
ya fuera destituyéndolos o por algún otro medio.
Y a medida que este Parlamento crecía en poder, también erigió un consejo de estado,
y luego se le mandó un mensaje a Richard Cromwell
(quien ya estaba desprovisto de todo poder),
para que desalojara el palacio de Whitehall, lo que finalmente hizo,
ya que el Parlamento le concedió dos mil libras por gastos de mudanza,
y prometió pagar sus deudas contraídas por el público.
Su hermano Henry, que era el representante de Irlanda,
también fue llamado por el Parlamento a que regresara, y así,
estos dos hermanos fueron reducidos de nuevo al estado de ciudadanos particulares.

Entonces E. Burrough le escribió una carta al Parlamento,
y en esta los exhortaba seriamente a desistir de toda persecución por motivo religioso,
y a quitar las leyes que la permitían. Por este tiempo hubo
una insurrección en Cheshire en apoyo al rey Carlos,
bajo el mando de sir George Booth, quien, habiendo recibido una comisión del príncipe,
reunió tal número de seguidores que se apoderó de la ciudad de Chester.
Entretanto,
el Parlamento había mandado a Edmund Ludlow a Irlanda para
que fuera el comandante en jefe del ejército ahí,
en lugar de Henry Cromwell,
y el general Lambert fue enviado con un ejército contra Booth.
Ahora bien,
dado que algunas personas temerarias que se hacían llamar Cuáqueros
estaban a favor de tomar las armas bajo el mando de Lambert,
y hallar que el comité de seguridad ofrecía grandes
posiciones y mandos a algunos de esa persuasión,
para arrastrarlos de la verdad que profesaban,
G+++.+++ Fox escribió un documento en el que mostraba lo ilícito de las guerras y peleas,
presentándolas como una obra que no correspondía en absoluto a los seguidores de Cristo.
Exhortó a sus amigos a que no se unieran con los que tomaban armas,
sino a que pelearan sólo con las armas espirituales,
las que quitarían la razón de todas las armas carnales.
Esto también lo recomendaba en su predicación,
pues él afirmaba y practicaba siempre una vida pacífica e inofensiva.

En cuanto a George Booth, fue derrotado y al tratar de escapar vestido con ropa de mujer,
fue descubierto en una posada y puesto bajo custodia,
y cuando fue llevado a Londres por orden del Parlamento, lo confinaron en la Torre.
Los oficiales del ejército, del que George Fleetwood era ahora comandante en jefe,
estaban muy ocupados tratando de obtener el poder en el Parlamento,
lo que causó una gran división y confusión en la nación, porque era bien sabido,
que si el poder supremo era ofrecido al ejército, ellos podían, entonces,
hacer lo que quisieran, y por tanto, la nación sería gobernada por la espada.
También estaba fresco en la memoria,
que había sido por el ejército que Cromwell había avanzado hasta
convertirse en protector y supremo gobernador de la nación;
y por eso muchos se habían opuesto a esa designación.

Por este tiempo también,
los oficiales militares se inclinaron a eliminar las cargas de los diezmos,
y a establecer otra manutención para los predicadores nacionales.
Pero como no querían que el Parlamento fuera el amo del ejército,
se quejaron de haber sido engañados por el Parlamento,
y el coronel Desborough dijo que el Parlamento no había cumplido
ninguna parte de las promesas que le habían hecho al ejército;
que no se habían preocupado por asegurar la libertad
religiosa para las consciencias tiernas;
y que la intención de ellos era quitar a los principales oficiales,
y colocar a otros en sus mandos que fueran de principios diferentes.

Ahora bien,
el consejo de oficiales militares estaba a favor de convocar a un nuevo Parlamento,
pero esto se topó con una oposición no pequeña. En este ajetreo,
el consejo de oficiales empezó a buscar el favor del clero,
y acordaron con ellos que su manutención por diezmos no sería quitada,
hasta que se impusiera otro ingreso amplio y seguro para ellos.
También acordaron que debían ser tomadas algunas disposiciones
para los que diferían en fe y adoración de la iglesia establecida,
pero que los Cuáqueros y algunos otros, cuyos principios, según ellos,
"`tendían a la destrucción civil de la sociedad,`" no debía ser tolerados del todo.
En este confundido estado,
cuando algunos estaban a favor y otros en contra del Parlamento,
por lo que apenas se sabía en quien residía la autoridad suprema,
Edward Burrough escribió y publicó de manera impresa, un extenso discurso titulado,
"`A message to the present rulers of England, whether committee of safety, so called,
council of officers, or others whatsoever.^
footnote:["`Mensaje a los actuales gobernantes de Inglaterra,
sean del comité de seguridad, así llamado, del consejo de oficiales,
o de cualquier otro.`"]`" Él indicaba a manera de introducción,
que el contenido le había sido encomendado para que lo entregara de palabra y viva voz,
a los hombres que entonces estaban en el poder, pero como no había podido hacerlo,
había escrito lo que tenía.

[.embedded-content-document.letter]
--

[.salutation]
Amigos,

Mi Amo es un alto, fuerte y poderoso príncipe, y muy honorable; y todo temor, reverencia,
respeto y sujeción le pertenecen sólo a Él, de parte de ustedes y de toda la humanidad.
Él es sabio y entendido, y de gran fortaleza,
y Su dominio es desde la eternidad hasta la eternidad.
Él puede hacer todo lo que quiera en el cielo y en la tierra,
porque Él gobierna con Su vara de hierro sobre el mundo, y todo lo que dice, se hace;
porque Su palabra es un mandamiento eterno.
Si Él le dice a un hombre, "`vive,`" así es; si le dice a un hombre, "`muere,`" sucede.
Si Él le da paz a un hombre, o a una nación, nadie puede hacer la guerra;
y si Él hace guerra contra una persona, o contra una nación,
ningún hombre es capaz de hacer la paz.
Porque Él tiene todo el poder en Su mano, y se le ha dado todo el juicio y la autoridad.
Él es el Hijo del Dios vivo, el Creador eterno.
Él era, es y ha de venir.
Su ojo contempla todas las cosas, y Su brazo rodea el cielo y la tierra;
y siempre ha cumplido y cumplirá Su propósito.
Si Él establece gobernantes, ellos deben gobernar;
y si los derriba nadie lo puede impedir.
A quien quiere, honra; y si es Su complacencia, avergüenza a los hombres.
Si derriba a una nación, nadie puede edificarla,
y si confunde poderes y autoridades en los reinos de los hombres,
todos caen como hierba seca delante de Él.

¡Contemplen, ustedes hombres! Él es tan grande y fuerte, y de tan grande autoridad,
que todo lo que dice, se hace; y todo lo que quiere, se cumple;
y nadie puede resistirlo y vencer Su poder, cuando Su voluntad es realizar una obra.
Él es justo y misericordioso, lleno de bondad, justicia y verdad;
toda virtud habita en Él, y Su juicio y Su misericordia, Su autoridad y Su mansedumbre,
Su ira y Su amor, son compañeros.
¿Qué son ustedes delante de Él? O,
¿cómo podrán resistirlo o hacer retroceder Su propósito con respecto a ustedes
y a esta nación? Porque ustedes no tienen ser ni aliento sin Él. ¡Contemplen,
ustedes hombres!
Ciertamente son como el polvo ante el viento, así son para Él;
pronto arrastrados y el lugar de ustedes no se encuentra.
Como la hierba delante del segador, así son delante de Él; pronto cortados y marchitados,
y la belleza de ustedes extinguida por completo.
Como una vasija de alfarero bajo una vara de hierro, así son para Él;
Él puede quebrantarlos de inmediato y nunca ser vendados.
Como una gota de la fuente, así son para Él; pronto secada y hecha nada.

Por tanto, ustedes hombres, ustedes mortales criaturas, ignorantes,
hijos de transgresores, polvo y cenizas--porque así son en comparación con Él,
este poderoso Príncipe--escuchen Su mensaje, que viene de Él para ustedes.
¡Oigan y teman, y no sean obstinados contra el Señor Dios, que está a punto de hablarles!

En cuanto a esta pequeña isla de Inglaterra,
en la que se encuentran el lugar y ser actual de ustedes,
es una isla a la que el Señor le ha mostrado gran
favor en épocas pasadas y en el tiempo presente;
y debo decirles, que Él tiene un propósito de amor hacia ella,
y de honrarla a la vista del mundo, aunque a través de grandes tribulaciones.
Él tiene un propósito de gran bien para ella, porque tiene una Semilla,
una preciosa Semilla esparcida en ella,
tiene un pueblo que le teme a Su nombre y ha caminado en Sus caminos.
Él los ha hecho y los ha elegido, y lo que son, es por Él,
para que Él pueda habitar entre ellos y tener el gobierno completo sobre todos ellos.
Sí, Él tiene un propósito con respecto a esta nación, y Él la va a purificar con juicio,
y va a refinar a sus habitantes a través del fuego de las tribulaciones,
para que ella sea agradable a Él y apta para hacer Su voluntad.
Él tiene el propósito de obrar algo grande en ella, y debo decirles,
tal como Él me ha dicho que lo haga.
Él hará que Su nombre sea exaltado y reverenciado en esta isla,
y Su terror será enviado desde ella a través del mundo,
y Su rama se extenderá por todo la tierra.
Él se propone en Su tiempo,
tomarla en Su propia mano y regir el gobierno de ella con Su propio cetro,
establecer sólo la justicia, y derrocar a todos los opresores y todas las opresiones;
porque los reinos de este mundo deben convertirse en reinos del Señor y de Su Cristo.

Es cierto, que desde hace mucho tiempo, mi Amo ha sido, por decirlo así,
desterrado de la nación, y no se le ha permitido disfrutar Su derecho;
sino que ha sido expulsado, por decirlo de alguna manera,
por la fuerza de Satanás y anticristo,
quien por mucho tiempo ha usurpado la autoridad sobre los habitantes de esta nación,
y en ausencia de mi Amo, se ha ejercido lamentable injusticia, crueldad, inmisericordia,
tiranía y opresión sobre los habitantes;
y las pobres criaturas han sido mantenidas en gran esclavitud por sus gobernantes,
quienes han gobernado por el poder del dragón. Estas
han sido mantenidas por muchos años en gran ceguera,
ignorancia y bajo gran opresión (tanto de cuerpo como de espíritu) por maestros anticristianos,
mientras el gran Rey ha estado ausente, y, por decirlo así, lejos del país. Así, pues,
en todo este tiempo, han gobernado y reinado el anticristo y el diablo,
y han ejecutado opresión, y hecho leyes y decretos tiránicos,
tanto en la iglesia como en el estado;
y toda la nación ha estado fuera del orden correcto,
y yace asolada y estéril de buen fruto.
Los hombres que han gobernado por muchos años,
no han gobernado simplemente por la autoridad de mi Amo, sino por otro poder;
aunque no sin el conocimiento de mi Señor,
ni como si Él no tuviera poder para hacer otra cosa,
pero ha permitido que sea así por Su beneplácito.

Los hombres continúan mandando y gobernando en sus propias voluntades,
y en pos de sus propios deseos;
y el pueblo ha caminado perversamente para con Él y entre sí. Todo esto Él lo ha permitido,
no como si lo aprobara (porque Sus mensajeros y Su
Testigo en las consciencias de las personas,
han estado reprendiendo los caminos impíos del pueblo),
pues menudo ha mostrado Su desagrado, de muchas maneras, con señales,
con muchos juicios y extraños derrocamientos de gobernantes,
profetas y maestros de esta nación,
y aun así han continuado contra Su mente y contra Su voluntad,
a pesar de Sus reprensiones y juicios.
Sin embargo, Él ha sido lento para la ira y ha tenido gran paciencia,
y ha soportado todas las cosas, y ha tomado sobre Sí mismo la injusticia y la crueldad,
la maldad y la idolatría,
y toda la iniquidad que ha abundado en la nación y ha sufrido bajo ello,
y lo ha soportado por un tiempo apropiado,
mientras deplorables y lamentables opresiones han sido practicadas en el estado civil;
es decir, leyes infernales y diabólicos ejecutores de las mismas.
Despiadados tiranos han llevado el cetro y han reinado por muchos años sobre los habitantes,
y en la iglesia y en el estado se han perpetrado atroces idolatrías
y supersticiosas vanidades de alta naturaleza y medida,
desde el príncipe hasta el mendigo, gobernantes y súbditos, maestros y pueblo,
jueces y profetas.
Estos han sido corruptos tanto de corazón como de manos,
y han actuado con falsedad y con impiedad hacia Dios y entre sí; es decir,
para el gran disgusto e irritación de Él y Su bendito Espíritu.
Todo esto mientras Él ha estado como dormido y en descanso en Sí mismo.
Él ha dejado a los hombres para probarlos, para ver qué harían, y les ha dado un día;
ha dejado muchos reyes y gobernantes,
y les ha permitido tener un poco de tiempo para ver cómo lo usarían,
pero han abusado de él y no han gobernado para Él, ni realizado Su obra,
ni cumplido Su voluntad, sino que han actuado incluso en oposición a Él,
a Su poder y para Su gran deshonra.

¡Ay!
Debo ser claro con ustedes: Mi Señor ha sido completamente exiliado,
y enormemente deshonrado,
y altamente provocado e irritado por causa de los procedimientos
que han tenido lugar en esta nación por tantos años,
a través de la corrupción de todo tipo de hombres en posición y poder,
que no han gobernado para Él sino para el diablo, para sus propios fines corruptos.
Sin embargo, Él ha permitido que los hombres sigan su propio curso por un tiempo;
algunos como si aparecieran por un tiempo en escena,
y repentinamente desaparecieran de nuevo por causa de sus iniquidades.
Su mano ha estado en todas estas cosas, aunque muy privada y secretamente,
no conocida ni discernida por los hijos de los hombres; sin embargo,
Él ha gobernado sobre los reinos de los hombres, y ha derribado uno y levantado otro.

Y tal era la crueldad, tiranía, opresión e idolatría,
tanto en la iglesia como en el estado civil,
a la que el pueblo de esta nación estaba sometido en los días del poder católico;
tal era, digo, el sobrepeso de la crueldad y de la tiranía en ese tiempo,
que casi nadie que temiera o reverenciara a mi Señor en alguna medida,
podía vivir o tener un ser en la nación. La boca del infierno estaba abierta contra
todo hombre que se inclinara ante Él y deseara el conocimiento de Sus caminos,
y fueron tragados y muchas de sus vidas arrebatadas de la tierra,
por el poder infernal que en ese día había usurpado la autoridad en esta isla.
Y cuando esto estaba así, Él miró desde el cielo,
y Su corazón se movió con tal compasión por el bien del pueblo oprimido que Lo deseaba,
que quebrantó y derribó el poder de sus opresores en cierta medida,
tal como se mantenía en la autoridad católica,
y cuando la iniquidad de ese poder llegó al colmo, tomó venganza sobre él. Debo decirles,
que fue Él quien lo llevó a cabo, es decir,
que fue Él quien realizó la destrucción de ese poder en esta nación y la liberó de él;
aunque los hombres que fueron instrumentos en la causa no eran más siervos Suyos,
de lo que fue Nabucodonosor.
Porque Él tiene una manera secreta de usar al malvado, y tal es Su poder,
que puede convertir la maldad del impío para Su gloria,
y puede hacer una vara para azotar a sus adversarios y luego quemarla cuando haya terminado,
y a menudo ha destruido una maldad con otra.

Pero dejo eso,
aunque Él liberó a la nación en cierta medida de la mucha
tiranía y crueldad al expulsar la autoridad católica,
¡ay!,
en pocos años la nación estaba casi tan invadida
por la injusticia y crueldad bajo el poder sucesor,
como alguna vez lo había estado bajo el poder católico.
Y aunque había habido una pequeña reforma y cambio en la
apariencia externa (aunque pequeña en terreno y naturaleza),
la opresión, idolatría y superstición en la iglesia y el estado,
y todo tipo de profanación y maldad entre el pueblo, crecieron tan alto,
como habían crecido bajo el poder católico antes.
Y todos los que deseaban seguir al Señor y estaban cansados de la iniquidad,
y de las presentes opresiones e idolatrías, eran perseguidos, asesinados y destruidos.
En realidad, la injusticia y la crueldad eran ejecutadas sobre ellos,
casi hasta el desarraigo de la justicia y aflicción del Espíritu del Señor.

Pero entonces, debido al clamor del pueblo y la opresión de la nación bajo esa autoridad,
mi Señor volvió a mirar hacia abajo, y por amor a Su nombre, y por amor a Su Semilla,
tuvo compasión de esta nación para liberarla y romper sus opresiones.
Y en una gran medida liberó al pueblo de esta nación en muchas cosas,
por lo que se produjo una reforma parcial,
y se pretendía y se esperaba mucho más. Todo esto sucedió a través de Él,
y mi Señor lo cumplió; no obstante, los instrumentos por medio de los cuales obró,
resultaron engañosos y se convirtieron en opresores como los otros antes que ellos.
Y aunque en esta nación hubo un día de grandes dificultades y guerras,
contiendas y grandes luchas,
y el desperdicio de mucha sangre y tesoros terrenales (y ninguna de estas cosas,
debo decirles, cayeron sin la orden de la mano de mi Amo), resultó, sin embargo,
que después de que esta nación fue restaurada a la paz,
y se eliminó mucha injusticia e iniquidad, con todo,
quedó mucho atrás. Y muchos de los hombres que Él
había usado como instrumentos en Su mano,
y en una buena obra, a quienes Él les había dado sabiduría y entendimiento,
y les había aparecido con mucha misericordia y gran liberación,
se desviaron para buscar sus propios intereses,
y se corrompieron con los despojos de sus enemigos.
Y cuando la paz y la plenitud abundaban, el Señor fue olvidado de nuevo,
y entonces la tierra cayó bajo los opresores y comenzó a clamar de nuevo por libertad,
mientras otros cuernos de la primera bestia brotaban y cada uno salía contra su compañero.
Y aunque un cuerno se esforzó por romper otro,
después de que uno fue derribado otro se levantó,
y gobernó y rigió por el mismo espíritu y autoridad derivados del poder del dragón,
en crueldad y opresión; e hicieron leyes y las ejecutaron para deshonra del Señor,
para gran opresión de Su pueblo y llenar esta isla de injusticia y crueldad,
de una generación a otra hasta hoy.

Y así, arriba y abajo, los tiempos y las estaciones han sido alterados;
poderes y autoridades, estatutos, leyes y decretos han sido cambiados;
porque cuando la iniquidad de un poder llegaba al colmo,
ese poder era echado abajo y otro tenía su día,
hasta que la medida de iniquidad de ese también fuera colmada,
para que participara de los mismos juicios.
Y la propia mano de mi Señor ha estado presente en todos estos derrocamientos,
abatimientos y derrumbamientos, aunque en secreto y sin ser discernida.
Sin embargo, Su poder ha ocasionado y permitido que todas estas cosas sucedan;
¿y quién Lo acusará de injusticia?
O quién Le dirá, "`¿qué has hecho?`"
O, "`¿por qué lo has hecho?`"
Porque como he dicho, Él es un príncipe alto y poderoso, y puede hacer todo lo que quiera.
Él es el poder y la autoridad supremos,
que gobierna y reina en y sobre todos los reinos de los hombres.
¿Y qué,
si Él ha creído conveniente usar a hombres impíos
como instrumentos para realizar Su obra,
y ha hecho de los impíos Su vara para que una maldad destruya otra,
y un opresor abata a otro, y el reino del anticristo se confunda?
Toda carne debe estar en silencio delante de Él,
y todo pueblo y la tierra entera deben estar sujetos a Él;
porque el gobierno y el dominio sobre el cielo y la tierra son Suyos,
y todo poder y dominio le pertenecen sólo a Él. Todo juicio está en Su mano,
para llevar a cabo lo que Él quiera y por quien quiera, según le plazca.

Pero ahora, mis amigos, aunque deseo no ser tedioso para ustedes,
debo decirles la verdad,
y entregarles fielmente el mensaje del Señor. En cuanto a este último derrocamiento,
hubo algo de la mano de mi Señor en él; y Él puede llevar a cabo,
y llevará a cabo Su propia obra y alabanza por medio de este,
y será para el bien de todo Su pueblo que espera en Él,
aunque haya habido mucha ambición y corrupción en los instrumentos,
y ninguna de las partes haya sido perfectamente pura para el Señor en sus procedimientos,
ya que la obra de ellas estuvo manchada con el espíritu falso e idólatra del egoísmo.
Sin embargo, el Señor es capaz de hacer surgir Su gobierno y Su planta deliciosa,
a través y más allá de todo esto, incluso a partir de otra raíz,
que todavía no aparece entre ninguno de ellos;
y la justicia puede levantarse en la nación, contraria a ambos, a partir de otro tallo;
porque Él establecerá Su reino,
y en el ínterin dejará un tiesto de la tierra para quebrantar otro.

En cuanto a ustedes que hoy se sientan sobre el trono y gobiernan, ¡ay!,
ustedes no son más que otro cuerno de aquella cuarta bestia,
que ha sido hecha para gobernar sobre el mundo y sobre la tierra por muchas generaciones,
y aunque son un poco más refinados que los últimos, son de los últimos,
de la misma manera que la octava era de las siete,
como se menciona en Apocalipsis 17:11. Este, el actual gobierno de ustedes,
está leudado con el espíritu del antiguo dragón que
ha matado a los santos y bebido su sangre,
¿por qué razón establecería el Señor este gobierno?
No, el reinado de ustedes resultará pequeño y poco,
y estará lleno de alborotos y dificultades, y habrá poca paz,
satisfacción y establecimiento en él para ustedes o para el pueblo bajo ustedes;
todo lo contrario, la confusión lo acompañará y los temores lo rodearán.

Aunque debo decirles esto, ya que son hombres,
ustedes tienen su propio día de prueba en cuanto a lo que harán,
como muchos otros la han tenido antes.
Y hay algo que pueden y deben hacer,
porque tienen un talento puesto en sus manos que pueden incrementar,
para la honra del Señor, para el bien de la nación y para sus propias felicidades.
Si son fieles al Señor para hacer lo que Él requiere de ustedes,
si se vuelven hombres mansos y humildes, temen Su nombre, se niegan a sí mismos,
no buscan su propia honra, ni ninguna ventaja terrenal para sí mismos; digo,
que si hacen esto, entonces el Señor les mostrará misericordia,
y no caerán repentinamente delante de sus enemigos,
aunque muchos se levanten contra ustedes.
Si caminan de esta manera y gobiernan sólo para el Señor,
entonces serán honrados como hombres (por no decir como autoridad),
y ustedes y la nación serán preservados en paz,
la fuerza del impío se volverá atrás y no caerán repentinamente.
Dejen que los varios derrocamientos en esta nación sean ejemplos para ustedes,
para que no sigan los pasos de aquellos que Dios ha expulsado,
no sea que lleguen al mismo final de confusión y miseria.
Porque, con respecto a esa asamblea de hombres que previamente se sentó sobre el trono,
en algunas cosas le sirvió a mi Señor y fue una vara en Su mano para herir a Sus enemigos;
sin embargo, ellos no se mantuvieron fieles hasta el fin,
hasta que todos Sus enemigos fueran destruidos,
sino que se unieron para pelear contra el Señor y Su pueblo,
y se apresuraron en el camino de opresión y persecución. Y entonces,
llegó el momento de que el Señor los quitara,
y los pusiera a un lado como una vasija vacía, que antes había sido útil;
y de quebrarlos como una vara, que antes había servido como azote sobre Sus enemigos.
Y cuando el día de prueba terminó, el que Dios les había dado,
al no ser más instrumentos idóneos en Su mano, los echó en el fuego;
porque habían entrado en el mismo espíritu de maldad, opresión y persecución,
que el Señor había reprendido una vez a través de ellos y sacado por medio de ellos.

Y aunque algunos de ustedes, actuales gobernantes,
sean considerados grandes traidores y tiranos en sus tratos hacia ellos,
y sin ninguna duda los hombres de ese grupo buscarán vengarse contra ustedes,
mediante su predicación y oración,
y los maldecirán en el nombre del Dios de ellos y
buscarán continuamente la destrucción de ustedes,
al considerar que les han quitado parte de su fuerza y echado abajo sus ídolos; con todo,
¡ay!, todo esto es nada, porque el Señor no cuenta como lo hacen los hombres.
Porque estas cosas deben suceder necesariamente para
el progreso del reino y gobierno de Jesucristo,
para que este brote y se levante a través de todo.
Y si son fieles a lo que el Señor requiere de ustedes en sus procedimientos,
entonces lo que ustedes les hayan hecho a ellos no será contado contra ustedes,
ni por Dios, ni por hombres buenos.
Pero si ustedes, los del ejército, continúan siendo traidores y desobedientes a Él,
abusando de su poder, descuidando el talento que Dios les ha dado,
desperdiciando su tiempo en posiciones de honor, y en tales asuntos egoístas;
y la causa de Dios es descuidada por ustedes y Su pueblo continuamente
oprimido bajo ustedes (como lo ha sido durante mucho tiempo),
entonces serán desechados con vergonzosa deshonra,
y la pesada mano del Señor estará sobre ustedes en juicio,
y serán heridos más que cualquiera antes de ustedes.
Sus propiedades no se librarán del saqueador, ni sus almas del pozo,
ni sus personas de la violencia de los hombres, no, ni sus cuellos del hacha.
Porque si son infieles y continuamente traidores a la causa de Dios,
entonces serán abandonados a la voluntad de sus enemigos,
ellos los acusarán de traición y deslealtad,
y sus personas y propiedades serán dadas por presa a sus enemigos.
Ustedes no se liberarán a sí mismos,
ni el Señor los librará de la ejecución de hombres despiadados,
porque mi Señor dejará que los crueles de corazón contiendan contra ustedes.

Por tanto, para que estén advertidos, les aconsejo que sean fieles;
no dejen caer la causa de Dios,
ni que la causa de sus enemigos prospere delante de ustedes;
porque no hay otra manera por la que puedan ser preservados,
ni van a encontrar ninguna otra defensa de la ira del Señor,
ni de la furia de sus enemigos devoradores,
más que la fidelidad de ustedes en la causa de Dios.
Por tanto, alivien al oprimido y quiten todas las opresiones,
destruyan todas las leyes injustas y liberen a todas las personas de las cargas injustas;
y acaben toda opresión, tanto en la iglesia como en el estado civil.
En cuanto a las leyes opresivas, a los jueces injustos y a los hombres malos en el poder,
que todos sean quitados,
y que la nación sea limpiada y liberada de todos
los hombres y leyes que han mantenido a personas,
propiedades y consciencias de gente buena bajo opresión. Esto es lo que mi Señor,
el gran Rey, requiere de ustedes, y Él hará que suceda repentinamente en la nación,
si no por ustedes, entonces contra ustedes, y para la completa destrucción de ustedes.

Esta es la sustancia misma de mi mensaje para ustedes,
el que mi Amo me ha dado para que se los diga.
He venido en Su nombre a reclamar de ustedes el derecho
de mi Amo hace mucho tiempo perdido.
Dejen que Él tenga Su derecho, del que ha sido desterrado hace mucho tiempo.
Él lo demanda de ustedes, de todos los que parecen llevar el gobierno de la nación;
les encargo en Su nombre que dejen que Él tenga Su título y prerrogativa.
Dejen que Él sea el total Señor y Rey en Su propio reino.
Dejen que Él ejercite las consciencias de Su pueblo por medio de Su propio Espíritu,
en todas las cosas relacionadas con Su adoración y servicio.
Dejen que tenga completa autoridad por medio de Su Espíritu,
en todas las cosas que pertenecen a la iglesia, ministerio, fe y religión;
y dejen que Su Espíritu sea la única autoridad para persuadir
y disuadir a las personas de tal o cual ministerio,
adoración y práctica de religión. Eliminen rápidamente
toda manutención obligatoria a los ministros,
y los diezmos;
y que todas las leyes y decretos que fueron hechas y practicadas
en los días del anticristo (sobre los cuerpos,
propiedades y consciencias de las personas, en opresión e injusticia),
que tengan que ver con la iglesia,
adoración y religión sean completamente revocadas y anuladas,
y nunca más puestas en vigor en esta nación.

Más bien, dejen que mi Señor sea el único gobernante y gobernador,
y que tenga la total autoridad en Su propio reino,
y en todas las cosas relacionadas con este.
Porque a Él le corresponde ser el único juez y tener completo poder en Su propio reino;
porque hasta que Le den el derecho, Le entreguen Su propio reino,
y la instrucción de las consciencias de las personas
en todas las cosas relacionadas con religión,
nunca prosperarán; ni lo hará ninguno que venga después de ustedes,
que en alguna medida limite a mi Amo en Su propio derecho,
del que ha sido desterrado durante mucho tiempo.
Y hasta que se le dé Su derecho, como ha sido dicho, Él arrojará a un impío contra otro,
y ninguno será jamás establecido; sino que un cuerno tras otro cuerno será roto,
y un poder tras otro poder será llevado a confusión.

Por tanto, ustedes hombres, no luchen contra Él en este asunto,
sino cédanle la instrucción de sus propias consciencias
por medio de Su Espíritu en ustedes,
y dejen que Lo haga con todos los demás, tal como esperan que prospere en ustedes mismos.
Dejen que los hombres justos, que los hombres rectos,
que los hombres mansos y que los hombres que tienen el temor
y la sabiduría de Dios en ellos (sin acepción por nacimiento,
o de otra manera), ejecuten el poder y el juicio que se les encomiende,
para determinar en las cosas entre hombre y hombre.
Acaben con todos los aduladores de falso corazón, con todos los que juzgan por recompensa.
Saquen a todos los gobernantes asalariados,
quienes ejecutan la ley por dinero y no defienden
la causa del pobre sin cobrar grandes honorarios.
Acaben con todos los que no sirven en sus puestos de confianza a cambio de grandes sueldos.
Saquen todas estas cosas de la tierra,
porque ellas son terribles opresiones para los hombres
y grandes abominaciones ante los ojos de Dios.
Porque el propósito del Señor es de una forma u otra,
limpiar la tierra de todas estas y otras opresiones,
para que el pueblo de esta tierra sea un pueblo libre
de todos los pesados yugos del anticristo,
con los que por mucho tiempo ha sido oprimidos.

Considerando que hay un gran clamor acerca del ministerio,
acerca de enviar y mantener ministros,
y acerca del fomento de un ministerio piadoso (como dicen ustedes),
esto responderé en nombre de mi Señor. Debo decirles claramente,
en cuanto a un verdadero ministerio piadoso, verdaderamente llamado y enviado por Dios,
que tal ministerio y tales ministros no podrán ser obstaculizados por ustedes;
sino que el Señor los enviará, manteniéndolos y preservándolos, lo deseen ustedes o no.
Mientras se meten en este asunto,
no hacen más que entrometerse en cosas por encima de la línea de ustedes,
y fuera de la jurisdicción de ustedes; porque pertenece a Su gobierno enviar ministros,
a quienes Él desee, mantenerlos y defenderlos según Su propia voluntad,
y todo esto sin ustedes.
Porque tales ministros,
que son verdaderamente llamados para ello y enviados por el Señor,
no vendrán a ustedes para ser enviados, o para ser mantenidos por ustedes; sino que,
sin ustedes y contra ustedes, serán enviados y mantenidos.
Así el Señor tendrá un ministerio en esta nación puramente Suyo, no del hombre,
ni por el hombre, y ustedes no podrán obstaculizar tal ministerio.

Debo decirles claramente, en cuanto a estos hombres llamados ministros en esta nación,
que por la forma en que son establecidos y enviados, por la manera que son mantenidos,
por la manera en que defienden su puesto, y todos los papeles particulares de este,
ellos son ahora la más grande y más lamentable opresión en esta nación. En verdad,
las más abominables e injustas crueldades y tiranías son perpetradas por ellos,
y son (como se dijo antes),
la lamentable causa de los gemidos de la nación bajo un trato inmisericorde.
¿Qué les diré de ellos?
La tierra es oprimida por ellos, los habitantes gimen bajo ellos,
el Dios justo es agraviado por ellos,
y ellos y todas sus prácticas (como tales) son el combustible de Su enojo,
para ser consumidos por el fuego de Su celo.
La nación está cansada, junto con sus habitantes,
y el Señor está cansado por causa de estos hombres.
¿Es este el ministerio que ustedes consideran santo y piadoso?
¿Son estos los hombres que la nación está obligada a mantener en
su orgullo e idolatría? ¿Es este el ministerio que debe ser alentado?
Pues bien,
si estos son los hombres y este es el ministerio
que debe ser establecido y alentado por ustedes,
al hacerlo nunca prosperarán, sino que se ganarán el desagrado del Todopoderoso.
Porque debo decirles que la mano de mi Señor está contra ellos,
y cualquiera que intente defenderlos, no prosperará en sus obras, porque las opresiones,
crueldades, engaños y abominaciones de ellos, han llegado a su final y cumplimiento.
Por tanto, miren por ustedes mismos, porque este es el consejo de mi Amo para ustedes;
no toquen este ministerio y no se unan a Baal, no sea que perezcan.

Por último, debo decirles, que mi Amo tiene un pueblo en esta nación,
un pueblo sufriente, que ha soportado la carga de crueldad, injusticia y perversidad,
que tanto gobernantes como maestros le han infringido,
quienes (por decirlo así) lo han pisoteado y hecho presa de sus bocas devoradoras.
El clamor mismo de sus sufrimientos ha alcanzado el cielo,
el sonido del cual ustedes han oído. En verdad, este pueblo es muy amado,
y mi Señor ciertamente lo honrará,
y Su mano continuará preservándolo y defendiéndolo contra todos sus enemigos.
Porque Él lo reserva para Sí mismo para una gloriosa
obra que tiene que hacer por medio de ellos.
Él los ha formado para Sí mismo,
y ellos no pueden unirse con ninguno de los cuernos de la gran bestia,
ni ningún lugar de honor puede pervertirlos de su perfecto camino.
Mi Señor los rodea por todos lados, y los ha guardado en medio de las pruebas,
acusaciones y sufrimientos, y los ha cubierto en el calor y en la tormenta,
hasta que Le plazca hacer más uso de ellos.
Ellos son de Él y no de sí mismos; y deben cumplir Su voluntad y no otra.
Ellos verdaderamente reposan en Él,
incluso mientras las montañas son derribadas y mientras
un tiesto de la tierra rompe otro;
esto debe ser hasta el tiempo señalado.
Por tanto, oh, hombres, no los toquen, ni los aflijan, si esperan prosperar.
Recuerden la causa de ellos y no permitan que sea siempre rechazada,
como ha sucedido durante mucho tiempo,
sino manténgase libres de la injusticia y crueldad de los que los han precedido,
quienes fueron opresores despiadados de este pueblo,
hasta que mi Señor los desconcertó y llevó a confusión.

Así les he entregado el presente mensaje del Señor, el cual recibí de Él,
y de este modo estoy limpio delante de Dios; ya sea que lo acepten o lo rechacen,
mi paz y recompensa están para siempre con Él. Yo sigo siendo
un súbdito de Su reino y un amigo de esta nación,
aunque los hombres ignorantes me juzguen de otra manera.

[.signed-section-signature]
Edward Burrough

[.signed-section-context-close]
El mes Nueve, 1659

--

Ahora, cuánto tiempo después se cumplieron estos dichos de Burrough,
"`Sus propiedades no se librarán del saqueador, ni sus cuellos del hacha;
sus enemigos los acusarán de traición,
y si intentan detener la obra del Señor no estorbarán
la tierra por mucho tiempo,`" lo veremos en breve.

Por esta época Burrough también les escribió varios epístolas a sus amigos,
en las que los exhortaba tan poderosamente a la fidelidad y perseverancia,
que se procuró un nombre que nunca moriría, al vivir en la memoria de miles,
aunque hace mucho tiempo se fue del camino de toda carne,
habiendo entregado su vida en prisiones por el testimonio de Jesús,
como se dirá en su debido lugar.

También tengo un trozo de una carta escrita por este tiempo a los Monárquicos,^
footnote:[Partidarios del regreso de Carlos Estuardo a la corona.]
de la que no puedo decir si fue hecha por E. Burrough, o por George Fox el joven,
o por George Bishop; pero dice así:

[.embedded-content-document.letter]
--

El espíritu de orgullo, opresión e idolatría ha entrado en ellos (es decir,
en sus enemigos),
y ahora vive en ellos en tan alta medida como nunca vivió entre ustedes.
Las iniquidades de ellos están a punto de terminar,
y el Señor de una forma u otra los corregirá y reprenderá;
y serán tratados de la misma manera que ellos usaron para tratarlos a ustedes;
porque ellos no fueron más que una vara en la mano del Señor por un tiempo,
y deben ser quebrados y echados al fuego también. Y si el
Señor hace uso de ustedes alguna vez para reprenderlos,
como hizo con ellos para reprenderlos a ustedes, eso no lo determino,
sino que se lo dejo Al que puede hacer lo que quiera, por el instrumento que le plazca.
Es cierto que ustedes han hecho varios intentos de vengarse de ellos,
pero hasta ahora no han prosperado;
pero si se dejaran humillar y entraran en el manso Espíritu del Señor,
entonces prosperarían. Hasta ahora el Señor los ha derrotado y los ha inclinado siempre,
bajo un pueblo tan indigno como otros; pero el tiempo de ellos llegará a su fin.
Sométanse, por tanto,
a la voluntad del Señor en lo que ha sucedido y no busquen vengarse,
y entonces el Señor vengará la causa de ustedes;
porque las iniquidades de sus adversarios están maduras.
Carlos Estuardo debe convertirse al Señor y ser gobernado por Él, o de lo contrario,
nunca podrá gobernar correctamente para Dios en esta nación. Aunque creo,
que no es imposible que él sólo sea una vara para
golpear a los que una vez lo golpearon a él,
para que las opresiones y ambiciones de esos reciban un freno a través de él.

--

Entre varios otros predicadores notables,
Stephen Crisp también se había convertido en un ministro público de la palabra de Dios,
y por esta época fue a Escocia a predicar el evangelio
y a edificar las iglesias con su don.

Este año,
G+++.+++ Fox el menor escribió una exhortación a los oficiales militares y al ejército,
mostrándoles cómo se había separado de su primera integridad y caído en orgullo y desenfreno.

G+++.+++ Fox el mayor, estaba en Norwich aproximadamente en el mes Décimo,
donde se había fijado una reunión. Cuando el alcalde recibió la noticia,
intentó emitir una orden de arresto contra él, pero al enterarse,
envió a algunos de sus amigos al alcalde para que hablaran con él al respecto.
Su respuesta fue, que temía que una reunión de ese tipo causara un tumulto en el pueblo,
pero al hablársele de manera amable, se comportó moderadamente,
y se celebró una gran reunión pacífica; a la que entre otros,
también llegaron varios sacerdotes, y entre ellos estaba un tal Townsend,
quien se puso de pie y gritó: "`¡Error, blasfemia!`" etc.
G+++.+++ Fox quería que él no se cargara con lo que no podía probar,
pero él afirmaba que era un error y una blasfemia que G. Fox dijera
que las personas debían esperar en Dios mediante Su poder y Espíritu,
y sentir Su presencia cuando no hablaban palabras.
Ante esto,
G+++.+++ Fox le preguntó si los apóstoles y los hombres santos
de Dios no habían oído a Dios hablarles en silencio,
antes de que ellos hablaran la Escritura y antes de que fueran escritas.
Él respondió:
"`Sí,`" y lo confirmó al decir claramente que David y los profetas lo habían hecho.
Entonces G. Fox les mostró a las personas cuán absurdo era
que Townsend llamara a tal práctica error y blasfemia.
Esto desconcertó tanto a Townsend que dijo: "`Oh,
este no es el George Fox con el que quería hablar; sino que este es un hombre astuto.`"
Ahora bien,
cuando algunos de la audiencia llamaron al sacerdote y le pidieron que
probara la blasfemia y el error con los que había acusado a G. Fox,
él se fue; y después de que George Whitehead y Richard Hubberthorn hablaron con él,
quienes también estaban en Norwich, pronto quedó confundido y humillado.

Estando el comité de seguridad en el poder,
Edmund Ludlow continuó instando la restauración del Parlamento; y el general Monk,
que comandaba el ejército en Escocia y pretendía la restauración del rey,
le escribió al presidente de la cámara, William Lenthal,
diciéndole que él actuaría a favor del Parlamento; y así fue restaurado.

G+++.+++ Fox el menor, escribió una carta a este Parlamento,
en la que les decía que el día de ellos se había convertido en tinieblas,
y que el sol se había puesto sobre ellos; sí,
que el decreto había salido y había sido sellado contra ellos, y no podía ser revocado,
junto con muchas otras expresiones notables.
Él le había escrito en otros momento al ejército y al Parlamento,
como también lo había hecho Richard Hubberthorn,
lo cual paso por alto para evitar palabrería.

Ahora, echemos de nuevo un vistazo a la persecución en Nueva Inglaterra.
Ya he hecho mención de Lawrence y Cassandra Southwick, y su hijo Josiah,
de quien se hablará más después; pero primero hablaré de Daniel y Provided,
hijo e hija de los mencionados Lawrence y Cassandra.
Estos niños,
al ver cuán irrazonablemente habían sido tratados sus honestos padres y su hermano,
estaban tan lejos de ser disuadidos por eso,
que más bien se sintieron animados a seguir sus pasos,
y no frecuentar las asambleas de una generación tan perseguidora.
Por la ausencia de ellos a dichas asambleas fueron multados con diez libras,
aunque era bien sabido que ellos no tenían patrimonio,
pues sus padres ya habían sido llevados a la pobreza por sus rapaces perseguidores.
Para obtener este dinero, fue emitida la siguiente orden en el Tribunal General de Boston.

[.embedded-content-document.legal]
--

En vista de que Daniel Southwick y Provided Southwick, hijo e hija de Lawrence Southwick,
se ausentaron de las ordenanzas públicas,
han sido multados por los tribunales de Salem y Ipswich;
y al pretender que no tienen patrimonio y resolver no trabajar, la corte,
tras una revisión cuidadosa de una ley que fue hecha acerca de la cuenta por deudas,
en respuesta a lo que debe hacerse para el pago de multas,
resuelve que los tesoreros de varios condados están, y estarán,
plenamente autorizados a vender a las mencionadas personas
a cualquiera de la nación inglesa en Virginia o Barbados,
para responder a dichas multas, etc.

[.signed-section-signature]
Edward Rawson, Secretario

--

El tema de esta orden fue respondido eficaz y ampliamente
de manera impresa por George Bishop,
quien demostró muy claramente lo irrazonable de esta obra a partir del escrito sagrado.
Como en Amos 2:6,
donde se declaran los juicios de Dios contra los que vendían al justo por plata,
y al pobre por un par de zapatos.
De Levítico 25:42, donde se prohíbe expresamente hacer esclavos a los hijos de Israel;
que esto no era lícito, excepto en caso de robo,
si el ladrón no tenía con que hacer satisfacción. Pero regresando a Daniel y Provided,
no quedaba nada sino la ejecución de dicha orden contra ellos.
Por tanto, Edmund Butter, uno de los tesoreros, para obtener algo del botín,
buscó un pasaje para enviarlos a Barbados y venderlos,
pero nadie estaba dispuesto a tomarlos o llevarlos; y cierto capitán de un barco,
para desanimar el asunto, pretendió que ellos arruinarían todo la compañía del barco.
Butter respondió a esto: "`No, no deben temer eso,
porque ellos son pobres criaturas inofensivas, que no le harán daño a nadie.`"
"`¿No lo harán?,`" replicó el capitán del barco, "`¿y sin embargo,
te ofreces hacer esclavos a tales criaturas inofensivas?`"
Y así, Edmund Butter,
viendo que el invierno estaba cerca (a pesar de sus perversas intenciones),
los mandó a la casa de nuevo para que se valieran por sí mismos,
hasta que pudiera encontrar una oportunidad conveniente para mandarlos.

Este año también sucedió, que una niña de unos once años, llamada Patience Scot,
cuya madre religiosa había sido cruelmente azotada por esta gente,
dio testimonio contra su malvada persecución;
lo que indignó tanto a los perseguidores que la enviaron
a prisión. Pero al ser interrogada por los magistrados,
la niña habló tan bien al respecto que confundió a sus enemigos;
algunos de los cuales declararon que ellos tenían muchos niños que había sido bien educados,
pero que "`sería bueno que ellos pudieran decir a favor de Dios,
la mitad de lo que ella pudo decir a favor del diablo.`"
Pero esta niña, al no tener la edad para ofender la ley, por muy malvados que fueran,
parece que no pudieron decidirse a proceder al destierro, como habían hecho con otros.

Todo lo que he dicho hasta el momento de la persecución en Nueva Inglaterra,
no es más que superficial,
y sólo una parte muy pequeña de los múltiples azotes que fueron infligidos ahí;
además de las extorsiones por multas, que eran tan exorbitantes,
como puede verse por lo que se le hizo a William Maston, en Hampton.
Este hombre fue multado con diez libras por dos libros que se encontraron en su casa,
cinco libras por no asistir a la iglesia de ellos, y tres libras adicionales,
que supuestamente le debía al sacerdote;
pero al no tener libertad de consciencia para pagar la multa,
le quitaron una suma que ascendía a más de veinte libras.
También encuentro, que no mucho después de este tiempo,
a algunos les fueron exigidas más de mil libras,
sólo porque se habían separado de la iglesia perseguidora.
Parece que a estos también los excluyeron de la protección de la ley, a tal punto,
que Thomas Prince, gobernador de Plymouth, no dudó en decir que, en su consciencia,
los Cuáqueros eran un pueblo que merecía ser destruido sin piedad o misericordia; ellos,
sus esposas y niños, sus casas y tierras.
También encuentro, que un tal Humphrey Norton de New Haven, por ser Cuáquero,
fue azotado severamente y quemado en la mano con la letra H, que significa hereje.

Esta crueldad que hicieron los ingleses también incitó a los holandeses a la persecución;
porque sin investigar qué tipo de pueblo eran los Cuáqueros,
parecían dispuestos a concluir que eran hombres de opiniones perniciosas,
ya que los líderes de su propia nación,
que pretendían mayor pureza que los otros Protestantes, los perseguían muy severamente.

Sucedió que un tal Robert Hodshone, estando en la plantación holandesa en Hamstead,
tuvo una reunión con algunos de sus amigos que eran ingleses y que vivían ahí;
pero mientras iba caminando en la huerta, llegó un oficial y lo cogió,
y lo llevó delante de un tal Gildersleve, un inglés y magistrado ahí,
quien lo envió a prisión,
y luego cabalgó hasta el gobernador holandés para ponerlo al corriente.
Al regresar con una guardia de mosqueteros,
el fiscal registró al prisionero y le quitó su cuchillo, papeles y una biblia,
y luego lo ató y mantuvo así toda esa noche y el día siguiente.
E indagando para encontrar a los que lo habían hospedado,
tomó bajo custodia a dos mujeres en esa ocasión,
una de las cuales tenía dos niños pequeños y la otra todavía estaba amamantando.
Luego consiguieron una carreta y se llevaron a las mujeres en ella,
y a Robert lo ataron a la parte trasera de la carreta,
y lo arrastraron a través de los bosques durante la noche,
por lo que quedó muy desgarrado y muy lastimado.
Cuando llegaron a New Amsterdam (hoy New York) lo soltaron,
y con la cuerda con la que había estado atado a la carreta, lo condujeron al calabozo,
un lugar asqueroso y lleno de alimañas; y a las dos mujeres las llevaron a otro lugar.
Un tiempo después de esto lo interrogaron,
donde un tal capitán Willet de Plymouth incitó mucho al gobernador contra él,
quien antes había sido un hombre moderado.
Al final, se le leyó a Robert la sentencia en holandés,
en la que se le obligaba a trabajar dos años con una carretilla con un negro, o pagar,
o hacer que se pagaran, seiscientos florines.
Ante esto él intentó presentar su defensa de manera sobria,
pero no se le permitió hablar, y fue mandado al calabozo de nuevo,
donde no se le permitió a ningún inglés visitarlo.
Al cabo de unos días lo sacaron y lo ataron,
y puesto de cara a la sala del tribunal le quitaron
el sombrero y le leyeron otra sentencia en holandés,
la cual no entendió,
pero se vio que disgustó a muchos de esa nación por el movimiento de sus cabezas.
Luego fue arrojado de nuevo en el calabozo, donde permaneció algunos días.

Finalmente, temprano en la mañana,
lo sacaron a rastrar y lo encadenaron a una carretilla, y le ordenaron trabajar;
a lo que él respondió,
que él no había sido educado ni estaba acostumbrado a ese tipo de trabajo.
Ante lo cual,
hicieron que un negro tomara una soga llena de brea de unos diez centímetros de grosor,
y lo golpeara hasta que Robert cayera al suelo.
Luego,
lo levantaron de nuevo e hicieron que el negro lo golpeara con la mencionada cuerda,
hasta que cayera por segunda vez; y se cree que recibió unos cien golpes.
Así lo mantuvieron todo ese día en el calor del sol, encadenado a la carretilla,
con su cuerpo muy herido e hinchado por los golpes.
Pero aunque no le dieron comida y se desmayó varias veces,
él estaba sentado en el suelo con su mente retirada en el Señor y entregado a Su voluntad,
por lo que se sintió sostenido.
En la noche fue encerrado de nuevo en el calabozo,
y a la mañana siguiente fue encadenado de nuevo a la carretilla,
y le pusieron un centinela para que nadie pudiera hablar con él.
El tercer día fue sacado y encadenado de la misma manera;
y no es de extrañar que él aún se negara a trabajar,
porque además de lo irrazonable de exigirle un trabajo tan
servil a un hombre que no había cometido ningún mal,
él no estaba en condiciones de ejecutarlo,
ya que estaba completamente incapacitado por los crueles golpes que le habían dado.
En este débil estado fue llevado ante el gobernador quien le ordenó trabajar,
"`de lo contrario,`" dijo él,
"`serás azotados todos los días.`" Robert le preguntó qué ley había quebrantado él,
y pidió que se presentaran sus acusadores para poder conocer
su transgresión. Pero en lugar de recibir una respuesta,
fue encadenado de nuevo a la carretilla,
y amenazado con recibir un castigo peor si le hablaba a alguien.
Sin embargo, él no se abstuvo de hablar con algunos de los que se le acercaban,
según lo consideraba oportuno y pensaba que era conveniente.
Luego, viendo que no podían hacerlo callar,
lo metieron de nuevo en el calabozo y lo dejaron encerrado tres días y tres noches;
un día y medio sin pan y agua.

Después de esto, una mañana muy temprano fue llevado a un cuarto privado,
donde lo desnudaron hasta la cintura, lo colgaron de sus manos,
y le ataron un gran tronco de madera a sus pies para que no pudiera girar su cuerpo.
Luego hicieron que un negro fuerte lo azotara con unas varas,
y este le descargó numerosos azotes que le desgarraron sobremanera la carne.
Luego lo bajaron y lo pusieron en el calabozo como antes,
y no se le permitió a nadie que lo visitara.
Dos días después de esto, fue llevado de nuevo y colgado como antes,
y otro negro le descargó más azotes.
Casi desmayado y sin saber si le quitarían la vida,
pidió que se le permitieran a algún inglés visitarlo, lo cual fue concedido,
y una mujer inglesa llegó y lavó sus heridas,
y lo encontró tan abatido que pensó que no viviría hasta la mañana siguiente.
Al contarle esto a su esposo, le causó tal impresión,
que fue a ver al fiscal y le ofreció un buey gordo a cambio de que le
permitiera a Robert quedarse en su casa hasta que estuviera bien de nuevo.
Pero el fiscal no le permitía salir a menos que se pagara toda la multa.
Y aunque allí había algunos que de buena gana habrían pagado la multa por él,
él no podía consentirlo.
Pero al cabo de tres días, después de que había sido azotado de esa manera,
se recuperó tan fuerte como antes,
y se sintió libre de trabajar para no ser una carga para nadie.

Algunos otros de los llamados Cuáqueros,
que habían llegado desde las plantaciones de Nueva Inglaterra para disfrutar libertad
de consciencia (y cuyos nombres y sufrimientos paso por alto en aras de la brevedad),
también se toparon con duras medidas por parte del gobernador,
por la instigación del mencionado capitán Willet.
El hecho de que se mantuviera a Robert como un esclavo para que trabajara duro,
suscitó la compasión de muchos, y la hermana del gobernador,
que estaba mucho más afectada por sus sufrimientos,
se convirtió en un instrumento decisivo para obtener su libertad,
porque ella instó tanto a su hermano,
que él finalmente lo dejó libre sin pagar un penique,
o sin que nadie más pagara por él. Con esto el gobernador demostró que,
aunque él había sido forzado con demasiada facilidad a cometer el mal,
aún no había llegado a la misma altura de maldad que los perseguidores de Nueva Inglaterra.
Porque estos crecieron en su dureza de corazón y se acostumbraron tanto a la crueldad,
que si alguno de ellos no daba su voto para la persecución,
era considerado indigno de ser magistrado;
como aparece en una carta de un tal James Cudworth,
escrita algún tiempo antes a uno de sus amigos en la Vieja Inglaterra,
en la que me encuentro con estas palabras:

[.embedded-content-document.letter]
--

En cuanto al estado y condición de las cosas entre nosotros, es triste.
El espíritu perseguidor anticristiano está muy activo,
y se mueve en los poderes de este mundo.
El que no azota, persigue y castiga a los hombres que difieren en asuntos de religión,
no puede sentarse en el tribunal, ni ocupar ningún cargo en la mancomunidad.
En la última elección, Mr. Hatherly y yo dejamos el tribunal,
y yo fui destituido de la capitanía porque había
hospedado a algunos Cuáqueros en mi casa,
para poder estar mejor informado de sus principios.
Pensé que era mejor hacerlo así, que censurarlos, condenarlos,
reprocharlos e injuriarlos con el mundo ciego, cuando ellos ni veían sus personas,
ni sabía algo de sus principios.
Pero los Cuáqueros y yo no podemos coincidir en varias cosas;
y en la corte indiqué que yo no era Cuáquero, y que cuando tuviera ocasión y oportunidad,
daría mi testimonio contra diversas cosas que ellos sostienen.
Sin embargo, les dije que aunque no era Cuáquero, nunca sería un perseguidor.

--

Ahora entraré en la narración de las muertes de algunos, que murieron como mártires;
porque aún faltaba esto para completar esta tragedia,
que parece que no podía ser hecha a satisfacción de los actores,
sin interpretar un papel asesino.

Los dos primeros que sellaron su testimonio con su sangre fueron William Robinson,
comerciante de Londres, y Marmaduke Stevenson, un campesino de Yorkshire.
Cuando estos llegaron a Boston a inicios de septiembre,
fueron enviados y condenados por el tribunal de asistentes,
al destierro bajo pena de muerte.
Esta sentencia también se dictó en contra de Mary Dyer, mencionada anteriormente,
y contra Nicholas Davis, quienes se encontraban en Boston.
Pero William Robinson, al ser considerado un maestro,
también fue condenado a ser azotado severamente,
y se le ordenó al alguacil que consiguiera un hombre capaz de hacerlo.
Luego llevaron a Robinson a la calle y ahí lo desnudaron,
y con sus manos metidas entre los agujeros de un carruaje
de una gran arma en la que el carcelero lo sostenía,
el verdugo le dio veinte azotes con un látigo de tres cuerdas.
Luego él y los otros prisioneros fueron rápidamente liberados y desterrados;
y que esto fue por ninguna otra razón que por ser Cuáqueros,
se ve en la siguiente orden judicial:

[.embedded-content-document.legal]
--

Se le requiere mediante la presente, que libere a William Robinson, Marmaduke Stevenson,
Mary Dyer y Nicholas Davis, quienes por orden de la corte y del consejo,
habían sido encarcelados, porque según su propia confesión, palabras y actos,
parecían ser Cuáqueros.
Por lo tanto,
se dictó una sentencia contra ellos para que salieran
de esta jurisdicción bajo pena de muerte,
y que debían responder por su cuenta y riesgo,
si ellos (o cualquiera de ellos) eran encontrados dentro de esta jurisdicción,
o cualquier otra parte de ella, después del 14 del presente mes de septiembre.

[.signed-section-signature]
Edward Rawson

[.signed-section-context-close]
Boston, 12 de septiembre, 1659

--

Ahora bien, Mary Dyer y Nicholas Davis dejaron esa jurisdicción en ese momento,
pero W. Robinson y M. Stevenson, aunque salieron de la ciudad de Boston,
no pudieron decidirse (al no sentirse libres en sus mentes) a dejar la jurisdicción,
aunque sus vidas estuvieran en juego.
Y así,
se fueron a Salem y a otros lugares aledaños para
visitar y edificar a sus amigos en la fe.
Pero no pasó mucho tiempo antes de que fueran capturados
y puesto de nuevo en prisión en Boston,
con cadenas atadas en sus piernas derechas.
El mes siguiente Mary Dyer también regresó,
y mientras estaba de pie frente a la prisión hablando con un tal Christopher Holder,
que había ido ahí para informarse de un barco con destino a Inglaterra,
adonde él pretendía ir, también fue detenida.
De este modo tenían a tres personas, quienes, de acuerdo a su sanguinaria ley,
habían perdido sus vidas.
Y el 20 de octubre, estas tres personas fueron llevadas a la corte,
donde estaban reunidos John Endicot y otros.
Y al ser llamados al estrado,
Endicot le ordenó al guarda de la cárcel que les quitara los sombreros,
y luego dijo que ellos habían promulgado varias leyes
para evitar que los Cuáqueros llegaran entre ellos,
y que ni los azotes, ni los encarcelamientos, ni el corte de orejas,
ni los destierros bajo pena de muerte, los mantenían lejos.

Además dijo, que él (o ellos) no deseaba la muerte de ninguno de ellos; no obstante,
sus siguientes palabras, sin más, fueron:
"`Escuchen y presten atención a su sentencia de muerte.`"
William Robinson entonces quiso que se le permitiera leer un papel,
dando cuenta de la razón por la que él no había salido de esa jurisdicción;
pero Endicot no permitió que se leyera, y dijo enfurecido: "`No lo leerás,
ni la corte lo oirá leer.`"
Entonces Robinson lo dejó sobre una mesa.
Este papel había sido escrito el día anterior, y en él relataba,
cómo estando en Rhode Island,
el Señor le había ordenado ir a Boston y entregar su vida allí,
y que había también sentido la seguridad de que su
alma iba a entrar en perpetua paz y reposo eterno.
Que no se había atrevido a nada más que a obedecer este mandato,
sin preguntar más al respecto, creyendo que le correspondía, como a un niño,
mostrar obediencia al Señor, sin ninguna falta de voluntad.
Que esta, afirmó él,
había sido la causa por la que después del destierro bajo pena de muerte,
se había quedado en la jurisdicción de ellos;
y que ahora con sinceridad de corazón podía decir: "`Bendito sea el Señor,
el Dios de mi vida, quien me ha llamado a hacer esto,
y me ha considerado digno de testificar contra los hombres perversos y malvados,`" etc.

Entregado este papel a Endicot, lo leyó para sí mismo, y después de que lo había hecho,
le dijo a Robinson: "`No es necesario que hagas tanto ruido para que lo lean,
porque tú hablaste más ayer de lo que está escrito aquí.`" Sin embargo, no era así,
porque el papel contenía un relato circunstancial de las operaciones divinas en su mente,
explicando que él no había llegado ahí en su propia voluntad,
sino en obediencia a su Creador; y que viajando en Rhode Island, el 8 del mes Ocho,
había sido movido por el Señor, y por tanto,
que se había sometido a Su divino beneplácito sin murmuración.
Robinson pidió de nuevo que se leyera el papel,
para que todos los presentes pudieran escucharlo.
Pero le fue negado y Endicot dijo:
"`W. Robinson presta atención a tu sentencia de muerte;
serás regresado al lugar de donde viniste (es decir, la prisión),
y de ahí al lugar de ejecución, para ser colgado en la horca hasta que mueras.`"
Esta sentencia no fue del todo inesperada para W. Robinson, pues hacía ya cuatro meses,
que creía que esa sería su suerte.

Cuando se llevaron a Robinson, llamaron a M. Stevenson, y Endicot le dijo:
"`Si tienes algo que decir, puedes hablar.`"
Sabiendo como habían tratado a su compañero, guardó silencio,
aunque él también había escrito un papel que explicaba
la causa por la que había llegado ahí,
pero lo guardó con él, y más tarde encontró la oportunidad de entregárselo a alguien.
Entonces Endicot pronunció la sentencia de muerte contra él, diciendo:
"`Marmaduke Stevenson, serás llevado al lugar de donde viniste, y de ahí a los cadalsos,
y ahí serás colgado hasta que mueras.`"
Ante lo cual, M. Stevenson dijo así: "`Escuchen ustedes magistrados,
y todos los culpables;
porque esto ha dicho el Señor con respecto a ustedes y Él cumplirá Su palabra,
que el mismo día que ejecuten a Sus siervos,
el día de la visitación de ustedes pasará sobre sus cabezas y serán malditos para siempre.
La boca del Señor de los ejércitos lo ha dicho.
Por tanto, en amor por todos ustedes,
los exhorto a que tomen la advertencia antes de que sea demasiado tarde,
para que la maldición sea eliminada.
Porque ciertamente, si nos ejecutan,
traerán sangre inocente sobres sus cabezas y les sobrevendrá una rápida destrucción.`"

Después de haber dicho esto se lo llevaron, y llamaron a Mary Dyer,
a quien Endicot le habló así: "`Mary Dyer, irás al lugar de donde viniste,
y de ahí al lugar de ejecución, y serás colgada hasta que mueras.`"
A lo que ella replicó: "`Sea hecha la voluntad del Señor.`" Entonces Endicot dijo:
"`Llévatela, alguacil.`"
A lo que ella respondió: "`Sí, voy gozosa.`"
Y camino hacia la prisión, pronunció a menudo palabras de alabanza al Señor,
y llena de gozo le dijo al alguacil,
que podía dejarla sola porque iría a la prisión sin él. A esto él le respondió:
"`Yo le creo, señora Dyer,
pero debo hacer lo que se me ordenó.`" Así fue conducida a la prisión,
donde permaneció una semana con sus otros dos compañeros
que habían sido condenados a muerte también.

El papel de Marmaduke Stevenson, mencionado antes,
que él entregó después de que había recibida la sentencia de muerte, fue el siguiente:

[.embedded-content-document.paper]
--

Al principio del año 1655, estaba yo en el arado, en la zona oriental de Yorkshire,
en Vieja Inglaterra, cerca del lugar donde se encontraba mi vivienda exterior,
y mientras caminaba detrás del arado fui llenado del amor y presencia del Dios vivo;
lo cual extasió mi corazón cuando lo sentí,
pues se incrementó y manó en mí como una corriente viva.
El amor y la vida de Dios corrieron a través de mí como un ungüento precioso,
expeliendo un olor agradable que me hizo quedarme quieto; y mientras estaba callado,
con mi corazón y mi mente fijos en el Señor,
la palabra del Señor llegó a mí en un silbo apacible y delicado, que yo oí perfectamente,
diciéndome en lo secreto de mi corazón y consciencia:
"`Te he dado por profeta a las naciones.`"
Y al oír la palabra del Señor, paré en seco,
ya que no era más que un niño para tan importante asunto.
Así, en el tiempo señalado, Barbados fue puesto delante de mí,
adonde el Señor me pidió que fuera,
y que dejara a mi querida y amada esposa y a mis tiernos niños;
porque el Señor me dijo inmediatamente por Su Espíritu,
que Él sería como un esposo para mi esposa, y como un padre para mis hijos,
y que a ellos no les faltaría nada en mi ausencia,
porque Él les proveería cuando yo estuviera fuera.
Y yo creí que el Señor cumpliría lo que había dicho,
porque me hizo estar dispuesto a entregarme a Su obra y servicio,
a dejarlo todo para seguirlo a Él, cuya presencia y vida están conmigo,
donde descanso en paz y quietud de espíritu (con mi querido hermano),
bajo la sombra de Sus alas.
Él nos hizo estar dispuestos a entregar nuestras vidas por causa de Su propio nombre,
si se les permitía a hombres despiadados tomarlas; y si lo hacían,
sabíamos que tendríamos paz y reposo con el Señor para siempre en Su santa morada,
cuando ellos tendrían tormento noche y día.

Así, en obediencia al Dios vivo,
hice preparativos para ir a Barbados en el mes Cuatro de 1658.
Y después de que había estado algún tiempo en dicha isla al servicio de Dios,
oí que en Nueva Inglaterra había sido promulgada
una ley para ejecutar a los siervos del Dios vivo,
si regresaban después de que habían sido sentenciados a salir, lo cual, en ese momento,
me afectó. Y mientras consideraba el asunto y lo meditaba en mi corazón,
vino inmediatamente a mí la palabra del Señor diciendo:
"`Puede que te pida que vayas allí.`" Pero yo guardé esta palabra en mi corazón,
y no la declaré a nadie hasta el tiempo señalado.
Y así, después de eso, me embarqué en una nave que estaba lista hacia Rhode Island.
Un tiempo después de haber estado ahí visitando a la semilla que el Señor ha bendecido,
la palabra del Señor vino sobre mí diciendo:
"`Ve a Boston con tu hermano William Robinson.`"
Y fui obediente a Su orden y me rendí para hacer Su voluntad,
para que Su obra y servicio se cumplieran, porque Él me había dicho,
que tenía una gran obra que hacer a través de mí; la cual ya se ha cumplido.
Y por rendir obediencia al Dios eterno y acatar Su voz y mandato,
quien creó los cielos y la tierra, y las fuentes de las aguas, sufro, con mi hermano,
ataduras externas cerca de la muerte.
Esto se da para que quede registro y para que todas las personas que lo oigan sepan,
que nosotros no hemos venido por nuestras propias voluntades,
sino en la voluntad de Dios.
Entregado por mí; conocido entre los hombres por el nombre de,

[.signed-section-signature]
Marmaduke Stevenson.

[.signed-section-context-close]
A quien se le ha dado un nuevo nombre, que el mundo no conoce,
escrito en el libro de la vida.

[.signed-section-context-close]
Escrito en la prisión de Boston, en el mes Ocho de 1659.

--

Mary Dyer, de vuelta en prisión, escribió la siguiente carta,
la cual envió a los gobernantes de Boston.

[.embedded-content-document.letter]
--

[.letter-heading]
Al Tribunal General en Boston

Soy acusada por muchos de la culpabilidad de mi propia sangre;
si se refieren a mi venida a Boston, estoy en ella libre y justificada por el Señor,
en cuya voluntad vine, quien, estén seguros,
demandará mi sangre de aquellos que han hecho una ley para
quitarles la vida a los inocentes siervos de Dios,
si vienen entre ustedes.
Estos son llamados por ustedes "`malditos Cuáqueros,`" aunque yo digo,
y soy una testigo viva en su nombre, y en nombre del Señor,
de que Él los ha bendecido y enviado a ustedes.
Por tanto, no sean hallados peleando contra Dios, antes bien,
acepten mi consejo y mi petición de derogar todas esas leyes,
para que la Verdad y los siervos del Señor tengan libre paso entre ustedes,
y ustedes sean guardados de derramar sangre inocente, lo cual sé,
que hay muchos entre ustedes que no lo harían,
si supieran que es así. Ni el enemigo que los incita así a destruir Su santa semilla,
puede en alguna medida compensar el gran daño que obtendrán al hacerlo.

Por tanto, dado que el Señor no me lo ha ocultado, está sobre mí, en amor a sus almas,
persuadirlos así. No tengo fines propios (el Señor lo sabe);
porque aunque me concedieran mi vida, de nada me valdría, ni podría esperarla de ustedes,
en tanto deba oír o ver diariamente los sufrimientos de este pueblo,
mis queridos hermanos, y de la semilla con la que mi vida está ligada,
como lo he hecho estos dos años; y ahora es probable que tal sufrimiento se incremente,
incluso hasta la muerte, por ningún mal, sino sólo por venir entre ustedes.
¿Se ha oído alguna vez una ley así entre el pueblo
que profesa que Cristo ha venido en la carne?
¿No tienen otras armas sino esas leyes,
con las cuales pelear contra la "`maldad espiritual`" como la llaman ustedes?
¡Ay de mí por ustedes! ¿De quién toman ustedes consejo?
Examinen con la luz de Cristo en ustedes, y ella les mostrará,
como ha hecho conmigo y muchos otros, quienes han sido desobedientes y engañados,
como lo son ustedes ahora.
En la medida que entren en esta luz, y obedezcan lo que les es manifestado por ella,
no lamentarán que fueran impedidos de derramar sangre, aunque sea por una mujer.

No busco mi propia vida (porque prefiero escoger sufrir con el pueblo de Dios,
que disfrutar los placeres de Egipto), sino la vida de la Semilla,
que sé que el Señor ha bendecido,
y por eso el enemigo busca vehementemente destruir Su vida,
como lo ha hecho siempre en todas las épocas.
¡Oh, no le presten atención, se los ruego, por la Semilla,
que es una en todos y es querida a los ojos de Dios; porque los que tocan esto,
tocan la niña de Su ojo y no pueden escapar de Su ira!
Y yo, tras haber sentido esta ira,
no puedo sino persuadir a todos los hombres (especialmente a ustedes,
que mencionan el nombre de Cristo),
a que salgan de tal iniquidad como el derramamiento de sangre;
la sangre de los santos del Altísimo.

Por tanto, que mi petición tenga tanta aceptación en ustedes, si son Cristianos,
como tuvo Ester con Asuero, cuya relación se queda corta a la que hay entre Cristianos,
y mi petición es la misma que la de ella.
Porque el rey no dijo,
que él había hecho esa ley y que sería deshonroso para él revocarla; sino más bien,
cuando entendió que ese pueblo era muy apreciado por ella y que le afectaba
tanto (como verdaderamente los son este pueblo para mí),
ustedes pueden ver lo que él hizo por ella.
Por tanto, dejo estas líneas con ustedes, apelando al Testigo fiel y verdadero de Dios,
que es uno en todas las consciencias, ante quien debemos comparecer todos,
y con quien yo reposaré eternamente en gozo y paz perpetuos,
ya sea que escuchen o se abstengan de escuchar.
Mi recompensa está con Él, con quien vivir es mi alegría, y morir es mi ganancia,
incluso si no se me hubieran dado el aviso de cuarenta y
ocho horas para la preparación de la muerte de Mary Dyer.

Y sepan esto también,
que si ustedes (por la enemistad) se declararan peores que el rey Asuero,
y de ese modo confirmaran la ley, aunque sea quitando una de nuestras vidas,
el Señor derribará tanto su ley como a ustedes, mediante Sus justos juicios y plagas,
derramados justamente sobre ustedes, quienes ya,
mientras son advertidos de ello y tiernamente buscados, pueden evitar una cosa,
eliminando la otra.
Si ustedes no escuchan ni obedecen al Señor, ni a Sus siervos,
aun así Él enviará más de Sus siervos entre ustedes,
para que se frustre el propósito de los que piensan impedirles a los que
ustedes llaman "`malditos Cuáqueros`" de venir entre ustedes,
mediante cualquier cosa que les puedan hacer.
Sí, en verdad,
Él tiene una semilla aquí entre ustedes por la cual hemos sufrido todo esto tiempo,
y todavía sufrimos.
Y el Señor de la mies enviará más obreros para sacarla
de la boca de los devoradores de toda clase,
y llevarla a Su aprisco, donde Él la guiará a verdes pastos, a las sendas de justicia,
por amor de Su nombre.
¡Oh, que ninguno de ustedes aleje este buen día,
que en la luz del Señor en verdad veo que se aproxima,
incluso para muchos en Boston y sus alrededores,
que es el lugar más amargo y oscuro que profesa el
Cristianismo del que yo haya oído alguna vez!

Por tanto,
que el tiempo pasado sea suficiente para una profesión
que produce tales frutos como los son estas leyes.
En amor y en el espíritu de mansedumbre, de nuevo les ruego,
pues no tengo enemistad con nadie; pero ustedes sabrán que Dios no puede ser burlado,
sino que lo que siembren, eso cosecharán de Él,
quien dará a cada uno según las obras hechas en el cuerpo, sean buenas o malas.
Así sea, dice,

[.signed-section-signature]
Mary Dyer.

[.signed-section-context-close]
Una copia de esto fue entregada al Tribunal General,
después de que Mary Dyer había recibido la sentencia de muerte,
alrededor del octavo o noveno mes de 1659.

--

El día señalado para la sangrienta ejecución de la sentencia fue el 27 de octubre,
cuando por la tarde,
los condenados fueron conducidos a las horcas por
el alguacil Michaelson y el capitán James Oliver,
con una banda de casi doscientos hombres armados, además de muchos jinetes;
como si temieran que algunos del pueblo hubieran querido rescatar a los prisioneros.
Y para que no faltaran actores en el escenario,
se unió a la compañía el sacerdote Wilson, quien,
cuando el tribunal estaba deliberando cómo lidiar con los Cuáqueros, había dicho:
"`Cuélguenlos, o si no&hellip;,`" (arrastrando sus dedos a través de su garganta,
como diciendo: "`Despáchenlos de esta manera`").

Así comenzó la marcha,
y un tamborilero que iba delante de los condenados golpeaba los tambores,
especialmente cuando alguno de ellos intentaba hablar.
Gloriosos signos de gozo y alegría celestial se veían en los rostros de estas tres personas,
quienes caminaban de la mano, siendo Mary la del medio.
Esto hizo que el alguacil le dijera a ella (que era un hombre mayor):
"`¿No te avergüenza caminar de la mano entre dos hombres jóvenes?`"
"`No,`" respondió ella,
"`esta es para mí la hora del más grande gozo que podría disfrutar en este mundo.
Ningún ojo puede ver, ningún oído puede oír, ninguna lengua puede pronunciar,
ni ningún corazón puede entender,
el dulce fluir y la refrescante influencia del Espíritu del Señor que siento ahora.`"
Y así, en la marcha, William Robinson dijo:
"`Esta es la hora de ustedes y del poder de las tinieblas.`"
Pero inmediatamente golpearon los tambores; sin embargo,
poco después de que el tamborilero dejó de tocar, Marmaduke Stevenson dijo:
"`Este es el día de la visitación de ustedes, en el que el Señor los visita.`"
Habló más, pero no se le pudo entender porque volvieron a sonar los tambores.
Con todo, ellos continuaron con gran alegría,
como si fueran para un banquete de bodas eterno,
y regocijándose de que el Señor los hubiera tenido
por dignos de sufrir la muerte por causa de Su nombre.

Cuando se habían acercado a las horcas,
el sacerdote le dijo a William Robinson de manera burlona:
"`¿Deberían los imbéciles como tú presentarse ante la autoridad con los sombreros puestos?`"
A esto Robinson respondió: "`¡Consideren, consideren;
por no quitarnos el sombrero es que somos llevados a la muerte!`"
Cuando llegaron a la escalera, se despidieron con tiernos abrazos,
y luego Robinson subió alegremente, y ya arriba le dijo al pueblo:
"`Este es el día de la visitación de ustedes, en el que el Señor los visita;
este es el día en que el Señor se ha levantado en
Su gran poder para vengarse de todos Sus adversarios.`"
También dio a entender que él no sufría como un malhechor,
y luego deseó que los espectadores le prestaran atención a la luz que estaba en ellos;
es decir, a la luz de Cristo,
de la que él daba testimonio y estaba a punto de sellar con su sangre.
Esto indignó tanto la envidia del sacerdote, que dijo: "`Cierra la boca; cállate;
vas a morir con una mentira en tu boca.`"
Con la soga al cuello, el verdugo le sujetó sus manos y piernas,
y le ató el pañuelo a la cara.
Hecho eso, Robinson dijo:
"`Ahora son puestos de manifiestos,`" y cuando el verdugo estaba a punto de ahorcarlo,
dijo: "`Sufro por Cristo, en quien vivo y por quien muero.`"
Al ser colgado, W. Robinson, Marmaduke Stevenson subió la escalera, y dijo:
"`Sea sabido por todos hoy, que nosotros no sufrimos como malhechores,
sino por causa de la consciencia.`"
Y cuando el verdugo estaba a punto de ahorcarlo, dijo:
"`Este día estaremos en reposo con el Señor,`" y así fue colgado.

Mary Dyer, al ver a sus compañeros colgando muertos frente a ella,
también subió la escalera; pero después de que le ataron su abrigo en los pies,
le pusieron la soga alrededor del cuello,
y le cubrieron la cara con un pañuelo (que el sacerdote
Wilson le había prestado al verdugo),
justo cuando estaba a punto de ser ahorcada, se oyó un grito: "`¡Detente,
porque ella ha sido indultada!`"
Entonces le soltaron los pies y le ordenaron que bajara.
Pero ella, cuya mente ya estaba como en el cielo, se quedó quieta,
y dijo que estaba dispuesta a sufrir como lo habían hecho sus hermanos,
a menos que anularan su perversa ley.
No se prestó atención a lo dicho por ella, sino que la bajaron,
y tomándola por sus brazos, el alguacil y otros la llevaron a prisión de nuevo.
El hecho de que en ese momento fuera liberada de la horca,
fue por intercesión de su hijo,
a quien parece que no pudieron negarle entonces ese favor.
Al oír la razón por la que había sido indultada, al día siguiente, que era 28 de octubre,
escribió la siguiente carta al tribunal.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
28 del mes Ocho de 1659.

Una vez más, Mary Dyer le habla igual que antes, al Tribunal General reunido en Boston.
Me ofrecen mi vida,
pero no puedo aceptarla porque no tiene valor para
mí en comparación con la vida y libertad de la Verdad,
y de los siervos del Dios vivo, por los que en amor y mansedumbre les he suplicado.
Sin embargo, con manos impías ustedes han ejecutado a dos de ellos,
lo que me hace sentir que "`la piedad de los impíos es crueldad.`"
Yo prefiero morir que vivir, a partir de ustedes,
siendo culpables de la sangre inocente de ellos.
Pero viendo que mi deseo es obstaculizado,
los encomiendo al Juez justo y escrutador de todos los corazones, quien,
con la medida pura de luz que Él le ha dado a todo hombre para provecho,
en Su tiempo les hará ver de quien son siervos ustedes, y de quien han tomado consejo,
en lo cual deseo que indaguen; pero todo Su consejo ha sido desechado,
y ustedes no han querido ninguna de Sus reprensiones.
Lean su porción en Proverbios 1:24-32. Porque, ciertamente,
la noche viene pronto sobre ustedes,
en la que ningún hombre puede trabajar y de seguro caerán delante de su propio amo.

En obediencia al Señor, a quien sirvo con mi espíritu y en piedad por sus almas,
a las que ustedes no conocen ni compadecen,
no puedo hacer menos que advertirles una vez más, que desechen el mal de sus obras.
Honren al Hijo, a la luz que está en ustedes, antes de que se encienda Su ira en ustedes;
porque ciertamente, cuando Su ira se encienda,
nada fuera de ustedes podrá ayudarlos o liberarlos de Su mano.
Si estas cosas no resultan así,
entonces pueden decir que no ha sido enviado profeta del
Señor entre ustedes (porque aunque nosotros no somos nada,
por medio de lo que no es, Le place a Él deshacer lo que es).

Cuando oí la lectura de la última orden de ustedes, fue una perturbación para mí,
porque en ese momento, yo, muy voluntariamente,
estaba ofreciendo mi vida Al que me la dio y me envió aquí a hacerlo.
Al ser la obediencia Su propia obra, Él la acompañó gloriosamente con Su presencia,
paz y amor en mí, en lo cual descansaba de mi obra;
hasta que por la orden de ustedes y del pueblo quedé tan perturbada,
que no pude retener más de las palabras de la misma,
excepto que debía regresar a prisión y permanecer ahí cuarenta y ocho horas;
a lo que me sometí, sin encontrar nada contrario del Señor,
para poder conocer cuál es Su beneplácito y consejo con respecto a mí,
en quien ahora espero.
En verdad, Él es mi vida y la duración de mis días, y como dije antes,
vine por Su mandamiento y por Su mandamiento me voy.

[.signed-section-signature]
Mary Dyer

--

Al percibir los magistrados que la ejecución de William Robinson y Marmaduke
Stevenson había provocado un gran descontento entre el pueblo,
resolvieron enviar a Mary Dyer lejos, y de ese modo calmar un poco los ánimos.
Así que la montaron en un caballo y cuatro jinetes
la condujeron quince millas hacia Rhode Island,
donde fue dejada con un caballo y un hombre para que la llevara el resto del camino,
al que ella pronto envió de regreso, y así volvió a casa.
Por el estilo de sus cartas y su imperturbable porte,
parece que realmente tenía unas cualidades extraordinarias.
También encontré que ella era de semblante hermoso y serio,
de buena familia y patrimonio, y madre de varios niños;
pero parece que su esposo era de otra persuasión.

Ahora la dejo a ella en casa, y continúo con el relato de un tal John Chamberlain,
habitante de Boston, que después de ver la ejecución de W. Robinson y M. Stevenson,
fue tan tocado por sus piadosas palabras,
que recibió la doctrina de la Verdad por la que ellos murieron.
Pero su visita a los que estaban en prisión fue tan mal vista,
que después lo azotaron varias veces.
Además, un tal Edward Wharton, habitante de Salem,
después de decir que la culpa de la sangre de Robinson y Stevenson
eran tan grande y pesada que no era capaz de soportarla,
fue, por su pretendida indiscreción,
azotado con veinte latigazos y multado con veinte libras.

Pero antes de despedirme de las personas que fueron colgadas, debo decir,
que estando muertas sus semblantes todavía se veían frescos (porque
el terror de la muerte no se había apoderado de ellas).
Pero al ser cortadas las sogas, fueron tratados bárbaramente,
porque al no sostener sus cuerpos, cayeron al suelo de manera tal,
que el cráneo de William Robinson se quebró; e incluso,
sus camisas fueron arrancadas con un cuchillo,
y sus cuerpos desnudos tirados en un hueco que había sido cavado, sin cubierta alguna.
Y cuando algunos de sus amigos querían que sus cuerpos fueran puestos en ataúdes,
se les negó. Tampoco permitieron que el lugar donde
fueron tirados los cuerpos se cercara con postes,
para que las bestias voraces no hicieran presa de ellos.

Cuando la gente regresaba de la ejecución, muchos parecían tristes y pesados,
y al llegar al puente levadizo,
uno de sus extremos cayó sobre algunos y varios resultaron heridos,
especialmente una mujer perversa que había injuriado a los dos hombres en su muerte.
Pero esta mujer quedó tan lastimada, que su carne se empezó a podrir desde sus huesos,
y hedía tan desagradablemente que la gente no soportaba estar con ella;
en esa miserable condición permaneció hasta que murió. Pero los magistrados,
en lugar de tomar nota de esto, se endurecieron más; y el sacerdote Wilson fue tan lejos,
que compuso una balada acerca de los hombres que había sido ejecutados.

Ahora regreso a Mary Dyer, quien después de llegar a Rhode Island,
se fue de ahí a Long Island, donde se quedó la mayor parte del invierno.
Luego, al volver a su casa, fue movida a regresar al sangriento pueblo de Boston,
adonde llegó el 21 del mes Tres de 1660,
y el 31 fue mandada a llamar por el Tribunal General.
Al llegar, el gobernador John Endicot, dijo:
"`¿Eres tú la misma Mary Dyer que estuvo aquí antes?`"
Porque parece que él esperaba una evasiva de ella,
dado que había otra con el mismo nombre que recientemente había regresado de Vieja Inglaterra.
Pero ella estaba tan lejos de disimular, que respondió imperturbablemente:
"`Yo soy la misma Mary Dyer que estuvo aquí en la última corte general.`"
Entonces Endicot dijo: "`Tú te reconocerás como Cuáquera, ¿cierto?`"
A lo que Mary Dyer dijo: "`Reconozco ser llamada así en menosprecio.`"
Entonces el carcelero (que también quería decir algo) dijo: "`Ella es una vagabunda.`"
Y Endicot dijo: "`Esta sentencia fue pronunciada sobre ella en la última corte general,
y ahora también:
Debe regresar a prisión y ahí permanecer hasta mañana a las nueve en punto;
luego desde ahí debe ir a la horca, y ser colgada hasta morir.`"
A lo que Mary Dyer dijo: "`Esto no es más que lo que dijiste antes.`"
Y Endicot respondió: "`Pero ahora se va a ejecutar; por tanto,
prepárate para mañana a las nueve en punto.`"
Entonces ella habló así:
"`Vine en obediencia a la voluntad de Dios durante la última corte general,
deseando que revocaran sus injustas leyes de destierro bajo pena de muerte; y lo mismo,
es mi obra ahora y mi más ferviente petición; aunque les dije,
que si rehusaban revocarlas,
el Señor enviaría a otros de Sus siervos para testificar contra ellas.`"
En seguida, Endicot le preguntó si ella era profetisa.
Mary contestó que ella simplemente decía las palabras que el Señor hablaba en ella;
y que ahora la cosa se había cumplido.
Y al comenzar a hablar de su llamado, Endicot gritó: "`Sáquenla; sáquenla.`"
Por tanto, fue llevada a la prisión donde había estado antes,
y la mantuvieron encerrada hasta el día siguiente.

Aproximadamente a la hora señalada el alguacil Michaelson
llegó y la llamó para que saliera apresuradamente;
y al entrar al cuarto donde estaba ella, Mary quería que él se quedara un momento,
y hablando suavemente, dijo que estaría lista en breve.
Pero al ser él de carácter áspero, dijo que no podía esperarla,
sino que ella debía atenderlo.
Una tal Margaret Smith, compañera de ella, afligida por ver tanta dureza de corazón,
habló algo contra las leyes y procedimientos injustos de ellos, a lo que él dijo:
"`Tú tendrás tu parte de lo mismo.`"
Entonces Mary Dyer fue sacada y conducida por una banda de soldados a través del pueblo,
tocando los tambores delante y detrás de ella;
y continuaron tocando para que nadie pudiera oírla
hablar durante todo el camino al lugar de la ejecución,
que estaba como a una milla.

Con esta guardia llegó a la horca, y tras subir la escalera,
algunos le dijeron que si quería volver a casa, podía bajar y salvar su vida.
A esto ella respondió: "`No, no puedo, porque en obediencia a la voluntad del Señor vine,
y en Su voluntad permaneceré fiel hasta la muerte.`"
Entonces, el capitán John Webb dijo, que ella había estado ahí antes,
y había recibido la sentencia de destierro bajo pena de muerte,
y había quebrantado la ley al regresar, y que por lo tanto,
era culpable de su propia sangre.
A lo que ella replicó: "`No, vine para evitarles la culpa de sangre,
al desear que deroguen la incorrecta e injusta ley de destierro bajo pena de muerte,
hecha contra los inocentes siervos del Señor; por tanto,
mi sangre será demandada de las manos de ustedes, quienes voluntariamente lo hacen.
Pero a los que lo hacen en la sencillez de sus corazones, deseo que el Señor los perdone.
Yo vine a hacer la voluntad de mi Padre, y en obediencia a Su voluntad,
me mantengo hasta la muerte.`"

Entonces el sacerdote Wilson dijo: "`Mary Dyer, arrepiéntete, arrepiéntete,
y no te dejes engañar y llevar por el engaño del maligno.`"
A esto Mary respondió: "`No, hombre, ahora no es el tiempo para arrepentirse.`"
Y al preguntarle algunos si quería que los ancianos oraran por ella, dijo:
"`No conozco a ningún anciano aquí.`" Y al preguntarle además,
si quería que alguien del pueblo orara por ella,
respondió que deseaba las oraciones de todo el pueblo de Dios.
Entonces algunos dijeron con sorna:
"`Tal vez piensa que no hay ninguno aquí.`" Mirando alrededor de ella, dijo:
"`Sólo conozco a unas pocas personas aquí.`" Luego le volvieron a decir,
que uno de los ancianos podía orar por ella; a lo que ella contestó: "`No,
primero tiene que haber un niño, luego un joven, luego un hombre fuerte,
antes de que pueda haber un anciano en Cristo Jesús.`"
Después de esto la culparon de algo que no se entendió,
pero que a ella le pareció oír, porque dijo: "`Es falso, es falso;
nunca dije esas palabras.`"
Entonces alguien mencionó que ella había dicho algo
de estar en el paraíso. Y a esto respondió:
"`Sí,
he estado en el paraíso varios días.`" Y además habló de
la eterna felicidad a la que estaba a punto de entrar.
Y en esta bien dispuesta condición, fue colgada, y murió como mártir de Cristo,
siendo llevada dos veces a la muerte; la primera vez esperó con inquebrantable valor,
y ahora sufrió con cristiana fortaleza.

Así terminó sus días esta honesta y valiente mujer.
Pero estos perseguidores estaban tan endurecidos,
que uno de los miembros de la corte burlonamente dijo:
"`Ella colgó como una bandera para que otros tomen el ejemplo.`"
Las ejecuciones no terminaron aquí, como será narrado más adelante;
pero primero regresaré a Vieja Inglaterra,
donde había entonces una gran división y una revolución en el estado.
