== Capítulo 11

Tras comenzar el año 1661, el gobierno había cambiado por completo,
Carlos II estaba sentado ahora en el trono de Inglaterra en paz,
y el poder de la persecución parecía un tanto frenado,
así que había una aparente tranquilidad y calma.
Por tanto, haré un giro hacia Nueva Inglaterra,
para descorrer las cortinas del sangriento escenario en Boston.
Ya hemos visto en el relato anterior, la manera en que William Robinson,
Marmaduke Stevenson y Mary Dyar fueron ejecutados por sus perseguidores, sin embargo,
su sed de sangre aún no se había apagado.

William Leddra, quien había sido desterrado de Boston so pena de muerte,
se sintió bajo tal necesidad de consciencia, que no pudo evitar regresar ahí,
adonde llegó a finales del año anterior.
Pronto fue hecho prisionero, y estando amarrado a un gran tronco de madera,
fue dejado noche y día encerrado con cadenas en una cárcel abierta,
durante un invierno muy frío; donde lo dejaremos por el momento.
Mientras tanto,
insertaré una "`justificación`" escrita de los perseguidores
de Boston con respecto a su cruel postura,
que puede servir para confirmar la verdad de lo que
ya se ha relatado de sus perversos tratos.
Porque parece,
que temiendo que sus sangrientos actos fueran desaprobados por la corte de Inglaterra,
pensaron que los más seguro era pintar sus transacciones con una pretensión engañosa,
aunque esto no tuvo otro efecto que el de exponer
más su propia vergüenza a la vista del público;
y con el paso del tiempo también incurrieron en el desagrado del rey.
Porque, aunque Carlos II estaba inclinado a la sensualidad, era de buen corazón,
y la persecución en su reinado procedía principalmente
de la instigación de otros hombres maliciosos.
Pero llego ahora, a la justificación o declaración de los sangrientos perseguidores,
que fue como sigue:

Aunque la justicia de nuestros procedimientos contra William Robinson,
Marmaduke Stevenson y Mary Dyar, respaldada por la autoridad de este tribunal,
las leyes de este condado y la ley de Dios,
puede persuadirnos a esperar el estímulo y el elogio
de todos los hombres prudentes y piadosos,
más que convencernos de alguna necesidad de justificación de los mismos, aun así,
por cuanto los hombres de entendimiento más débil,
por piedad y conmiseración (que es una virtud encomiable y cristiana,
pero de la que se puede abusar fácilmente,
y susceptible de impresiones siniestras y peligrosas por falta
de una información completa) pueden estar menos satisfechos,
y puesto que los hombres de principios perversos pueden ser conducidos a calumniarnos,
y a presentarnos como perseguidores sangrientos; por tanto,
a fin de satisfacer a unos y detener la boca de otros,
hemos creído necesario declarar lo siguiente.

Hace unos tres años,
varias personas que se profesaban Cuáqueras (de cuyas opiniones y prácticas perniciosos
habíamos recibido información de buenas manos en Barbados e Inglaterra),
llegaron a Boston, cuyas personas fueron detenidas entonces,
sólo para ser enviadas de regreso en la primera oportunidad, sin censura o castigo,
aunque los principios profesados por ellos,
y comportamientos turbulentos y despectivos hacia la autoridad,
habrían justificado una condena más severa.
Sin embargo, la prudencia de este tribunal se ejerció, únicamente,
en la toma de las medidas necesarias para asegurar
la paz y el orden aquí establecidos contra sus intentos,
cuyo plan (del que estábamos bien seguros por experiencia propia,
así como también por el ejemplo de sus predecesores
en Munster) era socavar y arruinar dicho tribunal.

En consecuencia,
se promulgó y publicó una ley que les prohibía a todos los
capitanes de barco traer algún Cuáquero a esta jurisdicción,
y que también les prohibía a los Cuáqueros entrar,
so pena de ser confinados en la casa de corrección hasta que fueran expulsados.
A pesar de esto, encontraron entrada por una puerta trasera,
y la pena que se les impuso resultó insuficiente
para frenar sus descaradas e insolentes intrusiones,
y se aumentó a la pérdida de las orejas de aquellos
que por segunda vez infringieran la ley.
Al ser esto también una defensa demasiado débil contra su impetuosa y frenética furia,
nos obligó a buscar nuestra propia seguridad, y tras una seria consideración,
después de la experiencia anterior de sus incesantes asaltos,
se promulgó una ley para que estas personas fueran desterradas so pena de muerte,
en concordancia con el ejemplo de Inglaterra en su disposición contra los Jesuitas.

Después de que en el último Tribunal de Asistentes se pronunció esta sentencia en conformidad,
contra las partes arriba mencionadas,
y ellos regresaron o presuntuosamente permanecieron
en esta jurisdicción después del tiempo limitado,
fueron aprehendidos, y tras reconocer que eran las personas desterradas,
fueron condenadas a muerte por el tribunal, según la ley antes mencionada,
y ejecutada sobre dos de ellos.
Mary Dyar,
(por petición de su hijo y misericordia y clemencia de este
tribunal) tuvo libertad de partir en el lapso de dos días,
lo que ella ha aceptado.

La consideración de nuestros procedimientos graduales
nos vindicará de las ruidosas acusaciones de severidad,
y nuestra propia defensa justa y necesaria nos obliga
(habiendo fallado otros medios) a sostener la espada,
a la que estas personas se han abalanzado violenta y deliberadamente,
convirtiéndose así en _felons de se_ +++[+++es decir,
asesinos de sí mismos]. Que esto pudo haberse evitado,
y preservado la ley soberana y seguridad del pueblo, nuestros anteriores procedimientos,
así como también el perdón de Mary Dyar por una insignificante intercesión,
demostrarán manifiestamente, y se verá que deseábamos sus vidas ausentes,
en lugar de sus muertes presentes.

Edward Rawson, Secretario.

En esta reivindicación,
en la que los Cuáqueros (que siempre fueron un pueblo inofensivo,
y nunca pusieron resistencia con armas externas) son comparados
con los Anabaptistas amotinados y revoltosos de Munster,
también se dice de ellos que encontraron entrada "`por la puerta trasera.`"
Esto se refiere a algunos que inesperadamente entraron a Nueva Inglaterra por tierra,
dado que no pudieron encontrar la oportunidad de llegar por mar,
porque los capitanes de barcos, temiendo la severidad de las leyes de Boston,
no estaban dispuestos a llevar a ningún Cuáquero allí. Esto le dio oportunidad
a Thomas Thirstone (quien habiendo estado ya en Boston,
había sido enviado lejos a bordo de un barco) a pensar en otros medios;
pues al hallarse movido en espíritu a regresar,
él y Josiah Coale (de quien se ha hecho mención antes,
y de quien se puede hablar más adelante) fueron de Inglaterra a Virginia,
desde donde ellos, junto con un tal Thomas Chapman,
viajaron varios cientos de millas a pie a través de vastos páramos y bosques,
y para finalmente llegar a Nueva Inglaterra.
Esto hizo que los perseguidores de allí se asombraran,
porque ellos pensaban que eso era imposible,
pues consideraban esos parajes infranqueables para cualquiera que no fuera de los nativos.
Su viaje, no obstante, fue muy duro;
porque no sólo pasaron hambre y frío (pues era invierno),
sino que también estuvieron en peligro de ser devorados por animales salvajes,
y de perecer en pantanos y ciénagas desconocidos.
Pero fueron preservados por la mano Todopoderosa;
aunque este maravilloso viaje fuera presentado por estos
perseguidores de Nueva Inglaterra como un desprecio criminal.

Me parece que la mencionada justificación, publicada en forma impresa,
e igualmente respondida, fue dada antes de que Mary Dyar fuera ejecutada.
Pero después de su muerte,
la Corte General de Boston le envió un reporte al rey Carlos II,
firmado por su gobernador John Endicot, para justificar sus crueles procedimientos.
En este reporte dicen, que ellos habían escogido el culto puro de la Escritura,
con una buena consciencia, en ese remoto paraje entre los paganos,
en lugar de los placeres de Inglaterra sujetos a
la imposición de la entonces jerarquía predominante,
los que no podrían disfrutar sin ofender sus consciencias.
En cuanto a los Cuáqueros,
dijeron que ellos eran abiertos blasfemos y que incitaban
a otros a apartarse de la gloriosa Trinidad,
de Cristo el Señor y del bendito evangelio;
que eran abiertos enemigos del gobierno mismo,
y promotores malignos de doctrinas que tendían directamente
a socavar tanto a la iglesia como al estado.
Además, dijeron que para su propia seguridad,
finalmente se habían visto obligados a dictar sentencia
de destierro contra ellos so pena de muerte,
ya que en la consciencia,
el magistrado se juzgaba a sí mismo designado para la defensa de todos,
y mantener la paz con la punta de la espada dirigida hacia ellos;
y que esta no dañaría a los que fueran advertidos por ella.
Pero que el hecho de que los Cuáqueros se abalanzaran había sido un acto propio de ellos,
y un crimen que había hecho caer su sangre sobre sus propias cabezas.

Si hubieran podido hacer que el rey creyera esto, lo habrían hecho de buena gana,
pero él tenía demasiado sentido común para dejar que se le impusieran así,
aunque hicieron todo lo posible para evitar que oyera a la otra parte, diciéndole:
"`Que el rey no escuche las palabras de los hombres; tus siervos son hombres veraces,
temerosos de Dios y del rey, y no dados al cambio.
Somos celosos del gobierno y del orden; no sediciosos para los intereses del César.`"

Por muy suave y plausible que pareciera esto, no pudo resistir la prueba;
y Edward Burrough, quien respondió de manera impresa, se dirigió al rey así:

Oh, rey,
la razón de presentarte estas consideraciones es muy urgente y de gran necesidad,
es decir, en nombre de la sangre inocente,
y espero que mi obra encuentre tal favor en ti,
como para inducirte a su lectura y seria consideración.

E+++.+++ Burrough, examinando entonces todas las pretendidas razones de ellos,
también le describió al rey cómo algunos de estos demandantes, un tiempo antes de esto,
no habían dudado en escribir en una carta desde Boston a un tal Gordon:
"`Hay más peligro en estos Cuáqueros, para perturbar y vencer Inglaterra,
que en el rey de Escocia^
footnote:[Es decir, hablando de Carlos Estuardo II,
cuando había sido declarado rey de Escocia, pero no había sido coronado en Inglaterra.]
y en todos los príncipes Católicos de Alemania;`" lo cual claramente denotaba,
que ellos consideraban al rey un perturbador de Inglaterra,
a quien contaban entre los príncipes Católicos de Alemania.
Lo que E. Burrough obtuvo del rey para sus amigos, lo veremos más adelante.

Pero primero vuelvo a William Leddra,
a quien dejamos en prisión. El 9 del mes Primero de este año,
fue llevado al Tribunal de Asistentes encadenado y con el tronco en sus talones.
Cuando él le preguntó al carcelero cuándo pensaba quitarle los grilletes de sus piernas,
el carcelero le respondió ásperamente: "`Cuando vayas a ser colgado.`"
Entonces fue llevado al estrado y los gobernantes le dijeron,
hablando de la ley de ellos, que había sido declarado culpable, y por lo tanto,
debía morir.
Él preguntó: "`¿Qué mal he hecho?`"
La respuesta fue, que su propia confesión valía como mil testigos.
Preguntó, cuál había sido su confesión, y ellos le respondieron,
que él había reconocido a los Cuáqueros que habían sido condenados a muerte,
y declarado que ellos eran inocentes.
Además, que no se había quitado el sombrero en la corte,
y había hablado de "`ti`" y "`tú.`" Entonces William les dijo:
"`¿Ustedes me van a condenar a muerte por hablar en inglés, y por no quitarme mi ropa?`"
A esto, el general de división Denison respondió:
"`Un hombre puede hablar de traición en inglés.`" Y William replicó:
"`¿Es traición hablarle de "`ti`" y "`tú`" a una persona?`"
Pero nadie respondió,
solamente Simon Broadstreet (uno de los miembros
del tribunal) le preguntó si se iría a Inglaterra.
A lo que él respondió: "`No tengo negocios ahí.`" Con lo cual, Broadstreet,
señalando hacia las horcas dijo:
"`Entonces irás en esa dirección.`" A lo que William respondió: "`¿Qué,
me van a condenar a muerte por respirar el aire en
su jurisdicción? Por lo que tienen contra mí,
apelo a las leyes de Inglaterra para mi juicio, y si soy hallado culpable por ellas,
no rehúso morir.`"
No se tomó nota de esto, pero en lugar de ello,
se esforzaron por persuadirlo a que se retractara
de su error (como lo llamaban ellos) y se conformara;
ante lo cual, él, con una grave benevolencia respondió:
"`¡Qué! ¿Y unirme a unos asesinos como ustedes?
Entonces todo el que me encuentre dirá: '`He aquí,
el hombre que ha abandonado al Dios de su salvación.`'`"

Mientras se celebraba el juicio de W. Leddra, Wenlock Christison,
quien ya había sido desterrado so pena de muerte, entró en la corte.
Esto desanimó sus espíritus a tal punto,
que por un lapso de tiempo hubo silencio en la corte; pero finalmente,
uno del sangriento consejo gritó: "`¡Aquí está otro, llévenlo al estrado!`"
A lo que el alguacil, secretario Rawson dijo: "`¿No es tu nombre Wenlock Christison?`"
"`Sí,`" dijo Wenlock.
"`Bien,`" dijo el gobernador, John Endicot,
"`¿qué estás haciendo aquí? ¿No fuiste desterrado bajo pena de muerte?`"
A esto Wenlock respondió: "`Sí, lo fui.`"
Y a la pregunta, qué estaba haciendo ahí, respondió:
"`He venido para advertirles que no derramen más sangre inocente;
porque la sangre que han derramado,
ya clama delante del Señor Dios para que la venganza caiga sobre ustedes.`"
Después de lo cual se dijo: "`¡Llévatelo, carcelero!`"

Después de que a W. Leddra se le dijo que en la última corte
general se le había dado la libertad de irse a Inglaterra,
o de salir de su jurisdicción; y que al prometer hacerlo y no regresar más,
podía salvar su vida, respondió: "`No estoy en mi propia voluntad,
sino en la voluntad del Señor. Si tengo mi libertad, me iré,
pero no puedo hacerles esa promesa.`"
Pero esto estuvo tan lejos de producirles satisfacción,
que procedieron a pronunciar la sentencia de muerte contra él; hecho lo cual,
fue llevado de la corte a la prisión de nuevo,
donde el día antes de su muerte les escribió a sus amigos la siguiente carta:

Muy queridos e internamente amados,

Las dulces influencias de la Estrella de la mañana,
como un torrente que destila en mi inocente habitación,
me han llenado de tal manera del gozo del Señor en la hermosura de la santidad,
que mi espíritu está como si no habitara en un tabernáculo de barro,
sino como si hubiera sido completamente tragado en el seno de la eternidad,
de la que recibió su ser.

¡Ay, ay! ¿Qué le puede hacer la ira y el espíritu del hombre, que desea envidiar,
agravado por el calor y la fuerza del rey de las langostas que salió del pozo,
a uno que está escondido en los lugares secretos del Todopoderoso,
o a los que están recogidos bajo las alas de salvación del Príncipe de Paz?
Bajo cuya armadura de luz podrán resistir en el día de la prueba,
teniendo puesta la coraza de justicia y la espada del Espíritu,
que es el arma de guerra de ellos contra la maldad espiritual, principados,
potestades y gobernantes de las tinieblas de este mundo, tanto dentro como fuera.

¡Oh, mis amados!
Esperé como una paloma en las ventanas del arca, y permanecí quieto en esa vigilia,
hasta que el Amo (sin el cual yo no podía hacer nada)
me recompensó con la plenitud de Su amor en Su venida,
en la que mi corazón se ha regocijado,
para que en el amor y vida de Dios pueda hablarles unas pocas palabras,
selladas con el Espíritu de la promesa,
y para que el olor de estas sea olor de vida para sus vidas,
y un testimonio en ustedes de mi inocente muerte.
Y si hubiera permanecido completamente callado,
y el Señor no hubiera abierto mi boca para ustedes, aun así,
Él habría abierto sus corazones y ahí habría sellado
mi inocencia con las corrientes de vida,
por las que todos somos bautizados en el cuerpo que está en Dios,
en Cuya presencia hay vida.
Mientras permanezcan en esta vida, se mantendrán en la columna y baluarte de la verdad,
porque sabiendo que la vida es la verdad y el camino, no den un paso sin ella,
no sea que sólo le den vueltas a una montaña en el desierto;
porque hay un tiempo para todo.

Como la corriente de la marea del océano llena cada arroyo y ramificación de este,
y luego se retira hacia su propio ser y plenitud, y deja un olor tras ella,
así fluyen la vida y virtud de Dios en cada uno de sus corazones,
a quienes Él ha hecho partícipes de Su naturaleza divina;
y cuando se retiran sólo un poco, dejan un dulce olor detrás de ellas,
de modo que muchos pueden decir que están "`limpios por la palabra que os he hablado,`"^
footnote:[Juan 15:2]
en cuya inocente condición ustedes pueden ver lo que son en la presencia de Dios,
y lo que son sin Él.

Por tanto, mis queridos hermanos, que el disfrute de la vida sea la única esperanza,
gozo y consolación de ustedes;
que el hombre de Dios huya de esas cosas que quieren apartar la mente de la cruz,
porque entonces el olor de la vida será enterrado.
Y aunque algunos hablen de las experiencias que recibieron en la vida,
si la vida está velada,
y el olor que es dejado atrás es lavado por las frescas inundaciones de la tentación,
entonces la condición que anteriormente disfrutaron en la vida y de la que se jactaron,
será como el maná que fue recogido ayer, sin ningún buen aroma o sabor.
Porque al hombre le fue bien, sólo mientras permaneció en la vida de inocencia,
pero al ser expulsado de la presencia del Señor a la tierra, ¿de qué puede jactarse?

Y aunque ustedes saben estas cosas,
y muchos de ustedes saben más de lo que yo puedo decir;
por el amor y el celo que tengo por la verdad y el honor de Dios,
y el tierno deseo de mi alma hacia los que son jóvenes,
a fin de que puedan leerme en el Espíritu del que escribo,
para fortalecerlos contra las artimañas de la sutil serpiente que engañó a Eva, digo:
Permanezcan en la vigilancia interior, en el temor del Señor,
el cual es la entrada misma a la sabiduría,
y el estado en el que están preparados para recibir los
secretos del Señor. Tengan hambre y sed con paciencia;
no se cansen, ni duden.
Permanezcan quietos y cesen de sus propias obras,
y a su debido tiempo entrarán en el reposo y sus ojos contemplarán Su salvación,
cuyos testimonios son seguros y completamente justos.
Dejen que sean como una marca sobre sus brazos, y como joyas alrededor de sus cuellos,
para que otros vean lo que el Señor ha hecho por sus almas.
Confiésenlo delante de los hombres, sí, delante de Sus mayores enemigos,
y no teman lo que ellos puedan hacerles; porque mayor es el que está en ustedes,
que el que está en el mundo.
Él los vestirá con humildad,
y en el poder de Su mansedumbre reinarán sobre la
furia de sus enemigos en el favor de Dios.

Mientras permanecen ahí, en fe, son la sal de la tierra; y muchos,
al ver sus buenas obras,
puede que glorifiquen a Dios en el día de su visitación. Por tanto,
tengan cuidado de recibir lo que no han visto en la luz, no sea que oigan al enemigo.
Lleven todas las cosas a la luz, para que se pruebe si son hechas en Dios.
El amor al mundo, los deseos de la carne y la vanidad de los ojos, están fuera de la luz,
están en el mundo.
Por tanto, tengan sus vasos en toda santificación y honor,
y dejen que su ojo mire directo a la marca.
Aquel que los ha llamado es santo, y si hay en ustedes un ojo que peca,
arránquenlo y tírenlo.
No dejen que ninguna tentación se apodere de ustedes, porque si lo hacen,
esta los apartará del favor de Dios, y ese será un estado triste;
porque si no se posee gracia, no hay seguridad de salvación. Por gracia son salvos;
y que la experiencia de esta gracia sea suficiente para ustedes,
a la cual los encomiendo a todos mis queridos amigos, y en ella permanezco,

El hermano de ustedes,

William Leddra.

Cárcel de Boston, 13 del mes Primero, 1661.
+++[+++El día anterior a su sufrimiento]

Al día siguiente que se escribió esta carta, se llevó a cabo la ejecución de W. Leddra,
el 14 del mes Primero.
Una vez terminada la lectura, el gobernador John Endicot,
acudió con una guardia de soldados a la prisión,
donde se le quitaron los grilletes a Leddra (en concordancia
con lo que en una ocasión había dicho el carcelero,
como ha sido relatado antes),
con los que había estado encadenado a un tronco noche y día durante el frío invierno.
Entonces, William se despidió de Wenlock Christison,
y de otros que estaban entonces atados, y salió a la matanza,
rodeado de una guardia para evitar que hablara con sus amigos.

Edward Wharton, un habitante de Salem y también desterrado so pena de muerte,
al ver esto y hablar en contra, uno del grupo le dijo: "`¡Oh, Edward serás el próximo!`"
A lo que el capitán Oliver añadió: "`Si dices una palabra, te taparé la boca.`"
Luego, W. Leddra fue llevado al pie de la escalera, donde lo ataron,
y cuando estaba a punto de subir se despidió de su amigo E. Wharton, a quien le dijo:
"`Todos los que quieran ser discípulos de Cristo, deben tomar la cruz.`"
Estando en la escalera alguien le dijo: "`William, ¿tienes algo que decirle a la gente?`"
Y acto seguido dijo lo siguiente: "`Por el testimonio de Jesús,
y por testificar contra los engañadores y engañados, he sido traído aquí para morir.`"

Esto conmovió tanto a la gente, que muchos fueron enternecidos, pero para apagar esto,
el sacerdote Allen les dijo a los espectadores: "`Pueblo,
no quiero que se extrañen de ver a un hombre tan dispuesto a morir;
porque esto no es nuevo.
Ustedes pueden leer lo que dijo el apóstol,
que muchos serían entregados a fuertes delirios, y que incluso,
se atreverían a morir por ello.`"
Pero no dijo dónde había dicho esto el apóstol,
ni yo lo he encontrado en ningún lugar de las Sagradas Escrituras;
aunque sé que Pablo dijo en Romanos 5:7,
"`pudiera ser que alguno osara morir por el bueno.`"
Pero parece, que a Allen le bastaba hacer a Leddra odioso para la multitud, que con todo,
seguía alegre.
Porque mientras el verdugo le ponía la soga al cuello, se le oyó decir:
"`Te encomiendo mi justa causa a ti, oh, Dios.`"
Entonces, al decírsele al verdugo que se apresurara, W. Leddra,
al vuelco de la escalera gritó. "`¡Señor Jesús recibe mi espíritu!`"
Así fue colgado y sus días terminados.

El verdugo cortó la soga,
y para que el cadáver no fuera tratado tan bárbaramente
como los de William Robinson y Marmaduke Stevenson (que,
debido a que nadie los sostuvo cuando se cortaron las sogas,
cayeron al suelo tan violentamente que el cráneo de W. Robinson se quebró),
Edward Wharton, John Chamberlain y otros,
cogieron el cuerpo en sus brazos y lo pusieron en el suelo.
El verdugo lo despojó entonces de sus ropas, y tras hacerlo,
dijo que era un hombre apuesto, como en verdad lo era.
Luego, los amigos de William cogieron el cuerpo, lo pusieron en un ataúd y lo sepultaron.
Para mayor confirmación de lo que se ha relatado aquí,
se puede añadir la siguiente carta de uno de los espectadores,
que por accidente estaba ahí:

Al señor George Lad, capitán del "`América`" de Dartmouth, ahora en Barbados.
Boston, 26 de Marzo, 1661.

El 14 de este mes, un tal William Leddra fue ejecutado.
La gente del pueblo me dijo que él se pudo haber ido si lo hubiera deseado;
pero cuando investigué más a fondo,
oí al alguacil decir que él había estado encadenado en prisión,
desde el momento que fue condenado hasta el día de
su ejecución. Yo no soy de su opinión religiosa,
sin embargo, verdaderamente creo que el Señor se manifestaba poderosamente en ese hombre.
Fui a ver a uno de los magistrados de Cambridge,
que había sido parte del jurado que lo había condenado, como él mismo me dijo,
y le pregunté por cuál regla lo había hecho.
Él me respondió: "`Él era un insolente, muy insolente.`"
"`Pero,`" le dije, "`¿qué tiene que ver esto con la pregunta?
¿Dónde está tu regla?`"
Me dijo que había abusado de la autoridad.

Entonces me dirigí a William Leddra,
y le pregunté si no consideraba una infracción de la norma,
despreciar y subestimar la autoridad.
Le dije que Pablo le había dado a Festo el título de honor, aunque era un pagano.
(No digo que estos magistrados sean paganos).
Entonces, cuando el hombre estaba en la escalera, me miró y me llamó amigo, y dijo:
"`Sepas que en este día yo estoy dispuesto a ofrecer mi vida por el testimonio
de Jesús.`" Luego les pedí permiso a los oficiales para hablar,
y dije: "`Caballeros, soy un extraño, tanto para sus personas como para su país,
y sin embargo, amigo de ambos.`"
Luego grité en voz alta: "`¡Por el amor del Señor, no le quiten la vida a este hombre;
sino recuerden el consejo de Gamaliel a los judíos:
'`si esto es de lo hombres se desvanecerá, pero si es de Dios, no lo podrán destruir.
Tengan cuidado de no ser hallados luchando contra Dios`'!`" Y el capitán dijo,
"`¿Por qué no viniste a la prisión?`" "`La razón fue,`" dije,
"`porque oí que el hombre se podía ir si le placía;`" por lo tanto, lo llamé y le dije:
"`Baja, William, puedes irte si quieres.`"
Entonces el capitán Oliver dijo que no era así;
y me preguntó qué tenía que ver yo con esto.
Luego me ordenó que me fuera, y les dije: "`Estoy dispuesto a irme,
porque no soporto ver esto.`"
Cuando estaba en el pueblo, algunos parecían comprender mi aflicción,
pero les dije que ellos no tenían orden de la palabra de Dios,
ni precedente de nuestro país, ni poder de su majestad para colgar a este hombre.

Sigo siendo tu amigo,

Thomas Wilkie.

Una vez ejecutado William Leddra, se resolvió ponerle fin a Wenlock Christison.
Por tanto, fue llevado de la prisión al tribunal en Boston,
donde el gobernador John Endicot y el representante del gobernador, Richard Bellingham,
estando ambos presentes, le dijeron: "`A menos que renuncies a tu religión,
de seguro morirás.`" Pero en lugar de acobardarse dijo con inquebrantable valor: "`No,
no cambiaré mi religión, ni buscaré salvar mi vida,
ni tampoco pretendo negar a mi Maestro;
pero si pierdo mi vida por causa de Cristo y la predicación del evangelio,
salvaré mi vida.`"
Esta noble resolución frenó de manera tal a los perseguidores,
que no continuaron con el juicio, sino que lo enviaron a prisión de nuevo.
Y cuando alguien dijo que William Leddra estaba muerto, cierta persona le dijo a Wenlock:
"`¡Oh, tu turno es el siguiente!`"
A lo que él replicó gravemente:
"`Sea hecha la voluntad del Señor,`" mostrando así su total rendición.

Encerrado de nuevo en la cárcel, fue mantenido allí casi hasta el mes Cuatro.
Pero cuando finalmente se instaló el tribunal,
apareció un espíritu de confusión y se levantó una división entre varios de los miembros.
Porque aunque la mayoría estaba a favor de seguir el mismo curso con él,
como el que habían tomado con los que ya habían sido ejecutados,
aun así varios no querían consentirlo.
Y como los sucesos naturales a veces provocan reflexiones entre las personas observadoras,
así sucedió aquí,
porque durante sus deliberaciones con respecto a cómo lidiar
con Wenlock Christison (que duraron el lapso de dos semanas),
el sol no brilló, cosa que en esa estación era algo extraordinario.
Esto dio oportunidad a que algunos dijeran, que el sol se había ocultado de ellos,
por aborrecer ese sangriento asunto.

Pero después de muchos debates,
el sanguinario consejo finalmente llegó a un acuerdo y Wenlock fue llevado al estrado.
Ahí el gobernador John Endicot le preguntó: "`¿Qué tienes que decir a tu favor?
¿Por qué no debes morir?`"
Él respondió: "`No he hecho nada digno de muerte.
Si lo he hecho, no rehúso morir.`"
Ante esto otro dijo: "`Tú has venido entre nosotros en rebelión,
que es como pecado de brujería y debes ser castigado.`"
De esto es evidente,
cuán perversamente aplicaban las Sagradas Escrituras estos
perseguidores sedientos de sangre a sus crueles fines,
y por lo tanto,
hacían un uso equivocado de las palabras del profeta
Samuel a Saúl. A esta falsa conclusión Wenlock respondió:
"`No vine entre ustedes en rebelión, sino en obediencia al Dios del cielo;
y ustedes lo sabrán un día,
cuando ustedes y todos los hombres deban dar cuenta de las obras hechas en el cuerpo.
Tengan cuidado,`" continuó, "`porque no pueden escapar de los justos juicios de Dios.`"
Entonces, el general de división Adderton dijo: "`Tú pronuncias ayes y juicios,
y los que vinieron antes que tú pronunciaron ayes y juicios,
pero los juicios del Señor Dios no han venido sobre nosotros aún.`"

Cuán insolente y duro de corazón puede llegar a ser el hombre,
que no duda en desafiar al Altísimo.
Pero antes de que corramos las cortinas de este escenario,
veremos el trágico final de este Adderton, quien recibió esta respuesta de Wenlock:
"`No se enorgullezcan, ni dejen que sus espíritus se levanten.
Dios no hace más que esperar que se llene la medida de iniquidad de ustedes,
y hayan corrido su impía carrera.
Entonces, la ira de Dios vendrá sobre ustedes hasta el extremo.
Y en cuanto a tu parte,
ya cuelga sobre tu cabeza y está a punto de ser derramada sobre ti,
y vendrá como ladrón en la noche, repentinamente, cuando no pienses en ello.`"

Entonces Wenlock preguntó: "`¿Por cuál ley me van a sentenciar a muerte?`"
La respuesta fue: "`Tenemos una ley, y por nuestra ley tienes que morir.`"
"`Así le dijeron los judíos a Cristo,`" replicó Wenlock: "`'`Nosotros tenemos una ley,
y según nuestra ley debe morir.`' ¿Quién los autorizó para hacer esa ley?`"
A lo que uno de los miembros del tribunal respondió: "`Tenemos una patente,
y nosotros somos los titulares de la patente, por tanto,
tenemos el poder de hacer leyes.`"
Entonces Wenlock preguntó de nuevo:
"`¿Qué? ¿Ustedes tienen poder para hacer leyes que son ofensivas a las leyes de Inglaterra?`"
"`No,`" dijo el gobernador.
"`Entonces,`" dijo Wenlock, "`han ido más allá de sus límites y han perdido su patente;
y eso es más de lo que pueden responder.
¿Son ustedes súbditos del rey, sí o no?`"
"`¿Qué bien te hará esto?,`" replicó el secretario.
"`Si lo son,`" respondió Wenlock, "`entonces, díganlo;
porque en la petición de ustedes al rey, querían que él los protegiera,
y que pudieran ser dignos de arrodillarse entre sus leales súbditos.`"
A esto uno de ellos dijo: "`Sí, somos súbditos.`"
"`Bien,`" dijo Wenlock, "`yo también, y por lo que sé, soy tan buen súbdito como ustedes,
si no es que mejor; porque si el rey conociera sus corazones como los conoce Dios,
vería que ellos están tan corrompidos hacia él como lo están hacia Dios.
Por tanto, al ver que ustedes y yo somos súbditos del rey,
exijo ser juzgado por las leyes de mi propia nación.`" Se le respondió:
"`Serás juzgado por un tribunal y un jurado;`" pues parece que empezaron
a tener miedo de seguir el curso anterior de juicio sin jurado,
por ser contrario a las leyes de Inglaterra.

Pero Wenlock dijo: "`Eso no está de acuerdo con la ley; porque yo nunca he oído,
ni he leído de alguna ley en Inglaterra, para colgar Cuáqueros.`"
A esto el gobernador replicó, que había una ley para colgar Jesuitas.
Wenlock respondió: "`Si ustedes me condenan a muerte,
no es porque yo vaya bajo el nombre de Jesuita, sino de Cuáquero.
Por tanto, apelo a las leyes de mi nación.`" Pero en lugar de tomar nota de esto,
uno dijo: "`Tú estás en nuestras manos, y has quebrantado nuestra ley,
y nosotros te juzgaremos.`"
Wenlock apeló de nuevo a la ley de su propia nación; sin embargo, el jurado fue llamado,
salió y regresó rápido, dando el veredicto de "`culpable.`"
Ante esto, el secretario dijo, "`Wenlock Christison, levanta tu mano.`"
"`No lo haré,`" dijo Wenlock, "`estoy aquí y puedo oírte.`"
Entonces el secretario gritó: "`¿Culpable o no culpable?`"
"`Niego toda culpa,`" replicó Wenlock,
"`porque mi consciencia está limpia ante los ojos de Dios.`"
Pero el gobernador dijo: "`El jurado te ha condenado.`"
Wenlock, respondió: "`El Señor me justifica; ¿quiénes son ustedes que condenan?`"

Entonces, votaron con respecto a la sentencia de muerte,
pero estaban en cierto modo confundidos, y varios no pudieron declararlo digno de muerte.
Al ver el gobernador esa división, dijo:
"`¡Yo podría encontrar en mi corazón ir a casa!,`"
y enfurecido arrojó algo sobre la mesa.
Esto hizo que Wenlock gritara: "`Sería mejor para ti estar en casa que aquí,
porque estás a punto de hacer una obra maldita.`"
Entonces el gobernador volvió a someter al tribunal a votación,
pero esta se hizo de forma confusa,
lo cual indignó tanto al gobernador que se levantó y dijo:
"`Ustedes que no quieren consentir, háganlo constar.
Gracias a Dios yo no tengo miedo de dar la sentencia.`"

Así vemos que estar ebrio de sangre, no apaga la sed de sangre;
pues el gobernador Endicot, al ver que otros no estaban dispuestos a votar,
se precipitó a dictar sentencia él mismo, y dijo: "`¡Wenlock Christison,
escucha tu sentencia: Debes regresar al lugar de donde has venido,
y de ahí al lugar de ejecución, y ahí debes ser colgado hasta que estés muerto, muerto,
muerto!`"
A lo que Wenlock, dijo: "`Sea hecha la voluntad del Señor,
en Cuya voluntad he venido entre ustedes, y en Cuyo consejo permanezco,
al sentir Su poder eterno que me sostendrá hasta el último suspiro.`"
Además gritó: "`Sepan todos ustedes, que si tienen poder de quitarme la vida,
mi alma entrará en el reposo eterno y paz con Dios,
donde ustedes nunca llegarán. Y si tienen poder de
quitarme la vida (poder que pongo en duda),
creo que nunca más volverán a quitarle la vida a un Cuáquero; tomen nota de mis palabras.
No piensen que pueden cansar al Dios vivo quitándoles la vida a Sus siervos.
¿Qué ganan ustedes con ello?
Porque después del último hombre que ejecutaron, cinco más han llegado en su lugar.
Y si ustedes tienen poder de quitarme la vida,
Dios puede levantar la misma Semilla en diez de Sus siervos,
y enviarlos entre ustedes en mi lugar, para que tengan tormento sobre tormento,
que es la porción de ustedes; porque no hay paz para el impío, dice el Señor.`"

La santa confianza con la que él pronunció estas palabras
muestra (y lo que sigue lo manifiesta claramente),
que algo sobrenatural estaba contenido en ellas.
Y es notable, que entre los Cuáqueros encarcelados entonces,
había varios que habían sido desterrados bajo pena de muerte,
entre estos también Elizabeth Hooton y un tal Edward Wharton,
quien había permanecido en su casa en contra de su sentencia de destierro.

Después de recibir la sentencia de muerte, Wenlock fue llevado de nuevo a prisión,
donde tras cinco días de estar detenido,
llegaron un alguacil y un oficial con una orden del tribunal, para liberarlo a él,
junto con veintisiete de sus amigos que estaban entonces
en prisión por el testimonio de la Verdad;
y diciendo, que el tribunal les había ordenado darle a conocer su nueva ley.
"`¿Qué significa esto?,`" dijo Wenlock, "`¿tienen una nueva ley?`"
"`Sí,`" dijeron.
"`Entonces ustedes han engañado al pueblo,`" dijo Wenlock.
"`¿Por qué?,`" preguntaron ellos.
"`Porque,`" respondió, "`ustedes le dijeron que la horca era su última arma,
y que su ley era buena y sana,
hecha para la paz de ustedes y la salvaguarda de
su país. ¿Se han debilitado ahora sus manos?
El poder de Dios está sobre todos ustedes.`"

Así fueron abiertas las puertas de la prisión,
y Wenlock junto con veintisiete más de sus amigos, como se dijo antes, fueron liberados,
salvo dos de ellos, a saber, Peter Pearson y Judith Brown, quienes,
desnudos hasta la cintura y atados a una carreta,
fueron azotados a través de la ciudad de Boston con veinte azotes cada uno.

Ahora bien,
aunque no mucho después de esto llegó una orden del rey (como se mencionará en breve),
en la que se les ordenaba a estos perseguidores a desistir de ejecutar a los Cuáqueros,
parece que ellos ya habían percibido el disgusto del rey,
quien tenía la intención de detener su sangrienta carrera.
Pues habiendo obtenido un libro escrito por George Bishop
que relataba la cruel persecución en Nueva Inglaterra,
leyó en él un pasaje sobre el general de división Denison, quien,
para desanimar a los que se quejaban de su malvado proceder, había dicho:
"`Este año ustedes irán a quejarse al Parlamento,
y el año siguiente ellos enviarán a ver cómo está todo aquí;
y el tercer año el gobierno será cambiado.`"
El rey le prestó mucha atención a esto, y llamando a los lores para que lo oyeran dijo:
"`He aquí, estos son mis buenos súbditos de Nueva Inglaterra, pero yo los detendré.`"

No pasó mucho tiempo antes de que se le presentara una oportunidad,
porque habiendo llegado a Inglaterra la noticia de la muerte de William Leddra,
con información del peligro que corrían otros de seguir el mismo camino,
sus amigos lo tomaron a pecho.
Y Edward Burrough, tras obtener audiencia con el rey le dijo:
"`Hay una vena de sangre inocente abierta en tu dominio, la cual si no es detenida,
invadirá todo.`"
A esto el rey replicó: "`Pero yo detendré esa vena.`"
Entonces Burrough quiso que lo hiciera rápidamente; "`porque no sabemos,`" dijo él,
"`cuántos vayan a ser ejecutados pronto.`"
El rey les dijo a algunos de los presentes: "`Llamen al secretario y lo haré en seguida.`"
El secretario llegó, y un escrito judicial fue concedido inmediatamente.
Uno o dos días después regresó a ver al rey para pedirle que despachara el asunto,
y el rey le dijo que hasta el momento no había tenido
ocasión de enviar un barco a Nueva Inglaterra;
pero que si ellos querían enviar uno, podrían hacerlo tan pronto como pudieran.
Edward Burrough le preguntó al rey entonces,
si él estaría dispuesto a conceder su representación
a una persona identificada como un Cuáquero,
para llevar el escrito judicial a Nueva Inglaterra.
El rey respondió: "`Sí, a quien tú desees.`"
Con lo cual, E. Burrough nombró a un tal Samuel Shattock,
que siendo habitante de Nueva Inglaterra,
había sido desterrado bajo pena de muerte si alguna vez regresaba.
En consecuencia, el rey le concedió la representación a él,
con plenos poderes de llevar el escrito, que era como sigue:

Charles R.

Leal y bien amado, te saludamos.
Habiendo sido informado de que varios de nuestros súbditos entre ustedes,
llamados Cuáqueros, han sido y son encarcelados por ustedes,
de los cuales algunos han sido ejecutados,
y otros (como se nos ha descrito) corren el peligro de padecer lo mismo,
nos ha parecido oportuno indicar nuestro agrado a favor de ellos para el futuro,
y por la presente requerimos,
que si hay alguna de estas personas llamadas Cuáqueras entre ustedes,
que ya esté condenada a sufrir la muerte, u otro castigo corporal,
o que esté encarcelada y sujeta a la misma condena,
te abstengas de seguir adelante con ello.
Por el contrario,
debes enviar a dichas personas de inmediato (ya sea condenadas
o encarceladas) a este nuestro reino de Inglaterra,
junto con los respectivos crímenes u ofensas que se les imputan,
con el fin de que se tome con ellos el curso conforme a nuestras leyes y deméritos.
Para ello, esta carta será para ti suficiente garantía y descargo.

Dado en nuestro tribunal en Whitehall, el 9 de Septiembre de 1661,
en el año trece de nuestro reinado.

Por mandato de su majestad,

William Morris.

El encabezado decía:

A nuestro fiel y amado John Endicot, Esq,
y a todos y a cualquier otro gobernador o gobernadores
de nuestras plantaciones en Nueva Inglaterra,
y a todas las colonias que pertenecen a ella, que son ahora o serán en el futuro;
y a todos y a cada ministro y funcionario de nuestras mencionadas plantaciones y colonias,
dentro de la tierra de Nueva Inglaterra.

Así de favorable se manifestó el rey;
y en Inglaterra la persecución por religión se detuvo un poco,
pero esto fue sólo un tipo de respiro.
G+++.+++ Fox el joven, un hombre de excelentes cualidades y gran audacia,
previó una tormenta inminente;
y para que ningún descuido pudiera entrar entre sus amigos,
en el mes Cuatro les escribió la siguiente exhortación:

Lo que mi Padre celestial ha determinado que hagan estos hombres,
ningún hombre lo puede detener.
¡Oh, que la paciencia sea la morada de todos los que conocen Su nombre,
y se sometan a Su voluntad aquellos que Él ha llamado! ¡Estén quietos, no luchen,
sino beban la copa que nuestro Padre permite que
se nos dé! Sé que será amarga para algunos,
pero quienquiera que luche contra ella sufrirá pérdida y vergüenza.
Porque el Señor probará aún más a Su pueblo,
hasta que sea completa y claramente manifiesto quiénes son aprobados ante Sus ojos.
Esto lo hará ciertamente; por tanto,
no dejen que la presente calma engendre en alguno una seguridad equivocada, porque,
he aquí, el día se apresura y viene velozmente, cuando otra tormenta debe levantarse;
y será en vano huir a los altos cedros o fuertes robles en busca de refugio,
porque nada sino el nombre del Señor puede preservar en ese día.

George Fox, el joven.

George Fox el joven, no se equivocó en esta exhortación cuando dijo,
"`el día se apresura cuando otra tormenta debe levantarse,`" como veremos dentro de poco;
pero primero debemos echar un vistazo a las cosas en América.

Tras ser obtenido el escrito judicial para los gobernantes de Nueva Inglaterra,
como se ha dicho,
se consideró necesario un rápido despacho para enviarlo ahí. Y
habiendo sido autorizado por el rey que Samuel Shattock lo llevara,
se llegó a un acuerdo por trescientas libras (con
bienes o sin ellos) con un tal Ralph Goldsmith,
que era capitán de un buen barco y uno de los llamados Cuáqueros,
de zarpar en diez días. Él preparó todo inmediatamente para zarpar,
y con un próspero vendaval llegaron en casi seis semanas a la ciudad de Boston,
en Nueva Inglaterra,
el Primer-día. Al ver los concejales del pueblo entrar
en la bahía un barco con los colores ingleses,
no tardaron en subir a bordo y preguntar por el capitán.
Ralph Goldsmith les dijo que él era el comandante.
Entonces ellos le preguntaron si tenía cartas, y él dijo: "`Sí.`" Con lo cual,
le preguntaron si las entregaría, pero él dijo: "`No; hoy no.`"
Entonces bajaron a tierra e informaron que había un barco lleno de Cuáqueros,
y que entre ellos estaba Samuel Shattock, de quien sabían que según su ley,
podía ser condenado a muerte por regresar después del destierro.
Pero ellos no sabían su encargo ni autoridad.

Todo se mantuvo quieto y no se le permitió a nadie del grupo que bajara a tierra ese día,
y a la mañana siguiente Samuel Shattock (el representante
del rey) y Ralph Goldsmitth (comandante de la nave),
fueron a tierra.
Luego, mandaron de regreso al barco a los hombres que los habían llevado a tierra,
y ellos dos atravesaron la ciudad hasta la puerta del gobernador John Endicot,
y llamaron.
Él mandó a un hombre para enterarse del asunto,
y ellos le respondieron diciendo que el asunto de ellos era del rey de Inglaterra,
y que no le darían su mensaje a nadie sino al propio gobernador.
En seguida se les permitió entrar,
y el gobernador se acercó a ellos y ordenó que le quitaran el sombrero a Shattock,
y tras recibir la autorización y el escrito judicial, se quitó el sombrero.
Entonces, ordenando que le devolvieran el sombrero a Shattock,
miró los documentos y salió con su representante,
y le pidió al representante del rey y al capitán del barco que lo siguieran.
Después de acercarse a su representante y consultar con él sobre el asunto,
regresó donde las mencionadas personas y les dijo:
"`Obedeceremos el mandato de su majestad.`"
Después de esto, el capitán del barco les dio libertad a los pasajeros a bajar a tierra,
y lo hicieron,
y se reunieron con sus amigos de la ciudad para ofrecer
alabanzas a Dios por esta maravillosa liberación.

Ahora bien, como varios de sus amigos estaban todavía en prisión en Boston,
el consejo dio la siguiente orden no mucho después.

A William Salter, guarda de la prisión en Boston.

La autoridad y Tribunal General le ordenan que rápidamente
libere a los Cuáqueros que en la actualidad están bajo custodia.
Mira que no desatiendas esto.

Por orden del tribunal,

Edward Rawson, Secretario:

Boston, 9 de Diciembre, 1661.

Luego consultaron qué hacer para no incurrir en el desagrado del rey,
y acordaron enviarle un representante.
Primero,
fue enviado el coronel Temple para que le informara al rey
que ellos habían puesto en libertad a los Cuáqueros;
y poco después le siguieron el sacerdote principal John Norton, y Simon Broadstreet,
uno de los magistrados.

El año ya ha terminado, pero antes de concluirlo debo señalar,
como un flagrante ejemplo de las maravillosas fluctuaciones de los asuntos mundanos,
que en la primera parte de este año, el cuerpo de Oliver Cromwell,^
footnote:[La cabeza de Cromwell permaneció en un poste sobre Westminster Hall hasta 1685,
cuando se desprendió durante una fuerte tormenta.
Después de esto,
estuvo en manos de varios coleccionistas privados y museos hasta el 25 de marzo de 1960,
cuando por fin fue enterrada en el Sidney Sussex College de Cambridge,
el alma mater de Cromwell.]
que había sido sepultado con gran fanfarria en Westminster Abbey, fue exhumado,
al igual que los cuerpos de Bradshaw e Ireton,
y los tres cadáveres fueron llevados en carretas a Tyburn y ahí colgados en la horca.
Luego el verdugo cortó las cabezas, pisoteó con su pie los cuerpos,
que fueron arrojados a una fosa cavada cerca de la horca,
y las cabezas fueron expuestas en lo alto de Westminster Hall,
donde recuerdo haberlas visto.
Le sucedió entonces a Cromwell,
lo que él había dicho unos siete años antes en su discurso al Parlamento,
como se ha mencionado en su debido lugar, a saber,
que él prefería ser arrojado en la tumba y ser sepultado con infamia,
que consentir a que se desechara uno de los fundamentos de ese gobierno, concretamente,
la libertad de consciencia.
Sin embargo, permitió que la persecución continuara, como ha sido relatado ampliamente;
pero luego, según sus propias palabras, fue arrojado con infamia en la tumba,
lo cual puede servir, en efecto,
como un notable ejemplo de la justicia y equitativos juicios de Dios.

Por este tiempo se publicó un libro en Londres, con el título _Semper Idem,_ es decir,
// jason: this was italicized in the ODT.  should it be a book-title?
'`Siempre lo Mismo; un Paralelo de Fanáticos.`'
El autor ocultó su nombre,
pero dejó suficientemente claro que era un Católico romano, y tal vez, Jesuita;
porque no sólo arremetió contra los Cuáqueros y Bautistas,
sino también contra los Presbiterianos, e incluso, los Episcopales, y consecuentemente,
contra todos los Protestantes.
En realidad,
los mártires que fueron quemados durante el sangriento
reinado de María (la hija mayor del rey Enrique VIII),
no fueron menos despreciados que los Cuáqueros en el mencionado libro,
con el despectivo nombre de "`rebeldes`" y "`fanáticos.`"
Este libro se vendió públicamente,
y parecía que nadie se atrevía a oponerse a él por temor a disgustar a la corte.
Pero Edward Burrough, quien era de un valor inquebrantable,
y continuó así hasta su muerte,
empleó su pluma para refutarlo y dio su respuesta por escrito,
mostrando claramente lo que pretendía el autor anónimo, a saber,
que quería revivir el uso cruel del fuego y la leña,
y deseaba que la quema de supuestos herejes fuera puesta en boga de nuevo.
Esto fue digno de tomarse en cuenta,
porque una publicación así de desprecio a los mártires con calumnias,
no se había visto en Londres por más de cien años,
y todas las posiciones infundadas de dicho autor fueron
muy claramente respondidas por el citado E. Burrough.

Y dado que a finales de este año la persecución empezó a aparecer de nuevo a cara descubierta,
// jason: this was italicized in the ODT.  should it be a book-title?
él publicó un libro que tituló, Antichrist`'s Government Justly Detected.^
footnote:[El Gobierno del Anticristo Puesto de Manifiesto en Justicia]
Este fue dedicado a todos los gobernantes, etc.,
en el llamado "`mundo cristiano;`" y en él Burrough manifestó con sólidos argumentos,
la ilegalidad e injusticia de la persecución, y de dónde se había levantado;
y mostró cuán peligroso era imponer una religión.

También trató ampliamente sobre la herejía,
y qué castigo les corresponde a los que son verdaderamente condenados por ella.
Pero para que nadie pensara que él se oponía al deber
del magistrado civil contra los malhechores,
dijo con respecto al castigo de la herejía,
el cual declaró ser sólo una censura eclesial, que él sólo concebía esta,
cuando el error de un hombre y su herejía en su mente y juicio,
se extendían sólo para dañar su propia alma, y contra Dios,
y no dañaban a la persona o propiedad de su prójimo.
"`Pero,`" continuó,
"`si el error y herejía se extienden más allá que sólo contra Dios y su propia alma,
es decir, en agravios externos, o males, o violencia,
o la ejecución de daños visibles como asesinatos,
y otros crímenes similares contra los hombres, en perjuicio de los demás,
entonces no prohíbo que el castigo externo sea infligido
corporalmente sobre la persona y patrimonio de tal hombre.`"
El autor también escribió circunstancialmente sobre el gobierno del anticristo,
y mostró el engaño que había en él, y quiénes eran los súbditos de su reino.

Un poco antes de este tiempo, George Fox el joven,
estando prisionero y viendo una intención de promover el papismo,
le escribió la siguiente carta al rey:

El Rey de reyes ha contemplado, sí, el Rey de reyes ha visto todos tus actos,
incluso en la oscuridad, y ha rastreado tu caminar en lugares oscuros;
y no has ocultado tus consejos al Todopoderoso,
sino que Él ha visto todas las intenciones de tu corazón,
y tus buenas palabras no lo han engañado en absoluto,
ni a los que permanecieron puramente en Sus consejos;
porque Él ha visto las trampas y contemplado los pozos que
han sido preparados secretamente para el inocente (incluso,
en el tiempo cuando se pronunciaron suaves palabras), y se los ha mostrado a otros.

¡Ojalá hubieras tomado consejo del Señor, y lo hubieras obedecido,
porque entonces habrías prosperado;
pero has tomado el consejo de los que te han hecho errar!
También has buscado exaltarte y establecerte a ti mismo, has buscado tu propio honor,
y no has buscado sólo la verdad y el honor de Dios; lo cual,
si en verdad lo hubieras hecho (en auto negación), Dios te habría honrado.
No has tomado al Señor como tu fuerza y apoyo,
sino que te has apoyado en lo que no te puede ayudar, es decir,
en lo que resultará ser una caña quebrada para ti si llegas a probar su fuerza.
Tú has deshonrado y afligido mucho al Señor, al establecer ministros que Él detesta,
y proveerles un mantenimiento obligatorio mediante una ley injusta,
para que sigan haciendo presa de Su pueblo,
quienes por un asunto de consciencia no pueden poner comida en sus bocas,
al haber sido espiritualmente sacados de tales cosas por la Palabra
del Señor. Tú también has afligido al Espíritu del Señor,
al no establecer una diferencia entre lo que se mueve por el Espíritu del Señor,
y lo que se mueve por los deseos malignos de los hombres;
y por ello has justificado lo que Dios ha condenado,
y condenado lo que Él ha justificado y justificará ante los ojos de Sus enemigos.

Oh, amigo, no es la persona de ningún hombre lo que Dios considera,
sino la justicia lo que Él respeta, y en la medida que el hombre (cualquiera que sea),
por las persuasiones de la Verdad llega a la justicia y actúa en ella,
en esa medida el Señor tiene unidad con él,
y no más. Estas cosas deberían haber sido consideradas por ti.
Tú también has afligido al Espíritu Santo al permitir todos esos espectáculos
y deportes malvados y profanos que han abundado desde tu llegada,
por los que la buena creación del Señor ha sido abusada, desperdiciada y devorada.
Has desagradado mucho al Señor Dios,
al permitir que la persecución sea ejecutada en tu nombre, incluso,
cuando en palabras has prometido libertad; sí,
muchos hoy están en huecos y prisiones por el testimonio de una buena consciencia,
y por obedecer la doctrina de Cristo.
¡Oh!
El Señor está afligido por el orgullo y la maldad que se vive,
tanto en tu familia como en tus dominios,
y tú mismo no has sido un modelo y ejemplo entre ellos como debías haber sido.

Oh, amigo, cuando contemplo la maldad,
crueldad y opresión que abunda en esta nación a vista de todos,
y también las secretas abominaciones que se cometen,
acechan y se traman en las cámaras interiores;
ciertamente mi vida se inclina por causa de la fiera
ira del Todopoderoso que veo que se enciende,
y por causa de la gran destrucción que veo que acompaña a los malvados,
cuyos fines y consejos frustrará el Señor, y sobre quienes Él derramará desprecio eterno.
Sí, y a menudo ha estado en mí (antes de que entraras en la tierra y desde entonces),
cuando se me ha mostrado la idolatría que se pretende introducir en secreto,
que ciertamente habría sido mejor para ti nunca haber venido,
porque he visto que tiende a tu destrucción. Y cuando he visto
la abominación y las crueldades con se cometen y pretenden cometer,
se ha levantado en mí una compasión hacia ti por el bien de tu alma, y ha sido mi deseo,
si fuera apoyado por la voluntad de Dios,
que Él ponga en tu corazón salir de la tierra de nuevo,
para que tu vida sea preservada y tengas tiempo para arrepentirte;
porque aunque muchos hombres te halagan y aplauden por fines egoístas,
veo que el Señor está disgustado con tus caminos.

Qué ningún hombre te engañe con palabras fingidas; Dios no puede ser burlado:
lo que siembres, es lo que cosecharás. No puedes esconderte del Señor,
ni librarte del golpe de Su mano.
¡Oh, considera cuán pronto se ha llevado el Señor a tu hermano, quien,
según la apariencia externa, podría haber vivido mucho más que tú!^
footnote:[Enrique Estuardo, duque de Gloucester, murió de viruela en septiembre de 1660,
a los veinte años de edad.]
¡No creas que los hombres pueden preservarte,
aunque todas las naciones alrededor prometan ayudarte!
Porque cuando el Señor se manifieste contra ti, entonces tendrás que caer; en verdad,
se acerca una gran desolación y tu mano no puede detenerla;
Dios ha decretado exaltar Su propio reino.
Las naciones son como una olla en ebullición, una pequeña llama las incendiará,
y la ventosa doctrina de los sacerdotes ayudará a encenderlas.
¡Oh, el día será terrible, quien podrá soportarlo!
El rastrojo será consumido y la paja será quemada; los impíos serán abatidos,
porque no pueden resistir el juicio; pero la Semilla será exaltada.

Oh, ¿qué diré que pueda ser para tu seguridad?
En realidad, puedo decir poco; el decreto del Señor debe permanecer,
el Señor está altamente disgustado y Su ira está próxima a ser revelada.
Él es rápido en Sus movimientos y acortará los días
de Sus enemigos por amor de Sus escogidos.
¡Ojalá tu alma se salve en el día del Señor!
Mi espíritu sufre por ti,
mi alma está afligida dentro de mí debido a la proximidad del día de tu calamidad,
del que nadie puede librarte.
Esta es la Verdad que debe permanecer, y en amor a tu alma,
es declarada por Aquel que debe tratar con rectitud con todos los hombres.
Aunque sufro externamente por ello,
aun así tengo un Testigo en tu consciencia al que soy manifestado;
y la paz con el Señor es mi porción, la cual es mejor que una corona terrenal.

George Fox, el joven.

Entregada el 9 del mes Ocho, 1660.

Esta carta (una clara evidencia del inocente valor del autor) fue entregada al rey,
quien la leyó y pareció ser alcanzado por ella, y tocado en su corazón. Pero su hermano,
el duque de York, se disgustó con ella, y al oponerse violentamente contra el autor,
le aconsejó al rey ser severo contra él. Pero el rey, que era bondadoso, dijo:
"`Sería mejor para nosotros enmendar nuestras vidas.`"

Mientras George Fox el joven era prisionero en Lambeth-house,
// jason: another italicized possible book title
también escribió un pequeño tratado llamado England`'s Sad Estate and Condition Lamented.^
footnote:[Lamentación de la triste situación y condición de Inglaterra.]
En el que reprobaba las graves abominaciones que se cometían entre los habitantes,
la opresión ejecutada por medio de la persecución, y la hipocresía de los sacerdotes.
También predijo la peste que se mencionará más adelante en su debido lugar,
y dio a entender, no oscuramente,
que se harían públicamente esfuerzos para introducir la superstición y la idolatría,
pero que aquellos que pretendían hacerlo serían frustrados por el Señor en sus intentos.
Y que otros, cuya adoración desagradaba al Señor,
se molerían y se destruirían unos a otros, y que más allá de sus expectativas,
Él sacaría entre ellos y preservaría la Semilla santa.
Y que después de que hubiera ejecutado Su venganza sobre los rebeldes y traidores mercaderes,
sacaría a la luz entonces al remanente de Su santa semilla,
el cual sería preservado de la furia de ellos,
y sería esparcido por todo y dominarían. "`Pero,`" continuó, "`aunque estas cosas,
con respecto al remanente santo, ciertamente se cumplirán en su momento, aun así,
antes de que se cumplan completamente,
grandes serán las tribulaciones de muchos de los justos,
y habrá grandes juicios ejecutados en ustedes, oh, tierra,
por Aquel que a veces hace estéril una tierra fructífera,
por la maldad de los que habitan en ella.`"
Esto y mucho más escribió y publicó en forma impresa.
Varias de sus predicciones las hemos visto cumplidas,
como aparece en el progreso de la historia;
y de esta última nos referiremos en el momento apropiado.
Después de escribir este tratado, también entregó el siguiente documento.

Ciertamente fuiste Tú, oh, Señor, quien le puso límites al mar,
para que las inundaciones de este no aneguen a Tus escogidos.
Tú dejas salir los vientos y permites las tormentas, y cuando te place haces la calma.
¡Tú tienes la gloria de todo, Rey de los santos y Salvador de Israel!
Tú puedes hacer lo que te plazca,
por eso confiaremos en Tu nombre y no temeremos lo que los hombres puedan hacernos,
porque Tú no nos abandonarás;
sino que defenderás nuestra causa ante los ojos de nuestros adversarios,
y ellos sabrán que Tú eres nuestro Dios, que puedes salvar perpetuamente.
¡Oh, Señor, justicia nuestra, alabaremos Tu nombre,
porque Tus misericordias son para siempre!
Nuestros ojos, oh, Dios, están puestos en Ti, porque no tenemos otro ayudador.
Nuestra fe, oh, Señor, permanece en Ti, porque no puedes olvidar a tu pueblo.
Tú has revelado y sacado a la luz a Jacob,
quien lucha Contigo y prevalece como un príncipe, por tanto, vendrá la bendición. ¡Oh,
Señor, el nacimiento de Tu semilla clama a Ti, Tu propio Elegido,
que ha sido oprimido por mucho tiempo!
Tú no puedes negarte a Ti mismo, por eso tenemos fe y una esperanza que no decepciona.
¡Señor, cuán inescrutables son Tus caminos!
Tú has asombrado a Tu pueblo con la profundidad de Tu sabiduría;
sólo Tú tendrás la gloria de la liberación de ellos,
y por eso has permitido que sucedan estas cosas.
¡Oh, Señor, Tú eres justo en todos Tus juicios;
sólo preserva al pueblo que has reunido y reunirás para Ti en el día de la prueba,
para que ellos canten de Tu poder y magnifiquen Tu nombre en la tierra de los vivos!

Este George Fox (el joven) también escribió vario otros documentos y epístolas en prisión,
para exhortación y consolación de sus amigos; sin embargo, su obra fue acabada pronto,
porque no mucho después de esto partió de esta vida,
lo que sucedió este año o el siguiente.
Él era, como puede verse por sus escritos,
un hombre de extraordinaria entrega y valentía; y puede verse que rindió su vida,
en un pequeño libro que escribió estando en prisión en Lamberth-house, al cual llamó:
// jason: another italicized possible book title
The Dread of God`'s Power Uttering its Voice through Man, unto the Heads of the Nation.^
footnote:[El Pavor del Poder de Dios al Emitir Su Voz a Través del Hombre,
a los Jefes de la Nación.]
En este exhortó a los gobernantes muy seriamente a hacer justicia,
y les dijo entre otras cosas: "`Amigos,
debo tratar claramente con ustedes ante los ojos de Dios,
quien me ha hecho profeta para la nación. Yo no puedo adular a ninguno de ustedes.
Mi vida está en la mano de mi Hacedor,
y ni un solo cabello de mi cabeza puede caer al suelo sin Su providencia.
Él ha redimido mi alma del infierno y mi mente de la tierra;
y me ha dado Su buen Espíritu para guiarme.
Por consiguiente, ya no soy mío, sino del Señor, quien me ha formado para Su alabanza,
y me ha sacado para que haga sonar Su poderosa Verdad entre el pueblo.
Por tanto, no debo temerle al hombre, ni debo atemorizarme de los hijos de los hombres.`"

Así se mostró inmutable; pero no pasó mucho tiempo antes de su partida,
de la que no puedo dejar de decir algo.
Encuentro que en su enfermedad, aunque estaba débil de cuerpo, era fuerte de espíritu,
de modo que cantaba con gozo de corazón. Exhortó a sus amigos a mantenerse en unidad,
previendo, tal vez,
que algo se podía levantar y darle oportunidad a la división. Y luego,
con mucho fervor de espíritu oró a Dios,
y exhortó a sus amigos a que mantuvieran sus vestiduras sin mancha del mundo,
porque el día de prueba que se acercaba iba a ser grande.
Después de encomendarlos al Señor,
se despidió de ellos y durmió en perfecta paz con el Señor,
estando en su sano juicio hasta el final.
Entonces el polvo regresó a la tierra y el espíritu al Dios que lo dio;
y así fue liberado de todo peligro de perder la corona de vida inmortal,
al que el hombre, por la tentación y las casualidades de esta vida,
está expuesto si no continúa vigilando diligentemente.
Pero este valiente ahora estaba más allá del alcance de todas las tentaciones,
y así lo dejo, para poder pasar a otros asuntos.

En este año Edward Burrough les escribió un documento al rey y a su consejo,
// jason: another italicized possible book title
que él llamó: A Just and Righteous Plea,^
footnote:[Una Defensa Justa y Recta.]
en el que proponía, con detalles,
las razones por las que los llamados Cuáqueros se negaban a tomar el juramento de lealtad,
mostrando que no era porque no fueran fieles al rey,
sino únicamente por un asunto de consciencia,
dado que Cristo les había ordenado expresamente a sus seguidores:
"`No juréis en ninguna manera;`" un mandato que ellos no se atrevían a transgredir.
Sin embargo, para asegurarle al gobierno la fidelidad de ellos, dijo lo siguiente:

Ahora somos y seguiremos siendo, fieles,
inocentes y pacíficos en nuestros varios puestos y condiciones,
bajo el presente gobierno del rey Carlos II,
a quien reconocemos como magistrado y gobernante supremo sobre este reino;
y por un asunto de consciencia le obedecemos y nos sometemos a él, como tal,
en todos sus mandatos, ya sea haciendo y ejecutando lo que él justamente requiera,
o sufriendo pacientemente bajo lo que se nos inflija,
en los asuntos que por consciencia no podemos ser obedientes,
cuando se nos pida algo distinto a la ley justa de Dios.
A esta sujeción al rey y a su gobierno, estamos obligados por la ley de justicia;
y este ha sido siempre nuestro principio y práctica, y lo es hasta este día: es decir,
ser tranquilos, pacíficos y pacientes bajo cada autoridad que esté sobre nosotros,
y no conspirar en injusticia,
ni tramar o rebelarnos contra ningún gobierno o gobernantes,
ni buscar nuestra propia liberación de la injusticia y opresión de esa manera.

Estamos persuadidos de buscar la preservación de la persona y autoridad del rey,
por todos los medios justos y legítimos, y de no rebelarnos contra él con armas carnales.
Y en la medida que su gobierno sea en justicia, misericordia y rectitud,
declararemos verdadera y fiel sujeción y obediencia a dicho gobierno;
y en lo que no sea así,
nos someteremos mediante paciente sufrimiento a lo que se nos imponga injustamente,
y sin embargo,
no nos rebelaremos de ninguna manera turbulenta en conspiraciones e insurrecciones,
porque nuestros principios no son para la guerra, sino para la paz con todos los hombres,
en la medida en que esté bajo nuestro control.
Tampoco podemos devolver mal por mal,
sino que debemos estar sujetos al rey y a su gobierno, activa o pasivamente,
en las condiciones antes mencionadas.

También rechazamos toda autoridad extranjera, poder y jurisdicción del papa,
o cualquier otra, de tener alguna supremacía sobre el rey,
o alguno de los buenos súbditos del Inglaterra.
Esto lo declaramos,
reconocemos y testificamos en el temor y presencia de Dios
(a quien nosotros y toda la humanidad debe rendir cuentas),
sin equívocos secretos, o alguna reserva mental engañosa.

Así se declaró ampliamente E. Burrough,
e hizo un relato circunstancial de la práctica de sus amigos al reunirse,
o de su forma de adoración pública,
para asegurarle así al gobierno su conducta y fidelidad pacíficas.
Pero todo esto resultó en vano;
porque al ser bien sabido que los Cuáqueros se negaban a jurar,
eran continuamente molestados y perseguidos con el pretexto
de no dar la debida satisfacción de su fidelidad al gobierno,
transgrediendo así las leyes.

Ahora, bien, los representantes de Nueva Inglaterra llegaron a Londres,
y se esforzaron por explicarse lo mejor posible, especialmente el sacerdote Norton,
quien se inclinó con no menos reverencia ante el arzobispo que ante el rey.
Y así, adulando a los Episcopales,
encontraron los medios para mantenerse en la posición de molestar a los llamados Cuáqueros,
aunque se les prohibió darles muerte.
Y el hecho de que muchos de los obispos eran grandes enemigos de los mencionados Cuáqueros,
se desprende claramente de la cruel persecución que, tras una breve calma,
se levantó en Inglaterra.

Pero volviendo a los representantes de Nueva Inglaterra,
estos se habían excusado con entusiasmo;
y el sacerdote Norton pensó que era suficiente decir
que él no había asistido al sangriento juicio,
ni lo había aconsejado; sin embargo, John Copeland,
a quien le habían cortado una oreja en Boston, lo acusó de lo contrario.
George Fox (el mayor) también tuvo oportunidad de
hablar con ellos en presencia de algunos de sus amigos,
y le preguntó a Simon Broadstreet, uno de los magistrados de Nueva Inglaterra,
si él había participado en la muerte de los apodados Cuáqueros.
Al no poder negarlo, confesó que había participado.
Entonces G. Fox les preguntó a él y a sus asociados que estaban presentes,
si se reconocían sujetos a las leyes de Inglaterra; y sí lo hacían,
por cuáles leyes habían condenado a muerte a sus amigos.
Ellos respondieron que estaban sujetos a las leyes de Inglaterra,
y que habían condenado a muerte a sus amigos,
por la misma ley con la que los Jesuitas habían sido condenados a muerte en Inglaterra.

Ante esto, G. Fox les preguntó si ellos creían que sus amigos,
a quienes habían condenado a muerte, eran Jesuitas,
o que estaban influenciados por los Jesuitas.
Ellos dijeron: "`No.`" "`Entonces,`" replicó G. Fox, "`ustedes los han asesinado; porque,
dado que los han ejecutado por la ley con la que los Jesuitas son ejecutados en Inglaterra,
se ve claramente que los han ejecutado arbitrariamente, sin ninguna ley.`"
Por tanto, Broadstreet, viéndose él y sus compañeros atrapados por sus propias palabras,
preguntó: "`¿Has venido a atraparnos?`"
Pero él les dijo: "`Ustedes se han atrapado a sí mismos,
y podrían ser justamente juzgados por sus vidas;`" y añadió que si el padre de
William Robinson (uno de los que fueron ejecutados) estuviera en la ciudad,
probablemente los interrogaría y pondría sus vidas en peligro;
porque al no ser de la persuasión de los Cuáqueros,
posiblemente no tendría tanto aprecio por la tolerancia como ellos.
Cuando Broadstreet se vio en peligro,
empezó a echarse atrás y a justificarse porque algunos de los antiguos monárquicos
querían que los Cuáqueros procesaran a los perseguidores de Nueva Inglaterra.
Pero G. Fox y sus amigos dijeron que ellos los dejaban en manos del Señor,
a quien le pertenecía la venganza, y que Él pagaría. Broadstreet, sin embargo,
pensando que no era seguro permanecer en Inglaterra,
abandonó la ciudad y regresó a Nueva Inglaterra con sus compañeros.

No mucho antes de este tiempo, G. Fox, con la ayuda de John Stubbs y Benjamin Furly,
// jason: another italicized possible book title
publicó un libro llamado A Battledoor.^
footnote:[Un "`battledoor,`" también llamado libro de cuerno,
era una hoja o página que contenía el alfabeto u otros materiales educativos,
cubierta con una hoja de cuerno transparente y fijada en un marco con un asa,
que antiguamente se utilizaba para enseñar a leer a los niños.]
En este libro se exponían ejemplos de casi treinta idiomas,
para demostrar que cada idioma tenía su particular
denominación para el singular y el plural,
al dirigirse a las personas; y en cada lugar donde comenzaba la descripción,
se delineaba la forma de una cartilla.
Esta obra se promocionó para todo público por G. Fox,
con el fin de mostrarles a los entendidos,
que la costumbre de los llamados Cuáqueros de usar el "`tú`" para una persona,
aunque fuera el rey, y no el "`usted,`" no era irregular ni absurdo,
sino que se había usado de forma generalizada; y que, por lo tanto,
ellos no podían acusarlos justamente de falta de respeto,
por no seguir la costumbre común,
que únicamente se había infiltrado por el orgullo de los hombres.
Ahora bien, aunque Gerard Croese desaprobó que G. Fox pusiera su nombre en este libro,
así como también J. Stubbs y Benjamin Furly,
yo no lo considero tan inapropiado como el mencionado autor dijo;
porque G. Fox fue un gran promotor de esta obra, y aunque no era un experto en idiomas,
y algunos lo llamaban idiota o tonto,
sé que era un hombre de buen entendimiento y de profundo juicio.
En su diario,
él libremente reconoce que John Stubbs y Benjamin Furly
se esmeraron mucho en la compilación de dicho libro,
que él les había pedido que escribieran, y que luego,
él mismo había añadido algunas cosas; de modo que, en cierto sentido,
también podría ser considerado un autor.

Este libro (en el que J. Stubbs y B. Furly también daban
instrucciones para que los estudiantes leyeran el hebreo,
el oriental y otros idiomas) fue distribuido libremente.
Algunos de ellos fueron presentados al rey y a su consejo, al arzobispo de Canterbury,
al obispo de Londres, y uno a cada universidad.
El rey confesó que la diferencia entre el plural y el singular,
en lo que se refiere a personas, era el lenguaje propio de todas las naciones;
y cuando se le preguntó al arzobispo qué pensaba de eso, estaba tan perplejo,
que no supo qué decir; porque al parecer, no quería recomendarlo,
ni tampoco podía decidirse a desaprobarlo.
Sin embargo, esto informó y convenció de tal manera a la gente,
que después muchos no se sentían tan ofendidos como antes,
al oír el "`tú`" y "`ti`" en referencia a una persona.

Entonces, muchos Católicos romanos empezaron a lisonjear a los llamados Cuáqueros,
y decían públicamente que de todas las sectas,
los Cuáqueros eran las mejores y más sobrias personas,
y que era una gran pena que no regresaran a la santa madre iglesia.
Pero aunque puede ser que hayan tenido esperanzas de ganar prosélitos de entre los Cuáqueros,
quedaron decepcionados.
Mientras tanto, no les hicieron más que un pobre servicio a los Cuáqueros,
porque esto les dio oportunidad a sus enemigos,
de difundir el rumor que había una afinidad y complicidad
entre los Cuáqueros y los Católicos romanos.

En ese momento,
algunos Jesuitas indicaron que estaban dispuestos a conversar con los Cuáqueros,
y G. Fox consintió, y para ello se fijó una hora y un lugar.
G+++.+++ Fox les hizo la misma pregunta que había formulado en una ocasión anterior,
como ya se ha relatado,
que si la iglesia de Roma no se había degenerado
de la iglesia de los tiempos primitivos--del espíritu,
poder y práctica que tenía en los días de los apóstoles.
El Jesuita a quien se le planteó la pregunta,
dijo que no la respondería. G. Fox le pregunto:
"`¿Por qué?`" Pero él no quiso dar ninguna razón. Entonces sus compañeros dijeron
que ellos no se habían degenerado de la iglesia de los tiempos primitivos.
Luego, G. Fox le preguntó al otro si él era del mismo parecer, y este dijo: "`Sí.`"

G+++.+++ Fox, para no darle cabida a ninguna excusa por error, repitió la pregunta diciendo:
"`¿Está la iglesia de Roma en la misma pureza, práctica,
poder y espíritu en que estaba la iglesia en los días de los apóstoles?`"
Los Jesuitas, al ver cuán exacto buscaba G. Fox ser con ellos,
dijeron que era presunción en cualquiera decir que tenía
el mismo poder y espíritu que tenían los apóstoles.
Pero G. Fox les dijo,
que era presunción en ellos entrometerse con las palabras de Cristo y Sus apóstoles,
y hacerle creer a la gente que eran los sucesores de los apóstoles, y sin embargo,
verse obligados a confesar que no tenían el mismo poder y espíritu que tenían los apóstoles.
"`Esto,`" dijo él, "`es un espíritu de presunción,
y es reprendido por el espíritu de los apóstoles.`"
Entonces les mostró cuán diferentes eran sus frutos
y prácticas de los frutos y prácticas de los apóstoles.
Esto disgustó tanto a los Jesuitas, que uno de ellos dijo:
"`Ustedes son un grupo de soñadores.`"
"`No,`" dijo G. Fox, "`ustedes son los soñadores,
que sueñan que son los sucesores de los apóstoles, y sin embargo,
confiesan no tener el mismo poder y espíritu en el que estaban los apóstoles.`"
Luego, comenzó a decirles también, cómo eran guiados por un espíritu maligno,
y que ese espíritu los había inducido a orar con cuentas y a las imágenes,
y a ejecutar personas por religión. Habló aún más,
pero los Jesuitas se cansaron pronto de esa conversación y se fueron,
encargando después a los de su persuasión, que no discutieran con los Cuáqueros,
ni leyeran ninguno de sus libros.

Un tiempo después de esto G. Fox fue a Colchester, donde tuvo reuniones muy numerosas.
De ahí pasó a Coggeshall;
no lejos de ahí había un sacerdote convencido de
la verdad de la doctrina sostenida por él y sus amigos,
y tuvo una reunión en su casa.
Y después de visitar a sus amigos en sus reuniones de los alrededores, regresó a Londres,
donde encontró más obra; pues John Perrot, de quien se dijo que estaba en Roma,
había cedido tanto a sus vanas imaginaciones,
que se creía más ilustrado que G. Fox y sus amigos.
A partir de esta presunción declaró,
que él no aprobaba que cuando alguien orara en la
reunión los demás se quitaran los sombreros,
calificando eso como una formalidad y una costumbre común del mundo,
de la que había que apartarse.
Y como las novedades a menudo arrastran a la gente tras ellas, así sucedió en este caso,
al punto que ganó un buen número de adherentes.
Pero no se detuvo ahí; pues como un error procede de otro,
dio otros pasos extravagantes y dejó crecer su barba, en lo que fue seguido por algunos.

Mientras tanto,
G+++.+++ Fox se esforzaba tanto por palabra como por escrito para detener su avance,
y aunque la mayoría de sus amigos también daban testimonio contra esto,
pasaron varios años antes de que este fuego extraño se extinguiera por completo.
John Perrot, quien ahora caminaba por una senda errónea, empeoró más y más, a tal punto,
que tras llegar a América, cayó en manifiestas sensualidades y obras de la carne,
pues no sólo empezó a usar ropas llamativas, sino también una espada,
y al obtener cierto lugar en el gobierno,
se convirtió en un severo '`apremiador`' de juramentos,
aunque antes había profesado que por un asunto de consciencia no podía jurar.
Antes de dejar a Perrot,
insertaré aquí una carta escrita por él desde Roma cuando fue liberado de la prisión;
y aunque creo que en ese momento estaba en mejor estado que después, aun así,
en esta carta pueden verse algunas chispas de orgullo espiritual,
que aunque en ese momento estaba bajo cierta limitación,
con el paso del tiempo estalló de tal manera que causó su caída. La carta era como sigue:

Oh, Israel, el ejército del Dios Altísimo;
Su majestad me ha cumplido la visión de mi cabeza, tras mostrarse como el Santo y Justo.
Él me ha liberado últimamente de la prisión de la ciudad de Roma,
junto con los dos corderos que están conmigo, cuyos rostros, a través de Dios,
están vueltos a ti; por lo que te ruego en el Santo Espíritu de mansedumbre,
que bendigas el nombre del Señor Dios.
Dale gracias a Él por Su poder.
El Dios de vida los promueva a todos en la virtud de Su misericordia y perdón,
y los guarde en el poder de Su amor eterno hasta el fin.

John.

Escrito para todos ustedes fuera de las puertas de Roma, el 2 del mes Cuarto, 1661.

Envíen esto y lean mi vida en sus reuniones.

Él no añadió su apellido, al parecer, en imitación al apóstol Juan.
También lo omitió en otra carta que escribió desde la prisión en Roma,
la cual comenzaba así:

Yo Juan el prisionero, estando en el sentido del Espíritu de vida con todos ustedes, etc.

No puedo decir quiénes era los dos corderos mencionados en esta carta;
si eran personas que habían estado encarceladas con él en la cárcel
de la Inquisición y se habían convertido por él (como él pensaba),
o si se refería a John Stubbs y Samuel Fisher, no lo sé. Se puede suponer más bien,
que se refería a Charles Bayley y Jane Stoakes,
quienes fueron a Roma para procurar su libertad.
Si no me equivoco, fue por este tiempo que ellos fueron a Roma, y tal vez,
después de esforzarse por obtener su libertad, partieron a Inglaterra antes que él.

Después de que Perrot vivió en América, al principio del año 1665,
John Taylor escribió así desde Jamaica con respecto a él:

Uno de los jueces de este lugar me dijo,
que él nunca había visto a alguien que exigiera tan
severamente un juramento de las personas,
como lo hacía John Perrot.
Y otro juez, que también estaba presente,
dijo que Perrot había renunciado por completo a su fe,
y que no buscaba más que su beneficio.

Tal hombre era John Perrot, aunque algunos sabios lo admiraron por un tiempo;
pero él se convirtió en un hombre de comportamiento rudo.
No puedo decir, si alguna vez se arrepintió sinceramente.
Robert Rich, quien participó mucho en las extravagancias de James Nayler,
como se ha relatado, también se unió a Perrot,
y se alejó de los Cuáqueros y murió en esa condición. Él
fue uno de aquellos de los que el apóstol Juan dijo:
"`Salieron de nosotros, pero no eran de nosotros.`"

Ahora bien, como la persecución continuaba en Inglaterra, Edward Burrough,
que continuamente luchaba con su pluma oponiéndose a esta maldad,
también escribió un librito que llamó,
// jason: another italicized possible book title
The Case of Free Liberty of Conscience in the Exercise of Faith and Religion,
presented unto the King and both Houses of Parliament.^
footnote:[La Demanda de Libertad de Consciencia en el Ejercicio de la Fe y de la Religión,
Presentada al Rey y a Ambas Cámaras del Parlamento.]
En este tratado él demostraba que privar a las personas honestas y pacíficas
de la libertad de consciencia en el ejercicio del culto a Dios,
era injusto, una invasión a la soberanía de Dios, y una usurpación de Su autoridad.
También recomendaba que se considerara,
que imponer por la fuerza una religión a los hombres,
era la forma de llenar la tierra de hipócritas.
Demostraba con sólidas razones,
que perseguir a las personas por el ejercicio de la religión y su adoración a Dios,
llevaría inevitablemente a la destrucción del comercio,
de la agricultura y de los productos.

A esto añadió, que los llamados herejes eran castigados como malhechores,
mientras que los borrachos y otros viciosos quedaban impunes,
y para inculcarlo con más fuerza, hizo uso de las palabras del Dr. Taylor,
un obispo en Irlanda, quien dijo:
"`¿Por qué somos tan celosos contra los llamados herejes, y sin embargo,
grandes amigos de los borrachos, blasfemos, fornicadores, desmedidos y viciosos?
Estoy seguro de que un borracho es tan contrario
a las leyes del Cristianismo como un hereje.
Y estoy seguro también, de saber qué es la embriaguez,
pero no estoy tan seguro de que tal o cual opinión sea una herejía,`" etc.

Sucedió por esta época en Inglaterra que algunas personas codiciosas,
con el fin de arrebatar herencias para sí mismas,
trataron de poner en duda los matrimonios de los llamados Cuáqueros.
Y fue en este año, que dicha causa fue juzgada en la sesión de la corte en Nottingham.
Cierto hombre, identificado como un Cuáquero,
murió y dejó una esposa embarazada y un patrimonio en tierras de copropiedad.
Cuando la mujer dio a luz al niño,
un pariente cercano del esposo trató de probar que el niño era ilegítimo.
El abogado del demandante, dispuesto a ensuciar la reputación de los Cuáqueros,
afirmó que el niño era ilegítimo porque el matrimonio
de sus padres no era conforme a la ley;
y también dijo sin rodeos (y muy indecentemente)
que los Cuáqueros se unían como bestias salvajes.

Después de que los abogados de ambas partes habían hecho el alegato, el juez,
cuyo nombre era Archer, le abrió el caso al jurado,
alegando que en el paraíso había sucedido un matrimonio, cuando Adán había tomado a Eva,
y Eva a Adán,
y que había sido el consentimiento de las partes lo que había constituido el matrimonio.
Y en cuanto a los Cuáqueros, dijo que no conocía sus opiniones,
pero que no creía que se unieran como bestias salvajes, como se había dicho de ellos,
sino más bien como Cristianos, y por lo tanto,
que él creía que el matrimonio era legal y el niño era el legítimo heredero.
Con el fin de satisfacer mejor al jurado,
les relató otro caso donde un hombre débil de cuerpo, que guardaba cama,
había querido casarse en esa condición. El hombre había
declarado ante testigos que tomaba a la mujer como su esposa,
y la mujer había declarado también que ella tomaba al hombre como su esposo.
Posteriormente, el matrimonio había sido puesto en duda,
pero que todos los obispos de ese tiempo habían concluido que el matrimonio era legal.
El jurado, después de recibir esta instrucción,
dio su veredicto a favor del niño y lo declaró el legítimo heredero.

Se ha mencionado antes que G. Fox, cuando estaba encarcelado en Derby en el año 1650,
fue muy afligido y maltratado por el guarda de la prisión. Pero que este hombre,
tras ser golpeado por los terrores del Señor, se convirtió en un converso tan notable,
que en el año 1662, le escribió la siguiente carta a G. Fox:

Querido Amigo,

Teniendo un mensajero tan conveniente,
no podía menos que hacerte un relato de mi actual condición,
al recordar que en mi primer despertar al sentido de la vida y Semilla interior,
le plació a Dios usarte como un instrumento;
de modo que a veces me admira que haya llegado por los medios que llegó, es decir,
que la Providencia te ordenara ser mi prisionero
para darme mi primera visión real de la Verdad.
Esto muchas veces me hace pensar en la conversión del carcelero por medio de los apóstoles.
Y aunque mis pérdidas externas son tales desde entonces,
que me he convertido en nada en el mundo, con todo,
espero encontrar que todas estas leves tribulaciones momentáneas,
obren en mí un más excelente y eterno peso de gloria.
Me lo han quitado todo, y ahora, en lugar de ser guarda de prisión,
estoy esperando convertirme yo mismo en un prisionero.
Ora por mí, para que mi fe no desfallezca,
sino que pueda resistir hasta la muerte para recibir la corona de vida.
Deseo saber de ti de todo corazón, y de tu condición, la cual me alegraría mucho.
No teniendo otra cosa por el momento,
sino mi cordial amor hacia ti y todos los amigos Cristianos contigo,
aunque apresuradamente,

Tuyo en Cristo Jesús,

Thomas Sharman.

Derby, 22 del mes Cuarto, 1662.

En el pasado hice mención del encarcelamiento de Catherine
Evans y Sarah Cheevers por la Inquisición en Malta.
Fue por este tiempo que ellas fueron liberadas, pues G. Fox y Gilbert Latey,
habiendo entendido que el señor d`'Aubigny podía procurar su libertad,
se dirigieron a él, y tras informarlo del encarcelamiento de ellas,
le pidieron que les escribiera a las autoridades en Malta
para su liberación. Él prometió hacerlo y les dijo,
que si ellos regresaban en un mes,
tal vez les tendrían noticias de su liberación. Ellos regresaron por ese entonces,
pero les dijo que pensaba que sus cartas se habían perdido, sin embargo,
les prometió que escribiría de nuevo, y así lo hizo; y esto tuvo tal efecto,
que las mencionadas mujeres fueron liberadas de su prolongado encarcelamiento.
G+++.+++ Fox tuvo entonces la oportunidad de razonar con este señor (que
era un sacerdote Católico romano en las órdenes) acerca de religión,
y lo llevó a confesar que Cristo "`alumbra a todo
hombre que viene a este mundo`" con Su luz espiritual,
que Él había probado la muerte por todo hombre, que la gracia de Dios,
que trae salvación, había aparecido a todos los hombres,
y que esta les enseñaría y les traería salvación si la obedecían.
Entonces G. Fox le preguntó qué harían los romanistas con todas
sus reliquias e imágenes si reconocieran y creyeran en esta luz,
y recibieran la gracia de Dios para que les enseñara
y trajera salvación. Y el sacerdote respondió,
que esas cosas no eran más que políticas para mantener a las personas en sujeción.

Pero dejo estas conversaciones,
y ahora haré un relato claro y circunstancial del encarcelamiento
de las antes mencionadas Catherine Evans y Sarah Cheevers,
compilado principalmente de cartas y documentos escritos por ellas en prisión,
y enviados desde ahí a Inglaterra,
donde fueron publicados en forma impresa no muchos después de su regreso, en el año 1662.

En el año 1658, Catherine Evans y Sarah Cheevers,
habiendo sido persuadidas en sus mentes de viajar a Alejandría,
fueron en barco de Inglaterra a Leghorn en Italia,
y tras pasar treinta y un días entre Plymouth y Leghorn,
finalmente desembarcaron a salvo en esa ciudad.
Allí encontraron a algunos de sus compatriotas y amigos,
y se quedaron varios días repartiendo muchos libros cuando la ocasión lo permitía.
También hablaron con personas de varios niveles sin ser molestadas por ninguno.
Ahí obtuvieron pasaje en un barco holandés con destino a Alejandría, o Scanderoon,
pero el capitán del barco, al estar en compañía de otro que iba para Malta,
fue también ahí, aunque no tenía negocios en ese lugar;
pero antes de que llegaran a Malta, Catherine cayó en tal angustia de mente que exclamó:
"`¡Oh, tenemos una terrible copa que tomar en ese lugar!`"
Al entrar en el puerto y estando en la cubierta del barco,
mirando a la gente que estaba parada en los muros, dijo en su corazón:
"`¿Nos van a destruir?
Si nos rendimos al Señor, Él es suficiente para librarnos de sus manos,
pero si desobedecemos a nuestro Dios, ninguno de estos podrá librarnos de Su mano.`"
Y así les fue quitado todo temor al hombre.

Al día siguiente, el Primer-día,
fueron a la orilla donde el cónsul Inglés las recibió y les preguntó a qué habían venido.
Ellas respondieron lo que les pareció que era conveniente y le dieron algunos libros.
Entonces él les dijo que en ese lugar estaba la Inquisición,
e invitándolas amablemente a su casa,
les dijo que todo lo que él tenía estaba al servicio de ellas mientras
estuvieran ahí. Ellas aceptaron la invitación y fueron con él,
y muchos llegaron a verlas, a los que ellas llamaron al arrepentimiento,
de modo que varios se mostraron atentos.
Cerca de la noche regresaron al barco y al día siguiente fueron de nuevo a la ciudad,
y yendo adonde el gobernador,
él les dijo que tenía una hermana en el convento que deseaba verlas.
Entonces fueron al convento y hablaron con las monjas y les dieron libros.
Uno de los sacerdotes, que las llevó a la capilla,
quería que se inclinaran frente al altar mayor, pero ellas se negaron,
afligiéndose por la idolatría que ahí se cometía. Después de esto
regresaron a la casa del cónsul donde se quedaron varias semanas.

Durante ese tiempo,
una vez entraron en uno de los lugares de culto en el tiempo de la adoración,
y Catherine, de pie en medio del pueblo, le dio la espalda al altar mayor,
y arrodillándose,
levantó la voz en oración al Señor. El sacerdote que oficiaba se quitó su sobrepelliz^
footnote:[Prenda larga y amplia,
de tela blanca y fina y con las mangas muy anchas que lleva sobre la sotana el sacerdote.]
y se arrodilló cerca de ella hasta que Catherine terminó. Entonces él extendió
la mano hacia ellas para que se acercaran y le ofreció una moneda a Catherine,
que al tomarla como la marca de la bestia, la rechazó. En seguida,
puso la moneda en la mano de Sara, pero ella se la devolvió,
y le mostró la cartera para que él viera que ella tenía para dar,
si alguien tenía necesidad, y que hasta ahora ella no tenía falta de nada.
Luego les preguntó si ellas eran Calvinistas o Luteranas.
Ellas respondieron: "`No.`" Les preguntó si ellas irían a Roma para ver al papa.
Al negarlo, les preguntó si eran católicas, a lo que dijeron,
que ellas eran verdaderas cristianas, siervas del Dios vivo.
Pero como todavía no habían aprendido mucho del idioma que se hablaba ahí,
se expresaron muy deficientemente, en parte con palabras y en parte con señas,
lo mejor que pudieron, y muchos de los que las rodeaban quedaron asombrados;
al final se marcharon pacíficamente.

Un tiempo después fueron de nuevo a una '`casa de la misa,`' cuando el sacramento,
como lo llaman ellos, era administrado.
Había muchas luces, y una gran opulencia y refinamiento,
y afligidas debido a la idolatría,
estuvieron cerca de tres cuartos de hora llorando y temblando, especialmente Catherine.
Esto impactó tanto a la congregación, que algunos se alejaron de ellas por temor.
Finalmente se fueron, pero aún bajo tal temblor,
que iban por la calle tambaleándose y desconcertadas,
de modo que se convirtieron en un espectáculo para todos los que las veían.

Catherine y Sara estuvieron cerca de tres meses en la casa del cónsul inglés,
y al estar él bajo sospecha por esa razón,
no hizo lo que podía haber hecho para salvarlas, porque en cierto sentido,
las había entregado a la Inquisición,
aunque por juramento estaba obligado a proteger a todos los ingleses ahí. Mientras tanto,
las mantuvo en su casa y no les permitió que se fueran al extranjero,
aunque el gobernador le había dicho que él podría
dejarlas ir para que se dedicaran a sus asuntos.
"`Porque,`" dijo él, "`ellas son mujeres honestas.`"
El cónsul también podría haberlas dejado libres,
antes que cayeran bajo el poder de la vara negra.
Percibiendo ellas que algo para su perjuicio se estaba agitando,
y haciendo cuentas de que una prisión sería su destino,
le expresaron que ellas sospechaban de él,
y le dijeron que Pilato les había hecho un servicio a los judíos, y sin embargo,
se había lavado las manos en inocencia.
Sabiéndose descubierto, les pidió una señal que demostrara que eran mensajeras de Dios,
y ellas le dieron a entender que lo siguiente serviría de señal:
Que a ellas les iría bien, pero que a él no.

Después de esto sucedió que la Inquisición envió a buscarlas.
Ese mismo día la esposa del cónsul les llevó algo de comer, pero al pasar junto a ellas,
Catherine fue golpeada, como si hubiera recibido una flecha en el corazón,
y le pareció oír una voz diciendo: "`Ella ha logrado su propósito.`"
Entonces Catherine no quiso probar la comida, sino que se apartó y lloró mucho.
El cónsul la llamó y le dijo que la Inquisición había mandado a buscarlas,
al recibir órdenes de Roma, pero que él esperaba que ellas fueran liberadas.
Esto, sin embargo, no era cierto,
porque él sabía (como ellas entendieron más tarde) que se había
preparado una habitación para ellas en la prisión de la Inquisición.

No había pasado mucho tiempo antes de que el canciller,
el cónsul y uno con la vara negra llegaran a buscarlas,
y las llevaran delante del señor inquisidor.
Él les preguntó si habían cambiado de opinión,
porque parece que esto se les había exigido anteriormente,
pero ellas respondieron que no, y que no abandonarían la Verdad.
Luego les preguntó acerca de esa nueva luz de la que ellas hablaban.
Ellas contestaron que no era una nueva luz,
sino la misma de la que los profetas y apóstoles dieron testimonio.
Entonces les preguntó cómo se había perdido esa luz desde los tiempos primitivos.
Ellas contestaron que no se había perdido, que los hombres todavía la tenían en ellos,
pero que no la conocían por causa de la noche de
la apostasía que se había extendido sobre las naciones.
Entonces les dijo que si cambiaban de opinión y hacían lo que se les había dicho,
que lo dijeran, o de lo contrario, las tratarían a su antojo.
Pero las dos mujeres, indicando que no cambiarían de religión, dijeron:
"`Hágase la voluntad del Señor.`" Entonces el señor
inquisidor se levantó y se fue con el cónsul,
dejándolas ahí,
y el hombre con la vara negra y el guarda las cogieron y
las metieron en una habitación interior de la Inquisición,
la cual sólo tenía dos pequeños agujeros en ella para luz y aire.
Este lugar estaba tan extremadamente caliente,
que parecía que la intención de ellos era sofocarlas, como podemos ver a continuación.

No mucho después fueron llevadas delante de los inquisidores
para ser interrogadas más a fondo.
No sólo les preguntaron sus nombres, sino también los nombres de sus esposos y padres,
y cuántos hijos tenían, y por qué estaban ahí. A lo que ellas respondieron,
que eran siervas del Dios vivo y que estaban allí para llamarlos al arrepentimiento.
Al día siguiente las llamaron de nuevo, pero esta vez las interrogaron por separado.
Cuando le preguntaron a Sara si ella era una verdadera Católica,
ella dijo que era una verdadera Cristiana, que adoraba a Dios en Espíritu y en Verdad.
Luego le mostraron un crucifijo y le pidieron que jurara que diría la verdad.
A lo cual ella dijo, que diría la verdad, pero que no juraría,
porque Cristo había mandado: "`No juréis en ninguna manera.`"

El cónsul inglés que también estaba presente, trató de persuadirla a que jurara,
y le dijo que nadie le haría daño. Como Sara tenía algunos libros con ella,
se los quitaron, y le preguntaron por qué llevaba ella esos libros,
a lo que ella respondió, porque ellas no podían hablar su idioma.
Luego le preguntaron qué era George Fox.
Ella respondió: "`Un ministro.`"
Además, le preguntaron de nuevo, por qué estaba ahí. Ella replicó,
para hacer la voluntad de Dios,
según había sido movida por el Señor. La siguiente pregunta fue,
cómo le había aparecido el Señor. A lo cual respondió: "`Por medio de Su Espíritu.`"
Y al preguntarle si ella había visto Su presencia y oído Su voz, su respuesta fue,
que ella había oído Su voz y visto Su presencia.
Entonces le preguntaron, qué le había dicho Él. Ella respondió,
que Él le había pedido que cruzara los mares para hacer Su voluntad.
Esto hizo que le preguntaran,
cómo había sabido ella que era el Señor quien le había pedido esto.
A lo que ella respondió, que Él le había indicado que Su presencia viva la acompañaría,
y que ella lo encontraba cumpliendo Su promesa,
porque ella sentía efectivamente Su presencia viva.
Después de esto se fueron.

Dos días después de esto llegaron los inquisidores y llamaron a Catherine,
y ofreciéndole el crucifico,
le dijeron que los magistrados le ordenaban jurar que diría la verdad.
A lo que ella dijo que diría la verdad, porque era testigo de Dios, pero que no juraría,
dado que Uno mayor que los magistrados había dicho: "`No juréis en ninguna manera.
Pero sea vuestro hablar: Sí, sí; no, no; porque lo que es más de esto, procede del mal.`"
Entonces ellos le dijeron: "`Debes obedecer al juez y él te ordena jurar.`"
Ella objetó: "`Yo obedeceré al juez, pero si debo jurar, haré algo injusto,
porque el Justo (Cristo) dijo:
'`No juréis en ninguna manera.`'`" Entonces le preguntaron si ella
reconocía al Cristo que había muerto en Jerusalén. Ella respondió:
"`Nosotras reconocemos al mismo Cristo y a ningún otro; Él es el mismo ayer,
hoy y por los siglos.`"
A continuación le preguntaron,
qué haría en Jerusalén. Ella respondió que no sabía que debía ir ahí,
pero que había intentado ir a Alejandría. "`¿A hacer qué?,`" le preguntaron ellos.
La respuesta de ella fue: "`La voluntad de Dios; y si el Señor abriera mi boca,
llamaría a la gente al arrepentimiento, les declararía el día del Señor,
y dirigiría sus mentes de las tinieblas a la luz.`"
También le preguntaron si ella había visto al Señor; y ella respondió:
"`Dios es espíritu, y Él es discernido espiritualmente.`"

Ahora bien,
aunque de las respuestas de estas mujeres muy poco podía ser tomado para culparlas,
las mantuvieron encerradas, lo que pareció afligir al cónsul inglés,
pues llegó donde ellas con lágrimas en sus ojos y les dijo,
que estaba tan dolido por ellas como por su propia carne.
Pues parece que él había recibido algo por entregarlas,
lo que voluntariamente habría devuelto,
si de ese modo hubiera podido obtener su libertad.
Sin embargo, un temor servil lo había poseído y nunca tuvo paz mientras vivió.

Algunos días después de esto, llegaron un magistrado, dos frailes,
el hombre con la vara negra, un escriba y el guarda de la inquisición para interrogarlas.
Ellos les pidieron nuevamente que juraran, pero respondieron como antes,
que Cristo había dicho:
"`No juraréis en ninguna manera;`" y que el apóstol Santiago había encargado lo mismo.
Entonces el magistrado les preguntó si dirían la verdad, y ellas dijeron:
"`Sí.`" En seguida les preguntó si creían en el credo,
a lo que ellas dijeron que sí creían en Dios, y en Jesucristo,
y que había nacido de la virgen María y sufrido en Jerusalén bajo Poncio Pilatos,
que se había levantado de los muertos al tercer día y ascendido a Su Padre,
y que vendría a juzgar tanto a los vivos como a los muertos.
Les preguntó además, cómo creían en la resurrección, y ellas respondieron,
que creían que los justos y los injustos se levantarían, conforme a las Escrituras.
Lo siguiente que preguntó fue: "`¿Creen ustedes en los santos y les oran a ellos?`"
Su respuesta fue: "`Nosotras creemos en la comunión de los santos,
pero no les oramos a ellos, sino sólo a Dios en el nombre de Jesús.`"

Su siguiente pregunta fue, si ellas creían en la iglesia Católica, y ellas respondieron,
que ellas creían en la verdadera iglesia de Cristo,
"`pero la palabra católica,`" dijeron, "`no la hemos leído en las Escrituras.`"
También les preguntó si ellas creían en el purgatorio.
"`No, sino en el cielo y el infierno,`" le respondieron.
Entonces uno de los frailes, que era inglés dijo,
que se nos manda a orar por los muertos,
y puesto que los que estaban en el cielo no tenían necesidad,
y para los que estaban en el infierno no había redención,
entonces debía haber un purgatorio.
Entonces él les preguntó, si ellas creían en el santo sacramento, a lo que respondieron,
que nunca habían leído la palabra sacramento en las Escrituras.
El fraile replicó: "`Donde ustedes leen en sus biblias santificación,
en las nuestras es sacramento.`"
Él dijo que el santo sacramento de ellos era el pan y el vino,
que ellos convertían en carne y sangre de Cristo, por virtud de Cristo.
"`Entonces,`" dijeron las mujeres, "`ustedes obran milagros,
pues la virtud de Cristo es la misma que era cuando Él convirtió
el agua en vino en las bodas de Caná.`" El fraile dijo:
"`Si nosotros no comemos la carne y bebemos la sangre del Hijo de Dios,
no tenemos vida en nosotros.`"
Ellas respondieron: "`La carne y la sangre de Cristo son espirituales,
y nosotras nos alimentamos de ello diariamente,
porque lo que ha sido engendrado de Dios en nosotras,
no puede vivir sin comida espiritual,
más de lo que pueden hacerlo nuestros cuerpos temporales sin comida temporal.`"
Entonces dijo: "`Ustedes nunca oyen misa.`"
"`Pero,`" dijeron ellas, "`nosotras oímos la voz de Cristo,
el único que tiene palabras de vida eterna y que es suficiente para nosotras.`"
Él replicó: "`Ustedes son herejes y paganas,`" a lo que ellas respondieron:
"`Herejes son los que viven en pecado y maldad, y paganos los que no conocen a Dios.`"

Luego se les preguntó quién era la cabeza de la iglesia de ellas, a lo que respondieron:
"`Cristo.`"
Además se les preguntó qué era George Fox, ellas dijeron: "`Él es un ministro de Cristo.`"
Al ser interrogadas si él las había enviado, la respuesta de ellas fue:
"`No. El Señor nos movió a venir.`"
Entonces el fraile dijo: "`Ustedes están engañadas y no tienen la verdadera fe,
aunque tengan todas las virtudes.`"
Ellas replicaron: "`La fe es el fundamento del que proceden las virtudes.`"
Después se les dijo que si tomaban el santo sacramento podrían obtener su libertad,
de lo contrario, el papa no las dejaría ir ni por un millón de piezas de oro,
sino que perderían sus almas y sus cuerpos también. A esto ellas dijeron:
"`El Señor ha provisto para nuestras almas,
y nuestros cuerpos son libremente entregados para servirle a Él.`"
Luego se les preguntó si no creían que el matrimonio era un sacramento,
y ellas respondieron que era una ordenanza de Dios.
También se les preguntó si creían que los hombres podían perdonar pecados,
y la respuesta de ellas fue, que nadie podía perdonar pecados, sino sólo Dios.

Después de otro intercambio de palabras las mujeres preguntaron:
"`¿En qué les hemos hecho daño para que nos mantengan
prisioneras todos los días de nuestra vida?
Nuestra sangre inocente será requerida de sus manos.`"
El fraile dijo que él tomaría la sangre de ellas sobre sí mismo.
Ellas respondieron:
"`Llegará el momento en el que encontrarás que tienes
suficiente sobre ti mismo sin ella.`"
Entonces se les dijo que el papa era el vicario de Cristo,
y que lo que él hacía era para el bien de sus almas.
A esto ellas respondieron:
"`El Señor no ha encomendado la carga de nuestras almas al papa, ni a ustedes tampoco,
porque Él las ha tomado en Su posesión. ¡Gloria sea a Su nombre por siempre!`"
Entonces se les dijo que debían ser obedientes.
Ellas contestaron que ellas eran obedientes al gobierno del Espíritu o luz de Cristo.
El fraile dijo: "`Nadie tiene la verdadera luz sino los católicos,
la luz que ustedes tienen es el espíritu del diablo.`"
Pero dijeron ellas:
"`¡Ay de aquellos que maldicen a Jesús! ¿Puede el
diablo dar poder sobre el pecado y la iniquidad?
Eso destruiría su reino.`"
"`Todos se ríen y se burlan de ustedes,`" dijo el fraile.
"`Pero,`" respondieron ellas, "`¿qué será de los burladores?`"
"`Eso no importa,`" dijo él,
"`ustedes se apresuran a predicar y no tienen la verdadera fe.`"
Ellas respondieron: "`La verdadera fe se sostiene en una consciencia pura,
vacía de ofensa hacia Dios y los hombres.
Todos tienen la verdadera fe que cree en Dios y en Jesucristo a quién Él ha enviado,
pero los que dicen que creen y no guardan Sus mandamientos, son mentirosos,
y la fe no está en ellos.`"

El fraile confesó que eso era cierto,
aunque las molestaba continuamente con amenazas para que se convirtieran.
Para este fin fueron encerradas en una habitación tan caliente,
que se dijo que era imposible que pudieran vivir mucho tiempo en ella.
Cuando se acostaban en la cama las picaban tantos mosquitos, que sus caras se hincharon,
como si se hubieran enfermado de viruela, por lo que muchos empezaron a temerles;
y el fraile le dijo a Sara que él divisaba un espíritu malo en la cara de ella.

En otro momento que estaban siendo interrogadas,
les preguntaron cuántos de sus amigos habían salido
al ministerio y a qué partes del mundo.
Ellas respondieron lo que sabían,
y se les dijo que todos los que entraran en el territorio donde el papa tenía poder,
nunca regresaría. Pero ellas dijeron que el Señor era suficiente para ellos,
como lo había sido para los tres muchachos en el horno de fuego,
y que su confianza estaba en Dios.
Como Catherine estaba enferma, le preguntaron porque se veía así,
y si el espíritu de ella estaba débil.
Ella respondió: "`No, mi cuerpo está débil porque no he comido nada.`"
Al oír esto, el fraile le ofreció una licencia para que comiera carne,
porque estaban en la Cuaresma de ellos,
pero ella la rechazó y dijo que no podía comer nada.
Después se fue a la cama, y permaneció ahí noche y día por doce días seguidos,
ayunando y sudando, pues estaba muy afligida y su agonía era grande.

Después de permanecer diez días allí, llegaron donde ella dos frailes, el canciller,
el hombre con la vara negra, un médico y el guarda.
Uno de los frailes le ordenó a Sara que saliera de la habitación,
y luego sacó de la cama la mano de Catherine, y dijo:
"`¿Es tan grande el demonio en ti que no puedes hablar?`"
A lo que ella respondió: "`Apártate de mí hacedor de iniquidad,
el poder del Señor está sobre mí, ¿y tú Lo llamas demonio?`"
Entonces él tomó su crucifijo para golpearla en la boca,
y ella le preguntó que si esa era la cruz que había
crucificado a Pablo al mundo y el mundo a Pablo.
Este fraile ignorante dijo que lo era.
Pero ella negó eso y dijo:
"`El Señor me ha hecho testigo para Él contra todos los hacedores de iniquidad.`"
Él entonces le ordenó que obedeciera y quiso golpearla, a lo que ella dijo:
"`¿Me vas a golpear?`"
Al decir él que sí lo haría, ella añadió:
"`Entonces estás fuera de la doctrina de los apóstoles,
porque ellos nunca golpearon a nadie.
Niego que seas uno de los enviados en el nombre del Señor.`" A esto él le respondió,
que él le había llevado un médico por caridad, y ella dijo:
"`El Señor es mi médico y salud salvadora.`"

El fraile, cada vez más enojado dijo, que sería azotada,
descuartizada y quemada esa noche en Malta,
y su amiga también. Pero ella le dijo modestamente que no tenía temor,
porque el Señor estaba a su lado, y que él no tenía poder sino el que había recibido,
y que si no usaba su poder para el mismo fin para el que el Señor se lo había dado,
Él lo juzgaría. Ante estas palabras todos quedaron mudos y se marcharon.
Luego el fraile se dirigió a Sara y le dijo que Catherine
lo había llamado hacedor de iniquidad.
"`¿Lo hizo?,`" dijo Sara, "`¿estás libre de pecado?`"
A lo que él respondió que sí. "`Entonces,`" contestó Sara,
"`ella te ha agraviado.`"

A última hora de la tarde,
algo se proclamó en la puerta de la prisión con el golpe de un tambor,
y a primera hora de la mañana algunos regresaron con un tambor y armas.
A mí me parece que eso fue hecho con el propósito de atemorizar a estas pobres mujeres,
y hacerlas creer que serían ejecutadas, pues, en realidad, no esperaban algo diferente,
ya que por varias semanas habían creído que serían llevadas a la hoguera.
Pero ellas estaban plenamente entregadas y rendidas
a lo que el Señor se complaciera en permitir.
Entre tanto, como Catherine continuaba enferma, el fraile regresó con el médico,
pero ella le dijo que no podía tomar nada a menos que sintiera la libertad.
Entonces él dijo que ellas nunca saldrían de esa habitación mientras vivieran,
y pretendiendo ser amable con ellas añadió:
"`Ustedes pueden agradecerle a Dios y a mí que sus condiciones no son peores,
porque pudieron haber sido peores.`"
Entonces respondieron, que si ellas hubieran muerto,
habrían muerto tan inocentes como cualquier siervo del Señor. El fraile,
volviéndose a Sara,
le pidió que se fijara en el tormento que sufriría Catherine a la hora de la muerte,
diciendo que miles de demonios vendrían a llevarse su alma al infierno.
Pero Sara le dijo que ella no le temía a tal cosa.
Él le preguntó a Catherine si no creía correcto que
los ancianos de la iglesia oraran por los enfermos.
Ella dijo: "`Sí, cuando son movidos por el Espíritu del Señor.`" Entonces,
él cayó sobre sus rodillas y comenzó a aullar y a
desear que cayeran sobre él toda clase de males,
si no tenía la fe verdadera.
Entre tanto, el médico estaba enfurecido porque ella no se había inclinado ante él.

Mientras Catherine estaba enferma, Sara no estaba exenta de gran aflicción,
pues le dolía ver a su querida compañera tan enferma,
y ella fácilmente previó que si Catherine moría sus
propios sufrimientos serían más pesados.
Sin embargo, ella estaba rendida a la voluntad del Señor,
y no resentía en lo más mínimo que Catherine llegara al reposo eterno.
Pero con el tiempo Catherine empezó a recuperarse, y al tener hambre y comer,
se sintió renovada.
Pero la habitación donde estaban encerradas estaba tan excesivamente caliente,
que a menudo se veían obligadas a levantarse de la cama y recostarse
cerca del hueco de la puerta para recibir aire y tener aliento.
El calor era muy grande, porque no sólo venía de afuera,
sino también de adentro de la cárcel, y las afectó tanto que la piel se les resecó,
se les cayó el pelo y se desmayaban con frecuencia.
Sus aflicciones eran tan grandes, que cuando era de día deseaban la noche,
y cuando era de noche deseaban el día. Sí,
debido a la debilidad humana deseaban la muerte,
y comían su pan llorando y mezclaban su bebida con lágrimas.

Una vez,
que los frailes acudieron a verla con un médico diciéndole que era una obra de caridad,
Catherine les preguntó: "`¿Nos mantienen en esta habitación tan caliente para matarnos,
y luego nos traen un doctor para mantenernos más tiempo vivas?`"
A esto el fraile dijo que el inquisidor perdería la cabeza si él las sacaba de ahí,
y que era mejor mantenerlas ahí que matarlas.
Entonces ellas le escribieron al inquisidor y le expusieron su inocencia,
y también dijeron, que si era la sangre de ellas lo que buscaban,
podían tomarla de cualquier otra forma,
así como también sofocándolas en esa habitación caliente.
Pero esto enfureció tanto al inquisidor,
que mandó al fraile a quitarles sus plumas y tinteros,
(y ya les habían quitado sus biblias).
Ellas le preguntaron la razón por la que les eran quitados sus bienes; se les respondió:
"`Todo es nuestro y sus vidas también, si así lo deseamos.`"
Entonces ellas preguntaron, cómo habían perdido el derecho de sus vidas, y se les dijo:
"`Por traer libros y papeles.`"
Ellas replicaron, que si había algo en ellos que no fuera cierto,
que ellos podían escribir contra eso.
Pero el fraile dijo:
"`Nosotros no les escribimos a tontos y asnos que no saben el verdadero
latín.`" Además se les dijo que el inquisidor las quería separar,
porque Catherine estaba débil y debía ir a una habitación más fresca,
pero que Sara debía permanecer ahí. Entonces Catherine tomó a Sara por el brazo y dijo:
"`El Señor nos ha unido y ¡ay de aquellos que nos separen!
Preferiría morir aquí con mi amiga, que separarme de ella.`"
Esto impresionó tanto al fraile que se fue y no regresó por cinco semanas,
y la puerta de esa habitación no fue abierta en todo ese tiempo.

Pasado ese tiempo, los frailes regresaron para separarlas,
pero Catherine estaba enferma y con un sarpullido de pies a cabeza.
Ellos enviaron a buscar un médico, y este les dijo que ellas debían tener aire,
o de lo contrario debían morir.
Esto le fue dicho al inquisidor y él ordenó que se abriera la puerta seis horas al día;
pero diez semanas después fueron separadas,
lo cual fue una aflicción tan gravosa para ellas,
que declararon que la muerte misma no les habría sido tan difícil.
Los frailes decían que ellas se corrompían una a la otra,
y que estando separadas se inclinarían y someterían. Pero estos hombres se vieron decepcionados,
porque las mujeres eran más fuertes después que antes,
al ser adaptadas por el Señor a cada condición. Antes de que fueran separadas,
los frailes les habían llevado un azote pequeño de
cuerdas de cáñamo y les preguntaron si deseaban tenerlo,
y les dijeron que los monjes los usaban para azotarse a sí mismos hasta sangrar.
Pero las mujeres dijeron que eso no podía alcanzar al diablo,
porque él se sentaba en el corazón. Luego los frailes dijeron:
"`Toda la gente de Malta está a favor de ustedes,
y si cambiaran y se hicieran Católicas todos las aceptarían.`" Pero ellas respondieron:
"`El Señor nos ha transformado en lo que no cambia.`"
Ellos dijeron: "`Todas nuestras mujeres santas están orando por ustedes,
y si se convierten serán honradas por todo el mundo.`"
Ellas replicaron: "`El mundo yace en maldad,
y nosotras hemos rechazado todo honor y toda gloria del mundo.`"
Los frailes añadieron: "`También serán honradas por Dios, pero si no,
serán odiadas por todos.`"
"`Esto,`" dijo una de las mujeres, "`es una muestra evidente de Quién somos siervas,
porque el siervo no es mayor que su Señor.`"

Un Primer día, los frailes llegaron y les ordenaron arrodillarse con ellos para orar.
Ellas expresaron que ellas sólo podían orar cuando eran movidas por el Señor. Entonces
los frailes les ordenaron una segunda vez y luego se arrodillaron al lado de la cama,
y oraron según su manera.
Tras hacerlo les dijeron a las mujeres:
"`Hemos probado sus espíritus y ahora sabemos de qué espíritu son.`"
Pero ellas les dijeron que no podían saber eso,
a menos que sus mentes se volvieran a la luz de Cristo en sus consciencias.
Entonces, el fraile inglés enfureciéndose les mostró su crucifijo y les ordenó mirarlo,
pero ellas le dijeron: "`El Señor dice:
No te harás imagen de ninguna cosa arriba en el cielo, o abajo en la tierra,
o en el agua debajo de la tierra.
No te inclinarás ante ellas ni las adorarás, porque yo el Señor tu Dios,
soy Dios celoso.`"
El fraile al ver a Sara hablarle tan audazmente pidió los grilletes para encadenarla.
Entonces ella bajó la cabeza y le dijo: "`No sólo mis manos y pies,
sino también mi cuello por el testimonio de Jesús.`" El fraile aparentemente
apaciguado dijo que él les haría cualquier bien que pudiera,
porque vio que lo que ellas hicieron no había sido con malicia.
Los frailes con frecuencia les decían:
"`Si ustedes cedieran un poquito serían puestas en libertad, pero no quieren ceder nada,
sino estar contra todo.`"
A lo que ellas respondían, que harían cualquier cosa que obrara para la gloria de Dios.

Mientras estuvieron encarceladas ahí,
sucedió que la casa de la Inquisición fue construida nueva o reparada,
lo que tomó cerca de un año y medio.
Durante ese tiempo, algunas personas importantes fueron a ver la construcción,
lo que les dio oportunidad a estas mujeres de hablarles
y declarar la Verdad en el nombre del Señor.

Ahora bien,
aunque ellas eran amenazadas por los frailes por predicar la luz de Cristo tan audazmente,
no sólo los magistrados, sino también el señor inquisidor,
se empezaron a mostrar más moderados con ellas,
y dieron la orden de que se les dieran plumas,
tinta y papel para que escribieran a Inglaterra.
Algunos parecían inclinados a ponerlas en libertad,
pero los frailes trabajaban fuertemente contra eso,
pues habían trabajado cerca de tres cuartas parte del año para separarlas,
antes de conseguirlo.
Y cuando finalmente lo habían logrado,
le dijeron a Catherine que ellas nunca se volverían a ver las caras.

Mientras tanto, Catherine estaba enferma y casi no tenía apetito, y no quería comer nada,
sino lo que le fuera ofrecido por Sara.
Y,
tras decírsele a uno de los frailes que ella necesitaba que alguien
le lavara la ropa y le preparara algo de comida caliente,
él mandó a buscar a Sara para saber si ella lo haría por Catherine,
y Sara dijo que sí lo haría. Por este medio oyeron
una de la otra todos los días por varias semanas.
Una vez un fraile le dijo a Catherine:
"`Tú puedes liberarte de tu miseria cuando quieras,
porque puedes hacerte Católica y tener la libertad de ir adonde quieras.`"
Ella le dijo: "`Así tendría un nombre de que vivía, cuando estaba muerta.
Ustedes ya tienen suficientes católicos,
y si se esforzaran por llevar a algunos de ellos a la luz en sus consciencias,
entonces temerían y no pecarían.`" Este fraile estaba tan ansioso,
que dijo que perdería uno de sus dedos si ella y Sara se volvían Católicas.
Pero ella dijo: "`Babilonia es la ciudad que se construye con sangre,
pero Sión es redimida con juicio.`"

Se emplearon muchos medios para apartarlas de sus convicciones,
y en una ocasión trataron de persuadirla de que pusiera una pintura a
la cabecera de su cama como representación. Pero ella dijo con aborrecimiento:
"`¡Qué! ¿Crees que me hace falta un becerro para adorar?
¿Caminan ustedes por la regla de las Escrituras?`"
A lo que el fraile respondió: "`Sí, lo hacemos, pero también tenemos tradiciones.`"
Ella replicó:
"`Si sus tradiciones derogan o discrepan de los fundamentos de la doctrina de Cristo,
de los profetas y de los apóstoles,
las niego en el nombre del Señor.`" Pero él afirmó que no lo hacían. Entonces ella preguntó
qué regla tenían ellos para quemar a los que no podían unirse a ellos por causa de consciencia.
Él respondió: "`San Pablo lo hizo peor, porque él los entregaba al diablo,`" y añadió,
que ellos juzgaban condenados a todos los que no eran de su fe.
Entonces ella objetó varios de los ritos supersticiosos de la iglesia de Roma,
y también mencionó la prohibición del matrimonio, "`que,`" dijo ella,
"`es doctrina de demonios, según lo dicho por el apóstol.`"

Al ser puesto en aprietos, él le dijo que Pedro había sido el primer papa de Roma,
y que había edificado un altar ahí,
y que el papa era su sucesor y podía hacer lo que quisiera.
Pero ella refutó eso con buena razón. Él, entonces,
se jactó de la antigüedad de su iglesia,
pero ella expresó que la iglesia a la que ella pertenecía era aún más antigua:
"`Porque nuestra fe es desde el principio,`" dijo ella,
"`y Abel era de nuestra iglesia.`"
El fraile viéndose perdido y que ya no podía resistir a Catherine,
se fue adonde Sara y habló con ella en los mismos términos,
y ella también le dijo que Abel era de su iglesia.
A lo que él dijo: "`Abel era Católico,`" y sobrepasándose dijo:
"`Y Caín y Judas también.`" A lo que Sara respondió: "`Si eso es cierto,
entonces el diablo es Católico y yo no lo seré. No
me convertiré aunque me partas en pedazos.
Creo que el Señor me haría capaz de soportarlo.`"

En otro momento, el citado fraile, cuyo nombre era Malaquías,
volvió adonde Catherine y le dijo que si ella estaba dispuesta a ser Católica,
que debía decirlo, de otro modo,
la tratarían severamente y nunca más vería el rostro de Sara,
sino que moriría sola y mil demonios se llevarían su alma al infierno.
Entonces ella le preguntó si él era el mensajero de Dios para ella.
Él respondió: "`Sí.`" "`¿Por qué?,`" preguntó ella, "`¿cuál es mi pecado,
o en qué he provocado al Señor para que me envíe semejante mensaje?`"
"`¿Es?,`" dijo el fraile: "`porque no quieres ser católica.`"
Después de lo cual ella dijo: "`Te rechazo a ti y también rechazo el mensaje,
y al espíritu que habla en ti,
porque el Señor nunca habló así.`" Él enfureciéndose le dijo que
le pondría un montón de cadenas donde no viera el sol ni la luna.
Ella dando a entender cuán rendida estaba dijo,
que él no podría separarla del amor de Dios que es en Cristo Jesús,
la pusiera donde la pusiera.
Y al agregar él que la entregaría al diablo, ella prosiguió:
"`No les temo a todos los demonios del infierno,
el Señor es mi guardián. Aunque tuvieras la Inquisición,
con todos los países de alrededor de tu lado, y yo estuviera sola, no les temo.
Y si fueran miles más, el Señor está a mi derecha;
y lo peor que pueden hacer es matar el cuerpo,
no pueden tocar mi vida más de lo que el diablo pudo tocar la de Job.`"

Entonces el fraile dijo que ella nunca saldría viva
de la habitación. A lo que ella valientemente respondió:
"`El Señor es suficiente para librarme, pero ya sea que lo quiera o no,
no abandonaré la Fuente viva para beber de cisternas rotas.
Y ustedes no tienen ninguna ley para retenernos aquí,
sino la ley que tuvo Acab para la viña de Nabot.`"
El fraile, maldiciéndose e invocando sus dioses salió corriendo,
y mientras tiraba de la puerta dijo: "`¡Quédate aquí, miembro del diablo!`"
Y ella dijo: "`Los miembros del diablo hacen las obras del diablo;
y los ayes y plagas del Señor caerán sobre ellos por eso.`"

Luego, el fraile fue y le contó al inquisidor de esto, y el inquisidor se rio de él,
y antes de que volviera,
Catherine había sido sacada de esa habitación. Cuando fue adonde ella,
llevó con él a uno de los hombres del inquisidor y dos buenas gallinas,
y dijo que el señor inquisidor se las había enviado en amor a ella.
Ella respondió que recibía su amor,
pero no se mostró muy dispuesta a aceptar las gallinas,
dando a entender que estaba dispuesta a pagar por ellas,
pues no quería ser carga de nadie mientras tuviera su propio dinero.
El fraile, quien al parecer quería que pusieran su dinero a sus pies,
dijo que ellas no debían contar nada como propio,
porque en los tiempos primitivos los cristianos vendían
sus posesiones y ponían el dinero a los pies de los apóstoles.
Además dijo: "`No te faltará nada, aunque gastemos mil coronas.
Pero eres orgullosa,
porque no quieres coger las gallinas que el inquisidor te envió por caridad.`"
Entonces Catherine preguntó: "`¿Qué clase de caridad es esta,
dado que me mantiene prisionera?`"
Él respondió que era por el bien de sus almas que él las mantenía prisioneras; y añadió:
"`Si no hubieran ido a predicar, habrían podido ir donde quisieran.`"
Ella respondió: "`Nuestras almas están fuera del alcance del inquisidor.
Pero, ¿por qué se extiende tu amor hacia nosotras más que a tu propia gente?
Pues ellos cometen toda forma de pecados de los que no puedes acusarnos.
¿Por qué no los metes en la casa de la Inquisición y les mandas que se conviertan?`"

Entonces él le dijo:
"`Tú no tienes la verdadera fe;`" y mostrándole su
crucifijo le preguntó si ella pensaba que él lo adoraba.
Ella le preguntó:
"`¿Qué haces entonces con él?`" Y él respondió que era una
representación. Ella replicó que eso no representaba a Cristo,
pues Él era la imagen expresa de la gloria de Su Padre, que es luz y vida.
"`Pero,`" continuó ella, "`si puedes poner vida en cualquiera de tus imágenes,
entonces tráela y muéstramela.
¿Qué representación tenía Daniel en el foso de los leones,
o Jonás en el vientre de la ballena?
Ellos clamaron al Señor y Él los libró.`" El fraile,
que no podía soportar oírla hablar tanto contra los ídolos,
dijo que ella hablaba como un loca, y agregó: "`Te entregaré al diablo.`"
Ella sin temor a eso, dijo: "`Entrega lo tuyo,
yo soy del Señor.`" Entonces él se puso de pie y dijo:
"`Haré contigo lo que los apóstoles hicieron con Ananías y Safira.`"
Entonces ella, poniéndose también de pie, dijo: "`Te rechazo en el nombre del Señor,
el Dios vivo; tú no tienes poder sobre mí.`"

El fraile se fue con las gallinas adonde Sara y le dijo que Catherine estaba enferma,
y que el señor inquisidor había mandado dos gallinas,
y que Catherine estaría encantada de comer un trozo si ella preparaba una en ese momento,
y la otra el día siguiente.
Sara, que no era menos prudente y cautelosa que Catherine,
y no estaba dispuesta a recibir ese regalo antes de saber lo que podría ser conveniente,
le respondió lo mismo que Catherine.
Entonces, llevándose de nuevo las gallinas dijo:
"`Ustedes desean fervientemente ser quemadas,
porque así le harían creer al mundo que aman tanto a Dios como para sufrir de esa manera.`"
Oyendo Catherine eso dijo: "`Yo no deseo ser quemada, pero si el Señor me llama a eso,
creo que Él me dará poder para padecerlo por Su Verdad,
y si cada cabello de mi cabeza fuera un cuerpo,
yo podría ofrecerlos todos por el testimonio de Jesús.`"

El fraile regresó después y le preguntó nuevamente a Catherine,
si ella no había sido inspirada por el Espíritu Santo a ser Católica
desde que había llegado a la casa de la Inquisición. Ella dijo:
"`No.`" Pero él arguyendo lo contrario dijo:
"`Tú eres de las que llaman al Espíritu de Dios, Espíritu del diablo.`"
"`No,`" respondieron ellas (que aunque estaban separadas podían oírse una a la otra),
"`el Espíritu de Dios en nosotras resiste al diablo,
y la inspiración del Espíritu Santo no se realiza en la voluntad del hombre,
ni en el tiempo del hombre, sino en la voluntad y tiempo de Dios.`"
Discutieron más acerca de este asunto, y luego,
pidiendo sus biblias que les habían quitado,
él les dijo que nunca las verían de nuevo porque eran falsas.

Así, a menudo eran molestadas y presionadas por los frailes,
que por lo general llegaban de dos en dos, aunque a veces solo uno.
Uno de ellos con frecuencia levantaba su mano para golpearlas, pero nunca lo hizo,
pues como ellas no se dejaban mover por el miedo, se avergonzaba,
y luego decía que ellas eran buenas mujeres y que les haría todo el bien que pudiera.
Como en efecto hacía, pues algunas veces trabajaba para ellas,
y decía que era por amor a Dios y que ellas debían agradecerle por eso.
A lo que ellas respondían: "`Los que hacen algo para Dios,
no buscan una recompensa del hombre.`"
En una ocasión esto lo enojó tanto,
que dijo que ellas eran las peores de todas las criaturas,
y que serían tratadas peor que los Turcos, Armenios y Luteranos.
A lo que una de ellas dijo: "`La vida pura siempre ha sido contada como lo peor,
y si sufrimos somos del Señor y podemos confiar en Él. Haz lo que quieras con nosotras,
no tememos ninguna mala noticia.
Estamos establecidas y cimentadas en la Verdad, y cuánto más nos persigan,
más fuertes nos haremos.`"
Ellas en verdad experimentaban esto, según lo indicaban en sus cartas,
aunque estuvieron separadas una de la otra un año.

Sucedió en una ocasión, que un inglés que vivía ahí,
habiendo oído que Sara estaba en una habitación con una ventana que daba a la calle,
subió por la pared y le habló unas pocas palabras,
pero fue violentamente jalado y echado en prisión para ser juzgado por su vida.
Él era uno de los que ellos habían tomado de los Turcos,
y le habían hecho Católico romano.
Los frailes fueron donde ellas para saber si él les había llevado alguna carta.
Ellas dijeron: "`No.`" Catherine ni siquiera lo había visto, sin embargo,
les dijeron que era probable que lo ahorcaran.
Sara le dio información a Catherine de esto escribiéndole una pocas líneas
(porque parece que en ese momento ya no podían oírse una a la otra),
y le dijo que ella pensaba que los frailes ingleses
eran los principales actores de este asunto.

Esto entristeció a Catherine y le escribió a Sara de nuevo,
pues ellas tenían una forma privada de escribirse una a la otra.
En esta carta, después de su saludo,
le dijo a Sara que podía estar segura de que los frailes eran los principales actores,
pero que ella creía que el Señor preservaría a ese pobre inglés por Su amor,
y que se sentía movida a buscar al Señor por él con lágrimas,
y que deseaba que ella le enviara algo a él una vez al día, si el guarda lo llevaba.
También le dijo que se sentía embargada por el amor de Dios por el alma de ella,
y que su Amado era "`señalado entre diez mil,`" y
que no le temía al rostro de ningún hombre,
aunque podía sentir sus flechas.
Además,
le indicaba que tenía la expectativa del regreso de ellas sanas y salvas a Inglaterra.
Y en la conclusión de la carta,
le pidió a Sara que tuviera cuidado de no ser tentada con dinero.

Pero esta carta (por cuál medio, nunca lo supieron), llegó a manos del fraile inglés,
quien la tradujo al italiano y se la entregó al señor inquisidor.
Luego,
fue con el asistente del inquisidor donde Catherine y le mostró los dos documentos,
y le preguntó si ella podía leer el que estaba en inglés. "`Sí,`" dijo ella,
"`yo lo escribí.`" "`¡Ah, sí!,`" dijo él. "`Y,
¿qué es lo que dices de mí aquí?`" "`Nada más que lo que es cierto,`" replicó ella.
Entonces él dijo: "`¿Dónde está el papel que envió Sara?
Entrégalo o de lo contrario buscaré en tu baúl y en cualquier otro lugar.`"
Ella indicándole que buscara donde quisiera, él le dijo:
"`Debes decirme quién te trajo tinta, o de lo contrario, serás encadenada al momento.`"
Ella le respondió que no había hecho más que lo que
era justo y correcto a los ojos de Dios,
y que lo que ella sufriera por esa razón, sería por la Verdad.
Luego él dijo: "`Por amor a Dios, dime qué escribió Sara.`"
Ella le dijo algo de lo que había escrito, y que lo que había dicho era verdad.
"`Pero,`" respondió él,
"`tú dices que era probable que nosotros las tentáramos con dinero.`"
Y esto de hecho sucedió después.

Entonces el asistente cogió la tinta de Catherine y la tiró, y se fueron;
y el pobre inglés fue liberado la mañana siguiente.
De ahí se fueron donde Sara y le dijeron que Catherine
honestamente lo había confesado todo,
y que lo mejor sería que ella confesara también. Ellos la amenazaron con una soga,
que le quitarían la cama y el baúl, y el dinero también. A lo que Sara dijo,
que era posible que ya no pudiera enviarle a Catherine nada más,
pero luego le preguntó al asistente, si él era un ministro de Cristo o un magistrado.
Que si era un magistrado, él podía tomar su dinero, pero que ella no se lo daría. Él,
enfureciéndose, dijo que ella estaba poseída, a lo que ella replicó: "`Si es así,
entonces es con el poder de una vida indestructible.`"

Así, de vez en cuando sufrían asalto tras asalto, y a veces sucedía también,
que los que llegaban a verlas eran golpeados en el corazón,
lo cual ofendía a los frailes.
Finalmente el dinero casi se les había acabado,
pues a veces lo habían utilizado para comer.
Los frailes les dijeron que ellas habrían podido guardar el dinero para otros servicios,
porque ellos las habrían mantenido mientras estuvieran prisioneras.
A esto ellas respondieron que no habrían podido guardar
el dinero y haber sido carga para otros.
Sucedió entonces que perdieron el apetito y comieron poco por tres o cuatro semanas,
hasta que finalmente se vieron obligadas a ayunar por varios días seguidos.
Esto hizo que los frailes dijeran que era imposible
que alguien viviera con tan poca comida como ellas.
Luego se les dijo que el señor inquisidor había dicho
que ellas podían tener lo que quisieran,
a lo que respondieron, que no estaban en sus propias voluntades ayunar,
sino que debían esperar a conocer la mente del Señor; lo que Él quería que hicieran.
Así continuaron debilitándose, especialmente Sara,
que al comprender que su muerte estaba cerca,
se vistió como deseaba ser depositada en la tumba.
Ambas estaban tan débiles que no podían ponerse ni quitarse la ropa,
y eran incapaces de arreglar sus camas,
y aunque deseaban estar juntas en una misma habitación, los frailes no lo permitieron.
En esta condición concluyeron que era probable que murieran,
pero el cielo había dispuesto otra cosa.

Por ese entonces, Catherine, que estaba siendo ejercitada en súplica al Señor,
mientras oraba que le placiera a Él ponerle fin a la prueba
de ellas de la manera que le pareciera bien a Sus ojos,
creyó oír una voz que decía: "`No morirán.`" Ella tomó esto como una voz celestial,
y a partir de ese momento se sintieron refrescadas con la presencia viva del Señor,
para gran gozo y consuelo de ambas,
de modo que sintieron la libertad para comer de nuevo.
Entonces se les proporcionó buena comida,
pero aún tenían temor de comer algo que en algún sentido pudiera ser considerado impuro.
Por tanto, clamaron al Señor diciendo:
"`Preferimos morir que comer algo que esté contaminado o sea impuro.`"
Entonces Catherine entendió que se le había dicho de parte del Señor:
"`Puedes comer tan libremente,
como si hubieras trabajado por ello con tus propias manos.`"
Y Sara, que a veces trabajaba para otros en la casa de la Inquisición,
fue persuadida de que se le había dicho por inspiración:
"`Tú comerás el fruto de tus manos, y serás bendecida.`"
Y así comieron, y por ocho o diez días obtuvieron todo lo que pidieron.

Pero un tiempo después de esto, fueron tan afligidas por falta de comida,
que esto les hizo más daño que el ayuno.
Sin embargo, al ser conservadas con vida, un fraile dijo:
"`El Señor las mantiene vivas mediante Su gran poder,
porque Él desea que sean Católicas.`"
A esto ellas respondieron: "`Un día será conocido que el Señor tenía otro fin en esto.`"
Pero los frailes les dijeron claramente que no había redención para ellas.
Después de lo cual ellas dijeron:
"`En el Señor hay misericordia y abundante redención,`" y les advirtieron
que tuvieran cuidado de no "`ser hallados luchando contra Dios.`"
Los frailes respondieron: "`Ustedes son unas insensatas.`"
"`Entonces lo somos,`" replicaron ellas, "`las insensatas del Señor;
y los tales son queridos y preciosos ante Sus ojos.`"
Entonces los frailes, mostrándoles sus coronillas afeitadas,
dijeron que ellos eran los insensatos del Señor, y señalando sus vestidos,
dijeron que ellos los usaban por amor a Dios para que el mundo se riera de ellos.

Por este tiempo uno de los frailes hizo lo que pudo para enviar a Catherine a Roma,
y al no conseguirlo, dijo que irían los dos.
Pero como esto tampoco surtió efecto,
el fraile fue enviado allí con un documento que contenía acusaciones contra Catherine.
Pero, Catherine, al enterarse del contenido de la carta,
le habló celosamente al escriba y pronunció ayes contra todas esas mentiras,
y lo desafió en el nombre del Señor. Antes de que el fraile
partiera le dijo a Sara que Catherine era bruja,
y que ella sabía qué se hacía en otros lugares.
Dijo esto, porque una vez que le había dicho un montón de mentiras a Catherine,
ella le dijo que ella tenía un Testigo de Dios en ella que era fiel y verdadero,
y que ella le creía a ese Testigo más que a las palabras de él.

Después que se fue, llegó a verla el cónsul inglés,
y llevaba con él un dólar enviado por el capitán de un barco que había llegado de Plymouth.
Ella le dijo que recibía el amor de su compatriota, pero que no podía recibir su dinero.
Entonces él le pregunto qué haría ella si no tomaba el dinero, a lo que ella respondió:
"`El Señor es mi porción, y por tanto, no me hace falta ninguna cosa buena.
Nosotras estuvimos en tu casa cerca de quince semanas,
¿viste alguna causa de muerte o cautiverio en nosotras?`"
Y al responder él que no,
ella le indicó que en cierto sentido él había sido cómplice del encarcelamiento de ellas,
y que él no ignoraba la intención. "`Tú sabías,`" dijo ella,
"`que una habitación estaba preparada para nosotras en la Inquisición,
y si no hubiéramos sido mantenidas vivas por el gran poder Dios,
hace mucho tiempo que habríamos muerto.`"
Tratando de excusarse dijo: "`¿Cómo habría podido evitarlo?`"
Entonces ella le recordó lo que había sucedido en la casa de él mientras estuvieron ahí,
y cómo los habían llamado al arrepentimiento y los habían advertido.
A lo que él respondió: "`Sea como sea, les irá bien.`"
Luego ella le recordó que él había requerido una señal de
ellas que demostrara que eran siervas del Señor Dios,
y le preguntó si no era cierto lo que ellas le habían dicho:
"`Tú eres un condenado y eres culpable ante Dios, sin embargo, arrepiéntete,
si puedes encontrar lugar para ello.`"
Mientras ella le hablaba así,
al cónsul le temblaban los labios y se le estremecía todo el cuerpo,
por lo que apenas podía mantenerse en pie,
y aunque era un hombre muy apuesto y en la flor de su vida,
se veía como alguien que se estaba muriendo.
Esta era señal suficiente para toda la ciudad,
si la hubieran tenido debidamente en cuenta.

Como Catherine rechazó la moneda, el cónsul se fue adonde Sara con el dinero,
pero ella también le dijo que no podía tomarla,
pero que si él tenía una carta para ellas, se sentiría libre de recibirla.
Él dijo que no tenía ninguna y le preguntó si necesitaba algo, a lo que ella respondió:
"`El Señor es mi Pastor, no me hace falta ninguna cosa buena; pero anhelo mi libertad.`"
Él, no queriendo desalentarla le dijo: "`La tendrás en un tiempo.`"
Pero él no vivió para verlo,
porque la siguiente vez que oyeron hablar de él estaba muerto.

Mientras el fraile estaba en Roma,
se les dijo que también iban a ser enviadas ahí. De hecho,
hubo una gran agitación al respecto,
pero parece que no pudieron ponerse de acuerdo en el asunto.
Mientras tanto, Catherine y Sara permanecían separadas,
pues había cinco puertas entre ellas con barras y cerraduras.
Sin embargo, Sara a veces encontraba una oportunidad,
fuera por descuido del guarda o porque era hecho a propósito,
para acercarse hasta donde podía ver a Catherine, y aunque los frailes las vigilaban,
ella a menudo llegaba a la puerta de Catherine por la noche.
Pero en una ocasión la descubrieron y la encerraron nuevamente, sin embargo,
no mucho tiempo después las puertas volvieron a quedar abiertas,
de modo que ellas se sentaban a la vista la una de la otra.

A veces, personas de varias naciones eran llevadas como prisioneras a la Inquisición,
y los frailes y otros hombres importantes,
se esforzaban a su manera por hacerlos cristianos.
Y ellas, por su parte, a menudo mostraban los errores del papismo y declaraban la Verdad,
por la cual estaban dispuestas a sufrir la muerte, si les era requerida;
pero esto fue tomado muy mal.
Al fin sucedió que dos ingleses llegaron a la ciudad
y trataron de obtener la libertad de ellas,
pero fue en vano.
Sin embargo,
poco después los magistrados mandaron por ellas y les preguntaron
si estaban enfermas o si les hacía falta algo;
y al decirles que podían escribir a Inglaterra,
le ordenaron al escriba que les diera tinta y papel.

No mucho después llegaron un tal Francis Steward, capitán de barco,
y un fraile de Irlanda, y ambos se esforzaron mucho por obtener su liberación;
y sus amigos en Inglaterra no escatimaron en nada que pudiera procurarles la libertad.
Pero esta no estaba en poder de los magistrados,
pues el inquisidor dijo que él no podía ponerlas en libertad sin una orden del papa.
No obstante,
Catherine y Sara fueron llevadas a la sala de la corte y el cónsul inglés les preguntó,
si ellas estaban dispuestas a regresar a Inglaterra.
Ellas dijeron: "`Sí, si es la voluntad de Dios.`"
El capitán del barco, que también estaba ahí,
les habló con lágrimas en los ojos y les contó lo que él había hecho a favor de ellas,
pero que había sido en vano.
"`Es el inquisidor,`" dijo él, "`quien no las dejará salir libres,
porque ustedes han predicado entre estas personas.`"
Ellas dijeron que ellas habían dado testimonio de la Verdad,
y que estaban dispuestas a sellarlo con su sangre.
Él respondió, que si ellas eran puestas en libertad,
él les daría los pasajes gratis y proveería para ellas.
Y ellas le respondieron que su amor era bien aceptado
por el Señor. También les ofreció dinero,
pero ellas rehusaron tomarlo.

Luego, ellas le hicieron un relato de su encarcelamiento y sufrimientos,
y que no podían cambiar sus convicciones religiosas
aunque fueran reducidas a cenizas o picadas en pedacitos.
El fraile acercándose dijo que ellas no trabajaban, pero esto no era cierto,
porque ellas tenían trabajo propio y trabajaban como podían. También
le dijeron que el trabajo y negocio de ellas estaba en Inglaterra.
Él confesando que eso era cierto,
dijo que ellas habían sufrido suficiente y por mucho tiempo,
y que deberían obtener su libertad en un corto tiempo,
pero que necesitaban una orden del papa.
Mientras tanto, al capitán le afligía no poder obtener la libertad de ellas,
y marchándose, oró que Dios las consolara.
Ellas le rogaron al Señor que lo bendijera y lo preservara para vida eterna,
y que nunca dejara que él se fuera sin una bendición de Él por su amor,
pues él había arriesgado su propia vida, al esforzarse por obtener la libertad de ellas.

Después de que él se fue, se encontraron con un peor trato.
El inquisidor llegó y las miró con ira,
pues parece que la eliminación de sus vidas estaba de nuevo sobre la mesa,
y sus puertas fueron cerradas por muchas semanas.
Después de un tiempo, el inquisidor regresó a la torre donde ellas se sentaban,
y Sara lo llamó y le pidió que les abrieran las puertas
para bajar el patio a lavar sus ropas.
Él entonces ordenó que las puertas fueran abiertas una vez a la semana,
y no mucho después eran abiertas todos los días. Ya que se había
dicho que ellas no podían ser liberadas sin permiso del papa,
Sara le dijo: "`Si somos prisioneras del papa, apelamos al papa.
Envíanos, pues, a él.`" Pero los que tenían su domicilio en la Inquisición,
especialmente los frailes, eran enemigos mortales de ellas,
aunque las habrían alimentado a veces con lo mejor de sus provisiones,
y les habrían dado botellas enteras de vino, si ellas lo hubieran recibido.
Pero esto las molestaba tanto, que se negaban a comer y a beber con ellos,
al considerarlos sus feroces perseguidores.

Una vez llegaron dos o tres barcos ingleses al puerto, y el cónsul inglés al contarles,
dijo que había hecho todo lo que había podido por ellas,
pero que no las dejarían ir a menos que se convirtieran en católicas, y por tanto,
ellas todavía debían sufrir encarcelamiento.
Antes que Sara supiera que estos barcos habían llegado,
ella los había visto durante la noche en un sueño,
y había oído una voz diciendo que ellas no podían irse todavía.
Cuando los barcos se fueron,
mandaron a buscar a las mujeres y les preguntaron si querían convertirse en católicas,
y ellas respondieron:
"`Nosotras somos verdaderas cristianas y hemos recibido el Espíritu de Cristo.`"
Uno de los magistrados les mostró la cruz,
y ellas le dijeron que ellas tomaban la cruz de Cristo cada día, la cual era,
el poder de Dios para crucificar el pecado y la iniquidad.
Sabiendo que había un fraile, quien, según les había dicho el capitán,
se había tomado grandes molestias por ellas,
y no viéndolo ahí (pues el que las favorecía secretamente
estaba ausente) les dijeron a los que estaban presentes:
"`Uno de sus padres nos ha prometido nuestra libertad;`" pero esto no sirvió de nada.
Sin embargo, ellas aceptaban la amabilidad de él,
y después le dijeron que él nunca tendría motivo para arrepentirse.

Una vez un fraile fue adonde ellas y les dijo:
"`Es la voluntad de Dios que ustedes sean mantenidas aquí,
o de lo contrario no podríamos retenerlas.`"
A lo que Catherine respondió: "`El Señor permite que los hombres malvados hagan maldades,
pero Él no quiere que ellos las hagan.
Él permitió que Herodes decapitara a Juan el Bautista, pero Él no quería que lo hiciera;
Él permitió que Esteban fuera apedreado y que Judas traicionara a Cristo,
pero Él no quería que ellos lo hicieran; porque si fuera así,
Él no los habría condenado por eso.`"
El fraile les preguntó: "`¿Somos nosotros entonces, hombres perversos?`"
Ella respondió: "`Los hombres perversos son los que obran maldad.`"
"`Pero,`" dijo él, "`ustedes no tienen la verdadera fe.`"
Y ella respondió: "`Por la fe estamos firmes y por el poder de Dios somos sostenidas.
¿Piensas que es por nuestro propio poder y santidad
que somos guardadas de una vana manera de vivir,
y del pecado y la maldad?`"
Entonces al decir él que era por el orgullo de ellas, Catherine le dijo:
"`Nosotras nos podemos gloriar en el Señor, pues éramos hijas de ira,
igual que los demás,
pero el Señor nos vivificó cuando estábamos muertas mediante la palabra viva de Su gracia,
y nos ha lavado, limpiado y santificado en alma y espíritu--en parte,
según nuestras medidas, y proseguimos hacia lo que es perfecto.`"
Él dijo: "`Ustedes son buenas mujeres,
pero aun así no hay redención para ustedes a menos que sean católicas.`"
En una ocasión los frailes les dijeron:
"`Ustedes pueden convertirse en católicas y conservar su propia religión,
y no será sabido a menos que sean llevadas delante de un juez.`"
A lo que ellas respondieron: "`¿Qué, y profesar un Cristo del que nos avergonzamos?`"

Algunos de los que iban a verlas las compadecían por no convertirse en católicas,
pero otros les mostraban su odio gritando que ellas debían ser quemadas, y vociferando:
__"`Fuoco, fuoco.`"__
(Fuego, fuego) Mientras permanecían separadas una de la otra,
Catherine a menudo se preocupaba mucho por Sara y temía que la atraparan,
pues uno de los frailes solía acosarla con palabras aduladoras.
Pero ambas continuaron firmes,
y con frecuencia se sentían embargadas del gozo y consolación
que sentían del Señor. Catherine contó en una de sus cartas,
que una vez el espíritu de oración había estado sobre ella,
pero que había tenido miedo de hablarle al Señor por temor
a decir una palabra que no le agradara a Él. Y que entonces,
le había sido respondido de parte del Señor: "`No temas, hija de Sión,
pide lo que quieras y Yo te lo concederé; lo que tu corazón desee.`"
Pero Catherine no deseó nada del Señor sino lo que fuera para la gloria de Él,
ya fuera su libertad o cautiverio, vida o muerte;
y en esta rendición ella fue hallada acepta ante el Señor.

A veces ellas hablaban tan eficazmente a los que llegaban a verlas,
que no podían refutarlas, y eran obligados a confesar que Dios estaba con ellas.
Sin embargo, otros hacían un ruido horrible y gritaban:
"`Jesús María,`" y se alejaban corriendo como si hubieran sido golpeados por el temor.
La celda de Catherine estaba tan cerca de la calle
que podía ser escuchada por los que pasaban,
y en algunas ocasiones era movida a llamarlos al arrepentimiento
y a volverse a la luz con la que eran iluminados,
la cual los podía sacar de todos sus caminos y obras de maldad,
para servir al Dios vivo y verdadero en espíritu y en verdad.
Esto alcanzó a algunos de manera tal, que suspiraban y gemían y se quedaban a escucharla,
pero no podían hacerlo por mucho tiempo porque estaba estrictamente prohibido.
No obstante,
algunos de los que pasaban por ahí hacia sus '`casas de adoración`' eran tan perversos,
que lanzaban piedras a la ventana de Catherine y con frecuencia
hacían un ruido lastimero y aullaban como perros.
Así eran acosadas, tanto desde el exterior como desde el interior por los frailes,
quienes las amenazaban ferozmente por el atrevido
testimonio de ellas contra la idolatría. Una vez,
que ellos le mostraron a Sara un cuadro de la virgen
María y de su bebé pintado en una pared,
y le pidieron que lo mirara, Sara, para mostrar su celo contra la adoración a los ídolos,
zapateo con su pie y dijo: "`Malditas todas las imágenes,
todos los hacedores de imágenes y los que se postran para adorarlas.`"

Sucedió que unos barcos franceses y españoles llegaron a unirse
a los caballeros de Malta para pelear contra los turcos.
Sara, al oír esto dijo: "`¡Dios está enojado!
No salgan para matarse unos a otros.
Cristo no vino para destruir la vida, sino para salvarla.`"
Ella le dijo esto a muchos que estaban persuadidos de obtener la victoria,
pero sucedió lo contrario, porque su flota fue golpeada por los turcos,
y regresaron con grandes daños.

En una ocasión, un fraile fue a ver a Catherine y le preguntó, por qué ella no trabajaba.
Entonces ella le preguntó: "`¿Qué trabajo haces tú?`" Él respondió: "`Yo escribo.`"
Entonces Catherine respondió: "`Yo también escribiré, si tú me traes pluma,
papel y tinta.`"
Él, que no estaba dispuesto a que ella escribiera le dijo:
"`Pablo trabajó cuando estaba en Roma,
y tejiendo tú podrías ganar unos tres medios peniques al día.`" Ella le dijo:
"`Si nosotras pudiéramos tener ese privilegio entre ustedes,
el que tuvo Pablo en Roma bajo el César (que era un príncipe pagano),
trabajaríamos y no seríamos carga para nadie.
Pues él vivió por dos años en su propia casa alquilada,
predicando el evangelio y la doctrina del Señor Jesucristo.`"

Ella también le preguntó, si él conocía la guerra santa de Dios.
"`Y si la conoces,`" dijo ella,
"`entonces no ignoras que nosotras no podemos estar sin
labor día y noche;`" esto detuvo la boca del fraile.
Además, era bien sabido que ellas no pasaban el tiempo ociosamente,
pues tejían medias para los que eran serviciales con ellas.
También hacían vestidos para los prisioneros pobres y remendaban sus propias ropas;
pero no estaban dispuestas a trabajar para los frailes.
Estos hombres a veces iban a ver a Catherine, se arrodillaban,
y querían que ella repitiera delante de ellos lo que ellas hablaban,
pero ella se rehusaba a hacerlo, aunque esto los enfurecía más.

Estos y otros hechos similares la afligían tanto, que una vez,
angustiada de espíritu clamó a Dios diciendo:
"`¡Mejor me fuera morir que vivir así!`" Pues al ser casi continuamente
obligada a testificar contra la idolatría y la superstición,
ella habría estado dispuesta a rendir su vida por el testimonio contra ella,
si le hubiera sido requerido.
Y cuando en una ocasión los frailes le dijeron que Sara iba a ser llevada a Roma,
mientras que ella debía permanecer en Malta, se afligió tanto,
que con súplica le preguntó al Señor si Él no la consideraba digna de
ir a Roma también y ofrecer su vida ahí por el testimonio de Jesús,
porque si ella tenía la libertad de escoger,
prefería ir que regresar sin Sara a Inglaterra.

En otro momento, cuando les fue dicho que sus Biblias eran falsas,
Catherine le preguntó al fraile que lo había dicho: "`¿Por qué son falsas?`"
Él respondió, porque los libros de los Macabeos no estaban en ellas.
Ella respondió, que aunque algo hiciera falta, el resto aún podía seguir siendo bueno,
pero que si algo era añadido, entonces la Biblia estaba corrompida.
Esto golpeó algunos agregados que ella había visto en las Biblias ahí. Luego él le preguntó
si ella no creía que todos debían inclinarse ante el nombre de Jesús,
al responder ella que sí, él dijo:
"`Jesús,`" y le pidió que se arrodillara o se inclinara.
Entonces ella le dijo,
que todo su corazón y su cuerpo estaban inclinados ante el nombre de Jesús,
pero que ella no se inclinaría por la voluntad de él. "`El
que se aparta de la iniquidad (continuó ella),
se inclina delante del nombre de Jesús, pero el que vive en pecado y maldad,
no se postra delante del Hijo de Dios.`"
Entonces él dijo que él y sus compañeros estaban en el mismo poder,
y que eran guiados por el mismo Espíritu, tal como los apóstoles.
Esto hizo que ella le preguntara,
porqué entonces ellos abusaban de ese poder y usaban armas carnales.
Él respondió que ellos no lo hacían,
porque tanto su Inquisición como sus cadenas y grilletes eran espirituales.
Luego él le preguntó si ella no pensaba que todos
los que no eran de su persuasión estaban condenados.
Ella respondió: "`No, Cristo no nos ha enseñado así,
porque aquellos que hoy están en estado de condenación, si al Señor le place,
pueden ser llamados mañana a salir de ella.`"
Entonces él dijo: "`Nosotros pensamos que ustedes están condenadas,
y todos lo que no son de nuestra creencia.`"
A lo cual ella respondió: "`El juicio del hombre no nos hace daño.`"

A veces algunos llegaban a la prisión en sus días "`santos`"
y les preguntaban a las mujeres qué día era,
y ellas al no estar familiarizadas con esos santos respondían: "`No sabemos.`"
Cuando los otros les decían, que ese día era el día de tal o cual santo,
y que dicho santo las castigaría esa noche por no haber guardado su día, respondían:
"`Nosotras sabemos que los santos están en paz con nosotras,
y que por eso no les tememos.`"
En otra ocasión un fraile llegó y les dijo que faltaban diecisiete días para Navidad,
y que la virgen María había concebido ese día. Sobre lo cual Catherine hizo notar,
que eso en verdad era muy extraño,
que ella portara un niño sólo diecisiete días. Tales
y similares sucesos la afligían mucho,
cuando consideraba la gran oscuridad en la que estaban esas personas.
Y una vez, mientras clamaba al Señor en oración,
que parecía que todo el trabajo y la labor de ellas era infructuoso,
percibió esta respuesta: "`No te aflijas, aunque Israel no se reúna,
la Semilla de Malta se incrementará en multitud; eso que han sembrado no morirá,
sino que vivirá.`"

Después de que Catherine y Sara habían estado encarceladas en Malta cerca de tres años,
llegó un hombre llamado Daniel Baker,
quien hizo lo que pudo para obtener la libertad de ellas,
y también fue a ver al inquisidor, pero todo fue en vano.
Porque parece que el inquisidor exigía que algunos comerciantes ingleses en Leghorn,
o en Messina, se comprometieran a pagar cuatro mil dólares^
footnote:[Moneda que circulaba en varios países de Europa,
diferente al dólar actual de Estados Unidos.]
para que ellas fueran liberadas, y nunca regresaran a esos lugares.
Pero ellas no estaban dispuestas a entrar en esos términos,
ya que no sabían lo que el Señor de un momento a otro podría requerir de ellas.
Daniel, al ver que no podía obtener la libertad de ellas de esa manera,
se ofreció a ser encarcelado en lugar de ellas, y como no se aceptó fue aún más allá,
y expresó que estaba dispuesto a dar su vida por la libertad de Catherine y Sara,
si no había otro modo de que su libertad fuera comprada.
¡Gran amor, en verdad, del que son hallados muy pocos ejemplos!

Al oír ellas de esto, fueron tocadas con gran admiración. Mientras tanto,
Daniel Baker encontró la manera de que unas cartas les fueran entregadas,
y él mismo les escribió también,
tanto para consolarlas como para exhortarlas a la constancia.
Finalmente, también halló los medios para hablar con ellas; pues una vez,
mientras estaban en los portones de la prisión,
llegó ante ellas y las saludó con estas palabras:
"`Todo el cuerpo de los elegidos de Dios, queridas hermanas, reconoce sus testimonios.
Ustedes son un sabor dulce para el Señor y Su pueblo.`"
A lo que una de ellas respondió, que era una pena para ellas no poder ser más útiles.
Esto hizo que el corazón de él se derritiera con piedad y compasión,
considerando la maravillosa misericordia del Señor
al preservarlas sin desmayar en esa dura prueba.
Y ellos, viéndose unos a otros a la distancia a través de las rejas de hierro,
en ese momento fueron mutuamente refrescados.
Tiempo después ellas le escribieron y le manifestaron, con las más tiernas expresiones,
lo mucho que apreciaban su gran amor,
y también le enviaron cartas para sus amigos y familiares en Inglaterra.
Él no dejó de escribirles en respuesta durante su estancia,
que fue en la primera parte del año 1662; sin embargo,
se vio forzado a dejarlas en prisión ahí. Pero el momento de su rescate se acercaba,
el cual fue llevado a cabo por instancias de George Fox y Gilbert Latey,
al escribirle al señor Aubigny, como ya ha sido dicho.

Antes de que Daniel Baker llegara a Malta,
se les había dicho a ellas que si se convertían al catolicismo podrían vivir en Malta.
A lo que ellas respondieron, que ellas eran verdaderas Católicas.^
footnote:[La palabra Católico significa "`universal o general,`" y originalmente
fue usada para referirse a la iglesia universal o mundial de Cristo.
A lo largo de los siglos,
el término lentamente se convirtió en sinónimo de la iglesia de Roma (o papista).]
Uno de los magistrados les dijo, que si no se hacían católicas,
tendrían que sufrir un largo encarcelamiento por orden del papa, (sin embargo,
no era cierto que tal orden existiera).
También se les dijo, que si besaban la cruz serían liberadas,
y entonces podrían estar en la casa del cónsul inglés hasta
que se ofreciera una oportunidad de ser llevadas a Inglaterra.
Entre tanto,
ellas habían oído que el papa había dado la orden de que fueran llevadas
a Inglaterra sin causarles ningún daño. Pero sea como fuere,
ellas fueron guardadas en contentamiento,
y resueltamente dijeron que no besarían la cruz, ni comprarían su libertad a ese precio.

Parece que el cónsul pretendía obtener alguna ventaja
monetaria por la liberación de ellas,
porque les dijo que el inquisidor había dicho,
que si alguien ofrecía garantías de tres o cuatro
mil dólares a pagar si ellas volvían alguna vez,
serían puestas en libertad.
Esto también se lo dijo a Daniel Baker, y añadió,
que si nadie se comprometía como garante debían morir en prisión,
y que esa era la orden del papa.
Después de la partida de Daniel Baker,
se envió un mensaje a algunos comerciantes ingleses con respecto a tal compromiso,
pero ninguno pareció dispuesto a aceptarlo.
Y las prisioneras estaban tan lejos de desearlo, que hablaron contra esa idea.
Sin embargo, había muchos buscando obtener la libertad de ellas,
mostrándose a sí mismos dispuestos a comprometerse con lo que fuera razonable;
pero todos los esfuerzos fueron en vano.

Una vez ellas ayunaron tres días, y aunque era la estación fría,
se sentaron en el piso con muy poca ropa, sin medias ni zapatos,
y no tenían más que cenizas sobre sus cabezas.
Cuando los inquisidores vieron esto se maravillaron grandemente,
y Sara comenzó a hablar con gran celo en contra de la superstición
e idolatría. Y cuando el tiempo de su ayunó acabó,
Catherine compuso lo siguiente:

Himno a Dios

¡Toda alabanza a Aquel que no me ha dejado,

ni de Su mente me ha sacado,

ni Su misericordia de mí ha cerrado,

hasta donde he hallado!

¡Infinita gloria, loor y alabanzas,

sean dadas a Su nombre,

Quien ha dado a conocer en nuestras jornadas,

su fuerza y noble renombre!

¡Oh, nadie es al Cordero semejante,

del que resplandece brillante Su belleza!

¡Oh, que Su santo nombre se exalte,

Su majestad y fuerza!

¡Al único Dios mi alma alaba,

a la fuente pura y clara,

cuya corriente cristalina el exterior alcanza,

y lejos y cerca lava!

¡Los manantiales de eternidad,

muy puros y dulces son,

brotan sin cesar,

para a mi novio encontrar!

¡Mi dulce y querido Amado,

Su voz es para mí,

más que toda la gloria del mundo,

o que los tesoros que pueda descubrir!

¡Él es la gloria de mi vida,

mi gozo y mi placer.

Dentro del seno de Su amor,

me cercó de día y hasta el anochecer!

¡Él me preserva limpia y pura,

dentro de Su habitación,

donde yo con Él estoy segura,

y salva de toda equivocación!

¡Qué mi alma te alabe Señor!

¡Qué te alabe con gozo y paz!

¡Qué mi espíritu y mi mente día y noche,

te alaben sin cesar!

¡Oh, magnifiquen Su majestad,

Su fama y renombre,

Cuya morada es alta en Sión,

la gloria de Su corona!

¡Oh, alabanzas, alabanzas a nuestro Dios!

¡Canten alabanzas a nuestro Rey!

¡Oh, enseñen a la gente en el extranjero,

Sus alabanzas cantar!

¡Una canción brillante de gloria a Sión,

una que muy claro brille.

Oh, manifiéstenla ante la visión,

de las naciones lejos y cerca!

¡Qué Dios tenga Su debida gloria,

Su honor y Su fama

Qué todos Sus santos canten de nuevo,

las alabanzas a Su nombre!

Después de que Catherine cantó tan gozosamente,
se fue al pozo del patio y tomó mucha agua a la vista de los prisioneros,
y Sara también lo hizo; pues estaban muy sedientas.
Sara, además, se lavó la cabeza con agua fría,
y los prisioneros les gritaban en su lengua:
"`Ustedes se matarán y se irán al infierno.`"
Pero ellas ni le temían a eso, ni se enfermaron,
y se convirtieron en una maravilla para los demás.

Alrededor de medio año después de la partida de Daniel Baker,
entró en el corazón de Catherine, que si ella hablaba con el inquisidor,
él les concedería la libertad, y no había pasado mucho tiempo después de eso,
cuando él acudió a la sala de la corte de la Inquisición. Al enterarse de su llegada,
ellas solicitaron hablar con él y les fue concedido, y al ser admitidas en su presencia,
le dijeron que ellas no habían agraviado ni defraudado a nadie, y que sin embargo,
habían sufrido inocentemente casi cuatro años por causa de la consciencia, etc.
Después de esto,
el inquisidor fue muy cortés con ellas y les prometió la libertad en pocos días,
diciéndoles que enviaría a buscar al cónsul y lo
haría comprometerse a pagar 500 dólares por ellas,
si alguna vez regresaban.
Y que en el caso de que el cónsul se negara,
enviaría un recado al papa en Roma pidiéndole permiso para ponerlas en libertad,
sin ninguna obligación.

No muchos días después, el inquisidor llegó con su teniente, el canciller y otros,
y después de un discurso,
les preguntó si estaban dispuestas a regresar a sus esposos e hijos,
si esa fuera la voluntad de Dios.
A lo cual respondieron, que era la intención de ellas hacerlo en la voluntad de Dios.
En seguida fueron liberadas,
y el inquisidor se despidió muy cortésmente de ellas y les deseó un próspero regreso
a su país. De igual manera hicieron los magistrados y los oficiales inferiores,
sin exigir un penique por honorarios o asistencia.
Sin embargo, en su propia libertad, ellas le dieron algo al guardián y a algunos pobres.

Puestas así en libertad,
se arrodillaron y oraron a Dios que no les tomara
en cuenta lo que ellos les habían hecho,
porque ellos no las conocían. Y luego fueron entregadas en manos del cónsul,
quien les dijo que él se había comprometido por ellas para que fueran liberadas,
pero ellas nunca pudieron encontrar que eso fuera cierto.
Catherine y Sara estuvieron once semanas en la casa del cónsul,
antes de poder obtener un pasaje a Inglaterra.
Mientras tanto, Catherine,
estando bajo una gran preocupación debido a un juicio
que sentía que era inminente sobre la ciudad,
les escribió un documento a los gobernantes de Malta en el que decía,
que el 25 del mes llamado Agosto,
había venido sobre ella de parte del Señor escribirles en Su nombre lo siguiente:

"`Mi ira está encendida contra ustedes y Mi juicio está establecido entre ustedes,
debido a la dureza de sus corazones e incredulidad.
Yo, el Señor, que no deseo la muerte de ningún hombre,
sino que todos regresen a Mí y vivan,
he enviado a Mis siervas entre ustedes (contrario a su voluntad y sin
el conocimiento de ellas) para advertirles del mal que vendría sobre ustedes.
Porque todos los impíos serán llevados a juicio.
En verdad, Yo estableceré a Mi amado Hijo sobre Su trono,
y Él gobernará en Su regio poder y reinará en Su real majestad,
Cuyo derecho está sobre todo.
Él establecerá en todos los lugares Su propio gobierno espiritual,
un gobierno justo y una adoración pura en Espíritu y en Verdad.
Nada puede detener al Señor. Si ustedes no oyen a Mis siervas que hablan Mis palabras,
a quienes han probado por casi cuatro años,
cuyas vidas han sido inofensivas e inmaculadas,
y han estado entre ustedes en inocencia pura, entonces,
Yo traeré sobre ustedes ay sobre ay, y juicio sobre juicio,
hasta que los vivos no puedan sepultar a los muertos.
Mi boca ha hablado esto y Mi celo lo hará,
y la mano de cada hombre estará sobre sus lomos por causa del dolor,
porque el día de la recompensa ha llegado.
Pero si oyen a Mis siervas que hablan en Mi nombre,
y se vuelven en sus mentes a la luz en sus consciencias que convence de todo mal,
y rechaza todos los pensamientos, palabras y actos del mal, entonces,
Yo derramaré mi Espíritu sobre ustedes,
y pronto serán curados de sus enfermedades y sanados de su dolor.`"

Esto y más escribió, y se lo entregó al cónsul para que se lo diera al '`gran maestre`'^
footnote:[El _gran maestre_ es la máxima autoridad de una orden,
con un poder casi absoluto, tanto en lo militar, como en lo político o lo religioso.]
y al resto de los gobernadores, pero el cónsul al no estar complacido con esto,
la amenazó con encarcelarla de nuevo.
Qué sucedió con el documento, no lo sé,
pero el 8 de Octubre hubo grandes truenos y relámpagos que incendiaron
y volaron una de las casas de pólvora,
aproximadamente a una milla de la ciudad, y otra casa de pólvora fue derribada.
En la ciudad, cinco casas se vinieron abajo,
la mayoría de las ventanas de vidrio de los palacios y otras casas se quebraron,
las puertas se despegaron de sus bisagras,
las paredes se rompieron y la ciudad entera fue terriblemente sacudida,
tanto que al ser medianoche, un lamento atravesaba toda la ciudad y las campanas sonaban.
Al pie de la cama donde Catherine y Sara dormían,
había una ventana de vidrio que también se quebró,
pero ellas no recibieron ninguna herida,
aunque la casa se sacudió tanto que ellas estaban muy asustadas y temblando.
Sin embargo, tras estando entregadas al Señor para vivir o morir,
el temor pronto fue quitado de ellas y se convirtió en gozo en
el Señor. Cuando llegó la mañana el cónsul fue adonde ellas,
y estando quietas y en silencio, preguntó si habían muerto.
Mientras él aún hablaba, otros entraron contando lo que había sucedido en la ciudad,
y él les contó que incluso los barcos en el puerto habían sido dañados.
Entonces ellas dijeron: "`¡Un ay ha pasado, y he aquí viene otro rápidamente,
si ustedes no se arrepienten!`"

Algunos días después de esto, Sara ayunó,
sentándose en el piso con ceniza sobre su cabeza, y con su cuello y hombros descubiertos,
y le habló al cónsul para que le pidiera al '`gran maestre`' que proclamara un ayuno,
e hiciera que el pueblo se reuniera a esperar en el Señor, con sus mentes vueltas a Él,
para que apartara Sus juicios de ellos, porque la hora de Sus juicios había llegado,
en la que la ramera pintada debía ser desnudada y recibir la copa de temblor
de la mano del Señor. El cónsul llevó este mensaje a los magistrados,
y los frailes dijeron que las mujeres tenían buenas intenciones.
Un tiempo después llegó el inquisidor y hablando con ellas les dijo:
"`La intención de ustedes es buena, pero el diablo las ha engañado.`"
Ellas le preguntaron si el diablo podía dar poder sobre el pecado, a lo que él dijo,
que el diablo podía transformarse en una imagen de luz.
Ellas asintieron a esto, sin embargo dijeron,
que él no podía esconderse de los hijos de luz,
aunque los que estaban en oscuridad no pudieran discernirlo.
Él no pudo soportar oír esto y se fue,
y el cónsul, que estaba presente, se afanó contra ellas para encerrarlas de nuevo,
pero fue en vano.
Luego muchos murieron en el pueblo por una fiebre violenta,
pero no puedo decir si algún otro desastre siguió la predicción de ellas.^
footnote:[Es interesante señalar, que poco después de esta época,
Malta sufrió la peor epidemia de peste de la historia de la isla.
En diciembre de 1675 se produjo un brote de peste
bubónica que se prolongó hasta agosto de 1676,
y provocó aproximadamente 11.300 muertes;
alrededor de una sexta parte de la población de la isla.
La mayoría de las muertes se produjeron en las zonas urbanas, incluyendo la capital,
La Valeta, y las Tres Ciudades,
que tuvieron una tasa de mortalidad de alrededor del 41+++%+++. Bartholomeo dal Pozzo (1637-1722),
conocido historiador contemporáneo de la Orden de San Juan,
comenzó su descripción de este brote afirmando,
"`La venganza divina ordenó el castigo de la peste por nuestros pecados.`"]

Al fin, llegó una fragata del rey de Inglaterra llamada el Zafiro,
comandada por el capitán Samuel Titswel, quien acogió a Sara y a Catherine,
junto con algunos caballeros de Malta.
Entre ellos estaba el hermano del inquisidor,
quien a menudo le hablaba al capitán para que a las mujeres
no les faltara nada de lo que había en el barco,
y a ellas les dijo que si regresaban a Malta no serían tan perseguidas.
Al capitán le dijo: "`Si ellas van al cielo de una manera y nosotros de otra,
todos nos encontraremos al final.`"
Pero ellas le respondieron que Cristo Jesús, la luz del mundo,
era el único camino al Padre.

Un tiempo después de haber partido de Malta, llegaron a Leghorn,
donde los comerciantes les mostraron gran amabilidad,
y les enviaron vino y otras cosas para que se refrescaran,
y también les ofrecieron dinero, pero ellas no quisieron aceptarlo.
De ahí llegaron a Tánger,
lugar que le pertenecía al rey de Inglaterra por
su matrimonio con la hija del rey de Portugal.
Este lugar estaba entonces sitiado por los moros, sin embargo,
Catherine y Sara entraron al pueblo,
y muchos acudieron en masa a la casa donde ellas se alojaban,
porque exhortaban valientemente al pueblo a apartarse de la maldad.
También fueron a ver al gobernador,
quien fue cortés con ellas y tomó la amonestación amablemente,
y prometió seguir su consejo.
Él quiso darles dinero, pero ellas no lo tomaron, aunque sí aceptaron su amor,
porque él había ordenado que ninguno de la guarnición las maltratara,
ni de palabra ni de hecho, bajo pena de severo castigo.
Sin embargo,
parecía que los portugueses e irlandeses estaban
suficientemente dispuestos a hacerles daño.

Estando ellas inclinadas a salir y hablarles a los moros,
le pidieron al gobernador que las dejara ir,
pero él les dijo que ellas sólo podían esperar de esa gente salvaje,
una muerte cruel o prisiones para siempre.
Y aunque le manifestaron que ellas creían que el Señor las guardaría,
ya que estaban persuadidas de que Él les pedía ir a los moros,
el gobernador de manera amistosa les impidió ir.
Detenidas así, entendieron que el Señor había aceptado la buena voluntad de ellas,
y cuando volvieron a embarcarse (aunque en otro barco),
varios tomaron transporte con ellas por creer, que por causa de ellas,
tendrían una travesía segura.
El capitán y los demás que iban en el barco se comportaron muy cortésmente con ellas,
y aunque se toparon con tempestades, al final llegaron seguros a Inglaterra.

Catherine relató después, que mientras estaba en la Inquisición,
por muchos días seguidos había estado a la espera de ser quemadas en la hoguera.
Por ese tiempo vio en un sueño durante la noche,
una habitación grande y un gran fuego de leña en la chimenea,
y observó a alguien sentado en una silla junto al fuego en forma de siervo,
a quien ella tomó como el Hijo del Dios eterno.
También vio a un niño varón muy amistoso y hermoso,
sentado en un sillón directamente sobre el fuego
(que no parecía tener más de nueve meses de edad,
y no tenía más ropa que un lino pequeño y fino alrededor de la parte superior),
y que el fuego ardía alrededor; sin embargo, el niño jugaba y estaba feliz.
Entonces ella quiso cogerlo por temor a que se quemara,
pero el que estaba sentado en la silla le pidió que lo dejara en paz.
Luego, al volverse vio a un ángel,
y el que estaba sentado en la silla finalmente le pidió que cogiera al niño,
lo cual hizo,
y vio que no había sufrido ningún daño. Al despertar le contó el sueño a Sara,
y le pidió que no temiera, porque las huestes celestiales las seguían.

He recogido el relato de lo que les sucedió a estas
mujeres en Malta de varios documentos y cartas,
que no mucho después de su regreso a casa fueron publicados en forma impresa.
Y como en la publicación no se guardó el orden debido, y se mencionaron muchas cosas,
que para evitar la redundancia he dejado pasar,
puede que yo sin intención haya perdido en uno u otro caso,
el orden o la secuencia del tiempo,
pero aun así creo que los hechos no están distorsionados.
Ahora, para darle una idea al lector del ánimo de estas mujeres y de sus sufrimientos,
insertaré algunas de sus cartas.
Entre las que les escribieron a sus amigos en Inglaterra estaba la siguiente:

"`Queridos y amados amigos, padres, ancianos y pilares de la casa espiritual de Dios,
y hermanos y hermanas en el Señor Jesucristo,
en la medida del amor y vida de nuestro Dios,
los saludamos a todos y los abrazamos en lo que es eterno.
Nos regocijamos grandemente y glorificamos el nombre de nuestro Padre celestial,
por habernos considerado dignas de participar de
la muerte y sufrimientos de Su bendito Hijo con ustedes.

Aunque somos las más pequeñas del rebaño de Dios,
somos del verdadero rebaño del que Cristo Jesús es el pastor.
Él ha tenido tan tierno cuidado sobre nosotras,
como ha tenido sobre todos los corderos que ha llamado en el día de Su poder.
Él nos ha llevado a través y sobre grandes aflicciones,
como a muchos otros de nuestros hermanos y sufrientes por Su nombre; en burlas, mofas,
escarnios, críticas, azotes, contradicciones, peligros en la tierra, peligros en el mar,
pruebas ardientes, crueles amenazas, aflicciones de corazón, dolores de alma,
calores y fríos, ayunos y vigilias, temores internos y luchas externas,
terribles tentaciones y persecuciones,
pavorosos encarcelamientos y bofetadas de Satanás. Sin embargo,
en todas estas pruebas el Señor ha sido muy misericordioso con nosotras,
y no se ha apartado, ni ha permitido que Su fidelidad nos falle,
sino que nos ha sostenido y nos ha guardado de desmayar en medio de nuestro apuro.

Nosotras no teníamos a nadie más ante quien hacer nuestro clamor,
sino ante el Señor únicamente; ni podíamos esperar una gota de misericordia,
favor o refrigerio,
sino lo que Él destilaba de Su presencia viva y obra por Su propia fuerza.
Porque cerca de un año estuvimos sentadas, una en una habitación y la otra en otra,
como búhos en el desierto y personas abandonadas en lugares solitarios.
Pero entonces,
disfrutábamos la presencia del Señor y contemplábamos el resplandor de Su gloria,
y los veíamos a ustedes, amigos queridos,
en la luz de Jesús. Contemplábamos su orden y la
firmeza de su fe y amor para con todos los santos,
y éramos refrescadas en todos los de corazón fiel;
y sentíamos el flujo de amor y vida que
fluía de los corazones de los que estaban completamente unidos a la fuente,
y nos hicimos sensibles al beneficio de sus oraciones.

¡Oh, las tristezas, los lamentos, las lágrimas que hemos experimentado!
Pero "`los que sembraron con lágrimas,
con regocijo segarán.`" La verdadera tristeza engendra verdadero gozo,
y la verdadera cruz trae verdadera corona.
Pues cuando abundaban nuestras tristezas, el amor de Dios sobreabundaba.
Cuánto más profunda era la tristeza, más grande era el gozo; cuánto más grande la cruz,
más pesada la corona.

Queridos amigos y hermanos, no se maravillen de que Israel no se haya reunido;
nuestro juicio queda en el Señor y también nuestras obras.
No ha sido por falta de esfuerzo laborioso, ni de dolor,
ni de amor por las almas de ellos,
porque nos habríamos contentado con ser alimentadas con hierba del suelo,
si así hubiéramos tenido la libertad de compartir con ellos.
Porque de no ser por la gran oposición,
nos habrían seguido como pollitos tras la gallina; tanto grandes como pequeños. ¡Pero,
oh, los encrespados mares y las furiosas y espumosas olas;
los vientos tormentosos y las inundaciones;
las profundas aguas y las altas montañas y colinas; las duras piedras,
los caminos ásperos y las sendas tortuosas; los altos cedros, los fuertes robles,
las árboles sin fruto y corruptos que ponen obstáculos en el suelo,
y estorban para que la Semilla justa no sea sembrada,
ni las plantas nobles sean plantadas! ¡Oh,
ellos les cierran el reino a los sencillos de corazón
y esconden de los inocentes la llave del conocimiento;
no entran en el reino, ni se lo permiten a los que desean entrar!

En su lugar, incitan a los magistrados a desarrollar armas carnales,
con la intención de evitar que el Señor reciba Su herencia, y despojar a Su Hijo,
el heredero de todo, para que no tenga morada entre ellos,
ni una habitación cerca de ellos.
Pero Su luz pondrá al descubierto sus tinieblas,
y Su resplandor quemará todas sus abominaciones, y desfigurará su belleza,
manchará su gloria, su pompa y su orgullo,
para que eso perezca como los higos fuera de tiempo, caiga como la flor del campo,
y se marchite como la hierba sobre el terrado.
¡Oh, el vientre del infierno, las fauces de Satanás,
todo el misterio de la iniquidad está en apogeo,
y todas las formas de abominaciones que hacen desolación,
están donde no deben estar y son amparadas por una ley, contra la que nadie debe hablar,
ni caminar en contra, bajo pena de muerte!

¡Pero alabanzas a nuestro Dios, que nos llevó a declarar contra ello día a día! ¡Oh!
Los guías ciegos, los espíritus de seducción que hacen que la gente se equivoque,
que obligan a las personas a adorar a la bestia y su imagen,
a tener su marca en sus frentes y en sus manos,
a inclinarse ante cuadros y paredes pintadas,
a adorar las cosas de sus propias manos y caer ante lo que sus propios dedos han moldeado.
Ellos no les permiten mirar hacia Sión, bajo pena de muerte, ni caminar hacia Jerusalén,
bajo pena de ser quemados en la hoguera,
sino permanecer en Babel y creer lo que sea que digan o declaren ser la verdad.

¡Oh!
Los caminos, las adoraciones, las modas, formas, costumbres, tradiciones,
observaciones e imaginaciones que han atraído en sus oscuras adivinaciones,
para mantener a la pobre gente en ceguera e ignorancia,
para que perezcan por falta de conocimiento,
y sean corrompidos porque el camino de la Verdad no es dado a conocer entre ellos.
Todos ellos están en las muchas formas, y fuera del único camino verdadero y vivo.
De hecho, sus caminos son tantos y tan monstruosos, que son indescriptibles.
Sin embargo,
el Señor nuestro Dios ha encendido un fuego en medio
de ellos que consumirá todas las formas,
modas, costumbres y tradiciones de los hombres, y quemará los cardos, los espinos,
la cizaña, el rastrojo, los árboles infructuosos y los corruptos.
Marchitará todos los frutos, las obras y labores de los hombres malvados e impíos,
con la plaga de Su iracunda indignación,
y esparcirá a todos Sus enemigos con los torbellinos de Su disgusto.`"

Esta carta fue firmada por ambas, aunque es posible que Catherine fuera la escritora.
Ella también le escribió una carta de exhortación al inquisidor Católico en Malta,
y otra al fraile Malaquías. Entre las cartas que ella les escribió a su esposo e hijos,
cuento la siguiente como realmente digna de ser entregada a la posteridad:

Para las manos de John Evans, mi querido y precioso esposo, y a mis tiernos hijos,
quienes son más queridos y preciosos para mí que la niña de mis ojos.

Queridísimo y fiel esposo, amigo, y hermano, engendrado por mi Padre eterno,
de la Semilla inmortal del pacto de luz,
vida y bendición. Tengo unidad y comunión contigo día y noche,
para mi gran refrigerio y continuo consuelo.
¡Alabanzas, alabanzas sean dadas a nuestro Dios para siempre,
quien nos ha unido en lo que ni el mar ni la tierra pueden separar o dividir!

Mi querido corazón,
mi alma te saluda sinceramente a ti y a mis queridos y preciosos hijos,
quienes son queridos y preciosos en la luz del Señor,
para tu gozo infinito y mi eterno consuelo.
¡Gloria a nuestro Señor Dios eternamente, quien los ha llamado con llamamiento santo,
y ha hecho que Su belleza resplandezca sobre ustedes en el día de Su poder,
en el que está preparando Su tesoro y uniendo a Sus
fieles en el vínculo del amor y salvación eternos,
entre quienes Él los ha contado por Su gracia gratuita.
En esta, les suplico, queridos corazones, en el temor del Señor,
que permanezcan en sus medidas según la manifestación
de la revelación del Hijo de Dios en ustedes.
Mantengan diligente vigilancia sobre cada pensamiento, palabra y acto,
y dejen que sus mentes permanezcan continuamente en la luz,
donde descubrirán las trampas y cebos de Satanás, y serán preservados de sus trampas,
redes y pozos, para que no sean esclavizados por él a su antojo.

¡Oh, mi querido esposo e hijos,
cuán a menudo he derramado mi alma ante el Padre eterno por ustedes,
con ríos de lágrimas noche y día,
para que sean guardados puros y limpios ante los ojos de nuestro Dios,
incrementando sus talentos como vírgenes prudentes, teniendo aceite en sus vasijas,
con sus lámparas ardiendo, vestidos con la larga y blanca túnica de justicia,
listos para entrar a la recámara, cenar con el Cordero,
y ser alimentados en el banquete de manjares suculentos,
donde sus almas pueden ser nutridas, refrescadas, consoladas y satisfechas,
y nunca tener hambre de nuevo!

Mis queridos corazones, ustedes no carecen de enseñanza;
ustedes están en la tierra de bendición,
en la que fluye leche y miel entre los mayordomos fieles,
cuyas bocas están abiertas de par en par a la justicia,
para declarar los eternos misterios del reino perpetuo,
de las interminables alegrías y de la gloria eterna,
donde todo los dispuestos y obedientes entrarán y serán bendecidos para siempre.

Mis queridos corazones, las promesas del Señor son grandes,
y '`todas son sí y Amén`' para los que temen Su nombre.
Él consolará a los dolientes en Sión,
y hará que los abatidos se regocijen en Jerusalén a causa de las buenas nuevas.
Los que carguen la cruz con paciencia, llevarán la corona con gozo,
pues es a través de la longanimidad y paciente espera,
que se obtiene la corona de vida e inmortalidad.
El Señor ha ejercitado mi paciencia y me ha tratado hasta el extremo,
para Su alabanza y mi consuelo eterno;
Quien no ha dejado de proporcionarnos todo en Su propio y debido tiempo.
En realidad, nosotras somos testigos de que Él puede aderezar una mesa en el desierto,
tanto espiritual como temporal.
¡Oh, el infinito amor de nuestro Dios, quien es perpetua fuente de todo refrigerio vivo,
y cuyos arroyos cristalinos nunca dejan de correr hacia toda alma
sedienta que respira en pos de los manantiales de vida y salvación!

En nuestra más profunda aflicción,
cuando yo esperaba que cada respiración fuera la última, no podía, sin embargo,
desear no haber atravesado el mar,
porque sabía que había sido la voluntad de mi Padre eterno para probarme,
junto con mi querida y fiel amiga.
En todas las aflicciones y miserias, el Señor recordó la misericordia,
y no nos dejó ni nos abandonó, ni permitió que Su fidelidad nos fallara,
sino que hizo que las dulces gotas de Su misericordia destilaran sobre nosotras,
y que el resplandor de Su glorioso semblante brillara en nuestros corazones,
y nunca dejó de concedernos revelaciones y visiones.

¡Oh,
¿cómo puedo explicar la plenitud del amor de Dios hacia
nuestras almas?! ¡Ninguna lengua puede expresarlo,
ningún corazón puede concebirlo, ninguna mente puede comprenderlo! ¡Oh, el embeleso,
el arrebato, el glorioso y resplandeciente semblante de nuestro Señor Dios,
quien es nuestra plenitud en el vacío, nuestra fuerza en la debilidad,
nuestra salud en la enfermedad, nuestra vida en la muerte, nuestro gozo en la tristeza,
nuestra paz en la inquietud, nuestra alabanza en la pesadez,
nuestro poder en todas las necesidades! ¡Sólo Él es un Dios pleno para nosotras,
y para todos los que confían en Él! Él nos ha vaciado y purgado de nosotras mismas,
y nos ha edificado por completo sobre un fundamento seguro, la roca de los siglos,
Jesucristo, la Luz del mundo, en Él que ni los encrespados mares,
ni las embravecidas y espumosas olas, ni los vientos tormentosos, pueden movernos,
aunque golpeen con vehemencia.

¡Gloria, honor y alabanza sean dadas a nuestro Dios por siempre,
quien a partir de Sus tesoros eternos nos llena de Sus riquezas eternas
día a día! Él nutre nuestras almas con lo más selecto de Sus misericordias,
alimenta nuestros cuerpos con Su buena creación,
y alivia todas nuestras necesidades plenamente.
¡Alabanzas, alabanzas sean dadas sólo a Él, quien es nuestra porción eterna,
nuestra confianza y nuestro regocijo,
a quien servimos aceptablemente con reverencia y piadoso temor;
porque nuestro Dios es fuego consumidor!

Oh, mi querido esposo y mis preciosos hijos,
puede que sientan los flujos de amor y vida que fluyen
como un río hacia cada uno de ustedes,
desde un corazón que está completamente unido a la fuente.
Mis oraciones son por ustedes día y noche sin cesar,
suplicándole al Señor Dios de poder que derrame Sus tiernas misericordias sobre ustedes,
los guarde en Su temor puro, incremente su fe, los confirme en toda justicia,
y los fortalezca al creer en el nombre del Señor Dios Todopoderoso,
para que sean establecidos como el Monte de Sión, que jamás podrá ser conmovido.
Mantengan sus almas sin mancha del mundo,
y ámense fervientemente unos a otros con corazón puro.
Sírvanse unos a otros en amor, edifíquense unos a otros en lo Eterno,
sobrelleven los unos las cargas de los otros por el bien de la Semilla,
y cumplan así la ley de Dios.
Esta es la palabra del Señor para ustedes, mis amados.

Amados corazones, los encomiendo a las manos del Todopoderoso, quien habita en lo alto,
y a la Palabra de Su gracia en ustedes,
quien es capaz de edificarlos para vida eterna y perpetua salvación. Por mí,
quien soy tu amada y preciosa esposa y cónyuge, en el matrimonio del Cordero,
en el lecho sin mancilla,

C+++.+++ E.

Mi amada compañera de yugo en la obra de nuestro Dios, cariñosamente te saluda.
Saluda con cariño a nuestros preciosos amigos en todo lugar.
Creo que volveremos a ver sus rostros con alegría.

Escrito en la Inquisición en Malta, en el mes Once, de 1661.

La siguiente carta fue escrita por Sara a su esposo, Henry Cheevers y a sus hijos.

Mi querido esposo, mi amor y mi vida están rendidos al servicio del Dios vivo,
y a la obediencia de Su llamado puro en la medida de la manifestación de Su amor, luz,
vida y Espíritu de Cristo Jesús, Su unigénito Hijo,
a quien Él ha hecho manifiesto en mí y en miles más mediante el resplandor de Su aparición,
para ponerles fin al pecado y a Satanás,
y sacar a la luz la inmortalidad a través de la predicación del evangelio eterno,
por medio del Espíritu de profecía,
que es derramado sobre los hijos e hijas del Dios vivo, según Su propósito;
para el cual Él me ha escogido, a mí que soy la más pequeña de todos.
Pero Dios, que es rico en misericordia,
por amor a Su propio nombre ha pasado por alto mis ofensas,
y me ha considerado digna de llevar testimonio de Su santo nombre,
ante los poderosos hombres de la tierra.
¡Oh, el amor del Señor a mi alma!
Mi lengua no puede expresar, ni ha entrado en el corazón del hombre concebir,
las cosas que Dios ha preparado para los que le temen.

Por tanto, mi alma respira anhelante a mi Dios por ti y por mis hijos de noche y de día,
para que sus almas sean unidas a la luz del Señor Jesús,
sean trasladadas del reino de Satanás al reino de Dios,
donde podemos disfrutarnos unos a otros en la vida eterna,
y donde ni el mar ni la tierra pueden separarnos.
En esta luz y vida los saludo, mi querido esposo y amados hijos,
deseando que abracen el amor de Dios,
al hacer que Su verdad se manifieste muy claramente entre ustedes.
De la que yo soy testigo, es decir,
de la fuente eterna que ha sido abierta por los mensajeros
de Cristo que les predican la palabra de Dios,
a tiempo y fuera de tiempo, indicándoles donde pueden encontrar a su Salvador,
para purgarlos y limpiarlos de sus pecados, y reconciliarlos con Su Padre,
y tener unidad con Él y con todos los santos en la luz,
y ser conciudadanos en el reino de gloria,
reposo y paz que Cristo ha comprado para los que lo aman y le obedecen.
¿Qué provecho tiene ganar el mundo entero, y perder sus almas?
Busquen primero el reino de Dios y Su justicia,
y todas las otras cosas les serán añadidas.
Porque la piedad es una gran ganancia,
pues tiene promesa de esta vida presente y de la venidera; la cual se cumple en mí,
que he gustado el amor infinito y las misericordia del Señor para con mi alma.

Y desde el movimiento del mismo amor y vida oro por ti,
mi querido esposo y mis queridos hijos.
Mi querido amor los saluda a todos; mis oraciones a Dios son por todos ustedes,
para que sus mentes sean unidas a la luz con la que son iluminados,
y yo pueda disfrutarlos en lo que es eterno, y tener comunión con ustedes en el Espíritu.
"`El que se une al Señor, un espíritu es con él,`" un corazón, una mente, un alma,
para servirle al Señor en un mismo consentimiento.
No puedo expresar por medio de la pluma o del papel el gran amor de Dios,
al cumplir Sus misericordiosas promesas para conmigo en el desierto,
tras haber sido puesta en prisión por la verdad de
Dios para permanecer allí todos los días de mi vida;
y ser examinada, probada, interrogada bajo pena de muerte,
entre los enemigos de Dios y Su verdad; y estar mi vida en peligro,
hasta que el Señor los sojuzgó y sometió mediante Su poderosa fuerza,
e hizo que nos alimentaran y nos quisieran dar dinero y ropa; y sin embargo,
el Señor engalanó ricamente nuestra mesa en el desierto.
Se acerca el día del Señor en el que Él descubrirá toda obra de las tinieblas,
por muy secreta que sea;
porque la luz de Jesucristo la hará manifiesta en cada consciencia.
En efecto, el Señor arrancará todas las cubiertas que no sean de Su propio Espíritu.

El Dios de paz sea con todos ustedes.
Amén.

Escrito en la prisión de la Inquisición por Sara Cheevers.

Tanto ella como Catherine escribieron varias otras cartas a sus esposos y familiares,
pero como gran parte de mi relato fue extraído de ellas, las paso por alto.
Sin embargo, por medio de estas que inserté,
uno puede ver que ellas no eran mujeres de tonto, sino inteligentes y alegres.

En una carta de Sara a sus amigos en Irlanda, encontré estas palabras:

Mi vida está rendida al servicio del Señor. Ataduras, cadenas, cerrojos, hierros,
puertas dobles y la muerte misma,
es demasiado poco por el testimonio de Jesús y por la Palabra de Dios.
Por tanto, es un sacrificio razonable con tal que la Semilla sea reunida.
Los lazos y las aflicciones suceden en el evangelio de Cristo.
Los que quieran vivir piadosamente en Cristo Jesús, deben sufrir persecución.

Catherine escribe en una carta enviada a Daniel Baker,

El tiempo es demasiado poco para que yo pueda revelar
la vigésima parte de los terribles pruebas.
Sin embargo, cada vez que fuimos llevadas a alguna prueba,
el Señor quitó todo temor de nosotras, multiplicó nuestras fuerzas,
y nos dio poder y osadía para defender la Verdad del Señor Jesús,
y sabiduría de palabras para tapar la boca de los detractores.
Pero entonces ellos decían, que nosotras no teníamos la verdadera fe,
pero que teníamos todas las virtudes.
Estimado hermano, ora por nosotras, para que no caigamos ni fallemos,
para que nuestros enemigos no tengan ninguna ventaja de gozarse y decir,
que nosotras servimos a un Dios que no puede servirnos,
y que invocamos a un Dios que no puede librarnos; como si nosotras fuéramos como ellos,
para invocar piedras, cuadros, paredes pintadas y cosas muertas, que no pueden oír,
ver ni hablar.
Te suplicamos que les cuentes a todos nuestros queridos amigos, padres y ancianos,
los pilares de nuestro edificio espiritual,
junto con el resto de nuestros hermanos Cristianos,
que deseamos sus oraciones porque tenemos necesidad de ellas.

Ellas concluyeron esta carta con el siguiente poema:

¡Cuán fuerte y poderoso es nuestro Rey,

para todos los que en Él creen!

Él los guarda de los que los quieren lazar,

y a la fuerza los quieren desgarrar.

En nosotros los que sufrimos por la Semilla,

nuestros corazones están heridos y sangran,

al ver la opresión y la crueldad,

de los hombre que niegan Tu Verdad.

En fuertes prisiones y profundas mazmorras

sólo a Dios clamamos y lloramos.

Nuestras penas nadie las puede aprender ni leer,

sino los que nuestro camino han de recorrer.

Pero Aquel cuya belleza brillante resplandece

El que vuelve las tinieblas en luz,

hace que los cedros se inclinen y los robles se doblen,

ante el que es enviado para el mismo fin.

Él es una fuente pura y clara,

Sus cristalinos arroyos corren lejos y cerca,

para limpiar a todo el que a Él se acerca,

Para ser sanado de su pecado.

Todos aquellos que pacientemente permanecen,

y nunca se desvían ni se descarrían,

el Señor los librará de toda

opresión, cautiverio y esclavitud.

Ellas compusieron varios otros, que cayeron en las manos de sus enemigos,
y le fueron dadas copias de estos al inquisidor.
Y ahora las dejo.
