== Capítulo 12

Antes de regresar a los asuntos en Inglaterra,
relataré un notable asunto sobre Daniel Baker,
quien habiendo llegado a Esmirna con la intención de viajar desde allí a Constantinopla,
fue detenido por el cónsul inglés y enviado a la Isla de Zante,
donde había un barco con destino a Venecia,
en el que se embarcó. Tras llegar a la ciudad, se quedó una semana allí,
y luego se fue a Leghorn con la intención de embarcarse hacia Inglaterra.
Pero durante su estancia en ese lugar, sintió persuasiones internas de dirigirse a Malta,
para ver si podía serles útil a Catherine y Sara que eran prisioneras ahí,
habiéndose sentido varias veces impulsado a ello.
Y aunque la dificultad del asunto lo había retenido,
ya no podría encontrar paz en su mente antes de haberse rendido a dicho servicio.
Por tanto, se embarcó en una nave francesa hacia Sicilia,
y al llegar a Siracusa se quedó ahí cinco días, y luego zarpó hacia Malta.
Una vez que llegó, consiguió que le permitieran hablar con el inquisidor del papa,
a quien le habló en lengua italiana de esta manera:
"`He venido a exigir la justa liberación de mis inocentes amigas,
las mujeres inglesas presas en la Inquisición.`" El inquisidor
le preguntó si tenía alguna relación con ellas de esposo o pariente,
y si había salido de Inglaterra a propósito con ese mensaje.
Daniel respondió que él había llegado de Leghorn con ese propósito.
Pero el inquisidor le dijo que ellas debían permanecer en prisión hasta que murieran,
a menos que algunos comerciantes ingleses (u otros que fueran capaces) se comprometieran,
por el valor de tres o cuatro mil dólares, a que ellas nunca volverían a esas partes.
Al serle denegada su petición, fue a ver al cónsul inglés y habló con él y varios otros.
Pero todos sus esfuerzos fueron en vano,
y él mismo fue amenazado con la inquisición. Además,
el representante del papa quiso obligarlo a no hablarle
ni bien ni mal a nadie mientras estuviera en la isla,
salvo a él y al cónsul inglés.

Después de permanecer ahí tres semanas,
regresó a Italia y de ahí se embarcó hacia Inglaterra.
Pero al llegar al Estrecho de Gibraltar,
vio que el peñón que había ahí era el mismo lugar
que había visto el año anterior en un sueño,
estando preso en la cárcel de Worcester en Inglaterra.
Ahí el barco en el que estaba, junto con otras naves,
estuvo parado cerca de un mes debido al viento contrario, de modo que no podía zarpar.
Entre tanto, estando bajo una carga, percibió que había un servicio para él en tierra.
Pero al considerar que esto era peligroso, deseó ser eximido de este;
pero no sintió paz hasta que se rindió completamente,
sin importar que le sobrevinieran ataduras o la muerte.
Mientras la flota estaba ahí con el viento en contra, varios barcos intentaron pasar,
pero no pudieron; y una tentación similar a la de Jonás lo atacó, es decir,
huir del lugar y así escapar de la carga del Señor bajo la que sufría dolores de parto.
Pero encontró (como lo señaló después en un relato
impreso) que la obediencia era su deber,
aunque se le hubiera requerido que fuera una señal
contra la idolatría de la iglesia de Roma.
Entonces le dijo algo del asunto al capitán del barco en el que era pasajero,
y le dijo que creía que después de que él realizara el servicio,
Dios le daría a la flota la oportunidad de seguir.
Fue difícil persuadir al capitán de llevarlo a tierra,
pero al final lo permitió el día que ellos solían llamar Jueves Santo.

Ya en tierra,
se dirigió a la ciudad y entró en la '`casa de la misa,`'
donde halló al sacerdote arrodillado frente al altar mayor,
con su sobrepelliz blanco, adorando la hostia.
Después de ver esta idolatría por un tiempo,
sintió que se encendía la indignación de Dios en su corazón contra ella,
y dándole la espalda al sacerdote y a su dios muerto,
puso el rostro hacia la gente y vio que la multitud también
estaba sobre sus rodillas '`adorando lo que no conocían.`'^
footnote:[Juan 4:2]
En esta postura, extendió sus brazos, se quitó la prenda superior,
la desgarró de arriba abajo en varios pedazos,
y la arrojó de él con indignación. Luego se quitó el sombrero de su cabeza,
por ser la cubierta superior del hombre, y tirándolo al suelo lo pisoteó con sus pies.
Entonces, mostrándose vestido de cilicio,
con fuerte voz llamó tres veces al arrepentimiento,
y dijo que la vida de Cristo y Sus santos no se hallaba en la hostia,
sino que había resucitado de entre los muertos.
Y se fue sin ser molestado,
anunciando el mismo mensaje de arrepentimiento por las calles,
hasta que llegó a la orilla del mar,
donde se arrodilló para orar y darle gracias al Señor por Su maravillosa preservación,
al no permitir que ningún hombre lo tocara o le hiciera algún daño. Estando en la costa,
también entregó un documento escrito en el idioma español,
para el gobernador y los habitantes de Gibraltar,
junto con algunos libros en latín. El dirigido al gobernador era como sigue:

[.embedded-content-document.paper]
--

¡Mirad, mirad, ha llegado el gran día de Dios y de Su ira, y de la ira de Su cordero!
La hora de Su juicio ha llegado.
Por eso, ¡oh, habitantes de la tierra, arrepiéntanse, arrepiéntanse, arrepiéntanse!
Temed a Dios y dadle gloria,
y adorad a aquel que hizo el cielo y la tierra y las fuentes de las aguas.^
footnote:[Apocalipsis 14:7]
¡Ay, ay, ay, de los que moran en la tierra!^
footnote:[Apocalipsis 8:13]
Juan oyó otra voz del cielo, que decía: Salid de ella, pueblo mío,
para que no seáis partícipes de sus pecados, ni recibáis parte de sus plagas.^
footnote:[Apocalipsis 18:4]
Estas son las palabras del poder de Cristo, que es contrario a la falsa iglesia.
¡Mirad, mirad, vienen plagas, plagas, plagas sobre la iglesia de Roma,
y sobre sus cabezas en todas partes del mundo!

--

Al día siguiente del que Daniel había vuelto a bordo del barco,
el Señor les dio un viento de popa, y toda la flota zarpó;
y después de un tiempo llegaron a salvo a Inglaterra.
Pero después de llegar a Londres, no había pasado mucho tiempo antes de que él,
que había viajado sin daño en el extranjero,
fuera hecho prisionero por sus propios compatriotas; como se relatará más adelante.
Y estando encerrado en prisión, escribió una narración de sus viajes,
de la que he sacado mi relato.

Por este tiempo John Stubbs regresó a Inglaterra,
después de haber estado en los dominios del gran Turco.
Pero no encuentro que se haya topado con algún suceso notable,
excepto que había distribuido algunos libros.
Cuando él y Alexander Parker llegaron a Londres encontraron a G. Fox ahí,
con quien viajaron a Bristol.
Por el camino tuvieron varias reuniones, y al llegar a dicha ciudad,
entendieron que era probable que los oficiales llegaran a perturbar las reuniones.
El Primer-día fueron a una reunión, y A. Parker se levantó primero para predicar,
pero mientras hablaba, llegaron los oficiales y se lo llevaron.
Entonces, G. Fox se levantó y predicó sin ser molestado,
de modo que la reunión terminó pacíficamente.
Luego, quedándose una semana en el pueblo, visitó a sus amigos y fue visitado por ellos.

El siguiente Primer-día,
algunos de sus amigos fueron a verlo y trataron de
persuadirlo de que no fuera a la reunión ese día:
"`Porque,`" dijeron ellos,
"`los magistrado han amenazado con llevarte, y para ese fin,
han traído una compañía entrenada.`"
G+++.+++ Fox les pidió que siguieran su camino a la reunión, sin decirles lo que pensaba hacer.
Sin embargo, no mucho después de esto él también fue;
pero al encontrarse con algunos de sus amigos de camino,
ellos hicieron lo que pudieron para detenerlo diciendo:
"`¡Qué! ¿Te vas a meter en la boca de la bestia?`"
Y otro dijo:
"`¿Te vas a meter en la boca del dragón?`" Pero G. Fox no permitió que se lo impidieran,
y continuó. Al llegar percibió la preocupación y temor de sus amigos por él,
pero su predicación fue tan poderosa, que todo el temor desapareció de ellos;
y después de concluir su sermón con una oración,
se levantó de nuevo y le dijo al auditorio:
"`Ahora pueden ver que hay un Dios en Israel que libra.`"
Porque los oficiales y soldados habían ido e interrumpido otra reunión,
lo cual les tomó todo su tiempo, y estaban furiosos por haber perdido a G. Fox;
porque se había resuelto perseguir a los Cuáqueros, y de ser posible, erradicarlos.

Después de haber permanecido unos días en Bristol,
G+++.+++ Fox regresó a Londres a través de Wiltshire y Berkshire; sin embargo,
no se quedó mucho tiempo, sino que viajó a Leicestershire, y pasando por Barnet Hills,
encontró allí a un capitán apellidado Brown, un Bautista,
cuya esposa pertenecía a la sociedad de los llamados Cuáqueros.
Este capitán, por temor a que su esposa asistiera a las reuniones y fuera encarcelada,
había dejado su casa en Barrow y se había instalado en Barnet Hills,
creyéndose más a salvo ahí. G. Fox fue a ver a la esposa, y después de entrar en la casa,
le preguntó a él cómo estaba.
"`¿Cómo estoy?`"
dijo él, "`¡las plagas y la venganza de Dios están sobre mí, pues soy un fugitivo,
un Caín! Es en vano que Dios me busque a mí y a los que son como yo,
para que seamos Sus testigos; porque si todos los hombres no fueran más fieles que yo,
entonces a Dios no le quedarían testigos en la tierra.`"
En esta condición vivía Brown, a pan y agua, y pensaba que era demasiado bueno para él;
pero al final, regresó con su esposa a su propia casa en Barrow,
donde llegó a convencerse de la Verdad profesada por los llamados Cuáqueros,
y murió en ella.
Un poco antes de su muerte dijo,
que aunque no había dado testimonio de la Verdad durante su vida,
daría testimonio en su muerte; y quiso que lo sepultaran en su huerto de forma sencilla.

Ahora regreso a G. Fox, quien habiendo entrado en Leiscertershire, fue a Swanington,
a la casa de una mujer viuda.
Allí uno llamado señor Beaumont, y una compañía de soldados,
fueron a buscarlo por la noche y lo sacaron de la sala donde estaba,
y lo llevaron ante dicho señor, quien le preguntó el nombre.
A esto respondió: "`Mi nombre es George Fox, y soy bien conocido por ese nombre.`"
"`Sí,`" dijo Beaumont, "`eres conocido en todo el mundo.`"
Luego, metió sus manos en los bolsillos de George para registrarlos,
y sacó su estuche de peine,
y después le ordenó a uno de los oficiales que buscara cartas.
Esto hizo que G. Fox dijera que él no era un cartero,
y le preguntó por qué venía entre un pueblo pacífico con espadas y pistolas,
pero sin un alguacil, dado que eso era contrario a la proclamación del rey.
Tampoco se podía decir que hubiera una reunión,
porque G. Fox únicamente había estado hablando en la sala con la mujer viuda y su hija.
Beaumont entonces, mandó a llamar a los alguaciles y les encargó,
que vigilaran a G. Fox y a otros que estaban con él esa noche.
Por lo tanto, los alguaciles los vigilaron,
y a la mañana siguiente los llevaron a la casa de Beaumont,
quien luego les dijo que ellos se habían reunido en contra de la ley;
porque no mucho antes de ese momento, el Parlamento, por instigación del clero,
había promulgado una ley contra los conventículos,^
footnote:[Es decir, una reunión religiosa ilegal.]
en la que se establecía que si alguien era condenado por haber estado en un conventículo,
se le impondría una multa no mayor de cinco libras,
o un encarcelamiento de no más de tres meses.
Al decirle G. Fox al señor Beaumont, que él no los había encontrado en una reunión,
y que por lo tanto, no había transgresión de dicha ley,
Beaumont le preguntó si prestaría los juramentos
de lealtad y supremacía. A esto G. Fox respondió:
"`Yo nunca he prestado juramento en toda mi vida;`"
y luego le pidió que le mostrara el juramento,
para ver si no estaba hecho para descubrir a los Católicos recusantes.^
footnote:[Es decir, los que no cumplían con la ley de adoptar la religión estatal.]
Pero Beaumont, al no estar dispuesto,
hizo que se emitiera una orden judicial en la que mencionaba que Fox y sus amigos tenían
la intención de celebrar una reunión--un astuto artificio para molestar al pueblo inocente.
Y con esta orden judicial,
encargó a los alguaciles transportarlos a la cárcel de Leicester.

El alguacil encargado de llevar a G. Fox y a sus amigos a prisión,
no estaba dispuesto a hacerlo él mismo, y siendo la temporada de cosecha,
era difícil encontrar que alguien fuera con ellos.
Él quería que les dieran la orden judicial, y que ellos mismos la llevaran al carcelero.
Ellos se rehusaron hacerlo,
aunque en algunas ocasiones algunos de sus amigos lo habían hecho;
porque los alguaciles tenían tal experiencia de su fidelidad,
que se atrevían a confiar en ellos incluso en esos casos,
sin temer que intentaran escapar.
Y así, el alguacil contrató a un pobre hombre,
que se mostró reacio a acompañarlos en esa misión; sin embargo,
cabalgaron con él por el condado, siendo cinco en total.
Algunos de ellos llevaban sus biblias abiertas en sus manos,
y cuando cruzaban los pueblos les decían a las personas
que eran prisioneros del Señor Jesucristo,
y que iban a sufrir prisiones por causa de Su nombre.
Al llegar a Leicester y entrar en una posada,
el dueño de la casa pareció algo afligido porque iban a ser llevados a la cárcel,
pero como no estuvieron dispuestos a consultar con abogados (lo que se les aconsejó),
fueron llevados a prisión. Cuando llegaron G. Fox preguntó si el carcelero o su esposa,
era el dueño de la cárcel, y le dijeron: "`La esposa.`"
Esta mujer, aunque coja e incapaz de moverse sin sus muletas,
golpeaba a su esposo cuando él estaba a su alcance, si no hacía lo que ella quería.

Al darse cuenta G. Fox de que sin el permiso de ella
no podría llegar a un acuerdo con su esposo,
consiguió que alguien negociara con ella una habitación para él y sus amigos,
y que los dejara darle lo que ellos quisieran; a lo cual,
ella consintió. Pero luego se les dijo a los prisioneros que el carcelero
no les permitiría llevar ninguna bebida del pueblo a la cárcel,
sino que debía beber únicamente la cerveza que ellos le compraran a él,
y que (como era fácil de adivinar) sería a un precio muy alto.

G+++.+++ Fox dijo que él podía remediar eso; porque como el carcelero no podía negarles agua,
él cogería un cubo de agua una vez al día y pondría dentro de él un poco de ajenjo,^
footnote:[Se pensaba que el ajenjo purificaba el agua de toxinas y parásitos.]
y eso les serviría. Mientras G. Fox estuvo en prisión,
él y sus amigos tuvieron una reunión cada Primer-día en el patio,
a la que no sólo acudían los deudores y delincuentes que estaban presos,
sino también varias personas del pueblo y del condado;
por lo que muchos fueron convencidos de la verdad que él predicaba,
y continuaron siendo fieles testigos de ella.

Mientras G. Fox estuvo confinado allí,
varios más de sus amigos fueron enviados a prisión, hasta unos veinte.
Y cuando llegaron las sesiones del tribunal, fueron llevados delante de los jueces,
y estos les ofrecieron los juramentos de lealtad y supremacía;
pues esta era la trampa que comúnmente se usaba contra este pueblo,
cuando ninguna otra cosa era hallada para acusarlos.
Pero G. Fox les dijo que él nunca había prestado un juramento en su vida: "`Y,`" añadió,
"`ustedes saben que no podemos jurar porque Cristo y Sus apóstoles lo prohibieron;
y por lo tanto, esto no es más que una trampa contra nosotros.
Sin embargo,
si ustedes pueden probar que después de que Cristo y Sus apóstoles prohibieran jurar,
les ordenaron a los Cristianos jurar, entonces prestaremos esos juramentos.
De lo contrario, estamos resueltos a obedecer el mandamiento de Cristo,
y la exhortación de los apóstoles.`"
Ante esto,
se les afirmó que debían prestar el juramento para manifestar su lealtad al rey.
G+++.+++ Fox, para mostrar que él no era desleal al rey,
les contó que él anteriormente había sido hecho prisionero por el coronel Hacker,
y que había sido llevado de ese pueblo a Londres,
bajo el pretexto de que él celebraba reuniones conspirando para traer al rey Carlos.
Luego pidió que la orden judicial contra ellos fuera leída,
la cual mostraría que la razón de su encarcelamiento era
la intención de ellos de celebrar una reunión. Y añadió,
que el señor Beaumont no podía enviarlos a la cárcel por esa ley,
a menos que hubieran sido efectivamente apresados en una reunión,
e instó a la lectura de la orden judicial,
para que se pudiera ver cuán injustamente habían sido encarcelados.
Pero dijera lo que dijera, los jueces no tomaron nota de la orden judicial,
sino que convocaron a un jurado,
y acusaron a los prisioneros por rehusarse a prestar los juramentos de lealtad y supremacía.

Mientras los prisioneros estaban esperando en la corte,
un carterista había metido su mano en el bolsillo de algunos de ellos,
y ellos se lo hicieron saber a los jueces y les mostraron
al ladrón. Entonces ellos lo llamaron,
y al interrogarlo no pudo negar lo que había hecho; sin embargo lo dejaron libre,
como si el robo a los llamados Cuáqueros no fuera un delito.

No había pasado mucho tiempo antes de que el jurado regresara,
y les diera a los prisioneros el veredicto de culpables.
Los jueces susurraron entonces entre ellos,
y le ordenaron al carcelero que cogiera a los prisioneros
y los llevara de regreso a la cárcel.
Pero poco después de que regresaran a la cárcel, el carcelero llegó y les dijo:
"`Caballeros, es el deseo del tribunal que todos sean puestos en libertad,`" etc.
Y así fueron liberados repentinamente, lo cual, fue notable en verdad,
porque el jurado los había declarado culpables y se suponía que debía seguir una sentencia.
Pero la libertad de G. Fox parece haberse debido a la siguiente causa:
Él había recibido una carta del señor Hastings, quien al oír de su encarcelamiento,
les había escrito desde Londres a los jueces de las
sesiones para que lo pusieran en libertad.
Él no les había mostrado todavía esa carta a los jueces,
aunque parece que ellos habían recibido algún conocimiento
de la opinión del señor Hastings de otra fuente,
lo que los hizo tomar la decisión de la repentina liberación. G. Fox ahora libre,
llevó dicha carta al señor Beaumont, quien tras abrirla y leerla,
parecía algo preocupado; sin embargo,
lo amenazó diciéndole que si tenía más reuniones en Swanington,
las dispersaría y lo enviaría a él a prisión de nuevo.
Pero, a pesar de las amenazas,
él y sus amigos fueron a Swanington y tuvieron una reunión ahí sin ser molestados.
De ahí viajó a Londres donde lo dejaremos,
y mientras tanto veremos lo que sucedía en otros lugares.

Un tiempo antes de esto, Thomas Goodair y Benjamin Staples fueron encarcelados en Oxford,
y al ser llevados a la corte de judicatura ante sir William Walter,
quien se sentaba ahí como juez,
y al ser interrogado Goodair y no encontrarse nada en su contra,
se le presentó el juramento de lealtad,
al que respondió que él reconocía al rey como supremo
gobernador en los asuntos civiles temporales,
y que estaba dispuesto a obedecerlo en todos los mandatos justos.
"`Pero,`" dijo,
"`si el rey Carlos y los que están bajo su autoridad me
ordenan hacer algo contrario al mandamiento de Cristo,
entonces debo obedecer a Cristo en lugar de obedecer al rey Carlos,
o a los que estén bajo su autoridad.
Es por un asunto de consciencia que no puedo jurar,
aunque ganara el mundo entero con ello.
Porque Cristo ha prohibido hacerlo, diciendo:
'`No juréis en ninguna manera;`' y Santiago dice:
'`Pero sobre todo no juréis.`'`" Pero todo lo que dijo Goodair fue en vano,
porque le demandaron que jurara, y al rehusarse continuamente a jurar,
el juez Walter les preguntó a los que estaban con él en el banquillo,
si tenían algo que decir en contra de que dictara sentencia contra ellos.
Habiendo dicho todos ellos que no, él le habló así a Goodair: "`Escucha tu sentencia.
Quedas fuera de la protección del rey.
Todas tus tierras,
propiedades y posesiones personales son embargadas
y quedarán confiscadas para el uso del rey;
y tú permanecerás prisionero durante la voluntad del rey.`"
Luego le ordenó al carcelero que se llevara a Goodair,
quien preguntó si se le había ordenado al carcelero que lo encadenara,
porque él había estado encadenado como los ladrones y los
delincuentes antes de haber sido llevado al tribunal.
Ante lo cual el juez respondió: "`El carcelero puede hacer contigo lo que quiera;
porque ahora estás fuera de la protección del rey.`"
Y así fue sacado y Benjamin Staples llevado al estrado,
a quien también se le ofreció el juramento, y como rehusó tomarlo también,
se dictó la misma sentencia contra él. Al regresar ambos hombres a la cárcel,
el carcelero les dijo a los otros prisioneros que estaban ahí por maldades y deudas:
"`Si necesitan abrigos, pueden tomar los de los Cuáqueros,
porque ellos están ahora fuera de la protección de la ley.`"
Pero uno de los prisioneros fue muy honesto al decir,
que él prefería andar desnudo que coger los abrigos de esos hombres.
Cuánto tiempo estuvieron ellos en prisión,
y si murieron ahí o finalmente fueron liberados, no lo sé.^
footnote:[Según el relato de John Witing,
ambos hombres fueron liberados en la siguiente "`liberación general de la cárcel.`"
Thomas Goodair fue posteriormente encarcelado durante algunos años en Warwick,
habiendo sido acusado sin juicio legal ni sentencia de premunire.
Finalmente murió en Selby, en Yorkshire, en 1693.]

Pero ahora regreso a Ambrose Rigge, quien habiendo llegado a Hurst Pier-point en Sussex,
tuvo una reunión ahí en la casa de su suegro, el capitán Thomas Luxford.
Esto disgustó tanto al sacerdote Leonard Letchford,
que Rigge fue capturado y llevado delante de los jueces Walter Burril,
Nisel Rivers y Richard Bridge, quienes teniendo la intención de someterlo a sufrimientos,
le presentaron el juramento de lealtad.
Al decir que él no podía jurar por un asunto de consciencia,
fue enviado inmediatamente a la prisión de Horsham, y a la hora de la sesión judicial,
fue llevado a la corte donde el juez Samuel Brown dictó la sentencia
de '`premunire`' contra él. Entonces fue llevado de vuelta,
y por instigación del mencionado Leornard Letchford,
recluido sin ninguna libertad por más de diez años,
y durante ese tiempo sufrió muchas penurias por la malicia de los carceleros,
ya que los prisioneros como él estaban excluidos de la protección del rey.

Entre tanto,
el antes mencionado sacerdote Letchford citó a la
esposa de Rigge para que le pagara los diezmos,
pero como ella se rehusó hacerlo,
también fue encarcelada por la acusación de este sacerdote.
Luego, el sacerdote también se apoderó de los bienes de ella,
llevándose además lo que su esposo había ganado en prisión con su duro trabajo,
y no les dejó a él ni a su esposa una cama donde acostarse.
De hecho,
también se llevó una olla que ellos habían tomado
prestada de otros prisioneros para hervir la comida,
y se jactó de haber sujetado a Rigge con tal seguridad,
que no estaba en poder del rey liberarlo.
Pero, a pesar de esta malvada jactancia, para su gran intranquilidad y disgusto,
vivió para ver a Rigge liberado por el rey bajo el gran sello.
Thomas Luxford, suegro de Ambrose Rigge,
después de haber llegado a ser parte de la sociedad de los llamados Cuáqueros,
también se negó a pagarle sus diezmos,
e igualmente sintió los efectos de la furia de Letchford,
porque hizo que lo metieran en la cárcel donde fue mantenido seis años. Y después
de que estos prisioneros fueron finalmente liberados por el alguacil,
T+++.+++ Luxford fue excomulgado por Letchford,
y posteriormente demandado por el estatuto __de excommunicato capiendo,__^
footnote:[El estatuto _de excommunicato capiendo_ era un escrito del antiguo
derecho inglés que ordenaba el encarcelamiento de una persona excomulgada,
hasta que él o ella se sometiera a la iglesia nacional.]
por lo que fue encerrado en prisión de nuevo,
hasta que eventualmente fue puesto en libertad por una ley del Parlamento.

No mucho después de esto,
Letchford obtuvo una orden judicial para demandar también a otros
de los llamados Cuáqueros que pertenecían a su parroquia,
por no pagar diezmos.
Pero antes de que pudiera encarcelarlos sucedió,
que habiéndose acostado sano por la noche, en la mañana fue encontrado tieso,
muerto en su cama, según el testimonio de sus vecinos;
y esto evitó el golpe que había dirigido contra los otros.

Por no estar dispuesto a terminar este relato abruptamente, avancé en el tiempo,
pero ahora regreso al año 1662.
A mediados de este año, sir Henry Vane y John Lambert,
ambos vigorosos campeones contra el rey Carlos I,
y que habían tenido gran autoridad bajo el gobierno anterior,
fueron llevados a sus respectivos juicios.
Vane se comportó con una gran presencia de ánimo.
Hasta qué punto era culpable, no lo voy a averiguar,
pero fue declarado culpable y después decapitado en Tower-Hill.
Él tenía fama de ser un hombre de gran conocimiento,
ya que había sido uno de los principales miembros
del Parlamento Largo y un opositor de Cromwell;
pues era un completo republicano,
y había tenido gran participación en la administración de los asuntos de estado.
Lambert, quien había sido un eminente general, salvó su vida; pues como Vane,
según dice Ludlow, abogó por la vida y libertades de su país, y Lambert por las de él,
evadió la tormenta que se llevó a Vane.
Lambert entonces, aunque condenado a muerte, pidió clemencia,
y fue confinado a prisión perpetua y llevado a una pequeña isla cerca de Plymouth^
footnote:[Isla Drake.]
donde terminó sus días.

Ahora bien, tras la insurrección de los hombres de la Quinta Monarquía,
se aprovechó la oportunidad para promulgar una ley
contra las reuniones conspiradoras y sediciosas,
y así se incrementó la persecución contra los Cuáqueros.
Y bajo el pretexto de que las reuniones de ellos eran peligrosas
y constituían un terror para los súbditos del rey,
se promulgó una ley adicional contra los que se negaban a prestar juramento.

[.embedded-content-document.legal]
--

[.letter-heading]
Ley para prevenir el mal y el peligro que pueda surgir
por ciertas personas llamadas Cuáqueros,
y por otros que se niegan a prestar juramentos legales.

Al considerar que en los últimos tiempos ciertas personas bajo el nombre de Cuáqueros,
y otros nombres de separación, han adoptado y mantenido diversas opiniones y principios,
entre otros, que el prestar juramento, en cualquier caso,
incluso ante un magistrado legítimo,
es totalmente ilegal y contrario a la palabra de Dios;
debido a que dichas personas se niegan diariamente a prestar juramento,
aunque sea legalmente presentado,
por lo que a menudo sucede que la verdad es completamente
suprimida y la administración de justicia muy obstruida;
al considerar que dichas personas, bajo el pretexto de adoración religiosa,
se reúnen con frecuencia en gran número,
en varias partes de este reino para poner en gran peligro la paz y seguridad pública,
y para el terror de las personas,
al mantener una correspondencia secreta y estricta entre ellos,
mientras se separan y dividen del resto de los buenos y leales súbditos de su majestad,
de las congregaciones públicas y de los lugares comunes de adoración divina, por tanto:

Para remediar y prevenir mejor las muchas formas de mal y peligro que surgen,
y puedan surgir, por tales principios peligrosos y dichas asambleas ilegales,
se decreta por la excelentísima majestad del rey,
por y con el consejo y consentimiento de los señores espirituales y temporales,
y por la autoridad del Parlamento: (1) Que aquella persona o personas,
que sostengan que prestar un juramento en cualquier
caso (aunque sea delante de un magistrado legítimo),
es totalmente ilegal y contrario a la palabra de Dios,
desde y a partir del 24 de Marzo del presente año de nuestro Señor, 1661,
y se nieguen voluntaria y obstinadamente a prestar un juramento que es presentado legalmente;
(2) Que traten de persuadir a cualquier otra persona,
a quien se le haya presentado un juramento de forma debida y legal,
a que se niegue y se abstenga de prestarlo; (3) Que por medio de una impresión,
escrito o cualquier otro medio sostengan y defiendan que
prestar un juramento en cualquier caso es totalmente ilícito;
(4) Que si dichas personas, comúnmente llamadas Cuáqueros,
desde y a partir del 24 de Marzo salen de sus lugares
de residencia y se reúnen en número de cinco o más,
de dieciséis años en adelante, en cualquier momento, en cualquier lugar,
bajo el pretexto de unirse a un culto religioso no
autorizado por las leyes de este reino;
(5) Que en tales casos, la parte ofensora,
al ser condenada legalmente por el veredicto de doce hombres, o por su propia confesión,
o por la notoria evidencia del acto, perderá y le pagará a la majestad del rey,
por la primera ofensa, la suma que se le imponga, que no excederá las cinco libras.

(6) Que si una persona o personas,
habiendo sido condenadas una vez por alguno de los mencionados delitos,
vuelven a transgredir en ellos y son legalmente condenadas, estas, por la segunda ofensa,
le pagarán al rey la suma que se les imponga, que no excederá las diez libras;
(7) Que las mencionadas penas se aplicarán mediante la incautación de propiedades,
y la venta de los bienes de la parte condenada.
(8) Que ante la falta de incautación o pago de dichas penas,
dentro de la semana siguiente a la condena, las partes condenadas mencionadas,
por la primera ofensa, serán encerradas en la cárcel común o casa de corrección,
por el espacio de tres meses; y por la segunda ofensa, seis meses,
sin fianza o pago de garantías, y ahí deberán realizar trabajos forzados.
(9) Que si alguna persona,
después de haber sido condenada dos veces por alguno de los delitos mencionados,
transgrede una tercera vez y es condenada legalmente por ello,
entonces por su tercera ofensa renunciará al reino,
o será transportada en algún barco o barcos,
a cualquiera de las plantaciones de su majestad más allá de los mares, etc.

--

Esta ley hizo que Edward Burrough escribiera un librito llamado,
[.book-title]#The Case of the People called Quakers, Stated,
to Show the Falsehood of the Accusations Charged upon Them.#^
footnote:[El caso de los llamados Cuáqueros,
expuesto para demostrar la falsedad de las acusaciones que se les imputan.]
En este tratado demostró, en primer lugar,
que incluso si se supusiera que los Cuáqueros eran personas
herejes y estaban equivocadas (lo cual nunca se ha probado),
aun así no se encuentran ejemplos en las Escrituras
de que tales personas deban ser encarceladas,
o afligidas con castigos corporales.
Y después de tratar este asunto en general,
expuso el estado de su forma de reunión y adoración,
apelando a otros por este motivo con las siguientes palabras:

[.embedded-content-document.treatise]
--

¿Qué juicio dan nuestros vecinos en este caso?
Con respecto a nuestras reuniones,
dicen que por muchos años han sabido que nos reunimos así, en pueblos y villas,
y que nunca han visto o sabido de algún daño o perjuicio en ellas,
ni han sido dañados en sus personas o propiedades por nuestras reuniones.
El Testigo mismo de Dios en todos nuestros vecinos testifica y da juicio,
de que nuestras reuniones han sido siempre pacíficas y tranquilas,
que nos reunimos en paz y buen orden, y que así nos despedimos,
y que ninguna persona ha sido dañada alguna vez por nuestras reuniones.
Pregúntenles a nuestros vecinos y les dirán,
que ellos creen en sus consciencias que nuestras reuniones son para bien,
que tienen buenos efectos, que no son malas ni le producen ningún mal a nadie.

En cuanto a la manera en que nos reunimos y estamos juntos, es ordenada,
decente y de buen testimonio entre los hombres.
Y en cuanto a cualquier doctrina que haya sido sostenida,
o haya sido oída de alguno de nosotros, nadie puede acusarla, realmente, de ser un error,
una herejía o sedición; sino todo lo contrario,
saben que ella testifica contra todo pecado e iniquidad,
y se inclina a volver a la persona de la impiedad e injusticia a la verdad y santidad.
De hecho,
muchos pueden declarar que esto es llevado a cabo
por la doctrina predicada en nuestras reuniones;
y nuestros vecinos puede testificar que nosotros
salimos de nuestras reuniones en paz y buen orden,
y a una hora respetable; y pueden decirles que no son aterrorizados,
ni la paz de la tierra perturbada por nuestras reuniones,
ya que son celebradas en el temor de Dios y para la gloria de Su nombre,
al estar de acuerdo con la ley de Dios, el evangelio y el ejemplo Cristiano primitivo.

[.small-break]
'''

Somos acusados de ser delincuentes malvados y por eso encarcelados,
porque se supone que no nos sometemos en obediencia a las leyes conocidas del país,
sino que las infringimos; y que no nos conformamos a la iglesia nacional,
ni pagamos diezmos, ni prestamos juramentos,
aunque sepamos que las leyes de la tierra ordenan estas cosas.

Pero a esto digo: Primero,
en cuanto a la sumisión a todas las leyes conocidas de la tierra,
es sabido por Dios y por nuestros vecinos, que nuestro principio y práctica es,
y ha sido siempre, someternos a todo gobierno y a todas las leyes de los hombres,
ya sea haciendo o sufriendo,
como hasta el día de hoy que no nos resistimos a las más grandes
aflicciones y tribulaciones que puedan ser impuestas sobre nosotros.
Es bien conocido por nuestros vecinos y por todas las personas,
que nos sometemos a todas las leyes de los hombres,
mediante paciente sufrimiento sin resistencia.
Porque cuando una ley requiere de nosotros algo que
no podemos realizar por asuntos de consciencia,
cumplimos dicha ley con paciente sufrimiento, sin resistir a ningún hombre,
ni pagando mal por mal a nadie.

El juicio de las Escrituras, según la ley, el evangelio y los precedentes de los santos,
nos justifica en este caso,
al elegir pacientemente sufrir las más grandes penas de la ley antes que obedecer,
(haciendo) cualquier ley que requiera cosas contrarias a nuestras consciencias puras.
Esto está en concordancia con el ejemplo de los tres jóvenes en Daniel 3,
a quienes se les ordenó postrarse y adorar la imagen
de oro cuando oyeran el sonido de la música,
bajo pena de ser arrojados en medio del horno de fuego; mandato que no pudieron obedecer,
ni postrarse para adorar la imagen,
sino que prefirieron sufrir el castigo de ser arrojados en medio del fuego,
lo que consecuentemente se hizo con ellos.
También en el caso de Daniel, capítulo 6,
a quien se le ordenó no hacer ninguna petición a ningún dios u hombre por treinta días,
excepto al rey Darío, bajo la pena y aflicción de ser arrojado al foso de los leones.
Pero Daniel prefirió sufrir la pena antes que obedecer el mandamiento,
y por eso fue arrojado al foso de los leones.
Por estos ejemplos de hombres santos,
junto con muchos más que se podrían dar de las Escrituras,
es evidente que los hombres justos preferirán sufrir que obedecer
cualquier ley del hombre que sea contraria a sus consciencias.
Así, pues, la ley de Dios,
el ejemplo de los santos y las Sagradas Escrituras nos juzgan en este caso,
al preferir sufrir que obedecer leyes contrarias a nuestras consciencias.
Y estas, por consiguiente, también condenan a los que nos persiguen y encarcelan,
porque nos exigen obediencia en cosas que están en contra de nuestras consciencias.

Segundo, aunque nosotros desobedecemos algunas leyes,
y no podemos obedecer activamente todas las leyes de los hombres
cuando exigen y demandan cosas contrarias a una buena consciencia,
aun así, en esto también somos justificados por la ley de Dios,
el ejemplo de los santos y las Sagradas Escrituras, y dan un juicio a nuestro favor,
y en consecuencia, contra nuestros enemigos en este caso.
Esto es particularmente evidente en los dos ejemplos antes mencionados en Daniel,
donde a los tres jóvenes se les ordenó expresamente postrarse y adorar la imagen de oro,
y a Daniel se le exigió que por decreto del rey, no le orara a ningún dios u hombre,
salvo al rey Darío. Sin embargo,
estos santos hombres de Dios desobedecieron absolutamente
la ley y el decreto que les exigían,
y actuaron contra el mandamiento.
Por su parte, a los apóstoles de nuestro Señor Jesucristo^
footnote:[Hechos 4:18]
se les ordenó que no predicaran más en el nombre de Jesús,
pero ellos desobedecieron el mandamiento y continuaron
predicando en el Espíritu y poder de Cristo,
contra el mandamiento de los gobernantes, y apelando dijeron:
"`Es necesario obedecer a Dios antes que a los hombres.`"^
footnote:[Hechos 5:29]
Podríamos recoger muchos ejemplos de las Escrituras,
en los que vemos que los siervos de Dios desobedecieron las órdenes de reyes y gobernantes,
y no pudieron obedecer (haciendo) ningún mandato contrario a Dios,
sino que prefirieron sufrir aflicciones y hasta la muerte misma,
antes que obedecer las leyes y decretos que exigían algo contra la consciencia pura.
Y este es nuestro caso hoy.
Nosotros no podemos obedecer (haciendo) nada contra nuestras consciencias,
sino que debemos quebrantar las leyes de los hombres y desobedecer sus mandatos,
antes que quebrantar la ley de Dios y pecar contra nuestras propias consciencias,
sin importar lo que suframos por ello;
y los ejemplos de los santos y las Escrituras nos justifican en este sentido.

[.small-break]
'''

Por tanto,
que nuestros enemigos dejen de gritar que somos "`rebeldes y desobedientes
a las leyes y al gobierno;`" porque no somos de los que desobedecen
voluntaria y obstinadamente ninguna ley de los hombres,
sino sólo por motivo de consciencia, y para no pecar contra Dios,
ni ofender a Su testigo en nosotros.
Es por esta razón que no podemos obedecer leyes contrarias a nuestras consciencias,
sin importar lo que suframos (sufrimientos que no rechazamos,
ni nos rebelamos contra ninguno en este caso).
Nuestros principios y prácticas son obedecer todas las leyes y gobiernos,
ya sea haciendo o sufriendo.
Y aunque desobedezcamos las leyes que no están de acuerdo con la ley de Dios,
y escojamos sufrir,
aun en esto somos justificados por la ley de Dios y las Sagradas Escrituras.

Tercero, en cuanto a nuestra conducta entre los hombres,
en lo que se refiere a nuestro diario caminar y conversación con ellos en nuestros tratos,
que es en toda honestidad y fidelidad, verdad y equidad en nuestros trabajos y palabras,
nuestros vecinos testificarán por nosotros.
No nos justificaremos a nosotros mismos en esto, Dios nos justifica; y la ley de Dios,
el evangelio de Cristo, las Escrituras, los ejemplos de los hombres santos,
nuestros vecinos y el Testigo de Dios en las consciencias de los hombres,
darán testimonio de nuestra conducta.
¡Oh, Señor Dios eterno, sé Tú el juez de nuestra causa.
Manifiesta a todo el mundo, a Tu tiempo, que nosotros somos Tu pueblo,
que Te amamos por encima de todo, que tememos Tu nombre más que cualquier otra cosa,
que amamos la justicia y aborrecemos la iniquidad,
y que ahora sufrimos por Tu santo nombre y verdad, por Tu honor y justicia,
y por Tu verdad y santidad.
Oh, Señor, Tú sabes que estamos resueltos a morir,
antes que ofenderte en la cosa más pequeña!

Que nuestras acusaciones y respuestas sean verdaderamente
consideradas y pesadas en la balanza de justicia y verdad,
en la consciencia de todo hombre.
Que todo el mundo juzgue en este caso: ¿Merecemos ser arruinados, destruidos,
encarcelados, desterrados y devorados por bestias salvajes,
como amenazan nuestros enemigos?
¿Somos herejes?
¿Somos sediciosos?
¿Somos borrachos?
¿Somos traidores?
¿Somos de los que la ley Dios condena?
¿Qué mal hemos hecho en la tierra?
¿Le hacemos daño a alguien?
¿Acaso no somos inocentes delante del Señor y de los hombres?
Apelamos al justo Testigo de Dios y a los hombres.
Que se responda; y aunque ningún hombre oiga o considere nuestra causa hoy,
aun así el Señor defenderá nuestra causa en Su tiempo y ocasión,
y le dará a conocer al mundo que somos Su pueblo.
Entre tanto, estamos dispuestos a sufrir el rechazo de los hombres impíos,
hasta que el Señor obre la liberación en la tierra.

Pero ahora, los magistrados y gobernantes podrían objetar,
que ustedes tienen una ley contra nosotros,
y que ahora debemos sufrir el castigo de esta,
ya que no pueden evitar poner en ejecución la ley,
de acuerdo con sus juramentos y oficios; y que no son ustedes los que nos persiguen,
sino que ahora sufrimos por la ley de la tierra,
y que ustedes no pueden ser culpados por nuestros
sufrimientos porque sólo ejecutan la ley, etc.
Este es el razonamiento de algunos actualmente.

A todo esto respondo: Es cierto que ahora hay una ley promulgada contra nosotros,
que se dice que es la razón de nuestro sufrimiento.
Y si esta ley es justa o injusta en sí misma, no lo demostraré ahora,
sino que lo dejaré al juicio de todo hombre Cristiano que nos conoce,
que conoce nuestros principios, doctrinas, formas y conducta;
y que ellos juzguen si merecemos las penas y castigos en ella descritos,
por alguno de los principios o prácticas que nosotros sostenemos o mantenemos.
Pero aunque haya una ley contra nosotros,
los magistrados que la ejecutan pueden hacerlo con moderación o con violencia,
con discreción o con excesivo rigor;
y será bueno que todos usen la moderación y la discreción en este caso,
y así se salvarán del peso de la ira e indignación que caerán
sobre todos los violentos que buscan destruir al inocente,
y se regocijan cuando se presenta la ocasión.

Y aunque se promulgó esta ley contra las reuniones que son "`peligrosas
para la paz pública,`" y "`un terror para el pueblo,`" con todo,
nuestras reuniones no son así, por lo tanto,
esta ley no puede extenderse justamente en su ejecución para disolver nuestras reuniones,
que son para la adoración de Dios,
que son pacíficas y de buen testimonio entre todos los buenos hombres,
y que no son para perturbar la paz, ni para el terror del pueblo.

Y aunque esta ley se pretenda contra nosotros,
con el fin de desterrarnos y librar a la tierra de nosotros,
¿debe necesariamente ser ejecutada hasta su colmo,
sin limitación ni restricción? ¿Debe ser ejecutada esta ley más que otras leyes,
que están tan verdaderamente promulgadas y tan plenamente
vigentes como puede estarlo esta ley?
Porque en realidad, hay algunas leyes que merecen mayor ejecución que esta,
y sin embargo, permanecen dormidas como es evidente en la actualidad.
Como es el caso de __4 Jac. c. 5,__^
footnote:[Entiéndase año cuarto del reinado de Jacobo, cláusula 5.]
en donde se encuentran estas palabras:

"`Que se promulgue,
que todas y cada una de las personas que se emborrachen
y sean legalmente condenadas por el delito de embriaguez,
serán multadas y perderán cinco chelines por cada delito de este tipo,
a pagar a los administradores de la iglesia de la parroquia donde se cometa el delito,
quienes serán responsables de usarlo a favor de los pobres de la misma parroquia.
Y si la mencionada persona o personas así condenadas
se negaran o rechazaran pagar dicha multa,
esta será recaudada de sus bienes por medio de una orden de precepto de la corte,
juez o magistrados, ante quienes fueron condenadas.
Y si el infractor no es capaz de pagar la suma de cinco chelines,
será enviado al cepo por el espacio de seis horas.`"

Y en __1 Jac. c. 7,__^
footnote:[Entiéndase año uno del reinado de Jacobo, cláusula 7.]
se encuentran estas palabras:

"`Todas las personas que anden mendingando;
todos las personas ociosas que anden por cualquier condado,
ya sea mendingando o usando cualquier arte sutil, o juegos o trucos ilegales,
o pretendiendo que pueden decir la fortuna, o cualquier otra imaginación fantástica;
todos los esgrimistas, domadores de osos,^
footnote:[Los que entrenaban osos y los enfrentaban
contra perros para el entretenimiento del público.]
trovadores comunes que anden deambulando; serán capturados,
juzgados y considerados villanos, vagabundos y mendigos,
y sufrirán las penas y castigos que se expresan en __39 Eliz. c. 4,__^
footnote:[Entiéndase año treinta y nueve del reinado de Elizabeth, cláusula 4.]
a saber, que toda persona de este tipo será desnudada de la mitad hacia arriba,
y públicamente azotada hasta que su cuerpo esté ensangrentado,`" etc.

Lean este estatuto en su totalidad, y luego consideren cuán puntualmente se ejecuta hoy,
y por qué la última ley contra nosotros,
es más rigorosamente aplicada sobre personas honestas, sobrias y de buena conducta.
Porque muchas de estas son arrastradas de sus reuniones
donde se han unido sólo para adorar a Dios,
sin ningún otro fin.
Y muchas son enviadas a prisión y perseguidas hasta el colmo de dicha ley,
mientras personas ociosas siguiendo juegos y trucos ilegales,
domadores de osos y trovadores de diversas clases,
vagan de arriba para abajo por las ciudades y condados; y sin embargo,
tales personas y cosas, aunque aparecen públicamente, están permitidas,
y algunos de los magistrados les prestan poca o ninguna atención,
como para castigarlos por la infracción de la ley.

Parece, entonces, que esta ley contra nosotros se ejecuta mucho más que esas otras leyes,
porque hay más envidia contra nosotros y nuestras reuniones religiosas pacíficas,
que la envidia que hay contra la vulgaridad, maldad, embriaguez,
representaciones teatrales y cosas similares.
Y estos magistrados, dondequiera que estén,
no son excusables ante los ojos de Dios cuando procesan una ley contra nosotros,
pero no hacen nada para aplicar otras buenas leyes contra
personas y prácticas profanas e impías. Por tanto,
estos también se ven obligados a reconocer que no
es sólo porque hay una ley contra nosotros,
sino también, o mejor dicho, porque hay enemistad,
ira y maldad en los corazones de los hombres contra nosotros,
lo cual es la causa principal de nuestros sufrimientos en este día.

--

Así era E. Burrough, siempre laborioso,
y como un fiel y diligente ministro de Cristo estaba tan
plenamente entregado al servicio de Dios y de la iglesia,
tanto predicando como escribiendo en la defensa del evangelio,
que apenas reservaba tiempo para sí mismo.
Rara vez tomó un descanso,
sino que continuó trabajando incesantemente hasta que se acercó el momento de su partida;
demostrando claramente que su comida y bebida eran realmente,
hacer la voluntad de su Padre celestial;
y esto lo procuró incansablemente hasta el final de su días.

Ahora regreso a Nueva Inglaterra,
donde aunque la escena del asesinato ya se había representado en su totalidad,
su sed de sangre no se apagaba,
como puede verse en el siguiente relato que haré
de los crueles azotes infligidos a algunos.
Si yo relatara todo lo que ocurrió en Nueva Inglaterra,
por sí solo constituiría un volumen bastante grande; por tanto,
sólo mencionaré unos pocos casos.

Entre estos, me encuentro con Josiah Southick, (cuyos padres,
Lawrence y Cassandra habían sido de los primeros
que fueron desterrados de Boston debido a su religión,
como se ha mencionado antes;
y cuyo hermano y hermana habían sido dispuestos para ser vendidos como esclavos).
Este joven, después de un tiempo de haber estado en Vieja Inglaterra,
se sintió obligado a regresar a Boston, a pesar de sus severas leyes.
Por esto fue sentenciado a ser azotado detrás de una carreta,
primero en Boston y luego en Roxbury y Dedham, con los brazos extendidos.
Pero él les dijo a los que lo habían sentenciado: "`Aquí está mi cuerpo.
Si necesitan un testimonio adicional de la Verdad que profeso, tómenlo y háganlo pedazos,
es voluntariamente entregado.
En cuanto a la sentencia, no me importa;`" y añadió,
"`no me aterroriza más que si hubieran tomado una pluma,
la hubieran lanzado al aire y hubieran dicho:
'`ten cuidado para que no te haga daño.`' Porque, en definitiva,
la lengua no puede expresar o declarar la bondad y amor de Dios para con Su pueblo sufriente.`"
Luego fue desnudado y atado a la parte trasera de una carreta en Boston,
donde el verdugo lo azotó con toda la vehemencia que pudo.
Es de destacar, que el azote que se usaba para estas crueles ejecuciones,
no era un azote de cuerdas, como los usados en Inglaterra, sino de tripas secas,
y el extremo de cada cuerda tenía tres nudos, que al estar sujetas a un palo,
el verdugo con frecuencia asestaba los golpes con ambas manos,
provocando violentas heridas en el cuerpo.
Pero toda esta crueldad no fue capaz de hacer que Josiah desfalleciera,
porque mientras era conducido por las calles de Boston detrás de la carreta,
iba cantando en alta voz, y se le oyó decir estas palabras:
"`Aquellos que conocen a Dios como su fuerza, no temen lo que el hombre pueda hacer.`"
El mismo día fue azotado en Roxbury, y al día siguiente, que estaba muy frío,
fue eximido del resto de la condena y enviado a tierras salvajes;
estos furiosos profesantes de Nueva Inglaterra eran tan inhumanos,
que parece que pensaban que no estaba mal hacerles cualquier cosa a los Cuáqueros.
De hecho, ha sucedido,
que estando encerrados con ladrones y esforzándose por volverlos de sus vidas perversas,
han sido maltratados por eso,
y los ladrones puestos en libertad para que no se conviertan en Cuáqueros.

En Dover, Nueva Inglaterra, Anne Coleman,
Mary Tomkins y Alice Ambrose fueron sentenciadas a ser cruelmente azotadas,
por sólo haber llegado ahí. La orden judicial era la siguiente:

[.embedded-content-document.legal]
--

[.letter-heading]
A los alguaciles de Dover, Hampton, Salisbury, Newbury, Rowley, Ipswich, Wentham, Linn,
Boston, Roxbury, Dedham.
Hasta que estas Cuáqueras vagabundas sean sacadas de esta jurisdicción:

A ustedes y a cada uno se les ordena, en el nombre de la majestad del rey,
coger a estas Cuáqueras vagabundas, Anne Coleman, Maru Tomkins y Alice Ambrose,
y atarlas firmemente a la parte de atrás de una carreta,
y mientras se conduce la carreta a través de sus varios pueblos,
azotarlas sobre sus espaldas desnudas, sin exceder diez azotes sobre cada una,
en cada pueblo;
y así llevarlas de alguacil a alguacil hasta que estén fuera de esta jurisdicción,
ya que ustedes responderán a esto bajo su propio riesgo.
Esto les servirá como orden judicial.

[.signed-section-signature]
Richard Waldron.

[.signed-section-context-close]
En Dover, con fecha de 22 de Diciembre, 1662.

--

Esta orden fue verdaderamente cruel;
porque azotar a estas tres tiernas mujeres a través de once pueblos,
con diez azotes cada una en cada lugar, a lo largo de casi ochenta millas,
con un frío glacial,
habría sido suficiente para dejar sus huesos al descubierto
y sus vidas fuera de sus cuerpos.

Sucedió que un día muy frío, el representante Walden, en Dover,
hizo que estas mujeres fueran desnudadas de la mitad para arriba y atadas a una carreta.
Luego las azotó mientras el sacerdote miraba y se reía; lo cual,
al verlo algunos de sus amigos y tomar nota de la crueldad de Walden,
testificaron contra él; por lo que Walden puso a dos de ellos en el cepo.

Una vez azotadas en Dover, fueron llevadas a Hampton,
y ahí entregadas al alguacil William Fifield, quien, a la mañana siguiente,
quería azotarlas antes de que amaneciera;
pero las mujeres se negaron diciendo, que ellas no se avergonzaban de sus sufrimientos.
Entonces él les dijo que las azotaría con sus ropas cuando las tuviera atadas a la carreta.
Pero ellas le dijeron: "`O nos dejas libres,
o haces conforme a lo ordenado;`" lo cual era azotarlas con sus espaldas desnudas.
Entonces,
él habló con una mujer que estaba presente y le ordenó
que les quitara la ropa a las mujeres,
pero ella dijo que por nada del mundo lo haría. "`Entonces,`" dijo él,
"`declaro que yo mismo lo haré.`" Entonces las desnudó,
y luego se puso a temblar con el látigo en la mano y así llevó a cabo la ejecución,
aunque al principio había declarado que era un hombre valiente.
Luego las llevó a Salisbury, a través de tierra, y nieve a media pierna de profundidad,
y allí fueron azotadas de nuevo.

Sucedió que entre los espectadores, estaba un tal Edward Wharton que pasaba por ahí;
y mientras contemplaba la paliza, Thomas Broadbury,
secretario de los tribunales de Salisbury y Hampton le dijo: "`Edward Wharton,
¿qué haces aquí?`" "`Estoy aquí,`" respondió, "`para ver la maldad y crueldad de ustedes,
para que si matan a estas mujeres, yo pueda declarar cómo las asesinaron ustedes.`"
Porque, en efecto, sus cuerpos estaban tan desgarrados,
que si la Providencia no hubiera velado sobre ellas,
habrían estado en peligro de perder sus vidas.
Pero sucedió que después de esta paliza las mujeres fueron liberadas,
porque un tal Walter Barefoot solicitó que se le delegara a él llevarlas a Newberry,
pero en lugar de esto él las dejó en libertad; aunque John Wheelwright, el sacerdote,
le aconsejó al alguacil que continuara con el castigo de ellas.

Al ser liberadas inesperadamente, las tres se fueron a New Quechawanah,
donde tuvieron una reunión, y Shubal Drummer, el sacerdote del lugar,
también llegó y se sentó en silencio.
Cuando la reunión terminó, el sacerdote se puso de pie y dijo: "`Buenas mujeres,
ustedes han hablado bien y orado bien; por favor, díganme,
¿cuál es la regla por la que ustedes caminan?`"
Ellas le respondieron: "`El Espíritu de Dios es nuestra regla para caminar,
y debe ser la tuya y la de todos los hombres.`"
Pero él replicó: "`No es mi regla, ni espero que lo sea nunca.`"
Una clara evidencia de cómo los prejuicios pueden predisponer incluso a personas discretas;
pues al estar predispuestas a ello, a veces hablarán precipitadamente,
sin considerar lo que dicen.

Poco después, estas tres mujeres regresaron a Dover a visitar a sus amigos,
y estando en una reunión el Primer-día, los alguaciles, Thomas Roberts y su hermano John,
entraron apresuradamente y le pusieron las manos
encima a Alice Ambrose mientras estaba orando.
Tomándola, uno por un brazo y el otro por el otro,
la arrastraron al aire libre cerca de una milla,
con su rostro hacia la nieve que llegaba casi hasta las rodillas,
sobre tocones y árboles viejos; ellos se habían puesto sus ropas viejas a propósito,
para así no ensuciar sus mejores trajes.
Luego la encerraron en una casa y regresaron a buscar a Mary Tomkins,
a quien arrastraron de la misma manera; y viéndolo el padre de ellos,
Thomas Roberts viejo, se lamentó y lloró:
"`¡Qué desgracia que yo sea padre de hijos tan malvados.`"
Pero parecía que no les importaba lo que su padre dijera.
Este anciano había sido miembro de la iglesia en Dover por más de veinte años,
pero como ya no frecuentaba el culto por causa de la degeneración de ellos,
le quitaron su vaca, la leche de la cual ayudaba a mantenerlo a él y a su esposa.

Después de llevar a Mary Tomkins a la casa donde estaba Alice Ambrose,
fueron a buscar a Anne Coleman.
La mañana siguiente los alguaciles consiguieron una canoa,
y amenazaron a las mujeres con hacer algo para no volver
a tener problemas con ellas--lo que aparentemente significaba,
que las dejarían a merced del mar.
Entonces, un tal Edward Weymouth cogió a Mary por los brazos,
y la arrastró de espaldas contra los tocones de los árboles,
cuesta abajo de una colina muy empinada,
por lo que ella quedó muy herida y se desmayó varias veces.
También agarraron a Alice y la tiraron violentamente al agua,
y la mantuvieron nadando al lado de la canoa,
por lo que corrió peligro de ahogarse o morir congelada.
Anne Coleman también fue tratada con rudeza,
y todo esto se realizó en presencia de un anciano gobernante llamado Hate-evil Nutwel,^
footnote:[Que traducido es Odio-al-Mal Nutwel]
quien había incitado a los alguaciles a esta malvada acción,
demostrando así que llevaba el nombre equivocado.
Pero la maligna intención de estos hombres fue detenida por un poder de lo alto,
porque repentinamente se levantó una gran tempestad,
por lo que tuvieron que llevar a las mujeres de regreso a la casa,
y a eso de la medianoche las enviaron a todas a la nieve,
con un clima tan helado que la ropa de Alice estaba congelada como tablas.
A pesar de lo bárbaramente que fueron tratadas estas mujeres,
le plació al Señor preservar sus vidas y sustentarlas.

Sucedió después,
que Anne Coleman y cuatro de sus amigas fueron azotadas a través de Salem,
Boston y Dedham, por orden de William Hawthorn, quien antes de ser magistrado,
se había opuesto a la coerción por consciencia.
Y cuando durante el gobierno de Cromwell estaba la propuesta de
dictar una ley que impidiera que alguien predicara sin licencia,
él públicamente dijo en Salem, que si se dictaba una ley así en Nueva Inglaterra,
él lo consideraría uno de los actos más abominables que se hubieran cometido ahí,
y que sería una evidente señal de que Dios había abandonado Nueva Inglaterra.
Sin embargo,
este hombre se convirtió después en un feroz perseguidor de los que afirmaban
la libertad de la predicación. Ahora regreso a Anne Coleman;
cuando iba a ser azotada en Dedham y amarrada a una carreta,
el representante Bellingham después de ver la orden judicial de Hawthorn, dijo:
"`La orden es firme,`" y le ordenó al verdugo continuar; quien, alentado de esta manera,
la azotó tan severamente, que con el nudo del látigo le partió el pezón de un pecho,
lo que la torturó tanto, que casi le cuesta la vida.
Y ella, que era una mujer pequeña y frágil, pensando que la muerte podría ser su suerte,
dijo en una ocasión, que si llegaba a morir de esta manera,
estaba dispuesta a que su cuerpo fuera puesto delante de la puerta de Bellingham,
con una acusación de su boca de que él era culpable de su sangre.

No puedo pasar por alto el trato con el que se encontró
Elizabeth Hooton debido a su edad,
quien, teniendo casi sesenta años,
al oír de la maldad que se cometía por los de Nueva Inglaterra,
fue movida a hacer un viaje a América.

Ella salió de Inglaterra en el año 1661, llevando consigo a una tal Joan Broksup,
una mujer casi tan anciana como ella, quien resolvió libremente ser su compañera;
y debido a que no encontraban a un capitán de barco que
estuviera dispuesto a llevarlas a Nueva Inglaterra,
por la multa que se cobraba por cada Cuáquero que se llevara ahí,
se embarcaron hacia Virginia, donde encontraron una nave que las llevó parte del camino,
y después fueron por tierra el resto del trayecto, y así finalmente llegaron a Boston.
Pero ahí, no pudieron encontrar fácilmente un lugar de acogida,
por la pena sobre todos los que recibieran a un Cuáquero en su casa.
Sin embargo,
por fin una mujer las recibió. Al día siguiente fueron
a la prisión a visitar a sus amigos,
pero el carcelero no quiso dejarlas entrar y las llevó ante el gobernador Endicot,
quien con un lenguaje muy abusivo las llamó brujas,
y le preguntó a Elizabeth para que había llegado ahí. A esto ella respondió:
"`Para hacer la voluntad de Aquel que me envió.`" Y al demandar él cuál era esa voluntad,
ella replicó: "`Para advertirte que no derrames más sangre inocente.`"
Endicot replicó, que aún colgaría más;
pero ella le dijo que él estaba en las manos del Señor, quien podía llevárselo primero.^
footnote:[Lo cual se cumplió,
pues después de este momento no volvió a quitar la vida a ninguno de los llamados Cuáqueros,
y murió el 15 de marzo de 1665.]
Esto le disgustó tanto, que las envió a prisión, donde estaban muchos más de sus amigos.
Después de consultar qué hacer con ellas,
fueron llevadas a dos días de viaje dentro de parajes salvajes,
y dejadas entre lobos y osos.
Pero por la Providencia llegaron a Rhode Island, donde tomaron un barco a Barbados,
y de ahí a Nueva Inglaterra de nuevo, y así regresaron a Boston.
Pero entonces fueron puestas en un barco que las llevó a Virginia,
y de ahí Elizabeth partió hacia Vieja Inglaterra,
donde se quedó un tiempo en su propia casa.

Pero vino sobre ella el visitar Nueva Inglaterra otra vez, y así lo hizo,
esta vez llevando con ella a su hija Elizabeth.
Y después de arribar,
los magistrados presentes habrían multado al capitán del barco
con cien libras por llevarla ahí en contra de la ley de ellos,
si no es porque les dijo, que Elizabeth había estado con el rey Carlos II,
y que había obtenido de él la libertad de ir allí y comprar una casa.
Esto desconcertó tanto a estos perseguidores gruñones,
que quedaron confundidos y se vieron impedidos de apoderarse de los bienes del capitán.

Después de llegar a Boston, a pesar de los gobernantes,
Elizabeth fue donde ellos y les indicó que estaba ahí para comprar una
casa y vivir ahí. Ella fue cuatro veces a los tribunales con ese propósito,
pero le fue negado; y aunque había dicho que esta negativa le daba la oportunidad,
si iba a Inglaterra de nuevo, de presentarse ante el rey,
sus palabras fueron en vano y no tuvieron ninguna influencia sobre ellos.

Partiendo entonces, y pasando por varios lugares, llegó a Cambridge,
donde fue arrojada en un calabozo asqueroso y no había nada donde acostarse o sentarse.
Allí la mantuvieron dos días y dos noches, sin darle nada de comer o beber;
y como cierto hombre, movido por la compasión, le llevó un poquito de leche,
lo arrojaron en prisión también y lo multaron con cinco libras.
Cuando la llevaron a la corte, se ordenó que fuera enviada fuera de las costas,
y azotada en tres pueblos con diez azotes en cada uno.
Por tanto, en Cambridge la amarraron al poste de los azotes y le dieron diez latigazos,
con un látigo de tres cuerdas y tres nudos al extremo de cada cuerda.
En Water Town le dieron diez latigazos más, con varas de sauce; y para concluir,
en Dedham, en una mañana helada, recibió diez crueles latigazos más,
atada a la parte trasera de una carreta.
Luego, después de ser golpeada y flagelada,
fue puesta sobre el lomo de un caballo y llevada muchas millas dentro de tierras salvajes,
y hacia la noche, dejada donde había muchos lobos, osos y otras bestias salvajes,
y muchas aguas profundas que atravesar.
Pero al ser preservada por una mano invisible,
por la mañana llegó a un pueblo llamado Rehoboth, sin estar cansada ni desfallecida.
De ahí se fue a Rhode Island, y al llegar donde sus amigos,
dio gracias a Dios por haberla considerado digna y haberle permitido sufrir por Su nombre,
más allá de lo que su edad y género, en general, habrían podido soportar.

Después de una estancia ahí regresó a Cambridge, a unas ochenta millas,
para recoger su ropa blanca y su ropa,
que los inhumanos perseguidores no le permitieron
llevarse después de que la habían azotado.
Una vez recuperadas estas cosas y regresando con
su hija y Sara Coleman (otra mujer de edad),
fue detenida por el alguacil de Charlestown y llevada prisionera a Cambridge.
Ahí, al ser interrogada por uno de los magistrados cuyo nombre era Daniel Goggin,
sobre la razón de su regreso, siendo que ellos le habían advertido que no lo hiciera,
ella respondió que no había regresado por su propia voluntad,
sino que se había sido visto obligada a ello para recuperar su ropa,
la cual no le habían permitido llevarse con ella
después de que había sido azotada y expulsada,
y que luego había sido tomada a la fuerza del camino y llevada allí. Entonces
le preguntó a la otra mujer si ella estaba a favor de Elizabeth y su religión,
a lo que respondió: "`Yo estoy a favor de la Verdad.`"
Y de la hija de Elizabeth exigió: "`¿Tú estás a favor de la religión de tu madre?`"
Pero como ella permaneció en silencio,
fueron enviadas a la casa de corrección con orden de ser azotadas.
La mañana siguiente el verdugo llegó antes de que amaneciera y les preguntó,
si querían ser azotadas ahí, pero esto hizo que Elizabeth le preguntara:
"`¿Vienes a tomar nuestra sangre en la oscuridad,
por vergüenza a que se vean tus actos?`"
Pero no hizo caso de lo dicho por ella,
y se la llevó escaleras abajo y la azotó con un látigo de tres cuerdas.
Luego se llevó a la otra mujer e hizo lo mismo.
Y tomando a la hija de Elizabeth también le hizo lo mismo,
quien nunca había estado ahí antes, ni había dicho o hecho nada.
Después de esto,
Elizabeth (madre) fue azotada de nuevo atada a la parte trasera de una carreta,
en Boston y otros lugares, donde había ido a ver a sus amigos.
Pero después de esto la he visto varias veces en Inglaterra en buen estado.

Podría relatar muchas más crueldades de los perseguidores de Nueva Inglaterra,
pero deseo llegar al final, por lo tanto,
daré un gran paso y dejaré atrás un espacio de tiempo.

En el año 1664, sucedió que Mary Tomkins y Alice Ambrose regresaron a Boston,
después de haber estado en Virginia,
donde por su religión no sólo habían sido puestas en el cepo,
sino azotadas con treinta y dos azotes cada una, con un látigo de nueve cuerdas,
y en cada cuerda tres nudos.
Estas mujeres fueron tan cruelmente tratadas,
que el primer latigazo les sacó la sangre e hizo que corriera por sus pechos.
Después de llegar a Boston,
Mary se enfermó tanto que pensó que estaba al borde de la muerte,
lo que hizo que Edward Wharton y Wenlock Christison llegaran de Salem a visitarla.
Después de un rato de haber llegado, entraron dos alguaciles,
y a pesar del débil estado de Mary, obligaron a todos a ir a la casa del gobernador.
Entonces, aunque Mary parecía estar mejorando un poco,
todavía estaba tan enferma que se desmayó y se cayó en el trayecto.
Pero uno de los alguaciles se quedó con ella hasta que recobró la consciencia,
y luego la llevó ante el gobernador,
donde también estaban el representante Bellingham y Thomas Daufort,
uno de los magistrados.
Allí se ordenó que azotaran a los cuatro,
pero como Mary estaba tan débil y podía morir en manos de ellos,
dieron órdenes de que a ella y a Alice no las azotaran en Boston,
sino en los pueblo de más allá. Esto habría sido
ejecutado de no ser por el coronel Temple,
quien, entrando, intercedió por tres de ellos y prevaleció. Pero entonces,
Edward Wharton, se convirtió en el objeto de la furia de ellos,
en quien descargaron su pasión, aunque no tenían nada de qué culparlo,
sino de haber llegado de Salem a Boston a visitar a su amiga enferma;
y bajo este supuesto crimen se dictó la siguiente orden judicial:

[.embedded-content-document.legal]
--

[.letter-heading]
A los alguaciles de Boston, Charlestown, Maiden y Lynn.

Se les requiere a cada uno de ustedes, tomar bajo custodia a Edward Wharton,
condenado por andar vagabundeando desde su lugar de residencia.
El alguacil de Boston debe azotarlo severamente con treinta azotes en su cuerpo desnudo.
Y luego, de alguacil a alguacil, deberán llevarlo hasta que llegue a Salem,
el lugar donde dice vivir; y al hacerlo esta será su orden.

[.signed-section-signature]
John Endicot.

[.signed-section-context-close]
Fechado en Boston el 20 de Junio, de 1664.

--

De acuerdo con esta orden judicial, E. Wharton (a quien se le llamaba vagabundo,
por ninguna otra razón que la de haber salido de su lugar
de residencia) fue conducido al mercado donde lo desnudaron,
y le ataron los brazos a la rueda de un gran cañón. Luego el alguacil John Loel,
le ordenó al verdugo que hiciera su obra severamente; lo cual hizo tan cruelmente,
que se testificó que los guisantes habrían cabido en los hoyos que los
nudos del látigo habían hecho en la carne de sus brazos y espalda.
Su cuerpo estaba hinchado y muy negro de la cintura para arriba.
Esta fue la conducta de los que, para disfrutar del libre ejercicio de su adoración,
habían salido de Vieja Inglaterra; y así trataron a un hombre que tenía buena reputación,
y que había vivido en aquellos lugares por más de veinte años, y que en una ocasión,
el propio gobernador había reconocido como su amigo (cuando
le había ayudado en un momento de necesidad) diciendo,
que si alguna vez estaba en su poder le pagaría; lo que hizo entonces,
pero ¡de qué manera tan inhumana y bárbara!
Que este gobernador Endicot había sido un hombre de escasa condición económica,
se desprende de una carta que le escribió poco tiempo después de la muerte Mary Dyar,
un tal John Smith,
porque Endicot no sólo había hecho que azotaran a su esposa severamente,
sino que también la había mantenido prisionera durante
todo el invierno separada de sus hijos,
y había estado colaborando con la elaboración de una orden para no dejar
que ningún hombre o mujer les llevara algo a los Cuáqueros encarcelados,
o llevaran algo de ellos, bajo la pena de ser multados con cinco libras la primera vez,
y con diez libras la segunda.
En esta carta John Smith decía:

[.embedded-content-document.letter]
--

¡Oh, mi espíritu está afligido por ti,
porque el amor que una vez vi en ti ha desaparecido!
Ahora queda en ti un espíritu de crueldad y de dureza de corazón hacia tus pobres vecinos,
con quienes has estado anteriormente muy obligado,
y por quienes fuiste ayudado en momentos de necesidad, cuando no tenías pan para comer.
¡Considera esos momentos y no los olvides,
ni olvides el amor que encontraste entre la gente pobre en el tiempo de tu necesidad!
¡Considera cuánto mal les has hecho y cómo les has pagado a algunos de ellos hoy;
y cómo caminas y actúas en contra de lo que antes profesabas!
Sí, he oído que dices que todos los ejércitos de la tierra
no podrían someter la lujuria en un hombre o mujer;
y ahora dictas sentencia de muerte sobre algunos,
porque no se pueden someter a tu voluntad, ni adorar como lo haces tú.

--

Pero regreso a Edward Wharton,
quien después de su paliza no fue conducido por el camino directamente a Salem,
sino por Charlestown, y así por todo el condado,
como si hubieran tenido en mente hacer de él un espectáculo.
Sin embargo,
el alguacil de Charlestown fue tan compasivo que lo hospedó en su casa y vendó sus heridas,
y al día siguiente lo llevó a su casa en Salem.
Desde entonces, el mencionado Wharton ha sido azotado severamente en otra ocasión;
pero paso por alto los detalles para evitar la redundancia.
Sin embargo, no puedo dejar de decir, que antes de ser azotado en Boston,
como se ha relatado,
se le dijo que si él le prometía al gobernador no
regresar más a la reunión de los Cuáqueros en Boston,
era probable que el gobernador lo dejara en libertad; a lo que Edward replicó:
"`Por nada del mundo.
Y amigos, tengo una espalda para presentarle al azotador,
y he sentido los crueles latigazos de ustedes antes de ahora,
y el Señor me ha hecho capaz de soportarlos.
Mientras yo permanezca en Su temor, no temo lo que se les permita hacerme.`"

El caso de una tal Anne Needham es también muy notable,
y daré una breve reseña de este.
Ella fue multada en Boston por ser parte del pueblo
llamado Cuáqueros y sentenciada a ser azotada,
lo que el alguacil, Thomas Roots, ejecutó con gran crueldad;
porque al ver que ella permanecía en silencio mientras la azotaba,
hizo lo que pudo con su látigo atormentador para hacerla llorar,
pero todos sus esfuerzos resultaron en vano.
Esto hizo que él dijera que los Cuáqueros eran personas duras de corazón; sin embargo,
este apelativo se ajustaba mejor a él y a todos los crueles perseguidores,
que se habían convertido en personas de corazón realmente duro hasta el más alto grado,
tanto así, que no sólo se habían desprendido de toda humanidad,
sino de todo verdadero sentido de piedad,
lo que probaré con ejemplos en los que algunos incluso fueron blasfemos.

Un tal Barlow, que anteriormente había sido predicador en Exeter,
y que después se había convertido en abogado, y al final, en alguacil,
se jactaba de que cuando iba a confiscar bienes para el pago de multas,
pensaba para sí mismo qué bienes eran los más útiles para los Cuáqueros,
y luego se los quitaba.
Con tales acciones alentaba a otros al vicio, porque cierto indígena,
que tomó un cuchillo de la casa de un inglés y se le dijo que no debía robar,
respondió que él pensaba así también,
pero que luego había visto lo que Barlow y los magistrados les hacían a los Cuáqueros.
Este Barlow se enriqueció en los días de Cromwell con el botín de los inocentes,
pero empobreció después de que el rey Carlos fue restaurado.
Esto hizo que Barlow dijera que él esperaba tener buenos tiempos otra vez,
pero luego se tomó la vergonzosa libertad de decir:
"`Pero creo que los Cuáqueros no me permitirán pasar necesidad.`"

En Hampton, el sacerdote Seaborn Cotton,
enterado de que un tal Eliakim Wardel había hospedado a Wenlock Christison en su casa,
fue con algunos de sus oyentes a la casa de Eliakim,
poniéndose a la cabeza de sus seguidores como un tenaz pastor, con un garrote en su mano.
Al verlo Wenlock en esa postura, le preguntó qué planeaba hacer con el garrote;
a lo que el sacerdote respondió: "`He venido a alejar a los lobos de mis ovejas.`"
Al preguntar Wenlock si esos que él guiaba eran sus ovejas, no recibió respuesta,
sino que fue llevado a Salisbury por ese grupo.
Este mismo sacerdote Cotton,
después de oír que el alcalde Shapleigh se había hecho Cuáquero, dijo: "`Lo lamento,
pero me esforzaré por convertirlo.`"
Y después, bebiendo en una casa cerca del río Piscataway,
y oyendo que el alcalde estaba allí en un almacén,
fue a buscarlo para hablar con él. Pero subiendo las gradas y vencido por la bebida,
se derrumbó, y tuvo una caída tan fuerte,
que el alcalde mismo llegó para ayudar a ese borracho conversor.

Cuando en una ocasión el gobernador Endicot le dijo a Edward Wharton,
que toda alma debía sujetarse al poder superior, E. Wharton le preguntó,
si lo que había erigido la imagen de oro y exigido que se postraran y la adoraran,
era el poder superior.
Endicot respondió: "`Sí.`" Entonces Edward le preguntó,
si el poder que había exigido que Daniel fuera arrojado al foso de leones,
por haber orado a alguien que no era el rey por un período de treinta días,
era el poder superior.
El gobernador dijo: "`Sí.`" La siguiente pregunta de Edward fue,
si los tres jóvenes que habían sido arrojados al horno de fuego,
habían hecho bien al no postrarse ni adorar la imagen de oro;
y si Daniel había hecho bien en orar a su Dios,
en contra de lo que el poder superior había ordenado.
El gobernador replicó: "`Sí,`" de nuevo.
Pero el secretario Rawson, viendo cómo el gobernador se había metido en un aprieto,
y a fin de ayudarlo a salir dijo:
"`Ellos obedecieron al poder superior sufriendo bajo él;`" a lo que Edward replicó:
"`Nosotros también.`"

A un tal Brian Pembleton, otro de los magistrados,
George Walton y su esposa Alice (que tenía la fama de ser una de
las mujeres más piadosas de los alrededores) le preguntaron,
qué era la unción que el apóstol Juan exhortaba que obedecieran los santos
en sus días. Pero la maldad de este Pembleton queda patente por la abominable
respuesta que dio--que Juan era o un tonto o un loco,
o que no sabía lo que decía. Y cuando se le preguntó
qué era esa luz que brillaba alrededor de Pablo,
lo que dijo en respuesta a la pregunta fue una blasfemia en grado sumo, porque respondió:
"`Por lo que sé, era la luz del diablo.`"

Joshua Scotaway, también uno de los magistrados,
le preguntó a Mary Tomkins en el tribunal en Boston, dónde vivía ella,
y Mary respondió con las palabras del apóstol: "`En Dios;
porque en Él vivimos y nos movemos y somos.`"
A esto Scotaway no dudó en decir: "`También los perros y los gatos.`"
En realidad no es de extrañar, que hombres así de oscurecidos en sus mentes,
se endurecieran tanto en su persecución como para gloriarse en ella.
De hecho, este era el caso de un tal Thomas Daufort, un magistrado de Cambridge,
que en la casa del gobernador en Boston,
puso su mano en el hombro de Wenlock Christison y le dijo:
"`Wenlock yo soy un hombre mortal y debo morir, y eso, en poco tiempo;
y debo presentarme ante el tribunal de Cristo,
y debo dar cuentas de lo que haya hecho en el cuerpo.
Y creo que mi mayor gloria en ese día será,
que yo haya dado mi voto para que seas fuertemente azotado en este momento.`"
Esto hizo que Wenlock dijera: "`Oh, perverso hombre,
si no tienes nada de que gloriarte en ese día,
sino en el derramamiento de la sangre del inocente,
y en los azotes a los siervos del Dios vivo, tu gloria será convertida en vergüenza,
y un ay será tu porción.`"

Pero ninguna exhortación, por extraordinaria que fuera,
parecía hacer mella en estos perseguidores.
Porque una vez una niña de trece o catorce años llamada Hannah Wright,
cuya hermana había sido desterrada por religión, fue movida por tal celo,
que llegando a la sangrienta ciudad de Boston desde Long Island a cientos de millas,
se presentó en el tribunal de esa ciudad y advirtió
a los magistrados que no derramaran más sangre inocente.
Esas palabras los impactó tanto, que al principio todos se sentaron en silencio,
hasta que el secretario Rawson dijo: "`¿Qué,
nos vamos a desconcertar por alguien como ella?
Vámonos a beber un trago.`"

Aquí vemos la religión de estos hombres, quienes en el pasado habían sido tan cuidadosos,
que no se unían al culto de la iglesia de Inglaterra, sin embargo,
puede que la razón por la que ellos habían caído en esta dureza de corazón haya sido,
porque después de haber sido convencidos en sus entendimientos de algunas
ceremonias supersticiosas que aún permanecían en la iglesia de Inglaterra,
no pusieran su luz en el candelero, ni testificaran fielmente contra esas cosas,
sino que prefirieran huir a América para esquivar la cruz y evitar los sufrimientos.
No obstante, estos hombres eran tan presuntuosos,
que decían que ellos eran la iglesia más pura sobre la tierra,
y que sus magistrados y predicadores eran hombres piadosos.
Pero, independientemente de lo que estos ingleses pensaran,
parecían ser peores que muchos otros,
porque en algunos lugares de América también vivían suecos,
quienes en cuanto a su adoración no eran menos despreciados por los ingleses,
que los samaritanos por los judíos, y sin embargo,
estos suecos atendían mucho mejor a los Cuáqueros cuando llegaban entre ellos,
que los ingleses.
De modo que, hacían ver que ellos los superaban en vida y conducta,
aunque no fueran tan acertados en su profesión religiosa.
Pero estos rígidos hombres de Nueva Inglaterra parecían
colocar una gran virtud en la severidad inflexible,
de la cual lo que sigue es un ejemplo:

Un holandés, en Ostender, cuyo nombre era John Lawrence,
fue tomado bajo custodia por adulterio y llevado ante el tribunal en Boston,
donde el gobernador John Endicot le preguntó si era culpable o no.
A esto el prisionero, que parece que hablaba muy poco inglés, respondió: "`No guilt.^
footnote:[Culpable, en español.]`" Sobre esto Endicot dijo de manera burlona: "`No gelt,
no hay dinero.`"
Porque '`gheld`" significa dinero en holandés. De este modo,
las palabras y el sentido del holandés fueron burlonamente distorsionadas,
y aunque no había una clara evidencia contra él, fue condenado a la horca.
Pero como el holandés negaba haber cometido un acto indebido, la ejecución fue aplazada,
mientras tanto,
los sacerdotes John Wilson y James Mayo fueron a la prisión para ver qué podían sacarle.
El sacerdote Mayo le dijo que su tiempo estaba cerca del fin y que debía morir en breve,
por lo que le pidió que confesara.
Entonces el prisionero le preguntó si él creía que
debía confesar algo que nunca había hecho.
Pero Mayo no desistió, sino que dijo: "`Confiesa, mi hijo, y dale gloria a Dios.`"
Sin embargo, el prisionero continuó negando el cargo y afirmó que estaba limpio.
"`Pero,`" dijo el sacerdote, "`no puedes estar limpio;
porque nuestro Señor y salvador dice,
que cualquiera que mire a una mujer para codiciarla,
ya adulteró con ella en su corazón`"--verdaderamente un
muy perverso uso de la Escritura para alcanzar un fin falso.
Pero el holandés viendo que ellos habían llegado a traicionarlo, fue cauteloso,
y al final, después de un largo y tedioso encarcelamiento,
encontró los medios para fugarse de la prisión y escapar
de los que se habían acostumbrado a ser despiadados;
por lo que a veces otros, además de los Cuáqueros, sentían el peso de su severidad.

Sucedió también, en la época en que William Leddra fue ejecutado,
que una tal Elizabeth Nicholson y sus dos hijos, Christopher y Joseph,
fueron culpados de la muerte de su esposo y padre, Edmund Nicholson,
quien fue encontrado muerto en el mar.
Y debido a la información que se había dado,
de que estas personas habían mostrado amor a los que ellos llamaban "`malditos
Cuáqueros,`" los tres fueron sacados de su vivienda en Salem y llevados
a Boston para ser juzgados por sus vidas por mera sospecha.
Pero, a pesar de que no se probó nada de asesinato contra ellos,
la madre fue multada con una gran suma,
y sus dos hijos fueron sentenciados a permanecer bajo las horcas por ciertas horas,
con las sogas en sus cuellos, y a ser azotados en el mercado,
lo cual fue ejecutado como correspondía. Y debido a que estos jóvenes no se amedrentaron,
el sacerdote Wilson que estaba al lado de ellos dijo: "`¡Ah,
maldita generación!`" Y se ordenó que fueran azotados también en Salem,
lo que se ejecutó tan despiadadamente,
que uno de los jóvenes se hundió o desmayó ante la tortura,
aunque después se levantó otra vez.

De esta manera vemos cómo estos perseguidores de Nueva Inglaterra
se habían endurecido hasta la excesiva severidad.
Pero antes de dejarlos, debo mencionar también la espantosa partida de algunos de ellos.

El último acto de la parte sangrienta del gobernador Endicot que encuentro,
fue la cruel paliza de Edward Wharton en Boston, relatada anteriormente,
porque había llegado el momento de que él dejara el escenario,
y diera cuenta de su extravagante severidad ante
otro tribunal además del de su sangrienta corte.
La medida de su iniquidad había llegado al colmo,
y fue visitado por una enfermedad repugnante, a tal punto,
que apestaba en vida y murió en la podredumbre,
siendo su nombre capaz de dar un mal sabor a través de las edades por venir.

Aún más notable fue la muerte del general de división Adderton,
quien cuando Mary Dyar fue colgada dijo burlonamente,
que ella "`colgaba como una bandera para que otros tomaran ejemplo.`"
Este hombre,
cuando Wenlock Christison fue condenado a muerte y advirtió
a los perseguidores de los justos juicios de Dios,
dijo presuntuosamente: "`Tú pronuncias ayes y juicios,
y los que te han precedido pronunciaron ayes y juicios,
pero los juicios del Señor Dios no han venido sobre nosotros
todavía.`" Pero ahora veremos la manera en que este hombre
fue golpeado por esos juicios y sirvió de ejemplo para otros.

Cierto día, después de haber ejercitado a sus soldados,
iba cabalgando orgullosamente sobre su caballo hacia su casa,
y llegó cerca del lugar donde solían soltar a los llamados
Cuáqueros de la carreta después de haber sido azotados.
En ese momento apareció una vaca y se cruzó en el camino,
ante lo cual su caballo se asustó y lo tiró, tan violentamente, que murió,
los ojos se salieron de su cabeza, el cerebro salió por su nariz,
la lengua se salió de su boca, y la sangre corría por sus oídos.
Así llegaron los juicios de Dios sobre él, de repente y sin darse cuenta.

John Norton, el sacerdote principal de Boston, también murió de repente.
Fue él quien promovió la ejecución de aquellos mártires que murieron en Boston,
como se ha relatado;
y cuando vio que los magistrados se detenían en la
ejecución de William Robinson y Marmaduke Stevenson,
los alentó a hacerlo, especialmente, porque John Winthrop, el gobernador de Connecticut,
trató seriamente de disuadirlos de derramar sangre inocente.
Fue también, el que no dudó en decir,
cuando William Brend fue azotado bárbaramente con una cuerda,
como se relató en su debido lugar:
"`Ya que William Brend se esforzó por maltratar nuestras
ordenanzas evangélicas hasta dejarlas llenas de moretones,
no es más que la justicia sobre él,
que sea golpeado hasta quedar lleno de moretones también.`" Pero
este Norton recibió entonces un golpe que lo hizo hundirse;
porque después de estar en su '`casa de adoración`' por la mañana,
y tener la intención de regresar en la tarde,
mientras caminaba en su casa soltó un gran gemido,
y apoyando su cabeza en la repisa de la chimenea, se le oyó decir:
"`¡La mano o los juicios de Señor están sobre mí!`"
Estas fueron sus últimas palabras y cayó muerto,
y habría caído en el fuego si no hubiera sido atrapado por alguien que estaba presente.
Podría dar más ejemplo de esta naturaleza, pero estos pueden ser suficientes.

Lo que he relatado de estas crueldades y mucho más,
fue publicado en forma impresa por aquel entonces,
para que el rey y el Parlamento de Inglaterra conocieran lo que pasaba en Nueva Inglaterra;
porque estas acciones habían salido a la luz pública y eran conocidas por el
país. Todo lo que se hizo en respuesta fue poner un color falso a su severidad,
y disfrazar los asuntos.
En realidad,
estos perseguidores de Nueva Inglaterra fueron afortunados
por no tener que lidiar con un pueblo vengativo,
de lo contrario se habrían visto envueltos en grandes dificultades;
pero los amigos de las víctimas encomendaban toda venganza a Dios,
aunque algunos de los magistrados en Inglaterra les
aconsejaban que demandaran a los perseguidores,
lo que según la ley habrían podido hacer.

Richard Bellingham, un feroz perseguidor,
y el gobernador de Boston después de John Endicot,
perdió sus facultades mentales diez años después,
y murió en esa condición. No mucho antes de esto, William Coddington,
gobernador de Rhode Island,
le escribió una carta en la que le hacía recordar los tiempos pasados.
Este W. Coddington fue uno de los primeros fundadores de las colonias en Nueva Inglaterra,
el primero que construyó una casa en Boston, y después, fue magistrado por siete años;
y cuando se levantó la persecución por primera vez,
él se declaró abiertamente contra ella.
El caso fue debatido por tres días en el tribunal,
pero el partido moderado era el más débil, y todos los sacerdotes se opusieron a él,
excepto un tal John Cotton, quien dijo que él recordaba cómo a su partida de Inglaterra,
él había predicado de Hechos 4:11,
mostrando a partir de ese texto que había una gracia interior que debía ser considerada,
y que por lo tanto, él no daría su voto para perseguir a los que afirmaban esa doctrina;
demostrando mucho más sentido de religión que los sacerdotes perseguidores.
Ahora,
aunque William Coddington era uno de los más grandes mercaderes o comerciantes en Boston,
y con toda probabilidad había adquirido grandes riquezas ahí,
al ver que su buen consejo no había sido escuchado,
resolvió dejar ese lugar e irse a vivir a otro.
Pero lo que sea que le haya dicho a Bellingham en su carta,
ese hombre permaneció endurecido como el Faraón, y se mostró cruel,
incluso cuando Mary Fisher y Anne Austin llegaron por primera vez a Boston,
cuando las trató de manera bárbara.

Sin embargo, debo mencionar algo notable aquí, a lo cual,
cuando lo escuché por primera vez, no le di completo crédito;
pero pensando que valía la pena hacer una estrecha investigación al respecto, la hice,
no sólo por medio de lo escrito,
sino también por el testimonio de las personas que habían sido testigos oculares,
o habían sido informadas por ellas.
De todos ellos recibí el mismo testimonio, a saber,
que la tierra alrededor de Boston había sido anteriormente un suelo muy fructífero,
que producía excelente trigo,
pero que desde el momento en que dicha ciudad se
había manchado con la sangre de los llamados Cuáqueros,
ni el trigo, etc., crecía hasta la perfección en un radio de veinte millas,
aunque el terreno hubiera sido arado y sembrado varias veces.
En algunas ocasiones lo que se sembraba se dañaba por pestes o insectos; en otras crecía,
pero escasamente producía más de lo que se había sembrado, y por eso,
no podía compensar los costos; y otro año,
la esperada cosecha se arruinaba por otro accidente.
Y como estas decepciones continuaron por muchos años,
las personas finalmente se cansaron de hacer más pruebas y dejaron la tierra sin cultivar,
a pesar de que a veinte millas de distancia de Boston,
el suelo permanecía muy fructífero, y los rendimientos del grano eran muy buenos.
Pero, tras tantos casos reiterados de falta de fruto cerca de la ciudad,
los ancianos que todavía viven y recuerdan los primeros tiempos,
en general concuerdan con la opinión de que esto es un juicio del cielo,
y una maldición sobre la tierra, por el derramamiento de sangre inocente en Boston.
Este relato lo he recibido de muchas personas creíbles,
aunque unas no sabían nada de las otras.
Sin embargo, lo que me dijeron concordaba tan bien en lo fundamental,
que no pude evitar creerlo, a pesar de que yo no tiendo a ser crédulo; por lo tanto,
he sido muy preciso en mi investigación de los hechos.
Así que ya no puedo cuestionar el asunto;
sino que me parece que es un castigo a esa sed de sangre que hace tiempo ha cesado.

En la isla de Barbados,
los llamados Cuáqueros también sufrieron mucho en manos de la gente,
al ser instigadas no poco por los sacerdotes Samuel Graves, Mathew Gray,
Thomas Manwaring y Francis Smith; ya que estos, al estar a menudo borrachos,
daban oportunidad para ser reprendidos.
Un tal Thomas Clark,
que una vez entró al lugar público de culto y exhortó a la audiencia
a que desistieran de la lascivia y temieran a Dios,
fue golpeado tan gravemente con palos, que cayó desmayado.
Después, el sacerdote Graves que había predicado esa mañana,
fue a la casa de Thomas Clark, arrastró a su esposa fuera de la puerta,
y le desgarró la ropa de la espalda.
Y el sacerdote Manwaring,
que había amenazado a T. Clark con procurar que se dictara
una ley por medio de la cual le cortaran las orejas,
una vez le escribió en una carta a Clark: "`Lamento que tu celo sobrepase tu moderación,
y que ahora un garrote deba sacar de ti lo que él diablo ha inspirado.`"
Esto fue,
porque T. Clark le había dicho que su conducta de
ebriedad no era apropiada para un ministro del evangelio.
Paso por alto otros tratos duros por los que pasó Clark,
aunque una vez fue puesto en el cepo y encarcelado.
Pero ahora dejo América y regreso a Inglaterra.
