== Capítulo 13

[.section-date]
1662

[.chapter-synopsis]
* Persecución severa en toda Gran Bretaña
* Crueldad practicada contra los Amigos en Londres
* Concejal Brown
* Intentos de impedir que los Amigos celebren sus reuniones
* Detenciones y encarcelamientos sin orden judicial
* Jovencitos enviados a Bridewell
* Crueldad contra D. Baker
* Preso golpeado en audiencia pública
* Conducta bárbara de R. Brown
* Testimonio de F. Howgill respecto a la continuidad de la Sociedad de Amigos
* Persecución en Southwark
* Juicio y sentencia de varios Amigos allí
* Juicio de J. Crook
* Acusación
* Sentencia de premunire
* El Cuáquero zapatero
* Condición de los Amigos confinados en Newgate
* Un impostor
* T. Ellwood
* Richard Hubberthorn muere en prisión.

Habiendo dejado América y regresado a Inglaterra,
vayamos a ver el estado de la persecución en Londres,
donde se propagaba entonces una furia violenta; aunque no sólo en esa importante ciudad,
eran gravemente perseguidos los llamados Cuáqueros.
Porque un poco antes de ese tiempo,
se había publicado en forma impresa un breve relato
de la persecución de este pueblo en toda Inglaterra,
firmado por doce personas,
en el que se mostraba que más de cuatro mil doscientos de los llamados Cuáqueros,
hombres y mujeres, estaban en prisión en Inglaterra,
y se indicaba el número de los encarcelados en cada condado,
ya fuera por frecuentar reuniones, negarse a tomar juramento, etc.
Muchos de ellos habían sido gravemente golpeados, o les habían arrancado la ropa,
o se las habían quitado, y algunos habían sido puestos en apestosos calabozos,
de los que algunos hombres dijeron que ellos no habrían puesto ahí a sus perros de caza.
Algunas prisiones estaban abarrotadas, tanto de hombres como de mujeres,
de modo que no había suficiente espacio para que todos se sentaran a la vez;
y en Cheshire,
sesenta y ocho personas fueron encerradas de esta manera en una pequeña
habitación--señal evidente de que ellos eran un pueblo inofensivo,
ya que tal número no opuso resistencia, ni hizo uso de la fuerza.
Muchos se enfermaron por esos maltratos, y no pocos murieron en tales cárceles;
porque no se tomaba en cuenta la edad, ni el género;
ni siquiera se salvaron ancianos de sesenta,
setenta y más años. La mayoría de ellos eran comerciantes, tenderos y agricultores,
por lo que fueron reducidos a la pobreza; y además,
les confiscaron sus bienes por no ir a la iglesia (así llamada), o no pagar los diezmos.
Muchas veces se les hacía permanecer en prisiones sobre suelos fríos y asquerosos,
sin que se les permitiera tener paja; y a menudo se les mantenía varios días sin comer.
No es de extrañar, por tanto,
que muchos murieran a causa de estos encarcelamientos tan duros.

En esa época estaban encarcelados en Londres y sus suburbios,
no menos de quinientos de los llamados Cuáqueros.
Algunos fueron puestos en huecos tan angostos,
que cada persona apenas tenía comodidad para acostarse,
y a menudo se permitía que los delincuentes les robaran sus ropas y dinero.
Muchos de los que no estaban encarcelados, sufrían penurias en sus reuniones,
especialmente en la casa de reunión en Londres, conocida por el nombre de Bull y Mouth.
Allí, las bandas militares entrenadas llegaban con frecuencia armadas con mosquetes,
picos y alabardas,
siendo conducidas por un oficial por orden de la magistratura de la ciudad;
y precipitándose en la reunión de manera enfurecida,
comenzaban a golpear a los que estaban reunidos esperando en el Señor,
por lo que muchos eran gravemente heridos, algunos caían desmayados,
y algunos eran golpeados tan violentamente que no vivían mucho tiempo después de esto.

Entre estos estaba un tal John Trowel, quien resultó tan golpeado y magullado,
que murió pocos días después. Por tanto,
sus amigos consideraron apropiado llevar el cuerpo al mencionado lugar de reunión,
para que permaneciera expuesto por algunas horas y fuera visto por todos.
Esto suscitó la compasión y piedad entre muchos de los habitantes de Londres,
pues el cadáver, que por la golpiza había quedado como gelatina,
estaba negro e hinchado de forma espantosa.
Esto dio lugar a que algunos mandaran a llamar al juez de instrucción, y este, al llegar,
constituyó un jurado de vecinos y les encargó, según su oficio,
que hicieran una verdadera investigación bajo juramento,
y presentaran lo que encontraran como causa de su muerte.
El jurado, tras ver el cadáver,
y teniendo con ellos a uno o dos cirujanos para conocer su juicio con respecto a esto,
se retiró finalmente sin dar su veredicto,
y sólo les solicitaron a los amigos que sepultaran el cadáver,
lo que seguidamente se hizo esa misma tarde.
Y aunque el jurado se reunió varias veces con el forense, y realizó muchas consultas,
nunca dieron un veredicto sobre la causa de la muerte;
aunque estaba suficientemente claro que el hombre
había sido asesinado por una violenta paliza.
La razón que dieron algunos para no dar un veredicto fue,
que como John Trowel había sido golpeado y dejado inconsciente,
en medio de una gran multitud en confusión,
ningún hombre en particular podía ser acusado como su asesino.
Y si se daba el veredicto de que la persona fallecida había sido asesinada,
y sin embargo, no se podía acusar a ninguna persona en particular,
entonces la ciudad se exponía a una gran multa, a voluntad del rey,
por permitir que se cometiera un asesinato de este tipo durante el día;
porque este crimen no había sido cometido en un rincón, sino en un lugar público,
y no habían logrado apresar al asesino, sino que lo habían dejado escapar.

Mientras tanto, los amigos del fallecido no dejaron de dar aviso público del hecho,
y también enviaron una carta al alcalde, la cual publicaron después en forma impresa,
junto con un relato de este sangriento asunto.
En la carta se decía: "`Es de suponer que has oído de esto,
porque no fue hecho en la noche, sino en pleno día; ni de forma repentina,
inconsciente o accidental, sino intencionadamente y por un período de tiempo;
y no en un rincón, sino en las calles de la ciudad de Londres;
todas estas circunstancias agravan enormemente este asesinato,
para la vergüenza e infamia de esta famosa ciudad y su gobierno.`"

Cierta persona que repartió algunos de estos relatos impresos fue encarcelada como pago.
No obstante, otra persona llevó uno al rey y le dijo como se habían hecho las cosas;
ante lo cual el rey dijo:
"`Te aseguro que no fue por mi consejo que alguno de tus amigos haya sido asesinado;
debes hablarles de esto a los magistrados de la ciudad, y procesar la ley contra ellos.`"
Esta afirmación del rey no tardó en ser publicada en forma impresa,
pero la violencia siguió prevaleciendo,
porque la persona que fue detenida por repartir los mencionados libros,
fue enviada a prisión por la orden especial del concejal Richard Brown.
Y puesto que en esta obra se hará mención varias veces de Richard Brown,
me da la oportunidad de decir algo del tipo de hombre que era.
En tiempo de Cromwell había sido un fiero opositor de los monárquicos,
especialmente en Abington, no muy lejos de Oxford; por este error,
ahora se esforzaba en hacer compensación persiguiendo
violentamente a los inofensivos Cuáqueros.
Era un hombre bien parecido y podía cometer crueldades con una sonrisa en su rostro;
pero se presentarán más de sus acciones en adelante.

Cuando los llamados Cuáqueros vieron que no podían obtener justicia,
dejaron el asunto del asesinato de personas en paz;
porque en ese momento el sufrimiento era su porción, y por eso dejaron su causa a Dios.
Con frecuencia los soldados les impedían entrar en sus casas de reunión,
pero ellos no se marchaban, sino que se ponían delante del lugar, y generalmente,
uno u otro de sus ministros se subía en una banca, o en un lugar alto,
y predicaba con valentía. De este modo aumentó su número rápido,
porque a veces tenían más oyentes de los que habrían tenido de otra manera.
A veces, derribaban pronto al que estaba predicando,
lo que le daba oportunidad a otro para ponerse de pie y predicar; y así, con frecuencia,
cuatro o cinco, uno tras otro, eran llevados como ovejas inocentes,
y conducidos a prisión con otros de sus amigos, a veces cuarenta o cincuenta a la vez.

Esto me hace recordar lo que le oí decir a mi madre Judith Zinspenning,
quien el año siguiente fue a Inglaterra (con William Caton y su esposa,
quienes vivían en Ámsterdam) a visitar a sus amigos ahí. Al llegar
a Londres y dirigirse con otros a la reunión en Bull and Mouth,
se les negó la entrada, así que se reunieron en la calle,
donde vio cómo era derribado un predicador tras otro al grito de un oficial que decía:
"`¡Alguacil, llévatelo!`"
Así se llevaron a varios, y el alguacil también se acercó a ella,
y al darse cuenta por su vestido que era holandesa,
le tiró de la manga y dijo con sorpresa: "`¡Qué,
una cuáquera holandesa!,`" pero no se metió más con ella.

La celebración de las reuniones en las calles se convirtió así en una costumbre en Inglaterra;
porque los llamados Cuáqueros estaban persuadidos de que el ejercicio
de su culto público era un deber del que ningún hombre podía eximirlos,
y creían que Dios requería de sus manos la ejecución de este servicio.
Y al reunirse en las calles de esta manera, ocurría a veces que más de uno, sí,
hasta tres o cuatro, predicaban al mismo tiempo, uno en un lugar y otro en otro,
lo cual no habría podido realizarse convenientemente en sus lugares
de reunión. De este modo conseguían una gran cantidad de oyentes,
entre los cuales a veces se encontraban hombres importantes,
quienes al pasar en sus carruajes, ordenaban a sus cocheros detenerse.
De esta manera descubrieron, que en verdad había una gran cosecha,
y su iglesia creció bajo los sufrimientos.
En esa época de prueba fueron bastante purificados de escoria,
ya que la prueba era demasiado ardiente para los que no eran sinceros;
porque en esos tiempos, ellos estaban en peligro de ser encarcelados,
de ser golpeados hasta quedar lisiados, o incluso morir, por asistir a sus reuniones;
pero esto no pudo apagar el celo de los rectos.

Ahora, el que un predicador fuera llevado y otro se pusiera de pie,
se convirtió en algo común en Inglaterra, y duró mucho tiempo después de esto,
como yo mismo lo he presenciado.
Y cuando no había más predicadores hombres presentes,
algunas veces se levantaba una mujer y ministraba en la reunión. De hecho,
algunos no eran más que niños en cuanto a su edad,
que dotados con un celo varonil animaban a sus amigos a la perseverancia.
Mientras tanto, también se encarcelaron a muchos, sin que estuvieran en una reunión;
pues algunos fueron detenidos por el mero hecho de decir algo a favor de sus amigos.
Tal fue el caso de Rebecca Travers, quien fue a ver al teniente de la Torre,
y le pidió tener compasión de algunos que estaban
encarcelados por haber asistido a las reuniones.
Pero el teniente se enojó por ello, y mientras ella se iba,
uno de los guardas de la cárcel le dijo unas palabras groseras,
por lo que ella lo exhortó a hacer el bien en su puesto,
mientras fuera la voluntad de Dios que lo tuviera.
Pero él se ofendió tanto, que se volvió al teniente y se quejó diciendo,
que ella había hablado de traición, y por eso fue detenida y enviada a prisión.

A veces, los soldados que eran rudos,
eran alentados a la crueldad por oficiales que no eran ni un poco mejor,
ya que ellos mismos a veces ponían violentamente sus manos sobre personas pacíficas.
Entre estos estaba el antes mencionado concejal Richard Brown,
quien antes había sido general de división bajo el gobierno de Cromwell,
y ahora se comportaba con una ferocidad tan escandalosa,
que incluso los comediantes no dudaban en exponerlo
haciendo alusiones a su apellido Brown,^
footnote:[Marrón en español.]
diciendo: "`El diablo es marrón.`"

También se publicó un libro,
en el que se exponían a la vista pública muchos de
sus viles abusos junto con su conducta fiera;
este libro fue dedicado a él con esta pequeña epístola:

[.embedded-content-document.letter]
--

[.salutation]
Richard Brown,

Si tú no estás sellado ya para la destrucción,
y si el arrepentimiento no está completamente oculto a tus ojos,
qué el Señor te convierta y te perdone por tus duros y crueles tratos hacia nosotros.
Deseamos tu arrepentimiento antes que tu destrucción. Qué el Señor Dios
del cielo y de la tierra dicte un juicio definitivo entre tú y nosotros,
para que toda la tierra sepa si tu causa contra nosotros, o nuestra causa,
es justa delante de Él, quien es el único Juez justo.

--

El mencionado libro, aunque publicado sin el nombre del autor,
no sólo fue enviado a Brown,
sino que también se les entregaron unos treinta ejemplares
al alcalde y a los alguaciles de Londres,
para que supieran lo que se hacía bajo su autoridad; porque algunos,
aunque no estaban autorizados, al ser favoritos de la corte,
se atrevían a actuar contra los Cuáqueros en cualquier
forma en que los impulsara su malicia.
Entre estos estaba un tal Philip Miller, quien, aunque no era un oficial,
en el mes llamado Mayo de este año,
entró en una reunión del mencionado pueblo en John`'s Street,
en la parroquia de Sepulchers, en Londres, sin ningún mandato u orden judicial.
Y con un bastón en su mano,
le ordenó a la chusma que lo acompañaba que detuvieran a quien quisieran,
y luego buscó a un alguacil a quien forzó, mediante amenazas, a ir junto con él,
y así cinco personas fueron detenidas, entre estas John Crook,
de quien se hará mención en breve.
Algunos días después,
este Miller llegó de nuevo al mencionado lugar y golpeó a varias personas con su bastón,
porque no se marchaban a su orden,
y luego les encargó a los alguaciles que había llevado con él,
que detuvieran y tomaran bajo custodia a quien quisieran.

Hacia finales de dicho mes, un Primer-día,
un tal capitán Reeves y algunos soldados con mosquetes y espadas desenvainadas,
entraron violentamente en la reunión en Bull and Mouth,
donde derribaron al que estaba predicando,
y en seguida agarraron a otro que le pidió a Reeves
que mostrara la orden judicial para sus acciones.
A esto Reeves replicó que no lo haría en ese lugar;
pero luego se supo que no pudo mostrarla, porque no se le había concedido ninguna orden.
Sin embargo,
hizo que sus soldados se llevaran unas cuarenta personas
(algunas de las cuales no estaban en la reunión,
sino que habían sido recogidas en las calles) y que las condujeran a Paul`'s Yard,
donde las mantuvieron hasta que terminó el culto público.
Entonces,
el concejal Richard Brown entró al lugar donde estaban custodiados los prisioneros,
y con gran rabia y furia puso las manos primero sobre un anciano,
y lo tiró al suelo dos veces por el ala de su sombrero,
por lo que lo perdió. Luego lastimó a otro de la misma manera,
mientras un soldado lo golpeaba con una pistola en la cabeza desnuda.
Brown trató a otros dos de la misma manera,
y luego los envió a todos a la prisión de Newgate, custodiados por soldados.

Ese mismo día algunos soldados llegaron a la reunión en la calle Tower,
y sin ninguna orden se llevaron a veintiuna personas de los llamados Cuáqueros,
y las condujeron a Exchange, donde las retuvieron por algún tiempo,
y luego las llevaron ante el mencionado Richard Brown, quien de la manera más furiosa,
golpeó a unas y pateó a otras.
Al ver que Richard golpeaba a un hombre con su puño por la cara,
y la pateaba en la espinilla, hizo que uno de los prisioneros dijera: "`¿Qué, Richard,
te vas a convertir en un asesino?
No lo hacías así cuando yo era un soldado bajo tu mando en Abingdon.
Porque entonces me ordenabas a mí y a otros,
que registráramos las casas de la gente en busca de pasteles y carne asada,
porque celebraban la navidad como un tiempo sagrado,
y llevábamos a esas personas como prisioneras a la guardia,
por observar esas supersticiones.`"
Porque en aquel tiempo bajo Cromwell, Brown había sido un hombre tan estricto,
que se había propuesto erradicar esas costumbres supersticiosas de la iglesia;
aunque hay motivos para dudar si su corazón era sincero en ese aspecto.
No obstante,
un celo tan ciego era inadecuado para convencer a la gente de su superstición; y Brown,
sabiendo bien que por su anterior comportamiento
había contrariado a los de la iglesia de Inglaterra,
ahora se esforzaba por enmendarlo mediante su fiera
brutalidad contra los inofensivos Cuáqueros,
y así ganarse el favor de los eclesiásticos y de los asistentes del rey.
Uno de los familiares de Brown, al oír lo que le decían replicó:
"`Aquí tenemos un soldado de Abingdon!`"
A lo que Brown contestó:
"`¡Es un bribón!,`" y luego lo golpeó con su puño bajo la barbilla,
lo que hizo que otro prisionero dijera: "`¿Qué, magistrado y atacante?`"
A quien Brown, con ambas manos tiró al suelo por el ala de su sombrero,
y luego ordenó a los soldados que los cogieran a
todos y los llevaran a la prisión de Newgate.

Un Primer-día, en el mes llamado Junio,
una compañía de soldados entró a la reunión en Bull and Mouth con picos,
espadas desenvainadas, mosquetes y antorchas, como si fueran a luchar;
aunque sabían muy bien que sólo iban a encontrar personas inofensivas.
Lo primero que hicieron fue derribar al hombre que estaba predicando,
a quien sacaron a rastras de la reunión,
regocijándose como si hubieran obtenido una gran victoria.
Luego lo llevaron al guarda principal en Paul`'s Yard y regresaron a Bull and Mouth,
donde detuvieron a algunos más, y también los llevaron a Paul`'s Yard.
Después de algunas horas llevaron a estos prisioneros a la casa del mencionado Brown,
y él, preguntándoles los nombres y oyendo el de John Perrot, dijo: "`Cómo,
tú has estado en Roma para socavar&hellip;,`" pero recordándose dijo:
"`para convertir al papa.`"
A lo que Perrot le dijo que había sufrido en Roma
por el testimonio de Jesús. Con lo cual,
Brown contestó: "`Si hubieras convertido al papa a tu religión,
me gustaría mucho menos de lo que me gusta ahora.`"
A esto Perrot replicó: "`Pero le habría gustado más a Dios.`"
Después de un poco más de conversación, Brown los envió a todos a Newgate.

De esta manera eran perturbadas las reuniones de los llamados Cuáqueros en ese tiempo,
de lo cual podría dar, si fuera necesario, muchos más ejemplos.
Una vez, un tal Cox, tonelero de vinos, entró con algunos soldados a una reunión, donde,
tras una gran violencia, capturaron a dos hombres de los llamados Cuáqueros,
a quienes golpearon muy fuertemente por rehusarse a ir con ellos,
aunque no mostraron ninguna orden para ello.
Finalmente, los soldados los obligaron con mosquetes a entrar en Paul`'s Yard,
y cuando los tumbaron al suelo,
arrastraron a uno por los talones sobre su espalda de manera salvaje.
Hecho esto, se le oyó decir al citado tonelero,
que iría y buscaría una copa de vino porque esos demonios lo habían cansado.
Luego fue a otro lugar de reunión de este pueblo,
donde también se comportó muy perversamente.
Y cuando le pidieron la orden, respondió sacando su espada y diciendo:
"`Esta es mi orden.`"
Parece que así se congraciaba con Brown, quien entonces gozaba del favor de la corte,
había sido nombrado caballero,
y poco después había sido escogido para ser alcalde de Londres.

La furiosa conducta de Richard Brown,
también animaba a los soldados a cometer toda clase de daños; tanto así,
que cuando se les preguntaba qué orden tenían para sus actos,
uno levantando su mosquete dijo: "`Esta es mi orden.`"
Estos soldados tampoco respetaban edad,
porque sacaron de una reunión en Mile-end a dos jovencitos,
uno de unos trece años y el otro de unos dieciséis.
Y cuando fueron llevados ante el teniente de la Torre,
uno de los presentes dijo que suponía que no tenían dieciséis años, y que por lo tanto,
no podían ser castigados por la ley.
Pero otro respondió: "`Son lo suficiente mayores para ser azotados,
y deben serlo por su religión.`"

Así que fueron enviados a Bridewell,
donde por dos horas les pusieron las manos en el cepo,
y quedaron tan apretadas que se les hincharon las muñecas.
Les hicieron esto porque se rehusaron a trabajar,
estando persuadidos de que no merecían ser tratados de esa manera.
Tampoco comían nada por cuenta de la citada casa de trabajo.
Estos muchachos, aunque estuvieron bastante tiempo en esa prisión, permanecieron firmes,
regocijándose de haber sido considerados dignos de sufrir por el nombre
del Señor. También escribieron una carta a los hijos de los amigos,
exhortándolos a ser fieles en dar testimonio del Señor contra toda maldad e injusticia.

Unos días antes de este tiempo,
Thomas y John Herbert (viviendo en Londres) junto con otros mosqueteros,
entraron con sus espadas desenvainadas en algunas viviendas
privadas y quebraron dos o tres puertas (porque en esa época,
cuando se veía que algunas personas entraban en una casa,
aunque sólo fuera para visitar a sus amigos, eran llamadas reuniones).
Sucedió que estos rudos individuos encontraron en una casa a cinco personas juntas,
uno de los cuales era William Ames, quien había llegado ahí desde Holanda,
y otro era Samuel Fisher.
Y cuando se les preguntó qué orden tenían, levantaron sus espadas y dijeron:
"`No nos pidan una orden; esta es nuestra orden.`"
Con lo cual, se llevaron a estas personas por la fuerza y las condujeron a Paul`'s Yard,
donde se convirtieron en el hazmerreír de los soldados.
De ahí fueron trasladados a Exchange,
donde no encontraron un mejor recibimiento por parte de los rudos soldados;
y de ahí fueron conducidos a la casa de Brown en Ivy-lane.
Cuando Brown vio los prisioneros,
los mandó a Bridewell con una orden judicial para que fueran sometidos a trabajos forzados.
Pero más tarde,
al reconsiderar el asunto y encontrar que su orden judicial no se basaba
en la justicia (porque estas personas no fueron capturadas en una reunión),
a la mañana siguiente envió otra orden judicial,
en la que se les acusaba de reunirse ilegalmente para adorar.

Así entonces, estas personas fueron enviadas a la prisión de Bridewell,
donde se les obligó a golpear cáñamo; y fueron tratados tan severamente,
que William Ames se enfermó y fue liberado estando al borde de la muerte;
pues al alegarse que era de Ámsterdam (donde había vivido
la mayor parte del tiempo por años de manera sucesiva),
parece que no querían que muriese en prisión como
había sucedido con algunos de sus amigos.
Los otros, tras seis semanas en Bridewell,
fueron presentados en las sesiones del tribunal en Old Bailey,
pero en lugar de ser juzgados por lo que ya habían sido acusados,
fueron obligados a tomar el juramento de lealtad como único
asunto del tribunal (según lo que dijo el secretario adjunto).
Los prisioneros demandaron entonces,
que se leyera la ley en virtud de la cual se les requería dicho juramento.
El tribunal prometió hacerlo, pero en lugar de eso,
le ordenaron al secretario que leyera sólo la forma del juramento mismo,
pero no permitieron que leyera la ley por la que se imponía el juramento.
Y antes de que los prisioneros hubieran declarado su disposición de tomarlo o rechazarlo,
se ordenó que fueran llevados, lo que hicieron los oficiales con tal violencia,
que lanzaron a algunos de ellos sobre piedras.
Esto hizo que Samuel Fisher dijera: "`Tengan en cuenta, pueblo,
que todavía no hemos rechazado tomar el juramento,
y que la corte ha rehusado cumplir su promesa,
la cual hicieron justo ahora delante de todos ustedes, de leer el estatuto del juramento.
Si actos como este prosperan,
debe ser porque no hay Dios en ninguno de sus pensamientos.`"
Pero esto no fue considerado;
y los prisioneros fueron enviados a la prisión de Newgate sin ninguna justicia.

Entre estos también estaba un tal John Howel,
quien había sido enviado por el concejal Brown a trabajar en Bridewell,
porque estando frente a él, no le había dicho inmediatamente su nombre.
Y cuando se le preguntó en la corte la razón por la que no había dicho su nombre,
respondió que había sido golpeado y lastimado en presencia
de Richard Brown cuando lo llevaron delante de él. Brown,
que también estaba en el tribunal, le preguntó bruscamente: "`¿Cómo te han maltratado?`"
Howel respondió: "`Derramaron mi sangre delante de ti;
lo cual no debería ser hecho en presencia de un juez de paz.`"
Pero Brown cada vez más temerario replicó: "`Detén tu parloteo,
o se hará lo mismo en presencia del tribunal.`"

Hacia mediados del verano, regresó a Inglaterra Daniel Baker (quien, como se ha relatado,
había estado en Malta), y unas dos semanas después de su arribo,
él y otros cuatro fueron capturados por una banda de soldados
en la reunión de Bull and Mouth y llevados a Paul`'s Yard,
donde después de ser retenidos ahí algunas horas,
fueron trasladados a la prisión de Newgate.
Por la noche fueron llevados delante del concejal Brown,
a quien Baker con mansedumbre dijo:
"`Que el temor de Dios y Su paz sean puestos en tu
corazón.`" Pero Brown se echó a reír y dijo:
"`Yo preferiría oír a un perro ladrar;`" y usando más expresiones de burla
acusó a Baker y a los otros de transgredir la ley del rey al reunirse.
A esto Baker dijo:
"`A los siervos de Dios en los días de los apóstoles
se les ordenó no hablar más en el nombre de Jesús;
y ellos respondieron, y yo también,
que era necesario obedecer a Dios antes que a los hombres,
juzga tú.`" También mencionó el caso de los tres jóvenes en Babilonia y el de Daniel,
quienes no obedecieron los decretos del rey.
Pero Brown se enfureció tanto que les ordenó a sus
hombres que golpearan a D. Baker en la cara.
Ellos lo hicieron,
y tirándolo cuatro o cinco veces al suelo lo golpearon con sus
puños y le retorcieron el cuello como si hubieran querido asesinarlo.
Esto lo hicieron para complacer a Brown,
mostrándose dispuestos a hacer cualquier servicio, por abominable que fuera.
Y Baker, haciendo referencia a sus viajes,
señaló que incluso los turcos y paganos aborrecerían tales actos de brutalidad.
Sus compañeros prisioneros también fueron lastimados por
Brown y luego enviados a la prisión de Newgate de nuevo.

Después de algunos días fueron llamados a las sesiones del tribunal,
donde se les leyó su acusación, en la que como otras en tales casos,
en general decía que "`los prisioneros bajo el pretexto de realizar un culto religioso,
en contra de las leyes del reino de Inglaterra,
ilícita y tumultuosamente se habían reunido y congregado
para gran terror del pueblo de su majestad,
y para el disturbio de la paz del rey, en desprecio al mencionado rey y su ley,
y para el mal ejemplo de todos los demás,`" etc.
La acusación fue leída y no apareció ningún testigo en contra de los prisioneros,
excepto Brown, quien también estaba sentado en el tribunal.
Por lo tanto, se les presentó el juramento, como trampa habitual,
pues era suficientemente sabido que su profesión no les permitía jurar.
Como ellos se negaron a hacerlo fueron enviados de regreso a prisión,
donde permanecerían hasta que estuvieran dispuestos a prestar el juramento.

Si yo quisiera dejar por escrito todos los casos similares a este que han sucedido,
encontraría más trabajo del que podría realizar.
Porque estas trampas con el juramento se habían vuelto tan comunes,
que algunos eran capturados en las calles y llevados ante un juez de paz,
sólo para que este les presentara el juramento, y en el caso de que se negaran,
fueran enviados a prisión,
aunque esto estaba directamente en contra del estatuto de la Carta Magna,
la cual expresamente dice: "`Ningún hombre libre serán capturado, o encarcelado,
o desposeído de sus propiedades o libertades, sino por la ley de la tierra.`"
Pero esto no era considerado por Richard Brown, que hacía lo que quería;
quien entonces prevalecía por la fuerza y la violencia.
Y a veces, cuando los prisioneros eran llevados al tribunal por asistir a reuniones,
se les negaba la libertad de justificarse a sí mismos;
sino que su porción era ser intimidados y turbados.

Sucedió en una ocasión,
que un prisionero que antes había sido soldado bajo el mando de Richard Brown,
al ver que no se observaba justicia ni equidad, lo llamó diciendo:
"`Tú no eres apto para sentarte en el tribunal,
porque tú hiciste que un hijo colgara a su padre en Abingdon,
y puedo probar que eres un asesino.`"
Esta atrevida afirmación causó cierta conmoción en el tribunal,
y Brown no negó el asunto en la corte, ni se exculpó de ella.
Sin embargo,
los otros prisioneros Cuáqueros no aprobaron la censura de este prisionero contra Brown,
sino que señalaron, que aunque el hecho fuera cierto,
no estaban para reprochar a ningún magistrado que se sentaba en el tribunal,
cuyo lugar y oficio respetaban y honraban.
No obstante,
no encuentro que Brown haya enjuiciado (por este motivo) al hombre que habló tan audazmente,
aunque por lo demás, él hacía lo que deseaba,
sin temor a que sus compañeros magistrados se lo reprocharan,
como aparece en el siguiente ejemplo.

Cierta persona,
que había sido sacada por los soldados de una reunión de manera muy violenta y abusiva,
dijo en el tribunal que su negativa a acompañar a los soldados había sido,
porque ellos no le habían mostrado ninguna orden judicial para su captura;
ya que por lo que sabía, ellos habrían podido ser ladrones o asesinos,
con quienes no estaba obligado a ir.
Pero Brown, quien estaba a favor de la violencia, le dijo:
"`Si te hubieran arrastrado por todas las cunetas de la calle,
sería lo que te habrías merecido, si te hubieras negado a ir con ellos.`"
Esto lo dijo de manera tan furiosa, que uno de los prisioneros le dijo:
"`Tú has recibido muchas advertencias y visitas del amor de Dios,
pero las has despreciado; por tanto, ten cuidado de ser sellado para la ira de Dios.`"
Entonces,
uno de los carceleros se acercó con su bastón y golpeó
a algunos de los prisioneros tan fuertemente,
que varios quedaron muy heridos; y algunos informaron que Brown había gritado:
"`¡Noquéenlo!,`" aunque otros (mitigando un poco)
declararon que sus palabras habían sido:
"`¡Derríbenlo!`"
No obstante, lo primero parece más probable,
porque los golpes fueron tan fuertes que algunos de los espectadores gritaron:
"`¡Asesinato, asesinato!,`" y preguntaron:
"`¿Vas a permitir que un hombre sea asesinado en el tribunal?`"
Con lo cual, uno de los alguaciles bajó en persona de su asiento para detener la paliza.
Pero Brown estaba tan terriblemente lleno de ira, que les dijo a los prisioneros:
"`Si alguno de ustedes es asesinado,
su sangre caerá sobre su propia cabeza;`" y el verdugo,
que estaba de pie con su mordaza en la mano,
amenazó a los prisioneros con amordazar a cualquiera que dijera algo.
Y así, la inocencia se vio forzada a darle paso a la violencia.
Y una vez, ante la pregunta común, "`culpable o no culpable,`" uno respondió:
"`Niego ser culpable,`" y "`puedo decir que no soy culpable,`" y en latín:
"`__Non reus sum.__`"
Aun así, fue sentenciado como mudo y multado en concordancia,
aunque las palabras que había dicho claramente significaban no culpable, sin bien,
no las había expresado en los términos exactos.
Parecía, entonces, que estaban en pro de oponerse a los Cuáqueros en todos los aspectos.

Mencionaré aún algunos casos más de la brutalidad de Brown antes de dejarlo.
A otro, a quien se le demandó que respondiera a su acusación,
"`culpable o no culpable,`" y no responder inmediatamente
por pensar un momento en cómo hablar de manera segura,
Brown burlonamente dijo: "`Tendremos una revelación en breve.`"
A esto el prisionero dijo: "`¿Por cuánto tiempo más te vas a oponer al inocente?
¿Hasta cuándo perseguirás a la semilla justa de Dios?`"
Pero mientras hablaba,
Brown empezó a gritar indecentemente en el lenguaje
de las mozas que anuncian por las calles:
"`¡Ostras, Ostras! ¿Quieren ostras?
¿Quieren manteca?`"
Y cuando un prisionero dijo en el tribunal que por su consciencia
no podía dejar de reunirse con el pueblo de Dios,
Brown burdamente replicó: "`¡Consciencia, mi abuela!`"
Y cuando el concejal Adams hablándole a uno de los prisioneros dijo:
"`Lamento verte aquí.`" "`¡Lamento!,`" dijo Brown, "`¿cómo que te lamentas?`"
"`Sí,`" dijo Adams, "`él es un hombre sobrio.`"
Pero Brown, que no soportó oír eso replicó:
"`Nunca ha habido un hombre sobrio entre ellos;`" hablando de los Cuáqueros.
Los espectadores que le prestaban atención a él, desaprobaban mucho su conducta.
Pero él parecía estar muy endurecido; porque en cierto momento,
estando dos personas en un juicio por el robo de una casa, les dijo:
"`Ustedes son los más grandes bribones de Inglaterra, excepto por los Cuáqueros.`"

Sucedía a veces, que los prisioneros eran llevados al tribunal sin haber sido acusados,
y cuando preguntaba, qué habían hecho y deseaban que se les hiciera justicia,
Brown (al no tener una acusación contra ellos) a menudo gritaba:
"`¿Prestarán juramento?`"
Y cuando ellos respondían diciendo:
"`No podemos jurar por un asunto de consciencia,`" eran condenados como transgresores,
aunque tales procedimientos estaban directamente en contra de la ley.
Pero en ese tiempo, eso no parecía ser considerado.

No obstante, un tiempo antes de esto, sucedió que en Thetford, en el condado de Norfolk,
el juez Windham se mostró más justo en un caso similar,
porque él reprendió severamente a los jueces del tribunal,
pues no sólo habían enviado a prisión a algunas personas,
sino que también las habían hecho comparecer ante el tribunal
cuando no se había presentado ningún acusador contra ellas.
Pero Richard Brown hacía lo que le daba la gana, y se mostraba más furiosamente perverso,
cuando era llevado delante de él un prisionero con su sombrero puesto.

Un tal John Brain, capturado en la calle, y no en una reunión,
fue llevado por algunos soldados delante de Brown.
Al verlo con su sombrero puesto,
Brown ordenó que tiraran a Brain al suelo seis o siete veces, y cuando quedó en el suelo,
le golpearon la cabeza contra el piso y le dieron un pisotón. Entonces Brown,
como un loco, les mandó que le arrancaran la nariz;
por lo que le tiraron violentamente de la nariz.
Y cuando se levantó, lo tiraron de nuevo al piso halándolo del pelo de su cabeza,
y así lo levantaron también. Y cuando quiso hablar a su favor contra esta crueldad,
Brown les mandó que le cerraran la boca.
Entonces no sólo lo golpearon en la boca,
sino que le amordazaron la boca y la nariz tan fuertemente,
que no podía respirar y se estaba sofocando;
ante estas acciones Brown se echó a reír y finalmente lo envió a la cárcel.

Llevado Thomas Spire ante Brown, este ordenó que le quitaran el sombrero,
y como no se realizó con toda la violencia que él pretendía,
hizo que se lo pusieran de nuevo diciendo: "`No debe ser arrancado tan suavemente.`"
Entonces T. Spire fue tumbado al piso halado de su
sombrero y levantado de nuevo por el pelo.
Cuando William Hill fue llevado delante de Brown,
este mandó que le arrancaran el sombrero para que su cabeza pudiera inclinarse,
después de lo cual también fue tirado al piso y levantado de nuevo por el pelo.
George Ableson fue tirado al piso y levantado por el pelo cinco veces, una tras otra,
y fue golpeado en la cara de manera tal, a los lados de su cabeza,
que se tambaleó y sangró, y por algunos días sufrió mucho dolor.

Llevado Nicholas Blithold delante de Brown,
este tomó su sombrero con ambas manos y procuró tirarle al suelo,
pero como no caía totalmente hacia delante, lo empujó para tirarlo hacia atrás,
luego le dio una patada en la pierna y lo echó fuera.
Al ser llevado Thomas Lacy delante de él, el propio Brown le dio un golpe en la cara;
e Isaac Merrit, John Cook, Arthur Baker y otros no fueron tratados mucho mejor,
por lo que parecía que era más apto para ser verdugo que concejal o juez.
Me cansa mencionar más ejemplos de su crueldad.
Estos abominables logros fueron publicados en forma impresa,
más extensamente de lo que yo los he mencionado, y el libro, como ya se ha dicho,
fue dedicado a él.

[.offset]
En ese ardiente tiempo de persecución,
Francis Howgill escribió y publicó el siguiente documento para el aliento de sus amigos.

[.embedded-content-document.epistle]
--

Durante meses, semanas y días las reflexiones de mi corazón,
con respecto al pueblo que el Señor ha levantado para que
dé testimonio de Su nombre en este el día de Su poder,
han sido muchas, profundas y pesadas.
Se ha intercedido a menudo por ellos al Señor y se ha esperado pacientemente,
para conocer Su mente con respecto a ellos para el tiempo por venir;
en lo cual con frecuencia recibí complacencia en cuanto a mí mismo.
Sin embargo, fui persuadido por el Señor a esperar algo más,
para que pudiera consolar y fortalecer a Su rebaño con un testimonio seguro.
Y mientras esperaba en mi espíritu y con mi corazón
puesto en nada más que en el Dios vivo,
fuera de todas las cosas visibles y completamente fuera del mundo,
el Señor abrió los manantiales de la gran profundidad
e inundó todo mi corazón con luz y amor.
Mis ojos eran como una fuente por causa de lágrimas de gozo debido a Su herencia,
la que me mostró y de la que me habló con un poder pleno, fresco y vivo,
y con un testimonio santo y pleno, de modo que mi corazón se extasió con gozo inefable.
Yo estaba fuera de mi cuerpo con Dios en Su paraíso celestial,
donde vi y sentí cosas indecibles, y más allá de toda demostración o discurso.
Finalmente, la vida se unió a mi entendimiento y mi espíritu la escuchó,
y el eterno Dios dijo: "`¿Encubriré algo a los que buscan mi rostro en justicia?
No, lo manifestaré a los que me temen.
Yo hablaré,
y tú escucha y publícalo entre todo Mi pueblo para que sean consolados y tú seas satisfecho.`"
Así habló el Dios vivo del cielo y la tierra, el 28 de mes Tres de 1662.

El sol dejará su brillo resplandeciente y cesará de alumbrar al mundo;
la luna se oscurecerá por completo y no alumbrará en la noche;
las estrellas dejarán de conocer su oficio o lugar; mi pacto con el día, la noche,
los tiempos y las estaciones se acabará,
antes de que el pacto que he hecho con este pueblo, en el que ellos han entrado conmigo,
termine o sea roto.
Sí, aunque el poder de las tinieblas y el infierno se combinen contra ellos,
y las fauces de la muerte abran su boca, Yo los libraré y los guiaré a través de todo.
Confundiré a sus enemigos como lo hice en Jacob,
y los dispersaré como lo hice en Israel en los días antiguos.
Tomaré a sus enemigos y los arrojaré aquí y allá,
como se arrojan las piedras con una honda; y la memoria de esta nación,
que es santa para Mí, nunca será desarraigada,
sino que vivirá a través de las edades como una nube
de testigos en las generaciones venideras.
Yo los he llevado hasta el momento de nacer, sí, los he engendrado;
los he envuelto y son Míos. Los alimentaré y llevaré en alas de águila;
y aunque las nubes se junten contra ellos, Me abriré paso a través de ellas.
Aunque las tinieblas se amontonen y abunden tempestades,
Yo las dispersaré con un viento solano; y las naciones sabrán que ellos son Mi herencia,
y ellos sabrán que Yo soy el Dios vivo,
quien defenderá su causa ante todo lo que se levante en oposición contra ellos.

Estas palabra son santas, fieles, eternas, buenas y verdaderas.
Bienaventurados los que oyen y creen hasta el fin.
Y debido a estas palabras, no me quedó fuerza por un tiempo; pero al fin,
mi corazón fue llenado de gozo,
como cuando el arca de Dios fue llevada de la casa de Obed-Edom,
cuando David danzaba delante de ella e Israel gritaba de júbilo.

[.signed-section-signature]
Francis Howgill.

--

Ciertamente, este escrito de F. Howgill,
quien era un hombre piadoso de grandes habilidades,
junto con muchas otras poderosas exhortaciones de aquellos que
valientemente se adelantaron y nunca abandonaron al rebaño oprimido,
contribuyó en gran medida a animarlos en ese tiempo de ardiente
persecución. Porque sin importar cuán furiosos fueran sus enemigos,
continuaron fieles en súplicas y fervientes oraciones a Dios,
para que Él se complaciera en asistir a los que en su celo recto,
no aspiraban nada para sí mismos, sino que,
desde un verdadero y reverente temor delante de Él,
no se atrevían a dejar sus asambleas religiosas.
Ellos hallaron que el Señor oía sus oraciones, a tal punto,
que recuerdo haber oído a uno decir,
que en una reunión donde parecían estar en peligro de muerte por sus feroces perseguidores,
él estaba (por decirlo así) tan dominado por el poder del Señor,
que apenas sabía si estaba en o fuera del cuerpo.
Y así, perseverando en fidelidad a lo que creían que el Señor había requerido de ellos,
con el transcurso del tiempo,
cuando sus enemigos habían tomado tales medidas para suprimir y extinguir a los Cuáqueros,
vieron como el Señor Dios Todopoderoso se levantó en defensa de ellos,
y sometió y confundió las malignas artimañas de sus crueles perseguidores,
como se verá en el curso de esta historia.

Entre tanto, demos un vistazo a la persecución en Southwark.
Allí las reuniones de los Cuáqueros no eran menos perturbadas que en Londres.
Varias personas que habían sido sacadas de sus reuniones
religiosas fueron enviadas a prisión;
y después de haber estado en White-lion presas por casi nueve semanas,
fueron llevadas al tribunal, donde Richard Onslow se sentaba como juez de las sesiones.
La acusación formulada contra ellos era como sigue:

[.embedded-content-document.legal]
--

Los jurados de nuestro señor el rey, presentan bajo juramento, que Arthur Fisher,
de la parroquia de St. Olave, en el municipio de Southwark, en el condado de Surry,
propietario rural; Nathaniel Robinson, del mismo lugar, propietario rural; John Chandler,
del mismo lugar, propietario rural; y otros, son personas perversas, peligrosas,
sectaristas sediciosas y desleales, y mayores de dieciséis años, quienes el 29 de Junio,
en el año del reinado de nuestro señor Carlos II
(quien por la gracia de Dios es rey de Inglaterra,
Escocia, Irlanda, etc.), se negaron obstinadamente a asistir a alguna iglesia,
capilla o lugar habitual para oír la oración común,
según las leyes y estatutos de este reino de Inglaterra.
Y además, el 3 de Agosto, en la parroquia de St. Olave antes mencionada,
se unieron voluntaria e ilegalmente, y estaban presentes, en una asamblea,
conventículo y reunión ilegal, bajo el pretexto del ejercicio de la religión,
contra las leyes y estatutos de este reino de Inglaterra,
en desacato de nuestro señor el rey, sus leyes,
y como un ejemplo malo y peligroso para todos los demás.

--

He insertado esta acusación para que el lector pueda ver, no sólo la manera de proceder,
sino también los colores negros y atroces con que se describían
las reuniones religiosas de los llamados Cuáqueros.
Cuando se leyó esta acusación,
los prisioneros pidieron ser juzgados según la última
ley del Parlamento contra los conventículos.
Pero se les respondió que podían ser juzgados por cualquier ley que estuviera en vigor.
Entonces los prisioneros pidieron que se leyera el estatuto (es decir,
el estatuto 35 de Elizabeth).
Eso se hizo sólo en parte, y entonces se le dijo al secretario que había leído suficiente.
Los prisioneros dijeron que esa ley había sido hecha en un tiempo de ignorancia,
cuando el pueblo apenas había salido del papado;
y luego se esforzaron por demostrar cuán injustamente habían sido tratados.
Pero cuando se les mandó que se declararan culpables o no culpables de la acusación,
algunos que no fueron rápidos en responder,
fueron sacados del tribunal como _pro confessi_ +++[+++como si hubieran confesado]
y mandados a prisión de nuevo.
El resto, que eran veinte y dos, se declararon no culpables.

Entonces fueron llamados los hombres del jurado,
y cuando los prisioneros objetaron contra uno, el juez no le dio lugar,
porque no le gustó la razón que dieron, a saber, que ellos veían la envidia,
prejuicio y comportamiento vano de él. Se objetó
contra otro porque se le había oído decir,
que él esperaba que dentro de poco los Cuáqueros fueran procesados en el tribunal,
y "`desterrados a una tierra donde no hubiera más que osos.`"
Ante esto, el tribunal estalló en carcajadas; sin embargo,
se admitió la objeción y el hombre fue dejado de lado.
Como los prisioneros pensaron que no era conveniente hacer más objeciones,
el jurado prestó juramento.
Luego fueron llamados dos testigos,
que sólo declararon que en cierto lugar habían cogido
a ciertas personas que se habían reunido,
cuyos nombres se especificaron por escrito.

Entonces los prisioneros les pidieron a los miembros del jurado que tuvieran cuidado,
por la manera en que se divertían o jugaban con las cosas santas,
y que las cosas que conciernen a la consciencia eran en verdad, cosas santas.
Y que así como un hombre no debía jugar con la salud o enfermedad de su prójimo,
tampoco debía jugar con la libertad o destierro de su prójimo.
Y que aunque se les acusaba de ser perversos, peligrosos y sectaristas sediciosos,
eso no era cierto; porque no eran perversos, sino que se esforzaban por vivir sobria,
justa y piadosamente en el mundo.
Que tampoco eran sediciosos, sino pacíficos.
Y que si bien, se les acusaba de no ir a oír la oración común, eso era incongruente;
ya que ese libro de servicios no había sido impreso sino
hasta varias semanas después del mencionado 29 de Junio;
de modo que ellos no podían ser acusados de negarse
a oír algo que no podía ser oído en ningún lugar.
Esto desconcertó no poco al tribunal, y los prisioneros,
algunos de los cuales eran hombres cultos, dieron otras razones de peso, a tal punto,
que el juez no podía responder a sus objeciones más que con movidas y evasivas.
Finalmente, el jurado salió para deliberar, y se le oyó decir a uno de ellos,
mientras subían las escaleras: "`Qué lío tenemos aquí,
debemos condenar a un grupo de hombres inocentes.`"

Después de un tiempo regresó el jurado,
y cuando se les preguntó si los prisioneros del tribunal eran culpables o no culpables,
dijeron que eran culpables en parte, y no culpables en parte;
pero este veredicto no le agradó al juez.
Entonces el jurado salió de nuevo, y prevaleciendo unos sobre otros,
regresaron rápidamente y declararon a los prisioneros culpables,
de acuerdo con la forma de la acusación. Con lo cual, el juez Onslow dictó sentencia,
a saber: Que ellos debían regresar a prisión y permanecer ahí tres meses sin fianza;
y que si no se sometían como ordenaba la ley,
ya fuera en o antes del final de los mencionados tres meses, debían abandonar el reino.
Pero en el caso de que se negaran a abandonar el reino,
o a salir dentro del tiempo especificado, o regresaran sin permiso,
debían ser procesados como delincuentes.

Justo antes de que se dictara la sentencia,
el juez le dijo a uno de los prisioneros que había una manera de escapar a la pena,
a saber, sumisión. Y cuando se le preguntó a qué se refería, el juez respondió:
"`Ir a oír la oración común y abstenerse de esas reuniones.`"
Al dar el prisionero razones para la negativa de ellos a ambas cosas, el juez dijo:
"`Entonces deben abjurar la tierra.`"
"`Adjurar,`" replicó el prisionero, "`es renunciar bajo juramento.`"
A lo que uno de los magistrados dijo riendo:
"`Y ustedes no pueden jurar del todo;`" como si fuera
un chiste tratar así a los hombres religiosos.
Pero ellos ya le habían indicado al jurado que preferían morir que hacerlo.
Cuánto tiempo fueron mantenidos prisioneros y cuándo fueron liberados, no lo encontré;
pero sé esto, que en casos similares,
muchos fueron mantenidos en la cárcel por mucho tiempo, a veces,
hasta que eran puestos en libertad por la proclama del rey.

En este año le tocó a John Crook (que alguna vez
fue juez) ser sacado de una reunión en Londres,
en John`'s Street, como ya se ha dicho, por un tal Miller, aunque no era un oficial.
Él, junto con otros,
fue llevado a su juicio en la mencionada ciudad ante el alcalde de Londres,
el registrador, el presidente del tribunal Forster, y otros jueces y magistrados,
entre quienes también estaba Richard Brown.

Ahora bien, dado que John Crook publicó este juicio de manera impresa,
y por eso podemos juzgar,
según _ex ungue leonem_ +++[+++a partir de la parte podemos juzgar el todo]
otros juicios de los Cuáqueros, lo expondré aquí en detalle:

Cuando John Crook fue llevado a la corte en Old Bailey, con dos de sus amigos,
Isaac Gray, doctor en medicina, y John Bolton, orfebre;
uno de los prisioneros fue llamado al estrado y el presidente del tribunal le preguntó:

[.discourse-part]
__Presidente del tribunal:__ ¿En qué reunión estabas tú?

[.discourse-part]
__Prisionero:__ Deseo ser escuchado, ¿dónde está mi acusador?

[.discourse-part]
__Presidente del tribunal:__ Tu lengua no es tuya,
y tú no tienes libertad de hablar lo que quieras.

[.discourse-part]
__Prisionero:__ Hablo en presencia y temor del Dios eterno.
En efecto, mi lengua no es mía,
porque es del Señor y está a disposición de Él según Su voluntad,
y no para hablar mis propias palabras.
Por tanto, deseo ser escuchado.
He estado mucho tiempo en prisión... +++[+++entonces fue interrumpido por el juez.]

[.discourse-part]
__Juez:__ ¡Deja tu palabrería!

[.offset]
+++[+++Luego ordenó que se lo llevaran, lo que hizo el carcelero.
Esto fue la sustancia de lo que el prisionero mencionado dijo la primera vez.]

[.discourse-part]
__Presidente del tribunal:__ Llamo a John Crook al estrado;
+++[+++lo que el pregonero hizo en consecuencia,
pues estaba entre los delincuentes como se dijo antes.]

[.discourse-part]
__Presidente del tribunal:__ ¿Cuándo prestaste el juramento de lealtad?

[.discourse-part]
__John Crook:__ Deseo ser escuchado.

[.discourse-part]
__Presidente del tribunal:__ Responde la pregunta y serás escuchado.

[.discourse-part]
__John Crook:__ He estado casi seis semanas en prisión,
¿y ahora soy llamado a acusarme a mí mismo?
Porque la respuesta negativa a esa pregunta sería acusarme a mí mismo,
a lo cual tú no deberías forzarme;
porque _Nemo debet seipsum prodere_ +++[+++Nadie debe ser obligado a traicionarse a sí mismo.]
Soy un ciudadano inglés, y según la ley de Inglaterra, no debo ser capturado,
ni encarcelado, ni privado de mis posesiones, ni cuestionado, ni obligado a responder,
sino de acuerdo con la ley de la tierra; la cual reclamo como mi derecho de nacimiento,
en mi propia defensa y la de todo el que me oye hoy +++[+++o palabras
para ese efecto]. Estoy aquí en este estrado como un delincuente,
y deseo que mi acusador sea traído para que me acuse por mi delincuencia,
y luego responderé a mi acusación, si es que soy culpable de alguna.

[.discourse-part]
__Presidente del tribunal:__ Se te pide que prestes el juramento de lealtad,
y cuando lo hayas hecho, entonces serás escuchado sobre la otra acusación;
porque tenemos poder de presentar el juramento a cualquier hombre.

[.discourse-part]
__John Crook:__ No para mí en esta ocasión, ni en este lugar;
porque ya he sido traído aquí como un transgresor,
y no debería ser hecho un transgresor aquí,
ni debería ser obligado a acusarme a mí mismo.
Porque soy un ciudadano inglés, como te he dicho,
y deseo el benefició de las leyes de Inglaterra;
porque por ellas obtengo una mejor herencia como ciudadano inglés,
que la que recibí de mis padres, pues por la primera se preserva la segunda,
y esto se ve en el capítulo 29 de la Carta Magna,
y en la "`petición de derecho`" mencionada en el año 3 de Car.
I, y en otras buenas leyes de Inglaterra.
Por lo tanto, deseo el beneficio y la observación de esas leyes;
y ustedes que son jueces en el tribunal, deberían ser mis consejeros, no mis acusadores,
e informarme de los beneficios de esas leyes.
Y donde yo no tenga conocimiento, deben informarme,
para no perder por mi propia ignorancia las ventajas
que dichas leyes de Inglaterra me ofrecen como inglés.

[.small-break]
'''

+++[+++Lector, aquí te doy un breve relato de cómo fui capturado y encarcelado,
para que puedas juzgar mejor la justicia que recibí del mencionado tribunal;
que es de la siguiente manera.

Estando en John`'s Street, en Londres, alrededor del día 13 del mes Tres (llamado Mayo^
footnote:[En Inglaterra y en todas sus colonias,
marzo fue el primer mes del año hasta 1752.]),
con algunos otros del pueblo de Dios esperando en Él, mientras estábamos sentados juntos,
entró un hombre rudo llamado Miller con un largo bastón en la mano,
quien puso sus manos violentamente sobre mí (junto con algunos otros),
y mientras golpeaba a algunos de los presentes,
les daba órdenes a los alguaciles que entraron después de él,
pero como estos no tenían una orden judicial, no estaban dispuestos a intervenir.
Pero como sus amenazas prevalecieron y ellos le temían,
se unieron a él para llevar a varios de nosotros delante del juez llamado Powel,
quien al día siguiente se sentó en las sesiones del tribunal en Hicks`'s Hall;
donde después de hablar varias veces con ellos,
les manifestamos la ilegalidad de nuestro encarcelamiento y sus procedimientos al respecto.
A pesar de eso, me detuvieron a mí y a otros,
e hicieron que se formulara una acusación contra nosotros,
basada en la última ley contra los Cuáqueros y otros;
y luego nos remitieron a New Prison, donde continuamos algunos días,
y luego nos trasladaron a la prisión de Newgate,
donde permanecimos hasta las sesiones del tribunal en Old Bailey como ya se mencionó.
De este modo puedes entender el tipo de justicia con el que me encontré,
por lo que sucedió antes; y ahora seguimos.]

[.small-break]
'''

[.discourse-part]
__Presidente del tribunal:__
Nosotros nos sentamos aquí para hacer justicia y estamos bajo juramento.
Nosotros te decimos qué es ley, y no tú a nosotros; por tanto, sirrah,^
footnote:[_Sirrah,_ era una palabra de reproche o desprecio,
utilizada para dirigirse a personas viles.]
tú eres demasiado atrevido.

[.discourse-part]
__John Crook:__ '`Sirrah`' no es una palabra apropiada para un juez,
pues no soy un delincuente.
Ni deberías amenazar al prisionero en el estrado,
porque estoy aquí siendo procesado por mi vida y libertad,
la preservación de mi esposa e hijos, y mi propiedad externa, que ahora está en juego.
Por lo tanto, deberías escuchar todo lo que pueda decir en mi defensa.
Así, pues, espero que el tribunal tenga paciencia conmigo,
si me atrevo a afirmar mi libertad como ciudadano inglés y como Cristiano;
y si hablo en voz alta es por mi celo por la Verdad y por el nombre del Señor,
y es mi inocencia lo que me hace ser audaz...

[.discourse-part]
__Juez:__ +++[+++Interrumpiendo a John Crook]
Ese es un celo maligno.

[.discourse-part]
__John Crook:__ No; soy audaz en el nombre del Señor Dios Todopoderoso, el eterno Jehová,
a afirmar la Verdad y a ser testigo de ella.
Que mi acusador se presente, estoy listo a responder a cualquier tribunal de justicia...

[.offset]
+++[+++Entonces el juez me interrumpió,
diciendo "`sirrah,`" junto con algunas otras palabras que no recuerdo.
Pero respondí:]

[.discourse-part]
__John Crook:__ No debes amenazarme, ni esos insultos son apropiados en la boca de un juez;
porque la seguridad del prisionero depende de la imparcialidad del tribunal.
Y ustedes no deberían comportarse como un partido unido,
todos buscando una ventaja contra el prisionero,
y no prestándole atención a cualquier cosa que ayude a su exoneración o ventaja.
+++[+++El juez me interrumpió de nuevo, diciendo:]

[.discourse-part]
__Juez:__ Sirrah, debes prestar el juramento, y aquí te lo presentamos,
+++[+++ordenando a uno que lo leyera].

[.discourse-part]
__John Crook:__ Déjenme ver a mi acusador,
para que yo pueda saber por qué razón he estado seis semanas encarcelado,
y no me pongan a acusarme a mí mismo haciéndome preguntas;
sino que se presente mi acusador, o de lo contrario, libérenme por proclamación,
como deberían hacerlo.
+++[+++Aquí fui interrumpido otra vez.]

[.discourse-part]
__Juez Twisden:__ No tiene importancia la razón por la que estás aquí;
da lo mismo que seas un vagabundo o cualquier otra persona presente aquí hoy,
porque podemos presentarle el juramento a cualquier hombre.
+++[+++Y otro juez habló algo parecido.]

[.discourse-part]
__John Crook:__ He sido traído al tribunal como un prisionero restringido de mi libertad,
y pregunto si ustedes en justicia,
deberían presentarme el juramento en esta ocasión. Se supone que soy un transgresor,
o si no, ¿por qué he estado ya en prisión seis semanas?
Que primero se me exonere de mi encarcelamiento,
y luego responderé a la acusación contra mí y a la pregunta planteada;
porque amo la justicia con toda mi alma, y es bien conocido por mis vecinos donde vivía,
que soy una persona que mantiene la consciencia libre
de ofensa hacia Dios y hacia los hombres.

[.discourse-part]
__Juez:__ Sirrah, deja tu palabrería.

[.discourse-part]
__John Crook:__ ¿Es palabrería declarar las palabras de las Escrituras?

[.discourse-part]
__Juez:__ Es palabrería en tu boca, aunque sean las palabras de Pablo.

[.discourse-part]
__John Crook:__ Yo declaro las palabras de las Escrituras, y no es palabrería,
aunque las diga yo; sino que son palabras de verdad y sobriedad en mi boca,
experimentadas por mí y cumplidas en mí.

[.discourse-part]
__Juez:__ Te preguntamos de nuevo, ¿tomarás el juramento de lealtad?
Es una pregunta corta, puedes responderla si quieres.

[.discourse-part]
__John Crook:__ ¿Según qué ley tienen poder para presentarme el juramento?
+++[+++Entonces, después de consultar entre ellos susurrando, pidieron el libro de leyes,
y pasando las páginas, respondieron:]

[.discourse-part]
__Juez:__ Por la tercera del rey James.

[.discourse-part]
__John Crook:__ Deseo que sea leído el estatuto;
porque yo lo he consultado y no entiendo que ese
estatuto les dé el poder de presentarme el juramento,
estando aquí delante de ustedes, en este lugar y en esta ocasión, ya como un delincuente.
Por tanto, deseo la opinión del tribunal en este caso y que ese estatuto sea leído.

[.discourse-part]
__Juez:__ +++[+++Entonces tomaron el libro de leyes y consultaron juntos sobre esto, y uno dijo:]
Nosotros somos los jueces de esta tierra, y entendemos mejor nuestro poder que tú,
y juzgamos que podemos hacerlo legalmente.

[.discourse-part]
__John Crook:__ ¿Es esta la opinión del tribunal?

[.discourse-part]
__Juez:__ Sí.

[.discourse-part]
__John Crook:__
Deseo que se lea el estatuto que los faculta para presentarme
el juramento en esta ocasión y en este lugar:
porque _Vox audita perit, sed litera scripta Manet_
+++[+++las palabras que sólo se hablan se pierden, pero las escritas permanecen],
por tanto, déjenme oírlo leído.

[.discourse-part]
__Juez:__ Escúchame.

[.discourse-part]
__John Crook:__ Estoy tan dispuesto a oír como a hablar.

[.discourse-part]
__Juez:__ Entonces, escúchame.
Estás aquí obligado a prestar el juramento que te presenta el tribunal,
y te voy a informar cuál será el castigo en caso de que te niegues.
La primera negativa será registrada,
y luego se te presentará de nuevo al final de las sesiones.
A la segunda negativa te expones a la sentencia premunire,^
footnote:[__Premunire__ era una sentencia legal concebida para privar de derechos
a los que se rehusaban a jurar formalmente lealtad al rey de Inglaterra.
Los que estaban bajo la sentencia premunire eran considerados traidores
a su país. Perdían todo derecho a la propiedad y a las posesiones,
se les quitaba la protección del rey, y a menudo se les encarcelaba de por vida.]
la cual implica la pérdida de todo tu patrimonio (si tienes alguno) y el encarcelamiento.

[.discourse-part]
__John Crook:__ Es la justicia lo que defiendo;
déjenme obtener justicia trayendo a mi acusador cara a cara,
como deberían hacerlo por ley,
ya que estoy aquí en el tribunal de ustedes como un delincuente.
Y cuando esto sea hecho, responderé a lo que se me impute,
así como también a la cuestión del juramento.
Hasta entonces, no daré otra respuesta que la que ya he dado, al menos por el momento.

[.offset]
+++[+++Entonces se oyó un grito en el tribunal que decía:
"`¡Sáquenlo!,`" lo que provocó una gran interrupción,
y John Crook dijo algo parecido a lo siguiente:]

[.discourse-part]
__John Crook:__ Teman al Señor Dios,
para que lleguen al conocimiento de Su voluntad y hagan justicia.
Y tengan cuidado y no opriman al inocente,
porque el Señor Dios del cielo y de la tierra ciertamente defenderá su causa.
Por mi parte, deseo que no se dañe uno solo de los cabellos de sus cabezas;
sino que la sabiduría de Dios los guíe. +++[+++Estas palabras
las dijo en el tribunal y mientras era sacado.]

[.offset]
+++[+++El sexto día de la semana, la mañana siguiente,
estando reunido el tribunal fue llamado al estrado John Crook.]

[.discourse-part]
__Presidente del tribunal:__ Amigo Crook,
te hemos dado tiempo para que consideres lo que te dijo el tribunal ayer,
esperando que lo hayas pensado mejor para este momento.
Por tanto, sin más palabras, ¿prestarás el juramento?
+++[+++Él entonces llamó al secretario y le ordenó leerlo.]

[.discourse-part]
__John Crook:__ No lo hice, ni tampoco niego mi lealtad al rey,
pero deseo saber la razón de mi tan prolongado encarcelamiento.
Porque, como dije ayer, estoy aquí ante el tribunal de ustedes como un delincuente,
y he sido traído a la fuerza, en contra de la ley.
Por tanto, déjenme ver a mi acusador, o de lo contrario libérenme por proclamación,
como debería ser, si nadie puede acusarme de infringir alguna ley.
Porque la ley se basa en la justa razón, y lo que sea contrario a la justa razón,
es contrario a la ley.
Por tanto, si no aparece ningún acusador, ustedes deberían absolverme primero,
y luego responderé (como ya dije) si aparece algún otro asunto; de lo contrario,
estoy siendo forzado ilegalmente, lo que nuestra ley aborrece.
Porque lo que no se hace legalmente, no debería hacerse del todo.
Y por lo tanto,
me encuentro en la condición de no haber sido traído delante de ustedes legítimamente.
En consecuencia, no se puede suponer, en justa razón,
que ustedes tienen poder en este momento y en este lugar,
para presentarme legalmente el juramento.

[.discourse-part]
__Juez:__ Léanle el juramento.
+++[+++Y el secretario empezó a leer.]

[.discourse-part]
__John Crook:__ Deseo justicia de acuerdo con las leyes de Inglaterra.
Ustedes deberían condenarme primero por la causa de mi largo encarcelamiento.
Porque deben proceder según las leyes ya promulgadas, y no hacer leyes;
porque ustedes deben ser ministros de la ley.

[.discourse-part]
__Juez:__ Eres un tipo descarado e insolente.
¿Nos vas a enseñar la ley o nuestros deberes?
+++[+++Entonces le dijo al secretario:]
¡Continúa leyendo! +++[+++Y cuando el secretario terminó de leer, John Crook dijo:]

[.discourse-part]
__John Crook:__ Lee el prefacio de la ley.
Repito, lee el título y el prefacio de la ley;
porque los títulos de las leyes son _claves legum,_ como _llaves para abrir la ley;_
porque por sus títulos se entienden y se conocen las leyes,
como los hombres por sus rostros.
+++[+++Entonces los jueces me habrían interrumpido, pero dije lo siguiente:]
Si no me escuchan, ni me hacen justicia,
debo apelar al Señor Dios del cielo y de la tierra, quien es juez de vivos y muertos,
delante de quien todos debemos comparecer para darle
cuenta de todas las obras hechas en el cuerpo;
porque Él juzgará entre ustedes y yo, si hoy me han hecho o no justicia.

[.offset]
+++[+++Estas palabras a continuación (o similares) las dije mientras era sacado del tribunal.]

[.discourse-part]
__John Crook:__ Teman al Señor Dios, para que puedan hacer justicia,
no sea que perezcan en Su ira.

[.offset]
+++[+++Porque a veces el tribunal gritaba: "`¡Sáquenlo!,`" y luego decían:
"`¡Tráiganlo otra vez!`"
Y así lo hicieron varias veces, como hombres en confusión y desorden.
El mismo día, por la tarde, logrado el silencio,
John Crook fue llamado al estrado ante los jueces y magistrados mencionados.
Una vez leída la acusación, el juez dijo:]

[.discourse-part]
__Juez:__ Señor Crook, has oído tu acusación, ¿qué dices?
¿Eres culpable o no culpable?

[.discourse-part]
__John Crook:__ Deseo decir unas pocas palabras en humildad y sobriedad,
dado que mi patrimonio y libertad están en juego,
y es probable que sea un precedente para muchos más de mis Amigos.
Por tanto, espero que el tribunal no me niegue el derecho y beneficio de la ley,
como ciudadano inglés que soy.
Tengo buenas razones, antes de que diga algo sobre la acusación,
de demandarles y decirles, que deseo conocer a mis acusadores.
He sido mantenido estas seis semanas en prisión, y todavía no conozco a mis acusadores,
ni he visto sus rostros.

[.discourse-part]
__Juez:__ Te concederemos el derecho de la ley, como ciudadano inglés que eres.
Dios no permita que se te niegue; pero debes responder primero, culpable o no culpable,
para que en tu juicio tengas una audiencia y alegato justos.
Pero si continúas como lo haces (y no respondes culpable o no culpable),
te enfrentarás a la sentencia de premunire,
perderás el beneficio de la ley y te expondrás--cuerpo y patrimonio--a grandes peligros,
y luego cualquier violencia que le ocurra a tu persona o a tu patrimonio,
estarán fuera de la protección del rey, y perderán el beneficio de la ley;
y todo esto por tu negativa a responder culpable o no culpable.
Si te declaras no culpable, puedes ser escuchado.

[.discourse-part]
__John Crook:__
Estas palabras están registradas en los estatutos 28 Edw. 3l. y 3; y en 42 Edw. 3.:
"`Ningún hombre debe ser capturado, ni encarcelado, ni obligado a responder,
sin haber comparecido ante jueces, ni haberse registrado el asunto,
sin haberse llevado a cabo el debido proceso, según la antigua ley de la tierra.
Y si se hace algo en contra, será nulo en el tribunal y considerado un error.`"
También en los estatutos 25 de Edw. 1. 2; y 3 de Car. I.,
y en el capítulo 29 de la Carta Magna:
"`Ningún hombre libre será capturado y encarcelado sino por la ley de la tierra.`"
Estas palabras ("`la ley de la tierra`"),
son explicadas por el estatuto 37 Edw. 3. 8. como:
"`sin el debido proceso de la ley;`" y si se dictan
sentencias contrarias a la Carta Magna,
serán nulas por 25 Edw. 1. 2.

[.discourse-part]
__Juez:__ Señor Crook, estás confundido y no entiendes la ley.
Aunque adores los estatutos de la ley, aun así no la entiendes.

[.discourse-part]
__John Crook:__ Deseo que me digas la forma correcta de entenderla.

[.discourse-part]
__Juez:__ Señor Crook, escúcheme.
Debes decir culpable o no culpable.
Si te declaras no culpable serás oído,
y luego podrás ver hasta qué punto te favorece la ley.
Lo siguiente es, que no hay circunstancias que sean la causa de tu encarcelamiento,
el cual tú cuestionas,
sino aquella en la que tienes tus derechos si haces lo que te decimos,
renuncias a otras cosas, y respondes culpable o no culpable.
Tendrás lo que la ley te concede, si haces lo que la ley demanda de ti;
o de lo contrario,
perderás el beneficio de la ley y quedarás fuera de la protección del rey.

[.discourse-part]
__John Crook:__
Observen cómo el juez busca arrastrarme a una trampa--haciendo
que primero me declare culpable o no culpable,
y cuando lo haya hecho, declararme proscrito, fuera de la protección del rey; y entonces,
¿cómo podré obtener una solución legal por mi falso encarcelamiento?
Por tanto, primero exonérenme o condénenme por mi falso encarcelamiento,
mientras todavía pueda tener el beneficio de la ley;
y no me proscriban primero por un delito que ustedes han creado para detener mi boca,
para luego decirme que si he sido agraviado, o falsamente encarcelado,
podré obtener solución legal después. Esto es para atraparme,
y es contrario tanto a la ley como a la justicia.

[.discourse-part]
__Juez:__ Declárate culpable o no culpable.

[.discourse-part]
__John Crook:__
Con humildad y mansedumbre debo decir que no lo haré.
No me atrevo a traicionar la honestidad de mi causa,
y a los honestos de esta nación cuya libertad defiendo,
así como también la mía. Porque realmente,
no estoy convencido en mi opinión ni en mi consciencia,
de que deba declarar un nuevo delito creado por ustedes,
antes de ser primero absuelto de la causa por la que fui traído prisionero al tribunal.
Por tanto, no veo otro camino que insistir en esto,
que pueda ver a mis acusadores...+++[+++Interrupción].

[.discourse-part]
__Juez:__ El más notorio ladrón podría decir que no está convencido en su consciencia.

[.discourse-part]
__John Crook:__ Mi caso no es el de ellos.
Pero aun así, a ellos se les permite ver a sus acusadores;
¿y no puedo llamar a los míos? Por tanto, llámenlos, pues deben hacerlo,
como Cristo le dijo a la mujer: "`Mujer, ¿dónde están tus acusadores?`"
Así deben decirme ustedes: "`Hombre, ¿dónde estás tus acusadores?`"
...+++[+++Interrupción].

[.discourse-part]
__Juez:__ Tu imputación es tu acusador,
y el gran jurado te ha hallado culpable porque no quisiste jurar.
¿Qué dices, Señor Crook, eres culpable o no culpable?
Si no respondes, entonces lo que ya has dicho será tomado como tu respuesta;
y como te dije antes, perderás el beneficio de la ley.
Lo que te digo es por tu bien.

[.discourse-part]
__John Crook:__ Lo que es verdaderamente por mi bien, espero tomarlo así.

[.discourse-part]
__Juez:__ Si no respondes, te expones a la sentencia de premunire;
y perderás el beneficio de la ley y la protección del rey,
a menos que te declares culpable o no culpable.

[.discourse-part]
__John Crook:__ He sido traído por la fuerza y con violencia;
no estaría aquí sino por una acción violenta.
Que ustedes no presten atención a esto es extraño para mí, y no sólo eso,
sino que me lleven tan rápidamente a un curso de acción en el que no podré,
por ningún medio, ayudarme a mí mismo,
debido a sus apresurados procedimientos contra mí para sacarme
de la protección del rey y del beneficio de toda la ley.
¿Se ha sabido u oído alguna vez un caso similar en un tribunal de justicia?

[.discourse-part]
__Juez:__ Amigo, aquí la cuestión no es si has sido traído injustamente o no.
Si fuiste traído por una mano equivocada, tienes una apelación contra ellos;
pero debes primero responder culpable o no culpable.

[.discourse-part]
__John Crook:__
¿Cómo me puedo ayudar a mí mismo después de que ustedes me hayan proscrito por premunire?
Por tanto,
que se haga una proclamación en el tribunal de que he sido traído por la fuerza,
y que primero sea absuelto por proclamación, tal como ustedes deben hacerlo;
ustedes deben _discernere per legem, quid sit juslum,_
+++[+++determinar justicia por medio de la ley],
y no hacer lo que les parezca bien ante sus propios ojos.

[.offset]
+++[+++Aquí me interrumpieron de nuevo,
pero habría podido decir las palabras del juez Crook en el caso Hampden, quien dijo:
"`Nosotros los jueces hablamos bajo juramento, y por lo tanto,
debemos dictar nuestras sentencias en concordancia con nuestras consciencias;
y la culpa recaerá sobre nosotros si es ilegal, y aun así la dictemos como ley.`"
Y además dijo:
"`Nosotros los jueces no debemos dictar nuestras sentencias según la política,
las reglas del estado, ni las conveniencias, sino sólo según la ley.`"
Estas fueron sus palabras, las cuales yo habría podido decir, pero fui interrumpido.]

[.discourse-part]
__Juez:__
Aunque ningún hombre te haya presentado el juramento
cuando fuiste enviado a prisión (como dices),
ahora te es presentado.
Y al serte presentado por una autoridad legal,
estás acusado desde el momento en que lo rechazaste.
No nos fijamos en el motivo por el que fuiste traído aquí, pero al estar aquí,
te presentamos el juramento; y al encontrar que lo rechazas,
tu encarcelamiento ahora es justo y de acuerdo con la ley.

[.discourse-part]
__John Crook:__ ¿Cómo llegué aquí? Ya les he dicho que fue por la fuerza y con violencia,
sin una orden judicial, lo que nuestra ley condena por completo.
Y por tanto, como no estoy legalmente ante ustedes, no estoy ante ustedes;
porque lo que no es verdad según la ley, no es verdad.
Porque como fui traído ilegalmente a este tribunal,
ustedes no deberían tomar nota de mi presencia, y mucho menos,
crear cargos adicionales contra mí.

[.discourse-part]
__Juez:__ No, no, estás equivocado;
porque puedes decir lo mismo de todos los mirones que están aquí,
que al no estar legalmente aquí, no están. Te digo,
aunque un hombre sea traído por la fuerza,
aun así nosotros podemos presentarle el juramento; y si él no presta el juramento,
puede ser enviado a prisión. La autoridad nos ha dado ese poder,
y la ley no has dado autoridad de presentar el juramento a cualquier persona,
y por eso te lo hemos presentado a ti; y por tu negativa a prestar juramento,
has sido acusado por el gran jurado.
Responde a la acusación o refuta la acusación; debes hacer una u otra,
culpable o no culpable.

[.offset]
+++[+++Aquí fui interrumpido, pero podría haber dicho,
que los espectadores que asistían a los juicios y los oían,
no debían ser llamados "`mirones,`" como los llamó el juez,
porque como ciudadanos ingleses tenía la libertad y el privilegio de hacerlo,
y la ley de Inglaterra lo permitía. De modo que no
debe usarse el término "`mirones`" por este motivo,
pues están en este lugar para oír juicios y para ver que se haga justicia.]

[.discourse-part]
__John Crook:__ La ley está construida sobre la razón, o justa razón,
y cualquier cosa que sea contraria a la justa razón, es contraria a la ley;
la razón de la ley, es la ley misma.
No soy abogado y mi conocimiento de la ley es poco, y sin embargo,
he sentido amor por ella, por la justa razón que he encontrado en ella,
y he pasado algunas hora de ocio en su lectura.
Honro la ley y es buena en su lugar, muchas leyes son justas y buenas--no todas ellas,
pero, digo, gran parte de ellas--y no es mi intención, en lo más mínimo,
despreciarlas o derogarlas.

[.discourse-part]
__Juez:__ Señor Crook, se le ha dicho que debe declararse culpable o no culpable,
o de lo contrario se expondrá a la sentencia de premunire.
No sea su propio enemigo, ni tan obstinado.

[.discourse-part]
__John Crook:__ No estoy delante de ustedes obstinadamente,
ni tampoco soy así. Si lo entienden de otro modo, es un error.

[.discourse-part]
__Juez:__ ¿Hablarás sobre la acusación? Entonces después,
puedes hacer la declaración. Si no respondes culpable o no culpable,
lo registraremos y el juicio será en tu contra.
Secretario, regístralo.

[.discourse-part]
__Registrador:__ Señor Crook, si respondes, podrás declararte culpable o no culpable.
¿O tomarás el juramento?
El tribunal no toma en cuenta cómo llegaste aquí. ¿Qué dices?
¿Responderás? Porque un hombre puede ser arrastrado
de Smithfield por la cabeza y los hombros,
se le puede presentar el juramento y puede ser enviado a prisión,
sin haber tomado en cuenta cómo llegó aquí.

[.discourse-part]
__John Crook:__ Ese tipo de procedimiento no es sólo injusto,
sino también irrazonable--+++[+++aquí hubo una interrupción]--y
es contra las leyes antes mencionadas,
que dicen: "`Ningún hombre será capturado, sino por una orden judicial,
o el debido proceso,`" por lo que este discurso del
registrador tiene más sabor a pasión que a justicia;
más a crueldad que a la debida observación de la ley;
porque toda forzada restricción de la libertad de un hombre,
es un encarcelamiento según la ley.
Además, este tipo de práctica, la de tomar hombres por la fuerza y encarcelarlos,
y luego hacerles preguntas, cuyas respuestas los hacen culpables,
no es sólo injusta en sí misma, sino que es contra la ley,
y hace un acto malo sea el fundamento de otro; y un agravio a uno,
se convierta en el fundamento de otro; y este es mi caso hoy--+++[+++Interrupción.]

[.discourse-part]
__Juez:__ Señor Crook, tú no debes ser tu propio juez; nosotros somos tus jueces.
Pero por nuestra parte, no te haremos mal.
¿Responderás culpable o no culpable?
Si no, te expondrás inevitablemente a la sentencia premunire,
y entonces experimentarás lo que se te ha dicho que seguiría;
porque nosotros no tomamos en cuenta cómo llegaste aquí, sino que estando aquí,
te presentamos el juramento.

[.discourse-part]
__John Crook:__ Parece, entonces, que ustedes hacen de la ley una trampa para atraparme,
o como una "`nariz de cera,`"^
footnote:[El término "`nariz de cera`" era usado para referirse a una persona
o cosa que era fácilmente torcida o influenciada en cualquier dirección.]
o cualquier cosa que les plazca.
Bueno, dejaré mi causa al Señor Dios, quien me defenderá en justicia.
Pero supongan que presto el juramento ahora, en este momento,
mañana me pueden llamar de nuevo y hacerme un nuevo ofrecimiento;
u otros me pueden llamar ante ellos.

[.discourse-part]
__Juez:__ Sí, si hubiera un asunto nuevo;
o si hubiera sucedido algo repentinamente por lo que dieras motivo.
Señor Crook, ¿vas a jurar?

[.discourse-part]
__John Crook:__ Si lo hago hoy, se me puede presentar mañana otra vez,
y al día siguiente también, _ad infinitum,_
por lo que una gran parte de mi tiempo puede ser
gastado y ocupado en prestar el juramento y jurar.

[.discourse-part]
__Presidente del tribunal:__ Una vez que hayas jurado, no podrás ser puesto en eso de nuevo,
a menos que des motivo.

[.discourse-part]
__John Crook:__ ¿Es esta la sentencia del tribunal,
que es suficiente que yo haya prestado el juramento una vez,
y que no me debe ser presentado una segunda vez, sin ninguna nueva ofensa por mi parte?

[.discourse-part]
__Juez:__ Sí; siempre y cuando hagas ver que lo has prestado una vez.

[.discourse-part]
__John Crook:__ ¿Es esta la sentencia de todo el tribunal?
Porque no quiero hacer nada apresuradamente.

[.discourse-part]
__Jueces:__ Sí, esta es la sentencia del tribunal, +++[+++a lo que todos dijeron de pie: "`Sí.`"]

[.discourse-part]
__John Crook:__ Entonces, parece, que después de haber prestado juramento una vez,
debo dar un nuevo motivo, o no se me debe presentar una segunda vez.

[.discourse-part]
__Jueces:__ Sí.

[.discourse-part]
__John Crook:__ Entonces, por sentencia de esta corte,
si puedo hacer ver que ya he tomado el juramento una vez,
y que no he dado motivo por el que pueda ser justamente culpado de haberlo transgredido,
el juramento no se me debe presentar una segunda vez.
Pero, en realidad, ya lo he prestado una vez,
cuando me nombraron ciudadano de la ciudad de Londres; vean los registros en Guildhall,
los cuales puedo presentar; y no se ha presentado ningún nuevo motivo por mi parte.
Si hay, háganmelo saber.
Si no, no deben, por decisión de ustedes, presentarme el juramento una segunda vez.
+++[+++Interrumpido por el grito del tribunal,
cuando estas últimas palabras podrían haberse dicho.]

[.discourse-part]
__Juez:__ Señor Crook, estás equivocado, no debes pensar en sorprender al tribunal,
ni sacar falsas conclusiones de nuestros juicios.

[.discourse-part]
__John Crook:__ Si esta no es una conclusión natural del fallo del tribunal,
dejen que la justa razón juzgue.
Y si ustedes se retractan de sus propios juicios, ¿qué justicia puedo esperar de ustedes?
Porque, si no son justos con ustedes mismos, ni con sus propios juicios,
¿cómo puedo esperar que sean justos conmigo?

[.discourse-part]
__Juez:__ Señor Crook, aunque hubieras prestado juramento, si hay un nuevo suceso,
debes volver a prestarlo.
Como por ejemplo, el rey ha estado fuera de Inglaterra y ahora ha regresado.
Hay muchos que habían prestado juramento hace veinte, treinta o cuarenta años,
sin embargo, este nuevo suceso lo requiere de nuevo.
Y aunque tú hayas prestado juramento,
no debes '`ponerlo sobre la mesa`' antes de responder culpable o no culpable.
Por tanto, no te equivoques, ni te pongas en peligro a ti mismo, ni a tu familia.
¿Acaso crees que todos los que vienen aquí argumentarán como tú? No necesitamos
nada más sino saber si responderás culpable o no culpable,
o prestarás juramento, y luego serás liberado de la acusación. ¿Qué dices?
¿Eres culpable o no culpable?

[.discourse-part]
__John Crook:__ ¿No se mantendrán en sus propios juicios?
¿No dijiste ahora, que si yo había prestado juramento una vez,
no se me debía presentar una segunda vez,
a menos que yo diera un nuevo motivo de no haberlo cumplido?
Pero al no haber un motivo, no deben presentarme el juramento la segunda vez,
según la confesión de ustedes mismos, mucho menos, acusarme por negarme.

[.discourse-part]
__Juez:__ Si no te declaras, lo registraremos y se dictaré sentencia contra ti.
Por lo tanto, di culpable o no culpable, o de lo contrario, lo registraremos.
+++[+++Entonces el secretario comenzó a registrarlo.]

[.discourse-part]
__John Crook:__ Antes de responder, solicito una copia de mi acusación;
porque he oído decir a un abogado experto en la ley,
que si hago una declaración antes de tener una copia, o de haber hecho mis objeciones,
mis posteriores objeciones contra la acusación serán nulas.
Por lo tanto, deseo una copia de mi acusación.

[.discourse-part]
__Juez:__ El que dijo eso no merece el nombre de abogado;
porque la ley dice que debes responder primero, y luego tendrás una copia.
¿Te declaras culpable o no culpable?

[.discourse-part]
__John Crook:__ Si mi declaración de culpabilidad o no culpabilidad,
no me priva del beneficio de anular la acusación por insuficiencia,
o de otras objeciones que pueda hacer contra ella, hablaré.

[.discourse-part]
__Juez:__ No, no te privará. ¿Responderás culpable o no culpable?
Si no declaras, la acusación será pronunciada en tu contra.
¿Responderás? No esperaremos más tiempo.

[.discourse-part]
__John Crook:__ Estoy en el punto.
¿No me privará mi declaración del beneficio de la ley.
Este aspecto es muy importante para mí, porque no se trata sólo de mi propio caso,
sino que puede ser el caso de miles más; por tanto,
no quiero hacer nada que pueda perjudicar a otros, o a mí mismo, como Cristiano,
o como ciudadano inglés.

[.discourse-part]
__Juez:__
Se te hará lo correcto como ciudadano inglés. La forma es responder culpable o no culpable.
Si declaras, y posteriormente encuentras que la acusación no es buena,
tendrás tus recursos.
Responde, culpable o no culpable.

[.discourse-part]
__John Crook:__ En cuanto a la acusación, es muy extensa y parece confusa,
y compuesta de cosas que son verdaderas y otras que son falsas.
Por tanto, mi respuesta es, no niego lo que es verdadero en la acusación,
porque hago de lo que digo un asunto de consciencia.
Por tanto, con respecto a lo que es verdadero, me declaro culpable,
pero no culpable de lo que es falso.

[.discourse-part]
__Juez:__ Eso no es suficiente, responde culpable o no culpable,
o se dictará sentencia contra ti.

[.discourse-part]
__John Crook:__ Diré la verdad, como delante del Señor,
como siempre me he esforzado por hacer.
No soy culpable de lo que es falso, contenido en la acusación,
que es la sustancia de esta.

[.discourse-part]
__Juez:__ No más demora.
¿Eres culpable o no?

[.discourse-part]
__John Crook:__ No debo dañar mi consciencia.
No soy culpable de lo que es falso, como dije antes.
Soy culpable de lo que es verdadero;
no soy culpable de lo que no es verdadero--que es la mayor parte de la acusación,
como dije antes.

[.discourse-part]
__Registrador:__ Es suficiente y servirá de turno.
Entre esto, secretario.

[.offset]
__Séptimo día de la semana, llamado Sábado.__

Al hacerse silencio, John Crook fue llamado al estrado.
El secretario de las sesiones leyó algo con respecto al nuevo jurado,
el cual fue constituido a propósito,
ya que el jurado anterior había sido despedido por haber
presenciado lo que había pasado entre nosotros y el tribunal.
Varios de ese nuevo jurado eran soldados,
algunos de los cuales habían sacado a Amigos de sus reuniones por la fuerza y con violencia,
y a algunos de nosotros de nuestras casas;
y ese era el jurado por el que íbamos a ser juzgados.
Entonces, el secretario leyó la acusación +++[+++según recuerdo.]

[.discourse-part]
__John Crook:__ Deseo que se escuchen unas pocas palabras, que son las siguientes:
Solicito que hasta las próximas sesiones trimestrales,
nos den la libertad de analizar la acusación, pues es extensa y en latín,
y probablemente, un precedente para muchos otros.
Espero no tener que insistir en este asunto;
porque entendí que ustedes lo prometieron (y especialmente del registrador, quien,
cuando se le preguntó, declaró: "`Tendrás tu asesoramiento`"), por lo cual,
no puede esperarse que hayamos tenido el beneficio hasta ahora,
pues el tiempo ha sido corto y hemos sido mantenidos prisioneros,
y no se nos ha permitido salir para asesorarnos con un abogado,
ni hemos encontrado la manera de conseguir que un abogado venga a nosotros.
Y como no hemos tenido una copia de la acusación antes de esta mañana,
y hoy repentinamente nos apresuraron a venir a las sesiones del tribunal,
no se puede suponer razonablemente que estemos preparados
(en lo que respecta a la ley) para hacer nuestra defensa.

[.discourse-part]
__Juez:__ Te hemos dado suficiente tiempo, no tendrás más. Te juzgaremos en este momento,
por tanto, juramentaremos al jurado.

[.discourse-part]
__John Crook:__ Deseo que se nos haga justicia y que no seamos enredados en nuestro juicio,
sino que tengamos tiempo hasta las siguientes sesiones trimestrales,
pues nuestra sentencia está en latín y es extensa.
Esto es razonable y es la práctica en otros tribunales.
Porque, en cualquier juicio que sea por más de cuarenta chelines,
normalmente no se finaliza en menos de dos o tres períodos.
Y en la sesiones trimestrales, si un hombre es acusado por una infracción,
aunque sólo sea por el valor de cinco chelines, tiene libertad de presentar su defensa,
y bajo garantía, se le concede la libertad hasta las siguientes sesiones,
lo cual es una práctica normal.
Nosotros también deseamos esta libertad, y esperamos, ya que es razonable,
que no se nos niegue, especialmente en esta ocasión,
dado que es probable que nos convirtamos en un precedente para otros.

[.discourse-part]
__Juez:__ No hay un gran asunto de ley en este caso; es sólo un asunto de hecho,
si has rechazado prestar el juramento o no.

[.discourse-part]
__Registrador:__ Señor Crook, no hay necesidad de ley o abogado en este caso;
por eso lo consideramos anoche y le enviamos un mensaje.
Se le dijo al guarda de la prisión que te dijera
que teníamos la intención de juzgarte hoy,
y luego ordenamos que el abogado fuera a verte si tú lo deseabas así. También
se le dijo al secretario que te diera una copia de la acusación. Eso es justo;
por tanto, procederemos a juramentar al jurado,
pues el asunto es sólo si te niegas a prestar juramento o no.
Por tanto, es en vano decir algo, porque el tribunal está decidido a juzgarte ahora; así,
pues, juramenta al jurado, pregonero.

[.discourse-part]
__John Crook:__ Espero que no intenten sorprendernos.

[.offset]
+++[+++Entonces los otros prisioneros (que también estaban acusados) gritaron:
"`Hágannos justicia,
y que el jurado no sea juramentado hasta que se nos haya escuchado primero.`"
Entonces se armó un gran alboroto, y estando el tribunal sumido en confusión,
algunos gritaban: "`¡Sáquenlos!`"
Otros: "`¡Quietos, déjenlos en paz!`"
Otros: "`¡Procedan a juramentar al jurado!,`" y el pregonero,
en ese alboroto y confusión, hizo algo para ese fin.
Entonces todos clamábamos por justicia y libertad hasta las siguientes sesiones.
El tribunal continuó en un estado de confusión, unos gritando una cosa y otros otra,
que ahora no puedo recordar, ni qué les dijimos a ellos, ni qué nos dijeron a nosotros.
El ruido era grande y las órdenes del tribunal a los oficiales eran diversas,
algunos les ordenaban que nos sacaran; otros que nos dejaran en paz;
otros que nos acercaran;
otros que nos devolvieran al lugar donde solían estar los delincuentes,
lo que nos obligaron a hacer.
Y en ese gran desorden y confusión que había entre ellos,
algunos hombres fueron juramentados para que testificaran
que nosotros nos habíamos negado a prestar el juramento,
algo que nosotros nunca hicimos positivamente.
Otros oficiales del tribunal (que ellos deseaban que juraran) se negaron hacerlo,
y aunque fueron presionados por el presidente del tribunal, quisieron ser excusados.
Entonces uno de los prisioneros habló de nuevo,
pero apenas se le pudo entender por causa del ruido en el tribunal.
Pero al dirigirse a la gente en voz alta a manera de exhortación,
algunos pudieron oír la sustancia de lo que dijo,
que ahora no se puede recordar en particular; pero en esencia,
expresó la presencia y amor de Dios para con él,
y exhortó a otros a que tuvieran en cuenta Su temor,
para que también pudieran llegar a conocer a Dios, etc.]

[.discourse-part]
__Juez:__ ¡Cállale la boca, verdugo! +++[+++Lo que fue hecho consecuentemente.]

[.discourse-part]
__Prisioneros:__ ¿No nos dejarán hablar por nosotros mismos?
Nosotros objetamos a algunos del jurado, al ser nuestros enemigos.
De hecho, algunos son los mismos hombres que ordenaron en contra de la ley,
que nos sacaran por la fuerza de nuestras reuniones,
y nos llevaron a prisión sin una orden judicial ni el debido proceso de la ley.
¿Serán estos ahora nuestros jueces?
Objetamos contra ellos.

[.discourse-part]
__Juez:__ Es demasiado tarde ya,
deberían haberlo hecho antes de que ellos fueran juramentados como jurado.
¡Jurado, reúnanse ahora!
Lo que deben determinar es si ellos se negaron a prestar el juramento o no,
sobre lo cual se ha jurado delante de ustedes que ellos se negaron.
No es necesario que se retiren del estrado.
+++[+++Palabras parecidas fueron pronunciadas por el registrador y otros,
mientras había confusión y ruido en el tribunal, y muchos hablaban al mismo tiempo.]

[.offset]
+++[+++Entonces clamamos por justicia y que fuéramos escuchados,
deseando hacer nuestra defensa antes de que el jurado diera su veredicto.
Pero el juez y registrador dijo que no seríamos escuchados, gritando de nuevo:
"`¡Cállales la boca, verdugo!,`" lo cual fue hecho consecuentemente, con un trapo sucio.
El verdugo también se esforzó por amordazarme, luchando por agarrar mi lengua,
y teniendo una mordaza lista en su mano para ese propósito;
y así fuimos tratados varias veces.
Entonces yo grité en voz alta:]

[.discourse-part]
__John Crook:__ ¿Nos van a condenar sin escucharnos?
Esto es tratar con nosotros peor que lo que hizo Pilato con Cristo.
Porque aunque él condenó a Cristo sin una razón,
aun así no lo hizo sin haberlo escuchado hablar por Sí mismo.
Pero ustedes nos niegan ambas cosas.

[.discourse-part]
__Juez:__ Que el Señor Gray venga al estrado.

[.offset]
+++[+++Al hacerse espacio, Isaac Gray fue conducido por un oficial al estrado interior,
donde le habló al tribunal para dicho efecto:]

[.discourse-part]
__Isaac Gray:__ Deseo saber, si según la ley y la práctica de este tribunal,
yo y mis compañeros de prisión tenemos libertad de poner una fianza,
a fin de procesar nuestra defensa en las próximas sesiones.

[.discourse-part]
__Tribunal:__ No, los juzgaremos en este momento.

[.discourse-part]
__Juez:__ ¡Cállales la boca,
verdugo! +++[+++Y ese era el grito de muchos de los miembros del tribunal,
al estar todavía en confusión. Algunos le gritaban al jurado: "`Den su veredicto,
porque no los escucharemos a ellos;`" junto con otras
palabras que no pudieron ser oídas debido al ruido,
pues el tribunal estaba en desorden.]

[.discourse-part]
__John Crook:__ Habría sido lo mismo que nos hubieran mandado a matar antes de llegar aquí,
que traernos aquí bajo el pretexto de juzgarnos y
no darnos la libertad de hacer nuestra defensa;
pero en lugar de eso,
ordenan que seamos lastimados así y que mantengamos las bocas calladas.
¿Se ha sabido de algo así antes?
¡Qué el justo Dios juzgue entre nosotros! ¿Me escucharán?
Ustedes a menudo han prometido que lo harían.

[.discourse-part]
__Juez:__ Escúchame y te escucharemos.
+++[+++Entonces él empezó a hablar y otros de los miembros del tribunal lo interrumpieron.
A veces dos o tres hablaban a la misma vez,
y había ruido entre los oficiales del tribunal.
Pero el juez dijo:]
Podemos darles libertad hasta las siguientes sesiones, pero es nuestra escogencia;
y por tanto, escogemos juzgarlos ahora.

[.discourse-part]
__John Crook:__ +++[+++Le pedí a la gente:]
Tomen nota de la promesa de ellos, que yo tendría libertad de hablar.
+++[+++Luego hablándole a los jueces:]
Miren, cumplan su palabra.

[.discourse-part]
__Juez:__ La ley de Inglaterra no sólo es justa, sino misericordiosa; por tanto,
no serán sorprendidos ni enredados,
sino que tendrán lo que la justicia de la ley permite.

[.discourse-part]
__John Crook:__ El juez acaba de decir que la ley de Inglaterra era una ley misericordiosa,
y el tribunal dijo que ellos podrían, si estaban dispuestos,
darnos libertad hasta las siguientes sesiones,
pero que no lo harían. La máxima de la ley es, _Summum jus est summa injuria,_
+++[+++Extrema justicia es extrema injusticia.^
footnote:[Una advertencia de que la aplicación de la ley al pie de la letra,
puede convertirse a veces en la mayor forma de injusticia.]]
Por tanto, espero que la práctica de ustedes esté de acuerdo con esta máxima,
y muestren que la ley de Inglaterra es una ley misericordiosa;
y que no ejecuten la _summun jus_ +++[+++extrema justicia]
sobre mí, y se condenen así ustedes mismos, por medio de sus propias bocas.

[.discourse-part]
__Juez:__ Jurado, dé su veredicto.

[.discourse-part]
__John Crook:__ Permítanme hablar primero, son sólo unas pocas palabras;
y espero hacerlo con la brevedad y pertinencia que mi entendimiento lo permita,
y esta ocasión requiere.
Es con respecto a estos dos temas: Cuestión de ley, cuestión de consciencia.
Con respecto a la cuestión de ley, tengo que decir lo siguiente: Primero,
en cuanto al estatuto mismo, fue hecho contra los papistas,
ocasionado por la '`conspiración de la pólvora`'^
footnote:[La _conspiración de la pólvora_ fue un intento
fallido de hacer estallar al rey James I y al Parlamento,
el 5 de Noviembre de 1605, dirigido por Robert Catesby,
quien trató de restaurar la monarquía católica.]
y se titula, "`Para el mejor descubrimiento y supresión de los papistas recusantes.^
footnote:[Es decir,
Católicos romanos no conformistas.]`" Pero ahora
estos tienen libertad y nosotros somos destruidos.
--+++[+++Interrumpido por los jueces y alteración del tribunal.]--
En cuanto a la cuestión de consciencia tengo algo que decir,
y es, que la consciencia es algo tierno,
y nosotros hemos experimentado lo que es ofenderla;
y es por esta razón que no nos atrevemos a quebrantar los mandamientos de Cristo,
quien dijo: "`No juréis en ninguna manera;`" y el apóstol Santiago dijo:
"`Pero sobre todo, hermanos míos, no juréis.`" --+++[+++Interrumpido.
El tribunal volvió a llamar al verdugo para que me tapara la boca,
lo que hizo consecuentemente con un trapo sucio, como se dijo antes,
y la mordaza en su mano.]

[.discourse-part]
__Juez:__ Oigamos al jurado.

[.offset]
+++[+++Entonces el jurado le dijo algo al juez, que se suponía era el veredicto.]

[.discourse-part]
__Juez:__ ¡Pregonero, haz silencio en el tribunal! +++[+++Entonces el registrador,
tomando un papel en su mano leyó:]

[.discourse-part]
__Registrador:__ El jurado del rey encuentra que John Crook,
John Bolton e Isaac Gray son culpables de negarse a prestar el juramento de lealtad;
por lo que incurren en la sentencia premunire,
que es la pérdida de todos sus bienes inmuebles durante sus vidas,
y sus bienes personales para siempre.
Ahora son puestos fuera de la protección del rey,
y estarán encarcelado durante el tiempo que él lo quiera.
Esta es la sentencia para ustedes.

[.discourse-part]
__John Crook:__ Pero todavía estamos bajo la protección de Dios.

[.asterism]
'''

Entonces los prisioneros fueron enviados a la prisión de Newgate,
donde John Crook encontró la oportunidad de hacer el relato de todo el juicio,
el cual fue impreso como ya se dijo, junto con la acusación en latín,
en la que mostró varios errores, ya fuera por expresiones erróneas, como por omisiones.
Así quedó expuesta a la vista pública la injusticia de estos procedimientos arbitrarios,
para que el rey mismo pudiera ver con ello cuán equivocadamente eran tratados sus súbditos.
Pero en ese tiempo había tantos hombres entre los líderes y obispos
que se inclinaban a promover el exterminio de los Cuáqueros,
que parecía no haber ayuda humana.
John Crook demostró también, específicamente,
cómo en muchos procesos del juicio habían actuado contra la ley;
porque él mismo habiendo sido anteriormente un magistrado,
conocía muy bien cómo y de qué manera se debía administrar y mantener la justicia.
No pude encontrar por cuanto tiempo estuvo prisionero.
Pero sólo por este juicio,
el lector puede ver cómo eran tratados los llamados Cuáqueros con respecto al juramento.
Este tipo de procedimientos fue la porción de muchos,
porque la intención del momento de quienes estaban
en autoridad parecía ser la eliminación de este pueblo.

Por medio de estos y tratos similares,
vemos cómo se esforzaban los perseguidores por erradicar a los Cuáqueros,
si les hubiera sido posible; para cuya realización,
el concejal Richard Brown hacía lo que podía,
soltando continuamente las riendas de su exorbitante malicia,
sin considerar si aquello contra lo que se inclinaba era realmente castigable o no,
de lo cual puede servir de prueba el siguiente ejemplo.

Cierto zapatero, que pertenecía a la sociedad de los Cuáqueros,
fue solicitado por un trabajador un séptimo día de la semana, a altas horas de la noche,
para que le remendara un par de zapatos,
a fin de que estuvieran listos de nuevo por la mañana,
ya que no tenía otros zapatos que ponerse.
El zapatero, para complacer al hombre, se quedó trabajando hasta después de medianoche,
pero como no pudo terminar el arreglo se fue a dormir,
y se levantó temprano por la mañana y regresó al trabajo tan privadamente como pudo,
en su habitación. Pero un vecino envidioso lo denunció por trabajar un Domingo,
por lo que fue llevado ante el mencionado Richard Brown,
quien lo encarceló en Bridewell para que lo sometieran a trabajos forzados.
Como se negó a golpear cáñamo,
al estar completamente convencido de que no merecía ese castigo, fue cruelmente azotado.
Pero él soportó con gran firmeza y como no cedió,
fue puesto entre los de su sociedad que estaban encarcelado ahí por motivos religiosos.

Así como este caso (que le sucedió a un hombre honesto) era digno de compasión,
por ese tiempo también sucedió algo entre los Cuáqueros en Londres igualmente ridículo.
Porque varios de ellos, habiendo sido sacados de sus reuniones religiosas,
fueron confinados en la prisión de Newgate,
en una sola habitación grande que tenía en el centro una gran columna.
Muchos amarraban un extremo de sus hamacas a esta columna,
y en la pared opuesta sujetaban el otro extremo, a todo alrededor de la habitación,
tres pisos de altura, una encima de la otra;
de modo que los que se acostaban en las filas de
arriba y del medio tenían que acostarse primero,
y estaban obligados a subir a las hamacas más altas metiéndose primero en las inferiores.
Y debajo del nivel inferior de las hamacas, había camas sobre el piso.
Tal multitud de camas para tantas personas en una sola habitación,
no podía más que contaminar el aire y provocar un ambiente insalubre;
de modo que muchos prisioneros se enfermaron y uno
de ellos murió. Esto causó cierta conmoción,
y cuando un ciudadano anciano y respetable vio a los prisioneros amontonados así,
no le faltó razón al decir:
"`Esto es suficiente para desatar una infección entre ellos.`"
Cuando se le contó esto a sir William Turner, uno de los alguaciles de Londres,
entró en Newgate y le mandó al carcelero que bajara a dichos prisioneros al patio,
y luego ordenó que los regresaran a Bridewell donde habían estado primero.

Entre estos había un tipo desvergonzado, quien, a fin de obtener comida sin trabajar,
se había metido entre los Cuáqueros cuando habían sido capturados en una reunión,
con el propósito de ser enviado a prisión y ser mantenido por ellos.
Este perezoso sinvergüenza no había sido una carga pequeña para nuestros prisioneros,
porque cada vez que les llegaba comida,
ya fuera porque la habían comprado con su propio dinero,
o les había sido enviada por sus amigos,
él no dudaba en clavar su cuchillo y hacer su propio corte.
Era tal su descaro, que si veía que las provisiones eran pocas,
se aseguraba de tomar lo suficiente para él, aunque a otros les faltara.
Pero, a pesar de que este holgazán era muy gravoso para los prisioneros,
no habían podido obtener alivio de él; porque, ¿a quién se quejarían?,
dado que los carceleros, así como los otros, estaban por afligirlos y oprimirlos.
Pero finalmente llegó una oportunidad de librarse de su
molesta compañía. Entre los prisioneros estaba Thomas Ellwood,
un hombre de letras y de agudo ingenio,
con quien (mucho tiempo después de esto) entablé
una familiar y agradable correspondencia por carta.
Cuando T. Ellwood oyó que ellos iban a ser enviados a Bridewell,
se acercó al alguacil y señaló al mencionado individuo, y dijo:
"`Ese hombre no sólo no es parte de nuestro grupo,
sino que es un tipo vagabundo y depravado,
que se metió entre nuestros amigos para vivir de ellos; por tanto,
deseo que no seamos molestados por él en Bridewell.`"

El alguacil, sonriendo y viendo al tipo de pie con el sombrero puesto,
tratando de verse tan serio como podía para que el alguacil lo tomara por un Cuáquero,
lo llamó y le dijo:
"`¿Cómo llegaste a prisión?`" "`Fui capturado en una reunión,`"
dijo él. "`Pero qué asunto tenías ahí,`" dijo el alguacil.
"`Fui a escuchar,`" replicó el tipo.
"`Sí, parece que fuiste con una peor intención que esa,`" contestó el alguacil,
"`pero te voy a decepcionar,
porque te voy a cambiar de grupo y te voy a enviar con los que
son más como tú.`" Entonces llamó al carcelero y le dijo:
"`Toma a este tipo y ponlo entre los delincuentes,
y asegúrate de que no moleste más a los Cuáqueros.`"
Este sujeto, no poco asombrado al oír su destino,
se apartó repentinamente de la compañía de los Cuáqueros;
pues se quitó su sombrero y empezó a inclinarse y a raspar el pie,^
footnote:[La forma de inclinarse consistía en raspar exageradamente
el pie derecho hacia fuera y por detrás del cuerpo,
para luego arrodillarse.]
y luego le dijo al alguacil: "`¡Su señoría, tenga compasión de mí y déjeme libre!`" "`No,
no,`" dijo el alguacil, "`no te decepcionaré. Dado que tenías en mente estar en prisión,
en prisión te quedarás.`" Entonces,
ordenándole una vez más al carcelero que se lo llevara,
lo subió y lo puso entre los delincuentes.
De este modo, este supuesto Cuáquero fue recompensado según sus actos;
y así se libraron de él los verdaderos Cuáqueros.

Termino ahora este chistoso relato, aunque cierto,
y regreso al relato serio de los sufrimientos de los fieles,
que provocaron la muerte de algunos de ellos.
Entre esos estaba Richard Hubberthorn,
quien un tiempo antes (como ha sido relatado) había tenido una conversación con el rey,
quien en ese momento le prometió que él y sus amigos no
sufrirían por sus opiniones o religión. Pero entonces,
en el mes llamado Junio,
R+++.+++ Hubberthorn fue violentamente sacado de la reunión llamada Bull and Mouth,
y llevado ante el concejal Richard Brown,
quien con sus propias manos haló el sombrero de Richard sobre su cabeza con tal violencia,
que llevó su cabeza cerca del piso, y luego lo envió a Newgate.
Ahí, amontonado entre muchos otros, pronto se enfermó, y su enfermedad se agravó tanto,
que apenas llevaba dos meses en prisión cuando se lo llevó la muerte.
Dos días antes de su partida, siendo visitado por algunos de sus amigos,
quienes le preguntaron si había algo en su espíritu que quisiera decir,
dijo que no había necesidad de discutir los asuntos,
porque conocía el fundamento de su salvación y estaba
convencido de su paz con el Señor para siempre.
También dijo: "`Conozco bien esa fe que ha obrado mi salvación,
y tengo una fundada convicción en ella.`"
Por la mañana antes de su deceso, una tal Sarah Blackberry estaba con él,
a quien le dijo: "`No trates de retenerme aquí, porque es demasiado confinado para mí,
y debo partir de este confinamiento; porque estoy partiendo hacia la libertad,
y voy a ser levantado en lo alto, por encima de todo.`"
En este estado de ánimo partió de esta vida, al atardecer,
y así entró con felicidad en la eternidad.
