== Capítulo XVI

[.section-date]
1664--1667

Continuación de la persecución bajo la Ley de los Conventículos--Relato
de los padres del autor--"`Epístola a los Amigos de la Verdad`"--Seiscientos
Amigos en las cárceles de Inglaterra--Algunos de los desterrados son desembarcados
por los capitanes de los barcos--No se permite que los barcos naveguen
hacia las Indias Occidentales sin llevar a los Cuáqueros desterrados--Plaga
en Londres--Otros juicios y destierros de Cuáqueros--I. Penington,
sobre la persecución--G. Fox y Margaret Fell de nuevo juzgados y castigados con la sentencia
de premunire--Traslado de G. Fox al castillo de Scarborough--Interesantes entrevistas--Incidentes
en la vida de W. Dundas--Muerte de W. Caton--Muerte de muchos Amigos desterrados a bordo
del barco--Capturados por un corsario--G. Fox y el Dr. Cradock--G. Fox liberado--Gran
incendio en Londres--T. Ibbitt--Epístola de S. Crisp--Persecución de W. Armorer--Muerte
de R. Farnsworth--Robert Barclay--Perseguidores de M. Halhead.

En Diciembre, de nuevo, doce de los llamados Cuáqueros fueron condenados al destierro;
porque se había resuelto continuar,
a pesar de lo que George Bishop había publicado en forma impresa,
y había hecho que se entregara al rey y a los miembros del Parlamento, lo cual decía:

Para el rey y ambas Cámaras del Parlamento, el Señor dice esto:

"`No se entrometan con mi pueblo por causa de sus consciencias para Conmigo,
y no los destierren de la nación por sus consciencias; porque si lo hacen,
enviaré Mis plagas sobre ustedes, y ustedes sabrán que Yo soy el Señor.`"

Escrito en obediencia al Señor, por Su siervo,

George Bishop,

Bristol, 29 del mes Quinto de 1664.

Veremos el cumplimiento de esta predicción,
porque en un corto tiempo se produjo una guerra contra los Holandeses,
y apareció la peste^
footnote:[La Gran Peste de 1665 fue el peor brote de peste bubónica en Inglaterra
desde la muerte negra de 1348. Se calcula que la peste mató a 100.000 personas,
casi una cuarta parte de la población de Londres, en 18 meses.]
en Londres.
Pero antes de que estallara la plaga,
más de los Cuáqueros encarcelados fueron condenados al destierro, a saber,
treinta y dos personas, hombres y mujeres, que fueron sentenciados por el tribunal el 6,
14 y 15 de Diciembre; pues todo lo que dijeron en defensa de sí mismos resultó inútil.
Uno preguntó: "`Si nosotros nos reunimos verdaderamente para adorar a Dios,
¿debemos sufrir por ello?`"
El juez Hide respondió: "`Sí, deben sufrir.`"
Pero el juez Keeling, a fin de enmendar un poco el asunto dijo:
"`No deben sufrir por adorar a Dios,
sino por estar en una asamblea ilegal contraria a la ley.`"
Otro dijo: "`Yo me reúno para adorar al Dios eterno en Espíritu,
como Él persuade mi corazón y mi consciencia;
¿y debo ser condenado al destierro por ello?`"
"`Sí, sí,`" dijo el juez Keeling, "`porque la ley está en contra.`"
A lo que el juez Twisden agregó:
"`Aquí él ha confesado que estaba ahí para adorar a Dios;
y la adoración de ellos es contraria a la liturgia de la iglesia de Inglaterra.`"
Así vemos, que si había evidencia de que los prisioneros habían estado en una reunión,
era motivo suficiente para condenarlos.
A una mujer que se le preguntó, qué tenía que decir ante la evidencia dada, respondió:
"`Sepan todos ustedes, que si yo tuviera tantos cuerpos como cabellos en mi cabeza,
los entregaría todos por la verdad eterna y viva del Dios vivo.`"
Después de que todos los prisioneros fueron llamados al estrado,
fueron finalmente condenados a ser transportados
a Jamaica y a permanecer ahí por siete años.

En Septiembre de este año (1664) murió mi madre, Judith Zinspenning, en Ámsterdam,
Holanda, donde había nacido de padres religiosos que se contaban entre los Bautistas,
en cuya sociedad había entrado de manera inusual su padre Conrad Zinspenning.
Y aunque parezca que me salgo un poco de mi camino,
por causa de los notables pasos de la Providencia que aparecen en éste,
daré un breve relato de él. Siendo de Colonia, Alemania, fue criado como Papista,
y después de que había pasado por las escuelas de latín,
su padre lo metió en un claustro (porque los Papistas de ahí solían
considerar meritorio ofrecer al clero a uno de sus hijos).
Su padre murió antes de que se cumpliera su año de prueba,
y al encontrar él la vida monástica muy en contra de su inclinación,
le rogó a su madre que lo ayudara en su intención de dejar la fraternidad,
dado que él aún no estaba obligado por los votos.
Ella accedió a su deseo, y salió, y luego fue colocado como aprendiz.
Después de cumplir su tiempo resolvió viajar, y primero viajó a Holanda,
de ahí a Francia, luego a Italia, a Roma la capital, y de ahí regresó a su casa.
Habiendo sido un fraile laico,
obtuvo cartas de recomendación para los monasterios que
eran de la orden de los monjes con los que él había vivido,
para que a veces pudiera encontrar en ellos alojamiento gratuito.
Pero como le había gustado mucho Holanda, decidió quedarse ahí por un tiempo;
lo que hizo, llegando con el tiempo a vivir con un Bautista que lo empleó como jornalero.

Hasta entonces, él nunca había tenido un Nuevo Testamento,
pero al comenzar a leerlo con mucha avidez, y el Señor a cooperar con Su buen Espíritu,
su entendimiento se abrió y obtuvo una clara visión de las supersticiones
y errores de la religión Papista en la que había sido criado.
Finalmente, conversando con su maestro,
fue persuadido a renunciar al papismo y a entrar en la comunión de los Bautistas.
Esto le puso fin a todos sus planes con respecto a sus futuros viajes,
y al decidir establecerse donde estaba, tomó como esposa a una tal Catherine de Mol,
una joven virtuosa,
cuyo padre había sido uno de los primeros Bautistas
que se levantaron bajo la persecución en Flandes,
de donde él con muchos otros llegaron a establecerse en Holanda.
De estos padres descendía mi madre,
quien desde su juventud tenía inclinaciones religiosas,
y llegó a ser muy versada en las Sagradas Escrituras.
Era tan diligente en escribir de memoria muchos de los sermones que oía,
que su padre a veces decía: "`Es una pena que esta niña no sea un chico,
porque con el tiempo habría podido llegar a ser un eminente instrumento en la iglesia.`"

Después de que llegó a la mayoría de edad,
aunque más inclinada a llevar una vida de soltera, al final se casó con mi padre,
Jacob Williamson Sewel, un joven muy religioso,
que se esforzaba por caminar en el camino estrecho,
y sostenía conversaciones especialmente con los más estrictos profesantes
de esos días. El nombre de su padre era William Sewel,
de Kidderminster, en Worcestershire,
uno de los Brownistas que dejó Inglaterra y se estableció en Holanda;
ahí se casó con una holandesa de Utrecht, donde nació mi padre.
Con el tiempo, tanto mi padre como mi madre,
se empezaron a sentir insatisfechos con la adoración a la que se habían unido;
aunque mi madre excedía a mi padre en claridad de entendimiento.
Sin embargo,
ella seguía insatisfecha (al igual que él) con la
forma de adoración común a la que pertenecía,
de modo que a menudo, cuando regresaba a la casa después de la reunión,
decidía no volver más,
diciendo que ella no cosechaba ningún beneficio real ni sustancial por ello.

No obstante, cuando llegaba otra vez el Primer-día, ella estaba en apuros,
pensando que independientemente de cómo fuera la adoración de ellos,
hemos sido exhortados por el apóstol a no dejar de congregarnos.
En esta indecisa condición continuó largo tiempo,
y al estar agobiada por los cuidados de la familia,
no tenía tanta libertad para realizar tareas religiosas (es decir, orar,
leer y meditar en las Sagradas Escrituras, visitar a los enfermos,
y similares ejercicios piadosos), como hacía antes de casarse.
Esto a veces la hacía desear no haberse casado,
y volver a poder vivir y disfrutar aquella paz y quietud que alguna vez había conocido.
Pero ella todavía no sabía que era el amor del Señor el que estaba obrando así,
para apartarla de todas las cosas transitorias.
En este estado, a menudo se apoderaban de ella el dolor y la tristeza,
y se llegaba a considerar la más miserable de las mujeres, porque ni el esposo,
ni los niños, ni ningún disfrute externo le proporcionaban ningún placer,
pues todo su deseo era un estado inmaculado en el que pudiera vivir una vida irreprochable,
no sólo delante de los hombres,
sino delante de Dios también. Porque sintiendo que
todavía había algo en ella que era malo y contaminante,
luchaba por vencerlo, pero toda su labor resultaba en vano.
Esto la hacía clamar fervorosamente al Señor, como una persona que está en gran peligro,
y se incrementaban sus dudas sobre si era posible alcanzar tal perfección.

Sin embargo,
en este estado de desolación le plació al Señor manifestarse a ella en alguna medida,
aunque en ese entonces ella no sabía que era Él. A menudo clamaba: "`¡Señor,
¿de qué me sirve saber que Tú enviaste a Tu Hijo al mundo,
que fue crucificado y murió por los pecados del mundo, si yo no soy salva por ello?
Señor, perdona mis pecados y ten misericordia de mí!`" Y una vez que estaba sola,
derramando su corazón delante del Señor, Él se dio a conocer a ella y le habló a su alma,
diciendo, que si ella deseaba ser perfecta, debía seguir Su luz en todos los aspectos.
Después de oír esto, ella quería saber qué era esa luz,
y el Señor le mostró que la '`luz era la vida de los hombres.`'^
footnote:[Juan 1:4]
Esto lo entendió en alguna medida,
y por ello se separó tanto como convenientemente podía de la interacción con otros,
esforzándose por vivir más retiradamente.
Por este tiempo,
oyó al Dr. Galenus Abrahams (un eminente maestro
Bautista) predicar sobre la parábola del sembrador,
y lo que él dijo con respecto a la buena tierra,
y que la tierra debía ser acondicionada por la obra del Señor, la afectó tanto,
que decidió descansar de su propia labor,
y dejó de frecuentar las asambleas de los Bautistas.

En este estado de retiro continuó un buen tiempo,
y finalmente fue a oír a William Ames predicar;
él declaró que la luz de Cristo era el verdadero maestro,
y eso concordó con lo que las manifestaciones directas
del Señor ya le habían dado a conocer internamente.
Así llegó a estar completamente convencida,
de que esta era la verdad que por tanto tiempo había deseado conocer,
y vio claramente que su deber era renunciar a todo y no retener nada;
porque ya había visto que si quería ser discípula de Cristo, debía abandonarlo todo,
incluso su propio yo.
Y aunque el temor a la cruz era un gran impedimento para ella, se rindió en obediencia,
y pronto vio que sus actuaciones anteriores habían sido defectuosas,
y luego todos los fallos anteriores le llegaron claramente a la memoria.
Esto le causó tristeza, pero oraba al Señor de día y de noche; y entonces,
Él manifestó Su poder por el que fue sacada de las tinieblas
y de la esclavitud en la que había estado cautiva.
Ella le suplicaba al Señor que las cosas no fueran como antes, a saber,
que a veces tenía un gran celo y a veces una gran frialdad de nuevo;
sino que pudiera continuar con espíritu ferviente.
Después de un largo tiempo de lamento, el Señor le manifestó Su bondad,
mediante la cual fue vivificada y refrescada; y por medio de los juicios del Señor,
todo fue minuciosamente escudriñado y nada pudo ser escondido;
fue hecha una separación entre lo precioso y lo vil, y la muerte pasó sobre todo.
Pero separarse de su propia sabiduría y abandonar sus grandes logros,
no fue una cruz pequeña. Sin embargo, estuvo dispuesta a llevarla,
aunque se levantaron muchas violentas tempestades para arrastrarla
(si era posible) de la estrecha adhesión al Amado de su alma.

No obstante, no se apresuró a imitar a ningún hombre;
pues cuando mi padre fue convencido de la verdad predicada por W. Ames y W. Caton,
pronto dejó la forma común de saludo,
y a veces trataba de convencerla con argumentos para que hiciera lo mismo,
pero ella le decía, que si abandonar la costumbre era algo que el Señor demandaba,
ella creía que Él se lo mostraría a Su debido tiempo,
porque ella se había entregado a seguir Sus requerimientos.
Y como ella continuó con celo y fidelidad,
le plació a Él después de la muerte de mi padre, darle un testimonio público,
y llegó a estar notablemente dotada;
pues sus habilidades naturales superaban las cualidades ordinarias de su género.
Y conforme se santificaba más por el Espíritu del Señor,
no podía sino causar buenos efectos,
de modo que llegó a ser muy visitada y buscada por profesantes, e incluso,
los hombres de la Quinta Monarquía aplaudían sus sinceras amonestaciones.
Pero ella estaba por encima de las adulaciones y las pisoteaba.
En realidad, era tan estimada,
que recuerdo una vez que se sintió movida a visitar a los universitarios en su reunión,
y después de que uno de ellos terminó de hablar,
se puso de pie y dijo que ella tenía algo en su mente que decirles a manera de
exhortación. Pero sabiendo que no les permitían a las mujeres hablar entre ellos,
no quiso entrometerse bruscamente, sino que les pidió permiso,
y se lo concedieron de buena gana, y unos de sus principales oradores le dijo:
"`Es verdad, amiga, no les permitimos a las mujeres hablar en la iglesia, sin embargo,
te tenemos tanto respeto, que te concedemos la libertad de hablar.`"
Entonces, descargó su consciencia delante de ellos,
habiendo frecuentado con anterioridad esa asamblea.
Y cuando terminó de hablar, no recuerdo que nadie la contradijera,
sino que uno de los oradores terminó la reunión con una oración.

Antes de ese momento,
ella había escrito y publicado un pequeño libro a los de su antigua sociedad,
el cual tituló, Serious Reproof of the Flemish Baptists^
footnote:[Seria Reprensión a los Bautistas de Flandes.],
en el que trataba muy claramente con ellos y les mostraba cómo habían apostatado.
También escribió algunos otros tratados, todavía impresos,
y era muy amada y muy estimada por sus amigos ingleses,
como se desprende de varias cartas que le escribieron desde Inglaterra.
Los de su propia nación a menudo acudían a ella en busca de instrucción,
ya que tenía tanta experiencia en el camino del Señor,
que era capaz de decir una palabra oportuna para diversas condiciones.
Visitó muchas veces las reuniones en Alkmaar, Haarlem y Rotterdam,
y sus amigos la invitaban con frecuencia a ir y edificarlos con su don.
También escribió muchas cartas para la edificación y amonestación de personas en particular,
y algunas epístolas para la iglesia.
Pero le plació al Señor tomarla para Sí, temprano.
Cuando se enfermó, pronto tuvo la sensación de que era probable que no se recuperara,
por tanto,
me habló mucho en privado y me puso al corriente
de varias cosas que tenían que ver conmigo,
y con sus bienes externos.
La noche antes de su partida,
me llamó al lado de su cama y me exhortó muy fervientemente
a apartarme del mal y temer al Señor;
lo cual, por la misericordia de Dios,
con el tiempo causó una muy profunda impresión en mi mente,
por lo que todavía encuentro razones para bendecir el nombre
del Señor por haber sido hijo de tan excelente madre.
Temprano a la mañana siguiente, cuando sintió que se aproximaba la muerte,
hizo que me levantara de mi cama,
y me envió a buscar a su hermano y a William Caton para que vinieran a verla,
y al regresar,
escasamente había pasado un cuarto de hora cuando partió de esta vida y durmió en paz.

Para dar un pequeño ejemplo de su verdadero celo a Dios,
insertaré aquí la siguiente epístola que les escribió a sus amigos,
para despertar la mente pura en ellos.

Epístola a los Amigos de la Iglesia

Gracia y paz sean multiplicadas entre ustedes, mis queridos y muy amados Amigos,
quienes han recibido la bendición de Dios el Padre celestial en Cristo Jesús,
el Señor de gloria, quien por Su indescriptible amor y Su inmutable luz,
los ha sacado de toda adoración imaginaria y llevado a conocer en medida,
Al que era desde el principio.
Queridos Amigos, manténganse en la luz con la que son alumbrados,
y en el conocimiento de Dios que cada uno ha recibido para sí mismo;
velando contra la seducción de Satanás, para que sus ojos se mantengan abiertos,
y no prevalezca el engaño en ninguno de ustedes,
por el que se pierde la verdad y se oscurece el brillo del Señor.

Aunque joven, les escribo estas cosas en el verdadero amor,
como alguien que tiene cuidado de ustedes.
El Señor sabe cuán a menudo están ustedes en mi memoria,
deseando que no sólo conozcan la verdad, sino que sean testigos vivos de ella.
Porque conociendo lo preciosa que es,
no puedo sino desear que otros también participen de ella.
Por tanto, trabajen por ella, mis Amigos,
para que cuando el Señor venga y arregle cuentas con ustedes,
cada uno sea hallado fiel según lo que ha recibido.
Porque este es el talento que el Señor ha dado, es decir,
el conocimiento del que es verdadero y que recompensa a cada uno según sus obras.
Pero el siervo negligente y perezoso dijo que su Señor era un amo duro,
y que recogía donde no había sembrado; esa fue su condenación, pues el Señor le dijo:
"`Tú sabías que yo era un hombre severo; ¿por qué, entonces,
no pusiste mi dinero en el banco, para que al regresar yo,
hubiera podido recogerlo con intereses?`"

Tengan en cuenta estas cosas, mis amados Amigos, ustedes que tienen oído para oír,
y busquen el significado de esta parábola en ustedes mismos.
Porque todos hemos recibido talentos, algunos más, otros menos.
Por tanto, que cada uno sea fiel al Señor según lo que ha recibido;
porque yo en verdad creo, que algunos de ustedes han recibido cinco talentos.
Sólo hay que considerar debidamente y ver en la luz del Señor,
el conocimiento que han tenido del Dios eterno, más allá del de muchos otros.
¿Cuántas veces se ha aparecido el Señor y se ha manifestado claramente?
¿Cuán abundantemente ha dado a conocer en sus corazones
que Él es digno de ser temido y servido?
En verdad, este es un talento grande y de peso,
y por eso el Señor puede decir con justicia:
'`¿Qué más habría podido hacer Yo por Mi viña?`' Oh, mis Amigos, y además de todo esto,
Él ha hecho que Su luz eterna brille en nuestros corazones,
por la que hemos visto los caminos corruptos del
mundo y las sendas que conducen a la muerte.
Esto, digo yo, nos lo ha mostrado el Señor por Su luz eterna.
¡Gloria y alabanzas sean dadas a nuestro Dios para siempre!

Queridos Amigos, continúen en esta luz en la que han comenzado;
porque puedo dar testimonio del Señor,
de que Su amor ha sido abundantemente derramado sobre nosotros, sin acepción de personas.
Porque los que Le temen y obran justicia son aceptables para Él;
y Él hace que Su verdad se manifieste entre nosotros,
y que Su paz y Su misericordia descansen sobre nosotros.
Es cierto que Satanás no cesa en sus intentos de dispersarnos
y de sembrar dudas e incredulidad en nuestros corazones;
pero al mantenernos cerca del Señor somos preservados de sus trampas;
y feliz aquel que ha encontrado un lugar donde es libre de las tempestades.
Pero antes de encontrar ese lugar seguro,
hay muchas rocas escondidas que pueden ser fácilmente golpeadas,
que no son desconocidas para mí,
y por eso tengo verdadera compasión por todos los que no las han pasado con seguridad;
porque cualquiera de estas rocas puede resultar en un naufragio.

Sin embargo,
en todo este peligro hay algo en lo que podemos descansar
con seguridad y en lo que podemos confiar,
algo que es como un faro; a saber, la luz que brilla en nuestros corazones,
aunque a veces no sea más que una chispa,
y tan pequeña en comparación con las múltiples seducciones del enemigo,
que apenas se puede discernir.
Aquí, entonces, se experimenta una cantidad no pequeña de dolor y angustia;
aquí todas las misericordias del Señor (que anteriormente disfrutamos
en abundancia) son cuestionadas y puestas en duda;
aquí hay peligro, y sin embargo, hay certeza; porque al no pecar,
el faro puede ser seguido, y al descansar en una verdadera esperanza de ser salvados,
somos preservados en la tempestad.
Escribo estas cosas para información de los que están
viajando hacia esa ciudad que tiene fundamentos,
y cuyo arquitecto y constructor es Dios.
Hacia estos se extiende mi amor,
y mi deseo ante el Señor por ellos es que sean guardados
por Su poder y que permanezcan firmes en Su venida.

Queridos Amigos, mantengan sus reuniones en el temor del Señor,
y cuiden que sus mentes no sean arrastradas en pos de palabras externas;
sino permanezcan crucificados a eso que desea refrescamiento de afuera.
Y si en algún momento sienten muy poco refrescamiento,
no dejen entrar en sus corazones que el Señor no se interesa por ustedes,
sino vuélvanse al interior y céntrense en Su luz pura, y permanezcan quietos en ella.
Entonces,
tal vez encuentren la causa por la que la presencia del Señor se ha alejado por un tiempo,
y al quitar la causa, vuelvan a disfrutar del Señor para gran consuelo de ustedes.

Que el Dios Todopoderoso los guarde a todos por medio de Su poder,
para que no haya entre ustedes ninguna contienda o discordia, y puedan crecer en amor,
y de ese modo, se vean obligados a llevar las cargas los unos de los otros.
No dejen que las cosas transitorias estorben sus corazones, sino ríndanse al Señor;
porque a lo que hemos sido llamados,
no puede compararse con lo que es transitorio o perecedero.
En verdad, la parte más gloriosa de este mundo no es más que vanidad de vanidades.
¡Oh, mis Amigos, que ninguno se vea obstaculizado por algún impedimento,
de entrar en el reino de los cielos, sino esfuércense por entrar por la puerta estrecha!
Cada uno de ustedes escudriñe su propio corazón con la luz con la que han sido alumbrados,
la cual les manifestará sus verdaderos estados; y al permanecer en ella,
multiplicará la paz en ustedes y la encontrarán ser su propio maestro,
como han experimentado todos los que han buscado al Señor con todo su corazón.

Que el Dios de toda misericordia, el único inmortal,
los guarde a ustedes y a nosotros juntos hasta el fin,
para que en estos tiempos peligrosos podamos permanecer
firmes para la gloria de Su gran nombre.
Oh, Amigos,
mantengan lejos toda astucia y no entren rápidamente en
conversaciones con los que están fuera de la verdad,
porque ellos hablan en sus propias voluntades y son astutos,
y al no experimentar freno en sus mentes, atrapan al simple e inocente.
Más bien, manténganse en la luz en la que pueden ver sus sutilezas, porque entonces,
aunque no tengan una sola palabra para defenderse, permanecerán por encima de ellos.

Esto es escrito en amor a ustedes, de una planta joven,
según el don recibido del Señor. Mi saludo es para todos ustedes en la luz de la verdad.

Judith Zinspenning.

En el año 1664,
salió impreso un pequeño libro dirigido al rey y a ambas cámaras del Parlamento,
en el que no sólo se exponía la violenta persecución que tenía lugar en casi todo Inglaterra,
con los nombres de las personas, lugares y casos (que por cierto,
eran deplorables y algunos sangrientos), sino que también se mostraba que en ese momento,
había más de seiscientas personas del pueblo llamado Cuáqueros en prisión,
simplemente por causa de la religión.

En el mes llamado Enero del año 1665, treinta y seis de dicha persuasión,
entre ellos ocho mujeres, fueron condenados a ser transportados a Jamaica.
El jurado,
que no estaba tan dispuesto a declarar a los prisioneros culpables como deseaba el tribunal,
fueron persuadidos sin embargo, por las amenazas del juez Keeling,
el registrador Wild y el escandaloso Richard Brown, a hacer lo que se les exigía.

Los días 18 y 22 del siguiente mes,
treinta y cuatro del mencionado pueblo fueron sentenciados a ser transportados a Jamaica,
y cinco a Bridewell.
Paso por alto los detalles de sus juicios, para evitar la redundancia.
Los que fueron juzgados el día 18 fueron sentenciados por el juez Wharton,
y los del día 22 por el juez Windham.
Una tal Anne Blow,
declarando que por el temor del Señor que estaba en su corazón
no se atrevía a conformarse a algo que fuera injusto,
el juez Windham replicó: "`Anne Blow,
te mostraré tanto favor como el tribunal te lo permita,
si dices que no irás más a esa reunión sediciosa,`" refiriéndose a la de Bull and Mouth.
A esto ella respondió: "`¿Quieren que peque contra Dios en mi propia consciencia?
Si yo fuera puesta en libertad hoy, y el Señor me lo exigiera,
iría a Bull and Mouth mañana.`"

Con respecto a un tal John Gibson,
el mencionado juez le habló al jurado de la siguiente manera: "`Caballeros,
si bien es cierto, como dice Gibson,
no se puede probar que ellos estuvieran haciendo algún mal en Bull and Mouth,
aun así fue una transgresión que se reunieran ahí,
porque con el paso del tiempo se podría hacer mal en dichas reuniones.
Por eso se dictó esta ley para impedirlas.`"
De esta manera,
podemos ver con que colores engañosos encubrían los perseguidores sus acciones.
Encuentro entre mis papeles una carta de John Furly
y Walters Miers (a quienes conocí bien),
en la que se menciona que algunos miembros del jurado,
por negarse a dar el veredicto que se les exigía,
fueron multados con una gran suma y enviados a prisión hasta que la pagaran.

Habiendo dicho mucho de sus sentencias,
ha llegado el momento de hablar de las ejecuciones de estas.

Algunas de las personas sentenciadas al destierro se enfermaron y murieron en prisión;
algunas se convirtieron en apóstatas,
y algunas fueron redimidas por parientes que no eran Cuáqueros.
Sin embargo, un considerable número, aunque con gran pena,
fue llevado a bordo de un barco para ser transportado a las Indias Occidentales.
Ya hemos visto cómo los que fueron sentenciados en Hertford por el juez Orlando Bridgman,
regresaron a casa tras haber sido puestos en tierra por el capitán del barco.
No mucho después de esto, tres de los amigos de estos,
estando a bordo del barco llamado The Many-Fortune de Bristol,
también fueron puestos en tierra con un certificado del capitán del barco,
firmado por él y siete de sus hombres,
en el que declaraban que Dios les había hablado (por así decirlo) en sus corazones:
"`Maldito el hombre que separa a esposo y esposa, y oprime al pueblo de Dios,
porque muchas plagas vendrán sobre él.`"

Pero los primeros de los llamados Cuáqueros que realmente probaron el destierro fueron,
Edward Brush y James Harding,
quienes fueron desterrado no sólo de Londres (donde como ciudadanos
tenían tanto derecho a vivir como los principales magistrados),
sino también de sus condados natales,
en contra del derecho de un ciudadano inglés. Estos dos hombres,
junto con un tal Robert Hays,
el 24 del mes llamado Marzo fueron sacados temprano
en la mañana de la prisión de Newgate en Londres,
y llevados a las escaleras de Blackfriars,
donde fueron puestos en un bote y transportados a Gravesend,
y ahí colocados a bordo de un barco.
Apenas se les había dado aviso a estos prisioneros; y Robert Hays que no se sentía bien,
no había comido nada antes de llegar a Gravesend, y dado que esa mañana estaba muy fría,
cayó enfermo en el barco de una enfermedad tan grave que murió por ella,
y su cadáver fue llevado a Londres y sepultado ahí.
Los otros dos hombres fueron llevados a Jamaica,
donde, por la providencia de Dios, con el tiempo les fue bien,
y Edward Brush vivió para regresar a Inglaterra.
No obstante, fue notable, que no mucho después de que estas personas fueran desterradas,
estalló una gran pestilencia en Londres, que comenzó en una casa en Bearbinder-lane,
al lado de la casa donde vivía el mencionado Edward.
Algunos pensaron que esto era digno de ser mencionado,
ya que esa casa fue la primera en ser cerrada por causa de la plaga.

Con los otros prisioneros tuvieron más problemas y molestias,
porque no se encontraban capitanes que estuvieran dispuestos a llevarlos.
Por tanto, se les impuso una restricción a todos los comerciantes,
con la orden de que ninguno podía ir río abajo sin tener un pase del Almirante,
y dicho pase no se lo darían a ningún capitán que se dirigiera a las Indias Occidentales,
si no prometía llevar algunos Cuáqueros junto con él al lugar de su destierro.
Cualquier cosa que hayan dicho los capitanes contra esto,
indicando que había una ley según la cual ningún ciudadano inglés
podía ser llevado fuera de su país natal en contra de su voluntad,
fue en vano.
Finalmente, consiguieron, por la fuerza, que uno cumpliera lo que se habían propuesto,
y el día 18 del mes llamado Abril,
siete personas que habían sido sentenciadas al destierro fueron
llevadas de la prisión de Newgate a las escaleras de Blackfriars,
y de ahí a Gravesend en un bote.
Mientras tanto, la peste se acrecentaba en Londres, y no muchos después, el juez Hide,
que había sido muy activo en la persecución, fue, junto con muchos otros,
repentinamente retirado de esta vida.
Después de haber sido visto por la mañana en Westminster,
en cuanto a su apariencia exterior, en buen estado de salud,
se dijo que esa misma tarde había sido hallado muerto en su recámara;
siendo citado a comparecer y a dar cuenta de sus actos delante
de un Tribunal superior a todos los que él había presidido.

Pero a pesar de este azote del cielo, el destierro aún no había llegado a su fin.
Como se ha dicho, primero tres personas, luego siete, y luego,
el 16 del mes llamado Mayo,
ocho más fueron llevadas río abajo a Gravesend y puestas a bordo de un barco.
Pero así como se incrementaba el número de los que
eran transportados más allá de los mares,
también se incrementaba el número de los que morían por la pestilencia.
Sin embargo, finalmente se encontró a un capitán de barco que dijo, según lo informado,
que él no dudaría en transportar a nadie, así fuera a uno de sus más cercanos parientes.
Entonces se llegó a un acuerdo con él para que subiera
a su barco entre cincuenta y sesenta Cuáqueros,
y los llevara a las Indias Occidentales.
Así, pues, fueron llevados a la orilla en grupos de ocho o diez, y con botes o barcazas,
los transportaron al barco que estaba anclado en el Támesis, en Bugbey`'s-hole,
un poco más allá de Greenwich.
Muchos de estos prisioneros, entre quienes había varias mujeres,
no se mostraron dispuestos a subir al barco,
para que no pareciera que contribuían con su propio transporte,
por lo que tuvieron que izarlos con aparejos.
Como los marineros se mostraron reacios a hacer ese trabajo,
y dijeron que si se hubiera tratado de los bienes de un
comerciante no habrían tenido reparos en izarlos así,
los oficiales se apoderaron de los aparejos y dijeron: "`Ellos son bienes del rey.`"
Esto sucedió el 20 del mes llamado Julio, y el 4 del siguiente mes, cuando,
según la cuenta de mortalidad,
habían muerto tres mil cuarenta personas en una semana por causa de la peste,
el resto de los prisioneros desterrados fue llevado por soldados al mencionado barco,
en el que entonces había cincuenta y cinco Cuáqueros desterrados,
y entre ellos dieciocho mujeres.
Pero algo adverso impidió que este barco se hiciera a la mar,
y cuando se descubrió que la peste había llegado al barco,
la que rápidamente le quitó la vida a muchos de los prisioneros,
el resto fue liberado del destierro.

Sin embargo, aunque la peste se intensificó aún más en Londres,
y había estallado una guerra entre Inglaterra y Holanda,
el fuego de la persecución continuó ardiendo,
y no dejaron de perturbar las reuniones de los llamados
Cuáqueros y de encarcelar a muchos de ellos.
En realidad,
algunos de estos perseguidores estaban tan endurecidos y eran tan implacables,
que cuando en una semana murieron más de cuatro mil personas en Londres,
dijeron que la única manera de detener la plaga era sacando del país a los Cuáqueros.

En Setiembre,
algunas de las reuniones de este pueblo continuaron siendo perturbadas en Londres,
aunque el número de muertos en una semana había ascendido a más de siete mil.
A los que intentaban reunirse en Bull and Mouth se les impedía entrar a su casa de reunión,
pero al reunirse en la calle, no se les molestaba,
porque para entonces se había levantado cierto temor entre la gente común,
y muchos estaban descontentos porque los comerciantes ganaban poco dinero.
Por otro lado, la ciudad llegó a estar tan vacía,
que la hierba empezó a crecer en las calles que una vez habían estado llenas de personas,
y se veían pocas ir y venir.
Así, pues, la ciudad se convirtió en un desierto, y la miseria era tan grande,
que se creía que algunos habían muerto por falta de atención.

Fue por esta época que Samuel Fisher murió piadosamente en prisión.
Primero había estado encarcelado en la prisión de Newgate,
en Londres, y desde principios del año 1663 hasta este momento en Southwark,
aproximadamente un año y medio.

Se cuenta, que en una ocasión durante el tiempo de esta gran mortalidad,
el rey preguntó si alguno de los Cuáqueros había muerto por la plaga.
Y como se le dijo que sí, pareció menospreciar la enfermedad y luego concluir,
que no se podía considerar que era un juicio o plaga sobre sus perseguidores.
Pero de seguro, sus capellanes podrían haberle hecho recordar aquel dicho de Salomón:
"`Un mismo suceso ocurre al justo y al impío;`"^
footnote:[Eclesiastés 9:2]
y este dicho de Job: "`Al perfecto y al impío él los consume;`"^
footnote:[Job 9:22]
y también el del profeta: "`...de delante de la aflicción es quitado el justo.`"^
footnote:[Isaías 57:1]

Los viajes por el país se detuvieron entonces,
lo que hizo que algunas personas fueran con botes a lo largo de la costa,
y bajaran a tierra donde quisieran.
Así hizo Stephen Crisp, quien llegó a York por este tiempo,
donde el duque de York estaba entonces con muchos de los grandes.
Por este tiempo llegaron a Londres Alexander Parker y George Whitehead,
donde realizaron un buen servicio predicando la verdad.

Por esta época se prendieron grandes fuegos en las calles con la
intención de purificar el aire contaminado por la peste,
pero no se encontró ningún alivio,
porque a finales de Septiembre murieron en Londres más de ocho mil personas en una semana,
como recuerdo haber visto en uno de los reportes de mortalidad de ese momento.
Mientras tanto,
el barco en el que se encontraban los prisioneros desterrados no podía zarpar,
sino que continuaba en el río como blanco de las
miradas de todos los barcos que pasaban por ahí,
pues el capitán estaba encarcelado por deudas.

Entonces, la predicción de George Bishop se cumplió,
porque las plagas del Señor cayeron tan pesadamente sobre los perseguidores,
que su afán por desterrar a los Cuáqueros y enviarlos lejos, empezó a disminuir.
El mismo George Bishop, a mediados del verano,
les escribió una carta a sus amigos desde la prisión de Bristol,
exhortándolos a permanecer firmes, y prediciéndoles que si llegaban a ser desterrados,
Dios les daría gracia ante los ojos de aquellos entre quienes fueran enviados,
si continuaban sujetos a Él; y que cuando Él los hubiera probado,
los volvería a traer a su país de nacimiento y nadie los desarraigaría.
También dijo que el Señor visitaría a sus enemigos con espada y pestilencia,
y los golpearía con terror, etc.
Esta no es más que una mención de lo que escribió en detalle.

G+++.+++ Fox el joven,
también había publicado un pequeño libro en el año 1661
(del que se han hecho algunas pequeñas menciones antes),
en el que hacía lamentación por Inglaterra,
por los juicios que estaban por venir sobre sus habitantes
por su maldad y persecución. Decía,
entre otras cosas, que el Señor le había hablado con respecto a los habitantes:
"`El pueblo es demasiado, el pueblo es demasiado.
Lo voy a reducir, lo voy a reducir.`"
Además de esto, que el Espíritu del Señor le había señalado que un desbordante azote, sí,
que un juicio sumamente grande y terrible estaba por venir sobre la tierra,
y que muchos caerían en él y serían llevados.
Y que este decreto del Señor era tan firme,
que aunque algunos de los hijos del Señor y profetas
aparecieran y se colocaran en la brecha,
Su decreto no sería alterado.
Esto y mucho más escribió muy claramente,
y aunque él hacía mucho tiempo que había muerto,
este documento fue reimpreso para mostrarles a los
habitantes cuán fielmente habían sido advertidos.

Lo que Isaac Penington, estando prisionero,
les escribió al rey y al Parlamento sobre este tiempo, y publicó en forma impresa,
fue también muy notable, expresándolo con mansedumbre Cristiana para disuadirlos,
si era posible, de continuar con la maliciosa obra de persecución. En este documento,
que contiene algunas preguntas, entre muchas expresiones de peso,
encuentro las siguientes:

A pesar de haber hecho todo lo que han podido, es decir,
de haber promulgado leyes tan fuertes como han podido,
y de ponerlas en ejecución de la manera más estricta posible;
una noche del Señor puede ponerle fin a la controversia,
y mostrar si nosotros agradamos al Señor en obediencia a Él,
o ustedes Le agradan haciendo leyes contra nosotros
por nuestra fidelidad y obediencia a Él.

Si ustedes equivocan su obra y malinterpretan la providencia de Dios,
y erran en el corazón sobre lo que causa Su desagrado; y de ese modo,
por un error de juicio se colocan en oposición contra Él,
y replantan lo que Él no desea que crezca, y arrancan las plantas de Su plantación,
¿acaso no provocan así al Señor para que extienda Su brazo contra ustedes?
Nosotros somos pobres gusanos.
¡Ay, si sólo tuvieran que lidiar con nosotros, no seríamos nada en sus manos!
Pero si Su fuerza está detrás de nosotros, resultaremos una piedra muy pesada,
y encontrarán que es muy difícil sacarnos del lugar donde Dios nos ha puesto.
Y sería feliz para ustedes, si en lugar de perseguirnos,
fueran persuadidos a esperar el mismo engendramiento
de Su Espíritu que nosotros hemos sentido,
fuera de la naturaleza terrenal y dentro de Su vida y naturaleza,
y luego aprendieran de Él a gobernar en este.
Entonces,
sí que podrían ser establecidos y librados del peligro de las sacudidas
y vuelcos que Dios está apresurando sobre la tierra.

Ahora bien,
debido a que ustedes son capaces de pensar que escribo estas cosas por mi propio bien,
y por el bien de mis amigos y compañeros en la verdad de Dios,
con el fin de escapar de los sufrimientos y severidad
que probablemente padeceremos por parte de ustedes,
y que no lo hago principalmente y sobre todo por el bien de ustedes,
para que no traigan la ira de Dios y la miseria sobre sus
almas y cuerpos--para evitar este error añadiré lo que sigue.
En efecto, no es esa la intención de mi corazón; porque por mucho tiempo he esperado,
y sigo esperando, esa copa de aflicción y persecución externas de parte de ustedes,
y mi corazón está tranquilo y satisfecho con ella,
sabiendo que el Señor traerá gloria a Su nombre y bien para nosotros a partir de ella.
Pero estoy seguro de que no es bueno para ustedes
afligirnos por lo que el Señor requiere de nosotros,
y en lo que nos acepta; y descubrirán que es la obra más amarga que jamás hayan hecho,
y al final, desearán que el Señor no les hubiera dado nunca este día de prosperidad,
en lugar de haberles permitido que hicieran uso de él de esta manera.
Ahora, para que puedan ver más claramente el temperamento de mi espíritu,
y cómo está mi corazón en este asunto,
les mostraré un poco mi fe y mi esperanza al respecto con los siguientes detalles:

Primero, estoy seguro en mi corazón y en mi alma que este menospreciado pueblo,
llamado Cuáqueros, ha sido engendrado por el Señor en Su propia vida y naturaleza.
De hecho, si yo no hubiera visto el poder de Dios en ellos,
y no hubiera recibido del Señor un incuestionable testimonio con respecto a ellos,
nunca los habría mirado; porque, por lo demás, eran muy despreciables ante mis ojos.
Y no puedo sino testificar con respecto a ellos,
que he hallado la vida de Dios en mí reconociéndolos,
y que eso que Dios ha engendrado en mi corazón ha
sido refrescado por el poder de la vida en ellos.
Y nadie más que el Señor conoce la belleza y excelencia
de gloria que Él ha escondido bajo esta muy baja apariencia.

Segundo, el Señor los ha preservado hasta ahora contra las grandes oposiciones,
y todavía puede preservarlos.
Hasta ahora, ningún poder ha podido vencerlos,
sino que han permanecido por el cuidado del Señor y Su tierna misericordia;
y los diversos poderes que los han perseguido, han caído uno tras otro.

Tercero,
yo mismo he experimentado la bondad del Señor y Su
preservación en mi sufrimiento con ellos,
por el testimonio de Su verdad, quien hizo que mis ataduras me resultaran agradables,
y que mi repugnante prisión (que era suficiente para haber destruido mi
débil y tiernamente educada naturaleza) fuera un lugar de placer y deleite,
donde era consolado por mi Dios noche y día, y llenado con oraciones por Su pueblo,
así como de amor y oraciones por los que habían sido el medio de
afligirme externamente a mí y a otros por motivos del Señor.

Cuarto, no tengo dudas en mi corazón de que el Señor nos librará. La fuerza del hombre,
la determinación del hombre no es nada ante mis ojos
comparada con el Señor. El Señor salva según Su deseo,
a aquel a quien Él ama.
Ha comenzado Él a romper nuestras ataduras y a librarnos,
¿y vamos a desconfiar ahora de Él? ¿Estamos en una peor condición que la de Israel,
cuando el mar estaba delante de ellos, las montañas a cada lado,
y los egipcios persiguiéndolos detrás? Es cierto que quien mira con ojos de hombre,
no puede ver ningún motivo de esperanza, ni siquiera una posibilidad de liberación;
pero para el ojo de la fe, ahora está más cerca que cuando Él comenzó a liberar.

Quinto, el Señor se deleita y se glorifica liberando a Su pueblo,
cuando al ojo del hombre le parece imposible.
Es entonces cuando se deleita extendiendo Su brazo, cuando nadie más puede ayudar.
Es entonces cuando le complace tratar con los enemigos de Su verdad y de Su pueblo,
cuando se levantan por encima del temor de Él,
y están listos a decir en sus corazones con respecto a Su pueblo:
"`Ya están en nuestras manos, ¿quién podrá librarlos?`"

Bien, si no fuera por el amor que les profeso y por lástima a
lo que ciertamente les sucederá si continúan por este camino,
podría decir en el gozo de mi corazón,
y en la consciencia de la buena voluntad de mi Dios hacia nosotros,
quien permite que sucedan estas cosas: Continúen,
pruébenlo con el Espíritu del Señor. Vengan con sus leyes, prisiones,
despojo de nuestros bienes, destierros y muerte, y vean si lo pueden llevar a cabo.
Porque no salimos contra ustedes en nuestras propias voluntades,
o en alguna enemistad contra sus personas o gobiernos,
o con alguna terquedad o espíritu recalcitrante;
sino con la naturaleza del cordero en la que el Señor nuestro Dios nos ha engendrado,
y que es enseñada y capacitada por Él tanto para hacer Su voluntad,
como para sufrir por causa de Su nombre.
Y si no podemos vencerlos así, es decir, en paciencia de espíritu y amor hacia ustedes;
y si el Señor nuestro Dios se complace en no comparecer por nosotros,
nos contentamos con ser vencidos por ustedes.
¡Qué se haga la voluntad del Señor, dice mi alma!

El autor termina con una posdata que contiene una seria exhortación a abandonar el mal.
Además de este,
publicó otro documento en el que les planteaba al rey y a ambas cámaras del Parlamento:
Si las leyes hechas por el hombre, en equidad,
debían extenderse más allá del poder de obediencia del hombre;
y si no era cruel requerir obediencia en aquellos casos en los
que la parte no tenía la capacidad en ella de obedecer.
Y para explicar un poco más esto dijo:
"`En las cosas concernientes a la adoración a Dios,
en la que el hombre es limitado por Dios mismo,
tanto en qué adoración realizará y de qué adoración se abstendrá,
aquí no se le da la libertad de obedecer las leyes
hechas por el hombre que son contrarias a esto.`"
Así se esforzó Penington por escrito,
para mostrarles a los perseguidores la maldad de sus acciones.
No obstante, en ese momento prevalecía un partido feroz,
y el clero soplaba continuamente sobre el fuego de la persecución. De hecho,
muchos presumían que ya había llegado el momento de destruir totalmente a los Cuáqueros,
y en Diciembre doce más fueron condenados al destierro.

Con respecto a los desterrados que se encontraban en un barco en el río Támesis,
los dejaré ahí y volveré a George Fox,
a quien el año anterior dejamos en la prisión de Lancaster.
En el mes llamado Marzo de este año (1665),
fue llevado de nuevo a juicio delante del juez Twisden;
y aunque el juez Turner había encargado en la sesión anterior del tribunal,
que se aseguraran de que no hubiera errores tan graves como en la acusación anterior,
en este aspecto esta no estaba mejor que la anterior,
aunque el juez mismo la había examinado.
Entonces, al ser llamado el jurado a prestar juramento,
y tras el testimonio de tres oficiales del tribunal que declararon que en la
última sesión del tribunal se le había presentado el juramento de lealtad,
en concordancia con la acusación, el juez le preguntó qué tenía que decir al respecto,
y si él había prestado juramento en la última sesión del tribunal.
A continuación, George Fox dio cuenta de lo que se había hecho en ese momento,
y que él había dicho que el libro que le habían dado para jurar sobre él, dice:
"`No jurarás en ninguna manera.`"
Y reiterando más lo que había dicho entonces, el juez dijo: "`No discutiré contigo,
salvo cuestiones de la ley.`"
Y cuando George Fox se ofreció a hablarle algo al jurado con respecto a la acusación,
fue detenido por el juez.
Entonces Fox le preguntó si el juramento debía ser
presentado únicamente a los súbditos del rey,
o a los súbditos de príncipes extranjeros.
El juez replicó: "`A los súbditos de este reino.`"
"`Bien,`" dijo Fox,
"`miren la acusación y podrán ver que la palabra '`súbdito`'
fue dejada por fuera en esta acusación también.`" Asimismo,
hizo notar otros tantos graves errores en cuanto al tiempo y la fecha en la acusación,
pero tan pronto como habló de los errores, el juez gritó: "`¡Llévatelo, carcelero,
llévatelo!`"

La gente pensó que lo llamarían de nuevo, pero no fue así. Después de que se lo llevaron,
el juez le preguntó al jurado si habían llegado a un acuerdo.
Ellos dijeron:
"`Sí,`" y dictaron sentencia a favor del rey y en contra de él. La razón
por la que se llevaron tan repentinamente a George Fox parece haber sido,
que ellos esperaban que él demostrara que los oficiales del tribunal habían jurado falsamente,
siendo que el día en el que le había sido presentado el juramento en la sesión anterior,
estaba mal registrado en la acusación; y que sin embargo,
habían jurado que ese día él se había negado a prestar juramento.
Ahora bien, antes de que George Fox fuera llevado delante del juez,
él ya había dictado la sentencia de premunire contra Margaret Fell,
por haberse negado a prestar juramento.
Y aunque esta sentencia no había sido dictada contra George Fox,
fue registrado como una persona contra la que se había dictado la sentencia de premunire;
aunque no se le había preguntado qué tenía que decir para
que no fuera pronunciada dicha sentencia contra él. Y así,
continuó prisionero en el castillo de Lancaster.

Mientras estuvo ahí, aunque débil de cuerpo, escribió varios documentos;
pero los magistrados de alrededor se esforzaron mucho por
conseguir que lo trasladaran de ahí a algún lugar remoto,
ya que era bien conocido entre el pueblo la forma en que lo había tratado el tribunal.
Así, aproximadamente seis semanas después,
obtuvieron una orden del rey y del consejo para trasladarlo del castillo de Lancaster.
También recibieron una carta del conde de Anglesey, en la que se decía,
que si las cosas de las que lo acusaban resultaban ciertas,
no merecía clemencia o misericordia; y sin embargo,
el asunto más grande que tenían contra él era su negativa a prestar juramento.

Ahora que sus perseguidores se habían preparado para su traslado,
el representante del alguacil y los hombres del alguacil mayor,
junto con algunos agentes judiciales, llegaron al castillo para sacarlo,
cuando él estaba tan débil por permanecer en esa prisión fría, húmeda y llena de humo,
que apenas podía moverse o mantenerse en pie.
Así que lo bajaron a la casa del carcelero donde
estaban el juez William Kirby y varios otros.
Ellos pidieron que le dieran vino, pero conociendo muy bien su malicia contra él,
George les dijo que no quería su vino.
Entonces gritaron: "`Saquen los caballos.`"
Por lo tanto,
George Fox quiso que le mostraran primero la orden del tribunal o una copia de ella,
si tenían la intención de trasladarlo; pero no quisieron mostrarle más que sus espadas.

Entonces George les dijo, que no se había dictado ninguna sentencia contra él,
y que hasta donde sabía, tampoco se había dictado contra él la sentencia de premunire;
y por lo tanto, que aún no había sido hecho prisionero del rey,
sino que seguía siendo prisionero del alguacil; porque ellos y todo el condado sabía,
que él no había sido escuchado completamente en la última sesión del tribunal,
ni se le había permitido mostrar los errores que tenía la acusación,
los cuales eran suficientes como para anularla.
Que todos ellos sabían que no se había dictado la sentencia de premunire contra él,
y por lo tanto, que al no ser prisionero del rey, sino del alguacil, quería ver la orden.
Pero en lugar de mostrarle la orden,
lo sacaron a rastras y lo subieron sobre uno de los caballos del alguacil,
porque estaba tan débil que apenas podía montar.
Así cabalgó por la calle, bajo la mirada de la gente,
y después tuvo grandes razones para decir que no había recibido un trato cristiano,
ni civilizado, ni humanitario; porque a pesar de lo enfermo y débil que estaba,
ellos lo habían llevado apresuradamente unas catorce millas hasta Bentham, en Yorkshire.
Por su parte, la maldad del carcelero era tal, un tipo joven apellidado Hunter,
que varias veces azotó con su látigo el caballo en
el que cabalgaba G. Fox para hacerlo brincar,
a tal punto, que a Fox le resultaba muy difícil mantenerse sentado sobre él. Entonces,
este tipo desvergonzado se acercaba y mirándolo en la cara le decía: "`¿Cómo está,
señor Fox?`"
A lo que George respondía, que no era civilizado de su parte hacer eso.
Sin embargo, este malvado tipo parecía no darle importancia;
pero no tuvo mucho tiempo para gozarse con esta clase de insolencias,
porque poco después fue cortado por la muerte.

Cuando G. Fox llegó a Bentham, fue recibido por un alguacil,
varios soldados y muchos miembros de la nobleza,
además de una gran cantidad de personas que habían llegado para mirarlo.
Al entrar en la casa y sintiéndose muy cansado,
pidió que le permitieran acostarse en una cama, lo que los soldados permitieron;
y el alguacil, a quien G. Fox fue entregado,
puso una guardia alrededor de él. Después de estar ahí por un rato,
consiguieron caballos y mandaron a llamar al agente judicial y a los alguaciles,
y trasladaron a G. Fox a Giggleswick esa noche.
Allí apostaron a los alguaciles,
quienes se sentaron a beber toda la noche en la habitación de al lado,
por lo que apenas pudo descansar.
Al día siguiente, llegando a un pueblo de mercado, varios de sus amigos llegaron a verlo,
y en la noche les preguntó a los soldados, adónde pensaban llevarlo.
Algunos dijeron: "`Más allá del mar,`" y otros: "`A Tinmouth Castle.`"
Y aunque existía el temor entre ellos de que algunos intentaran rescatarlo,
no había ninguna razón para ello.
La noche siguiente fue llevado a York, donde el alguacil lo puso en una gran cámara,
y muchos de los soldados llegaron a verlo.
Entonces, al hablarles a los soldados algo a manera de exhortación,
muchos de ellos se volvieron muy tiernos con él. Y un poco después de esto,
el señor Frecheville, quien comandaba la tropa de caballos,
llegó a verlo y se portó cortés y cariñoso,
y G. Fox le dio cuenta de su encarcelamiento.

Después de una estadía de dos días en York,
el alguacil y cinco soldados fueron comisionados a llevarlo al castillo de Scarborough;
ellos se comportaron civilizadamente con él. En el camino se alojaron en Malton,
y permitieron que sus amigos lo vieran.
Después, cuando llegaron a Scarborough,
lo llevaron a una posada y le dieron aviso al gobernador,
quien envió seis soldados para que lo custodiaran esa noche.
Al día siguiente lo llevaron al castillo,
y allí lo pusieron en una habitación con un centinela para que lo vigilara.
De esta habitación pronto lo llevaron a otra,
que estaba tan abierta que entraba la lluvia, y estaba muy llena de humo,
lo cual era muy desagradable para él.

Un día el gobernador, sir John Croslands, llegó al castillo con un tal sir Francis Cob.
George le pidió al gobernador que entrara a su habitación para que pudiera verla,
y ellos la encontraron tan llena de humo, que apenas pudieron encontrar la salida.
G+++.+++ Fox le dijo a este hombre, que era Católico romano,
que ellos lo habían puesto en su purgatorio.
Porque claramente parecía que ellos lo habían colocado
ahí con la intención de fastidiarlo y angustiarlo;
porque después de gastar cincuenta chelines para protegerse
de la lluvia y algo más para disminuir el humo,
lo pusieron en una habitación peor, en la que no había chimenea ni hogar;
y al estar muy abierta hacia el lado del mar,
el viento hacía entrar la lluvia tan fuertemente que el agua no sólo corría por la habitación,
sino que también llegaba hasta su cama.
Y como no tenía fuego para secar su ropa mojaba, su cuerpo estaba entumecido por el frío,
y sus dedos se hincharon a tal punto,
que cada uno duplicó su tamaño. Sus perseguidores eran tan perversos,
que apenas le permitían a algunos de sus amigos que llegaran a verlo;
ni siquiera para que le llevaran un poquito de comida,
de modo que era forzado a contratar alguien para que le llevara lo que necesitaba.
Así pasó una cuarta parte del año, y después,
cuando fue puesto en una habitación en la que se podía hacer fuego,
contrató a un soldado para que le llevara lo que necesitaba.
Entonces casi sólo comía pan, y tan poquito,
que una hogaza de tres centavos comúnmente le alcanzaba para tres semanas.
La mayor parte de lo que bebía era agua remojada con ajenjo; y una vez,
cuando el clima era muy fuerte, y había cogido un gran resfriado,
le dieron a beber cerveza de elecampana.^
footnote:[Planta parecida al girasol que tiene propiedades medicinales.]

Ahora, aunque él quería que a sus amigos y conocidos les permitieran llegar a verlo,
esto le era negado, pero a algunos otros sí los dejaban llegar y mirarlo,
especialmente a los papistas.
Una vez, que llegaron un gran grupo de estos, afirmaron que el papa era infalible,
y que lo había sido desde los tiempos de San Pedro.
Pero G. Fox lo negó, alegando por la historia, que Marcellinus,
uno de los obispos de Roma, había negado la fe y sacrificado a los ídolos, y por tanto,
que no era infalible.
También dijo: "`Si los papistas estuvieran en el espíritu infalible,
no mantendrían su religión con cárceles, espadas, horcas, hogueras, tormentos, torturas,
etc., ni necesitarían tales medios para sostenerla.
Porque si estuvieran en el espíritu infalible,
preservarían la vida de los hombres y sólo usarían armas espirituales en asuntos
de religión.`" También les dijo cómo cierta mujer que había sido papista,
y después había entrado en la sociedad de los llamados Cuáqueros,
teniendo un sastre trabajando en su casa y hablándole
acerca de la falsedad de la religión papista,
había sido amenazada por él con apuñalarla, y que con ese fin había sacado su cuchillo,
diciendo que era uno de los principios de los papistas,
matar si podían a cualquiera que se aparte de su religión. Él les contó esta
historia a los papistas y ellos no negaron que ese fuera un principio de ellos,
pero le preguntaron si él lo declararía en el exterior.
Y él les respondió: "`Sí, esas cosas deben ser declaradas en el exterior,
para que sea conocido cuán contraria es la religión de ustedes al verdadero Cristianismo.`"
Entonces, se marcharon furiosos.

Un tiempo después de esto, otro papista llegó a conversar con él,
y dijo que todos los patriarcas habían estado en el infierno,
desde el momento de la creación hasta que había venido Cristo,
y que cuando Cristo había sufrido había entrado en
el infierno y el diablo le había dicho:
"`¿Para qué has venido aquí, para quebrantar nuestras fortalezas?`"
Y que Cristo había dicho: "`Para sacar a todos.`"
Y así,
dijo que Cristo había estado tres días y tres noches en el infierno para sacar a todos.
Ante esto G. Fox le dijo que eso era falso, porque Cristo le había dicho al ladrón:
"`Hoy estarás conmigo en el paraíso.`" También le
dijo que Enoc y Elías habían sido traslados al cielo,
y que Abraham también estaba en el cielo,
ya que las Escrituras dicen que Lázaro fue a su seno.
Y que Moisés y Elías habían estado con Cristo sobre
el monte de la transfiguración antes de sufrir.
Con estos ejemplos tapó la boca de su adversario y lo paró en seco.

En otro momento, llegó a verlo un gran médico, llamado Dr. Witty,
acompañado del señor Falconbridge, gobernador de Tinmouth Castle, y varios caballeros.
G+++.+++ Fox fue llevado delante de ellos y el doctor se dispuso a conversar con él,
y le preguntó la razón por la que estaba en prisión. G. Fox le dijo,
porque no había desobedecido el mandamiento de Cristo y no había jurado.
A esto el doctor le dijo que él debía hacer su juramento de lealtad al rey.
Pero G. Fox, sabiendo que él era un gran Presbiteriano,
le preguntó si él no había jurado primero contra el rey y la casa de los lores,
y tomado el pacto escocés; y si desde entonces había jurado o no su lealtad al rey.
Como el doctor no tenía una respuesta lista para esto, G. Fox le preguntó: "`Entonces,
¿para qué sirve tu juramento?`"
Y añadió: "`Mi lealtad no consiste en jurar, sino en verdad y fidelidad.`"
Después de un poco más de conversación, G. Fox fue llevado de regreso a prisión.

Tiempo después, el doctor regresó, acompañado de muchas personas distinguidas,
y afirmó delante de todos ellos,
que Cristo no había alumbrado a todo hombre que viene al mundo,
que la gracia de Dios que trae la salvación, no se había manifestado a todos los hombres,
y que Cristo no había muerto por todos los hombres.
Entonces G. Fox le preguntó,
qué clase de hombres eran esos a los que Cristo no había
alumbrado y a los que Su gracia no había aparecido.
El doctor respondió: "`Cristo no murió por los hombres adúlteros, idólatras,
ni perversos.`"
Entonces G. Fox le preguntó si los hombres adúlteros y perversos eran pecadores.
El doctor dijo: "`Sí.`" Esto hizo que G. Fox dijera:
"`¿Y no murió Cristo por los pecadores?
¿No vino a llamar a los pecadores al arrepentimiento?`"
"`Sí,`" dijo el doctor.
"`Entonces,`" replicó G. Fox, "`tú has tapado tu propia boca.`"
Y luego demostró que la gracia de Dios se había manifestado a todos los hombres,
aunque algunos convertían Su gracia en libertinaje
y caminaban despectivamente contra ella;
y que Cristo había alumbrado a todos los hombres, aunque de hecho algunos odiaban Su luz.
Varios de los que estaban presentes confesaron que eso era cierto,
pero el doctor se marchó furioso y no volvió más.

En otra ocasión el gobernador fue a verlo con dos o tres hombres parlamentarios,
y ellos le preguntaron si él aceptaba ministros y obispos.
A esto G. Fox respondió: "`Sí, aquellos a quienes Cristo envía;
a los que han recibido gratuitamente y quieren dar gratuitamente;
y a los que han sido hechos aptos y están en el mismo poder y Espíritu,
en el que estaban los ministros en los días de los apóstoles.
Pero a obispos y maestros como los de ustedes, que no harán nada sin un gran beneficio,
no los acepto; porque ellos no son como los apóstoles.
Porque Cristo les dijo a Sus ministros:
'`Vayan a todas las naciones y prediquen el evangelio.`' Pero ustedes, parlamentarios,
mantienen a su sacerdotes y obispos con tan grandes
beneficios que los han mimado a todos,
porque, ¿creen ustedes que ellos van a ir a todas las naciones a predicar,
o que van a ir más allá de sus grandes beneficios?
Juzguen ustedes mismos si lo harán o no.`"
De esto no pudieron decir mucho, y sobre todo lo que le objetaban,
él siempre tenía una respuesta pronta;
y como algunas veces era una respuesta simple y clara,
sus enemigos se aprovechaban para decir que era un tonto.
Pero independientemente de lo que dijeran, lo cierto es que tenía un buen entendimiento,
aunque no había sido educado en las escuelas del saber humano.
Esto lo sé por mi propia experiencia, porque he tenido conversaciones cercanas con él.

Mientras estuvo en esa prisión fue muy visitado, incluso por muchas personas de renombre.
Una vez llegó a verlo la viuda del general Fairfax con un gran grupo de personas,
una de las cuales era un sacerdote que empezó a discutir con G. Fox,
debido a que cuando él le hablaba a una persona usaba "`ti`"
y "`tú,`" y no "`usted;`" y que a los que hablaban así,
dijo el sacerdote, él los consideraba tontos.
Esto hizo que G. Fox le preguntara si los que habían traducido
las Escrituras y habían hecho el libro de gramática eran tontos,
ya que habían traducido las Escrituras así,
y habían hecho el libro de gramática así--"`tú`"
para una persona y "`ustedes`" para más de una.
Con estas y otras razones pronto silenció al sacerdote,
y varios del grupo reconocieron la verdad que les declaraba y fueron amables con él;
y algunos de ellos quisieron darle dinero, pero él no lo recibió.

Mientras lo dejo todavía en prisión,
iré a otros asuntos y relataré el notable caso de un tal William Dundas,
quien siendo un hombre de cierta reputación en Escocia,
entró en comunión con las llamados Cuáqueros de una manera sorprendente.
Él era un hombre de vida estricta,
y que observaba las instituciones eclesiales allí
tan diligentemente como cualquiera de los más meticulosos;
pero con el tiempo vio que "`el ejercicio corporal para poco es provechoso,`"^
footnote:[1 Timoteo 4:8]
y que el Señor requería del hombre verdadera piedad.
En este estado, volviéndose más prudente de lo que solía ser,
no frecuentaba tanto como antes las asambleas públicas.
Pero eso fue notado pronto y cuando le preguntaron la razón,
dijo que él estaba buscando algo más allá de eso.
Entonces, cuando le dijeron que ese era un principio peligroso,
Dundas replicó que él no debía recibir la ley de Dios de boca del hombre.
El ministro (así llamado) le dijo que estaba tentando a Dios, a lo que Dundas respondió,
que Dios no podía ser tentado por el mal.
Ahora bien, lo que hizo que él sintiera más aversión por los sacerdotes de esa nación,
fue ver su orgullo dominante,
y la manera en que forzaban a algunos que no concordaban con ellos en principio,
a cumplir con sus instituciones, incluso,
rociando a los niños sin el consentimiento de sus padres.
Además de eso, que ellos a menudo pasaban de un beneficio a otro,
y siempre estaban listos a pasar de una iglesia pequeña a una más grande,
con el pretexto de realizar más servicio por la iglesia;
cuando claramente parecía que el interés egoísta era, en general, la causa principal.
Este comportamiento del clero y su inflexible persecución,
cuando alguien se desviaba un poco de las ceremonias eclesiásticas y de la forma común,
apartó el afecto de Dundas por ellos.

Un ejemplo de esta rigidez se manifestó en el caso de un tal Wood,
quien tenía un cargo en la aduana de Leith;
y que habiendo aceptado algunos aspectos de la doctrina de los llamados Cuáqueros,
afirmaba que Cristo era la palabra, y que la letra no era la palabra.
Por esto fue citado ante la asamblea eclesiástica de Lothian,
en la que Dundas estaba presente.
Pero Wood defendió tan bien su punto, que nadie fue capaz de rebatir sus argumentos;
principalmente extraídos de las palabras de Juan: "`Y la Palabra fue hecha carne,
y habitó entre nosotros.`"^
footnote:[Juan 1:14 RV1602P]
Como Wood continuaba manteniendo su afirmación, empezaron a amenazarlo con la excomunión,
y que no le darían más tiempo sino hasta la siguiente asamblea para que diera su respuesta.
La excomunión era un pena tal, que las personas bajo ella,
se veían muy privadas de su interacción con los hombres.
En un corto tiempo, el temor de esto hizo que Wood accediera;
y al encontrarse con Dundas unos tres meses después en una calle de Edimburgo,
le contó que se había visto forzado a inclinarse
ante la asamblea en contra de su propia luz,
porque si hubiera sido excomulgado, habría perdido su sustento.
Así se inclinó Wood por temor humano; sin embargo, apenas sobrevivió dos años.

Mientras tanto, los sacerdotes desconfiaban cada vez más de Dundas;
porque como no los tenía en la estima que ellos deseaban,
decían que él infectaría a toda la nación. Y no se detuvieron ahí,
sino que a fin de saber con quién sostenía correspondencia en Inglaterra,
abrían sus cartas en la oficina de correos,
(así de grande era el poder de ellos) y en algunas ocasiones las guardaban.
Pero si no encontraban nada en ellas que pudiera perjudicarlo,
hacían que las sellaran de nuevo y se las entregaran.
Mediante esta práctica ruin, se enteraron de que un tal Gawen Lawry,
un comerciante de Londres,
le había enviado una caja con libros por valor de unas tres libras esterlinas.
Dundas descubrió después que el sacerdote John Oswald se había llevado esos libros,
e hiciera lo que hiciera, no pudo recuperarlos hasta que los ingleses entraron a Escocia,
pero para entonces muchos de ellos se habían perdido.
Mientras tanto, como Dundas no estaba dispuesto a cumplir con la iglesia,
finalmente fue excomulgado; pero era en general tan bien estimado,
que nadie parecía tener en cuenta su sentencia, como para mantenerse a distancia de él;
lo que hizo que ese acto fuera más despreciable.
Ahora bien, aunque Dundas estaba a favor de la doctrina de los Cuáqueros,
aún era un pueblo tan despreciado, que él,
que era un hombre de cierta importancia en el mundo,
no podía rendirse todavía para unirse a ellos.

Sucedió en una ocasión que cabalgando de Edimburgo a su casa en una tarde de invierno,
oyó el ruido de unos hombres peleando,
y entonces le pidió a su criado que subiera a toda prisa y viera qué pasaba.
Al hacerlo, el criado le gritó que había dos hombres a caballo golpeando a otro a pie.
Dundas cabalgó hacia ellos y vio a los dos hombres golpeando al otro,
quien entonces les dijo: "`¿Qué les he dicho sino que teman a Dios?`"
En ese momento Dundas se dio cuenta de que el hombre
que estaba siendo golpeado era un Cuáquero,
y al preguntarle el nombre, lo reconoció, aunque no conocía al hombre de vista.
Dundas empezó entonces a golpear a los dos con su vara,
y les ordenó a los que estaban con él que los llevaran a la próxima prisión;
pero el mencionado Cuáquero le rogó que los dejara ir,
lo que Dundas hizo después de preguntarles sus nombres y lugares de residencia.
Una semana después de esto, el mencionado Cuáquero habló con un pariente de Dundas,
y le contó cuánta amabilidad le había mostrado, y cómo de cierta manera lo había salvado:
"`Sin embargo,`" dijo, "`encontré en él,
el mismo espíritu que estaba en los otros dos hombres que me golpeaban.`"
Una observación como esta habría ofendido a algunos hombres,
pero tuvo el efecto contrario en Dundas; porque estas palabras lo alcanzaron tanto,
que un tiempo después que se encontró otra vez con el mismo Cuáquero,
le pidió que cada vez que pasara por ahí, hiciera de su casa su lugar de alojamiento;
una amable invitación que el Cuáquero pareció dispuesto a aceptar.
Dundas había alcanzado ya suficiente experiencia,
que podía discernir entre los espíritus de mansedumbre y temeridad; sin embargo,
aún no podía humillarse tanto como para unirse en sociedad con los Cuáqueros,
aunque secretamente se esforzaba cada vez más por
vivir de acuerdo con la doctrina de ellos,
y en eso disfrutaba más paz en su corazón que antes.

Pero como su condición externa en el mundo no era muy ventajosa,
se fue Francia y se instaló en Dieppe.
Mientras vivía ahí llegó una mujer de Inglaterra con su criada,
y repartió en el pueblo algunos libros de George Fox y William
Dewsbury que habían sido traducidos al francés;
y como ella misma había escrito unos documentos,
le pidió a Dundas que los tradujera al francés, y así los distribuyó. Sin embargo,
le ocultó a Dundas la razón principal por la que había llegado a ese lugar,
y no sin razón, porque lo que hizo ahí fue tan inusual, que si se hubiera sabido antes,
es probable que no lo habría podido realizar.
Aunque no sé con certeza cuál era su intención en este asunto,
me parece probable que ella, por no conocer el idioma que se hablaba ahí,
tratara de testificar mediante una señal,
contra la orgullosa vestimenta de la gente del lugar de la siguiente manera.

El Primer-día de la semana,
ella y la criada llegaron a la casa de reunión de los Protestantes del lugar,
donde estaban reunidas algunos miles de personas.
Y sentándose en el lugar más visible, antes de que terminara el servicio,
se levantó con su criada, se quitó el manto y la capucha que la cubrían,
y apareció delante de todos vestida con tela de saco,
con el pelo colgando y rociada con ceniza.
Así se dio vuelta varias veces, para que toda la gente pudiera verla.
Esta visión impactó al predicador y a la audiencia con no poca estupefacción;
y la esposa del predicador contándole a alguien después,
cuánto la había afectado ver eso, dijo:
"`Eso tuvo un alcance más profundo de lo que puedo comprender.`"
Estas mujeres, después de permanecer un rato de pie, cayeron sobre sus rodillas y oraron,
y luego salieron de la reunión con mucha gente siguiéndolas,
entre quienes distribuyeron algunos libros.
Luego regresaron a su alojamiento, que estaba en la casa de un escocés,
pero como él les negó la entrada, fueron adonde se alojaba Dundas,
quien no sabía nada de todo esto.
Ellas le dijeron que la obra por la que habían llegado a esa nación ya estaba hecha.
Él les preguntó qué habían hecho,
ellas le contaron y le indicaron que necesitaban alojamiento hasta que se fueran.
Dundas fue a ver si podía encontrarles alojamiento, pero fue en vano,
de modo que les ofreció su cama, pues estaba dispuesto a mudarse a otro lugar.
Pero las mujeres se negaron a aceptar su ofrecimiento,
y la casera de él no quiso que pasaran la noche en ninguna de sus habitaciones,
por lo que se vieron obligadas a pasar esa noche en un cobertizo.

Este asunto causó tal revuelo en el pueblo,
que uno de los oficiales del rey llegó al día siguiente a ver a Dundas,
y le dijo que había transgredido las leyes de la nación
por haber recibido personas de otra religión en su alojamiento;
porque el rey sólo toleraba dos religiones: La Católica y la Protestante.
Ante esto Dundas dijo que él no había transgredido la ley de la hospitalidad,
y que se había visto forzado a hacerlo,
ya que no podía dejar a las mujeres tiradas en la calle,
donde sus vidas habrían corrido peligro de muerte por la multitud grosera.
Luego se llevaron a las mujeres y las enviaron a prisión,
y como no se les proporcionaba comida,
Dundas se encargó. Un tiempo después de esto llegó una orden del Parlamento, en Rouen,
y se las leyeron,
en la que se requería que fueran transportadas de
inmediato a Inglaterra en el primer barco de pasajeros,
y que todos sus documentos y libros fueran quemados en el mercado, y a ellas también,
si alguna vez volvían a esa nación. En cumplimiento de esto,
fueron puestas en un barco de pasajeros durante la noche y enviadas de regreso a Inglaterra.

Después los papistas de Dieppe pretendieron perseguir a Dundas como uno de su persuasión,
pero él no estaba dispuesto a ser considerado como tal,
aunque los Protestantes habían informado contra él que no asistía a sus reuniones.
Pero de esto no se podía alegar ningún delito,
y Dundas les dijo que si ellos lo perseguían,
siendo un comerciante y hombre de negocios ahí,
podían esperar lo mismo de sus comerciantes en Inglaterra.
Y cuando el juez afirmó que Dundas era de la opinión de aquellas dos mujeres,
él les dijo que ellas eran mejor que él,
pero que el camino de ellas era demasiado estrecho como para que él lo recorriera.
Sucedieron entonces dos cosas notables de las que Dundas se dio cuenta; una fue,
que el escocés que les había cerrado la puerta a las mujeres,
murió en el término de doce meses; la otra fue, que la casa de su casera,
que se había rehusado a darles a las mujeres una habitación para que se alojaran,
se quemó en el tiempo mencionado, sin que se supiera de dónde había procedido el fuego;
y además, no se quemó ninguna otra casa, aunque estaba en medio de la ciudad.

Mientras tanto, Dundas continuaba intranquilo; porque por razones de temor humano,
se descubría demasiado débil para profesar públicamente delante de los hombres,
lo que creía que era la verdad.
Entonces se fue a Rouen, pero no encontró reposo ahí,
ya que estaba algo indispuesto de cuerpo.
Y habiendo recibido de Inglaterra una gran cantidad de libros
que trataban de la doctrina de los llamados Cuáqueros,
le mandó algunos al juez penal de Dieppe,
y algunos al colegio de Jesuitas ahí y en París. Después repartió algunos libros en Caen,
donde vivían muchos Protestantes.
Pero como estos libros hablaban contra los papistas,
y los Calvinistas tenían temor de que por ello se les hiciera sufrir,
se quejaron de Dundas con el teniente general del pueblo,
diciendo que no acudía a sus reuniones.
Por esta causa, se vio forzado a dejar ese lugar y se fue a Alencon,
y mientras permanecía ahí, el juez penal lo mandó a llamar,
y después de una larga conversación, él y Dundas concordaron tanto,
que el juez lo invitó a llegar a verlo más a menudo, y que si lo quería,
podía tener la oportunidad de disputar con algunos de los Jesuitas.
Pero Dundas le dijo que él no estaba buscando disputar con nadie,
aunque no tenía temor de sostener sus principios contra todos los Jesuitas de
la nación. Cuando les contaron esto a los Jesuitas se disgustaron tanto con él,
que una vez mientras estaba fuera de la ciudad,
hicieron derribar la puerta de su habitación para registrar su alojamiento.
Al quejarse de esto con el juez penal, el juez le dijo que no sabía nada de eso,
y que si había algo,
de seguro procedía de los Jesuitas debido a su postura confiada contra ellos.
Esto no parecía improbable,
porque varias veces descubrió que sus cartas habían sido abiertas en la casa de correos,
y cuando interpeló al jefe de correos acerca de esto,
le dijo que las cartas le llegaban así.

Un tiempo después de esto regresó a Caen, donde no había estado mucho tiempo,
cuando su representante en Alencon le mandó un mensaje diciendo
que el día después de su salida de dicho lugar,
el gobernador de la ciudad había ido a su alojamiento a buscarlo.

El año siguiente, cuando se levantó una guerra entre Inglaterra y Francia,
volvió a Dieppe con el propósito de regresar a Inglaterra,
después de haber adquirido un pasaje en compañía de lord Hollis, embajador de Inglaterra.
Una vez que llegó, frecuentaba las reuniones de los llamados Cuáqueros,
pero aún no se atrevía a admitir el nombre de Cuáquero
y continuaba con la forma común de saludo, etc.
Sin embargo, la verdad que este pueblo profesaba tenía tal poder sobre él,
que al no poder disfrutar paz sin rendirse en obediencia
a las convicciones internas sobre su mente,
finalmente se dio por vencido y entró en la sociedad de ellos,
obteniendo la verdadera paz con el Señor que sus
razonamientos habían impedido durante tanto tiempo.
Con el paso del tiempo publicó un libro impreso del que he extraído este relato,
el cual concluyó con un poema,
en el que le agradecía a Dios Sus sorprendentes tratos y misericordias concedidas a él,
y deseaba que otros pudieran beneficiarse de ello.

Al separarme de William Dundas, debo decir que en Diciembre de este año, 1665,
murió William Caton en Ámsterdam.
Era un hombre no sólo de letras y celoso de la religión pura,
sino de temperamento y conducta cortés y amables,
por lo que gozaba de buena estima entre sus conocidos.
Y en cuanto al respeto que él tenía ahí, lo siguiente puede servir de ejemplo.
Como en ese tiempo Holanda estaba en guerra con Inglaterra,
había varios prisioneros de guerra ingleses en la
prisión del tribunal del almirantazgo en Ámsterdam,
a quienes Caton visitaba de vez en cuando y les suministraba algo de comida.
Pero en el cumplimiento de este servicio fue obstaculizado por un oficial del tribunal,
quien parecía estar ofendido porque Caton no le había dado el honor de quitarse el sombrero.
Esto le dio ocasión a Caton de presentar su caso ante el alcalde de la ciudad,
creo que era lord Cornelius Van Vlooswyh,
quien en ese tiempo era uno de los lores del almirantazgo.
Este hombre le pidió a Caton que llegara a su casa
a la hora en que saldría para el tribunal;
y cuando llegó se dirigió con el mencionado alcalde hacia el tribunal.
Al llegar y encontrar otra vez que el antes mencionado oficial le negaba la entrada,
el alcalde le encargó al oficial que no le impidiera a Caton visitar a los prisioneros.

Por este tiempo se promulgó una ley en Inglaterra llamada,
An Act for Restraining Non-Conformists from Inhabiting in Corporations.^
footnote:[Ley para Restringir a los No-Conformistas a Residir en Sociedades.]
Esta ley fue principalmente promulgada contra los Presbiterianos e Independientes,
que anteriormente habían estado empleados en la iglesia pública,
en las que se les exigía un juramento de que ellos no "`destilarían los principios
venenosos del cisma y de la rebelión en los corazones de los súbditos de su majestad,
para gran peligro de la iglesia y del reino.`"
Todos los vicarios, curas,
conferencistas y personas de órdenes santas estaban
obligados por esta ley a prestar el siguiente juramento:

Yo, +++______+++ juro que no es lícito, bajo ningún pretexto, tomar armas contra el rey;
y que aborrezco esa posición traicionera de tomar armas contra su persona,
o contra aquellos que son comisionados por él, en cumplimiento de dicha comisión;
y que en ningún momento intentaré alguna alteración del gobierno,
ya sea en la iglesia o en el estado, etc., bajo pena de perder 40£.

Pero aunque, como se ha dicho,
esta ley fue principalmente dirigida contra los Presbiterianos e Independientes,
ellos sufrieron muy poco por ella.
No obstante, fue astutamente usada para maltratar a los Cuáqueros, quienes,
debido a que por razones de consciencia no podían jurar, eran procesados, encarcelados,
etc., por esta ley.

Ahora bien, como la peste había sido tan fiera este año en Londres,
y cerca de cien mil personas habían sido llevadas por ella,
y también muchos de los llamados Cuáqueros,
había muchas viudas pobres y niños sin padre entre los de esa sociedad.
Y como los hombres, que a veces celebraban reuniones para cuidar de los pobres,
encontraron que esa carga se había hecho demasiado pesada para ellos,
ofrecieron parte de ese servicio y cuidado a las
mujeres más serias y sólidas de la iglesia,
quienes se reunían una vez a la semana en Londres para este servicio; y esto,
con el tiempo,
dio origen a las reuniones mensuales de mujeres en otros lugares de Inglaterra.

Ahora regreso al barco en el que estaban los prisioneros desterrados,
que dejé en el Támesis.
Los propietarios habían puesto a otro capitán cuyo nombre era Peter Love, y así,
después de mucho tiempo, el barco dejó el río y llegó a los Downs.
En el mes llamado Enero del siguiente año (1666), Luke Howard escribió desde Dover,
que de las cincuenta y cuatro persona desterradas,
que hacía casi medio año habían sido llevadas a bordo,
sólo quedaban veintisiete y que el resto había muerto.
Por causa de esta larga demora,
el barco requirió ser suplido con provisiones frescas varias veces,
y la tripulación del barco estaba tan intranquila, que dos de ellos,
después de llegar a tierra con un pequeño bote,
huyeron y dejaron el bote flotando a la deriva, por lo que se hizo pedazos.
Finalmente, el capitán resolvió hacerse a la mar,
aunque no tenía más que unos pocos marineros (que en su mayoría eran hombres inexpertos),
y estaba pobremente provisto de comida.
Así que levaron anclas y bajaron por el canal hasta Plymouth,
donde después de una estadía, zarparon de nuevo el 23 del mes llamado Febrero.
Pero al día siguiente, habiendo avanzado hasta Land`'s End,
un corsario holandés llegó y capturó el barco,
y para evitar ser capturados, bordearon la parte trasera de Irlanda y Escocia,
y después de tres semanas llegaron con algunos de los desterrados a Horn,
en Holanda del Norte, y unos días más tarde, el resto también entró a ese puerto.
Ahí se les mantuvo algún tiempo en prisión,
pero cuando los comisionados del almirantazgo entendieron que no
había posibilidad de conseguir que los Cuáqueros desterrados fueran
canjeados por prisioneros de guerra holandeses en Inglaterra,
resolvieron dejarlos en libertad, y les dieron una carta de pasaporte,
junto con un certificado que decía que los prisioneros no se habían escapado,
sino que habían sido enviados de regreso por ellos.
Llegaron entonces a Ámsterdam,
donde sus amigos les proporcionaron alojamiento y ropa (porque la tripulación del corsario,
les habían quitado sus artículos de primera necesidad),
y con el tiempo todos regresaron a Inglaterra, excepto uno, que al no ser inglés,
se quedó en Holanda.
De este modo, los desterrados fueron liberados,
y el designio de sus perseguidores fue anulado por la mano del Todopoderoso.

Mientras tanto, G. Fox continuaba prisionero en Scarborough Castle,
donde era negada la entrada de sus amigos,
pero sí eran admitidas personas de otras persuasiones.
En una ocasión llegó a verlo un tal doctor Gradock, con tres sacerdotes,
acompañados por el gobernador y su esposa, y muchos otros.
Cradock le preguntó por qué estaba ahí. Él respondió,
por obedecer el mandamiento de Cristo y Su apóstol de no jurar.
"`Pero,`" dijo Fox, "`si tú, que eres doctor y juez de paz,
puedes convencerme de que Cristo y el apóstol después de que prohibieron jurar,
les mandaron a los Cristianos jurar, juraré.`" "`Aquí está la Biblia,`" continuó,
"`muéstrame cualquier mandamiento de este tipo si puedes.`"
Ante esto Cradock dijo: "`Está escrito, '`...y jurares en verdad y justicia.`'^
footnote:[Jeremías 4:2]`" "`Sí,`" dijo G. Fox,
"`eso fue escrito en la época de Jeremías,
pero fue muchos años antes de que Cristo mandara no jurar en ninguna manera.
Pero, ¿dónde está escrito una cosa así después de que Cristo prohibió jurar del todo?
Yo podría sacar tantos ejemplos del Antiguo Testamento sobre jurar, como tú,
y puede que más,
pero ¿qué fuerza tienen para probar que jurar es lícito en el Nuevo Pacto,
dado que Cristo y los apóstoles lo prohibieron?
Además,
donde está escrito "`...y jurares en verdad y justicia,`" ¿le fue
dicho a los gentiles o a los judíos?`" Cradock no respondió a esto,
pero uno de los sacerdotes dijo:
"`Le fue dicho a los judíos.`" "`Muy bien,`" dijo G. Fox, "`pero,
¿dónde les dio Dios la orden a los gentiles de jurar?
Porque sabes que somos gentiles por naturaleza.`"
"`De hecho,`" dijo Cradock,
"`en el tiempo del evangelio todo debía establecerse por boca de dos o tres testigos,
y entonces no había que jurar.`"
"`¿Por qué entonces,`" replicó G. Fox, "`fuerzan a los Cristianos a prestar juramento,
en contra del propio conocimiento de ustedes del tiempo del evangelio?
¿Y por qué excomulgan a mis amigos?`"

Cradock respondió: "`Por no asistir a la iglesia.`"
"`¡Cómo!,`" dijo G. Fox, "`ustedes nos dejaron hace más de veinte años,
cuando no éramos más que unos jóvenes, en manos de los Presbiterianos,
Independientes y Bautistas,
muchos de los cuales nos despojaron de nuestros bienes
y nos persiguieron porque no los seguíamos.
No siendo más que jóvenes, sabíamos muy poco entonces de los principios de ustedes,
y aquellos que los sabían pudieron habernos enviado sus epístolas;
porque Pablo les escribió epístolas a los santos aunque estaba en prisión; pero nosotros,
por todo lo que teníamos de ustedes para instruirnos,
pudimos habernos convertido en turcos o judíos. Y ahora nos han excomulgado, es decir,
nos han sacado de su iglesia antes de habernos metido en ella,
y antes de habernos llevado a conocer sus principios.
¿No es esto una locura, que nos expulsen antes de haber entrado?
Pero, ¿a qué le llamas iglesia?`"
"`A eso que ustedes llaman '`casa del campanario,`'`" replicó Cradock.

Entonces G. Fox le preguntó:
"`¿Fue derramada la sangre de Cristo por la '`casa del campanario`'?
¿Purificó y santificó Él la '`casa del campanario`' con Su sangre?
Y siendo que la iglesia es la novia y esposa de Cristo,
y que Él es la cabeza de la iglesia,
¿piensas que la '`casa del campanario`' es la esposa y novia de Cristo;
y que Él es la cabeza de una casa antigua?
O, ¿es la cabeza de Su pueblo?`"
"`No,`" dijo Cradock, "`Cristo es la cabeza del pueblo y ellos son la iglesia.`"
"`Pero,`" replicó G. Fox,
"`ustedes le han dado a una vieja casa el título que le pertenece al pueblo,
y le han enseñado al pueblo a creerlo.`"
También le preguntó por qué perseguían a sus amigos por no pagar diezmos;
y si Dios le había ordenado alguna vez a los gentiles que pagaran diezmos;
y si Cristo no había acabado con los diezmos,
cuando acabó con el sacerdocio levítico que cobraba diezmos; y si Cristo,
cuando envió a Sus discípulos a predicar, no les había ordenado predicar gratuitamente,
como Él les había predicado gratuitamente;
y si todos los ministros de Cristo no estaban obligados
a guardar este mandamiento de Cristo.
Entonces Cradock dijo que no discutiría eso;
como no estaba dispuesto a quedarse en ese tema, pasó a otro asunto.
Pero al ver que G. Fox nunca se quedaba sin respuesta,
y que no podía obtener ninguna ventaja sobre él, finalmente se fue con su compañía.

G+++.+++ Fox a menudo se vio molestado por ese tipo de personas mientras estuvo prisionero ahí;
porque la mayoría de los que llegaban al castillo querían hablar con él,
y tuvo muchas disputas con ellos.
Pero en lo que concierne a sus amigos, él era como un hombre enterrado vivo,
pues a muy pocos de ellos se les permitió llegar a verlo.
Una vez que Josiah Coale quería entrar, el gobernador le dijo:
"`Tú eres un hombre entendido, pero G. Fox es un simple tonto.`"
Ahora bien, aunque el gobernador hablaba con dureza de él,
con el tiempo cambió. En una ocasión,
el representante del gobernador le dijo a G. Fox que el rey,
sabiendo que él tenía una gran influencia sobre la gente, lo había enviado ahí para que,
si se levantaban disturbios en la nación, lo colgaran en el muro.
Y que en ese entonces, entre los Católicos, que eran numerosos en aquellos lugares,
también se hablaba mucho de colgarlo.
Pero G. Fox le dijo que si eso era lo que deseaban y el Señor se los permitía,
él estaba listo,
porque nunca le había temido a la muerte ni a los sufrimientos en su vida,
sino que era conocido como un hombre inocente y pacífico,
libre de todo disturbio y conspiración, y que buscaba el bien de todos los hombres.
Pero el gobernador con el tiempo se hizo más amable; y en una ocasión,
cuando el gobernador estaba a punto de ir al Parlamento en Londres,
G+++.+++ Fox le habló y le pidió que hablara con el esquire Marsh, el señor Francis Cob,
y algunos otros, y les contara cuánto tiempo había estado preso allí,
y por qué. El gobernador lo hizo,
y a su regreso le dijo a Fox que el esquire Marsh
había dicho que él conocía tan bien a G. Fox,
que iría cien millas descalzo por su libertad,
y que varios otros en la corte habían hablado bien de él.

Después de haber estado prisionero en el castillo más de un año,
le envió una carta al rey en la que le daba cuenta de su encarcelamiento,
y de los duros maltratos que había sufrido ahí, y además,
que había sido informado de que nadie podía liberarlo sino el rey.
El esquire Marsh que era un caballero de los asistentes personales del rey,
hizo lo que pudo para procurar su libertad,
y finalmente obtuvo una orden del rey para su liberación.
La sustancia de dicha orden era,
que el rey había sido verazmente informado de que G. Fox era un
hombre con principios en contra de conspiraciones y peleas,
y que había estado dispuesto en todo momento a descubrir
conspiraciones en lugar de hacerlas,
etc., que por tanto, su real deseo era que Fox fuera liberado de su encarcelamiento, etc.
Obtenida esta orden,
no se tardó mucho en llevarla a Scarborough y entregarla al gobernador,
quien al recibirla, lo liberó y le dio el siguiente pasaporte:

Permítase al portador de la presente, George Fox,
recientemente prisionero aquí y liberado por orden de su majestad,
seguir tranquilamente con sus legítimas ocupaciones, sin ser molestado.
Firmado en Scarborough Castle, el día 1 de Septiembre,

Jordan Croslands

Gobernador de Scarborough Castle.

G+++.+++ Fox, liberado de este modo,
le habría dado algo al gobernador por la cortesía
y amabilidad que le había mostrado últimamente,
pero el gobernador no quiso recibir nada, y dijo,
que todo el bien que pudiera hacer por él y sus amigos, lo haría,
y que nunca les haría daño. Y así continuó amándolos hasta el día de su muerte;
y si en algún momento el alcalde del pueblo le pedía soldados
para ir a dispersar las reuniones de los llamados Cuáqueros,
y le mandaba algunos, les encargaba en privado que no se entrometieran en la reunión.

Al día siguiente de la liberación de G. Fox, estalló el gran incendio en Londres.
La noticia del suceso llegó rápidamente al condado,
informando que la ciudad se había convertido en escombros y cenizas, a tal punto,
que después de un incesante fuego que duró cerca de cuatro días,
sólo había quedado en pie una pequeña parte del viejo Londres,
y trece mil doscientas casas se habían quemado.
El relato de este incendio ha sido descrito tan detalladamente por otros,
que no necesito tratarlo en profundidad; pero no puedo omitir decir que Thomas Briggs,
unos años antes,
había pasado por las calles de Londres y les había predicado arrepentimiento a los habitantes,
y que al pasar Cheapside,
había gritado que Dios destruiría Londres a menos
que se arrepintiera como lo había hecho Nínive.

Ahora puedo relatar otra notable predicción.

Thomas Ibbitt, de Huntingdonshire,
llegó a Londres unos pocos días antes del incendio de la ciudad,
y según han relatado algunos testigos presenciales,
al llegar se bajó de su caballo y desabotonó su ropa, dejándola suelta,
como si se la hubiera puesto a toda prisa al salir de la cama.
De esta manera recorrió la ciudad el sexto día (el
mismo día que llegó) y el séptimo día de la semana,
pronunciando un juicio por fuego que devastaría la ciudad.
Al atardecer de esos días algunos de sus amigos se reunieron con él,
para preguntarle sobre su mensaje y su llamado a pronunciar ese inminente juicio.
Y al dar cuenta de ello,
dijo que había recibido una visión del incendio hacía algún tiempo,
pero que se había demorado en llegar y declararlo como se le había ordenado,
hasta que sintió, según lo expresó, el fuego en su propio pecho.
Este mensaje o visión, muy rápidamente, resultó ser tristemente cierto,
como lo declara en parte el breve relato anterior.
El incendio comenzó el 2 de Septiembre de 1666,
el Primer-día que siguió inmediatamente después a los dos días en los que el
mencionado Thomas Ibbitt había recorrido la ciudad declarando el juicio.

Después de que recorrió la ciudad de arriba abajo, como se ha dicho,
y vio estallar el incendio y contempló el cumplimiento de su predicción,
se apoderó de él un orgullo espiritual,
que si los otros no hubieran sido más sabios que él,
lo habría llevado a su total destrucción. Porque
cuando el fuego alcanzó el extremo este de Cheapside,
se colocó delante de las llamas y extendió sus brazos hacia el frente,
como para detener su progreso; y si un tal Thomas Matthews, junto con otros,
no lo hubieran sacado de ahí (que en ese momento
parecía estar completamente fuera de sí),
es probable que hubiera perecido en el incendio.
Sin embargo, con el paso del tiempo, según se me ha dicho,
T+++.+++ Ibbitt se recuperó y confesó su error,
dando una prueba evidente de la debilidad humana,
y un ejemplo notorio de nuestra fragilidad,
cuando nos atribuimos la realización de algo para lo que sólo el cielo puede capacitarnos.

No puedo pasar este evento sin mencionar,
que unas tres semanas antes del mencionado incendio,
los ingleses desembarcaron en la isla de Schelling, en Holanda,
bajo el mando del capitán Holmes, y le prendieron fuego al pueblo,
y se quemaron unas trescientas casas que pertenecían
en su mayoría a Bautistas que no portaban armas.
Cabe señalar, además,
que ese verano los ingleses fueron derrotados en el mar por los holandeses,
bajo el mando del almirante De Ruyter, en una batalla que duró cuatro días. Así, pues,
los ingleses tuvieron oportunidad de recordar cuán a menudo
se les habían predicho estos juicios de Dios,
que ahora estaban sobre su país, a saber: la peste, la guerra y el incendio.

Ya en libertad, G. Fox no dejó de visitar a sus amigos,
y de edificarlos en sus reuniones con sus exhortaciones,
por las que algunas veces otros llegaron a ser convencidos.
Y al llegar a Whitby, fue a la casa de un sacerdote,
que catorce años antes había dicho que si alguna vez volvía a ver a G. Fox,
él tendría su vida o Fox tendría la de él. Pero para entonces,
la esposa del sacerdote no sólo se había convertido en una de las amigas de G. Fox,
sino que el propio sacerdote estaba a favor de la doctrina profesada por su esposa,
y fue muy amable con G. Fox.
De ahí se fue a York donde tuvo una gran reunión, y también visitó al juez Robinson,
quien había sido cariñoso con él desde el principio.
En ese momento estaba con él un sacerdote que le dijo a G. Fox: "`Se dice de ustedes,
que no aman a nadie más que a ustedes mismos.`"
Pero George le mostró su error y le dio tal satisfacción, que se separaron amigablemente.

Tuvo muchas reuniones en ese condado, y una no lejos de la morada del coronel Kirby,
quien había sido el principal medio de sus encarcelamientos
en los castillos de Lancaster y Scarborough;
y quien al enterarse de su liberación dijo, que lo haría encarcelar de nuevo.
Pero en ese momento, cuando G. Fox estaba tan cerca de él, fue presa de la gota,
la cual se apoderó de él con tal fuerza, que se vio obligado a permanecer en su cama.
Después Kirby se topó con otras adversidades,
como sucedió con la mayoría de los jueces y otros que habían
sido la causa del encarcelamiento de G. Fox.
Al llegar a Synder-hill Green, G. Fox tuvo una gran reunión ahí,
por lo que el sacerdote envió al alguacil a ver a
los magistrados y pedirles una orden judicial;
pero como el aviso había sido repentino y el camino era largo,
y se había gastado tiempo buscando a Fox en otra casa,
para cuando los oficiales llegaron al lugar ya había terminado la reunión,
a pesar de que estuvieron a punto de lastimar a sus caballos por la dura cabalgata.

De ahí, G. Fox se fue a través de Nottinghamshire, Bedfordshire,
Buckinghamshire y Oxfordshire,
y visitando a sus amigos en todos los lugares a los que llegaba,
y edificándolos en sus reuniones, finalmente llegó a Londres.
Pero para ese momento él estaba tan débil por haber
pasado casi tres años en duras y frías prisiones,
y sus articulaciones y cuerpo estaban tan rígidos y entumecidos,
que apenas podía montar a caballo.

Estando ya en Londres,
contempló las ruinas de la ciudad y vio el cumplimiento
de lo que se le había mostrado algunos años antes.
Pero a pesar de este golpe en Londres, la persecución no cesó,
lo que le dio oportunidad a Josiah Coale de escribirle estas líneas al rey:

Rey Carlos,

Pon al pueblo de Dios en libertad,
que sufre encarcelamientos por el ejercicio de sus consciencias hacia Él,
y dales libertad de consciencia a ellos para adorarlo y
servirle según Él requiera y los guíe por Su Espíritu;
o de lo contrario, Sus juicios no se apartarán de tu reino,
hasta que por medio de ellos Él haya obrado la libertad
para Su pueblo y eliminado sus opresiones.
Y recuerda que has sido advertido una vez más,

Por un siervo del Señor,

Josiah Coale,

Londres, 2 de Diciembre de 1666.

Por este tiempo, o tal vez el siguiente mes,
Stephen Crisp publicó una epístola que contenía una exhortación para sus amigos,
y una predicción con respecto a los tiempos venideros, la cual es como sigue:

Amigos,

Me siento persuadido en este momento a visitarlos con una epístola,
porque el Señor me ha dado una visión de Su grande y terrible día, y de Sus obras en él,
que está cerca y se apresura enormemente.
Con respecto a esto tengo algo que decirles,
para que estén preparados para permanecer firmes en Su día,
puedan contemplar Su maravillosa obra entre Sus enemigos,
y tener comunión con Su poder en él,
y para que no se desanimen ni se alejen en la tempestad, que será grande.

Con respecto a los tiempos venideros,
el Espíritu del Señor ha indicado que serán tiempos
de horror y estupor para todo el que conoce Su consejo,
y sin embargo, lo rechaza.
Porque así como los días de Su paciencia, advertencia e invitación han sido largos,
así de feroz y terrible será Su aparición entre los que Lo han resistido; es decir,
tan terrible como, "`¿quién podrá soportar el día de Su venida?`"
Porque el Señor obrará tanto secretamente como abiertamente,
y Su brazo se manifestará a Sus hijos en ambos casos.

Secretamente, levantará una continua e inquietante angustia entre Sus enemigos,
unos contra otros,
de modo que afligidos y atormentados
internamente tratarán de hacerse miserables unos a otros,
y se deleitarán en ello por un corto tiempo.
Y luego el vencedor será vencido, y el cavador del pozo caerá en él;
y la confianza que los hombre han tenido unos en otros fallará, y se confundirán,
y se traicionarán unos a otros, tanto por medio del consejo como por la fuerza.
Y así como se han unido para quebrantarlos a ustedes (a los que Dios ha reunido),
así se unirán unos contra otros, para quebrantarse,
dañarse y destruirse entre sí. Y a través de la multitud de sus traiciones,
todo crédito o creencia en ellos fracasará;
de modo que pocos hombres se considerarán a sí mismos, o a lo que es suyo,
seguros en las manos de un amigo que no haya escogido su seguridad
y amistad en la luz pura de la inmutable verdad de Dios.
Todos los consejos secretos de los impíos serán reducidos a nada,
unas veces por sus propios medios,
y otras veces por las imposibilidades que se interponen en sus caminos,
lo cual hará que sus corazones fallen en el cumplimiento de lo que se han propuesto.

En este estado los hombres se inquietarán por un tiempo,
y no podrán ver la mano que se vuelve contra ellos,
sino que se volverán a pelear contra una cosa, y contra otra, y contra una tercera,
y se tambalearán y titubearán en el consejo y en el juicio,
como ebrios que no saben dónde encontrar el camino para descansar.
Y cuando a pesar de eso, sigan levantándose contra el pueblo santo,
y contra el pacto santo de luz, y contra los que caminan en él,
serán aún más confundidos; porque el pueblo de Dios será ayudado con pequeño socorro,
el que todos los impíos no podrán impedir, a saber,
el brazo secreto del Señor sosteniendo la causa de ellos,
y levantando un testigo en los corazones mismos de sus adversarios,
para alegar su inocencia, y esto les causará aún más intranquilidad.
Porque cuando los enemigos de la verdad miren hacia arriba, hacia su religión, su poder,
política, preferencias, amistades,
o hacia cualquier otra cosa en la que hayan confiado y se hayan apoyado,
entonces tendrán motivo para maldecirla.
Y cuando miren hacia abajo, hacia los efectos producidos por todas esas cosas,
entonces he aquí, la preocupación,
el horror y la ira se apoderarán de ellos y los llevarán a las tinieblas.
Y así, al no tener más ayuda que la terrenal,
y estar fuera del conocimiento del gran poder de
derrocamiento del Señor Todopoderoso Dios,
se desesperarán y gastarán sus días con angustia.

Además de todo esto,
la terrible mano del Señor es y será abiertamente
manifestada contra esta generación impía,
al traer sobre ella juicios, y plagas graves y terribles,
al derribar todo aquello en lo que se apoyaba su orgullo y su gloria, e incluso,
al abatir los cimientos de su fortaleza.
Sí,
el Señor asolará el monte de los impíos y la fortaleza
de su ciudad fortificada fracasará. Ah,
mi corazón se ablanda y se conmueve en la consciencia de estas cosas,
mucho más de lo que puedo escribir o declarar, por lo que el Señor hará en la tierra,
y se apresurará también a realizar entre los hijos de los hombres,
para que sepan y confiesen que el Altísimo gobierna en los reinos de los hombres,
y derriba y levanta según Su voluntad.
Y esto lo harán los hombres antes de que pasen los '`siete tiempos,`'
y se contentarán con dar su gloria Al que está sentado en el cielo.

Pero, oh, amigos, mientras todas estas cosas están obrando y sucediendo,
descansen en la fortaleza de esa Roca que todas estas sacudidas no moverán, es decir,
en el conocimiento y sentimiento del poder eterno de Dios,
que los mantiene rendidos a Su voluntad celestial.
Sientan esto diariamente matar y humillar lo que
queda de este mundo en cualquiera de ustedes;
porque la parte mundana en cualquiera, es la parte cambiante, que está arriba y abajo,
llena y vacía, alegre y triste; según vayan bien o mal las cosas en el mundo.
Porque así como la verdad es una sola, y muchos son hechos partícipes de su espíritu,
así también el mundo es uno solo, y muchos son partícipes de su espíritu;
y todos los que participen de él serán angustiados y quedarán
perplejos con él. Pero los que están unidos a la verdad,
esperando sentir diariamente la vida y la virtud de ella en sus corazones,
se alegrarán en medio de la adversidad.
El corazón de éstos no será movido por el temor,
ni se agitará con la angustia a causa de las malas noticias (Salmo 112:7-8),
porque lo que los ancla permanece con ellos.
Estos experimentarán su entrada con el novio y así serán guardados de la tristeza,
aunque Su venida sea con mucho ruido.
Y cuando haya llegado la noche sobre la gloria de todos los hombres, estos, sin embargo,
al estar listos y preparados, encontrarán que les va bien;
y al tener una verdadera consciencia de Su poder obrando en ellos,
no podrán evitar tener unidad y comunión con las obras de Su poder en la tierra,
y no murmurarán en absoluto en contra de lo que está sucediendo,
ni desearán que sea diferente.
Estos descansarán hasta que pase la indignación,
y como no tienen el propósito de llevar a cabo o promover ningún partido en la tierra,
es imposible que sean derrotados o defraudados en sus empresas.

Y cuando vean divisiones y partidos, y el corazón de las naciones desgarrado,
y rumores y tempestades en las mentes de las personas,
entonces tengan cuidado de no ser movidos a este o aquel partido,
o de dar su fuerza a este o aquel camino; sino manténganse firmes en la verdad de Dios,
en la cual no hay ni guerra, ni desgarro,
ni división. Y tengan cuidado con esa parte en cualquiera de ustedes,
que confía y se apoya en los hombres de este mundo en el día de su prosperidad;
porque esa misma parte los hará sufrir con ellos en el tiempo de su adversidad,
que no tardará en llegar.
Porque no habrá estabilidad en ese terreno; pero cuando digan:
"`vengan a unirse a nosotros en esto o aquello,`" recuerden
que ya están unidos al Señor por Su Espíritu puro,
para caminar con Él en paz y justicia; y al sentir esto,
serán apartados de todos los bullicios, ruidos, partidos y tumultos,
y serán llevados a exaltar el estándar de la verdad
y de la justicia mediante sus conductas inocentes.
Así, muchos se volverán a la verdad, y ésta será un refugio para muchos de los cansados,
zarandeados y afligidos en esos días,
y un amparo para muchos cuyo día de visitación aún no ha terminado.

Así que, queridos amigos y hermanos,
que han creído y experimentado la bendita aparición de la verdad,
que no se turben sus corazones por ninguna de estas cosas.
Oh, no dejen que las cosas presentes, ni las que están por venir,
los aparten de la firmeza; antes bien, redoblen la diligencia,
el celo y la fidelidad a la causa de Dios.
Porque los que experimenten la obra ya realizada en sí mismos,
descansarán en el día de la angustia.
Sí: "`Aunque la higuera no florezca, ni en las vides haya frutos,
aunque falte el producto del olivo, y los labrados no den mantenimiento,
y las ovejas sean quitadas de la majada, y no haya vacas en los corrales; con todo,
yo me alegraré en Jehová, y me gozaré en el Dios de mi salvación.`" (Habacuc.
3:17-18).

Pocos saben lo cerca que están estos días para esta pobre nación; y por eso,
el clamor del Señor hacia sus habitantes a través
de sus siervos y mensajeros es muy fuerte,
a fin de que valoren su tiempo mientras lo tienen, y no sean derribados,
consumidos y desolados antes de que se den cuenta,
y antes de que la destrucción venga sobre ellos, y no haya remedio,
como ya les ha sucedido a muchos.

¡Oh, Londres, Londres!
Ojalá tú y tus gobernantes hubieran considerado, hubieran prestado atención y oído,
en el día de tus advertencias e invitaciones, y no hubieran persistido en la rebelión,
hasta que el Señor se movió contra ti para cortar a miles y a multitudes de tus calles,
para quitar el apremio y la aglomeración de gente de tus puertas, y luego,
para destruir y arruinar también tus calles,
y dejar desoladas tus puertas cuando pensabas haberlas reabastecido otra vez.
¡Oh, dice mi alma, ojalá que tus habitantes sean todavía advertidos,
y persuadidos a arrepentirse y a volverse al Señor,
desechando el mal que hay en sus corazones contra la aparición de la verdad en ustedes,
y contra los que andan en ella,
antes de que los alcance una mayor desolación y destrucción! ¡Oh,
qué diré para prevalecer sobre Londres y sus habitantes!
El Señor ha llamado en voz alta, ha rugido desde Sion hacia ellos,
pero muchos de ellos no han escuchado en absoluto, ni han creído.

Pues bien, amigos míos (y tú, alma mía),
vuelvan a su descanso y habiten en el tabernáculo de la casa del
Dios de ustedes y mío. Refúgiense bajo la sombra de Sus alas,
donde serán testigos de Sus hechos, y verán Sus extraños actos realizados,
pero no serán heridos con ellos, ni se desanimarán.

¡Oh, amigos míos, desde lo más profundo de mi querido y tierno amor,
les he señalado estas cosas, para que puedan estar armados con toda la armadura de Dios,
vestidos de justicia y calzados sus pies con el apresto del evangelio de la paz,
entregados voluntariamente en todas las cosas a la disposición del Señor,
quien nos librará, no por la fuerza, ni por la espada, ni por la lanza,
sino por Su propio brazo eterno e invisible.
Sí, todavía nos salvará y nos librará, y Se hará un nombre preservándonos.
Todavía viviremos para alabar a Aquel que es digno de gloria, de honor y de renombre,
desde que sale el sol hasta que se pone, ahora y siempre!
Amén, Amén, dice mi alma.

Stephen Crisp

Un tal William Armorer muy a menudo llegaba a la casa de Thomas Curtis, en Reading,
para perturbar la reunión allí, y tomaba a muchas personas prisioneras;
en una ocasión se llevó treinta y cuatro a la vez, tanto hombres como mujeres.
Y cuando estas fueron llevadas a juicio,
se les presentó el juramento como el medio más fácil para atraparlas y mantenerlas
en prisión. Entre los prisioneros sacados de la reunión estaba un tal Henry Pizing,
a quien al momento de acercarse al estrado con su sombrero en la mano,
el juez Thomas Holt dijo:
"`Aquí hay un hombre que tiene algunos modales,`"
y le preguntó si tomaría el juramento de lealtad.
Pizing respondió que ya lo había tomado dos veces.
"`Pero,`" dijo el juez, "`tú no eras un Cuáquero entonces.`"
A esto el mencionado Henry replicó: "`Ni tampoco lo soy ahora,
pero he estado muchas semanas entre ellos y nunca me han hecho daño,
sino que me han parecido personas honestas y civilizadas.`"
Al oír esto, William Armorer, quien lo había hecho prisionero dijo:
"`¿Por qué no me lo dijiste antes?`"
A lo que Henry respondió: "`Su merced estaba tan iracundo que no quiso escucharme.`"
Entonces el juez dijo: "`Él debe prestar el juramento de nuevo.`"
El juramento fue leído, él lo tomó, tras lo cual lo dejaron libre sin pagar nada.
Pero le pidieron que saliera por la puerta trasera y que no se acercara más a los Cuáqueros,
y Pizing respondió: "`Espero que ahora que soy libre,
pueda salir por la puerta que yo desee.`"

Después, al ser llamado Thomas Curtis,
el juez le preguntó si tomaría el juramento de lealtad.
A esto él respondió que no rechazaba el juramento porque no fuera leal al rey,
sino porque Cristo había mandado '`no jurar en ninguna manera;`' pues estaba persuadido
de que había manifestado ser tan buen súbdito del rey como la mayoría del condado,
desde que había llegado a él, y que si pudiera tomar algún juramento,
ya fuera para salvar su patrimonio o su vida, confesaba que comenzaría con ese juramento.
Entonces solicitó que el tribunal se complaciera en dejar
que algunos de sus ministros le mostraran en las Escrituras,
cómo podía prestar juramento sin quebrantar el mandamiento de Cristo.
Entonces el juez llamó a un tal Worrel,
un sacerdote que estaba cerca de él y le pidió que le respondiera a Curtis en ese aspecto.
Pero el sacerdote quitándose el sombrero e inclinándose ante el tribunal,
quería que lo excusaran, diciendo, que él ya había hablado con algunos de ellos,
pero que eran personas obstinadas y que no quedarían satisfechas.
"`Sí,`" dijo Curtis, "`esta es la respuesta que comúnmente obtenemos de estos hombres,
cuando les solicitamos que nos respondan una pregunta conforme a las Escrituras;
porque cuando les hacemos ver que no dieron una respuesta satisfactoria a la pregunta,
dicen que somos obstinados.`"
Curtis (cuya esposa Anne era hija del alguacil de Bristol que había sido ahorcado
cerca de su propia puerta por intentar traer al rey) fue liberado al poco tiempo.
Pero poco después de esto fue hecho prisionero de nuevo por Armorer,
quien al darse cuenta de que él intentaba ir a la feria de Bristol,
hizo que lo llevaran a una posada donde le dijo: "`Vas a la feria de Bristol,
pero yo voy a detener tu viaje.`"
Y luego, le ordenó al alguacil que lo llevara a prisión,
y fue obligado a ir sin una orden judicial.

Por ese entonces, los amigos de Curtis que estaban en la cárcel,
escribieron un documento (en el que es probable que él participara),
para mostrar el daño y la malicia que se desprendían de los juramentos.
Este documento fue enviado por él a uno de los magistrados,
al que se le concedió permiso para que lo leyera en la cámara del consejo,
al leer estas palabras:
"`A causa de los juramentos la tierra está de luto,`"
el concejal Johnson dijo que eso era muy cierto.

Un tiempo después de esto sucedió, que estando Thomas Curtis,
su esposa y un sirviente en prisión,
Armorer envió a su siervo a averiguar si había alguien en la casa además de la familia.
Como la criada respondió que no, Armorer mismo se presentó y tocó la puerta,
pero la criada no le abrió por temor.
Entonces Armorer sacando un instrumento de su bolsillo,
forzó la cerradura y entró a la casa, y buscando de habitación en habitación,
llegó finalmente a una donde encontró a un tal Joseph Coale que vivía en la casa,
y que no estaba bien en ese momento.
Armorer lo cogió del brazo y tirando de él escaleras abajo, le dijo:
"`¿Prestarás el juramento de lealtad?`"
Como Coale se negó a hacerlo fue enviado a la casa de corrección,
donde el día anterior habían llevado también a siete mujeres,
que habían sido sacadas de una reunión. Este acto audaz
de forzar la cerradura se repitió en otros momentos,
en una ocasión,
cuando la criada había salido para llevar algo de comida
a sus señores en prisión. Mientras estaba afuera,
él registró el almacén donde había mucha tela; y a una mujer que estaba ahí,
que habló contra entrar forzando la cerradura de la puerta, le dijo:
"`¿Qué tienes que ver con eso?`"
Y luego dijo: "`¿Dónde está la ramera?,`" refiriéndose a la criada.
La mujer le respondió que sí tenía que ver con eso,
porque ella tenía que vigilar que nadie robara nada de la casa.

Además de esto,
Armorer se ocupaba continuamente de perturbar la reunión
que se celebraba comúnmente dos veces a la semana.
En esas ocasiones solía maldecir y golpear con un gran bastón a los que encontraba ahí,
y siempre mandaba a algunos a prisión. Una vez hizo que
le trajeran a tres mujeres que estaban en la casa de corrección,
y les exigió que pagaran una multa por haber estado en una reunión. Ante esto,
una tal Anne Harrison dijo: "`Ya nos han quitado la casa que construimos,
y nuestros medios de subsistencia;
¿y ahora quieres hacerme pagar más dinero cuando no he quebrantado ninguna ley?
Además, sólo había cuatro de nosotras con más de dieciséis años,
y la ley dice que deben ser más de cuatro.`"
A esto Armorer dijo que su criado le había dicho que había seis,
y que dos se habían escapado.
"`Eso es falso,`" dijo Anne, "`Frances Kent, que es comadrona,
estaba atendiendo un parto; y en cuanto a la sexta, no estaba ahí.`" Pero Armorer,
sin prestar atención a lo que Anne decía, dijo de manera ruda:
"`Yo también cogeré a la señorita Kent, y luego,
aunque la mejor señora en la tierra la necesite,
no irá a menos que el rey o el tribunal mande por ella.`"

Si yo mencionara los horrores de la conducta violenta de Armorer,
este relato sería demasiado largo; por tanto,
pasaré por encima de la mayoría de los casos y tocaré unos pocos.
Más de una vez sucedió,
que cuando los prisioneros reprendían a Armorer por su injusticia y le
recordaban que él eventualmente tendría que dar cuenta de sus malos actos;
de la manera más impúdica decía: "`Ya verán el día del juicio qué trasero será más negro,
si el de ustedes o el mío.`" Y cuando uno de los prisioneros le dijo que
era una descortesía que uno que se llamaba juez hablara con tales palabras,
replicó: "`¿Por qué, sirrah, qué descortesía es?
¿Acaso no es tu nariz tu nariz, y tu trasero tu trasero?`"

Paso por alto otros disparates con los que se toparon los prisioneros en el tribunal,
junto con la manera en que algunas veces fueron tratados por negarse a jurar.
Por lo que ya se ha dicho en más de un lugar con respecto a casos similares,
uno puede fácilmente adivinar cómo se tramitaban los asuntos,
que a veces era de manera tan grosera,
que incluso los espectadores mostraban su disgusto.
Cuando una vez por falta de buenos testigos el jurado no pudo llegar a un acuerdo,
Amorer se levantó del estrado y compareció como testigo.
Pero a pesar de esto,
el jurado regresó por segunda vez y emitió un veredicto de ignoramus.
Al oír esto, el otro juez le dijo al jurado que el señor William Armorer,
un honorable caballero, también había prestado juramento en este caso.
A esto el jurado replicó, que era cierto que William Amorer era un honorable caballero,
pero que también era un hombre sujeto a pasiones.
Y como seguían sin querer declarar culpables a los prisioneros, los dos jueces,
Proctor y Armorer (porque en ese momento no había más en el estrado),
continuaron renuentes a absolver a los prisioneros, y en su lugar,
los mandaron de regreso a la cárcel como "`personas sediciosas,`" pues
Proctor les había dicho a los miembros del jurado el día anterior,
que si ellos no declaraban culpables a los prisioneros,
parecería que William Armorer y el secretario habían jurado en falso.

Cuando se llamó a Anne, la esposa de Thomas Curtis,
y se le preguntó si prestaría el juramento, dijo:
"`Me parece muy duro que se me pida prestar este juramento, estando "`bajo cubierta,`"^
footnote:["`Bajo cubierta`" era un estatus legal en el derecho común por el que,
al casarse,
los derechos y obligaciones legales de una mujer quedaban incorporados a los de su marido.
Una mujer soltera tenía derecho a poseer bienes y
a realizar contratos en su propio nombre.
Pero una mujer "`bajo cubierta`" era considerada
legalmente como una sola persona con su marido,
y no se le reconocían derechos y obligaciones legales distintos de los de su marido.]
y siendo mi esposo actualmente víctima de lo mismo.
Porque no hay ninguna otra mujer en Inglaterra, que yo sepa,
que estando "`bajo cubierta,`" también se le exija prestar
ese juramento y se le mantenga en prisión por ese motivo.`"
Pero Armorer, lleno de cólera, gritó: "`¡Cuida tu lengua, mujer, y sal de aquí!`" Y así,
ella, junto con otra mujer a la que también le había exigido el juramento,
fueron llevadas de regreso a la cárcel como "`personas peligrosas y sospechosas.`"
Al final, algunos magistrados procuraron su libertad,
y esto disgustó tanto a Armorer que no descansó antes de tenerla de nuevo
en prisión. Pero parece que algunos otros deseaban tanto su libertad,
que fue absuelta una segunda vez,
aunque los bienes y el dinero de su esposo habían sido confiscados.

Sólo mencionaré brevemente,
cómo fue amenazado un prisionero con ser amordazado
porque había dicho algo en su propia defensa;
cómo envió Armorer a algunas jóvenes a la casa de corrección;
y cómo llegó en invierno a la reunión y arrojó en los rostros de algunas jóvenes,
el agua que había en un balde asqueroso.
Pero parecía estar enormemente ofendido por Anne Curtis,
que al ser una mujer inteligente,
no dejaba de hablarle de su comportamiento descortés
cuando se ofrecía la ocasión. Por eso,
no tardó en meterla en la cárcel otra vez,
y cuando se propuso liberar a algunas prisioneras en verano por el extremo calor,
siempre que dieran una garantía, Amorer dijo: "`No, la señora Curtis no saldrá,
aunque dé una garantía, sino que permanecerá en la cárcel hasta que se pudra.`"
Pero sin importar su maldad,
no pudo evitar que toda su exorbitante conducta contra
los Cuáqueros fuera publicada de manera impresa.

Pero en ese tiempo, tal conducta no era ni rara ni poco común,
porque como la persecución se encubría continuamente bajo el pretexto
de combatir la rebelión y la sedición en todo el país,
había muchos que perseguían a los Cuáqueros hasta el máximo de su poder.
Entre otros, había un tal Henry Marshall, sacerdote de Crosthwait, en Westmoreland,
que aunque tenía varios beneficios y una gran manutención por parte de la iglesia,
aun así mantenía a los pobres de esa persuasión en prisión por no pagarle diezmos;
y una vez dijo muy presuntuosamente desde el púlpito,
que no se debería dejar vivo a ni un solo Cuáquero en Inglaterra.
Pero después de hacer esa temeraria afirmación no vivió mucho,
porque mientras se dirigía medio vestido a su cama para acostarse, cayó escaleras abajo,
como se dedujo de las circunstancias,
pues fue hallado tendido en el piso con el cráneo quebrado, luchando con la muerte,
sin poder hablar una sola palabra.
Murió dejando a su esposa e hijos en tal condición,
que por causa de las deudas cayeron en la pobreza.

Por esta época cierto autor papista,
que no expresó su nombre más allá que con la letras A. S., publicó un libro llamado,
The Reconciler of Religions; or, A Decider of all Controversies in Matters of Faith.^
footnote:[El Reconciliador de Religiones; o,
Un Decisor de Todas las Controversias en Materia de Fe.]
Josiah Coale, quien era muy celoso de la verdad y vio bien lo que pretendía este autor,
le respondió en un libro que apareció impreso, con el título, The Whore unveiled;
or The Mystery of the Deceit of the Church of Rome revealed.^
footnote:[La Ramera Desvelada; o, El Misterio del Engaño de la Iglesia Romana Revelado.]
Ahora bien,
aunque el mencionado A.S. atacó principalmente a los Cuáqueros como los peores herejes,
y tergiversó falsamente sus doctrinas al afirmar que el
mismo espíritu que había reprendido a Judas de pecado,
también lo había inducido a colgarse,
no dejó de atacar la doctrina de otras sociedades Protestantes.
En su libro afirmaba que la iglesia romana es la verdadera iglesia,
de la que estas se habían apartado injustamente y a la que todas debían regresar;
porque la romana, dijo él, era la iglesia santa, católica y apostólica, era infalible,
no podía errar, y tenía el poder de hacer milagros.
También afirmaba que ella estaba unida en materia de fe,
que era gobernada por una cabeza invisible, Cristo, y por una cabeza visible, el papa;
y que por eso, ella era la verdadera iglesia, etc.

Josiah Coale respondió a todas esas pretensiones de manera clara y enfática,
porque era un disputador resuelto y celoso.
Además de señalar la superstición,
idolatría y cruel persecución de la iglesia de romana que le había
arrebatado la vida a muchos miles de personas honestas y piadosas,
Josiah Coale aportó abundante material para demostrar otros errores papistas,
y probar con toda claridad que era una iglesia falsa.
Porque, aunque no negaba que la verdadera iglesia era universal,
negaba que la universalidad de la iglesia de Roma fuera un argumento suficiente,
para probar que ella era la verdadera iglesia.
"`¿Qué iglesia,`" preguntó, "`es más universal que la gran ramera, la falsa iglesia,
la que tiene un nombre escrito: '`Misterio de Babilonia la grande,
la madre de las rameras y de las abominaciones de
la tierra,`' que se sienta sobre las aguas,
las cuales son pueblos, y multitudes, y naciones, y lenguas?
¿Y no se maravilló el mundo entero en pos de la bestia que llevaba a la ramera?
¿No se sentó ella como una reina sobre todos ellos, con su hermosa profesión religiosa,
o con el cáliz de oro en su mano lleno de abominaciones y de la inmundicia de su fornicación?
¿Y no bebieron del vino de su fornicación todos los habitantes de la tierra,
y los reyes de la tierra, y fornicaron con ella?
Noten cuán universal era esta gran ramera--la iglesia falsa--y cuán confiada estaba;
pues decía en su corazón que no vería llanto,
se glorificaría a sí misma y reinaría sobre los reyes de la tierra.
¿No es este el verdadero estado de la iglesia de Roma hoy?
¿No reina ella sobre los reyes de la tierra?
¿No lo ha hecho por mucho tiempo, es decir, durante muchas épocas?
Que ella ha ejercido autoridad sobre reyes,
puede verse en el caso del emperador Frederick,
a quien se le hizo sostener el estribo del papa mientras se montaba al caballo.
¿No bebió la gran ramera, la que vio Juan,
la sangre de los santos y mártires de Jesús? Ciertamente,
las historias de muchas generaciones pasadas testifican de esto.`"

De ese modo se enfrentó Josiah Coale al enmascarado A. S.,
y respondió de forma copiosa a sus afirmaciones.
Y al responder ampliamente a estas y otras objeciones,
también mostró la vanidad de su jactancia de los milagros,
de los que se glorificaba la iglesia de Roma;
y refutó todas las falsedades que el autor anónimo había lanzado contra los Cuáqueros,
declarando que era un pueblo que podía ser agraviado sin incurrir en ningún peligro.
Pero omitiré citar todas las respuestas de J. Coale por razones de brevedad.

Así escribió celosamente J. Coale otra vez contra el papismo; y sin embargo,
tal era la malicia de muchos,
que presentaban a los Cuáqueros como partidarios de la iglesia de Roma,
aunque en muchas ocasiones ellos habían demostrado efectivamente lo contrario.
Pero sus enemigos se esforzaban por tacharlos de muchas maneras,
y no dejaban piedra sin remover para ensuciarlos;
a lo que en algunas ocasiones los falsos hermanos dieron oportunidad.
Por este tiempo todavía quedaban adeptos del ya mencionado John Perrot,
quienes a menudo maltrataban y hablaban mal de los que no aprobaban sus disparates.
Los vituperios de Perrot y sus seguidores también cayeron sobre Richard
Farnsworth (uno de los primeros predicadores entre los llamados Cuáqueros),
aunque era un hombre de un notable don,
y en su lecho de muerte dio evidencias de una firme y constante confianza en Dios.
Fue por esta época que R. Farnsworth cayó enfermo y murió en Londres,
y entre las muchas expresiones que señalaban su buen
estado de ánimo y el divino consuelo que sentía,
estaban también estas palabras que fueron tomadas por escrito desde su boca:

Amigos,

Dios ha estado poderosamente conmigo y ha estado a mi lado en este momento.
Su poder y Su presencia me han acompañado todo el tiempo,
aunque algunos piensen que estoy bajo una nube.
Pero Dios ha aparecido para confirmar nuestro testimonio,
y ha irrumpido en mí como una inundación,
y estoy lleno de Su amor más de lo que soy capaz de expresar.
Verdaderamente Dios ha aparecido por nosotros.

Esto lo dijo poco tiempo antes de su partida,
y exhortó a sus amigos a la fidelidad y constancia,
para que no le permitieran la entrada a nada de otra
naturaleza diferente a la verdad que ellos profesaban,
y se mezclara con ella, diciéndoles:
"`No se debe llevar ninguna prenda de lino y lana mezclados.`"
Luego les dijo otras palabras consoladoras,
y su último testimonio fue como un sello sobre todos los testimonios anteriores
que había dado por el Señor. Y después de permanecer una o dos horas más,
durmió en paz con el Señor,
y dejó un buen sabor detrás de él en todos los que verdaderamente lo habían conocido,
y sabían cuán celosamente había trabajado en el ministerio del evangelio por muchos años.

Ahora regreso a G. Fox, que este año no sólo estuvo en Gales,
sino en varios otros lugares sin ser encarcelado.
Sin embargo, en Shrewsbury, donde tuvo una gran reunión,
el alcalde convocó a los oficiales para consultarles qué hacer contra él,
ya que se decía que el gran Cuáquero de Inglaterra había llegado al pueblo.
Pero no pudieron ponerse de acuerdo entre ellos,
pues unos estaban a favor de encarcelarlo y otros de dejarlo en paz;
y como estaban divididos, se les escapó de sus manos.

Así como varios eminentes hombres entre los llamados
Cuáqueros habían sido quitados por la muerte,
otros llegaron a ocupar sus lugares.
Entre estos, y no por eso de los menos importantes, estaba Robert Barclay,
hijo del coronel David Barclay,
(descendiente de la antigua y famosa familia de los Barclays)
y de Katherine Gordon (de la casa de los duques de Gordon).
Robert nació en Edimburgo en el año 1648, se educó en Francia y se formó en literatura;
y vivió algunos años con su tío en París,
donde los Católicos se esforzaron mucho por convertirlo a su religión.
Pero aunque a esa tierna edad parecía prestarles un poco de atención,
al crecer en edad y avanzar en conocimiento, pronto tuvo una clara visión de sus errores.

Durante su estancia en Francia, no sólo llegó a dominar el francés,
sino también el latín; y después de haberse instruido en las lenguas de los doctos,
y en otros aspectos de la literatura humana, regresó a Escocia.
Pero durante su ausencia, su padre había recibido la doctrina de los Cuáqueros,
y mostraba por su piadosa conducta que no había actuado irreflexivamente.
Robert Barclay,
que había llegado a los diecinueve años y alcanzado una buena madurez de entendimiento,
encontró tanta satisfacción en la religión que profesaba su padre, que también la abrazó,
y abiertamente demostraba delante de todo el mundo,
que el despreciado nombre de Cuáqueros no le impediría sostener
audazmente lo que entonces consideraba que era la verdad.
De hecho, llegó a ser tan celoso y valiente en la doctrina que profesaba,
que se convirtió en un promulgador público de ella,
y a menudo se veía envuelto en disputas con los eruditos, no sólo verbalmente,
sino también por escrito.
Pues Robert Barclay era tan diestro en el conocimiento,
que era capaz de enfrentarse a los eruditos con sus propias armas,
y tenía una comprensión tan rápida,
que no era inferior a las inteligencias más refinadas.
Su mansedumbre era también notable,
y esas cualidades estaban acompañadas con un comportamiento tan sabio,
que lo hacía muy aceptable para los demás. Y aunque sus habilidades naturales
eran suficientemente grandes como para superar a otros en el conocimiento humano,
y para haberse hecho famoso entre los hombres,
aun así valoraba tan poco ese conocimiento,
que en ninguna forma se esforzaba por ser distinguido por ese motivo.
Pero su objetivo principal era avanzar en la verdadera piedad, como, sin ninguna duda,
me lo afirmaba la relación que tenía con él; pues llegué a conocerlo bien.

También conocí bien a Roger Haydock de Lancashire,
un hombre culto e inteligente,
que por este tiempo también había entrado en sociedad con los llamados Cuáqueros,
cuya doctrina había recibido antes que él, su hermano mayor John Haydock.
Sucedió que una vez que Roger llegó a la casa de su padre,
su madre lo envió a conversar con su hermano John,
con la esperanza de que pudiera apartarlo del camino de los Cuáqueros.
Pero John dio razones de tanto peso para lo que él afirmaba ser la verdad,
que rápidamente dejó a Roger en silencio.
Esto disgustó tanto a su madre, quien estaba inclinada a la forma Presbiteriana,
que lo culpó de no haber resistido por más tiempo contra su hermano.
Pero Roger le dijo: "`Es la verdad, y no me atrevo a hablar contra ella.`"
Tras ser convencido de esta manera,
se convirtió en un profesante público de la doctrina de los Cuáqueros, y con el tiempo,
en un celoso predicador de ella también. Y al ser un hombre de grandes habilidades,
bien leído y lleno de conocimiento,
muchas veces se veía envuelto en disputas con los sacerdotes, y a veces,
también hacía uso de su pluma para ese fin.
Era un obrero incansable, y sufrió el despojo de sus bienes y varios encarcelamientos;
y aunque estaba afectado por debilidades corporales, no se restringió por ello,
sino que viajó mucho para visitar a las iglesias en Inglaterra, Escocia, Irlanda,
Holanda, etc.
Continuó firme hasta el fin de sus días; y no sólo por esto,
sino también por el especial afecto que tenía hacia mí,
su recuerdo es todavía muy querido para mí.

Debo hacer ahora mención de nuevo de Miles Halhead,
quien ha sido nombrado varias veces en esta historia.
Este año llegó a Devonshire, y al ser llevado ante los magistrados,
se le preguntó qué asuntos tenía (siendo que vivía en Westmoreland) en Devonshire.
A esto respondió que había ido a ver a sus viejos amigos,
con quienes hacía unos diez años, había estado relacionado.
Uno de los magistrados le preguntó los nombres de esos amigos.
A lo que replicó: "`El señor John Coplestone,
que en ese entonces era el alguacil principal de Devonshire; John Page,
que era el alcalde de Plymouth; el juez Howel,
que entonces era el juez de las sesiones del tribunal en Exeter; y el coronel Buffet,
que en ese tiempo también era juez.`"
Entonces, uno de los magistrados les dijo a los otros: "`Verdaderamente, caballeros,
este hombre llama a estos hombres sus amigos, aunque han sido sus perseguidores.`"
Luego otro de los magistrados le contó en qué lamentable
condición habían caído esos hombres,
y cómo habían perdido sus propiedades.
En efecto, el coronel Buffet había sido enviado a prisión por alta traición,
se había escapado de la cárcel y no se le podía encontrar
en su propio país. Además le dijo a M. Halhead:
"`Así te he dado un relato verdadero de tus viejos amigos.
Si estos hombres eran tus perseguidores, puedes estar seguro de que no te molestarán más;
porque si los que te molestan y te persiguen no tienen mejor fortuna que estos,
deseo que ni yo, ni ninguno de mis amigos, meta la mano para perseguirte.`"
Y así, estos discretos magistrados le permitieron seguir su camino, sin meterse con él.

En general, la persecución en Inglaterra por este tiempo,
ya no era tan intensa como había sido antes; sin embargo,
los Presbiterianos y algunos otros no se atrevían
a celebrar sus reuniones públicas para no ser multados.
A veces, cuando se reunían para el culto, tenían pipas de tabaco, pan,
queso y carne fría en la mesa, y habían acordado de antemano,
que si llegaban los oficiales dejarían de predicar y orar y comenzarían a comer.
Esto hizo que G. Fox le dijera a un tal Pocock, cuya esposa era una de las Amigas de Fox:
"`¿No es esto una vergüenza para ustedes, que nos persiguieron y encarcelaron,
y nos despojaron de nuestros bienes porque no los seguíamos y no éramos de su religión,
y nos llamaban '`house-creepers`'^
footnote:[Es decir, los que se escabullen de casa en casa.
]?`" "`Bien,`" dijo Pocock, "`debemos ser astutos como serpientes.`"
A esto G. Fox replicó: "`Esta es la sabiduría de la serpiente, en efecto.
¿Quién hubiera pensado que ustedes Presbiterianos e Independientes,
quienes persiguieron y encarcelaron a otros por no ser de su religión,
ahora se acobardarían y no permanecerían para reconocer su propia religión?`"

G+++.+++ Fox viajó este año a través de Inglaterra y visitó a sus amigos en sus reuniones;
pero paso por alto sus acontecimientos.
Este año se estableció la paz entre Inglaterra y Holanda,
no mucho después de que los holandeses quemaran algunos
de los barcos del rey en el río Támesis.
