== Capítulo XIV

[.section-date]
1662--1664

[.chapter-synopsis]
* Enfermedad y muerte de E. Burrough
* Testimonio de F. Howgill sobre E. Burrough
* Enfermedad y muerte de W. Ames
* Carta de G. Fox sobre la muerte de E. Burrough
* G. Fox responde a la pregunta: "`¿Quién hizo al diablo?`"
* Caza de fanáticos
* Muerte espantosa del coronel Robinson
* G+++.+++ Fox y el coronel Kirby
* Arresto de G. Fox
* Largo interrogatorio
* Cruel persecución en Colchester
* Giles Barnardiston
* Procesos contra los Amigos en Worcester
* Narración del cambio de T. Lurting de marinero combatiente a pacífico Cuáquero
* Piratas turcos
* Esclavos Cuáqueros en Argel
* La madre del autor visita Inglaterra
* Relato sobre Stephen Crisp
* Muggleton y Reeves
* Caso de Oliver Atherton.

Ahora llego también a la gloriosa partida de Edward Burrough, ese valiente héroe,
de quien a menudo se ha hecho mención en esta historia.
Estuvo en Londres por mucho años,
y ahí predicó el evangelio con penetrantes y poderosas declaraciones.
Esa ciudad estaba tan cerca de su corazón,
que cuando la persecución se hizo más ardiente,
con frecuencia le decía a Francis Howgill, su amigo íntimo:
"`Podría ir voluntariamente a la ciudad de Londres,
y dar mi vida por el testimonio de esa Verdad que
he declarado a través del poder y Espíritu de Dios.`"
Este año estaba en Bristol y sus alrededores, y sintiéndose movido a regresar a Londres,
les dijo a muchos de sus amigos cuando se despedía de ellos,
que no sabía si vería de nuevo sus rostros; por tanto,
los exhortó a la fidelidad y constancia en las que
habían encontrado descanso para sus almas.
Y a algunos les dijo: "`Subo de nuevo a la ciudad de Londres,
para dar mi vida por el evangelio y para sufrir entre los Amigos en ese lugar.`"

Poco después de esto,
al llegar a Londres y predicar en la casa de reuniones llamada Bull and Mouth,
fue violentamente empujado por algunos soldados,
llevado ante el concejal Richard Brown y encarcelado en Newgate.
Varias semanas después fue llevado a la casa de sesiones en Old Bailey,
allí el tribunal lo multó con veinte marcos y se
le ordenó permanecer en prisión hasta que pagara.
Pero al considerar que esa multa era muy irrazonable,
no pudo cumplir con ella por motivos de consciencia.
Por tanto, fue dejado en prisión por casi ocho meses,
con casi ciento cincuenta prisioneros más,
encarcelados por la misma razón. Pero como estaban tan hacinados,
se sofocaban mucho por falta de espacio, y muchos se enfermaron y murieron,
de los cuales él fue uno.
Y aunque se les envió a los alguaciles de Londres una orden especial por parte del rey,
para que él y otros prisioneros fueran liberados,
la enemistad de algunos de los magistrados de la ciudad era tal,
especialmente la de Richard Brown,
que hicieron lo que estaba en su poder para evitar la ejecución de dicha orden.
Y así, E. Burrough continuó preso, aunque su enfermedad se agravaba.

Durante el tiempo de su debilidad, fue muy ferviente en la oración,
tanto por sus amigos como por sí mismo,
y muchas expresiones gloriosas y de consolación salieron de su boca.
En una ocasión se le escuchó decir:
"`He experimentado el testimonio del amor del Señor para conmigo desde mi juventud;
y mi corazón, oh, Señor, se ha rendido para hacer Tu voluntad.
He predicado el evangelio gratuitamente en esta ciudad,
y a menudo he entregado mi vida por causa del evangelio.
Y ahora, oh, Señor,
abre mi corazón y mira si no es correcto delante de Ti.`" En otro momento dijo:
"`No hay iniquidad a mi puerta,
sino que la presencia del Señor está conmigo y siento que Su vida me justifica.`"
Otro día fue escuchado orar a Dios así: "`Tú me amaste cuando estaba en el vientre;
y yo Te he amado desde mi cuna y desde mi juventud hasta hoy,
y Te he servido fielmente en mi generación.`" Y a
sus amigos que estaban a su alrededor les dijo:
"`Vivan en amor y paz, y ámense unos a otros.`"
En otro momento dijo: "`El Señor quita al justo de delante de la aflicción.`"^
footnote:[Isaías 57:1]
Y orando por sus enemigos y perseguidores dijo: "`Señor,
perdona a Richard Brown, si puede ser perdonado.`"
Y siendo consciente de que la muerte se aproximaba, dijo:
"`Aunque este cuerpo de barro se vuelva polvo,
tengo testimonio de que le he servido a Dios en mi generación,
y de que ese Espíritu que ha vivido, operado y gobernado en mí,
aún se manifestará en miles.`"

La mañana anterior a su partida de esta vida (que fue hacia el final de este año), dijo:
"`Ahora mi alma y mi espíritu están centrados en su propio ser con Dios,
y la forma de esta persona debe regresar de donde fue tomada.`"
Y poco tiempo después entregó su espíritu.
Así fue la partida de Edward Burrough, quien, en la flor de su vida,
con casi veintiocho años y estando soltero,
cambió esta vida mortal por una incorruptible,
y cuya flor de verano juvenil fue cortada en la estación invernal,
después de haber predicado muy celosamente el evangelio por unos diez años.

Tenía unos diecinueve años cuando llegó por primera
vez a Londres con un testimonio público,
y por casi ocho años continuó predicando la palabra de Dios en esa ciudad con gran éxito;
de modo que muchos llegaron a convencerse,
y gran número fue añadido a la iglesia allí. En su
juventud superó a otros de su edad en conocimiento,
y aunque G. Croese en su pretendida historia de los Cuáqueros lo
llamó un "`tipo rústico,`" no lo era más que el propio autor,
porque fue bien educado e instruido en la educación que ofrecía el lugar de su nacimiento,
es decir, la baronía de Kendal en Westmoreland.
De manera tal, que aunque no era hábil en idiomas,^
footnote:[Por ejemplo griego, hebreo o latín.]
aun así tenía la lengua de los instruidos;
y en su ministerio público era muy fluido y elegante en el habla,
incluso según el juicio de los hombres doctos.

Entonces sus enemigos comenzaron a regocijarse,
pues parecían imaginar que debido a su muerte,
se detendría o retardaría el progreso de esa doctrina
que él había predicado tan poderosa y exitosamente,
pero hicieron una estimación errónea.
Francis Howgill pronunció luego una especie de lamentación que, aunque escrita en prosa,
no estaba exenta de expresiones poéticas, en la que decía lo siguiente:

[.embedded-content-document.testimony]
--

¿Podrán los días, los meses o los años desgastar tu nombre como si no hubieras existido?
¡Oh, no! ¿Acaso no vivirán en las generaciones por venir tus nobles y valientes actos,
y las poderosas obras que realizaste por el poder de Aquel que te separó desde el vientre?
¡Oh, sí! Los niños que no han nacido aún, tendrán tu nombre en sus bocas,
y tus obras testificarán de ti en generaciones que
todavía no existen y te tendrán por bienaventurado.
¿Se apagó tu vida como la mecha de una candela?
¡Oh, no!
Tú penetraste los corazones de muchos,
y la memoria del justo vivirá para siempre y será
tenida en estima entre los hijos de los hombres.
Pues volviste a muchos a la justicia, y brillarás por los siglos de los siglos,
como una estrella en el firmamento del poder de Dios;
y los que estén en el poder de Dios, te verán y te disfrutarán ahí,
aunque te hayas ido de aquí y ya no puedas ser visto en mutabilidad; aun así,
tu vida y tu espíritu correrán paralelos a la inmortalidad.

¡Oh, Edward Burrough!
No puedo sino llorar por ti, aunque no como alguien sin esperanza y sin fe,
sabiendo y teniendo en mi corazón, por el Espíritu del Señor,
un testimonio perfecto de tu bienestar; con todo,
tu ausencia es grande y los años por venir la sentirán. ¿No habré
de lamentarme como hizo David por un hombre peor que tú,
es decir, por Abner,
cuando en venganza pereció por la mano de Joab sin ninguna razón justa,
aunque era un hombre valiente?
David se lamentó por Abner y dijo: "`¿Había de morir Abner como muere un villano?`"
¡Oh, no; él fue despojado de su vida!
Así también fuiste despojado tú de la tuya por la mano del opresor,
cuyas habitaciones están llenas de crueldad.
¡Oh, que mi alma no entre en el consejo de ellos,
porque tu sangre será requerida de las manos de aquellos
que tenían sed de tu vida y clamará como la de Abel,
quien estaba en la fe; así también estabas tú,
y tu sangre pesará como una pesada piedra de molino sobre sus cuellos,
y los aplastará y será como un gusano que roe y no muere!

Cuando pienso en ti, me derrito en lágrimas de verdadera tristeza;
y debido a que la herencia del Señor tiene una gran necesidad de ti,
mi sustancia se disuelve.^
footnote:[Job 30:22]
¿No habré de decir como David dijo de Saúl y Jonatán
cuando fueron muertos en el monte Gilboa:
"`¡Ha perecido la gloria de Israel sobre tus alturas!`"?
Así mismo fuiste sofocado tú en asquerosos agujeros y prisiones,
con muchos otros que eran preciosos a los ojos del
Señor. ¡Ciertamente fuiste precioso para mí,
querido Edward, estoy afligido por ti, hermano mío! Muy agradable fuiste para mí,
y mi amor hacia ti era maravilloso, sobrepasando el amor de mujer.
¡Oh, tú, cuyo arco nunca se volvió atrás,
ni cuya espada nunca estuvo libre de la sangre de los muertos en la matanza de los poderosos;
tú hiciste que naciones y multitudes temblaran con la Palabra de vida en tu boca,
y eras muy temible para los enemigos del Señor!
Pues cortabas como una navaja, y sin embargo, para la semilla de Dios,
la que Él dio a luz,
tus palabras caían como aceite y tus labios eran como un panal de miel.

Serás registrado entre los valientes de Israel que alcanzaron el primer orden,
por el poder del Señor que obraba poderosamente en ti en tu día;
porque fuiste digno de doble honor por causa de tu obras.
Eras experto en el manejo de tu arma y por ella cayeron los poderosos,
y los muertos del Señor fueron muchos.
Numerosos fueron aguijoneados en el corazón por el poder de la Palabra de vida,
y los carbones encendidos que salían de tu boca, encendieron muchos matorrales,
cardos y espinos,
y el fuego devoró mucho rastrojo que estorbaba el terreno y manchaba la tierra.
¡Oh, qué sonido tan certero daba tu trompeta! ¡Qué gran alarma hiciste sonar en tu día,
que hizo que las huestes de los incircuncisos se
angustiaran grandemente! ¿A qué hombre valiente,
aunque hubiera sido como Goliat de Gad, no habría enfrentado tu valor,
aunque muchos despreciaran tu juventud?
¡Yo que te vi herir a los poderosos con tu honda y con tu piedra!
Y lo que al bando del dragón le pareció despreciable, es decir,
como la quijada de un asno, con ella mataste a los filisteos montón tras montón,
al igual que Sansón. Pusiste tu mano en el martillo del Señor,
y con frecuencia enclavaste las cabezas de los enemigos del Cordero,
como hizo Jael con Sísara.
Muchas piedras toscas puliste y cuadraste, y las hiciste aptas para el edificio de Dios;
y mucha madera nudosa tallaste en tus días,
porque no era apta para la edificación de la casa de Dios.

¡Oh, tú, profeta del Señor,
estarás registrado para siempre en el libro de vida del Cordero,
entre los dignos del Señor,
los que han seguido al Cordero a través de grandes tribulaciones,
como muchos pueden testificar de ti desde el principio!
Y ahora,
por fin has vencido y has sido hallado digno de estar con el Cordero sobre el Monte Sion,
la colina de Dios.
¡Oh!
A menudo te vi con tu corazón bien afinado como un arpa,
para alabar al Señor y anunciar Su gran salvación,
lo cual muchas veces alegró los corazones de los que creían,
y fortaleció su fe y esperanza.

Bien, ahora estás en reposo y atado en el haz de vida;
y sé que todas las lágrimas han sido enjugadas de tus ojos,
porque no hay causa de tristeza en ti.
Pues sé que experimentaste la desaparición de las cosas viejas y que no fue una maldición,
sino que fueron derramadas bendiciones sobre tu cabeza como lluvia,
y paz como un poderoso aguacero, y que las plagas están lejos de tu morada.
Aunque en el hombre exterior experimentaste dificultades por todo lado,
y por causa del evangelio tuviste más participación en ellas
durante tu vida que muchos otros (aunque sólo eras un joven),
ahora eres libre y has obtenido un nombre por la fe con los santos en luz.
Pues bien, ¿tenías algo más que entregar que tu vida por el nombre de Jesús en este mundo?
No, sino sólo sellar el testimonio que se te encomendó con tu propia sangre,
como a menudo dijiste en tu día,
lo cual permanecerá como una corona sobre ti por los siglos de los siglos.
Y ahora eres libre de las tentaciones del que tenía el poder de la muerte,
y de tus enemigos externos, quienes te odiaban por causa del amor que moraba en ti.

Ahora permaneces a la diestra de Dios,
donde hay gozo y placer para siempre en la luz eterna,
de la que testificaste muchas veces,
según la palabra de profecía en tu corazón que te fue dada por el Espíritu Santo;
y estás en reposo en la perfección de ella, en la belleza de la santidad.
Y sin embargo, siento que tu vida y tu espíritu están presentes,
y que tienen unidad con ella y en ella,
más allá de todas las cosas creadas y visibles que están sujetas a variación y cambio.
Y Aquel que es tu vida entrará en otros para testificar la misma Verdad,
que es desde la eternidad y hasta la eternidad;
porque Dios ha resucitado y le resucitara hijos a Abraham,
de aquellos que han sido como piedras muertas.
En efecto, Su poder es Omnipotente y Él es grande en Su pueblo en medio de sus enemigos.

--

Con estas sublimes expresiones lamentaba Francis
Howgill a su entrañable amigo Edward Burrough.

A finales de este año también falleció William Ames en Ámsterdam,
después de llegar de Inglaterra en condición débil,
pues había sufrido tantas dificultades en Bridewell, Londres,
que su salud estaba muy deteriorada cuando llegó a Holanda.
En su enfermedad, la cual fue persistente,
le dijeron que entre los Bautistas y universitarios
se decía que él había cambiado de opinión,
y que estaba afligido por haberlos juzgado incorrectamente.
Pero él dijo: "`No es así; todavía considero que su forma de adoración,
especialmente sus disputas y culto voluntario,
están fuera del camino del Señor.`" Y en esta creencia murió en paz.

En su juventud había sido de temperamento alegre y amante de la compañía festiva;
pero estando en esa condición, frecuentemente intranquilo en su mente,
se convirtió en un seguidor cercano de sacerdotes y maestros,
y se ejercitó diligentemente en la lectura de las Sagradas Escrituras, lo cual,
aunque bueno en sí mismo, no lo llevó a tener verdadera paz con Dios.
No obstante, al ser de entendimiento rápido, podía hablar mucho de ellas, tanto así,
que al entrar en sociedad con los Bautistas se convirtió en un maestro entre ellos.
En ese tiempo, aunque era más cuidadoso y se esforzaba para no cometer pecados,
encontraba que la raíz de la que brotaba el pecado permanecía viva en él;
porque cuando se encontraba con algo que era contrario a su propia voluntad o mente,
el enojo no tardaba en prevalecer.
Sin embargo, en ese estado a menudo hablaba de justificación,
santificación y limpieza por medio de la sangre de Cristo,
aunque él mismo no había llegado a ese lavamiento puro.
En esa condición se dio cuenta de que no era un verdadero miembro de Cristo,
pues aún le faltaba la regeneración. De este modo vio que
una celosa profesión de religión no servía de nada,
y que se requería algo más para obtener un estado feliz;
pero aún no sabía qué era lo que lo intranquilizaba así, aunque a veces,
al cometer algún pecado, sentía que algo lo aterrorizaba.

Finalmente, le plació al Señor que al oír a uno de los llamados Cuáqueros predicar,
que lo que convencía al hombre de pecado era la "`luz de
Cristo que ilumina a cada hombre que viene a este mundo`",
esta doctrina entrara tan profundamente en él, que la abrazó. Y así,
caminando con gran prudencia y temor delante del Señor,
halló que prestando diligente atención a lo que internamente
lo reprendía y condenaba por el mal,
llegaba a ser libre de ello y a experimentar una verdadera santificación. Y así,
avanzando en la piedad,
se convirtió en un celoso predicador de esa doctrina
que lo había tocado tanto en su corazón. Fue,
en verdad, un hombre celoso,
y aunque algunos estaban dispuestos a pensar que lo era en demasía, con todo,
era prudente; y sé que era condescendiente en asuntos sin importancia,
al pensar que había costumbres que, aunque no eran seguidas en un país,
eran tolerables en otro.
También fue generoso, y para que a nadie le pareciera que era una carga,
prefería trabajar con sus manos.

Ahora regreso a los sucesos de G. Fox, a quien dejamos en Londres,
donde habiendo pasado algún tiempo,
se fue al principio del año 1663 a Norwich y de ahí a Cambridgeshire,
donde escuchó del deceso de Edward Burrough.
Y al ser consciente del gran dolor que sería su muerte para sus amigos,
escribió las siguientes líneas:

[.embedded-content-document.epistle]
--

Amigos, permanezcan quietos y tranquilos en sus propias condiciones,
y afírmense en la Semilla de Dios que no cambia;
para que en ella puedan sentir al querido E. B. entre ustedes, en la Semilla,
en la que y por la que los engendró en Dios, con Quien está ahora.
De este modo, todos pueden verlo y sentirlo en la Semilla,
en la que está la unidad con él en la Vida; y disfrutarlo así en la Vida que no cambia,
la cual es invisible.

[.signed-section-signature]
G+++.+++ Fox

--

Después de viajar por varios lugares, G. Fox llegó a Londres,
donde tras visitar a sus amigos en sus reuniones (que eran numerosas),
viajó con Thomas Briggs a Kent.
Al llegar a Tenterden, tuvieron una reunión a la que llegaron muchos,
y se convencieron de la Verdad que era declarada.
Pero cuando intentó partir con su compañero,
vio a un capitán y a su compañía de soldados con mosquetes y antorchas encendidas.
Algunos de esos hombres se acercaron a ellos y les dijeron,
que debían acompañarlos a ver a su capitán. Cuando los llevaron delante de él,
el capitán preguntó: "`¿Dónde está George Fox?
¿Cuál es?`"
A lo que G. Fox respondió: "`Soy yo.`"
El capitán de alguna manera sorprendido dijo:
"`Los voy a encerrar entre los soldados;`" sin embargo, se comportó civilizadamente,
y un tiempo después dijo: "`Deben venir conmigo al pueblo.`"
Al llegar, llevó a G. Fox y a T. Briggs con algunos otros de sus amigos a una posada,
que era la casa del carcelero.
Y después de un rato el alcalde del pueblo, con el mencionado capitán y el teniente,
que eran jueces, llegaron e interrogaron a G. Fox,
preguntándole la razón por la que había llegado allí para hacer disturbios.
G+++.+++ Fox les dijo que no había llegado para provocar disturbios, ni había hecho ninguno.
Entonces les dijeron que había una ley contra las reuniones de los Cuáqueros,
que se había hecho sólo contra ellos.
G+++.+++ Fox les dijo que él no sabía de tal ley.
Entonces les mostraron la ley que había sido hecha contra los Cuáqueros y otros.
Cuando G. Fox la vio, dijo:
"`Esta ley es contra los que son un terror para los súbditos del rey, y son enemigos,
y sostienen principios peligrosos para el gobierno; por lo tanto,
no es contra mis amigos, porque ellos sostienen la verdad,
sus principios no son peligrosos para el gobierno y sus reuniones son pacíficas,
como es bien sabido.`"

Ahora, bien, no le faltó razón a George cuando dijo que no sabía de dicha ley;
dado que ellos habían dicho,
que era una ley que había sido hecha sólo contra las reuniones de los Cuáqueros; si bien,
la ley tenía la apariencia de haber sido hecha contra
los conspiradores y enemigos del rey,
entre los cuales, ciertamente, no estaban los Cuáqueros.
Sin embargo, se le sugirió entonces a G. Fox, que él era enemigo del rey.
Pero él lo negó,
y les contó que una vez había sido echado en un calabozo
en Derby (por el tiempo de la batalla de Worcester),
porque no había tomado armas contra el rey,
y que después el coronel Hacker lo había enviado a Londres
acusado de conspirar para traer al rey Carlos,
y que había sido mantenido prisionero en Londres
hasta que fue puesto en libertad por Oliver Cromwell.
Entonces le preguntaron si había sido encarcelado
en el momento de la insurrección. Él respondió:
"`Sí,`" pero que había sido liberado por orden del rey.
Finalmente, le exigieron una fianza para comparecer en las sesiones del tribunal,
y querían que prometiera que no regresaría allí. Pero G. Fox rechazó lo uno como lo otro.
Sin embargo, estos hombres se comportaron moderadamente, y le dijeron a él,
a Thomas Briggs y a los demás: "`Verán que somos civilizados con ustedes,
porque el alcalde desea que todos sean liberados.`"
A esto G. Fox respondió que el respeto de ellos era noble, y se fueron;
y él pasó por muchos lugares, donde le ocurrieron muchas cosas notables,
y aunque le tendieron muchas trampas,
en algunas ocasiones escapó de las manos de sus enemigos perseguidores.

Al llegar a Cornwall encontró a un tal Joseph Hellen y a George Bewly, quienes,
aunque profesaban la verdad, se habían dejado seducir por Blanch Pope,
una mujer desbocada, que los había atrapado principalmente al preguntarles:
"`¿Quién hizo al diablo, acaso no fue Dios?`"
Esta tonta pregunta, la cual J. Hellen y G. Bewly no supieron responder,
se la plantearon a G. Fox, y él respondió diciendo: "`No;
porque todo lo que Dios creó era bueno, y fue bendecido,
y por eso no fue creado un diablo.
Era llamado serpiente antes de ser llamado diablo y adversario;
y después fue llamado dragón, porque era un destructor.
La serpiente no permaneció en la verdad,
y fue por apartarse de la verdad que se convirtió en el diablo.
Ahora bien, no hay promesa de Dios para el diablo,
de que alguna vez vaya a regresar a la verdad;
pero para el hombre y la mujer que han sido engañados por él,
la promesa de Dios es que "`la simiente de la mujer herirá a la serpiente en la cabeza,
y romperá su poder y su fuerza en pedazos.`"
Con esta respuesta G. Fox satisfizo a sus amigos presentes;
pero Joseph Hellen estaba tan envenenado y alejado de la Verdad, que ellos lo negaron.
George Bewly, sin embargo, se recuperó de su falta mediante un sincero arrepentimiento.

Después de realizar su servicio allí, se fue a Helston, cerca de Falmouth,
donde tuvo una gran reunión en la que muchos fueron convencidos,
pues le explicó a la audiencia el estado de la iglesia en los tiempos primitivos,
el estado de la iglesia en el desierto,
así como también el estado de la iglesia falsa que se había levantado desde entonces.
A continuación,
mostró que el evangelio estaba siendo predicado de nuevo sobre la cabeza de la ramera,
la bestia,
el anticristo y los falsos profetas que se habían levantado desde los días de los apóstoles,
y que entonces, el evangelio eterno estaba siendo recibido,
el cual saca a la luz la vida y la inmortalidad.
Este sermón produjo tal efecto,
que el pueblo en general reconoció que la Verdad eterna se había declarado ese día allí.

Pasando de ahí, finalmente llegó a Land`'s End, donde había una asamblea de sus amigos,
y un pescador llamado Nicholas Jose predicaba entre ellos,
quien había sido convencido tres años antes por el ministerio de G. Fox.

Mientras estaba en esos lugares, sucedió un acontecimiento muy funesto y espantoso.
Desde la llegada del rey, un tal coronel Robinson había sido nombrado juez de paz,
y se había convertido en un cruel perseguidor de los llamados Cuáqueros.
Muchos de ellos fueron enviados a prisión,
y al enterarse que el carcelero les había concedido a algunos la
libertad de ir a visitar a sus esposas y niños en algunas ocasiones,
interpuso una queja delante del juez Keeling en la sesión del tribunal,
quien luego multó al carcelero con cien marcos.
No mucho después de la sesión del tribunal,
este coronel Robinson mandó a llamar a un juez vecino,
porque quería que lo acompañara a "`cazar fanáticos`" (con lo que quería decir,
a perturbar e interrumpir las reuniones de los Cuáqueros).
El día que pretendía ir a "`cazar,`" envió a su sirviente con sus caballos,
y él se dirigió al edificio donde estaban sus vacas y la lechería,
y donde sus sirvientes estaban ordeñando en ese momento.
Cuando llegó les preguntó por su toro,
y las criadas le dijeron que lo habían encerrado
en el campo porque estaba revoltoso entre las vacas.
Entonces entró en el campo, y acostumbrado como estaba a jugar con el toro,
empezó a practicar esgrima con su vara como solía hacer.
Pero el toro, resoplando,
retrocedió un poco y echó a correr ferozmente hacia él y le clavó un cuerno en el muslo.
Y luego, levantándolo con su cuerno lo lanzó sobre su espalda,
y lo desgarró desde el muslo hasta el vientre.
Cuando aterrizó en el suelo se quebró una pierna,
y entonces el toro lo embistió de nuevo con sus cuernos,
y bramando comenzó a lamer su sangre.
Una de la criadas al oír los gritos de su amo,
entró corriendo al campo y tomó al toro por los cuernos para quitárselo de encima,
pero el toro, sin herirla,
la puso gentilmente a un lado con sus cuernos y siguió
corneando al coronel y lamiendo su sangre.
Entonces la criada corrió y llamó a unos trabajadores que estaban cerca,
para que vinieran a rescatar a su amo, pero no pudieron ahuyentar al toro del todo,
hasta que llevaron a unos mastines y se los echaron; y luego el toro huyó.

Cuando la hermana del coronel recibió la noticia de su tragedia, llegó y dijo: "`¡Ay,
hermano, qué juicio tan pesado es este!`"
Y él respondió: "`¡Ah, hermana, un pesado juicio efectivamente;
ruega que se mate al toro y se les dé la carne a los pobres!`"
Entonces lo alzaron y lo llevaron a su casa,
pero estaba tan gravemente herido que murió poco después;
y el toro se había vuelto tan fiero, que se vieron forzados a matarlo a tiros.
Este fue el resultado de la maliciosa intención de Robinson de ir a "`cazar fanáticos.`"
Recuerdo que en mi juventud escuché con asombro el
relato de este accidente por parte de William Caton,
quien había recibido esta información por medio de una carta desde Inglaterra;
porque el asunto fue tan notable,
que las noticias se difundieron rápidamente hasta muy lejos.

Ahora regreso a G. Fox, quien de Cornwall viajó a Bristol, y así a Gales, de donde,
atravesando Warwickshire y Derbyshire, llegó a York.
Ahí se enteró de un complot que lo hizo escribir un documento a sus amigos,
en el que los exhortaba a ser cautelosos,
y a no meterse para nada en ese tipo de actividades.
Y viajando hacia Lancashire, llegó a Swarthmore,
donde le contaron que el coronel Kirby había enviado a su teniente allí a buscarlo,
y que había registrado baúles y cofres.
Al oír esto, al día siguiente fue a Kirby Hall, donde vivía dicho coronel,
y llegando le dijo: "`He venido a visitarte, entiendo que deseabas verme;
y ahora me gustaría saber qué tienes que decirme,
y si tienes algo contra mí.`" El coronel, que no esperaba tal visita,
y estaba a punto de salir hacia Londres al Parlamento, dijo delante de la compañía:
"`Como soy un caballero no tengo nada contra ti,
pero la señora Fell no debe celebrar reuniones grandes en su casa,
porque se reúnen en contra de la ley.`"
G+++.+++ Fox le dijo: "`Esa ley no nos afecta,
sino a los que se reúnen para conspirar y maquinar,
y levantar insurrecciones contra el rey, y nosotros no somos de esos,
sino que somos un pueblo pacífico.`"
Después de unas palabras más,
el coronel tomó a G. Fox de la mano y le dijo que no tenía nada contra él;
y algunos otros dijeron que él era un hombre encomiable.

Entonces G. Fox se fue y regresó a Swarthmore,
pero poco después se enteró de que había habido una reunión
privada de jueces y tenientes adjuntos en Houlker-hall,
donde el juez Preston vivía,
y de que ahí ellos habían emitido una orden de arresto contra él. Él podía haberse
marchado en ese momento y haberse puesto fuera del alcance de ellos,
pero sabiendo que había rumores de una conspiración en el norte,
consideró que si se marchaba ellos irían contra sus amigos,
pero que si se quedaba y era capturado, entonces sus amigos podrían escapar mejor.
Por lo tanto, se entregó a la captura.
Al día siguiente llegó un oficial con su espada y pistolas para apresarlo.
G+++.+++ Fox le dijo: "`Yo conocía tu encargo desde antes y me entregué para ser capturado,
porque si hubiera querido escapar del encarcelamiento, estaría a cuarenta millas,
pero soy un hombre inocente, de modo que no importa qué puedan hacerme.`"
Entonces el oficial le preguntó cómo se había enterado de ello,
sabiendo que la orden había sido emitida en privado
en un salón. G. Fox le dijo que no importaba cómo,
que era suficiente que él lo supiera.
Luego le pidió al oficial que le mostrara la orden de arresto.
Pero él colocando su mano en la espada dijo:
"`Debes venir conmigo ante los tenientes y responder a las preguntas que ellos te hagan.`"
Entonces,
aunque G. Fox insistió en ver la orden diciéndole
que era respetuoso y razonable que la mostrara,
el oficial no quiso hacerlo; y luego G. Fox le dijo: "`Estoy listo.`"
Así que fue junto con el oficial, y Margaret Fell también, a Houlker-hall.

Cuando llegaron, estaba un tal juez Rawlinson, sir George Middleton,
el juez Preston y varios más que él no conocía. Luego llevaron a un tal Thomas Atkinson,
uno de sus amigos, como testigo contra él,
por unas palabras que él le había dicho a un tal Knipe,
quien había informado contra él. Dichas palabras fueron,
que él había escrito contra los conspiradores y los había detenido.
Pero a partir de esas palabras poco podía hacerse contra él. Entonces Preston le preguntó
si él había participado en la escritura de Battledore (el libro ya mencionado).
"`Sí,`" dijo G. Fox.
Luego le preguntó si entendía idiomas.
Él respondió: "`Lo suficiente para mí.`"

Después de hablar algo más sobre ese tema, Preston dijo: "`Vamos a ver,
te interrogaremos sobre asuntos más elevados.`"
Entonces George Middleton dijo: "`Tú niegas a Dios, la iglesia y la fe.`"
"`No,`" replicó George Fox: "`Yo reconozco a Dios,
a la verdadera iglesia y la verdadera fe.`"
"`Pero,`" preguntó George (habiendo entendido que Middleton
era un papista) ¿cuál iglesia reconoces tú?`" Este hombre,
en lugar de responder la pregunta dijo: "`Tú eres un rebelde y un traidor.`"
Al percibir G. Fox que Middleton era un hombre envidioso le preguntó:
"`¿A quién le hablas?
¿Quién es un rebelde?`"
El otro, permaneciendo en silencio un rato, por fin dijo: "`Te hablo a ti.`"
Entonces, G. Fox, golpeando su mano sobre la mesa le dijo:
"`Yo he sufrido más que veinte como tú,
o cualquier otro aquí. Porque fui echado en el calabozo de Derby por seis meses seguidos,
y sufrí mucho porque no tomé las armas contra este rey antes de la pelea de Worcester.
Fui enviado como prisionero fuera de mi condado por el coronel Hacker a Oliver Cromwell,
como conspirador para traer al rey Carlos.
Ustedes hablan del rey, un grupo de ustedes,
pero ¿dónde estaban ustedes en los días de Oliver y qué hicieron entonces por el rey?
Pero yo tengo más amor por él, por su bien y bienestar eternos,
que cualquiera de ustedes.`"

Entonces le preguntaron si había oído del complot.
Y él dijo: "`Sí.`" Con lo cual,
le preguntaron cómo se había enterado y a quién conocía que estaba involucrado en ello.
Él respondió que se había enterado a través del alguacil principal de Yorkshire,
quien le había contado al Dr. Hodgson que había un complot en el norte;
pero que él no había oído nada al respecto en el sur,
y que no conocía a nadie que estuviera involucrado.
Entonces le preguntaron la razón por la que había escrito contra eso,
si no conocía a nadie que estuviera involucrado en el asunto.
"`Mi razón fue,`" dijo él,
"`porque ustedes son muy rápidos en mezclar al inocente y al culpable; por tanto,
escribí en contra para que la Verdad quedara limpia de esas cosas,
y para detener a todos los espíritus atrevidos e insensatos de correr a tales cosas.
Envié copias de esto a Westmoreland, Cumberland, Bishoprick y Yorkshire,
y a ustedes aquí. También le envié una copia al rey y a su consejo;
y es posible que esté impresa en este momento.`"
Entonces uno de ellos dijo: "`¡Oh este hombre tiene un gran poder!`" "`Sí,`" dijo él,
"`tengo el poder de escribir contra los conspiradores.`"
"`Pero,`" dijo uno de ellos, "`tú estás en contra de la ley de la tierra.`"
"`No,`" dijo él,
"`porque mis amigos y yo dirigimos a todo el pueblo al Espíritu de Dios en ellos,
para hacer morir las obras de la carne.
Esto los lleva al bien y los aleja del mal,
contra el que está la espada de los magistrados.
Esto, en realidad,
alivia a los magistrados que están puestos para castigar a los malhechores.`"

Middleton cansado, según parecía, de lo que decía, gritó:
"`¡Traigan el libro y preséntenle el juramento de lealtad y supremacía!`" Pero G. Fox,
sabiendo que él era un papista, le preguntó si él, que era uno de los que juraban,
había tomado el juramento de supremacía. Porque este
juramento que rechazaba el poder del papa en Inglaterra,
era un tipo de prueba para evidenciar si las personas eran papistas o no.
"`Pero en cuanto a nosotros,`" dijo G. Fox, "`no podemos jurar del todo,
porque Cristo y Sus apóstoles lo prohibieron.`"
Entonces algunos de los que estaban ahí, al ver a Middleton en apuros,
no querían que se le presentara el juramento a G. Fox.
Pero otros lo querían,
sabiendo que esta era su última trampa y que no tenían otra manera de ponerlo en prisión,
porque todas las otras cosas habían sido aclaradas.
Así, pues, se le presentó a G. Fox el juramento,
y al rehusar tomarlo consultaron entre sí acerca de enviarlo a la cárcel;
pero al no estar todos de acuerdo, sólo le ordenaron comparecer en las sesiones, y así,
lo despidieron por el momento.

Entonces regresó con Margaret Fell a Swarthmore, donde el coronel West,
quien era juez de paz en ese momento, llegó a verlo.
Y G. Fox,
preguntándole qué pensaba que le iban a hacer en las próximas sesiones del tribunal,
le respondió, que ellos le presentarían el juramento otra vez.
Acercándose el tiempo de las sesiones,
G+++.+++ Fox fue a Lancaster y se presentó según su compromiso,
donde encontró al juez Flemming en el tribunal,
quien en Westmoreland había ofrecido cinco libras a cualquiera que apresara a G. Fox.
También estaban los jueces Spencer y Rawlinson, el coronel West,
y un gran concurrencia del pueblo,
y cuando G. Fox se acercó al estrado y permaneció con el sombrero puesto,
lo miraron con seriedad.

Luego se llamó a todos a guardar silencio bajo pena de ser encarcelados,
y George dijo dos veces: "`La paz esté entre ustedes.`"
Entonces Rawlinson, que era el presidente, habló y le preguntó si sabía dónde estaba.
A lo que G. Fox respondió: "`Sí lo sé; pero puede que mi sombrero los ofenda.
Pero esta es una cosa pequeña y no es el honor que les doy a los magistrados;
porque el verdadero honor viene de arriba,
y espero que el sombrero no sea lo que ustedes consideran su honor.`"
A esto el presidente dijo: "`Nosotros también deseamos el honor del sombrero.`"
¿En qué muestras tu respeto a los magistrados si no te quitas el sombrero?`"
G+++.+++ Fox respondió: "`Viniendo cuando me llaman.`"
Entonces le ordenaron a uno que le quitara el sombrero.
Tras una pausa,
el presidente le preguntó si él sabía de una conspiración.
A esto respondió que él había oído de ella en Yorkshire,
por un amigo que tenía noticias del alguacil principal.
La siguiente pregunta fue, si él le había declarado esto a los magistrados,
y su respuesta fue:
"`Envié documentos al exterior contra la conspiración y los conspiradores,
y también a ustedes, tan pronto como llegué al condado,
para quitar de sus mentes toda sospecha sobre mí y mis amigos.
Porque ha sido y es nuestro principio declarar contra tales cosas.`"
Luego le preguntaron si él no sabía de una ley contra las reuniones.
A lo que respondió,
que él sabía que había una ley que se aplicaba contra los
que se reunían para aterrorizar a los súbditos del rey,
eran enemigos del rey y sostenían principios peligrosos.
"`Pero espero,`" dijo, "`que no nos consideren tales hombres,
porque nuestras reuniones no son para aterrorizar a los súbditos del rey,
ni somos enemigos de él, ni de ningún hombre.`"

A continuación le presentaron el juramento de lealtad y supremacía. Ante
esto les dijo que él nunca había hecho un juramento en su vida,
y que no podía hacer ningún juramento del todo,
porque Cristo y Sus apóstoles lo habían prohibido.
Entonces Rawlinson, que era abogado, le preguntó si creía que era ilegal jurar.
G+++.+++ Fox claramente percibió que le hacía esta pregunta para atraparlo,
porque por la ley 13 y 14 de Carlos II, capítulo 1,
los que decían que era ilegal jurar quedaban expuestos al destierro o a una gran multa.
Por tanto, para evitar esta trampa les dijo: "`En el tiempo de la ley entre los Judíos,
antes de la venida de Cristo, la ley les mandaba a los hombres jurar; pero Cristo,
quien cumplió la ley en el tiempo del evangelio, ordena no jurar del todo;
y el apóstol Santiago también prohíbe jurar,
incluso a los que eran Judíos y tenían la ley de Dios.`"
Después de muchos otros discursos,
fue llamado el carcelero y G. Fox fue enviado a prisión. Entonces,
teniendo en su poder el documento que había escrito contra los conspiradores,
quiso que fuera leído en el tribunal, pero no lo permitieron.
Siendo encarcelado por rehusarse a jurar,
les dijo a los que estaban en el tribunal y a toda la gente:
"`Tomen nota de que sufro por la doctrina de Cristo y por mi obediencia a Su mandamiento.`"
Después entendió que los jueces tenían instrucciones
privadas del coronel Kirby para procesarlo,
a pesar de su justo comportamiento y aparente amabilidad que había tenido hacia él antes.

Dejando a G. Fox en prisión, voy a decir que la ya mencionada ley,
por la que se les imponía una pena a todos los que dijeran,
"`es ilegal prestar juramento,`" era una ley que se extendía hasta el destierro,
al haber sido hecha no muchos antes y expresamente dirigida contra los Cuáqueros,
como tan claramente se ve por el título.
Por esta ley fueron desterrados muchos de los llamados Cuáqueros después,
como se va a relatar en su debido tiempo y lugar.
Y aunque el rey mismo era de una naturaleza bastante bondadosa,
se dejó influenciar tanto por las instigaciones de algunos hombres
envidiosos (tanto entre los eclesiásticos como entre los laicos),
que dio su consentimiento real.

Mientras G. Fox estaba preso en Lancaster,
muchos de sus amigos también estaban siendo encarcelados por frecuentar reuniones religiosas,
por rehusarse a prestar juramentos y por no pagar los diezmos a los sacerdotes;
pero como no fue llevado a su juicio sino hasta el año siguiente,
lo dejaremos en la cárcel, y mientras tanto nos dirigiremos a Colchester,
donde la persecución era entonces excesivamente fiera.

En el mes de octubre, William More, alcalde del pueblo,
llegó un Primer-día y disolvió la reunión de los llamados Cuáqueros,
y envió a prisión a algunos de ellos.
La siguiente semana hizo lo mismo,
y una semana después hizo que un grupo de las tropas militares del condado entrara
en la reunión. Estos golpearon a algunos e hicieron muchos destrozos en las bancas,
asientos y ventanas del lugar de reunión. Después,
el alcalde empleó a un anciano para que le impidiera
a la gente entrar por la puerta de la sala de reuniones,
diciéndoles a todos los que querían entrar,
que el alcalde lo había puesto ahí para impedirles la entrada.
Aunque ellos sabían que él no era un oficial, ni tenía una orden,
no opusieron resistencia; sino que, reunidos en la calle,
celebraron su reunión de manera pacífica, al no sentirse libres,
por asuntos de consciencia, de dejar su culto público a Dios,
aunque en esa época del año hacía frío y a menudo estaba mojado.
Así continuaron por muchas semanas, aunque con mucha dificultad.

En los primeros días de diciembre,
llegaron a una de estas reuniones cerca de cuarenta soldados del rey a caballo,
en sus armaduras, con sus espadas, carabinas y pistolas, gritando:
"`¿Qué diablos están haciendo aquí?`" Y cayendo violentamente
sobre este inofensivo grupo,
los persiguieron de un lugar a otro por las calles, golpeándolos,
algunos con espadas y otros con carabinas, sin distinción entre hombre o mujer,
joven o viejo, hasta que muchos quedaron muy heridos.
El siguiente Primer-día, estos enfurecidos individuos llegaron otra vez,
tras haber conseguido entonces garrotes,
con los que (así como con sus espadas y carabinas) golpearon muy gravemente
a los que estaban pacíficamente reunidos en la calle para adorar a Dios.
Esta cruel paliza fue tan extrema, que algunos recibieron más de cien garrotazos,
y fueron golpeados hasta que quedaron totalmente magullados
y sus extremidades perdieron la fuerza natural.
Uno de los soldados golpeó por tanto tiempo a una persona,
que la hoja de su espada se salió de la empuñadura,
y al verlo la persona que estaba siendo golpeada le dijo al soldado:
"`Te la devolveré,`" lo cual hizo con estas palabras:
"`Deseo que el Señor no te cargue la obra de este día.`"

Pero para evitar el exceso de palabras,
no mencionaré en detalle todos los abusos que encuentro que fueron
cometidos ahí. Estos crueles actos continuaron por varias semanas,
y algunos fueron golpeados con tanta violencia,
que su sangre quedaba derramada en las calles, y caían y se desmayaban.
Un tal Edward Graunt,
un hombre de unos setenta años (cuya esposa e hijas
yo conocía bien) fue tan terriblemente golpeado,
que después no vivió más que unos pocos días. Este tiempo de persecución fue tan ardiente,
que estos adoradores, cuando iban a sus reuniones,
parecían salir dispuestos a encontrarse con sus muertes;
porque no podían prometerse que regresarían a su hogar ni enteros ni vivos.
Sin embargo, y a pesar de todo, su celo por su adoración estaba tan vivo,
que no se atrevían a quedarse en casa,
aunque el razonamiento humano se los hubiera aconsejado.
Algunos de estos habían sido personas de notoriedad en el mundo;
como (entre otros) un tal Giles Barnadiston,
quien tras pasar seis años en la universidad estudiando literatura humana,
luego llegó a ser coronel, pero con el tiempo,
después de escuchar a G. Fox el joven predicar,
quedó tan completamente convencido de la Verdad declarada,
que dimitió de su mando militar y entró en la sociedad de los llamados Cuáqueros.
Y continuando fiel, con el tiempo llegó a ser ministro del evangelio entre dicho pueblo,
siendo un hombre de espíritu manso, a quien yo conocí muy bien.
Este Giles Barnadiston no dejó de asistir a las reuniones,
a pesar de lo ardiente que era la persecución,
estando completamente entregado a arriesgar su vida con sus amigos.

Un tal Solomon Fromantle, comerciante, a quien yo conocía bien,
fue tan gravemente golpeado que cayó y perdió mucha sangre en la calle, y sin embargo,
los crueles soldados no dejaron de golpearlo.
Su esposa, hija del mencionado Edward Graunt, temiendo que fuera asesinado,
se lanzó sobre él para cubrirlo y protegerlo de los golpes, arriesgando su propio cuerpo,
como me lo contó ella misma en presencia de su esposo--un amor
y fidelidad conyugal muy dignos de ser mencionados y de dejar constancia.
Y aunque ella no recibió golpes muy violentos,
a varias mujeres les tocó la porción de ser severamente
golpeadas con garrotes con púas de hierro.
Entre estas estaba una anciana viuda,
quien recibió no menos de doce sangrientos golpes
de este tipo en varias partes de su cuerpo;
y a otra mujer le perforaron sus lomos con estos garrotes.
Un anciano de sesenta y cinco años fue perseguido
por tres hombres a pie y uno a caballo un gran trecho,
golpeándolo e hiriéndolo tanto, que una mujer compadecida por el anciano,
les dijo a estos tipos perversos que se detuvieran.

Pero esto enfureció tanto al que iba a caballo, que maldiciendo y con rabia,
le dio un fuerte golpe en el hombro con su espada.
Esta barbarie continuó hasta que los perseguidores
parecían estar más cansados que los perseguidos,
quienes parecían crecer en valentía en este tipo de tribulaciones,
sin importar cuán graves fueran.
Un gran promotor de esta furiosa violencia era el capitán Turner,
quien dirigía a sus tropas a actuar de esta manera.
Tal era su malicia, que una vez al irrumpir en una reunión,
él no sólo dio la orden de golpear a las personas, sino también de destruir puertas,
ventanas y paredes, de modo que el daño ascendió a veinticinco libras.

Ahora podría entrar en un gran relato del juicio de muchos
prisioneros en Worcester ante los jueces Hide y Terril,
pero dado que ese juicio fue muy parecido al de John Crook,
ya mencionado aquí en detalle,
sólo haré una breve mención. Cuando los prisioneros fueron llevados al tribunal
y preguntaron por qué habían sido mantenidos por tanto tiempo en prisión,
se les respondió con la pregunta, si prestarían el juramento de lealtad,
y se hicieron esfuerzos para arrastrar a algunos a acusarse a sí mismos,
preguntándoles dónde había estado tal y tal día. Porque si ellos
hubieran dicho "`en una reunión,`" entonces parecería que se habían
acusado por su propia boca de actuar contra la ley,
pero ellos respondieron cautelosamente,
sabiendo que no estaban obligados a acusarse a sí mismo.
A otros se les acusó de haber estado en una reunión,
y cuando dijeron que sus reuniones no siempre eran para adoración pública,
sino que también celebraban reuniones para el cuidado de las viudas,
huérfanos y otros que estaban en necesidad,
se le dijo al jurado que aunque no hubiera evidencia
de que se había predicado en la reunión,
si ellos creían que los prisioneros habían celebrado una reunión de adoración religiosa,
sería suficiente para probar la acusación. Sin embargo,
en otros casos tales procedimientos se habrían considerado totalmente injustificados.

Un tal Edward Bourn fue encarcelado por haber asistido a una reunión,
y luego fue llevado a juicio, donde se le presentó el juramento.
Entre otras palabras dijo en su defensa:
"`Supongan que Cristo y Sus apóstoles celebraran una reunión aquí en este tiempo,
¿se les aplicaría a ellos también esta ley contra los conventículos?`"
"`Sí,`" dijo el juez, "`se les aplicaría.`" Pero luego, repensando su respuesta dijo:
"`No responderé a tus preguntas; ustedes no son apóstoles.`"
El desenlace fue,
que Bourn y varios de sus amigos fueron multados con cinco libras cada uno.

Ahora bien,
dado que los que eran multados por tales cosas normalmente no pagaban
las multas (al juzgar que la cosa por la que habían sido multados
era un deber indispensable que le debían a Dios,
y por lo tanto, no podían pagar ninguna multa de ese tipo con buena consciencia),
por lo general, la consecuencia era el encarcelamiento y la confiscación de sus bienes,
por lo que algunos perdían el doble, o incluso el triple, de la suma de la multa.
Algunos de los prisioneros hicieron ver claramente que habían
estado en otro lugar en el momento de la reunión,
y que no habían estado en la casa de Robert Smith donde se había celebrado; sin embargo,
debido a que no habían respondido satisfactoriamente cuando se
les preguntó si habían estado ahí en algún momento de ese día,
fueron declarados culpables.

Al mencionado Robert Smith se le aplicó la sentencia premunire;
porque cuando le fue presentado el juramento de lealtad,
y fue amenazado por el juez con la sentencia premunire, él preguntó,
con qué propósito se había hecho la ley relativa a ese juramento,
y si se había hecho o no para los católicos.
Y al tener la sospecha de que algunos de esa persuasión estaban sentados en el tribunal,
también preguntó si los que estaban presentes, para satisfacción del pueblo,
no debían prestar también el juramento.
Pero el juez lo desestimó, diciéndole que _él_ debía prestar el juramento,
o de lo contrario, se pronunciaría la sentencia en su contra.
Entonces Smith preguntó, si el ejemplo de Cristo debía decidir el asunto;
pero el juez dijo:
"`No vengo aquí a discutir contigo con respecto a la doctrina de Cristo,
sino a informarte con respecto a la doctrina de la ley.`"
Luego se llevaron a Smith, y después,
cuando se redactó una acusación por negarse a prestar juramento,
fue llevado de nuevo al tribunal y se le preguntó si respondería
o no a la acusación. Pero como no aceptaron las razones que dio,
el juez (antes de que Smith acabara de hablar) dijo:
"`Esta es tu sentencia y el juicio del tribunal:
Quedarás excluido de la protección del rey,
y entregarás tus bienes personales al rey para siempre,
y tus propiedades por el resto de tu vida.`"
A esto Robert dijo con una mente serena: "`El Señor ha dado,
y si Él permite que sea quitado, sea hecha Su voluntad.`"
Así sufrió Robert Smith, junto con muchos más de sus amigos,
tanto ahí como en otros lugares--sobre lo cual,
creo que no sería suficiente mi vida entera para describirlo en detalle.

Dejando entonces las otras persecuciones de este año,
relataré un extraordinario caso que sucedió este año, 1663,
en el que la paciencia triunfó notablemente sobre la violencia.
Pero antes de entrar en esa narración, no estaría de más retroceder un poco,
y mencionar algunos asuntos notables con respecto
al actor principal de la historia que voy a describir.

Su nombre era Thomas Lurting,
quien anteriormente había sido oficial a bordo de un buque de guerra,
y a menudo había sido preservado de peligros inminentes.
Una vez, estando en las Islas Canarias bajo el mando del almirante Blake,
comandante de dicha expedición,
derrotaron al almirante y vicealmirante de los galeones españoles, y hecho esto,
fue enviado con otros siete hombres en una pequeña embarcación de remos,
a prender fuego a los tres galeones que quedaban en la bahía.
Él ejecutó la orden prendiéndole fuego a uno,
que a su vez les prendió fuego a los otros dos.
Pero cuando regresaban, al pasar por un fuerte,
recibieron una descarga de pequeños disparos,
por los que dos hombres (sentados cerca de Thomas) murieron,
y un tercero fue herido en la espalda; aunque Thomas no sufrió ningún daño. Entonces,
saliendo de la bahía, se acercaron,
a una distancia equivalente a cuatro veces el tamaño del bote en que iban,
a un castillo que tenía cuarenta cañones,
y cuando estaban directamente al frente del castillo, fueron disparados los cañones,
y un tiro cortó la cuerda que aseguraba la vela,
apenas por encima de la cabeza de Thomas, aunque sin herirlo.
Él fue extraordinariamente preservado de otros peligros también,
pero para no ser demasiado tedioso,
relataré ahora cómo de ser un marinero luchador pasó a ser un Cristiano inofensivo.

Sucedió por el año 1654, que entre los soldados que estaban en su barco,
había uno que había estado en una reunión de los llamados Cuáqueros en Escocia,
y dos jóvenes que mantuvieron algo de conversación con él;
pero este hombre pronto fue sacado del barco.
Sin embargo, estos dos jóvenes parecían estar un tanto convencidos de la verdad,
porque unos seis meses después de esto,
tuvieron dudas de ir a escuchar al sacerdote de a
bordo y de quitarse sus sombreros ante el capitán,
por lo que llegaron a ser llamados Cuáqueros.
Estos dos a menudo se reunían en silencio,
lo que fue observado por los otros en el barco,
y su número pronto se incrementó. Esto preocupó mucho
al capitán y el sacerdote se enojó un poco,
y le dijo a Thomas Lurting: "`Oh, Thomas, tú eres un hombre honesto y un buen Cristiano,
pero hay una gente peligrosa a bordo--los Cuáqueros,
un pueblo blasfemo que niega las ordenanzas y la palabra de Dios.`"
Esto enfureció tanto a Thomas, que con un celo intolerante,
se dedicó a golpear y a lastimar a estos hombres cuando estaban religiosamente reunidos.
Pero pronto descubrió que esta no era la manera de tener una mente tranquila y sosegada,
porque el recuerdo de sus anteriores liberaciones de la muerte pesaba tanto sobre él,
que encontró que no podía golpear más a ninguno de dicho pueblo.
Después de esto,
Thomas llegó a tener una visión más clara de la clase de hombre que era el sacerdote;
porque cuando él no pudo lastimar más a los Cuáqueros,
el sacerdote dejó de considerarlo un hombre honesto o un buen Cristiano.
Ahora bien, por este tiempo,
sintiéndose bajo condenación debido a los desvíos de su mente del Señor,
le hizo muchas promesas al Señor, pero al ser hechas en su propia voluntad y fuerza,
resultaron de poco efecto.

Entre los llamados Cuáqueros que estaban en el barco, había un tal Roger Dennis,
a quien él amaba mucho y por eso nunca lo golpeó;
porque este hombre tenía tal influencia sobre Thomas, que con sólo que lo mirara,
no se atrevía a tocar a ninguno de los hombres a quienes intentaba lastimar.
Permaneciendo por algún tiempo en ese estado, y sin sentir la paz en su mente,
deseaba mucho estar solo y derramar más libremente su corazón delante del Señor;
y aunque entonces se sentía internamente condenado,
los juicios del Señor se volvieron agradables para él,
porque así su corazón se hacía tierno y quebrantado.
En este estado, a veces no podía dejar de gritar: "`¡Señor!`"
Pero esto, al ser observado por la tripulación,
hizo que algunos dijeran que se había vuelto loco, y otros que estaba enfermo;
y algunos escribieron a Inglaterra con respecto a estas cosas.
Entonces le tocó ser objeto de burla y ser ridiculizado,
pero se esforzaba por rendirse al Señor completamente,
si así podía tener paz en su consciencia con Dios.

Estando solo una noche, delante del Señor,
deseaba muy ferviente conocer a qué pueblo debía unirse;
y entonces le fue mostrado claramente que debía unirse a los Cuáqueros.
Pero esto lo alarmó tanto en ese momento,
que deseó que el Señor lo dejara morir antes que vivir;
porque unirse a un pueblo al que había golpeado y lastimado tan a menudo,
le parecía más duro que la muerte misma.
Y por la sutileza de Satanás, con frecuencia era asaltado con diversos pensamientos,
para mantenerlo alejado de dicho pueblo.
Pero cuando el Señor le hacía recordar sus múltiples preservaciones y liberaciones,
se apaciguaba su corazón, y así finalmente llegó a esta resolución: "`Sea Cuáquero o no,
necesito paz con Dios.`"
Sin embargo, esto le costó muchos suspiros amargos y muchas lágrimas de dolor,
antes de poder llegar a una total rendición. Pero las reprensiones internas del Señor,
acompañadas con juicios, lo seguían tan de cerca,
que no pudo resistirse más y finalmente se rindió.

Entonces aprovechó la oportunidad de exponer su corazón a su amigo Roger Dennis,
quien le habló de tal manera,
que recibió una gran satisfacción. Pero no mucho después de esto,
las tentaciones lo volvieron a asaltar de la siguiente manera: "`¿Qué,
te unirás a un pueblo tan insensato?`"
Y la sola idea de esto le resultaba tan penosa, que incluso llegó a cansarse de su vida;
porque exponerse así al desprecio le parecía una cruz intolerable.
Pero descubrió que esta lucha contra la verdad no era el camino para obtener paz con Dios.
Al llegar el Primer-día, resolvió ir a la pequeña reunión,
que ahora era de seis personas;
pero al informarse que él se había reunido con los Cuáqueros,
muchos otros del grupo dejaron su culto para ir a verlo, y ahí armaron un gran alboroto.
Cuando el tiempo de culto se acabó, el capitán preguntó la razón del alboroto,
y se le dijo:
"`Thomas está entre los Cuáqueros;`" tras lo cual envió por él.
Había también varios oficiales presentes en ese momento,
pero el sacerdote fue el primero en hablar, diciendo: "`Thomas,
te consideraba un hombre muy honesto y un buen Cristiano,
pero lamento que ahora estés tan engañado.`"
Y luego el capitán se esforzó por demostrar con la
Biblia que los Cuáqueros no eran Cristianos.
Mientras tanto, Thomas estaba quieto y tranquilo,
y viendo los otros que no podían convencerlo de esa manera,
tomaron otro curso y dieron muchos falsos informes
acerca de los llamados Cuáqueros a bordo del barco.
Pero debido a que Thomas sabía que esas acusaciones eran completamente falsas,
y veía cómo trataban de derribarlo con mentiras, más fortalecido se sentía; de modo que,
dirigiéndose después adonde sus amigos, les dijo: "`Cuando fui a ver al capitán,
sólo era medio Cuáquero, pero al oír sus mentiras y falsos informes,
ellos han hecho de mí casi un Cuáquero completo; o al menos espero ser uno.`"

Al continuar reuniéndose con sus amigos para celebrar el culto,
algunos más se unieron a ellos,
de modo que en menos de seis meses había doce hombres y dos muchachos,
uno de los cuales era el hijo del sacerdote.
Ahora bien, no había nadie a bordo que quisiera lastimar a los Cuáqueros,
aunque eran muy probados por el capitán,
pues incitaba a algunos hombres de otros barcos a propósito, para exasperarlos.
Pero, independientemente de la ferocidad con la que se comportaran esos otros,
un poder superior los limitaba.
Al final,
se propagó una enfermedad contagiosa a bordo del barco que
arrasó con más de cuarenta en un corto tiempo.
La mayoría de los llamados Cuáqueros también se enfermó, pero ninguno murió por ella,
aunque algunos se vieron muy mal.
Ellos se cuidaron mucho unos a otros mientras estaban enfermos,
y lo que uno poseía era dado para el uso de todos.
Cuando los otros vieron este cuidado,
hizo que algunos de ellos exclamaran en sus lechos de muerte:
"`¡Llévenme donde los Cuáqueros, porque ellos tienen gran cuidado unos por otros,
y cuidarán de mí también!`"

Ahora bien, la visitación de esta enfermedad en el barco cambió tanto al capitán,
que se volvió muy amable con Thomas, y Thomas viéndolo en tan buena disposición,
le solicitó el uso del camarote como lugar de reunión de sus amigos.
Para ese entonces el capitán estaba tan complacido con él,
que cuando había que hacer algo, a menudo decía: "`Thomas, coge a tus amigos,
y has esto y esto.`"
(Todavía estos hombres no estaban en contra de las luchas, y por lo tanto,
no eran completamente Cuáqueros).
Y así, cuando Thomas y sus amigos eran enviados en alguna expedición,
hacían su trabajo más allá de las expectativas del capitán; pero,
aunque todavía no se abstenían de luchar, cuando, con otros,
marchaban contra sus enemigos,
no tomaban nada del botín. En ninguna de esas contiendas recibieron daño alguno,
aunque varios otros murieron y otros fueron heridos; y se comportaban tan valientemente,
que su capitán les decía a otros capitanes,
que no le importaba si todos su hombres fueran Cuáqueros,
porque eran los hombres más resistentes de su barco.
Pero aunque este era un tiempo de paz exterior,
Thomas lo consideraba como un precursor de un ejercicio posterior;
porque veía que lo que le hacían entonces con supuesta amistad,
sólo servía a sus propios fines; por lo tanto, esperaba un tiempo de prueba por venir,
y así fue.

Por haber llegado a Leghorn,
se les ordenó ir a Barcelona para tomar o quemar
un buque de guerra español. Sus órdenes eran entonces,
ponerse frente a un castillo y bombardearlo, lo que hicieron,
y los llamados Cuáqueros pelearon con tanto valor como cualquier otro.
Al descubrir Thomas que desde una de las esquinas
del castillo empezaron a disparar contra su barco,
se dedicó a derribar esa parte.
Luego, despojándose de su chaleco y yendo hacia la parte delantera de la cubierta,
comenzó a nivelar los cañones, y dijo:
"`No disparen hasta que salga y vea desde donde nos están disparando,
para que podamos apuntar nuestros cañones más alto o más bajo.`"
Pero mientras salía a ver desde donde procedían los disparos del enemigo,
repentinamente lo atravesó: "`¿Qué pasa si ahora matas a un hombre?`"
Esto lo impactó como un rayo;
y Aquel que puede volver los corazones de los hombres a Su placer,
cambió el de Thomas a tal grado en un minuto que,
mientras que justo antes había empleado toda su fuerza para matar hombres,
ahora no hallaba en sí mismo ninguna voluntad para ello,
aunque fuera para ganar el mundo;
porque inmediatamente percibió que esa convicción venía del Señor. Luego,
poniéndose su ropa,
caminó sobre la cubierta como si no viera que los cañones estaban siendo disparados,
y estando bajo un gran ejercicio mental, algunos le preguntaron si estaba herido.
Él respondió: "`No;
pero tengo dudas de consciencia con respecto a luchar,`" aunque
en ese momento él no sabía que los Cuáqueros se negaban a pelear.

Cuando llegó la noche, salieron del alcance de los cañones del castillo,
y él aprovechó el momento para hablar con dos de sus amigos en el barco,
preguntándoles sus opiniones con respecto a la lucha.
Sus amigos dieron poca respuesta, sin embargo, dijeron:
"`Si el Señor nos manda bien a casa, nunca lo volveremos a hacer.`"
A esto Thomás replicó, que si era honesto con el don de Dios en su propia consciencia,
y fueran enviados a pelear al día siguiente,
con la ayuda del Señor daría su testimonio en contra; porque veía claramente,
que aunque habían sido grandes actores en la lucha anteriormente,
ahora debían dar sus testimonios contra ella, y esperar a ver qué resultaría de eso;
diciendo entre ellos: "`La voluntad del Señor sea hecha.`"
Al día siguiente se enteraron de que varios habían muerto en tierra,
lo que entristeció no poco a Thomas.
Un tiempo después de esto,
uno de los amigos de Thomas fue a ver al capitán a pedirle que le diera de baja.
El capitán le preguntó la razón,
y su respuesta fue que no podía luchar más. Ante esto el capitán dijo:
"`Si alguien se niega a luchar en tiempo de combate,
le clavaré mi espada en las tripas.`"
"`Entonces,`" dijo el otro,
"`serás un homicida y culpable de derramar sangre;`" por lo que el capitán (que
también era un predicador Bautista) lo golpeó fuertemente con el puño y el bastón,
de modo que, el que había sido amigo de ellos,
se había convertido en enemigo declarado de ellos.

Tiempo después de esto, alrededor del año 1665, estando en Leghorn,
se les ordenó ir de crucero,^
footnote:[Es decir, a navegar de un lado a otro en busca de barcos enemigos.]
y una mañana divisaron un gran barco que se dirigía hacia ellos,
el cual supusieron que era un buque de guerra español. Inmediatamente
se dieron órdenes de despejar el barco y prepararse para la lucha.
Estando Thomas sobre la cubierta,
vio claramente que había llegado el momento de la prueba,
y le oró al Señor muy fervorosamente que lo fortaleciera.
Le pareció que lo más conveniente sería reunirse con sus amigos, lo cual,
después de dar aviso, fue hecho consecuentemente.
Estando juntos les dijo cómo se sentía, y que las cosas parecían muy oscuras y nubladas;
y sin embargo,
que su esperanza era que el Señor lo librara a él y a todos lo que eran de su fe;
a lo que agregó: "`No pongo esto como un mandato sobre nadie,
sino que los dejo a todos en manos del Señor.`" Además dijo: "`Debo decirles,
que el capitán tiene gran confianza en ustedes.
Por lo tanto, seamos cuidadosos de no darle una razón justa de sentirse ofendido.
Todos los que sean de mi opinión, reunámonos en la parte más pública de la cubierta,
a plena vista del capitán,
para que no diga que lo engañamos al no decirle que no pelearíamos, y que de ese modo,
pueda poner a otros en nuestros lugares.`"

Luego Thomas subió a cubierta y puso la espalda contra el cabrestante,^
footnote:[Un cabrestante es una máquina giratoria de eje
vertical desarrollada para su uso en barcos de vela y multiplicar
la fuerza de tracción de los marineros al tirar de los cabos.]
y un poco después, volviendo su cabeza, vio a sus amigos subir detrás de él. Al ver esto,
aunque se alegró, su corazón se agitó dentro de él,
sintiendo que estaban ahí como ovejas listas para la matanza.
Al poco tiempo, el teniente llegó y le dijo a uno de ellos:
"`Baja a tu cuartel;`" a lo que el hombre respondió:
"`No puedo pelear más.`" Entonces el teniente se dirigió al capitán,
e hizo lo peor diciendo: "`Los Cuáqueros están todos juntos y puede que se amotinen;
y uno dice que no puede pelear.`"
El capitán le preguntó el nombre y se fue donde él, le arrojó el sombrero por la borda,
y luego, agarrándolo por el cuello,
lo golpeó con un gran bastón y lo arrastró hasta su cuartel.
Luego subió de nuevo a la cubierta y pidió su espada, la cual, al recibirla de su criado,
desenvainó con gran furia.
Apenas había hecho eso,
cuando la palabra del Señor atravesó a Thomas (según la tomó él) diciendo:
"`La espada del Señor está sobre él, y si él desea un sacrificio, ofréceselo.`"
Esta palabra corrió a través de él tan poderosamente,
que Thomas temblaba y se estremecía, aunque se esforzaba por detenerlo,
temiendo que pensaran que tenía miedo, lo cual no era así. Luego,
volviendo su cabeza sobre sus hombros, le dijo a su amigo Roger:
"`Debo ir a ver al capitán.`" A lo que Roger respondió:
"`Asegúrate de saber lo que haces.`"
Y Thomas respondió:
"`Una necesidad está puesta sobre mí.`" Al ver que
el capitán se les acercaba con la espada desenvainada,
Thomas fijó sus ojos con gran seriedad sobre él y dio un paso hacia él,
manteniendo sus ojos sobre el capitán con mucho temor en el Señor,
sintiéndose elevado por encima de su furiosa mirada.
Ante esto, el semblante del capitán repentinamente palideció,
y dándose vuelta llamó a su criado para que le quitara la espada, y se fue.
No mucho después, el barco contra el que esperaban pelear resultó ser genovés,
amigo de ellos;
y antes de la noche el capitán envió al sacerdote
a ver a Thomas para pedirle disculpas por su ira,
diciendo que había actuado con cólera.
A esto Thomas respondió que no tenía más que buena voluntad hacia él,
y le pidió al sacerdote que le dijera al capitán que tuviera cuidado de tales pasiones,
porque si mataba a un hombre estando encolerizado,
podría ser que aunque buscara el arrepentimiento no lo encontrara.
Así venció Thomas esta tormenta, y al final llegó a salvo a casa.

Después, dejando los barcos militares, se hizo a la mar en un barco mercante; pero luego,
en varias ocasiones se vio forzado a servirle al rey, y así,
siendo llevado a un buque de guerra sufrió mucho.
Una vez ayunó durante cinco días, tomando a veces sólo un trago de agua,
porque vio fácilmente que si hubiera comido de la comida de ellos, le habría ido peor;
porque se negaba a hacer algún trabajo en el barco,
aunque no estuviera en una lucha activa,
pues juzgaba que ayudaba a los que tenían como negocio la lucha.
Por tanto, en un barco así, descubrió que no podía hacer casi nada, fuera lo que fuera,
sin ayudar y apoyar la guerra.

En esta condición se topó con varios sucesos rudos, durante algunos años seguidos.
En una ocasión, estando en Harwich trabajando duro en un barco,
mientras cargaba trigo en una pequeña embarcación de fondo plano,
fue reclutado para el servicio del rey.
Pero uno de los hombres dijo que él era un Cuáquero,
y el capitán que había llegado a bordo en la pequeña embarcación le dijo burlonamente:
"`Tú no eres Cuáquero, porque si fueras un Cuáquero, estarías esperando en el Señor,
y dejando que Sus cuervos te alimentaran,
y no trabajando duro con tu cuerpo;`" porque Thomas vestido sólo con su camiseta y calzoncillos,
tenía la camiseta mojada de sudor.
Finalmente, después de un breve silencio Thomas le dijo al capitán:
"`Veo que has leído algunas partes de las Escrituras.
¿Has leído que el que no provee para su familia es peor que un infiel?
A menudo he oído que se culpa a los Cuáqueros de no trabajar,
pero tú eres el primero que oigo que los critica por hacerlo.`"
A esto el capitán dijo: "`¡Llévenselo, es un Cuáquero!`"
Pero un poco después gritó: "`¡Tráiganlo de nuevo, no es un Cuáquero!`"
Entonces le dijo a Thomas: "`Tú no eres un Cuáquero,
porque tú traes trigo aquí y de él se hace pan,
y por la fuerza de dicho pan matamos a los holandeses.
Por tanto, no eres Cuáquero.
¿Acaso no eres tan cómplice de sus muertes como nosotros?
Respóndeme.`"
Por no responder inmediatamente,
Thomas fue objeto de burla y abucheos por parte de los marineros,
pero al fin le dijo al capitán: "`Soy un hombre que puedo alimentar a mis enemigos,
y lo mismo puedo hacer con ustedes, que pretenden ser mis amigos.`"
A esto el capitán replicó: "`¡Llévenselo, es un Cuáquero!`"

Pero unos pocos días después, fue forzado a salir de nuevo del barco mercante,
y llevado a bordo de un buque de guerra.
Ahí se le ordenó ir al camarote, donde estaban el capitán y varios oficiales.
Al entrar, el capitán empezó a maldecir a los Cuáqueros,
y juró que si no colgaba a Thomas, lo llevaría ante el duque de York,
y con seguridad él lo haría. Pero Thomas dijo muy
poco y se sintió guardado por el Señor del temor.
Y cuando el capitán se cansó de clamar y de increpar, dijo más blandamente: "`Qué,
¿no dices nada por ti mismo?`"
Thomas respondió:
"`Tú dijiste suficiente por ti mismo y por mí;`" porque halló más seguro decir poco.
Esto, ciertamente, fue lo mejor; porque por lo general, ninguna razón, por buena que sea,
es aceptable para los hombres apasionados,
que con frecuencia piensan que escuchar a alguien que consideran inferior,
está por debajo de ellos.
Pero estos a veces se dan cuenta de que están equivocados, como le pasó a este capitán,
quien a pesar de su altivez, pronto fue impactado por un poder superior.
Porque la noche siguiente, repentinamente se oyó un grito: "`¿Dónde está el Cuáquero?
¿Dónde está el Cuáquero?`"
Cuando Thomas lo oyó dijo: "`¡Aquí estoy! ¿Qué se necesita a esta hora de la noche?`"
A lo que se le respondió: "`Debes venir a ver al capitán inmediatamente.`"
Entonces, al llegar a la puerta del camarote el capitán preguntó:
"`¿Está ahí el Cuáquero?`"
"`Sí,`" respondió Thomas, y el capitán le dijo: "`No puedo dormir.
Debes irte a tierra.`"
Thomas replicó: "`Estoy en tu poder, y puedes hacer conmigo lo que quieras.`"
De este modo y por orden del capitán, fue llevado en la embarcación a tierra en Harwich,
quien en su furia había previamente dicho que colgarlo era demasiado bueno para él,
pero ahora, debido a que su mente estaba perturbada no podía dormir, aunque Thomas,
que estaba acostado sobre las duras tablas, dormía muy bien.

Habiendo dicho mucho de ese marino,
veamos ahora cómo y de qué diligente manera recuperó
un barco que había sido tomado por un pirata,
sin traspasar los límites de una disposición apacible.
Esto sucedió en el año 1663, de la siguiente manera:

Por el mes de octubre, el capitán de un barco cuyo nombre era George Pattison,
uno de la sociedad de los llamados Cuáqueros,
estando con su barco en el Mediterráneo camino a Venecia,
fue perseguido por un pirata de Argel cerca de la isla de Mallorca;
y como su barco navegaba bien, se esforzaron por escapar.
No obstante, al llevar demasiada vela, parte de su equipo cedió,
por lo que los turcos se acercaron al lado de ellos y le
ordenaron al capitán que subiera a bordo de su barco,
quien, en conformidad, se fue en una pequeña embarcación junto con otros cuatro hombres,
dejando a bordo de su barco solamente a su oficial (el ya mencionado Thomas Lurting),
con tres hombres y un muchacho.

Tan pronto como los ingleses subieron a bordo del barco pirata,
los turcos metieron en la embarcación a trece o catorce
de sus hombres para regresar al barco inglés. Mientras tanto,
Thomas estaba muy atribulado,
y más porque el capitán y cuatro de sus hombres estaban entonces con los turcos,
y los que habían quedado a bordo eran algo revoltosos.
Sin embargo, en esta preocupación, creyó que el Señor le había dicho internamente:
"`No temas, porque no irán como prisioneros a Argel.`"
Y habiendo tenido anteriormente una gran experiencia de las liberaciones del Señor,
como ha sido mencionado antes,
ya había aprendido a confiar en Dios a pesar de todas las apariencias externas.
Al considerar eso, se quitó de él todo temor,
y yendo al costado del barco para ver a los turcos abordar,
los recibió como si fueran sus amigos, y ellos también se comportaron civilizadamente.
Luego les mostró toda la nave y la carga que llevaba.
Después les dijo a los hombres que estaban con él: "`No teman,
porque a pesar de todo esto, no iremos a Argel.
Pero permítanme pedirles, que así como han estado dispuestos a obedecerme,
estén dispuestos a obedecer a los turcos de la misma forma.`"
Ellos se lo prometieron, y al hacerlo,
pronto se dio cuenta de que se ganaban el favor de los turcos;
porque al ver la diligencia de los marineros,
se volvieron más descuidados y favorables hacia ellos.
Y tras tomar una pequeña cantidad de la carga,
algunos de ellos regresaron a su propio barco,
y ocho turcos se quedaron con los ingleses.

Entonces Thomas empezó a pensar en el capitán y en
los otros cuatro que estaban en el barco turco.
Porque en cuanto a sí mismo y a los otros que estaban con él, no tenía temor alguno;
en efecto, estaba tan lejos de eso, que le dijo a uno de sus hombres:
"`Si el capitán estuviera a bordo y el resto de nuestros hombres también,
aunque hubiera el doble de turcos, no les temería.`" Con esto animó a los marineros,
que al no ser de su persuasión religiosa, pensaban muy diferente a él,
y habrían estado lo suficientemente dispuestos a
matar a los turcos si hubieran visto una oportunidad.
Mientras tanto, Thomas le pedía fervientemente al Señor,
que pusiera en el corazón de los turcos enviar de regreso al capitán y a los otros cuatro.
Y su deseo fue respondido; porque poco después de esto,
el capitán y aquellos hombres fueron devueltos a bordo.

Entonces, toda clase de temor con respecto a ir Argel fue quitado de él,
lo que hizo que algunos dijeran que era un hombre extraño,
porque antes tenía temor de ser apresado, pero después no.
Pues antes de que fueran apresados, habiendo oído que había muchos turcos en el mar,
trató de persuadir al capitán de ir a Leghorn y esperar allí un convoy,
pero el capitán no había estado de acuerdo.
Por lo tanto, para responderles a los hombres que pensaban que su conducta era extraña,
Thomas les dijo: "`Ahora creo que no iré a Argel; y si permanecen bajo mi dirección,
actuaré tanto por la liberación de ustedes como por la mía.`" No obstante,
aunque dijo esto con valentía, no veía cómo podrían ser liberados,
porque todos los turcos estaban armados, y los ingleses no tenían armas.

En un momento, cuando los ingleses estaban todos juntos excepto el capitán,
Thomas les dijo: "`¿Qué, si domináramos a los turcos y luego fuéramos a Mallorca?`"
Ante esto la tripulación se alegró mucho, y uno dijo: "`Mataré a uno o dos.`"
"`Y yo,`" dijo otro, "`le cortaré la garganta a tantos como ustedes quieran.`"
Pero Thomas se afligió mucho ante estas palabras,
porque él intentaba no herir a ningún turco, y por tanto les dijo:
"`Si yo me entero de que alguno de ustedes quiere
tocar a alguno de los turcos para herirlo,
yo mismo se los diré. Pero,`" añadió, "`si se someten a mi dirección,
actuaré por ustedes, y si no, me quedaré quieto.`"
Los otros, viendo que no les permitiría tomar su propio camino,
acordaron hacer lo que les pedía. "`Pues bien,`" dijo Thomas,
"`si los turcos les ordenan hacer algo, háganlo sin quejarse,
y con toda la diligencia y rapidez que puedan, porque eso les agrada,
y hará que nos dejen permanecer juntos.`"
Todos los hombres estuvieron de acuerdo.
Entonces Thomas fue a ver al capitán y le contó la intención que tenían,
pero el capitán replicó: "`Si nos levantamos contra ellos y nos vencen,
más vale que nos quemen vivos.`"
Thomas sabía muy bien que el capitán tenía razón, es decir,
que si fallaban en el intento,
probablemente se toparían con el trato más cruel que los turcos pudieran imaginar.
Ahora bien, la razón por la que el capitán, aunque un hombre muy valiente,
no aprobó fácilmente la propuesta, era porque temía que derramaran sangre.
Pero Thomas le dijo que ellos estaban decididos a hacerlo sin derramar una gota de sangre:
"`Y además,`" dijo él, "`yo preferiría ir a Argel, que matar a un turco.`"
Hablando así convenció al capitán de manera tal,
que al final accedió a que hiciera lo que quería, siempre que no mataran a nadie.

Ahora bien, como dos turcos permanecían en el camarote con el capitán,
se acordó que él continuara allí para que no sospecharan nada.
Mientras tanto, empezó a hacer mal tiempo,
de modo que perdieron la compañía del buque de guerra turco,
que era lo que Thomas más deseaba.
Y al ver los turcos la diligencia de los marineros ingleses, se despreocuparon de ellos,
que era algo que Thomas también pretendía. La segunda noche después de esto,
el capitán de los turcos y uno de su grupo fueron a dormir al camarote con el
capitán. Entonces Thomas convenció a uno a que se fuera a dormir al camarote,
y cerca de una hora después a otro en otro camarote; y al final,
como estaba lloviendo mucho, persuadió a todos a acostarse y dormir.
Cuando todos estaban dormidos, se acercó a los turcos y se apoderó de sus armas.
Hecho esto, les dijo a sus hombres: "`Ahora tenemos a los turcos bajo nuestras órdenes,
pero nadie herirá a ninguno de ellos; porque si lo hacen, yo me pondré contra ustedes.
Esto es lo que haremos, ahora que ellos están bajo la cubierta,
los mantendremos ahí e iremos a Mallorca.`"
Y habiéndoles ordenado a algunos que vigilaran las puertas,
pusieron rumbo hacia Mallorca, y debido a que había un fuerte vendaval,
se acercaron a ella por la mañana.
Entonces Thomas les ordenó a sus hombres, que si alguno de los turcos quería salir,
no fuera más de uno o dos a la vez; y cuando uno salió, esperando ver su propio país,
no fue poca la sorpresa cuando en su lugar vio Mallorca.
Luego Thomas les dijo a sus hombres: "`Tengan cuidado ahora con la puerta,
porque cuando entre y hable con ellos,
veremos qué harán. Pero tengan cuidado de no derramar sangre.`"
Cuando el turco bajó al camarote y les contó a sus compañeros lo que había visto,
y que iban hacia Mallorca, en lugar de levantarse, se echaron a llorar,
porque se quedaron sin valor,
y les rogaron a los ingleses que no los vendieran como esclavos.
Thomas les prometió diciendo, que no los venderían. Y cuando los tranquilizó,
entró en el camarote del capitán, quien todavía no sabía nada de lo que había sucedido,
y le dio cuenta del repentino cambio y de cómo habían vencido a los turcos.
Y al comprender entonces lo que había sucedido,
le informó al capitán de los turcos que la nave ya no estaba en su poder,
sino en el suyo; y que iban hacia Mallorca.
Ante esta inesperada noticia el capitán de los turcos
lloró y le pidió al capitán que no lo vendiera,
y el capitán prometió que no lo haría. También le dijeron,
que harían un lugar para esconderlos,
para que los españoles que subieran a bordo no los encontraran.
Y así lo hicieron, por lo que los turcos se alegraron mucho.

Cuando llegaron al puerto de Mallorca, el capitán y cuatro de sus hombres,
fueron a tierra, y dejaron a Thomas a bordo con los diez turcos.
Al terminar sus negocios, el capitán regresó a bordo sin tomar licencia,
para que los españoles no subieran a bordo y vieran a los turcos.
Pero otro capitán inglés, que era conocido y estaba en el mismo puerto con su barco,
subió a bordo por la noche, y después de un rato de conversación,
le contaron lo que habían hecho, bajo promesa de silencio,
para que los españoles no subieran y se llevaran a los turcos.
Pero este hombre rompió su promesa,
porque quería llevarse con él a Inglaterra a dos o tres turcos,
pero al comprender su plan, le negaron la petición, y viendo que no podía prevalecer,
les dijo a Pattison y a su oficial que eran unos tontos,
porque no querían vender a los turcos,
que valían unas doscientas o trescientas piezas de plata cada uno.
Pero ellos le dijeron, que aunque les ofrecieran muchos miles, no aceptarían ni una,
porque esperaban enviarlos de regreso a casa; "`y,`" dijo Thomas,
"`no los vendería ni por toda la isla.`"

Luego, el otro capitán fue a tierra y les contó a los españoles lo que sabía,
quienes entonces amenazaron con llevarse a los turcos.
Pero al oírlo Pattison y su oficial, reunieron a los turcos y les dijeron:
"`Ustedes deben ayudarnos, o los españoles se los llevarán.`" Al escuchar esto,
los turcos, como es fácil de imaginar, estuvieron muy dispuestos a ayudar,
por lo que rápidamente se hicieron a la mar.
Y los ingleses, a fin de salvar a los turcos,
se pusieron en riesgo de ser vencidos por ellos otra vez,
pues siguieron navegando por varios días,
porque no querían entrar en ningún puerto de España, por temor a perder a los turcos.
Por cuatro o cinco días se les dio libertad a los turcos,
hasta que intentaron levantarse contra los ingleses,
que Thomas impidió sin herir a ninguno de ellos,
aunque en una ocasión tuvo que sujetar a uno.
Sin embargo, generalmente era tan amable con ellos,
que algunos de sus hombres refunfuñaban y decían
que se preocupaba más por los turcos que por ellos.
A lo que él les respondía, que ellos eran extranjeros y por eso debían tratarlos bien.
Finalmente, después de varios sucesos,
Thomas le dijo al capitán que él pensaba que lo mejor era ir a las costas de Barbary,
porque entonces era probable que evitaran los buques de guerra.
El capitán accedió a ello.
No obstante, para engañar a los turcos, navegaron de un lado a otro por varios días;
ya que durante el día se dirigían hacia Argel,
pero al llegar la noche tomaban el camino contrario y regresaban,
con lo cual mantenían a los turcos en la ignorancia, para estar tranquilos.

Pero el noveno día, estando todos en la cubierta,
cuando no había más ingleses que el capitán, su oficial y el hombre del timón,
los turcos empezaron a mostrarse tan obstinados y altaneros,
que a Thomas le pasó por la mente,
qué pasaría si agarraban al capitán y lo lanzaban por la borda;
pues ellos eran diez hombres fuertes y el capitán
un hombre pequeño. Este pensamiento lo aterró,
pero recapacitando y tomando valor,
golpeó con su pie para llamar a los hombres a cubierta,
y uno de ellos pidió una palanca y otro un hacha, a fin de caer sobre los turcos.
Pero Thomas les ordenó no herir a ninguno, y dijo:
"`Yo me encargaré de su capitán,`" y así lo hizo.
Pues habiendo oído que ellos amenazaban al capitán Pattison,
se adelantó y sujetando al capitán turco le dijo que debía bajar,
lo cual hizo muy tranquilamente, con todo el resto siguiéndolo.

Dos días después, tras llegar a las costas de Barbary,
estaban (según decían los turcos) a unas cincuenta millas de Argel, y a seis de tierra.
Por la tarde el mar se empezó a calmar,
pero aún no se había resuelto cómo poner a los turcos en tierra.
Thomas entendía muy bien, que puesto que él era el hombre que había iniciado este asunto,
también le tocaría llevarlo a su fin.
Entonces le dio a conocer al capitán,
que él estaba dispuesto a llevar a los turcos a tierra,
pero que aún no sabía cómo hacerlo con seguridad,
porque entregarles la embarcación pequeña era demasiado peligroso,
pues ellos podrían reunir más hombres y armas,
y luego regresar y retomar el barco con su propio bote.
Llevarlos a tierra con dos o tres hombres del barco era también un gran peligro,
porque los turcos eran diez, y poner a la mitad en tierra no era menos peligroso,
porque entonces podrían alertar a los hombres del país,
y así sorprender a los ingleses cuando llegaran con la otra mitad.
En esta gran aprieto Thomas le dijo al capitán:
"`Si me dejas la embarcación pequeña y llevar a tres hombres conmigo,
me aventuraré a poner a los turcos en tierra.`"
El capitán, confiando tal vez en la conducta de su oficial, accedió a la propuesta,
aunque no sin que ambas partes derramaran algunas lágrimas.
Sin embargo, Thomas tomando valor le dijo al capitán:
"`Yo creo que el Señor me preservará,
porque no tengo más que buena voluntad al arriesgar mi vida,
y no tengo el menor temor sobre mí, sino que confío en que todo saldrá bien.`"

Tras recibir el consentimiento del capitán,
Thomas llamó a los turcos y entrando con dos hombres
y un muchacho en la embarcación pequeña,
subió a los diez turcos, todos sueltos y sin ataduras.
Tal vez alguien piense que este fue un acto muy descuidado,
y que habría sido más prudente que los turcos tuvieran las manos atadas, especialmente,
porque él les había hecho prometer a sus hombres
que no les harían nada a los turcos sin su permiso,
dándoles toda la libertad a los turcos de actuar en favor
de sus propias vidas según juzgaran conveniente.
Pero como no sabía cuán cerca de la costa podría dejar a los turcos,
y si tendrían que nadar un poco,
no le pareció prudente hacer algo que pudiera exasperarlos;
porque si ocurría que tenían que nadar, entonces tendrían que desatarlos,
y eso sería muy peligroso.
Sin embargo, Thomas no dejó de tener todo el cuidado posible.
Porque llamando al capitán de los turcos, lo colocó primero en la popa de la embarcación,
luego llamó a otro y lo colocó en el regazo del capitán, y luego llamó a dos más,
y los puso uno a cada lado del capitán, y a dos más en los regazos de estos,
y así hasta que colocó a todos,
y lo hizo de este modo para evitar que pudieran hacer un levantamiento repentino.
Él se sentó en la proa de la embarcación con un garfio en la mano,
tenía a su lado a uno de los hombres del barco, y los otros dos que iban a remar,
uno con un formón de carpintero y el otro con una navaja.
Estas eran todas las armas que llevaban, además de las que les pertenecían a los turcos,
las cuales tenían en su poder.
Así partió la embarcación y se dirigió a la orilla.
Pero conforme se acercaban, los ingleses empezaron a asustarse,
y uno de ellos gritó de repente: "`¡Señor ten misericordia de nosotros,
hay turcos en los arbustos de la orilla!`"
Al percibir los turcos en la embarcación que los ingleses tenían miedo,
se levantaron a la vez.
Pero Thomas, quien en ese gran trance continuaba imperturbable,
demostró ser entonces un hombre valiente.
Les ordenó a los hombres que tomaran las armas que tenían,
pero que no hicieran nada con ellas hasta que él les diera permiso.
Y luego,
viendo que no había hombres en los arbustos y que sólo era la imaginación del otro,
se le quitó todo temor.
Al incrementarse su valor pensó dentro de sí:
"`Es mejor golpear a un hombre que cortarle la cabeza;`"
y así girando su garfio en la mano,
le dio un fuerte golpe al capitán y le ordenó que se sentara, lo cual hizo al instante,
al igual que todos los demás. Cuando la embarcación se acercó lo suficiente a la orilla,
tanto que se podía vadear fácilmente el mar,
el oficial les ordenó a los turcos que saltaran, y así lo hicieron,
y como ellos habían dicho que estaban a unas cuatros millas del pueblo,
les dio unos panes y otros artículos de primera necesidad.

Ellos habían persuadido con gran entusiasmo a los
ingleses para que fueran con ellos a un pueblo,
prometiéndoles agasajarlos con vino y otras cosas buenas,
pero aunque Thomas confiaba en la divina Providencia,
no era tan descuidado como para entrar voluntariamente a un aparente peligro sin necesidad.
Porque aunque él en ese momento creía que los turcos no le harían ningún mal,
le parecía demasiado arriesgado rendirse así a la misericordia de los que vivían ahí;
y por lo tanto, rechazó muy prudentemente la invitación,
sabiendo bien que las Escrituras dicen: "`No tentarás al Señor tu Dios.`"
Viendo los turcos que no lo podían persuadir,
se despidieron con muestras de gran amabilidad, y se fueron a tierra.
Luego, los ingleses pusieron la embarcación más cerca y arrojaron las armas a la orilla,
pues no querían quedarse con nada que les perteneciera.
Y cuando los turcos subieron a una colina, agitaron sus gorras a los ingleses,
y así se despidieron alegremente por última vez.
Tan pronto como la embarcación subió de nuevo a bordo del barco,
tuvieron un viento favorable,
algo que no habían tenido todo el tiempo que los turcos habían estado a bordo.
Y así salvó Thomas Lurting el barco y a sus hombres; los cuales,
así maravillosamente preservados, regresaron a salvo a Inglaterra con un viento próspero.

Ahora bien, antes de que la nave llegara a Londres,
las noticias de este extraordinario caso ya habían llegado ahí;
y cuando estaban subiendo por el Támesis, se le dijo al rey,
al duque de York y a varios lores que estaban en Greenwich,
que venía subiendo por el río un barco de Cuáqueros,
que había sido tomado por lo turcos y que se había redimido sin luchar.
Al oír esto el rey, llegó con su barcaza a un costado del barco,
y sosteniendo en su mano la cuerda de entrada,
escuchó de la propia boca de Thomas cómo habían sucedido los hechos.
Pero cuando le oyó decir cómo habían dejado libres a los turcos, le dijo al capitán:
"`Tú has actuado como un tonto,
pues podrías haber obtenido una buena ganancia por ellos.`"
Y a Thomas le dijo: "`Debiste traerme a los turcos.`"
Pero Thomas le respondió:
"`Pensé que era mejor para ellos estar en su propio
país.`" Ante esto el rey y los demás sonrieron,
y se fueron, pensando que el capitán había actuado tontamente.
Pero él y su oficial eran de otra opinión,
y así hicieron ver que aprobaban la lección de nuestro Salvador: "`Amen a sus enemigos,
y hagan el bien a los que los aborrecen,`" no sólo con sus bocas,
sino también con sus actos.

Aunque he descrito estos hechos a partir de un relato impreso,
he añadido algunas circunstancias de boca de Thomas Lurting,
con quien tuve cierta relación.

Varios años después,
cuando algunos marineros del pueblo llamado Cuáqueros eran esclavos en Argel,
G+++.+++ Fox les escribió un documento al sultán y al rey de Argel,
en el que les exponía sus comportamientos indecentes y tratos irracionales,
mostrándoles por su Corán que eso le desagradaba a Dios,
y que Mahoma les había dado otras instrucciones.
A esto le agregó una breve narración de lo que ha sido relatado aquí,
de la captura y recuperación del barco de George Pattison,
y de cómo habían sido liberados los turcos sin haber sido esclavizados,
por medio de lo cual los mahometanos podrían ver qué clase de Cristianos eran los Cuáqueros,
es decir, aquellos que efectivamente mostraban que amaban a sus enemigos,
según la doctrina de su supremo legislador, Cristo.

Ahora, con respecto a los Cuáqueros en Argel,
de quienes se ha hecho mención que eran esclavos ahí,
pasó bastante tiempo antes de que se encontrara la oportunidad de rescatarlos.
Pero mientras tanto, les sirvieron tan fielmente a los amos,
que se les permitía andar sueltos por el pueblo, sin cadenas o sin grilletes,
y también se les daba libertad de reunirse a horas fijas para el culto religioso.
Sus propios amos algunas veces iban y veían lo que los esclavos hacían en las reuniones,
y al no hallar imágenes o cuadros (como los que usaban
los Católicos Romanos en el ejercicio de su culto),
sino que estos reverentemente adoraban y honraban al Dios vivo,
el Creador del cielo y de la tierra, los elogiaban por esto,
y decían que eso era muy bueno y que podían hacerlo libremente.
Y como uno de ellos se levantó para hablar a manera de edificación para sus amigos,
algunos otros esclavos ingleses que asistían a sus reuniones llegaron a unirse a ellos.
Mientras tanto,
el nombre de los Cuáqueros llegó a ser conocido en Argel
como un pueblo en el que se podía confiar más que en otros.

En este año William Caton llegó a Inglaterra con
su esposa desde Holanda (donde se había casado),
junto con otros dos amigos, una de las cuales era Judith Zinspenning, mi madre,
quien fue movida a hablar en la reunión en Kingston,
en la que William Caton tradujo para ella.
Y en otro momento, estando ella en la reunión en Londres y W. Caton ausente,
y sintiéndose impulsada a declarar de la amorosa
bondad del Señor para con los que Le temían,
quiso que un tal Peter Sybrands fuera su traductor; pero él,
aunque era un hombre honesto, no era muy apto para esa obra.
Sin embargo,
uno o más amigos le dijeron que ellos eran tan sensibles al poder por el que ella hablaba,
que aunque no entendieran sus palabras,
eran edificados por la vida y poder que acompañaban su discurso, y por lo tanto,
que la falta de traducción importaba muy poco; y así, continuó sin traductor.
Ella tenía, en efecto, un muy buen don, y dejó tal sabor tras de sí,
que cuando yo llegué a Inglaterra varios años después de esto,
en muchos lugares me mostraron amabilidad por causa de ella.
Después de estar algunas semanas en Londres y sus alrededores,
ella se fue a Colchester para regresar con la esposa de W. Caton a Holanda.
Pero quedándose primero en esa ciudad, escribió un libro de proverbios, el cual,
después de que W. Caton lo tradujo al inglés, fue impreso en Londres.
Después de la partida de ellas a Holanda, Caton se quedó y viajó a través de Essex,
Warwickshire, Staffordshire, Derbyshire, Nottinghamshire y Yorkshire; y luego,
cuando llegó a Lancashire, regresó a Swarthmore,
y encontró allí no sólo a su antigua ama, Margaret Fell,
quien lo recibió muy amablemente, sino también a G. Fox,
poco antes de que fuera tomado prisionero.

Desde allí Caton fue a Sunderland, y luego a Scarborough, donde,
al encontrarse con un barco con destino a Holanda, se embarcó y partió con buen viento.
Pero no pasó mucho tiempo antes de que el viento cambiara,
y estando a unas diez leguas de la tierra, el cielo empezó a parecer tempestuoso.
Esto hizo que Caton le aconsejara al capitán que regresara, pero él,
pensando que el clima cambiaría pronto, no quiso hacerlo.
Sin embargo, pronto se levantó una violenta tormenta,
por la que el barco estaba siendo tan fuertemente agitado, que empezó a hacer agua,
y se llenó tanto que las bombas tuvieron que mantenerse funcionando continuamente.
Esto cansó tanto a los marineros, que Caton también empezó a bombear,
porque aunque se encontraba preparado para afrontar la muerte,
si esa hubiera sido la voluntad del Señor,
sabía que el deber de un hombre era preservar su vida por los medios legales,
tanto como fuera posible.
Además, se compadecía de los pobres marineros,
y por eso estaba dispuesto a ayudarlos en la medida de sus posibilidades.
Pero al final perdieron el uso del timón,
y se acercaron a las arenas y a las aguas poco profundas,
por lo que aumentó grandemente el peligro y parecía que la muerte se aproximaba.

Ahora bien, Caton,
aunque rendido a la voluntad de Dios y preparado para encontrar su tumba en las profundidades,
no omitió invocar al Señor y orar al Altísimo pidiéndole liberación,
si era consistente con Su santa voluntad.
Y cuando la tormenta llegó a su punto máximo,
su súplica fue escuchada y la tempestad repentinamente
empezó a cesar y el viento a amainar.
Esto, en efecto,
le dio la oportunidad de alabar al Todopoderoso por la gran
misericordia mostrada hacia él y hacia los marineros.
Sin embargo, al ser el viento contrario, el capitán resolvió entonces entrar en Yarmouth,
donde Caton se encontró con otro tipo de tormenta.
Porque el Primer-día, estando en una reunión de sus amigos,
él y siete más fueron apresados y llevados a la guardia principal.
Al día siguiente fueron llevados ante los alguaciles del pueblo,
quienes les presentaron el juramento de lealtad; el cual, como se negaron a prestarlo,
fueron enviados a prisión, donde los mantuvieron más de seis meses.
Así, pues, no regresó a Holanda sino hasta el año siguiente.

Mientras él estaba en la cárcel en Yarmouth,
Stephen Crisp llegó por primera vez a Holanda para
visitar a sus amigos ahí y edificarlos con su don.
No estaría de más mencionar aquí un poco de las cualidades de Stephen Crisp.
Él era un hombre de notables habilidades naturales,
y había sido celoso de la religión antes de entrar en comunión con los llamados Cuáqueros.
Porque cuando llegó la noticia de este pueblo al lugar donde vivía,
investigó acerca de ellos y de su doctrina, y aunque sólo oía hablar mal de ellos,
le causó cierta impresión el considerar cómo eran escarnecidos, odiados,
calumniados y perseguidos, sabiendo que esta, en general,
había sido la porción de los que verdaderamente temían a Dios.
Pero habiendo oído que uno de sus principios era
que el pecado podía ser vencido en esta vida,
le pareció un gran error.
Y por lo tanto, cuando el joven James Parnell llegó a Colchester,
Stephen se armó con argumentos para oponerse a él seriamente;
y considerando que Parnell no era más que un joven,
pensó que sería capaz de prevalecer sobre él. Stephen
Crisp tenía entonces unos veintisiete años,
y no sólo estaba bien versado en las Sagradas Escrituras,
sino también en los escritos de muchos de los antiguos filósofos.

Después de escuchar a Parnell predicar muy poderosamente,
y encontrar que sus palabras eran más penetrantes de lo que había imaginado,
se aventuró a oponerse a él con algunas preguntas,
pero pronto descubrió que el joven estaba dotado con buen juicio, y Crisp,
a pesar de toda su sabiduría y conocimiento, no pudo resistirlo,
sino que se vio obligado a someterse a la verdad que Parnell sostenía. Entonces,
se sintió tan enriquecido por este nuevo entendimiento,
que por un mes o dos se dedicó a defender, por medio de la fuerza de su propia razón,
la Verdad que había abrazado.
Pero pronto encontró que eso no era suficiente,
porque el yo no había sido sometido aún a la cruz,
y no había llegado a conocer por experiencia lo que afirmaba y defendía con palabras.
En esta condición vio que debía llegar a ser verdaderamente pobre en espíritu,
si quería que Dios lo enriqueciera alguna vez con sabiduría celestial.
Esto lo llevó a la aflicción y a la tristeza,
por medio de lo cual fue destetándose cada vez más de su conocimiento natural,
en el que solía deleitarse.
Y al continuar fielmente en este camino de negación al yo,
al fin empezó a disfrutar de paz en su mente,
y avanzó tanto en virtud y conocimiento real,
que con el tiempo se convirtió en un eminente ministro del evangelio;
y viajando de un lugar a otro, muchos se convirtieron por su ministerio.

Por este tiempo apareció en Inglaterra un tal Lodowick Muggleton,
quien pretendía que él y un tal John Reeves eran los dos testigos de los que se hablaban
en Apocalipsis 11:3. Y aunque no pasó mucho tiempo antes de que Reeves muriera,
Muggleton continuó con sus descabelladas imaginaciones, y llegaron a crecer a tal grado,
que publicó un documento en el que decía que él era "`el juez principal
en el mundo,`" comisionado para dictar sentencia de muerte y condenación
eterna sobre las almas y cuerpos de los hombres.
Afirmaba además, que en obediencia a su comisión,
ya había maldecido y condenado lejos de la presencia de Dios,
a muchos cientos de personas en cuerpo y alma, tanto a hombres como a ángeles,
por toda la eternidad; y que ni el Espíritu de Cristo, ni ningún otro dios,
podrían o serían capaces de liberar de su sentencia y maldición.
Estas abominables blasfemias las pronunció en público.

Richard Farnsworth, un ministro celoso e inteligente entre los llamados Cuáqueros,
le contestó por escrito a este blasfemo,
y puso al descubierto lo horrible de sus doctrinas y opiniones profanas y malditas.
En un libro que publicó impreso, decía, entre otra cosas:
"`Considera la naturaleza de tu ofensa y hasta dónde se extiende; es decir,
hasta dictar sentencia de muerte y condenación,
tanto sobre los cuerpos como sobre las almas de hombres y mujeres, por toda la eternidad.
Considera que tu injusticia, cometida bajo el pretexto de un oficio celestial,
merece un castigo proporcional a la ofensa;
¿y puede esta ofensa ante los ojos del Señor ser
menos que un pecado contra el Espíritu Santo,
puesto que tú has pretendido hacerla en nombre del Espíritu Santo,
y de esa manera has hecho al Espíritu Santo autor de tu ofensa, cuando no lo es?
Y dado que eres culpable de un pecado contra el Espíritu Santo,
ya hay un castigo proporcionado para tal ofensa.
Y eres castigable también por la ley de la tierra, por presumir,
bajo la pretensión de una comisión, y como juez,
de dictar sentencia de muerte sobre los cuerpos de hombres y mujeres,
reclamando cierta autoridad al hacerlo, como lo hacen los jueces de la tierra.`"
Así continuó Farnsworth contestándole ampliamente a Muggleton,
mostrándole cómo su juicio no sólo era contrario a la verdad,
sino también contrario a la ley de la tierra.

Pero Muggleton se atrevió a dar una respuesta a esta seria contestación, y dijo en ella,
que elogiaba a Farnsworth, primero, por poner su nombre en ella; y segundo,
por expresar sus palabras tan verdadera y puntualmente,
que había hecho que su comisión y autoridad resplandecieran con más brillo y claridad.
Luego insistió en que él era, en efecto, "`un embajador de Dios tan verdadero,
y juez del estado espiritual de todos los hombres,
como lo ha sido cualquiera desde la creación del mundo.
Y si ustedes los Cuáqueros y otros,`" continuó,
"`pueden probar que nunca ha habido un hombre comisionado por Dios para bendecir y maldecir,
entonces todos escaparán de la maldición que he pronunciado sobre tantos cientos,
y sólo yo sufriré por maldecir a otros sin haber sido comisionado por Dios.
No obstante, mi comisión no es algo fingido, sino tan verdadera como lo fue la de Moisés,
los profetas y los apóstoles.`"

Este blasfemo profirió muchas más abominaciones, y entre esas,
la afirmación de que ningún hombre podía llegar a la seguridad del favor de Dios,
sino al creer que Dios le había dado ese poder a John Reeves y a él;
que a él se le había dado poder sobre todos los otros
dioses y espíritus infinitos de cualquier tipo;
que él tenía las llaves del cielo y del infierno,
y que nadie podía entrar al cielo a menos que él le abriera las puertas.
También alegó tener poder para remitir los pecados de aquellos que recibían su doctrina,
y para retener y atar los pecados de aquellos que menospreciaban o no recibían su doctrina.
Dijo que él era único en doctrina, conocimiento,
juicio y poder por encima de todos los hombres (ya fueran profetas o apóstoles),
desde el principio del mundo, o que lo sería en adelante mientras el mundo durara;
y que no había un verdadero ministro,
mensajero o embajador de Dios en el mundo además de él,
ni habría más enviados de Dios después de él hasta el fin del mundo.
Además, afirmó que un dios fuera de él,
le había hablado por medio de palabras audibles al oído,
y que ninguna persona que hubiera sido condenada por él, podría apelar a Dios,
ni por medio de él, ni por medio de ningún otro,
porque Dios no estaba en el mundo en absoluto.
"`Este poder de condenar,`" dice él, "`me lo ha dado Dios, y en este sentido,
soy el único y solo juez en lo que se refiere a lo que les
sucederá a los hombres y a las mujeres después de la muerte;
ni los que son condenados por mí, verán a ningún otros dios o juez que no sea yo.`"
Me resisto a transcribir más de estas horribles blasfemias,
y tenemos motivos para asombrarnos de la larga paciencia de Dios,
que soportó así la desdeñosa afrenta presentada por
este inhumano monstruo en desafío a Su Omnipotencia.

Este Muggleton también le dijo a Richard Farnsworth,
que debido a que él no estaba aún bajo la sentencia de su maldición, ni verbalmente,
ni por escrito, le respondería su carta.
"`Porque,`" dijo él,
"`yo nunca le respondo por escrito a nadie que esté bajo
la sentencia de mi condenación.`" Esta estratagema,
afirmando que no estaba obligado a responder cuando había
encerrado a alguien bajo su pretendida condenación,
parecía cómica y ridícula.
Sin embargo, Farnsworth no dejó de responder públicamente a sus opiniones blasfemas,
y de mostrar lo absurdo de que Muggleton y John Reeves fueran los dos testigos.

Más adelante tendré ocasión de mencionar de nuevo a este Muggleton,
porque vivió aún varios años,
y no encuentro que los magistrados le hayan infligido
otro castigo más que el cepo y medio año de prisión;
aunque muchos piensan (no sin razón) que tales blasfemos
deben ser apartados de la interacción con otros hombres.

Francis Howgill, en la última parte de este año,
mientras se ocupaba de su negocio en el mercado de Kendal, en Westmoreland,
fue citado por el alguacil principal para que compareciera
ante los jueces de paz en una taberna;
porque, al ser un celoso predicador entre los llamados Cuáqueros,
se buscaba la ocasión de encarcelarlo bajo algún pretexto de justicia,
aunque fuera injusto.
Cuando llegó al lugar citado, le fue presentado el juramento de lealtad,
y como por razones de consciencia se negó a jurar,
lo enviaron a prisión hasta la sesión del tribunal en Appleby.
Luego, cuando compareció en Appleby,
los jueces le presentaron el mismo juramento en el tribunal,
y como no estuvo dispuesto a prestarlo,
fue acusado y se le dio libertad de responder a la
acusación en la siguiente sesión de la corte.
Mientras tanto, había una liberación de cárcel^
footnote:[Una absolución colectiva de un gran número de presos,
como resultado de una administración laxa o imprudente de la ley,
o de defectos en la misma.]
en Appleby, y se le exigió una fianza por su buena conducta.
Pero sabiendo bien que eso era sólo una trampa para ponerle más trabas,
lo rechazó y por eso fue enviado de nuevo a prisión.
Y al no ser juzgado hasta el siguiente año,
lo dejaremos ahí.

Por esta época ocurrió un caso notable, que no puedo dejar de mencionar.
Un tal Oliver Atherton, un hombre de constitución débil,
después de negarse a pagarle los diezmos a la condesa de Derby (quien reclamaba
los ingresos eclesiásticos de la parroquia de Ormskirk donde él vivía),
fue encarcelado por acusación de ella, en un hueco húmedo e insalubre en Derby.
Este encarcelamiento lo debilitó tanto, que después de estar ahí por dos años y medio,
se enfermó; y se le escribió una carta a la condesa en nombre de él,
en la que se le exponía no sólo la razón por la que
él se había negado a pagar los diezmos (a saber,
por un asunto de consciencia),
sino también que la vida de él estaba en peligro si permanecía
por más tiempo en esa insalubre prisión. Por lo tanto,
se le pedía que mostrara compasión,
no fuera a ser que atrajera sobre ella la culpa de sangre inocente.

Ahora bien, aunque el hijo de Oliver, que llevó la carta,
se topó con un trato brusco por no descubrirse la cabeza,
la carta fue entregada en manos de ella.
Sin embargo, la condesa continuó con el corazón endurecido.
Godfrey Atherton, el hijo,
regresó a la prisión donde estaba su padre (quien
en ese momento yacía en su lecho de muerte),
y le contó que la condesa no le daría ninguna libertad.
A lo que él dijo: "`Ella ha sido la causa de mucho derramamiento de sangre;
pero esta será la sangre más pesada que haya derramado
alguna vez;`" y no mucho después murió. Sus amigos,
después de recoger su cadáver, lo llevaron a Ormskirk, pero en Garstang,
Preston y otros pueblos que cruzaron durante el camino,
fijaron en la cruz del mercado la siguiente inscripción,
que también había sido puesta en su ataúd.

[.embedded-content-document.paper]
--

Este es Oliver Atherton de la parroquia de Ormskirk,
a quien la condesa de Derby persiguió hasta la muerte
por tener una buena consciencia para con Dios y Cristo,
al no pagarle los diezmos.

--

Ahora, aunque había otros tres encarcelados con Oliver por la misma causa,
le avisaron a la condesa de esto,
esperando no morir como había muerto su compañero de prisión; sin embargo,
ella no mostró compasión;
y también amenazó con acusar a los de Garstang delante del rey y su consejo,
por permitir que dicha inscripción fuera puesta.
Pero con esto abrió aún más la boca del pueblo,
y una mano omnipotente evitó que ejecutara su amenaza,
pues exactamente tres semanas después del día en que Atherton fue sepultado, ella murió.

También en octubre de este año, Humphrey Smith,
un predicador entre los llamados Cuáqueros,
tras estar prisionero un año en la prisión de Winchester por su religión,
fue liberado de sus ataduras por la muerte.
Él tuvo una visión en el año 1660, en el mes llamado julio,
con respecto al incendio de Londres ocurrido seis años después;
un relato de lo cual él dio a conocer en forma impresa.

En el año 1662, estando en Londres,
les dijo a algunos de sus amigos que tenía que pasar por un camino estrecho;
y más de una vez dio a entender que veía que sería
encarcelado y que podría costarle su vida.
Y llegando no mucho después a Alton en Hampshire,
fue sacado de una reunión de sus amigos y confinado
en una apestosa y pequeña prisión en Winchester,
donde después de un año entero de encarcelamiento, se enfermó;
y durante su enfermedad les habló muchas y excelentes
palabras a los que estaban a su alrededor,
diciendo que estaba rendido a la voluntad del Señor, ya fuera en la vida o en la muerte.
Y estando en gran debilidad, dijo: "`Mi corazón está lleno del poder de Dios.
Es bueno para un hombre en un tiempo como este, tener al Señor como su amigo.`"

En otra ocasión se le oyó decir: "`Señor, tú me has enviado a hacer Tu voluntad,
y Te he sido fiel en la pequeña medida que me has encomendado;
pero si aún quieres probarme más, sea hecha Tu voluntad.`"
También dijo: "`Soy del Señor, que haga lo que quiera.`"
No mucho antes de su partida oró muy fervientemente diciendo: "`¡Oh, Señor,
oye los suspiros y gemidos internos de tus oprimidos.
Escúchame, Señor, sostenme y presérvame.
Yo sé que mi Redentor vive.
Tú eres fuerte y poderoso, oh, Señor!`"
También le pidió a Dios que liberara a Su pueblo de sus crueles opresores.
Y por aquellos que habían sido convencidos por su ministerio,
oró que el Señor fuera su maestro.
Continuó quieto y en su sano juicio hasta los últimos momentos de su vida,
muriendo como prisionero por dar testimonio de la verdad;
y así pasó de esta vida difícil y transitoria a una que es eterna.
