== Capítulo XV

[.section-date]
1664

[.chapter-synopsis]
* Juicio de G. Fox en la sesión del tribunal en Lancaster
* Actuación arbitraria de los jueces
* Encarcelamiento--Crueldades contra G. Fox en la prisión
* G. Fox escribe al emperador, a los reyes de Francia y España, y al papa
* Juicio de F. Howgill en Appleby
* Relato sobre J. Camm
* Relato sobre J. Audland
* Segundo juicio de F. Howgill y su sentencia
* "`Ley para Prevenir y Suprimir los Conventículos Sediciosos`"
* Juicio a los Cuáqueros en Hartford por asistir a una reunión
* Sentencia de destierro
* Juicio a los Cuáqueros en Heck`'s Hall bajo la Ley de Conventículos
* Determinación de destruir a los Cuáqueros mediante la severidad del castigo
* Fidelidad bajo el sufrimiento
* Gran número de personas sacadas de las reuniones, juzgadas y sentenciadas
* Exhortaciones a la constancia
* Advertencia al rey y al Parlamento.

El año anterior dejamos a G. Fox en la prisión de Lancaster,
donde en las sesiones del tribunal le presentaron el juramento de lealtad y él lo rechazó,
y fue llevado a su juicio a inició del año 1664, en el mes llamado marzo.^
footnote:[Hasta 1752,
marzo fue considerado el primer mes del año en toda Inglaterra y sus colonias.]
Cuando fue llevado al estrado delante del juez Twisden dijo:
"`La paz sea con todos ustedes.`"
A lo que el juez dijo mirándolo: "`¡Qué! ¿Entras al tribunal con tu sombrero puesto?`"
Con lo cual, el carcelero se lo quitó y G. Fox dijo:
"`El sombrero no es el honor que viene de Dios.`"
Entonces el juez dijo: "`¿Prestarás el juramento de lealtad?`"
G+++.+++ Fox respondió: "`Nunca he prestado un juramento en mi vida.`"
"`Bien,`" dijo el juez, "`¿jurarás o no?`"
G+++.+++ Fox replicó: "`Soy un Cristiano y Cristo me ordena a no jurar,
y lo mismo hace el apóstol Santiago; y juzga tú si debo obedecer a Dios o al hombre.`"
"`Te pregunto de nuevo,`" dijo el juez, "`¿jurarás o no?`"
A lo cual Fox respondió lo siguiente: "`No soy turco, ni judío, ni pagano,
sino Cristiano, y debo mostrar el Cristianismo en todo lo que haga.
¿Acaso no sabes que los Cristianos en los tiempos primitivos,
bajo las diez persecuciones,^
footnote:["`Se suele afirmar que hubo diez persecuciones
romanas contra el Cristianismo decretadas por diez emperadores:
Son las persecuciones de Nerón, Domiciano, Trajano, Marco Aurelio, Septimio Severo,
Maximiano, Decio, Valeriano, Aureliano y Diocleciano.
En realidad,
durante todo este período el cristianismo fue religión prohibida __(religio illicita)__
y estuvo permanentemente bajo el riesgo de persecución dependiendo
de la sensibilidad de los gobernadores provinciales del momento.`"
Tomado de la revista, __La Razón Histórica.__]
al igual que algunos de los mártires en los días de la reina Mary,
se negaron a jurar porque Cristo y el apóstol lo habían prohibido?
Tú tienes suficiente experiencia de cuántos hombres han jurado primero a favor del rey,
y luego contra él. Pero en cuanto a mí, nunca he prestado un juramento en mi vida,
y mi lealtad no radica en jurar, sino en la verdad y fidelidad;
pues honro a todos los hombres, y mucho más al rey.
Pero Cristo, que es el gran Profeta, que es el Rey de reyes,
el Salvador del mundo y el gran Juez del mundo entero, dice que no debo jurar.
Por tanto, el punto es este, si debo obedecer a Cristo o a ti.
Porque es en la ternura de consciencia y en obediencia al mandato de Cristo, que no juro.
Y tenemos la palabra de un rey en defensa de nuestra tierna consciencia.`"

Después de hablar tanto, G. Fox le preguntó al juez: "`¿Reconoces al rey?`"
El juez dijo: "`Sí, reconozco al rey.`"
"`Entonces, ¿por qué,`" dijo Fox, "`no respetas su declaración de Breda^
footnote:[Ver la declaración de Breda en el capítulo 10, párrafo 3 de la declaración.]
y sus promesas desde que llegó a Inglaterra,
de que ningún hombre debería ser cuestionado por asuntos de religión,
mientras viviera pacíficamente?
Ahora, si tú reconoces al rey, ¿por qué me cuestionas y me pones a jurar,
viendo que ni tú, ni nadie más, me puede acusar de no vivir pacíficamente?`"
El juez con cara de enojo, dijo: "`Sirrah,^
footnote:[Palabra de reproche y desprecio que se
utilizaba para dirigirse a personajes viles.]
¿vas a jurar?`"
A lo que G. Fox le dijo: "`No soy ninguno de tus '`sirrahs.`' Soy un Cristiano,
y para ti, que eres un anciano y juez, sentarte ahí y ponerles apodos a los prisioneros,
no es apropiado ni por tus canas, ni por tu cargo.`"
El juez un poco más tranquilo, después de un intercambio de palabras, dijo: "`George Fox,
di si prestarás el juramento o no.`"
A lo que él replicó: "`Si yo pudiera prestar algún juramento, haría este;
pero no niego algunos juramentos solamente, o en algunas ocasiones,
sino todos los juramentos, en concordancia con la doctrina de Cristo que dijo:
'`No juréis en ninguna manera.`' Ahora, si tú, o cualquiera de los presentes,
o alguno de tus ministros o sacerdotes aquí, prueba que Cristo o Su apóstol,
después de haber prohibido jurar, ordenó alguna vez a los Cristianos jurar,
entonces juraré.`"

Como ninguno de los sacerdotes se ofreció a hablar, el juez dijo:
"`Soy siervo del rey y el rey no me mandó a discutir contigo,
sino a poner en ejecución las leyes; por lo tanto, te presento el juramento de lealtad.`"
G+++.+++ Fox siguió negándose a jurar,
y fue enviado de nuevo a prisión. Dos días después de esto,
al ser llevado de nuevo delante del juez,
se le preguntó si negaba la acusación o se sometía. A esto G. Fox dijo:
"`Deseo tener la libertad para examinar la acusación y juzgarla.`"
Entonces se dieron órdenes de que se lo llevaran,
y se le mantuvo en prisión hasta la siguiente sesión del tribunal.

Mientras estaba prisionero en el castillo de Lancaster,
se oía hablar mucho de los progresos del gran turco en Hungría,
dado que en ese tiempo había guerra entre el emperador y los turcos.
Muchos estaban asustados, y George les dijo a algunos,
que una vez mientras caminaba en su recámara,
había visto el poder del Señor volverse contra el gran turco,
haciendo que retrocediera de nuevo.
Y un mes después de esto, llegaron noticias de que había sido derrotado.
En otro momento, mientras caminaba en su habitación con su mente puesta en el Señor,
vio una luz extraordinariamente grande, y mirando hacia arriba,
vio a un ángel del Señor con una espada reluciente extendida hacia el sur,
que brillaba tan intensamente, que parecía que el tribunal estaba en llamas.
Como prueba de esto tengo lo que G. Fox dice de ello en su diario,
y también otro pequeño libro que publicó bajo el título __A Warning to England.__^
footnote:[__Una Advertencia a Inglaterra.__]
No mucho después de esto, estalló una guerra entre Inglaterra y Holanda,
después apareció la peste en Londres^
footnote:[La Gran Peste de Londres, que duró de 1665 a 1666,
fue la última gran epidemia de peste bubónica que se produjo en Inglaterra.]
(que se encuentra al sur de Lancaster),
y poco después la ciudad quedó reducida a escombros por el fuego.^
footnote:[El Gran Incendio de Londres, fue un incendio que arrasó el centro de la ciudad,
desde el Domingo 2 de septiembre hasta el Jueves 6 de septiembre de 1666.
Destruyó 13.200 casas, 87 iglesias parroquiales,
la catedral de San Pablo y la mayoría de los edificios de las autoridades de la ciudad.
Se calcula que destruyó los hogares de 70.000 de los 80.000 habitantes de la ciudad.]

Pero vuelvo a la sesión del tribunal en Lancaster.
Margaret Fell, que en ese momento era viuda,
también estaba bajo confinamiento por negarse a prestar el juramento de lealtad.
Y estando G. Fox en prisión, les escribió varios documentos a los magistrados,
en los que manifestaba el mal de la persecución y los exhortaba a la virtud y a la piedad.

En el mes llamado agosto, la sesión de la corte fue celebrada de nuevo en Lancaster,
donde el juez Turner se sentó en la silla de la corona.
Cuando G. Fox fue llevado allí y llamado al estrado,
el juez le preguntó a los magistrados si le habían presentado
el juramento de lealtad en las sesiones anteriores.
Ellos respondieron que lo habían hecho, y después de jurarlo,
el jurado también tomó juramento.
Entonces el juez le preguntó a George si se había negado
a prestar el juramento en la última sesión del tribunal.
A lo que él respondió: "`Nunca he prestado juramento en mi vida;
y Cristo el Salvador y Juez del mundo dijo: '`No juréis en ninguna manera.`'`" El juez,
que al parecer no tomó nota de esta respuesta le preguntó,
si se había negado o no a prestar juramento en la última sesión del tribunal.

G+++.+++ Fox continuó manteniendo la ilicitud de jurar,
y el juez dijo que en ese momento no iba a discutir si era lícito o no jurar,
sino preguntar si se había negado a prestar juramento, sí o no.
Entonces G. Fox,
dando a entender que no desaprobaba las cosas mencionadas en el juramento, dijo:
"`Conspirar contra el rey, aprobar el poder del papa, o cualquier otro poder extranjero,
lo niego por completo.`"
"`Bien,`" dijo el juez, "`dices bien en eso, pero ¿te negaste a prestar juramento?`"
"`¿Qué quieres que te diga,`" respondió, "`ya te he dicho antes lo que dije.`"
Después de algunas palabras más de ambas partes,
se leyó la acusación. Estando informado de los errores que había en ella,
G+++.+++ Fox dijo que tenía algo que decir al respecto,
porque la acusación tenía muchos y graves errores.
El juez le indicó que no lo escucharía, pero cuando estaba a punto de dictar sentencia,
el jurado salió, y cuando regresó emitió un veredicto de culpabilidad.
Con lo cual,
G+++.+++ Fox les dijo que tanto los magistrados como ellos mismos habían jurado en falso,
lo que causó tal confusión en el tribunal,
que la pronunciación de la sentencia fue retrasada.
Margaret Fell fue la siguiente en comparecer ante
el tribunal y fue declarada culpable también.

Al día siguiente ella y G. Fox fueron llevados de
nuevo al tribunal para recibir su sentencia.
Como el abogado de ella alegó muchos errores en su acusación,
Margaret fue dejada de lado; y entonces fue llamado G. Fox,
que se mostró poco dispuesto a dejar que alguien defendiera su caso,
lo que pareció detener sus procedimientos.
Sin embargo,
al fin el juez le preguntó por qué no debería dictar
sentencia contra él. Ante esto G. Fox le dijo:
"`No soy abogado, sin embargo, tengo mucho que decir,
si tienes paciencia para escucharme.`"
Entonces los que estaban en el tribunal se rieron y dijeron: "`Vamos,
¿qué tienes que decir?`"
Entonces le preguntó al juez si el juramento tenía
que ser presentado a los súbditos del rey,
o a los súbditos de príncipes extranjeros.
El juez dijo: "`A los súbditos de este reino.`"
"`Entonces,`" dijo George,
"`mira la acusación y verás que han omitido la palabra "`súbdito;`"
y al no referirse a mí en la acusación como un súbdito,
no pueden aplicarme la sentencia de premunire por no prestar el juramento.`"
Entonces miraron el estatuto y la acusación, y vieron que era cierto,
y el juez reconoció que era un error.
A continuación, G. Fox les dijo que tenía algo más que decir,
y les pidió que miraran qué día decía la acusación le habían presentado el juramento
en las sesiones allí. Ellos miraron y dijeron que había sido el 11 de enero.
Entonces él les preguntó:
"`¿Qué día de la semana fue celebrada esa sesión?`" "`Martes,`" dijeron.
Ante lo cual G. Fox dijo:
"`Ahora miren sus almanaques y vean si se celebró
alguna sesión en Lancaster el 11 de enero.`"
Ellos miraron y descubrieron, que el 11 de enero había sido el día llamado Lunes,
y que esas sesiones se habían llevado a cabo en el día llamado Martes,
que era 12 del mencionado mes.
"`Miren ahora,`" dijo George,
"`ustedes me han acusado de negarme a prestar el juramento en las sesiones
trimestrales celebradas en Lancaster el día 11 del pasado enero,
y los magistrados han jurado que ellos me presentaron
el juramento en las sesiones públicas aquí ese día,
y el jurado bajo juramento me ha hallado culpable de lo mismo; y sin embargo,
ustedes ven que no se celebraron sesiones en Lancaster ese día.`"

El juez, para cubrir el asunto,
preguntó si las sesiones no habían comenzado el día
11+++.+++ A lo que algunos en el tribunal respondieron:
"`No; las sesiones se celebraron sólo un día,
y fue el día 12.`" Entonces el juez admitió que se trataba de un gran error.
Algunos de los magistrados se enojaron tanto ante esto,
que parecían dispuestos a abandonar el estrado, y zapateando dijeron: "`¿Quién hizo esto?
Alguien ha hecho esto a propósito.`"
Entonces G. Fox dijo:
"`¿Acaso no han jurado en falso los jueces que juraron
aquí esta acusación? Pero eso no es todo,
todavía tengo más que presentar para que no se dicte sentencia contra
mí. ¿En qué año del rey se efectuó aquí la última sesión del tribunal,
la que fue celebrada en el mes llamado marzo?`"
El juez dijo que había sido en el año decimosexto del rey.
"`Pero,`" dijo G. Fox, "`la acusación dice que fue en el año decimoquinto.`"
Esto también se reconoció como un error,
pero tanto el juez como los magistrados estaban tan alterados, que no sabían qué decir;
porque también habían jurado que le había presentado a G.
Fox el juramento en el decimoquinto año del rey,
cuando había sido en el decimosexto.
Esto hizo a G. Fox decir: "`¿Acaso no ha jurado en falso el tribunal también,
habiendo jurado con un año entero de diferencia?`"
También mostró algunos otros errores notables, pero como no quiero ser tedioso,
los paso por alto.

G+++.+++ Fox dijo entonces, que él no buscaba misericordia, sino justicia, y el juez dijo:
"`Tú tendrás justicia y tendrás la ley.`"
Esto hizo que G. Fox preguntara:
"`¿Estoy libre ya de todo lo que se ha hecho contra mí en este asunto?`"
"`Sí,`" dijo el juez; pero luego empezando a endurecerse dijo:
"`Pero yo puedo presentar el juramento a cualquier hombre aquí;
y te lo presentaré de nuevo.`"
Entonces G. Fox le dijo que él tenía suficientes ejemplos
de los juramentos y falsos juramentos del día anterior;
"`porque he visto ante mis ojos,`" dijo,
"`que tanto los magistrados como el jurado juraron en falso.`"
Sin embargo, el juez le preguntó si prestaría juramento.
Pero él respondió:
"`Hazme justicia por mi falso encarcelamiento durante todo este tiempo;`" porque
había estado encerrado (como era bien sabido) en una habitación húmeda y fría,
y por eso dijo: "`Yo debería ser puesto en libertad.`"
Ante esto el juez dijo: "`Estás en libertad,
pero ahora te volveré a presentar el juramento.`"
Entonces, G. Fox, dándose vuelta le dijo a la gente: "`Tomen nota, esta es una trampa.
Yo debería ser liberado por el carcelero y por esta corte.`"
Pero el juez, en lugar de escuchar esto gritó: "`¡Denle el libro!`"
G+++.+++ Fox tomó el libro y mirando en él dijo: "`Veo que es una Biblia y me alegro de ello.`"
Mientras tanto, el jurado estaba en espera, tras haber sido llamado por el juez;
porque aunque habían querido que los despidieran después de haber dado su anterior veredicto,
el juez les dijo que no podía despedirlos todavía, porque tenían asuntos que hacer,
y por lo tanto, debían estar presentes y estar listos.
G+++.+++ Fox, percibiendo su intención, miró al juez a la cara, lo que hizo que se ruborizara.
Sin embargo, hizo que se leyera el juramento,
y luego le preguntó a G. Fox si prestaría juramento o no.
A esto George dijo: "`Tú me has dado un libro para que lo bese y para que jure sobre él;
pero este libro dice: '`Besad al hijo;`'^
footnote:[Salmo 2:12 Reina Valera Gomez, Reina Valera 1602 Purificada]
y el Hijo dice en este libro: '`No juréis en ninguna manera,`'^
footnote:[Mateo 5:34]
y también lo dice el apóstol Santiago.
Estoy diciendo lo que dice el libro, y sin embargo,
me encarcelas por hacer lo que el libro me manda.
¿Por qué no encarcelas el libro por decir eso?
¿Cuál es la razón por la que el libro que me manda a no jurar esté libre entre ustedes?
¿Por qué no encarcelas el libro también?`" Mientras hablaba así,
sostenía la Biblia abierta para mostrar el lugar donde Cristo prohibía jurar.
Pero le quitaron el libro y el juez dijo: "`No, pero encarcelaremos a George Fox.`"

Este caso fue tan singular,
que se esparció por todo el condado que le habían
dado a G. Fox un libro sobre el cual jurar,
que le mandaba a no jurar en ninguna manera,
y que dicho libro (la Biblia) estaba en libertad,
y él en prisión por hacer lo que la Biblia decía.
Pero aun así el juez lo presionó a jurar,
ante lo cual G. Fox dijo: "`Soy un hombre de consciencia tierna, considera por lo tanto,
que es en obediencia al mandamiento de Cristo que no puedo jurar.
Pero si cualquiera de ustedes puede convencerme de que después
de que Cristo y el apóstol ordenaron no jurar,
alteraron el mandamiento y ordenaron a los Cristianos jurar,
entonces verán que juraré.`" Y viendo allí a varios sacerdotes, dijo:
"`Si tú no puedes hacerlo, entonces deja que tus sacerdotes lo hagan.`"
Pero ninguno de los sacerdotes dijo nada, y el juez dijo:
"`El mundo entero no puede convencerte.`"
A esto replicó: "`¿Cómo podría convencerme el mundo?
El mundo entero yace en maldad.
Pero trae a tus hombres espirituales, como los llaman, para que me convenzan.`"
Entonces el alguacil y el juez dijeron que el ángel había jurado en Apocalipsis.
Y G. Fox respondió: "`Cuando Dios introdujo a Su Hijo primogénito en el mundo, dijo:
'`Adórenle todos los ángeles de Dios;`' y Él es el que dijo:
'`No juréis en ninguna manera.`'`" "`No,`" dijo el juez,
"`no discutiré.`" Entonces G. Fox le dijo al jurado,
que él no podía jurar por causa de Cristo,
y por eso les advirtió no actuar en contra del don de Dios en las consciencias de ellos,
porque todos debían comparecer ante Su tribunal.
Después de decir algunas palabras más, el carcelero se lo llevó.

Por la tarde lo llevaron de nuevo,
y después de que el jurado lo declaró culpable por
el cargo que se le imputaba en la acusación,
es decir, su negativa a prestar juramento,
el juez le preguntó si tenía que decir algo a su favor.
Él pidió que se leyera la acusación,
ya que no podía responder a lo que no había oído. Al leerla el secretario, el juez dijo:
"`¡Más vale que esta vez no tenga ningún error!`"
Pero el secretario la leyó de manera tal,
que G. Fox apenas pudo entender lo que leía. Y cuando terminó,
el juez le preguntó a G. Fox qué tenía que decir sobre la acusación. A esto respondió:
"`Escuchar un escrito tan largo leído de una sola vez,
y a una distancia tal que apenas pude oír con claridad todas las partes,
no sé muy bien qué decir al respecto.
Pero si me permites tener una copia de la acusación y darme tiempo para considerarla,
responderé.`"

Esto hizo que el tribunal se detuviera un poco;
pero finalmente el juez le preguntó cuánto tiempo quería. Y él respondió:
"`Hasta la siguiente sesión del tribunal.`"
"`Pero,`" dijo el juez, "`¿qué declaración harás ahora?
¿Eres culpable o no culpable?`"
A lo que G. Fox replicó:
"`No soy culpable en absoluto de negarme a jurar '`obstinada y
testarudamente;`' y en cuanto a las cosas mencionadas en el juramento,
como conspiraciones Jesuitas y poderes extranjeros,
las niego completamente en mi corazón. Y si pudiera prestar juramento, prestaría este;
pero nunca he prestado juramento en toda mi vida.`"
A esto el juez respondió: "`Dices bien.
Pero el rey jura, el parlamento jura, yo juro, los magistrados juran,
y la ley es preservada por los juramentos.`"
Ante lo cual G. Fox le dijo que ellos habían tenido suficiente
experiencia con los juramentos de los hombres,
y que habían visto cómo los magistrados y el jurado
habían jurado en falso el otro día. Y continuó:
"`Si has leído el libro de los mártires,
has visto cómo muchos de ellos se negaron a jurar,
tanto durante el tiempo de las diez persecuciones, como en la época del obispo Bonner,
y has visto que negarse a jurar en obediencia al mandamiento de Cristo no es algo nuevo.`"
Entonces el juez respondió que deseaba que las leyes fueran de otro modo.
G+++.+++ Fox dijo entonces: "`Nuestro sí es sí, y nuestro no es no.
Y si transgredimos nuestro sí y nuestro no, que suframos como lo hacen,
o deberían hacerlo, los que juran en falso.
Esto se lo he ofrecido al rey y el rey dijo que era razonable.`"

Después de más conversación, G. Fox fue enviado a prisión de nuevo,
y el coronel Kirby le ordenó al carcelero que lo mantuviera
aislado y que no le permitiera a nadie visitarlo,
como si fuera alguien con quien no era adecuado conversar.
El carcelero no dudó en cumplir esa orden, porque lo encerró en una torre llena de humo,
donde el humo de los otros prisioneros subía tan denso a su habitación,
que a veces difícilmente se podía ver una candela encendida.
En realidad, parecía que intentaban sofocarlo;
pues apenas se pudo persuadir al que tenía las llaves,
que abriera un poco una de las puertas superiores para que saliera el humo.
Además de esta dificultad el clima estaba húmedo, y cuando llovía se mojaba su cama,
a tal grado, que su camisa se mojaba.
En esta lamentable condición permaneció durante un largo y frío invierno,
la cual lo afectó tanto,
que su cuerpo se hinchó y tenía las extremidades muy entumecidas.
Lo dejaremos aquí hasta que sea llevado de nuevo a juicio,
el cual sucedió el año siguiente.

Pero debo mencionar antes de separarme de él,
que algún tiempo antes de esto había escrito varios documentos dirigidos al emperador,
a los reyes de Francia y España, y también al papa.
Estos escritos fueron traducidos por alguien más al latín, y así se imprimieron.
En estos documentos se dirigió principalmente contra la persecución
por asuntos de religión. Reprendió al rey de España especialmente,
por la Inquisición y la quema de personas en la hoguera.
Y no perdonó al papa,
entremezclando sus escritos con muchas demostraciones
de que la iglesia romana era la ramera de Babilonia,
que era ella la que se había contaminado con la idolatría y superstición,
y se había bañado con la sangre de los santos,
atacándolos furiosamente tanto con la espada como con el fuego.
Esto lo concluyó con estas palabras: "`Las plagas de Dios serán tu porción, oh papa,
que has engañado a las naciones.
Y todos ustedes Jesuitas y Cardenales, aúllen, porque se acerca su miseria,
y el día poderoso del Señor Dios viene sobre todos;
porque el Señor Dios será adorado en Espíritu y en Verdad,
y con ninguna de sus invenciones.`"
Así les escribió G. Fox en aquel día al papa y a sus consejeros;
y no es de extrañar que pagara caro por este fuerte
lenguaje contra la cabeza de la iglesia de Roma,
pues se creía que gran parte del partido de los de la realeza en aquellos días,
eran o Católicos encubiertos o favorecedores de ellos.
Y sin embargo, entre el clero nacional, e incluso, entre los de otras persuasiones,
tachaban a los Cuáqueros con el nombre de Católicos clandestinos,
para hacerlos merecedores del odio del pueblo.

Ahora regreso a Francis Howgill, a quien dejamos el año anterior en la cárcel de Appleby.
Él fue llevado a juicio en la primera parte de este
año. Tras llegar al tribunal antes que los jueces,
le habló al secretario de la sesión del tribunal diciéndole,
que él no sabía si esperaban su comparecencia en ese momento o no.
El secretario le dijo: "`Has hecho bien en venir;`" y dijo que se lo haría saber al juez,
quien sólo lo comprometería a comparecer en las próximas sesiones del tribunal,
para que respondiera a la acusación contra él. Francis
le pidió que hiciera lo que fuera necesario hacer.
Mientras tanto, sir Philip Musgrave (así llamado),
un gran adversario de la Verdad y el más grande y principal acusador de Francis,
había informado a los jueces contra él diciéndoles que era una persona peligrosa,
un cabecilla,
y de los que celebraban reuniones que eran de consecuencias peligrosas
y destructoras de la paz de la nación. Por lo tanto,
concluyeron que Francis debía comparecer ante el tribunal;
y así se lo comunicó el secretario,
y le dijo a qué hora aproximadamente debía ser llamado.
Cuando comenzó el juicio,
el juez Twisden le dio la acusación al gran jurado en la que él decía: "`Hay un pueblo,
quienes bajo la pretensión de consciencia y religión,
parecen basarse en la declaración del rey en Breda, y bajo esa cubierta,
traman traición y rebelión.`" Luego le dio el encargo al
jurado de que investigaran y descubrieran a tales hombres,
para que la paz de la nación fuera preservada.
A continuación, convocaron al jurado y Francis fue llamado al estrado,
y el juez habló de la siguiente manera.

Hablando con calma el juez le dijo:
"`La apariencia de las cosas ha cambiado mucho desde la última sesión del tribunal,`"
y luego pronunció un gran discurso para F. Howgill y el condado,
diciéndole,
que todas las sectas bajo pretexto de consciencia violaban las leyes y tramaban rebeliones.
"`No, que tenga algo de qué acusarte,`" dijo él,
"`pero dado que el juramento de lealtad te fue presentado en la última sesión del tribunal,
y tú te negaste a prestarlo,
se consideró que tales personas eran enemigos del rey y del gobierno.`"
Luego dijo: "`No te molestaré ahora para que respondas a tu acusación,
pero debo hacerlo en la siguiente sesión del tribunal.
Mientras tanto, debes dar fianza de buen comportamiento.`"

[.offset]
A esto Francis Howgill respondió:
"`Deseo libertad para hablar;`" lo cual le fue concedido sin interrupción,
y dijo lo siguiente:

[.discourse-part]
__F+++.+++ Howgill:__ Juez Twisden, tú sabes bien con cuán escasa,
o ninguna razón fui traído delante de ti en la última sesión del tribunal,
en la que te plació presentarme el juramento de lealtad,
aunque creo que tanto tú como el resto del tribunal sabían,
que es un principio aceptado entre nosotros no jurar en ninguna manera.
Muchas razones te di entonces, y tengo muchas más que añadir, si me escuchan.
Porque si no ofrezco mis razones,
puede que te parezca algo absurdo y obstinado por mi parte que me niegue a hacerlo.
Yo no soy de esos que hacen de la religión una capa para la maldad,
ni hago de mis reclamos de consciencia una cubierta
para llevar a cabo maquinaciones y conspiraciones;
el Señor me ha redimido a mí y a muchos más de tales cosas.
Y viendo que estoy obligado a comparecer en la siguiente sesión del tribunal,
deseo que no se requiera nada más de mí.

[.discourse-part]
__Juez:__ Debes dar fianza durante este tiempo peligroso; por tanto, considéralo,
y dímelo ahora o antes de que acabe la sesión del tribunal.

[.offset]
El segundo día de la sesión del tribunal fue llamado de nuevo.

[.discourse-part]
__F+++.+++ Howgill:__ Viendo que te complace dejarme responder a la acusación,
cosa que estoy dispuesto a hacer, he sido de buen comportamiento y así continuaré;
pero me parece algo duro y lleno de severidad,
que viéndose que estoy obligado a comparecer para
responder a una acusación de tan grave naturaleza,
que apunta a la pérdida de mi libertad de por vida, y de mi patrimonio para siempre,
espero que el tribunal no me prive también de mi
libertad durante los próximos cinco meses.

[.discourse-part]
__Juez Turner:__ No deseamos tu encarcelamiento, si eres de buen comportamiento.

[.small-break]
'''

Entonces F. Howgill pidió que no lo obligaran a dar fianza de buen comportamiento,
sabiéndose obligado por la Verdad de tal manera que no podía portarse mal.

Un tal Daniel Flemming, otro juez perseguidor,
que había formulado otra acusación contra él por asistir a una reunión,
se puso de pie (temiendo que la trampa de dar una
fianza no se sostuviera) y dijo lo siguiente:

[.discourse-part]
__D+++.+++ Flemming:__ Mi señor,
él es un gran orador y puede que los Cuáqueros no puedan seguir sin él.

[.discourse-part]
__Juez:__ Que sea lo que quiera si da una fianza.

[.small-break]
'''

Entonces F. Howgill dijo que no tenía nada de qué acusarse,
porque su consciencia le daba testimonio de que amaba
la paz y la buscaba con todos los hombres.

[.discourse-part]
__Jueces:__ ¿Por qué hablas de consciencia?
Nosotros no nos entrometemos con ella; pero ustedes desatienden las leyes,
celebran grandes reuniones y no van a la iglesia.

[.discourse-part]
__F+++.+++ Howgill:__ Hemos caído en una época triste,
si reunirnos pacíficamente sin armas ni fuerza, ni intención de hacerle daño a nadie,
sino únicamente para adorar a Dios en Espíritu, y exhortarnos unos a otros a la justicia,
y orar juntos en el Espíritu Santo como lo hacían los Cristianos
de antaño--se considera una ruptura de la paz y mal comportamiento.

[.discourse-part]
__Juez Twisden:__ ¿Comparas este tiempo con aquella época?
Ellos eran paganos que perseguían, pero nosotros somos magistrados Cristianos.

[.discourse-part]
__F+++.+++ Howgill:__ Es una doctrina sostenida por nosotros siempre,
y un principio recibido en el que creemos,
que el reino de Cristo no puede ser establecido con armas carnales,
ni el evangelio puede propagarse por la fuerza de la armas,
ni la iglesia de Dios puede ser edificada con violencia;
sino que debido a que el Príncipe de Paz ha sido manifestado entre nosotros,
no nos adiestramos más para la guerra,
sino que amamos a nuestros enemigos y perdonamos a los que nos hacen mal.

[.small-break]
'''

Entonces Philip Musgrave se puso de pie y dijo: "`Mi señor,
hemos sido negligentes con esta gente, y hemos luchado contra ellos,
y los hemos puesto en prisión una y otra vez, y multado, y tan pronto como salen,
se reúnen de nuevo.`"

Luego se levantó John Lowther, llamado magistrado, y dijo: "`Mi señor,
ellos se hacen más insolentes, a pesar de todas las leyes y la ejecución de ellas,
aun así siguen creciendo y sus reuniones son peligrosas.`"

Luego se levantó Philip Musgrave con el juez Flemming,
y mostraron un papel escrito con grandes letras mayúsculas, y se lo dieron al juez.
Él le contó al juez que algunos Cuáqueros habían sido enviados a prisión,
y que uno de ellos había muerto en Lancaster,
y que habían llevado el cadáver a través del condado, con ese papel sobre el ataúd:
"`Este es el cuerpo de tal, quien fue perseguido por Daniel Flemming hasta la muerte.`"

[.discourse-part]
__Juez:__ Hemos pasado mucho tiempo contigo; no discutiré más.

[.discourse-part]
__F+++.+++ Howgill:__
Reconozco
tu ecuanimidad hacia mí,
al permitirme la libertad de hablar.
No te molestaré mucho más. Estoy dispuesto a comparecer
y a responder a la acusación en la próxima sesión del tribunal,
y mientras tanto, viviré pacífica y tranquilamente, como lo he hecho,
si eso le satisface a la corte.

[.discourse-part]
__Juez:__ Debes dar fianza de que no asistirás a más reuniones.

[.discourse-part]
__F+++.+++ Howgill:__ No puedo hacer eso; si lo hiciera,
estaría traicionando a Dios y a mi propia consciencia,
y el pueblo y tú me juzgarían como un hipócrita.

[.small-break]
'''

Ellos estaban reacios a encerrarlo, sin embargo, al final lo hicieron.
Esto sucedió en la última parte del mes llamado marzo,
y lo mantuvieron unos cinco meses en una habitación inmunda como antes,
y no se le permitía a nadie que hablara con él,
sino los que se acercaban a él sin el conocimiento del carcelero.

Por este tiempo partió de esta vida John Audland.
Él y su querido amigo John Camm (que había fallecido unos años antes),
viajaron mucho juntos en el ministerio del evangelio.
Por tanto, haré un relato ininterrumpido de sus finales, comenzando con el de John Camm.

Nació en Camsgil de muy buena familia, en la baronía de Kendal, en Westmoreland,
cuya localidad habían poseído sus ancestros mucho tiempo
antes que él. Desde su infancia se inclinó a ser religioso,
y después, buscando las mejores cosas,
se unió con los que eran más estrictos en el cumplimiento de los deberes religiosos.
Después de oír a G. Fox, abrazó como verdad la doctrina que él predicaba,
y creciendo en ella,
J+++.+++ Camm mismo se convirtió en un eminente ministro
del evangelio entre los llamados Cuáqueros.
Él y su querido amigo John Audland,
fueron los primeros de dicha sociedad que predicaron en Bristol,
donde después de estar en las reuniones de los Bautistas e Independientes,
también tuvieron reuniones en varios lugares fuera de la ciudad,
a las que asistieron una gran cantidad de personas, y muchas recibieron su doctrina.

Desde ese momento estos dos ministros viajaron mucho juntos,
y muchos fueron convencidos por sus ministerios.
Pero al final, John Camm, que no era indulgente consigo mismo,
empezó a caer bajo una especie de tuberculosis,
al punto de que por causa de la debilidad se vio obligado a quedarse en casa.
Entonces, a menudo reunía a sus hijos y a su familia,
y los exhortaba a la piedad y oraba al Señor por ellos.
En una ocasión, unas semanas antes de su muerte, se expresó así:
"`Qué gran beneficio disfruto sobre muchos,
al tener tanto tiempo de preparación para la muerte, muriendo diariamente, para que así,
yo pueda vivir con Dios en ese reino que está indescriptiblemente lleno de gloria.
Mi hombre exterior se gasta y se corrompe, y se dirige hacia su lugar y centro;
pero mi hombre interior revive, y se eleva hacia su lugar y habitación en los cielos.`"

La mañana que partió de esta vida, llamó a su esposa, hijos y familia,
y los exhortó a temer al Señor, amar Su verdad,
caminar en ella y ser amorosos y amables los unos con los otros,
les dijo que su reloj de arena se había acabado,
que el momento de su partida había llegado, y que estaba por entrar en la tranquilidad,
gozo y reposo eternos,
y les encargó a todos que fueran pacientes y estuvieran contentos con
su separación de él. Luego se desvaneció y cayó en un dulce sueño. Pero
por el llanto y los gritos de los que estaban a su alrededor,
se despertó y pidió que lo enderezaran un poco en la cama,
y luego les habló en estos términos: "`Mis queridos corazones,
me han agraviado y perturbado, porque estaba en un dulce reposo.
No deben lamentarse tan apasionadamente por mi partida;
esta casa de tierra y barro debe ir a su lugar,
y esta alma y espíritu deben ser recogidos por el Señor, para vivir con Él para siempre,
donde nos encontraremos de nuevo con el gozo eterno.`"
Luego despidiéndose de su familia, les encargó que se contentaran con su partida,
y recostándose, al poco tiempo falleció.

Su querido amigo John Audland (quien a menudo lamentaba la pérdida de su querido compañero),
también murió de una especie de tuberculosis;
pues su ardiente celo con frecuencia lo hacía levantar
su voz más allá de lo que su cuerpo podía soportar.
En una ocasión, en una reunión que tuvo con John Camm a las afueras de Bristol,
donde Charles Marshall era uno de los oyentes,
después de que John Camm terminó de hablar,
se levantó con un semblante terrible y brillante,
y levantando su voz como una trompeta dijo:
"`Proclamo una guerra espiritual contra los habitantes de
la tierra que están en la caída y separación de Dios,
y profetizo a los cuatro vientos de los cielos.`"
Así continuó con gran poder, exhortando a la gente al arrepentimiento,
y habló con una autoridad tan penetrante,
que algunos de los oyentes cayeron al suelo y lloraron bajo la consciencia de sus transgresiones.

Y cuando estaba en Bristol, muchas veces le predicó a una gran multitud en un huerto,
y alzaba su voz tremendamente a fin de ser escuchado por todos.
Así gastó su fuerza natural, aunque no era más que un joven.
Alrededor del vigésimo año de edad, se casó con Anne Newby, de Kendal,
una virtuosa doncella, no sólo de una buena familia,
sino también sobresaliente en piedad.
Ella lo entregó libremente para que viajara al servicio del evangelio,
a pesar de que su compañía le era muy querida,
diciendo con frecuencia que ella creía que pocas disfrutaban
de una mayor bendición en un esposo tan amable y afectuoso.
Y cuán sincera y tiernamente lo amaba,
se puede ver en la siguiente carta que ella le escribió.

[.embedded-content-document.letter]
--

[.salutation]
Querido esposo,

Eres más querido para mí que nunca; mi amor fluye hacia ti,
en el mismo amor con el que soy amada por mi Padre.
En ese amor, deseo que saludes a todos mis amigos de mi parte,
porque todos son queridos para mí, y mi vida se refresca mucho cuando oye de ustedes.
Recibí tus cartas, y puedo decir que todo lo que mi alma desea es oír de ti en la Vida.
Amado corazón, habita en la Vida, porque ahí estoy contigo fuera de todo tiempo,
fuera de toda palabra, en el poder puro del Señor, donde están mi gozo y fortaleza.

¡Oh, cuánto me refresca oír de ti, oír de tu fidelidad y denuedo en la obra del Señor!
No puedo expresar el gozo que siento por ti.
Tu presencia me acompaña continuamente en espíritu y me llena de alegría.
¡Toda la gloria y el honor sean para nuestro Dios para siempre! ¡Oh,
bendito sea el día en que naciste,
que fuiste hallado digno de trabajar en la obra del Señor!
Ciertamente el Señor te ha hallado fiel en lo poco, y por eso te ha encomendado mucho.
Sigue, pues, en el nombre y poder del Señor Jesucristo, de quien viene toda la fuerza,
a quien pertenece toda la gloria y el honor para siempre.
¡Oh, amado corazón, continúa venciendo y para vencer, sabiendo esto,
que tu corona es segura!
Ahora es el tiempo de la obra del Señor y pocos están dispuesto a salir a ella.
Todo el mundo yace en maldad, haciendo su propia obra;
pero bendito sea el Señor por siempre,
quien nos ha llamado de hacer nuestra propia obra para hacer Su gran obra.
¡Cuán maravillosas son sus obras e inescrutables sus caminos!

¡Oh, amado esposo, tú conoces mi corazón y puedes leer en él diariamente,
cuánto me regocijo en nada más que en tu prosperidad en la obra del Señor!
En verdad, no tengo palabras para expresar el gozo que siento por ti.
Estoy llena de amor hacia ti; nunca antes había conocido un amor como este.
¡Qué el gran poder del Señor te acompañe y te mantenga fiel,
valiente y osado en Su consejo puro, para permanecer firme fuera del mundo!
Mi amor por ti es más puro que el oro purificado siete veces en el fuego.
¡Oh, puro es Aquel que nos ha amado, por tanto,
que la pureza y santidad nos cubran para siempre!
Un sonido jubiloso fue para mí oír que habías sido movido a ir a Bristol.
¡Oh, mi propio corazón, mi propia vida!
En esa Vida que ahora sientes, actúa y obedece para que te mantengas en guardia,
y que tus oraciones por mí sean que me mantenga pura, fuera de toda tentación,
para morar plenamente en la vida.

[.signed-section-closing]
Así que adiós.

[.signed-section-signature]
Anne Audland.

--

De esta carta se desprende,
que había un entrañable y mutuo amor entre esta virtuosa pareja.
Él era un hombre de gran conocimiento,
pero cuando su entendimiento fue abierto por la predicación de G. Fox, a veces decía:
"`Ah, ¿qué hemos estado haciendo?
¿De qué sirve nuestra gran profesión religiosa?
Todo nuestro edificio se derrumba, nuestra profesión es tan alta como el viento,
y el día del Señor está sobre ella.
Su palabra, como fuego, la consume como hojarasca seca,
y le pone fin a todas las profesiones vacías y a
los conceptos altivos que no tienen vida ni sustancia,
y a toda la sabiduría del hombre caído. Debemos abandonar el mundo y toda su gloria;
porque todo es vanidad y aflicción de espíritu.
Anhelo al Salvador, Aquel por quien mi alma suspira.
¡Oh, que pueda ser recogido en Su vida, eclipsado con Su gloria,
completamente santificado por Su palabra y levantado por Su poder eterno!`"
Continuando en este estado de súplica diaria y esfuerzo interno de alma,
le plació al Señor, finalmente,
dotarlo de una extraordinaria capacidad para proclamar Su palabra,
lo cual hizo durante algunos años fielmente y con gran celo.
Y aunque su esposa lo amaba mucho,
y prefería su compañía por encima de lo que el mundo pudiera darle,
con respecto a su servicio en el evangelio,
ella lo entregó libremente para que estuviera mucho tiempo fuera de casa;
por lo que durante gran parte de su matrimonio, ella no tuvo su deseable compañía.

Mientras tanto,
él trabajó diligentemente en la mies del Señor hasta
que su fuerza corporal empezó a flaquear,
y al toparse con duros encarcelamientos, era atacado por una tos muy violenta,
seguida por una fiebre que le quitaba el sueño. Esto lo debilitó mucho,
pero él soportó su enfermedad con gran paciencia, y en una ocasión dijo,
que en aquellas grandes reuniones en un huerto en Bristol,
a menudo se olvidaba de sí mismo,
y que no consideraba la incapacidad de su cuerpo con tal de ser escuchado por todos;
y que no obstante, su recompensa estaba con él y estaba contento de estar con el Señor,
lo cual su alma valoraba por encima de todas las cosas.

No mucho antes de su partida, cuando lo visitaban algunos de sus amigos,
hablaba cómodamente y con gran poder,
como quien está más allá del sentimiento de su debilidad.
A su esposa, que estaba embarazada y a punto de dar a luz,
sabiendo muy bien cuán tiernamente lo amaba ella, le dijo:
"`Mi voluntad está en verdadera sujeción, sometiéndose a la voluntad del Señor,
ya sea en la vida o en la muerte; por tanto,
entrégame libremente a Su disposición.`" Y aunque él era muy querido para ella,
así lo hizo; lo cual le dio cierta tranquilidad a él,
al ver la sincera rendición de ella.
A veces, sobrecogido por el gozo, alababa a Dios en su enfermedad; y en efecto,
su celo era tan ardiente, que una vez, aunque estaba muy débil,
pidió que lo ayudaran a levantarse en la cama sobre sus rodillas,
y fervientemente le suplicó al Señor en favor de las iglesias,
que las preservara en la verdad, fuera del mal del mundo,
y que el evangelio se extendiera y fuera publicado para
reunir a todos los que pertenecían a Israel.

Su fuerza disminuía a diario,
y partió dulcemente de esta vida a la edad de treinta y cuatro años,
unas tres semanas después de que la fiebre se apoderara de él por primera vez.
Su viuda, que diez días después de su fallecimiento dio a luz un hijo,
se comportó con discreción, y dijo después en un documento con respecto a él:
"`El Dios eterno,
quien por Su providencia nos unió en matrimonio en nuestros días de juventud,
en Su bendito consejo, también hizo que Su día brotara desde lo alto sobre nosotros.
Y en el brillante resplandor de Su maravillosa luz,
reveló a Su Hijo Jesucristo en nosotros y nos dio fe para creer en Él,
la Palabra eterna de vida,
por medio de la cual nuestras almas llegaron a ser movidas y vivificadas en Él. Además,
en y por el poder vivificante de Su santo poder,
fuimos hechos uno en una relación espiritual y celestial,
al unir nuestros corazones en el inefable amor de la verdad, el cual era nuestra vida,
gozo y deleite, e hizo que nuestros días juntos fueran sumamente cómodos;
pues por este todos nuestros disfrutes temporales fueron
santificados y se convirtieron en una bendición para nosotros.
Cuán difícil fue,
y cuán grande pérdida supuso separarme de un esposo
tan querido y tierno como fue él conmigo,
está más allá de lo que puedo expresar.
Mi lengua o mi pluma no son capaces de declarar el dolor de mi corazón. Sin embargo,
me contenté con saber que era la voluntad del Señor
que él fuera tomado de este mundo malo,
y que mi pérdida, aunque grande, no debía compararse con su ganancia eterna.`"
Esta viuda, con el paso del tiempo, se casó de nuevo con Thomas Camm, hijo de John Camm,
el amigo querido de su anterior esposo.
Era, en verdad, una mujer de gran virtud, pero ahora la dejo,
con la intención de decir más de ella cuando llegue el momento de su fallecimiento.

Regreso a Francis Howgill, a quien dejamos en prisión,
y que en el mes llamado agosto compareció de nuevo
en la sesión del tribunal que se celebró en Appleby.
Tras obtener la libertad de hablar con el secretario de la sesión del tribunal,
se le dijo que debía prepararse para ir a juicio.
A esto él respondió que estaba preparado, aunque todo lo que dijera no sirviera de nada,
pues creía que ellos tenían el propósito de procesarlo con toda severidad.
Este resultó ser el caso, como se verá en lo que sigue,
pues los magistrados del condado habían incitado a los jueces contra él de antemano.
Sin embargo, Howgill se esforzó todo lo que pudo por convencerlos de su inocencia,
y para ese fin escribió la sustancia del juramento en varios puntos que podía suscribir;
a esto adjuntó otro documento para el juez Turner,
mostrando la razón de su primer encarcelamiento y
los anteriores procedimientos contra él,
y cuán injusto era procesarlo en virtud de un estatuto hecho contra los Católicos recusantes.^
footnote:[Un Católico romano inglés, entre 1570 y 1791,
que se negaba a reconocer la supremacía del rey,
o a ajustarse a los ritos establecidos por la iglesia de Inglaterra.]
También indicó en ese documento,
que él era un hombre de espíritu tierno y que temía al Señor desde niño,
y que no había prestado ningún juramento salvo una vez en su vida,
cuando tenía veinte años. Explicó que su negativa a prestar el juramento de lealtad,
no se debía a una mala intención contra la persona del rey o del gobierno,
sino simplemente a motivos de consciencia,
y que no podía jurar al estar persuadido por el Señor de lo contrario,
ya que era contra el mandamiento de Cristo y la doctrina del apóstol Santiago.

Además de esto dijo, que podía hacer evidente que por varios cientos de años,
jurar había estado en contra del ejemplo de los Cristianos primitivos,
y que por lo tanto, no era una opinión nueva.
Afirmó además, que no se rehusaba a jurar testarudamente, ni obstinadamente,
estando consciente del daño que sobrevendría si lo procesaban basados en ese estatuto,
pues tenía esposa y niños,
y un pequeño patrimonio que sabía que estaba en juego en el asunto; pero que,
aunque su vida también estaba en juego,
no podía rebelarse o negar aquello en lo que ciertamente había creído. No obstante,
dijo que si alguien podía convencerlo de lo contrario
por medio de las Escrituras o la razón,
él tenía oídos para escuchar.
Por tanto, consideradas todas esas cosas,
pidió ser liberado de sus ataduras y de la persecución que le hacían por ese motivo.
Los documentos les habían sido entregados a los jueces y a los
magistrados antes de que él compareciera en el tribunal,
y fueron leídos por ellos.
Entonces, cuando lo llamaron al estrado en la sesión del tribunal en Appleby,
el juez Turner le dijo:
"`Aquí hay una acusación contra ti por rehusarte a prestar el juramento de lealtad,
así que debes declararte culpable o no culpable.`"

[.offset]
F+++.+++ Howgill, con el corazón ceñido de fuerza y valor dijo: "`Juez Turner,
¿puedo tener la libertad de hablar y hacer mi defensa,
ya que no tengo a nadie que defienda mi causa, sino al Señor?`"

[.discourse-part]
__Juez:__ Puedes.

[.discourse-part]
__F+++.+++ Howgill:__ Expondré delante de ustedes el verdadero estado de mi caso,
y de los procedimientos contra mí desde el principio,
ya que el juez Twisden no está aquí,
y era el que tenía conocimiento de todos los procedimientos hasta ahora.
Yo soy un compatriota, nacido y criado en este condado;
mi porte y mi conducta son conocidos,
y que he caminado pacíficamente para con todos los hombres,
como espero que mis conciudadanos puedan atestiguar.
Hace casi un año,
estando en el mercado de mi pueblo vecino por motivos razonables y legítimos,
fui llamado a salir del mercado por un alguacil mayor
y a comparecer ante los jueces de paz,
delante de los cuales me presenté; cuando llegué ahí, no tenían nada de qué acusarme,
pero empezaron a hacerme preguntas acerca de nuestras reuniones para atraparme.
Y cuando no encontraron ninguna razón,
me dijeron que me presentarían el juramento de lealtad,
y aunque ellos nunca me lo leyeron, ni yo tampoco lo negué positivamente,
me enviaron a prisión. Así fui traído aquí, a esta sesión del tribunal,
y entonces se pidió la orden judicial por la que yo había sido encerrado,
y el juez la leyó y les dijo a los magistrados que era insuficiente.
No obstante, el juez Twisden me presentó el juramento de lealtad en ese momento.

Muchas cosas alegué entonces y muchas más tengo que decir ahora, si el tiempo lo permite.
Desde ese momento he estado bajo el compromiso de
comparecer en la siguiente sesión del tribunal,
y por eso fui llamado, y comparecí en la última liberación de la cárcel,
pero me fue requerida una fianza adicional por buena conducta,^
footnote:[Este nuevo requerimiento de una fianza por buena conducta,
incluía la promesa de no asistir más a las reuniones religiosas.]
que no pude cumplir, para no caer en una nueva trampa.
Desde entonces he estado en prisión estos cinco meses,
durante los cuales me han mantenido bajo gran restricción,
y no se les ha permitido a mis amigos hablar conmigo; y así, brevemente,
les he dado cuenta hasta ahora.
En cuanto al juramento, la sustancia de este, junto con la descripción de mi caso,
ya han sido presentados al tribunal, sobre lo cual he puesto mi firma,
y con esas mismas palabras testificaré en una audiencia pública si se requiere.
Y dado que es la sustancia misma que la ley requiere,
solicito que se acepte y que yo sea liberado del encarcelamiento.

[.discourse-part]
__Juez:__ Yo he venido para ejecutar la ley, y la ley requiere un juramento,
y no puedo alterarla.
¿Acaso piensas que la ley debe ser cambiada para ti, o para unos pocos?
Si se permitiera esto, la administración de justicia sería entorpecida,
no se podría juzgar ninguna acción, ni presentarle prueba al rey,
ni juzgar otros casos específicos.
Tus principios son completamente inconsistentes con la ley y el gobierno;
te pido que me muestres el camino que debemos seguir,
muéstrame alguna razón y dame algún fundamento.

[.discourse-part]
__F+++.+++ Howgill:__ Lo haré,
"`En la boca de dos o tres testigos toda verdad es confirmada;`" y nunca
hemos negado dar y todavía estamos dispuestos a dar evidencia al rey,
en lo que nos concierne,
y en cualquier otro asunto para poner fin a la disputa
entre hombre y hombre en la verdad y justicia,
y esto responde a la sustancia de la ley.

[.discourse-part]
__Juez:__ ¿Crees que esa es una buena respuesta?
La ley requiere un juramento.

[.discourse-part]
__F+++.+++ Howgill:__ Aun así, la evidencia es y puede ser dada en la verdad,
en concordancia con la sustancia de la ley,
de manera que no se perjudique a ninguna de las partes,
dado que el verdadero testimonio puede darse sin un juramento.
No hablé de cambiar la ley; sin embargo,
viendo que nosotros no nos negamos a dar un testimonio verdadero,
el cual responde a la intención y sustancia de la ley,
juzgué que era razonable recibir nuestro testimonio y no exponernos a tales sufrimientos,
al ver que tenemos escrúpulos con respecto a jurar únicamente por motivos de consciencia,
en ternura de consciencia, por temor a quebrantar el mandamiento de Cristo,
el Salvador del mundo; que si lo hiciéramos,
ninguno de ustedes sería capaz de defender nuestra causa ante Él.

[.discourse-part]
__Juez:__ Pero, ¿por qué no van a la iglesia,
sino que se reúnen en casas y conventículos privados, lo cual prohíbe la ley?

[.discourse-part]
__F+++.+++ Howgill:__
Nosotros nos reunimos sólo para adorar al Dios verdadero en Espíritu y Verdad,
teniendo a los Cristianos primitivos como ejemplo, y para ningún otro fin,
sino para ser edificados y Dios glorificado;
y cuando dos o tres están reunidos en el nombre de Cristo, y Él está en medio de ellos,
hay una iglesia.

[.discourse-part]
__Juez:__ Eso es cierto.
Pero, ¿hace cuánto que no vas a la iglesia?
O, ¿irás a la iglesia que la ley sí permite?
Dame algunas razones por las que no vas.

[.discourse-part]
__F+++.+++ Howgill:__ Tengo muchas que darte, si tienes paciencia de oírme.
Primera, Dios no habita en templos hechos por manos de hombres.
Segunda, la casa de la parroquia ha sido un templo para ídolos, es decir,
para sus ceremonias e imágenes; y no me atrevo a tener comunión con ídolos,
ni adorar en templos de ídolos; porque, ¿qué tenemos que ver nosotros con ídolos,
sus templos y adoración?

[.discourse-part]
__Juez:__ ¿No había casas en las Escrituras llamadas casas de Dios y templos?

[.discourse-part]
__F+++.+++ Howgill:__ Sí, bajo la ley; pero los Cristianos, los que habían creído en Cristo,
se separaron de estas (y el templo fue hecho y dejado
desolado) y de los templos gentiles también,
y se reunían en casas, y partían el pan de casa en casa.
Y la iglesia no estaba confinada entonces en un determinado lugar, ni lo está ahora;
muchas más cosas tengo que decir.
+++[+++El juez interrumpió.]

[.discourse-part]
__Juez:__ ¿Responderás a tu acusación?

[.discourse-part]
__F+++.+++ Howgill:__ No sé qué es, nunca la he oído, aunque a menudo he pedido una copia.

[.discourse-part]
__Juez:__ ¡Secretario, léela!

[.offset]
Entonces, el secretario la leyó, declarando que F. Howgill, "`se había negado testaruda,
obstinada y despectivamente a jurar cuando se le había presentado el juramento.`"

[.discourse-part]
__F+++.+++ Howgill:__ Lo niego.

[.discourse-part]
__Juez:__ ¿Qué niegas?

[.discourse-part]
__F+++.+++ Howgill:__ La acusación.

[.discourse-part]
__Juez:__ ¿No te negaste a jurar?
La acusación te declara culpable por no haber jurado.

[.discourse-part]
__F+++.+++ Howgill:__ Yo le di al tribunal la sustancia del juramento, como todos saben.
Segundo, les dije que no lo negaba obstinada o testarudamente,
ni en desprecio a la ley del rey ni del gobierno;
porque mi voluntad preferiría escoger mi libertad, que cadenas.
Y estoy consciente de que esto me puede causar un gran daño, porque tengo esposa y niños,
y algunos bienes, con los que podríamos subsistir y hacer bien a otros,
y sé que todo esto está en juego.
Pero, aunque mi vida estuviera en juego también,
no me atrevería hacer otra cosa sino lo que estoy haciendo,
para no incurrir en el desagrado de Dios.
¿Crees que yo perdería mi libertad voluntariamente,
y que sufriría el despojo de mi propiedad,
y la ruina de mi esposa y mis niños por obstinación y testarudez?
Ciertamente no.

[.discourse-part]
__Juez:__ Jurado, ustedes pueden ver que él niega el juramento,
y que no se declarará culpable de la acusación,
sino que objeta contra ella por la forma de las palabras; pero pueden ver que no jura,
y que aun así niega la acusación, y ven en qué se basa.

[.small-break]
'''

Entonces llamaron al carcelero para que atestiguara
y jurara que en la última sesión del tribunal,
F+++.+++ Howgill se había negado a prestar el juramento, etc.; y luego el jurado,
sin salir del estrado,
dio su veredicto de "`culpable,`" y la corte levantó la sesión esa noche.

Al día siguiente hacia el anochecer, cuando habían juzgado a todos los prisioneros,
Francis fue llevado al estrado para recibir su sentencia.

El juez se puso de pie y dijo: "`Vamos, la acusación está aprobada contra ti,
¿qué tienes que decir del por qué no debería ser dada la sentencia?`"

[.discourse-part]
__F+++.+++ Howgill:__ Tengo muchas cosas que decir, si desean escucharlas.
En primer lugar, como he dicho, no me he negado por obstinación o testarudez,
sino que he estado dispuesto a testificar la verdad en este asunto de la obediencia,
o en cualquier otro asunto en el que esté involucrado.
En segundo lugar,
me he negado debido a que jurar está directamente en contra del mandamiento de Cristo.
En tercer lugar, porque está en contra de la doctrina del apóstol Santiago.
En cuarto lugar, incluso algunos de los principales pilares de la iglesia de Inglaterra,
como el obispo Usher, por un tiempo arzobispo de Irlanda, dijo en sus obras,
que los valdenses^
footnote:[El movimiento valdense surge en el siglo XII a partir del movimiento
de "`los pobres de Lyon`" y de la predicación de Pedro Valdo.
Los valdenses se proclamaban sucesores directos de los cristianos primitivos,
quienes durante las persecuciones por parte de los romanos en el siglo I,
se dispersaron por toda Europa, y luego, cuando surgió la Reforma protestante,
se unieron a ella.]
negaron todo juramento en su época,
debido al mandamiento de Cristo y del apóstol Santiago,
y que eso era suficiente fundamento.
Y el Dr. Gauden, último obispo de Exeter, en uno de sus libros que leí recientemente,
citó a muchos antiguos padres para demostrar,
que por los primeros trescientos años los Cristianos no juraron,
de modo que esta no es una doctrina nueva.

[.small-break]
'''

El tribunal pareció prestarle un poco de atención a esto y no dijo nada,
sino que hablaron entre ellos, mientras Francis permanecía en silencio.
Entonces el juez dijo:

[.discourse-part]
__Juez:__ De seguro que te equivocas.

[.discourse-part]
__F+++.+++ Howgill:__ No tengo los libros aquí.

[.discourse-part]
__Juez:__ ¿Dices bajo tu honesta palabra que ellos negaban todo juramento?

[.discourse-part]
__F+++.+++ Howgill:__ Lo que he dicho es cierto.

[.discourse-part]
__Juez:__ ¿Por qué ustedes no van a la iglesia y oyen el servicio,
y se sujetan a la ley y a cada ordenanza del hombre por causa del Señor?

[.discourse-part]
__F+++.+++ Howgill:__ Nosotros estamos sujetos, y por esa causa pagamos impuestos,
tributos y rentas, y le damos al César las cosas que son del César,
y a Dios las cosas que son de Dios, a saber, adoración, honor y obediencia;
y si te refieres a la asamblea parroquial, honestamente te digo, que estoy persuadido,
sobre un buen fundamento, que sus maestros no son los ministros de Cristo,
ni su adoración la adoración de Dios.

[.discourse-part]
__Juez:__ ¡Vaya, por unos pequeños desacuerdos en el servicio lo rechazan todo!

[.discourse-part]
__F+++.+++ Howgill:__ En primer lugar, es evidente que son servidores del tiempo;^
footnote:[Un "`servidor del tiempo`" es aquel que
adapta sus opiniones y modales a los tiempos,
o a los cambiantes poderes gobernantes.]
en un momento predican como '`servicio divino`' lo
que en otro momento habían tachado como papista,
supersticioso e idólatra.
Y lo que han predicado por veinte años seguidos, lo hacen naufragar en un día;
y más tarde lo volverán a llamar divino,
y obligarán a todos a creer lo que ellos mismo anularon una vez.

[.discourse-part]
__Juez:__ ¿Cómo, desde que el rey entró?

[.discourse-part]
__F+++.+++ Howgill:__ Sí, los mismos hombres que predicaron en su contra una vez,
ahora lo recomiendan y obligan a todos a creer.
Son tan inestables y vacilantes, que no podemos creer que sean los ministros de Cristo.
En segundo lugar, enseñan por un salario, viven de un mantenimiento forzado,
y quieren imponer una fe sobre los hombres,
en contra de la regla de Cristo y de Su apóstol,
que dijo que cada uno debe estar persuadido en su propia mente,
y que "`todo lo que no proviene de fe, es pecado.`"
Y aunque los sacerdotes dicen:
"`La fe es don de Dios,`" aun así quieren imponer la de ellos sobre nosotros;
y debido a que no podemos recibirla,
gritan "`ustedes no están sujetos a la autoridad ni a las leyes,`"
y no hacen más que amenazarnos con la confiscación de bienes,
encarcelamientos y destierros.
Podría mencionar más detalles.
+++[+++Entonces el juez interrumpió.]

[.discourse-part]
__Juez:__ Bien, veo que no juran, ni se conforman, ni se sujetan,
y piensan que los tratamos severamente, pero si se sujetaran, no sería necesario.

[.discourse-part]
__F+++.+++ Howgill:__ En efecto,
juzgo que nos tratan con severidad por obedecer el mandamiento de Cristo.
¿Podrías mostrarme cómo han procedido con este estatuto,
contra las personas para las que se hizo la ley?
Aunque no envidio la libertad de nadie.

[.discourse-part]
__Juez:__ ¡Oh,
sí! Puedo citar a muchos en todo el condado que han
sido procesados con el estatuto premunire.
Yo mismo lo he hecho, he dictado la sentencia contra varios.

[.discourse-part]
__F+++.+++ Howgill:__ ¿Contra los papistas?

[.discourse-part]
__Juez:__ No.

[.discourse-part]
__F+++.+++ Howgill:__ ¿Contra los Cuáqueros?
Sí, eso he oído. Por tanto, aunque el estatuto fue hecho contra los papistas,
ustedes los dejan en paz y lo ejecutan contra los Cuáqueros.

[.discourse-part]
__Juez:__ Bien, ustedes desean reunirse en gran número, y siguen aumentando,
pero hay un nuevo estatuto que hará que sean menos.

[.discourse-part]
__F+++.+++ Howgill:__ Bien, si debemos sufrir, es por causa de Cristo y hacer el bien.

[.small-break]
'''

Estando Francis en silencio, el juez pronunció la sentencia, pero habló en voz tan baja,
que el prisionero, aunque estaba cerca de él, apenas pudo oírla.
La sentencia fue: "`Quedas fuera de la protección del rey y del beneficio de la ley;
tus tierras son confiscadas para el rey durante todo tu vida,
y tus bienes y pertenencias para siempre; estarás preso durante toda tu vida.`"

[.discourse-part]
__F+++.+++ Howgill:__ Una sentencia dura por mi obediencia a los mandamientos de Cristo;
el Señor los perdone a todos.

[.offset]
Entonces se apartó del estrado, pero al hablar el juez, se volvió de nuevo,
y se expresaron muchas palabras con el mismo propósito de antes.
Al final, el juez se levantó y dijo:

[.discourse-part]
__Juez:__ Bien, si todavía quisieras someterte a la ley, el rey te mostrará misericordia.

[.discourse-part]
__F+++.+++ Howgill:__ El Señor ha mostrado misericordia hacia mí,
y no he hecho nada en contra del rey, ni del gobierno, ni de ningún hombre;
¡y bendito sea el Señor, en eso está mi paz!
Pues es por causa de Cristo que sufro y no por hacer el mal.

Y así se levantó la sesión. La gente en general se comportó moderadamente,
y muchos lamentaron lo que se había hecho contra él. Pero
Francis manifestó cuán contento y feliz estaba,
de tener algo que perder por la preciosa Verdad del Señor,
de la que él había dado testimonio públicamente,
y de que ahora era considerado digno de sufrir por ella.

Esto lo hizo alegremente,
y murió en prisión después de más de cuatro años de encarcelamiento,
como se relatará a su debido tiempo.
Él era un hombre culto y un gran escritor entre sus compañeros creyentes.
Durante su confinamiento escribió,
no sólo varias epístolas edificantes para exhortar a sus
amigos a la constancia y firmeza en la doctrina de la Verdad,
sino también algunos libros para refutar a los que se oponían a ella.

Acabamos de ver cómo el juez dijo: "`Hay un nuevo estatuto que hará que sean menos.`"
Este estatuto llevaba el título de "`__An Act to Prevent and Suppress Seditious Conventicles.__`"^
footnote:["`__Ley para Prevenir y Suprimir los Conventículos Sediciosos.__`"]
Y aunque una ley promulgada dos años antes se extendía hasta el destierro,
ese castigo fue renovado y expresado con más amplitud en esta nueva ley,
un extracto de la cual es como sigue:

[.embedded-content-document.legal]
--

[.letter-heading]
Ley para Prevenir y Suprimir los Conventículos Sediciosos

Para proporcionar adicionales y más rápidos remedios contra
las crecientes y peligrosas prácticas de sectas sediciosas,
y otras personas desleales, quienes bajo la pretensión de consciencia tierna,
traman insurrecciones en sus reuniones, como ha demostrado la reciente experiencia:

Se promulga por la excelentísima majestad del rey,
por y con el consejo y consentimiento de los señores (espirituales y temporales),
y por la autoridad del presente Parlamento,
que si alguna persona de dieciséis años o más, súbdito de este reino,
en cualquier momento después del 1 de julio de 1664, se hace presente en alguna asamblea,
conventículo o reunión, bajo el pretexto de algún ejercicio de religión,
en una forma diferente a la que es permitida por
la liturgia o práctica de la iglesia de Inglaterra,
en cualquier lugar dentro del reino de Inglaterra y el dominio de Gales;
y en dicha asamblea, reunión o conventículo hay cinco o más personas reunidas,
además de las personas de la familia misma; es legal que dos jueces de paz,
o el magistrado principal del condado en el que se cometió el mencionado delito,
levanten un acta de cada uno de los delitos, la firmen y la sellen,
después de que se haya demostrado por la confesión de la parte,
por el juramento de un testigo, o por evidencia del hecho.
Acto seguido, los citados jueces, o el magistrado principal,
enviarán a cada transgresor así condenado a la cárcel o casa de corrección,
donde permanecerá sin fianza por un período que no exceda los tres meses,
a menos que el ofensor pague a los citados jueces, o magistrado principal,
una suma de dinero no mayor de cinco libras,
dinero que se entregará a los guardas de la iglesia para el alivio de los pobres
de la parroquia en la que el ofensor habitó más recientemente.

Se promulga además por la autoridad antes mencionada,
que si el transgresor así condenado, comete de nuevo el mismo delito contra esta ley,
y es condenado por ello, entonces, dicho transgresor condenado por un segundo delito,
merecerá la pena de prisión en la cárcel o casa de
corrección por un tiempo que no exceda los seis meses,
sin fianza, a menos que el transgresor pague a los citados jueces,
o magistrado principal, una suma de dinero no mayor de diez libras.

Se promulga además por la autoridad antes mencionada,
que si alguno de los transgresores condenados por un segundo delito,
vuelve a cometer un tercer delito en contra de esta ley, entonces dos jueces de paz,
o el magistrado principal, enviará a dicho transgresor a la cárcel o casa de corrección,
donde permanecerá sin fianza hasta las siguientes sesiones trimestrales generales.
Y si el transgresor es legalmente condenado por dicho delito,
sea por confesión o veredicto,
o si dicho transgresor se niega a declarar o admitir la acusación,
entonces los respectivos jueces de paz quedarán por la presente habilitados
y obligados a hacer que se dicte sentencia contra el transgresor,
que será desterrado más allá de los mares a cualquiera de las plantaciones
extranjeras de su majestad (exceptuando sólo a Virginia y Nueva
Inglaterra) donde permanecerá por siete años.

Se promulga además por la autoridad antes mencionada,
que toda persona que a sabiendas y voluntariamente permita que se celebre en su casa,
dependencia, granero o habitación, patio, bosques o terrenos,
cualquiera de estos conventículos,
asambleas o reuniones ilegales antes mencionadas de cinco o más personas,
sufrirá las mismas penas y decomisos que sufre cualquier
otro transgresor contra esta ley,
y será procesado en todos los aspectos,
de la misma manera que debe ser procesado cualquier otro transgresor de esta ley.

En lo que respecta a la secta llamada Cuáqueros,
si se descubre que además obstruyen los procedimientos de la justicia,
por su obstinada negativa a prestar juramentos que son legalmente
presentados ante ellos en el curso ordinario de la ley,
entonces, en tal caso,
los respectivos tribunales en los que se produzcan tales negativas,
quedarán habilitados y obligados por la presente a registrar
o anotar tales negativas como una condena por el delito;
y toda persona que infrinja de esta manera,
sufrirá la sentencia y castigo de destierro al extranjero en la forma previamente descrita.

--

Un erudito en Londres, no sé de qué persuasión religiosa,
publicó un librito en relación con esta ley,
en el que a partir de las leyes de Inglaterra, demostraba lo absurdo de esta.
"`Porque,`" dijo él,
"`si se prohibieran todos los actos de religión ejecutados por seis personas
que no estuvieran de acuerdo con la formalidad de la iglesia de Inglaterra,
entonces, se consideraría una transgresión,
que una persona del grupo dijera una oración cuando una mujer que
está dando a luz estuviera en peligro de perder su vida.
Lo mismo sería cierto,
si alguien dijera algo para consolar a los parientes cercanos de una persona fallecida,
u orara por la salud o felicidad de una joven pareja recién casada, etc.
Entonces, podría ocurrir que alguno, por la malicia de sus enemigos,
no sólo sufriera encarcelamiento por tres meses,
sino que también fuera condenado al destierro.`"
Ahora bien, que esta suposición no era irracional,
quedó suficientemente demostrado por lo que el juez
Orlando Bridgman le dijo al jurado en Hertford:
"`Ustedes no deben esperar pruebas claras contra ellos por lo dicho o hecho en sus reuniones,
porque ellos pueden hablar entre sí, aunque no con o por medio de sonidos audibles,
sino con la mirada, el movimiento de la cabeza o de un pie, o el gesto del cuerpo.
De modo que, si descubren o creen en sus corazones que ellos estaban en la reunión,
bajo el pretexto de tener una reunión de religión a su manera,
aunque sólo estaban sentados quietos y se miraban entre sí,
estaban en una reunión ilegal.`"

Ahora,
como en ese entonces muchos estaban resueltos a desterrar a los llamados Cuáqueros,
George Whitehead publicó un librito en el que demostraba la sinrazón de los perseguidores,
y fortalecía a sus amigos con sólidos argumentos contra la acusación de terquedad,
respondiendo a algunas acusaciones engañosas.
Entre otras, se había sugerido que los Cuáqueros podrían mantener pequeñas reuniones;
porque si no se reunían más de cinco personas,
se mantendrían fuera del alcance de la ley; y al mantener reuniones pequeñas y privadas,
también podrían absolver sus consciencias delante de Dios.
Pero George Whitehead respondió a esto,
que se le habría podido objetar al profeta Daniel, que él habría podido orar en secreto,
y no con las ventanas abiertas tres veces al día,
después de que el rey Darío había firmado el decreto.
Pero que Daniel, a pesar del decreto, había continuado orando a Dios como antes.
"`Dado que nuestras reuniones,`" dijo G. Whitehead,
"`se mantienen en obediencia al Señor Dios, y según la libertad que Él nos ha dado,
no podemos dejar de dar nuestro testimonio de Dios en este caso, sino ser fieles a Él,
suframos lo que suframos por ello.
Porque ni las amenazas de los hombres, ni su severidad o crueldad contra nosotros,
por mucho que se extiendan, pueden hacernos abandonar al Señor,
haciendo que no mantengamos nuestras asambleas,
o que nos avergoncemos de Cristo delante de los hombres,
no sea que después Él se avergüence de nosotros delante
de Su Padre que está en los cielos.`"

Además de esto,
demostró cuán irracional era incitar al jurado con una sospecha infundada,
sin dejarles la libertad de su propio juicio.
También demostró cuán impropio era que los mismos soldados
que habían lastimado a los Amigos en sus reuniones,
fueran llamados como testigos contra ellos,
y que los Amigos fueran encerrados con ladrones y delincuentes,
siendo que era contrario al derecho de un ciudadano inglés. Pero
esta publicación de G. Whitehead fue en gran medida ignorada,
dado que muchos estaban decididos a continuar desterrando a los Cuáqueros,
y transportándolos a las Indias Occidentales, aunque, según las antiguas leyes,
esto no se le podía hacer a ningún ciudadano inglés contra su voluntad.
Por este tiempo, Josiah Coale también presentó un documento,
que era una advertencia al rey y a ambas cámaras del Parlamento,
para disuadirlos de la persecución. Pero no sirvió de nada,
porque la persecución continuó.

En el mes llamado agosto, siete de los llamados Cuáqueros, a saber: Francis Prior,
Nicholas Lucas, Henry Feast, Henry Marshal, Jeremiah Hern, Thomas Wood,
John Blendale y Samuel Trahern,
fueron llevados a Hertford delante del ya mencionado juez, Orlando Bridgman.
La acusación alegaba que habían estado en una reunión ilegal bajo la pretensión de religión,
y los testigos declararon que se habían reunido más de cinco personas,
y que habían sido cogidos en tales momentos y en tales lugares;
pero los testigos también declararon que no los habían oído decir ninguna palabra,
ni los habían visto hacer nada en sus reuniones, además de estar sentados.
Después de que la acusación le fue entregada al jurado,
no pudieron ponerse de acuerdo en su veredicto;
porque había algunos entre ellos cuyas consciencias
no los dejaban ser cómplices de esta obra de persecución;
y por lo tanto, entregaron su veredicto como __ignoramus.__^
footnote:[Queriendo decir, que no había suficiente evidencia para respaldar los cargos.]
Ahora, bien, aunque un veredicto como este no debía ser rechazado, el juez Bridgman,
poniéndose de pie y en apariencia enojado, le habló al jurado de la siguiente manera:
"`Mis señores, ¿qué se proponen hacer?
¿Harán de la ley una '`nariz de cera`'^
footnote:[Algo que puede ser fácilmente doblado, cambiado o influenciado.]
y permitirán que la ley sea confundida?
Aquellos que piensan burlar la ley, serán burlados por la ley.
¿Por qué no los declaran culpables?`"
A esto, uno de los miembros del jurado dijo,
que a ellos les concernía ser cuidadosos y estar bien satisfechos en lo que hacían,
porque las vidas de los hombres estaban en juego
por lo que ellos sabían. "`No,`" dijo el juez,
"`no deseo sus vidas,
sino que se reformen;`" y luego le dio al jurado algunas instrucciones,
y coloreó el asunto de manera tal,
que el jurado salió y regresó con un veredicto de "`culpables.`"

Entonces, cuatro de los prisioneros fueron llamados al estrado.
Les fue leída la acusación y se les preguntó: "`Culpables o no culpables.`"
A esto ellos respondieron:
"`No culpables,`" afirmando que no habían transgredido ninguna ley justa.
"`Pero,`" dijo el juez,
"`ustedes han transgredido _esta_ ley (sosteniendo el acta de la ley en su mano),
y ya han sido condenados dos veces en el expediente,
y si son hallados culpables por el jurado este vez,
debo dictar la sentencia de destierro contra ustedes.
Pero verán que no deseamos forzar la ley hasta la máxima severidad,
ni tampoco creemos que el objetivo de los legisladores fuera ser severos,
sino hacer que se conformen.
Ahora, si ustedes prometen que no irán,
o no volverán a estar en ninguna de esas reuniones, les mostraré este favor,
los absolveré de lo que ha pasado.
Este favor pueden recibirlo antes de que el jurado emita su veredicto;
después no puedo hacerlo.
También sepan, que si el jurado, por falta de evidencias puntuales,
no los encuentran culpables, aun así, si son cogidos otra vez,
estarán en la misma situación en la que están ahora.
¿Qué dicen?
¿Prometerán no reunirse más?`"

Los prisioneros respondieron que no podían hacer esa promesa.
Entonces fue llamado el jurado, y se leyó la acusación por segunda vez,
alegando que los prisioneros habían estado en una
reunión ilegal en cierto momento y en cierto lugar,
la primera vez, la segunda y la tercera vez.
Fueron llamados los testigos, dieron la misma evidencia de antes,
y luego el juez le dijo al jurado: "`Mis señores, el jurado,
ustedes oyeron la prueba que dieron los testigos,
la manera en que estos hombres fueron cogidos en ciertos momentos y en ciertos lugares,
que son los lugares en los que ellos suelen reunirse.
Vieron que superaban el número de cinco,
además de los miembros de la familia en donde estaban reunidos;
y que ya han sido condenados dos veces en el expediente.
Esta es la tercera transgresión,
la que implica la sentencia de destierro si los encuentran culpables.`"

Entonces, pronunció las palabras que ya habían sido mencionadas:
"`Ustedes no deben esperar pruebas claras contra ellos por lo dicho o hecho en sus reuniones,
porque ellos pueden hablar entre sí, aunque no con o por medio de sonidos audibles,
sino con la mirada, el movimiento de la cabeza o de un pie, o el gesto del cuerpo.
Ellos mismos dicen que la adoración de Dios es interna, en el Espíritu,
y que ellos pueden discernir los espíritus y conocerse los unos a los otros en espíritu.
De modo que, si descubren o creen en sus corazones que ellos estaban en la reunión,
bajo el pretexto de tener una reunión de religión a su manera,
aunque sólo estuvieran sentados quietos y se miraran entre sí,
estaban en una reunión ilegal;
ya que su costumbre y práctica no están en concordancia
con la liturgia de la iglesia de Inglaterra,
que permite y ordena que cuando la gente se reúne en la iglesia,
se lea ese servicio divino, etc.
Por tanto, deben declararlos culpables;
porque ustedes deben respetar el significado y la intención de la ley,
la que el rey y el Parlamento han promulgado en sabiduría y política,
no sólo contra los conventículos,
ya que se añadieron las palabras '`asamblea`' y '`reunión;`'
porque recientemente hemos tenido experiencia del peligro
de tales reuniones bajo el pretexto de ser una reunión religiosa,
y en tales reuniones es fácil conspirar y tramar el mal.
Por tanto, la sabiduría y la política del rey y del Parlamento, para no ser socavados,
han hecho esta ley; la cual, no es una ley contra la consciencia,
pues no toca la consciencia en absoluto, como confieso que sí hacen algunas otras leyes,
que exigen ir a la iglesia y hacer otras cosas.`"

Esto y más le habló el juez Bridgman al jurado,
con el fin de persuadirlos de que declararan a los prisioneros culpables.
Y saliendo el jurado, al cabo de una hora regresó,
y su presidente declaró que Nicholas Lucas y los otros tres eran culpables.

Lo que dijo el juez,
que últimamente habían experimentado el peligro de reuniones bajo el pretexto de religión,
no tenía ninguna fuerza;
porque nunca se vio que los Cuáqueros hicieran algo
más que adorar en sus reuniones religiosas,
aunque sí había evidencia de lo contrario con respecto
a los hombres de la Quinta Monarquía. Sin embargo,
era universalmente conocido que los Cuáqueros no tenían nada que ver con ese pueblo,
ni se unían a ellos en lo más mínimo.
Era además muy absurdo que el juez afirmara que dicha ley no tocaba consciencias,
porque era enteramente por razones de consciencia
que los Cuáqueros no frecuentaban el servicio público,
ni realizaban la liturgia de la iglesia de Inglaterra,
y mantenían reuniones religiosas por sí mismos.
Pero parece que el jurado quedó muy satisfecho con lo que les dijo el juez;
y tras obtener de esta manera su objetivo, leyó los nombres y les dijo:
"`¿Qué pueden decir a su favor para que la sentencia
de destierro no sea dictada contra ustedes?`"
Ellos dijeron: "`Somos inocentes y no hemos transgredido ninguna ley justa.
Pero si debemos recibir esa sentencia,
entregamos nuestros cuerpos libremente en las manos del Señor. ¡Sea hecha
la voluntad del Señor!`" "`¿No tienen nada más que eso?,`" dijo el juez.
"`Nada, sino que somos inocentes,`" replicaron los prisioneros,
"`y que no hemos hecho mal a nadie.`"
"`Entonces escuchen su sentencia,`" dijo el juez.
"`Serán transportados más allá de los mares a la isla de Barbados,
donde permanecerán siete años.`"

Luego fueron llamados al estrado Jeremiah Hern y Thomas Wood,
y fueron leídas sus acusaciones, de las que se declararon:
"`No culpables;`" y Jeremiah dijo que él no era una persona como la descrita por la ley,
pues estaba en contra de conspirar y planear insurrecciones.
El juez lo interrumpió diciendo:
"`Tú eres un hombre atrevido y tienes un patrimonio;`" he hizo que lo dejaran pasar.
A Thomas Wood le dijo: "`He oído hablar bien de ti, por tanto, considera lo que haces.
Siendo que tienes una buena reputación entre tus vecinos,
lamentaría que se te encontrara culpable, lo que me temo que te ocurrirá si vas a juicio.
Estoy dispuesto a mostrarte favor, y puede que a un hombre le vaya mejor que a otro.`"
Esto lo dijo pensando en Jeremiah, quien, por la malicia de un tal John King,
había sido falsamente presentado ante el juez.
Sin embargo, cuando Jeremiah demostró cómo había sido perjudicado,
el juez dijo que ambos participarían de su favor, si ellos así lo deseaban.
Su favor consistía,
en que él suspendería los procedimientos de la corte y les
daría tiempo hasta la siguiente sesión del tribunal,
para que lo consideraran mejor.
"`¿Qué dicen?,`" continuó,
"`¿quieren que se aplace su juicio hasta la siguiente sesión del tribunal?`"
A esto los prisioneros replicaron: "`Nosotros no hemos transgredido ninguna ley de Dios,
ni le hemos hecho mal a nadie.
Le dejaremos eso al tribunal, pero no lo queremos.`"
"`Si no lo quieren,`" dijo el juez, "`entonces no puedo hacerlo, ni lo haré.`"

Luego, fueron llevados al estrado otros tres prisioneros,
entre los que se encontraba un tal John Reynolds, quien,
según la declaración de los testigos,
había estado a menos de un metro de la puerta del lugar de reunión,
con su rostro de espalda a ella.
El juez dijo entonces.
"`Dios me libre de hacer algo que no sea correcto y justo según mi consciencia;
porque veo escrito sobre la pared delante de mí un
recordatorio de que no debo juzgar por el hombre,
sino por Dios.`"
Entonces,
volviéndose hacia el jurado les habló casi de la misma manera que había hecho antes,
con respecto a los otros cuatro prisioneros.
Y para inducirlos a declarar a Reynolds culpable (quien había sido capturado,
pero no había estado en la reunión), dijo así:
"`Supongan que un hombre es asesinado en una casa, y nadie vio al que lo asesinó,
pero un hombre es hallado saliendo de la casa con un cuchillo lleno de sangre en su mano;
es muy probable, que ese hombre sea el culpable del asesinato.
Así, pues,
aunque los testigos dicen que no vieron ni capturaron a este hombre en la reunión,
ellos juraron que estaba a menos de un metro de la puerta donde suelen reunirse,
y él ya ha sido capturado dos veces y está condenado en el expediente.
Mis señores, les dejo esto a ustedes; salgan.`"
Luego se llamó a un alguacil y se le encargó que proporcionara una habitación al jurado,
que no dejara que nadie les hablara, ni que tuvieran pan, bebida o candela,
hasta que presentaran su veredicto.

Entonces el jurado salió, se puso de acuerdo pronto,
y después de regresar dijeron que cuatro de los cinco prisioneros eran culpables,
y que el que había estado fuera de la puerta no era culpable.
De esta manera fue absuelto Reynolds,
pero los otros cuatro fueron llevados al estrado y el juez les preguntó:
"`¿Qué pueden decir para que no se dicte la sentencia de destierro contra ustedes?`"
La respuesta de ellos fue: "`Somos inocentes,
y no hemos transgredido ninguna ley justa de Dios o del hombre para merecer esa sentencia.
Dejamos todo al testigo de Dios en sus consciencias.`"
Entonces el juez dijo:
"`Ustedes han transgredido __esta__ ley (con el acta de la ley
delante de ellos) hecha por el rey y el Parlamento,
y ejecutada por nosotros sus ministros subordinados.
Si no es recta y justa, debemos responder por ello.`"
Entonces les preguntó a los prisioneros: "`¿Tienen algo más que decir?`"
A lo que ellos respondieron: "`Nada, sino que somos inocentes.`"
Entonces dijo: "`Escuchen su sentencia: Serán transportados más allá de los mares,
a la isla de Jamaica, que es una de las plantaciones foráneas del rey,
donde permanecerán siete años. Y ahora tengo esto que informarles,
que si alguno de ustedes le paga al tribunal cien libras,
antes de que se levante la sesión,
cada uno de ustedes será liberado y claramente absuelto de lo que ha pasado.
Y les mostraré este favor, no levantaré la sesión en este momento,
sino que me esperaré hasta la tarde.`"
Y así fue hecho, y cuando el tribunal se volvió a reunir,
el juez les preguntó a los prisioneros condenados si iban a pagar las cien libras,
pero al responder: "`No;`" el tribunal fue despedido pronto.

No mucho después de esto,
siete de ellos fueron llevados a bordo de un barco
para ser transportados a las Indias Occidentales;
pero asombrosamente, por los vientos contrarios y un clima tormentoso,
el barco se vio impedido de hacerse a la mar.
No sólo el capitán, cuyo nombre era Thomas May,
sino también sus hombres se inquietaron mucho ante esto;
porque creían que el cielo estaba contra ellos.
De hecho, los marineros amenazaron con abandonar el barco,
si el capitán no ponía a los prisioneros en tierra.
Y el propio capitán, considerando que habían permanecido mucho tiempo en los Downs,
y que más de una vez habían intentado zarpar,
pero no habían podido por los vientos contrarios,
finalmente resolvió (después de haberse retardado casi dos
meses) llevar a tierra a los hombres desterrados.
Y así lo hizo, dándoles un certificado del que tengo una copia en mi poder,
en el que hacía constar que ellos no se habían fugado,
sino que habían sido puestos en tierra por voluntad de él,
para lo cual dio entre otras razones,
que al ver las grandes adversidades con las que se había topado,
había concluido que la mano de Dios estaba contra él, y que por eso,
no se había atrevido a navegar con esos prisioneros,
porque los había encontrado hombres honestos, que no se merecían el destierro.
También afirmó,
que había una ley vigente de que ningún ciudadano
inglés podía ser transportado contra su parecer;
y añadió que sus hombres se habían negado a continuar
el viaje si él se llevaba a esas personas.
Él firmó este certificado y los dejó ir;
no mucho después de esto el barco zarpó con buen viento.
No encuentro que los hombres desterrados, quienes regresaron a casa,
hayan sido procesados por este motivo;
porque la sentencia contra ellos fue ejecutada hasta donde se pudo en ese momento,
y ellos no se habían opuesto a ella, sino que la habían sufrido.

Mientras tanto, la persecución no cesó; pero esto no desanimó a los llamados Cuáqueros.
Ellos continuaron valientes,
como he visto en muchas cartas enviadas por esa época a algunos de mis conocidos.
Uno dijo en un tribunal de justicia:
"`Estamos al servicio del Señor y no debemos abandonarlo.`"
Otro a quien se le había ofrecido liberarlo del destierro si pagaba cien libras dijo:
"`Aunque tuviera cien vidas que perder y pudiera redimirlas todas por cien peniques,
no lo haría.`" Pero nada de esto detuvo la violencia de los perseguidores,
hasta que una mano más pesada los alcanzó, como será relatado más adelante.

En los meses de octubre y diciembre muchos fueron condenados al destierro,
entre estos varias mujeres, de cuyos juicios no hablaré más que superficialmente,
porque si relatara todos los detalles, la descripción excedería por mucho mis límites.
Por lo tanto, sólo me referiré a unas pocas cosas.

El 13 de octubre, dieciséis de los llamados Cuáqueros fueron juzgados en Hicks`'s Hall,
en Middlesex, por la tercera transgresión, como la llamaban ellos.
El gran jurado, deliberando sobre la acusación, no pudo llegar a un acuerdo.
Entonces, al ser reprendidos por los magistrados,
uno de los hombres del jurado pidió saber,
por cuál ley debían encontrar ellos culpable a una persona,
cuando no había testigos presentes para testificar
que el crimen o el acto se hubiera cometido.
A esto el tribunal respondió,
que los expedientes de ellos testificaban que el crimen o acto se había cometido,
y que dichos expedientes eran un testigo suficiente sin el testimonio de ningún hombre.
El jurado, que ya había salido dos veces por este asunto, fue enviado una tercera vez,
y Edward Shelton, el secretario, dijo que saldría a ayudarlos y así lo hizo;
tras haberse hecho la amenaza,
de que si los miembros del jurado no los declaraban culpables serían multados.

Sin embargo, cuando regresaron respondieron: "`No hay veredicto.`"
Con lo cual, al descubrir que los miembros del jurado no habían respondido a sus fines,
los magistrados los separaron y los interrogaron uno por uno,
diciéndoles que lo único que debían considerar era si los Cuáqueros
se habían reunido en un número superior de cinco personas;
lo cual, según dijeron, mostraban sus expedientes.
Esto hizo que algunos de los miembros del jurado accedieran,
pero otros se mantuvieron firmes y señalaron que por un asunto
de consciencia no podían consentir lo que se les pedía. Pero después
de que la mayoría había accedido a los jueces (tras ser amenazados),
y otros habían sido fuertemente presionados, por una especie de fuerza,
la acusación fue finalmente aceptada.
Pero quedó demostrado cuán doloroso había sido este caso para algunos,
por la triste confesión de uno de los miembros del jurado,
quien para tranquilizar su consciencia publicó de
manera impresa un pequeño libro con el título,
__The Wounded Heart, or The Juryman`'s Offenses.__^
footnote:[__El Corazón Herido, o Los Delitos del Jurado.__]
En este libro el desaprobó abiertamente la acusación que fue inducido a aceptar por temor.
Y se informó que el secretario había dicho,
que él habría preferido pagar veinte libras antes que haberse tomado tantas
molestias para persuadir al jurado de que dictara un veredicto de culpabilidad.

Al día siguiente los prisioneros fueron llevados al estrado, y William Proctor,
de Gray`'s Inn, se sentó como juez en el tribunal.
Omitiré las preguntas y respuestas para efectos de brevedad, pero a una tal Hannah Trigg,
que se declaraba inocente,
se le preguntó cuántos años tenía. Ella afirmó que aún no tenía dieciséis años,
y uno de los magistrados no dudó en decir: "`¡Ella miente,
y yo creía que los Cuáqueros no mentían!`"
Pero pronto se vio que sólo lo estaba suponiendo,
porque según el certificado presentado por algunos
de los que estuvieron presentes en su nacimiento,
(que también fue difundido en forma impresa), se probó que ella,
siendo hija de Timothy Trigg,
había nacido en Londres el 20 del mes llamado agosto de 1649,
y que sólo tenía quince años, y que por eso, había sido procesada en contra de la ley.
Pero esta jovencita cayó enferma y murió en prisión,
después de que la sentencia de destierro fuera dictada contra ella;
sentencia que también fue pronunciada entonces contra otras doce personas,
entre las que se encontraban otras cuatro jóvenes.
También se condenaron a cuatro mujeres casadas a
un confinamiento de once meses en la prisión de Bridewell.
Cuando el juez pronunció esta sentencia estaba tan perturbado en su mente,
que ordenando que algunos fueran transportados a Virginia y otros a Barbados,
también condenó a algunos a ser enviados a La Española;
ante lo cual la gente se sorprendió bastante,
dado que La Española no estaba dentro de los dominios del rey de Inglaterra.

El 15 de octubre,
más de cuarenta de los prisioneros llamados Cuáqueros
fueron juzgados ante los jueces Hide y Keeling.
Considero innecesario mencionar todas las irregularidades
de este juicio (que no fueron pocas);
porque en lo que se refiere a las preguntas y respuestas,
y la dictaminación de la sentencia,
el lector se puede hacer una idea de ello por lo que ya se dijo del juicio en Hertford, etc.
Cuando se le pidió a una joven que se declarara culpable o no culpable, respondió:
"`Nunca en mi vida he sido capturada en un conventículo o reunión sediciosa.`"
A lo que el juez dijo: "`Pero, mujer, ¿no fuiste capturada en Bull and Mouth,
el 21 de agosto?`"
Ella respondió: "`Soy inocente ante los ojos de Dios y de toda la gente buena.`"
El juez no negó que eso fuera cierto, pero dijo: "`Te creo, mujer,
pero has transgredido una ley.`"
Ella replicó: "`En cuanto a la reunión en Bull and Mouth,
creo que he asistido trescientas veces, y si el Señor me permite la vida y la libertad,
no sé sino que puede que vaya unas cien veces más.`" Entonces el juez dijo: "`Mujer,
¿te declaras culpable o inocente; de lo contrario, debo dictar sentencia contra ti.`"
Ella respondió: "`Sea hecha la voluntad del Señor, soy inocente.`"
Sin embargo, esto no la ayudó y fue declarada muda, o __pro confesso,__^
footnote:[Es decir, como si hubiera confesado.]
en cuanto a los cargos contra ella en la acusación. Otros
que se quejaron contra lo irrazonable de los procedimientos,
fueron ridiculizados como insolentes.

Entre tanto,
había algunos entre los testigos que ni siquiera conocían a los prisioneros de cara,
lo cual era razón suficiente para refutar su testimonio; pero a pesar de las objeciones,
el asunto siguió adelante.
Porque aunque uno de los testigos declaró que la reunión
de la que habían sacado a los prisioneros era pacífica;
y uno de los prisioneros dijo que la ley estaba hecha contra las reuniones sediciosas,
y que no se había probado nada contra las reuniones de ellos,
el juez Keeling dijo que la ley estaba hecha para impedir ese tipo de reuniones,
porque bajo el color y pretexto de religión,
se podían llevar a cabo planes y conspiraciones.
Y cuando un prisionero dijo que él había estado en una reunión pacífica y piadosa,
y había recibido mucho consuelo ahí, el juez replicó: "`Eso es todo lo que queríamos.
Has confesado que estabas ahí, y aunque era una reunión pacífica, aun así era ilegal.`"
A otro de los prisioneros que alegó que la ley por la que el tribunal había actuado
era contraria tanto a la Carta Magna como a las antiguas leyes fundamentales de la tierra,
el juez Hide le respondió:
"`Si el rey y el Parlamento hicieran una ley para que dos jueces, sin un jurado,
pudieran condenar a muerte a un hombre por la tercera transgresión como delincuente,
sin el beneficio del clero, sería una buena ley,
y en concordancia con la Carta Magna y las leyes de la tierra;
y nosotros estaríamos obligados a ejecutarla.`"
Parece que este juez (quien no mucho después de esto fue repentinamente llamado
a comparecer a la sesión del Tribunal divino) era de la opinión de que,
dado que el poder legislativo residía en el rey y el Parlamento,
todo lo que ellos resolvían y decretaban debía ser considerado una "`buena ley.`"

Pero si mencionara todos los absurdos que encuentro en estos procedimientos,
¿cuándo terminaría? Es cierto que a veces se hacía un alarde de piedad,
porque el juez Keeling le dijo a dos jóvenes:
"`Sentimos que unas doncellas tan jóvenes sean engañadas así.`"
Pero debido a que ellas no prometieron ir a la iglesia pública,
aunque se declararon dispuestas a asistir al servicio divino,
fueron declaradas culpables.
Otro prisionero, a quien el juez Hide le preguntó si iría a la iglesia, respondió:
"`Si obtengo mi libertad, sin duda que iré a la iglesia.`"
Pero cuando resultó que no se refería a la iglesia establecida o nacional,
esta promesa no lo salvó. A un tal Richard Poulton, un muchacho de quince años,
que mediante un certificado demostró que aún no tenía dieciséis, y por tanto,
no era transgresor de la ley, se le preguntó:
"`¿Jurarías que no tienes dieciséis?`" A lo que él
respondió que no había sido educado para jurar.
Y cuando se le preguntó si prometía ir a la iglesia,
respondió que no podía prometer tal cosa.
Entonces fue devuelto con el resto que iba a ser sentenciado.

El 17 del ya mencionado mes, diecinueve personas, entre las que había algunas mujeres,
fueron condenadas al destierro,
y cuatro mujeres casadas fueron condenadas a doce meses de prisión en Bridewell.
Parece que ninguno de los jueces tenía la intención de pronunciar la sentencia,
y por lo tanto, le dejaron el asunto al registrador.^
footnote:[Persona con conocimientos jurídicos nombrada
por el alcalde y los concejales de la ciudad,
para "`registrar`" los procedimientos de sus tribunales
y las costumbres del despacho o de la ciudad.]
Entonces, pidiéndoles a los prisioneros que escucharan la sentencia del tribunal,
habló en voz tan baja que no se le podía oír,
lo cual hizo que uno de los prisioneros le dijera que debía hablar más alto,
porque ellos no lo podían oír. Pero como siguió hablando en voz baja como antes,
otros dos o tres prisioneros le dijeron que no podían oír lo que decía. A esto
el registrador respondió que no le importaba si lo podían oír o no,
y luego dijo: "`Escuchen su sentencia,
todos y cada uno de ustedes serán transportados más allá de los mares,
los hombres a Barbados y las mujeres a Jamaica,
que son dos de las plantaciones de su majestad,
y ahí permanecerán siete años.`" De esta manera se esforzaban
los perseguidores por deshacerse de los Cuáqueros;
pero, aunque la persecución era entonces muy intensa, ellos no desmayaban,
ni les faltaban muchos ayudantes, que tanto por el ejemplo como por palabras,
velaban y los animaban continuamente a la fidelidad.

Entre estos estaba Josiah Coale, quien por este tiempo, según se me ha contado,
estaba en prisión en Londres,
y que por escrito y por palabra exhortaba a sus compañeros creyentes a la constancia.
Porque cuando estaba bajo confinamiento, se dedicó a su pluma,
y les recomendaba a sus amigos que no abandonaran sus reuniones,
aunque tuvieran que pasar por grandes sufrimientos,
ya que era la buena voluntad de Dios dejar que la paciencia de ellos fuera probada.
"`Y,`" dijo él,
"`sabiendo que estas aflicciones vienen sobre nosotros con el permiso de Dios, ¡quién,
será entonces,
el que lo desafíe o trate de razonar con Él sobre asuntos de grande importancia,
dado que Su camino está escondido para el hombre!`" Él también
les señalaba que esto era permitido para probar su fe,
y que por eso, debían continuar osadamente y perseverar valientemente.
"`Y aunque nos acompañan grandes sufrimientos y aflicciones,`" decía él,
"`aun así mi corazón (alabado sea el Señor) no está turbado,
ni se ha apoderado de mí el temor, porque veo la intención del Señor en esto.`"
Y en otra carta decía así: "`Amigos, sepan esto,
que por el bien del resto de la semilla que aún no ha sido reunida,
voluntariamente ofrezco mi vida en las manos del Señor para que sea sacrificada;
y estoy listo y dispuesto a entregarla por el testimonio
de la bendita verdad que Dios me dio para testificar,
si soy llamado a ello.
Pues cadenas y aflicciones me acompañan diariamente, y puedo decir,
que nuestras vidas peligran todos los días. Así, pues,
que sus oraciones a Dios por mí sean,
que yo sea guardado hasta el final y termine mi testimonio con gozo,
y que en todas las cosas lleve gloria y honor al nombre del Señor, que es sobre todo,
bendito por los siglos de los siglos.`"
Este deseo cristiano lo obtuvo después, como será mostrado en su debido lugar.

Este fue un tiempo de sufrimiento y aquellos a quienes les tocó en suerte sufrir,
siguieron siendo valientes.
Otros no dejaron de exhortar al rey y al Parlamento para
que dejaran la persecución. Entre estos estaba William Bayly,
quien expresó la siguiente exhortación y seria advertencia contra la persecución:

[.embedded-content-document.epistle]
--

[.letter-heading]
Para el Rey y el Parlamento, etc.

[.salutation]
Amigos,

El Dios del cielo ha puesto en mi corazón escribir unas pocas palabras para ustedes,
en el temor y pavor de Su nombre, y en el consejo de Su propia voluntad,
con respecto a la obra que ustedes han emprendido contra Él y Su pueblo.
Este no es el fin ni la obra para la que el Señor les ha
concedido los lugares de gobierno y dominio en esta nación,
ni es el camino para que prosperen o prolonguen sus días en la tierra,
persiguiendo y afligiendo así a un pueblo inocente e inofensivo,
que es pacífico y camina en rectitud hacia Dios y el hombre,
y se esfuerza en todas las cosas por mantener sus consciencias sin ofensa.
Estos no tienen quien les ayude en la tierra sino sólo al Señor,
ni su reino es de este mundo,
sino que en verdad son los hijos y siervos del altísimo Dios,
a quienes Él ha reunido de entre los hombres para que sean
una especie de primicias para Él en esta época.
Nosotros somos de Él y no de nosotros mismos; Él nos ha traído y redimido para Él,
y sólo a Él hemos encomendado nuestra inocente causa,
y Él se ha comprometido a defenderla por nosotros ante todos nuestros adversarios.

Por tanto, amigos, despierten y abran sus ojos,
y vean qué gran revuelo y conmoción hay aquí en esta nación.
Se arrancan y se arrastran de sus pacíficas reuniones,
a una compañía de personas tiernas, inocentes e inofensivas--hombres,
mujeres y niños--que se reúnen en el temor y tierno amor de Dios,
sin ninguna perversa o mala intención hacia nadie,
sino más bien con buena voluntad y compasión hacia todos los hombres,
incluso nuestros peores enemigos, como el Señor nos da testimonio.
Sin embargo, estas son conducidas como ovejas al matadero y arrojadas en sucias cárceles,
prisiones y casas de corrección,
por gente ruda y brutal que ustedes han puesto a
trabajar por la autoridad que se les ha concedido,
al punto de que muchos de ellos han sufrido pacientemente la muerte,
y cuya sangre inocente ciertamente será requerida de las manos de ustedes.
Vean, pues, cómo en esta época,
los discípulos de Cristo Jesús son como ovejas y corderos en medio de lobos,
y como lirios entre espinos,
sólo por obedecer Sus mandamientos y adorar al eterno
Dios invisible en Espíritu y en Verdad,
según las Escrituras.

En verdad, si ustedes supieran y entendieran lo que han hecho contra ellos,
temblarían por haber causado que muchos de estos pequeños que creen en Cristo,
sufrieran tan gravemente,
porque Él dijo que "`...cualquiera que haga tropezar
a alguno de estos pequeños que creen en Mí,
mejor le fuera que se le colgase al cuello una piedra de molino,
y que se le hundiese en lo profundo del mar.`"
Y tan cierto, como que Cristo Jesús sufrió y se levantó de nuevo,
y que Dios vive y Lo resucitó de los muertos,
es que nosotros somos algunos de los pequeños que creen en Él,
los que en burla y escarnio son llamados Cuáqueros--como
también se podría llamar a Moisés,
a los profetas y a los apóstoles,
quienes en los días pasados temblaron y se estremecieron ante la presencia del Señor,
que es hoy como siempre ha sido, aunque los impíos no lo conozcan a Él,
ni conozcan Su poder.

Pero, ¿qué les diré? Si ustedes no quieren,
o no pueden creer nuestro testimonio fiel (o el testimonio de Dios a través de nosotros),
ni la inocencia de nuestra causa, ni la de nuestros sufrimientos,
tampoco creerían si alguno se levantara de los muertos y se los declarara.
Porque ustedes han tenido muchas visitas tiernas,
oportunas advertencias y gentiles reprensiones del Espíritu puro del Señor Dios,
tanto de Su testigo en sus consciencias,
como de Sus siervos y mensajeros fieles que les han
escrito y declarado en Su nombre y poder.
En cuanto a mí (que soy uno de los más pequeños de los miles de Israel),
de buena gana habría guardado silencio para con ustedes en este momento, pero el Señor,
a quien sirvo en mi espíritu, me ha encomendado advertirles una vez más,
por quienes he soportado una carga en la verdadera vista
y consciencia de la triste condición en la que se encuentran,
al ver que un día de densas tinieblas,
ira y angustia se precipita sobre ustedes proveniente del Todopoderoso.

Por tanto, no sean orgullosos ni rebeldes,
sino oigan y obedezcan la palabra del Señor. Porque
así dice el Señor Dios que hizo el cielo y la tierra:
"`Dejen en paz a mi pueblo inocente, y no lo toquen más como hasta ahora han hecho;
porque son Míos y Yo los he llamado, escogido y redimido.
Ellos son Mi tesoro que estoy preparando,
y mostrarán Mi gloria delante de los hombres del mundo entero.
Yo los he ungido, y los preservaré,
liberaré y coronaré con eterna salvación. Yo reprenderé
a los reyes y gobernantes por causa de ellos,
angustiaré a las naciones,
y destronaré de sus puestos a los poderosos que se levantan contra ellos, como he hecho.
Por tanto, dejen que Mi evangelio eterno tenga paso libre en estas naciones,
y no censuren ni aflijan más a Mis siervos y mensajeros,
a quienes Yo he escogido y enviado a predicar y a declarar
el camino de vida y salvación hasta los confines de la tierra;
antes bien, inclinen sus oídos y sus corazones ante el testimonio de ellos,
para que les vaya bien y prolonguen sus días. Porque el que los bendiga será bendito,
y el que los maldiga será maldito, y toda mano que se oponga a ellos se secará.

Pero si no oyen, sino que persisten y continúan como lo han hecho,
oprimiendo a Mi heredad y a Mi inofensivo pueblo,
y hacen guerra y oposición contra Mi poder y Mi verdad,
y de esa manera se colocan a sí mismos y colocan su poder contra Mí, el Dios vivo,
los haré caer repentinamente para asombro de las naciones, acortaré sus días,
y convertiré sus placeres en aullidos y lamentos, y luego,
la vergüenza y el desprecio cubrirán su memoria como un vestido.
Así obraré para la liberación de Mi semilla y nadie lo impedirá.`"

Por tanto, miren lo que están haciendo, y consideren sus caminos,
y cuál será el efecto de su obra.
Ustedes no son más que hombres, e hijos de los hombres;
sus alientos están en sus narices y sus vidas no son más que un vapor
que pronto se desvanecerá. Trabajan para
alimentar el fuego y producir viento,
el cual atiza la llama de eso que los consumirá y privará de toda felicidad para siempre.
¡Ojalá tuvieran corazones para considerarlo!
Porque cuanto más luchen contra el Señor y más opriman a Su pueblo,
más se multiplicará y más fuerte se hará. Y ustedes más
se debilitarán y sus obras serán como una pesada carga.

Pero amigos, ¿no han estado ustedes mismos bajo sufrimientos,
y no han sido llevados algunos de ustedes a países
o tierras extrañas por su "`causa`" (como fue llamada)?
En realidad, ¿no huyó y se refugió el propio rey en un árbol^
footnote:[Tras la derrota final de los monárquicos
en la Guerra Civil inglesa (3 de septiembre de 1651),
Carlos II se vio obligado a huir de los soldados del Parlamento,
y evitó ser descubierto escondiéndose en un roble del bosque de Boscobel.]
para salvarse de las manos de sus enemigos?
¿No fue eso una gran misericordia y liberación de Dios,
para esconderlo y preservarlo de aquellos que lo
perseguían? ¿Se han olvidado de estas cosas?
¿Recuerdan y aman Sus misericordias haciendo justicia y caminando humildemente con Él,
como Él lo requiere?
O, ¿se jactan en vana gloria, como si sus propios brazos lo hubieran hecho,
o sus propias fuerzas los hubieran liberado?

¿Dicen ustedes que los sufrimientos que pasaron por causa de los que se les oponían,
fueron injustos y desiguales?
Si dicen, "`lo fueron,`" entonces yo digo,
¿no es mucho más injusto y muy desigual a los ojos de Dios (y de toda persona sobria
que Le teme) que le infrinjan tan crueles sufrimientos a un pueblo inocente e inofensivo?
Porque ustedes encarcelan,
sofocan hasta la muerte en cárceles y agujeros asquerosos entre ladrones y asesinos,
y dictan sentencias de destierro contra un pueblo pacífico,
que no se opone a ustedes en lo más mínimo con ninguna fuerza externa,
ni se alojan los pensamientos de ello dentro de nuestros pechos,
como el Señor Dios lo sabe, quien nos ha llamado a la paz; sino todo lo contrario,
hemos buscado y buscamos el beneficio y felicidad de ustedes,
tanto en este mundo como en el venidero, el cual a su tiempo se manifestará a todos.

Déjenme repetirles, que por estos tratos irracionales e injustos,
los entendimientos de miles se han abierto más. La parte tierna y sobria de muchos
pueden sentir el peso y la carga de esta pena que ustedes han prescrito,
y de cómo persiguen y encarcelan tan afanosamente a tantas
personas inocentes y ciudadanas de esta nación;
y cómo dictan contra ellos la antinatural y cruel sentencia de destierro,
que separa esposos queridos y tiernos de sus queridas y tiernas esposas,
de sus tiernos niños y de sus pequeños e inocentes bebés. ¡Oh,
cómo quebrantan el corazón del manso de la tierra,
a quien Dios ha bendecido! ¿Qué ha sido de todas las promesas
de libertad que hicieron para las consciencias tiernas?
Ojalá el Dios Todopoderoso acorte las obras de ustedes en justicia,
y los días de opresión y crueldad por causa de Sus escogidos,
quienes claman a Él de noche y de día,
y dan a conocer Su nombre y poder hasta los confines de la tierra.

¡Oh, Dios justo, santo, puro y eterno!
Aunque te has acercado para juzgar,
eres desconocido para todo el que se sienta en tinieblas
y habita en el espíritu de enemistad contra Ti y Tu pueblo.
(Malaquías 3:5) Tu camino de vida y salvación está oculto para ellos, por tanto,
nos odian sin causa,
y nos tratan perversamente en las tinieblas de sus
mentes y en la ignorancia y dureza de sus corazones.
Por esto mi alma tiene compasión de ellos, y hasta te suplica, que si es posible,
sus ojos sean abiertos, sus corazones sean suavizados y sus espíritus humillados,
para que puedan ver lo que están haciendo en las tinieblas,
y considerar los efectos de sus obras que de seguro resultarán.
Y si Tus advertencias y gentiles visitaciones no los humillan,
entonces deja que Tus juicios los despierten, los abatan y los humillen,
para que puedan percibir algo de lo que Tú estás
haciendo en estos últimos días. Porque Tú has comenzado,
continuarás y perfeccionarás Tu obra; levantarás a Tu semilla,
y reunirás a Tus escogidos desde los cuatro vientos
y los traerás desde los confines de la tierra,
y dispersarás al orgulloso en las vanas imaginaciones de sus corazones.
Tú quebrantarás todo lo que se oponga contra Ti en este día de Tu gran poder,
en el que Te has levantado '`para terminar con la transgresión,
y para ponerle fin al pecado, y para traer y establecer justicia eterna;`'^
footnote:[Daniel 9:24]
para que el reino de este mundo se convierta en Tu reino,
como has prometido y estás cumpliendo ahora.
¡Gloria, honor, agradecimiento y alabanzas eternas sean dadas a Tu glorioso nombre,
por los siglos de los siglos!
Amén

Por tanto, amigos,
están y han sido advertidos una y otra vez por los mensajeros
y fieles siervos del Señor en amor por sus almas;
y ahora quedan sin excusa.
Por medio de esto pueden ver cómo se esfuerza el Señor por ustedes,
para que se arrepientan y sean salvos de la ira venidera, aunque ahora,
algunos de ustedes sientan poco de esto en sus propias consciencias.
Pero no contenderá Su espíritu con ustedes para siempre,
porque si no respetan lo que ha salido de sus propias bocas,
ni cumplen sus propias palabras y compromisos públicos en lo que es justo,
ni recuerdan Sus misericordias pasadas y presentes, ni Su paciencia para con ustedes,
sino que pisotean todo bajo el pie; yo digo, si es así y resuelven continuar,
entonces serán totalmente abandonados,
se endurecerán en extremo y crecerán en desesperada crueldad y opresión contra Dios,
Su verdad y Su pueblo.
Y luego (tan cierto como que Dios vive),
las inundaciones vendrán sobre ustedes y caerán a la manera de Egipto;
y el peso de los pavorosos juicios repentinamente los hundirán en el pozo sin fondo.

[.signed-section-closing]
Del siervo de Dios, amante del bienestar de todas sus almas,

[.signed-section-signature]
William Bayly

[.signed-section-context-close]
Escrito en el mes Diez de 1664, en Hartford.

--
