== Capítulo XVII

[.section-date]
1668--1670

[.chapter-synopsis]
* Convencimiento de W. Penn
* Qué trae la salvación
* G. Fox y esquire Marsh
* La infanticida penitente
* Expresiones de T. Loe al morir
* Disputa entre los Bautistas y los Amigos
* "`El Fundamento de Arena Sacudido`"
* Circunstancias que acompañaron la muerte de J. Coal
* Muerte de F. Howgill
* Excelente consejo para las jóvenes doncellas
* G. Fox en Irlanda
* Solomon Eccles
* Historia de G. Fox "`convertido`" al Presbiterianismo
* Matrimonio de G. Fox
* Margaret Fox en prisión
* Segundo conventículo
* Ley
* Informantes
* Enfermedad de G. Fox.

A principios del año 1668, William Penn, hijo del almirante sir William Penn,
empezó a mostrarse abiertamente partidario y afirmador
de la doctrina de los llamados Cuáqueros.
Él había sido educado en la Universidad de Oxford,
y después fue enviado por su padre a Francia,
donde vivió por algún tiempo (como me lo contó en
una ocasión) con el famoso predicador Moses Amyrault.
Después de una estancia considerable en ese reino regresó a su país,
y luego se fue a Irlanda por un tiempo,
donde asistía a una reunión de los llamados Cuáqueros.
Al ser interrumpida esta reunión por los magistrados,
W+++.+++ Penn (aunque estaba finamente vestido como un joven caballero y llevaba
una larga peluca) fue llevado a prisión junto con varios otros,
donde por la conversación con sus compañeros de prisión fue más
confirmado en esa doctrina que ya comprendía como verdadera.
Pero cuando se supo que él era hijo del almirante Penn, fue puesto en libertad pronto.
Este cambio afligió no poco a su padre,
pues había tenido la intención de educarlo para la corte,
pero ahora veía que su hijo mayor, que en ese momento tenía unos veinte años,
entraba en la sociedad del despreciado pueblo llamado Cuáqueros.
Se usaron varios medios para apartarlo de sus decisiones,
incluso le retiraron lo que cubría sus necesidades básicas;
pero todos los artificios y artimañas resultaron en vano, porque continuó firme.
W+++.+++ Penn conversaba mucho con Josiah Coale,
quien también se había pasado a los Cuáqueros en su juventud.

Este verano Stephen Crisp estaba encarcelado en Ipswich,
donde el número de amigos se había incrementado considerablemente por su ministerio.
Yo, junto con algunos otros amigos de Holanda,
lo visitamos en dicha prisión y lo encontramos alegre;
estaba tan contento como si estuviera libre,
porque sufría por el ministerio del evangelio,
y continuó predicando en prisión cuando sus amigos llegaban a visitarlo.

Paso por alto el viaje que hizo G. Fox este año a través de Inglaterra y Gales.
Él regresó a Londres en la última parte del verano,
donde con gran satisfacción lo escuché predicar varias veces ante una gran audiencia;
por este tiempo, las reuniones de los disidentes no eran perturbadas en Londres.
En realidad,
todo estaba tan tranquilo que a los llamados Cuáqueros se les permitió
construir un gran lugar de reunión en Gracechurch-street,
donde la primera vez que se celebró una reunión,
yo estaba presente y vi a G. Fox y lo oí predicar.

Mientras G. Fox estaba en Londres, pasó a visitar al esquire Marsh,
que ahora era juez de paz en Middlesex.
Cuando G. Fox llegó a su casa el esquire estaba cenando, y le agradó tanto,
que amablemente lo invitó a sentarse a comer con él, pero G. Fox se excusó cortésmente.
Había en ese momento varias personas de importancia a la mesa con el juez Marsh,
quien le dijo a una de ellas (un papista):
"`Aquí está un Cuáquero que no has visto antes.`"
A raíz de eso, el mencionado papista aprovechó la oportunidad para preguntarle a G. Fox,
si él reconocía el bautismo de niños. A esto G. Fox respondió
que no había ninguna Escritura para tal práctica.
"`¿Qué,`" dijo él, "`no para el bautismo de niños?`" "`No,`" replicó G. Fox,
"`reconocemos el único bautismo por el único Espíritu en un solo cuerpo,
pero no hay ninguna Escritura que hable de echar
un poco de agua sobre el rostro de los niños,
y que a eso se le llame bautizar y cristianizar.`"

Entonces el papista le preguntó si él no reconocía la fe Católica.
"`Sí,`" dijo G. Fox, "`pero ni el papa ni los papistas están en la fe católica;^
footnote:[La palabra __católica__ significa universal.]
ya que la verdadera fe obra por el amor y purifica el corazón.
Y si ellos estuvieran en esa fe que da la victoria,
por la que podrían tener acceso a Dios,
no les hablarían a las personas de un purgatorio después de la muerte,
ni tampoco usarían prisiones,
torturas o multas para obligar a otros a entrar en su religión;
pues esa no fue la práctica de los apóstoles ni la de los Cristianos primitivos,
pero los judíos y paganos incrédulos hicieron uso de esos medios para forzar.
Pero,`" continuó G. Fox,
"`viendo que eres un hombre importante y líder entre los papistas,
y que dicen que no hay salvación sino en su iglesia, quiero saber de ti,
¿qué trae la salvación en tu iglesia?`"

A esto el papista respondió: "`Una buena vida.`"
"`¿Nada más?,`" dijo G. Fox.
"`Sí,`" replicó el otro, "`buenas obras.`"
"`¿Es esta tu doctrina y principio?`"
preguntó G. Fox.
"`Sí,`" dijo él. Por tanto G. Fox replicó: "`Entonces ni tú, ni el papa,
ni ninguno de los papistas saben qué es lo que trae
la salvación.`" Entonces el papista le preguntó:
"`¿Qué trae la salvación en tu iglesia?`"
G+++.+++ Fox respondió:
"`Lo mismo que trajo la salvación a la iglesia en los días de los apóstoles, a saber,
la gracia de Dios; de la que la Escritura declara que trae salvación,
que se ha manifestado a todos los hombres,
que nos enseña a renunciar a la impiedad y a los deseos mundanos, y a vivir piadosa,
justa y sobriamente en este mundo.
Por esto, parece que no son las buenas obras, ni una buena vida lo que trae salvación,
sino la gracia.`"
"`¿Qué,`" dijo el Católico romano,
"`esta gracia que trae salvación se manifiesta a todos los hombres?`"
"`Sí,`" dijo G. Fox.
"`Niego eso,`" replicó el otro.
"`Todos lo que lo niegan,`" replicó G. Fox, "`son sectaristas, y no están en la fe,
gracia y verdad universales en las que estaban los apóstoles.`"
Entonces el papista empezó a hablar de la madre-iglesia,
lo que dio lugar a una gran discusión,
y G. Fox afirmó que si algún lugar externo tenía derecho a ser
llamado '`madre-iglesia`' por encima de las otras iglesias,
entonces Jerusalén tenía mucho más derecho a ello que Roma.
Pero en conclusión dijo: "`No hay otra madre-iglesia sino la Jerusalén celestial,
que es de arriba, y es libre, y es la madre de todos nosotros, como dice el apóstol.`"

Después de algunas otras conversaciones,
G+++.+++ Fox tuvo la oportunidad de ir con el mencionado Marsh a otra habitación y pedirle,
que ya que tenía la mayor parte de la administración de asuntos,
evitara la persecución de sus amigos tanto como le fuera posible.
Marsh no se mostró reacio a esto,
pero dijo que estaba en apuros en cómo actuar entre los Cuáqueros y algunos otros disidentes.
"`Porque,`" dijo, "`ustedes dicen que no pueden jurar, y los Independientes, Bautistas,
y los hombres de la Quinta-monarquía, dicen que tampoco pueden jurar.`"
A esto G. Fox dijo: "`Te voy a mostrar cómo distinguir:
los miembros de esas sociedades de las que hablas sí juran en algunos casos,
pero nosotros no podemos jurar en ningún caso.
Si alguien les robara sus vacas o sus caballos,
y les preguntaras si ellos jurarían que les pertenecen,
muchos de ellos lo harían de buena gana.
Pero si tú pruebas a nuestros amigos,
ellos no podrían jurar ni siquiera por sus propios bienes.
Por lo tanto, cuando les presentes el juramento de lealtad a alguno de ellos,
pregúntales si pueden jurar en algún otro caso; en cuanto a su vaca o a su caballo.
Lo cual, si ellos son realmente de nosotros, no pueden hacer,
aunque de buena gana darán testimonio de la verdad.`"
Entonces G. Fox le relató a Marsh de un juicio en Berkshire,
y de cómo había sido encarcelado un ladrón que le había
robado dos animales a uno de los llamados Cuáqueros.
Pero que alguien le había informado al juez que el
hombre que procesaba al ladrón era un Cuáquero,
y que al percatarse el juez de que el Cuáquero no juraría,
se había negado a escuchar lo que el hombre pudiera decir y en su lugar le había presentado
el juramento de lealtad y supremacía. Y cuando el cuáquero se negó a jurar,
dictó la sentencia premunire contra él, y dejó al ladrón en libertad.

Cuando el esquire Marsh oyó este relato, dijo que el juez era un hombre malvado.
Y por lo que G. Fox le había dicho,
entendió lo suficiente como para poder distinguir entre los Cuáqueros y otras personas.
Es verdad que los Bautistas en esos días profesaban
"`no jurar,`" pero cuando eran juzgados por ese motivo,
pronto desistían de esa parte de su profesión como
se mostrará ampliamente en lo que sigue.
Pero tanto ellos como los Independientes eran muy
reacios a prestar el juramento de lealtad,
principalmente, por un rencor que tenían contra el gobierno;
y esto era bien conocido por los que estaban en el liderazgo.
Pero los Cuáqueros estaban continuamente expuestos a la malicia de sus perseguidores,
y soportaban el impacto más duro de las leyes contra los disidentes.
Sin embargo,
el juez Marsh no dejaba de librar a los Cuáqueros
de la persecución tanto como estaba en su poder;
porque evitó que varios fueran condenados con la sentencia de premunire,
en aquellas partes donde él era el juez.
Y en aquellas ocasiones que no podía evitar enviar
a prisión a los que eran llevados delante de él,
los enviaba sólo por unas pocas horas, o por una noche.
Sin embargo, esta era una labor tan dura para él,
que al final le dijo al rey que él había enviado a algunos
de los Cuáqueros a prisión en contra de su consciencia,
y que no podía hacerlo más. También le aconsejó al rey que diera libertad de consciencia;
y fue tan útil para detener la violencia de la persecución,
que por esa época se oía poco acerca de disturbios en las reuniones.

En la primera parte de este año, si no me equivoco, sucedió un caso en Edmundsbury,
que no puedo dejar pasar.
Cierta joven, tras dar a luz un niño bastardo, lo mató,
por lo que fue enviada a prisión. Mientras estaba en la cárcel,
se dice que William Bennit, un prisionero por motivos de consciencia,
llegó a verla y le preguntó,
si a lo largo de su vida no había transgredido muchas veces su consciencia;
si no había sentido a menudo frenos secretos y reprensiones internas,
y si no se había turbado en su mente debido al mal cometido.
Esto lo hizo de una manera tan convincente,
que ella no sólo asintió a lo que le había mostrado,
sino que su discurso tocó tanto el corazón de la joven, que vio claramente,
que si no hubiera sido tan testaruda y desobediente a esas reprensiones internas,
con toda probabilidad no habría llegado a un lugar tan miserable
como aquel en el que se encontraba entonces.
Porque el hombre que no desea el conocimiento de los caminos de Dios y se aparta de Él,
queda desamparado y no puede guardarse del mal,
aunque sea un mal que expresamente hubiera aborrecido en grado sumo,
y hubiera dicho con Hazael: "`Pues, ¿qué es tu siervo, este perro,
para que haga tan grandes cosas?`"^
footnote:[2 Reyes 8:13]
La sana amonestación de W. Bennit obró de tal manera sobre la mente de la joven,
que ella,
que nunca había conversado con los Cuáqueros y era
completamente ignorante de la doctrina de ellos,
llegó a la comprensión de que "`la gracia de Dios que trae
salvación`" era lo que ella había resistido tan a menudo,
y que esa gracia no la había abandonado aún del todo,
y en ese momento la estaba haciendo consciente de la grandeza de su transgresión.

Esta consideración obró tan poderosamente en ella, que de ser una muy grave pecadora,
se convirtió en una verdadera penitente,
y con un corazón lleno de tristeza le clamaba al Señor que
se complaciera en no esconder Su rostro de ella.
Y continuando en este estado de humillación y sincero arrepentimiento,
y perseverando en la súplica, con el tiempo sintió una medida de alivio;
y prestando atención a las exhortaciones del mencionado Bennit,
finalmente alcanzó una segura esperanza de perdón
mediante la preciosa sangre del Cordero inmaculado,
quien murió por los pecados del mundo.

Ella dio pruebas manifiestas de este cambio en su juicio frente al juez Matthew Hale,
quien, habiendo oído de cuán arrepentida estaba, deseaba ansiosamente perdonarla,
e intencionalmente hizo que se insertara en la acusación,
que ella había cometido el hecho "`voluntaria y deliberadamente,`" para que,
aprovechándose de eso,
pudiera negar el cargo y así anular la acusación. Pero cuando se le preguntó
según la forma "`culpable o no culpable,`" ella rápidamente contestó:
"`Culpable.`"
Esto asombró al juez, por lo que le dijo,
que parecía que ella no había considerado debidamente lo que había dicho,
ya que no era fácilmente creíble que una persona como ella,
que tal vez había manejado bruscamente a su hijo,
lo hubiera matado "`voluntaria y deliberadamente.`"
Aquí el juez le abrió una puerta trasera para evitar la pena de muerte.

Pero en ese momento el temor de Dios había ganado tanto lugar en el corazón de ella,
que ninguna manipulación serviría; ninguna hoja de higuera podría servir como cubierta,
porque ella sabía entonces, que eso habría sido añadir pecado al pecado;
'`cobijándose con una cubierta, y no del Espíritu de Dios.`'^
footnote:[Isaías 30:1]
Por tanto, ella le indicó de manera clara al tribunal, que, en efecto,
ella había cometido el malvado acto intencionalmente para ocultar
así la vergüenza de haber dado a luz un niño fuera del matrimonio;
y que habiendo pecado tan gravemente y estando afectada entonces por el verdadero arrepentimiento,
no podía excusarse por ningún medio,
sino que estaba dispuesta a sufrir el castigo que exigía la ley;
y que por eso no podía sino reconocerse culpable,
ya que de otra manera no podría esperar el perdón de Dios.
Esta confesión libre y no disimulada, pronunciada con un rostro serio,
afectó tanto al juez que las lágrimas le corrían por el rostro, y muy entristecido dijo:
"`Mujer, nunca me había topado con un caso como este.
Tal vez tú, que no eres más que una joven y hablas tan piadosamente,
como una persona que ha sido golpeada en el corazón por el arrepentimiento,
habrías podido hacer mucho bien en el mundo.
Pero ahora me obligas que, __ex officio__,^
footnote:[Obligación bajo la que está alguien en virtud de su oficio.]
pronuncie la sentencia de muerte contra ti, ya que no permites ninguna excusa.`"

Manteniéndose firme en lo que ella había dicho, el juez pronunció la pena de muerte.
Y cuando más tarde ella llegó al lugar de ejecución,
pronunció un conmovedor discurso al pueblo, exhortando a los espectadores,
y especialmente a los jóvenes, a tener el temor de Dios ante sus ojos,
a prestarle atención a Sus secretas reprensiones por el mal,
para no afligir ni resistir al buen Espíritu del Señor;
pues al no ocuparse ella misma de hacerlo, la había hecho correr en el mal, y así,
continuando de maldad en maldad había llegado a esa funesta escena.
Pero dado que había confiado firmemente en la infinita misericordia de Dios,
y creía verdaderamente que sus pecados, aunque de tinte sangriento,
habían sido lavados por la sangre pura de Cristo, podía partir contenta de esta vida.
De esta manera predicó en el patíbulo la doctrina de los llamados Cuáqueros,
y dio pruebas conmovedoras de que su alma inmortal iba a entrar en el paraíso,
no muy diferente a la del ladrón en la cruz muchos siglos antes.
He sido informado de manera fehaciente,
por una persona que lo supo por boca de los que estuvieron presentes en la ejecución,
que en su petición a Dios le rogó que se complaciera en
dar una señal visible de que había sido recibida en Su favor.
Y que aunque en ese momento el día estaba nublado,
inmediatamente después de que fue colgada,
las nubes se abrieron un poco y el sol brilló por unos momentos sobre el rostro de ella,
y que luego el cielo continuó nublado.
Así, pues, en un estado de ánimo serio, sufrió la muerte que su crimen justamente merecía.

Este año murió en Londres Thomas Loe, un hombre con un excelente don,
que había trabajado celosamente en el ministerio del evangelio en Irlanda,
y que por medio de su predicación había atraído a muchos a la Sociedad de sus amigos;
entre otros a William Penn, a quien Thomas en su lecho de muerte le dijo:
"`Lleva tu cruz y permanece fiel a Dios;
entonces Él te dará una corona eterna de gloria que no te será quitada.
Ningún otro camino prosperará,
sino el camino en el que los santos hombres de la antigüedad caminaron.
Dios ha '`sacado a luz, la vida y la inmortalidad por el evangelio.`' ¡Gloria,
gloria a Él, porque Él es digno de gloria! ¡Su amor sobrecoge mi corazón; oh,
mi copa reboza! ¡Gloria a Su nombre por los siglos de los siglos!`"
No es de extrañar que estas palabras,
viniendo de alguien que estaba a punto de entrar a la eternidad,
sirvieran para confirmar aún más a William Penn en
esa doctrina que ya había abrazado como verdad.

En otro momento Thomas Loe les dijo a sus amigos que estaban al lado de su cama:
"`No se angustien,
el amor de Dios sobrecoge mi corazón.`" Y a George Whitehead y a otros les dijo:
"`El Señor es bueno conmigo; hoy Él me ha cubierto con Su gloria.
Estoy débil, pero me siento refrescado al verlos.
El Señor es bueno conmigo.`"
A otro amigo que le preguntó cómo estaba, le respondió:
"`Creo que estoy a punto de dejarlos, pero estoy tan bien en mi espíritu,
como puedo desear.
¡Bendigo al Señor!
Nunca he visto más de la gloria de Dios que la que he visto
este día.`" Y cuando se pensó que estaba a punto de partir,
comenzó a cantar alabanzas al Señor diciendo: "`¡Gloria, gloria a Ti para siempre!`"
Lo cual, afectó profundamente a los que estaban presentes, al oír cantar a un moribundo.
Y en este glorioso estado partió de esta vida el 5 de octubre.

Ahora bien, como este año la persecución en Londres se había detenido,
los de otras persuasiones a veces atacaban verbal
y amargamente desde el púlpito a los Cuáqueros,
y también los desafiaban a disputar.
William Burnet y Jeremy Ives, eminentes maestros Bautistas,
se habían enfrentado a George Whitehead este verano en Chertsey y en Horn, en Surry,
donde disputaron sobre la resurrección y el cuerpo de Cristo en el cielo.
Estos se esforzaron por denigrar a los Cuáqueros en esos puntos,
porque se limitaban al lenguaje de las Escrituras,
de las que los otros se habían apartado, desarrollando absurdos muy manifiestos.

Un tal Thomas Vincent, maestro Presbiteriano,
estaba muy molesto porque algunos de sus oyentes
se habían ido a la sociedad de los Cuáqueros;
y para hacerlos odiosos,
él y sus compañeros maestros los acusaban de sostener
una doctrina errónea con respecto a la Trinidad.
Esto era, principalmente, porque los Cuáqueros,
aunque creían en los "`tres que dan testimonio en el cielo, el Padre,
la Palabra y el Espíritu Santo,`"^
footnote:[1 Juan 5:7. Aunque los Amigos se oponían al concepto
de tres "`Personas distintas y separadas`" en la Deidad,
y no usaban con frecuencia la palabra "`Trinidad,`" (u otro término escolar que
no se encuentre en la Escritura) no se debía a alguna insatisfacción o desunión
con la doctrina bíblica del Dios Trino que da testimonio en el cielo,
la divinidad eterna del Señor Jesús, Su sacrificio propiciatorio en la cruz,
como la única ofrenda universal por los pecados de todo el mundo,
o cualquiera de Sus oficios para la salvación del hombre.
Los Amigos declaraban abiertamente su plena fe en todo esto,
y que buscaban alcanzar una experiencia más completa y práctica
de la obra transformadora de corazón que realiza la religión viva,
libre de los ritos externos e imposiciones de los hombres,
en los que creían que ellos mismos, así como otros, habían confiado indebidamente,
en lugar de haber insistido en pos de la virtud y del poder vivos del evangelio,
que redime el alma de la contaminación del pecado,
y le permite caminar en novedad de vida.
En una respuesta publicada a las acusaciones sobre este punto,
George Fox escribió lo siguiente:
{footnote-paragraph-split}
"`Nosotros
reconocemos al Padre,
al Hijo y al Espíritu Santo, como han declarado los apóstoles.
'`Y el Espíritu es el que da testimonio; porque el Espíritu es la verdad.
Porque tres son los que dan testimonio en el cielo: el Padre,
el Verbo +++[+++la Palabra+++]+++ y el Espíritu Santo; y estos tres son uno.
Y tres son los que dan testimonio en la tierra`' etc., lo cual nosotros reconocemos.
(1 Juan 5:7-8) Y ahora,
que nadie se ofenda porque no los llamamos por esos
nombres no escriturales de Trinidad y Tres Personas,
las cuales no son palabras de las Escrituras.
Por eso dicen falsamente que nosotros negamos al Padre, a la Palabra y al Espíritu Santo,
que son los Tres que dan testimonio en el cielo, etc.,
Tres que nosotros reconocemos con todo nuestro corazón, como lo hizo el apóstol Juan,
como lo hicieron todos los verdaderos Cristianos, y como lo hacen hoy.
Y si ustedes dicen que nosotros no somos Cristianos porque no llamamos al Padre,
al Hijo y al Espíritu Santo, la '`Trinidad,
personas distintas y separadas,`' entonces pueden concluir también que Juan no era Cristiano,
porque tampoco les dio estos nombres al Padre,
al Hijo ni al Espíritu Santo.
{footnote-paragraph-split}
Nosotros creemos,
con respecto a Dios el Padre, Hijo y Espíritu,
en concordancia con el testimonio de las Sagradas Escrituras,
el cual recibimos y abrazamos como la declaración
más auténtica y perfecta de la fe Cristiana,
al ser escrito por el Espíritu Santo de Dios que nunca erra: Primero,
que hay un solo Dios y Padre, de quien son todas las cosas.
Segundo, que hay un solo Señor Jesucristo,
por quien fueron hechas todas las cosas (Juan 1 y 17; Romanos 9),
que fue glorificado con el Padre antes de que el mundo fuera, que es Dios sobre todo,
bendito para siempre (Juan 17). Que hay un solo Espíritu Santo,
la promesa del Padre y del Hijo; líder,
santificador y consolador de Su pueblo (1 Juan 5). Y creemos además,
como las Sagradas Escrituras expresan sólida y suficientemente, que esos Tres son uno,
es decir, el Padre, la Palabra y el Espíritu.`"
--FLP]
no aprobaban expresiones que no se encuentren en las Sagradas Escrituras,
como la de "`tres personas distintas y separadas.`"
Sobre este tema se celebró una disputa en la casa
de reunión de los Presbiterianos en Londres,
entre el mencionado Vincent por un lado, y George Whitehead por el otro.
Lo que Vincent y sus hermanos propusieron primero,
fue la acusación de que los Cuáqueros sostenía "`doctrinas condenables.`"
George Whitehead negando esto,
solicitó dar al pueblo información sobre los principios de sus amigos;
pero en lugar de ello, Vincent planteó esta pregunta:
"`¿Reconoces tú una sola Deidad que subsiste en tres personas distintas y separadas?`"
Al decir Whitehead y los que estaba con él que esa no era una doctrina de las Escrituras,
formuló este silogismo.

[.syllogism]
* Hay tres que dan testimonio en el cielo; el Padre, la Palabra y el Espíritu Santo: y estos tres son uno.
* Estos son, o bien tres manifestaciones, tres operaciones, tres sustancias, o tres algo más, además de subsistencias.
* Pero ellos no son tres manifestaciones, tres operaciones, tres sustancias, ni tres algo más, además de subsistencias. Ergo, ellos son tres subsistencias.

G+++.+++ Whitehead rechazó esos términos porque no se encuentran en las Escrituras,
y no se pueden deducir de 1 Juan 5:7,
el lugar que Vincent citó. Y por eso pidió una explicación de los términos,
puesto que Dios usualmente no envuelve Sus verdades en metafísica pagana,
sino en un lenguaje sencillo.
Pero, dijera lo que dijera,
no pudo obtener una mejor explicación que "`personas`" distintas,
o "`modos de sustancia.`"
G+++.+++ Whitehead y William Penn (que también estaba ahí) alegaron varios
lugares de las Escrituras que mostraban la completa unidad de Dios.
Entonces W. Penn negó la proposición menor del silogismo de Vincent: "`Porque,`" dijo él,
"`ninguna sustancia puede tener tres subsistencias
'`distintas,`' y todavía conservar su propia unidad;
porque cada subsistencia debe tener su propia sustancia; de modo que,
'`tres subsistencias distintas`' requerirán tres distintas sustancias o seres;
en consecuencia, tres Dioses.
Porque si la divinidad infinita subsiste en tres formas separadas o distintas,
entonces ninguna de ellas es una subsistencia perfecta y completa sin las otras dos;
así que Dios debe tener partes y hay algo finito en Él; o si hay algo infinito en Él,
entonces debe tener tres subsistencias distintas e infinitas; y, ¿qué es esto,
sino afirmar tres Dioses, ya que nadie es infinito sino Dios?`"

Después de varias palabras por ambas partes, G. Whitehead,
para acercar esta extraña doctrina a la capacidad de la gente,
comparó sus "`tres personas separadas`" con tres apóstoles,
y dijo que no entendía cómo Pablo,
Pedro y Juan podían ser tres personas y todavía ser un apóstol.
Ante esto, un tal Maddocks, uno de los ayudantes de Vincente,
formuló este extraño silogismo:

[.syllogism]
* El que con desdén y reproche compara nuestra doctrina de la bendita Trinidad del Padre, Hijo y Espíritu, uno en esencia pero tres en personas, con tres hombres finitos como Pablo, Pedro y Juan, es un blasfemo.
* Pero tú, George Whitehead, lo has hecho.
* Ergo, tú eres un blasfemo.

Una conclusión precipitada, pero dejo que el lector juicioso determine cuán sólida es.
No tengo interés en adentrarme más en esta disputa,
ya que las partes de ambos lados se fueron insatisfechos.
Porque Vincent no había podido probar que la doctrina de los Cuáqueros era condenable,
como había afirmado,
sino que se había dejado llevar por la pasión. Y
a los de su propia sociedad les dijo desde el púlpito,
que él prefería que fueran a un prostíbulo a que frecuentaran las reuniones de los Cuáqueros,
debido a sus doctrinas erróneas y condenables.
Y señalando hacia la ventana añadió: "`¡Si hubiera una copa de veneno allí,
preferiría tomarla, que sorber sus doctrinas condenables!`"
Pero este intempestivo celo no le sirvió de nada,
porque dio oportunidad a que algunos de sus oyentes
indagaran en las doctrinas de los Cuáqueros,
y así algunos llegaron a convencerse de su veracidad.

Ahora bien, como la mencionada disputa hizo un gran ruido en Londres,
William Penn publicó un libro con el título, [.book-title]#The Sandy Foundation Shaken#,^
footnote:[El Fundamento de Arena Sacudido.]
en el que explicaba los puntos disputados y defendía su
posición con buenas razones y con las Sagradas Escrituras.
Pero incluso este libro, que él mismo distribuyó, causó tal revuelo,
que se habló en contra,
y no mucho después W. Penn fue encarcelado en la Torre de Londres;
y algunos pensaron que a sabiendas de su padre, tal vez para prevenir algo peor.

Esto sucedió en la última parte del año, época en que Josiah Coale cayó enfermo,
lo que lo sacaría del escenario de esta vida.
Él se había estado deteriorando por mucho tiempo, y sin embargo, no escatimaba su voz,
sino que a menudo la levantaba predicando y orando;
así gastó tremendamente su fuerza natural, aunque todavía estaba en una edad floreciente.
En realidad, su vida y su gozo era declarar el evangelio y proclamar la palabra de Dios,
para lo cual tenía una excelente habilidad; y cuando le hablaba al mundo impío,
aparecía una terrible seriedad en su semblante y
sus palabras eran como un martillo y una espada afilada.
Pero aunque era un "`hijo del trueno,`" muchas palabras placenteras fluían de
su boca como un apacible arroyo para la consolación y alivio de las almas piadosas.
¡Oh, cuán conmovedoramente lo oí orar cuando,
transportado y arrebatado en alguna medida por el Espíritu,
humildemente le suplicaba a Dios que se placiera en alcanzar a los de duro corazón,
sostener a los piadosos y preservarlos firmes! ¡Y con qué voz encantadora
y melodiosa entonaba las alabanzas al Altísimo en sus oraciones en público!
Pero su obra ya estaba hecha, él había finalizado su travesía,
y el tiempo para descansar de sus obras había llegado.

Aunque estaba débil, su espíritu varonil y su gran valor lo sostuvieron por algún tiempo.
Pero su enfermedad, que parecía ser una especie de tuberculosis,
al final se agravó tanto, que se vio obligado a permanecer en casa varias semanas.
Más tarde, al recuperarse un poco, salió de nuevo y asistió a una reunión en Londres,
donde vi su semblante muy diferente al que solía tener,
porque claramente manifestaba su indisposición corporal.
Sin embargo,
predicó con un celo piadoso y sus saludables exhortaciones
fluían como un río de sus labios,
que parecían ser tocados por un carbón del altar del cielo mientras
predicaba el evangelio para la edificación de sus oyentes.
En realidad, levantó su voz de nuevo a tal grado, que a juzgar por ello,
uno habría podido suponer que estaba bastante restablecido.
Pero como la causa de su enfermedad no había sido quitada,
pronto le fue necesario permanecer en casa otra vez.
Entonces, su fuerza natural se agotó tan rápidamente y decayó tanto,
que se empezó a esperar su muerte, la cual tomó lugar no mucho después.

Poco antes de que muriera,
G+++.+++ Fox fue a verlo y le preguntó si tenía algo que escribirles a los amigos en Inglaterra.
Pero J. Coale le indicó que no tenía nada que escribir,
sólo deseaba que su amor les fuera recordado a ellos,
y quiso que G. Fox orara pidiéndole a Dios que su paso fuera fácil,
porque sentía que su fin se aproximaba.
Tras cumplir con este deseo y viendo que parecía cansado,
G+++.+++ Fox le pidió que fuera a acostarse en la cama, lo cual J. Coale hizo.
Pero al encontrarse, según parecía, más incómodo ahí,
con la ayuda de sus amigos se levantó de nuevo y se sentó a un lado de la cama,
con sus amigos a su alrededor.
Entonces, al sentirse tan vívida y poderosamente levantado, les habló de esta manera:
"`Bien, amigos, sean fieles a Dios y tengan un ojo puro hacia Su gloria.
No busquen nada para el yo ni para la gloria de ustedes; y si algo de eso se levanta,
júzguenlo por el poder del Señor Dios, para que así sean limpios ante Sus ojos,
y puedan hacer lo que es correcto según Su testigo en todas las personas; entonces,
tendrán la recompensa de vida.
Por mi parte, he caminado con fe en el Señor;
y hasta aquí he acabado mi testimonio y tengo paz con el Señor.
Su majestad está conmigo y Su corona de vida está sobre mí. Exprésenles,
pues, mi amor a todos los amigos.`"
Entonces dejó de hablar; y un rato después le dijo a Stephen Crisp: "`Querido,
mantente humillado en la semilla santa de Dios, y esa será tu corona para siempre.`"
Después de una breve pausa dijo: "`Un ministro de Cristo debe andar como yo he andado.`"

Poco después de esto se desmayó, y estando sostenido por sus amigos,
partió en sus brazos sin el menor suspiro o gemido,
sino como alguien que cae en un dulce sueño; y lleno de consuelos celestiales,
pasó de esta vida mortal a la inmortal,
tras alcanzar los treinta y cinco años y dos meses de edad,
y habiendo predicado el evangelio alrededor de doce años. Viajó
mucho por las Indias Occidentales y soportó grandes dificultades,
y mientras trabajaba en el ministerio se encargó de sus propios gastos,
entregándose libremente a gastar sus bienes en el servicio
del Señor. Y aunque atravesó muchas persecuciones,
encarcelamientos y otras adversidades, no le temía al peligro,
sino que siempre fue valiente.
Continuó soltero para poder trabajar más libremente en la cosecha celestial,
y muchos se convirtieron por su ministerio.
Vivió para ver cumplido el deseo de su corazón,
porque cuando fue alcanzado por primera vez por el Espíritu de Verdad,
estando bajo la consciencia de sus anteriores transgresiones,
le clamó al Señor liberación diciendo con David: "`Si Tú, oh, Dios,
me ayudas completamente, entonces les enseñaré a los transgresores tus caminos,
y los pecadores se convertirán a ti.`"
Viajó por largo tiempo en estado de aflicción,
aunque naturalmente era de carácter alegre;
y habiendo pasado finalmente la senda de dolor,
era más capaz de consolar a los afligidos de Sion.
La iglesia estaba muy consciente de esta gran pérdida,
y tengo razones para pensar que su cuerpo fue acompañado
a la tumba por más de mil de sus amigos,
entre quienes me encontraba yo entonces; pues su entierro,
al ser muy público y bien conocido, atrajo hacia sí la mirada de muchos espectadores.
Que nadie piense que es extraño que me haya extendido
en la vida y muerte de este buen hombre;
porque él, en realidad, era muy querido para mí,
y todavía tengo fresco en mi memoria su trato amable; porque la piedad de mi madre,
a quien él había visto en Inglaterra,
hizo que me diera señales de la estima que le tenía a su memoria.
Y sus excelentes dones me afectaban de manera tal,
que estaba ansioso de ir a cualquier reunión,
de la que tenía noticia que era posible que él asistiera.
Yo en verdad, veía en él algo tan extraordinariamente valioso,
que le profesaba un respeto muy reverente, y más aún,
porque la diferencia de nuestras edades me privaba de una comunión más familiar con él.

El veinte del mes llamado enero de 1669, Francis Howgill murió en la prisión de Appleby,
después de una enfermedad de nueve días,
donde había permanecido más de cinco años. Durante
su enfermedad permaneció en perfecto entendimiento,
y oró con frecuencia muy fervientemente,
pronunciando muchas expresiones consoladoras para gran refrigerio de los que lo rodeaban.
Varias veces se le oyó decir que estaba contento de morir,
y alababa a Dios por los muchos y dulces placeres y refrescamientos
que había recibido en su lecho de muerte en la prisión,
donde estaba acostado,
perdonando libremente a todos los que habían tenido que ver con su confinamiento.
Y dijo: "`Este fue el lugar de mi primer encarcelamiento por la verdad,
aquí en este pueblo, y si es el lugar donde debo rendir el cuerpo, estoy contento.`"
Varias personas importantes, habitantes de Appleby, como el alcalde y otros,
fueron a visitarlo; y algunos de estos oraron que Dios hablara paz a su alma,
ante lo que él replicó: "`Él lo ha hecho.`"

Unos dos días antes de su partida,
estando acompañado por su esposa y algunos de sus amigos, les dijo: "`Amigos,
con respecto a las palabras, no deben esperar mucho más de mí;
tampoco hay gran necesidad de ello,
ni de hablarles de asuntos de fe a ustedes que ya están convencidos.
Únicamente recuérdenles mi tierno amor a todos los amigos que pregunten por mí;
porque siempre he amado bien a los amigos, o a cualquiera en el que apareciera la verdad.
En verdad, Dios reconocerá a Su pueblo, como lo ha hecho hasta ahora,
y como lo hemos atestiguado nosotros diariamente.
Porque tan pronto como hacían el acto de destierro,
para gran sufrimiento de muchos buenos Amigos, el Señor suscitaba enemigos contra ellos,
mediante lo cual les quitaba la violencia de sus manos.
Repito, Dios reconocerá a Su pueblo, es decir, a todos aquellos que son fieles.
Y en cuanto a mí, estoy bien y estoy contento de morir, no le temo para nada a la muerte.
Pero había algo en mi corazón que intenté escribirle a George Fox y a otros, es decir,
algo que he observado, a saber, que esta generación pasa rápidamente.
Hemos visto durante estos pocos años,
que muchos buenos y preciosos amigos nos han sido quitados; por lo tanto,
los Amigos tienen gran necesidad de vigilar y ser muy fieles,
para que podamos dejar un buen aroma (no uno malo) a la siguiente generación,
porque vemos que el tiempo que cualquiera de nosotros
tiene para permanecer aquí es corto.`"

Unas pocas horas antes de su partida,
llegaron a visitarlo algunos amigos de otros lugares,
a quienes les preguntó sobre su bienestar,
y oró fervientemente con muchas expresiones celestiales,
que el Señor por medio de Su gran poder los preservara de
todas aquellas cosas que pudieran manchar y contaminar.
Entonces su voz empezó a fallar por causa de su gran debilidad,
pero un poco después recuperó algo de fuerza y dijo:
"`He buscado el camino del Señor desde mi niñez,
y he vivido inocentemente entre los hombres;
y si alguien pregunta con respecto a mis últimos momentos,
háganle saber que muero en la fe en la que viví y por la que sufrí.`"
Después de estas palabras dijo otras en oración a Dios,
y dulcemente terminó sus días en paz con el Señor, a los cincuenta años de edad.

F+++.+++ Howgill dejó un buen nombre tras de sí entre todos los que lo conocieron.
Algún tiempo antes de su enfermedad,
considerando este estado mutable y encontrando en sí mismo cierta decadencia de la naturaleza,
hizo su testamento, en el que,
como su amor hacia los hermanos con quienes había
trabajado en el ministerio era muy tierno,
le dejó a cada uno de ellos un recuerdo de su amor;
también les dejó un regalo a los amigos pobres donde él vivía. Porque
aunque sus bienes muebles habían sido confiscados para el rey para siempre,
la confiscación de sus bienes inmuebles sólo había sido de por vida; de modo que,
al tener algo que dejar de ahí, pudo disponer de ellos mediante su testamento.

Durante su encarcelamiento no dejó de consolar y fortalecer a sus hermanos por escrito,
realizando con su pluma lo que no podía hacer de palabra.
También defendió su doctrina contra los que se oponían a ella; y entre otras cosas,
escribió un extenso tratado contra los juramentos,
contradiciendo la opinión de los que consideran lícito jurar bajo el evangelio.

Unos dos años antes de su muerte,
le escribió una epístola de guía y consejo (como
su última voluntad y testamento) a su hija Abigail,
una niña a la que amaba mucho,
que había nacido en un tiempo de profundas pruebas y angustias para él,
y que sin embargo, por la bondad del Señor había pacientemente atravesado.
Por eso él llamó a su niña Abigail,
que significa '`el gozo del padre.`' En este testamento le da las
siguientes instrucciones para la conducta futura de su vida:

[.embedded-content-document.letter]
--

[.salutation]
Abigail, querida hija,

Esto es para que lo observes, lo guardes y le prestes atención todos los días de tu vida,
para que regule tu vida y tu conducta en este mundo;
para que tu vida sea feliz y tu fin bendito,
y para que Dios pueda ser glorificado por ti en tu generación. Estas cosas
te las entrego y te las aconsejo para que las observes siempre,
siendo que son las únicas importantes que tengo para ofrecerte,
las que aprecio más que las riquezas externas.
Ojalá lo hagas así también, y observes y guardes mis dichos;
te encarezco delante de Dios, y por la venida de nuestro Señor Jesucristo,
que observes lo que te digo.
Estoy movido por el Señor a dejarte esto a ti, en tierno amor y afecto hacia ti, mi hija,
para que el Señor te dé Su bendición,
y haga prósperos tus caminos y que tu último fin sea paz.

Ante todo, conoce esto: Yo no nací en grandes posesiones,
ni heredé grandes cosas en este mundo;
pero el Señor siempre me ha provisto de lo necesario y suficiente,
y ha sido como un Padre tierno para mí,
porque mi corazón ha confiado en Él y amado los caminos de justicia desde
niño. No tengo una gran porción de las cosas de este mundo para darte;
sin embargo, de lo poco que tengo, con lo que Dios me ha bendecido,
te daré algo que no mencionaré aquí, pero lo sabrás a mi muerte.
No obstante, te encomiendo a tu querida madre, quien, confío,
proveerá lo suficiente para ti;
para quien mi corazón ha sido recto delante del Señor. Cuando me casé con tu madre,
ella tenía una porción y una dote suficientes, que no deseo disminuir ni menoscabar;
y todo lo que era de ella (si le place al Señor que
yo muera antes que ella) se lo dejo libremente,
como fue siempre mi intención y propósito, lo cual no ha cambiado ni cambiará,
por la fuerza de Dios--como sólo Dios conoce y me da testimonio.
Esto será manifestado a todos en su debido tiempo,
como ya se ha manifestado delante del Señor,
quien ha estado conmigo en medio de muchas dificultades, pruebas y sufrimientos,
y ha levantado mi cabeza sobre mis adversarios, porque sólo he confiado en Su Nombre;
el cual en todo momento lo he encontrado ser un refugio,
y un pronto auxilio en tiempos de necesidad; y así será para ti,
si temes Su Nombre y confías en Él siempre.

Y ahora, querida niña, escucha las palabras de mi boca y atiende mi consejo.
Reflexiona en estas cosas que te dejo para que las observes,
a fin de que tus días se prolonguen sobre la tierra, y sean bendecidos y cómodos para ti,
y un honor para Dios en tu generación.

Tú naciste y viniste al mundo en un tiempo de profunda
prueba y dificultad para mí--no del Señor,
quien siempre me ha hablado paz y me ha sostenido--sino
por causa del adversario de la humanidad,
quien siempre busca devorar lo bueno en todos,
y es el sembrador de discordia y maldad en los corazones de los que no le temen al Señor,
ni permanecen en Su consejo.
Él entra en estos, según se le da lugar para sus tentaciones, y ahí corrompe la mente.
Pero aunque entonces había una gran prueba sobre mí,
el Señor guardó mi corazón en rectitud hacia Él y me dio mucha paciencia.
Y aunque la tierra había sido quitada y echada al mar,
y todas las cosas externas habían sido confundidas,
y la naturaleza había cambiado su curso, con todo,
el Señor me dio la resolución y la fuerza para no angustiarme ni ofenderme,
porque Él me sostenía. En ese tiempo naciste tú, y por eso te llamé Abigail,
que significa "`gozo o deleite del padre;`" porque en ti
fui consolado y mi angustia presente fue mitigada.

Ahora, mi consejo para ti es que te acuerdes de tu Creador en los días de tu juventud,
y le temas al Señor en tu juventud,
y aprendas a conocerlo y a servirle todos tus días.
Busca primero el reino de Dios y su justicia.
Su reino no está lejos de ti; está dentro de ti.
Este consiste en vida y poder, y permanece en la rectitud, verdad, equidad, justicia,
misericordia, longanimidad, paciencia, amor, luz y santidad; este es su ser y su centro.
Por tanto, no busques el "`he aquí`" o el "`he ahí`" fuera de ti,
en esta o aquella evidencia externa; porque muchos buscan ahí y nunca lo encuentran.
Pero busca, y hallarás; espera, y recibirás.

Si preguntas,
"`en qué debo buscar,`" o "`en qué debo esperar,`" y "`cómo debo buscar,`" te informo:
Debes silenciar todos tus propios pensamientos,
y debes volver tu mente a ese don que es puro, santo y bueno dentro de ti.
Busca y espera en eso, en la Luz de Jesucristo con la que eres alumbrada,
y te muestra cuando haces mal, te refrena y te reprende.
Préstale atención a eso, y te mostrará los movimientos y pensamientos malvados;
y en la medida que lo ames,
eso también los someterá y te preservará fuera del mal para el tiempo por venir.

Porque aunque tú hayas nacido en el mundo como una criatura racional,
aun así debes nacer de nuevo y ser hecha una __nueva criatura__, de lo contrario,
no podrás entrar en el reino de Dios.
Debes conocer a la Semilla del reino en ti misma (de la
que debes nacer) y ser formada de nuevo a la imagen de Dios.
Te he dicho que Dios la ha sembrado en ti--un grano de ella, una medida de ella,
una porción de ella, una medida de Luz y Verdad, de justicia y santidad.
Mantente vuelta a ella en tu mente; ámala y sentirás al Padre Celestial obrando en ti,
y creándote de nuevo para vida por medio de Jesucristo, quien te ha alumbrado.
Y sentirás el poder del Señor fortaleciéndote en tu poquito,
y haciéndote crecer en la Semilla inmortal de Su reino,
y dejando atrás y superando todo mal,
para que mueras diariamente al mal y no tengas placer en él, sino en el Señor,
y en Su bondad y virtud derramadas en tu corazón,
lo cual gustarás y sentirás en el interior, y tendrás gozo y consuelo en ello.

Ama al Señor con tu corazón y con tu alma, es decir,
Al que te hizo y te dio (y a todas las otras cosas en el cielo y en la tierra) un ser.
Espera el conocimiento de Él en ti misma; Él no está lejos de ti,
sino cerca de ti y de todos que lo invocan con corazón recto.
Pregunta a tu querida madre y ella te informará; ella lo conoce a Él,
y conoce el camino de vida y paz; por tanto, escucha su instrucción.

Dios es Espíritu, es un Espíritu puro de luz, vida y poder.
Él es el que escudriña el corazón y te muestra cuando haces mal, o piensas mal,
o hablas mal; y les muestra a los hombres y a las mujeres sus pensamientos.
Eso que muestra el mal, es bueno; y eso que muestra la mentira, es Verdad.
Esto está en tu interior;
préstale atención. En las Escrituras se le llama Espíritu de Dios; cree en Él, ámalo,
y Él vivificará tu corazón para el bien y someterá el mal.
Él es tu maestro cercano; ámalo.
Si actúas contrario a Él, te condenará; por tanto,
préstale atención a este Espíritu de Verdad y Él te alumbrará y te avivará.
Él abrirá tu entendimiento y te dará a conocer qué es Dios,
y a hacer lo que es bueno y aceptable ante Sus ojos.
Este Espíritu nunca se equivoca, sino que saca de todo error e introduce en toda verdad.

¡Oh, Abigail, cree mis palabras!
Ellas son las palabras de Dios y Verdad.
No seas descuidada, sino de mente sobria en tu juventud.
Espera en el Señor en el interior y escúchalo.
Dios es Luz inmortal, Vida inmortal, Verdad inmortal; un Espíritu perpetuo y eterno.
Él habla espiritual e invisiblemente dentro de los
corazones y consciencias de hombres y mujeres.
Escucha lo que Él dice y obedece Su voz, y tu alma vivirá. Teme ofenderlo,
o pecar contra Él; porque la paga del pecado es muerte.
Por tanto, aprecia Su amor en tu juventud y en tus años tiernos.

Lee las Escrituras y los libros de los Amigos,
y presta atención a lo que lees para obedecerlo, hasta donde entiendas.
Ora con frecuencia al Señor y pídele que te dé Su conocimiento
y abra tu entendimiento en las cosas de Su reino.
Escudriña tu corazón a menudo con la Luz de Cristo en ti;
manifiesta y lleva tus obras a la Luz, para que puedan ser probadas.
Examínate a ti misma, para ver cómo está el caso entre el Señor y tú;
y si ves que estás equivocada, humíllate y arrepiéntete.
Vuélvete a Él, y Él te mostrará misericordia; y luego ten cuidado en el tiempo por venir,
para que no corras al mismo mal de nuevo.
Guarda tu corazón limpio; vigila contra el mal en ti en esa luz que lo muestra;
en ella hay poder y así tienes poder para vencer todo mal.

Querida hija, no te ocupes de los placeres del pecado que sólo duran un momento,
y su fin es miseria; sino niégalos y mantén sometida tu voluntad y afectos.
Así tu mente no tendrá placer en el mal, sino sólo en el bien;
y sentirás a la Semilla inmortal brotando en ti,
a La que le pertenecen la paz y el amor de Dios.

¡Oh, Abigail, estas cosas son grandes y de peso, y no deben ser menospreciadas!
Acompáñate siempre con los que le temen al Señor,
que Le temen y Lo adoran en espíritu y verdad, y lleva una vida santa e irreprochable.
No los niegues, sino ámalos y sufre con ellos.
Mira que no sigas a los maestros asalariados,
que predican para obtener ganancias y riquezas, y no permanecen en la doctrina de Cristo.
No les creas, no los atiendas, porque no le hacen bien a la gente;
pero tú los verás por ti misma.
Estos a veces tienen una apariencia externa de piedad,
pero niegan el poder de Dios y la verdadera santidad.
Recuerda que te lo he dicho, como alguien que ha tenido un conocimiento perfecto de ellos.

Asegúrate de no dejar que nada separe tu amor de Dios ni de Su pueblo.
Aquellos que guardan Su ley, obedecen la voz de Cristo y llevan una vida santa,
son Su pueblo.
Estos siempre han sido odiados, rechazados y perseguidos,
y la gente mala y libertina siempre han hablado mal de ellos.
Estos son el pueblo de Dios y Su amor, paz y bendición están con ellos.
Por tanto, crece entre ellos como una rama natural de la Vid viva,
y continúa todos tus días en obediencia a la voluntad de Dios.
Así sentirás gozo y amor en tu corazón,
lo cual debes perseguir por encima de todas las cosas,
y alcanzarás y obtendrás la paz eterna.
¡Qué el Señor te conceda esto, según las riquezas de Su misericordia y amor,
que perduran por los siglos de los siglos, amén!

Y ahora Abigail, con respecto a tu bienestar en esta vida,
este es mi consejo y recomendación para ti: Ama a tu querida madre,
obedécela y hónrala siempre.
Mira que no la aflijas, ni seas terca ni voluntariosa, sino sométete a ella,
y sé una hija obediente para ella;
porque su amor y cuidado han sido grandes sobre ti y tus hermanas,
lo que ha traído mucha preocupación sobre ella.
Aprende en tu juventud a leer y a escribir un poco, a coser y tejer,
y todos los elementos de buena labor que corresponden a una criada;
y huye de toda ociosidad y pereza que alimentan el pecado.
A medida que crezcas en años, guárdate del orgullo, la extravagancia y la curiosidad;
y más bien, conténtate con la ropa que tu madre te permita,
en lo que también puedes ser un buen ejemplo para otros.
No seas imprudente, desenfrenada, ni liviana, sino templada, moderada y casta;
y no te adelantes en palabras o expresión, sino sé rápida para oír y lenta para hablar.
Vive siempre con tu madre,
sé una ayuda para ella y cuídala en su vejez y en sus últimos años,
para que ella se consuele en ti y su alma te bendiga.
Ama a tus hermanas y sé amable con ellas siempre, y con tu hermano Thomas;
anímense unos a otros en el bien.

Y Abigail, si vives hasta llegar a ser una mujer de edad madura,
guárdate sin mancha y no dejes que tu mente vaya tras deportes y pasatiempos,
porque el fin de todo eso es dolor; ni busques jóvenes.
Si deseas casarte, no busques marido, sino que el marido te busque;
y si tú vives una vida honesta y virtuosa en el temor de Dios,
entonces los que temen a Dios te buscarán. No dejes que
tus afectos vayan tras de todos los que te ofrecen amor,
sino sé prudente; y por encima de todo (si te casas) escoge uno que ame y tema al Señor,
cuya conducta, costumbre y curso de vida conozcas bien, antes de darle tu consentimiento.
Sé discreta y sabia.
No le ocultes nada a tu madre, y ella sin ninguna duda te aconsejará para tu bien;
y si ella está viva, no te cases sin su consentimiento.
Y si te unes a un marido, asegúrate de amarlo en tu corazón y sé obediente a él,
y hónralo en presencia de todos;
así su corazón será más para ti y su amor aumentará. No lo entristezcas,
sino sé amable y fácil de tratar, ocupándote de tus propios asuntos.
Y si el Señor les da niños, críalos en el temor de Dios y en la buena disciplina,
manteniéndolos en sujeción a ti.
Sé un ejemplo de virtud y santidad para ellos,
para que sientas la bendición del Señor en tu juventud,
en la vejez y durante toda tu vida.

¡Oh, Abigail, recuerda estas cosas; tenlas presentes!
Lee a menudo esta carta; hazla copiar.
Guarda mis palabras en tu corazón y hazlas; así serás feliz en esta vida y en la porvenir.
Te encargo que guardes estas cosas, como expresión de mi mente,
voluntad y consejo inalterables para ti; en testimonio de lo cual he firmado.

[.signed-section-closing]
Tu querido padre,

[.signed-section-signature]
Francis Howgill.

[.signed-section-context-close]
26 del mes Quinto de 1666

--

A principios de este año,
los miembros de esta sociedad celebraron la reunión general anual en Londres,
que desde entonces, se ha realizado anualmente en la semana de Pentecostés,^
footnote:[Desde entonces, se ha fijado su celebración el Segundo-día,
inmediatamente posterior al tercer Primer-día del quinto mes.]
porque esa época del año suele ser la mejor para viajar.
Se envían a varios de todas partes para que asistan a esta reunión,
y en ella se tratan los asuntos generales de la iglesia.

La persecución por religión parecía estar entonces en un punto muerto,
lo que desagradaba a algunos de los eclesiásticos más rígidos, como ya hemos mostrado,
y demostraremos de nuevo en su momento.

Por este tiempo, creo,
cierto obispo dijo que los Cuáqueros se estaban incrementado
mucho por su ilimitada libertad,
y que por eso era muy necesario tener cuidado de ellos,
viendo que a menudo tenían asambleas mucho más grandes que la iglesia nacional:
"`Porque,`" dijo él, "`en cierto momento yo mismo estaba predicando,^
footnote:[La frase utilizada en inglés aquí puede tener dos significados.
Puede significar: 1) que el obispo mismo estaba predicando,
o 2) que el obispo estaba predicándose a sí mismo,
o exaltándose a sí mismo con su predicación. El obispo
obviamente pretendía el primer significado,
pero en lo que sigue,
vemos que el lord jugó con sus palabras y le acusó del segundo significado.]
y no había más que unos pocos oyentes,
cuando al mismo tiempo la reunión de los Cuáqueros en las cercanías estaba llena.`"
A continuación quiso que consideraran si no era tiempo de detener a esos sectarios.
Después de que había expuesto su argumento ampliamente,
otro lord que estaba presente entre los demás dijo, que en efecto,
parecía que el señor obispo había dicho algo muy cierto,
que los sectarios a menudo tenían más oyentes que los predicadores de la iglesia nacional,
y que no le extrañaba que le desagradara al obispo, ya que asumía una tarea tan elevada:
"`Porque,`" dijo,
"`su señoría acaba de decir que él '`se estaba predicando,`' y los Cuáqueros,
que tienen asambleas tan grandes, predican a Jesucristo; por tanto,
no es de extrañar que tengan más oyentes.`"
Este fue un giro tan ingenioso de las palabras del obispo,
que sin duda lo hizo pensar que no era prudente entrar en discusión,
porque era palpable que el comentario de este lord hacia el obispo
era principalmente para evitar que promoviera la persecución.

Viajando hacia York esta primavera,
G+++.+++ Fox pasó por varios otros lugares al norte de Inglaterra;
y aunque se acercó a su viejo enemigo el coronel Kirby,
quien tenía un ataque de gota y lo había amenazado, pasó sin ser molestado.
Continuó hacia Liverpool,
de donde él junto con otros amigos--entre los que estaba
Thomas Briggs y John Stubbs--se dirigió a Irlanda;
y tras llegar a Dublín, fue amablemente recibido por sus amigos.
Al adentrarse en el país,
encontró no poca oposición por parte de los Católicos
que eran muchos ahí. Al llegar a cierto lugar,
desafió a los Jesuitas, sacerdotes y monjes a que probaran si el dios de ellos,
que hacen de una hostia, era un dios inmortal, pero ellos no quisieron hacerlo;
por lo que dijo que ellos eran peores que los sacerdotes de Baal,
porque los sacerdotes de Baal habían estado dispuestos a probar a su dios.
Entonces se fue a Cork,
donde tenían conocimiento de su llegada y pretendían tomarlo prisionero;
pues los Cuáqueros en Irlanda fueron duramente perseguidos por muchos años,
al igual que sus hermanos en Inglaterra,
pero mencionar todos los sucesos daría para un tratado muy extenso.

Por este tiempo había muchos prisioneros en Cork, entre los que estaba Samuel Thornton,
a quien yo conocía bien.
Estando él reunido con sus amigos en un aposento un Primer-día, el oficial Quinnal llegó,
cerró la puerta de la habitación y los encerró, en total ochenta personas,
y le llevó la llave al alcalde Matthew Dean.
Entonces, el alcalde dio la orden de que no se les llevara nada de comer ni de beber,
y que sólo pudieran obtener lo que fuera subido con
cuerdas por la reja o lanzado a través de un hueco.
Debajo de esa habitación se les ordenó a los soldados
que vigilaran para que nadie se escapara,
y estos hicieron un fuego tan grande,
que muchos de los prisioneros se enfermaron por el humo,
entre los cuales había personas ancianas y débiles,
y algunas mujeres embarazadas y lactantes que estaban casi asfixiadas.
Al presentar una queja ante el alcalde, este respondió con sorna:
"`Todos son hermanos y hermanas, que se acuesten unos sobre otros,
y si se asfixian será por su propia culpa.`"
Así estuvieron veinticuatro horas, y después algunos fueron llevados a prisión.

Este año, Solomon Eccles, a quien yo también conocí muy bien,
estaba en la prisión de Gallaway, en Irlanda,
donde había sido llevado por un extraño incidente.
Él era un hombre extraordinariamente celoso,
y se oponía calurosamente a lo que él juzgaba malo, incluso con riesgo de su vida.
Este celo lo llevó a realizar una extraña acción
en la capilla de los papistas a las afueras del pueblo;
pues desnudo de la cintura para arriba y con un plato
de carbones y azufre ardiendo sobre su cabeza,
entró a la capilla cuando toda la gente estaba arrodillada para orar a su ídolo,
y dijo lo siguiente: "`¡Ay de esto adoradores idólatras!
Dios me ha enviado hoy para advertirles y a mostrarles lo que será su porción,
si no se arrepienten!`"
Cuando terminó se fue al pueblo, donde pronto fue hecho prisionero.
Cuál podría haber sido el beneficio de esta extraña acción, lo dejo.

Entre los mártires de los reformados,
encontramos algunos ejemplos de personas que fueron celosas hasta grados extraños,
como William Gardiner en Lisboa, y Bertrand le Bias en Tournay,
cuyas acciones no fueron menos notables.
Se dice que este último le arrebató la hostia al
sacerdote en su iglesia mientras estaban en la misa,
lo cual fue, ciertamente, un intento audaz, y no digno de elogio,
si sólo fue un acto de ingenio humano.
Pero encuentro más seguro dejarle a Dios el juicio de esto, más aún,
porque hizo esto esperando el castigo más severo que le podían infligir,
y no retrocedió ante él,
sino más bien se fortaleció. Y aunque a Solomon Eccles
no le tocó una consecuencia tan severa,
aun así encuentro más seguro no juzgar precipitadamente esta acción poco común. Él era,
por lo que sé, un hombre audaz e intrépido, y previo a su acto en la capilla,
había hecho algo de una naturaleza similar en Londres durante la época de feria,
entre las obras de teatro,
donde sufrió mucho porque los cocheros lo azotaron severamente en su espalda desnuda.
Pero esto no apagó su celo ferviente,
que se encendía no sólo contra la conducta inmodesta e impía de los pretendidos tontos,
sino también contra otras vanidades que se permitían allí.

El siguiente ejemplo mostrará hasta qué punto lo llevó su celo.
Él había sido miembro de la iglesia de Inglaterra, luego se pasó a los Presbiterianos,
más tarde a los Independientes, y luego se convirtió en Bautista;
durante todo ese tiempo fue un músico notable,
de modo que por su arte podía obtener más de 150 libras al año. Pero al final,
al convertirse en Cuáquero, no pudo, por motivos de consciencia,
continuar lo que entonces llamaba su negocio de música babilónico.
Por eso aprendió a hacer ropa para ganarse la vida,
y vendió sus libros e instrumentos de música.
Pero, según declaró, aún no tenía paz en su consciencia;
pues creyendo que eran instrumentos de vanidad, juzgó que debían ser destruidos.
Por tanto, los compró de nuevo (aunque valían más de 20 libras),
y los llevó (clavicordios, violines, etc.) a Tower-hill,
donde los colocó juntos y les prendió fuego.
Pero cuando algunos que estaban cerca trataron de impedirlo y llevarse uno de los clavicordios,
S+++.+++ Eccles pisoteó el instrumento con su pie y no descansó hasta que lo había destruido.
Después de esto dijo que había encontrado paz en su consciencia,
habiendo hecho una ofrenda de eso que una vez había amado tanto,
y en cuyo uso había sido educado; porque no sólo su padre y su abuelo,
sino también el padre de su abuelo, habían sido músicos,
y él mismo tenía el nombre de un notable maestro de música.

Ahora regreso a G. Fox en Cork, Irlanda, donde había un plan para tomarlo prisionero.
Sin embargo, lo dejaron ir sin ser molestado,
aunque cabalgó por el mercado y por la puerta del alcalde, quien no sólo lo vio,
sino que dijo: "`Ahí va George Fox,`" y sin embargo, lo dejó pasar tranquilamente.
Después de viajar por muchos lugares en Irlanda, llegó de nuevo a Dublín,
de donde regresó otra vez a Inglaterra.
Al llegar a Gloucestershire,
se enteró en Nailsworth de una noticia que se había extendido por el condado,
de que se había convertido en Presbiteriano,
y que le habían preparado un púlpito en el patio donde le iba a predicar al pueblo.

Cuando G. Fox escuchó esto pensó que era muy extraño,
por lo que fue al lugar del que se hablaba,
y efectivamente encontró un púlpito ahí. Pero el caso era el siguiente:
Cierto predicador Presbiteriano llamado John Fox, que andaba predicando por el condado,
iba a predicar ahí, y parece que algunos habían cambiado el hombre de John a George,
por lo que se informó que G. Fox se había convertido de Cuáquero a Presbiteriano.
Esto suscitó tanta curiosidad entre la gente,
que muchos fueron a oír a este Cuáquero vuelto Presbiteriano, y así,
John Fox llegó a tener una audiencia de varios cientos de personas,
quienes de haberlo sabido, no habrían viajado ni un metro para oírlo.
Pero algunos centenares de ellos,
después de oír que el verdadero G. Fox estaba en una reunión no muy lejos de ahí,
fueron y estuvieron sobrios y atentos,
y fueron dirigidos por Fox a la gracia de Dios en ellos que les
enseñaría y les traería salvación. Y cuando terminó la reunión,
algunas de las personas dijeron que les gustaba más
la predicación de George Fox el Cuáquero,
que la de George Fox el Presbiteriano.

No mucho después se presentó una queja en la Cámara de los Comunes contra este John Fox,
por tener reuniones tumultuosas y en las que se decían palabras de traición. Ahora bien,
John Fox había sido anteriormente sacerdote de Marshfield, en Gloucestershire,
y tras ser expulsado de ese lugar,
un sacerdote de la oración común le permitía predicar
algunas veces en su '`casa del campanario.`' Al final,
parece que ese John Fox presumía demasiado de la
anterior concesión del sacerdote de la parroquia,
y empezó a mostrarse más atrevido que bien recibido,
deseando predicar ahí cada vez que quería. Esto causó un
gran alboroto y una gran contienda entre los dos sacerdotes,
y entre los oyentes de cada lado, en cuyo momento,
el libro común de oraciones fue supuestamente cortado en pedazos; y se dice,
que entonces los seguidores de John Fox pronunciaron algunas palabras
de traición. Este caso se publicó rápidamente en los periódicos,
y algunos Presbiterianos malintencionados hicieron que se redactara de manera tal,
que sugiriera que la traición había salido de la boca de G. Fox el Cuáquero.
Sin embargo,
algunos miembros de la Cámara de los Comunes certificaron con sus firmas que,
en realidad, John Fox, anteriormente sacerdote de Marshfield,
había sido el líder de esa asamblea ilícita.

Después de esto G. Fox viajó a Bristol, donde se encontró con Margaret Fell,
para ese entonces viuda, que había llegado a visitar a su hija Yeomans.
Antes de este momento, él le había expresado a ella su afecto,
y le propuso tomarla en matrimonio en el momento adecuado;
pero aunque él tenía la consciencia en sí mismo de que esto era del Señor,
no había encontrado la libertad previamente para llevarlo a cabo.
Pero cuando todos los obstáculos quedaron eliminados,
le propuso que si ella estaba dispuesta a dar su consentimiento,
primero enviara a buscar a sus hijos.
Cuando todos estuvieron reunidos, G. Fox les preguntó a sus dos hijas y a sus esposos,
si ellos tenían algo en contra de que él tomara en matrimonio a su madre.
Y ellos individualmente expresaron su satisfacción por ello.
Entonces G. Fox le preguntó a Margaret,
si ella había realizado la voluntad de su primer esposo.
Y les preguntó a los hijos, si en el caso de que su madre se casara de nuevo,
ellos perderían algo.
Todos los hijos dijeron que ella había realizado la voluntad de su padre para con ellos,
y por eso le pidieron que no hablara más del asunto.
Así, pues, viendo que todos ellos estaban satisfechos procedió a casarse,
y tomó a Margaret Fell como esposa en una reunión pública de Amigos en Bristol.
Ella era una mujer de noble talento, y lo sé no sólo por sus escritos,
sino también porque la he oído predicar durante una hora seguida,
exponiendo su asunto de manera concisa y ordenada.

Ya casado, G. Fox permaneció con su esposa alrededor de una semana,
y luego se fueron a Oldstone.
Allí se despidieron y se separaron, ella regresó a su casa en el norte,
y él viajó a través de Wilshire, Berkshire, Oxfordshire, Bucks y así hasta Londres;
porque aunque ahora tenía esposa,
no abandonó el cuidado de las iglesias de toda la nación,
edificándolas con el don que había recibido de Dios, tanto en palabra como por escrito.
Y entre otras cosas, tenía especial interés en que los pobres fueran atendidos,
para cuyo fin escribió una epístola en Londres,
mandando que los niños pobres fueran puestos como aprendices de oficios,
para que con el tiempo, pudieran ayudar a sus padres ancianos,
y pudieran criar a sus familias y mantenerse cómodamente.

G+++.+++ Fox no se quedó mucho tiempo en Londres; pero habiendo llegado el año 1670,
viajó a través de Hertfordshire, Cambridgeshire, Huntingdonshire y Leicestershire,
donde esperaba encontrarse con su esposa;
porque él le había escrito un mensaje de que se reuniera con él ahí,
si lo encontraba conveniente.
Pero en lugar de eso,
descubrió que ella había sido arrastrada de su casa y llevada a la prisión de Lancaster,
bajo la acusación de una antigua sentencia de premunire
que había sido pronunciada contra ella cinco años antes,
de la que había sido liberada por orden del rey y el consejo el año anterior.
Por tanto, después de haber visitado a sus amigos en esos condados, regresó a Londres,
donde encontró a dos hijas de su esposa,
y las animó a ir rápidamente al rey para informarle de cómo había sido tratada su madre.
Ellas lo hicieron y se toparon con mucha dificultad, pero al fin,
a través de una perseverante aplicación, se les permitió hablarle al rey,
a quien una de ellas le dijo,
que en lugar de haber esperado para darle las gracias por la liberación de su madre,
ahora estaban obligadas a quejarse porque su madre
había sido encarcelada por segunda vez.
Con lo cual, el rey le dio orden a sir John Otway de escribirle al alguacil de Lancaster,
para que la pusiera en libertad;
y con dicha carta G. Fox apresuró a sus hijas hacia el condado.

El Parlamento entonces reunido, promulgó una ley titulada:
__Ley para Prevenir y Suprimir los Conventículos Sediciosos__, la cual es como sigue:

[.embedded-content-document.legal]
--

Para proporcionar mayores y más rápidos remedios contras las crecientes
y peligrosas prácticas de sectas sediciosas y otras personas desleales,
quienes bajo el pretexto de tierna consciencia,
tienen o pueden en sus reuniones planear insurrecciones
(como ha demostrado la experiencia reciente):

[.small-break]
'''

I+++.+++ Se decreta por la excelentísima majestad del rey,
por y con el consejo y consentimiento de los señores espirituales y temporales,
y el presente Parlamento reunido y por la autoridad de este,
que si una persona de dieciséis años o más, siendo súbdito de este reino,
en cualquier momento después del día décimo del próximo
mes de mayo está presente en una asamblea,
conventículo o reunión, bajo el pretexto de un ejercicio de religión,
en una forma diferente a la liturgia y práctica de la iglesia de Inglaterra,
en cualquier lugar dentro del reino de Inglaterra o del dominio de Gales,
en cuyo conventículo, reunión o asamblea se encuentren reunidas cinco personas o más,
además de las personas de la misma familia,
será legal para uno o más jueces de paz del condado levantar un acta de cada infracción,
y firmarlas y sellarlas respectivamente.
Y a partir de ahí, el mencionado juez, o jueces, o magistrado en jefe,
impondrá sobre cada ofensor así acusado,
__una multa de cinco chelines por su primera ofensa__;
cuyo registro y condena serán certificados por dicho juez, jueces, o magistrado en jefe,
en las siguientes reuniones trimestrales del condado o lugar donde se cometió la infracción.

[.small-break]
'''

II. Se decreta además, por la autoridad antes mencionada,
que si un transgresor así condenado,
en algún momento vuelve a cometer el mismo delito o delitos
en contra de esta ley y es condenado por ello,
dicho transgresor __incurrirá en la pena de diez chelines__ por cada infracción;
dicha multa o multas serán cobradas con la incautación
y venta de los bienes y propiedades del transgresor;
o en caso de pobreza del transgresor,
sobre los bienes y propiedades de cualquier otra persona o personas que en ese
momento sean condenadas por la misma transgresión en el mismo conventículo,
a discreción del juez, de los jueces o magistrado en jefe respectivamente,
de modo que la suma que se imponga a una persona
en caso de pobreza y se le cobre a otros transgresores,
no supere en su totalidad la suma de diez libras, en ocasión de una reunión.

[.small-break]
'''

III.
Se decreta por la autoridad antes mencionada,
que cada persona que se encargue de predicar o enseñar en cualquiera de estas reuniones,
asambleas o conventículos, y por esa razón sea condenada, como se ha dicho,
perderá por su primera transgresión __la suma de veinte libras__,
que serán cobradas de la manera ya mencionada con sus bienes o propiedades.
Y si dicho predicador o maestro es extranjero, y se desconocen su nombre y residencia,
o ha huido, o no puede ser hallado, o a juicio del juez,
es considerado incapaz de pagar la multa,
dicho juez está facultado por la presente y se le exige,
que cobre la multa mediante una orden judicial sobre los bienes y propiedades
de cualquiera de las personas presentes en el mismo conventículo.
Y si dicho transgresor así condenado,
en algún momento vuelve a cometer el mismo delito o delitos en contra de esta ley,
y es condenado por ello de la manera antes mencionada,
entonces por cada transgresión __incurrirá en la pena de cuarenta libras__,
que se cobrarán y dispondrán como se ha dicho.

[.small-break]
'''

IV. Se decreta por la autoridad antes mencionada,
que toda persona que voluntariamente permita que se celebre cualquier conventículo,
reunión o asamblea ilícita en su casa, anexo, granero o patio,
y es condenada por ello de la manera antes mencionada, __perderá la suma de veinte libras__,
que serán cobradas de la manera ya mencionada, con sus bienes y propiedades;
o en caso de pobreza o incapacidad,
con los bienes y propiedades de las personas que
sean condenadas por estar presentes en el mismo conventículo; etc.

--

Por esta ley muchas familias se empobrecieron,
porque los Cuáqueros no dejaron de reunirse públicamente.
Muchos de los más sinceros entre ellos se volvieron aún más celosos,
y así se separaron de la paja, que en tiempos de tranquilidad,
algunas veces se colaba entre la gente verdaderamente religiosa.
En Londres, así como en otros lugares,
muchos fueron despojados de sus bienes despiadadamente,
y muchas veces personas de buena posición fueron llevadas a la mera pobreza;
siendo que a algunas les confiscaron no sólo los bienes de sus tiendas,
sino también los domésticos.
En algunos casos, a los enfermos les quitaron sus camas y los pusieron en el suelo.
De hecho, fueron tan crueles que dejaron a algunas familias sin nada;
pues al encontrar a un niño comiendo en un plato de metal,
tiraron la comida para coger el plato.

Si yo relatara todos los detalles que he recibido con respecto a este tiempo,
el relato podría alcanzar para hacer un volumen en sí mismo; pues los informantes^
footnote:[Los informantes eran los que les reportaban los
"`conventículos ilegales`" a los magistrados locales,
con la expectativa de recibir un tercio del dinero
o de los bienes confiscados a los Cuáqueros.]
eran generalmente pobres, y algunas veces también los jueces,
así que estos aprendieron a dividir los botines de manera tal,
que el rey y el pobre obtenían muy poco.
Sin embargo, en algunas ocasiones,
los jueces liberaban a los que habían sido apresados en reuniones,
porque era bien sabido que estos informantes, que también actuaban como testigos,
eran astutos tiburones,
que se preocupan principalmente por obtener su tercio del botín. Y así, a veces,
un juez honesto liberaba a un hombre o a una mujer que había sido capturado en una reunión,
si se hallaba que el informante se había equivocado, ya fuera en el día del mes,
o había cometido algún otro error pequeño.

En Londres, una vez apareció delante del alcalde, sentado en un tribunal de concejales,
un informante deshonesto que tenía una lista tan larga de personas que había que multar,
que la suma ascendía a 1500 libras.
Pero el alcalde, despreciando tales prácticas,
suspendió la sesión y se marchó. Pero este determinado
informante no se contentó con dejar el asunto ahí,
y continuó presentándose delante del tribunal de tiempo en tiempo,
buscando hacer presa de los bienes de personas honestas.
Sin embargo, ellos continuaron posponiéndolo,
hasta que al fin el informante mismo fue arrestado por deudas y enviado a prisión,
donde terminó sus días.

Aunque la ley contra los conventículos sediciosos se había aprobado por
la sospecha de que los Presbiterianos estaban listo para levantarse--al
considerarse el ajetreo y tumulto ocasionado por John Fox en Gloucestershire,
lo que fue muy notorio (como he mencionado antes)--las reuniones de los Cuáqueros
se convirtieron en el principal objetivo en la ejecución de esta ley.
A raíz de lo cual, estando G. Fox en Londres,
expuso por escrito la injusticia de esta ley, con el fin, si era posible,
de persuadir al gobierno de no ponerla en ejecución. Sin embargo,
estando también consciente de que una gran tormenta
se cernía sobre las cabezas de sus amigos,
también escribió una epístola para ellos, exhortándolos a la fidelidad,
animándolos a permanecer firmes en sus testimonios,
y a soportar con paciencia cristiana el sufrimiento que había venido sobre ellos.

Ahora bien, el primer día que esta ley fue puesta en efecto,
Fox fue a la reunión de Amigos en Gracechurch-street, en Londres;
pero al llegar al lugar encontró la calle llena de gente,
y un guarda que impedía que entraran a la casa de
reunión. Entonces se fue a la calle Lombard,
de la que también había una entrada a la casa de reunión,
pero ahí también encontró un guarda.
Dado que el patio delante de la puerta estaba lleno de gente,
uno de los ministros Cuáqueros estaba ahí predicándoles a las personas, y cuando terminó,
G+++.+++ Fox se levantó y dijo: "`Saulo, Saulo, ¿por qué me persigues?
Dura cosa te es dar coces contra el aguijón.`" Con estas palabras
explicó que la naturaleza de Saulo era la que perseguía,
y que aquellos que perseguían a Cristo en Sus miembros,
estaban dando coces contra el aguijón;
que el nacimiento de la carne era el que siempre perseguía al nacimiento del Espíritu;
que la naturaleza de los perros era desgarrar y devorar a las ovejas;
pero que los que sufrían como las ovejas, que no devolvían los mordiscos,
eran un pueblo pacífico, que amaban incluso a sus perseguidores, etc.
Mientras G. Fox estaba predicando llegó un alguacil y un informante con soldados,
que lo bajaron del lugar donde estaba.
Entonces dijo:
"`Bienaventurados los pacificadores,`" pero el comandante
de los soldados les ordenó que lo aseguraran:
"`Porque,`" dijo él, "`tú eres el hombre que estábamos buscando.`"
Por tanto, él junto con otros dos de sus amigos, John Burnyeat y otro,
fueron llevados delante del alcalde, y mientras se iban el informante dijo:
"`Nunca será un mundo bueno,
hasta que toda la gente llegue a la buena y antigua religión
que había hace doscientos años.`" Al oír esto,
G+++.+++ Fox dijo: "`¿Eres un papista?
¿Qué? ¿Un papista informante?
Pues hace doscientos años no había en esta nación
otra profesión pública religiosa que la de los papistas.`"

Al informante le molestó que G. Fox le hubiera oído hablar de esta manera;
porque vio que había quedado atrapado en sus propias palabras.
Cuando entró al patio frente a la casa del alcalde,
algunas personas que estaban ahí le preguntaron a G. Fox la razón por
la que había sido llevado ahí. "`Pregúntenle al informante,`" dijo,
"`y pregúntenle su nombre;`" pero él no quiso decir su nombre.
Entonces uno de los oficiales del alcalde le dijo
que debía decir su nombre antes de irse:
"`Porque,`" dijo,
"`el alcalde querrá saber con qué autoridad te has inmiscuido con soldados,
en la ejecución de las leyes que le corresponden
ejecutar al magistrado civil y no al militar.`"
Cuando el informante escuchó esto, se escapó, pero no sin cierta dificultad,
porque ellos no querían dejarlo salir del patio.
Pero al abrir la puerta a la fuerza y salir a la calle,
la gente dio un gran grito exclamando:
"`¡Un papista informante! ¡Un papista informante!`"
Y este, posiblemente habría sido herido,
si G. Fox no le hubiera aconsejado al alguacil y a los soldados que lo
mantuvieran lejos de las manos de la gente común. Acto seguido,
el informante entró a la casa, se cambió la peluca y huyó.

Cuando el alcalde llegó a la casa, y G. Fox fue llevado delante de él, le dijo:
"`Señor Fox, tú eres un hombre eminente entre los de tu profesión;
te ruego que seas un instrumento para persuadirlos
de que no se reúnan en tan grande número.
Porque dado que Cristo ha prometido que donde dos o tres estén reunidos en Su nombre,
Él estaría en medio de ellos;
y que el rey y el Parlamento bondadosamente se complacen
en permitir que se reúnan cuatro a adorar a Dios,
¿por qué no se contentan en participar tanto de la promesa de Cristo a dos o tres,
y de la indulgencia del rey a cuatro?`"
A lo que G. Fox respondió lo siguiente:
"`La promesa de Cristo no fue para desanimar a muchos de reunirse en Su nombre,
sino para animar a los pocos;
para que el menor número no dejara de reunirse a causa de su escasez.
Pero si Cristo ha prometido manifestar Su presencia en medio de tan pequeña asamblea,
donde sólo dos o tres estén reunidos en Su nombre,
cuánto más abundaría Su presencia donde doscientos
o trescientos se reunieran en Su nombre.`"

Entonces G. Fox le pidió que considerara
si esta ley no habría resistido a Cristo,
y a Sus doce apóstoles y setenta discípulos,
(de haber existido en aquel tiempo) quienes solían reunirse a menudo y en grandes multitudes.
"`Sin embargo,`" dijo él, "`esta ley no nos concierne,
porque fue hecha contra las reuniones sediciosas de los
que se reúnen bajo el pretexto y motivo de la religión,
con el fin de planear insurrecciones, tal como dice la ley.
Pero nosotros hemos sido suficientemente examinados y probados,
y siempre hemos sido encontrados pacíficos.
Por tanto, tú harías bien en diferenciar al inocente del culpable.`"
Entonces el alcalde dijo que la ley había sido hecha contra las reuniones,
y contra la adoración que no estaba acorde con la liturgia.
G+++.+++ Fox le dijo, "`__acorde con__ no significa que tenga que ser __exactamente la misma__.`"
¿Es la liturgia acorde con las Escrituras?
¿Podemos no leer las Escrituras y hablar de las Escrituras?`"
El alcalde dijo: "`Sí.`" Entonces G. Fox le dijo:
"`Esta ley les estorba a los que se reúnen a planear e idear insurrecciones,
'`como lo ha demostrado la experiencia reciente,`'
pero nunca han experimentado eso de nosotros.
Sólo porque los ladrones están a veces en el camino,
¿se les debe impedir a los hombres honestos que viajen?
Y porque los conspiradores e intrigantes se reúnen para hacer el mal,
¿se les debe impedir a las personas honestas y pacíficas
que se reúnan para hacer el bien?
Ahora bien, considera esto,
si nosotros fuéramos un pueblo que desea reunirse para planear e idear insurrecciones,
nos habríamos reunido en grupos de cuatro,
porque cuatro podrían hacer más mal al conspirar que cuatrocientos;
pues cuatro podrían hablar con más libertad que cuatrocientos.
Por tanto, al ser nosotros un pueblo inocente,
y no el pueblo al que esta ley hace referencia,
nos reunimos como siempre lo hemos hecho.`"
Luego le dijo al alcalde: "`Creo que tú sabes en tu consciencia que somos inocentes.`"

Después de esta y más conversación, el alcalde, cuyo nombre era Samuel Starling,
los dejó ir,
viendo que el informante se había ido antes y que en ese momento nadie los acusaba.
El trato que recibió este informante hizo que otros dudaran,
sin embargo varias de sus reuniones en Londres fueron perturbadas,
y algunos de sus predicadores echados en la cárcel.
Pero aunque los Bautistas y otros disidentes dejaron sus reuniones públicas,
los Cuáqueros continuaron con las de ellos como siempre habían hecho,
por lo que sucedió que algunas de sus casas de reunión fueron derribadas, y entre otras,
la casa de reunión en Ratcliffe, que era un edificio importante y casi nuevo.

Después de algún tiempo el calor de la persecución en esta ciudad comenzó a disminuir,
pero en otros lugares arreció con más fiereza.
Esto obligó a G. Fox a dejar la ciudad y a viajar
por muchos lugares del país para visitar a sus amigos.

Este año G. Fox fue atacado severamente por una enfermedad, a tal grado,
que por un tiempo estuvo ciego y sordo,
y algunos perdieron la esperanza de su recuperación; pero después de un tiempo mejoró.

Mientras tanto, la persecución en muchos lugares se hizo muy lúgubre;
porque muchos de los amigos eran golpeados con espadas, picos y mosquetes,
a tal punto que su sangre corría por el suelo,
y los informantes estaban tan deseosos de cazar a sus presas,
que a veces informaban de reuniones cuando no había habido ninguna.
Entre otros, el siguiente fue un ejemplo.
En Droitwitch, John Cartwright llegó a la casa de un amigo,
y al sentarse a la mesa oró antes de comer.
Cuando un informante lo escuchó, ya que la habitación estaba al lado de la calle,
se fue inmediatamente e informó que había una reunión en la casa,
y así obtuvo una orden judicial para embargar sus bienes.
Pero cuando iba cabalgando con los oficiales por la noche,
se cayó de su caballo y se rompió el cuello,
obteniendo así la muerte en lugar de la presa que perseguía.
