== Capítulo XVIII

[.section-date]
1670--1674

[.chapter-synopsis]
* Juicio de W. Penn y W. Mead
* Valor de los prisioneros y resolución del jurado
* Persecución de T. Rudyard por denunciar la injusticia del tribunal
* Registrador Howell
* Juez Whaley y los Amigos en Nottingham
* Crueldades en Warwickshire
* Reunión de Horslydown
* S. Eccles y el sacerdote en Cork
* Oración de G. Fox
* G. Fox en América
* Príncipe William de Orange
* G. Fox vuelve a Inglaterra y es encarcelado
* M. Halhead y el general Lambert
* Carta de M+++.+++ Halhead a G. Fox
* Juicio de G. Fox y T. Lower en Worcester
* G. Fox permanece encarcelado
* G. Fox ante el tribunal del Rey
* Encarcelado en Worcester
* Condenado con la sentencia premunire
* Llevado de nuevo ante el tribunal del Rey.

Ahora, aunque la persecución no era tan fiera en Londres como en otros lugares del país,
a veces, incluso ahí, era muy severa,
como puede verse en el caso de William Penn y William Mead,
quienes fueron sacados de una reunión, encarcelados y juzgados en el mes de septiembre.

La acusación decía que William Penn y William Mead, junto con otras personas,
hasta un número de trescientas, habían tenido una reunión tumultuosa el 15 de agosto,
por la fuerza y con armas, en Gracechurch-street, Londres; y que William Penn,
en acuerdo con William Mead, había predicado ahí en la calle pública,
causando con esto una gran concurrencia y tumulto de personas, etc.
Ahora bien,
el hecho de que hubiera una reunión en la calle pública procedía de la necesidad,
porque se había colocado un guarda en la puerta de
la casa de reunión para evitar que los amigos entraran.
Pero era una gran falsedad que se hubieran reunido a la fuerza y con armas,
las cual nunca fueron usadas por los Cuáqueros.

Después de que se leyó la acusación delante del tribunal,
se les demandó a los prisioneros, según la costumbre,
que se declararan culpables o no culpables.
Con lo cual, William Penn dijo:
"`Es imposible que podamos recordar la acusación palabra por palabra; por tanto,
deseamos una copia de ella, como es la costumbre en casos similares.`"
El registrador John Howel dijo al respecto:
"`Ustedes deben responder primero a la acusación,
antes de que puedan tener una copia de ella.`"
Entonces William Penn dijo que él deseaba que no
se tomara ninguna ventaja en contra de él,
ni que se le privara de ningún beneficio que pudiera recibir,
y que el tribunal le prometiera un juicio justo y la libertad de hacer su defensa.
Ante esto, el tribunal dijo que no se debía tomar ventaja contra él,
que tendría la libertad y que sería oído. Entonces W. Penn
dijo que se declaraba no culpable en modo y forma.
Luego, se le requirió a W. Mead que se declarara culpable o no culpable,
y él respondió lo mismo que W. Penn.
Luego, el tribunal procedió a juzgar a los ladrones y asesinos,
haciendo que los prisioneros esperaran cinco horas antes de regresarlos a la prisión;
y después de dos días fueron llevados de nuevo ante el tribunal.

Los oficiales del tribunal les quitaron los sombreros a los prisioneros, y el alcalde,
Samuel Starling,
se mostró disgustado por eso y les ordenó a los oficiales
que les pusieran otra vez los sombreros.
Hecho esto, el registrador John Howel, que en todas las ocasiones mostraba su saña,
los acusó de no mostrar respeto al tribunal,
y condenó a cada uno de ellos con una multa de cuarenta marcos por no quitarse el sombrero.
Acto seguido,
W+++.+++ Penn dijo que quería que se observara que ellos
habían entrado al tribunal sin sus sombreros,
(es decir,
que se los habían quitado) y que si en ese momento
los tenían puestos era por orden del tribunal,
por lo que debía multarse al tribunal y no a los prisioneros.
Luego se juramentó al jurado,
se leyó otra vez la acusación y fueron llamados los testigos,
quienes declararon que habían visto a William Penn hablándole a
la gente que estaba reunida en gran número en Gracechurch-street,
pero que no habían podido oír lo que decía.

El registrador le preguntó a William Mead si él estaba ahí. Quien respondió:
"`Es una máxima en tu propia ley, _nemo tenetur se ipsum accusare,_
que si no es verdadero latín, estoy seguro de que es buen inglés:
'`Ningún hombre está obligado a acusarse a sí mismo.`'
¿Por qué entonces me pones una trampa con esa pregunta?`"
En ese momento el registrador se mostró tan disgustado que dijo: "`Señor,
detén tu lengua, yo no intento ponerte trampas.`"
Entonces William Penn dijo: "`Nosotros confesamos estar tan lejos de retractarnos,
o de avergonzarnos de nuestras asambleas para predicar, orar o adorar al Dios eterno,
santo y justo, que le declaramos a todo el mundo,
que creemos que es nuestro deber indispensable reunirnos regularmente por tan buen motivo;
y que ni todos los poderes sobre la tierra podrán desviarnos
de reverenciar y adorar al Dios que nos hizo.`"

Entonces Richard Brown dijo: "`Ustedes no están aquí por la adoración a Dios,
sino por quebrantar la ley.
Se hacen a sí mismos un gran daño al seguir con ese discurso.`"
Ante esto W. Penn respondió: "`Yo afirmo no haber quebrantado ninguna ley,
ni soy culpable de la acusación que se me imputa.
Y a fin de que el tribunal, el jurado y yo mismo, junto con los que nos escuchan,
podamos tener un entendimiento más directo de este procedimiento,
deseo que me hagan saber en virtud de cuál ley me están procesando ustedes,
y sobre cuál ley fundamentan mi acusación.`" El registrador respondió:
"`Sobre la '`ley común.`'^
footnote:[La ley común es un conjunto de leyes no escritas basadas en precedentes legales
establecidos por los tribunales.]`" "`¿Dónde está esa '`ley común,`'?`" dijo W. Penn.
"`No puedes pensar,`" dijo el registrador,
"`que soy capaz de hacerte un relato de tantos casos juzgados, a lo largo de tantos años,
que llamamos '`ley común,`' para responder a tu curiosidad.`"
"`Estoy seguro de que esta respuesta,`" replicó W. Penn, "`es muy corta para mi pregunta;
porque si es común, no debería ser difícil de mostrar.`"
El registrador respondió: "`Señor,
¿te declararás culpable de tu acusación?`" "`¿Debo,`" respondió W. Penn,
"`declararme culpable de una acusación que no tiene fundamento en la ley?
Si mi acusación contiene la ley que ustedes dice que he quebrantado,
¿por qué se niegan a mostrarla?
Pues sería imposible para el jurado determinar o ponerse de acuerdo para dar un veredicto,
cuando no han visto la ley por la que deberían medir la verdad de esta acusación,
y mi culpabilidad o inocencia.`"
El registrador enfurecido dijo: "`¡Eres un tipo insolente;
habla de la acusación!`" W. Penn replicó:
"`Yo digo que me corresponde hablar de asuntos de derecho.
Estoy imputado como prisionero; mi libertad, que está a la altura de la vida misma,
está en juego ahora.`"

En ese momento varios de los que estaban en el tribunal litigaron contra el prisionero,
para que se le detuviera.
W+++.+++ Penn dijo: "`Ustedes son muchas bocas y muchos oídos contra mí,
y si no se me permite hacer lo mejor en pro de mi causa, lo encuentro muy difícil.
Repito,
a menos que ustedes me muestren a mí y a la gente
la ley sobre la que fundamentan la acusación,
daré por sentado que los procedimientos de ustedes son meramente arbitrarios.`"
Entonces el registrador replicó:
"`La cuestión es si eres culpable de esta acusación.`" "`La cuestión,`" dijo W. Penn,
"`no es si soy culpable de esta acusación, sino si la acusación es legal.
Es demasiado general e imperfecto decir '`es la ley común,`'
a menos que sepamos dónde está y cuál es la ley.
Porque donde no hay ley, no hay transgresión; y una ley que no existe,
está tan lejos de ser común, que no es ley del todo.`"

El registrador chilló: "`¡Eres un tipo insolente! ¿Le enseñarás al tribunal qué es la ley?
Es la _lex non scripta_ +++[+++es decir, una ley no escrita],
la que muchos han estudiado treinta o cuarenta años para conocerla,
¿y quieres que te la diga en un momento?`"
"`Ciertamente,`" replicó W. Penn, "`si la ley común es tan difícil de ser entendida,
está lejos de ser muy común;
pero si lord Coke en sus Institutos es de alguna consideración,^
footnote:[Sir Edward Coke (1552-1634) fue un abogado, juez y político inglés,
considerado el mejor jurista de su tiempo.
Se le conoce sobre todo por sus
[.book-title]#Institutos de las Leyes de Inglaterra# en cuatro volúmenes,
y por su [.book-title]#Law Reports# en trece volúmenes.]
él nos dice que '`ley común`' es derecho común;
y que el derecho común es la Carta Magna de privilegios confirmada, 9 Hen.
3.29; 25 Edw.
1.1; 2 Edw.
3.8: Institutos de Coke, 2. p. 56.`" El registrador nada complacido con este discurso,
dijo: "`Señor, eres un tipo molesto,
y no es para el honor de esta corte permitirte continuar.`"

W+++.+++ Penn replicó: "`No he hecho más que una pregunta y ustedes no me han respondido;
aunque los derechos y privilegios de todo ciudadano inglés están implicados.`"
"`Bien,`" dijo el registrador,
"`si yo te permitiera hacer preguntas hasta mañana por la mañana, no serías más sabio.`"
"`Eso dependería de las respuestas,`" dijo W. Penn.
"`Pero,`" dijo el registrador,
"`nosotros no debemos soportar oírte hablar toda la noche.`"
Ante esto W. Penn replicó: "`No deseo afrentar al tribunal,
sino sólo ser oído en mi justa defensa.
Y debo decirles claramente,
que si me niegan ver la ley que ustedes sugieren que he quebrantado,
me niegan inmediatamente un derecho reconocido;
y evidencian ante el mundo entero también,
la resolución de ustedes de sacrificar los privilegios de
un ciudadano inglés a sus designios siniestros y arbitrarios.`"
Esto enfureció tanto al registrador, que le gritó a los oficiales: "`¡Llévenselo!`"
Y al alcalde le dijo: "`Mi señor,
si no tomas alguna otra medida contra este tipo pestilente para detenerle la boca,
no podremos hacer nada esta noche.`"
Entonces el alcalde gritó: "`¡Llévenselo; llévenselo;
enciérrenlo en el "`bail-dock`"^
footnote:["`Bail-dock`" era un compartimento pequeño y asegurado en una sala de tribunal,
que se utilizaba para retener a un acusado penal durante su audiencia.].

Al ver W. Penn cuánta fuerza y violencia prevalecía dijo:
"`Estas son sólo vanas exclamaciones.
¿Es esto justicia o un verdadero juicio?
¿Debo ser sacado porque apelé a las leyes fundamentales de Inglaterra?`"
Entonces dirigiéndose al jurado dijo: "`No obstante,
esto lo dejo a la consciencia de ustedes, miembros del jurado y mis únicos jueces:
Si estas antiguas leyes fundamentales que se refieren a la libertad y a la propiedad,
y que no están limitadas a particulares persuasiones en materia de religión,
no deberían ser indispensablemente mantenidas y observadas; entonces,
¿quién puede decir que tiene derecho al abrigo que lleva sobre su espalda?
Sí, nuestras libertades pueden ser abiertamente invadidas, nuestras esposas violadas,
nuestros hijos esclavizados, nuestras familias arruinadas,
y nuestros patrimonios llevados en triunfo como trofeos
de cualquier mendigo tenaz y malicioso informante,
bajo el pretexto de que hemos renunciado a ello por motivos de consciencia.
El Señor del cielo y de la tierra será juez entre nosotros en este asunto.`"
Oír este enfático discurso fue tan molesto para el registrador, que gritó: "`¡Cállate!`"
Ante lo cual W. Penn respondió:
"`No voy a quedarme callado en una causa en la que estoy tan involucrado, y no sólo yo,
sino muchas decenas de miles de familias más.`"

Después de que arrastraron a W. Penn al "`bail-dock,`"
le tocó el turno a W. Mead de declarar,
y habló así: "`Hombres del jurado,
estoy aquí para responder a una acusación en mi contra,
que es un fardo lleno de mentiras y falsedades,
pues en ella se me acusa de reunirme ilegalmente por la fuerza de las armas.
Hubo un tiempo en el que yo tenía la libertad de usar un arma carnal,
y pensaba que no le temía a ningún hombre; pero ahora le temo al Dios vivo,
y no me atrevo a usar tales armas, ni a herir a ningún hombre,
ni me conduzco como una persona revoltosa.
Soy un hombre pacífico; por tanto,
fue muy apropiado que William Penn exigiera en este caso,
tener una vista de la ley sobre la que está basada nuestra acusación.`"

A esto el registrador dijo: "`Ya he respondido a eso.`"
Entonces, W. Mead volvió su rostro al jurado y dijo: "`Hombres del jurado,
que son mis jueces,
si el registrador no les dice qué constituye un alboroto o una asamblea ilegal, Coke,
el que una vez fue llamado lord Coke,
nos dice qué constituye un alboroto o una asamblea ilegal.
'`Un alboroto es cuando tres o más se reúnen para golpear a un hombre,
o para entrar por la fuerza en la tierra de otro, o para cortar su hierba, o madera,
o para derribar su cerca.`"
El registrador lo interrumpió y quitándose el sombrero dijo con desdén: "`Te agradezco,
señor, que me hayas dicho cuál es la ley.`"
Y Richard Brown, el empedernido enemigo de los Cuáqueros dijo: "`Él habla al azar,
una vez como Independiente, otra como de otra religión y ahora como Cuáquero,
la próxima será como papista.`"
Mead, no estando dispuesto a afrentar abiertamente a este concejal,
le dijo este bien conocido verso en latín:
__"`Turpa est doctori cum culpa redarguit ipsum.`"__
+++[+++En español: _Es vergonzoso culpar a los demás de las cosas que uno mismo hace._]

Pues el propio Brown anteriormente había sido Independiente,
aunque en ese momento pertenecía a la iglesia de Inglaterra y era del partido del tribunal.
Pero el alcalde, que al parecer era un gran amigo de Brown le dijo a Mead:
"`Mereces que te corten la lengua.`"
"`Y,`" agregó el registrador, "`si hablas de esta manera, tomaré ocasión contra ti.`"
A lo que Mead replicó:
"`Ustedes me prometieron que yo tendría la libertad de ser escuchado.
¿Por qué no puedo tener el privilegio de un ciudadano
inglés? Deberían avergonzarse de tales tratos.`"
Ante esto, el envidioso registrador dijo:
"`Yo te considero un enemigo de las leyes de Inglaterra,
las cuales deben ser observadas y guardadas.
Tampoco eres digno de los privilegios que tienen otros.`"
Mead, viendo que la fuerza y la violencia prevalecían ahí,
y que nada de lo que dijera serviría de algo, dijo con mente serena:
"`El Señor juzgue entre mí y ustedes en este asunto.`"

Después de esto,
lo encerraron en el "`bail-dock,`" y el registrador le encargó al jurado lo siguiente:
"`Ustedes han escuchado en qué consiste la acusación;
es por predicarle a la gente y atraer a un grupo tumultuoso tras ellos;
y que el señor Penn estaba hablando.
Si no son detenidos, verán que siguen adelante.
Hay tres o cuatro testigos que han confirmado que él sí estaba predicando ahí;
y el señor Mead no lo negó. Más allá de esto,
han escuchado por testigos sustanciales lo que se dice contra ellos.
Entonces, estamos tratando cuestiones de hecho,
a las que deben prestar atención y apegarse,
como han jurado hacerlo bajo su propio riesgo.`"
Que el registrador le dijera esto al jurado en ausencia
de los prisioneros fue verdaderamente irregular;
por lo que W. Penn, que lo oyó desde lejos,
habló en voz muy alta para que los que estaban en el tribunal pudieran escucharlo,
y dijo: "`Apelo al jurado, quienes son mis jueces, y a esta gran asamblea,
si los procedimientos del tribunal no son de lo más arbitrarios y carentes de toda ley,
al formularle al jurado su encargo en ausencia de los prisioneros.
Yo digo,
que es directamente opuesto y destructivo del indudable derecho de todo prisionero inglés,
como habla Coke en el 2 Inst.
en el capítulo de la Carta Magna.`"

El registrador, al ser inesperadamente increpado por su procedimiento extrajudicial dijo,
con una sonrisa desdeñosa: "`Vaya, _estás_ presente; me oíste, ¿cierto?`"
A lo que Penn respondió:
"`No gracias al tribunal que ordenó que me pusieran
en el '`bail-dock.`' Y ustedes miembros del jurado,
tomen nota de que no he sido escuchado,
ni podrán abandonar legalmente la sala del tribunal antes de que yo sea escuchado,
pues tengo al menos diez o doce puntos que presentar para invalidar su acusación.`"
Esta forma de hablar de W. Penn enfureció tanto al registrador que gritó:
"`¡Bajen a ese tipo! ¡Bájenlo!`"
Parece que Penn, para que se le oyera mejor,
se había subido un poco en las barandillas del '`bail-dock.`' Entonces W. Mead dijo:
"`¿Es conforme a los derechos y privilegios de un ciudadano inglés que no se nos escuche,
sino que se nos confine en el '`bail-dock`' por hacer nuestra defensa,
y que se le formule al jurado su encargo en nuestra ausencia?
Yo digo, estos son procedimientos bárbaros e injustos.`"
El registrador aún más indignado gritó: "`¡Métanlos en el agujero!
Oírlos hablar toda la noche, como de seguro harían, no es de honor para el tribunal.`"

Después de que los prisioneros fueron metidos en un agujero apestoso,
se le ordenó al jurado que saliera y acordara su veredicto;
y después de una hora y media, ocho bajaron en acuerdo, pero cuatro permanecieron arriba.
Entonces el tribunal envió a un oficial a buscarlos, y ellos bajaron;
pero el tribunal profirió muchas amenazas indecentes contra los cuatro que disentían,
y después de mucho lenguaje amenazador y un comportamiento muy dominante contra el jurado,
los prisioneros fueron llevados de regreso al estrado.
Luego se le preguntó al presidente del jurado: "`¿Qué dicen;
es William Penn culpable del asunto del que se le acusa, o no es culpable?`"
El presidente respondió: "`Culpable de hablar en Gracechurch-street.`"
La siguiente pregunta fue: "`¿Es todo?`"
A lo que el presidente dijo: "`Es todo lo que tengo en comisión decir.`"
Esta respuesta disgustó tanto al registrador que dijo:
"`¡Ustedes bien podrían no haber dicho nada!`"
Entonces el alcalde Starling dijo: "`¿Acaso no era una asamblea ilegal?
¿Seguramente quieren decir que él le estaba hablando a un tumulto
desenfrenado de gente ahí?`" A lo que el presidente replicó:
"`Mi señor, eso fue todo lo que se me comisionó decir.`"
Algunos del jurado parecían ceder ante las preguntas del tribunal;
pero otros seguían oponiéndose,
diciendo que ellos no admitían la palabra "`asamblea ilegal`" en su veredicto;
ante lo cual algunos de los miembros del tribunal
tomaron ocasión para denigrarlos con lenguaje abusivo.
Y debido a que el tribunal no quería despedir al jurado
antes de que diera un veredicto más satisfactorio,
ellos pidieron pluma y papel y volvieron a subir.
Y al regresar media hora después, entregaron el siguiente veredicto por escrito:

[.embedded-content-document.legal]
--

Nosotros, los jurados nombrados a continuación,
encontramos a William Penn culpable de hablar o predicar en una asamblea,
reunida en Gracechurch-street, el 14 de agosto pasado, de 1670;
y que William Mead no es culpable de dicha acusación.

[.signed-section-signature]
Foreman Thomas Veer, Charles Milson, Edward Bushel, Gregory Walklet, John Hammond,
John Baily, Henry Henly, William Lever, Henry Michel, James Damask, John Brightman,
William Plumsted.

--

Este veredicto fue tan altamente resentido por el alcalde y el registrador,
que sobrepasaron los límites de toda moderación y civismo.
El registrador dijo: "`Caballeros,
ustedes no serán despedidos hasta que tengamos un veredicto que el tribunal acepte.
Y serán encerrados sin comida, bebida, fuego y tabaco.
No deben pensar en abusar así del tribunal; tendremos un veredicto con la ayuda de Dios,
o morirán de hambre por ello.`"

Ahora bien, aunque el jurado había dado su veredicto,
y dado a entender que no podían dar otro; todo fue en vano.
Al ver W. Penn cómo los trataban contra toda razón, dijo: "`Mi jurado,
quienes son mis jueces, no deben ser amenazados así. Su veredicto debería ser libre,
y no forzado.
Los miembros del tribunal deberían servirles; no obstaculizarlos.
Quiero que sea hecha justicia,
y que las resoluciones arbitrarias del tribunal no
sean hechas la medida del veredicto del jurado.`"
Este modesto discurso indignó tanto al registrador, que gritó:
"`¡Ciérrenle la boca a ese charlatán, o sáquenlo de la corte!`"
Y el alcalde le dijo al jurado:
"`Ustedes han escuchado que él predicó y reunió a un grupo de personas tumultuosas,
y que ellos no sólo desobedecen el poder marcial, sino también el civil.`"
A lo que W. Penn replicó: "`Eso es un gran error.
Nosotros no hicimos el tumulto, sino los que nos interrumpieron.
El jurado no puede ser tan ignorante como para pensar,
que nosotros nos reunimos ahí con la intención de perturbar la paz civil, dado que,
en primer lugar,
se nos había impedido por la fuerza de las armas entrar a nuestra legítima casa de reunión,
y nos habíamos reunido tan cerca de ella en la calle,
como los soldados nos lo permitieron.
Y en segundo lugar, porque esta reunión no era algo nuevo,
ni estaba acompañada por las circunstancias expresadas en la acusación,
sino la que era habitual y acostumbrada entre nosotros.
Es bien sabido que nosotros somos un pueblo pacífico,
y que no podemos manifestar violencia a ningún hombre.`"

Como el tribunal estaba decidido a enviar a los prisioneros a la cárcel,
y al jurado a su cámara, Penn habló de la siguiente manera: "`En derecho,
el acuerdo de doce hombres es un veredicto,
y dado que el veredicto ya ha sido emitido por el jurado,
espero que el secretario de paz lo registre,
ya que él responderá por eso bajo su propio riesgo.
Y si el jurado trae otro veredicto contradictorio al dado, yo afirmo que han perjurado.`"
Y mirando al jurado dijo: "`Ustedes son ciudadanos ingleses; cuiden su privilegio;
no renuncien a su derecho.`"
A esto E. Bushel, uno del jurado, replicó:
"`Ni lo haremos jamás.`" Otro de los hombres del jurado alegó indisposición física,
y por lo tanto, deseaba ser despedido, pero el alcalde le dijo:
"`Estás tan fuerte como cualquiera de ellos.
Adelante, muérete de hambre entonces, mientras mantienes tus principios.`"
A esto el registrador añadió: "`Caballeros, deben contentarse con su dura suerte.
Vean si su paciencia la puede superar; pues el tribunal ha decidido tener un veredicto,
y eso antes de que puedan ser despedidos.`"
Y aunque los miembros del jurado dijeron: "`Hemos llegado a un acuerdo,
hemos llegado a un acuerdo, hemos llegado a un acuerdo,`" con todo,
el tribunal designó a varias personas para que mantuvieran
al jurado toda la noche sin comida,
bebida, fuego o cualquier otra comodidad; de hecho, ni siquiera tenían un orinal,
aunque fue solicitado.
Así prevalecieron la fuerza y la violencia.

Al día siguiente, aunque era el primer día de la semana, comúnmente llamado domingo,
el tribunal sesionó otra vez.
Los prisioneros fueron llevados al estrado,
se llamó al jurado y se le preguntó a su presidente:
"`¿Es William Penn culpable del asunto del que se le acusa, o no es culpable?
A lo que el presidente respondió como antes:
"`William Penn es culpable de hablar en Gracechurch-street.`"
Entonces el alcalde preguntó: "`¿En una asamblea ilegal?`"
Edward Bushel respondió: "`No, mi señor,
no damos un veredicto diferente al que dimos anoche; no tenemos otro veredicto que dar.`"
"`Eres,`" replicó el alcalde, "`un tipo insolente.
Tomaré acción contra ti.`"
"`He actuado conforme a mi consciencia,`" dijo Bushel.
Esto disgustó tanto al alcalde que dijo: "`¡Esa consciencia tuya me cortará la garganta!
Pero yo te cortaré la tuya en cuanto pueda.`"
Y el registrador añadió: "`Él ha inspirado al jurado;
tiene el espíritu de adivinación. Creo que puedo sentirlo.
Tendré un veredicto positivo, o morirás de hambre por ello.`"

Entonces W. Penn dijo: "`Deseo hacerle al registrador una pregunta:
¿aceptas el veredicto con respecto a William Mead?`"
A esto el registrador respondió: "`No puede ser un veredicto,
porque ustedes están acusados de conspiración. No
puede ser hallado culpable uno y el otro no.
Este no puede ser un veredicto.`"
Esto hizo que Penn dijera: "`Si '`no culpable`' no puede ser un veredicto,
entonces tú haces que el jurado y la Carta Magna sean una mera nariz de cera.`"^
footnote:[Como se mencionó en el capítulo 13,
la expresión __"`nariz de cera`"__ se refiere a una persona o cosa
que se tuerce o se balancea fácilmente en cualquier dirección.]
"`¿Cómo?,`" preguntó W. Mead, "`¿'`no culpable`' no es un veredicto?`"
"`No,`" dijo el registrador, "`no es un veredicto.`"
A esto Penn replicó:
"`Yo afirmo que el acuerdo de un jurado es un veredicto según la ley;
y si W. Mead no es culpable, se deduce en consecuencia, que yo también estoy limpio,
ya que ustedes nos han acusado de conspiración, y no es posible que yo conspire solo.`"
Después de esto el tribunal le habló al jurado e hizo que subiera de nuevo,
para obtener por la fuerza otro veredicto de ser posible.
El jurado fue llamado de nuevo y el secretario le preguntó: "`¿Qué dicen?
¿Es William Penn culpable del asunto del que se le acusa, o no es culpable?`"
El presidente respondió: "`Culpable de hablar en Gracechurch-street.`"
A lo que el registrador respondió: "`¿De qué sirve eso?
Te he dicho que obtendré un veredicto.`"
Y hablándole a E. Bushel dijo: "`Eres un tipo insolente, pondré una marca sobre ti;
y mientras yo tenga algo que hacer en esta ciudad, te tendré vigilado.`"
El alcalde, dirigiéndose a los otros miembros del jurado dijo:
"`¿No tienen más ingenio que dejarse llevar por un tipo tan lamentable?
Le cortaré la nariz.`"

Así se esforzó el tribunal por confundir al jurado; por ello,
a William Penn no le faltó buena razón cuando dijo:
"`Es intolerable que mi jurado sea amenazado de esta manera.
¿Está esto acorde con las leyes fundamentales?
¿No son estos mis propios jueces acorde con la Carta Magna de Inglaterra?
¿Qué esperanza hay de que se haga justicia cuando se amenazan
a los miembros del jurado y su veredicto es rechazado?
Me veo obligado a hablar, y me duele ver procedimientos tan arbitrarios.
¿No están buscando claramente condenar como "`tipo insolente`"
a cualquiera que no actúe de acuerdo con sus fines?
Es realmente triste ver que los jurados sean amenazados con multarlos,
matarlos de hambre o arruinarlos,
si no dan veredictos en contra de sus propias consciencias.`"
Estas expresiones tan claras molestaron tanto al registrador, que le dijo al alcalde:
"`Mi señor, tienes que tomar medidas contra este tipo.`"
Entonces el alcalde gritó: "`¡Detén su boca carcelero;
traigan grilletes y clávenlo en el suelo!`"
A esto W. Penn dijo: "`Hagan lo que quieran, no me importan sus grilletes.`"
El registrador se aventuró a decir entonces:
"`Hasta ahora nunca había entendido la razón y la prudencia
de los españoles al permitir la Inquisición entre ellos.
Y ciertamente, no nos irá bien en Inglaterra,
hasta que se establezca algo parecido a la Inquisición española.`"
Cuando se le demandó al jurado que encontrara un veredicto diferente,
y ellos respondieron que no podían dar otro, el registrador se enfureció tanto, que dijo:
"`Caballeros, no estaremos para siempre en este callejón sin salida con ustedes.
Encontrarán que después de las siguientes sesiones del Parlamento se promulgará una ley,
para que aquellos que no se conformen, no tengan la protección de la ley.
El veredicto de ustedes es nada; se mofan del tribunal.
Ahora les digo, que deben reunirse y traer un veredicto diferente o morirán de hambre,
y haré que los lleven por la ciudad como en tiempos de Eduardo III.`"

El jurado se rehusó a dar otro veredicto,
dado que ellos estaban de acuerdo con el que habían dado,
y como se mostraron indispuestos a salir de nuevo,
el alcalde mandó al alguacil que los hiciera ir.
El alguacil, levantándose de su asiento dijo: "`Vengan, caballeros, deben salir;
ustedes ven que me han ordenado hacerlos salir.`"
Con lo cual,
el jurado salió y se designó que varios los mantuvieran sin las comodidades ya mencionadas,
hasta que dieran su veredicto.
Los prisioneros fueron enviados a la prisión de Newgate,
donde permanecieron hasta la mañana siguiente.
Tras ser llevados de nuevo al tribunal y ser colocados en el estrado,
se llamó al jurado y se le preguntó:
"`¿Es William Penn culpable del asunto del que se le acusa, o no es culpable?`"
El presidente respondió: "`Ustedes ya tienen por escrito nuestro veredicto,
y nuestras manos lo han firmado.`"
El registrador impidió que el secretario leyera el papel,
y el tribunal dijo que el papel no era un veredicto.
Entonces el secretario preguntó: "`¿Qué dicen?
¿Es William Penn culpable o no culpable?`"
A esto el presidente respondió: "`No culpable.`"
Se hizo la misma pregunta con respecto a W. Mead, y el presidente respondió lo mismo:
"`No culpable.`"
Entonces el secretario le preguntó al jurado si todos decía lo mismo,
y ellos respondieron: "`Sí.`" El tribunal aún insatisfecho,
ordenó que cada persona respondiera a su nombre y diera su veredicto, lo cual hicieron,
y por unanimidad dijeron: "`No culpable.`"
El registrador, que no podía soportar esto, finalmente dijo: "`Lamento, caballeros,
que ustedes hayan seguido sus propios juicios y opiniones,
en lugar del buen y saludable consejo que se les dio.
Que Dios guarde mi vida de sus manos.
Por esto, el tribunal les impone una multa de cuarenta marcos por hombre,
y prisión hasta que se pague.`"

W+++.+++ Penn acercándose al estrado dijo: "`Exijo mi libertad,
habiendo sido liberado por el jurado.`"
"`No,`" dijo el alcalde, "`todavía están pendientes tus multas.`"
"`¡Multas!,`" replicó Penn, "`¿por qué?`" "`Por desacato al tribunal,`" dijo el alcalde.
"`Pregunto,`" dijo Penn, "`¿si está de acuerdo con las leyes fundamentales de Inglaterra,
que cualquier ciudadano inglés sea multado o penalizado,
sino por el juicio de sus pares o jurado,
ya que contradice expresamente los capítulos 14 y 29 de la Carta Magna de Inglaterra,
que dicen:
'`Ningún hombre libre debe ser multado excepto por el juramento de hombres
buenos y decentes de la localidad`"? En lugar de responder a esta pregunta,
el registrador gritó: "`¡Sáquenlo, sáquenlo! ¡Sáquenlo del tribunal!`"
Ante lo que W. Penn dijo:
"`Cada vez que insisto en las leyes fundamentales de Inglaterra, tú gritas '`sáquenlo,
sáquenlo.`' Pero no es de extrañar,
dado que la Inquisición española ocupa un gran lugar en el corazón del registrador.
Dios Todopoderoso, quien es justo, los juzgará por todas estas cosas.`"
No se le permitió decir nada más a W. Penn,
sino que él y W. Mead fueron arrastrados al '`bail-dock,`'
y de ahí enviados a la prisión de Newgate,
junto con los miembros del jurado.
Cómo fueron libertados finalmente, no lo sé.

Este juicio fue publicado después de manera impresa
con más detalle del que se expone aquí,
y se le adjuntó un apéndice en el que se demostraba no sólo la invalidez de las pruebas,
sino también lo absurdo de la acusación,
la ilegalidad de los procedimientos del tribunal, y cómo, según la Carta Magna,
los prisioneros habían sido tratados de forma contraria a la ley.
También se menciona el caso del presidente del tribunal lord Keeling,
quien por haberle puesto restricciones a los jurados, el 11 de diciembre de 1667,
un comité del Parlamento llegó a la resolución,
de que sus procedimientos habían sido innovaciones
en un juicio de hombres por sus vidas y libertades;
y que él había usado un poder arbitrario e ilegal,
que era de consecuencias peligrosas para la vida y libertad del pueblo de Inglaterra,
y que tendían a la introducción de un gobierno arbitrario.
Además, que él había infravalorado,
desacreditado y condenado la Carta Magna en un tribunal de justicia, y que por eso,
debía ser llevado a juicio a fin de recibir el castigo,
de la manera que la Casa juzgara la más conveniente y necesaria.
Dos días después, el 13 de diciembre, se resolvió que eran ilegales,
los precedentes y la práctica de multar o encarcelar
a los miembros de un jurado por veredictos.
Creo que el libro que contenía el mencionado juicio de W. Penn y W. Mead,
fue reimpreso más de una vez, porque llegó a ser muy solicitado,
pues en él se defendieron bien las libertades del pueblo y se controló el poder arbitrario.
El título del libro era, [.book-title]#Las Antiguas y Justas Libertades del Pueblo Afirmadas;#
y debajo se añadió este bien conocido verso de Juvenal:
__Sic volo, sic jubeo; stat pro ratione voluntas.__^
footnote:[Así lo deseo, así lo ordeno, mi voluntad está en lugar de la razón.]

Este asunto fue tratado más detalladamente en un
libro publicado por el abogado Thomas Rudyard,
quien demostró con cierta extensión,
el derecho de los jurados y la ilegalidad de los
procedimientos que estaban entonces en boga;
lo que presentó claramente tanto desde la ley,
como a partir de citas de libros de eminentes abogados.
Y tras haber defendido la causa de los oprimidos en varias ocasiones,
él también se convirtió en objeto de la furia persecutoria, la cual,
no podía soportar su fiel defensa de
los inocentes.
Por tanto, en el verano de este año,
los magistrados de Londres emitieron una orden de
allanamiento de su casa en la oscuridad de la noche,
con el fin de detenerlo.

La orden fue ejecutada por los soldados de un tal capitán Holford;
y al día siguiente T. Rudyard fue enviado a la prisión de Newgate por orden del tribunal,
firmada y sellada por el alcalde de Londres Samuel Starling, por William Peak,
Robert Hanson y varios otros,
bajo el pretexto de que él había "`incitado a las
personas a la desobediencia de las leyes,
e instigado y alentado a quienes se reunían en conventículos ilegales y sediciosos,
en contra de la última ley.`"
Pero este caso fue llevado delante de los magistrados del Tribunal de Causas Comunes,
en Westminster, por un __habeas corpus__^
footnote:[Es decir,
por el derecho que protege a cualquier ciudadano ante arrestos y detenciones arbitrarias.];
dicho tribunal, después de un solemne debate,
dictaminó que Thomas Rudyard había sido injustamente encarcelado e injustamente detenido;
por lo que fue puesto en libertad.
Pero al alcalde Samuel Starling, preocupado por esta liberación,
encontró nuevas estratagemas para cumplir su deseo sobre él. Pues se formuló una acusación
contra él por haber estorbado el debido proceso de la ley contra un tal Samuel Allingbridge,
pero Rudyard se defendió tan bien, que fue absuelto de este cargo;
lo que indignó tanto al alcalde,
que no mucho después de esto volvió a enviar a T.
Rudyard a la prisión de Newgate por un motivo religioso,
a saber, por haber estado en la reunión de Whitehart-court, en Gracechurch-street.
Los procedimientos contra él y contra otros por este motivo,
no fueron menos arbitrarios que los procedimientos
ya mencionados contra W. Penn y W. Mead,
por lo que Rudyard expuso su juicio y el de ellos en la prensa.
Y dado que él entendía bien la ley,
era en verdad capaz de demostrar la injusticia de estos procedimientos,
y cuán inconsistentes eran las acusaciones con las leyes del país.

Pero para evitar la redundancia, relataré poco de esos otros juicios,
ya que en ellos ocurren muchas cosas que ya han sido mencionadas en otros casos.
La manera en que el registrador John Howel estaba inclinado con respecto a la religión,
se puede deducir de lo que ya se ha dicho de su elogio a la Inquisición española.
Y a Rudyard y a sus compañeros prisioneros,
no les dio una evidencia oscura de qué religión prefería;
ya que cuando los prisioneros decían que ellos siempre
estaban en silencio y en paz en sus asambleas,
y que las leyes contra los disturbios no estaban dirigidas contra ellos,
sino contra los papistas o similares perturbadores de la paz,
el registrador respondía que los papistas eran mejores súbditos del rey que ellos;
y que los Cuáqueros eran personas obstinadas y peligrosas, y que debían ser sometidas,
o que por causa de ellos no habría vida segura.
A los prisioneros que ofrecieron defenderse de estas odiosas y sucias calumnias,
no se les permitió decir nada en su propia defensa;
sino que en lugar de oírlos fueron metidos en el
'`bail-dock`' por orden del alcalde y del registrador,
y tratados casi de la misma manera que trataron a W. Penn y a W. Mead antes.

Pero entonces prevalecía la violencia; y el registrador,
debido a su escandalosa conducta contra los Cuáqueros,
gozaba de tanto favor en el tribunal de justicia,
que el concejal J. Robinson no dudó en decirles que él merecía
cien libras por el servicio prestado en Old Bailey^
footnote:[El Tribunal Penal Central de Inglaterra y Gales.]
en las últimas sesiones.
Y la propuesta fue tan aceptada,
que el tribunal consintió en pagarle cien libras por el mencionado servicio,
a través del administrador de Londres.
Como esto era bien conocido por T. Rudyard,
mencionó el día de dicha orden--el 8 de octubre, 1670--en un libro que publicó,
y en el que mostraba que se le habían dado otras órdenes
por doscientas libras en los últimos ocho meses.
Y con el fin de reprender tales actos de manera satírica,
los llamó "`una excelente manera de aliviar la hacienda de estar
sobrecargada con el dinero para los huérfanos,`" porque mediante
estos siniestros fines y distribución de su efectivo,
la cámara estaba tan profundamente endeudada que casi era increíble.

Ahora bien, dado que Rudyard, como abogado,
conocía mejor que muchos otros la ilegalidad de estos
procedimientos contra él y sus amigos,
escribió un tratado de esos actos judiciales, que llamó [.book-title]#Segunda Parte
de Las Antiguas y Justas Libertades del Pueblo Afirmadas.#
Muchos verdaderos amantes de su país estaban complacidos con esta publicación,
porque el partido que apoyaba al papismo, y por lo tanto,
que se esforzaba por violar los derechos del pueblo,
en ese momento luchaba por tomar la delantera.

La persecución estaba entonces muy candente y fiera por todo el país,
porque se había abierto una puerta para que toda clase de tipos bajos
y malvados se hicieran de un botín al convertirse en informantes;
pues según la ley contra las reuniones,
el informante debía recibir una tercera parte de la multa impuesta.
Esto puso a trabajar a muchas personas viles,
(y entre estos algunas veces a ladrones y tipos perversos) que intentaban darle a cualquier
encuentro de Cuáqueros--aunque sólo fuera una visita social o un entierro--el nombre
de "`reunión,`" y luego juraban que allí se había celebrado una reunión. En realidad,
a veces juraban sólo suponiendo que en cierto lugar se había celebrado una reunión,
aunque los testigos no la habían visto, como lo exigía la ley.
Y ser informante se puso tan de moda,
que incluso algunos magistrados se volvieron uno de ellos.

[.centered]
__¡Quid non mortalia pectora cogis Auri sacra fames!__^
footnote:[Maldita sed de oro.
¿Hay algo que un mortal no haga por ti?]

Yo podría escribir un volumen extenso de estos hechos abominables,
si pudiera encontrar tiempo para ello; sin embargo,
de vez en cuando mencionaré algunos ejemplos,
por medio de los cuales el lector pueda suponer el resto.

Este año en Alford, en Somersetshire, en el mes llamado agosto,
fue enterrado el cuerpo de un tal Samuel Clothier,
y aunque todos se mantuvieron en silencio en el cementerio, el juez, un tal Robert Hunt,
multó a algunos de los que habían estado en el entierro
por haber asistido a esa supuesta reunión.

Ocurrió que en Nottingham a finales de este año, el juez Penniston Whaley,
quien había multado a muchos de los llamados Cuáqueros por asistir a sus reuniones religiosas,
durante las sesiones del tribunal animó al pueblo a perseguir a los Cuáqueros sin piedad,
diciéndoles: "`Endurezcan sus corazones contra ellos;
pues la ley del año 35 del reinado de Elizabeth no está hecha contra los papistas,
ya que la iglesia de Roma es una iglesia verdadera, así como cualquier otra iglesia.
Pero estos Cuáqueros están equivocados y son personas sediciosas.`"
Por estas palabras uno puede fácilmente juzgar a
qué religión estaba inclinado este juez de paz;
pero muchos de estos pretendían ser Protestantes,
para poder desempeñar cargos honorables.
No menciono a muchas personas que por ser golpeadas,
empujadas y pisoteadas en sus reuniones quedaron tan gravemente lastimadas,
que algunas sobrevivieron poco tiempo después de cometida la violencia sobre ellas,
y sintieron el dolor o escozor de la misma hasta su muerte.

A mediados del verano de este año, Thomas Bud falleció en Ivelchester, en Somersetshire,
después de haber estado prisionero cerca de ocho años y medio,
porque por razones de consciencia no había podido jurar.
Algunas horas antes de su muerte se le oyó decir,
que él había renovado su pacto con Dios y estaba bien satisfecho;
que creía que Dios lo sostendría con la mano derecha de Su justicia;
y que se regocijaba y le agradecía a Dios porque todos sus
hijos caminaban en el camino del Señor.

En Warborough, en Oxfordshire,
los llamados Cuáqueros también sufrían los más graves abusos en sus reuniones,
y ni siquiera las mujeres de edad avanzada se salvaban.
Esto a menudo hacía que los gritos de niños inocentes subieran al cielo,
cuando veían a sus madres maltratadas de esa manera.
Porque en esta época era común que los magistrados mismos quebraran sus
bastones en pedazos sobre los cuerpos de los que se habían reunido,
y a veces, encontraban otros palos para hacer uso de ellos.
Las mujeres a menudo eran desnudadas de sus prendas superiores,
y dichos abusos eran con frecuencia acompañados del despojo de bienes.
Sin embargo,
el hecho de que los perseguidores se enfurecieran de esa manera no es de extrañar,
si consideramos que algunos eran incitados por sus maestros religiosos;
un ejemplo de lo cual fue dado por un tal Robert Priest del mismo lugar,
quien dijo en su sermón que aunque las leyes del rey fueran contrarias a la ley de Dios,
debían ser obedecidas.
Muy distinta a la doctrina del apóstol Pedro y Juan,
cuando les dijeron a los judíos del concilio:
"`Juzgad si es justo delante de Dios obedecer a vosotros antes que a Dios.`"^
footnote:[Hechos 4:19]

En Northamptonshire, donde la persecución era también muy acalorada,
el obispo de Peterborough dijo públicamente en la '`casa del campanario,`'
después de haberles ordenado a los oficiales a poner en ejecución
la última ley contra las reuniones sediciosas:
"`Esta ley ha hecho su trabajo contra todos los fanáticos, excepto los Cuáqueros;
pero cuando el Parlamento sesione otra vez, se emitirá una ley más fuerte,
no sólo para quitarles sus tierras y bienes, sino también para venderlos como esclavos.`"
Así avivaban los eclesiásticos el fuego de la persecución.

En York, el concejal Richardson también impulsaba ferozmente el despojo de bienes;
e incluso los jovencitos, hombres y mujeres menores de dieciséis años, y por tanto,
no sujetos a la pena de la ley, eran multados.
Y cuando los alguaciles se mostraban renuentes a ayudar en tales robos se les gruñía,
y uno fue perseguido por no cumplir con su deber,
pues se había negado a quitarle la capa a un hombre.
Pero si yo mencionara los malos tratos cometidos en todos los condados y lugares,
¿cuándo llegaría a una conclusión?

Thomas Green, un hombre serio, con quien he estado muy familiarizado,
estando en oración en una reunión en Sawbridgeworth, en Hertforshire,
fue jalado de sus rodillas y arrastrado.
Y al ser llevado delante de los magistrados Robert Joslin y Humphrey Gore,
estos le impusieron una multa de veinte libras por
hablar o predicar en la mencionada reunión,
y les otorgaron una orden judicial a los alguaciles
John Smith y Paul Thomson para confiscar sus bienes;
con lo cual, ellos entraron en la tienda de dicho Thomas Green, en Royston,
y tomaron tantos bienes hasta el valor de cincuenta libras.
Pero esto no apagó su celo; porque como un verdadero y fiel pastor,
continuó alimentando al rebaño y edificando a la iglesia con su don,
en el que era muy útil.

En otro momento,
los magistrados Peter Soames y Thomas Mead dieron una orden judicial
para confiscar el valor de veinte libras de los bienes del
mencionado Thomas Green por predicar en una reunión en Upper-Chissel,
en Essex.
Los oficiales entraron en la tienda de Thomas Green y se llevaron todo lo que pudieron,
y no dejaron más que una simple madeja de hilo en la tienda,
que se había caído al suelo y no fue observada por ellos.

Theophilus Green también sufrió gran despojo de sus bienes;
porque tras predicar en una reunión en Kingston-upon-Thames,
fue puesto en el cepo por algunas horas y multado con veinte libras.
Y después de predicar los siguientes tres Primeros-días en Wadsworth,
fue multado con la misma cantidad por cada ocasión.

La semana siguiente, Theophilus Green,
estando en Uxbridge y visitando a algunos niños pobres, hijos de sus amigos,
cuyo padre y madre habían muerto en corto tiempo uno tras otro,
tomó a dos de ellos como propios y se ocupó de la colocación del resto.
Y quedándose ahí hasta el Primer-día,
fue a la reunión y exhortó a sus amigos a mantener sus reuniones
en el nombre de Jesús. Después de decir estas palabras,
el alguacil y un informante entraron y se lo llevaron ante el juez Ralph Hawtrey,
que le impuso una multa de veinte libras, y lo envió a la prisión de Newgate, en Londres,
con una orden judicial en la que era acusado de exhortar
a la gente a mantener sus reuniones en el nombre de Jesús,
a pesar de que las leyes de los hombres eran contrarias.
Se emitieron órdenes de confiscar sus bienes por el monto de las multas ya mencionadas,
(cuya cantidad sumaba cien libras y cinco chelines) y llegaron
y abrieron la puerta de su casa y se llevaron todo lo que encontraron,
sin dejarle cama ni taburete.
Y después de haber permanecido prisionero tres meses,
fue llevado con siete más a la casa de sesiones en Hicks`' Hall,
y ahí se les presentó el juramento de lealtad y supremacía.
A esto Theophilus Green respondió:
"`Como ciudadano inglés,
yo debería ser absuelto o condenado por la causa por la que fui encarcelado,
antes de responder por cualquier otro asunto o causa.
Además, considero que he sido ilegalmente encarcelado,
ya que he sido multado y enviado a prisión por el mismo hecho.`"
Pero ellos le dijeron que él debía responder primero si juraría o no,
y luego sería oído. Pero como siguió negándose a jurar,
fue enviado de nuevo a prisión junto con los demás;
y después de ser llamado de nuevo y continuar negándose a quebrantar el
mandamiento de Cristo de '`no jurar en ninguna manera,`' se les leyó la
sentencia de premunire a él y a sus compañeros prisioneros,
y así continuaron en prisión más de dos años,
hasta que fueron liberados por la _Ley de Gracia_ del rey.

Las reuniones de los llamados Cuáqueros eran miserablemente perturbadas en Horslydown,
en el condado de Surry.
El 25 de septiembre varios mosqueteros entraron en la casa de reunión,
y después de arrastrar a la calle a los que estaban presentes,
los soldados arremetieron con violencia cabalgando entre ellos, golpeándolos,
lastimándolos y empujándolos con sus carabinas^
footnote:[Rifle de cañón corto que llevaban los jinetes.]
y con las culatas de sus mosquetes, a tal punto,
que más de veinte personas resultaron heridas y gravemente golpeadas.
De hecho, estos tipos eran tan desesperadamente malvados,
que una partida de jinetes intentó cabalgar sobre estas personas indefensas,
pero los caballos, siendo más misericordiosos que los jinetes, no avanzaron;
entonces con las riendas los hicieron girar y retroceder,
esforzándose por hacer cualquier maldad que pudieran.
El 2 de octubre, este pacífico pueblo impedido de entrar en su lugar de reunión,
adonde llegó una partida de infantería y una de caballería,
fue lastimado con no menos violencia que la semana anterior; de manera tal,
que golpeándolos y aporreándolos quebraron varios de sus mosquetes, picas y una carabina,
y más de treinta personas resultaron tan gravemente heridas
y golpeadas que su sangre quedó derramada en las calles.

El 9 del mismo mes, los soldados tanto de caballería como de infantería,
llegaron de nuevo a la reunión del lugar ya mencionado,
y uno de ellos que tenía una pala,
lanzó la tierra y el barro de los canales sobre hombres y mujeres.
Después de esto llegaron y cayeron sobre ellos los
soldados de la caballería y de la infantería,
golpeándolos y derribándolos sin respetar la edad o el sexo,
hasta que hicieron brotar la sangre de muchos.
Y cuando algunos de los habitantes, movidos a compasión,
se llevaron a algunos de ellos a sus casas para salvarles la vida,
los soldados abrieron las puertas a la fuerza y los arrastraron de nuevo a la calle,
y les arrancaron los sombreros para poder golearlos en la cabeza desnuda;
de modo que muchos resultaron con sus cabezas gravemente heridas.
Además, algunos soldados desgarraron la ropa de las mujeres por la espalda,
y luego las arrastraron por el barro al lado de sus caballos.
Algunos de los soldados de infantería metieron sus manos de la
manera más vergonzosa debajo de los abrigos de las mujeres;
y uno golpeó dos veces con su mosquete el vientre
de una mujer que estaba embarazada y una vez el pecho,
mientras que otro le arrojaba tierra en la cara,
de modo que abortó. Ese día más de cincuenta personas
resultaron gravemente heridas y golpeadas.

El 16 del mencionado mes, reuniéndose de nuevo este diligente pueblo para adorar a Dios,
una gran partida de caballería e infantería llegó
y cayó sobre ellos golpeándolos tan violentamente,
como si hubieran querido matarlos a todos en el acto,
de modo que la sangre corría por las orejas de muchos.
Y cuando uno de los alguaciles trató de impedir que
la perversa cuadrilla derramara más sangre,
cayeron sobre él también y le rompieron la cabeza.
Cuando se les reprendió por ese cruel trato, algunos dijeron:
"`Si ustedes supieran las órdenes que tenemos,
dirían que los hemos tratado con misericordia.`"
Y cuando se les preguntó:
"`¿Cómo pueden tratar de esta manera a un pueblo que no
ofrece resistencia ni oposición?,`" respondieron,
"`preferiríamos y sería mejor, si ustedes se resistieran y se opusieran.`"
De esto se desprende claramente,
que esta maldad era realizada con el fin de provocar oposición,
para poder tener una excusa para bañar sus manos con la sangre de estos sufrientes,
y de esa manera, haber tenido sus vidas y sus bienes como presa.
Por tanto, se creyó conveniente informar al rey y a su consejo de esa bárbara crueldad;
lo cual, tuvo tal efecto, que se detuvieron algunas de estas excesivas crueldades,
aunque los abusos no cesaron completamente.

Sucedió por este tiempo que Solomon Eccles llegó a Cork, en Irlanda,
y entró en la catedral,
donde el sacerdote Benjamín Cross predicaba con sobrepelliz Episcopal.
Este sacerdote anteriormente había sido un predicador Presbiteriano en Dorsetshire,
Inglaterra, y ahí había dicho que él prefería ir a la hoguera y ser quemado,
antes que ponerse una sobrepelliz;
pero ahora se había convertido en un traidor con fines de lucro.
Después de que terminó su sermón y concluyó con una oración, Solomon Eccles dijo:
"`La oración del perverso es abominación para el Señor.`" Y conociendo
el engaño de este sacerdote y su condición de apóstata,
agregó: "`¿Qué se le hará al hombre que naufraga de la buena consciencia?`"
Por esto, S. Eccles fue capturado y enviado a prisión por el alcalde, donde,
después de permanecer diez días, fue acusado de ser un vagabundo,
y sin ningún interrogatorio fue azotado por las calles de Cork,
desde North-Gate hasta South-Gate, recibiendo cerca de noventa latigazos,
y luego fue expulsado de la ciudad.
Anteriormente hemos visto algunos ejemplos de su gran celo;
y aunque en algunos aspectos pudo haberse dejado llevar demasiado por él,
aun así dio pruebas de tener un corazón sincero.
Porque una vez, poco tiempo después de esto, le dijo a un tal John Story,
(que se había lanzado a una gran altivez y arrogancia) que era
la palabra del Señor que él debía morir ese año. Sin embargo,
Eccles mismo dijo después, tanto en Londres como en Bristol, y en otros lugares,
que él no había dicho eso según el consejo del Señor,
sino que había sido en su propia voluntad y desde su propia mente adelantada.
También confesó que había sentido la ira del Señor sobre él,
por haberle llamado a sus propias palabras, palabra del Señor;
de lo cual se arrepintió verdaderamente.

Al principio del año 1671, G. Fox estaba en Londres,
y aunque seguía débil después de un tiempo de fuerte enfermedad, no dejó de predicar.
Por esta época hizo la siguiente oración al Señor, la cual puso por escrito:

[.embedded-content-document.prayer]
--

¡Oh, Señor Dios Todopoderoso!
Prospera la Verdad y preserva la justicia y la equidad en la tierra,
y derriba toda la injusticia e iniquidad, la opresión y falsedad,
la crueldad e inmisericordia en la tierra,
para que la misericordia y la justicia puedan florecer.

¡Y, oh, Señor Dios!
Establece y fija la verdad y presérvala en la tierra;
y derriba en la tierra todo desenfreno, vicio, prostitución y fornicación;
y a ese espíritu de rapiña, que hace y conduce a las personas a no tener estima de Ti,
oh, Dios, ni de sus almas, ni de sus cuerpos, ni del Cristianismo, ni de la modestia,
ni de la humanidad.

¡Y, oh, Señor!
Pon en el corazón de los magistrados acabar con toda impiedad, violencia, crueldad,
profanación, maldición y juramento;
y derribar todos los prostíbulos y casas de juego que corrompen a la juventud y al pueblo,
y los alejan del reino de Dios, donde nada impuro puede entrar;
porque tales obras llevan a las personas al infierno.
Por Tu misericordia derriba todas estas cosas en la nación para que tu ira, oh, Dios,
deje de venir sobre la tierra.

[.signed-section-signature]
G+++.+++ Fox

[.signed-section-context-close]
Esta oración fue escrita el 17 en la noche, del mes Dos, de 1671.

--

G+++.+++ Fox, que pensaba que su esposa estaba en libertad,
comprendió entonces que los enemigos de ella, a pesar de la orden del rey de liberarla,
habían encontrado los medios para mantenerla en prisión. Por lo tanto,
no se permitió ningún descanso hasta que por medio de la
ayuda de otros obtuvo del rey un descargo bajo el gran sello,
para liberarla tanto a ella como a su patrimonio,
después de que había sido prisionera por diez años en total y en diferentes momentos,
y bajo la sentencia de premunire.
Él le mandó esta orden real inmediatamente a ella, y así quedó en libertad.

Ahora bien, como en ese momento el calor de la persecución empezó a enfriarse,
se sintió inclinado a hacer un viaje a América,
para visitar a sus amigos ahí. Le dio aviso de esta intención a su esposa por carta,
y le pidió que llegara a Londres; y ella lo hizo.
Y tras despedirse de ella, se embarcó a finales del verano con rumbo a América,
y con varios de los amigos que le acompañaban.

Ahora, mientras lo dejo a bordo del barco,
no puedo dejar de mencionar que este año apareció
en Londres un ingenioso panfleto con este título,
_Una Manera Fácil de Obtener Dinero cum Privilegio_
+++[+++es decir, sin temor ni obstáculos],
publicado para la sociedad de informantes.
Este libro contenía una reprimenda satírica para los informantes,
que comenzaba con estas palabras: "`A todos ustedes que pueden trabajar, pero no quieren;
y a todos los que por otras formas de extravagancia se han metido en deudas,
obligaciones y otras necesidades; para su rápido abastecimiento y futuro sostén,
hay una oportunidad al alcance de sus manos tanto segura y provechosa, como honorable.
Esta es, convertirse en informantes.`"

A continuación el autor dijo: "`Esta es una manera fácil,
ya que sólo involucra buscar cualquier casa, granero o establo,
donde haya cinco personas juntas, además de los de la familia.
Aunque no se diga una palabra, si tan solo juran que es un conventículo,
entonces es un conventículo.
No importa si nunca hubo un pensamiento en los corazones de las personas
de conspirar o tramar insurrecciones (para lo que fue hecha la ley),
ya que por el mero hecho de estar reunidas es suficiente para multarlas
con cinco chelines por cabeza la primera vez,
y veinte libras por la casa; y la segunda vez diez chelines por cabeza,
y puede que la segunda vez puedan obtener veinte libras más por la casa,
aunque la ley no lo conceda.
De todas las multas la tercera parte es de ustedes.
Esto lo obtendrán fácilmente, pues los jueces temen el poder de ustedes,
dado que están protegidos por la ley; en realidad, ellos no los cuestionarán mucho,
para no ser tomados como fanáticos.
¿Pueden sus corazones desear más? ¿Quién no querría ser informante?`"

En cuanto a la rentabilidad de este empleo, el autor dijo:
"`Además de veinte libras y diez chelines por cabeza por una reunión,
si pueden tentar a cualquiera de los presentes, con preguntas u otras provocaciones,
a decir una palabra para responderles,
eso servirá para hacer de esa persona un predicador, y entonces,
por la primera transgresión son veinte libras y por la segunda cuarenta.
No importa qué se diga, o con qué propósito;
si ustedes tan solo juran que oyeron a cierta persona decir una palabra,
es suficiente para convertirlo en predicador.`"

De esta manera trató el asunto el autor,
sacando del camino todas las dificultades y escrúpulos que cualquiera habría objetado;
y aunque lo hizo de manera cómica, lo que dijo fue tan firme y enérgico,
que dio pruebas de ser un hombre de entendimiento, además de gran ingenio.
Porque, aunque de manera ingeniosa demostró lo abominable del oficio de ser informante,
aun así lo propuso como seguro en todo sentido; ya que nunca resultaba en pérdida,
sino siempre en ganancia segura.
Además dijo:
"`Y cuando a todos estos infalibles beneficios se les añade el honor de la posición,
¿qué más puede desear uno?
Porque, ¿no sería honorable en verdad,
que se les ordene a los magistrados y a los oficiales militares
que sigan a un informante dondequiera que vaya?
Y para obtener este alto cargo, uno no necesita pagar un gran costo para comprarlo,
ni romperse los sesos estudiando;
ya que desde el primer conventículo podrían comenzar como profesionales.`"
Pero, de qué profesión religiosa eran estos informantes,
el propio autor no parece saberlo.
Porque "`no deben ser judíos,`" dijo, "`porque éstos no debían codiciar el buey,
ni el asno, ni nada que fuera de su prójimo.
Ni tampoco pueden ser gentiles, porque según Pablo,
los gentiles tenían una consciencia que los acusaba,
y '`hacían por naturaleza las cosas de la ley,
teniendo la ley escrita en sus corazones.`' Y por ningún medio pueden ser Cristianos;
porque éstos dicen que han abandonado al diablo y todas sus obras,
y todos los deseos de la carne, y que no herirían a nadie de palabra ni de hecho.`"

Ahora regreso a George Fox, a quien dejamos en el barco rumbo a América.
Durante su viaje sufrió mucho en su cuerpo;
porque las consecuencias de las muchas heridas y golpes que había recibido anteriormente,
y de las aflicciones y enfermedades que había contraído en Inglaterra por el frío,
las privaciones y largos encarcelamientos,
volvieron a recaer sobre él ahora que estaba en el mar y le causaron gran dolor.
Y después de haber estado siete semanas y unos días en el mar, él,
junto con sus compañeros de viaje, llegaron a salvo a la isla de Barbados.
Lo que le sucedió ahí está ampliamente descrito en su diario.
Muchos de los hombres importantes de ese lugar, especialmente el gobernador,
le mostraron mucha amabilidad.
Y después de edificar a sus amigos en varias ocasiones,
y exhortarlos a mantener el buen orden, tanto en las cosas relacionadas con la iglesia,
como en el correcto gobierno de sus esclavos, y habiendo recuperado su salud,
partió de la isla después de una estancia de tres meses y se embarcó hacia Jamaica.
No había pasado mucho tiempo ahí cuando Elizabeth Hooton (quien
ha sido mencionada varias veces en esta obra) partió de esta vida,
habiendo estado bien el día anterior a su muerte; y así terminó ella sus días,
en un buen estado de ánimo.
Después de haber estado ahí unas siete semanas, completó su servicio a su satisfacción.

Al principio del año 1672 se embarcó hacia Maryland, donde al llegar,
él y sus compañeros viajaron a través de los bosques y páramos, pantanos y grandes ríos,
hacia Nueva Inglaterra.
En el camino tuvo algunas oportunidades de hablar con los indios y sus reyes;
y en otros momentos se topó con casos notables, todo lo cual, por asuntos de brevedad,
paso en silencio.
También fue al pueblo anteriormente llamado New Amsterdam, cuyo nombre es ahora New York.
Allí se alojó en la casa del gobernador y también
tuvo una reunión ahí. De ahí regresó a Maryland,
y también fue a Virginia y a Carolina,
y así pasó más de un año viajando de un lado a otro en América.

Mientras estaba ahí, Inglaterra y Francia entraron en guerra contra Holanda,
y aunque todavía tengo ese tiempo fresco en mi memoria,
y la maravillosa manera en la que le plació al Señor salvar
a nuestro país de ser completamente invadido y sometido,
no mencionaré esas cosas, dado que han sido ampliamente expuestas por otros escritores.
Sin embargo, mencionaré rápidamente algo de la notable exaltación de William III,
príncipe de Orange, quien luego llegó a ser rey de Gran Bretaña.

Ya he dicho en su debido lugar, que mediante un edicto perpetuo,
se intentó evitar que llegara a ser alguna vez estatúder^
footnote:[Estatúder era un cargo político de los Países Bajos,
que recaía en nobles que representaban a las provincias neerlandesas.]
o diputado.
Pero, a pesar de lo fuerte que fue el juramento de dicho edicto,
el cielo lo anuló y rompió las ataduras de éste por medio del pueblo común de la nación;
porque cuando los franceses entraron en la provincia
de Utrecht y todo parecía estar en confusión,
las mujeres y muchos otros de la multitud forzaron a los magistrados a romper sus juramentos,
y a restaurar al joven y magnánimo príncipe William
al honor y dignidad de sus renombrados ancestros.
El miserable destino de los dos hermanos, John y Cornelius de Wit,
que habían sido los principales instrumentos en la redacción del mencionado edicto perpetuo,
y fueron asesinados y descuartizados de la manera
más abominable por los habitantes de La Haya,
no fue sin buena razón desaprobado por muchas personas importantes y serias.
Es cierto, que fue un gran error que ellos actuaran de esa manera,
pareciendo así que le ponían límites al Todopoderoso,
pero no creo que la intención de ellos fuera esa;
creo que anularon el cargo de estatúder,
porque juzgaron que era conducente al beneficio del país. Después de que fueron asesinados,
la viuda de Cornelius de Wit parecía tener la firme creencia
de que ellos habían entrado en la gloria eterna;
porque aunque por un tiempo después de la muerte de ellos estuvo bajo una gran preocupación,
considerando que la salida de ellos de esta vida había sido súbita e imprevista;
finalmente, una mañana temprano, ya fuera en un sueño o una visión,
afirma haberlos visto en una nube en una forma gloriosa,
con las manos levantadas y vestidos con ropas blancas y puras.
Esta visión le quitó toda su anterior preocupación y temor,
y quedó plenamente satisfecha con respecto al bienestar eterno de ellos.
He recibido este relato de varias personas creíbles,
quienes dijeron que la habían obtenido de la propia boca de ella;
y todas concordaron en las circunstancias importantes.

En Inglaterra,
donde se observó que la persecución por religión durante
la guerra no podía ser sino perjudicial para el público,
el rey publicó una declaración por la que se suspendía la ejecución de las leyes penales.
Pero como los Papistas, contra quienes la mayoría de estas leyes habían sido dictadas,
obtuvieron así la libertad de entrar a cargos de confianza,
muchos de los ciudadanos se intranquilizaron por ese motivo; al punto,
de que en el año 1673, el Parlamento le mostró su desagrado al rey diciéndole,
que los estatutos penales acerca de asuntos eclesiásticos no podían ser suspendidos,
excepto por una ley del Parlamento.
El rey, que necesitaba dinero para continuar la guerra,
cedió un poco ante el Parlamento con respecto a los sacerdotes Papistas y Jesuitas,
consintiendo que las leyes contra ellos continuaran en vigor.

G+++.+++ Fox regresó este verano a Inglaterra y llegó a Bristol,
de lo cual dio aviso a su esposa por carta.
Ella no tardó en ir a verlo, y con ella llegó su yerno Thomas Lower, y dos hijas de ella.
Su otro yerno, John Rouse, acompañado por William Penn y algunos otros,
también llegaron de Londres; y como en ese momento había una feria en Bristol,
llegaron muchos otros amigos de otras partes del país. Por tanto,
se celebró una gran reunión allí,
en la que G. Fox predicó de los tres principales maestros, a saber:
Que Dios había sido el primer maestro del hombre y de la mujer en el paraíso;
y que mientras se habían mantenido en la enseñanza de Dios,
se habían mantenido en la imagen de Dios, y en la justicia,
santidad y dominio sobre todo lo que Dios había hecho.
Pero después de haber escuchado la falsa enseñanza de la serpiente,
que estaba fuera de la verdad y había desobedecido a Dios,
habían perdido la imagen de Dios--es decir, la justicia y la santidad--y así,
bajo el poder de Satanás,
habían sido expulsados del paraíso. Que esta serpiente había sido el segundo maestro,
y el hombre al seguir su enseñanza,
había entrado en la miseria y en la caída. Que Jesucristo, entonces,
era el tercer maestro, de quien Dios había dicho: "`Este es mi Hijo amado,
en quien tengo complacencia; a Él oíd;`" y el Hijo mismo había dicho:
"`Aprended de mí.`" Que Él era el verdadero maestro del evangelio que nunca había caído,
y por tanto, debía ser oído en todas las cosas, ya que era el Salvador y el Redentor,
y habiendo dado Su vida, había comprado Sus ovejas con Su sangre preciosa.
De este tema habló ampliamente en la mencionada reunión.

Después de permanecer un tiempo en Bristol, se fue a Gloucestershire;
y yendo de ahí a Oxfordshire, finalmente llegó a Londres,
donde la persecución en ese momento no era tan acalorada como antes,
pero los Bautistas y Socinianos^
footnote:[Doctrina defendida por L. Socino y por su sobrino F. Socino,
reformadores naturales de Siena del siglo XVI, que negaba la Trinidad y, particularmente,
la divinidad de Jesucristo.]
se mantenían muy activos en la tergiversación de los Cuáqueros,
al publicar varios libros contra ellos en los que
afirmaban que los Cuáqueros no eran Cristianos.
Pero estos perversos libros no quedaron sin respuesta,
ni las falsedades que contenían sin refutar.

Después de que G. Fox había estado un tiempo en Londres,
fue con su esposa y Thomas Lower a Worcester;
y cuando él le indicó a ella que era probable que una prisión fuera su porción,
ella pareció (no sin razón) afligida por la noticia.
No mucho después de esto G. Fox realizó una reunión en Armscot,
en la parroquia de Tredington, y después de que terminó la reunión, él y Thomas Lower,
sentados en el salón y conversando con algunos amigos,
fueron tomados prisioneros el 17 de diciembre y enviados
a la cárcel de Worcester por el juez Henry Parker,
bajo el pretexto de que habían celebrado grandes reuniones
que podrían ser perjudiciales para la paz pública.
Su esposa y la hija de esta, regresaron entonces al norte;
y cuando pensó que ella ya había llegado a la casa,
le escribió una breve carta y la exhortaba a estar contenta con la voluntad de Dios.
También le escribió una carta a lord Windsor, que era teniente de Worcestershire,
y otra a los magistrados, en la que les informaba de su encarcelamiento,
y de que él no había sido capturado en una reunión,
sino en una casa donde tenía algunos negocios.
También señaló que tenía la intención de visitar a su madre,
de lo que en ese momento estaba impedido, y que no podía obtener su libertad.
Sin embargo, Thomas Lower habría podido ser liberado si así lo hubiera querido,
porque su hermano, el Dr. Lower, al ser uno de los médicos del rey,
había conseguido que un tal Henry Savil le escribiera al
mencionado lord Windsor para que liberara a Thomas Lower.
Pero su amor por su suegro G. Fox era tal,
que guardó dicha carta en su bolsillo y nunca la envió;
y así ambos continuaron prisioneros.

Ahora, mientras los dejo en prisión, regreso una vez más a Miles Halhead,
de quien ya se ha hecho mención. Estando en Plymouth este año,
se sintió movido a ir a ver a John Lambert, quien después de haber sido general,
ahora estaba confinado a prisión perpetua en una pequeña isla no lejos de Plymouth,^
footnote:[Isla Drake]
como se ha dicho en su debido lugar.
Halhead llegó a dicha isla, y aunque encontró una fuerte guardia de soldados,
obtuvo permiso de ver a J. Lambert; y al llegar a donde él le preguntó: "`Amigo,
¿es tu nombre John Lambert?`"
A lo que Lambert respondió: "`Sí.`" Esto hizo que Miles le dijera: "`Entonces te pido,
amigo,
que escuches lo que el siervo del Señor tiene que
decirte;`" y continuó de la siguiente manera:
"`Amigo, el Señor Dios hizo uso de ti y de otros para la liberación de Su pueblo,
y cuando clamaste a Él, Él te liberó en tu angustia, como en Dunbar y en otros lugares,
y puso en tus manos la oportunidad de hacer el bien;
y tú prometiste que harías grandes cosas por el pueblo del Señor. Pero, en verdad,
John Lambert,
pronto olvidaste las promesas que le hiciste al Señor aquel día y momento de gran angustia,
y volviste el filo de tu espada contra los siervos y siervas del Señor,
a quienes Él había enviado para declarar Su verdad eterna; e hiciste leyes,
y consentiste leyes, y permitiste que se hicieran leyes contra el pueblo de Dios.`"

A esto Lambert dijo: "`Amigo, quiero que sepas,
que algunos de nosotros nunca hicimos leyes, ni consentimos leyes para perseguirte a ti,
ni a ninguno de tus amigos;
porque siempre estuvimos en contra de la persecución.`" A esto Miles replicó:
"`Puede que sea así;
pero las Escrituras de verdad se cumplen contra los mejores de ustedes;
porque aunque tú y algunos otros no hayan dado su consentimiento
para hacer leyes contra el pueblo del Señor,
permitieron que fueran hechas y ejecutadas;
y cuando el poder y la autoridad estaban en sus manos, habrían podido hablar,
y los siervos y siervas del Señor habrían sido liberados de las manos de los devoradores.
Pero no se halló a nadie entre ustedes que defendiera la causa del inocente; y así,
el Señor Dios de vida se entristeció con ustedes,
porque despreciaron al Señor y a Sus siervos,
y empezaron a establecer sus propios intereses, y a añadir campo a campo, casa a casa,
y a engrandecer sus nombres en la tierra.
Entonces el Señor les quitó el poder y la autoridad, la hombría y la audacia,
y los hizo huir delante de sus enemigos, y sus corazones desmayaron de temor;
y algunos terminaron sus días en angustia y tristeza,
y algunos yacen en huecos y cuevas hasta el día de hoy.
Así, pues, el Señor Dios del cielo y de la tierra,
le dará a cada uno la recompensa justa según sus obras.
Por tanto, mi querido amigo, valora el gran amor de Dios hacia ti,
quien no ha entregado tu vida en las manos de los devoradores,
sino que te ha dado tu vida por presa y tiempo para prepararte,
para que acabes tus días en paz.
Ciertamente el Señor es bueno para con todos los que le temen y creen en Su nombre;
porque aunque todos los poderes de la tierra se levantaron
contra el pobre e inocente pueblo,
el Señor Dios de vida y amor estuvo con ellos y defendió su causa,
aunque todos los hombres los despreciaban.
Y ciertamente, '`el mejor era como espino;
el más recto entre ellos como zarzal.`' Si el Señor no hubiera defendido nuestra inocencia,
no tendríamos un ser en la tierra de nuestro nacimiento.
Pero gloria a Su nombre para siempre, porque no ha permitido que venga contra Su pueblo,
que cree en Su nombre, más de la ira del hombre, ni leyes, ni decretos de hombres,
que lo que ha sido para Su honor y para Su gloria,
y para el eterno bien de todos Su hijos, hijas y siervos.
Y lo demás, el Señor Dios de vida y amor lo ha restringido hasta este día. ¡Gloria,
y honor, y vivas y eternas alabanzas sean dadas y devueltas al Señor Dios y al Cordero,
por los siglos de los siglos!`"

Así terminó Halhead su discurso, y Lambert, que lo había escuchado con gran agrado,
le pidió que se sentara, lo que Halhead hizo.
Entonces Lambert pidió cerveza y le dio a beber; después de lo cual le dijo: "`Amigo,
creo que me hablas en amor, y así lo tomo, en amor.`"
Y luego le preguntó si él había estado en la batalla de Dunbar.
Y después de que Halhead respondió: "`No;`" le preguntó:
"`¿Cómo sabes cuánto peligro corrimos en ese momento?`"
Entonces Halhead le contó que él había pasado por ese camino poco después de la batalla,
y al ver el pueblo de Dunbar, el terreno alrededor de él donde yacía el ejército inglés,
que el mar estaba a un lado, las colinas y montañas al otro,
y que el gran ejército escocés había estado delante y detrás del ejército inglés,
había considerado seriamente el gran peligro en el que habían estado los ingleses,
y había pensado en la gran deuda de los ingleses al Señor por su liberación,
para que lo sirvieran en verdad y rectitud de corazón todos los días de sus vidas.
"`En verdad, John,`" dijo entonces Halhead a Lambert,
"`yo nunca antes había visto tu rostro hasta ahora,
aunque en tiempos de Oliver Cromwell fui llevado ante muchos otros comandantes ingleses.`"
Entonces Lambert le preguntó ante quiénes había estado,
y Halhead nombró a los generales Fleetwood y Desborough,
al mayor Blackmore y al coronel Fenwick,
delante del cual había estado cuando era gobernador de Edimburgo.
Entonces Lambert dijo que él sabía que la mayoría de esos hombres habían sido muy moderados,
y que ellos siempre habían estado en contra de la persecución. A esto Miles replicó:
"`En efecto, ellos fueron muy moderados,
y no querían ser vistos persiguiendo o siendo severos con el pueblo del Señor,
pero permitieron que otros la realizaran,
e hicieron poco caso de los sufrimientos del pueblo de Dios;
de modo que no se halló a nadie que defendiera nuestra causa,
sino al Señor nuestro Dios.`"
A esto Lambert dijo:
"`Pero aunque tú y tus amigos sufrieron persecución y aflicciones en ese tiempo,
tu causa ahora no es peor por todo eso.`"
"`Eso es muy cierto,`" respondió Miles,
"`pero déjame decirte algo con toda la franqueza de mi corazón,
que eso no es gracias a ti ni a los otros comandantes,
sino a la gloria del Señor por los siglos de los siglos.`"
Miles conversó con Lambert, su esposa y sus dos hijas cerca de dos horas,
y después de descargar su consciencia se despidió de ellos y se separó con amor.

Ahora bien, antes de dejar a Halhead,
insertaré aquí una copia de una carta que él le escribió a G. Fox en el año 1674,
quien estaba prisionero en la cárcel de Worcester.
Dicha carta es la siguiente:

[.embedded-content-document.letter]
--

[.salutation]
George Fox,

Tú, querido y bien amado del Señor,
a quien Él envió en Su amor eterno a mí y a muchos más, que estábamos en tinieblas,
en ceguera y buscando Al que vive entre los muertos,
para mostrarnos y dirigirnos al camino que saca del pecado y del mal,
y lleva al Dios eterno, bendito para siempre.
Que el vivo y eterno Dios de vida y amor, que te envió al norte,
me guarde y me preserve
ahora mediante Su brazo y poder eternos,
y mantenga a todos mis amigos y hermanos verdaderamente conscientes de Su amor eterno,
que tengo constancia de que ha sido sumamente grande desde el día
que el Señor dio a conocer Su preciosa verdad entre nosotros.
Por tanto, querido George Fox, ora por mí, porque soy viejo y mi cuerpo está enfermo,
y la vista de mis ojos se debilita grandemente.
Oh, ruega que yo pueda mantenerme fiel y recto ante el
Señor en la medida que he recibido de Él,
en este día de Su amor eterno,
y que pueda rendir mis cuentas con gozo y regocijo y alegría de corazón,
y ser presentado contigo, y con todos mis hermanos, irreprochable delante del Señor,
y así ir a mi tumba en paz y reposar para siempre.
Amén.

Exprésales mi querido amor a mis buenos y viejos amigos, Margaret Fox y Thomas Lower;
su querido y tierno amor y cuidado hacia mí en meses
pasados no pueden ser olvidados por mí,
mientras habite y permanezca fiel a Aquel que es mi luz y mi vida, mi gozo y mi paz,
Dios sobre todo, bendito para siempre.
Amén.

[.signed-section-signature]
Miles Halhead.

--

En el mes llamado enero, de 1674,
G+++.+++ Fox y Thomas Lower fueron llevados a juicio en el tribunal de Worcester,
el último día de las sesiones.
Cuando ellos entraron, los que estaban en el tribunal se pusieron pálidos,
y permanecieron un tiempo sin poder hablar, a tal punto,
que un carnicero en la sala dijo: "`¡Qué! ¿Tienen miedo?
¿Los magistrados no se atreven a hablarles?`"
Finalmente el juez Parker,
por cuya orden G. Fox y T. Lower habían sido enviados a prisión,
pronunció un gran discurso,
muy parecido al contenido de la orden del tribunal contra ellos,
y añadió que él había pensado que era más liviano enviarlos a la cárcel,
que exponer a sus semejantes a la pérdida de doscientas libras,
suma que habrían tenido que pagar de haber puesto la ley contra conventículos en ejecución.
Pero este fue un giro muy pobre y una evasiva tonta;
porque al no haber reunión cuando G. Fox llegó, ni ninguna de la cual informar,
él no tenía pruebas con que condenarlos a ellos ni a sus amigos.

Cuando Parker terminó su discurso, los magistrados les hablaron a los prisioneros,
empezando con Lower,
a quien interrogaron sobre el motivo por el que había llegado a ese condado.
Cuando terminaron con él, le pidieron a G. Fox que relatara sus viajes, lo cual él hizo,
y les mostró claramente que él y sus amigos,
de quienes el juez Parker había hecho tanto ruido,
como si muchos hubieran llegado juntos de varias partes,
eran en cierto modo una sola familia.
Cuando terminó de hablar, el presidente Simpson dijo: "`Tu relato es muy inocente.`"
Luego,
después de que él y el juez Parker hablaron calladamente entre ellos por unos momentos,
el presidente se puso de pie y dijo: "`Señor Fox, usted es un hombre famoso,
y todo lo que usted ha dicho puede que sea verdad, pero para nuestra mayor satisfacción,
¿prestarías los juramentos de lealtad y supremacía?`" Ahora bien,
aunque G. Fox respondió a esto, que ellos habían dicho que no intentarían atraparlo,
y que eso era claramente una trampa,
dado que ellos sabían que él ni sus amigos prestarían ningún juramento, etc.,
todo fue en vano.
Entonces, hicieron que se leyera el juramento y una vez hecho, G. Fox les dijo:
"`Nunca he hecho un juramento en toda mi vida, pero siempre he sido fiel al gobierno.
Fui arrojado en el calabozo de Derby y mantenido prisionero por seis meses ahí,
porque no tomé las armas contra el rey Carlos en la batalla de Worcester.
Y por ir a las reuniones,
fui sacado de Leicester y llevado ante Oliver Cromwell
como conspirador para traer al rey Carlos.
Ustedes saben en sus propias consciencias que nosotros, el pueblo llamado Cuáqueros,
no podemos prestar juramento, o jurar en ningún caso, porque Cristo lo ha prohibido.
Pero en cuando a la materia o sustancia que contienen los juramentos,
esto puedo decir y lo digo:
Apruebo y reconozco que el rey de Inglaterra es el
legítimo heredero y sucesor del reino de Inglaterra;
aborrezco todo complot, conspiración y maquinación contra él,
y no tengo nada en mi corazón sino amor y buena voluntad hacia él y todos sus hombres,
y deseo su prosperidad y la de ellos.
El Señor lo sabe, delante de quien, soy un hombre inocente.
Y en cuanto al juramento de supremacía, niego al Papa y su poder,
y lo aborrezco de corazón.`"

Mientras todavía estaba hablando, ellos gritaron:
"`¡Denle el libro!`" (refiriéndose a la Biblia).
"`El libro,`" dijo G. Fox, "`dice,
'`No juréis en ninguna manera`';`" y al continuar declarando su opinión, gritaron:
"`¡Llévatelo, carcelero!`"
Como el carcelero no se mostró muy dispuesto, le gritaron de nuevo: "`¡Llévatelo!
Tendremos una reunión aquí; ¿por qué no te lo llevas?`"
Y uno del tribunal dijo: "`A ese tipo,`" hablando del carcelero,
"`le encanta oírlo predicar.`"
Entonces el carcelero se lo llevó, mientras G. Fox se alejaba diciendo:
"`El Señor los perdone a ustedes,
que me arrojan en prisión por obedecer la doctrina de Cristo.`"
Después de que se llevaron a G. Fox,
los magistrados le dijeron a Thomas Lower que él estaba en libertad;
pues ellos pesaban que no era seguro tratar con él
de la misma manera que habían hecho con G. Fox,
sabiendo que él tenía cierta protección en la corte.
Lower les preguntó entonces:
"`¿Por qué no se puede poner a mi suegro en libertad como a mí,
dado que ambos fuimos apresados juntos y nuestro caso es igual?`"
Pero ellos diciéndole que no lo oirían, le dijeron: "`Puedes dedicarte a tus asuntos,
porque no tenemos más que decirte, ya que has sido liberado.`"

Esto fue todo lo que Lower pudo obtener de ellos en ese momento, por lo tanto,
después de que se levantó el tribunal, fue a hablar con ellos a su cámara,
pues deseaba saber qué causa tenían para detener a su padre,
siendo que ellos lo habían liberado a él,
y para pedirles que consideraran si eso no era parcialidad.
Ante esto, el presidente Simpson dijo: "`Si no estás contento,
te presentaremos el juramento también y te enviaremos con tu padre.`"
A lo que Lower replicó: "`Ustedes pueden hacer eso, si lo consideran adecuado;
pero me envíen o no, tengo la intención de ir y atender a mi padre en prisión,
porque ese ahora es lo que me corresponde en este lugar.`"
Entonces el juez Parker le dijo: "`Señor Lower,
¿acaso crees que yo no tenía motivos para enviarte a ti y a tu padre a prisión,
cuando tuvieron una reunión tan grande,
que hasta el mismo párroco de la parroquia se quejó
conmigo de que ha perdido gran parte de sus feligreses;
y que cuando los visita, apenas quedan unos oyentes?`"
A esto Lower respondió:
"`He oído que el sacerdote de esa parroquia llega muy raramente a visitar a su rebaño,
una o dos veces al año, para recoger sus diezmos;
de modo que no fue más que caridad en mi padre,
la que lo hizo visitar a un rebaño tan desamparado y abandonado.
Por lo tanto, no tenías motivos para enviar a mi padre a prisión por visitarlos,
o por enseñarles, instruirlos y dirigirlos a Cristo, el verdadero Maestro de ellos,
al ver que ellos tienen muy poco consuelo o beneficio de su pretendido pastor,
que sólo llega a visitarlos para buscar su propia ganancia.`"
Entonces el juez se echó a reír, porque el Dr. Crowder, el sacerdote del que se hablaba,
estaba en ese momento en la habitación, sentado entre ellos, aunque Lower no lo conocía;
pero tuvo el sentido común de refrenar su lengua y de no tratar de vindicarse.
Pero después de que Lower se marchó, los magistrados se burlaron tanto del Dr. Crowder,
que este se avergonzó y se molestó tanto,
que amenazó con demandar a T. Lower ante el tribunal del obispo por difamación. No obstante,
cuando T. Lower oyó esto le envió un mensaje diciendo que podía actuar así,
si lo deseaba,
y que él le respondería y llevaría a toda su parroquia como
evidencia contra él. Después le dijo lo mismo cara a cara,
lo que enfrió tanto el afán del sacerdote,
que pensó que era más seguro para él dejar a T. Lower en paz.

Poco después de que las sesiones del tribunal terminaron,
fue enviado a Worcester una orden de _habeas corpus,_
para que el alguacil llevara a G. Fox al tribunal del rey,
a raíz de lo cual su yerno T. Lower lo condujo;
pues el asistente del alguacil había nombrado a Lower
como su representante para llevar a G. Fox a Londres.
Una vez allí, se presentó ante el tribunal del rey, donde encontró magistrados moderados.
Ellos lo oyeron pacientemente mientras les contaba cómo
había sido detenido en su viaje y enviado a la cárcel;
y cómo le habían presentado el juramento de lealtad y supremacía en su juicio;
y lo que él les había ofrecido a los magistrados como declaración,
y que estaba dispuesto a firmar dicha declaración
en lugar de prestar los mencionados juramentos.
A esto, el presidente del tribunal le dijo que ellos lo considerarían más adelante.
Entregado luego al guarda del tribunal del rey,
se le permitió ir y alojarse en la casa de uno de sus amigos;
pues aunque seguía estando prisionero,
ellos estaban suficientemente persuadidos de que él no huiría. Pero después de esto,
el juez Parker (según se dijo) le propuso al tribunal
que G. Fox fuera enviado de regreso a Worcester,
para que su causa fuera tratada ahí;
porque Parker vio claramente que si G. Fox era absuelto en Londres,
eso sería para vergüenza de él, por haberlo encerrado injustamente.

Entonces se señaló un día para otra audiencia,
y G. Fox compareció de nuevo ante el tribunal del rey.
Al oír que estaba bajo deliberación enviarlo de regreso a Worcester,
él les indicó que eso era sólo para atraparlo y presentarle el juramento,
y poder así dictar la sentencia de premunire contra él. Y les dijo además,
que aunque él nunca había tomado un juramento en su vida,
si él quebrantaba su sí o su no,
se sujetaría a sufrir la misma pena que sufren los que quebrantan sus juramentos.
Ahora bien, como Parker había difundido un informe en Londres,
y se había dicho en el Parlamento,
que cuando él había apresado a G. Fox había muchos hombres importantes con él,
procedentes de varias partes de la nación,
y que ellos tenían una conspiración o complot entre manos,
G+++.+++ Fox no dejó de mostrar la falsedad de esa maliciosa historia.
Y como de esa manera puso al descubierto la vergüenza
de Parker delante de sus amigos en el tribunal,
no fue sorprendente que los magistrados del rey cumplieran con el deseo
de Parker de mandar de regreso a Fox a la cárcel de Worcester.
G+++.+++ Fox descubrió que no lo podía evitar, por mucho que dijera en su defensa;
y sólo se le concedió este favor, que podía regresar por su propia cuenta y a su paso,
siempre y cuando estuviera ahí y sin falta,
para el momento de las sesiones del tribunal que
tenían que iniciar el 2 del mes llamado abril.

Por tanto, después de una estadía en Londres, G. Fox regresó tranquilamente,
y cuando llegó a Worcester,
fue llevado el 2 del mencionado mes de la cárcel a una posada cerca de la sala de sesiones.
No obstante, al no ser llamado ese día,
el carcelero fue a él de noche y le dijo que podía ir a casa, refiriéndose a la cárcel;
con lo cual, él mismo se dirigió ahí, acompañado por uno de sus amigos.
Al día siguiente fue llevado de nuevo,
y un niño de unos once años fue puesto como su guardián. Dado que
en mi relato de los procedimientos ante el tribunal del rey,
pasé por alto la mayor parte de los alegatos, haré lo mismo aquí,
para evitar repeticiones de lo que ya ha sido relatado
varias veces con respecto a estos juicios.
Sin embargo, no puedo pasar en silencio,
que después de haber dado cuenta de su viaje antes de ser apresado, añadió,
que desde su encarcelamiento había oído que su madre, que era una mujer anciana y débil,
había querido verlo antes de morir,
y que cuando ella se enteró de que él había sido detenido y encarcelado en su viaje,
y que probablemente no llegaría a verla, se había afectado tanto que murió poco después;
lo cual había sido muy duro para él. El juez Turner,
que anteriormente había sido muy severo con él, ahora parecía, según pensaban algunos,
inclinado a ponerlo en libertad,
dado que había visto que ellos no tenían nada justo contra él. Pero Parker,
que era quien lo había encarcelado, se esforzó por incitar al juez contra él,
sabiendo que si G. Fox era liberado,
él llevaría la culpa de haberlo encerrado injustamente.
Por tanto, Parker le dijo al juez que G. Fox era un cabecilla,
al que muchos de la nación seguían, y que no se sabía a qué podía llegar.
El juez le prestó poca atención a todo eso, estando dispuesto a ser moderado;
aunque no podía decidirse a poner en libertad a G. Fox, para no disgustar a otros.
Y así, en conclusión,
G+++.+++ Fox y su causa fueron remitidos a las siguientes sesiones y permaneció prisionero,
pero con la condición de que podía moverse libremente por el pueblo.

Gracias a esto tuvo oportunidad de hablar con muchas personas,
y a veces también con los sacerdotes,
uno de los cuales le preguntó si él había llegado a la perfección. A esto G. Fox respondió,
que lo que él era, lo era por la gracia de Dios.
"`Esto,`" replicó el sacerdote, "`es una respuesta modesta y civilizada.
Pero,`" continuó con las palabras del apóstol Juan: "`Si decimos que no tenemos pecado,
nos engañamos a nosotros mismos, y la verdad no está en nosotros.`"
Y preguntándole qué decía de eso, G. Fox respondió con las palabras del mismo apóstol:
"`Si decimos que no hemos pecado, le hacemos a él mentiroso,
y su palabra no está en nosotros.`"
Además dijo: "`Cristo vino a destruir el pecado y a quitarlo.
Hay un tiempo para que las personas vean que han pecado,
y hay un tiempo para que confiesen su pecado y lo abandonen,
y para que conozcan la sangre de Cristo que los limpia de todo pecado.`"
Después de más razonamiento, el sacerdote dijo:
"`Nosotros debemos esforzarnos siempre;`" a lo que G. Fox respondió:
"`Es un tipo de esfuerzo triste y desconsolador,
esforzarnos con la creencia de que nunca venceremos.
Pablo, que en una ocasión clamó a causa del cuerpo de muerte,
después le dio gracias a Dios por haberle dado la victoria, y dijo: '`Ahora, pues,
ninguna condenación hay para los que están en Cristo Jesús.`' Por tanto,
hay un tiempo para clamar por la falta de victoria,
y un tiempo para alabar a Dios por la victoria.`"
"`Pero,`" dijo el sacerdote, "`ni siquiera Job era perfecto.`"
A lo que G. Fox respondió:
"`Dios ha señalado en las Escrituras que Job era perfecto y recto,
y que se apartaba del mal.
Y el diablo mismo fue forzado a confesar que Dios había puesto una cerca alrededor de él;
la cual, no era una cerca externa, sino el invisible poder celestial.`"
"`Sin embargo,`" replicó el sacerdote, "`Job acusó Sus ángeles de necedad,
y dijo que los cielos no estaban limpios ante Sus ojos.`"
"`Eso es un error,`" dijo G. Fox, "`porque no fue Job quien dijo eso, sino Elifaz,
quien contendía contra Job.`"
"`Bien,`" dijo el sacerdote, "`pero,
¿qué dices de la Escritura '`el hombre más justo que existe,
peca siete veces al día`'?`" G. Fox respondió: "`No existe tal escritura.`"
Entonces el sacerdote guardó silencio y la conversación
se interrumpió. He relatado todo esto,
para mostrar que G. Fox no era una persona tan simple
como muchos (por mera envidia) han intentado describirlo;
porque él nunca se quedaba sin una respuesta, sino que siempre tenía una preparada.

Cuando llegó de nuevo el momento de las sesiones,
G+++.+++ Fox fue llamado a comparecer ante los magistrados, y un tal juez Street,
que era el presidente, tergiversó enormemente el caso diciéndole al pueblo,
que G. Fox había tenido una reunión en Tredington
con personas de todas partes de la nación,
para terror de los súbditos del rey.
"`Por esto,`" dijo el presidente Street, "`él ha sido enviado a prisión;
y para prueba de su fidelidad,
se le presentaron los juramentos de lealtad y supremacía.`" Entonces,
volviéndose a G. Fox le preguntó, si tomaría o no los juramentos,
puesto que había tenido tiempo para considerarlo.
G+++.+++ Fox, al obtener libertad para hablar por sí mismo, hizo un relato de su viaje,
y mostró que ni él ni sus amigos habían mantenido una reunión en ninguna forma,
para causarle terror a ningún súbdito del rey.
Y en cuanto a los juramentos, mostró la razón por la que él no podía hacerlos, y también,
lo que podía declarar en su lugar.
A pesar de todo esto, los juramentos le fueron leídos de nuevo,
y cómo el persistió en su negativa a prestar juramento,
también se le leyó la acusación. Después el presidente le preguntó si era culpable.
G+++.+++ Fox respondió: "`No,
puesto que la acusación es un montón de mentiras;`" lo que demostró con varios detalles,
y le preguntó al presidente si él no sabía en su consciencia que eran mentiras.
Entonces, el presidente le dijo al jurado qué debían hacer en ese caso;
y antes de que dieran su veredicto, G. Fox les dijo: "`Es por causa de Cristo,
y en obediencia a Su mandato y al de Su apóstol que no puedo jurar.
Por tanto, tengan cuidado con lo que hacen;
porque todos ustedes comparecerán ante el tribunal de Cristo.`"
El presidente dijo entonces: "`Esto es palabrería.`" G. Fox replicó:
"`Si confesar a Cristo nuestro Señor y Salvador,
y obedecer Su mandamiento es llamado palabrería por un juez del tribunal,
es de poco propósito que yo diga más entre ustedes.
Sin embargo, ustedes verán que soy Cristiano,
y mostraré el Cristianismo y mi inocencia será manifestada.`"
Al hablar de esta manera, la gente en general se sintió afectada,
pero el jurado de todas maneras dio un veredicto en contra de él, al que G. Fox,
no obstante, se opuso.
Pero el asunto no se pudo terminar en ese momento,
y se le pidió que pagara una fianza hasta las siguientes sesiones del tribunal.
Él se rehusó, y les advirtió a sus amigos que parecían dispuestos a comprometerse por él,
que no se metieran, porque había una trampa en ello.
Sin embargo, les dijo a los magistrados que él prometía comparecer,
si el Señor le daba salud y fuerza, y estaba en libertad.
Algunos de los magistrados se mostraron afectuosos,
y se esforzaron por impedir que el resto lo condenaran o le presentaran el juramento,
pero el presidente dijo que él debía continuar de acuerdo con la ley.
Con todo, le fue dada la libertad a G. Fox hasta las siguientes sesiones trimestrales.

Entonces se fue a Londres, pues se acercaba el tiempo de la Reunión Anual.
Pero, a petición de algunos de sus amigos,
se presentó de nuevo delante de los magistrados del tribunal del rey,
y les entregó la siguiente declaración,
exponiendo lo que él estaba dispuesto a prometer en lugar
de prestar los juramentos de lealtad y supremacía.

[.embedded-content-document.legal]
--

Declaro en la verdad y en la presencia de Dios,
que el rey Carlos II es el legítimo rey de este reino,
y de todos los otros bajo su dominio;
y que él fue traído y puesto como rey de este reino por el poder de Dios;
y no tengo más que amor y buena voluntad hacia él y hacia todos sus súbditos,
y deseo su prosperidad y eterno bien.
Aborrezco y niego totalmente el poder y supremacía del papa,
y todas sus invenciones supersticiosas e idólatras;
y afirmo que él no tiene poder para absolver el pecado.
Aborrezco y detesto que asesine a príncipes y a otras personas,
mediante planes y conspiraciones.
Igualmente, niego toda conspiración y maquinación,
y a los conspiradores y maquinadores contra el rey y sus súbditos,
sabiendo que estas son obras de las tinieblas, frutos de un espíritu maligno,
y contra la paz del reino, y que no provienen del Espíritu de Dios,
Cuyo fruto es el amor.
No me atrevo a prestar juramento, porque es prohibido por Cristo y Su apóstol;
pero si quebranto mi sí o mí no,
entonces déjenme sufrir la misma pena que sufren los que quebrantan sus juramentos.

[.signed-section-signature]
George Fox.

--

Esta declaración,
que era la sustancia de lo que los juramentos de lealtad y supremacía contenían,
la presentó G. Fox a los magistrados del tribunal del rey;
pero sabiendo que los procedimientos habían continuado en Worcester,
no estuvieron dispuestos a meterse en el asunto,
y sólo la remitieron a las siguientes sesiones trimestrales en Worcester.

Una vez finalizada la Reunión Anual, regresó a Worcester,
donde las sesiones se celebraban en el mes llamado julio.
G+++.+++ Fox fue llamado al estrado, la acusación fue leída,
el juez Street hizo que se leyeran también los juramentos, y se los presentaron otra vez.
Entonces G. Fox les dijo que él había llegado para objetar la acusación. Pero cuando
empezó a mostrar los errores que había en la acusación (que eran suficientes para anularla),
lo detuvieron con prontitud y le exigieron el juramento,
y como él seguía rehusándose a jurar, el jurado lo declaró culpable.
El presidente, aunque se había mostrado muy activo contra G. Fox,
puso entonces un semblante de preocupación,
y le habló de la triste sentencia que tenía que dictar contra él. A esto
G+++.+++ Fox replicó que tenía muchos más errores que alegar contra la acusación,
además de los que ya había mencionado.
A continuación,
el presidente le dijo que le iba a decir el peligro de una sentencia de premunire,
"`la cual,`" dijo, "`es la pérdida de tu libertad, de todos tus bienes y patrimonio,
y padecer el encarcelamiento durante toda tu vida.
Pero,`" agregó, "`no emito esto como la sentencia del tribunal,
sino sólo como una advertencia para ti.`"
Entonces se le pidió al carcelero que se lo llevara;
y a G. Fox se le informó más tarde con respecto a la pretendida advertencia,
que el presidente le había dicho al secretario de paz,
que lo que había dicho sería la sentencia de Fox.

Ahora bien, mientras G. Fox estaba en prisión,
llegó a verlo (entre otros) el hijo del conde de Salisbury, quien era muy afectuoso,
y parecía muy preocupado por el hecho de que lo hubieran tratado de esa manera;
y él mismo tomó una copia por escrito de los errores que había en la acusación. Después,
G+++.+++ Fox consiguió que las circunstancias de su caso se redactaran
por escrito y se entregaran al juez Wild.
También le escribió una carta al rey,
en la que le daba cuenta de los sentimientos de los
llamados Cuáqueros con respecto a jurar;
y cómo aborrecían toda conspiración y maquinación contra el rey.
No mucho después de esto, cayó en una enfermedad tal,
que muchos empezaron a dudar de su recuperación. Entonces,
uno de sus amigos fue a ver al juez Parker,
por cuya orden había sido encarcelado la primera vez,
y le pidió que le diera orden al carcelero,
de darle libertad a G. Fox de salir de la cárcel para ir a la ciudad.
Ante lo cual, Parker le escribió la siguiente carta al carcelero.

[.embedded-content-document.letter]
--

[.salutation]
Señor Harris,

He sido muy importunado por algunos amigos de G. Fox para que te escriba.
Me informan que él está en una condición muy débil, y muy indispuesto.
Cualquier favor lícito que puedas concederle, para que se beneficie con aire fresco,
para efectos de su salud, te ruego que se lo muestres.
Supongo que la próxima vez le harán una solicitud al rey.
Señor, soy tu atento amigo,

[.signed-section-signature]
Henry Parker.

[.signed-section-context-close]
Evesham, 8 de octubre, de 1674

--

Esta carta fue una orden suficiente para que el carcelero permitiera que
G+++.+++ Fox fuera llevado de la prisión a la casa de uno de sus amigos.
Su esposa había acudido a él antes de este momento,
y después de estar con él cerca de diecisiete semanas,
y ver que no era probable que se consiguiera una absolución, fue a Londres.
Al llegar a Whitehall y reunirse ahí con el rey,
le dio cuenta del largo encarcelamiento de su esposo y de cuán débil estaba,
y que no estaba exento del peligro de muerte.
Pero a esto el rey le dijo que él no podía hacer nada, y que ella debía ir al canciller.
Así que acudió a lord Finch, que en ese entonces era el canciller,
y después de darle cuenta del asunto,
le dijo que el rey había dejado todo el asunto en las manos de él,
y que si él no se compadecía y liberaba a su esposo de prisión,
ella temía que terminara sus días ahí. Pero el canciller le dijo
que el rey no podía liberarlo si no era mediante un indulto.
Ahora bien, G. Fox no podía decidirse a ser liberado de esa manera,
sabiendo bien que él no había hecho ningún mal,
y prefería permanecer en prisión toda su vida, antes que ser liberado de esa manera.
En efecto,
esta era la única razón por la que él había permanecido tanto tiempo en prisión,
ya que el rey desde antes había estado dispuesto a indultarlo.
El rey también le había dicho a un tal Thomas More,
que G. Fox no tenía por qué tener escrúpulos en ser liberado por un indulto,
"`pues a muchos hombres que eran tan inocentes como un niño se les había concedido uno.`"
Sin embargo, G. Fox no estaba dispuesto a recibir un indulto,
lo que quería era que se juzgara ante los magistrados
la validez de la acusación contra él. El canciller,
que se mostró como un hombre discreto,
consiguió entonces una orden de _habeas corpus_ para que G. Fox fuera llevado a Londres,
a comparecer una vez más ante el tribunal del rey.
Este _habeas corpus_ fue enviado inmediatamente por su esposa a Worcester,
pero al principio no quisieron dejarlo ir,
(ya que lo encontraban un poco recuperado de su enfermedad) bajo
el pretexto de que él estaba bajo la sentencia de premunire,
y no podía salir de esa manera.
Por tanto, se hizo necesario acudir a Londres otra vez;
y se obtuvo otra orden que fue enviada otra vez,
para presentar a G. Fox delante del tribunal del rey.
Como todavía estaba un poco débil, fue transportado a Londres en un coche,
acompañado por el asistente del alguacil y el secretario de paz.

Al llegar, fue llevado ante los cuatro magistrados del tribunal del rey,
donde el consejero Thomas Corbet defendió su causa y se desenvolvió muy bien;
porque inició una nueva defensa,
y les dijo a los magistrados que por ley ellos no
podían encarcelar a ningún hombre en premunire.
Entonces los magistrados dijeron que debían mirar sus libros y consultar los estatutos,
y se aplazó la audiencia hasta el día siguiente.
Y como parecía que Corbet tenía razón, optaron por abstenerse de dar declaración,
tal vez por temor a peores consecuencias.
Entonces comenzaron a examinar los errores de la acusación,
que resultaron ser tantos y tan grandes,
que todos los magistrados fueron de la opinión de
que la acusación era nula y no tenía efecto,
y que G. Fox debía ser liberado.
El mismo día varios lores y otros hombres importantes prestaron
los juramentos de lealtad y supremacía en audiencia pública;
y algunos de los adversarios de G. Fox presionaron a los
magistrados para que le presentaran de nuevo los juramentos,
diciendo que él era un hombre muy peligroso como para ser puesto en libertad.
Pero el juez Matthew Hale,
que por ese entonces era presidente del Tribunal Supremo de Inglaterra,
y un hombre realmente excelente y piadoso (como ya se ha insinuado antes) dijo,
que él había oído algunos informes así sobre G. Fox,
pero que también había oído muchos más informes buenos
sobre él. Esta declaración resultó útil,
y M. Hale y los otros magistrados ordenaron que G. Fox fuera liberado
por medio de una proclamación. Así fue puesto en libertad de manera honorable,
y su consejero Corbet, que había abogado por él, obtuvo gran fama por ello;
pues muchos otros abogados le dijeron que había sacado
a la luz algo que no se sabía antes.
Después del juicio, uno de los magistrados le dijo:
"`Has obtenido un gran honor por tu forma de defender la causa de G. Fox en el tribunal.`"
