== Capítulo XIX

[.section-date]
1674--1676

[.chapter-synopsis]
* Disputa con los bautistas
* Jeremy Ives
* Un amigo infiel
* Disputa en Barbican entre J. Ives y los Cuáqueros
* Continuación de la persecución
* Crueldades practicadas en Leicestershire, Norfolk y Somersetshire
* Terrible fin de los perseguidores
* Muerte de W. Bayly
* Penitencia de M. Hide
* Muerte del sacerdote Lampitt
* Uso bárbaro de E. Cooper
* Insolencia de los informantes
* Ultrajes en Hereford
* Exitosa apelación de J. Layton
* Muerte de doscientos Cuáqueros en prisión desde la Restauración
* Ley en Barbados para impedir que los negros asistan a las reuniones de los Amigos
* R. Barclay y Adrian Paets Correspondencia
* Exposición de algunas de las doctrinas de los Amigos.

El año estaba llegando a su final, pero antes de pasar al próximo,
debo mencionar que los Bautistas en Inglaterra,
al perder de vez en cuando a algunos de sus mejores miembros,
escribían muy ferozmente contra los Cuáqueros,
esforzándose por presentarlos como no Cristianos.
Pero dichos escritos eran continuamente respondidos
de manera impresa con tantas razones convincentes,
que los Cuáqueros ganaban aún más adeptos por ello.
Como consecuencia de esto,
se señaló una disputa pública entre los Bautistas y los Cuáqueros,
a celebrarse en la casa de reunión de los Bautistas en Londres.
Por los Cuáqueros, hablaron por turno George Whitehead, Stephen Crisp,
William Penn y George Keith; y los oponentes eran Jeremy Ives, William Kiffin,
Thomas Plant, Thomas Hicks y un tal Robert Fergurson,
un Presbiteriano que después fue conocido principalmente en Holanda,
por la fiera declaración que redactó en nombre del duque de Monmouth,
cuando ese infeliz príncipe fue a Inglaterra con fuerzas
armadas para disputar el trono contra el rey James.

Jeremy Ives era un eminente maestro entre los Bautistas,
que había estado preso en Londres catorce años antes de esta época por motivos religiosos,
y principalmente, porque por motivos de consciencia se había negado a jurar.
No muchos después de ser confinado,
les escribió desde prisión una dura carta a dos miembros de su sociedad,
quienes habiendo estado en prisión con él por la misma causa,
habían prestado el juramento para obtener sus libertades.
En esa carta él reprendía a sus hermanos por apostatar,
y señalaba que así habían aumentado la carga de los fieles.
Pero, ¡cuán cambiante criatura es el hombre si no continúa vigilante,
ni se mantiene cerca de la gracia divina, aferrándose continuamente a ella!
Porque escasamente cinco días después de escribir esa carta,
este inconstante Jeremy se cansó del encarcelamiento y también
prestó el juramento para salir de prisión. Pero no se detuvo ahí;
porque era evidente para todos que él se había separado de su profesión religiosa.
Por tanto, a fin de salvar la cara y encontrar excusas para lo que había hecho,
publicó un libro en el que afirmaba que jurar era lícito.

Se le preguntó en la disputa pública si él era el Jeremy
Ives que una vez había sido de una consciencia tan tierna,
que no se había atrevido a prestar juramento,
y que luego había defendido públicamente que jurar era lícito.
Él no negó el hecho, porque era notoriamente conocido,
pero trató de disfrazar el asunto y dijo:
"`Soy ese Jeremy Ives que prestó el juramento de lealtad y escribió un libro,
para probar que algunos juramentos son lícitos, aunque no todos.`"
Tampoco negó la antes mencionada carta, porque estaba impresa y es como sigue:

[.embedded-content-document.letter]
--

[.salutation]
Hermano Pitman y Hermano Shewel,

En este momento estoy sorprendido con una pasión santa;
y aunque Jonás no podía decir con respecto a la calabacera que hacía bien en enojarse,
yo, sin embargo, si mi experiencia en la palabra del Señor no me engaña,
puedo decir que en verdad hago bien en enojarme con ustedes.
Porque me sorprende que hayan sido tan fácilmente
persuadidos a apartarse de sus libertades espirituales,
y que hayan estado tan poco dispuestos a sufrir por ellas.
¡Oh, mis hermanos! ¿Dónde está el primer amor de ustedes?
¿Cuán diferentes son de los Cristianos de tiempos pasados?
Siempre he creído que los que abandonan la causa de la justicia,
también abandonarán los caminos de santidad,
como lo ha probado la triste experiencia de ayer,
para el gozo perpetuo de sus adversarios,
y para entristecer los corazones y añadir aflicciones
a las ataduras de los prisioneros del Señor.

Yo, por tanto, los exhorto, dado que un día le van a responder al gran Dios,
consideren que este es el momento de mirar sus ministerios
y al rebaño sobre el que el Señor los ha hecho supervisores,
para que puedan decir por la gracia que están limpios de la sangre de todos los hombres.
Observen que Dios ha venido a probarlos, para ver si guardarán o no Sus mandamientos.
Recuerden que cuando se debatió el caso de aquel apóstata,
ustedes no tuvieron celo ni indignación contra él,
sino que lo sofocaron todo con estas palabras:
"`Si fuera un asunto de fe y adoración del que él hubiera caído,
nos levantaríamos como un solo hombre contra eso.`"
Pues bien, he aquí el Señor les hace saber lo que hay en sus corazones,
porque ahora el asunto es puramente de adoración a Dios.
Dios los está probando para ver si Lo obedecerán o no.
¿No mostró la obra de ayer que ustedes están dispuestos a escoger el temor
al hombre (que debe morir) antes que el temor al gran Dios;
y el temor a los que pueden matar el cuerpo,
antes que el temor al Señor que puede arrojar tanto el cuerpo como el alma al infierno?
No tengo nada más que decir sino esto,
me preocupa que la manera en que cobardemente cedieron
y cumplieron los preceptos de los hombres,
sea porque su temor hacia el Señor les ha sido enseñado por los preceptos de los hombres.
No quiero ser demasiado censurador,
pero mis motivos son grandes y mis ataduras son mi corona;
pero el espíritu cobarde de ustedes es mi cruz.
Poco saben el escándalo que supone entre nosotros oír afirmar que uno de ustedes dijo,
que preferían pagar cincuenta libras antes que jurar, y sin embargo,
ahora se dice que ustedes juraron de buena gana.
¡Oh, por amor al Señor, hagan algo que quite este oprobio!
Estas son las oraciones de su hermano, que desearía denominarse,

[.signed-section-closing]
Compañero de ustedes en la tribulación,

[.signed-section-signature]
Jeremy Ives

[.signed-section-context-close]
14 de Enero de 1660.

--

Así de celosamente les escribió Jeremy Ives a sus compañeros maestros,
quienes por temor humano y para evitar sufrimientos,
habían prestado juramento en contra de su profesión
religiosa y la convicción de sus conciencias.
Pero, ¿quién se habría imaginado, en vista de tal carta,
que él mismo en tan corto espacio de tiempo,
haría lo que había censurado tan severamente en otros?
En verdad, en este caso parece muy aplicable lo dicho por el profeta Jeremías:
"`Engañoso es el corazón más que todas las cosas, y perverso; ¿quién lo conocerá?`" Y,
"`así que, el que piensa estar firme, mire que no caiga.`"
Feliz hubiera sido este hombre,
si hubiera sido tan consciente de sus transgresiones como un tal Edward Chilton, que,
aunque Cuáquero de profesión,
cuando llegó la prueba de hacer el juramento de lealtad
o se dictaría la sentencia de premunire contra él,
vaciló y se desmayó. Sin embargo, él no se apartó totalmente,
porque luego se arrepintió tanto por el mal que había cometido,
que se sintió obligado a dar prueba de ello,
y les escribió una carta a sus amigos que seguían presos
debido a que por motivos de consciencia no podían jurar;
mientras que él, para ser liberado de la prisión,
había prestado el juramento que le exigían. Pero, qué sabor amargo le produjo esto,
y qué terror y horror se apoderaron de él después, lo mostrará la siguiente carta:

[.embedded-content-document.letter]
--

[.salutation]
Mis queridos Amigos,

Deseo exponer ante ustedes mi condición en esta mi caída,
para que así mi caída no sea causa de tropiezo para ustedes,
y para que por ella sean más animados a permanecer.
Porque yo cedí ante el traidor y así traicioné a la Semilla inocente en mí;
porque abandoné el consejo del Señor,
consulté con '`carne y sangre,`' y caí en la trampa del mundo.
De hecho, descansé satisfecho en lo que había hecho por algunas horas,
pero cuando el Señor en Su poder me miró, entonces recordé lo que había hecho;
entonces recordé que había negado la verdad que alguna vez había profesado,
aunque una vez creí que yo me mantendría firme cuando otros cayeran.
Así que ahora los terrores del Señor se han apoderado
de mí y estoy bajo los juicios del Señor.

Ahora siento la verdad de las palabras que fueron dichas por Cristo,
que el que falla en una tilde, es culpable de todo;
y siento la verdad de que es mejor abandonar a la esposa y a los hijos,
y todo lo que el hombre tiene, incluso la vida misma, por Cristo y Su verdad,
que quebrantar una tilde de la ley de Dios escrita en el corazón. Así que espero,
que por la misericordia y el juicio, el Señor me redima para Él otra vez.
El Señor puede permitir que algunos caigan,
para que la posición de los que permanecen fieles parezca más gloriosa,
y para que tengan cuidado de no caer también.

Ahora sé y siento que es mejor separarse de todo lo de este mundo,
aunque sea tan querido para uno como su mano u ojo derecho,
que romper nuestra paz con Dios.

[.signed-section-closing]
Oren por mí, porque mis ataduras son más grandes que las de ustedes.

[.signed-section-signature]
Edward Chilton

[.signed-section-context-close]
Windsor, 22 del mes Once de 1660.

--

Es notable que E. Chilton en la conclusión de su carta diga
que sus ataduras eran mayores que las de sus amigos,
quienes no temieron la sentencia premunire, ni la pérdida de su libertad,
si debían pagar un precio tan caro como era el de prestar juramento.
Porque cuando alguien verdaderamente permanece en el temor de Dios,
no se atreve a transgredir los mandamientos divinos
en contra de las convicciones de su consciencia,
ni a buscar evasivas para evitar la presión de estos, porque ciertamente,
Dios no puede ser burlado.
¿Podría haber hablado nuestro Salvador en términos más claros y expresos que cuando dijo:
"`No juraréis en ninguna manera`"? Y sin embargo,
qué astutas artimañas han sido inventadas por los que se jactan de llamarse Cristianos,
para debilitar la fuerza de estas palabras expresas.
No es este el lugar apropiado para refutar las razones que dan, sin embargo,
no me parece inadecuado mostrar brevemente lo peligroso que es
actuar en contra de los mandamientos expresos de las Escrituras,
o en contra de la convicción de la propia consciencia para evitar
la persecución. Porque no sólo el apóstol Santiago dijo:
"`Porque cualquiera que ofendiere en un punto, se hace culpable de todos,`"^
footnote:[Santiago 2:10]
sino que nuestro supremo legislador, Cristo mismo, dice:
"`Y a cualquiera que me niegue delante de los hombres,
yo también le negaré delante de mi Padre que está en los cielos.
Y el que se avergonzare de mí y de mis palabras,
el Hijo del Hombre se avergonzará también de él,
cuando venga en la gloria de su Padre con los santos ángeles.`"^
footnote:[Mateo 10:33; Marcos 8:38]
Y para animarnos a la fidelidad también dijo: "`Y no temáis a los que matan el cuerpo,
mas el alma no pueden matar;
temed más bien a aquel que puede destruir el alma y el cuerpo en el infierno.`"^
footnote:[Mateo 10:28]
Sus palabras son en verdad tan enfáticas,
que no debería disgustarle a nadie que las repita tal como
han sido registradas por el evangelista Lucas:
"`Mas os digo, amigos míos: No temáis a los que matan el cuerpo,
y después nada más pueden hacer.
Pero os enseñaré a quién debéis temer:
Temed a aquel que después de haber quitado la vida, tiene poder de echar en el infierno;
sí, os digo, a este temed.`"^
footnote:[Lucas 12:4-5]

¿Cómo no van a impresionar estas palabras a un verdadero Cristiano?
Y más cuando consideramos que nada en el mundo puede
recuperar o restaurar a un alma que perece,
como puede verse en estas palabras de nuestro bendito Señor:
"`Porque ¿qué aprovechará al hombre, si ganare todo el mundo, y perdiere su alma?
¿O qué recompensa dará el hombre por su alma?`"^
footnote:[Mateo 16:26]
Una clara prueba de que el mundo entero y todo lo que está contenido en él,
no puede salvar un alma, ni proveer algo que la pueda redimir.
Si yo lo considerara necesario,
en este momento un celo piadoso me haría decir más sobre este tema,
pero para no extenderme demasiado e ir más allá de los límites de este tratado histórico,
no continuaré con este paréntesis, sino que volveré al relato del que me aparté.

Entonces, para retomar de nuevo el hilo de mi discurso, una vez más voy a Jeremy Ives,
quien para evitar la persecución, había prestado juramento en contra de su entendimiento.
Fue Thomas Rudyard, aludido aquí antes, quien le mencionó la carta, y Ives mismo,
sintiéndose tenso por ello, se esforzó por quebrar la fuerza de ésta diciendo,
que la razón por la que había culpado a sus amigos en la carta,
era únicamente porque habían dicho que preferían dar cincuenta
libras antes que prestar el juramento de lealtad,
y que sin embargo, juraban haberlo hecho libre y voluntariamente.
Pero, ¿hay alguien que no pueda ver cuán pobre fue la razón que dio?

Ahora pasemos a la disputa;
ya he mencionado que se afirmaba que los Cuáqueros no eran Cristianos,
y para mantener esto, Thomas Hicks usó el siguiente silogismo:

[.syllogism]
* Los que niegan a Cristo el Señor, no son Cristianos;
* No obstante los Cuáqueros niegan a Cristo el Señor,
* Por tanto, los Cuáqueros no son Cristianos.

A esto W. Penn dijo: "`Niego la menor,^
footnote:[Un silogismo categórico consta de tres partes: una premisa mayor,
una premisa menor y una conclusión. Argumentar con silogismos era la forma
más común de debate público entre la clase culta de la época.]
que es, que los Cuáqueros niegan a Cristo el Señor.`" Y T. Hicks respondió:

[.syllogism]
* Los que niegan que Cristo es una persona distinta fuera de ellos, niegan a Cristo el Señor;
* No obstante los Cuáqueros niegan que Cristo es una persona distinta fuera de ellos;
* Por tanto, los Cuáqueros niegan a Cristo el Señor.

W+++.+++ Penn pidió entonces,
que T. Hicks explicara lo que quería decir con el término "`persona.`"
Y T. Hicks respondió: "`Me refiero a Jesucristo hombre.`"
A lo que W. Penn replicó: "`Entonces niego la menor, que es,
que nosotros negamos a Jesucristo hombre.`"
A esto Hicks respondió: "`Yo puedo probar que ustedes niegan a Jesucristo hombre.
Uno de sus escritores dice que Cristo nunca fue visto con ojos carnales,
ni oído con oídos carnales.`"
A esto J. Ives añadió:

[.syllogism]
* El que niega que Cristo nunca fue visto alguna vez con ojos carnales, etc. niega a Jesucristo hombre;
* No obstante los Cuáqueros niegan que Cristo fue visto alguna vez con ojos carnales;
* Por tanto, los Cuáqueros niegan a Jesucristo hombre.

George Keith dijo entonces: "`Yo respondo distinguiendo lo siguiente:
Cristo como Dios nunca fue visto con ojos carnales;
pero como hombre fue visto con ojos carnales.`"
A esto J. Ives replicó: "`Pero Él era Cristo mientras era hombre;
¿cómo no iba a ser visto Cristo con los ojos de la carne?`"
A esta pregunta G. Keith respondió así:
"`Debemos considerar que el término o nombre '`Jesucristo`'
a veces es aplicado a Él como Dios,
y a veces a Él como hombre; sí,
a veces incluso al propio cuerpo de Jesús. Pero la pregunta es,
si ese nombre pertenece más apropiada, directa y originalmente a Él como Dios, es decir,
como era Él antes de que se hiciera hombre; o a la naturaleza humana misma.
Nosotros afirmamos que ese nombre es dado a Él más apropiada y eminentemente como Dios;
menos apropiadamente, pero aun verdaderamente, como hombre;
y menos apropiadamente a Su cuerpo, sí, a Su cuerpo muerto.`"
Entonces J. Ives preguntó: "`¿Dónde lees que al cadáver se le llamara el Cristo?`"
Esta expresión irreverente disgustó tanto a muchos, que algunos gritaron:
"`¿Dónde has leído que al cuerpo muerto de Cristo alguna vez se le llamara cadáver?`"
A raíz de este disgusto W. Penn dijo: "`Les ruego por amor al Señor,
que tratemos estas cosas como corresponde a Cristianos.`"

G+++.+++ Keith retomó entonces el discurso respondiendo a la pregunta de J. Ives así:
"`Pruebo que el cuerpo muerto de Jesús fue llamado Cristo,
a partir de las palabras de María,
'`¿Dónde lo han puesto?`' Porque ella justo antes
había llamado al cuerpo su '`Señor.`' Así mismo,
el ángel le dijo:
'`Ved el lugar donde fue puesto el Señor.`' Y del hecho
de que Él era Jesucristo incluso antes de hacerse carne,
lo pruebo a partir de lo dicho por el apóstol: '`Dios,
que creó todas las cosas por Jesucristo.`'`"^
footnote:[Efesios 3:9]

Entonces T. Hicks dijo: "`Yo demostraré que los Cuáqueros no son Cristianos.`"
Y J. Ives añadió: "`Los que dicen que Cristo no puede ser visto con ojos carnales,
y que nunca fue visible para los hombres impíos, niegan a Cristo el Señor;
porque Él fue visto con ojos carnales y por los hombres impíos.`" A esto W. Penn dijo:
"`Yo distingo la palabra '`visto`';
porque los hombres impíos pudieron verlo en la apariencia corporal, y sin embargo,
no lo vieron como Cristo el Señor. Ellos vieron Su naturaleza humana,
pero no Su condición de Cristo.
Esto lo probaré a partir de las palabras de Cristo
a Pedro (cuando Pedro confesó que Él era el Cristo,
el hijo del Dios vivo) diciendo: '`Porque no te lo reveló carne ni sangre,
sino mi Padre que está en los cielos.`'^
footnote:[Mateo 16:17]
Por tanto, de esto se deduce que Pedro, con un ojo carnal,
no había podido ver a Cristo el Señor;
mucho menos lo habrían podido ver los hombres impíos. Mi
segunda prueba es a partir de las palabras del apóstol:
'`A quien ninguno de los príncipes de este siglo conoció; porque si lo hubieran conocido,
nunca habrían crucificado al Señor de gloria.`'^
footnote:[1 Corintios 2:8]`" W. Penn, ampliando un poco más este tema dijo también,
que ver y conocer en las Escrituras a veces eran equivalentes.
Y G. Keith añadió: "`Cristo dijo: '`El que me ha visto a mí, ha visto al Padre;`'^
footnote:[Juan 14:9]
pero ningún hombre impío ha visto al Padre, por tanto,
ningún hombre impío ha visto verdaderamente a Cristo como tal.`"
Ives y sus compañeros se burlaron de esta distinción,
pero los Cuáqueros afirmaron que todos los que vieron a Jesús como el hijo del carpintero,
realmente no lo vieron como el Cristo de Dios.

Entonces Ives preguntó:
"`¿Es la naturaleza humana una parte de Cristo el Señor?`" A esto W. Peen respondió:
"`Ustedes todavía no nos han respondido una pregunta,
pero le responderé a J. Ives la suya, si él promete responderme la mía.`" Entonces,
como Ives dijo que la respondería, W. Peen replicó: "`Yo declaro aquí,
que nosotros fielmente creemos que esa santa naturaleza
humana es miembro del Cristo de Dios.`"
Y luego dirigiendo su pregunta a Ives, le dijo:
"`¿Era Él el Cristo de Dios antes de que se manifestara en la carne?`"
"`Él era el Hijo de Dios,`" respondió Ives.
"`Pero,`" replicó W. Penn,
"`¿era Él Cristo el Señor? Probaré que era Cristo
el Señor tanto antes como después. Primero,
a partir de las palabras del apóstol Pablo a los corintios,
donde dice que Israel bebía '`de la Roca espiritual que los seguía,
y la Roca era Cristo.`'^
footnote:[1 Corintios 10:4]
Luego de Judas, en la que algunas copias griegas tienen así:
'`que Jesús sacó al pueblo de Israel de Egipto.`'^
footnote:[Judas 5]`" Pero a esto Ives no dio respuesta,
sin importar cuántas veces se le pidió.

Esto no era de extrañar,
dado que era bien sabido que entre los Bautistas había algunos
que estaban a favor de los principios Socinianos.
Sin embargo, Ives para no parecer del todo sin palabras, volvió a hacer una pregunta,
diciendo: "`¿Creen que Cristo en Su naturaleza humana está en el cielo?`"
Esto hizo que G. Whitehead le dijera a la audiencia:
"`Ustedes han escuchado la acusación contra nosotros,
y la distinción que se ha hecho entre los dos tipos de ver a Cristo; a saber,
entre el ver espiritual salvador de Cristo el Señor, y el ver Su hombre exterior,
persona o cuerpo.
En este último sentido nunca se quiso decir que Él no fuera visible al ojo externo,
sino más bien, que Él era el Cristo, la Roca espiritual de la que todo Israel bebió;
que Él era antes que Abraham fuese;
que Él estaba glorificado con el Padre antes de que el mundo comenzara;
y que Cristo Mismo le dijo a Felipe: '`El que me ha visto a mí, ha visto al Padre`';
pues sólo los santos, o hijos de la luz, pueden decir verdaderamente:
'`hemos visto Su gloria, como del unigénito del Padre,
lleno de gracia y de verdad.`' En todas estas últimas consideraciones, o sentido de ver,
Cristo el Señor sólo fue visto espiritualmente, y no con los ojos carnales.`"
Ives concedió esto para que así se dejara este tema.

Sin embargo, inmediatamente después,
en lugar de probar que los Cuáqueros no eran Cristianos, volvió a preguntar:
"`¿Creen o reconocen ustedes que Cristo está en el cielo con Su naturaleza humana?`"
A esto W. Penn respondió:
"`Creemos que el hombre Jesucristo está glorificado en el cielo.`"
Pero al ver que Ives se negaba a aceptar esa respuesta
porque no se ajustaba a los términos de su pregunta,
Penn preguntó:
"`¿Qué diferencia hacen entre el ser hombre y naturaleza humana de Cristo?`"
"`Ninguna,`" respondió Ives, "`si hablas con franqueza.`"
A esto Penn respondió: "`Hablo con franqueza;
nosotros creemos que esa naturaleza humana santa está en la gloria celestial.`"

Ahora bien, como empezó a oscurecer,
los Bautistas querían dejar el debate y reanudar el asunto en otro momento;
pero las partes no pudieron ponerse de acuerdo.
Porque aunque los Bautistas seguían afirmando que los Cuáqueros no eran Cristianos,
se dieron cuenta de que los Cuáqueros tenían abundante razón para mantener lo contrario;
y esto lo habían hecho tan efectivamente, que los del otro partido,
bajo el pretexto de que el lugar de reunión estaba sobrecargado de personas,
y de la posibilidad de que la galería cediera,
disolvieron la reunión sin llegar a una conclusión final.

Este año la persecución en Londres no era muy aguda,
pero estaba muy activa en otros lugares,
por lo que no me falta material para hacer un extenso relato de ella.
Pero para evitar la redundancia, sólo mencionaré un caso.

Un tal Robert Tillet, en Buckingham,
que estaba enfermo de tisis y creía que su muerte estaba próxima,
quiso que algunos de sus amigos lo visitaran.
En respuesta a esta invitación llegaron a su casa algunos de ellos,
en un número no mayor de catorce personas.
Entonces, dos informantes fueron a poner sobre aviso a un juez de paz,
quien registró esa pequeña asamblea como una reunión sediciosa,
y multó al enfermo con veinte libras por su supuesta transgresión;
y por eso le confiscaron sus bienes y le quitaron seis vacas.
Y a un tal Robert Smith,
al que los informantes habían escuchado decir cinco o seis palabras,
también lo multaron con veinte libras como predicador;
multa que después fue exigida a algunos otros de los que estaban presentes en ese momento.

La paz entre Inglaterra y Holanda se firmó este año, ante la insistencia de España,
pero la guerra entre Holanda y Francia continuó.

Ahora paso al año 1675, a principios del cual G. Fox llegó a Londres,
mientras el Parlamento sesionaba y aconsejaba al rey que
suprimiera el crecimiento del papismo entre tanto,
los Cuáqueros seguían soportando la mayor parte de la persecución,
pues sus reuniones religiosas eran comúnmente denominadas conventículos sediciosos.

Después de asistir a la reunión anual de sus amigos en Londres,
G+++.+++ Fox dejó la ciudad y se fue a Lancaster, y de ahí a Swarthmore.
Allí, al tener una vivienda propia, permaneció casi dos años para descansar,
porque había contraído varias dolencias a causa de las privaciones
y encarcelamientos que habían debilitado mucho su cuerpo.
Estando allí,
se enteró de que cuatro jóvenes estudiantes de Aberdeen
habían sido convencidos de la verdad,
en una disputa que Robert Barclay y George Keith habían
sostenido con algunos de los eruditos de esa universidad.
En una ocasión, siendo visitado por algunos de los vecinos,
llegó también el coronel Kirby, su antiguo perseguidor,
que ahora se portaba muy afectuoso y le dio la bienvenida al condado.
A pesar de esta aparente amabilidad,
tiempo después les ordenó a los alguaciles de Ulverstone,
que le dijeran a G. Fox que no debía tener más reuniones en Swarthmore,
porque si lo hacía, ellos tenían la orden del coronel de disolverlas;
y que se presentarían el Domingo siguiente.
Pero esta amenaza no amedrentó a G. Fox,
porque él con sus amigos celebraron su reunión ese Primer-día y nadie llegó a molestarlos.
Durante su estancia en casa,
cuando no estaba viajando de un lado a otro del condado
edificando a sus amigos como solía hacerlo,
suplía esa necesidad con su pluma,
y los exhortaba por escrito cada vez que no podía hacerlo de palabra.
Además de esas cartas y epístolas, también escribió tratados de utilidad,
pues era un hombre diligente.

Mientras tanto, la persecución por la adoración a Dios no cesó por completo.
La ley contra los conventículos sediciosos les dio oportunidad a los malintencionados,
de perturbar las reuniones religiosas de los Cuáqueros,
que nunca se reunieron de manera clandestina, sino siempre públicamente.
Por este motivo se les impusieron muchas multas, a lo que hay que añadir,
que a menudo eran muy maltratados y gravemente lastimados, como en Long Claxston,
en Leicestershire,
donde algunas mujeres fueron arrastradas del cuello a lo largo de la calle.
Entre estas había una viuda, a quien se le arrancó la piel del cuello por esta grosería;
y una anciana de más de setenta años fue violentamente arrojada al piso.
Algunos de los hombres fueron arrastrados del pelo y otros de las piernas,
además de los muchos golpes que les dieron.
De hecho, algunos fueron pisoteados hasta hacerlos sangrar por sus bocas y narices.
Sin embargo, todo esto lo soportaron pacientemente, sin oponer resistencia;
y en algunas ocasiones sucedió, que los que no tenían el don de predicar,
alcanzaron a otros mediante sus pacientes sufrimientos,
al mostrar por su comportamiento manso que sus obras concordaban con su profesión Cristiana.
Y aunque muchos fueron despojados de todo lo que tenían,
incluso de sus ropas y de sus camas, continuaron firmes sin desmayar;
aunque a menudo se llamaba "`reunión,`" cuando algunos se
congregaban no propiamente para realizar la adoración religiosa,
como ya ha sido relatado.

En Kirby Muckloe,
donde varios habían acudido a la casa de John Penford
para proveer para los pobres entre ellos,
el sacerdote de la parroquia, llamado John Dixon,
informó contra ellos por carta a Wenlock Stanly, de Branston,
quien envió a tres de sus criados a inspeccionar dicha reunión. Y aunque estos
hombre revisaron el libro donde se había anotado la distribución de la caridad,
y encontraron que la reunión sólo había sido para
considerar las necesidades de los pobres,
varios fueron multados,
y el mismo J. Penford fue multado con veinte libras por su casa y diez libras por predicar;
porque como se le oyó hablar,
eso fue considerado suficiente para hacerlo pasar por predicador.
Ahora bien, aunque él y Richard Woodland apelaron a la justicia,
el tribunal les denegó rotundamente la apelación,
a menos que primero prestaran el juramento de lealtad.
Esta era la vieja trampa; por tanto,
se les negó su audiencia y se les impuso el triple de daños.

En Lewes, Sussex, el sacerdote William Snat se convirtió en informante,
y fue varias veces a la reunión de los Cuáqueros en ese lugar,
y de ahí al juez Henry Shully,
a quien le declaraba bajo juramento dónde había sido
celebrada la reunión y quién había predicado.
Este asunto era tan infame, que una vez dio información falsa con respecto a la casa;
pero la ganancia que resultaba de este trabajo, sin importar cuán abominable fuera,
brillaba tan seductoramente, que un pariente suyo llamado James Clark,
también entró en el oficio de informante; algo que cualquiera podía hacer fácilmente.

En Norfolk, la rabia de los perseguidores era tal,
que algunos que habían sido despojados de todo,
se vieron obligados a acostarse sobre paja, incluso en invierno,
como fue el caso de Joseph Harrison, su esposa y sus niños. Sin embargo,
esta incansable familia, no dejó de asistir a sus reuniones religiosas.
De hecho, ni siquiera se les permitía descansar a los muertos,
porque esta ultrajante barbarie llegó a tal altura, que Mary,
la esposa de Francis Larder, tras haber muerto y haber sido sepultada,
fue desenterrada por orden de un tal Thomas Bretland, por lo que se quebró el ataúd,
se arrastró y se expuso el cadáver en el mercado.
Así,
a esta mujer fallecida no se le permitió estar más tranquila
en su tumba de lo que había estado en su lecho de enferma,
pues el día anterior a su muerte,
había sido amenazada por orden de un tal Christopher Bedinfield,
con quitarle su cama mientras viviera.
Ahora, la razón para llevarse su cadáver fue,
que como su esposo era uno de los llamados Cuáqueros (aunque
ella no había sido propiamente miembro de dicha sociedad),
fue tomado a mal que hubiera sido enterrada de manera sencilla,
sin pagarle al sacerdote sus supuestos honorarios
por el acostumbrado servicio sobre los muertos.

En Somersertshire, treinta y dos personas fueron multadas por haber estado en un entierro.
Lo mismo sucedió en el condado de Derby,
donde Samuel Roe (tras morir su esposa) fue multado con veinte libras porque
sus amigos se habían reunido en su casa para llevar el cadáver a la tumba.
El sacerdote John Wilson actuó como informante ante el juez de paz, John Loe;
y de la casa del mencionado Samuel Roe se tomó el equivalente a treinta libras,
de modo que la parte del informante no fue menor de diez libras, dado que según le ley,
le correspondía un tercio del botín.

Podría relatar varios casos de grandes calamidades y tristes
juicios que cayeron sobre algunos de estos crueles perseguidores,
pero para no extenderme demasiado,
he pasado silenciosamente por muchos casos sorprendentes.
Sin embargo, en términos generales puedo decir, que muchos de los perseguidores,
tanto magistrados como informantes y otros, tuvieron un final miserable.
Algunos fueron sacados de esta vida por muertes repentinas o antinaturales,
y otros por persistentes enfermedades o dolencias,
o por enfermedades asquerosas y fétidas; mientras que otros,
por los botines que habían recogido acumularon grandes riquezas,
y después cayeron en gran pobreza y mendicidad.
Podría enumerar muchos nombres y mencionar también el tiempo y el lugar, y entre ellos,
a algunos eclesiásticos rapaces que tuvieron un triste final;
pero intencionalmente omito particularizar tales
casos para evitar la apariencia de rencor y envidia.
Algunos de los que habían sido muy activos en el despojo,
declararon con sus propias bocas el terrible remordimiento
de consciencia que sentían por haber perseguido a los Cuáqueros,
a tal punto, que algunos gemían su constante aflicción, mezclada con desesperación,
bajo los severos dolores que sufrían en sus cuerpos.

Fue juzgado por muchos como un caso muy notable, que alrededor del año 1663,
un tal Christopher Glin, sacerdote de Burford,
que había actuado con un celo muy imprudente contra los Cuáqueros,
después de leer su texto en el púlpito y luego intentar leer su sermón,
fue repentinamente golpeado con ceguera,
y continuó ciego hasta que murió. Pero ninguno de los perseguidores
parecía darse por enterado o considerar tales casos,
pues siguieron dándole rienda suelta a su ira contra los Cuáqueros;
quienes a pesar de todo, continuaban con paciencia,
si bien no creían que fuera ilícito denunciar la
grave opresión ante los que estaban en autoridad,
para que no se excusaran como ignorantes de estos violentos procedimientos.
Por tanto, no dejaron de publicar en forma impresa,
muchos de los casos notorios que han sido relatados aquí,
y de presentarlos al rey y al Parlamento con humildes discursos para tal efecto.
Pero todo esto encontró poca acogida.
El rey Carlos, al parecer, no iba a ser el hombre que quitaría el yugo de la opresión,
esta obra fue reservada para otros.
Su hermano James, quien fue su sucesor, empezó a hacerlo,
con qué intención sólo el cielo lo sabe;
y William III (ese excelente príncipe) la llevó
a la perfección en la medida de sus posibilidades.

Este año falleció en el mar William Bayly,
regresando de las Indias Occidentales en el barco llamado el "`Samuel,`" de Londres,
en la latitud de 46 grados y 36 minutos.
Él había sido maestro entre los Bautistas,
y había leído mucho de los libros de Jacob Boehme,
pero no había encontrado por ello una verdadera satisfacción para su alma.
Y después de entrar en sociedad con los llamados Cuáqueros,
se convirtió en un celoso predicador entre ellos.
Cuando en este último viaje se enfermó y sintió que se aproximaba la muerte,
le pidió a John Clark, capitán del mencionado barco,
que le diera recuerdos a su esposa y a sus pequeños, y también a George Fox,
George Whitehead y a otros; y sintiéndose lleno de gozo empezó a cantar:
"`La Palabra creadora del Señor permanece para siempre.`"
Tomó de la mano a varios que estaban a su alrededor y los exhortó a temerle al Señor,
y a no temerle a la muerte.
"`La muerte,`" dijo, "`no es nada en sí misma;
porque el aguijón de la muerte es el pecado.
Díganles a los Amigos en Londres, que se habrían alegrado de ver mi rostro,
que voy a mi Padre y al Padre de ellos, a mi Dios y al Dios de ellos.
Recuérdenle a mi esposa mi amor por ella; ella será una viuda triste,
pero no dejen que se lamente demasiado, porque yo estoy bien.`"
Y después de hablarle al capitán algo sobre sus asuntos externos,
dijo con respecto a su esposa y a sus hijos: "`No les he dejado porciones externas,
sino que mi esfuerzo ha sido hacer de Dios, el Padre de ellos.
¿Recostaré mi cabeza sobre las aguas?
Bien, Dios es Dios de todo el universo; y aunque mi cuerpo se hunda en el mar,
nadaré sobre las aguas.`"
Luego, despidiéndose del grupo dijo: "`No puedo ver a ninguno de ustedes,
pero les deseo lo mejor.`"
Y cuando uno le preguntó cómo estaba, respondió: "`Estoy perfectamente bien.`"
Después de decir muchas más palabras sensibles,
partió tranquilamente a eso de las cuatro de la mañana,
como si se hubiera quedado dormido.
Su esposa Mary,^
footnote:[El nombre de soltera de Mary Bayly era Mary Fisher,
mencionada en los capítulos 7 y 10 de esta historia.]
la misma que anteriormente había estado en Adrianópolis
y hablado con el emperador de los turcos,
escribió un excelente testimonio de él. Y John Crook,
en el prefacio de las obras de W. Bayly,
dio el siguiente testimonio de él (cuya verdad conozco por mi propia experiencia):

[quote]
____
Así como era audaz y celoso en su predicación,
al estar dispuesto a aprovechar su tiempo (como si hubiera
sabido que no iba a estar mucho tiempo entre nosotros),
también era valiente en sufrir por su testimonio cuando era llamado a ello.
Una vez lo vi ponerse de pie en el estrado para defender su causa inocente,
como el santo Esteban ante el Sanedrín,
cuando las amenazas de sus perseguidores se asemejaban a
la lluvia de piedras cayendo sobre aquel bendito mártir,
gritando con ruidos espantosos: "`¡Llévatelo, carcelero!,`" etc., y sin embargo,
en todo ese rato no cambió su semblante,
salvo por el adorno adicional de algunas sonrisas inocentes.
En una ocasión,
los crueles perseguidores lo lanzaron al piso y lo
arrastraron jalándolo del pelo de su cabeza,
y se esforzaron por desgarrarle la boca y quebrarle la mandíbula,
de modo que el suelo donde estaba quedó manchado con su sangre.
Y como si esta carnicería no hubiera sido suficiente para
convertirlo en un sacrificio idóneo para su crueldad,
un perseguidor corpulento y pesado le pisó el pecho con los pies,
tratando de sacarle el aire.
Y después de que este perseguidor había cumplido su voluntad,
le ordenó al carcelero que se lo llevara y lo pusiera en algún hueco apestoso
para su abrigo y curación. Y si el Dios de Israel no hubiera sido su médico ahí,
habría sido quitado de entre nosotros mucho tiempo antes.
____

Al principio de este año, 1676, murió en Londres un tal Matthew Hyde.
Este hombre se había dedicado por espacio de veinte años,
a contradecir públicamente a los Cuáqueros en sus reuniones,
y a molestarlos en su adoración a Dios,
pensando (a partir de un celo ciego) que le hacía a Dios un servicio aceptable,
mediante su celosa oposición a lo que él juzgaba ser herejía. Ahora bien,
por mucho que este hombre se inclinara contra ellos, mostraba esta moderación,
que en su oposición no se comportaba con furia, sino que parecía bien intencionado,
aunque se equivocaba enormemente,
y con frecuencia obstaculizaba la predicación de los ministros entre los Cuáqueros.
Esto llevó a William Penn a orar a veces a Dios muy fervientemente por él,
y a decirle en presencia de muchos oyentes que Dios
disputaría con él por medio de Sus justos juicios,
y que llegaría el momento cuando se vería forzado a confesar
la suficiencia de esa luz a la que entonces se oponía,
y a reconocer que Dios estaba con aquellos que eran llamados Cuáqueros.

Este mismo Hyde, estando al borde de la muerte por una enfermedad,
pidió que se enviaran a buscar a George Whitehead y a algunos de sus amigos.
A un tal Cotton Oade,
que le preguntó si tenía algo que decir para limpiar su consciencia por haberse
opuesto tan a menudo al pueblo llamado Cuáquero en su ministerio y oraciones,
le dijo: "`Lamento lo que he hecho, porque ellos son el pueblo de Dios.`"
Entonces G. Whitehead, que había llegado con otros a pesar de que era tarde en la noche,
le dijo: "`He venido con amor y ternura para verte.`"
A esto Hyde respondió: "`Me alegra verte.`"
Whitehead dijo: "`Si tienes algo en tu consciencia que decir,
deseo que limpies tu consciencia.`"
M+++.+++ Hyde respondió: "`Lo que tengo que decir, lo digo en la presencia de Dios.
Así como Pablo persiguió al pueblo del Señor, yo los he perseguido a ustedes, Su pueblo;
de la misma manera que el mundo persigue a los hijos de Dios.`"
Habló más, pero como estaba muy débil, sus palabras no pudieron ser bien entendidas.
Entonces G. Whitehead continuó:
"`Tu entendimiento estaba oscurecido cuando las tinieblas estaban sobre ti,
y te has opuesto a la verdad y al pueblo del Señor; y sé que esa luz a la que te oponías,
se levantará en juicio contra ti.
A menudo me esforcé, junto con otros, por llevarte al entendimiento correcto.`"
A esto Hyde dijo: "`Declaro esto en la presencia de Dios y de todos los que están aquí:
He hecho mal al perseguirlos a ustedes que son los hijos de Dios, y lo lamento.
Que el Señor Jesucristo tenga misericordia de mí,
y que el Señor incremente el número de ustedes y esté con ustedes.`"

Después de una pausa G. Whitehead le dijo: "`Quisiera, si puedes hablar,
que alivies tu consciencia tanto como puedas.
Mi alma se conmueve al oírte confesar así tu mal,
dado que el Señor te ha dado un sentido de este.
En el arrepentimiento hay misericordia y perdón;
al confesar y abandonar el pecado se encuentra la misericordia del Señor,
quien en medio del juicio se acuerda de la misericordia, para que Él sea temido.`"
M+++.+++ Hyde que estaba en gran angustia y luchando por respirar, dijo poco después:
"`He hecho mal al oponerme a ustedes durante sus oraciones;
que el Señor tenga misericordia de mí. Y así como
he sido un instrumento para alejar a muchos de Dios,
que el Señor levante muchos instrumentos para volver a muchos a Él.`" G. Whitehead continuó:
"`Quiero que encuentres misericordia y perdón en
la mano del Señor. ¿Cómo está tu alma ahora?
¿No encuentras algo de alivio?`"
"`Espero que sí,`" respondió Hyde, "`y si el Señor alargara mis días,
estaría dispuesto a dar testimonio a favor de ustedes,
tan públicamente como he aparecido contra ustedes.`"
Entonces su esposa dijo: "`Es suficiente; ¿qué más se podría desear?`"
Entonces Whitehead le preguntó: "`Si el Señor no alargara tus días,
¿deseas que lo que has dicho se comunique a otros?`"
"`Sí quiero,`" respondió Hyde, "`puedes hacerlo; he dicho todo lo que podía decir.`"
Después de un rato de silencio, ya que le faltaba mucho el aire, Whitehead dijo:
"`Si esta compañía te resulta cansada, podemos retirarnos.`"
A lo que respondió: "`Pueden hacer uso de su libertad.`"
Entonces G. Whitehead despidiéndose de él dijo: "`Te dejo en las manos del Señor,
y deseo que Él te muestre misericordia y perdón, como espero que lo haga.`"
Sobre esto, M. Hyde replicó: "`Que el Señor esté con sus espíritus.`"

Todo esto fue dicho a G. Whitehead y a sus amigos en presencia de la esposa de Hyde,
y de algunos otros conocidos de él, unas dos horas antes de su muerte,
y así dio pruebas manifiestas de un sincero arrepentimiento.
Porque su esposa Elizabeth, al verlo muy atribulado en su mente le había preguntado,
si deseaba hablar con algunos de los Cuáqueros.
Y él golpeándose el pecho con una mano había dicho: "`Con toda mi alma.`"
Después de que G. Whitehead y sus amigos se fueron, siendo el séptimo día,
varias veces expresó su deseo de vivir hasta la mañana,
para poder dar testimonio ese día (el primer día de la semana),
a favor de la verdad a la que se había opuesto tan frecuentemente; sin embargo,
dio a entender que ya había encontrado cierto alivio en su espíritu.
También exhortó a su esposa, que conversaba mucho con gente importante del mundo,
a que usara el lenguaje sencillo de los Cuáqueros.
Y después de algunas palabras más en este sentido,
pronunciadas por él con buen entendimiento, se estiró y murió muy tranquilo.

En efecto, aquí vemos una muy evidente señal de la inefable misericordia de Dios,
quien no desea la muerte de ningún pecador, sino que se arrepienta y viva; y quien,
conociendo plenamente la verdadera disposición del corazón del hombre,
perdona el pecado por mera gracia, sin ningún mérito en el hombre,
sino por amor a Sí mismo, como Él mismo lo ha dicho: "`Yo,
yo soy el que borro tus rebeliones por amor de mí mismo,
y no me acordaré de tus pecados.`"^
footnote:[Isaías 43:25]
La verdad de este dicho se vio muy claramente en el ladrón convertido en la cruz,
aunque su impenitente compañero de sufrimiento endureció su corazón contra ésta.

Este año, mientras G. Fox estaba en Swarthmore, murió William Lampitt,
el sacerdote de Ulverstone,
quien anteriormente había sido un gran amigo de Margaret (ahora esposa de G. Fox),
pero se había vuelto tan envidioso contra los amigos con los que ella estaba en sociedad,
que en el año 1652 dijo,
que él daría su vida con tal de que los Cuáqueros desaparecieran
y que en el término de medio año se convirtieran en nada.
Pero en su lecho de muerte le dijo a uno de sus oyentes que había llegado a visitarlo:
"`He sido predicador por mucho tiempo y creía que había vivido bien;
pero no creí que fuera porque está en la experiencia en progreso tan duro morir.`"

En Norwich,
se hicieron grandes despojos contra los Cuáqueros debido a sus asambleas religiosas.
En una ocasión Erasmus Cooper entró en la casa de Anthony Alexander,
y le dijo a su esposa que estaba esperando un hijo,
que había llegado a confiscar todo lo que ella tenía. "`¿Todo?,`" dijo ella,
"`¿por una multa de siete libras?
Eso es duro.`"
Pero él menospreciando lo que ella había dicho replicó,
que no le dejaría una cama sobre la cual acostarse.
Entonces empezaron a quebrar las puertas con un pico,
y él y sus compañeros se comportaron tan cruelmente,
que hizo llorar a algunos de los vecinos que estaban viendo.
En un momento dado, estos saqueadores forzaron al criado de Alexander a que los ayudara;
lo que hizo que Alexander dijera que era la cosa más irracional
exigirle al criado que los ayudara a tomar los bienes de su amo.
En respuesta a esto, el supervisor, Robert Clerk, le gruñó y le dijo:
"`Son _nuestros_ bienes.`"

Los mencionados oficiales también llegaron a la casa de Samuel Duncon,
y con ellos el informante Charles Tennison y el verdugo.
Allí estuvieron varios días y noches, y mantuvieron a la esposa de Samuel,
que estaba esperando un hijo, prisionera en su propia casa, sin dejarla hablar con nadie,
ni dejar que nadie llegara a verla.
Y después de que habían roto todas las puertas cerradas,
se llevaron un valor aproximado de cuarenta y tres libras en bienes.
Estos informantes eran tan insolentes, que uno no dudó en decir:
"`Haré que el alcalde me atienda cuantas veces quiera; a mi antojo.`"
En realidad, esta perversa banda se había hecho tan poderosa,
que nadie se atrevía a oponerse a ellos por temor a caer en desgracia con el tribunal;
pues era animados por los que estaban en altos puestos,
y probablemente por la insistencia de los papistas, o por los afectados por el papismo.

Este verano llegó a una reunión de los Cuáqueros en Norwich, el alguacil William Poole,
junto con un informante que había hecho que lo acompañara,
y al escuchar la predicación clamó con lágrimas en sus ojos: "`¿Qué debo hacer?
Sé que el poder de Dios está entre ustedes;`" y luego le dijo al informante,
que si había una maldición colgando sobre algún pueblo sobre la tierra,
era sobre los informantes.
Y el informante Tennison, que había ayudado a llevarse los bienes de Samuel Duncon,
estando después encarcelado por deudas,
confesó que nunca había prosperado desde que se había dedicado a ese trabajo;
y dijo que si era liberado, nunca más se metería en eso.

En Nottinghamshire también se realizaron grandes despojos y estragos,
de los que el juez Robert Thoroton fue un gran instrumento.
Pues en Sutton otorgó una orden para confiscar los bienes de dos personas,
una de la cuales era una mujer,
que después de hablar cinco o seis palabras en la reunión--lo que,
según el testimonio de algunos oficiales que estaban presentes,
no era de ninguna manera una predicación--fue delatada como "`predicadora,`" y por tanto,
multada por el mencionado juez Thoroton con veinte libras.
Como ella no podía pagar,
la mitad de la multa fue cargada sobre ella y la otra mitad fue cargada sobre John Fulwood.
En otro momento, Thoroton dio una orden para confiscar los bienes de William Day,
un molinero.
A este hombre, que había estado en la reunión en Sutton, en la calle,
se le impuso una multa de veinte libras cuando el supuesto predicador no pudo pagar;
aunque W. Day probó (y los oficiales que sacaron a sus amigos del lugar de reunión también
declararon) que las palabras que fueron llamadas "`predicación`" en dicha reunión,
no habían sido más que la respuesta a lo que otro había dicho.
A pesar de todo ello, Thoroton, a fin de proteger y gratificar al informante dijo:
"`Aunque sólo se haya dicho una palabra, es suficiente.`"
Una pobre mujer en South Collingham,
que ya había sido despojada de casi todo lo que tenía,
y a quien desde entonces sus amigos le habían provisto una cama y otras cosas necesarias,
también fue privada de esas cosas porque continuó asistiendo a las reuniones.
Matthew Hartly, un pobre hombre que vivía de hilar lana,
fue igualmente despojado de todo lo que tenía por asistir a la reunión del lugar.
Así sucedió con muchos otros,
cuyos nombre y apellidos podría mencionar si tuviera la intención de extenderme.
Y si sus amigos no se hubieran ocupado de ellos,
y de otras familias empobrecidas que había perdido todo mediante el despojo,
muchos podrían haber perecido.

En el pueblo de Hereford, las reuniones también eran perturbadas de tiempo en tiempo,
principalmente por muchachos que no sólo lanzaban piedras y excremento,
sino también petardos encendidos;
y hacían todo tipo de insolencias y travesuras contra este pueblo inofensivo;
ya fuera quebrando el vidrio de las ventanas, o las bancas y asientos.
Uno de los líderes de este revoltoso grupo era el hijo de un tal Abraham Seward,
quien por esta época fue electo alcalde.
Pero cuando le fueron presentadas las quejas sobre
las ultrajantes acciones de esta perversa banda,
fingió ignorar las acciones de su hijo,
y amenazó a los que habían acudido a él con aplicarles la ley si no suspendían sus reuniones.
Y como era bien sabido que el principal maestro de la escuela del pueblo,
estaba disgustado por la excesiva insolencia de algunos de sus estudiantes,
también se informó que se le había prohibido corregirlos por ello,
y que los sacerdotes los alentaban a hacerlo,
diciéndoles que los respaldarían en lo que hicieran,
pues algunos de estos salvajes muchachos eran cantantes del coro.
Dos amigos acudieron a los magistrados Robert Simons y Thomas Simons,
para informarles de los excesivos abusos que habían sufrido;
pero los magistrados no consideraron del todo su queja,
y R. Simons se esforzó por obtener de uno de ellos la confesión de alguna reunión,
con la intención, como él mismo dijo, de multarlo inmediatamente si hubiera confesado.

Ahora bien, como la insolencia de estos muchachos era alentada así por las autoridades,
no es de extrañar que continuara ahí todo un año. Finalmente,
ocho hombres fueron sacados de una reunión por el mencionado alcalde Abraham Seward,
y llevados al ayuntamiento; y de camino hacia el lugar,
el alcalde les dijo que nunca más se reunirían allí. En
respuesta a esto uno de los amigos que iba con él,
le dijo: "`Nosotros somos un pueblo congregado por el poder del Señor; por lo tanto,
el poder del hombre no puede dispersarnos.`"
Al llegar al ayuntamiento, les fueron presentados los juramentos de lealtad y supremacía,
sobre lo cual dijeron: "`Somos Cristianos; por lo tanto,
no podemos quebrantar el mandamiento de Cristo que nos prohíbe jurar en ninguna manera.
Sin embargo, no negamos ni rechazamos rendirle justa y legítima lealtad al rey.`"
Y por persistir en su negativa a jurar los enviaron a prisión. Al día siguiente,
un tal Walter Rogers, que era clérigo, pasó por la casa de reunión de los Cuáqueros,
y al observar cuán destruida estaba les dijo a algunos de los jóvenes,
que ellos eran muy buenos muchachos y que habían
hecho su trabajo mejor de lo que él había pensado.

En una de las sesiones trimestrales en Nottingham, apareció un tal John Sayton,
quien después de haber sido multado con veinte libras
por permitir un conventículo en su casa,
en la parroquia de Blyth, llegó a apelar a la justicia.
El testigo presentado contra él dijo:
"`Yo estaba ahí ese día y había varias personas reunidas,
pero todas estaban en silencio y no se dijo una palabra entre ellos;
pero no vi a John Sayton ahí.`" Ahora,
se hizo constar en audiencia pública mediante pruebas sustanciales,
que el mencionado John Sayton estaba a casi sesenta millas de la
casa ese mismo día. Entonces el abogado del acusado dijo:
"`En primer lugar, dado que no hubo predicación, oración,
ni lectura como el testigo declara, no pudo haber sido un conventículo religioso.
En segundo lugar, dado que no pueden probar que él estaba ahí,
¿cómo puede juzgarse que él haya consentido a sabiendas o voluntariamente
dicha reunión?`" A esto el abogado del informante objetó diciendo:
"`Aunque no haya habido predicación, oración o lectura,
es bastante evidente que estaban reunidos bajo el pretexto de un ejercicio religioso;
y dado que había más de cinco personas que no eran de la familia de John Sayton,
debe ser necesariamente un conventículo.
Y en cuanto a la segunda pregunta, dado que no podemos probar que él estaba ahí,
debemos dejar a la consciencia del jurado,
si él voluntariamente consintió o no la reunión.`"

Después de que hablaron los abogados de ambos lados, Peniston Whaley,
uno de los magistrados que ocupaba una silla como juez del tribunal,
se puso de pie y le dijo al jurado:
"`Aunque no había un ejercicio religioso visible que pueda ser probado,
los Cuáqueros dicen que ellos adoran a Dios en Espíritu y en verdad;
y nosotros sabemos que su manera es sentarse suspirando y gimiendo,`" etc.
Cuando el jurado regresó y el tribunal les preguntó:
"`¿Fallan a favor del rey o del acusado?,`" respondieron: "`A favor del acusado.`"
Esto disgustó tanto al mencionado juez Whaley,
que les pidió que salieran de nuevo y lo reconsideraran,
pero al decir uno de los hombres del jurado,
que ellos habían llegado a un acuerdo y habían considerado el asunto muy bien,
se enfureció de tal manera que les dijo: "`¡Todos ustedes merecen ser ahorcados;
porque no son mejores que los salteadores de caminos!`"
Tal vez él mismo era un informante, o un amigo especial de ellos,
y por eso lamentaba que el jurado lo hubiera privado del botín, o de una parte de este.

Había entonces una gran persecución en todas partes de Inglaterra,
y no le fue mejor al principado de Gales.
Este verano, en el condado de Merioneth, en el pueblo de Bala,
nueve personas fueron tomadas prisioneras y llevadas a la sesión
del tribunal bajo la acusación de no asistir a sus iglesias parroquiales,
y les fueron presentados los juramentos de lealtad y supremacía.
En vista de la negativa de ellos a prestar los juramentos,
los magistrados Kemick Eyton y Thomas Walcot declararon en audiencia pública,
que en caso de que los prisioneros se negaran a hacer los juramentos una segunda vez,
ellos debían ser procesados como traidores;
los hombres debían ser ahorcados y descuartizados, y las mujeres quemadas en la hoguera.
Pero estas amenazas no los amedrentaron;
porque en la siguiente sesión del tribunal cuando
les fueron presentados los juramentos de nuevo,
ellos continuaron negándose,
aunque solemnemente reconocieron su lealtad al rey como magistrado supremo.
En consecuencia, fueron enviados a una prisión cerrada,
donde uno de ellos llamado Edward Rees, que era de casi sesenta años,
no pudo soportar el frío y murió en el momento más gélido de la helada,
pues no se les permitió encender un fuego.

Un tiempo antes de esto, sucedió dentro de la corporación de Pool, en Montgomeryshire,
que el juez David Maurice entró en una casa donde un pequeño
número de personas estaban pacíficamente reunidas en silencio,
y les exigió que se marcharan.
Ante esto, Thomas Lloyd, uno del grupo,
empezó a decir unas pocas palabras para definir la verdadera
religión y qué era la verdadera adoración. Ahora bien,
lo que dijo fue tan razonable,
que el mencionado juez lo aprobó como sano y según la doctrina de la iglesia de Inglaterra.
Sin embargo, multó a Thomas Lloyd con veinte libras por predicar.

Este año murió en prisión John Sage, de casi ochenta años,
después de haber estado casi diez años prisionero en Ivelchester, en Somersetshire,
por no pagar los diezmos.
También resultó, que desde la restauración del rey Carlos,
más de doscientas personas de los llamados Cuáqueros habían muerto en prisión en Inglaterra,
donde habían estado confinados debido a su religión. Yo
podría relatar una gran cantidad de sucesos de este año,
si tuviera en mente extender mi obra; sin embargo, no puedo dejar de mencionar,
que este año, en la isla de Barbados, en las Indias Occidentales,
se promulgó una ley para evitar que los negros entraran a las reuniones de los Cuáqueros.
Dicha ley es como sigue:

[.embedded-content-document.legal]
--

Considerando que últimamente,
a muchos negros se les ha permitido permanecer en las reuniones
de los Cuáqueros como oyentes de sus doctrinas,
y les han enseñado sus principios,
por lo que la seguridad de la isla puede estar en peligro,
se promulga que si en algún momento después de la promulgación de la presente,
se halla a un negro, o negros, con el pueblo llamado Cuáqueros,
en cualquiera de sus reuniones, como oyente de sus predicaciones,
él o ella será decomisado--una mitad se embargará o demandará para él o ellos,
si pertenece a alguno de los Cuáqueros, y la otra mitad para el uso público de la isla.
Y si dicho negro, o negros,
no pertenece a ninguna de las personas presentes en la misma reunión, cualquier persona,
o personas,
podrá interponer una acción en virtud de este estatuto contra
cualquiera de las personas presentes en la mencionada reunión,
a elección del informante, y así cobrar diez libras por cada negro, o negros,
presente en dicha reunión como se ha dicho, para que sea dividido como se ha dicho.

Y ninguna persona podrá tener una escuela para instruir a un niño en cualquier aprendizaje,
a menos que primero preste los juramentos de lealtad y supremacía delante
de cualquier juez de paz de la parroquia donde vive la parte,
y obtenga un certificado de ello, u obtenga una licencia especial del gobernador,
bajo pena de tres meses de prisión y el decomiso de 300 libras de azúcar mascabado^
footnote:[El azúcar mascabado,
es azúcar no refinado o apenas refinado.]--una mitad para
el informante y la otra para el uso público de la isla.
Y ninguna persona, que no sea habitante o residente de esta isla,
y que no lo haya sido por doce meses seguidos,
podrá de aquí en adelante hablar o predicar públicamente en la reunión de los Cuáqueros,
bajo pena de seis meses de prisión y el decomiso de 1000 libras de azúcar mascabado,
una mitad para los que demandan por ello, y la otra para el uso público de la isla.

Leída y aprobada por el consejo el 21 de Abril de 1676,
y autorizada por su excelencia +++[+++el gobernador]
el mismo día.

[.signed-section-signature]
Edward Steed

[.signed-section-context-close]
Representante-secretario.

--

Aunque al principio de este estatuto,
la instrucción de los negros en la doctrina de los Cuáqueros es señalada
como algo por lo que la "`seguridad de la isla puede estar en peligro,`"
el resultado muestra que este no era en absoluto el asunto,
sino que se intentaba privar a los Cuáqueros de su debida libertad.

Este año Robert Barclay le escribió una carta a Herr Adrian Pacts,
con quien había tenido una conversación cuando el mencionado Herr regresaba de España,
donde había sido embajador de los Estados de las Provincias Unidas.
Herr Pacts, que tenía una extraña opinión de la doctrina de los Cuáqueros,
hacía un buen tiempo le había escrito una carta^
footnote:[Se encuentra en el libro llamado Prastantium ac
eruditorum virorum Epistole Eccksiastique & Theologica.
Amatelodami apud Franciscum Halman.
1704]
a Christian Hartzoeker, en Rotterdam, acerca de la doctrina de ellos;
y después de haber discutido con Barclay con respecto a
la revelación interior y directa del Espíritu de Dios,
esto llevó a Barclay a escribirle al mencionado Herr una carta del tema en latín,
en la que respondía más ampliamente a sus argumentos de lo que había hecho en persona.
Esta carta fue enviada de Escocia a Holanda, y entregada por Benjamín Furly en Rotterdam,
al mencionado Herr Pacts, expresándole el deseo de que se complaciera en responderle;
lo cual Pacts prometió que haría. Pero al continuar él deficiente en el caso,
Furly al final la publicó en forma impresa,
pero sin mencionar el nombre de la persona a quien había sido escrita,
únicamente que estaba dirigida a _Cuidam legato._
+++[+++En español: A cierto embajador.]

En esta carta se expuso en primer lugar, la objeción de Herr Pacts, a saber,
que puesto que el ser y la sustancia de la religión Cristiana
consistían en el conocimiento y fe con respecto al nacimiento,
vida, muerte, resurrección y ascensión de Jesucristo,
él consideraba que la sustancia de la religión Cristiana era una verdad contingente;^
footnote:[Una _verdad contingente_ es una proposición
que es verdadera pero que podría ser falsa.
La verdad de la proposición depende de otra cosa.
Una _verdad necesaria_ es una proposición que no podría ser falsa en ninguna circunstancia,
porque su negación implica una imposibilidad o una contradicción en la realidad.]
cuya verdad contingente era un asunto de hechos.
Y que los hechos, argumentaba él,
no podían ser conocidos excepto por el relato de otra persona,
o por la percepción de los sentidos externos; porque en nuestras almas naturalmente,
no había ideas de verdades contingentes,
como las había con respecto a las verdades necesarias,
tales como que '`Dios es,`' o que '`el todo es mayor
que la parte.`' Y dado que podía decirse,
sin caer en lo absurdo,
que Dios no podía hacer que una verdad contingente se convirtiera en una verdad necesaria,
ni podía hacer que las verdades contingentes o los hechos
fueran revelados sino a través de los sentidos externos,
la conclusión que se extraía de ahí era,
que los hombres no estaban obligados a creer que Dios hacía
alguna revelación en el alma con respecto a los hechos,
a menos que también añadiera algunos milagros que fueran obvios a los sentidos externos,
por medio de los cuales el alma pudiera comprobar
que la revelación venía indudablemente de Dios.

Todo esto fue ampliamente tratado por Barclay, como puede verse en la siguiente carta;
y varios años después, cuando Herr Pacts fue a Londres,
siendo uno de los comisionados de la compañía holandesa East India,
Barclay habló con él de nuevo y presentó el asunto de manera tal,
que Pacts fácilmente concedió que se había equivocado en su concepto de los Cuáqueros;
porque descubrió que podían hacer una defensa razonable
del fundamento de su religión. Con lo cual,
R+++.+++ Barclay tradujo la mencionada carta al inglés como sigue:

[.embedded-content-document.letter]
--

[.salutation]
Amigo mío,

Si bien considero que respondí completamente a todos
tus argumentos en la conversación que tuvimos,
con respecto a la necesidad y posibilidad de la revelación interna y directa,
y de la certeza de que la verdadera fe procede de ella; aun así,
debido a que después de que terminamos y nos separamos,
me recomendaste una mayor consideración de la fuerza de tu argumento,
como ese en el que supones que yace el eje mismo de la cuestión;
con el fin de satisfacer tu deseo y de que la verdad sea mejor presentada,
lo consideré aún más, pero cuánto más lo sopesaba, más débil lo hallaba.
Por lo tanto, para que tú mismo puedas juzgarlo mejor,
he creído conveniente enviarte mis nuevas consideraciones al respecto;
(lo cual habría hecho antes, si no me hubiera desviado en Londres y en otros lugares,
por otros asuntos necesarios), en las que no tengo dudas,
percibirás una respuesta completa y clara a tu argumento.
Pero si aún no pudieras ceder a la verdad,
o piensas que mi respuesta es defectuosa en alguna parte,
de modo que todavía te quede algún motivo de duda o escrúpulo, te pido encarecidamente,
que así como yo (por tu bien y amor a la verdad) no dejé de examinar
tu argumento y te comuniqué mis consideraciones al respecto,
te tomes la molestia de escribirme y enviarme lo que tengas que decir.
Lo cual, mi amigo N. N. que te entregó esto,
en el momento que tú señales recibirá de ti y me lo transmitirá,
para que al fin la verdad aparezca donde está.

Y para que todo el asunto se entienda más claramente, será conveniente, en primer lugar,
exponer tu argumento por el que te opones a la revelación directa de Dios en los santos,
y de allí concluyes que has derribado completamente el fundamento de los llamados Cuáqueros.
En cuyo argumento dices:

Que, puesto que (según juzgas tú) el ser y la sustancia de la religión Cristiana
consisten en el conocimiento y la fe con respecto al nacimiento,
vida, muerte, resurrección y ascensión de Jesucristo,
consideras que la sustancia de la religión Cristiana es una verdad contingente;
cuya verdad contingente es un asunto de hechos.
De lo cual razonas que:

"`Los hechos no pueden ser conocidos excepto por el relato de otra persona,
o por la percepción de los sentidos externos; porque en nuestras almas, naturalmente,
no hay ideas de verdades contingentes,
como las hay con respecto a las verdades necesarias,
tales como que '`Dios es,`' o que '`el todo es mayor
que la parte.`' Y dado que puede decirse,
sin caer en lo absurdo,
que Dios no puede hacer que una verdad contingente se convierta en una verdad necesaria,
ni puede hacer que las verdades contingentes o los hechos
sean revelados sino a través de los sentidos externos,
se deduce que los hombres no están obligados a creer que Dios hace
alguna revelación en el alma con respecto a los hechos,
a menos que también añada algunos milagros que sean obvios a los sentidos externos,
por medio de los cuales el alma pueda comprobar que
la revelación viene indudablemente de Dios.`"

Todo esto tratas de probarlo también, a partir de las escrituras en Romanos 10,
donde el apóstol dice:
"`La fe viene por el oír.`" Y como el apóstol después
habla de los que fueron enviados en número plural,
concluyes que de lo que se habla es de la predicación
externa por el ministerio de los hombres.
Y puesto que el apóstol formula una pregunta diciendo:
"`¿Cómo creerán si no oyen?,`" deduces a partir de la inducción y conexión del texto,
que el apóstol únicamente habla del oír externo;
y de aquí llegas a la conclusión de que sin el oír externo, la fe no puede ser producida.
Por lo tanto,
dices que no puede haber revelación directa por la
simple operación del Espíritu de Dios en la mente,
a menos que también se les proponga algo a los sentidos externos.

[.offset]
Antes de continuar con una respuesta directa a este argumento,
es necesario poner algunas premisas:

[.numbered-group]
====

[.numbered]
__Primera:__
Que se supone falsamente que la esencia de la religión Cristiana
consista en la fe y el conocimiento _histórico_ del nacimiento,
vida, muerte, resurrección y ascensión de Jesucristo.
Esta fe y conocimiento histórico son, en efecto, una parte de la religión Cristiana,
pero no una parte tan esencial como para que sin ella no pueda existir la religión Cristiana.
Sin embargo, es una parte integral que completa a la religión Cristiana,
como las manos y los pies son partes integrales del hombre, sin las que, no obstante,
puede existir, pero no como un hombre entero y completo.

[.numbered]
__Segunda:__
Si por revelación directa entiendes una revelación de Dios que engendra en nuestras
almas la fe y el conocimiento histórico del nacimiento de Cristo en la carne,
sin mediación de las Sagradas Escrituras,
no sostenemos que tal revelación sea algo comúnmente dado,
o algo que sea esperado por nosotros, o por cualquier otro Cristiano.
Porque si bien muchas otras verdades evangélicas se nos
muestran por medio de la directa manifestación de Dios,
sin usar las Escrituras, aun así,
el conocimiento histórico de Cristo no se nos manifiesta comúnmente, ni a ningún otro,
sino por las Sagradas Escrituras como medio, y eso mediante un objeto material.

[.numbered]
__Tercera:__ No obstante, decididamente afirmamos,
que Dios puede manifestar a nuestras mentes las verdades
históricas del nacimiento de Cristo,
etc., con la mayor facilidad, claridad, y certeza cuando le plazca,
incluso sin las Escrituras o cualquier otro medio externo.
Y debido a que tu argumento parece formulado contra la posibilidad de tal revelación,
procederé a discutirlo; pero primero debes notar,
que los profetas que predijeron la venida en la carne de Cristo,
Su nacimiento de una virgen, después Su muerte, etc.,
supieron de estos hecho por la inspiración interna de Dios, sin ningún medio externo;
para la prueba de lo cual ver 1 Pedro 1:10-11. Ahora bien, eso que ha sido,
puede seguir siendo.

[.numbered]
__Cuarta:__ Este argumento tuyo concluye, a lo sumo,
que nosotros no podemos conocer _naturalmente_ ningún hecho,
sino por el relato de otro fuera de nosotros,
o por la percepción de los sentidos externos,
porque _naturalmente_ no hay en nuestras mentes ideas sobre las verdades contingentes
(y todo asunto de hecho es una verdad contingente) como hay de las verdades necesarias.
Esto entonces prueba que no podemos conocer _naturalmente_ ninguna verdad contingente,
sino por el relato de otro o por la percepción de los sentidos externos;
pero esto no impide la verdad de que nosotros podemos conocer
una verdad contingente mediante un conocimiento _sobrenatural,_
en el que Dios ocupa el lugar de un relator externo; quien en realidad es tan verdadero,
que debe ser creído, ya que Dios es la fuente de la verdad.

[.numbered]
__Quinta:__
Cuando Dios da a conocer a los hombres algún hecho por medio de la revelación
o inspiración divina directa--Dios hablando al oído del corazón del hombre interior,
o escribiendo en él por Su dedo--deben ser consideradas
dos cosas en dicha revelación directa.

[.numbered]
1+++.+++ El hecho o la cosa revelada, lo cual es contingente.

[.numbered]
2+++.+++ La forma o modo en que es hecha la revelación; cuya forma es una revelación interna,
divina y sobrenatural,
que es la voz de Dios o discurso de Dios internamente
hablado al oído del hombre interior o mente del hombre,
o un escribir divino sobrenaturalmente impreso en ella.

[.small-break]
'''

Ahora bien, en cuanto a la cosa y hecho revelado,
esto es ciertamente una verdad contingente, y no se manifiesta por sí misma a la mente;
pero debido a la forma, es decir,
debido al modo divino y a la operación interna y sobrenatural,
se sabe que el hecho es verdadero.
Porque esa operación interna,
divina y sobrenatural que la mente siente y percibe en sí misma,
es la voz de Dios hablándole al hombre,
que por Su naturaleza y propiedad específicas es claramente
distinguida y entendida como la voz de Dios,
tal como se sabe que la voz de Pedro o Santiago es la voz de dichos hombres.
Porque todo ser como ser es conocible,
y eso mediante su propia y específica naturaleza o propiedad que procede de su naturaleza;
y dicho ser tiene su propia idea, por el que es distinguible de cualquier otra cosa,
si se suscita su idea en nosotros y se nos propone claramente.

[.numbered]
__Sexta:__ Ahora bien, así como algunos seres son naturales y otros son sobrenaturales,
algunas ideas son naturales y otras sobrenaturales.
Y puesto que, cuando alguna idea natural es suscitada en nosotros,
nosotros la conocemos claramente; así también,
cuando una idea sobrenatural es levantada en nosotros,
nosotros claramente conocemos la cosa de la que es idea.
Pero sabemos que la voz de Dios que le habla a la mente del hombre es un ser sobrenatural,
y suscita en nosotros una idea sobrenatural,
por la que claramente conocemos que esa voz interna
es la voz de Dios y no la voz u operación de otro,
o de algún espíritu maligno, o ángel,
porque ninguno de éstos tiene una idea sobrenatural
como la tiene la divina operación de Dios.
Pues la voz de Dios está llena de vigor, virtud y gloria divina, como dice el salmista,
quien la había experimentado a menudo;
y de la que nosotros también en nuestras medidas somos testigos,
porque la voz de Dios se conoce como Suya por su virtud divina.

[.numbered]
__Séptima:__ Los sentidos son externos o internos,
y los sentidos internos son naturales o sobrenaturales.
Tenemos un ejemplo del sentido natural interno cuando nos enojamos o tranquilizamos,
en el amor y en el odio, o cuando percibimos y discernimos cualquier verdad natural.
Un ejemplo del sentido sobrenatural interno es,
cuando el corazón o el alma de un hombre piadoso siente en sí mismo los movimientos,
influencias y operaciones divinas, que algunas veces son como la voz o discurso de Dios,
otras como una ilustración o realidad muy agradable
y gloriosa que se hace visible al ojo interior,
otras como el más dulce olor o sabor, otras como una calidez celestial y divina,
o por decirlo así, un enternecimiento del alma en el amor de Dios.
Además, esta operación divina y sobrenatural en la mente del hombre,
es un verdadero y muy glorioso milagro;
que cuando es percibida por el sentido interno y sobrenatural
divinamente levantado en la mente del hombre,
persuade tan evidente y claramente al entendimiento a aceptar la cosa revelada,
que no hay necesidad de un milagro externo;
porque esta aceptación no se debe a la cosa misma revelada,
sino a la revelación que la propone, la cual es la poderosa voz de Dios.
Porque cuando la voz de Dios es oída en el alma,
el alma percibe la verdad de esa voz con tanta certeza,
como la verdad del ser de Dios de quien procede.

====

Una vez establecidas estas premisas, ahora procedo a una respuesta directa.
En cuanto a lo que has dicho,
de que Dios no puede hacer que una verdad contingente se convierta en una verdad necesaria,
estoy de acuerdo.
Sin embargo,
cuando se nos manifiesta cualquier verdad contingente por revelación directa de Dios,
hay que considerar dos cosas; a saber,
la cosa revelada (que es contingente) y la revelación misma.
Y en la suposición de que sea efectivamente una revelación divina,
entonces no es una verdad contingente, sino una verdad muy necesaria.
Porque toda la humanidad estará de acuerdo con la suposición de que "`toda
revelación divina es necesariamente verdadera,`" y que es tan clara y
evidente como la proposición de que "`el todo es mayor que sus partes.`"

Pero tú dirás, ¿cómo sabes tú que una revelación divina es una revelación divina?
Yo respondo, ¿cómo sabes tú que un todo es un todo y que una parte es una parte?
Tú dirás, por la idea natural que es encendida en mí de un todo y de una parte.
Yo respondo de nuevo; también se sabe que una revelación divina es tal,
por una idea sobrenatural de revelación divina suscitada
en nosotros por un movimiento divino u operación sobrenatural.
Pero no es de extrañar que los hombres que no tienen experiencia de ideas sobrenaturales,
o al menos no les prestan atención, las nieguen.
Esto es como si un hombre naturalmente ciego negara
la existencia de la luz o de los colores,
o que un sordo negara los sonidos, sólo porque no lo han experimentado.
Por lo tanto, no podemos ocultar que sentimos un celo ferviente, es decir,
divinamente encendido en nosotros,
contra una opinión tan absurda como la que afirma que Dios no puede
darnos a conocer Su voluntad en ninguna verdad contingente,
sino proponiéndola a los sentidos externos.
Esta opinión de cierta manera convierte a los hombres en meros brutos,
pues plantea que el hombre no debería creer en su Dios,
a menos que Él les proponga a los sentidos externos qué debe ser creído;
sentidos que las bestias tienen en común con nosotros.
En efecto, anula el poder de Dios y Le imputa debilidad,
como si no pudiera hacer lo que no sólo los ángeles buenos y malos pueden hacer,
sino también las criaturas más bajas y las más inertes.
Por ejemplo, el calor del fuego, el frío del aire y del agua actúan sobre nosotros; sí,
si un alfiler nos punza, definitivamente lo sentimos, y eso por los sentidos externos,
porque estos objetos son externos y carnales.
Pero, puesto que Dios es un Espíritu mucho más puro y glorioso,
cuando actúa en lo más íntimo de nuestra mentes mediante Su voluntad,
¿acaso no serán Él y Su voluntad claramente sentidos según Su naturaleza, es decir,
por medio de un sentido espiritual y sobrenatural?
Porque así como es la naturaleza de Dios, así es la naturaleza de Su voluntad, es decir,
puramente espiritual, y por lo tanto, requiere un sentido espiritual para discernirla.
Y cuando este sentido espiritual es levantado en nosotros por una operación divina,
conoce muy clara y ciertamente la voz o revelación de la voluntad
de Dios con respecto a cualquier cosa que le plazca a Dios revelar,
por contingente que sea,
tal como los sentidos externos conocen y perciben los objetos externos.

Y no es menos absurdo requerir de Dios, que es el Espíritu más puro,
que les manifieste a los hombres Su voluntad por medio de los sentidos externos,
como absurdo sería requerir que un hombre vea los sonidos y oiga la luz y los colores.
Porque así como los objetos de los sentidos externos no se confunden,
sino que a cada objeto le corresponde su propio sentido;
de igual manera juzgamos los objetos internos y espirituales,
a los cuales también les corresponde su propio sentido por el que son percibidos.
Y dime, ¿cómo manifiesta Dios Su voluntad con respecto a los hechos,
cuando envía a Sus ángeles a los hombres,
puesto que los ángeles (como es comúnmente aceptado) no tienen sentidos externos,
o al menos, no tan físicos como los nuestros?
Sí, cuando los hombres mueren y comparecen ante el tribunal de Dios,
ya sea para vida o para muerte eterna, ¿cómo saben ellos esto,
habiendo dejado sus cuerpos junto con los sentidos externos?
Y sin embargo, esta verdad de Dios es una verdad de hecho,
como lo es la verdad histórica del nacimiento de Cristo en la carne.

O para llevarlo aún más lejos, ¿cómo conocen con certeza los hombres buenos y santos,
incluso en esta vida, que están en el favor y gracia de Dios?
Ninguna revelación externa se los da a conocer.
Pero el Espíritu, como dice el apóstol,
da testimonio a nuestros espíritus de que somos hijos de Dios.
Porque el mero testimonio de la consciencia humana,
sin el testimonio interno del Espíritu Santo,
no puede engendrar en nosotros un testimonio firme
e inconmovible de nuestra condición de hijos,
pues el corazón del hombre es engañoso.
E incluso, si el mero testimonio de la consciencia humana fuera cierto, sigue siendo,
a lo sumo, un testimonio humano que sólo engendra en nosotros fe humana.
Pero la fe por la que los hombres santos creen que son hijos de Dios, es la fe divina,
la que se apoya en el testimonio divino del Espíritu
Santo que atestigua que ellos son hijos de Dios.
Además,
cuando un hombre bueno siente en sí mismo ese indescriptible gozo del Espíritu Santo,
del que hablan las Sagradas Escrituras, y que es privilegio común de los santos,
¿cómo o de dónde siente él este gozo?
En realidad, tu posición no argumenta menos contra este gozo celestial y espiritual,
que es engendrado en las almas de los santos por el Espíritu Santo,
que lo que argumenta contra la revelación directa de Dios.
Porque no hay una idea natural de este gozo espiritual, o de lo contrario,
los hombres meramente naturales, incluso los que son profanos e impíos,
lo sentirían tanto como los piadosos.
Pero debido a que es algo sobrenatural,
no se puede tener una idea formada acerca de ello,
sino por medio de lo que también es sobrenatural.
Además,
¿cómo es que los hombres profanos a veces sienten en ellos la ira de Dios como un fuego,
cuando todas las cosas, en cuanto a lo externo,
les marchan tan prósperamente como a los piadosos, y a menudo más prósperamente?
Pues no hay una idea natural de la ira Dios en el interior de los hombres.
A veces,
también se levanta una aflicción en los hombres perversos
por el sentido de la ira de Dios,
que molesta y atormenta mucho sus mentes; y sin embargo,
esta aflicción no tiene una idea natural en nosotros.
Puesto que con frecuencia, los hombres perversos no sienten esta tristeza, y Dios está,
por decirlo así, en silencio, mientras los malvados continúan en pecado,
como dice el Salmo 1.

Todo lo cual demuestra muy claramente,
que en los hombres hay ideas sobrenaturales de cosas sobrenaturales; las cuales,
sin embargo,
no son percibidas por nosotros a menos que sean suscitadas
por alguna operación sobrenatural de Dios;
la cual levanta en nosotros sentidos sobrenaturales y espirituales,
que por su naturaleza, se distinguen de los sentidos naturales (internos o externos),
como se distinguen entre sí los sentidos naturales por sus diferencias específicas.
La Escritura habla con frecuencia de estos sentidos espirituales, como en Hebreos 5:14,
donde se habla de los sentidos espirituales en general,
por medio de los cuales el hombre espiritual tiene "`discernimiento del bien y del mal.`"
Ahora,
el "`bien`" mencionado aquí es de naturaleza espiritual
y conduce a alimentar en nosotros la vida espiritual y divina;
y el "`mal`" es aquello por lo que la vida espiritual es herida en nosotros; es decir,
los pecados, ya sean carnales o espirituales;
todo lo cual no puede ser discernido sino por aquellos que
tienen los sentidos espirituales despertados en ellos,
tal como dice el apóstol.
Las Escrituras hablan en otros lugares de estos sentidos espirituales en particular:
Como el ver y gustar, Salmos 34:8; el oír espiritual, Salmos 85:8; el oler espiritual,
Cantar de los Cantares 1:3; el toque espiritual, 1 Samuel 10:26;
y en muchos otros lugares de las Escrituras leemos
de estos sentidos espirituales en particular.
Sí, es la promesa del evangelio,
que la gloria de Dios será "`vista`" por los hombres santos,
los que son limpios de corazón, incluso en esta vida: Isaías 33:17; Mateo 5:8;
promesas que fueron cumplidas en los Cristianos primitivos, ver Juan 1:14; 1 Juan 1:2-4;
2 Corintios 3:18; y 4:6. Pero,
¿qué es esta visión de Dios y de la gloria divina
de la que gozan las almas de los santos en esta vida?
¿No son las arras o las primicias de esa visión gloriosa
y más abundante de la vida por venir,
de la que las Escrituras tanto declaran, que es la mayor felicidad del alma inmortal?

Por tanto, si existen tales cosas como ideas sobrenaturales,
entonces también existen sentidos o facultades perceptivas
por las que esas ideas son percibidas;
porque ambas están
relacionadas entre sí y se suponen e infieren mutuamente.
Pero en los hombres perversos estos sentidos o facultades están dormidos,
por decirlo así, de la misma manera que la facultad de ver en un ciego;
pero en los hombres piadosos están despiertos.
Ahora, mediante estos sentidos divinos y espirituales,
que son distintos y distinguibles de todas las facultades naturales del alma (ya sea,
la imaginación o la razón natural),
los hombres de mente espiritual contemplan la gloria y belleza de Dios,
con respecto a las cuales y comparadas con ellas,
toda la gloria de este mundo es despreciable para ellos; sí, como escoria y estiércol.
Y también oyen a Dios hablar internamente en sus almas,
palabras verdaderamente divinas y celestiales, llenas de virtud y vida divina;
y huelen y gustan las cosas divinas, y las manejan, por decirlo así,
con las manos de sus almas.
Y estos goces celestiales difieren tanto en su naturaleza de las
falsas semejanzas y apariencias ficticias de ellos (que,
o bien la mente del hombre por medio de su propia fuerza puede imitar,
o cualquier espíritu maligno para engañar al hombre puede falsificar),
como un hombre real difiere de la imagen muerta de un hombre; o como el pan, miel,
vino o leche reales difieren de la mera imagen de estas cosas.
Y aunque la imaginación del hombre o la sutileza del maligno,
pueda hacer falsificaciones de estos goces por medio de las cuales
los hombres pueden ser engañados (y sin duda muchos son engañados),
aun así,
esto no impide el hecho de que estos goces divinos sean claramente percibidos
por aquellos en quienes los sentidos divinos y espirituales están realmente abiertos,
y las verdaderas ideas sobrenaturales de estas cosas están verdaderamente levantadas.

Y si en algún momento hay un error,
entonces la iluminación divina no es la causa de ese error,
sino alguna mala disposición de la mente;
como también sucede en las cosas relacionadas con la razón natural.
Porque una razón falsa puede tener muchas apariencias,
que difieren tanto de la verdadera razón,
como las falsas y pretendidas revelaciones e inspiraciones
diabólicas difieren de las que son verdaderamente divinas.
Ahora bien, aunque hay muchos hombres a quienes les gustarían ser considerados filósofos,
pero que son miserablemente engañados por esas falsas semejanzas de la razón,
al juzgar que sus falsas razones son las verdaderas
imágenes de las cosas y de la lógica sólida;
esto, sin embargo, no mueve a cualquier hombre de sana razón,
a rechazar la sana y sólida razón como dudosa e incierta.
Porque incluso la sana razón natural es un excelente
don de Dios y muy útil para la humanidad,
cuando es usada en su lugar apropiado.
Pero que nadie crea comprender mediante su razón natural
las cosas que son del género divino y sobrenatural.

Pero prosigamos: Si escuchamos las Escrituras (como todo Cristiano debería hacerlo),
ellas nos testifican que Dios ha declarado Su mente y Su voluntad en los profetas,
incluso con respecto a las verdades contingentes por venir;
como evidentemente lo declara el primer capítulo a los Hebreos: "`Dios,
habiendo hablado muchas veces y en muchas maneras
en otro tiempo a los padres por los profetas.`"
Sí, oigamos a los propios profetas.
Oseas capítulo 1 dice claramente,
que "`la palabra del Señor fue hecha en él,`" como aparece en el hebreo.
Habacuc dice que él estaba '`en su guarda, para ver lo que Jehová hablaría en él.`'^
footnote:[Habacuc 2:1, traducción literal.]
Y es tan claramente manifiesto que las revelaciones más celestiales son
por ilustraciones e inspiraciones _internas_ en la mente misma de los profetas,
que es extraño cómo alguien que cree en las Escrituras dude de ello.
Y también es cierto, que aun cuando predijeron verdades contingente por venir,
estaban verdaderamente persuadidos de que eran divinamente inspirados; es decir,
sin la corroboración de ningún milagro externo.
Pues Juan el Bautista no hizo milagros;
y muchos otros profetizaron donde no ocurrió ningún milagro,
como a menudo se observa en las Escrituras.
Y nosotros también,
por la inspiración del mismo Espíritu divino mediante el cual profetizaron los profetas,
creemos que sus palabras y escritos son divinos,
tanto con respecto a las verdades contingentes pasadas como a las que están por venir.
En efecto,
nosotros no necesitamos milagros externos que nos muevan a creer en las Escrituras;
y por tanto,
mucho menos necesarios fueron los milagros para los profetas que las escribieron.
Porque vemos en muchos lugares de los profetas,
donde declaran profecías que les fueron reveladas por Dios,
que no se menciona una palabra de ningún milagro externo,
por medio del cual estuvieran seguros de ellas.

Además,
la falsedad de tu argumento aparece por el hecho de que las Escrituras declaran que
muchas verdades contingentes les fueron reveladas a los profetas en sueños. Ahora bien,
así como los hombres naturales y perversos no ven lo que
sueñan mediante una percepción real de los sentidos externos,
sino por ideas internas que se presentan en la mente y son percibidas por esta,
así también sucede en las revelaciones divinas de esta naturaleza.
De esto tenemos un claro ejemplo en José, el esposo de la bendita virgen, quien,
cuando observó que su esposa estaba encinta,
se le dijo en un sueño que ella había concebido por el Espíritu Santo.
Ahora, me gustaría que me dijeras, ¿a cuál sentido externo de José se le reveló esto?
O, ¿qué milagro lo indujo a creer eso que, al estar contra el orden de la naturaleza,
ciertamente chocó contra su razón? Las Escrituras
no mencionan ningún milagro en este asunto;
y sin embargo,
no cabe duda de que José habría pecado si no hubiera creído
esta revelación y rechazado a su esposa como adúltera.

Ahora, en cuanto a estas palabras del apóstol en Romanos 10,
"`la fe viene por el oír,`" Zwingli observó bien al decir que el apóstol no tenía
la intención de afirmar que la fe viene por el oír la palabra externa;
tampoco las siguientes palabras lo prueban:
"`¿Y cómo creerán en aquel de quien no han oído? ¿Y cómo oirán sin haber quien les predique?
¿Y cómo predicarán si no fueren enviados?`"
Pues el apóstol usa estas preguntas, no como su argumento,
sino como objeciones que podría ser formuladas, tal como hace en otros lugares;
objeciones que él también responde en el mismo capítulo,
como aparece en el versículo 18. "`Mas digo: ¿No han oído? Antes bien,
por toda la tierra ha salido la voz de ellos;`" es decir, la voz del Padre y del Hijo,
o del Padre en la Palabra; Palabra que no sólo está cerca de nosotros, sino que,
según el mismo apóstol en el mismo capítulo,
está '`en nuestras bocas y en nuestros corazones.`' Pero además,
insistir en que la fe sólo se engendra por el oír externo, y no de otra manera,
sería sugerir que nada puede ser ciertamente creído,
sino donde algo es propuesto al oído externo, lo cual, de hecho,
destruye toda tu hipótesis.
Porque has afirmado antes,
que los milagros externos son suficientes para brindarnos
la certeza de la verdad de cualquier revelación;
ya sea la curación de los enfermos, o la resurrección de los muertos, etc.
Pero ahora estos milagros no servirían de nada,
porque ellos (y casi todos los milagros) son obvios a la vista y no al oído.

Por último: Si toda la certeza de nuestra fe,
esperanza y salvación dependiera de la infalibilidad de los sentidos externos,
entonces seríamos muy miserables,
dado que es bien sabido que estos sentidos pueden ser fácilmente engañados,
así como debilitados o perjudicados por muchas causas externas y enfermedades naturales.
Y también hay (como afirman las Escrituras) falsos milagros, que en cuanto a lo externo,
no pueden distinguirse de los verdaderos;
los cuales no podemos juzgar infaliblemente por los sentidos externos,
que sólo disciernen lo que es externo.
Es necesario, por tanto, recurrir a algún otro medio de certeza.

De todo lo cual se desprende, cuán falaz y débil es este argumento.
Pero gracias sean dadas a Dios,
quien no ha querido que nuestra fe se edifique sobre un fundamento tan incierto y dudoso.
Y cualquiera que haya experimentado la verdadera fe,
o haya sentido el testimonio divino del Espíritu de Dios en su alma,
juzgará de otro modo, y no será movido por tales razonamientos.
Por tanto, oro a Dios que quite esas nubes que oscurecen tu entendimiento,
para que puedas percibir el glorioso evangelio de Cristo,
que es esa Palabra salvadora de gracia a la que te encomiendo.
Y que Dios te dé un corazón inclinado a creer y a obedecer la verdad;
es el deseo de tu fiel amigo,

[.signed-section-signature]
Robert Barclay

[.postscript]
====

Desde la prisión de Aberdeen, en Escocia,
donde estoy confinado por causa del testimonio de Jesús. 24 de Noviembre de 1676.

====

--
