== Capítulo XX

[.section-date]
1677--1684

[.chapter-synopsis]
* Amigos viajando por Holanda y Alemania
* Princesa Elizabeth del Palatinado
* Correspondencia entre la princesa Elizabeth y W. Penn y R. Barclay
* Anna Mary Schurman y los Labadistas--
* Carta de W. Penn al Consejo y al Senado de Embden
* Trato rudo del conde de Bruch
* Disputa de G. Fox y W. Penn con Galenus Abraham
* Más correspondencia entre la princesa Elizabeth y W. Penn
* Continuación de la persecución bajo la Ley de Conventículos
* Epístola de consuelo de G. Fox
* Apología de Barclay y los embajadores en Nimeguen
* Muerte de Isaac Penington
* Preguntas al Papa
* G. Whitehead arrestado como Jesuita
* Juicio en Ware
* Recuento de los sufrimientos de los Amigos presentado al Parlamento
* Concesión de Pennsylvania
* Almirante Penn
* Persecución en Bristol
* Reuniones mantenidas por los niños
* Casos de excesiva crueldad
* Setecientos Cuáqueros en prisión
* Carta de consolación de W. Dewsbury
* Wilkinson y Story
* Separación
* Discurso al rey
* Gabriel Shad el informante
* Muerte del rey Carlos.

Apenas había comenzado el año 1677, cuando G. Fox empezó a viajar de nuevo,
aunque los caminos todavía estaban cubiertos por la nieve.
Después de haber pasado por varios lugares y predicado en las reuniones de sus amigos,
llegó a York, y yendo de ahí a Nottingham, fue a la casa de John Reckless,
quien era el alguacil allí la primera vez que G. Fox predicó en el pueblo,
y que fue encarcelado por ese motivo.
Pero este alguacil, al recibir a G. Fox en su casa en ese momento,
fue tan alcanzado por lo que G. Fox habló,
que abrazó la doctrina expuesta y nunca se apartó de la profesión de ella.
De ahí Fox pasó por Leicestershire, Derbyshire, Warwickshire,
Buckinghamshire y Bedfordshire, donde se encontró con William Dewsbury,
y así llegó de nuevo a Londres.
Después de asistir a la reunión anual allí, él, junto con William Penn, Robert Barclay,
George Keith y algunos otros,
fue a Holanda para ver a sus amigos y para edificarlos con su don.
William Penn y Robert Barclay viajaron a Alemania,
y como R. Barclay el año anterior había hablado con
la princesa Elizabeth del Palatinado (hija de Frederick,
rey de Bohemia y hermana de Sofía, fallecida duquesa de Hanover, madre de George,
rey de Gran Bretaña), William Penn le escribió también dos cartas desde Inglaterra,
que ella respondió de la siguiente manera:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Hereford, 2 de Mayo de 1667

Esta carta, amigo, te informará que tus dos cartas fueron muy aceptadas,
junto con tus deseos de que yo obtenga esas virtudes que pueden
hacerme una digna seguidora de nuestro gran Rey y Salvador Jesucristo.
Lo que he hecho por Sus verdaderos discípulos no es ni siquiera un vaso de agua fría,
pues no les proporciona ningún refrescamiento.
Tampoco espero ningún fruto de mi carta a la duquesa de L.,
como se lo expresé al mismo tiempo a B. F.,
pero como Robert Barclay quería que yo le escribiera, no pude negarme,
ni omitir nada que se considerara conducente a la libertad de él,
aunque eso me expusiera a la burla del mundo.
Pero esto lo puede alcanzar un hombre meramente moral;
todavía faltan las verdaderas gracias internas,

[.signed-section-closing]
Tu afectuosa amiga,

[.signed-section-signature]
Elizabeth

--

G+++.+++ Fox también le escribió
una carta a esta virtuosa princesa desde Ámsterdam,
en la que elogiaba su vida modesta y retirada,
y la exhortaba a la piedad y a la santidad; a lo que ella respondió con esta carta:

[.embedded-content-document.letter]
--

[.salutation]
Querido Amigo,

No puedo dejar de tener un tierno amor por aquellos que aman al Señor Jesucristo,
y a quienes les es dado no sólo creer en Él, sino también sufrir por Él. Por tanto,
tu carta y la visita de tus amigos,
han sido muy bienvenidas para mí. Seguiré los consejos de ellos y los tuyos,
hasta donde Dios me conceda luz y unción; y seguiré siendo,

[.signed-section-closing]
Tu cariñosa amiga,

[.signed-section-signature]
Elizabeth

[.signed-section-context-close]
Hereford, 30 de Agosto de 1677

--

Esta correspondencia les dio oportunidad a William Penn y a Robert Barclay de ir a Herford,
un pueblo en las fronteras de Paderborn, y hacerle a la mencionada princesa una visita,
pues ella residía ahí. Con ella vivía Anna Mary, condesa de Homes;
y William Penn y Robert Barclay tuvieron una reunión con la princesa,
la condesa y algunos otros, en una de las estancias de la princesa,
para gran satisfacción de ellos.
La condesa, que era una de las partidarias de Labadie,
le indicó a William Penn que quería que se celebrara una reunión
en la que los criados inferiores pudieran asistir libremente.
William Penn no lo rechazó y la princesa lo consintió;
y después de la reunión (en la que ella no estuvo presente
para que sus criados pudieran tener acceso libre),
expresó mucha satisfacción por haber tenido esa buena oportunidad,
y luego invitó tan sinceramente a William Penn y a Robert
Barclay (que se hospedaban en una posada) a cenar con ella,
que no pudiendo rechazar la invitación, cedieron a ella.

Estaba con ella una mujer francesa de importancia,
quien habiendo tenido una opinión muy desfavorable de los Cuáqueros,
en ese momento estaba profundamente quebrantada,
y se había vuelto muy amable y respetuosa con William Penn y Robert Barclay.
El día siguiente era el Primer-día,
y habiendo acordado con la princesa tener otra reunión,
William Penn quiso que no sólo se les permitiera
estar ahí a todos los de su propia familia,
sino a todos los del pueblo que estuvieran dispuestos a asistir.
Ella cedió,
y así William Penn y Robert Barclay tuvieron una
gran oportunidad de predicar eficazmente y de descargarse.
Después de que terminó la reunión, la princesa se acercó a William Penn,
y tomándolo de la mano le habló del sentido que había tenido del
poder y de la presencia de Dios que había estado entre ellos.
Y al continuar así, estalló en una gran emoción exclamando: "`¡No puedo hablarte,
mi corazón está lleno!,`" dando palmadas sobre su pecho.
Esto afectó no poco a William Penn, sin embargo,
le dirigió una pocas palabras a manera de consejo y luego,
al despedirse de la princesa ella le dijo: "`¿No vendrán aquí otra vez?
Por favor, deténganse aquí cuando regresen de Alemania.`"
A esto él respondió: "`Nosotros estamos en la mano del Señor,
y al estar entregados a Su voluntad,
no podemos dirigir tan plenamente nuestro propio curso.`"
Después de una solemne despedida,
Robert Barclay regresó a Ámsterdam y William Penn fue a Paderborn,
y así por el camino de Cassel (donde habló con el
anciano y erudito Dureus) llegó a Frankfort.
Ahí encontró a varias personas de renombre, con quienes tuvo varias reuniones;
una en la casa de una joven dama de noble cuna llamada, Johannah Eleonora Merlane,
quien le dijo: "`Nuestros aposentos están disponibles para ustedes.
Qué vengan todos los que quieran; y alcen sus voces sin temor.`"

Partiendo de ahí, William Penn llegó a Chrisheim, una aldea cerca de Worms,
donde entonces vivían algunos de sus amigos que después fueron a Pensilvania
y se establecieron allí. Mientras William Penn estaba en el Palatinado,
les escribió una epístola de exhortación^
footnote:[Ver Penn`'s Travels in Holland, etc.
// lint-disable invalid-characters `º`
3º impresión, p. 77. t Ibid. p. 84.]
a Elizabeth, princesa de Palatinado, y a Anna Mary, condesa de Homes.
Luego se fue a Heidelberg, la principal ciudad de Palatinado,
para hablar con el príncipe elector, Charles Ludowick,
hermano de la citada princesa Elizabeth,
pero dicho príncipe estaba entonces fuera de la ciudad.
Dado que el principal mensaje de W. Penn era solicitarle al príncipe
que los Cuáqueros en Chrisheim fueran tratados con más suavidad,
aprovechó para escribirle una carta desde allí,
porque no sólo el párroco del pueblo les exigía diezmos a sus amigos,
sino también los sacerdotes papista de Worms;
y el alcalde de la ciudad se esforzaba por restringirles
su debida libertad de reunirse religiosamente.
Regresando después a Chrisheim, predicó en la reunión de sus amigos,
mientras era escuchado por el alcalde,
que estaba en la puerta trasera para que no lo vieran.
Pero este hombre quedó tan complacido por lo que oyó, que después le dijo al párroco,
que aunque era su deber descubrir si los Cuáqueros eran herejes, "`por mi parte,`" dijo,
"`no escuché nada más que cosas buenas, y por lo tanto, no me meteré con ellos.`"
Porque el párroco se había ocupado de persuadir al
alcalde de que era deber suyo suprimir la herejía;
pero aquí,
el alcalde le hizo saber que no tenía pensado perseguir a nadie
por asuntos de religión. Tras descargar su consciencia,
W+++.+++ Penn regresó por Frankfort, Colonia, Cleves, etc. a Ámsterdam;
en Colonia recibió una carta de la princesa Elizabeth,
en respuesta a la que él le había escrito desde el Palatinado.
Dicha carta es como sigue:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Septiembre de 1677

[.salutation]
Querido amigo,

He recibido tus saludos, buenos deseos y exhortaciones con mucho gozo,
y seguiré estas últimas hasta donde le plazca a nuestro gran Dios darme luz y fuerza.
Puedo decir poco por mí misma y nada puedo hacer por mí misma;
pero espero que el Señor me conduzca en Su tiempo por Su camino, a Su fin,
y que yo no me acobarde delante de Su fuego.
Lo anhelo; y cuando Él asegure mis caminos,
espero que me dé poder para llevar la cruz que me encuentre en ellos.
También me alegra saber que el viaje ha sido prosperado,
tanto en lo que se refiere a la salud de tu cuerpo,
para resistir las inclemencias del tiempo, como en la aceptación que tuviste en Cassel,
Frankfort y Chrisheim.
Nada me sorprendió, sino el viejo y buen John Dury,
en quien no esperaba tanta ingenuidad,
habiendo escrito últimamente un libro titulado [.book-title]#Le veritable Chretien#^
footnote:[__El verdadero Cristiano__.], que sí habla de otra manera.
Me gustaría saber qué acogida tuviste en Fredericksburg,
y si recibes esta carta en Cleves,
me gustaría que aprovecharas la oportunidad para ver a los dos pastores de Mulheim,
quienes realmente buscan al Señor, pero tienen algunos prejuicios contra tu doctrina,
como también la condesa de allí. Sería muy útil para
mi familia que se libraran de sus conceptos erróneos;
pero que sea hecha la voluntad de Dios en eso y en todo lo que concierne,

[.signed-section-closing]
A tu querida amiga en el Señor Jesús,

[.signed-section-signature]
Elizabeth

--

Mientras William Penn hacía este viaje en Alemania,
George Fox había ido a Hamburgo y a Frederickstadt a visitar a sus amigos allí. Penn,
tras regresar a Ámsterdam, se fue a Friesland,
y se encontró a George Fox en Leewarden cuando regresaba a Holanda;
de ahí pasó a Wiewart, donde vivía una sociedad de los Labadistas.
Allí habló con la famosa Anna Maria Schurman, con la dama de Somerdykes,
el pastor francés Peter Yvon y otros.
Después de algo de conversación de ambas partes,
cuando Yvon había hecho un relato acerca de John Labadie,
de cómo había sido criado entre los Jesuitas y había desertado de ellos,
y había abrazado la religión Protestante;
y de cómo al estar insatisfecho con los Protestantes formales,
él junto con algunos que se le unieron, se habían separado de las asambleas comunes,
Anna Maria Schurman empezó a hablar e hizo un recuento de su vida anterior,
de su gusto por aprender, y de su amor a la religión en la que se había criado,
pero confesó que en todo ese tiempo no había conocido verdaderamente a Dios ni a Cristo.
Y que aunque Dios la había visitado de vez en cuando desde niña,
aun así nunca había sentido un impacto tan poderoso como
el que había sentido por el ministerio de John Labadie.
Que sólo entonces había visto que su aprendizaje era vanidad
y que su religión era como un cuerpo de muerte;
y que por lo tanto, había resuelto despreciar la vergüenza,
abandonar su anterior forma de vida y conocidos,
y unirse a esa pequeña familia que estaba retirada del mundo.
Esto y mucho más dijo en un tono sensible y con actitud seria, y con algunos temblores.
Y entonces, una de las damas de Somerdykes,
también hizo un amplio relato sobre su estado interior,
y de cómo había sido alcanzada por la predicación de Labadie.
De cómo antes de ese tiempo se había lamentado por la muerte
y formalidad de la vida de los Cristianos comunes,
y había dicho dentro de sí misma: "`¡Oh, el orgullo, la lujuria,
los vanos placeres en los que viven los Cristianos! ¿Puede ser éste el camino al cielo?
¿Es éste el camino a la gloria?
¿Son estos seguidores de Cristo?
¡Oh, no!
Dios, ¿dónde está Tu pequeño rebaño? ¿Dónde está tu pequeña
familia que vive enteramente para Ti y te sigue?
¡Hazme una de ese número!`"
Luego contó cómo, estando compungida en el corazón por escuchar a Labadie predicar,
había resuelto abandonar la gloria y el orgullo de este mundo; y agregó,
que se consideraba feliz por haberse unido a esa familia separada.

Después de que algunos otros también dieron cuenta de su cambio,
William Penn relató cómo se había ido alejando gradualmente
de la vanidad y del orgullo de la vida;
mencionando las adversidades que había encontrado en la universidad de Oxford,
por no haberse unido al libertinaje que se cometía allí. Y cómo,
después de haber vivido un tiempo en Francia,
había sido convencido por el efectivo ministerio de Thomas Loe,
y se había unido a los despreciados Cuáqueros.
Concluyó este relato con una seria advertencia sobre cómo
debían continuar y crecer en el verdadero temor de Dios.
Al despedirse, uno de los pastores le preguntó,
si la verdad no había surgido primero entre un pueblo pobre, iletrado y simple.
"`Sí,`" respondió William Penn,
"`y es nuestro consuelo que no se lo debamos a la erudición de este mundo.`"
A lo que el pastor replicó:
"`Entonces no dejemos que la erudición de este mundo sea usada
para defender lo que el Espíritu de Dios ha hecho surgir;
porque los letrados que ahora se unen a ustedes,
serán propensos a mezclar la erudición escolar con
el lenguaje más simple y puro de ustedes,
y por medio de ello oscurecer el brillo de sus testimonios.`"
Después de que W. Penn respondió algo al respecto,
se despidió y viajó por el camino de Groninghen a Embden,
donde los Cuáqueros en ese entonces eran severamente
perseguidos con encarcelamientos y destierros.
Pero me abstendré de relatarlo, porque hace mucho tiempo fue publicado en la prensa,
y los magistrados de ahí,
movidos después a la piedad por la persecución que sufrían los Protestantes en Francia,
llegaron a una mejor resolución, como se menciona en lo que sigue.

Cuando W. Penn llegó a Embden, fue a hablar con el burgomaestre^
footnote:[El _burgomaestre_ es un cargo equivalente al de alcalde o magistrado principal,
de las grandes ciudades en Holanda, Flandes y Alemania.]
Andre a su casa, y le preguntó si hacía unos dos años,
él y el senado no habían recibido una carta en latín de un inglés
con respecto a su severidad hacia el pueblo llamado Cuáqueros.
El burgomaestre respondió que sí. Entonces W. Penn replicó: "`Yo soy ese hombre,
y me siento constreñido en mi consciencia a visitarte en nombre de ellos.`"
El burgomaestre se comportó con más amabilidad de la esperada,
y dio algunas débiles esperanzas de cambio;
pero era suficientemente evidente que el senado no estaba aún tan dispuesto,
pues la persecución continuó durante largo tiempo.

[.offset]
Una copia de la carta de W. Penn traducida al inglés,
dice lo siguiente y merece la seria consideración de todos los magistrados.

[.embedded-content-document.epistle]
--

[.letter-heading]
Al Consejo y Senado de la ciudad de Embden.

[.offset]
Que el Rey de reyes y Señor de señores, quien es Dios de todas las familias de la tierra,
incline sus corazones a la justicia, misericordia y verdad.

El sonido del severo trato hacia varias personas que son habitantes de este estado,
recriminatoriamente llamadas Cuáqueras,
ha llegado a estas partes y llenado a muchos de compasión y sorpresa: Compasión,
al oír hablar de las miserias de los hombres inocentes y rectos contra quienes ustedes
no tienen nada que objetar salvo el ejercicio puro de sus consciencias ante Dios.
Sorpresa, de que ustedes, un estado Protestante, empleen su poder civil para disuadir,
castigar y afligir gravemente a los hombres,
por seguir las convicciones de sus consciencias y
actuar conforme a lo mejor de sus entendimientos.

Los Protestantes obtuvieron su nombre al protestar contra la imposición,
¿y ahora se convertirán ustedes en impositores?
Ellos la condenaron,
¿y ustedes la practicarán? Ellos creían que era una marca propia de la bestia,
¿y ustedes ahora la consideran el deber de una magistratura Cristiana;
que las personas no deben vivir bajo su gobierno,
a menos que reciban la marca de ustedes sobre la frente o en la mano derecha?
Lo cual, en términos claros, es que sometan sus consciencias a los edictos de ustedes,
y que les pidan permiso sobre qué religión seguir.
Recuerden que la fe es don de Dios;
y que '`lo que no es de fe es pecado.`' Nada puede ser más irrazonable
que obligar a los hombres a creer en contra de sus creencias,
o afligirlos por practicar lo que creen cuando esto no se opone a la ley moral de Dios.

No hay duda de que ustedes se consideran Cristianos,
y estimarían un gran insulto si los consideraran de otra manera; sin embargo,
¿hay algo más anticristiano que el uso de la fuerza externa para influir en las
consciencias de los hombres sobre el ejercicio de la adoración religiosa?
Jesucristo, el Señor y autor de la religión Cristiana,
censuró a Sus propios discípulos que querían mandar a descender fuego del cielo,
para destruir a los que no se conformaban con lo que su bendito Maestro enseñaba.
¿Están ustedes más seguros de su religión? ¿Son mejores Cristianos?
O,
¿tienen más autoridad Cristiana que aquellos que fueron
escogidos para ser testigos de Jesús? No obstante,
recuerden que ellos pidieron fuego del cielo,
pero ustedes buscan encender fuego en la tierra para devorarlos--para
devorar a los que son de su propio pueblo,
y sólo porque discrepan de ustedes en cuanto a la religión.

Estoy bien persuadido,
de que aquellos a quienes ustedes les impusieron tan severos castigos,
tienen buenas intenciones en lo que creen, y que la razón de su actual alejamiento,
no es introducir opiniones peligrosas o extrañas, sino vivir una vida de más santidad,
pureza y negación al yo que antes.
Ellos no creen que ustedes caminen de acuerdo con sus propios principios,
y tienen razones para creer que el poder de la piedad está muy perdido entre ustedes.
Y tras permanecer por mucho tiempo bajo un sentido de decadencia
y languidez de alma por falta del verdadero alimento espiritual,
ahora han recurrido a ese don celestial y gracia de Dios en sí mismos,
en busca de la satisfacción divina, es decir,
han recurrido a esa santa unción que es capaz de enseñarles todas
las cosas que necesitan saber (como habla el bendito apóstol);
y en efecto, ellos encuentran los goces del Espíritu Santo al hacerlo.
Estoy persuadido de que ellos no son menos pacíficos, sobrios,
justos y amistosos que antes,
y que permanecen totalmente consistentes con la prosperidad de la sociedad civil.

Si ustedes pudieran dar fe, sería más excusable que castigaran a los que se resisten,
pero como es imposible, entonces lo otro no es razonable;
porque es afligir a los hombres por no ser lo que
no pueden ser a menos que se vuelvan hipócritas.
Este es el punto más alto al que puede llegar el poder coercitivo de ustedes;
pues de seguro, nunca ha podido convertir o preservar un alma para Dios.
En lugar de eso, le ofrece violencia a la consciencia,
y lleva al hombre a negar su fe y razón,
o a ser destruido por actuar de acuerdo con ellas.
¿Y qué consiguen sus prisiones, multas y destierros en la mente de un hombre?
De seguro no aconsejan el juicio de ningún hombre, no resuelven dudas,
ni convencen ningún entendimiento.
El poder de la persuasión no se halla en ninguna de esas acciones bárbaras,
porque ese curso de acción sólo destruye los cuerpos y patrimonios de los hombres,
en lugar de salvar sus almas.
Si están en el error, sería mejor que usaran las armas de Dios, la espada de Su Espíritu,
que salva a la criatura y mata el mal en ellas.

Les ruego por amor al Señor Jesucristo,
que tengan cuidado de cómo ejercen el poder sobre las consciencias de los hombres.
Amigos míos, la consciencia es el trono de Dios en el hombre,
y el poder de ésta es Su prerrogativa.
Poner señores sobre ella, es usurpar Su autoridad y ascender audazmente a Su trono.
Si la conducta de ellos fuera escandalosa y destructiva para el bien del estado,
entonces ustedes estarían justificados, pero en verdad,
ningún hombre de misericordia y consciencia puede defender
la práctica de ustedes sobre hombres tan pacíficos e inofensivos.
Gamaliel se levantará en juicio contra ustedes si persisten en este camino.
Les ruego con mucho amor,
como corresponde a hombres Cristianos y verdaderos Protestantes,
que dejen a los hombres en sus persuasiones particulares
relativas a los asuntos del otro mundo,
en tanto dichas persuasiones no tenga efectos dañinos sobre los asuntos de éste.
Sin embargo, el vicio tiene consecuencias nefastas en lo que se refiere a ambos mundos;
por lo tanto, castiguen el vicio y aspiren a la verdad y a la justicia.
No usen su poder civil para atormentar a los disidentes religiosos,
sino para perseguir una buena vida,
que lamentablemente se ha perdido en medio de tantas
grandes pretensiones de ser un pueblo religioso.
No hay duda,
de que la magistratura fue ordenada por Dios y elegida
por los hombres para ser terror de los malhechores,
y no para los que hacen el bien, aunque sean de diferentes opiniones.

Recuerden que ellos son hombres como ustedes,
que nacieron libres y que tienen el mismo derecho de ustedes a los privilegios comunes,
naturales y civiles.
La diferente persuasión de sus consciencias acerca de cosas relativas a otra vida,
en ningún modo puede hacerlos inadecuados para esta vida.
Tienen el mismo derecho a la libertad y propiedad de siempre,
al no haber perdido por lo que practican ninguna de esas ventajas
humanas que la naturaleza y las Escrituras les han conferido.
Si están equivocados, no son conscientes de ello.
¿Perseguirán a los hombres por ser lo que deben ser, si son fieles a sí mismos?
Les ruego que busquen una manera menos costosa de
contentarse que no resulte en la destrucción de ellos,
pues ellos están muy lejos de buscar la de ustedes.
Oh, llegará el día en el que un acto de ternura en cuestiones
de consciencia encontrará mejor recompensa,
que toda la severidad que usan los hombres para propagar
sus propias persuasiones en el mundo.
Y en efecto, hay una muy buena razón para esto, pues una fluye del Señor,
la otra del destructor de los hombres.
En fin, que la moderación de ustedes sea conocida por todos los hombres,
porque el Señor está cerca y su recompensa está con Él; y Él recompensará a cada hombre,
familia, estado, reino e imperio,
según la naturaleza de las obras cometidas en Su cuerpo mortal.

Imiten al Dios de naturaleza y gracia, siendo bondadosos con todos.
Su sol brilla sobre todos; Su lluvia cae sobre todos; Él le da vida y existencia a todos;
Su gracia visita a todos, y pasa por alto los tiempos de ignorancia.^
footnote:[Hechos 17:30 RV1602P]
Y aunque ustedes nos tengan por ignorantes, espero que no piensen que la pasan por alto,
viendo que hacen tan grandes manifestaciones de su desagrado.
Oh, ¿cuán indulgente y misericordioso es Dios hacia ustedes?
¿Han escapado recientemente de la ira de sus enemigos
y ya pueden tratar duramente a sus amigos?
Que la bondad de Él hacia ustedes prevalezca,
para que expresen clemencia hacia los demás,
para que el gran Dios de toda la tierra--es decir,
el Dios de los espíritus de toda carne que no hace acepción de rico, pobre,
o poderoso en el juicio--les muestre misericordia en el día de Sus justos juicios.
Amén.

[.signed-section-closing]
Su amigo en la Semilla universal de amor y verdad,

[.signed-section-signature]
W+++.+++ PENN

[.signed-section-context-close]
Londres, 14 de Diciembre de 1674

--

Después de pasar un tiempo en Embden, W. Penn se dirigió a Herford otra vez,
donde fue recibido muy amablemente por la princesa Elizabeth y la condesa de Homes.
Se reunió más de una vez en la estancia de ella,
donde la princesa fue tan alcanzada y afectada por su predicación que dijo:
"`Estoy completamente convencida; pero ¡oh!, mis pecados son grandes!`"
Esto le dio oportunidad a W. Penn de hablarles a la princesa y a la condesa por separado,
con respecto a sus condiciones particulares,
lo cual causó una impresión profunda en sus mentes, especialmente en la de la condesa.
Al ser muy presionado por la princesa para que se quedara a cenar con ella, él accedió;
y la condesa, desde un sentido serio de su conformación al mundo, le dijo:
__"`Il faut que je rompe, il faut que je rompe,`"__
es decir: "`Tengo que romper; tengo que romper.`"
Y en otro momento con un semblante grave, exclamó: "`Oh,
los estorbos y enredos de este mundo vano impiden todo bien.`"
Una vez la princesa les dijo: "`Es difícil ser fiel a lo que uno sabe.
Temo no tener suficiente peso en mi espíritu.`"
Y en otro momento ella le dijo:
"`Entre mis libros tengo registros de que el evangelio
fue traído por primera vez de Inglaterra a Alemania;
y ahora ha vuelto.`"
De este modo,
esta excelente princesa expresó lo mucho que valoraba
la predicación del evangelio de W. Penn a ella,
y cuánto estimaba su labor y ministerio.
Cuando él se despidió de estas notables personas, tomando a la princesa de la mano,
lo que ella recibió con gran amabilidad al estar muy quebrantada de espíritu,
él le deseó que la bendición y la paz de Jesús estuvieran con ella y sobre ella;
y luego al exhortar a la condesa,
ella le rogó que la recordara e implorara al Señor en su beneficio.

A continuación tomó un carruaje a Wesel, de ahí viajó a Duisburgh, Dusseldorp y Colonia,
y luego regresó a Dusseldorp,
para ver si en Mulheim se le abría la oportunidad de hablar con la condesa de Falkenstein,
de quien se decía que era una persona muy religiosa.
En su viaje anterior había tratado de visitarla, pero fue en vano,
porque el conde de Bruch y Falkenstein, padre de ella,
la tenía en una especie de confinamiento, porque era de un temperamento religioso,
y por eso la llamaba Cuáquera, aunque ella nunca había conversado con un Cuáquero.
También había tratado con mucha rudeza a W. Penn, cuando en un momento dado,
que necesitaba pasar por su castillo,
les preguntó a él y a sus amigos de dónde venían y hacia dónde iban,
pues era el señor de ese condado.
Ellos respondieron que eran ingleses llegados de Holanda,
y que no iban más allá de su ciudad Mulheim.
Pero como no se quitaron sus sombreros, el conde los llamó Cuáqueros y dijo:
"`No necesitamos Cuáqueros aquí. Salgan de mis dominios; no irán a mi ciudad.`"
Y les ordenó a algunos de sus soldados que los acompañaran
hasta que salieran de su territorio.
Por tanto, W. Penn y los que estaban con él,
se vieron obligados a pasar esa noche a campo abierto; pero al día siguiente,
le escribió una carta al mencionado conde, en la que le decía: "`Por tu dicho,
"`no necesitamos Cuáqueros aquí,`" yo digo que definitivamente los necesitas.
Porque un verdadero Cuáquero es aquel que tiembla ante la palabra del Señor,
y trabaja su salvación con temor y temblor.`"

Cuando W. Penn llegó a Mulheim,
no pudo encontrar más oportunidad para hablar con la condesa,
que la que tuvo la primera vez que había estado en esa zona; por tanto,
se fue a Duisburgh, Wesel y Cleves,
donde después de tener conferencias con algunas personas religiosas,
regresó por el camino de Utrecht a Ámsterdam, donde también había regresado G. Fox.

Aquí W. Penn y G. Fox tuvieron una conferencia y disputa con Dr. Galenus Abraham,
un eminente maestro Bautista,
y algunos de esa persuasión. Galenus afirmaba que en estos días,
nadie podía ser aceptado como mensajero de Dios,
a menos que confirmara su doctrina por medio de milagros.
W+++.+++ Penn no le faltaron argumentos para contradecir eso,
diciendo que la religión Cristiana ya había sido confirmada por milagros,
y que por eso ahora eran innecesarios entre los Cristianos.
G+++.+++ Fox de vez en cuando también decía algo del asunto,
pero como en ese momento le faltaba el aliento, varias veces salió y regresó,
lo que algunos atribuyeron a un temperamento apasionado;
pero sé bien que en eso se equivocaron de él. La disputa fue un asunto realmente problemático,
porque ambas partes tuvieron que hablar por medio de un intérprete,
lo que en general se realizó de una manera tan imperfecta,
que al final se interrumpió la conferencia sin llegar a una decisión,
aunque se objetaron muchos argumentos de peso contra la posición. En definitiva,
no pudo ser negado que Juan el Bautista había sido
enviado por Dios para predicar el arrepentimiento,
y que aunque en el escrito sagrado constaba claramente que Juan no había hecho milagros,
muchos habían creído en él. Que aunque entre los profetas varios habían hecho milagros,
no encontrábamos en las Escrituras que Jonás,
quien ciertamente había sido un notable predicador del arrepentimiento,
hubiera hecho alguno, y sin embargo,
los ninivitas habían creído en él. Que de varios otros verdaderos
profetas no se hacía la menor mención de que hubieran hecho milagros,
y que por el contrario,
las Escrituras señalaban que posiblemente se levantarían
falsos profetas y harían señales y maravillas.
Que hacer milagros no siempre era una prueba o evidencia
segura de que alguien hubiera sido enviado por Dios,
según se desprendía claramente de lo dicho por nuestro Salvador,
porque entre aquellos a quienes un día les diga:
"`Apartaos de mí,`" estarán los que le van a decir:
"`¿No echamos fuera demonios en tu nombre, y en tu nombre hicimos muchos milagros?`"
Y con respecto a los hechiceros de Egipto,
que habían hecho las mismas maravillas que Moisés y Aarón hicieron, aun así,
esas maravillas con las que habían engañado al faraón y a sus hombres,
no habían sido en ninguna manera realizadas por el poder divino.
Y dado que claramente se desprendía de las Sagradas
Escrituras y de lo que Cristo mismo había dicho:
"`Se levantarán falsos profetas;
y harán grandes señales y prodigios,`" podríamos sospechar con
buena razón de la doctrina del que obra milagros hoy a propósito,
para hacer pasar como verdad lo que declara.

Al considerar esto debidamente,
parece muy absurdo requerir que se hagan otra vez milagros para
confirmar el mismo evangelio que ya ha sido confirmado por milagros;
o desear que la verdad de lo que fue una vez declarado
por los apóstoles y fortalecido por obras maravillosas,
sea sellada de nuevo con más maravillas externas.
Pero, ciertamente, otro sería el caso si se predicara un _nuevo_ evangelio,
o si alguien pretendiera dar nuevas Sagradas Escrituras;
porque entonces se podría decir con alguna razón,
que es necesario que ese nuevo evangelio sea hecho
creíble y se confirme mediante milagros visibles.
Pero donde no se predica otro evangelio,
que el que una vez fue entregado a los Cristianos
por los primeros promulgadores del Cristianismo,
y donde dicha predicación no se hace entre paganos, sino entre Cristianos,
o al menos entre los que llevan el nombre,
allí no puede requerirse con razón que se confirme esta doctrina una vez más con milagros.
A esto puede añadirse también,
que los milagros que Cristo y Sus apóstoles realizaron para
darle crédito a la aparición del Hijo de Dios en la carne,
pueden ser considerados tipos y figuras de aquellas maravillas espirituales
o internas que deben ser realizadas en las almas de las personas,
cuando Cristo sea visto "`la segunda vez,`" y aparezca
por Su Espíritu "`para salvación de los que le esperan.`"
^
footnote:[Hebreos 9:28] Porque los ojos de la mente que están cegados,
deben ser abiertos e iluminados por Él; y muchos que están muertos en delitos y pecados,
serán resucitados por Él y vivificados.
Creo que esto es suficiente para demostrar que la
posición del Dr. Galenus no pudo soportar la prueba;
sin embargo, por mucho que se objetó contra ella, él siguió manteniendo su opinión.

No mucho después de esta disputa, G. Fox y W. Penn regresaron a Inglaterra, donde,
tras soportar una violenta tempestad en el mar, llegaron a salvo a Harwich.
Pasando de ahí a Londres, W. Penn recibió la siguiente carta de la princesa Elizabeth,
en respuesta a la de él:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Herford, 29 de Octubre, 1677

[.salutation]
Querido Amigo,

Tu tierno cuidado por mi bienestar eterno me obliga mucho,
y sopesaré cada artículo de tu consejo y lo seguiré tanto como me sea posible;
pero la gracia de Dios debe ser mi ayudadora, como tú mismo lo dices,
porque Él no acepta nada que no provenga de Él. Si
yo me despojara de todos los bienes mundanos,
y sin embargo, dejara de hacer lo que Él más requiere--es decir,
que yo haga todo en y por Su Hijo--no estaría en mejor condición que la actual.
Permíteme sentirlo a Él primero gobernando mi corazón,
para luego hacer lo que Él requiera de mí; pero no soy capaz de enseñar a otros,
si yo misma no he sido enseñada por Dios.
Recuerda mi amor a G. Fox, B. F., G. K. y a la querida Gertrude.^
footnote:[Esta era Gertrude Dericks, quien había visitado a la princesa,
después se fue a vivir a Inglaterra y se casó con Stephen Crisp.
Murió unos cuatro años después.]
No creas que me alejo de lo que te dije la última noche;
sólo me mantengo para hacerlo de manera responsable ante Dios y el hombre.
No puedo decir más ahora, sino encomendarme a tus oraciones,

[.signed-section-closing]
Tu amiga verdadera,

[.signed-section-signature]
Elizabeth

[.postscript]
====

P+++.+++ D. Casi olvido decirte,
que mi hermana me escribió diciendo que se había alegrado de que
al regresar a Ámsterdam hubieras emprendido tu viaje por Osenburgh.
También hay un Drossard de Limbourg cerca de este lugar (a quien le di una copia de
la apología de Robert Barclay) que está muy deseoso de hablar con algunos de sus amigos.

====

--

W+++.+++ Penn recibió aún otra carta de la mencionada princesa,
en respuesta a una que él le escribió desde Briel, en su paso hacia Inglaterra,
que decía:

[.embedded-content-document.letter]
--

[.letter-heading]
A la princesa Elizabeth, Salvación en la Cruz, Amén.

[.salutation]
Querida y verdaderamente respetada amiga,

Mi alma fervientemente desea tu felicidad temporal y eterna,
la cual consiste en que hagas la voluntad de Dios ahora en la tierra,
como se hace en el cielo.
¡Oh, querida princesa, hazla!
Di la palabra en verdad y justicia: "`¡No se haga mi voluntad, sino la Tuya, oh Dios!`"
Tus días son pocos y luego debes ir a juicio.
Entonces el Señor te pedirá cuentas de tu talento.
¿Qué incremento has hecho?
Deja que pruebe y muestre su propia excelencia, que es de Dios,
y que conduce a todos los que lo aman a Dios.
¡Ojalá puedas rendir cuentas con gozo!

No podía dejar este país sin testificar de los sentimientos que tengo en mi mente,
de ese recibimiento humilde y tierno que nos diste en tu corte.
Que el Señor Jesús te recompense, y de seguro, Él tiene una bendición guardada para ti.
Continúa, sé fiel, vence y heredarás. No te desanimes;
uno que es poderoso está cerca de ti; un socorro presente en el tiempo de angustia.
¡Oh,
que el deseo de tu alma sea Su nombre y Su recuerdo!
¡Espera en el Señor y renovarás tu fuerza!
Los muchachos se fatigarán y los jóvenes fracasarán,
pero los que confían en el Señor nunca serán confundidos.

Te deseo con toda mi alma, una verdadera y sólida felicidad.
Que el Señor del cielo y de la tierra te tenga en Su cuidado, para que no pierdas,
sino guardes en ese sentido divino, lo que Él ha engendrado en ti por Su Palabra eterna.
Recibe, querida princesa, mi saludo sincero y Cristiano.
La gracia, misericordia y paz se multipliquen entre todos los que aman al Señor Jesús.

Le daré seguimiento a tus asuntos con toda la diligencia y discreción que pueda,
y te daré cuenta por los primeros medios disponibles,
después de que le plazca al Señor llevarme a salvo a Londres.
Todos mis hermanos están bien,
y te presentan a ti y a todos los de tu familia que aman a Jesús, la luz del mundo,
su cariñoso amor.
Tú me has enseñado a olvidar que eres una princesa, y por eso uso esta libertad;
y a ese don de Dios en ti estoy manifiesto, y conozco mi integridad.
Si te place, dale mi cariñoso saludo a A. M. de Homes, con el adjunto.
Querida princesa, no la estorbes, sino ayúdala.
Es posible que se demande algo de ella,
lo cual (considerando tus circunstancias) es posible que no se requiera aún de ti.
Déjala libre, y su libertad hará tu paso más fácil para ti.
Acepta lo que digo, te lo ruego,
con ese amor y respecto puro y celestial con que te escribo tan claramente.
Me despido, mi querida amiga, y que el Señor esté contigo.
Soy más de lo que puedo decir,

[.signed-section-closing]
Tu amigo, que te ama y respeta,

[.signed-section-signature]
W+++.+++ Penn

[.postscript]
====

Te remito a los pasajes adjuntos.
Visitamos a Gichtel y a Hooftman, y ellos a nosotros.
Estuvieron en una o dos de las reuniones en Ámsterdam.
_Vale in sternum._

====

--

[.offset]
A esta carta la princesa respondió lo siguiente.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Este 17 de Noviembre, 1677

[.salutation]
Querido Amigo,

He recibido una carta tuya que parece haber sido escrita en tu viaje hacia Inglaterra,
el cual espero que sea próspero.
Está sin fecha,
pero no sin virtud para animarme a hacer y a sufrir la voluntad de nuestro Dios.
Puedo decir con sinceridad y verdad: "`Hágase tu voluntad,
oh Dios,`" porque lo deseo de corazón,
pero no puedo hablar con justicia hasta que posea esa justicia que es aceptable
para Él. Mi casa y mi corazón siempre estarán abiertos a los que lo aman a Él.
Gichtel ha quedado muy satisfecho por la conversación entre ustedes.
En cuanto a mis asuntos, irán como al Señor le plazca, y yo permanezco en Él

[.signed-section-closing]
Tu afectuosa amiga,

[.signed-section-signature]
Elizabeth

--

Ya en Londres, G. Fox recibió cartas de Nueva Inglaterra,
con un informe de los crueles procedimientos de los magistrados contra
sus amigos ahí. Como la persecución era intensa en Vieja Inglaterra,
hizo que las cosas fueran peor para los de Nueva Inglaterra; a tal punto,
que no sólo azotaban a los Cuáqueros que estaban allí, sino que también,
azotaron a algunos capitanes de barcos que no eran Cuáqueros,
sólo por llevar algunos de esa persuasión a ese lugar.
Pero por ese tiempo,
los indios atacaron a los ingleses y mataron a sesenta de sus hombres;
y habiendo tomado a uno de sus capitanes,
le desollaron la cabeza mientras estaba vivo y se lo llevaron triunfantes.

Ahora bien, dado que el pueblo llamado Cuáqueros era también muy perseguido en Escocia,
ellos redactaron un informe de sus sufrimientos y
se lo entregaron al rey al principio de este año;
pero no puedo decir si obtuvieron algún beneficio por ello.

En la última parte de este año, G. Fox viajó por muchos lugares de Inglaterra.
Mientras tanto, haré mención otra vez de la persecución ahí. Por ese tiempo en Plymouth,
los llamados Cuáqueros eran generalmente mantenidos fuera de sus lugares de reunión,
y por eso realizaban su adoración en la calle, como un deber que le debían a Dios.
Ellos sufrieron muchísimo por esto, no sólo por lo punzante del clima en el invierno,
sino también en el verano;
pues tuvieron que celebrar sus reuniones en la calle por más de doce meses,
durante los cuales fueron gravemente maltratados por la chusma y los soldados.
Las palizas y los puñetazos no parecían ser suficientes,
pues les lanzaban petardos y carbones encendidos,
y asquerosos excrementos por las ventanas.
Además, les impusieron multas por haber estado en la reunión,
y un tal Richard Samble fue multado como predicador
por haber estado sobre sus rodillas en oración,
multa que fue colocada sobre otros cuatro que estaban presentes en la misma reunión.

En Frenchay, Gloucestershire,
el magistrado John Merideth se comportaba con excesiva
furia al perturbar las reuniones de los Cuáqueros;
ya que él mismo no sólo los golpeaba,
sino que más de una vez sacó su cuchillo para "`marcarlos,`" según decía,
pero era frenado por sus criados, quienes, a pesar de todo,
no pudieron evitar que cogiera a algunos por el pelo de la cabeza y se los arrancara.
De hecho, los estragos y despojos eran tan exagerados, que a un tal Thomas Holbrow,
un anciano ciego, le quitaron su cama,
y él y su esposa durmieron sobre paja casi un cuarto de año. Y
cuando sus amigos le proveyeron algo de ropa para el invierno,
también le quitaron parte de ella.
Pues en ese entonces se realizaba tal saqueo,
que incluso los hombres más bajos estaban autorizados a privar a otros de sus bienes,
si sólo había un magistrado que lo favoreciera.

En Bayton, Suffolk, por una orden judicial del magistrado Burwel,
Edmund Bally fue despojado de lo que tenía,
tanto dentro como fuera de las puertas de su casa,
pues le confiscaron sus bienes cinco veces.
Y aunque se le obligó a dormir sobre paja, no dejó de ser molestado,
pues en una ocasión llegaron a su casa durante la noche armados con pistolas,
rompieron su puerta y lo amenazaron con destruirlo.
También sucedió en este lugar,
que una pobre viuda ciega fue visitada por algunos amigos en su lecho de enferma;
a esto se le llamó un conventículo, por lo que fueron multados,
y el mencionado magistrado emitió una orden judicial para confiscar los bienes de ellos.
En muchos otros lugares las cosas no estaban mejor,
pero no voy a detener a mi lector con cada detalle.

Este año murió en prisión William Dobson, de Brightwell, en Berkshire,
después de haber sido despojado de sus bienes una y otra vez durante
trece años (y casi siempre mientras estaba en prisión),
hasta que sus duros sufrimientos acabaron con su vida.

Fue también en este año que William III, príncipe de Orange,
llegó de Holanda a Inglaterra, y ahí se casó con la princesa Mary,
la hija mayor del duque de York,
lo que con el paso del tiempo le abrió el camino para ascender
al trono de Gran Bretaña. Él contrajo matrimonio el 4 de Noviembre,
día de su cumpleaños, y no mucho después regresó a Holanda con su esposa.

A principios del año 1678,
G+++.+++ Fox llegó a Londres y como el Parlamento estaba sesionando en ese momento,
él y George Whitehead se presentaron ante ellos y les informaron de los
graves sufrimientos de sus amigos por las leyes hechas contra los papistas.
Al ver que varios de los miembros de esa gran asamblea parecían estar a su favor,
no dejaron de tener esperanza de obtener algún alivio;
pero el Parlamento fue repentinamente prorrogado, por lo que se puso fin a sus esfuerzos.

G+++.+++ Fox viajó por muchos lugares y regresó a casa
en Swarthmore en la última parte del año;
y dado que muchos de sus amigos en ese momento estaban
bajo una gran persecución y en prisiones,
les escribió la siguiente epístola:

[.embedded-content-document.letter]
--

[.salutation]
Mis queridos Amigos,

Que sufren por causa del Señor Jesús y por el testimonio de la verdad;
que el Señor Dios Todopoderoso con Su poder los sostenga
y apoye en todas sus pruebas y sufrimientos,
y les dé paciencia y contentamiento en Su voluntad,
para que se mantengan valientes por Cristo y Su verdad sobre la tierra,
sobre el espíritu perseguidor y destructor que hace
sufrir en Cristo (quien aplasta su cabeza),
en quien tienen tanto la elección como la salvación. Desde la fundación del mundo,
el Señor ha hecho mucho bien por los elegidos de Dios;
como puede verse a lo largo de las Escrituras de Verdad; y aquellos que los tocan,
tocan la niña del ojo de Dios, porque son muy tiernos para Él. Por lo tanto,
es bueno para todos los hijos sufrientes de Dios
que confíen en el Señor y que esperen en Él;
porque serán como el monte de Sion que no puede ser removido de Cristo,
la roca y salvación de ellos, quien es el fundamento de todos los elegidos de Dios,
de los profetas y de los apóstoles, y del pueblo de Dios ahora y hasta el fin.
¡Gloria al Señor y al Cordero sobre todo!
Recuérdenles mi cariñoso amor a todos los amigos; y no piensen que el tiempo es largo,
porque todos los tiempos están en las manos y poder del Padre.
Por tanto, guarden la palabra de paciencia y ejerciten ese don;
y que el Señor los fortalezca en sus sufrimientos, en Su Santo Espíritu de fe.
Amén.

[.signed-section-signature]
George Fox

[.signed-section-context-close]
Swarthmore, día 5 del mes Doce, 1678

--

La persecución era entonces muy intensa en muchos lugares.
En Bawnasse, Westmoreland,
los miembros de la sociedad llamada Cuáqueros que se reunían religiosamente,
eran muy lastimados por la chusma; además,
se cometieron otros actos de insolencia y un perro fue lanzado en medio de ellos.
Un tal John Thomson le dijo a este grupo insolente,
que se comportaran de forma civilizada y moderada,
y por decir esto fue denunciado como predicador,
y por ese motivo fue multado con 20 libras.
Mary Tod, una viuda anciana y pobre en Yorkshire,
por tener una reunión en su casa también fue multada
con 20 libras por el juez Francis Driffield,
y cuando los informantes le dijeron que sus bienes no sumaban la multa,
ordenó que le quitaran todo lo que encontraran, y así lo hicieron,
y no le dejaron ni una cama donde acostarse, ni ropa.

Este año se reunieron en Nimeguen,
los embajadores del rey de Francia y los de los Países Bajos Unidos,
junto como otros varios potentados, para hablar de una paz general;
por lo que Robert Barclay les escribió una epístola en latín,
exhortándolos a esa buena obra.
La epístola junto con su [.book-title]#Apology for the true Christian Divinity#,^
footnote:[__Apología de la Verdadera Divinidad Cristiana__]
en latín, también fue entregada a cada uno de los mencionados embajadores;
un libro para cada uno de ellos.
George Fox también escribió una epístola de exhortación para ellos,
la cual fue traducida e impresa en latín, y también enviada.
Antes de que este año terminará, la paz fue firmada.

Mientras tanto, la persecución continuaba en Inglaterra,
y los envidiosos no carecían de pretextos engañosos para cubrir su malicia.
Por ese tiempo, al descubrirse un complot de los papistas,
parecía necesario vigilar las asambleas sediciosas, a tal punto,
que incluso aquellos que no tenían en mente perseguir,
en alguna forma se vieron obligados a hacerlo.
Un ejemplo de esto se vio en el año 1679, en Castle Dumington, en Leicestershire,
porque John Evat había sido multado por una reunión en su casa,
y como no se hallaron suficientes bienes para cubrir la multa,
el alguacil y otros tres oficiales fueron multados cada uno con cinco libras,
porque no habían estado dispuestos a quitarle sus bienes a Evat.
Sin embargo,
los eclesiásticos se mostraban cada vez más codiciosos
por obtener lo que pretendían que les correspondía,
y este año, un tal Michael Reynolds, de Farringdon, en Berkshire,
fue despojado de su ganado, cebada y frijoles,
por un valor de más de noventa y siete libras,
y todo esto por los diezmos de un solo año.

De este modo se oprimía a los hombres honestos,
lo cual le dio oportunidad a cierto escritor de la época (quien
de manera impresa publicó varios ejemplos similares) que dijera:
"`Verdaderamente los papistas pueden reírse de su victoria,
ahora que tienen una ley por la que un Protestante lucha contra otro.`"
Este comentario fue principalmente dirigido contra los conventículos;
ya que por ello muchas familias fueron empobrecidas,
pues a menudo se les robaba el triple de la suma de la multa,
y se usaban los medios más bajos imaginables para
enriquecer a los perseguidores con el botín del inocente.
Sucedió en una ocasión,
que cuando cuatro de los llamados Cuáqueros estaban viajando juntos,
se consideró una transgresión cuando un quinto se
unió a ellos que ni siquiera era de su sociedad.
Y tan grande era el poder de ellos,
que los informantes (algunas de las cuales a menudo era prostitutas,
o las esposas de informantes) la tildaron de reunión,
y por este motivo los bienes de las citadas cuatro personas fueron confiscados.
Yo podría mencionar más actos abominables de este tipo, si no pensara que sería tedioso.
Tales saqueos se le permitían entonces a cualquier tipo malo,
y esto los hizo tan descarados, que cuando se le mostró a un tal John Hill,
alguacil en Walsingham, Norfolk, la injusticia de la orden judicial que tenía, dijo:
"`Justa o no, la tomaré de todas maneras.`"

En Norwich vivía un tal William Wat,
quien por varios años se había dedicado al oficio de informante,
pero sin importar cuánto ganara por ello de nada le servía;
ya que a menudo sufría tales ataques de debilidad
que no podía mantenerse sobre sus piernas.
Pero en Octubre de este año, la mano de Dios cayó tan pesadamente sobre él,
que puso fin a su vida.
Él había cenado por la noche, y estaba tan bien como siempre,
según el relato de su esposa, pero de repente se desplomó en el piso,
y pareció mirar a su hija que lloraba a gritos,
y luego murió sin más. Pero lo extraño fue,
que su cadáver apestaba tan fuertemente que nadie estaba dispuesto a cargarlo,
y los supervisores de los pobres tuvieron que contratar
a cuatro hombres para que lo llevaran a la tumba.

Muy diferente fue la salida de Isaac Penington,
un eminente ministro y autor entre los llamados Cuáqueros,
y un hombre de un ingenio agudo y grandes dones naturales, quien en el año 1658,
en el llamado Domingo de Pentecostés, estando en una reunión en la casa de John Crook,
en Bedfordshire, fue tan alcanzado por la predicación de G. Fox, que él,
que antes de ese momento había contradicho a los Cuáqueros con su sabiduría natural,
abrazó entonces la doctrina de la verdad de ellos
y no dudó en hacer profesión pública de ella,
por lo que después sufrió varias veces encarcelamientos durante
varios años. Pero continuó firme hasta el final sin desmayar,
y murió piadosamente en Octubre, en su casa cerca de Goodnestone, en Kent,
de donde su cuerpo fue llevado a Buckinghamshire,
donde había vivido anteriormente y fue honorablemente enterrado ahí.

Algún tiempo antes de esto,
G+++.+++ Fox le había escrito varias preguntas al papa y a los papistas,
que al ser traducidas al holandés e impresas,
me pidió que las tradujera al latín y las enviara a Roma al papa.
Así lo hice, según su deseo, pero nunca recibí ni escuché alguna respuesta de ellos.
Las preguntas fueron las siguientes:

[.embedded-content-document.epistle]
--

[.letter-heading]
A Inocencio XI, papa de Roma, S.

[.salutation]
Gran Prelado,

Tal vez a primera vista te parezca extraño que se te envíe el escrito adjunto;
pero debes saber que fue hecho a petición del autor, y no inmerecidamente;
porque si sopesas y consideras correctamente el asunto,
tú tendrás que admitir con nosotros que habría sido
muy indigno ocultar este pequeño tratado de tu vista,
el cual ya ha sido publicado en lengua holandesa,
y lleva el nombre del papa en el frontispicio.^
footnote:[Página de un libro anterior a la portada,
que suele contener el título y algún grabado o viñeta.]
Tampoco podrás negar que no sólo no has sido agraviado,
sino que además hemos cumplido con el deber que te debemos,
al transmitir estas preguntas que propiamente te pertenecen.
Y si te place leerlas y devolver una respuesta,
complacerás al autor y eliminarás la sospecha de error de
tu religión ante la vista de todo la Cristiandad,
siempre que puedas dar una respuesta clara a las objeciones, no sólo de palabra,
sino también de hecho,

[.signed-section-closing]
Escribí esto a petición de algunos de mis amigos llamados Cuáqueros.

[.signed-section-signature]
William Sewel

[.signed-section-context-close]
Ámsterdam, día 23 del mes llamado Abril, 1679.

--

[.embedded-content-document.epistle]
--

[.blurb]
=== Algunas preguntas planteadas a los papistas y al papa de Roma, como cabeza suprema de su iglesia, y encomendadas a la consideración de ustedes por George Fox

[.salutation]
Amigos,

[.numbered-group]
====

[.numbered]
1+++.+++ ¿Por qué el papa y los cardenales no les conceden
a los Protestantes que viven en España,
Italia y Roma la libertad de reunirse para celebrar la adoración divina,
que ustedes sí disfrutan en Inglaterra,
Holanda y otros lugares donde los Protestantes tiene el poder principal?
¿Acaso el papa y sus ministros no los perseguirían,
entregarían a la Inquisición y quemarían,
si en algún momento establecieran tantas reuniones en España, Italia y Roma,
como las que ustedes ya disfrutan en muchos lugares de los países Protestantes?

¿Cumple esto la "`ley real`" de Dios,
que nos enseña a hacerles a los hombres lo que quisiéramos
que nos hicieran a nosotros mismos?
Mateo 7:12. ¿Quieren que los Protestantes les hagan lo que ustedes les han hecho a ellos?
Pero si no, ¿dónde están entonces "`la ley y el evangelio real`" entre ustedes?
¡Lejos esté de nosotros negarle la libertad a alguien
que reconozca a Dios y crea en Su Hijo,
el Señor Jesucristo!
Nos parece muy extraño, entonces,
que el papa y los papistas nieguen la misma libertad en los lugares
mencionados que ellos disfrutan entre los Protestantes.
El apóstol afirma: "`El que nació según la carne,
perseguía al que nació según el Espíritu.`"
¿Así pues, no han mostrado abiertamente los papistas el nacimiento carnal en sí mismos,
el cual es contrario a la razón, a la ley y al evangelio?

[.numbered]
2+++.+++ ¿Dónde ordenaron Cristo o Sus apóstoles que los hombres se inclinaran ante imágenes,
las adoraran y guardaran días santos?
¿Dónde ordenaron que se señalaran días santos en memoria de ellos mismos y que se honraran?
¿Por qué no nos dicen en qué lugar de los evangelios, epístolas, o de la revelación,
fue ordenado algo así a las iglesias que había en
el tiempo de los apóstoles y de los Cristianos primitivos?
Digo, ¿dónde dieron Cristo o Sus apóstoles el mandamiento de azotar,
colgar o quemar a los hombres; o incluso,
encarcelar a los hombres porque disentían de ellos y no podían unirse a su religión?

[.numbered]
3+++.+++ ¿Dónde ordenaron Cristo o Sus apóstoles a las iglesias primitivas
que encendieran velas al mediodía? Muéstrennos dónde está escrito,
si en los evangelios, o en las epístolas.
¿No se ha degenerado la iglesia romana de la iglesia de los tiempos primitivos?
¿No ha caído de las armas espirituales a las armas carnales?
¿No se ha rebelado de esa pureza y virginidad en la que anteriormente
experimentó a Cristo como la cabeza de Sus iglesias?

[.numbered]
4+++.+++ ¿Acaso las iglesias de la antigüedad escogieron a un hombre
en particular y lo consideraron la cabeza de la iglesia universal?
¿Dónde ordenó la iglesia primitiva que se rociaran a los niños con agua?
¿No dice Cristo: "`Enseñad a todas las naciones, bautizándoles,`" etc.
Mateo 28:19? ¿No deben ser enseñadas antes de ser bautizadas?
¿No se han degenerado ustedes de esa fe de la que Cristo es el autor y consumador,
que purifica el corazón y da victoria sobre el pecado y el mal (que separan de Dios),
y por la que tenemos entrada a Dios y en la que Él se complace?
¿No se han degenerado ustedes de la luz, verdad, gracia,
poder y espíritu en el que estaban los apóstoles?

[.numbered]
5+++.+++ ¿No se han degenerado de la antigua iglesia,
porque no le permiten a las personas leer las sagradas
Escrituras en su propia lengua materna?
Pues los apóstoles dicen: "`Y cuando esta epístola haya sido leída entre vosotros,
haced que también se lea en la iglesia de los laodicenses.`"
Colosenses 4:16 En otro lugar: "`Os conjuro por el Señor,
que esta carta sea leída a todos los santos hermanos.`"
1 Tesalonicenses 5:27 Sí, ¿no dijo Cristo también: "`¡Oh insensatos,
y tardos de corazón para creer todo lo que los profetas han dicho!`"?
Lucas 22:25 ¿Cómo podrá el pueblo común creer estas cosas que Cristo,
los profetas y los apóstoles han dicho,
a menos que se les concedan leerlas en su propia lengua materna,
con el fin de que puedan oírlas y entenderlas por el Espíritu que las dio?
¿Por qué, entonces, le quitan al pueblo el uso de las sagradas Escrituras?
¿Temen que se manifieste la verdad y que por ella vean y
crean lo que está escrito en la ley y los profetas,
y por Cristo y Sus apóstoles?
¿No tenían los judíos la ley y los profetas en su lengua materna,
para que sus niños pudieran leerlas?
¿No deberían igualmente todos los Cristianos,
tener el Nuevo Testamento que cuenta de Cristo y Sus apóstoles, en su lengua materna?
Pero si no, ¿por qué no nos muestran en qué lugar Cristo o Sus apóstoles lo prohibieron?

Pero, ¿qué dicen del llamado "`sacramento del altar`"? ¿Por qué
han matado a muchos y quemado vivos a otros en Inglaterra,
Francia, Países Bajos y otro lugares, porque no podían aprobarlo o recibirlo?
Ustedes afirman como algo cierto,
que tan pronto el pan y el vino son consagrados se convierten en Cristo; sí,
en todo Cristo, que consiste en alma, espíritu, carne, sangre y huesos.
Además de esto afirman audazmente, que todo el que recibe este sacramento,
recibe la totalidad de Cristo, y que después de la consagración,
la cosa misma se vuelve inmortal y divina.

Por tanto, vengan, papa, cardenales y sacerdotes,
tomemos una botella de vino y una hogaza de pan,
dividamos el vino a partes iguales en dos cuencos, y cortemos el pan a la mitad.
Luego, que el papa, los cardenales o los sacerdotes consagren una parte, la que quieran;
luego pongamos lo consagrado y lo no consagrado juntos en algún lugar seguro,
asegurándolo todo con siete cerraduras y llaves de parte de ustedes,
y con otras tantas de parte nuestra,
y que tanto los papistas como los Protestantes vigilen.
Y si se demuestra claramente que el pan y el vino consagrados son inmortales y divinos,
y no pierden nada de su virtud ni sabor, ni se enmohecen ni agrían,
como si no hubieran sido consagrados, entonces nosotros nos pasaremos a ustedes.
Pero si pierden su propiedad, calidad y sabor,
y ambas partes del pan se enmohecen por igual,
entonces será razonable que ustedes se pasen a nosotros y confiesen
que el llamado "`sacramento del altar,`" no es Cristo,
ni Su carne, ni algo inmortal o divino; porque Su carne no vio corrupción,
Hechos 2:27-31; 13:35-37, y Su preciosa sangre que libra del pecado y la corrupción,
no puede ser corruptible.

Que se haga un juicio de esto; y que el juicio se deje a árbitros justos y equitativos,
tanto papistas como Protestantes,
y eso en un lugar donde los Protestantes tengan el mismo poder que tienen ustedes;
porque sería injusto hacer este juicio donde ustedes
tengan toda la administración de la nación,
y se les niegue la misma libertad a los Protestantes.
Esto hará que la verdad se manifieste y se vuelva para el honor de Dios; porque,
de hecho,
ustedes han matado a multitudes del pueblo de Dios
y derramado mucha sangre por este motivo.

[.numbered]
6+++.+++ Además, ¿dónde les hablaron Cristo o Sus apóstoles a los santos de un purgatorio,
en el que los hombres serían purgados de sus pecados después de la muerte?
Muéstrennos donde está escrito eso en el Nuevo Testamento.
Por tanto,
contarles a las personas una fábula de un purgatorio
que las purificará del pecado después de la muerte,
¿no es una clara negación de que la sangre de Cristo purifica de todo pecado?
¿No es también una negación del bautismo de Cristo con el Espíritu Santo,
de la circuncisión espiritual,
y de la fe en Cristo que purifica del pecado en esta vida y da la victoria?

[.numbered]
7+++.+++ ¿No les respondió Cristo a unos que querían que descendiera
fuego del cielo y consumiera a los que no lo recibían a Él:
"`Vosotros no sabéis de qué espíritu sois,`" y los reprendió diciendo
que Él no había "`venido para perder las almas de los hombres,
sino para salvarlas`"? Lucas 9:54-56 Pero ustedes han destruido un gran
número de hombres y mujeres por disentir con respecto a ritos y ceremonias,
y les han quitado sus vidas con instrumentos como la tortura y el fuego;
cosas que no fueron enviadas del cielo, sino ideadas e inventadas por ustedes mismos.
¿No son ustedes peores que aquellos que querían que se hiciera
descender fuego del cielo para destruir las vidas de los hombres?
Y al ver que Cristo les dijo que ellos no sabían de qué espíritu eran,
¿saben ustedes de qué espíritu son;
ustedes que han ideado y usado tantas maneras para atormentar y matar a los hombres?

Porque, ¿cuándo ordenó Cristo o alguno de Sus apóstoles, o enseñó con su ejemplo,
que todo aquel que lo desobedeciera o rechazara su doctrina y religión,
debía ser perseguido y encarcelado, o castigado con armas carnales?
Dígannos donde se encuentra algo de este tipo,
ya sea en las cuatro historias evangélicas,
o en las epístolas escritas para las Iglesias Cristianas.
¿Fue alguna vez Cristo o Sus apóstoles a los fabricantes
de cuerdas para comprar látigos y sogas,
y con ello azotar y colgar a los hombres por disentir de ellos como lo han hecho ustedes?
¿Fueron alguna vez a los herreros para hacer cadenas, grilletes, pernos y cerrojos?
¿O a los armeros para comprar pistolas y mosquetes,
o a los fabricantes de espadas para comprar espadas y alabardas?
¿Construyeron alguna vez prisiones,
o hicieron cavar hoyos y cavernas en la tierra para
obligar a los hombres por estos medios,
a volverse a su religión? Muéstrennos un ejemplo
y un precepto dado por Cristo o Sus apóstoles,
que ordene y haga uso de tales armas e instrumentos.

Pero si no pueden probar esto,
es necesario que confiesen y admitan que han caído y se
han degenerado de las verdaderas armas Cristianas,
que usaron los apóstoles y los Cristianos primitivos al decir:
"`Porque las armas de nuestra milicia no son carnales,
sino poderosas en Dios,`" es decir, espirituales.
2 Corintios 10:4

====

[.signed-section-signature]
G+++.+++ Fox

--

[.embedded-content-document.letter]
--

[.letter-heading]
A Inocencio XI, papa de Roma, S

He aquí, gran prelado,
hace unos tres meses fue enviada por correo la copia
de unas preguntas escritas para ti y tus seguidores,
pero al no estar seguros si te fue entregada o no en tus manos,
pensamos que era buena idea escribir las preguntas de nuevo y enviártelas,
para que no seamos responsables si no las lees.
Porque pensamos apropiado que te ocupes seriamente de examinar lo que se ha impreso aquí,
porque si te agrada hacerlo y además respondes tanto de hecho como por escrito,
satisfará el deseo del autor y eliminará una duda
o escrúpulo de las mentes de muchas personas.
Me despido.

[.signed-section-closing]
Esto ha sido escrito en el nombre de algunos de mis amigos llamados Cuáqueros.

[.signed-section-signature]
William Sewel

[.signed-section-context-close]
Ámsterdam, 24 del mes llamado Julio, 1679.

--

Este año hubo una gran conmoción en Inglaterra por un complot
llevado a cabo por los papistas contra la vida del rey,
quien hizo que su hermano, el duque de York, se fuera al otro lado del mar por un tiempo;
pues el Parlamento sospechaba de él por este complot,
y se hizo una moción en la Casa de los Comunes para excluirlo de la sucesión al trono,
pero el proyecto fue anulado.

Al principio del año 1680, sucedió que George Whitehead y Thomas Burr,
al llegar a Norwich y predicar ahí en la reunión de sus amigos,
fueron tomados prisioneros, según se dijo,
bajo la frívola pretensión de que G. Whitehead podría ser un Jesuita.
Al ser llevados frente al magistrado Francis Bacon,
quien entonces era registrador de la ciudad, después de un extraño interrogatorio,
les exigió la multa de veinte libras a cada uno, por ser predicadores.
Como ellos se rehusaron a pagar, él les preguntó si prestarían el juramento de lealtad,
y como le respondieron que no podían prestar juramentos por causa de sus consciencias,
él dijo, que si ellos no pagaban la multa, ni prestaban juramento,
los enviaría a la cárcel.
Al demostrar ellos que no eran vagabundos, sino hombres bien conocidos,
de buena posición y con residencia fija, Bacon dijo: __"`De non apparentibus,
et non existentibus eadem est ratio,`"__ +++[+++en español:
Lo que no se ve es lo mismo que lo que no existe]; es decir,
que aunque G. Whitehead tenía un patrimonio en Londres y T. Burr vivía en Ware,
esas cosas eran como si no existieran, por no ser una evidencia palpable en ese momento.
Ahora bien, aunque ellos mostraron lo absurdo de esa extraña forma de lógica,
el magistrado Bacon no los escuchó, sino que los llamó seductores y sediciosos,
y les dijo que había un estatuto todavía en vigor,
hecho en los días de la reina Elizabeth, para colgar a las personas como ellos.
Y cuando ellos le preguntaron si él podía en virtud de esa ley perseguirlos o ejecutarlos,
él respondió: "`Sí, si el rey diera la orden de ejecutarlos yo lo haría y los colgaría,
si no abandonaran el reino.`"
De esto puede verse cuán violento era este registrador,
y que los prisioneros no podían esperar ningún buen trato de él. Y así,
al llegar la noche los envió a la cárcel.

Cerca de un mes después, en las sesiones trimestrales,
fueron llamados al tribunal de justicia para ser juzgados.
Al ser llevados al estrado, George Whitehead dijo:
"`Hemos estado en prisión cinco semanas.
Es oportuno que el tribunal conozca la razón; por favor,
permitan que se presente nuestra orden judicial.`"
Pero el registrador que estaba sentado como juez en la corte dijo:
"`No hay necesidad de que se lea la orden judicial aquí. Yo daré cuenta de la causa.`"
Entonces le dijo a la corte que ellos dos habían
reunido a un grupo de casi doscientas personas,
que él había enviado oficiales para dispersarlos, pero no habían podido.
Que luego había enviado al alguacil y que él sí había podido detenerlos,
y al presentarlos ante él, les había ofrecido liberarlos si pagaban sus multas,
pero como se habían rehusado a pagar, les había presentado el juramento de lealtad;
pero como tampoco habían querido prestar el juramento, los había enviado a la cárcel.

Y aunque G. Whitehead dijo con razón, que al ser ciudadanos ingleses,
tenían derecho a viajar por cualquier parte de la nación, y T. Burr añadió,
que al ser una persona que se dedicaba al comercio del maíz,
por la ley de Inglaterra podía viajar de un lugar a otro por sus asuntos;
el registrador se disgustó tanto, que dijo:
"`Habría sido mejor para ti darle vuelta a tu malta en casa que venir a predicar.
Las Escrituras dicen:
'`El Señor añadía cada día a la iglesia los que eran
salvos,`' y ustedes se alejan de la iglesia.`"
Y añadió:
"`La iglesia de Inglaterra jamás estará en paz hasta que algunos de ustedes sean colgados.`"
Entonces G. Whitehead demostró lo irracional del comportamiento del registrador,
al mostrar que un juez no debía reprender a los prisioneros ni amenazarlos;
y alegó como ejemplo, que en el caso de Humphrey Stafford, un archi traidor,
el presidente del tribunal Hussey no había querido (en conformidad
al deseo del rey) declarar su opinión con respecto a él,
antes de que fuera procesado judicialmente.
El registrador entonces preguntó: "`¿En qué reinado fue eso?`"
"`En el reinado de Enrique VII,`" respondió George Whitehead.
"`Veo que eres un hombre culto,`" replicó el registrador.
Y de hecho, lo era; y defendió su causa tan bien en el tribunal,
que los magistrados parecían perdidos.
Porque mostró tan claramente que había sido injustamente enviado a prisión,
que el alcalde (a quien él había apelado) dijo: "`Has apelado a mí,
pero nosotros en realidad somos comerciantes, no abogados.
Le dejamos los asuntos de la ley al registrador.
Él conoce la ley y debemos aceptar su juicio.`"

Si repitiera aquí todo lo que se dijo en pro y contra,
sería casi tan extenso como he sido en el relato
de los juicios de John Crook y William Penn.
Por tanto, sólo diré brevemente, que después de mucho razonamiento,
el registrador les presentó el juramento de lealtad, para poder tener, ante su negativa,
la ocasión de dictar la sentencia de premunire contra ellos.
Pero este registrador, antes de que todo el proceso llegara al final,
fue expulsado por los magistrados, de modo que las cosas no llegaron a tal extremo.
No obstante,
pasó un buen tiempo antes de que los citados George Whitehead y Thomas Burr fueran liberados,
después de que habían demostrado la ilegalidad de su encarcelamiento; primero,
por más de una orden judicial del registrador, y después,
por una orden de las sesiones trimestrales.

Este año los llamados Cuáqueros en Londres,
publicaron un breve relato de los sufrimientos con los que
se habían topado sus amigos desde la restauración del rey,
y se lo presentaron al rey y al Parlamento.
En él demostraban cuántos habían sido multados por los tribunales de los obispos,
cuántos habían sido despojados de todo lo que tenían,
cuántos habían sido metidos en prisión y muerto ahí. Se
calculó este número en doscientas cuarenta y tres personas,
muchas de las cuales habían sido tan gravemente golpeadas
y lastimadas por asistir a sus asambleas religiosas,
que habían muerto por sus heridas.
También se publicó un informe sobre los procedimientos injustos de los informantes,
y cómo ante sus demandas, sin un proceso judicial,
los acusados a menudo habían sido privados de sus bienes;
la ilegalidad de lo cual estaba claramente demostrada
en los libros de notables abogados.

Por ese entonces,
G+++.+++ Fox estaba viajando por varios lugares y llegó
a Londres alrededor de la época de la reunión anual,
y viajando después otra vez por el país,
regresó a la mencionada ciudad y se quedó allí la mayor parte del invierno.

El Parlamento estaba en ese entonces muy ocupado
investigando el complot llevado a cabo por los papistas,
y la Casa de los Comunes estaba especialmente activa en el caso,
por lo que el proyecto de ley para expulsar al duque de York de la sucesión a la corona,
fue aprobado después de una tercera lectura.
Pero la Casa de los Lores se opuso a ello, porque la mayoría,
entre los que se encontraban los obispos que no consentían la expulsión,
rechazó el proyecto.
Ahora bien,
puesto que algunos Episcopales malintencionados estaban
muy deseosos de colocar a los Cuáqueros entre los conspiradores,
G+++.+++ Fox hizo la siguiente declaración al Parlamento:

[.embedded-content-document.epistle]
--

Es nuestro principio y testimonio negar y renunciar
a todos los planes y conspiraciones contra el rey,
o cualquiera de sus súbditos, porque tenemos al Espíritu de Cristo;
por el cual tenemos la mente de Cristo,
quien vino a salvar las vidas de los hombres y no a destruirlas.
Y nosotros queremos que el rey y todos sus súbditos estén a salvo.
Por tanto, declaramos, que nos esforzaremos, según nuestro poder,
por salvar y defenderlo a él y a ellos,
poniendo al descubierto todos los planes y conspiraciones que lleguen a nuestro conocimiento,
que destruirían al rey y a sus súbditos.
Esto se los ofrecemos sinceramente.
Pero en cuanto a jurar y a luchar, lo que no podemos hacer por ternura de consciencia,
ustedes saben que por nuestra consciente negativa a ello,
hemos sufrido muchos años. Y ahora que el Señor los ha reunido,
deseamos que nos alivien y liberen de estos sufrimientos,
y que no nos obliguen a hacer esas cosas,
las cuales hemos sufrido tanto y por tanto tiempo, por no hacerlas.
Porque si nos obligan, harán nuestros sufrimientos y ataduras más fuertes,
en lugar de aliviarnos.

[.signed-section-signature]
George Fox

--

No mucho después de esto,
también les escribió un documento a todos los gobernantes y magistrados en Inglaterra,
Escocia e Irlanda,
para disuadirlos de la persecución por religión.
Su labor no pareció del todo ineficaz con el Parlamento,
ya que al inicio del año 1681, la Casa de los Comunes decidió lo siguiente:

[.embedded-content-document.paper]
--

"`Es la opinión de la casa,
que la persecución de los disidentes Protestantes basada en las leyes penales,
es en este momento grave para los súbditos; es un debilitamiento del interés Protestante,
un estímulo al papismo, y peligrosa para la paz de este reino.`"

--

Pero aunque la Casa de los Comunes llegó a esta resolución, no se detuvo la persecución,
porque mientras las leyes por las que perseguían no fueran derogadas
(lo cual no podía hacerse sin el acuerdo de los lores y del rey),
los perversos continuaron con sus viejas costumbres,
lo que duró todavía otros tres o cuatro años.

George Fox también se vio envuelto en algunos problemas,
al descubrir que él y su esposa estaban demandados por diezmos,
aunque ella había vivido cuarenta y tres años en Swarthmore,
y en todo ese tiempo nunca se habían pagado o demandado diezmos.
G+++.+++ Fox tenía certificados de esto, pero como no podían aceptarlos sin un juramento,
hizo que su caso fuera más difícil.
Él les planteó el asunto a cuatro jueces en Londres,
y encontró que uno era más moderado que los otros,
lo que le puso fin a lo que los enemigos de ella habían ideado.
Los jueces se maravillaron cuando oyeron que él había hecho una promesa por escrito,
de nunca meterse con el patrimonio de su esposa.

Este año el rey disolvió el Parlamento y convocó uno nuevo para sesionar en Oxford,
y así lo hizo; pero como no pudo hacer que cumpliera con sus demandas,
también lo disolvió. Un tiempo después de esto le
pidió al príncipe de Orange que llegara a Londres,
quien llegó de Holanda a Inglaterra, y tras una corta estadía, regresó a La Haya.

Fue también el año en el que el rey le dio a William
Penn una gran extensión de tierra en América,
con una patente bajo el gran sello para él y los suyos en _perpetumm_ +++[+++perpetuidad],
pues el rey todavía le debía una considerable suma por los servicios de su padre,
el almirante sir William Penn.
Esta extensión de tierra en el río Delaware,
desde el grado cuarenta hasta el cuarenta y tres,
junto con todas las islas que le pertenecen, se las dio el rey a W. Penn,
con toda la autoridad de fundar una nueva colonia ahí, vender tierra,
establecer magistrados, hacer leyes que no fueran contrarias a las leyes de Inglaterra,
y poder para perdonar delitos.
En esta patente, el rey declaraba que esa extensión de tierra debía llevar en adelante,
el nombre de Pensilvania.
Este favor del rey, William Penn se lo debía principalmente, creo, a James,
entonces duque de York.
Porque sir William Penn, siendo almirante en jefe de Inglaterra,
en su lecho de muerte le había pedido al duque proteger a su hijo contra sus enemigos,
quienes, debido a su religión, era probable que cayeran sobre él duramente.
El duque lo prometió y lo cumplió. Con toda razón, cuando dicho duque ascendió al trono,
William Penn se mostró dispuesto a servirle en todo lo que
pensara que pudiera ser de beneficio para el reino.
Así pues, William Penn fue a América con un gran grupo,
y después de ver la tierra que le habían dado, fundó allí la ciudad principal,
Filadelfia, y algunas otras ciudades.
Y para poder disfrutar más pacíficamente el país, les compró a los indios tanta tierra,
que se convirtió en propietario de una extensión
dos veces más grande que todas las Provincias Unidas,
como alguna vez él mismo me lo contó. Esta colonia creció tan rápidamente,
que al cabo de unos años se construyeron seiscientas casas de ladrillo en Filadelfia.

El padre de William Penn murió mucho antes de esto,
y en su lecho de muerte declaró que tenía un Dios misericordioso,
y dio muestras de una verdadera disposición Cristiana.
También le hizo a su hijo varias advertencias sanas sobre cómo comportarse en este mundo.
Se quejó mucho de la maldad de los tiempos y se le oyó decir en varias ocasiones:
"`¡Ay a ti Inglaterra! ¡Dios te juzgará, oh,
Inglaterra! ¡Grandes plagas están a tus puertas, Inglaterra!`"
También dijo: "`Dios nos ha abandonado.
Somos tontos y cerraremos nuestros ojos;
y no veremos nuestro verdadero interés y felicidad.
Seremos destruidos.`"
Cuando estaba a punto de morir y se despidió de sus parientes, le dijo a William Penn:
"`Hijo, William, si tú y tus amigos se mantienen en su forma sencilla de predicar,
y en su forma sencilla de vivir, acabarán con los sacerdotes hasta el fin del mundo.
Sepúltenme al lado de mi madre, vivan todos en amor, eviten toda forma de mal.
Le pido a Dios que los bendiga a todos,
y Él los bendecirá.`" Así murió el valiente almirante Penn, padre de William Penn,
propietario de Pensilvania; y ahora regreso a otros asuntos.

Dejé a George Fox en Londres,
y puesto que él continuó a los alrededores por un buen tiempo, daré un giró a Bristol,
donde en el año 1682,
se abrió una escena sombría de persecución. Las reuniones
de los llamados Cuáqueros eran perturbadas,
no sólo lastimándolos gravemente y encarcelándolos,
sino también porque eran acosados por personas que
irrumpían en sus casas y cometían toda clase de violencia.
Entre otros, esto fue lo que ocurrió en la casa de un tal Richard Marsh,
un reconocido comerciante de la ciudad.
Porque, para cobrarle la multa que se alegaba contra él,
se le quitó primero un barril de vino valorado en veinte libras y vendido en cuatro.
Esto sucedía a menudo,
pues los bienes que se tomaban de esta manera solían
ser vendidos por menos de la mitad de su valor,
porque la gente honesta no estaba dispuesta a comprarlos,
y por eso se los vendían a cualquiera que ofreciera algo de dinero, por poco que fuera.
Y lo que todavía quedaba de la multa, se le quitaba de nuevo al multado,
como hicieron en este caso; porque se abrieron paso a su despacho,
buscaron el dinero y se llevaron su libro de contabilidad, su diario, su libro de caja,
y otros libros y cuentas, además de muchos bienes domésticos.
Varias de las habitaciones de la casa fueron registradas,
mientras la esposa del mencionado R. Marsh estaba en su cama con un recién nacido.
Los actores principales de estas insolencias eran
el alguacil John Knight y el abogado John Helliar,
quienes, junto con sus compañeros Lugge, Tilley, Casse, Patrick, Hoare y Watkins,
servían como informantes.
Knight y Helliar llegaban frecuentemente con un gran número de
muchachos y chusma ruda a perturbar las reuniones de los Cuáqueros,
y luego los llevaban a las cárceles, que se llenaban tanto,
que se amontonaban casi cincuenta personas en una sola celda.
Esta celda estaba tan sucia, que uno de los concejales, sir Robert Cann,
dijo en una ocasión,
que si él tuviera un perro al que amara no lo pondría
allí. Y aunque el alcalde de la ciudad,
sir Thomas Earl, y algunos magistrados y concejales, a pedido de otros,
se mostraban inclinados a cambiar a los prisioneros a un mejor lugar,
el poder del citado alguacil John Knight era tal que lo impedía.

Las reuniones de otros Protestantes disidentes eran también perturbadas,
pero perdían fuerzas y cedían; mientras que los Cuáqueros permanecían firmes,
sin importar cuán acosados fueran, lo cual,
a menudo era hecho de una manera muy escandalosa.
Porque sus reuniones no sólo eran perturbadas con
frecuencia con ruidos de tambores y violines,
sino que se les daba libertad a los tipos más bajos de cometer todo tipo de groserías,
sin mostrar ninguna consideración por el sexo femenino,
a las que se les arrancaban sus capuchas y bufandas.
Y John Helliar, para darles a los muchachos la señal de que atacaran a las mujeres,
solía decirles: "`¡Ocúpense de sus capuchas y bufandas!`"
Entonces, los muchachos caían sobre ellas,
y tanto las ancianas como los ancianos eran llevados a prisión,
y a empujones y fuertes pellizcos en sus brazos los obligaban
a ir más rápido de lo que podían. En una ocasión,
cuando una joven dijo una palabra contra esta crueldad,
fue jalada del pelo y arrastrada a prisión. De hecho,
incluso los niños pequeños eran golpeados en la cabeza hasta que quedaban mareados,
y luego eran llevados a Bridewell,
donde J. Helliar encargaba al guarda "`conseguir un gato
de nueve colas,`"^
footnote:[Un gato de nueve colas es un instrumento de tortura--un látigo que
consiste en un mango de madera de 30 a 40 cm de largo al que se adjuntan nueve
cuerdas o correas de cuero con una longitud que varía de 40 a 60 cm en la que
cada extremo móvil termina en un nudo a veces dotado de una garra metálica.]
tratando de aterrorizar a los niños haciéndoles creer que serían azotados,
a menos que prometieran no volver a las reuniones.
Pero esto no tuvo éxito,
porque su inaudita maldad no doblegó la constancia de estos niños.

Era tal la rabia diabólica con la que perseguían a este pueblo en Bristol,
que no dejaron una piedra sin remover para afligirlos.
Una vez los encerraron dentro de su casa de reunión con tablas y clavos,
y ahí los mantuvieron por el espacio de seis horas;
lo cual debe haber sido muy difícil para la naturaleza,
ya que también había mujeres presentes de familias no insignificantes,
y entre ellas la viuda del alguacil superior de Lane.
Eran tantos los prisioneros, que al final no había más espacio para ellos en las cárceles.
Muchas familias fueron arruinadas por estos procedimientos,
porque les quitaron sus bienes, no sólo por motivo de las reuniones,
sino porque cuando se creía que alguno tenía buenas propiedades,
le presentaban el juramento de lealtad.
Parece que algunos en el tribunal estaban aún más ofendidos contra los Cuáqueros,
porque en la elección del Parlamento,
algunos de ellos habían votado por los que creían que eran hombres moderados,
y que no favorecían el papismo.
Por tanto, se dijo solapadamente,
que si el señor Penn y el señor Whitehead convencieran a
los Cuáqueros a no votar en la elección del Parlamento,
no habría más persecución contra ellos.

Mientras tanto,
la conducta de los perseguidores en las reuniones era brutal en grado sumo, a tal punto,
que cierta mujer,
al ver que el abogado John Helliar levantaba a su hijo por el pelo de su cabeza,
le preguntó por qué lastimaba así a su hijo,
y por eso ella misma fue maltratada por él. Y por orden del citado Helliar,
una joven fue enviada a la prisión de Bridewell,
porque golpeó en la oreja a un muchacho inescrupuloso que trataba de levantar sus abrigos.
Sin embargo, por defender su modestia, Helliar, este hombre salvaje,
la llamó "`alborotadora y sediciosa,`" porque como ya se ha dicho,
él era líder de muchachos insolentes y descarados,
a quienes a menudo llevaba con él para perturbar las reuniones de los Cuáqueros.
Por su parte,
el alguacil Knight con frecuencia golpeaba con su
bastón muy violentamente a los que estaban reunidos,
y en una ocasión,
maltrató gravemente a un anciano llamado Britton y pellizcó
con violencia a algunas mujeres en sus brazos.
Susannah York, una mujer de edad, fue derribada al piso;
Mary Hooper fue muy rudamente tratada por Helliar,
pues le arrancó la bufanda por la espalda y la empujó y zarandeó tanto,
que por mucho tiempo no pudo moverse.
Mary Page, que estaba embarazada, fue tan violentamente arrastrada de la reunión,
que su vida estuvo en peligro.
Se hizo costumbre con Helliar llamar a los hombres "`villanos,`" y a las mujeres "`prostitutas,
viciosas, carroñas y malditas perras.`"
También les ordenaba a los muchachos rasgar sus bufandas y lanzarles tierra.
Muchos eran testigos de esta furia bestial;
pues estos tratos abominables disgustaban a muchas personas de otras persuasiones religiosas.
Pero parece que estos tipos enfurecidos tenían el estímulo del tribunal,
en el que se atrevían a confiar; porque el alguacil John Knight fue nombrado caballero,
y por lo tanto, se hizo más perverso que antes.
Sucedió en una ocasión, que Helliar, después de perturbar una reunión,
llevó a las mujeres a lo largo de la calle como si fueran ganado,
y cuando una le preguntó si pretendía convertirlas en bestias, respondió:
"`Ustedes son peores que las bestias;
porque las bestias se dejan arrear, pero ustedes no.`"

Este disturbio a las reuniones continuó,
hasta que casi todos los hombres pertenecientes a ellas fueron confinados en prisión.
Algunos de ellos enviaron una petición al alcalde y a los magistrados de la ciudad,
solicitando que se les permitiera estar en celdas más amplias, ya que no sólo su salud,
sino también sus vidas estaban en peligro.
Algunos de dichos magistrados se mostraron inclinados a
permitirles a los prisioneros algo de alivio y libertad.
Pero el poder del alguacil Knight era tal,
que cualquier cosa que dijeran o hicieran ellos, resultaba en vano.
Ahora bien,
el alcalde le informó al alguacil que él deseaba
que todas las condenas fueran hechas abiertamente,
y no en cervecerías y tabernas;
y que todos los bienes confiscados fueran llevados a un almacén público y no a un callejón.
Pero aunque el alcalde _ex officio_ tenía el derecho de mandar al alguacil,
este oficial estaba tan apoyado por los que estaban en el poder,
que no le importaba lo que dijera el alcalde.
En efecto, era tan abusivo,
que sus partidarios empezaron a amenazar al alcalde con que debería dejar de ser parlamentario,
a tal punto, que él se vio forzado a cumplir en algún grado.

Mientras tanto, los estragos y despojos eran tan enormes,
que por lo general se tomaba el doble de la cantidad que sumaba la multa.
Los prisioneros, algunos de los cuales se acostaban sobre el piso, otros en hamacas,
y algunos en una celda fría y abierta,
al estar expuestos al viento y a los maltratos del clima, sufrían grandes dificultades.
El carcelero Isaac Dennis, imaginando que nada podía ser demasiado malo para ellos,
no les mostraba ningún favor, y su esposa no se mostraba menos irracional que él,
de modo que una extorsión se sumaba a otra.
Cuatro médicos de Bristol, a saber: John Griffith, William Turgis, J. Chauncy y T. Bourn,
al ver cuán estrechamente encerrados y amontonados estaban los prisioneros,
entregaron un certificado firmado por ellos en el que declaraban,
que movidos por la compasión y considerando las peligrosas
consecuencias que podía causar un confinamiento tan cerrado,
se veían obligados a certificar que tales condiciones eran
propicias para que se engendraran enfermedades infecciosas,
se pusiera en peligro sus vidas, etc.
Pero no les sirvió de nada,
porque no se consideró que valiera la pena preocuparse por ellos.
De hecho, el carcelero era tan terriblemente malo,
que cuando los prisioneros se quejaron por falta de espacio, le dijo a su criado,
que mientras pudiera cerrar la puerta era suficiente.
Pero a su debido tiempo veremos la angustia y horror que le sobrevinieron.

Después de que la mayoría de los hombres llamados Cuáqueros en Bristol estaban en prisión,
las mujeres que continuaron manteniendo sus reuniones religiosas también fueron apresadas,
y confinadas en tan grande número,
que al final pocas o ninguna quedó libre (salvo los niños
que quedaron con los criados en las casas de sus padres).
El número de prisioneros en este lugar por causa
de su religión sumaba entonces ciento quince,
y algunos de ellos estaban encerrados en Bridewell,
entre quienes estaban Barbara Blaugdon (varias veces mencionada antes) y Catherine Evans,
quien había aprendido en Malta lo que era sufrir un tedioso y duro encarcelamiento.
Es muy notable que los niños menores de dieciséis años realizaran
entonces lo que a sus padres les impedían hacer,
porque estos niños mantuvieron sus reuniones religiosas tanto como estaba en su poder.
Pero aunque ellos no estaban dentro del alcance de la ley,
una vez diecinueve de estos jóvenes fueron tomados y llevados a la casa de corrección,
donde fueron mantenidos por algún tiempo.
Y aunque fueron amenazados con azotarlos si alguna vez regresaban a la reunión,
ellos continuaron valientes sin desmayar,
aunque sufrieron mucho por causa de la chusma perversa.
Pero su celo era tan grande,
que permanecieron firmes a pesar de todo el insulto e insolencia, y así demostraron,
que pese a sus enemigos,
Dios no permitiría que la reunión de los Cuáqueros fuera completamente suprimida,
tal como se intentaba.
La persecución continuó allí hasta el siguiente año,
así como también en otros varios lugares; pues no faltaban informantes,
quienes continuamente estaban al acecho de sus presas, a tal grado, que una vez,
cuando algunos de los llamados Cuáqueros llegaron de otros lugares a comerciar,
y entraron a una posada para refrescarse,
un informante no dudó en declarar bajo juramento
que los Cuáqueros habían realizado una reunión allí.

Pero antes de dejar Bristol, debo dar cuenta de un acto ridículo,
realizado por un tal Erasmus Dole, quien llevaba el nombre de Cuáquero.
Como él había dicho que no tenía escrúpulos en declarar
el contenido del juramento de lealtad,
se planeó que lo recitara ante el secretario y omitiera las palabras que le disgustaban,
y usara otras en su lugar, tales como "`yo declaro`" en lugar de "`yo juro.`"
Así se hizo, y mientras él iba hablando, el carcelero le llevó su mano al libro,
y cuando Erasmus lo había dicho todo,
puso el libro sobre su boca para hacerlo pasar por un beso.
El tribunal pareció satisfecho con esto, y el obispo de Bristol,
al ver estas pantomimas de simio,
le dijo al tribunal que eso no era diferente a prestar el juramento,
de lo cual se gloriaron, como si hubieran obtenido una victoria.
Pero esta fue una lamentable victoria,
pues al ser Erasmus un hombre de vida indisciplinada,
los Cuáqueros no tenía muchos motivos para lamentar la pérdida de tal miembro.
Y al hacerse cada vez más desenfrenado,
con el paso del tiempo se vieron obligados a repudiarlo por su conducta ofensiva.

En Gloucestershire, el pueblo llamado Cuáqueros también estaba bajo grandes sufrimientos,
pues eran encarcelados por celebrar sus reuniones.
Sucedió aquí, que la esposa de un tal John Boy,
estando en una pacífica reunión en Little Badmanton,
por la instigación del sacerdote de la parroquia,
fue sacada a rastras de manera violenta de la reunión por los lacayos del señor Herbert.
Por causa de estos abusos, esta mujer cayó enferma y abortó,
poniéndose en peligro su vida; y a su esposo,
que también fue tomado prisionero en el mismo lugar,
no se le permitió ver a su esposa a pesar de su petición.

En Leicestershire las cosas no eran mejor.
Una tal Elizabeth Hill, que se encontraba en una reunión en Broughton,
fue arrastrada por unos muchachos muy rudos y tan lastimada,
que parecía agotada y casi muerta.
Y mientras yacía en la tierra,
uno de los muchachos le metió un dedo en la boca para comprobar si todavía estaba viva,
y al ver que respiraba dijo: "`¡Vamos por ella de nuevo.
El diablo sigue dentro de ella y nosotros tenemos que exprimirlo!`"
Estos crueles abusos hicieron que una vecina gritara: "`¡Qué,
¿van a matar a la mujer?!`" A lo que uno de los muchachos dijo: "`Qué nos importa;
el señor Cotton nos ordenó hacerlo.`"
"`¿Lo hizo?,`" preguntó la mujer.
"`Sí, en efecto,`" replicaron los muchachos.
"`Entonces,`" dijo ella, "`él debería avergonzarse por ello.`"
De este modo, los muchachos abiertamente dijeron que el párroco Thomas Cotton,
sacerdote de la parroquia, era quien los animaba a esa excesiva maldad.
Y el criado de este sacerdote, cuyo nombre era Thomas Ambrose,
no dudó en decir que nada ahuyentaría a los Cuáqueros sino el fuego o el agua;
y que si la casa fuera suya (es decir, la casa donde se reunían),
la quemaría sobre sus cabezas.
Podrían ser mencionados más ejemplos de esta enorme
perversidad que ocurría en varios lugares,
si no quisiera ser breve.

Estando G. Fox en Londres este año,
por el tiempo de la elección de nuevos alguaciles para la ciudad,
les escribió unas líneas a los candidatos a ese oficio,
que deseaban que sus amigos les dieran sus votos en apoyo a ellos.
Y en la conclusión decía: "`¿Seremos libres de servir y adorar a Dios,
y de guardar Sus mandamientos, si les damos nuestros votos en apoyo a ustedes?
Porque no estamos dispuestos a dar nuestros votos a los que nos vayan a encarcelar,
y perseguir, y saquear nuestros bienes.`"
Los alguaciles de Londres a veces eran enviados con órdenes judiciales,
a perturbar las reuniones de los Cuáqueros,
pero se veía fácilmente que ellos hubieran preferido haber sido liberados de esa comisión;
porque aunque le pedían a George Fox o a otros que predicaban que dejaran de hablar,
aun así ellos y los soldados que a veces los acompañaban,
por lo general se comportaban con moderación,
mostrando suficientemente que no estaban a favor de la persecución
y que lo que hacían era por causa de sus cargos.
De hecho, a veces les impedían a los amigos que entraran a sus reuniones,
pero aunque algunos eran mantenidos fuera, su número seguía creciendo.

Sucedió en una ocasión,
que los alguaciles le impidieron a George Fox entrar en la casa de reunión en Devonshire,
y después de estar un rato en el jardín hasta que se cansó,
uno le dio un banco para que se sentara.
Después de un rato se levantó y predicó, y en su declaración dijo:
"`Ustedes no necesitan venir contra nosotros con espadas y bastones,
porque nosotros somos un pueblo pacífico,
y en nuestros corazones sólo tenemos buena voluntad hacia el rey y los magistrados,
y hacia toda la gente de la tierra.
Y nosotros no nos reuniremos bajo el pretexto de religión,
para conspirar contra el gobierno o para levantar insurrecciones,
sino para adorar en espíritu y en verdad.`"
Cuando dijo lo que pesaba sobre él en ese momento se sentó,
y después de un rato concluyó la reunión con una oración, ante lo cual,
los alguaciles y los soldados, así como también otros, se quitaron sus sombreros.
Y cuando la reunión terminó, un alguacil quitándose su sombrero dijo muy seriamente:
"`El Señor los bendiga;`" y se permitió que todos se fueran sin ser molestados.

Así llegó a su fin este año. Todos los otros disidentes
Protestantes estaban entonces reprimidos;
pues se les impedía ejercer cualquier culto público.
Pero había algunos de estos, que en sus reuniones nocturnas,
oraban que el Señor mantuviera a los Cuáqueros firmes,
para que fueran como un muro alrededor de ellos,
a fin de que otros disidentes no fueran desarraigados.
Sin embargo,
estos mismos Protestantes habían sido anteriormente
muy activos pintando a los Cuáqueros muy mal,
para hacerlos odiosos, pero este pueblo continuó tan valiente y sin desfallecer,
que a algunos de sus perseguidores se les oyó decir:
"`Los Cuáqueros no pueden ser vencidos; el mismo diablo no puede desarraigarlos.`"

En el año1683, la persecución continuó en muchos lugares, y según los cálculos,
parecía que más de setecientos de los llamados Cuáqueros
seguían sufriendo encarcelamiento en Inglaterra.
Podría mencionar varios ejemplos de persecución en Leicestershire,
Northamptonshire y otros lugares, pero para evitar la repetición,
sólo me referiré de nuevo a Bristol, donde la persecución continuó a tal grado,
que si una persona de las llamadas Cuáqueras llegaba a una reunión,
era inmediatamente encarcelada.
Entre esas se encontraba un tal Richard Lindy, un anciano ciego de casi noventa años,
que fue llevado a la cárcel y forzado a sentarse tres noches en una silla,
aunque otros se ofrecieron a pagar su alojamiento,
si le facilitaban un lugar conveniente para acostarse.
Algunos de los prisioneros que eran comerciantes,
de buena gana habrían trabajado en prisión para ganar algo para su sustento,
pero el carcelero Isaac Dennis no les permitía esa libertad.
Otros prisioneros cayeron enfermos de fiebre manchada^
footnote:[La fiebre manchada es una enfermedad bacteriana que
se propaga mediante las picaduras de garrapatas infectadas.],
y algunos murieron por ello; con todo,
esto no suavizó el corazón endurecido del citado carcelero.
Pero al final, un duro golpe cayó del cielo sobre él,
porque a mediados del mes de Octubre se enfermó y una terrible angustia mental
se apoderó de él. Entonces deseó nunca haber visto el interior de la cárcel,
y le pidió a algunos de los Cuáqueros que oraran
por él y que lo perdonaran por lo que había hecho.
A eso ellos le respondieron que sí lo perdonaban,
pero que tenía que pedirle perdón a Dios.
Pero su angustia seguía aumentando, y cuando los médicos ordenaron que lo sangraran,
dijo que ninguna medicina le haría bien, porque su enfermedad era otra cosa,
y que ningún hombre podía hacerle bien,
pues su día de visitación había pasado y no había esperanza
de misericordia de Dios para él. Algunos de los Cuáqueros,
al verlo en esa lamentable condición, le dijeron que ellos querían,
si era la voluntad de Dios, que encontrara un lugar para el arrepentimiento.
También le dijeron que esperaban que su día de visitación no hubiera pasado,
porque tenía un sentido muy completo de su condición. A esto él respondió:
"`Gracias por su buena esperanza, pero no tengo fe para creer.`"
Y añadió: "`La fe es un don de Dios.`"
A pesar de todo lo que se le dijo,
continuó diciendo que su día había pasado y que no había misericordia
para él. Ese gusano que corroe es la culpa de la consciencia,
y en ese estado desesperado continuó un poco más de un mes,
y a finales de Noviembre murió sin ninguna señal visible de perdón;
pero el juicio de ello debemos encomendárselo a Dios.

Aunque el pueblo llamado Cuáqueros era oprimido por los sufrimientos en todo el país,
en general continuó valiente;
y como George Fox no dejaba de escribirles de vez en cuando,
animándolos a la fidelidad y constancia,
varios otros de sus maestros no desistieron de exhortarlos a la perseverancia,
tanto de palabra como por escrito.
Y lo realmente notable era,
que aquellos que viajaban de un lado a otro en el país y
predicaban públicamente en las reuniones de sus amigos,
generalmente mantenían su libertad,
y los informantes a menudo veían frustrados sus planes de atrapar a un predicador.
Encuentro registrado por Charles Marshall, un eminente ministro,
que durante el tiempo en que la persecución era más intensa,
él viajó por la nación y nadie le puso las manos encima, ni lo multó por su predicación,
lo cual fue muy notable, porque al ser un hombre muy celoso,
solía alzar su voz de manera muy poderosa.

William Dewsbury, que entonces había envejecido en su encarcelamiento en Warwick^
footnote:[William Dewsbury estuvo preso por diecinueve años en la cárcel de Warwick.],
les escribió una epístola de consolación a sus sufridos amigos, la cual,
se consideró conveniente reimprimir, y es como sigue:

[.embedded-content-document.epistle]
--

[.salutation]
Queridos hermanos y hermanas,

Escuchen la palabra del Señor. Así dice el Señor:
"`Aunque ahora beben la copa de adversidad, y comen el pan de aflicción,
y son pisoteados como si no fueran dignos de vivir sobre la tierra, aun así,
y a pesar de toda la furia de los hombres, están decididos en la fuerza de Mi Espíritu,
a ser privados para siempre de los dulces goces de esposa, esposo, hijos tiernos, padres,
posesiones externas, libertad y vida,
antes que negar el testimonio de Mi nombre delante de los hijos de los hombres.
Oh, queridos y tiernos hijos,
quienes en este día no aman sus vidas hasta la muerte para
completar un buen testimonio para la gloria de Mi nombre,
dice el Señor Dios; ¡alcen sus cabezas en la luz de Mi pacto y crean en Mi nombre,
porque yo estoy cerca de ustedes, dice el poderoso Dios de seguridad!
No dejen que ningún peso o carga recaiga sobre ustedes,
porque yo seré más que un esposo para sus esposas, y más que una esposa para sus esposos,
o padres para los hijos, o hijos para los padres; sí, seré un esposo para la viuda,
y un padre para los hijos que son privados de sus tiernos padres por causa de Mi nombre.
Yo ensancharé sus límites en la vida de Mi justicia.
Y a ustedes que sufren en verdadera inocencia,
Yo los refrescaré con la profundidad de Mis misericordias; sí,
Yo los guardaré con el ángel de Mi presencia,
y todos los que tramen maldades contra ustedes serán
confundidos delante de la gloria de Mi poder,
con el cual Yo los guardaré y preservaré en la palabra de Mi paciencia y seguridad,
en Mi presencia, dice el Señor Dios.

Por tanto, queridos hijos, que beben el más profundo de los sufrimientos,
no piensen que es demasiado difícil, porque ese es Mi propósito para con todos ustedes,
los que no tienen el ojo vuelto al yo,
sino que buscan únicamente Mi gloria en todo lo que hacen.
Yo los haré más y más honorables en la gloria de Mi vida,
y duplicaré Mis bendiciones sobre ustedes y los suyos, porque he visto su integridad,
y Mi corazón está poderosamente movido en compasión hacia ustedes.
Por tanto, me he levantado hoy por causa de ustedes para declararles, Mi sufrido pueblo,
que ni un cabello de sus cabezas perecerá,
ni serán detenidos en prisión y en desolados agujeros más
tiempo del que he determinado para el bien eterno de ustedes,
y para la gloria de Mi nombre para siempre.
Por tanto, permanezcan fieles en Mi vida, resistan todo mal pensamiento,
o cualquier cosa que los provoque a murmurar o a desear algo que
no sea lo que saben que hará avanzar la gloria de Mi nombre,
y la exaltación de Mi verdad sobre todo lo que se levanta contra ella.
Estén sujetos a la medida de Mi luz y de mi vida,
la cual no permitirá que ninguno busque preeminencia o estima entre los hombres.
Tampoco dejará que el esfuerzo propio ni el egoísmo tengan poder en ninguno,
sino que en verdadera humildad, amor y mansedumbre hará que velen unos sobre otros;
y que el fuerte tome al débil de la mano, para que todos con ternura, en amor,
mansedumbre y temor santo, teman Mi nombre y se sirvan unos a otros;
para que el amor de ustedes sea manifestado hacia Mí, dice el Señor su Dios,
y de los unos hacia los otros en la desnuda sencillez de sus espíritus.
Entonces, haré mi habitación entre ustedes y con ustedes;
y todos sentirán poderosamente dentro y entre ustedes,
Mi terrible y gloriosa presencia moviéndose en la
obra de Mi Espíritu para reconocimiento de Mi nombre,
y para el consuelo de unos y otros.
Yo los coronaré con bendiciones celestiales y con la gloria de Mi poderosa vida;
y alabarán Mi nombre para siempre, porque los he hecho Mi especial tesoro,
y los he tenido por dignos de sufrir por el testimonio de Mi nombre.
Yo iré delante de ustedes a través de todas las aguas y torrentes de aflicción;
compareceré con ustedes ante los consejos de los hijos de los hombres.
Mi poder salvador rodeará a todos los que confían únicamente en Mí,
en sus ardientes y agudas aflicciones, el Señor su Dios.
Por tanto, confíen en Mi nombre, Mis queridos hijos,
y echen toda su ansiedad sobre Mí. Y si algunos de
ustedes sufren gozosamente el saqueo de sus bienes,
Yo les supliré lo que es necesario para ustedes y los suyos;
y si algunos de ustedes sellan sus testimonios con su sangre en la palabra de Mi paciencia,
yo cuidaré sus tiernas viudas, hijos o padres,
por quienes sus almas se han derramado en oraciones ante Mí por el bien de ellos.

Por tanto, escuchen Mi palabra,
que les es anunciada desde el trono de Mi gracia y gloria eterna:
No se regocijen demasiado de que los espíritus se les sometan,
sino arrojen sus coronas delante de Mí,
para que no se halle un espíritu contencioso y egoísta en la familia de Mi pueblo.
Sientan todos el nacimiento inmortal levantarse en la resurrección de Mi vida en ustedes,
el cual hará que el yo no tenga reputación, y que de ese modo,
toda altivez sea abatida y toda arrogancia doblegada en todos,
y que Yo el Señor Dios sea amado, obedecido y exaltado.
Porque Yo estoy tomando, y tomaré, Mi gran poder y exaltaré a los mansos sobre la tierra,
y reinaré sobre toda soberbia de los hijos de los hombres (que
es exaltada por encima de Mi testigo en sus consciencias),
para que así Mis hijos sean traídos desde lejos y
Mis hijas desde los confines de la tierra,
a la vista de todos los pueblos.
Y haré que todos confiesen, en sujeción a Mi poder,
que ustedes son el pueblo amado del Altísimo Dios,
y que son la semilla justa que el Señor ha bendecido.
Ninguna arma forjada contra ustedes prosperará, sino que todas quedarán en nada,
y Mi voluntad será realizada según lo que es declarado aquí,
para el gozo y consuelo eternos de ustedes;
y sabrán con seguridad que la boca del Señor lo ha dicho.`"

La palabra del Señor arriba expresada, vino a mí en la prisión de Warwick,
el 13 del Primer-mes de 1664,
lo que me obligó a enviarla para que fuera leída entre ustedes, queridos,
fieles y sufrientes del Todopoderoso Dios,
en quien sigo siendo el hermano y compañero de ustedes en
la tribulación y reino de paciencia en el Señor Jesucristo.

[.signed-section-signature]
William Desbury

--

Mientras la persecución era intensa en Inglaterra,
se produjo una división entre los llamados Cuáqueros,
que se había originado unos años antes.
Los primeros que introdujeron el conflicto fueron John Wilkinson y John Story,
predicadores entre ellos, que se mostraban descontentos con George Fox,
principalmente por el manejo de los asuntos de la iglesia,
al encontrar que las cosas no siempre iban como ellos querían. Y ya que
George Fox había sido el primer fundador del buen orden entre sus amigos,
también era el principal objetivo de la envidia de los que estaban descontentos.
Ahora bien, debido a que al principio no había reuniones para el orden o la disciplina,
y sin embargo, habían vivido en mutua paz y unidad,
se afirmaba que tales reuniones eran innecesarias,
y que cada uno debía ser guiado por el Espíritu de Dios en su propia mente,
y no ser gobernado por ninguna regla de hombre.
Así pues,
parecía que estos hombres estaban en contra del establecimiento
de algún orden de gobierno en la iglesia.
Ellos estaban particularmente inclinados contra las reuniones de mujeres,
que en ciertos momentos se reunían como diaconisas,
para proveer para las familias pobres y para los enfermos que estaban en necesidad.
Ahora, es cierto,
que en esas reuniones a veces se debatían asuntos
que no eran tan apropiados en todos los aspectos,
porque las mujeres jóvenes también eran admitidas para que vieran
y aprendieran cómo manejaban los asuntos las mujeres serias y ancianas;
y tal vez,
algunas eran demasiado atrevidas entrometiéndose
en asuntos que pertenecen propiamente a los hombres.
No obstante, que entrara un uso incorrecto,
de ninguna manera justifica la abrogación de lo que es realmente útil,
y el hecho de que las mujeres honestas y ancianas cuidaran
de los miembros pobres e indigentes de la iglesia,
era ciertamente loable.
Pero como en las grandes comunidades generalmente se encuentran
algunos que aman gobernar sin ser aptos para ello,
así algunos del pueblo se unieron a John Wilkinson y John Story.
Estos hombres, y varios otros, además de oponerse al buen orden y gobierno de la iglesia,
estaban a favor de reunirse en secreto,
en lugar de asistir a las reuniones públicas y exponerse así a la furia de sus enemigos.
También defendían el pago de los diezmos a los sacerdotes,
en lugar de sufrir el despojo o encarcelamiento por negarse a hacerlo.

A partir de aquí surgió un cisma o ruptura, primero en el norte de Inglaterra,
y algunos que se alejaron bajo el nombre de Separatistas,
comenzaron a reunirse por sí mismos, dejando a sus antiguos amigos,
aunque pretendían estar de acuerdo con ellos en asuntos de doctrina.
A estos Separatistas se unieron varios que no eran estrictos en su manera de vivir,
y por eso no estaban dispuestos a someterse a la sana disciplina de la iglesia,
porque se había hecho muy común entre estas personas decir,
que como todos habían recibido una medida del Espíritu de Dios,
debían considerar a ese líder, sin tener en cuenta las reglas prescritas por los hombres.

Con el paso del tiempo,
William Rogers y Thomas Crisp aparecieron en la prensa contra sus antiguos hermanos,
acusándolos de comportamiento imprudente y actos desconsiderados.
Además, basándose en meros rumores,
publicaron una gran cantidad de falsedades y denunciaron incluso cosas lícitas;
un ejemplo de lo cual apareció,
cuando Rogers (en pésima poesía) los injurió despectivamente
por haberles dado algo a unos pocos predicadores itinerantes,
quienes para no descuidar su ministerio público,
habían dejado de ocuparse debidamente de sus asuntos privados,
aunque dicho suministro no había excedido sus provisiones necesarias.
Rogers continuamente apelaba a los "`tiempos primitivos`" de los amigos,
y para darle cierto peso a lo que afirmaba,
él y sus seguidores publicaron un documento con el nombre de Edward Burrough,
quien llevaba muerto veinte años. Pero George Whitehead y otros,
dieron buenas pruebas de que el autor de ese tan
aplaudido documento había sido el apóstata John Perrot.
Finalmente, la ruptura apareció también en Londres,
donde tampoco faltaban los que estaban descontentos,
quienes al no ser estrictamente conscientes de sus conductas,
preferían vivir sin ninguna restricción. Incluso algunos que eran honestos,
fueron persuadidos a separarse por medio de palabras justas,
pues entre los Separatistas predicaba un tal Charles Harris,
quien era bastante fluido en su discurso y elegante en sus expresiones;
como yo mismo vi y escuché. Sin embargo,
por muy engañosas que fueron las pretensiones de los Separatistas,
y por muchos esfuerzos que hicieron, no pudieron continuar y subsistir firmemente;
sino que al final, decayeron y se desvanecieron como la nieve en los campos,
porque los mejores entre ellos llegaron a ver a tiempo que habían sido engañados,
y los menos honestos se hicieron peor.
De hecho, entre ellos mismos no quedaron exentos de división,
y aunque George Keith (cuya apostasía se mencionará
en su lugar) anduvo merodeando entre ellos,
no obtuvo seguidores allí. Me he preguntado con frecuencia,
cómo pudieron apostatar a tal grado Wilkinson,
Harris y Keith (a quienes conozco personalmente).
Pero no es excesivamente extraño, como algunos puedan pensar,
porque encontramos en el registro que incluso en la iglesia apostólica primitiva,
un tal Alejandro el calderero, e Himeneo y Fileto, que naufragaron en cuanto a la fe,
causaron tal cisma, que se dijo que sus palabras carcomerían como la gangrena.

Este año las reuniones en Londres fueron a menudo perturbadas;
pero los magistrados mismos no parecían aprobarlo,
porque claramente veían que no había nada que temer de los Cuáqueros; sin embargo,
estaban reacios a ofender al partido de la corte que en ese momento prevalecía. En una
ocasión que G. Fox iba a la reunión en Gracechurch-street y los alguaciles se lo impidieron,
puesto de pie en el patio, le predicó a la gente,
pero un alguacil lo derribó y después lo dejaron libre.
En otro momento,
después de estar en la reunión de Savoy y ser llevado ante un magistrado,
un tal Gabriel Shad, un informante,
estaba tan lleno de palabras impertinentes que el magistrado se cansó. Sin embargo,
este magistrado se creyó obligado a hacer algo,
y le preguntó a G. Fox si él había predicado en la reunión.
G+++.+++ Fox respondió esta pregunta cautelosamente diciendo,
que sí había confesado lo que Cristo había hecho
por su alma y había alabado a Dios por ello;
y que él pensaba que podía hacer eso en las calles y en todos los lugares;
y que no se avergonzaba de confesarlo,
ni era contrario a la liturgia de la iglesia de Inglaterra.
A esto el magistrado dijo que las leyes estaban en contra
de las reuniones contrarias a la iglesia de Inglaterra;
y finalmente habló de enviar a G. Fox a la prisión de Newgate,
señalando que haría una orden judicial contra él después de haber cenado.
Pero cuando el alguacil regresó después del servicio vespertino,
el magistrado le dijo que podía dejar ir a G. Fox;
y al día siguiente le indicó a uno de los amigos de G. Fox,
que por un evento fortuito se había visto privado de multarlo.

Así fue liberado G. Fox y permaneció en Londres,
donde se decía que se tramaba un complot contra el rey y el duque de York,
del que se afirmaba que el duque de Monmouth era la cabeza.
Este plan, cualquiera que fuera, costó la vida de varias personas,
entre quienes estaba el conde de Essex, quien desafortunadamente pereció en la Torre,
y lord Russel, al que se le obligó inclinarse ante el hacha.

[.offset]
Ahora bien, como la persecución continuó con cierta pretensión de justicia,
los llamados Cuáqueros le redactaron el siguiente escrito al rey:

[.embedded-content-document.letter]
--

[.letter-heading]
Al rey

[.letter-heading]
El humilde escrito del pueblo comúnmente llamado Cuáqueros

[.salutation]
Oh, rey,

Que el Rey de reyes y Señor de toda la tierra,
incline tu corazón a lo que es justo y misericordioso ante Su vista,
y hagas claras y equitativas distinciones,
para que el inocente no sufra en ningún caso por el culpable;
para que eso redunde en tu honor y seguridad, y en consuelo para tus súbditos pacíficos.

Nuestra inocencia, amor y buena voluntad hacia tu persona y gobierno,
que Dios te ha encomendado, nos anima en este nuestro humilde escrito y solicitud.

Considerando que el complot contra el rey y su hermano el duque de York, etc.,
se convierte en una oportunidad para perseguir a
muchos de nosotros por nuestras reuniones religiosas,
incluso más severamente que antes,
nosotros solemnemente declaramos que es sabido por la Divina Majestad,
por la Sabiduría que todo lo ve,
por la que los reyes reinan y los príncipes decretan justicia, que nuestros múltiples,
extremos y continuos sufrimientos (que sólo son de orden
religioso) no nos han motivado o provocado a desear,
y mucho menos a conspirar, para hacerte el menor daño a ti o a tu gobierno,
o a la persona de tu hermano el duque de York.
Estamos limpios ante los ojos del Señor, de los ángeles y de los hombres,
de todo complot infernal, conspiración traidora,
y de todo plan y esfuerzo asesinos contra el rey,
su hermano o cualquier persona sobre la tierra,
sabiendo que estas son obras del diablo y de las tinieblas,
y habiendo aprendido todo lo contrario de Cristo
Jesús nuestro Señor. Porque hemos sido enseñados,
por Su luz y gracia en nuestros corazones, a no defender por la fuerza,
y mucho menos a vengarnos por los agravios hechos contra nosotros,
sino a encomendar la causa a Aquel que juzga con justicia,
como seguidores pacíficos de nuestro Salvador y Redentor,
en Su paciente ejemplo y sufrimientos, quien es el Príncipe de Paz.

Oh rey, además declaramos,
que Dios Todopoderoso nos ha enseñado y encargado como Su ordenanza,
reconocer y realmente obedecer a la magistratura en todo lo que
no sea contrario a Su ley y luz de nuestras consciencias,
lo cual, ciertamente está en concordancia con las Sagradas Escrituras,
y no admite ninguna acción inmoral u ofensiva.
E incluso, cuando por la ternura de consciencia no podamos conformarnos,
es nuestro deber sufrir pacientemente, y no rebelarnos, ni buscar venganza.
Esperamos, por Su divina gracia,
humillarnos siempre en nuestra conducta como Cristianos pacíficos bajo el gobierno civil;
y así como sinceramente y con reverencia confesamos el Divino poder y la Providencia
en tu restauración y en la preservación de tu persona hasta ahora,
así son nuestras oraciones y súplicas al Todopoderoso por tu futura seguridad y paz,
y para que en un recuerdo agradecido de las grandes misericordias de Dios para contigo,
te veas obligado a mostrar misericordia y alivies a los
oprimidos de las inmerecidas aflicciones y persecuciones,
bajo las que un gran número de nosotros sufren incluso hasta hoy,
en nuestras personas y patrimonios.
Nuestros sufrimientos no se deben únicamente a las
leyes que se han decretado contra nosotros,
sino también a las leyes que nunca fueron pensadas contra nosotros;
y (lo que es aún más extremo) recientemente se nos han infligido
y se nos siguen infligiendo varias severidades,
para las cuales ninguna petición de derecho ha sido o puede ser alegado.
Algunas cárceles están tan llenas ahora, que carecen de aire,
y muchas personas inocentes son retenidas bajo extrema angustia,
sin consideración de la edad, sexo o condición,
con las pérdidas de algunas vidas y el aparente peligro de muchas más. Muchas casas,
tiendas, graneros y campos han sido saqueados y limpiados de bienes, grano y ganado,
lo cual tiende a desanimar mucho el comercio y la agricultura,
y a empobrecer a un gran número de personas tranquilas y trabajadoras;
y esto por ninguna otra causa,
que la de la adoración y ejercicio religioso de sus tiernas
consciencias hacia el Todopoderoso Dios que las hizo,
quien es el soberano Señor de todo, y el Rey en las consciencias de los hombres.

Por lo tanto, humildemente te pedimos, oh, rey, que en justicia soberana,
caridad Cristiana y compasión,
abras las puertas de nuestra prisión y nos quites las ataduras,
dondequiera que estén oprimidos los inocentes en
tu tierra--hombres y mujeres que temen a Dios,
y en sus conductas honran verdaderamente al rey.
No permitas que la ruina de los que son tranquilos en la tierra,
viudas y huérfanos por sus consciencias pacíficas,
esté a la puerta de un príncipe que profesa la tierna y compasiva religión de Cristo.

--

Este escrito le fue presentado al rey en Windsor,
el 8 del mes llamado Agosto de este año, por George Whitehead, Alexander Parker,
Gilbert Latey y Francis Camfield, en nombre de ellos mismos y de sus amigos.
Le fue leído al rey y a su hermano el duque de York,
que en ese momento estaba presente junto con algunos otros,
pero no se produjo ningún alivio considerable.
Al parecer, el rey Carlos no iba a ser el instrumento para aliviar sus sufrimientos,
y aunque este príncipe no era de corazón duro por naturaleza,
había algunos que podían persuadirlo a la severidad.

Encontré que por este tiempo, Gabriel Shad, mencionado anteriormente,
que se había dedicado a servir como informante contra los Cuáqueros,
y últimamente había informado contra G. Fox,
estaba confinado en la prisión de Newgate en Londres,
por robarle unos bienes a un tal William Leman por valor de trescientas libras.
Pero aunque había sido hallado culpable de un delito en Old Bailey,
tenía tales amigos en el poder, que fue liberado de la horca,
y tras obtener el beneficio del clero, fue liberado con sólo quemarlo en la mano.
Tan infames eran estos informantes,
que las personas honestas despreciaban participar en una obra tan baja y abominable.

Este año la princesa Ana, hija del duque de York,
se casó con el príncipe George de Dinamarca.
El duque de Monmouth,^
footnote:[James Scott, primer duque de Monmouth (1649-1685),
fue el hijo ilegítimo del rey Carlos II y su amante Lucy Walter.]
que había caído en desgracia, volvió a gozar de favor,
pues su padre el rey lo amaba en verdad;
aunque se resistía a declararlo su hijo legítimo,
como muchos grandes hombres querían que hiciera,
en preferencia a su hermano el duque de York,
por lo que el rey persistió en su declaración,
de que nunca había estado casado con la madre de Monmouth.

El año siguiente, 1684,
G+++.+++ Fox y Alexander Parker llegaron a Holanda para visitar a sus amigos ahí;
y después de cierta estadía, regresaron a su país nativo.

Este año murió Thomas Stordy de Moorhouse, en Cumberland,
un caballero que veinte años antes había sido condenado con la sentencia de premunire,
porque por causa de su consciencia no había podido jurar.
Debido a esto, el alguacil John Lowther confiscó sus bienes patrimoniales y personales,
para uso del rey, y lo mantuvo prisionero once o doce años,
hasta que finalmente fue liberado por la declaración del rey en 1673,
y su patrimonio restaurado.
Después de esto,
sufrió grandes multas y el despojo de sus bienes por asistir a las reuniones,
y más tarde fue procesado por la ley de '`veinte libras
al mes,`' por no asistir a la adoración de ellos.
Por esta acusación permaneció preso varios años, hasta que murió en Diciembre,
habiendo estado dispuesto a perderlo todo por Cristo,
antes que ser desobediente a Él. Este Thomas Stordy
también les dispensó a los dueños de tierra,
y a sus herederos para siempre, una apropiación^
footnote:[_Apropiación_ (término del derecho eclesiástico inglés) era la entrega
de las rentas de los diezmos de un beneficio eclesiástico a un laico.]
de diez libras al año, beneficio que había recibido de su padre y de su abuelo,
mostrando que estaba conscientemente opuesto a recibir y a pagar diezmos.
No mucho antes de su deceso, exhortó a los que habían ido a visitarlo a seguir fieles:
"`Porque,`" les dijo, "`si continúan fieles al Señor mientras vivan en este mundo,
Él los recompensará, así como me recompensa a mí ahora, con Su dulce paz.`"
Así partió piadosamente Thomas Stordy de esta vida,
demostrando que era realmente un caballero,
cuya principal nobleza consistía en la virtud.
Yo podría mencionar algunos otros ejemplos o casos de persecución,
pero para llegar más rápido a la conclusión,
no entretendré al lector con el relato de ello.

Thomas Briggs, quien había sufrido mucho también,
al ser uno de los primeros predicadores entre los Cuáqueros,
ahora era un anciano y estaba débil.
Por este tiempo,
le escribió una carta a G. Fox en la que ponía de manifiesto su perseverancia a la piedad;
y no mucho después, hacia principios del año 1685, murió.

Por esta época,
el rey sufrió violentas convulsiones y también murió el mes llamado Febrero.
Al quedar vacante el trono por su muerte,
fue ocupado de nuevo por su hermano James II que le sucedió,
y que fue proclamado rey el mismo día. No puedo dejar de apuntar,
que la persecución continuó hasta la muerte del rey Carlos,
y que hasta ese mismo instante era muy intensa.
Tras salir del escenario, muchos parecían temer que se avecinaban peores tiempos,
y que la quema de herejes volvería a estar en boga, como en épocas anteriores.
Sin embargo, había algunos que creían que era probable que llegara la tranquilidad;
y el tiempo mostró que no se equivocaron.
