== Capítulo XXI

[.section-date]
1685--1688

[.chapter-synopsis]
* Petición al Parlamento de libertad de consciencia
* Solicitud al Rey
* Declaración de los sufrimientos de los Amigos
* Proclamación del rey favoreciendo a los disidentes
* Alto a la persecución
* Crueldad de un Cuáquero apóstata
* Duque de Monmouth
* Juez Jeffries
* Los magistrados de Emden invitan a los Amigos a establecerse en esa ciudad
* Correspondencia posterior
* El rey pone en libertad a la mayoría de los Amigos encarcelados
* Muerte de David Barclay
* Muerte de Anne Whitehead
* Libertad de consciencia concedida
* Cartas al rey James
* Orden del rey de eximir a los Amigos de prestar juramentos
* Transgresiones del rey a favor del papado
* Encarcelamiento de los obispos
* Carta de la Junta Anual
* Firmeza y fidelidad de Theophila Townsend
* Sufrimiento y liberación de Theophilus Green
* William Penn y el rey James
* Convencimiento, sufrimientos y muerte de William Dewsbury
* William, príncipe de Orange, desembarca en Inglaterra.

El rey James no llevaba mucho tiempo al mando del gobierno,
cuando los disidentes le solicitaron libertad de culto,
y entre ellos estaban también los Cuáqueros, que hicieron la siguiente petición:

[.embedded-content-document.letter]
--

Al rey y ambas cámaras del Parlamento:
Humildemente se presenta la sufrida condición del pacífico pueblo llamado Cuáqueros,
sólo por una consciencia tierna hacia el Todopoderoso Dios.

Se informa, que últimamente más de mil quinientos del citado pueblo,
tanto hombres como mujeres, han estado detenidos como prisioneros en Inglaterra,
y parte de ellos en Gales (algunos de los cuales
han sido liberados por los jueces desde entonces,
y otros, por la muerte a través de largos y tediosos encarcelamientos),
de modo que según las últimas cuentas,
ahora quedan unos mil trescientos ochenta y tres prisioneros;
doscientas de las cuales son mujeres.
Muchos de ellos, tanto hombres como mujeres, están bajo la sentencia de premunire,
y más de trescientos están cerca de recibirla; no por negar su deber,
ni por rechazar la sustancia del juramento mismo de lealtad, sino únicamente,
porque no se atreven a jurar.
Muchos están bajo orden de excomunión y multas para el rey, o bajo la ley de destierro,
además de trescientos veinte que han muerto en prisión desde el año 1660,
dejando viudas y huérfanos en angustia y dolor.
Los últimos dos severos inviernos,
y el estrecho confinamiento de un gran número de personas en muchas cárceles,
las encaminaron inevitablemente hacia su destrucción,
ya que su salud se vio evidentemente dañada.

Aquí en Londres, la cárcel de Newgate ha estado una y otra vez abarrotada,
durante los dos últimos años (algunas veces con casi veinte personas en un solo aposento),
en perjuicio de la salud de los prisioneros; y últimamente,
varios pobres comerciantes inocentes que se estaban
quedando sin aliento por el frío de la prisión,
fueron sacados enfermos con una fiebre maligna y murieron unos pocos días después.

Además de estas constantes y destructivas privaciones sobre
las personas de los hombres y mujeres antes mencionados,
también se han producido con frecuencia (y todavía se producen) grandes violencias,
terribles angustias y lamentables estragos y saqueos sobre nuestros bienes y propiedades,
tanto en esta ciudad de Londres, sus alrededores, y otras partes de la nación,
por parte de un grupo de informantes ociosos, desmedidos e inmisericordes,
que nos acusan basados en la ley de conventículos.
Muchos de nuestro pueblo han sido condenados y multados,
sin haber sido citados o escuchados en su propia defensa.
Todo esto ha llevado a comerciantes, agricultores y granjeros a la ruina,
y a muchas familias trabajadoras al empobrecimiento,
sin que se muestre compasión alguna hacia las viudas, huérfanos o desolados.
A algunos ni siquiera les han dejado una cama para descansar; a otros,
no les han dejado ganado para labrar la tierra, ni trigo para pan,
ni semilla para sembrar, ni herramientas para trabajar.
Los mencionados informantes y alguaciles en algunos lugares,
son ultrajantes y excesivos en sus angustias y confiscaciones,
irrumpiendo en casas y haciendo grandes destrozos y saqueos.
Y todas estas y otras crueldades son hechas contra nosotros
bajo el pretexto de que le sirven al rey y a la iglesia,
para forzarnos a una conformidad sin convicción interna,
o satisfacción de nuestras consciencias tiernas,
en lo que concierne a nuestra paz con Dios.

[.offset]
Los estatutos por los que nosotros, el citado pueblo, sufrimos prisión,
angustia y saqueo son los siguientes:

[.syllogism]
* Año quinto de Elizabeth, capítulo 23. __De Excommunicato Capiendo.__
* Año 23 de Elizabeth, capítulo 1, por veinte libras al mes.
* Año 29 de Elizabeth, capítulo 6, por continuar.
* Año 35 de Elizabeth, capítulo 1, por renunciar al reino bajo pena de muerte.
* Año 1 de Elizabeth, capítulo 2, por doce peniques el Domingo.
* Año 3 del rey James I, capítulo 4, por __Premunire,__ encarcelamiento de por vida y confiscación de propiedades.
* Año 13 y 14 del rey Carlos II contra los Cuáqueros, etc., por destierro.
* Año 22 del rey Carlos II, capítulo 1, contra conventículos sediciosos.
* Año 17 del rey Carlos II, capítulo 2, contra los no conformistas.
* Año 27 del rey Enrique VIII, capítulo 20, algunos sufren inmediatamente.

Basados en el derecho común,
por las alegadas e incriminatorias acusaciones contra
nuestras asambleas religiosas pacíficas,
calificadas como disturbios, quebrantamientos de la paz, etc.,
muchos hombres y mujeres han sido multados, encarcelados y detenidos por no pagar,
algunos incluso hasta la muerte.
Tomen por ejemplo la ciudad de Bristol,
donde por varios años un gran número de personas han estado confinadas y hacinadas
en la cárcel (en su mayoría más de cien a la vez) bajo tales pretextos,
de las cuales unas setenta son mujeres, muchas de ellas ancianas.
Y en la ciudad de Norwich, en los años 1682 y 1683,
cerca de setenta fueron mantenidas en prisión,
cuarenta y cinco de las cuales fueron puestas en
huecos y mazmorras por muchas semanas seguidas,
donde sufrieron grandes penurias.
Así pues,
nuestras reuniones pacíficas unas veces son multadas basados en la ley de conventículos,
considerándolas ejercicios religiosos ilegales,
y otras veces son perseguidas basados en el derecho común, calificándolas de revoltosas,
etc., cuando nunca se ha podido probar nada de esa naturaleza contra ellas,
al no haberse cometido,
amenazado o pretendido ninguna violencia o daño contra la persona o propiedad de nadie.

Los largos y tediosos encarcelamientos se deben principalmente
a los mandatos judiciales de __excommunicatu capiendo__^
footnote:[Un escrito que ordena el encarcelamiento de una
persona excomulgada hasta que se someta a la iglesia nacional.],
sentencia de premunire, o multas que se dice que son para el rey.

Los grandes despojos y excesivas aflicciones y decomisos
se deben principalmente a la ley de conventículos,
a la ley de multas de veinte libras al mes,
a la de dos terceras partes de las propiedades, y a la orden de __qui tam__.^
footnote:[Un mandato judicial __qui tam__,
es cuando una parte privada presenta una demanda
contra un individuo en nombre del rey o del gobierno.]
En algunos condados muchos han sufrido decomisos y aflicciones desde hace ocho años,
y en varios se han emitido órdenes para decomisos adicionales por veinte libras al mes,
por un valor de muchos miles de libras, embargándose a veces once meses de una sola vez,
y haciéndose venta de todos los bienes y posesiones (dentro y fuera de sus casas),
como los bienes domésticos, camas, artículos de las tiendas, ganado, etc.
Las acciones judiciales continúan y en varios condados se han incrementado mucho,
de modo que varios que han empleado por mucho tiempo
a cientos de familias pobres en fábricas,
y pagado considerables impuestos al rey,
se encuentran muy incapacitados por estas órdenes y embargos,
así como también por largos encarcelamientos.
Muchos tejedores en Plymouth,
que mantenían a más de quinientas personas pobres trabajando,
están imposibilitados por encarcelamiento.
Hay muchos en el condado de Suffolk que sufren largos encarcelamientos,
y están condenados con la sentencia de premunire,
uno de los cuales empleaba al menos a doscientas personas
pobres en la fabricación de lana cuando él estaba en libertad.
Omitiendo otros ejemplos, para no parecer demasiado tediosos,
estos pueden evidenciar cuán destructivas son tales
severidades para el comercio y la industria,
y de ruina para muchas familias pobres.

Por medio de la ley de conventículos,
durante estos dos últimos años muchos en la ciudad de Londres y sus alrededores,
han sido tremendamente oprimidos,
perjudicados y despojados de sus propiedades y negocios,
por las numerosas condenas y órdenes judiciales contra ellos en su ausencia,
simplemente por la información jurada por informantes,
varios de los cuales son mujeres impúdicas que juran por su parte de las multas y decomisos,
al estar sus esposos encarcelados por deudas debido a sus propias extravagancias.
Las órdenes judiciales comúnmente dadas para irrumpir y entrar en casas,
son ejecutadas con rigor y gran saqueo, sin perdonar viudas, huérfanos,
o familias pobres que se sostienen con sus cuidados y trabajos diarios,
y a menudo no les dejan ni siquiera una cama donde acostarse.
Las multas por las órdenes judiciales de un juez ascienden a varios cientos de libras;
con frecuencia, diez libras por orden, y dos órdenes de veinte libras,
ejecutadas a la vez sobre una misma persona.
Tres órdenes por un monto de sesenta libras fueron ejecutadas a la vez por otro juez,
sobre otra persona, y todos sus bienes fueron sacados en casi diez carretas.
Cinco órdenes por el monto de cincuenta libras, fueron ejecutadas a la vez sobre otra,
etc., además de lo que hemos sufrido por otros de la misma clase.
Y en este destructivo curso, los informantes reciben aliento y se les permite continuar,
arruinando a muchas familias en sus oficios y medios de vida;
y varios se desaniman y quedan tan imposibilitados que son
forzados a abandonar sus tiendas y oficios.

Estos informantes son comúnmente aceptados como testigos creíbles, sin embargo,
claramente juran para su propio beneficio y ganancia,
y a menudo en ausencia de las personas que están siendo procesadas.
Esto nos parece un procedimiento muy duro e indebido,
e inconsistente con el derecho común o justicia.
Ahora bien, si esto es equitativo o justo, les pedimos que por favor lo consideren,
ustedes que son hombres sabios y juiciosos;
y si es para honor del rey e interés del pueblo,
que se anime o se permita que vagabundos,
borrachos e informantes libertinos continúen arruinando el comercio,
la agricultura y a las familias,
u ordenándoles y amenazando a jueces de paz con la pérdida de cien libras,
si no dictan condenas o emiten órdenes judiciales sobre
la base de su información y de sus declaraciones dudosas,
frecuentemente en ausencia del acusado.

Tengan a bien tomar en sus manos nuestro caso,
y hacer con nosotros como desearían que se haga con ustedes.
Porque así como ustedes no quieren ser oprimidos ni destruidos en sus personas o patrimonios,
ni tener sus propiedades invadidas, ni sus posteridades arruinadas,
por servir y adorar al Todopoderoso Dios según sus persuasiones y consciencias, sino que,
sin ninguna duda, desean disfrutar de la libertad de ello,
les rogamos que permitan la misma libertad a nuestras tiernas consciencias,
que viven pacíficamente bajo su gobierno.
Y les pedimos que tengan a bien anular la llamada ley de conventículos,
para detener a esos informantes devoradores, y quitar todas las leyes sanguinarias,
y los castigos corporales y monetarios, por el mero hecho de la religión y consciencia.
No permitan que la ruina y el llanto de las viudas,
huérfanos y familias inocentes recaigan sobre esta nación, ni a la puerta de ustedes,
quienes no sólo tienen una gran responsabilidad depositada
sobre ustedes para la prosperidad y bien de toda la nación,
sino que también profesan el Cristianismo,
la tierna religión de nuestro Señor Jesucristo.

Y a pesar de toda esta opresión sostenida por tanto tiempo, nosotros,
el mencionado pueblo sufriente,
solemnemente profesamos y declaramos ante los ojos del Dios que todo lo ve,
que es el escudriñador de los corazones,
que así como nosotros nunca hemos sido hallados en ningún plan sedicioso o de traición
(al ser esto completamente contrario a nuestro principio y profesión Cristiana),
asimismo,
no tenemos más que buena voluntad y verdadero afecto
Cristiano hacia el rey y hacia el gobierno,
y sinceramente deseamos la seguridad,
prosperidad y acuerdo en misericordia y verdad del rey y de ustedes,
para el bien de todo el reino.

Habiéndoles dado así un resumen del estado de nuestro
sufrido caso de acuerdo con cuestiones de hecho,
sin reflexiones personales, nosotros, en humildad Cristiana y por Cristo,
les rogamos que consideren tierna y caritativamente los argumentos,
y encuentren alguna manera eficaz para nuestro alivio de las prisiones, saqueos y ruina.

--

[.offset]
También se presentó la siguiente solicitud.

[.embedded-content-document.letter]
--

[.letter-heading]
Al Rey James II

[.salutation]
Humilde solicitud del pueblo llamado Cuáqueros.

Considerando que le ha placido al Dios Todopoderoso, por quien reinan los reyes,
quitar al difunto rey Carlos II y preservarte pacíficamente a ti para sucederlo,
nosotros tus súbditos, deseamos de corazón que el Dador de todo bien y don perfecto,
se agrade en dotarte de sabiduría y misericordia en el uso de tu gran poder,
para Su gloria, honor del rey y bien del reino.
Y al ser nuestra sincera resolución,
en concordancia con nuestros principios y conducta pacíficos,
mediante la ayuda del Todopoderoso Dios,
vivir pacífica y honestamente como corresponde a verdaderos
y fieles súbditos bajo el gobierno del rey,
y a un pueblo consciente que verdaderamente teme y sirve a Dios,
humildemente esperamos que la ternura del rey se manifieste
y se extienda con su poder para expresar lo mismo,
encomendando a su generosa clemencia el caso de nuestros sufrientes amigos aquí adjuntos.

--

La lista anexada, con la petición anteriormente mencionada al rey y al Parlamento,
no fue completamente ineficaz,
ya que entonces se hablaba mucho de la libertad de consciencia.
Muchos parecían esperar que una gran concesión de
libertad sería publicada de manera impresa,
y se convirtió en un dicho común, "`la libertad de consciencia está bajo presión`",
lo cual al tener un significado ambiguo,^
footnote:[En inglés.]
a veces daba lugar a la broma.
Pero muchos miembros de la iglesia Episcopal estaban tan fuertemente
inclinados a negarles esa libertad a otros Protestantes,
que se informó que algunos en autoridad le habían prometido al
rey dar su voto a favor de la libertad de consciencia a los papistas,
siempre y cuando no se le concediera a otros disidentes.
Sin embargo, la petición de los Cuáqueros arriba mencionada tuvo tal efecto,
que el rey decidió aliviar la carga de su opresión mediante un perdón;
porque su poder llegaba hasta ahí. Pero la abrogación de leyes
no podía ser hecha sin el consentimiento del Parlamento,
el cual estaba cada vez más preocupado de que por la derogación de esas leyes,
los papistas (que entonces tenían un rey de su propia
persuasión) se hicieran demasiado poderosos.
Mientras tanto, el rey publicó la siguiente proclama:

[.embedded-content-document.legal]
--

[.signed-section-context-open]
James R.

[.salutation]
A todos los arzobispos y obispos, a sus cancilleres y comisionados,
y a todos los archidiáconos y a sus oficiales,
y a todos los otros ordinarios y personas que ejercen la jurisdicción eclesiástica.

Considerando que nuestro amadísimo hermano, el difunto rey,
les había manifestado a sus fiscales generales su intención de perdonar a aquellos
de sus súbditos que habían sufrido en la última rebelión por su lealtad,
o cuyos padres o parientes cercanos habían sufrido en la última rebelión por dicha causa,
o habían testificado su lealtad y afecto al gobierno, y sin embargo, eran procesados,
acusados o condenados por no prestar o negarse a
prestar los juramentos de lealtad y supremacía,
o habían sido procesados basados en cualquier ley
o cualquier pena por no asistir a la iglesia,
o no recibir el sacramento:

En cumplimiento de la mencionada voluntad de nuestro amadísimo hermano,
y en consideración a los sufrimientos de dichas personas,
es nuestra voluntad y complacencia ahora,
que ustedes hagan que todos los procedimientos contra las
mencionadas personas sean completamente suspendidos y anulados.
Y si algunas de estas personas son decretadas o declaradas excomulgadas,
o han sido certificadas, o están en prisión bajo la ley de __excommunicato capiendo__,
por alguna de las causas anteriormente dichas,
es nuestra voluntad que las absuelvan y hagan que
a tales personas se les levanten los cargos,
sean liberadas, o puestas en libertad, y que en lo sucesivo,
no se lleve a cabo ningún procedimiento en ningún tribunal contra
ninguna de dichas personas por ninguna de las causas mencionadas,
hasta que nuestra voluntad se manifieste de nuevo.

Dado en nuestra Corte de Whitehall, este 18 de Abril de 1685,
en el primer año de nuestro reinado.

[.signed-section-closing]
Por orden de su majestad,

[.signed-section-signature]
Sunderland

--

Este fue el primer paso del rey hacia la libertad de consciencia,
tanto para los papistas como también para las personas de otras persuasiones,
el cual le puso un freno efectivo a la persecución,
y el poder de los informantes quedó así muy dañado.
Asimismo, los perseguidos Cuáqueros tuvieron algún descanso,
porque la persecución no sólo cesó, sino que muchos,
que por causa de la religión había permanecido en prisión por varios años,
obtuvieron su libertad gracias a un príncipe papista,
algo que no se había podido conseguir de su hermano protestante,
el rey Carlos II. Ahora bien, muchos de los fieros perseguidores cayeron en vergüenza,
algunos en pobreza y otros tuvieron un fin miserable,
de lo cual se podrían presentar no pocos ejemplos, si tuviera en mente extenderme;
no obstante, sólo mencionaré uno o dos.

Un tal Edward Davis, profesó ser Cuáquero en algún momento de su vida,
pero al no ser sincero, halló que ese camino era demasiado estrecho para él,
y dejó a sus amigos; y después de convertirse en guarda de la cárcel de Ivelchester,
en Somersetshire, los acosó muy duramente.
Por pura malicia les puso grilletes de hierro a algunos,
y una vez le dijo a John Whiting cuando lo esposaba a otro prisionero,
que esos cerrojos no serían quitados ni aunque se los comieran los piojos.
Y su camarada Joseph Newberry no era mucho mejor,
porque cuando uno le dijo que sus manos se hinchaban por causa de los grilletes,
le dijo que no le importaba si sus corazones se hinchaban
también. Y cuando un tal John Dando,
le preguntó en una ocasión a Edward Davis qué pensaba qué sería de él cuando muriera,
respondió: "`Yo sé qué será de mí entonces, y por tanto,
aprovecharé al máximo mi tiempo ahora.`"
También señaló que sabía por dónde había salido y por dónde debía regresar,
si alguna vez iba a ser salvo; pero que si decidía nunca regresar,
entonces sería tan perverso como pudiera.
¡Realmente un dicho muy peligroso!
Como si la puerta de misericordia siempre estuviera abierta para el hombre,
y el día de visitación del amor de Dios nunca pasara sobre su cabeza,
aunque persevere en rebelión. Pero este Davis llegó a un estado muy lamentable,
de modo que cayó en la pobreza, y él mismo fue encarcelado por deudas,
de lo cual hablaré más adelante.
Y Joseph Newberry cayó en una condición triste,
pues se apoderó de él una parálisis severa, y sin embargo,
no dejó de maldecir ni de blasfemar ni de hablar del diablo de forma espantosa.
Y al permanecer por largo tiempo en cama, la carne de su espalda empezó a pudrirse;
y el que anteriormente había dicho,
con respecto a los prisioneros que estaban atados por las manos,
que no le importaba si sus corazones se hinchaban, ahora le dolía tanto la lengua,
que se le hinchó hasta que se le salió de la boca y se puso negra,
y murió miserablemente el 10 de Diciembre.
Así castiga Dios algunas veces al perverso, incluso en esta vida.
Y aunque los perseguidores no siempre llegaron a tan miserables finales,
muchos de ellos cayeron en la pobreza,
y otros estaban descontentos porque veían que aquellos a quienes habían perseguido cruelmente,
ahora gozaban de una libertad imperturbable,
porque el rey que estaba en ese momento en el trono,
continuaba dándoles libertad a los que habían sido oprimidos por religión.

Pero antes de decir más sobre esto,
no puedo dejar de mencionar algo del complot del infeliz duque de Monmouth,
quien tras la muerte de su padre el rey Carlos II, se fue a Bruselas.
Después de pasar de ahí a Holanda,
fue instigado tan vigorosamente por algunos extremistas ingleses,
que tras recibir dinero y ayuda de varios que estaban descontentos,
emitió una fiera declaración contra el rey James (que fue escrita,
según se me ha dicho de manera creíble, por el violento Robert Ferguson^
footnote:[Robert Ferguson (1637-1714) fue un ministro Presbiteriano escocés,
conspirador contra Carlos II y James II,
y un célebre escritor de violentos panfletos contra el gobierno.]),
y se fue a Inglaterra con tres buques de guerra y algunas tropas.
Cuando Monmouth desembarcó con sus fuerzas al oeste de Inglaterra, cerca de Lime,
fue derrotado por las tropas del rey y tomado prisionero,
habiendo sido traicionado por cierto señor, que así obtuvo el perdón para sí mismo.
Robert Ferguson, sin embargo, escapó por medio de un astuto artificio,
gritando a lo largo del camino por el que iba galopando a caballo:
"`¡Los rebeldes han sido derrotados! ¡Los rebeldes han sido derrotados!,`"
como si hubiera sido un mensajero enviado con ese encargo.
Así escapó, y después de llegar a Holanda, les contó a sus conocidos este astuto truco.
Monmouth, que fue declarado culpable de alta traición por una "`ley de sanciones`"^
footnote:[Legislación que podía imponer la pena de muerte sin juicio ni audiencia judicial.],
fue decapitado dos o tres días después de su llegada a Londres.
No obstante, considero digno de mencionar,
que él recibió serenamente la noticia de la orden de muerte emitida,
y que en el cadalso en Tower-hill, les dijo a los obispos que lo acompañaban:
"`Si no hubiera experimentado verdadero arrepentimiento,
no me sentiría tan libre del temor a la muerte.`"
Y cuando se le objetó que no debía confiar demasiado en eso,
dado que podría ser el efecto de un coraje natural, dijo: "`No,
no le atribuyo esto a mi naturaleza, porque naturalmente soy más temeroso que otros;
pero ahora soy libre del temor,
porque siento algo en mí que me da seguridad de que iré a Dios.`"
El verdugo le dio varios golpes con el hacha antes de que
su cabeza fuera finalmente separada de su cuerpo.
Después, algunos eclesiásticos dijeron que había muerto como un fanático,
porque no se había mostrado muy dispuesto a recibir los servicios de ellos,
y por decir que algo dentro de él le daba seguridad de que iría a Dios.
Pero como quiera que fuera,
me parece muy probable que él haya sido un verdadero penitente,
y que por ello haya muerto en paz; porque aunque no puedo sino desaprobar su complot,
es posible que mediante el verdadero arrepentimiento
no sólo haya obtenido perdón de Dios,
sino que también haya tenido plena seguridad de él.

No le fue mejor al conde de Argyle, quien se rebeló contra el rey James en Escocia.
Pero no detendré a mi lector con esto,
ni con el relato de la funesta ejecución de muchos,
que habiendo sido hallados culpables de alta traición (fuera por rebelión real,
o por haber sido cómplices de Monmouth),
fueron sentenciados a muerte por el infame George Jeffries,
quien entonces era el presidente del Tribunal Supremo y después fue canciller.
La fiera crueldad de este juez era tal,
que algunos perdieron sus vidas sólo por haberles
dado algo de heno o comida a los soldados de Monmouth.
Pero al no estar esto dentro de mi objetivo, lo dejaré de lado y pasaré al año 1686.

Por tanto, dejando Inglaterra, me volveré a Embden, en East Friesland,
donde un pequeño grupo de los llamados Cuáqueros
había estado por varios años bajo una severa persecución,
como he apuntado antes.
Pero al encontrar que los magistrados habían sido incitados
a la persecución por la instigación de sus predicadores,
los ciudadanos empezaron a disgustarse con ello.
Y dado que los Protestantes en Francia eran perseguidos violentamente en ese momento,
y un príncipe papista había ascendido al trono de Inglaterra,
los de Embden se inclinaron más a la moderación. Es probable que
la decadencia del comercio haya contribuido también con este cambio,
porque parecía que los magistrados estaban a favor
de conseguir más habitantes para su pueblo,
aunque ellos fueran Cuáqueros.
Esto se consideró un asunto de tal importancia,
que el consejo común deliberó sobre el tema,
y dos de los miembros de esa junta fueron enviados a Magdalena van Loar,
habitante de Embden, para pedirle que escribiera a Inglaterra y a Holanda,
que los magistrados de la ciudad habían decidido darle libertad
al pueblo llamado Cuáquero para que vivieran,
comerciaran y traficaran allí;
concesión que ofrecieron confirmar con el sello de la ciudad.

En conformidad con esta petición, se le dio aviso a los de esa persuasión en Ámsterdam,
de donde se le devolvió una respuesta a la mencionada Magdalena van Loar,
que ella entregó al consejero Polman, y él al senado.
Después de algunas deliberaciones, los magistrados,
junto con el consejo de cuarenta miembros y el tribunal eclesiástico,
se reunieron y llegaron a una resolución, de la que una copia fue enviada a Ámsterdam.
En ese escrito se mencionaban algunas condiciones,
sobre las que los magistrados en Embden estaban dispuestos a concederles
libertad a los Cuáqueros para vivir en su ciudad.
Pero los Cuáqueros en Ámsterdam, habiendo pesado y considerado debidamente el asunto,
hallaron que la propuesta contenía algunas expresiones
que podrían ser usadas como trampas contra los Cuáqueros,
por otros que llegaran después al poder.
Por tanto,
pensaron que era más seguro no contraer ningún compromiso
en los términos tal cual estaban prescritos.
No obstante, decidieron reconocer la buena intención de los magistrados de Embden,
redactando la siguiente carta y enviándola a ellos.

[.embedded-content-document.letter]
--

[.salutation]
A los señores, burgomaestres, consejeros y gobernantes de la ciudad de Embden.

La presente es para comunicarles, con el debido respeto, que el plan de ustedes,
con la fecha 11 de Febrero de 1686, ha llegado a nuestras manos,
el cual habiendo sido examinado por nosotros,
hemos pensado conveniente en el temor del Señor, enviarles la siguiente respuesta.

Primero,
le agradecemos al Dios Todopoderoso por el alivio y libertad
que nuestros amigos disfrutan actualmente bajo su gobierno,
y es probable que disfrutarán en el futuro.
Segundo, no podemos dejar de reconocer muy gratamente,
la clemencia y mansedumbre que muestran al tomar
en cuenta el estado de un pueblo despreciado y oprimido,
que debido a que su forma y adoración difieren de las muchas formas en el mundo,
son resistidos dondequiera.
Por tanto,
nos sentimos más movidos en nuestras mentes a orar fervientemente
al Señor Dios por la paz y prosperidad de ustedes,
y por la continuidad de su buena resolución;
para que todos los que sirven al Señor con rectitud de corazón,
puedan llevar una vida pacífica y piadosa entre ustedes,
mostrando los frutos del verdadero Cristianismo en verdad, sinceridad y justicia.

Ahora bien, en cuanto a lo que ustedes han tenido a bien declarar,
que están dispuestos a confirmar la mencionada buena
resolución mediante una declaración pública,
les dejamos saber,
que estamos tan satisfechos con su palabra y declaración
oral con respecto al asunto mencionado,
que es para nosotros más que cualquier cosa que hubiéramos podido desear,
sabiendo que los hombres buenos se consideran obligados por sus buenas palabras,
a realizar lo que es bueno.
Y dado que son conscientes de la razón por la que llegaron a dicha resolución,
no dudamos de que la misma persuasión y razón que continúan en ustedes,
resultarán en un compromiso más fuerte en ustedes
para cumplirla que cualquier sello externo.

En cuanto a lo que nos piden,
declaramos en la desnudez y sencillez de nuestros corazones,
que en lo que se refiere a nuestra conducta y comportamiento temporal,
no deseamos protección más allá de la que estamos
dispuestos a dispensar justamente a todos,
y caminar según la regla de oro,
haciendo a todos los hombres lo que deseamos que se haga con nosotros.
Y con respecto a nuestra religión y adoración,
que creemos que le debemos al Todopoderoso Dios,
hemos hallado que debido a que difiere de otras persuasiones,
no sólo nos hace detestables para la gente ignorante
que se burla de nosotros y nos injuria,
sino que también nos expone a la malicia y envidia
de muchos que nos odian sin una causa justa.
Por esta razón,
necesitamos de ustedes una interpretación favorable y el mejor entendimiento,
de lo que hacemos y de lo que dejamos de hacer.
Y si nos equivocamos en estos asuntos,
entonces seremos los más grandes perdedores por ello;
y si la verdad está de nuestro lado, nuestros adversarios no podrán prevalecer,
porque la verdad es más fuerte y no es bueno para nadie luchar contra ella.
Por lo tanto, esperamos que tengan a bien,
si nos comportamos pacífica y honestamente para con ustedes y todos los hombres,
que nos dejen ser partícipes junto con nuestros vecinos pacíficos,
de la protección general de ustedes.
Y aunque desean hacer una declaración pública a nuestro favor de la mencionada resolución,
claramente prevemos que nuestros enemigos, tergiversando una u otra palabra,
o mediante una interpretación errónea de las expresiones contenidas en ella,
podrán hacernos aparecer culpables de transgresión,
y así encontrar materia contra nosotros.

Así pues,
nosotros pensamos que es muy seguro confiar en la palabra y buena decisión de ustedes,
en la que les ha placido declarar que disfrutaremos
libertad para vivir y comerciar en su ciudad,
siempre que paguemos las aduanas y los impuestos a los que están sujetos los demás ciudadanos;
y que tendremos libertad de reunirnos para adorar a Dios
en la forma que Él nos ha convencido que debemos hacerlo,
para invocarlo a Él, y exhortarnos los unos a los otros al amor y buenas obras,
y a la conducta Cristiana.
En cuanto a ustedes,
esto resultará en alabanza para los magistrados porque nos favorecen de esta manera.
Además, será para el avance de la gloria de Dios y nos obligará a orar por ustedes,
para que el Señor Dios se complazca en guardarlos,
y hacer que continúen en un propósito tan bueno, sano y bien fundado.
Somos y permanecemos como,

[.signed-section-closing]
Sus verdaderos amigos y simpatizantes,

[.signed-section-signature]
Barent Van Tongeren, William Sewel, Jacob Claus, Stephen Crisp, John Roelofs, John Claus,
Peter Hendriksz.

[.signed-section-context-close]
Ámsterdam, 9 del mes Tres, alias Marzo, 1686

--

En respuesta a esto,
el senado envió la siguiente declaración a los firmantes de la mencionada carta, siendo,
como parece por el contenido,
el decreto del senado según quedó asentado en sus registros,
del que una auténtica copia firmada por el secretario de la ciudad está en mi poder.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Lunes 15 de Marzo, 1686

Recibimos una carta el 12 de este mes, escrita en Ámsterdam el 9 del mismo mes,
y firmada por Barent Van Tongeren, William Sewel, Jacob Claus, Stephen Crisp,
John Roelofs, John Claus, Peter Hendriksz,
en respuesta a nuestra decisión del 16 de Febrero último,
agradeciendo la prometida admisión y protección en esta ciudad,
para que comercien libremente y realicen su religión sin ofender a nadie;
indicando además, que quedarán satisfechos sin una declaración firmada por parte nuestra,
y que están dispuestos a confiar en nuestras palabras.
Después de deliberar al respecto, se consideró adecuado y se decidió,
que nuestra palabra efectivamente se mantendrá con
los firmantes y con todos los demás de su persuasión,
y que la protección prometida se cumplirá realmente.

[.signed-section-closing]
Ad mandatum senatus speciale,

[.signed-section-signature]
O+++.+++ Hillings, Sec.

--

De este modo,
el senado de Embden tuvo a bien concederles a los
llamados Cuáqueros la libertad de vivir entre ellos,
con el libre ejercicio de su religión. Poco tiempo después de esto,
sucedió que el burgomaestre Andrews llegando a la casa de Magdalena van Loar,
y un predicador llamado Alardyn a la de su hija Magdalena Hassbaant,
ambas les solicitaron que enviaran a Inglaterra lo resuelto,
para que se supiera que si alguno de la persuasión
de los Cuáqueros llegaba y se establecía en Embden,
sería bien recibido.

De este modo vemos la manera en que Dios tiene los
corazones de todos los hombres en Sus manos,
y que los vuelve hacia donde quiere.
Porque unos años antes de esto, los magistrados de Embden,
a partir de un celo ciego encendido por los que debían detenerlo,
habían emitido edictos muy severos contra los Cuáqueros y los habían perseguido ferozmente,
pero ahora les permitían plena libertad.

Pero dejo Embden y regreso a Inglaterra,
donde en ese momento también se detenía la persecución, tanto así,
que el rey ordenó que todos los Cuáqueros encarcelados que estaban en su poder liberar,
fueran puestos en libertad, porque los que estaban en prisión por no pagar diezmos,
estaban bajo la jurisdicción eclesiástica, la cual estaba fuera del alcance del rey.
Pero muchos otros que habían estado en custodia por varios años,
aparecieron entonces en Londres para la reunión anual de sus amigos,
para el gran gozo de sus hermanos.
Y cuando algunos de estos fueron a agradecerle al rey por su favor,
fueron recibidos amablemente.
De esta manera atrajo la disposición de ellos hacia él,
porque sus esfuerzos eran entonces, como dijo él,
lograr completa libertad de consciencia.
No puedo decir cuál era exactamente su objetivo, pues nunca lo alcanzó,
pero en el ínterin, hizo que la persecución cesara en general, no sólo en Inglaterra,
sino también en otros lugares de sus dominios.
Porque habiendo oído que los Cuáqueros en la isla de Barbados,
en las Indias Occidentales,
eran muy molestados porque por razones de consciencia no podían llevar armas,
les ordenó a algunos miembros de su consejo escribir la siguiente carta:

[.embedded-content-document.letter]
--

Después de nuestras sinceras recomendaciones,
le ha placido a su majestad remitirnos la petición de los Cuáqueros que habitan en Barbados,
y hemos considerado conveniente solicitarles y requerirles por la presente,
que examinen las alegaciones de la mencionada petición y los documentos adjuntos.
Y por cuanto su majestad, que recientemente ha extendido su favor hacia este pueblo aquí,
está inclinado a continuar dicho favor hacia ellos en este caso,
deseamos que nos informen qué facilidad se les puede dar con respecto
a la ley de milicia y a las penas impuestas por ella,
en la medida que sea consistente con la seguridad de la isla,
la preservación de la milicia, y en concordancia con la intención de la mencionada ley.
Nos despedimos de corazón. Sus afectuosos amigos,

[.signed-section-signature]
Jefferies, Craven, Albemarle, Middleton.

[.signed-section-context-close]
De la cámara del Consejo, Whitehall, 23 de Julio de 1686.

--

De esta carta se desprende claramente,
que el rey se esforzó por aliviar a los Cuáqueros de la
carga de la persecución a la que estaban sometidos.
La siguiente carta es también una prueba de esta intención,
escrita por el conde de Sunderland, entonces presidente del consejo privado,
al conde de Huntington, para detener la persecución en Leicestershire y Nottinghamshire,
donde un tal John Smith había actuado de forma muy grave.

[.embedded-content-document.legal]
--

[.signed-section-context-open]
Whitehall, 7 de Diciembre de 1686

Al honorable conde de Huntingdon, miembro del honorable consejo privado del rey,
registrador principal del Leicester, encargado de los registros del condado de Leicester.

[.salutation]
Mi señor,

Al ser informado el rey de que un tal John Smith, un informante común,
persigue de manera muy grave a los Cuáqueros en el condado
de Leicester y en el pueblo y condado de Nottingham;
y al estar su majestad complacido en extender su favor a los de esta persuasión,
quiere que su gracia ordene a los jueces de paz no
dar ningún tipo de apoyo al mencionado John Smith,
ni a su persecución contra los Cuáqueros.

Mi señor, soy por su gracia el duque de Newcastle,
miembro del honorable consejo privado del rey, etc.

[.signed-section-closing]
Tu más fiel y humilde siervo,

[.signed-section-signature]
Sunderland, P.

--

Estando inclinado así el rey a darle libertad a los
prisioneros que estaban en custodia por la religión,
no descuidó ninguna oportunidad de obtenerla,
de lo que la siguiente petición es evidencia.

[.embedded-content-document.letter]
--

Al presidente del Tribunal Herbert y al juez Wright,
asignados para celebrar la sesión del tribunal y
la liberación de la cárcel en el circuito oeste,
en Wells, para el condado de Somerset, el 30 del mes llamado Marzo de 1686.

Varios del pueblo llamado Cuáqueros,
en este momento prisioneros en la cárcel en Ivlechester, en el condado de Somerset,
en nombre de sí mismos y de muchos otros de dicho pueblo, en humildad presentan:

Dado que el sabio Dispensador de todas las cosas ha ordenado el empleo de ustedes
en este honorable servicio para aliviar al oprimido y liberar a los cautivos;
y dado que el rey James II les ha dado en custodia parte de su clemencia,
para que la distribuyan según incline el Señor su corazón;
y habiendo tomado especial nota de nuestros sufrimientos
y manifestado su voluntad y beneplácito de que nosotros,
el pueblo comúnmente llamado Cuáqueros, recibamos pleno beneficio de su perdón general,
junto con toda posible facilidad (cuya gracia y favor reconocemos
con toda gratitud a Dios como el principal autor,
quien tiene los corazones de los reyes a Su disposición; y al rey,
por estar listo a ocuparse de eso, hacia lo que el Señor inclina su corazón);
y después de haber oído el informe de la nobleza y moderación de
ustedes al manejar esta importante confianza que se les ha encomendado,
nos animamos a dirigirnos a ustedes, aunque con sencillez de palabra, y sin embargo,
con sinceridad de corazón, a poner delante de ustedes nuestro caso.

Hemos estado presos por varios años en la citada cárcel,
no por haber conspirado contra el rey o contra el gobierno,
ni por haber hecho daño a sus súbditos (porque nuestras vidas pacíficas
han manifestado nuestra fidelidad al rey y nuestro amor al prójimo,
al ser contrario a nuestros principios hacer lo opuesto),
sino sólo por motivos de consciencia,
porque en obediencia a Jesucristo no nos atrevemos a jurar en ninguna manera,
no dejamos de adorar a Dios como Él nos ha ordenado,
ni nos hemos conformado a la adoración en la que no tenemos fe;
porque si omitiéramos lo primero o practicáramos lo último, pecaríamos en ello,
y así heriríamos nuestras consciencias y quebrantaríamos nuestra paz con Dios.
Y entonces, ¿de qué nos servirían nuestras vidas,
incluso si pudiéramos disfrutar siempre del favor del mundo y de su amistad?

Por tanto, nuestra humilde solicitud a ustedes es,
que consideren y tengan compasión de nuestra sufrida condición,
y usen el poder y autoridad que Dios y el rey les
han confiado para nuestro alivio y libertad;
sabiendo que nosotros, con la ayuda de Dios,
de corazón nos proponemos continuar manifestando nuestro temor a Dios,
honor al rey y honestidad a todos sus súbditos, mediante nuestra conducta piadosa,
humilde y pacífica.
Las causas particulares de nuestros encarcelamientos están aquí atestiguadas,
firmadas por nuestro carcelero.
Además, solicitamos que todos los informantes mercenarios,
y aquellos que envidiosamente nos persiguen sólo por motivos de consciencia,
conforme a la sabiduría y prudencia de ustedes,
sean disuadidos de llevar a cabo tales acciones,
por las que muchas familias y personas trabajadoras
y conscientes están en peligro de ser arruinadas.
De este modo,
nosotros también nos sentiremos alentados a seguir
siendo diligentes en nuestras respetables vocaciones,
y podremos disfrutar del beneficio de nuestra labor,
y así estaremos mejor capacitados para realizar con alegría los deberes para con Dios,
el rey y todos los hombres.
Que el Señor los guíe en el juicio e incline más y más sus
corazones a amar la misericordia y hacer justicia,
y les conceda la recompensa correspondiente, lo cual es, en verdad,
nuestro deseo y oración.

--

Esta petición fue firmada por dieciséis personas,
algunas de las cuales habían estado en prisión quince, otras diez y algunas menos años;
y junto con la duración de sus encarcelamientos,
se añadían las causas por las que habían sido llevadas a prisión, es decir,
por la sentencia de premunire, excomunión, diezmos, etc.
Esta petición tuvo tal efecto,
que el presidente del Tribunal Herbert liberó a estos prisioneros; sin embargo,
antes de que fuera hecho, varios de los que habían estado encarcelados allí, murieron.
Muchos también fueron puestos en libertad por la proclamación del rey,
y era realmente algo tan inusual que este pueblo disfrutara una libertad tan amplia,
que parecía que los perseguidores malvados estaban restringidos por un poder superior.

George Fox en ese entonces estaba principalmente en Londres y sus alrededores,
esforzándose por poner todas las cosas en buen orden entre sus amigos;
y dado que no podía estar en persona en todas partes, escribió varios documentos,
además de cumplir con su deber de palabra.
Y para que el descuido no se infiltrara, debido a la libertad que entonces se disfrutaba,
les escribió la siguiente epístola a sus amigos.

[.embedded-content-document.epistle]
--

[.salutation]
Amigos,

El Señor, mediante Su poder eterno,
se ha abierto paso en el corazón del rey para abrir las puertas de la prisión,
por lo que unas mil quinientas o mil seiscientas personas están ahora en libertad;
y esto le ha puesto freno a los informantes,
de modo que en muchos lugares nuestras reuniones están bastante tranquilas.
Así, pues,
mi deseo es que tanto la libertad como el sufrimiento sean santificados para Su pueblo,
y que los amigos valoren las misericordias del Señor en todas las cosas y Le estén agradecidos,
quien calma las embravecidas olas del mar y aplaca las tormentas y tempestades,
y hace que haya calma.
Por tanto,
es bueno confiar en el Señor y echar toda la ansiedad sobre Aquel que cuida de ustedes.
Porque cuando estaban en sus cárceles y prisiones,
entonces el Señor los sostenía con Su brazo y poder eternos,
y santificaba esos sufrimientos para ustedes; y para otros,
había hecho que sus prisiones fueran como santuarios.
En efecto, Él estaba probando a Su pueblo, como en un horno de aflicción,
tanto en prisiones como a través del saqueo de los bienes.
Y en todo esto,
el Señor estaba con Su pueblo y les estaba enseñando
que de Él es la tierra y toda su plenitud;
y que Él está en todas partes, y '`corona el año con sus bienes.`' Salmo 65

Por tanto,
que todo el pueblo de Dios sea diligente y cuidadoso
para mantener el campamento de Dios santo,
puro y limpio; y para servir a Dios y a Cristo, y los unos a los otros,
en el glorioso y pacífico evangelio de vida y salvación,
cuya gloria resplandece sobre el campamento de Dios.
Porque Su gran Profeta, Obispo y Pastor está entre, o en medio de ellos,
ejecutando Sus oficios celestiales en ellos; para que ustedes, Su pueblo,
se regocijen en Jesucristo, a través de quien tienen paz con Dios.
Porque Aquel que destruye al diablo y su obra, y aplasta la cabeza de la serpiente,
es el fundamento y la roca celestial sobre la que todo el pueblo de Dios debe edificar;
la cual era la roca de los santos profetas y apóstoles en los días pasados,
y es hoy la roca de nuestra época; roca y fundamento de Dios que permanece firme.
Que el Señor Dios establezca sobre ésta a todo Su pueblo.
Amén.

[.signed-section-signature]
George Fox.

[.signed-section-context-close]
Londres, 25 del mes Siete de 1686.

--

Este año murió David Barclay en Ury, Escocia.
Antes de su partida pronunció muchas expresiones maravillosas,
por lo que no puedo dejar de mencionar algunos detalles.
A finales de Septiembre, después de superar los 76 años,
le sobrevino una fiebre que se prolongó por dos semanas,
y al estar muy afectado por la grava,^
footnote:[Es decir, piedras en los riñones.]
su enfermedad era acompañada con mucho dolor al orinar.
Dos días antes de su muerte, sintiendo su debilidad y estando en agonía,
le dijo a su hijo Robert que estaba con él: "`Estoy a punto de ir al Señor,
y a ser reunido con muchos de mis hermanos que me han precedido.`"
El 11 de Octubre, muy temprano en la mañana, se debilitó aún más,
y el mencionado Robert Barclay le hizo saber que su oración era
que Aquel que lo amaba estuviera cerca de él hasta el fin.
A esto David respondió:
"`El Señor está cerca,`" y les dijo a los otros que estaba a su alrededor:
"`¡Cuán grande bendición ha sido para mí y mi familia,
el descubrimiento perfecto de la Aurora de lo alto!`"
Cuando la esposa de Robert Barclay le preguntó si quería algo que lo refrescara,
dijo que no lo necesitaba; y colocando su mano sobre su pecho dijo:
"`Tengo lo que me refresca en el interior.`"
Un ratito después se le oyó decir varias veces:
"`La verdad está sobre todo;`" y tomando a su hijo mayor lo bendijo y dijo:
"`Oro a Dios que nunca te separes de la verdad.`"
Entonces la hija de su hijo mayor se acercó y él dijo: "`¿Es esta Paciencia?`"
(Porque ese era su nombre) "`Tenga la paciencia su obra perfecta`" en ti.
Y después de besar a los otros cuatro hijos de su hijo,
puso sus manos sobre ellos y los bendijo.
Acercándose también el boticario que le atendía, le tomó de la mano y le dijo:
"`Tú darás testimonio de mí, de que en todo este ejercicio no he procurado alterar,
ni mimar la carne.`"
"`Señor,
puedo dar testimonio de que tú siempre te has ocupado de la mejor parte y la más sustancial;
me regocijo ver el bendito final al que el Señor te está llevando.`"
A esto el enfermo replicó: "`Dar testimonio fiel y verdadero.
Es de la vida de justicia; de la vida de justicia es de la que damos testimonio,
y no de una profesión vacía.`" Luego llamó varias veces: "`¡Ven, Señor Jesús, ven, ven!`"
Y también dijo: "`Mi esperanza está en el Señor.`"

Después, durmió a ratos por algunas horas,
y viendo que un carpintero entraba en la habitación le dijo a su hijo:
"`Asegúrate de encargarle que no haga nada lujoso en mi
ataúd.`" Por la tarde varios de sus amigos llegaron a verlo,
lo que él observó y les dijo que habían llegado en el momento oportuno.
Después de algunas palabras y de que Patrick Livingston había orado,
la cual finalizó en alabanzas, el anciano enfermo levantó sus manos y dijo: "`¡Amén,
amén, para siempre!`"
Y después de que los presentes se pusieron de pie dijo:
"`¡Cuán precioso es el amor de Dios entre Sus hijos, y el amor de los unos a los otros!
En esto conocerán los hombres que son discípulos de Cristo, si se aman unos a otros.
¡Cuán precioso es ver a los hermanos vivir juntos en amor!
Mi amor está con ustedes.
Lo dejo entre ustedes.`"
Bastante tarde en la noche varios de sus amigos estaban reunidos alrededor de su cama,
y percibiendo él que algunos lloraban dijo: "`Queridos amigos,
ocúpense todos del hombre interior, no le presten atención al exterior.
Hay Uno que recompensa, el Señor de los Ejércitos es Su nombre.`"
La mañana siguiente, después de oír que el reloj daba las tres, dijo:
"`Ya viene el momento.`"
Y un poco después se le oyó decir: "`¡Alabanzas, alabanzas, alabanzas al Señor!
Deja ahora que Tu siervo parta en paz.
¡En tus manos, oh Padre, encomiendo mi alma, espíritu y cuerpo!
Sea hecha Tu voluntad, Señor, en la tierra como en el cielo.`"
Estas frases las pronunció en pequeños intervalos, una detrás de otra;
y poco después de las cinco de la mañana del 12 de Octubre, durmió en paz y quietud,
estando presentes en su final más de veinte personas que fueron testigos de lo
que se ha relatado aquí. Su cuerpo fue acompañado a la tumba por numerosas personas;
y aunque él había ordenado que no se invitaran a muchos a su entierro,
un gran número de la alta burguesía llegó sin invitación,
por la estima que tenían de su memoria.

Este año también partió de esta vida Anne Downer,
una de las primeras llamadas Cuáqueras en Londres.
Ella se casó primero con Benjamín Greenwel y después fue la esposa de George Whitehead.
Estando enferma se había trasladado a las afueras de Londres,
y al agravarse su enfermedad, se dio cuenta de que era muy posible que se la llevara.
Cuando su antigua amiga Mary Stout la visitó, le preguntó si la reconocía,
y Anne le respondió: "`Sí, muy bien, eres Mary Stout.
Tengo bien mi memoria y mi entendimiento es claro, aunque estoy muy débil;
pero estoy rendida a la voluntad del Señor, sea para morir o para vivir;
porque Le he sido fiel en lo que sabía, tanto en la vida como en la muerte.`"
Al percibir que algunos estaban atribulados por ella, dijo:
"`No hay razón para que estén atribulados o preocupados, porque estoy bien y en paz.`"
Ella pronunció muchas exhortaciones Cristianas en su lecho de muerte,
y les dijo a algunos de sus amigos que la llegaron a visitar: "`¿Qué,
vienen con el propósito de verme?
Lo tomo como fruto del amor de Dios y oro que Dios bendiga a sus hijos.`"
También se le oyó decir a otros: "`Si no volviera a ver sus rostros,
está bien para mí. Dios conoce mi integridad y cómo he sido
y caminado delante de Él.`" La noche anterior a su muerte,
le dijo a su esposo George Whitehead: "`El Señor está conmigo, bendigo Su nombre.
Estoy bien.
Es posible que tengas miedo de que sea llevada, y si es así,
que se haga la voluntad del Señor. No te aflijas,
ni hagas un gran alboroto por mí. Querido, ve a acostarte, ve a descansar,
y si no te digo nada más, conoces el amor eterno de Dios.`"
También se le oyó decir, que había terminado con todas las cosas de esta vida,
y que nada la afligía,
sino que estaba en verdadera paz y se sentía tranquila en todo sentido.
Unas horas antes de su partida dijo: "`Aunque estoy muriendo, aun así es una muerte viva;
porque aunque la debilidad se ha apoderado del cuerpo,
mi entendimiento está tan claro como cuando estaba sana.`"
Así partió de esta vida tranquilamente, con casi sesenta y tres años,
habiendo sido una mujer bien dotada y muy útil en la iglesia,
no sólo con exhortaciones sanas,
sino también por su cuidado Cristiano a los enfermos y pobres,
y a las viudas y huérfanos, que con su muerte perdieron a una madre notable.

Por esta época, George Fox les escribió a sus amigos varias epístolas generales,
algunas de las cuales eran bastante largas, exhortándolos a evitar la disputa,
guardar el mutuo amor y la unidad, y a ocuparse de la verdadera piedad.
También escribió muchos otros documentos edificantes;
y debido a que los papistas en ese entonces se mostraban abiertamente,
y realizaban su adoración públicamente, y se hablaba mucho de sus oraciones a los santos,
y oraciones usando cuentas, etc.,
en el año 1687 escribió el siguiente documento con respecto a la oración,
sin temor a contradecir abiertamente lo que él juzgaba ser superstición,
aunque el rey mismo era de la religión papista.

[.embedded-content-document.epistle]
--

Jesucristo, cuando enseñó a Sus discípulos a orar les dijo: "`Cuando oren, digan:
Padre nuestro, que estás en el cielo, santificado sea Tu nombre,`" etc.
Cristo no dice que oren a María madre de Cristo;
no dice que oren a los ángeles o a los santos que están muertos.
Cristo no les enseñó a orar a los muertos, ni por los muertos.
Ni Cristo ni Sus apóstoles les enseñaron a los creyentes a orar usando cuentas,
ni a cantar con órganos externos;
sino que el apóstol dijo que él cantaba y oraba en el Espíritu,
porque el Espíritu hace intercesiones, y que el Señor,
quien es el que escudriña el corazón, sabía la intención del Espíritu.

Tomar consejo de los muertos estaba prohibido por la ley de Dios,
sino que ellos debían tomar consejo del Señor. Él ha dado a Cristo en el nuevo pacto,
en el día de Su evangelio,
para que sea el consejero y líder de todo el que cree en Su luz.
Los hombres no deben correr a los muertos en busca de los vivos;
porque la ley y el testimonio de Dios lo prohíben.
Los judíos que rechazaron las corrientes de agua de Siloé,
fueron anegados por las inundaciones y las aguas de los asirios y babilonios,
y fueron llevados en cautiverio; y los que rechazan las aguas de Cristo,
son anegados por la inundación del mundo que yace en maldad.
Los que pedían consejo a los maderos y piedras,
estaban en el espíritu de error y fornicación, y se prostituyeron apartándose de Dios.
Oseas 4:12. Los que se unieron a Baal-Peor y comieron los sacrificios hechos a los muertos,
provocaron la ira del Señor y trajeron sobre ellos
el disgusto del Señor. Salmo 106:28-29. Por tanto,
pueden ver que los sacrificios hechos a los muertos estaban prohibidos.
"`Porque los que viven saben que han de morir; pero los muertos nada saben,
ni tienen más paga; porque su memoria es puesta en olvido.`"
Eclesiastés 9:5. "`¡Ay de los hijos que se apartan, dice Jehová, para tomar consejo,
y no de mí; para cobijarse con cubierta, y no de mi Espíritu,
añadiendo pecado a pecado!`"
Isaías 30:1.

[.signed-section-signature]
George Fox

--

El 20 del mes llamado Marzo, murió Robert Widders,
uno de los primeros predicadores entre los llamados Cuáqueros.
G+++.+++ Fox en ese entonces pasaba mucho tiempo en Londres,
pero su cuerpo se debilitaba cada vez más,
después de haber soportado muchos duros y crueles encarcelamientos por la verdad.
A veces se iba al campo para tomar aire fresco,
y en otras ocasiones pasaba un tiempo en la casa de campo de su yerno, William Mead,
casado con una de las hijas de su esposa.
Mientras tanto, escribía mucho, porque era de temperamento laborioso,
y en todos sus asuntos no dejaba de visitar las reuniones de sus
amigos y de edificarlos con sus amonestaciones y exhortaciones.
Pues ya se les permitía realizar sus reuniones sin ser molestados, ya que el rey,
en el mes llamado Abril,
había publicado su tan esperada declaración de libertad
de consciencia para todos sus súbditos,
que contenía: "`Que en adelante,
debe suspenderse la ejecución de todas las leyes penales relacionadas con asuntos eclesiales,
por no asistir a la iglesia, no recibir los sacramentos,
por cualquier otra no-conformación con la religión establecida,
o por realizar adoración religiosa de otra manera, etc.`"

Habría sido incluso más aceptable,
si dicha libertad hubiera sido establecida por el rey y el Parlamento,
pues ésta había sido otorgada sólo en virtud de la prerrogativa real; pero, sin embargo,
se disfrutó una verdadera libertad,
por la que se le permitió a los disidentes realizar su adoración libremente,
siempre que su predicación no tendiera a hacer que
las mentes de las personas se opusieran al gobierno.
Así pues, los amigos en Londres,
al ver que las otras persuasiones presentaban al rey cartas de
agradecimiento por su declaración de libertad de consciencia,
pensaron que era conveniente redactar una carta también y presentársela al rey,
la cual es como sigue:

[.embedded-content-document.letter]
--

[.letter-heading]
Al rey James II, sobre Inglaterra, etc.

Las humildes y agradecidas declaraciones de varios de los súbditos del rey,
comúnmente llamados Cuáqueros, en y alrededores de la ciudad de Londres,
en nombre propio y de los de su comunión.

[.salutation]
Que esto complazca al rey,

Aunque no somos los primeros en presentarnos de esta manera,
esperamos no ser los menos sensibles a los grandes favores por
los que venimos a presentarle al rey nuestro agradecimiento humilde,
sincero y de corazón; ya que ningún pueblo ha recibido mayores beneficios,
tanto al abrir las puertas de nuestras prisiones,
como por su reciente y excelente declaración Cristiana a favor de la libertad de consciencia;
ni ningún otro, ha sufrido más severamente,
ni ha estado más generalmente expuesto a la malicia de hombres malos por
motivo de religión. Y aunque recibimos este acto de misericordia con todos
los reconocimientos de un pueblo perseguido y agradecido,
debemos decir, sin embargo, que nos sorprende menos,
sabiendo que ha sido el principio declarado del rey,
desde mucho antes y desde que llegó al trono de sus ancestros.

Y así como nos regocijamos al ver el día que un rey de Inglaterra, desde su sello real,
afirma tan universalmente este glorioso principio,
de que la consciencia no debe ser forzada,
ni ninguna persona obligada por asuntos de mera religión
(la falta del cual ha sido la desolación de países,
y un reproche a la religión), así nosotros también,
con corazones humildes y sinceros le rendimos primero a Dios, y luego al rey,
nuestro sensible reconocimiento.
Y debido a que nuestro agradecimiento no puede ser
mejor expresado sino a través de una vida piadosa,
pacífica y obediente, con la ayuda de Dios,
nos esforzaremos por demostrar siempre que somos súbditos fieles y amorosos del rey;
y esperamos que después de que este bondadoso paso que ha dado el rey hacia la unión
de su pueblo y seguridad de su interés común haya tenido su debida consideración,
no habrá lugar para temores y preocupaciones que
puedan hacer que el reinado del rey sea intranquilo,
o que algunos de sus súbditos sean infelices.

Lo que nos queda por hacer, gran príncipe,
es suplicarle al Todopoderoso Dios (por quien reina
el rey y los príncipes determinan justicia),
que te inspire más y más con Su excelente sabiduría y entendimiento,
a proseguir con el designio Cristiano de aliviar a todos los disidentes religiosos,
con los métodos más agradables y duraderos.
Y le oramos a Dios que bendiga con gracia y paz al rey, a su familia real y a su pueblo;
y que después de un largo y próspero reinado aquí,
reciba una mejor corona entre los bienaventurados.

[.signed-section-closing]
La cual es la oración de, etc.

--

Esta carta fue recibida favorablemente, y por tanto,
algunos representantes de la reunión anual (que fue celebrada
en Londres un poco después) prepararon también una carta,
y fueron a Windsor donde estaba entonces la corte.
William Penn, que fue uno de los escogidos para presentar la carta,
pronunció el siguiente discurso ante el rey:

[.embedded-content-document.letter]
--

[.salutation]
Que esto complazca al rey,

Fue el dicho de nuestro bendito Señor a los judíos insidiosos con respecto al tributo:
"`Dad, pues, a César lo que es de César, y a Dios lo que es de Dios.`"
Como esta distinción debe ser observada por todos
los hombres en la conducta de sus vidas,
así el rey nos ha dado un ejemplo ilustre en su propia persona que nos estimula a ello;
porque mientras él era un súbdito, le dio al César su tributo,
y ahora que es como un César, le da a Dios lo que le corresponde, es decir,
la soberanía sobre las consciencias de los hombres.
Sería entonces una gran vergüenza para cualquier inglés que profesa el Cristianismo,
no darle a Dios lo que le corresponde.
Por esta gracia el rey ha aliviado a sus angustiados súbditos de sus crueles sufrimientos,
y ha levantado para sí un nuevo y duradero imperio,
al añadir los afectos de ellos a su deber.
Y le rogamos a Dios que mantenga al rey en esta noble resolución,
porque él ahora se basa en un principio que tiene una buena naturaleza, es decir,
el Cristianismo, y la bondad de la sociedad civil de su lado.

Espero que nadie piense que nosotros venimos aquí con el propósito de llenar la gaceta^
footnote:[Antiguo periódico inglés, publicado por primera vez en 1665.]
con nuestros agradecimientos;
pero así como nuestros sufrimientos habrían movido a las piedras a la compasión,
nosotros seríamos aún más duros, si no fuéramos movidos a la gratitud.

Ahora bien, puesto que la misericordia y bondad del rey han llegado hasta nosotros,
en todo el reino de Inglaterra y el principado de Gales,
nuestra asamblea de todos esos lugares,
reunida ahora en Londres para tratar nuestros asuntos eclesiales,
nos ha designado para esperar al rey con nuestros humildes agradecimientos,
y a mí para entregárselos.
Esto lo hago mediante este discurso, con todo el afecto y respeto de un súbdito obediente.

--

Después de que W. Peen habló, presentó la carta al rey,
quien después de recibirla amablemente,
se la dio de nuevo a William Penn para que la leyera, que era como sigue:

[.embedded-content-document.address]
--

[.salutation]
Al rey James II de Inglaterra, etc.

El humilde y agradecido reconocimiento de sus pacíficos súbditos llamados Cuáqueros,
en este reino, de su habitual reunión anual en Londres, el día 19 del tercer mes,
comúnmente llamado Mayo, de1687.

No podemos sino bendecir y alabar el nombre del Todopoderoso Dios,
quien tiene los corazones de los príncipes en Su mano,
por haber inclinado al rey a oír los clamores de
sus sufridos súbditos por motivos de consciencia;
y nos regocijamos, de que en lugar de molestarlo con quejas por nuestros sufrimientos,
nos haya dado una oportunidad tan notable de presentarle nuestro agradecimiento.
Y puesto que le ha placido al rey, por su gran compasión,
compadecerse de nuestra afligida condición,
manifestada particularmente mediante su bondadosa proclamación de este último año,
(por la que más de mil doscientos prisioneros fueron liberados de sus severos encarcelamientos,
y muchos otros del despojo y ruina de sus patrimonios y propiedades)
y por su declaración Cristiana a favor de la libertad de consciencia,
en la que no sólo expresa su aversión a toda fuerza sobre la consciencia,
y les concede a todos sus súbditos disidentes amplia libertad para adorar a Dios
en la forma que están persuadidos de ser la más aceptable a Su voluntad,
sino que también les da su palabra de rey,
de que dicha libertad continuará durante su reinado.
Por todo esto nosotros, como ya han hecho nuestros amigos de esta ciudad,
le rendimos al rey nuestro humilde, Cristiano y agradecido reconocimiento,
no sólo en nombre de nosotros mismos,
sino también en el de nuestros amigos en toda Inglaterra y Gales.
Con todo nuestro corazón le rogamos a Dios que te bendiga y preserve, a ti, oh rey,
y a todos los que están debajo de ti en tan buena obra,
y te aseguramos que estas cosas son bien recibidas
en todos los condados de los que venimos;
por lo que esperamos que los buenos efectos de dicha obra en la paz,
comercio y prosperidad del reino produzcan tal acuerdo en el Parlamento,
que los asegure a nuestro posteridad en los tiempos venideros.

[.signed-section-closing]
Sus pacíficos, afectuosos y fieles súbditos,

--

[.offset]
Después de que William Penn leyó la mencionada carta, el rey habló como sigue:

[.embedded-content-document.address]
--

[.salutation]
Caballeros,

Les agradezco de corazón su carta.
Algunos de ustedes saben, estoy seguro de que tú, señor Penn,
que siempre ha sido mi principio que la consciencia no debe ser forzada,
y que todos los hombres deben tener la libertad de sus consciencias.
Y lo que he prometido en mi declaración, lo continuaré realizando mientras viva;
y espero establecerlo antes de morir,
de modo que en las edades venideras no haya razón para alterarlo.

--

Aquí vemos que lo que el rey declaró era su intención, pero, tal vez no consideró,
que si tal libertad general hubiera sido conseguida,
no podría hacer que continuara más allá de lo que el clero papista pensara que era conveniente.
Porque, ¿quién ignora el poder ilimitado que los prelados romanos han usurpado,
no sólo en lo eclesiástico, sino también en la arena política?
De tal manera, que por muy sincera que hubiera sido la intención del rey,
es probable que se viera frustrada, aunque él hubiera deseado que fuera de otro modo.
En efecto, muchos que no eran de su persuasión creían que su intención era sincera,
y entre estos estaban los que pensaban que la libertad de
consciencia podría haberse establecido de modo tal,
que no quedara al alcance de los papistas romperla.
Pero el tiempo ha demostrado que el rey James no iba a ser el
instrumento para establecer tal libertad de consciencia,
y que la derogación de las leyes penales estaba reservada para otro príncipe.
Sin embargo,
algunos pensaban que el rey había hecho lo que había
podido para detener a los perseguidores rapaces,
y refrenar su poder con respecto a la imposición de juramentos.
De hecho,
algunos decían que el rey no podía hacer nada con respecto a la imposición de juramentos,
pues al concederles esta libertad a los Cuáqueros,
abriría una puerta para que los papistas ocuparan
cargos sin tener que prestar los juramentos requeridos.
No obstante, en la siguiente orden al alcalde de Londres,
se ve que él liberó a los Cuáqueros de algunos juramentos:

[.embedded-content-document.legal]
--

[.salutation]
Señor alcalde,

Se le ha informado al rey que Edward Brooker, Henry Jefferson y Joseph Tomlinson,
Cuáqueros, han sido propuestos por el señor Barker, administrador de Southwark,
como alguaciles y similares, lo cual, ellos están dispuestos a hacer;
pero cuando se les presentan los juramentos,
de los que se consideran exentos por la declaración del rey sobre la libertad de consciencia,
son amenazados con ser multados y molestados de cualquier
otra forma por su negativa a prestarlos.
Su majestad me ordena hacerle saber a su señoría, que es su voluntad,
que a los mencionados Edward Brooker, Henry Jefferson y Joseph Tomlinson,
y a todos los otros Cuáqueros,
se les permita servir ahora y en el futuro en los
mencionados cargos sin prestar ningún juramento,
o bien, que no sean multados ni molestados de ninguna forma por ese motivo;
y su majestad desea que des la orden correspondiente.

[.signed-section-closing]
Soy, mi señor, el más humilde servidor de su señoría,

[.signed-section-signature]
Sunderland.

--

Ahora bien,
considerando que en algunos lugares los bienes que se les
habían quitado a los Cuáqueros seguían sin vender,
el rey ordenó que esos bienes les fueran devueltos,
como puede verse por la siguiente carta escrita al alcalde y a los concejales de Leeds,
en Yorkshire:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Whitehall, 14 de Diciembre de 1687.

[.salutation]
Caballeros,

Al ser informado el rey de que algunos de los bienes que pertenecen a John Wales,
y a otros Cuáqueros de Leeds,
que les fueron confiscados y quitados por motivo de su adoración religiosa,
permanecen sin vender en las manos de John Todd,
que era alguacil en el momento de la confiscación,
o en las manos de algunas otras personas;
y como la intención de su majestad es que todos sus súbditos reciban
el pleno beneficio de su declaración sobre la libertad de consciencia,
su majestad me ordena que les comunique su deseo de que
los bienes que pertenecen al mencionado John Wales,
y a todos los otros Cuáqueros de Leed,
que fueron confiscados hasta ahora por motivos de su adoración religiosa,
y no están vendidos, y permanecen en manos de cualquiera,
sean inmediatamente devueltos a los respectivos propietarios sin cargo alguno.

[.signed-section-closing]
Soy, caballeros, su afectivo amigo y servidor,

[.signed-section-signature]
Sunderland

--

Por estos medios algunos recibieron de vuelta los bienes
que habían sido tomados por motivos de su adoración religiosa;
pues en muchos lugares dichos bienes habían permanecido por largo tiempo sin vender,
porque pocos compraban los bienes que habían sido tomados de esa manera.
Y no es de extrañar,
que por estos favores el rey atrajera hacia sí el amor y afecto de muchos de sus súbditos;
porque independientemente de su religión,
los había liberado de la pesada carga bajo la que habían
estado oprimidos por muchos años. A esto podría añadirse,
que él los trataba gentilmente en todos los aspectos,
y no permitía que sus siervos molestaran a ninguno por no quitarse
los sombreros cuando se acercaban a su persona real.
De hecho, su condescendencia llegaba tan lejos,
que cuando cierto campesino de la persuasión de los Cuáqueros
se acercó a él con su sombrero sobre su cabeza,
el rey se quitó el suyo y lo sostuvo bajo su brazo; lo que al verlo el Otro dijo:
"`El rey no necesita quitarse su sombrero por mí.`" A lo que el príncipe replicó:
"`No conoces la costumbre aquí, porque requiere que sólo un sombrero permanezca puesto.`"
Me han contado de sucesos similares que paso por alto; pero de todo esto se desprende,
que el rey se esforzó por tener entre los Cuáqueros la reputación de ser un príncipe
gentil y cortés. Este año también concedió total libertad de consciencia en Escocia,
y liberó a los que estaban todavía bajo sufrimientos,
permitiéndoles la libertad de sus reuniones religiosas.
Dicha libertad se las concedió también a los Presbiterianos,
siempre que no se reunieran en los campos, o en cobertizos, como hacían algunos.

Después de que el rey les había concedido libertad
de consciencia a personas de todas las persuasiones,
hizo todo lo que pudo para introducir el papismo en Inglaterra;
porque le permitió a los Jesuitas que erigieran una universidad en el Savoy, en Londres,
y les permitió a los frailes pasear públicamente con los atuendos de sus órdenes monásticas.
Esta era una visión muy extraña para los Protestantes en Inglaterra;
y provocó no poca fermentación en las mentes de las
personas cuando los becarios de la facultad de Magdalen,
en Oxford, fueron desposeídos por orden del rey para abrirles paso a los Romanistas.
Esta fue una usurpación tan abierta, que W. Penn no dejó de culpar al rey por ella,
y de decirle que ese era un acto que no podía ser defendido en justicia,
ya que la libertad general de consciencia no permitía privar
de su propiedad a nadie que hacía lo que debía hacer,
como parecían haber hecho los becarios de dicha facultad.
Pero esto no pudo enfriar el celo del rey por el papismo,
porque sin ningún disimulo siguió adelante tan rápido y a tal grado,
que el embajador del papa, Fernando d`'Ada,
hizo su entrada pública a Windsor ese verano con gran pompa.

Se hicieron entonces grandes esfuerzos para derogar "`las leyes de prueba y penales,`"^
footnote:[Las "`leyes de prueba y penales,`" eran leyes aprobadas contra
los católicos romanos en Gran Bretaña e Irlanda después de la Reforma,
que penalizaban la práctica de la religión católica
romana y los excluían de ocupar cargos públicos.]
porque si se conseguía este punto,
los papistas podrían ser admitidos en el gobierno al igual que los demás. Como
la libertad general de consciencia estaba provocando un espectáculo seductor,
varios disidentes (tanto Bautistas como otros) le
sirvieron al rey con sus plumas por este motivo,
y W. Penn que siempre había defendido la libertad de consciencia con buenas intenciones,
no se quedó inactivo en este asunto,
aunque tal vez se haya quedado corto en sus expectativas.
Recuerdo cuando en aquellos días los partidarios de la iglesia de Roma
afirmaban que la libertad de consciencia era un deber Cristiano.
En referencia a esto escuché a uno decir:
"`¿Puede el etíope cambiar su piel o el leopardo sus manchas?`"
El rey también se esforzó por persuadir al príncipe y a la princesa de Orange,
para que dieran su aprobación a la derogación de las "`leyes
de prueba y penales,`" pero no pudo obtenerla de ellos.
Y como el rey hizo que el abogado James Stuart^
footnote:[Sir James Stewart de Goodtrees (o Steuart; 1635-1713) fue un abogado escocés,
opositor político de los Estuardo y Lord Advocate reformador de Escocia.]
le escribiera con respecto a este asunto al señor
Fagel (consejero y principal pensionario en La Haya),
Fagel respondió a este documento en una carta al mencionado James Stuart,
en la que declaraba la opinión del príncipe y de la princesa en este caso;
que ellos estaban dispuestos a aprobar la derogación de las leyes penales,
en la medida que tuvieran que ver con el ejercicio de la adoración,
pero en cuanto a las que excluían a los papistas de sentarse en el Parlamento,
no podían dar su asentimiento para la derogación de esas limitaciones.
Esta carta fue aprobada en general por los Protestantes en Inglaterra, no obstante,
el rey continuó con la introducción del papismo, y a principios del año 1688,
no sólo instaló a varios romanistas en Oxford,
sino que se esforzó también por introducir a varios de su persuasión en la magistratura.
Ahora bien, para encubrir mejor ese propósito,
buscó que otros disidentes fueran también escogidos;
pero en general rechazaron la oferta, como lo hizo Stephen Crisp en Colchester,
quien era demasiado prudente como para caer en esa trampa, y por eso declinó la oferta.

El 27 del mes llamado Abril fue publicada de nuevo la declaración
del rey a favor de la libertad de consciencia,
para mostrar que era firme y constante en su resolución,
y que sus intenciones no habían cambiado desde que la había emitido la primera vez.
También buscó animar a su súbditos a unirse a él,
y a elegir miembros para el Parlamento que pudieran poner
de su parte para finalizar lo que él había comenzado.
Ahora bien, a dicha declaración se le anexó una orden del consejo,
para que fuera leída en todas las iglesias y capillas en todo el reino;
y también se les ordenó a los obispos que enviaran y distribuyeran la declaración en
todas sus diócesis para que fuera leída como correspondía.
No obstante, ellos se negaron a hacerlo, alegando que no era legal, si bien,
algunos de estos obispos se oponían sin ninguna duda a la libertad de consciencia.
Entonces el arzobispo de Canterbury y otros seis obispos,
le pidieron al rey que no insistiera en la distribución y lectura de su declaración,
afirmando que su gran aversión a la distribución
y publicación de dicha declaración en sus iglesias,
no procedía de ninguna falta de deber o desobediencia a su majestad,
ni de la falta de la debida ternura hacia los disidentes, sino únicamente,
porque tal orden estaba basada en un poder dispensador que
a menudo había sido declarado ilegal en el Parlamento.

Esta negativa molestó tanto al rey, que envió a estos obispos a la torre de Londres.
Mientras estaban confinados, en todas partes se hablaba mucho de este asunto,
y dado que era bien sabido que algunos obispos habían
sido los promotores de la anterior persecución,
parece que algunos también hablaban contra los hombres que estaban en ese momento confinados.
Cuando se les informó de esto, dijeron que los Cuáqueros los calumniaban,
al proclamar que ellos (los obispos) habían sido
la causa de la muerte de algunos de ellos.
Esto le dio la oportunidad a Robert Barclay de visitar a los obispos en la torre,
y hablando con ellos,
les dio pruebas innegables de que algunas personas
habían sido mantenidas en prisión hasta su muerte,
por orden de los obispos,
aunque habían sido advertidos por médicos que no eran Cuáqueros,
del peligro que corrían esas personas.
Esto fue tan evidentemente demostrado por R. Barclay, que los obispos no pudieron negarlo.
No obstante, Barclay les dijo, que dado que ellos estaban en ese momento bajo opresión,
la intención de los Cuáqueros no era en ninguna manera hacer público esos asuntos,
no fuera ser que exasperaran al rey contra ellos otra vez.
Y en efecto,
tuvieron cuidado de no hacer nada que pudiera agravar el caso de estos prisioneros,
porque no era el momento de frotar viejas llagas,
ya que los obispos parecían estar inclinados a declarar a favor de la libertad de consciencia.
Y dado que esta libertad ya era disfrutada en todo el reino,
los llamados Cuáqueros pensaron conveniente en su
reunión anual (que fue celebrada ese verano en Londres),
redactar de nuevo una carta al rey y ponerlo al corriente
de una cosa más que continuaba siendo un problema para ellos.
La carta que le presentaron es como sigue:

[.embedded-content-document.letter]
--

[.letter-heading]
Al rey James II sobre Inglaterra, etc.

[.offset]
La humilde carta del pueblo llamado Cuáqueros, de su Reunión Anual en Londres,
el día 6 del mes llamado Junio de 1688.

Nosotros, súbditos amorosos y pacíficos del rey,
procedentes de varias partes de sus dominios,
habiéndonos reunido en esta ciudad según nuestra costumbre,
para examinar los asuntos de nuestra sociedad Cristiana en todo el mundo,
pensamos que es nuestro humilde deber presentarle los benditos efectos
que ha tenido la libertad que gentilmente le ha concedido a su pueblo,
tanto en nuestras personas como en nuestros patrimonios.
Porque mientras que antes nos traían largas y penosas
listas de casi todas partes de sus territorios,
contándonos de prisioneros y saqueos de bienes por parte de hombres malos y violentos,
todo por motivos de consciencia, ahora bendecimos a Dios y agradecemos al rey,
que las cárceles están vacías en todas partes,
excepto por casos de diezmos y reparaciones de iglesias parroquiales,
y unos pocos por juramentos.
Por tanto, nosotros con toda humildad le pedimos al rey,
que considere las penurias bajo las que todavía están nuestros
amigos por causa de consciencia en estos aspectos;
quienes, por un lado, están expuestos a la ira actual del clero ofendido,
que últimamente ha encarcelado a algunos de ellos hasta la muerte; y por otro lado,
resultan muy poco rentables tanto para el público como para ellos mismos.
Y así como humildemente esperamos que pueda aliviarlos,
así confiamos en que nos aliviará en todo lo que pueda.

Ahora, puesto que te ha placido, oh rey,
renovarles a todos tus súbditos tu amable intención de proseguir con el
establecimiento de esta libertad Cristiana sobre un fundamento inalterable,
y a fin de cumplir con esto, celebrar un Parlamento el próximo Noviembre,
nos consideramos profundamente comprometidos a renovar
nuestra garantía de fidelidad y afecto,
y con la ayuda de Dios,
a poner de nuestra parte para que se complete tan bendita y gloriosa obra, de manera tal,
que quede fuera del poder de alguna de las partes herir a la otra por motivos de consciencia.
Y como creemos firmemente que Dios nunca abandonará esta causa justa y recta de la libertad,
ni abandonará al rey en su mantenimiento, esperamos por la gracia de Dios,
dejar que el mundo vea que podemos apoyar honestamente y de corazón la libertad de consciencia,
y aun así, ser enteramente fieles a nuestra propia religión,
cualquiera que sea la locura o malicia de algunos hombres que puedan sugerir lo contrario.

--

Esta carta presentada al rey fue bien recibida.
Algunos han pensado que la última parte de esta carta se refería al oficio de magistrado,
oficio que, según se cree,
un Cristiano puede desempeñar sin más incompatibilidad con una vida inocente,
que la incompatibilidad de un padre piadoso cuando
le da la debida corrección a su hijo rebelde.
Porque aunque nuestro Salvador nos dice que no resistamos al que es malo,
sino que amemos a los enemigos;
y cuando Pedro por un celo precipitado le cortó la oreja al siervo del sumo sacerdote,
y Cristo lo reprendió diciendo:
"`Mete tu espada en la vaina;`" y aunque el apóstol
Santiago también desaprueba la guerra y los pleitos;
aun así,
encontramos en las Escrituras que el apóstol Pablo llama al magistrado
"`servidor de Dios para bien,`" y "`vengador para castigar al que
hace lo malo;`" diciendo en términos claros,
que "`no en vano lleva la espada.`"^
footnote:[Romanos 13:3-4]

Pero volviendo a mi relato y retomando el hilo de esta historia
del que me desvié un poco por este paréntesis;
sé que había algunos en esos días que pensaban que si personas de todas
las persuasiones en Inglaterra tuvieran una participación en el gobierno,
proporcional a su número,
se podrían encontrar los medios para impedir que cualquier partido,
especialmente los papistas,
se exaltara por encima de los demás. Pero a mí me parece probable,
que si esto hubiera tenido efecto,
el tiempo habría demostrado que estos hombres estaban equivocados en sus apreciaciones.
No obstante, esto nunca llegó a pasar, porque el poder del rey ya se estaba tambaleando,
aunque él se esforzaba por mantenerlo, incluso con buenos medios.

Había entonces en Norwich casi cuarenta personas del pueblo llamado Cuáqueros,
quienes habiéndole pedido al rey que se complaciera en hacerlos hombres libres,
obtuvieron la siguiente orden de él:

[.embedded-content-document.legal]
--

[.signed-section-context-open]
A nuestro fiel y estimado Procurador General.

[.signed-section-context-open]
James R.

[.salutation]
Fiel y estimado, te saludamos cordialmente:

Considerando que hemos recibido un buen informe de
la lealtad de nuestros muy estimados súbditos,
Thomas Howard, Peter Launce, William Booley, Henry Jackson, Edward Pears, John Jenn,
Nicholas Comfit, John Harridence, John Gurney, Samuel Wasey, Edmund Cobb, Philip Paine,
Josiah Sherringham, Anthony Alexander, Thomas Darmar, John Cadee, John Fiddeman,
William Kiddle, James Pooley, John Defrance, Jr., Daniel Sharpen, William Milchar,
William Brown, John Sharpen, Jr., Samuel Kettle, Stephen Ames, Richard Rose,
Benjamin Stud, Edward Monk, John Cornish, John Hodson, James Polls, Michael Parker,
Richard Brown, Daniel Dye, Jr., John Elsegood, John Pike, y John Allen,
hemos pensado oportuno pedirte por la presente,
que de inmediato hagas a todos y a cada uno de los arriba mencionados,
hombres libres de nuestra ciudad de Norwich,
con todos los derechos y privilegios que les corresponden,
sin presentarles ningún juramento, o juramentos de ningún tipo,
lo que estamos agradablemente complacidos de dispensar a su favor.
Y para hacerlo, esta será tu orden; y así nos despedimos.

Dado en nuestra corte en Whitehall, el día 13 de Julio de 1688,
el cuarto año de nuestro reinado.
Por orden de su majestad.

[.signed-section-signature]
Sunderland.

--

Muchos decían entonces que el rey no tenía derecho a hacer esto;
y aquellos que les negaban a los Cuáqueros esta libertad,
no dudaron en describir la orden del rey con colores muy desfavorables; de hecho,
incluso llegaron a afirmar que William Penn había aconsejado al
rey que hiciera lo que no podía hacer sin quebrantar su promesa.
Sin embargo, si el rey no hubiera cometido una mayor infracción que ésta,
su reinado podría haber durado más tiempo; pero su expulsión de los becarios de Oxford,
el encarcelamiento de los obispos y el reconocimiento público de los Jesuitas y monjes,
causó gran efervescencia en las mentes de las personas.
Entonces, los siete obispos fueron juzgados en el tribunal del rey, en Westminster-Hall,
pero fueron absueltos y puestos en libertad.
El rey también nombró algunos "`comisionados eclesiásticos,`"
pero muchos consideraron esto como un tipo de inquisición,
y no parecía estar de acuerdo con la verdadera libertad de consciencia,
que si él hubiera mantenido justamente,
es probable que no hubiera llegado a una situación
tan difícil como la que encontró pronto.

No mucho antes de este tiempo, una tal Theophila Towsend,
una mujer de años y entendimiento,
publicó un libro en el que relataba la grave persecución que sus amigos
en Gloucestershire habían sufrido por encarcelamientos y saqueo de bienes,
y cómo ella misma había padecido también muchos sufrimientos,
y había estado prisionera en el castillo de Gloucester
durante más de tres años. Entre otras cosas,
relata, cómo un tiempo antes de su encarcelamiento,
había sido arrestada en la calle por orden de los jueces Thomas Cutler y James George,
momento en el que le dijo a este último,
que el Señor defendería su causa y que cualquier medida que él usara,
con esa misma medida sería medido.
Y así sucedió, porque antes de que ella fuera liberada de la prisión,
la esposa del mencionado James George (quien había separado
a Theophila de su marido) fue separada de él por la muerte.
Un tiempo después de esto, J. George llegó con el obispo de Gloucester a una reunión,
donde Theophila estaba orando de rodillas.
El obispo le preguntó a George si ella era la mujer de la que le había hablado,
y él respondió: "`Sí,
mi señor;`" el obispo la tomó por el brazo con tal
violencia que casi la tira hacia atrás,
diciendo: "`Entrégate, mujer, y obedece a los oficiales del rey.`"
Pero el celo de ella era tal, que su oración no podía ser detenida,
porque cuanta más oposición encontraba,
más se sentía animada e inspirada a alabar a Dios por Su bondad.
Y aunque el obispo incitaba al juez,
no parecía estar en su poder detener la corriente de las palabras de ella;
de modo que la dejaron en paz hasta que finalizó y se puso de pie.
Luego, se pusieron por escrito los nombres de los que se habían reunido,
y fue un tiempo después de esto, que ella, aunque anciana y débil,
fue conducida durante el invierno por cuatro o seis kilómetros a través de la nieve,
y encarcelada en Gloucester, donde permaneció tres años y cuatro meses,
y luego fue liberada por el rey James.

Después ella publicó un libro, como se ha dicho,
en el que relata cómo algunos de sus amigos habían sido golpeados,
apaleados y maltratados a tal grado, que murieron por sus heridas,
como ella misma testificó haber visto.
"`No obstante,`" dijo, "`aunque murieron muchos que eran más fuertes que yo,
le plació al Señor preservar mi vida para que pudiera
hablar para la alabanza de Su nombre,
y para que contara Sus maravillas, y les recordara una vez más a ustedes, perseguidores,
lo que corresponde a la paz de ustedes.
Bendito sea el Señor; Él se ha levantado por amor a Sion,
la que ustedes han arado por largo tiempo como un campo.
Y cuando los enemigos de ellos hayan hecho lo peor,
entonces el Señor hará que Su Sion sea una gloria eterna,
y Su Jerusalén la alabanza de toda la tierra.
Y así como ustedes pueden ver en los demás que la persecución es mala,
véanla en ustedes mismos también, y arrepiéntanse en polvo y ceniza.
Recuerden quién fue el que dijo: '`El sabio tiene sus ojos en su cabeza,
mas el necio anda en tinieblas.`' El ojo del necio busca errores en otros,
culpan a otros de lo que ellos mismos son culpables.`"
Y así continuó y reprendió a los informantes que
se habían enriquecido con el saqueo de sus vecinos;
y relató también cómo el sacerdote de Gloucester
había firmado con su nombre una petición al rey,
en la que el juez J. George y otros querían que la casa de reunión de los Cuáqueros
fuera cedida al pueblo para hacer una casa de trabajo para los pobres.
"`Pero,`" dijo ella, "`esto es como Judas, quien,
cuando llegó la mujer con un frasco de alabastro de perfume de nardo de gran precio,
dijo: '`¿Por qué este desperdicio?
¿Por qué no fue vendido este perfume y el dinero dado a los pobres?`'
Pero la Escritura dice que lo dijo '`no porque se cuidara de los pobres,
sino porque era ladrón, y teniendo la bolsa, sustraía de lo que se echaba en ella.`'`"

Luego, hablándole a los que habían participado en el saqueo de los bienes,
y exponiendo lo odioso de esa obra, dijo al final:
"`No escribo esto desde un espíritu de venganza contra nadie,
sino en el amor de Dios para advertirlos y exhortarles al arrepentimiento,
para que encuentren misericordia en el Señor, lo cual es el verdadero deseo de mi alma.
Puedo decir verdaderamente, en presencia del Señor,
que no tengo nada en mi corazón sino amor y buena
voluntad para el peor de nuestros enemigos,
y esto con pureza de corazón y sinceridad de mente.
Realmente deseo la paz y el bienestar eternos de ustedes,
aunque hayan endurecido sus corazones contra el Señor, contra Su verdad y Su pueblo.
¡Vuélvanse al Señor, se los ruego!
Inclínense delante del Todopoderoso,
quien juzgará a toda carne y llamará a todos a cuentas,
y recompensará a cada uno según lo que haya hecho mientras estaba en el cuerpo,
sea bueno o malo.
Consideren esto mientras tienen tiempo, y ocúpense de las cosas que pertenecen a su paz,
antes de que sean escondidas de sus ojos.
Porque la longanimidad del Señor llegará a su fin, quien dijo:
'`No contenderá mi espíritu con el hombre para siempre.`' Por tanto,
mientras el Espíritu del Señor, Su luz,
Su gracia contienda en sus corazones para volverlos de sus malos caminos,
dispónganse a abrazarlo, a creer en Él, a tomar consejo de Él,
a someterse a Él con todo el corazón. Dispónganse a ser conducidos y guiados por Él,
e inclinen sus corazones para seguirlo en todas las cosas,
y entonces Él los conducirá al reposo y a la paz con el Señor para siempre.`"
Ella dijo mucho más,
pero me interrumpo aquí. Algunos perseguidores han
sido tan tocados por discursos como estos,
que se han convertido en Cristianos inofensivos.

Casi he llegado a la conclusión de mi relato sobre la persecución;
acerca de la cual pude haber escrito mucho más,
pero no quise extenderme en mi obra más allá de lo que habría podido completar.
Sin embargo, antes de terminar completamente con este asunto,
mencionaré algo con respecto a Theophilus Green, de quien se ha hecho mención antes.
Él vivía en Battersea, no muy lejos de Londres,
y era un hombre querido por sus vecinos debido a su conducta honesta; aun así,
fue muy perseguido por asistir a las reuniones y por predicar.
Sucedió en una ocasión,
que unos oficiales llegaron a su casa para ver si había una reunión,
y se portaron moderadamente, porque su llegada parecía ser contraria a su deseo,
al ser sólo por obediencia a la orden del juez Duke, quien,
por motivos de un delito anterior,
había emitido órdenes judiciales para confiscar bienes.
Estos oficiales que no se sentían contentos con el caso,
y viendo que no se estaba llevando a cabo una reunión,
siguieron su camino y devolvieron la orden.
Después T. Green fue a ver al mencionado juez y le dijo:
"`Considera lo que esa boca y lengua tuyas han dicho anteriormente;
que yo siempre he sido amable contigo.
¿Y esto es lo que das a cambio?
Ten por seguro que el Dios a quien sirvo, y por cuya causa sufro ahora, me vengará,
porque del Señor es la venganza; y Él la pagará de una u otra manera,
a menos que tú te arrepientas rápidamente.`"
Al oír estas palabras, el juez empezó a temblar y gritando dijo:
"`¡No te haré más daño que el que hago a mi propia alma!
Por favor, ve a los oficiales y diles que nunca volveré a molestarlos por tu causa.`"
Y así lo hizo Green, y los oficiales se alegraron por eso.
Pero cuando este juez fue despedido más tarde por causa de alguna queja,
un tal sir John Broadrick lo sucedió en el cargo,
y mantuvo a Theophilus y a sus amigos fuera de su
casa de reunión por casi dos años y medio.

Después se les permitió ir de nuevo a su casa de reunión,
pero un tal juez Forster llegó y tomando sus nombres,
multó a Theophilus con diez libras como predicador.
Después de esto,
el mencionado juez y algunos otros llegaron con un
alguacil para confiscar bienes para cobrar la multa.
Cuando el alguacil llegó a la puerta de la casa dijo: "`Vecino Green,
¿dónde estás? Hemos venido a confiscar tus bienes si nos dejas entrar.`"
Pero esto disgustó tanto al juez,
que echándole un vistazo a la propiedad y viendo algunos remos y mástiles,
le ordenó al alguacil que se los llevara.
A esto el alguacil le respondió: "`Yo no soy un cargador.`"
"`Entonces,`" dijo el juez, "`ordena que otros lo hagan.`"
A lo que el alguacil replicó: "`Te ordeno a ti que lo hagas.`"
Esto enfureció tanto al juez que lo multó.

Un tiempo después,
el juez Forster llegó otra vez con un alguacil de alto rango y otro de menor rango,
y confiscó un pequeño bote, e hizo que se lo llevaran, e intentó venderlo varias veces,
pero nadie quería comprarlo.
Y después de que lo había llevado de un lugar a otro para venderlo,
finalmente fue encontrado a la deriva por alguien que no sabía que había sido confiscado,
y cuando el hombre que lo encontró oyó que era de Theophilus,
se lo llevó. Pero Theophilus fue donde los alguaciles y
les dijo dónde estaba el bote y cómo le había sido devuelto,
y dijo, que ya que lo tenía de nuevo estaba dispuesto a dejárselo;
pero que si se lo llevaban de nuevo,
no se los impediría. Cuando se le informó esto al juez,
envió una orden y encarceló a Theophilus en la prisión de Marshalsea.
Después de tres semanas se celebró la sesión del tribunal en Marshalsea,
y el último día el mencionado juez se presentó en la prisión y le dijo:
"`He venido a verte por amor y a aconsejarte para tu bien, que pagues la multa.
Porque estoy seguro de que el gran jurado ha fallado en tu contra, y si fueras liberado,
tengo tal influencia sobre el juez que haré que te presente el juramento,
y sé que no lo prestarás. Luego quedarás bajo la sentencia de premunire,
y es probable que no salgas de prisión mientras vivas.`"
A lo que Theophilus respondió: "`Dices que vienes por amor a aconsejarme para mi bien,
pero por lo que has dicho parece todo lo contrario;
porque ahora me doy cuenta de que has tramado contra mí todo el mal que has podido.
En cuanto a la multa, aunque sólo fueran diez peniques,
no la pagaría. Y si el Señor te permite hacer lo que has dicho,
y ser la causa de llevar mis canas cuanto antes hasta la tumba,
mi sangre estará a tu puerta y clamará venganza contra ti.`"

Al día siguiente los dos alguaciles fueron llamados delante del gran jurado,
donde se les preguntó lo que tenían que decir contra Theophilus Green.
El alguacil de alto rango respondió: "`En cuanto a Theophilus Green, aunque Cuáquero,
es un hombre tan honesto como los que viven por aquí. Él recientemente
estuvo a cargo de los pobres y se comportó tan bien en ello,
como cualquiera lo ha hecho en los últimos veinte
años. Y con respecto al bote por el que es acusado,
cuando se lo devolvieron,
él llegó donde nosotros y nos dijo cómo había llegado y dónde lo había puesto, diciendo,
que si nosotros se lo quitábamos de nuevo,
él no nos lo impediría. Esto es todo lo que tenemos que decir.`"
Algunos de los miembros del gran jurado conocían muy bien a Theophilus,
y la causa también, lo que no favorecía mucho al juez; y en cuanto a la acusación,
la declararon __ignoramus__.^
footnote:[La decisión de un gran jurado de que no hay pruebas que respalden los cargos,
en virtud de la cual se suspenden todos los procedimientos y el acusado queda en libertad.]
Así, Theophilus fue absuelto por proclamación, y sir Richard How,
uno de los miembros del jurado, le aconsejó que procesara al juez,
pues había dos cargos muy claros contra él, a saber, difamación y falso encarcelamiento.
Pero Theophilus le dijo que reconocía el amor de ellos,
pero que le dejaría el asunto al Señor por cuya causa sufría;
porque la venganza era del Señor y Él la pagaría. Y poco tiempo después de esto,
el mencionado juez Forster murió, según se informó, en gran terror y miseria.
No sé con exactitud el momento en que sucedió esto, sin embargo,
creo que fue unos años antes de la época que ahora describo.

Antes de concluir este año, debo mencionar algo con respecto a William Penn,
quien cuando el gobierno del rey se estaba hundiendo,
no sólo fue acusado de muchos errores, sino que algunos lo llamaban papista,
aunque esto era totalmente falso.
Pero Penn tenía muchos enemigos,
y no era nada nuevo que se tildaran a los Cuáqueros con el odioso nombre de Jesuitas;
porque treinta años antes de este momento,
se habían hecho grandes esfuerzos en Bristol por persuadir a la gente de que eran Franciscanos.
William Penn soportó pacientemente la calumnia de ser tachado como papista,
diciendo poco para justificarse,
hasta que finalmente respondió a una carta que alguien le envió,
rogándole seriamente que respondiera a las acusaciones que se habían inventado
contra su reputación. En este documento atribuyó su libre acceso al rey,
en parte, a la relación que su padre, como almirante,
había tenido al servicio del rey cuando todavía era
el duque de York y alto almirante de Inglaterra;
y también, por su favor al liberarlo de la torre de Londres en 1669.
A esto añadió:

[.embedded-content-document.letter]
--

La humilde solicitud que mi padre le hizo en su lecho de muerte fue,
que me protegiera de las inconveniencias y dificultades
a las que mi persuasión religiosa pudiera exponerme,
lo cual él amablemente prometió hacer, y ha cumplido además con exactitud.
Cuando todo esto es considerado, cualquiera que tenga la menor pretensión de bondad,
gratitud o generosidad, debe necesariamente saber cómo interpretar mi acceso al rey.
Por tanto, ¿hay algo más insensato, además de falso, que sugerir,
que debido a que a menudo estoy en Whitehall,
debo ser el autor de todo lo que se hace ahí que no agrada a la gente en el exterior?
Pero suponiendo que algunas de esas cosas hayan sido hechas, por favor díganme,
si estoy obligado a oponerme a algo que no estoy llamado a hacer.
Nunca he sido miembro del consejo, gabinete o comité,
donde se tratan los asuntos del reino.
Nunca he tenido un cargo o confianza, y por consiguiente,
no puede decirse que yo haya hecho algo.
Y a menos que ir a Whitehall una vez al día, en muchas ocasiones, o que no sea rechazado,
sea la prueba de mi acuerdo con cosas desagradables,
no sé qué más pueda alegarse contra mí con alguna verdad.

No dejo de temer la causa de ese comportamiento hacia mí; es decir,
por mi constante celo por la libertad imparcial de consciencia; pero si así debe ser,
la causa es demasiado buena como para estar dolido por ella.
Siempre he entendido dicha libertad como un derecho natural de todos los hombres,
y que el que tiene una religión sin ella,
su religión no es de él. Porque si no es una religión escogida por el hombre,
entonces es la religión de otro que la impone; así pues,
la libertad de consciencia es el primer paso para tener una verdadera
religión. Esta opinión no es nueva para mí. He escrito varias apologías
durante los últimos veinte años defendiéndola,
y eso imparcialmente.
Sin embargo, he declarado constantemente,
que se debían establecer límites a esta libertad, y que la moral era el mejor límite;
y que cuando la moral fuera violada bajo el pretexto de consciencia,
era adecuado que el poder civil tomara su lugar.
Ni una sola vez he pensado en promover algún tipo de libertad de consciencia,
para alguien que no preserve el reino Protestante
común y los antiguos derechos del gobierno;
porque a decir verdad, uno no puede mantenerse sin el otro.

--

De este pequeño extracto de la defensa de William Penn,
se desprende suficientemente qué tipo de libertad defendía;
y dicha libertad tomó lugar posteriormente en el reinado del siguiente rey.

He guardado silencio por largo tiempo con respecto a George Fox,
y no he encontrado ningún asunto notable que tenga que ver con él en este tiempo,
salvo que escribió mucho, tanto para la edificación de sus amigos,
como para la instrucción y amonestación de otros.
Él estaba continuamente ocupado con el cuidado de la iglesia,
y deseoso de que las cosas se mantuvieran en buen orden, y entonces,
para realizarlo de la mejor manera,
se quedó por un largo tiempo en Londres y sus alrededores.

Este año murió William Dewsbury,
uno de los primeros predicadores entre los llamados Cuáqueros,
habiendo sido un predicador muy celoso y un eminente
instrumento para la conversión de muchos.
Nació en Yorkshire y en su juventud fue pastor,
y después fue colocado como aprendiz de un fabricante de ropa,
pero cuando estallaron las guerras civiles se convirtió
en soldado y se unió a los que decían luchar por el evangelio.
Ahora bien, aunque era religioso según su entendimiento, aun así,
creciendo cada vez más en seriedad y volviendo su mente al interior,
vio que allí había enemigos internos y espirituales que enfrentar,
según el dicho del apóstol: "`No tenemos lucha contra sangre y carne,
sino contra huestes espirituales de maldad...`" Y este estado le
fue manifestado interiormente en las palabras de nuestro Salvador:
"`Mete tu espada en la vaina.
Si mi reino fuera de este mundo,
mis servidores pelearían.`" Esto obró tan poderosamente en su mente,
que no pudo involucrarse más con los asuntos militares,
sino que dejó el ejército y regresó a su antiguo oficio,
esforzándose por crecer en la verdadera piedad, en la que avanzó tanto,
que cuando George Fox llegó a Balby, en Yorkshire,
en el año 1651 y predicó el evangelio ahí,
no pudo sino aceptar la doctrina declarada por él como la
misma de la que ya había sido convencido en su mente,
a saber, que se le debe prestar atención a la reprensión Divina en el interior,
cuando señala lo que es malo.
Esta doctrina fue predicada por George Fox bajo el nombre de "`la
luz verdadera que alumbra a todo hombre que viene a este mundo;`"
diciendo que esa luz debe ser tenida en cuenta,
por ser la manifestación de esa gracia que "`trae salvación`" y
"`se ha manifestado a todos los hombres,`" (Tito 2:11). W. Dewsbury
no sólo estuvo de acuerdo con G. Fox en este punto de doctrina,
sino que con el paso del tiempo se convirtió en un celoso predicador de ella,
por lo que cayó bajo grandes sufrimientos; a tal punto,
que estuvo preso en Warwick diecinueve años por causa de la religión,
además de los encarcelamientos que sufrió por el mismo motivo en otros lugares.
Pero una vez liberado,
llegó a Londres en el mes llamado Mayo y predicó allí un sermón con respecto a la regeneración,
el cual fue tomado de su boca en taquigrafía y publicado después como sigue.

[.embedded-content-document.address]
--

[.letter-heading]
Sermón predicado por William Dewsbury en Gracechurch Street,

[.signed-section-context-open]
el 16 del mes Tres de 1688

[.salutation]
Mis Amigos,

[.offset]
A menos que sean regenerados y nazcan de nuevo, no pueden heredar el reino de Dios.

Esta es la palabra del Señor Dios para todos los hombres hoy.
Esto no se encuentra en una profesión superficial, en vana imaginación,
o en cualquier otra cosa con la que puedan engalanarse; no,
cada hombre y mujer en particular debe nacer de nuevo, o de lo contrario,
no podrá entrar en el reino de los cielos.
Esta era la doctrina de Cristo cuando estaba en el '`cuerpo preparado,`'^
footnote:[Hebreos 10:5]
en el que apareció en el mundo y le predicó a Nicodemo esta inmutable doctrina,
y es la doctrina que continúa hasta este momento,
y continuará mientras un hombre respire sobre la tierra.
No hay otro camino, ninguna otra puerta para entrar en la vida,
sino por esta gran obra de regeneración.

Ahora bien, para llegar a esta gran obra,
avanzar y viajar de la tierra al cielo (habiendo sido expulsados todos
del Paraíso por los querubines colocados junto con una espada encendida),
deben saber que no hay regreso a esa bendita vida,
sino mediante la pérdida de la vida que aflige al Espíritu de Dios,
y que hizo que el hombre fuera expulsado.
No hay otra manera de volver sino por medio del nuevo nacimiento.
Así como todos han sido expulsados y forzados a salir del Paraíso,
y los querubines y la espada encendida están colocados
para guardar el camino al árbol de la vida,
así deben regresar al favor de Dios, por medio de la luz de Cristo, y "`línea tras línea,
precepto tras precepto, un poquito aquí, un poquito allá`"^
footnote:[Isaías 28:10, 13]
dirigir sus mentes a la luz de Jesucristo.
Y así como '`el primer Adán fue hecho un alma viviente;
así el postrer Adán es un espíritu vivificante.`' Sepan esto con certeza,
que ningún hombre o mujer puede ser vivificado y levantado en la vida del postrer Adán,
hasta que la vida del primer Adán le sea quitada.

Así, pues,
cada uno trate sinceramente con su propio corazón. ¿Han llegado
ustedes a ser un pueblo muerto a la vida del primer Adán,
en cuya vida está obrando el misterio de iniquidad en cada parte del hombre?
Unos claman: "`Mirad, aquí está el Cristo;`" otros: "`Mirad,
allí está;`" y cada uno sigue su propia imaginación acerca de la letra de la Escritura.
Pero esto no es más que el espíritu vano del hombre
que corre y se esfuerza por rescatarse a sí mismo;
y esta es la causa de que haya tanta profesión de Dios,
y tan poco de Su naturaleza manifestándose entre los hijos y las hijas de los hombres.
Pero todos ustedes que buscan ser regenerados, deben ir a la luz de Cristo;
no hay otro camino para ello.
Él escudriñará sus corazones, tratará sus mentes,
pondrá sus pecados en orden delante de ustedes y
descubrirá las iniquidades que los rodean.
Deben ver que son un pueblo perdido, un pueblo pecador,
y así sentir el peso de sus pecados sobre sus consciencias.
No hay otra manera de llegar a la vida.
Nunca se quejarán del pecado hasta que sean agobiados por él,
hasta que una trompeta suene en sus oídos y los despierte,
para que se levanten de entre los muertos y Cristo les dé luz.

No hay otro camino, querido pueblo,
deben llevar sus obras a la luz de Cristo y permanecer
en la sentencia de condenación. Si salvan sus vidas,
las perderán; y si pierden sus vidas por causa de Cristo,
su vida eterna no corre peligro.
Juan el Bautista, el precursor de Cristo, declaró: "`Yo a la verdad os bautizo en agua;
pero viene uno más poderoso que yo,
de quien no soy digno de desatar la correa de su calzado;
él os bautizará en Espíritu Santo y fuego.
Su aventador está en su mano, y limpiará su era, y recogerá el trigo en su granero,
y quemará la paja en fuego que nunca se apagará.`" ¿De qué les
sirve leer las Escrituras si no conocen este bautismo de fuego,
el que todos los regenerados deben experimentar?
No se engañen,
Cristo aparecerá en llama de fuego y tomará venganza
de todos aquellos que no conocen a Dios,
y que no obedecen el evangelio de nuestro Señor Jesucristo.

Hoy estoy aquí como testigo del Señor de vida,
no hay forma de que las personas lleguen a la salvación,
sino conociendo a Cristo revelado en sus corazones.
¿Qué está haciendo Él allí sino tomando venganza de la mente carnal,
de toda la autocomplacencia y de los afectos desordenados?
Él viene con venganza para quitarles la vida;
Él los bautizará con el Espíritu Santo y con fuego.
Si no conocen este bautismo, no son verdaderos Cristianos.
Nunca mirarán a la muerte a la cara con gozo, ni descenderán a la tumba con triunfo.
Si viven como en casa en el cuerpo, huyen por sus vidas,
y no están dispuestos a perderla por Cristo si son llamados a ello;
y si no quieren que Cristo los lave (algunos rechazarán
esto por timidez y otros por amor al yo) yo les digo,
que si Cristo no los lava,
no tiene parte con Él. Deben ir a Cristo para que los purifique en el horno de fuego.
El día del Señor arderá como un horno (como lo dice el profeta); este es un día terrible,
un día de venganza, el día del Señor Jesucristo que redime a Su pueblo de sus pecados.
Sion es redimida con juicio y establecida con justicia.
No hagan el camino al cielo más fácil en sus mentes
e imaginaciones de lo que en realidad es,
ni crean que es suficiente vivir en un cumplimiento externo de los caminos de Dios.
Si sus voluntades permanecen vivas y sus corrupciones siguen sin ser crucificadas,
el juicio de Dios será la porción de ustedes.

Por tanto, en el nombre del Señor vengan conmigo.
He venido a declarar lo que he oído y visto del Padre.
Vengan y examinen sus consciencias.
¿Han llevado sus obras a la luz?
Si lo han hecho, entonces han recibido condenación sobre sí mismos,
y la altivez de ustedes ha sido abatida y humillada, y se ven a sí mismos pobres,
miserables y desventurados delante del Dios eterno.
Independientemente de lo que sepan de la mente de Dios, ¿han reformado sus caminos?
Vengan conmigo y díganme, ¿cuál es el fundamento de la fe y de la confianza de ustedes?
Lean el libro de la consciencia; ¿no tienen fundamento para su fe?
Se han revestido de la fe reformada, pero ¿han vivido una vida no reformada?

Examínate y pruébate, hombre o mujer.
¿Velas sobre ti mismo y te mantienes en un sentido de tu próxima destrucción,
pese a todas tus credenciales y reforma parcial?
¿Te esfuerzas por entrar por la puerta estrecha y el camino angosto,
para perder la vida de tu voluntad,
la vida del primer Adán? La justicia de Dios no te permitirá
hacer de tus deberes y credenciales un salvador;
o de tomar las joyas de Dios y adornarte con ellas.
No, tú no puedes ser salvo sin la justicia de Dios en Cristo Jesús. ¿Qué dice tu consciencia?
¿Estás siendo llevado a un cambio de tu mente y de tu conducta?
¿Estás dispuesto a separarte de tus pecados, junto con tu orgullo y altivez?
¿Estás dispuesto a separarte de tus viles afectos?
Esta es la obra de la gracia de Dios sobre ti.
¿Colocas tu confianza en tus deberes y cualidades,
y tomas las joyas y ornamentos de Dios y te engalanas con ellos?
"`Tomaste mis joyas,`" dice el Señor,
"`y te echaste como ramera;`" si te vuelves al Señor y te humillas,
y atraviesas esta tribulación, serás feliz para siempre.
Este juicio de Dios, esta espada encendida que se revuelve por todos lados,
te guardará de volverte al pecado.
Te llevará a Cristo y te separará de toda esperanza
de salvación que no sea a través de Él,
y te hará ver la absoluta necesidad de un Salvador,
y que tu vida está escondida con Cristo en Dios.

La infinita bondad de Dios para con los hombres consiste en "`apartar del varón la soberbia`"^
footnote:[Job 33:17], y humillarlos bajo Su poderosa mano.
Esta es la condición de las pobres criaturas a las que el
Altísimo les ha dado muerte por medio de Sus manos.
¿Cómo puedo saber si he sido matado y bautizado, y si he llegado a la sinceridad?
Los que tienen este bautismo entran a la vida celestial.
Si amas la luz de Jesucristo, así será contigo, Dios hará una obra rápida en tu tierra.
Pondrá tus pecados en orden delante de ti y te hará velar en oración,
te conducirá en santidad de vida y conducta,
y hará que te aborrezcas y que desprecies toda la pompa,
los placeres y vanidades de este mundo.
Cuando Él te haya adornado con Sus gracias, entonces mantente atento a la luz,
y en la luz de Cristo verás la luz, y sabrás que todo lo que has hecho y puedas hacer,
no es más que tu deber.
Y si esperas diligentemente verás más luz,
y la espada que sale de la boca de Cristo (quien es llamado la Palabra de Dios)
cortará todas tus esperanzas de salvación en cualquier cosa que hayas hecho,
en cualquiera de tus cualidades, y en cualquier cosa que puedas hacer;
de modo que serás un alma sin esperanza,
sin nada en tu propio sentido y comprensión. El poder
del primer Adán debe morir delante de Él,
y tú debes gritar: "`¡Soy una criatura muerta, perdida y deshecha!
Hay una vida escondida con Cristo en Dios para mí,
pero no podré tenerla hasta que haya muerto, y caiga en la voluntad de Dios,
me convierta en un niño pequeño,
y sea despojado de toda la excelencia que he alcanzado para mí. Debo llegar
a un sentido de mi propia miseria y postrarme a los pies de Dios.
Y cuando me haya convertido en un niño pequeño,
haya sido humillado y haya muerto a mi propia voluntad,
y a toda confianza en mi propia justicia, ciertamente viviré una vida santa.
Pero daré toda la vida que una vez tuve,
por esa vida que está escondida con Cristo en Dios.`"

¡Oh, cualquiera que llegue tan lejos no se perderá la vida eterna!
Todas las personas deshonestas que desean tener salvación por medio de Cristo,
pero que no lo dejan ejercer Su poder celestial, Su glorioso poder principesco,
para que los bautice en Su muerte,
ciertamente quedarán cortas de la salvación. Pero todas las que
se entregan a Cristo para ser redimidas a través del juicio,
y han llegado a ser como niños pequeños, estas están en un estado feliz.
Ustedes saben que nuestro Señor Jesucristo tomó a un niño pequeño en sus brazos y dijo:
"`De cierto os digo, que si no os volvéis y os hacéis como niños,
no entraréis en el reino de los cielos.`"
Todos deben llegar a ser como un niño pequeño,
y depender de la misericordia y gracia gratuita de Dios.
Todos deben llegar a una santa rendición de sus voluntades a la disposición de Dios.
Si van a Cristo como niños pequeños y dependen de Él,
no van a quedar cortos de Su salvación. Ésta es concedida
a las almas que oyen la voz de Cristo,
porque los que oyen la voz del Hijo de Dios vivirán.

Estoy aquí como testigo del Dios del cielo, yo nunca oí la voz de Cristo,
como seguidor Suyo, hasta que morí y fui bautizado,
y yací como un niño pequeño bajo Sus castigos celestiales.
Pero tan pronto como mi alma fue llevada a ese estado, en mi humillación, ¡oh, entonces!,
el terrible juicio fue quitado, el libro de la vida abierto para mí,
y el Señor me habló consoladoramente: "`Yo te he amado con amor eterno.`"
Por tanto, fui hecho Cristiano a través del día de venganza, ardiente como un horno,
y la altivez y el orgullo del hombre en mí fueron abatidos.
Ahora bien,
es a través de esta sumisión a la muerte de Cristo
que las personas pueden morir para vida;
y bienaventurados los muertos que mueren en el Señor,
porque ellos descansarán de sus trabajos y sus obras con ellos siguen.

¡Acaben entonces con sus propias voluntades, con su orgullo y altivez,
hipocresía y engaño, y con toda dependencia en cualquier cualidad propia!
Deben llegar a tener sus vidas separadas de ustedes, o de lo contrario,
perecerán. Aquellos que mueran con Cristo y estén dispuestos a morir por Él,
a éstos Él es revelado como Salvador.
Él vino a nosotros en los días de Su carne y cumplió con la voluntad de Su Padre.
Fue clavado en la cruz.
Cuando el Hijo de Dios llegó a la profundidad de Sus sufrimientos, clamó: "`Dios Mío,
Dios Mío, ¿por qué Me has abandonado?`"
Esto fue por tu causa y por la mía,
y por la de todo hombre y mujer que cree en Él. Él
bebió la copa que Su Padre le había dado a beber.
Si así se hizo con el árbol verde, ¿qué se hará con el seco?
Él fue delante de nosotros,
para que cuando venga de nuevo nos tome para Sí y nos saque de la inmundicia del pecado,
y podamos ser hechos nuevas criaturas.

Ahora, si no nacemos de nuevo, no podemos entrar en el reino de Dios;
y no nos convertimos en nuevas criaturas, hasta que hayamos muerto al viejo hombre.
Tú debes morir a tu orgullo y altivez, a la corrupción de tu propia voluntad,
y a todo egoísmo; Dios debe quemar estas cosas en ti.
El Espíritu Santo no destruirá ni quemará nada en ti,
sino aquello que traiga fuego eterno sobre tu alma.
'`Hazme saber, oh tú, a quien ama mi alma, ¿dónde está el camino de vida?
¿Por qué había de estar yo como errante junto a los rebaños de tus compañeros?`' Ahora,
todo el que viva en el cuerpo en el seno del yo, tome esto para sí:
Aunque profeses la verdad y vivas en conformación externa con ella,
si secretamente complaces tu voluntad corrupta, y vives una vida agradable a la carne,
y consultas con sangre y carne, y no te desprendes de tus concupiscencias,
no puedes disfrutar al Señor de vida.
"`Mientras estoy en el cuerpo,
estoy ausente del Señor.`" El cuerpo de pecado es como un imán
que te saca de la vida de Dios y de gloriarte en la cruz de Cristo.
Es carne y sangre, y la carne y sangre no pueden heredar el reino de Dios.
Por amor al Señor, por amor a tu alma y por amor a tu felicidad eterna,
no pospongas esta obra, sino búscala, y será perfeccionada.
Experimenta a Cristo siendo revelado en ti por Su Espíritu Santo y fuego.
Dios te redimirá por medio del espíritu de juicio y fuego,
no por deambular afuera en tu mente; sino que debes conocer a '`Cristo en ti,
a menos que estés reprobado`'^
footnote:[2 Corintios 13:5].

Si Él ha colocado tus ojos y corazón en Él, y ha hecho que mojes tu lecho con lágrimas;
si Él ha interrumpido tu sueño de modo que has gritado:
"`¡Seré condenado y nunca llegaré a la salvación!`" (ese será tu lloro;
una vez fue el mío), oh, entonces, no dejes que tus ojos se adormezcan,
ni que tus párpados descansen hasta que estés seguro de que el Señor es tu Dios.
Si encuentras estas señales, entonces estás en tu camino; de lo contrario,
serás como un arco engañoso y nunca permanecerás en el juicio.
Si rechazas el consejo de Dios contra ti,
te rehúsas a ser crucificado con Cristo y a ser bautizado con Su bautismo,
nunca tendrás vida.
Pero por Su bautismo y a través de la operación celestial
de Su Espíritu (teniendo fe en el nombre de Cristo),
serás unido a Él en justicia eterna.
Se nos traerá la salvación y se nos otorgará la vida eterna,
esa vida que está escondida con Cristo en Dios.
Él le dará esto a cada pobre y afligida alma que se someta a Su bendita voluntad,
y crea en el Señor Jesucristo.
Esta no es una fe de nuestra propia hechura, ni un vestido de nuestro propio bordado,
sino la que el Señor nos ha dado.

¡Oh, feliz el hombre o la mujer que obtiene este don de Dios!
Oh, ¿quién no perderá su vida por esta vida eterna?
¿Quién no morirá por esta vida eterna?
El asunto radica en la muerte de sus voluntades.
Y cuando hayan hecho la voluntad de Dios,
entonces vigilen que sus voluntades permanezcan muertas,
y que ese maldito yo no tome las joyas de Dios, o Sus brazaletes y adornos,
para otorgárselos a sí mismo, pintar y engalanar al maldito yo,
o tomar los miembros de Cristo y hacerlos miembros de una ramera.
Si están muertos a sus propias voluntades,
han resucitado con Cristo y recibirán la resurrección para vida eterna.
¡Oh, crucifiquen el yo, desechen el mundo, pisotéenlo y pisoteen todas sus cosas,
y considérenlas escoria y estiércol en comparación con Cristo,
a quien el Padre ha revelado ser nuestra vida en los días de dolor y luto,
en el día de nuestra calamidad,
en el día que gritamos que nuestra esperanza se ha perdido!

Así ha sido con las personas más santas en la tierra.
No es por sus propias obras de justicia que pueden ser salvas;
Cristo viene a cortar todo eso,
para que sean injertadas en Él y justificadas por Su gracia.
No hagan de esto un asunto de conversación, diciendo:
"`Yo ya he oído esto y aquello;`" sino miren en sus propios corazones y vean qué obras
celestiales hay allí. ¿Qué han experimentado ahí del poder del Señor Jesucristo?
¿Les ha hecho Su poder aborrecer a este mundo, y al amor desmedido por la creación,
para que disfruten todas estas cosas como si no las disfrutaran?
Cuando morimos y somos crucificados a este mundo, no podemos evitar decir:
"`Mi vida está en Cristo.`"
Llegamos a no atribuirnos nada a nosotros mismos, y todo a Cristo.

He aquí una bendita armonía: Corazones quebrantados, espíritus derretidos, y sin embargo,
almas gozosas.
Pobres criaturas que lloraban,
suspiraban y clamaban delante del Señor en lugares secretos diciendo:
"`Cortada es mi esperanza, me recostaré en Tu voluntad, oh, Dios;
has lo que desees conmigo.
Es Tu soberana complacencia o don gratuito, si me das la vida o me la niegas.`"
¡Oh, debemos rendirnos a la voluntad de Dios!
Así fue con el Señor Jesús, y así debe ser con cada verdadero santo de Dios.
Ustedes deben ser humillados como niños pequeños antes de que el juicio sea quitado,
y la amorosa bondad de Dios sea sellada en sus almas; pero si buscan esta obra de Dios,
la encontrarán; si la buscan sobre sus camas, en todas sus labores e intereses,
en todos sus puestos y relaciones.
Si insisten en pos del nuevo nacimiento,
deben disfrutar este mundo como si no lo disfrutaran,
y tener una esposa como si no la tuvieran, porque la forma de este mundo está pasando.

Pero déjenme decirles,
un mundo nuevo viene por la regeneración. El nuevo
hombre no se enaltece en su propia mente,
sino que permanece bajo ante sus propios ojos;
espera que la sabiduría de Dios lo gobierne, y es como un mayordomo de la gracia de Dios,
para darles a los que están en necesidad.
Cuando un hombre es regenerado y nace de nuevo, se contenta tanto con pan y agua,
como con todos los placeres de este mundo.
¿Cuál es la razón? Su propia voluntad se ha ido y ha sido puesta bajo sus pies,
junto con todo lo que le da vida a todos sus deseos y afectos vanos.
Oh, todo en el interior está en armonía. Hay un hombre
alabando a Dios y bendiciendo Su santo nombre,
sin enredos que aparten el corazón de servir a Dios y de buscar Su gloria.
Y si Dios llamara al esposo de la esposa,
o a la esposa del esposo para la gloria de Su nombre, no hay lloros, ni quejas,
ni clamores, sino más bien, una renuncia a ellos,
y una alabanza y bendición a Dios cuando son llamados a tal ejercicio.
Y si no son llamados así,
entonces fijan sus corazones para glorificar a Dios en sus varios lugares y posiciones,
y tienen pleno contentamiento en bendita rendición. Aquí son sacrificadas sus voluntades,
y alaban a Dios porque no tienen más deseo que "`Señor,
hágase tu voluntad,`" alabándolo siempre a Él,
y teniendo el temor y la gloria de Dios delante de sus ojos.
Toda maldad es planeada para complacer las voluntades de los hombres; es decir,
en el consejo del corazón que Dios no gobierna.
¿Vivirán como Cuáqueros?
Entonces deben vivir de una manera que será menospreciada,
y cada uno debe caminar en humildad y amor,
y en verdadero conocimiento del Dios del cielo.
He aquí entonces un nuevo mundo, y las modas del viejo mundo han desaparecido.
Todo orgullo, altivez, enojo y pisoteo de unos contra otros ha desaparecido,
todo ha muerto por la operación de Cristo.

¿Qué queda entonces?
Cristo en mí, y todos somos uno en Él. Cristo dio Su vida por ustedes y por mí,
y ahora reina en mí. Él ha preparado mi cuerpo para morir por la verdad,
como Su '`cuerpo preparado`' fue entregado por mi pecado.
Es una necedad cuando los hombres hacen profesión de Cristo, y sin embargo,
viven en codicia, profanación, sensualidad y cosas similares.
Los que han llegado a este nacimiento celestial, buscan las cosas de arriba,
y no pueden hacer otra cosa.
Primero hagan el árbol bueno y el fruto será bueno.
Ustedes deben ser injertados en la vid de la justicia de Dios.
¡No desprecien el día de su visitación! ¿De qué me
servía a mí leer que otro había nacido de nuevo,
hasta que yo mismo fui muerto y experimenté el bautismo celestial de Jesucristo,
y vi la espada encendida lista para matarme en cada vuelta?
La luz de Cristo me convenció de pecado y Su justicia me justificó,
entonces me fueron abominables todas las obras que le impedían el paso a mi alma a Cristo.
Al ligar mi alma con Él, Cristo se apoderó de mí y obró eficazmente en mí;
y ahora hay testimonio de Cristo en mí de que Él ha sellado mi alma para el día
de mi redención. He aquí cierto viaje y cierto camino que nadie se puede perder,
siempre y cuando esté dispuesto a perder su vida por Cristo.
Si no están listos ni dispuestos a perder sus vidas por Cristo,
no pueden venir aquí. Nadie entra por la puerta estrecha ni el camino angosto,
sino el que muere en unidad celestial con Cristo.
¡Oh, amigos, vaciémonos de nosotros mismos,
para que Cristo nos pueda llenar! ¡No seamos nada ante nuestros propios ojos,
para que seamos todo en Él y recibamos Su plenitud!

Ahora los encomiendo al testigo de Dios,
para que recuerden lo que se ha dicho en su presencia.
Pero consideren, que si no le prestan atención,
ello los seguirá y será una plaga para ustedes por toda la eternidad.
Si no se rinden a Cristo en este día que arde como un horno,
entonces deberán morar en ese fuego cuando salgan del cuerpo,
y no habrá forma de apagar el fuego que arderá para siempre.
Pero si son tan sabios como para rendirse a Cristo, e ir a Él como niños pequeños,
verán que eso no estorba sus responsabilidades terrenales.
Aunque el mundo los considere tontos,
aun así tendrán la sabiduría celestial para hacer lo que hacen para Dios.
Se comportarán con sus esposas como ante los ojos de Dios,
para que ellas sean santificadas para ustedes, y ustedes para ellas.
Se comportarán como es debido con sus hijos y con sus siervos,
y así abundarán en gracia y en toda buena obra,
lo cual redundará en beneficio eterno para ustedes.

¡Oh, les ruego, por amor del Señor,
esperen la luz de Cristo para que los guíe! Aprendan de Él a ser mansos y humildes,
entonces serán felices.
Porque Él mora con los humildes, pero al altivo mira de lejos.
Este nuevo nacimiento, que es una obra verdadera, y una obra real y celestial,
los hará así para siempre.
¡Oh, hagan lugar para Cristo en sus corazones, o de lo contrario,
es probable que Él no habite con ustedes nunca;
porque Él ama habitar con el pobre y humilde y contrito
de Espíritu! Él aborrece al soberbio,
pero vaciará sus almas para poder llenarlas.

Por tanto, los encomiendo a Dios.
He estado retenido por mucho tiempo bajo una gran debilidad,
y estuve inquieto hasta que pude venir a esta gran ciudad
de Londres para predicar el evangelio eterno entre ustedes;
y ahora ven que estoy aquí entre ustedes.
Vamos, vuélvase cada uno a su interior.
No dejen que estas palabras, que pasan a través de un vaso despreciable,
sean un discurso desnudo y vacío de la verdad para ustedes,
que sólo oyen y luego no tienen más cuidado de su salvación.
Cuídense de despreciar la luz que brilla en medio de ustedes,
sino sigan adelante en la obra celestial que está establecida en el poder de Jesucristo;
es decir, a través del juicio para muerte, entonces Él les dará vida eterna.
Que el Señor confirme esto y descanse sobre sus corazones,
para que estén muertos a las cosas del mundo.
No nos hemos acercado al Monte Sinaí, que da a luz servidumbre,
sino que nos hemos acercado al monte de Sion, a la ciudad del Dios vivo,
Jerusalén la celestial, a la compañía de muchos millares de ángeles,
a la congregación e iglesia de los primogénitos que están inscritos en los cielos,
a Dios el Juez de todos, a los espíritus de los justos hechos perfectos,
a Jesús el Mediador del nuevo pacto,
y a la sangre rociada que habla mejor que la de Abel.
Esta es la herencia de los redimidos del Altísimo.
¡Bendito sea el nombre del Señor! ¡Oh, descansemos en esperanza,
hasta que Él nos lleve a humildad y a una mente baja,
para que nos pueda revestir con gloria celestial según Su promesa:
"`Yo embelleceré Mi casa con gloria,
dice el Señor.`" Esta es la porción del pueblo pobre, que se postra delante del Señor,
para que Él los levante y sea todo en todo para ellos.
Y en Su bendita presencia tengan gozo y ríos de delicias a Su diestra para siempre.

--

Su intención era asistir a la reunión anual de sus amigos,
pero una enfermedad se lo impidió, por lo que antes de empeorar, regresó a Warwick,
donde vivía. Después de llegar allí, su enfermedad se agravó,
y estando muy enfermo en cama y rodeado por algunos de sus amigos que lo visitaban,
les dijo en gran debilidad de cuerpo, lo siguiente:

[.embedded-content-document.address]
--

Mi Dios puso en mi corazón dar testimonio de Su nombre y de Su bendita verdad.
No podré olvidar jamás el día de Su gran poder y bendita aparición,
cuando me envió por primera vez a predicar el evangelio
eterno y a proclamar el día del Señor a todas las personas.
Por tanto, amigos, sean fieles y confíen en el Señor su Dios; porque puedo decir esto,
que desde ese día, nunca me he acobardado,
sino que entré tan gozosamente en las prisiones como en los palacios,
y en la cárcel canté alabanzas a mi Dios,
y estimé sus pestillos y cerrojos sobre mí como joyas.

Amigos, esto debo testificarles una vez más en el nombre del Señor Dios,
que lo que vi hace más de treinta años,
todavía permanece como un testimonio que debo dejar detrás de mí;
que un día terrible y espantoso está cerca, y que ciertamente sucederá,
pero no puedo decir cuándo será. Pero revístanse todos de fuerza en el nombre del Señor,
y esperen sentir Su poder eterno preservándolos a través
de las tribulaciones de esos días que se aproximan.
Tengo además que manifestar, que mi partida está cerca.
Bendito sea mi Dios, estoy preparado,
y no tengo nada que hacer sino morir y despojarme
de este tabernáculo corruptible y mortal,
de esta carne que tiene tantas enfermedades.
Pero la vida que mora en él, ascenderá fuera del alcance de la muerte,
del infierno y de la tumba;
y la inmortalidad y la vida eterna serán mi corona para siempre.
Por tanto, ustedes que quedan detrás de mí, no teman, no se desanimen,
sino continúen en el nombre y poder del Señor,
y den un testimonio fiel y vivo de Él en sus días.
El Señor prosperará Su obra en sus manos,
y hará que Su verdad florezca y se extienda por todas partes.
Porque la verdad tendrá la victoria y ninguna arma forjada contra ella prosperará.

--

Así de ferviente en espíritu estaba William Dewsbury en su final.
Oró a Dios muy vehementemente por todos sus amigos,
especialmente por aquellos que estaban reunidos entonces en la asamblea anual en Londres,
y así muy piadosamente partió de esta vida en su casa, en buena vejez,
en el mes llamado Junio de este año. Era un hombre de celo y percepción notables.
A veces les hablaba a los jóvenes como a hombres,
diciéndoles que la bendición del Señor descansaría sobre ellos si vivían una vida piadosa;
y algunos de estos, que se han convertido en hombres,
han efectivamente experimentado la verdad de sus palabras.

Dos días antes del deceso de William Dewsbury,
Rebecca Travers partió de esta vida a los setenta
y nueve años. Era una mujer muy bien dotada,
que no sólo habló varias veces en público para la edificación de la iglesia,
sino que también escribió varios libros para el progreso de la piedad.
En uno de sus libros señaló,
que aunque había leído las Escrituras desde que tenía seis años, aun así,
fue hasta que el poder del evangelio eterno la volvió de las tinieblas a la luz,
que las Escrituras se hicieron mucho más claras para ella,
y que no carecían de interpretación. Era una mujer excelente, de corazón abierto,
y que tenía gran cuidado de los pobres.
Estuvo varias veces encarcelada por religión, pero perseveró constantemente en la fe,
y así entró piadosamente al descanso eterno.

En cuanto a los asuntos de estado, se produjo entonces una gran agitación en Inglaterra,
ya que se informó que la reina^
footnote:[Mary de Módena, segunda esposa de James II.]
estaba esperando un niño. Los esfuerzos del rey por introducir el papismo,
junto con su usurpación de algunos derechos y privilegios, habían causado tal revuelo,
que los Protestantes ingleses le pidieron e invitaron a William III,^
footnote:[William III era el sobrino Protestante y yerno del rey James II.]
príncipe de Orange y señor representante de Holanda, etc., acudir en su ayuda.
Él finalmente lo hizo, llegando con una flota y un número considerable de tropas.

El resultado de esta expedición está ampliamente descrito por otras plumas,
y no es de mi incumbencia relatarlo;
por lo que creo que es suficiente para mi propósito sólo decir, que William III,
después de algunas dificultades en el mar, entró en Inglaterra,
y al tener muchos partidarios allí,
hizo que el rey (a quien muchas de sus fuerzas lo
habían abandonado) resolviera irse a Francia,
donde la reina se había ido un poco antes con el pequeño niño de ambos.
De esta manera llegó James a Francia, donde fue bien recibido por Luis XIV,
quien le proveyó una corte en St. Germain.
Mientras tanto,
el príncipe de Orange llegó a Londres y fue saludado
por los grandes como el "`libertador de Inglaterra.`"
Y después de que el alcalde, los concejales y alguaciles de Londres lo felicitaron,
el príncipe mandó a llamar a algunos de los miembros
de Parlamentos anteriores para que fueran a verlo,
y les indicó que había deseado que se reunieran para
que lo aconsejaran de la mejor manera,
sobre cómo alcanzar los fines de su declaración, al convocar a un Parlamento libre,
para la preservación de la religión Protestante,
y la restauración de los derechos y libertades del reino,
a fin de que no corrieran peligro de ser nuevamente socavados.
En respuesta a esto,
se le dieron las gracias al príncipe por su cuidado y esfuerzo en defensa del pueblo,
su religión y sus leyes.
Y todas las cosas tomaron un giro favorable para él.

En Holanda, mucho tiempo antes de este momento,
se había publicado un documento por la prensa llamado,
"`Copia de una Carta Escrita por un Cuáquero en Londres a Sus Amigos en Rotterdam.`"
Esta carta falsificada mencionaba varias cosas que no eran del todo falsas,
y de cierta manera también predecía la llegada del príncipe William a Inglaterra.
Nunca pude averiguar quién escribió la mencionada carta,
pero estoy completamente convencido de que no era Cuáquero;
porque nunca ha sido costumbre de ellos ridiculizar príncipes,
ni caracterizarlos con denominaciones ridículas,
como encontramos en dicha carta mencionado a James de Gran Bretaña, Mary Módena,
William de Orange y Mary de Inglaterra, su esposa.
Tal lenguaje insensato se traiciona a sí mismo,
y sirve como evidencia palpable de que no procedía de la
pluma de ninguna persona del pueblo llamado Cuáqueros.
Pero tal vez, el autor de la carta conocía un secreto del gobierno,
del cual (a fin de permanecer desconocido) trató
de informar al mundo de una manera ridícula;
y que bajo el manto de ser un Cuáquero, podría continuar sin ser descubierto,
y que mediante este esquema, la carta se divulgara más, como en efecto sucedió,
ya que circuló muy rápidamente.
