== Capítulo XXII

[.section-date]
1689--1694

[.chapter-synopsis]
* Revolución en Inglaterra
* El Parlamento confirma la libertad de consciencia
* Declaración de fidelidad de los Amigos
* Amigos de Barbados aliviados
* Muerte de R. Barclay
* Epístola de S. Crisp a todas las iglesias de Cristo
* Enfermedad y muerte de G. Fox
* Carácter de G. Fox
* Epístola de G. Fox a todos los hijos de Dios en todas partes
* Apostasía de G. Keith
* G. Keith tergiversa los principios de los Amigos
* Declaración de la doctrina Cristiana de los Cuáqueros
* Francis Bugg
* Petición al Parlamento de una declaración en lugar de un juramento
* Estado del caso por T. Ecclestone
* Muerte de la reina Mary

Paso ahora al año 1689,
al principio del cual los aristócratas del reino le ofrecieron
la administración del gobierno al príncipe de Orange,
y él aceptó. No mucho después de esto,
él convocó una "`convención de los comunes,`" porque no podía llamarse Parlamento,
ya que en Inglaterra sólo el rey tiene poder para convocar un Parlamento.
Mientras tanto, el príncipe había hecho llegar a la princesa de Holanda a Inglaterra.
Finalmente, después de muchos y grandes debates,
la convención llegó a la resolución de que el trono estaba vacante;
la consecuencia de lo cual fue,
que el príncipe y la princesa de Orange fueran declarados,
con los nombres de William III y Mary II, rey y reina de Inglaterra, y por consiguiente,
fueron coronados después.

Un extenso relato de estos eventos puede ser hallado en varios libros, así que sólo diré,
que la coronación fue llevada a cabo por el obispo de Londres,
pues el arzobispo de Canterbury se había rehusado a participar en la solemnidad.
En el acto de coronación, el obispo les preguntó al rey y a la reina:
"`¿Prometen y juran solemnemente que gobernarán al pueblo
de este reino de Inglaterra y de los dominios que le pertenecen,
según los estatutos acordados en el Parlamento,
y las leyes y costumbres de dicho reino?`"
A lo que el rey y la reina respondieron:
"`Solemnemente prometo hacerlo así.`" El obispo preguntó: "`¿Harán ejecutar,
según su poder, la ley en justicia y misericordia en todos sus juicios?`"
La respuesta fue: "`Prometo.`"
La siguiente pregunta fue: "`¿Mantendrán, según su poder, la ley de Dios,
la verdadera profesión del evangelio y la religión
Protestante Reformada establecida por ley?
¿Preservarán para los obispos y para el clero de este reino,
y para las iglesias encomendadas a su cargo,
todos los derechos y privilegios que por ley les pertenecen o pertenecerán a ellos,
o a cualquiera de ellos?`"
A esto el rey y la reina respondieron: "`Prometo hacer todo esto.`"
Después, cada uno de ellos colocando sus manos sobre el libro del evangelio, dijo:
"`Todas estas cosas que he prometido antes,
las cumpliré y las guardaré. Con la ayuda de Dios.`"
Bajo estas preguntas puntuales y precisas,
se escondía más de lo que algunos puedan pensar.
Porque el rey, después de responder como se ha dicho,
no podía liberar a nadie de pagar los diezmos al clero sin violar su juramento.

No mucho después de que William y Mary fueron nombrados rey y reina de Inglaterra,
también fueron declarados rey y reina de Escocia.
Poco después de esto, se proclamó la guerra contra Francia, y el anterior rey, James,
apoyado por el rey francés, se dirigió a Irlanda.
Con el tiempo, fue expulsado de allí por el rey William,
después de la sangrienta batalla del río Boyne;
pero como estos sucesos no pertenecen a esta historia,
no detendré a mi lector con un relato de ello.

Habiendo subido al trono un nuevo rey,
la convención de los comunes fue convertida en un Parlamento, y luego,
esta gran asamblea se ocupó de restringir el forzamiento de consciencia;
y aprobó una ley para eximir a los Protestantes disidentes de las leyes penales,
por las que algunos disidentes, y especialmente los Cuáqueros,
habían sufrido y habían sido perseguidos por muchos años. Sin embargo,
se tuvo cuidado de mantener en vigor una ley,
por medio de la cual los papistas quedaban excluidos de
formar parte del Parlamento y servir en altos cargos.
La citada ley también les dio libertad a los disidentes de celebrar reuniones religiosas,
siempre que las puertas no estuvieran cerradas,
trancadas o aseguradas durante el tiempo de sus reuniones.
Pero ninguno de estos disidentes fue liberado de pagar diezmos,
u otros deberes de la iglesia (así llamada), al clero,
ni de ser citado ante los tribunales de los obispos.
No obstante,
esta libertad de mantener reuniones públicas no les fue permitida a los papistas;
porque a todo el que deseaba participar en dicha libertad,
se le requería que prestara el juramento de lealtad.
Sin embargo, para cumplir con el pueblo llamado Cuáqueros,
quienes por un asunto de consciencia se negaban a prestar juramento,
esta ley demandaba que subscribieran la siguiente declaración:

[.embedded-content-document.legal]
--

Yo+++_______+++, prometo sinceramente y declaro solemnemente, ante Dios y el mundo,
que seré fiel y leal al rey William y a la reina Mary; y profeso y declaro solemnemente,
que de todo corazón aborrezco, detesto y renuncio, como impía y herética,
esa doctrina y posición condenable, de que príncipes excomulgados o privados por el papa,
o cualquier autoridad de la cede de Roma,
pueden ser depuestos o asesinados por sus súbditos, o por cualesquiera otros.
Y declaro que ningún príncipe, persona, prelado, estado o potentado extranjero,
tiene o debe tener ningún poder, jurisdicción, superioridad, preeminencia o autoridad,
eclesial o espiritual, dentro de este reino.

--

[.offset]
Además de esto, estaban obligados a subscribirse a otra también,
con respecto a su ortodoxia, y para excluir el Socianismo.^
footnote:[Ver nota de pie de página, capítulo 18.]

[.embedded-content-document.legal]
--

Yo+++_______+++, profeso fe en Dios Padre y en Jesucristo su Hijo eterno, el verdadero Dios,
y en el Espíritu Santo, un solo Dios, bendito para siempre;
y reconozco que las Sagradas Escrituras del Antiguo
y Nuevo Testamento fueron dadas por inspiración divina.

--

Y para que ningún papista hiciera uso de esta declaración,
se requerían suficientes testigos Protestantes para
probar que el declarante era un Protestante disidente.
Además de esto,
esta ley no permitía ninguna congregación o asamblea para adoración religiosa,
hasta que el lugar de tal reunión estuviera certificado por el obispo de la diócesis,
o por el arcediano, o los jueces de paz en las sesiones de paz trimestrales o generales;
y registrado en el tribunal de dicho obispo o arcediano respectivamente,
o registrado en las mencionadas sesiones generales o trimestrales;
por lo que el registrador o secretario no debía cobrar más de seis peniques.

Aquí vemos por fin,
la religión de los Cuáqueros reconocida y tolerada por una ley del Parlamento;
y a ellos liberados de toda persecución por la celebración de su adoración pública,
y por negarse a prestar el juramento de lealtad.
Esta fue una obra reservada para ese gran príncipe y rey William,
quien habiendo nacido en un país donde la fuerza sobre la
consciencia había sido abolida bajo el gobierno Protestante,
ahora también, según su capacidad, introducía la misma libertad Cristiana en Inglaterra.
Pero liberar a los disidentes del pago de los diezmos estaba más allá de su alcance,
por muy irrazonablemente que actuara el clero en este caso.
Un notable ejemplo
de esto fue publicado en la imprenta por este tiempo,
donde a un tal John Bishop, un campesino de Wortham,
le habían quitado por dos años de diezmos varios caballos, vacas y ovejas,
por el valor de casi setenta y seis libras, según lo estimado por personas imparciales,
aunque él mismo lo había valorado en ochenta y tres libras.
Y sin embargo, el sacerdote Thomas Thurlow había declarado bajo juramento,
que él creía que la cantidad que se le debía por los diezmos de ambos años,
ascendía a tres libras, diecisiete chelines y seis peniques.

En Barbados, en las Indias Occidentales,
donde a los habitantes se les obligaba a servir en las fuerzas armadas,
los Cuáqueros (a pesar de lo que había sido ordenado en su favor
por el rey James) continuaban bajo difíciles sufrimientos.
Los que estaban así oprimidos,
enviaron una petición al rey en la que exponían cómo eran molestados,
y le solicitaban ayuda.
Esto tuvo tal efecto, que el rey emitió la siguiente orden:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
En el Consejo en Whitehall, 12 de Diciembre, 1689

[.salutation]
En atención a la excelentísima majestad el rey en el consejo.

Tras leer una petición de las personas llamadas Cuáqueros,
habitantes de la isla de Barbados, en la que exponen cómo,
debido a que los citados Cuáqueros no pueden servir en las fuerzas armadas,
ni prestar juramento en ningún caso,
han sufrido mucho en virtud de una ley promulgada
para establecer la milicia en dicha isla,
como se expresa más ampliamente en la petición adjunta,
a su majestad le ha placido referir el asunto de la petición al examen de James Kendal,
esquire, gobernador de su majestad en Barbados por el momento,
quien deberá darles a los peticionarios alivio con respecto a la milicia,
según le parezca justo y razonable responder a sus circunstancias particulares,
y luego informar de ello a su majestad.

[.signed-section-signature]
Richard Colling.

--

Este año murió Alexander Parker, algunas veces mencionado en esta historia,
al ser un hombre no sólo de una vida y conducta piadosas,
sino también de un semblante piadoso y porte sobrio.
El año siguiente, 1690, también partió de esta vida Robert Barclay,
un hombre de notables dones y grandes dotes,
experto no sólo en los idiomas de los eruditos,
sino también muy versado en los escritos de los antiguos padres y otros escritores eclesiásticos,
y provisto de un gran entendimiento, al ser no sólo de un juicio sano,
sino también de fuertes argumentos y alegre en los sufrimientos.
Además de esto, era de una conducta amigable y agradable, aunque sobria,
y notablemente apto para resolver diferencias.
Él realmente vivió según lo que profesaba, al ser de una conducta intachable,
verdaderamente piadosa y muy amado por aquellos con quienes conversaba.
En este feliz estado le plació a Dios sacarlo de este valle
de lágrimas para llevarlo a la gloriosa inmortalidad,
en la flor de su edad, sin haber vivido mucho más de la mitad de la vida de un hombre,
como es comúnmente contada, es decir, a los 42 años. Murió el 3 de Octubre,
en su casa en Ury, Escocia, de una enfermedad que no duró mucho, sin embargo,
dio a entender con buen entendimiento, que en cuanto a su alma, estaba bien.

Este año Stephen Crisp escribió una epístola de tierno amor y consejo fraternal,
a todas las iglesias de Cristo en todo el mundo,
en la que las exhortaba muy especialmente a la caridad.
Y ya que en ella se exponen y recomiendan varios deberes importantes,
no puedo dejar de insertar aquí una copia de ella, que es como sigue:

[.embedded-content-document.epistle]
--

[.salutation]
Queridos amigos y hermanos,

Reunidos fuera del mundo por el brazo y poder eternos del poderoso Dios,
para llevar Su santo nombre en la generación de ustedes;
mi amor y vida en la comunión del Espíritu universal los saluda a todos,
y oro a Dios que sean mantenidos firmes e inconmovibles en la gracia de Dios,
y en la comunión de Su Santo Espíritu, para que lleven fruto en abundancia,
según la abundante misericordia y gracia que les han sido concedidas,
para la gloria de Dios y el mutuo gozo, consuelo y edificación.

Para que puedan hacerlo, mantengan diariamente los ojos puestos en el Señor,
y contemplen y presten atención a las maravillosas
obras que Él ha realizado en ustedes y por ustedes,
desde el día en que fueron vivificados por primera vez por Su Palabra inmortal,
y movidos a buscarlo y a esperar en Él. Cuán bueno y misericordioso ha sido Él con ustedes,
al sacarlos de las estériles montañas,
donde sus almas languidecían por falta del alimento celestial,
y donde no conocían al Señor, ni se conocían unos a otros,
sino que estaban sin un consolador, y sin nadie que se compadeciera de sus lamentos.
Oh, cuánto se ha apiadado Él de los gemidos de ustedes y tenido compasión de sus suspiros,
y llevado a conocer a los que estaban en ejercicios similares.

Luego les enseñó a creer en Aquel que es capaz de ayudarlos;
y estos que fueron así enseñados por el Padre y sintieron
Sus cuerdas de amor prevalecer sobre ellos,
fueron a Cristo su Salvador, y en Él empezaron a sentir una unidad,
los unos con los otros,
en la fe que habían recibido en Él. Y así creyeron que Él les daría
de Su Espíritu para enseñarles y guiarlos en el camino de verdad,
justicia y paz; y de esta manera se colocó el fundamento de la santa comunión de ustedes,
y se levantó una esperanza viva en cada alma en particular,
de que Aquel que había comenzado esta bendita obra la continuaría. Esta esperanza hizo
que no se avergonzaran de hacer una profesión pública de Su nombre ante el mundo,
sino que alegremente tomaran Su cruz y se negaran a sí mismos los placeres,
amistades y deleites de este mundo que tenían anteriormente.
Esta esperanza los ha sostenido en muchas duras pruebas,
y en los amargos combates que han sostenido contra
el enemigo de la paz de sus almas en el interior,
y contra los enemigos del camino santo de Dios y de Su verdad en el exterior;
y en todos sus conflictos lo han hallado a Él cerca
para desplegar Su poder a favor de ustedes,
cuando han dependido de Su ayuda.

Por estas experiencias de Su bondad, la fe de ustedes ha sido fortalecida,
y la misma Palabra de vida que los vivificó, ha alcanzado a muchos más,
de modo que han visto una adición diaria de fuerza en ustedes,
y una adición al número de ustedes, para gran consuelo y aliento de todos.
En efecto, muchos han llegado a esperar en el Señor con ustedes,
y muchos a diario preguntan el camino a Sion,
con sus rostros vueltos hacia allá. Estas cosas son dignas
de ser recordadas y consideradas seriamente por ustedes,
para que estimen estas grandes misericordias como obligaciones sobre sus almas,
para que caminen humildemente delante del Señor,
y para que sean devotos y fervientes en sus testimonios, porque en verdad,
Dios ha hecho grandes cosas por ustedes.

Amigos,
consideren las grandes obras que este poderoso Brazo
del Señor ha llevado a cabo en general,
así como también en casos en particular.
Cuántas maquinaciones se han planeado,
cuántas leyes y decretos se han promulgado para asolarlos
y para que dejaran de ser un pueblo,
y cuánto se han regocijado los impíos en ello, por un tiempo, diciendo: "`¡Ea,
ahora todos ellos son entregados a destierros, encarcelamientos, saqueos y ruina!
Veamos si ese brazo invisible en el que confían puede liberarlos.`"

¡Oh, amigos! ¡Cómo los ha sostenido su Dios en medio de todos estos ejercicios!
Y cuando Le ha placido, ¡cómo ha calmado las tormentas más agudas,
y hecho retroceder las más grandes inundaciones y torrentes de persecución que alguna
vez hayan enfrentado! ¡Y cómo ha confundido a Sus enemigos y a los de ustedes,
y llevado confusión sobre las cabezas de los que buscaban dañarlos!
¿No fueron estas cosas realizadas por el poder de Dios?
¿Acaso el número, sabiduría, influencia de ustedes,
o cualquier cosa que pueda ser llamada de ustedes,
contribuyó en algo a estas grandes preservaciones y liberaciones?
Si no es así, entonces que Dios tenga la gloria, y reconozcan para Su alabanza,
que éstas han sido obras del Señor y que son maravillosas ante nuestros ojos.

De nuevo, queridos amigos,
consideren cómo ha obrado el maligno de manera misteriosa entre ustedes para dispersarlos,
y para que dejen de ser un pueblo como en este día. Cuántas maneras diferentes ha intentado,
levantando hombres de mentes perversas para trastornarlos y apartarlos
de la fe y de la sencillez que es en Cristo Jesús nuestro Señor;
para apartarlos de ese poder invisible que ha sido la fuerza de ustedes,
para separarlos unos de otros, y mediante sutiles artimañas,
conducirlos a una falsa libertad por encima de la cruz de Cristo.
Y a veces, sembrando semillas de herejía y sedición,
se ha esforzado por corromper las mentes de quienes ha podido,
con principios perniciosos.
Pero, ¡oh, cómo han sido frustrados sus planes,
y confundidos y reducidos a nada los autores de ellos!
Y cómo han sido preservados ustedes, como un rebaño bajo la mano de un Pastor cuidadoso,
incluso hasta el día de hoy,
lo que les da a todos los fieles grandes motivos de acción de gracias,
habiendo sido testigos de la obra de este poder preservador en sus casos particulares.

Además, amigos, es digno de su consideración, contemplar la manera mediante la cual,
por este poder invisible,
se han levantado muchos atalayas fieles sobre los muros de su Sion; de modo que,
en la mayoría de sus reuniones hay hombres y mujeres sobre los que Dios
ha colocado la preocupación de velar por el bien de la totalidad,
tomar la supervisión sobre ellas,
ver que todas las cosas se mantengan en un orden bueno y decente,
y hacer la debida provisión para el consuelo y alivio
de las necesidades de los necesitados y afligidos,
y que nada falte para hacer el camino de ustedes cómodo.
Estos atalayas no han sido, ni son puestos bajo este cargo, por ningún acto de ustedes,
sino que Dios ha levantado pastores y maestros,
ancianos y diáconos de Su propia elección y escogencia,
y ha inclinado sus espíritus para que tomen sobre sí la
obra y servicio para los que han sido designados,
por amor del Señor y por amor al cuerpo, que es la iglesia;
a quienes se les puede decir verdaderamente, como en Hechos 20:28:
"`Mirad por todo el rebaño en que el Espíritu Santo os ha puesto por obispos.`"
Y éstos deben ser escuchados en el cumplimiento de su deber,
como aquellos que deben dar cuenta Al que los llamó y los
dotó para sus varias obras y servicios en la iglesia.

Y de esta manera y por estos medios el Señor ha establecido
entre ustedes un gobierno celestial,
y edificado una cerca alrededor de ustedes, por decirlo así,
para que sean preservados de generación en generación,
como un pueblo apto para la gloria que es y cada día será más revelada,
entre los fieles y sobre los fieles,
quienes se deleitan en ese poder que los ha llamado a ser santos,
y hacer profesión por el nombre santo de Dios contra los muchos nombres
y formas que los hombres en sus mentes cambiantes han establecido,
para que sólo el nombre del Señor sea exaltado.

Y queridos amigos y hermanos,
les ruego que la consideración de estas grandes e importantes
cosas que Dios ha hecho por ustedes y entre ustedes,
tenga una influencia profunda y de peso sobre sus almas,
para que se vean comprometidos a responder al amor
y misericordia de Dios en sus vidas y conductas,
y en todo lo que hagan en este mundo.
Para que muestren el honor de Dios en todas las cosas,
y que la luz que Él ha hecho resplandecer en ustedes,
alumbre a través de ustedes a otros que todavía se sientan en tinieblas.
Para que todos los hombres puedan conocer por medio de sus conductas inocentes e inofensivas,
y por la cercanía de ustedes al Señor,
que son un pueblo asistido y ayudado por un poder sobrenatural
que gobierna sus voluntades y las sujeta a Su bendita voluntad;
que guía y ordena sus afectos, y los fija en objetivos celestiales y divinos;
y que les da poder de negar sus propios intereses privados dondequiera
que estén en competencia con los intereses de la Verdad.
Porque éstos y sólo éstos,
serán hallados verdaderos discípulos de nuestro Señor Jesucristo,
quienes se niegan a sí mismos, toman su cruz cada día,
y lo siguen bajo la guía de Su poder regenerador,
que trae la muerte sobre el yo y crucifica la vieja naturaleza con sus pasiones y concupiscencias,
y levanta un nacimiento en ustedes que tiene una voluntad santa,
el deseo de servir al Señor y de hacer Su voluntad en la tierra.
Los tales son instrumentos en la mano de Dios por medio de los cuales Él puede obrar,
y hacer obras de rectitud, justicia,
caridad y de todas las otras virtudes que pertenecen a la vida Cristiana,
para el honor de Dios y consuelo y beneficio de Su iglesia y pueblo.

Y todos ustedes, queridos amigos,
sobre los que el Señor ha puesto un cuidado por Su honor y prosperidad de la Verdad,
y los ha congregado en el buen orden del evangelio
para que se reúnan y administren sus asuntos;
cuiden de tener un ojo puro puesto en el Señor,
para hacer los negocios del Señor bajo la guía de Su Espíritu.
Porque la guía de Su Espíritu es una sola,
y hace que todos los que se rindan para ser gobernados por ella,
sean de una sola mente y de un solo corazón,
al menos en el propósito general y servicio de esas reuniones.
Y aunque a través de los diversos ejercicios,
y de los varios grados de crecimiento entre los hermanos,
puede que no todos vean o entiendan de la misma manera todos los asuntos, aun así,
esto no abre una brecha en la unidad, ni obstaculiza la bondad fraternal, sino más bien,
a menudo los pone en un ejercicio y en un esfuerzo interior hasta
sentir que la sabiduría pura y pacífica que es de arriba,
se abre entre ustedes.
Y como el oído de cada uno está abierto a dicha sabiduría, en cualquiera que hable,
es dado un sentido de vida a la reunión,
al que todos los que son de mente sencilla y tierna se unirán,
y con el que estarán de acuerdo;
pero si alguna persona entre ustedes tiene una mente contraria
en el manejo de algún asunto externo relacionado con la Verdad,
ésta en el momento no rompe la unidad que tienen en Cristo,
ni debe debilitar el amor fraternal,
en tanto ella se mantenga esperando el entendimiento que proviene
de Dios para ser unida en el mismo sentido con el resto,
y continúe caminando con ustedes según la ley de la caridad.
Tal persona debe ser soportada y tratada con ternura,
y las súplicas de sus almas deben subir a Dios por ella,
para que Él se lo revele si es Su voluntad; y así no haya diferencia en el entendimiento,
en cuanto a lo que es necesario para el bien de la iglesia.

Porque amigos,
no es absolutamente necesario que cada miembro de la iglesia
tenga la misma medida de entendimiento en todas las cosas;
porque entonces, ¿dónde estaría el deber del fuerte de soportar al débil?
¿Y dónde estaría el hermano de humilde condición?^
footnote:[Santiago 1:9]
¿Dónde estaría la sumisión a los que son puestos sobre otros en el Señor?
Todas estas cosas tienden a preservar la unidad en la iglesia,
a pesar de las diferentes medidas y diferentes crecimientos de los miembros de ella.
Porque así como "`los espíritus de los profetas están sujetos a los profetas,`"^
footnote:[1 Corintios 14:32]
así también,
los espíritus de todos los que se mantienen en verdadera
sujeción al Espíritu de vida en ellos mismos,
se mantienen en la misma sujeción al sentido de vida
dado por el mismo Espíritu en la iglesia;
y por este medio llegamos a experimentar al único Maestro, que es Cristo,
y no tenemos espacio para otros maestros en asuntos
que tengan que ver con nuestra obediencia a Dios.
Y mientras todos se mantienen en esta verdadera sujeción,
se experimenta una verdadera armonía, y el óleo no sólo está sobre la cabeza de Aarón,
sino que baja también hasta el borde de sus vestiduras;
y todas las cosas se mantienen dulces y sabrosas, y se aman unos a otros con sinceridad,
desde el mayor hasta el menor, y como dice el apóstol: "`Sin hipocresía.`"^
footnote:[Romanos 12:9]
Este amor excluye todos los susurros de cosas malas, calumnias, chismes,
rencores y murmuraciones, y mantiene limpias las mentes de los amigos unos hacia otros,
esperando cada oportunidad para hacerse mutuamente el bien,
y preservar la reputación del otro, y sus corazones son consolados al verse unos a otros.
Y en todos sus asuntos, tanto relacionados con la iglesia como con el mundo,
ellos vigilarán sobre sus propios espíritus, y en el poder del Señor,
se mantendrán sobre esa naturaleza y terreno en sí mismos que podrían ofenderse,
o interpretar cualquier palabra o acción en un sentido
peor que el que permite la intención del otro interesado.

Y considerando que puede suceder con frecuencia, que entre un gran número de personas,
algunas comprendan un asunto de manera diferente al resto de sus hermanos,
especialmente con respecto a cosas externas y temporales,
se debe mantener una libertad Cristiana para que
ellas expresen sus sentidos con libertad de mente,
o de lo contrario, se irán con una pesada carga.
Mientras que si expresan su opinión libremente,
y se permite una conversación amistosa y Cristiana al respecto, ellas pueden aliviarse,
y a menudo, la diferente comprensión de éstas llega a desaparecer por completo,
y su entendimiento se abre para ver de la manera en que ven los
demás. Porque el peligro en la sociedad no radica tanto,
en que algunos pocos tengan una diferente comprensión
de algunas cosas en el sentido general,
sino en esto, a saber:
cuando los que difieren se dejan llevar fuera de los límites del amor,
y así se esfuerzan por imponer su opinión personal sobre el resto de sus hermanos,
y se ofenden y enojan si no es aceptada.
Esta es la semilla de sedición y contienda que ha crecido en demasiados,
para su propio perjuicio.

Por tanto, mis queridos amigos,
tengan cuidado con esto y no traten de impulsar un asunto con fiereza o enojo,
ni se ofendan en sus mentes en ningún momento porque lo
que parece claro para ustedes no es recibido inmediatamente.
Sino dejen que todas las cosas en la iglesia sean propuestas con
terrible reverencia hacia Aquel que es la cabeza y la vida de ella;
quien ha dicho: "`Porque donde están dos o tres congregados en mi nombre,
allí estoy yo en medio de ellos.`"
Y así está, y puede ser sentido por todos los que se mantienen en Su Espíritu;
pero el que sigue su propio espíritu, no ve nada como debe verlo.

Por tanto,
cuídense todos de sus propios espíritus y temperamentos
naturales (como se les llama a veces),
y manténganse en un temperamento amable,
porque entonces serán aptos para el servicio de la casa de Dios, cuya casa son ustedes,
en la medida que se mantengan sobre el fundamento que Dios ha puesto.
Él los edificará y les enseñará a edificarse unos a otros
en Él. Y como cada miembro debe sentir la vida en sí mismo,
y toda la vida fluye de una Cabeza, así esta vida no se dañará a sí misma en ninguno,
sino que será tierna con la vida en todos.
Porque por esta única vida de la Palabra, ustedes fueron engendrados,
por ella son alimentados y son hechos crecer en sus
varios servicios en la iglesia de Dios.

No es el conocimiento ni las adquisiciones artificiales del hombre,
ni sus riquezas o grandeza en este mundo, ni su elocuencia y sabiduría natural,
lo que hace que sea apto para el gobierno en la iglesia de Cristo; a menos que él,
con todos sus dotes, sea sazonado con la sal celestial,
su espíritu sea sometido y sus dones pasados por el fuego del altar de Dios,
como un sacrificio para Su alabanza y honor.
Así el yo será crucificado y bautizado en la muerte,
y todos los dones serán utilizados en el poder de la resurrección de la
vida de Jesús en él. Y cuando esta gran obra es realizada en un hombre,
entonces todos sus dones y cualidades son santificados
y utilizados para el bien del cuerpo,
que es la iglesia,
y son como ornamentos y joyas que sirven para el gozo y consuelo de todos los que participan
de la misma comunión divina de vida en Cristo Jesús nuestro Señor. Así,
muchos llegan a estar capacitados y equipados para buenas obras,
las cuales son llevadas a cabo a su debido tiempo
para la enseñanza y edificación de los débiles,
para reparación de los lugares deteriorados,
y también para defensa de los que son frágiles,
para que las cosas dañinas no puedan acercarse a ellos.

Oh, amigos, grande es la obra a la que el Señor los ha llamado,
y para la que los está preparando,
los que inocentemente esperan en Él. El Señor ha abierto mi corazón para ustedes,
y me ha encomendado exhortarlos y rogarles que tengan cuidado de actuar como deben hacerlo,
en cualquier cosa que Dios les demande.
Y para expresar más detalladamente lo que está delante de mí en este asunto,
expondré algunas pocas observaciones en particular para el beneficio y ventaja de ustedes.
El deseo de mi alma es, que mi obra de amor tenga un buen efecto en todos sus corazones,
para que Dios sea honrado por ello.

Ahora bien, amigos,
ustedes saben que el asunto principal al que son
llamados en sus reuniones de hombres y mujeres,
recae sobre estos dos encabezados: Justicia y caridad.
En primer lugar, ver que a cada uno se le haga lo que es correcto; y en segundo lugar,
ver que nada falte para el consuelo de los pobres
que son partícipes de la misma fe con ustedes.
Y cuando se reúnan para tratar estas cosas, tengan al Señor frente a sus ojos,
y esperen Su poder para ser guiados y dirigidos,
para hablar y comportarse en la iglesia de Dios como corresponde al evangelio pacífico.

Cuídense de toda fragilidad de espíritu,
y de toda crítica aguda sobre las palabras de los demás,
porque encenderá la pasión y creará un fuego falso;
y cuando alguno se toma la libertad de hablar una palabra
áspera (dicha fuera del verdadero temor y de la ternura),
esto a menudo se convierte en una tentación para otro, quien, si no es cuidadoso,
también será arrastrado.
Entonces, el primero es culpable de dos males: en primer lugar,
de caer él mismo en una tentación, y en segundo lugar,
de convertirse en un tentador para otros.
Por tanto, es necesario que todos velen para no tentar ni ser tentados.
Que nadie piense que es excusa suficiente decir que fue provocado,
porque somos responsables ante Dios por toda palabra mala dicha bajo provocación,
como sin provocación; y con este fin el Señor nos ha revelado Su poder,
para mantenernos y preservarnos en Su temor y consejo
durante el tiempo de nuestras provocaciones.

Por tanto, si alguno, por falta de vigilancia es sorprendido por el calor o la pasión,
entonces "`la blanda respuesta quita la ira,`" dice el sabio.
Este es el mejor momento para una respuesta blanda,
no sea que el enemigo prevalezca en algunos para daño de ellos,
y para la angustia y aflicción de sus hermanos;
porque es el deber propio de los atalayas y obispos proteger el rebaño, es decir,
no dejar que nada se acerque a ellos que los dañe, hiera o aflija.
En efecto, el buen apóstol era tan cuidadoso sobre el rebaño de creyentes,
que si había algún asunto dudoso que discutir,
no quería que los que eran débiles en la fe estuvieran presentes en dichas discusiones;
entonces, menos aún,
que los que son débiles vean a los que son fuertes descender de
sus fuerzas y entrar en la debilidad donde no son capaces de resistir.
El apóstol en el lugar antes mencionado,
cuando él mandó a llamar a los ancianos de Éfeso a Mileto dijo: "`Mirad por vosotros.`"
Y en efecto, no somos capaces de desempeñarnos bien con los demás,
a menos que cuidemos de nosotros mismos,
para ser guardados en un estado de espíritu sobrio e inocente al que la Verdad nos llama.

En segundo lugar, mis queridos amigos, cuando se les llame a un asunto de justicia,
para dar su sentido del derecho entre amigo y amigo,
tengan cuidado de que ninguna parte se apodere de sus espíritus de antemano,
de ninguna manera o por ningún medio;
u obtenga de ustedes una palabra o decisión en ausencia
de la otra parte antes de que haya sido escuchada.
No hay nada más hermoso entre hombres que el juicio imparcial;
porque el juicio es un asiento donde ni el interés personal,
ni el afecto o la amabilidad anterior tienen cabida.
No podemos hacer diferencia entre la dignidad e indignidad de las personas en el juicio,
como podemos hacerla en la caridad; pero en el juicio, si un hombre bueno,
estando equivocado, tiene una causa mala, o un hombre malo tiene una causa buena,
él debe obtener su sentencia según su causa.
Por tanto, que todo sea hecho como para el Señor,
y según estén dispuestos a responder ante Su presencia;
y aunque algunos estén descontentos por un tiempo,
con el tiempo Dios aclarará su inocencia como el sol al mediodía,
y los que dan patadas contra el sano juicio descubrirán que es una obra dura,
porque no hacen más que dar patadas contra eso que los aguijonea.
Y aunque algunos, por su obstinación, se hagan daño,
ustedes serán preservados y disfrutarán su paz y satisfacción
en la descarga de sus consciencias ante los ojos de Dios.

Con respecto a la caridad práctica, ustedes saben que se apoya en la generosidad,
y donde cesa la generosidad, la caridad se enfría; en efecto, hasta ahí llega.
Donde no hay contribución, no hay distribución; donde una es escasa, la otra es escasa.
Por tanto, que cada uno alimente la caridad en su raíz, es decir,
que mantenga una mente generosa,
que mantenga un corazón que considere que la sustancia que se le da,
realmente le es concedida tanto para el sostén de la caridad,
como para el sostén de su propio cuerpo.
Y donde las personas son de esta mente,
serán cuidadosas de no retener nada de la parte de Dios;
porque en todas las edades y de la manera más singular,
Él ha defendido la causa del pobre, de la viuda y del huérfano;
y a menudo manifestó por Sus profetas y ministros,
un encargo especial para los ricos que poseían los bienes de este mundo:
que debían ser fieles administradores de lo que poseían, siendo hallados en buenas obras,
sin permitir que sus corazones se aferraran a las riquezas inciertas,
al punto de descuidar el servicio para el que Dios les había dado las cosas de esta vida.

Ahora, con respecto a las necesidades de los pobres,
hay gran necesidad de sabiduría cuando se reúnen para tratar este asunto;
porque como he dicho antes,
aunque la dignidad o indignidad de una persona no
debe considerarse en un asunto de justicia,
en la caridad sí. Ustedes se van a encontrar a algunos que Dios ha empobrecido,
a otros que se han empobrecidos a sí mismos,
y a otros que han sido empobrecidos por otros,
todos los cuales deben tener sus diferentes consideraciones.
Ustedes deben esforzarse por ser unánimes en esto,
y no dejarse llevar por el afecto hacia una persona más que hacia otra;
sino que todos deben a amar a todos en el Espíritu universal,
y luego repartir su amor en una manifestación externa,
según la medida que el Señor (en Su sabiduría obrando en ustedes) les medirá.

Y aquellos que por enfermedad, por estar lisiados,
por edad u otra incapacidad son llevados a la pobreza por la mano de la Providencia,
éstos deben ser considerados el objeto del cuidado particular de ustedes,
señalado por el Señor, a quienes deben otorgar su caridad,
porque para ellos la demanda el Señor. Porque así
como del Señor es la tierra y la plenitud de ella,
así ha ordenado Él por Su soberano poder en cada dispensación,
que una parte de lo que nosotros disfrutamos de Él sea empleada
así. Los israelitas no debían segar los rincones de sus campos,
ni espigar el trigo o las uvas de la tierra segada; eso era para los pobres.
En el tiempo del evangelio, ellos debían apartar cada primer día de la semana,
una parte de lo que Dios les había dado para el alivio de aquellos que estaban en necesidad.
De hecho, ellos no limitaban la caridad a sus propias reuniones,
sino que tenían una mirada universal sobre toda la iglesia de Cristo,
y en ocasiones extraordinarias,
enviaban su benevolencia para aliviar a los santos de Jerusalén en tiempo de necesidad.
Ciertamente, todo el que se mantiene dentro de la guía del mismo Espíritu universal,
se ocupará de ser hallado en la misma práctica de caridad y buenas obras.
"`Y de hacer bien y de la ayuda mutua no os olvidéis,`" dice el apóstol;
y los que no olvidan este deber Cristiano,
descubrirán '`los rincones de sus campos y lo que
no deben espigar`' en las ganancias de sus oficios,
la parte para los pobres,
tal como hicieron los israelitas de antaño en los rincones y rebuscos de sus campos.
Y en la distribución de estas cosas,
tengan cuidado de consolar los corazones de aquellos,
que por la divina providencia de Dios,
no pueden disfrutar las comodidades externas de salud,
fuerza y abundancia que otros gozan;
porque mientras ellos sean partícipes de la misma
fe y caminen en el camino de justicia con ustedes,
sometiéndose pacientemente a la dispensación de la providencia de Dios hacia ellos,
deben ser considerados como parte de sus hogares y bajo el cuidado de ustedes,
tanto para visitarlos como para aliviarlos, como miembros de un cuerpo,
del cual Jesucristo es la cabeza.
Y: "`A Jehová presta el que da al pobre,`" y Él lo pagará.

Pero hay otro tipo de pobres,
los que se han empobrecido a sí mismos por su propia pereza y descuido,
y a veces por su obstinación, siendo imprudentes y altaneros,
tomando más cosas de las que pueden manejar y floreciendo por un tiempo, pero luego,
por su propia negligencia, se hunden en gran pobreza.
Las iglesias primitivas empezaron a tener problemas con
este tipo de personas en los primeros días del evangelio;
pues el apóstol se fijó en algunos que no querían trabajar del todo,
y los reprende fuertemente diciendo: "`Si alguno no quiere trabajar, tampoco coma.`"
Estos comúnmente son una especie de entrometidos,
que se inmiscuyen en los asuntos de otros, mientras descuidan los propios,
y corren por un camino peor que los incrédulos; porque mientras profesan ser creyentes,
no tienen el debido cuidado de los de su propia casa.

La caridad que es apropiada para éstos, es darles amonestación y reprensión,
y convencerlos de su pereza y negligencia; y si se someten a la reprensión de ustedes,
y están dispuestos a enmendar sus caminos,
entonces se debe tener cuidado de ayudarlos a encontrar
un camino y los medios para mantenerse a sí mismos;
y a veces por un poco de ayuda de este tipo,
algunos han sido rescatados de las trampas del enemigo de sus almas.
Pero si ellos no reciben los consejos y amonestaciones saludables que ustedes les dan,
sino que dan coces contra ello, con sus palabras o actos,
entonces los Amigos quedarán libres de ellos ante los ojos de Dios.
Porque no es razonable alimentar a los que no se dejan gobernar por ustedes,
pues quebrantan las obligaciones de la sociedad por su caminar desordenado;
porque nuestra comunión no consiste sólo en asistir
a las reuniones y oír la verdad predicada,
sino en la sumisión a la bendita Semilla de verdad en vida y conducta,
y en ella tanto ricos como pobres tienen comunión unos con otros.

Hay otro tipo de pobres,
los que han sido empobrecidos por la opresión y crueldad de otros.
Estos pobres oprimidos claman a voces a los oídos del Todopoderoso,
y en Su propio tiempo Él vengará su causa.
Pero mientras tanto, hay que extenderles ternura,
sin saber cuán pronto será nuestro turno para sufrir.
Y si hay necesidad de consejo o asesoramiento,
o si se le puede hacer una petición a alguien que pueda liberarlos de los opresores,
en tales casos, que todos los que sean capaces estén listos y dispuestos a asesorar,
aliviar y ayudar a los afligidos.
Esta es una obra aceptable de caridad,
y un gran consuelo para los que están en dolorosas aflicciones,
y sus almas bendecirán a los instrumentos de su alivio y consuelo.

Mis queridos amigos,
que así como Dios los han honrado con un llamamiento tan alto y santo,
para ser Sus siervos y obreros en este grande y notable día,
y para trabajar juntos en Su poder, y proclamar Su alabanza y gloria en la tierra,
y reunir en uno la semilla dispersa en esta y otras naciones, ¡oh,
que la dignidad del llamamiento los provoque y aliente a ser asistentes
diligentes en esta obra y servicio al que han sido llamados!
No permitan que las preocupaciones del mundo les impidan
observar los tiempos y ocasiones señalados para reunirse,
sino que ustedes que son mayores, den un buen ejemplo a los más jóvenes,
observando debidamente la hora señalada,
para que aquellos que lleguen a tiempo no se desanimen por la larga espera de los demás,
y lleguen tarde la próxima vez.
Cuando llegue la hora de la reunión, dejen sus negocios por la obra del Señor,
y Él tendrá cuidado de que sus negocios no sufran,
sino que añadirá una bendición sobre ellos.

Y cuando tengan que tratar con personas perversas, obstinadas o desordenadas,
a quienes han tenido ocasión de reprobar y reprender por causa de la verdad,
y las hallan orgullosas y altivas, lanzando reproches contra ustedes;
entonces es tiempo para que la mansedumbre del Cordero resplandezca,
y para que ustedes sientan su autoridad en el nombre
de Cristo para tratar con tales personas,
y para esperar que la sabiduría pura y pacífica de lo alto
derribe y confunda la sabiduría terrenal de ellas.
Y en este estado de ánimo,
dejen que su labor conjunta sea sacar de la espesura a la oveja enredada,
y restaurar a la que se ha extraviado del redil, si pueden.
Pero si no las pueden restaurar, aun así,
se han salvado a sí mismos de la culpa de la sangre de ellas; y si al final perecen,
su sangre recaerá sobre sus propias cabezas.
Pero por otro lado, si ustedes permiten que los espíritus perversos de ellas entren,
y sus provocaciones ocupen un lugar en ustedes,
al punto de encender sus espíritus en el calor de la pasión,
entonces saldrán heridos y serán incapaces de hacerles algún bien; y por el contrario,
estallarán palabras que necesitarán arrepentimiento,
y el impío se endurecerá y fortalecerá por ello,
y ustedes perderán el servicio que realmente intentaban.

Por tanto, amados, manténganse vigilantes.
Mantengan su armadura espiritual;
mantengan sus pies calzados con el apresto del evangelio de paz,
y el Dios de paz estará con ustedes y coronará sus esfuerzos con buen éxito,
para gozo y consuelo de ustedes.
Y Él levantará Su poder sobre todos los adversarios y oponentes más y más,
ante el cual muchos se inclinarán y doblegarán a la vista de ustedes,
y así Él traerá vergüenza y confusión sobre los rebeldes que endurecen
sus corazones y fortalecen sus cuellos contra el Señor y Su Cristo,
y reino.
Porque este es el reino que tratamos de exaltar en la tierra,
a pesar de todo lo que Satanás y todos sus malvados instrumentos puedan
hacer para impedir el crecimiento y progreso de Su bendita verdad;
porque está escrito: "`El aumento de Su soberanía y de la paz, no tendrán fin.`"

Y ahora, amigos,
he aliviado mi consciencia de lo que había estado sobre mí por un tiempo,
para escribirles a manera de recordatorio y como exhortación de mi vida.
Y aunque mi hombre exterior se desgasta,
aun así en el hombre interior soy consolado al contemplar diariamente
las grandes cosas que nuestro Dios ha hecho y sigue haciendo,
por aquellos que dependen exclusivamente de Él. Así pues,
los encomiendo a la gracia de Dios como directora y preservadora de ustedes,
en este y en todos los varios servicios a los que Dios los ha llamado,
para que por las operaciones de Su gran poder sean
guardados irreprensibles y sin mancha del mundo,
para honor de Dios y consuelo de ustedes,
y para el consuelo y la edificación universal de la iglesia;
y para que así las alabanzas y acciones de gracias llenen sus corazones y bocas,
sus familias y sus reuniones; porque digno es Aquel que es nuestra torre, nuestro sostén,
el Señor de los ejércitos, el Rey de los santos, a quien sea toda la gloria,
el honor y el renombre, en ésta y todas las generaciones por los siglos de los siglos.
Amén.

[.signed-section-closing]
De su amigo y hermano, en la comunión y hermandad del evangelio de paz y pureza,

[.signed-section-signature]
Stephen Crisp

[.signed-section-context-close]
Londres, el 15 del mes Siete de 1690.

--

Paso de largo otros asuntos de este año, y llego al siguiente, al año 1691,
a comienzos del cual partió de esta vida G. Fox,
quien incluso en este último período de su vida escribió mucho,
y continuó laborioso sin desmayar.
La última epístola suya que he encontrado,
está dirigida a sus amigos y hermanos en Irlanda, quienes estaban sufriendo mucho,
principalmente a manos de los papistas,
debido a la revolución y a los problemas que ahí se producían; y por eso,
en la mencionada epístola exhortaba a sus amigos a la firmeza.
Esto fue en el mes llamado Enero; y al día siguiente,
el primer día de la semana y 11 del mencionado mes,
fue a la reunión en Grace-church-street, donde predicó muy eficazmente,
tocando muchas cosas con gran poder y claridad;
y concluyó con una oración. Una vez terminada la reunión,
fue a la casa de Henry Gouldney, en White-Hart Court, cerca de la casa de reunión,
donde les dijo a algunos que lo acompañaban,
que creía haber sentido que el frío golpeaba su corazón
cuando salía de la reunión. Sin embargo,
añadió: "`Estoy feliz de estar aquí. Ahora mi consciencia está tranquila,
completamente tranquila.`"
Cuando los amigos que estaban con él se retiraron,
se acostó en una cama con la ropa puesta, pero pronto se levantó de nuevo.
Sin embargo, después de un rato se acostó de nuevo, quejándose aún de que tenía frío;
y al ver que sus fuerzas decaían, no mucho después se desvistió y se fue a la cama,
donde permaneció con mucho contentamiento y rendición,
y continuó muy lúcido hasta el final.

Su enfermedad se agravó, y tal vez, percibiendo que su fin estaba cerca,
envió a llamar a algunos amigos y les recomendó que repartieran
los libros que contenían la doctrina de la verdad.
Y a algunos otros que llegaron a visitarlo en su enfermedad, les dijo: "`Todo está bien,
la Semilla de Dios reina sobre todo y sobre la muerte misma.
Y aunque,`" continuó, "`estoy débil en el cuerpo, aun así,
el poder de Dios está sobre todo,
y la Semilla reina sobre todos los espíritus desordenados.`"
Él a menudo llamaba a Cristo la Semilla, incluso en su predicación cuando hablaba de Él,
por lo tanto,
aquellos que estaban con él sabían muy bien lo que
quería decir cuando hablaba de la Semilla.
Así permaneció, en un estado de ánimo celestial,
con su espíritu completamente aplicado hacia el Señor,
y se fue debilitando poco a poco en su cuerpo,
hasta que al tercer día de la semana y tercer día de su enfermedad,
partió piadosamente de esta vida.
Unas cuatro o cinco horas antes, cuando le preguntaron cómo estaba, respondió:
"`No importa, el poder del Señor está por encima de toda enfermedad y muerte.
La Semilla reina, bendito sea el Señor.`" Y así, triunfando sobre la muerte,
partió de aquí en paz y durmió dulcemente el 13 del mes llamado Enero,
como a las diez de la noche,
a los 67 años. Su cuerpo fue sepultado cerca de Bunhill-fields, el 16 del citado mes,
acompañado por un gran número de sus amigos y de otras personas
también. Porque aunque había tenido muchos enemigos,
también se había hecho querer por muchos.

Era alto de estatura y bastante corpulento, sin embargo,
muy moderado en la comida y en la bebida,
y tampoco se entregaba mucho al sueño. Era un hombre
de profundo entendimiento y de espíritu agudo.
Y aunque sus palabras no siempre se unían mediante una conexión gramatical nítida,
y su predicación a veces parecía entrecortada, como si tuviera una especie de laguna,
aun así, se expresaba inteligentemente,
y lo que le faltaba de sabiduría humana era suplido
abundantemente con conocimiento celestial.
Era de una rápida comprensión,
y aunque su intelecto no estaba pulido por la educación humana, era ingenioso.
Y en sus oraciones, que por lo general no eran muy largas, pero poderosas,
aparecía una gravedad mezclada con una terrible reverencia,
para la admiración de los que lo oían. Sus cualidades
son ampliamente expuestas por Thomas Ellwood,
un eminente autor, que habiendo estado mucho con él,
dio la siguiente descripción de su carácter.

[.embedded-content-document.testimony]
--

Él era, en verdad, un hombre de mente celestial, celoso del nombre del Señor,
que prefería el honor de Dios antes que todas las cosas.
Era valiente en la verdad, audaz al afirmarla, paciente al sufrir por ella,
incansable al trabajar en ella, firme en su testimonio de ella, inamovible como una roca.
Tenía profundo conocimiento divino, y era claro al explicar misterios celestiales,
y sencillo y poderoso al predicar;
y era ferviente en la oración. Estaba ricamente dotado de sabiduría celestial,
y su discernimiento era agudo y su juicio sano.
Era capaz y presto para dar consejo y discreto en guardarlo.
Amante de la justicia, alentador de la virtud, justicia, templanza, mansedumbre, pureza,
caridad, modestia y negación al yo en todo, tanto de palabra como en ejemplo.
Gentil en el semblante, varonil en el carácter, sobrio en los gestos,
cortés en la conducta, serio en la comunicación, instructivo en el discurso,
libre de afectación al hablar y en su porte.
Reprendía severamente a los pecadores duros y obstinados,
y amonestaba con suavidad y gentileza a los que eran tiernos y sensibles de sus fallas.
No era propenso a resentir los agravios personales,
y con facilidad perdonaba las injurias, pero era celosamente serio,
en lo referente al honor de Dios, a la prosperidad de la verdad o a la paz de la iglesia.
Era muy tierno,
compasivo y piadoso con todos los que estaban bajo algún tipo de aflicción;
y estaba lleno de amor fraternal y cuidado paternal, pues, en efecto,
el cuidado de las iglesias de Cristo estaba diariamente sobre él,
cuya prosperidad y paz buscaba diligentemente.

--

Thomas Ellwood y otros han dicho muchos elogios más de él,
pero no detendré más a mi lector con ello.
Su esposa, unos seis meses antes de su muerte, había ido a verlo a Londres,
y estando contenta por la salud de él (que en ese
momento era mejor que algún tiempo antes),
después de una estadía en la mencionada ciudad, regresó a la casa muy satisfecha,
dejándolo en Londres,
donde su servicio general de la iglesia parecía ser más necesario entonces.
Después de su deceso se halló una epístola, escrita por su puño y letra,
y sellada con la siguiente inscripción: "`No abrir antes de tiempo.`"
Qué significaba esto, parecía un enigma; pero habiendo muerto,
se juzgó que era el tiempo de abrir la carta, la cual estaba dirigida a sus amigos,
y es como sigue:

[.embedded-content-document.epistle]
--

[.letter-heading]
Para la reunión anual y del segundo-día en Londres,
y para todos los hijos de Dios en todas partes del mundo.

[.offset.centered]
Por y de G. Fox.

Esto es para todos los hijos de Dios en todas partes,
que son conducidos por Su Espíritu y caminan en Su luz, en la que tienen vida,
unidad y comunión con el Padre y con el Hijo, y unos con otros.

Mantengan todas sus reuniones en el nombre del Señor Jesús,
las cuales son reunidas en Su nombre, por Su luz, gracia, verdad, poder y Espíritu;
por medio de lo cual sentirán Su presencia bendita
y refrescante entre ustedes y en ustedes,
para consuelo de todos y gloria de Dios.

Ahora, amigos, todas sus reuniones, tanto de hombres como de mujeres, mensuales,
trimestrales, anuales, etc., fueron establecidas por el poder,
Espíritu y sabiduría de Dios.
Y ustedes saben que en ellas han sentido tanto Su poder y sabiduría,
como Su bendito y refrescante Espíritu entre ustedes y en ustedes,
para Su alabanza y gloria, y para consuelo de todos;
de modo que han sido como una ciudad asentada en un monte que no se puede esconder.

Y aunque a veces se han levantado muchos espíritus libertinos
y revoltosos para oponerse a ustedes y a sus reuniones,
tanto por la prensa como de otras formas,
ustedes han visto que ellos han quedado en nada, y que el Señor los ha quebrantado,
ha sacado a la luz sus obras, y les ha hecho ver que son árboles sin fruto,
pozos sin agua, estrellas errantes en el firmamento del poder de Dios, mar en tempestad,
cuyas aguas arrojan cieno y lodo.
Y muchos de ellos han sido como el perro que vuelve a su vómito,
y la puerca lavada que regresa a revolcarse en el cieno.
Y esta ha sido la condición de muchos, Dios lo sabe.

Por lo tanto, estén firmes en Cristo Jesús la cabeza de todos, en quien todos son uno,
varón y hembra, y conozcan Su gobierno,
y lo dilatado de su imperio y paz que no tendrán límite.
Pero habrá un fin de lo del diablo,
y de todos los que están fuera de Cristo y se oponen a Él y a Su reino,
sobre los cuales la condenación ya de largo tiempo no se tarda,
y su perdición no se duerme.
Por tanto, vivan y caminen en la luz, vida,
Espíritu y poder de Dios y de Cristo que están sobre todo (y en la Semilla de ello),
en amor, inocencia y sencillez.
Moren en la justicia y santidad, y en Su poder y Santo Espíritu,
en los que el reino de Dios permanece.
Mantengan sus ojos en la Jerusalén nueva y celestial, que es de arriba, y es libre,
con sus hijos santos y espirituales.

En cuanto a este espíritu de rebelión y oposición
que se ha levantado tanto antes como últimamente,
está fuera del reino de Dios y de la Jerusalén celestial, y es para juicio y condenación,
con todos sus libros, palabras y obras.
Por tanto,
los amigos deben vivir y caminar en el poder y Espíritu de Dios que está sobre ese espíritu,
y en la Semilla que lo herirá y romperá en pedazos;
en cuya Semilla tienen gozo y paz para con Dios, y poder y autoridad para juzgarlo.
La unidad de ustedes está en el poder y Espíritu de Dios que lo juzga,
y todos los testigos de Dios en Su tabernáculo salen contra él,
y siempre lo han hecho y lo harán.

Que nadie viva para el yo, sino para el Señor,
así como morirán en Él. Busquen la paz de la iglesia de Cristo,
y la paz de todos los hombres en Él, porque los pacificadores son bienaventurados.
Moren en la sabiduría pura, pacífica y celestial de Dios, que es tierna,
llena de misericordia y fácil de ser invocada.
Esfuércense todos por ser uno en mente, corazón, alma y juicio en Cristo,
teniendo Su mente y Su Espíritu morando en ustedes,
edificándose unos a otros en el amor de Dios que edifica el cuerpo de Cristo, Su iglesia,
Quien es la cabeza santa de ella.
Gloria a Dios por Cristo, en esta y en todas las otras edades,
Quien es la roca y fundamento, y el Emanuel, Dios con nosotros, sobre todo,
el principio y el fin, amén. Vivan y caminen en Él, en Quien tienen vida eterna,
y en Quien me sentirán y yo a ustedes.

Todos los hijos de la nueva Jerusalén que desciende del cielo,
la ciudad santa y templo de los que el Señor y el Cordero es la luz,
nacieron de nuevo del Espíritu en esa ciudad.
Por tanto, la Jerusalén que es de arriba, es la madre de los que nacen del Espíritu.
Y así, los que vienen y los que han venido a la Jerusalén celestial,
son los que reciben a Cristo; y Él les da potestad de ser hechos hijos de Dios,
y nacen de nuevo del Espíritu,
de modo que la Jerusalén que es de arriba es madre de ellos.
Éstos se han acercado al monte de Sion, a la compañía de muchos millares de ángeles,
a los espíritus de los justos hechos perfectos; han llegado a la iglesia del Dios vivo,
inscrita en los cielos,
y tienen el nombre de Dios y de la ciudad de Dios escrita en ellos.
Entonces, he aquí una nueva madre que da a luz una generación celestial y espiritual.

No hay cisma, ni división, ni contienda,
ni pleito en la Jerusalén celestial ni en el cuerpo de Cristo,
que es hecho de piedras vivas, una casa espiritual.
Y Cristo no está dividido, porque en Él hay paz.
Cristo dice: "`En Mi tienen paz.`"
Él es de arriba y no de este mundo; pero en el mundo de abajo, en el espíritu de él,
hay dificultades.
Por tanto, manténganse en Cristo y caminen en Él. Amén.

[.signed-section-signature]
G+++.+++ Fox

[.postscript]
====

P+++.+++ S. Jerusalén era la madre de todos los verdaderos Cristianos antes de la apostasía;
y desde entonces,
los Cristianos externos están divididos en muchas sectas y han tenido muchas madres.
Pero todos los que han salido de la apostasía por el poder y Espíritu de Cristo,
tienen por madre a la Jerusalén de arriba, quien alimenta a todos sus hijos espirituales.

====

[.signed-section-signature]
G+++.+++ Fox

[.signed-section-context-close]
Leída en la Reunión Anual en Londres, 1691

--

Encuentro que William Goodbridge de Banwell, en Somersetshire,
fue liberado de prisión este año,
donde había estado confinado por unos trece años. Él había sido
condenado con la sentencia de premunire por rehusarse a jurar,
y sus bienes--de los cuales los bienes muebles fueron
estimados en casi doscientas cuarenta y cuatro libras,
y los bienes inmuebles calculados en sesenta libras anuales--fueron confiscados.
Sufrir el saqueo de bienes de esta manera, ha sido la porción de muchos otros,
y entre estos estaba Benjamín Brown, un anciano, de Brownish en Suffolk, quien también,
por no prestar juramento, fue despojado de todo lo que tenía,
de modo que su esposa e hijo se vieron obligados a acostarse en el suelo.

Ahora es tiempo de decir algo sobre la triste apostasía de George Keith,
quien estando en Pennsylvania,
hizo un gran alboroto ahí. Él era una persona ingeniosa y se le consideraba muy docto;
y había obtenido en la universidad el grado de máster en artes.
Él a menudo también daba pruebas de un alto conocimiento,
y estaba muy dispuesto a mostrar desde la filosofía,
las razones y causas de muchas cosas en la creación;
pero la doctrina de Francis Mercurius, varón de Helmons,
con respecto a la transmigración de las almas, había llegado a ser tan agradable para él,
que no sólo la aprobaba de muchas maneras,
sino que también se creía que había contribuido en el libro
que contenía doscientas preguntas sobre ese asunto,
gran parte de las cuales (como he sido informado) reconoció haberlas escrito él mismo,
aunque el libro había aparecido al público sin el nombre del autor.
Pero como esta idea no encontró aceptación entre los Cuáqueros,
su amor por ellos empezó a decaer.
Y su descontento se incrementó,
porque dos personas que se oponían a él habían usado
supuestamente algunas expresiones injustificables,
pero no habían sido tan severamente reprendidas como él,
que era de un temperamento ardiente, hubiera deseado.
Él acusó a estos dos hombres de decir que la luz interna
era suficiente para la salvación sin nada más;
y a partir de esto se esforzó por probar que ellos excluían al hombre Jesucristo,
como no necesario para la salvación; pero ellos negaron que esa fuera su doctrina.

Después dijo que William Stockdell,
una de las dos personas antes mencionadas en Filadelfia,
lo había acusado de predicar a dos Cristos,
porque predicaba la fe en Cristo dentro y en Cristo fuera de nosotros.
Ahora, aunque W. Stockdell no admitió que eso fuera cierto,
y algunos de los oyentes también negaron que eso se hubiera dicho, aun así,
G+++.+++ Keith le echó leña al fuego de esta disputa y se consiguió algunos partidarios.
También acusó al representante y gobernador Thomas Lloyd,
de haber dicho que la fe en el Cristo fuera de nosotros (que había
muerto por nuestros pecados y se había levantado de nuevo),
no era necesaria para nuestra salvación. Pero otros
dijeron que esas palabras no eran así,
y que el asunto no se había planteado con justicia.
Porque la pregunta no había sido si la fe en el Cristo fuera de nosotros
(que Él había muerto por nuestros pecados y se había levantado de nuevo),
era necesaria para nuestra salvación o no;
sino si la fe en la historia externa de la muerte y resurrección
de Cristo era indispensablemente necesaria para toda la humanidad,
y que nadie podía ser salvo sin ella, aunque no tuviera los medios,
oportunidad o capacidad de conocerla o recibirla.
Afirmado esto,
se pensó que tal posición no sólo excluía de la salvación a naciones enteras,
sino también a los infantes y a los sordomudos.
Pero hubiera sido mejor si tales preguntas nunca hubieran sido planteadas,
porque el mantenimiento apasionado de una posición diferente,
a menudo produce lucha y contienda.
Y George Keith, junto con otros, habiéndose separado entonces de la sociedad,
dijo que su descontento sólo
era con algunos Cuáqueros poco ortodoxos en América,
pero que estaba en unidad con todos los amigos fieles en Inglaterra.

Entonces comenzó a comportarse muy irrespetuosamente,
y por ello fue duramente reprendido por el mencionado Thomas Lloyd;
a quien no dudó de hablarle de manera reprochable,
acusándolo de insolencia y diciéndole que no era apto para ser gobernador,
y que "`su nombre apestaba,`" etc.
Y como algunos miembros del consejo no esperaban un mejor trato por parte
de él (ya que había llamado a uno de los magistrados "`bribón insolente`"),
esto se resintió mucho, y más aún,
porque G. Keith había publicado un documento en el que no sólo calumniaba escandalosamente
la diligencia de los magistrados en la detención de los ladrones,
sino también sus procedimientos judiciales contra los asesinos.
La consecuencia de este caso fue que G. Keith y un tal Thomas Budd,
con quien había compilado el citado documento, fueron multados por ello; sin embargo,
el gobierno fue tan moderado que la multa nunca fue exigida.
No obstante, G. Keith no dudó en levantar un gran clamor por sus sufrimientos,
y unos dos años después de esto llegó de nuevo a Inglaterra
para presentar su queja ante la iglesia en Londres.

Este año falleció Stephen Crisp en el mes llamado Agosto, cerca de Londres.
Hacía mucho tiempo que estaba débil de cuerpo y muy afligido por piedras, pero aun así,
había continuado su ministerio del evangelio.
Su servicio era muy aceptable porque tenía un don superior a muchos,
al ser no sólo sano en doctrina y juicio, sino serio y elegante en su expresión,
y bien calificado para convencer a sus oyentes, a menudo tocándoles el corazón,
de manera que generalmente se encontraba rodeado de una gran multitud de personas.
Cuatro días antes de su deceso, yaciendo enfermo en cama y sufriendo grandes dolores,
George Whitehead llegó a visitarlo, a quien Crisp le dijo en sustancia:
"`Veo el fin de la mortalidad, y sin embargo,
no puedo llegar a él. Deseo que el Señor me libere de este cuerpo adolorido.
Si Él sólo dice la palabra, es hecho.
No obstante, no hay ninguna nube en mi camino.
Tengo plena seguridad de mi paz con Dios en Cristo Jesús. Mi integridad
y rectitud de corazón son conocidas por el Señor,
y tengo paz y justificación en Jesucristo,
quien me hizo así.`" El día antes de su partida,
G+++.+++ Whitehead llegó a verlo y lo encontró en un estado agonizante y casi sin habla;
sin embargo se entendió que dijo: "`Espero, estoy siendo recogido, espero, espero.`"
G+++.+++ Whitehead, al despedirse de él le preguntó si deseaba comunicarle algo a los amigos;
a lo que él respondió:
"`Recuérdales mi cariñoso amor en Cristo Jesús a todos los amigos.`"
Al día siguiente, el 28 del citado mes, murió en Wandsworth,
a unas cinco millas de Londres.
Muchos de sus sermones tomados en taquigrafía de su boca están publicados,^
footnote:[Estos treinta y dos sermones están disponibles en friendslibrary.com]
y dan prueba de que ciertamente fue un ministro capaz del evangelio.

En este año murió también Catherine Evans, quien, como ha sido mencionado antes,
había estado encarcelada por largo tiempo en Malta.
Ella había sufrido mucho por su religión. En el año
1657 exhortó al pueblo de Salisbury al arrepentimiento,
y esto indignó tanto a los magistrados,
que por orden del juez Henry Ditton y el alcalde Robert Good,
fue desnudada y atada al poste de castigo en el mercado, y azotada.
Después de regresar allí y hablarle al pueblo en el mercado a modo de amonestación,
fue enviada a Bridewell, y puesta en un lugar oscuro y asqueroso.
Después de su regreso de Malta, el encarcelamiento fue su porción en varias ocasiones;
una en Welchpool, en Montgomeryshire, en el año 1666, por negarse a jurar;
y varios años después de esto, fue encarcelada también en Bristol.
Pero después de muchas adversidades y grandes sufrimientos,
murió habiendo llegado a una edad avanzada, y así entró en el reposo eterno.

Ahora vuelvo nuevamente a George Keith,
quien apareció en la asamblea anual en Londres en el año 1694;
pero ahí se mostró tan apasionado y bullicioso,
que no se pudo encontrar ningún medio para resolver las diferencias.
Parecía que había obtenido partidarios entre algunos
de los Separatistas de los alrededores de Londres,
pero cuando estos también se cansaron de él,
consiguió un lugar llamado Turner`'s Hall para predicar
allí. Al principio tuvo una gran concurrencia de personas,
dado que las novedades por lo general despiertan curiosidad.
Pero al parecer que cortejaba cada vez más a la iglesia de Inglaterra,
y que se unía a los Episcopales,
empezó a perder su estima entre el pueblo de otras persuasiones, en especial,
cuando finalmente se conformó por completo a la iglesia nacional,
a la que él había atacado antes muy celosamente por la prensa.
Y con el paso del tiempo, tomó la sotana y fue ordenado predicador entre ellos.
Después de esto, a veces predicaba con la sobrepelliz^
footnote:[Vestimenta blanca suelta que los ministros Episcopales
usan sobre otras prendas durante las ceremonias religiosas.]
puesta,
lo que con toda probabilidad habría aborrecido incluso
antes de haberse unido a los Cuáqueros,
porque había sido miembro de la iglesia Presbiteriana en Escocia,
la cual siempre había sido una celosa opositora de las ceremonias episcopales.
Y dado que George Keith había contradicho la doctrina
que él había afirmado y defendido antes,
y también había acusado a los Cuáqueros de una creencia
que ellos nunca habían admitido como suya,
se vieron obligados a exponer de nuevo su fe públicamente por la prensa, la cual,
a menudo habían afirmado con anterioridad tanto por palabra como por escrito,
para manifestar así,
que su creencia era realmente ortodoxa y en concordancia con las Sagradas Escrituras.
Esto lo hicieron mediante el siguiente tratado,
que en el año 1693 salió por la prensa en Londres como sigue:

[.embedded-content-document.paper]
--

[.letter-heading]
La Doctrina Cristiana y de la Sociedad del Pueblo Llamado Cuáqueros Absuelta de todo Reproche, etc.

Considerando que últimamente se han publicado por la prensa varios relatos sobre algunas
divisiones y disputas recientes entre personas bajo el nombre de Cuáqueros en Pennsylvania,
que tienen que ver con doctrinas fundamentales de la fe
Cristiana (como es pretendido por una de las partes),
y debido a que nuestros adversarios han aprovechado la oportunidad
para criticar tanto el ministerio Cristiano,
como a todo el cuerpo del pueblo comúnmente llamado Cuáqueros,
y su santa y Cristiana profesión,
tanto en Inglaterra como en todas partes (aunque no estén
involucrados en ninguna forma en la mencionada división,
sino que por el contrario, se han sentido afligidos y atribulados por ella,
y por el manejo indiscreto y reprochable de esto por la prensa):

Estamos, por tanto, tiernamente preocupados por el bien de la verdad,
en nombre de dicho pueblo,
y hacemos uso de nuestros justos esfuerzos para eliminar
la crítica y toda sospecha sin causa con respecto a nosotros,
en lo que se refiere a esas doctrinas del Cristianismo que se suponen
están en cuestionamiento por la citada división. Nosotros,
por tanto, en el temor de Dios y en la sencillez y claridad de Su verdad recibida,
solemne y sinceramente declaramos lo que nuestra creencia y profesión Cristiana ha sido,
y sigue siendo, con respecto a Jesucristo el unigénito Hijo de Dios, Su sufrimiento,
muerte, resurrección, gloria, luz, poder y gran día de juicio, etc.

[.offset]
Nosotros sinceramente profesamos:

Fe en Dios por Su unigénito Hijo Jesucristo, quien es nuestra luz y vida,
nuestro único camino al Padre,
y también nuestro único mediador y abogado para con el Padre.

Que Dios creó todas las cosas; que Él hizo los mundos por Su Hijo Jesucristo,
siendo Él la Palabra de Dios poderosa y viva por quien todas las cosas fueron hechas;
y que el Padre, la Palabra y el Espíritu Santo son uno, en Ser Divino inseparable;
un Dios verdadero, vivo y eterno, bendito por los siglos.

Sin embargo, esta Palabra o Hijo de Dios, en la plenitud del tiempo se encarnó,
se hizo hombre perfecto, según la carne,
descendió y vino de la simiente de Abraham y de David,
pero fue milagrosamente concebido por el Espíritu
Santo y nació de la virgen María. Además,
"`fue declarado ser el Hijo de Dios con poder, según el Espíritu de santidad,
por la resurrección de entre los muertos`" Romanos 1:4.

Nosotros creemos que en la Palabra (o Hijo de Dios) estaba la vida,
y la misma vida era la luz de los hombres; y que Él "`era la Luz verdadera,
que alumbra a todo hombre que viene a este mundo;`" por lo tanto,
los hombres deben creer en la luz, para que puedan llegar a ser hijos de la luz.
Por esto nosotros creemos en Cristo el Hijo de Dios como la luz y vida dentro de nosotros;
teniendo sincera reverencia y honor y creencia en Cristo en este sentido,
tal como lo hacemos en Su propia inaccesible e incomprensible gloria y plenitud;
porque Él es la fuente de la vida y de la luz, y el Dador de ellas a nosotros;
siendo--tanto como es en Sí mismo y como es en nosotros--no separado.
Y creemos que como hombre, Cristo murió por nuestros pecados,
se levantó de nuevo y fue recibido arriba en gloria en los cielos; habiendo sido,
en Su muerte por todos, esa única y grande ofrenda y sacrificio universal por la paz,
expiación y reconciliación entre Dios y el hombre;
y que "`Él es la propiciación por nuestros pecados; y no solamente por los nuestros,
sino también por los de todo el mundo.`"
"`Fuimos reconciliados por Su muerte, pero salvados por Su vida.`"

Nosotros creemos que Jesucristo,
quien está sentado a la diestra del trono de la Majestad en los cielos, es también rey,
sumo sacerdote y profeta en Su iglesia, "`ministro del santuario,
y del verdadero tabernáculo que el Señor levantó, y no el hombre.`"
Él es intercesor y abogado ante el Padre en el cielo,
y ahí se presenta delante de Dios por nosotros, compadeciéndose de nuestras flaquezas,
sufrimientos y dolores.
Y por Su Espíritu en nuestros corazones "`intercede
conforme a la voluntad de Dios,`" clamando:
Abba, Padre.

Nosotros creemos que a cualquiera que Dios haya dotado y
sinceramente llamado a predicar la fe en el mismo Cristo,
tal como es dentro y fuera de nosotros, esta no puede ser una predicación de dos Cristos,
sino la del único y mismo Señor Jesucristo,
teniendo que ver tanto con los grados de nuestro
conocimiento espiritual de Cristo Jesús en nosotros,
como con Su propia e inefable plenitud y gloria como son en Sí mismo,
en Su propio ser completo,
en donde Cristo mismo y la menor medida de Su luz o vida (en nosotros
como en la humanidad) no están separados ni son separables,
más de lo que el sol es separable de su propia luz.
Y como Él subió por encima de todos los cielos,
"`para llenarlo todo,`" Su plenitud no puede ser
comprendida o contenida en ninguna criatura finita;
y sin embargo, es conocida y experimentada en alguna medida en nosotros,
según seamos capaces de recibirla, "`porque de su plenitud tomamos todos,
y gracia sobre gracia.`"
Cristo nuestro Mediador recibió el Espíritu, no por medida, sino en plenitud;
pero a cada uno de nosotros fue dada la gracia "`conforme a la medida del don de Cristo.`"

Nosotros creemos que el evangelio de la gracia de
Dios debe ser predicado en el nombre del Padre,
del Hijo y del Espíritu Santo, siendo uno en poder, sabiduría y bondad, e indivisible,
o que no deben dividirse en la gran obra de salvación del hombre.

Nosotros sinceramente confesamos y creemos en Jesucristo,
que Él es tanto verdadero Dios como perfecto hombre;
y que Él es el autor de nuestra fe viva en el poder y la bondad de Dios,
como es manifestada en Su Hijo Jesucristo, y por Su propio bendito Espíritu,
o unción divina, revelada en nosotros,
por la que sentimos y gustamos internamente Su bien, vida y virtud;
y que nuestras almas viven y prosperan por y en Él.
El sentido interno de este poder divino de Cristo,
y fe en Él, y esta experiencia interna,
son absolutamente necesarios para hacer un Cristiano verdadero, sincero y perfecto,
en espíritu y vida.

Nosotros creemos que el honor y la adoración divinos se deben al Hijo de Dios;
y que a Él, en verdadera fe, se debe orar e invocar el nombre del Señor Jesucristo,
como hicieron los primeros Cristianos,
debido a la gloriosa unión o unicidad del Padre y del Hijo;
y que no podemos aceptablemente ofrecer oraciones y alabanzas a Dios,
ni recibir una respuesta o bendición misericordiosa de Él,
sino en y por medio de Su amado Hijo Cristo.

Nosotros creemos que el cuerpo de Cristo que fue crucificado no era la divinidad,
y sin embargo, que fue resucitado de entre los muertos por el poder de Dios;
y no cuestionamos en lo absoluto,
que el mismo Cristo que fue crucificado en dicho cuerpo, ascendió al cielo y a la gloria.
Su carne no vio corrupción, no se corrompió; no obstante,
es indudable que Su cuerpo fue transformado a una condición más gloriosa y celestial,
que la que tenía cuando estaba sujeto a diversos sufrimientos en la tierra.
Pero cómo y qué tipo de cambio experimentó después
de que fue resucitado de entre los muertos,
como para convertirse en un cuerpo tan glorioso como se declara que es,
es demasiado maravilloso para que los mortales lo conciban, comprendan o curioseen,
y más apropiado para que los ángeles vean.
La Escritura guarda silencio en este punto,
en lo que se refiere a la manera en que esto se realizó,
y no tenemos curiosidad de averiguar o disputar al respecto;
ni estimamos necesario hacernos sabios por encima de lo que está escrito con respecto
a la manera o condición del glorioso cuerpo de Cristo tal como está en el cielo;
ni tampoco consideramos necesario escudriñar cómo apareció
Cristo en varias maneras o formas después de Su resurrección,
o cómo entró en medio de Sus discípulos con las puertas cerradas;
o cómo se desapareció de la vista de ellos después de haber resucitado, etc.
Sin embargo, tenemos razones para creer que Su cuerpo, como está en el cielo,
ha sido transformado a una condición más gloriosa,
que trasciende por mucho la que tenía en la tierra, de lo contrario,
¿cómo podría ser transformado nuestro cuerpo inferior "`para que sea semejante a su
cuerpo glorioso`"? Porque cuando Él estaba en la tierra y estaba acompañado de sufrimientos,
se decía que era semejante a nosotros en todo, salvo en el pecado;
lo cual no puede decirse de Él ahora, que está en estado de gloria (por lo que Él oró);
de lo contrario, ¿dónde estaría el cambio, tanto en Él como en nosotros?

Nosotros creemos que la fe verdadera y viva en Cristo Jesús el Hijo del Dios vivo,
tiene que ver con: 1) Todo Su ser y plenitud; es decir,
con Él enteramente como es en Sí mismo,
y con todo el poder en el cielo y la tierra que le es dado a Él. 2) Con
el mismo Hijo de Dios que internamente se da a conocer a Sí mismo al alma,
en cada medida de Su luz, vida, Espíritu gracia y verdad.
Él es tanto la Palabra de fe como el Espíritu vivificador en nosotros,
por lo cual Él es la causa directa, el autor,
objeto y fuerza de nuestra fe viva en Su nombre y poder,
y de la obra de nuestra salvación del pecado y de la esclavitud
a la corrupción. El Hijo de Dios no puede ser separado de la menor
o más baja aparición de Su propia y divina luz o vida en nosotros,
o en la humanidad, así como el sol no puede ser separado de su propia luz.
Nosotros no establecemos la suficiencia de Su luz dentro de nosotros,
en oposición a Él como Jesucristo el hombre,
o en oposición a Su plenitud considerada como es en Él mismo;
ni decimos que cualquier medida o grado de luz recibida de Cristo, como tal,
puede ser llamada apropiadamente la plenitud de Cristo, o Cristo en plenitud;
ni esto Lo descarta, así considerado, de ser nuestro completo Salvador.
Porque conocer a Cristo mismo como nuestra luz,
nuestra vida y nuestro Salvador es tan congruente,
que sin Su luz no podríamos conocer Su vida,
no podríamos experimentarlo salvándonos del pecado o liberándonos de las tinieblas,
condenación o ira venidera.
Y donde el menor grado,
o menor medida de esta luz y vida de Cristo en el interior es sinceramente esperada,
seguida y obedecida, hay un bendito incremento de luz y gracia conocido y sentido,
tal como "`la senda de los justos resplandece más y más hasta que el día es perfecto.`"
De este modo,
se ha experimentado y se experimenta verdaderamente un crecimiento en la gracia
y en el conocimiento de Dios y de nuestro Señor y Salvador Jesucristo.
Y esta luz, vida o Espíritu de Cristo en el interior (pues son un sólo principio divino),
es suficiente para llevar a toda verdad,
teniendo en él las varias ministraciones tanto de juicio como de misericordia,
tanto de la ley como del evangelio, es decir,
de ese evangelio que se predica en toda criatura inteligente debajo del cielo.
No sólo manifiesta el pecado,
y reprende y condena por el pecado (como en su primera ministración);
sino también aviva y conduce a los que creen en él al verdadero arrepentimiento,
y así a recibir esa misericordia, perdón y redención en Cristo Jesús,
que Él ha obtenido para la humanidad en esos términos evangélicos de fe en Su nombre,
verdadero arrepentimiento y conversión a Cristo.

Así pues, la luz y vida del Hijo de Dios en el interior,
verdaderamente obedecidas y seguidas--al ser el principio del segundo o nuevo pacto,
o la Semilla o Palabra de fe en todos los hombres--no
dejan a los hombres o mujeres que creen en la luz,
bajo el primer pacto, ni como hijos de la mujer esclava,
como lo eran los judíos literales cuando habían dejado
al Espíritu de Dios y de Su Cristo en ellos;
sino que naturalmente los conducen al nuevo pacto, en el camino nuevo y vivo,
y a la adopción de hijos, para ser hijos de la mujer libre, o Jerusalén de arriba.

Es verdad que no debemos dejar de lado, ni de ninguna manera menospreciar,
sino más bien estimar altamente la verdadera predicación y las Sagradas Escrituras.
Tampoco debemos subestimar la sincera creencia y fe en Cristo,
como el que murió por nuestros pecados y se levantó de nuevo para nuestra justificación;
junto con Su aparición interna y espiritual, y Su obra de gracia en el alma,
que vívidamente abre el misterio de Su muerte y efectúa perfectamente nuestra reconciliación,
santificación y justificación. Y decimos que dondequiera que Cristo capacite
y llame a cualquiera a predicar y a demostrar el misterio de Su venida,
muerte, resurrección, etc., incluso entre los gentiles, ahí consecuentemente,
Él debe ser predicado, creído y recibido.

Sin embargo, suponiendo que haya habido, o haya tales gentiles piadosos y conscientes,
en quienes Cristo fue, y es como una semilla o principio del segundo o nuevo pacto,
la luz o la Palabra de fe;
y suponiendo que éstos viven recta y fielmente a la medida de luz que tienen,
o a lo que les es dado a conocer de Dios en ellos;
y suponiendo también que no tienen la ventaja externa de la predicación, las Escrituras,
o el conocimiento de la venida externa de Cristo; ¿pueden los tales, así considerados,
ser justamente excluidos del Cristianismo, o del pacto de gracia, en cuanto a la virtud,
vida y naturaleza de dicho pacto?
¿O deben ser todos excluidos de cualquier verdadero
conocimiento o fe en Cristo dentro de ellos,
a menos que también tengan el conocimiento de Cristo fuera de ellos?
¡Ciertamente no!
Porque eso implicaría la insuficiencia de Cristo y de Su luz dentro de ellos,
y frustraría el buen propósito de Dios y promesa en Cristo,
y Su amor y gracia gratuitos y universales para con la humanidad al enviar a Su Hijo.

Nosotros caritativamente creemos lo contrario; a saber,
que tales gentiles conscientes deben tener alguna fe verdadera en Cristo,
y algún beneficio de Cristo y Su mediación,
debido al amor gratuito de Dios en Cristo para con toda la humanidad,
y a que Cristo "`murió por todos los hombres,`" y fue dado "`como luz a los gentiles,
y para salvación hasta los confines de la tierra`"; y así, viviendo piadosa,
sincera y fielmente según la medida de Su luz en ellos, pueden ser aceptados y salvados.
Porque no podemos considerar razonablemente que un hombre sincero, piadoso o bueno,
esté totalmente vacío del verdadero Cristianismo, sea de la nación que sea;
porque nadie puede llegar a Dios o a la piedad sino por Cristo, es decir,
por Su luz y gracia en ellos.
Sin embargo, concedemos,
que si hay hombres o mujeres piadosos y sinceros que no tienen las Escrituras
o el conocimiento de Cristo (que fue externamente crucificado,
resucitó, etc.),
éstos no son perfectos Cristianos según el conocimiento y el entendimiento,
o según los puntos de doctrina y de la profesión externa de Cristo.
Pueden ser Cristianos sinceros y perfectos en género o naturaleza, en vida y sustancia,
aunque no así en conocimiento y entendimiento.
Un hombre o una mujer que tiene la vida y frutos del verdadero Cristianismo,
los frutos del Espíritu de Cristo en él, que puede hablar poco de credos,
puntos o artículos de fe (o tal vez, ni siquiera sabe leer), puede aun así,
ser un verdadero Cristiano en espíritu y vida.
De hecho, algunos podrían morir por Cristo,
aunque no hubieran podido disputar por Él. También
creemos que incluso los infantes que mueren en inocencia,
no están excluidos de la gracia de Dios, ni de la salvación en y por medio de Jesucristo,
quien está en ellos en alguna medida,
y ellos bajo el cuidado y especial Providencia de Dios.
Ver Mateo 18:2, 10.

Y aunque teníamos las Sagradas Escrituras del Antiguo y Nuevo Testamento,
y una creencia en Cristo crucificado y resucitado, etc.,
nunca conocimos verdaderamente el misterio de esto,
hasta que nos volvimos a la luz de Su gracia y Espíritu dentro de nosotros.
No sabíamos lo que era ser reconciliados por Su muerte y salvados por Su vida;
o lo que era experimentar la participación de Sus sufrimientos,
el poder de Su resurrección, o ser conformados a Su muerte,
hasta que Él abrió nuestros ojos,
y volvió nuestras mentes de las tinieblas a Su propia vida y luz divinas dentro de nosotros.

No obstante, nosotros valoramos sincera y grandemente las Sagradas Escrituras,
y la predicación y enseñanza de las personas fieles, divinamente inspiradas,
dotadas y capacitadas, y ministros de Jesucristo,
sabiendo que son grandes ayudas externas, e instrumentos en Su mano y por Su Espíritu,
para conversión,
dondequiera que le plazca a Dios proporcionar esas ayudas y medios externos.
No consideramos, ni podemos considerar,
la suficiencia de la luz o Espíritu de Cristo en el interior en ninguna forma,
como para desatender, menospreciar, rechazar o desestimar estas ayudas o medios externos;
porque todos proceden de la misma luz y Espíritu,
y tienden a dirigir las mentes de los hombres hacia Ello, y todo se centra en Ello.

Ni las Sagradas Escrituras ni la verdadera predicación externa,
pueden oponerse justamente a la luz o Espíritu de Dios, o a Cristo en el interior;
porque Sus mensajeros son ministros fieles,
enviados a volver a las personas a la misma luz y Espíritu en ellos.

Es cierto, que el misterio de la piedad es grande en sí mismo,
en su propio ser y excelencia; a saber, que Dios podía ser y "`fue manifestado en carne,
justificado en el Espíritu, visto de los ángeles, predicado a los gentiles,
creído en el mundo, recibido arriba en gloria.`"

Es también un misterio grande y precioso de piedad y Cristianismo,
que Cristo esté espiritual y efectivamente en los corazones de los hombres,
para salvarlos y liberarlos del pecado, de Satanás y de la esclavitud a la corrupción;
porque Él se revela así en los verdaderos creyentes, y mora en sus corazones por la fe,
'`Cristo en el interior la esperanza de gloria`', nuestra luz y vida,
"`el cual nos ha sido hecho por Dios sabiduría, justificación,
santificación y redención,`" 1 Corintios 1:30. Por lo tanto, este misterio de piedad,
como es en su propio ser y gloria,
y como es en los hombres (en muchos oculto y en algunos revelado),
ha sido y debe ser testificado, predicado y creído,
dondequiera que a Dios le plazca dar la comisión y preparar
los corazones de las personas para este misterio,
y no en la voluntad del hombre.

Con respecto a la resurrección de los muertos, al gran día de juicio que está por venir,
más allá de la tumba, o después de la muerte,
y a la venida externa de Cristo a juzgar a los vivos y a los muertos,
tenemos grandes razones para creer y no cuestionar,
lo que las Sagradas Escrituras claramente declaran y testifican de estos asuntos,
habiendo estado siempre listos a abrazar los testimonios
y profecías de Cristo y Sus apóstoles.

[.offset]
1+++.+++ En cuanto a la doctrina de la resurrección:

"`Si en esta vida solamente tenemos esperanza en Cristo,
los más miserables somos de todos los hombres`" (1
Corintios 15:19). Nosotros sinceramente creemos,
no sólo en una resurrección en Cristo del estado caído y pecaminoso aquí,
sino en una resurrección y ascensión a la gloria con Él en el futuro;
para que cuando Él al fin se manifieste, nosotros seamos manifestados con Él en gloria,
Colosenses 3:4;
1 Juan 3:2. Pero que todos los impíos que viven en rebelión contra la luz de gracia,
y mueran finalmente impenitentes, saldrán a una resurrección de condenación.

Y creemos que el alma o espíritu de cada hombre y mujer será reservado en su ser individual,
distinto y propio (de modo que habrá tantas almas en el mundo por venir como en este),
y cada semilla, sí, cada alma, tendrá su cuerpo propio e individual,
como a Dios le plazca darlo, 1 Corintios 15. Se siembra un cuerpo natural,
se resucita un cuerpo espiritual; siendo primero el natural y luego el espiritual.
Y aunque se dice que "`es necesario que esto corruptible se vista de incorrupción,
y esto mortal se vista de inmortalidad,`" aun así el cambio será
tal que '`carne y sangre`' no podrá heredar el reino de Dios,
ni la corrupción heredar incorrupción,
1 Corintios 15. Seremos resucitados fuera de toda corrupción y corruptibilidad,
fuera de toda mortalidad;
y los hijos de Dios y de la resurrección serán iguales a los ángeles de Dios en el cielo.

Y así como los cuerpos celestiales superan con creces a los terrenales,
así esperamos que los cuerpos espirituales en la resurrección
superen con creces a nuestros cuerpos ahora;
y esperamos que nadie nos culpe por esperar cuerpos mejores que los de ahora.
No obstante,
estimamos muy innecesario disputar o cuestionar cómo resucitarán los muertos,
o con qué cuerpos vendrán;
sino que sometemos esas cosas a la sabiduría y beneplácito del Todopoderoso Dios.

[.offset]
2+++.+++ En cuanto a la doctrina del juicio eterno:

Dios ha encomendado todo juicio a Su Hijo Jesucristo;
y Él es tanto juez de los vivos como de los muertos,
y de los estados y finales de toda la humanidad.
Juan 5:22; Hechos 10:42; 2 Timoteo 4:1; 1 Pedro 4:5.

Y creemos que en el futuro habrá una gran cosecha, que será el fin del mundo,
un gran día de juicio; y con respecto al juicio de ese gran día,
las Sagradas Escrituras son claras.
Mateo 13:39-41; 10:15; 11:24; Judas 6. "`Cuando el Hijo del Hombre venga en su gloria,
y todos los santos ángeles con él, entonces se sentará en su trono de gloria,
y serán reunidas delante de él todas las naciones, etc.`"
Mateo 25:31-32 hasta el final, comparado con Mateo 22:31; Marcos 8:38; Lucas 9:26;
1 Corintios 15:52; 2 Tesalonicenses 1:7-8 hasta el final, 1 Tesalonicenses 4:16;
Apocalipsis 20:12-15.

Creemos que este bendito hombre celestial, este Hijo del Hombre,
que tan profundamente ha sufrido y soportado tantas grandes
indignidades y persecuciones de parte de Sus adversarios,
tanto hacia Sí mismo como hacia Sus miembros y hermanos, al final, es decir,
en el último y gran día aparecerá--notable y manifiestamente en gloria y triunfo,
acompañado de todas Sus gloriosas y celestiales huestes y séquito--delante de las naciones,
delante de todos Sus enemigos y de aquellos que lo hayan negado.
Y esto será para gran terror y asombro de ellos,
que este gloriosísimo hombre celestial y Sus hermanos,
que han sido tan despreciados y menospreciados,
sean exaltados así sobre sus enemigos y perseguidores, en gloria y triunfo;
y que los que han sufrido con Él,
sean manifestados con Él en gloria y dignidad cuando Él se manifieste al fin.
Cristo fue juez del mundo y de su príncipe, cuando estuvo en la tierra;
Juan 9:39 y 12:31. Él sigue siendo juez del mundo, de la maldad y de su príncipe,
por medio de Su luz, Espíritu y evangelio en los corazones y consciencias de los hombre,
Juan 16:8-11; Mateo 12:20; Isaías 42:1; Romanos 2:16;
1 Pedro 4:6. Y Él será el juez y determinador final de ello en ese gran día señalado,
"`Dios ha establecido un día en el cual juzgará al mundo con justicia,
por aquel varón a quien designó.`" Cristo predijo que sería más tolerable
el día del juicio para los de la tierra de Sodoma y de Gomorra,
que para aquella ciudad o personas que no recibieran a Sus mensajeros o ministros, etc.
Mateo 10:15 y 11:24, Marcos 6:11; Lucas 10:
12-14. Es cierto que Dios sabe cómo librar a los piadosos de todas sus pruebas y aflicciones,
y al final sacarlos y levantarlos a la gloria con Cristo;
también sabe cómo guardar al injusto e impenitente para que el día del juicio sea castigado,
2 Pedro 2:9. Él los presentará en el día de ira, Job 21:30.
El Señor puede guardar y guardará a los criminales impenitentes,
presuntuosos y rebeldes,
atados bajo cadenas de oscuridad (como ha guardado a los ángeles caídos),
para el juicio del gran día, Judas 6;
Mateo 25:30. No nos corresponde a nosotros determinar
o disputar la manera cómo ellos serán guardados,
sino que lo dejamos a Dios; porque Él sabe cómo.

[.letter-heading]
Posdata relativa a la doctrina de la Resurrección y del Juicio eterno

A la final trompeta de Dios y a la voz del arcángel,
los muertos serán resucitados incorruptibles, los muertos en Cristo resucitarán primero.
1 Corintios 15:52; 1 Tesalonicenses 4:16, comparado con Mateo 24:31.

Muchos en este tiempo de prueba son a menudo alarmados
en la consciencia por la palabra y voz de Dios,
sin embargo, tapan sus oídos y desatienden Sus advertencias;
pero no podrán tapar sus oídos o escapar de la gran alarma final de la última trompeta,
porque inevitablemente los alcanzará y despertará finalmente para el juicio.
Aquellos que no se alarmen en sus consciencias para arrepentimiento aquí,
ni dejen sus pecados aquí, ciertamente serán alarmados para el juicio venidero.

Quienquiera que voluntariamente cierre sus ojos, odie,
desprecie o rehúya la luz de Cristo, o Su aparición en el interior,
al final se le hará ver,
y no será capaz de rehuir o esconderse de Su gloriosa
y terrible aparición desde el cielo,
con Sus poderosos ángeles, como con relámpagos y llamas de fuego,
para vengarse de todos los que no conocen a Dios,
ni obedecen el evangelio de nuestro Señor Jesucristo.
1 Tesalonicenses 4:16; Mateo 24:27; Lucas 17:24; Daniel 10:6; Job 37:3.

Y aunque muchos ahora evaden y rechazan las convicciones internas y el juicio de la luz,
y cierran los registros o libros de dichas convicciones y juicios en sus propias consciencias,
éstos al final serán abiertos y cada uno será juzgado por las cosas ahí registradas,
según sus obras.
Apocalipsis 20:12-15.

[.signed-section-closing]
Firmado en nombre de nuestra profesión Cristiana y del pueblo mencionado por,

[.signed-section-signature]
George Whitehead, Charles Marshall, Ambrose Rigge, John Bowater, William Fallowfield,
John Vaughton, James Parke, William Bingley.

--

Este documento fue en general satisfactorio y bien recibido en Holanda también,
donde después de traducirlo al holandés, logré publicarlo.
Ahora bien, dado que Francis Bugg, un apóstata envidioso,
culpó a los Cuáqueros de algunos conceptos socinianos,
y siendo alentado por algunos eclesiásticos, se esforzó por hacerlos odiosos al gobierno,
en Diciembre se presentó al Parlamento la siguiente
confesión de fe (firmada por treinta y un personas,
de las que G. Whitehead era una):

[.embedded-content-document.paper]
--

[.offset]
Sea conocido para todos que nosotros sinceramente creemos y confesamos:

[.numbered-group]
====

[.numbered]
I+++.+++ Que Jesús de Nazaret, quien nació de la virgen María, es el verdadero Mesías,
el mismo Cristo, el Hijo del Dios vivo, de quien todos los profetas dieron testimonio;
y que nosotros valoramos altamente Su muerte, sufrimientos, obras,
oficios y méritos para la redención de la humanidad, junto con Sus leyes,
doctrina y ministerio.

[.numbered]
II. Que este mismo Cristo de Dios,
quien es el Cordero de Dios que quita los pecados del mundo, fue inmolado,
estuvo muerto y está vivo, y vive para siempre en Su divina y eterna gloria,
dominio y poder con el Padre.

[.numbered]
III. Que las sagradas Escrituras del Antiguo y Nuevo Testamento, son de autoridad divina,
al haber sido dadas por la inspiración de Dios.

[.numbered]
IV. Que la magistratura o gobierno civil es ordenanza de Dios,
siendo sus buenos fines el castigo de los malhechores
y la alabanza de los que hacen bien.

====

--

Por medio de este y escritos similares,
los ojos de algunos que estaban en el timón empezaron a abrirse más,
e incluso entre los obispos había algunos inclinados a la moderación;
porque el rey se esforzó tanto como pudo,
por promover a los más moderados entre los eclesiásticos a esos altos puestos;
de modo que, el prejuicio que había cegado a muchos con respecto a los Cuáqueros,
empezó a disminuir más y más. Pero todavía había una cosa
que continuamente les causaba muchas dificultades,
a saber, su negativa a jurar;
porque debido a ello no sólo eran privados de sus derechos como hombres libres,
sino también de testificar en tribunales de justicia.
Por lo tanto, de vez en cuando presentaban peticiones al Parlamento,
en las que solicitaban ser liberados de esa pesada carga,
aunque hasta entonces no habían podido obtener ese favor.
Por tanto, el 26 de Noviembre, fue entregada una petición al Parlamento,
exponiendo los grandes sufrimientos que habían soportado porque
su solemne declaración no había sido aceptada en lugar del juramento.
Esta petición concluía así:

[.embedded-content-document.paper]
--

Por tanto, nosotros encarecida y humildemente solicitamos,
que tengan a bien darnos permiso de presentar un proyecto de ley,
que permita que nuestra solemne respuesta, afirmativa o negativa,
sea aceptada en lugar de un juramento, para aliviarnos en los casos antes mencionados,
o en los que ustedes en su sabiduría consideren convenientes.
Nosotros libremente proponemos,
que si alguno con reputación de ser Cuáquero falsifica la verdad,
y es debidamente condenado por ello,
que tal persona sea sometida a los dolores y penas que están
previstas contra las personas que cometen perjurio.

[.signed-section-signature]
William Mead, William Bingley, George Whitehead, Samuel Waldenfield, William Crouch,
John Staploe, Walter Rental, William Macker, Thomas Hart, Joseph Wright,
Jr. Michael Russet, Theodore Ecclestone.

--

[.offset]
Después de leída la petición en la Cámara de los Comunes,
se llegó a la siguiente resolución:

[.embedded-content-document.legal]
--

Una petición del pueblo llamado Cuáqueros fue leída. Se resolvió,
que la consideración de dicha petición se referiría a una comisión,
y que ellos informarán a la Cámara sus opiniones al respecto.

--

[.offset]
En consecuencia, se constituyó una comisión, que se reunió y dictaminó lo siguiente:

[.embedded-content-document.legal]
--

En general,
es la opinión de esta comisión que los Cuáqueros
sean liberados según lo solicitado en su petición.

--

Sin embargo, no se consiguió nada durante esa sesión,
ya que sus enemigos eran todavía lo suficientemente poderosos en el Parlamento,
como para encontrar medios de retrasar esta obra beneficiosa y detener su progreso.
Porque aunque los Cuáqueros ya no estaban expuestos
a la persecución a causa de su culto público,
seguían siendo vulnerables a otros abusos y malos tratos,
ya que aún no habían sido liberados en el caso de los juramentos.
Por lo tanto, el 22 de Diciembre del año 1694,
se entregó a los miembros del Parlamento una representación de su caso de no jurar,
firmada en nombre de ellos por Theodore Ecclestone, que decía lo siguiente:

[.embedded-content-document.paper]
--

[.centered]
=== Una breve declaración del por qué los Cuáqueros no juran, y por qué podrían haber sido, y aún pueden ser aliviados de esto por el Parlamento

Es una verdad cierta, que entre los Cristianos, y especialmente entre los Protestantes,
hay varias cosas en particular en religión que por
escrúpulos son conscientemente consideradas ilícitas,
y que otros estiman ortodoxas.
Por tanto,
no es de extrañar que los Cuáqueros difieran de muchos
otros (aunque no de todos) en este caso de los juramentos;
ya que creen que tienen absolutamente prohibido jurar en ninguna
manera por el claro mandamiento de Cristo en Mateo 5:34. Y que
ésta es innegablemente su verdadera profesión Cristiana,
se evidencia por los sufrimientos que han padecido durante muchos años por no jurar.

Por tanto, su caso puede merecer la atención caritativa del gobierno,
promulgando una ley para aliviarlos y no mantenerlos a ellos y
a sus familias expuestos a la ruina debido a su persuasión religiosa;
quienes, junto con sus vecinos,
alegremente pagan los impuestos para el sostén del gobierno,
y mediante sus oficios e industria, según sus capacidades,
hacen crecer el patrimonio nacional.

Por tanto, humildemente sugerimos, que es de interés del gobierno concederles este alivio.

La industria de ellos en el comercio, tanto terrestre como marítimo,
aporta beneficios al gobierno, y la posición que ocupan como comerciantes, granjeros,
fabricantes, mejoradores de tierras y haciendas,
es ventajoso para sus vecinos así como para los demás. Y
como no parece de interés para el gobierno en general,
que sean desanimados en su honesta industria,
así tampoco es de interés de ninguna parte eminente del gobierno (a saber,
los jueces) que no sean aliviados.

Porque los frecuentes litigios que se entablan contra los Cuáqueros,
ante los jueces de cancillería y hacienda, son sin duda muy molestos y onerosos,
debido a la dificultad de obtener un resultado justo por falta de juramento,
por lo que la justicia es retrasada y sus causas a menudo demoradas mucho tiempo.
Sin duda, cuando los jueces justos ven a los Cuáqueros agraviados y abusados,
y que no pueden aliviarlos, les resulta irritante; por lo que humildemente consideramos,
que sería de gran ayuda para estos tribunales que
los Cuáqueros sean liberados de los juramentos.

También es ventajoso para los otros tribunales del rey,
poder usar el testimonio de alguno que se llame Cuáquero, como testigo de una letra,
bono, deuda o escritura de contrato;
o cuando dé testimonio en casos de muertes no naturales,
en casos de allanamiento o delito, etc.

Viendo, pues, que su alivio es tan necesario para ellos,
tan inofensivo para todos y tan útil para el gobierno y sus vecinos,
consideremos un poco las objeciones comunes, que pueden resumirse así:

[.numbered-group]
====

[.numbered]
__Primera objeción:__ ¿Cómo podemos estar seguros de que dicen la verdad?

[.numbered]
__Segunda:__ ¿Por qué hay que modificar las leyes para ellos?

[.numbered]
__Tercera:__ Esto sería derribar viejos cimientos.

[.numbered]
__Cuarta:__ Les permitiría entrar en el gobierno.

====

[.offset]
Es de esperar que no resulte difícil responder a estas preguntas una por una,
y que sea razonablemente satisfactorio.

__En cuanto a la primera, es decir, la duda de certeza:__
Puede afirmarse racionalmente que quien está obligado a decir la verdad,
especialmente en contra de su propio interés (que
es donde radica principalmente la tentación,
si la hay), lo está por la ley de Dios, o por la ley de los hombres, o por ambas.

Ahora bien,
la obligación impuesta a la consciencia por la ley
de Dios constriñe a todos los hombres de bien,
tanto si responden con juramento como si lo hacen
mediante una afirmación solemne en el temor de Dios;
y los hombres deshonestos sólo están obligados por las leyes penales de los hombres.
Y si estas leyes penales son igualmente severas para los que dan
respuestas falsas tanto sin juramento como con juramento,
entonces serían igualmente eficaces y obligatorias tanto para los
que dan respuestas sin juramento como para los que juran.

[.small-break]
'''

__En cuanto a la segunda objeción, que sería una alteración de la ley:__
No sería una alteración de la sustancia de la ley, sino sólo de una circunstancia;
y si el cambio no tiene ninguna desventaja, sino que es realmente una enmienda,
y es una conveniencia para un pueblo honesto y laborioso, ¿por qué no habría de hacerse?
¿Qué sesiones del Parlamento se aprueban sin que se dicte una u otra ley para facilidad,
seguridad o alivio de algunos súbditos?

Si los extranjeros son demasiado duros para nuestra gente de mar,
pronto se promulga una ley del Parlamento para evitarlo.
Si nuestros pobres en casa necesitan seda para trabajar,
¿cuán pronto se les concede mediante una ley del Parlamento?
¿Y se va a conceder tan rápidamente la facilidad del comercio,
mientras se niega por tanto tiempo el alivio de consciencia,
sabiendo que el escrúpulo de este pueblo proviene de un mandato positivo de Cristo?

[.small-break]
'''

__Y para la tercera objeción, que esto es derribar viejos cimientos:__ Respondo que no;
que es más bien repararlos, lo cual es el trabajo propio del Parlamento.

¿No derogó el Parlamento el papismo, con todas sus pretensiones de antigüedad?
¿No promulgó un Parlamento la ley de __Habeas Corpus__^
footnote:[El acto de __Habeas Corpus__ otorgaba a las personas privadas de
libertad el derecho a impugnar la legalidad de su arresto o detención.]
contra la pretensión de prerrogativa real?
¿Era más razonable proteger a un súbdito del encarcelamiento de por vida por un rey,
sin haberle hecho un juicio, que impedir que un súbdito encarcele a otro hasta la muerte,
simplemente por no responder bajo juramento?
¿No le corresponde al Parlamento proteger al pueblo en sus bienes,
libertades y propiedades?
¿Y no debería corresponderle también al Parlamento proteger
a los Cuáqueros de la pérdida de todas sus propiedades,
simplemente porque no se atreven a cumplir con una circunstancia de la ley,
cuando (como ellos lo entienden) va en contra de un mandato expreso de Cristo?
Seguramente.
Y por lo tanto,
el alivio de ellos es un caso apropiado en el Parlamento
para ser tomado tiernamente en cuenta y acordado.

[.small-break]
'''

__En cuanto a la cuarta objeción, que tenderá a permitirles entrar en el gobierno:__
En respuesta a esto digo, que ustedes pueden impedirlo de la manera que les plazca;
sólo que no permitan que esta preocupación,
(de la que pueden ser eximidos tan fácilmente y de tan buena gana) sea un obstáculo
para el alivio y beneficio que el gobierno puede concederles tan fácilmente.

Pero mientras tengan la oportunidad por la posición en que la Providencia los ha colocado,
les ruego que sean de espíritus tan nobles y generosos como para aliviarlos,
aunque difieran de ustedes en la interpretación de un texto de
las Escrituras que ellos consideran claro y positivo a su favor,
y del que no se atreven a apartarse.
Y en esto tienen el acuerdo de muchos antiguos padres y mártires,
y más recientemente de los Menonitas y del difunto Francis Osbourne (esquire),
en sus [.book-title]#Reflexiones Políticas#, 7a edición, p. 319, quien hablando de casos judiciales,
llama al no jurar "`rendir sincera y fiel obediencia al precepto de nuestro Salvador,
'`no juréis en ninguna manera.`'`" "`Lo cual,`" dice él,
"`las glosas corruptas de nuestros expositores se esfuerzan mucho por eludir,
aunque todo en vano.`"
Y William Swinderby, en su apelación al rey, quejándose de los errores de los papistas,
dice: "`Como Cristo prohíbe jurar,
así el papa justifica jurar y obliga a los hombres a jurar.`"

Por lo tanto,
dado que los Protestantes se quejaron en un principio no sólo de los juramentos profanos,
sino también de los juramentos solemnes,
que a nadie le parezca extraño que los Cuáqueros
tengan ahora escrúpulos a la hora de jurar,
y que para estar tranquilos hayan buscado a menudo alivio en el Parlamento,
que es el lugar adecuado,
ya que creen que tienen de su parte la autoridad del mandato de Cristo,
la exhortación del apóstol (Santiago 5:12) y la doctrina de los mártires.
Y aunque algunos de ustedes no estén tan persuadidos,
dejen que el mundo contemple su justicia y voluntad, según el poder de ustedes,
de hacer el bien a todas las personas honestas y laboriosas que representan y gobiernan,
promulgando que su solemne afirmación sea aceptada en lugar de un juramento,
y que todos los que la falsifiquen sean castigados de la
misma manera que las personas que cometen perjurio.

Habiendo quedado claro ante un comité de este Parlamento, el 2 de Diciembre de 1692,
que este pueblo está expuesto a grandes penurias como se ha dicho;
y no sólo ellos mismos, sino también otros; dicho comité fue de la opinión,
e informó a la Cámara,
que los Cuáqueros debían ser eximidos de acuerdo con la solicitud
de la petición que presentaron entonces ante la Cámara.

Por lo tanto,
así como se les ha concedido la libertad de declarar su lealtad al gobierno sin jurar,
por cuya ayuda están sinceramente agradecidos, tengan a bien añadir a esa bondad,
su alivio en materia de juramentos entre ellos y otros súbditos,
así como entre el gobierno y ellos.

[.signed-section-closing]
Firmado en nombre del mencionado pueblo por,

[.signed-section-signature]
Theodore Ecclestone.

[.signed-section-context-close]
Londres, 22 de Diciembre de 1694.

--

Aunque después de entregar esta declaración,
el Parlamento no llegó este año a una resolución plena para alivio de ellos,
varios miembros se mostraron más inclinados a ello,
y el año siguiente el asunto fue sinceramente considerado de nuevo.

Al final de este año murió Mary II, reina de Inglaterra.
Ella fue, por encima de muchas,
una princesa eminentemente versada en la lectura y de gran conocimiento,
de lo cual sólo mencionaré, cómo el embajador del rey (su padre),
después de haber tratado de llevarla mediante muchos argumentos a la religión papista,
dijo después, en presencia de muchos grandes hombres,
que él antes no creía que pudiera encontrarse a una mujer en alguna
parte tan bien experimentada en la doctrina de la religión Cristiana;
y por eso, que él no le aconsejaba a nadie entrar en discusión con ella sobre ese asunto.

El 21 de Diciembre aparecieron algunos síntomas de viruela en la reina,
quien había estado enferma un día o dos antes,
y su enfermedad se agravó repentinamente a tal grado,
que los médicos empezaron a sentirse desesperanzados de su recuperación. Esto,
sin embargo, estaba tan lejos de atemorizarla, que dijo:
"`Gracias a Dios estoy preparada.`"
Esta quietud de espíritu no la abandonó,
ni siquiera cuando sintió que se aproximaba la muerte; porque entonces se le oyó decir:
"`Creo que voy a morir pronto;
y le doy gracias a Dios que desde mi juventud he aprendido esta verdadera doctrina,
que el arrepentimiento no debe ser aplazado hasta el lecho de muerte.`"
En tal disposición Cristiana continuó hasta la hora de su muerte,
y así entregó tranquilamente su espíritu a su Creador, de quien lo había recibido,
partiendo en Kensington no mucho después de la medianoche, entre el 26 y 27 de Diciembre,
dejando al rey con un dolor indecible, quien durante todo el tiempo de su enfermedad,
según se dice, no había salido de la recámara de ella.
Muchas plumas se afanaron en celebrar sus alabanzas y lamentar su muerte;
y tal vez ninguna reina haya sido más amada que ella en muchas edades.
Pero me detengo; otros han dado cuenta de sus excelentes cualidades y carácter al mundo,
y puede que ninguno mejor que el de Gilbert Burnet, obispo de Salisbury,
en un tratado titulado, [.book-title]#An Essay on the Memory of the late Queen#.^
footnote:[Ensayo en Memoria de la Difunta Reina.]
