== Capítulo XXIII

[.section-date]
1695--1702

[.chapter-synopsis]
* Sufrimientos de los Amigos en Barbados
* Final desastroso de varios perseguidores
* Penitencia de J. Batt
* Coronel Ruddock
* Ley que les permite a los Cuáqueros hacer una afirmación en lugar de un juramento
* G. Keith vuelve a denunciar a los Amigos
* G. Keith se hace Episcopal
* "`Declaración`" de la Cámara de los Comunes
* Testimonio de los Cuáqueros relativo a la "`Declaración`"
* Muerte y carácter de R. Haddock
* Carta de los Cuáqueros a William III sobre la firma de la paz
* Ley para restringir la prensa
* "`Serpiente en la hierba`"
* Relato de J. Crook
* Carta de los Amigos al Rey sobre la decisión de la sucesión
* Muerte del rey William
* Proclamación de la reina Ana
* Epístola de G. Fox sobre su primera misión
* Los frutos de la misión de G. Fox
* Relato de I. Penington sobre sí mismo
* Carta de J. Crook a I. Penington
* Caso de Susanna Withrow
* Convencimientos singulares
* Aumento de la Sociedad de los Amigos.

Ahora regreso al caso y asuntos de los Cuáqueros.
Dado que los de Barbados en América seguían siendo muy molestados por no tomar las armas,
el año 1695 enviaron una lista de lo que se les había quitado
bajo el gobierno de los coroneles Searle y Muddiford,
el presidente Wallum, los lores Francis Willowghby y William Willowghby,
los caballeros Jonathan Alkins y Richard Dutton,
y los coroneles Edwin Stede y James Kendall,
todo lo cual ascendía a 1423164 libras de azúcar
mascabado y 2910£ y 16 chelines en dinero.
A esta lista se unió un relato de las tragedias que
sufrieron varios de los perseguidores en Barbados,
en el que encuentro nombrados a más de treinta alguaciles o diputados,
que aunque se habían enriquecido con el botín y la
devastación de los bienes de personas honestas,
todos murieron pobres, y varios de ellos por muerte no natural, o con grandes dolores;
pero me abstengo de mencionar todos los detalles.
Entre ellos había un tal John Thurbon, mariscal del coronel Tidcomb,
quien solía burlonamente llamar a los Cuáqueros sus vacas lecheras,
diciendo que George Gray (uno de este pueblo) era una de sus mejores vacas lecheras,
y que le daba una gran cantidad de leche.
Porque él y otras aves de rapiña siempre tomaban mucho más de lo que sumaba la multa.
Pero al final este mariscal Thurbon murió en la pobreza,
aquejado de un gran absceso en el recto que no admitió cura.

Los Cuáqueros no sólo sufrían por no tomar las armas,
sino que con frecuencia se buscaban otras ocasiones para molestarlos.
Porque como los Cuáqueros,
con el fin de llevar a sus negros a un cierto conocimiento del verdadero Dios,
hacían que se reunieran una o dos horas a la semana
para instruirlos según la capacidad de ellos,
les leían algunas partes de las Sagradas Escrituras,
y les hablaban algo para dicho propósito, entonces,
se promulgó una ley que les prohibía dejar que los negros entraran en sus reuniones,
(aunque fueran celebradas en sus propias casas) bajo pena
de perder a cada negro que fuera encontrado ahí,
o en su lugar, ser multados con diez libras.

Un tal Thomas Cobham,
presentó una demanda contra Ralph Fretwell por ochenta de sus negros
que habían asistido a una reunión en su propia familia.
Pero aunque el juez John Merick hizo lo que pudo para ayudar al citado Cobham, aun así,
después de varias sesiones del tribunal, se dictó sentencia a favor del demandado.
Y fue notable que este T. Cobham, aunque era un joven robusto y apuesto,
se desanimó y se debilitó en general,
y poco después fue tomado por una fiebre e inflamación en su cuello y garganta,
que aumentó a tal grado, que hacia el final de su vida gritaba: "`¡Fuego, fuego;
estoy ardiendo!`"
Y a su madre le dijo que ella no necesitaba proporcionarle un ataúd,
porque él se quemaría antes de que lo hicieran, gritando:
"`¡Esto no es el cielo ni el infierno, sino todo fuego, fuego!`"
A lo que agregó:
"`Ahora los Cuáqueros dirán que es un juicio de Dios que ha caído sobre mí.`" De esta
manera terminó miserablemente sus días. La salida del juez Merick fue también funesta.
Porque cabalgando hacia su casa después de haber bebido demasiado,
fue tirado por su caballo, y su cerebro quedó tan herido,
que él permaneció por algunos días en una condición de violento desvarío,
para terror de sus amigos; y así murió. De igual manera William Sharp,
un juez de la corte que había sido un gran opositor
a que los Cuáqueros instruyeran a sus negros,
cabalgando de su casa a Brigdetown, se cayó del caballo y quedó tan herido,
que después no se le oyó decir nada, salvo: "`¡Oh, mi cabeza!`"
Y tres o cuatro días después de su caída, murió.

Sir Timothy Thornhill, mayor general,
había amenazado a menudo con quitarles la vida a los Cuáqueros,
y era un blasfemo tan abominable,
que me siento aterrorizado al leer las blasfemias más detestables y espantosas
que este miserable monstruo profirió. Porque estando en una fiesta y bebiendo
excesivamente al punto de que muchos de sus compañeros se negaron a beber más,
dijo que él deseaba ser Dios Todopoderoso para poder condenar las almas
de los que no estaban dispuestos a beber con él. En otro momento,
estando en compañía donde una mujer hablaba del poder y omnipotencia del Dios Todopoderoso,
respondió con este maldito lenguaje (peor que el del mismo diablo): "`Dios te maldiga,
sube a la copa de ese árbol a ver si Dios Todopoderoso te
salva de romperte el cuello antes de que golpees el fondo.`"
Paso en silencio otro lenguaje diabólico que dijo.
Cuando en una ocasión fue llevada delante de él una persona por no tomar las armas,
y le dijo que no podía hacerlo por motivos de consciencia, él le respondió:
"`¡Dios maldiga tu consciencia!
Si no puedo hacer que tu consciencia se incline,
haré que se doble tu testarudo lomo de perro!`"
Y así, él mismo le ató el cuello y los talones tan violentamente,
que casi privó al hombre de la vida.
Una vez también, cuando se publicó una declaración de guerra en la isla,
dijo que la primera vez que apareciera un enemigo colgaría a los Cuáqueros,
acompañando sus palabras con abominables juramentos, a los que estaba tan acostumbrado,
que rara vez hablaba sin ellos.
Pero al fin llegó el momento de ser removido de este mundo al otro.
Habiendo estado enfermo y luego bastante recuperado,
se jactaba entre sus compañeros de su conquista sobre la muerte,
y audazmente dijo que había negociado con Dios Todopoderoso treinta años más de vida.
Pero al cabo de unos meses de esto, el hilo de su vida fue cortado,
y su pretendido negocio fue arruinado por el Soberano del universo.
Así murió, sin que fuera lamentado por las personas sobrias, y maldecido por otros,
quienes perdieron mucho dinero por él,
a pesar de que su padre le había dejado una gran fortuna.

Mucho más feliz fue la salida del mariscal de Thornhill, John Batt,
quien también les había quitado muchos bienes a los Cuáqueros.
Pero en su lecho de muerte, unos años antes de esto (1679),
fue tan sensiblemente tocado por el arrepentimiento,
que hizo que se escribiera el siguiente documento y lo firmó.

[.embedded-content-document.address]
--

Yo, John Batt el más joven, de la isla de Barbados,
fui recientemente comisionado por el coronel Thornhill,
mariscal de su regimiento de infantería;
y por ese poder incauté las propiedades de varios del pueblo llamado Cuáqueros,
y tomé y me llevé muchos paquetes de su azúcar y otros bienes,
por no presentarse en armas a dicho regimiento,
lo cual ellos se negaron hacer por ternura de consciencia,
algo de lo que no tuve consideración. Pero ahora,
que el Señor ha puesto Su mano pesadamente sobre
mí afligiéndome con una dura y dolorosa enfermedad,
estas cosas hechas al mencionado pueblo vienen frescas a mi mente,
para mi gran dolor y terror;
y declaro que todos los pecados restantes de los que he sido culpable, que son muchos,
no perturban ni pesan tanto sobre mi consciencia como mis malos actos contra ese pueblo;
y creo que ningún hombre que practique tales cosas
contra dicho pueblo será jamás bendecido o prosperado.
En testimonio de lo cual firmo este décimo día de mayo de 1679.

[.signed-section-signature]
John Batt, Jr.

[.signed-section-context-close]
Testigo William Howard, Antrobus.

--

Bien hubieran hecho otros, si hubieran tomado ejemplo de esto;
pero no fue en vano lo que nuestro Salvador en la parábola del rico y Lázaro,
hace que Abraham le diga al rico: "`Si no oyen a Moisés y a los profetas,
tampoco se persuadirán aunque alguno se levantare de los muertos.`"
Sin embargo, otros perseguidores no tomaron la advertencia de este penitente John Batt,
porque no mucho después de esto,
algunos otros en Barbados mostraron con más furia su maldad y rabia contra los Cuáqueros,
y entre estos un tal Alexander Ruddock, escocés,
que no sólo era coronel de un regimiento de infantería,
sino también magistrado de un tribunal y uno de los miembros del consejo.
Él hizo que uno de la sociedad de los Cuáqueros fuera multado con
cuatrocientas libras de azúcar en pago de los salarios del sacerdote,
quien era su yerno, si bien, tras la queja de dicha persona y una investigación,
resultó que la pretendida deuda era sólo de diez libras de azúcar.
Y era bien conocido que este Cuáquero y sus amigos,
pagaban debidamente para mantener a los pobres y el arreglo de sus caminos;
pero nada de esto le sirvió,
porque le quitaron una vaca que valía diez libras esterlinas.
Y aunque algunos de los magistrados, al ver lo irrazonable de estos procedimientos,
le hubieran devuelto la vaca a su legítimo dueño,
era tal el poder del mencionado A. Ruddock, que no pudieron oponérsele.
Y cuando el mencionado Cuáquero se quejó del agravio y de la opresión que sufría,
Ruddock se indignó tanto,
que hizo que lo multaran con cinco libras esterlinas
por negarse a prestar juramento como alguacil,
aunque estaba dispuesto a desempeñar el oficio.
Para esta multa Ruddock emitió una orden judicial contra él,
por la que le fue quitada una mujer negra que fue vendida por veintiséis libras esterlinas,
y se retuvo todo el monto por la multa de cinco libras.
A este mismo hombre se le quitó el valor de más de siete
mil libras de azúcar en un año por orden de Ruddock;
y cuando el afectado se presentó ante él (en presencia de su hija,
la esposa del sacerdote) y le dijo que había sufrido todo eso por
quejarse del agravio que él le había hecho con su vaca,
Ruddock, como si se alegrara de ello,
le dijo que así sería cada año mientras él fuera magistrado.
Pero no vivió un año más después de esto.

Él era de un temperamento feroz y estaba muy dispuesto
a darle muerte a los negros como ejemplo,
diciendo:
"`¿Qué le importa a Barbados darles muerte a veinte
o treinta negros anualmente para dar ejemplo?`"
Y así como molestaba a los Cuáqueros de muchas maneras,
también mostraba su rencor quitándoles la comida que habían comprado.
En efecto, era tan malicioso,
que una vez que se encontró a un carnicero que llevaba comida para
la casa de un hombre que había comprado y pagado por ella,
él le ordenó que la devolviera diciendo: "`Los Cuáqueros no comerán carne fresca.`"
Pero finalmente la medida de su iniquidad llegó a su colmo,
porque un día que regresaba del consejo en el que se había emitido una
orden del gobernador para disolver las reuniones de los Cuáqueros,
él le prometió al gobernador obedecer diligentemente todas sus órdenes.
Pero en su camino de regreso a la casa se enfermó,
y cuando llegó pidió algo de cremor tártaro, el cual solía tomar en su caldo,
pero en su lugar y por su propio error tomó arsénico,
y así acabó miserablemente sus días. Y a pesar de lo malvado que había sido,
el sacerdote Kennedy, su compatriota, cuando predicó su sermón fúnebre,
no dudó en tomar su texto de las palabras del apóstol: "`He peleado la buena batalla,
he acabado la carrera, he guardado la fe.
Por lo demás, me está guardada la corona de justicia,
la cual me dará el Señor.`" En este sermón se declaró
que Ruddock había alcanzado la prudencia de un juez,
la dignidad de un coronel, el honor de un consejero;
que le había servido a su rey y a su país fielmente, y que había muerto como un santo.
Esta última expresión parecía estar relacionada con
algún arrepentimiento que había mostrado,
pero como quiera que fuera, debemos encomendarle eso a Dios; y mientras tanto,
no debemos confiar tanto en tal arrepentimiento,
puesto que Judas también se arrepintió de su maldad.
Si no buscara la brevedad,
yo podría relatar más casos notables con respecto a los perseguidores en Barbados;
pero aquí me detengo.

Ahora regreso a Inglaterra, donde el Parlamento se reunió a finales de este año,
y se ocupó de manera efectiva,
de hacer una ley que aliviara al pueblo llamado Cuáqueros
de la pesada carga de los juramentos.
Esta obra se topó con gran oposición,
porque aunque muchos miembros de buen carácter se inclinaban a ello con toda seriedad,
aun así, sus enemigos fueron tan activos en alterar y recortar el proyecto de ley,
que parecía que todo el proyecto hubiera quedado en nada.
Pero el rey mismo impulsó la obra, y sea dicho para alabanza suya,
que él fue el principal promotor de ella.
Así pues, a principios del año 1696 fue decretado por el rey y el Parlamento,
que la solemne afirmación y declaración del pueblo llamado Cuáqueros
sería aceptada en lugar de un juramento en la forma habitual,
como se desprende de la siguiente ley:

[.embedded-content-document.legal]
--

[.blurb]
=== Ley para que la Afirmación y Declaración Solemne del Pueblo Llamado Cuáqueros, Sea Aceptada en Lugar de un Juramento en la Forma Habitual.

Considerando que varios disidentes, comúnmente llamados Cuáqueros,
se niegan a prestar juramento en los tribunales de justicia y en otros lugares,
y por eso son frecuentemente encarcelados y sus propiedades confiscadas,
mediante un proceso de desacato emitido en dichos tribunales,
para la ruina de ellos mismos y de sus familias;
con el fin de remediarlo se promulga por la excelentísima majestad el rey--por
y con el consejo y consentimiento de los señores espirituales y temporales,
el presente Parlamento reunido y por la autoridad de dicho
Parlamento--que a partir del cuarto día de mayo de 1696,
a todo Cuáquero dentro de este reino de Inglaterra y el dominio de Gales,
que se le exija prestar juramento,
en cualquier ocasión legal y en cualquier caso en que la ley requiera un juramento,
en lugar de la forma habitual se le permitirá a ella o a él hacer
su afirmación solemne o declaración con las siguientes palabras:

[.offset]
"`Yo+++_____+++, declaro en presencia del Todopoderoso Dios,
que es testigo de la verdad de lo que digo, etc.`"

[.numbered-group]
====

[.numbered]
II. Esta solemne afirmación o declaración será pronunciada y tomada;
y por la presente se promulga y declara que tiene la misma fuerza y efecto,
para todos los propósitos, en todos los tribunales de justicia y en otros lugares,
dondequiera que se requiera un juramento por ley dentro
de este reino de Inglaterra y el dominio de Gales,
como si dicho Cuáquero hubiera prestado juramento en la forma habitual.

[.numbered]
III.
Se promulga además por la autoridad antes mencionada, que si algún Cuáquero,
al hacer tal afirmación o declaración solemne,
es legalmente condenado por haber afirmado o declarado deliberada,
falsa y corruptiblemente cualquier asunto o cosa,
lo cual habría equivalido a perjurio voluntario de haber declarado bajo juramento,
todo Cuáquero que así transgreda incurrirá en las mismas penas
y confiscaciones que las leyes y estatutos de este reino establecen
contra las personas condenadas por perjurio voluntario.

[.numbered]
IV. Se promulga, que ningún Cuáquero, o reputado Cuáquero,
en virtud de esta ley estará calificado o se le permitirá
dar testimonio en alguna causa penal,
o servir en algún jurado,
o desempeñar algún oficio o posición de beneficio para el gobierno.

[.numbered]
V+++.+++ Se dispone, que esta ley continuará en vigor por un período de siete años,
y a partir de ese momento hasta el final de la siguiente sesión del Parlamento,
y no por más tiempo.

====

--

De este modo fueron dispensados y liberados los Cuáqueros de esa
pesada carga por la que habían sido oprimidos por tantos años.

Ya se ha mencionado que George Keith consiguió un lugar
en Londres llamado Turner`'s-hall para predicar ahí,
y así como su auditorio consistía principalmente
en personas que tenían envidia contra los Cuáqueros,
había también entre ellos muchos del tipo vulgar,
quienes generalmente eran volubles e inestables, y a menudo inclinados a las novedades.
Y aunque Keith en algunos aspectos todavía deseaba
ser considerado partidario de los Cuáqueros,
aun así,
había publicado algunos documentos en los que se esforzaba por
hacer parecer que ellos mantenían varios sentimientos heterodoxos.

Los libros que había publicado con respecto a este asunto
fueron tan plenamente respondidos por los Cuáqueros,
que al no poder responder a sus respuestas,
pretendió que no estaba en condiciones financieras para poner la
imprenta a trabajar y asumir los gastos de impresión. Pero era
bien sabido que ésta era una frívola evasión. Sin embargo,
para hacer algo, recurrió a otro plan y publicó un aviso diciendo,
que el 11 del mes llamado junio, defendería su acusación contra los Cuáqueros,
por lo que convocó a algunos de ellos para que se presentaran
en ese momento y respondieran por sí mismos.
Comenzando entonces a conformarse con los Episcopales, según dijo después,
él le había avisado de sus intenciones al alcalde de Londres, y como éste no lo prohibió,
hizo que se sintiera más audaz.
Pero los Cuáqueros pensaron que no era conveniente
presentarse ahí para entrar en una disputa con él,
en parte porque el rey en ese momento estaba al otro lado del mar,
y muchas de las personas comunes estaban ociosas por falta
de trabajo y comercio (ocasionado por la escasez de dinero,
que entonces era muy grande, debido al acuñado), de modo,
que no se podía prever si algunas personas descontentas
se reunirían y causarían un disturbio peligroso.
Por tanto, declinaron presentarse y dieron las siguientes razones de su negativa,
las cuales fueron leídas en la citada reunión y después publicadas en la prensa:

[.embedded-content-document.paper]
--

Considerando que George Keith, según su habitual manera irregular y revoltosa,
ha desafiado a varios de nosotros a defendernos contra las
acusaciones que él desea presentar contra nosotros en Turner`'s-hall;
lo siguiente es para certificar las razones por las
que declinamos cualquier reunión de este tipo,
ante todos aquellos que les interese:

[.numbered-group]
====

[.numbered]
__Primera:__
Porque el citado G. Keith nos ha dado frecuentes pruebas de su muy apasionado y abusivo
comportamiento en las muchas reuniones privadas que hemos tenido con él,
ante toda manera de dulzura,
longanimidad y paciencia de nuestra parte para satisfacerlo y preservarlo de estos extremos;
de modo que no podemos esperar ahora una mejor acogida,
ni que la reunión tenga el éxito deseable.

[.numbered]
__Segunda:__ Declinamos reunirnos porque no es una reunión acordada por ambas partes,
como debería haber sido.
Y donde esto no es posible, la prensa es la siguiente manera justa y expedita,
que de hecho él ha comenzado, pero que ahora parece declinar;
ni nos ha enviado alguna copia de sus cargos o acusaciones contra nosotros,
lo que también debió haber hecho.

[.numbered]
__Tercera:__
Él tiene dos de nuestros libros que nos defienden
a nosotros y a nuestras doctrinas de sus acusaciones,
y que él no ha respondido aún;
de modo que no está en igualdad de condiciones con nosotros.
Por tanto, nosotros creemos que su desafío, reunión y convocatoria son injustos,
y creemos que todos los que no son parciales serán de la misma opinión de nosotros.

[.numbered]
__Cuarta:__
Tales reuniones públicas y descontroladas son muy a menudo acompañadas con pasión,
ligereza y confusión, y no responden al fin deseado por hombres sobrios e inquisitivos.
Además de esto,
puede establecer una práctica que las autoridades
pueden juzgar como un abuso de nuestra libertad,
y hacer que parezca que no somos amigos de la paz civil.

[.numbered]
__Quinta:__ Nosotros no sabemos a qué religión o persuasión pertenece este hombre vacilante,
ni a qué iglesia o pueblo está unido,
ni quién le recibirá o reconocerá con sus vanas especulaciones,
o quién será responsable ante nosotros de él y de sus irregularidades y abusos.

[.numbered]
__Sexta y última:__ Por tanto, sea sabido por todos,
que por el bien de la verdadera religión,
la libertad que se nos ha concedido y la paz civil, declinamos reunirnos con él;
y no por ningún temor que tengamos de sus habilidades,
ni por nuestra propia consciencia de error,
ni por ninguna injusticia hacia el citado G. Keith;
cuyo temperamento débil y desenfrenado sabemos que es tal,
que por mucho aprendizaje y habilidades que tenga,
no han sido capaces de equilibrarlo y sostenerlo en ocasiones menores,
de modo que podemos decir que están en malas manos.
Y si él prosigue como ha comenzado,
todos sus dones y aprendizaje serán empleados para un triste fin,
el cual--¡pobre hombre! --no puede ser de otro modo a menos que cambie de rumbo.
En efecto,
oramos de todo corazón para que él pueda encontrar un lugar de arrepentimiento;
y que a través de una verdadera contrición,
encuentre la remisión de su gran pecado de envidia,
y del perverso trato al pueblo y camino de Dios que nosotros profesamos,
y que él también--el citado G. Keith--ha profesado por mucho tiempo,
incluso recientemente, y celosamente defendido como tal.

====

--

Como se ha dicho,
estas razones fueron publicadas por los Cuáqueros para demostrarle al mundo,
que no habían aceptado la convocatoria de G. Keith por razones de peso.
Ahora, aunque George Whitehead y Wiiliam Penn, por las razones arriba mencionadas,
no se presentaron a Turner`'s-hall,
aun así algunos de sus amigos estaban ahí como espectadores,
para ver qué sucedería. G. Keith, viéndose así defraudado en su intención, se encargó,
sin embargo, de defender su acusación en ausencia de sus adversarios,
lo cual pudo hacer fácilmente, dado que nadie le contradijo;
y fue aplaudido por los frecuentes gritos de la turba que se había reunido en gran número.
Después de que se leyeron las razones de la no presentación de los Cuáqueros,
Keith señaló que no eran satisfactorias, calificándolas de "`endebles,
débiles y frívolas.`"
"`Qué,`" dijo, "`¿puede un criminal poner esta excusa:
'`No me llamarán ante un juez sin mi consentimiento`'? No. Si un hombre me roba,
puedo quejarme de él como ladrón, y sin su consentimiento pedirle cuentas.`"
Esta razón la publicó en la prensa en su relato del
trabajo de ese día. Pero quién hubiera pensado antes,
que un hombre tan pequeño como él, se sintiera tan grande ante sus propios ojos;
porque parecía que él pensaba que los Cuáqueros estaban obligados
a presentarse como criminales delante del pretendido juez Keith,
acompañado de sus asistentes, la chusma.
Y para seguir con la comparación de G. Keith,
aunque un criminal no pueda decir "`no me llamarán
ante un juez sin mi consentimiento;`" aun así,
podría decir con alguna buena razón,
"`no te harás a ti mismo juez,`" como Keith hizo entonces.
Es probable que él contara con el apoyo de algunos grandes eclesiásticos,
de lo contrario, una acción tan audaz fácilmente podría haberle perjudicado.

Mis límites no admiten un relato circunstancial de
lo que se trató en ese momento en Turner`'s-hall,
sin embargo, a fin de mostrar brevemente cómo manejó G. Keith los asuntos,
procederé a dar uno o dos ejemplos, dado que _ut ex ungue leonem_
(es decir, el todo puede ser juzgado por la parte).
Él dijo que acusaría a los Cuáqueros de nada más,
de lo que probaría a partir de los propios escritos de ellos, y continuó así:
"`Ofrezco probar que George Whitehead ha negado que Cristo sea Dios y hombre.`"
Esta fue una extraña afirmación, de hecho,
dado que era bien conocido que G. Whitehead había publicado
un libro de más de veinte hojas de extensión titulado:
[.book-title]#La Divinidad de Cristo, y la Unidad de los Tres que Dan Testimonio en el Cielo,
con el Bendito Fin y Efecto de la Aparición de Cristo, Su venida en la Carne,
Sufrimientos y Sacrificio por los Pecadores,
Confesadas y Defendidas por Sus Seguidores Llamados Cuáqueros.#
G+++.+++ Keith no podía pretender ignorancia de este libro,
porque escogió algo de él en su narración. Pero a fin de mantener su acusación,
apeló a un libro de G. Whitehead llamado [.book-title]#La Luz y Vida de Cristo en el Interior.#
G+++.+++ Whitehead había escrito este libro en respuesta a W. Burnet, un predicador Bautista,
quien escribiendo de Cristo dijo: "`Como Él era Dios, era Co-Creador con el Padre,
por tanto, era antes de Abraham y tenía Gloria con Dios antes de que el mundo fuera,
y en ese sentido descendió del cielo.`"
A esto G. Whitehead respondió: "`¿Qué lenguaje sin sentido y no escritural es éste,
hablar de que Dios es Co-Creador con el Padre?
¿O que Dios tenía gloria con Dios?
¿No implica esto dos dioses?
Que el lector juzgue.`"
Ciertamente, de esto se desprende claramente,
que G. Whitehead no intentaba otra cosa sino censurar
las expresiones no escriturales de su oponente,
como Co-Creador, implicando dos dioses; pues no sólo el apóstol dice:
"`Dios es Uno,`" sino que Cristo mismo dice: "`Yo y mi Padre somos Uno.`"
No obstante, G. Keith no dudó en decir:
"`G. Whitehead niega la divinidad de Cristo y engaña
a la nación y al Parlamento al decirles,
que los Cuáqueros reconocen a Cristo como Dios y hombre,
y que creen todo lo que está registrado de Él en las Sagradas Escrituras.`"

Ahora, para probar que G. Whitehead había negado que Cristo fuera hombre,
Keith citó el siguiente pasaje del antes mencionado
libro llamado [.book-title]#La Divinidad de Cristo, etc.:#
"`¿Dónde dicen las Escrituras que Su alma fue creada?
Pues, ¿no era Él el resplandor de la gloria del Padre,
la imagen misma de Su divina sustancia?
Pero, suponiendo que el alma de Cristo fue creada con el cuerpo en el tiempo, etc.`"
Aquí Keith interrumpió su cita y omitió las siguientes palabras: "`Yo pregunto,
¿si desde la eternidad Él era una '`persona`' distinta de Dios y de Su Espíritu Santo,
sin alma o cuerpo?
¿Dónde habla la Escritura de alguna '`persona`' sin alma o cuerpo?
Debemos ver pruebas claras de estas afirmaciones en las Escrituras.`"
Ahora,
aunque G. Whitehead había escrito esto para mostrar
cuán a menudo nos metemos en complicadas dificultades,
cuando no nos ceñimos a las Sagradas Escrituras (que en ninguna
parte habla de tres '`personas separadas`' en la Deidad);
con todo, Keith tergiversando abusivamente el pasaje, le dijo a su audiencia:
"`Aquí se ve que él no reconocerá que Cristo tenía un alma creada.`"
De esta manera razonó y trató Keith otros pasajes del citado libro.
Pero cuán ferozmente se habría quejado con otros,
si ellos hubieran citado sus palabras en pedazos y fragmentos.

Pero al verse que él se declaraba cada vez más en favor de la iglesia Episcopal,
alguien de esa persuasión (que se dio a conocer únicamente por las letras W. C.)
se ocupó de demostrar lo cambiante de la opinión y sentimientos de Keith,
a partir de los propios escritos que él había publicado de forma impresa.
De este modo probó claramente,
que Keith se había convertido en un apóstata en todos los sentidos,
aunque él parecía muy ofendido con los Cuáqueros porque
lo habían llamado así. "`Pero,`" dijo este autor,
"`si los principios Presbiterianos, de cuya sociedad Keith fue una vez miembro,
eran mejores que los de los Cuáqueros,
entonces el señor Keith es un apóstata al rebelarse y desertar de los Presbiterianos,
al cambiar su abrigo al estilo Cuáquero.
Pero si los Cuáqueros tenían más razón que los Presbiterianos,
entonces lo contrario es verdad.`"

Entonces parecía adular al clero Episcopal,
y estimaba lícitas cosas a las que antes se había opuesto celosamente.
Pues tenía la esperanza de que oponiéndose a los
Cuáqueros sería mejor recompensado entre los Episcopales;
y esto no era del todo sin razón,
porque como ya no estaba en poder de ellos perseguir
a los Cuáqueros de la misma manera que antes,
usaron otros medios para hacerlos odiosos a ellos y a sus doctrinas.
Para este propósito Keith les parecía una herramienta útil,
porque él no sólo era de temperamento ingenioso e impetuoso, sino también astuto, sutil,
malicioso y violento en sus expresiones.
Y para acusar a los Cuáqueros de herejes,
él mismo se lanzó a una opinión contraria a la verdadera doctrina Cristiana,
insistiendo que el conocimiento histórico de los sufrimientos, muerte, resurrección,
etc. de Cristo,
era absolutamente necesario para la salvación. Quién podría haber
imaginado que este mismo G. Keith acusaría a los Cuáqueros de herejes,
en un punto de doctrina que él con frecuencia había defendido tan eficazmente;
entre otros, en un libro contra un tal Cotton Mather, en el que,
bajo la acusación de que ellos eran culpables de muchas herejías y blasfemias,
Keith dijo de esta manera:
"`Nuestros principios concuerdan en su mayoría con
los artículos fundamentales de la fe Cristiana Protestante.
Según mi mejor conocimiento del pueblo llamado Cuáqueros,
y de aquellos reconocidos por ellos como predicadores y publicadores de
sus creencias (los que son de una incuestionable estima entre ellos,
y dignos de doble honor, como hay muchos así),
no conozco a ninguno que sea culpable de tales herejías y blasfemias como se les acusa.
Y creo que debería conocer, y conozco a los llamados Cuáqueros,
habiendo estado a menudo entre ellos,
tanto en reuniones públicas como en discursos privados
con los más notables y estimados entre ellos,
desde hace unos veinte años, y eso en muchos lugares del mundo,
tanto en Europa como en América.`"
¿Quién hubiera pensado entonces,
que alguien que había caminado tantos años con los Cuáqueros,
que había predicado su doctrina y la había defendido públicamente,
tanto por escrito como de palabra,
después los hubiera tachado de negadores de los puntos más esenciales de la fe Cristiana?
Pero dejemos que el caso de Balaam sirva como prueba,
de las extravagancias a las que la ganancia temporal puede llevar a un hombre.

En todo este relato del comportamiento de George Keith,
no he expuesto más que lo que creo que es verdaderamente cierto.
Ni me he esforzado por agravar sus fracasos, porque nunca le tuve mala voluntad,
sino una buena estima cuando le creía recto,
porque en ese tiempo percibía en él algunas buenas habilidades.
Y aún deseo de corazón que le plazca a Dios, desde Su inescrutable misericordia,
que toque su corazón antes de que se cierre la puerta de la gracia,
para que al ver la grandeza de su transgresión,
pueda mediante un verdadero arrepentimiento, obtener perdón del Señor por su mal;^
footnote:[Nota del Editor:
George Keith continuó injuriando y persiguiendo a los Amigos durante muchos años,
cuyos detalles pueden encontrarse en los diarios de John Richardson, Samuel Bownas,
Thomas Wilson, James Dickenson y otros.
Cayendo cada vez más en el descrédito general,
muchos de los vecinos de Keith solían decir que se alegrarían si los Cuáqueros lo readmitían,
para librarse de un espíritu tan turbulento.
William Hodgson,
en su [.book-title]#Select Historical Memoirs of the Religious Society of Friends,#
relata la siguiente información interesante sobre sus últimos días:
"`Hay motivos para esperar, que cerca del final de su vida,
George Keith tuviera algunas horas de seria reflexión,
en las que se dio cuenta de la paz que una vez había
disfrutado en comunión con los Amigos,
y sintió remordimiento por su pérdida; porque en una visita a Hurst-pierpoint,
durante una conversación sobre los Cuáqueros, reconoció ante varias personas,
que desde que los había abandonado, había perdido una cualidad que tenían entre ellos,
a saber,
que en sus reuniones religiosas podían detener todos
los pensamientos que obstaculizaban sus devociones,
algo que, admitió, nunca había podido lograr desde entonces.
Y cerca del final de su vida, un Amigo le hizo una visita;
la cual pareció recibir amablemente,
y entre otras observaciones se expresó en este sentido:
'`Desearía haber muerto cuando era Cuáquero,
porque entonces estoy seguro de que habría estado bien con mi alma`'.`" Murió en Sussex,
Inglaterra, el 27 de marzo de 1716.]
el cual considero peor,
porque mediante su astucia se esforzó por poner falsos
colores sobre cosas que eran realmente buenas,
y así introducirse en el favor del partido Episcopal.^
footnote:["`Esto lo escribí unos años antes de saber que G. Keith había fallecido.`"
--William Sewel]
Porque entonces,
el viejo cuento de que había emisarios papistas entre
los Cuáqueros fue revivido y divulgado otra vez.
Y tres clérigos Episcopales en Norfolk redactaron
también un documento para el rey y el Parlamento,
con la intención de difamar a los Cuáqueros a partir de sus propios escritos;
pero George Whitehead, William Penn y otros,
no tardaron en demostrar cómo habían pervertido sus
palabras o el verdadero significado de ellas.

En esta época, el anterior rey James se propuso invadir Inglaterra,
y en Francia se hicieron grandes preparativos para eso.
También se descubrió un complot en Inglaterra contra el rey William,
lo que le dio ocasión a la Cámara de los Comunes de redactar una
especie de declaración que debían firmar todos sus miembros,
que dice:

[.embedded-content-document.legal]
--

Considerando que ha habido una horrible y detestable conspiración,
formada y llevada a cabo por papistas y otras personas perversas y traidoras,
para asesinar a la persona real de su majestad,
y de esa manera alentar una invasión desde Francia, para menoscabar nuestra religión,
leyes y libertades; nosotros, cuyos nombres se suscriben aquí, prometemos,
testificamos y declaramos de corazón, sincera y solemnemente que su majestad actual,
el rey William, es el justo y legítimo rey de estos reinos.
Y mutuamente prometemos y nos comprometemos a apoyarnos y a ayudarnos unos a otros,
en la medida de nuestro poder,
en el apoyo y defensa de la más sagrada persona y gobierno de su majestad,
contra el anterior rey James y todos sus partidarios.
Y en caso de que su majestad sufra una muerte violenta e inoportuna--que Dios
no lo permita--por la presente nos obligamos libre y unánimemente a unirnos,
asociarnos y apoyarnos unos a otros, para vengarnos de sus enemigos y sus partidarios,
y para apoyar y defender la sucesión de la corona,
en acuerdo con la ley promulgada el primer año del
reino del rey William y de la reina Mary,
titulada: __"`An Act declaring the Rights and Liberties of the Subjects,
and settling the succession of the Crown.`"__^
footnote:[Ley por la que se declaran los derechos y libertades
de los súbditos y se establece la sucesión de la corona.]

--

Una declaración fue firmada también por los lores, y ambas fueron presentadas al rey,
y fueron seguidas por todas las casas en Inglaterra.^
footnote:[Ver [.book-title]#La Vida del Rey William,# vol. III]
Los disidentes también presentaran declaraciones
al rey que tenían ciertas semejanzas con las otras.
Pero los Cuáqueros, que profesaban una conducta de no resistencia e inofensiva,
de ninguna manera podían entrar en tal coalición. Sin embargo,
para demostrar que eran leales y fieles al rey,
redactaron la siguiente declaración y la publicaron en la prensa:

[.embedded-content-document.paper]
--

[.blurb]
=== El antiguo testimonio y principio del pueblo llamado Cuáqueros renovado, con respecto al rey y al gobierno, y tocante a la reciente declaración:

Nosotros, el citado pueblo, declaramos solemne y sinceramente,
que ha sido nuestro juicio y principio desde el primer día que fuimos llamados
a profesar la luz de Jesucristo manifestada en nuestras consciencias hasta hoy,
que el establecimiento y destitución de reyes y gobernantes,
es una prerrogativa propia de Dios, por razones mejor conocidas por Él;
y que no es nuestro trabajo u ocupación meter una mano o tener algún artificio en ello,
ni entrometernos en asuntos por encima de nuestra posición. Mucho menos nos corresponde
planear y conspirar la ruina o derrocamiento de ninguno de ellos,
sino orar por el rey y la seguridad de nuestra nación,
y por el bien de todos los hombres,
para que podamos vivir una vida pacífica y tranquila en toda piedad y honestidad,
bajo el gobierno que Dios se complazca poner sobre nosotros.

Y de acuerdo con este nuestro antiguo e inocente principio,
a menudo hemos dado nuestro testimonio, y lo damos ahora, contra todo complot,
conspiración, maquinación e insurrección contra el rey o el gobierno,
y contra todos los designios traicioneros, bárbaros y asesinos cualesquiera que sean,
como obras del diablo y de las tinieblas.
Nosotros sinceramente bendecimos a Dios,
y de corazón le agradecemos al rey y al gobierno,
por la libertad y los privilegios que disfrutamos bajo ellos por ley,
estimando que es nuestro deber ser fieles y leales a ellos.

Y considerando que se nos requiere firmar la mencionada declaración,
sinceramente declaramos que nuestra negativa a hacerlo
no se debe a ninguna desafección al rey o al gobierno,
ni tampoco en oposición a que haya sido declarado el justo y legítimo rey de estos reinos,
sino puramente, porque no podemos por asuntos de consciencia pelear, matar o vengarnos,
ni por nosotros mismos ni por ningún otro hombre.

Creemos que el descubrimiento oportuno y la prevención del último
plan bárbaro y malicioso complot contra el rey y el gobierno,
y los tristes efectos que podrían haber tenido,
es una notable misericordia del Todopoderoso Dios.
Y por esto, nosotros y toda la nación,
tenemos grandes motivos para humildemente estar agradecidos,
y orar por la continuación de Sus misericordias para con ellos y para con nosotros.

[.signed-section-closing]
De la reunión del citado pueblo en Londres, el 23 del primer mes, llamado marzo, de 1669.

--

Este año Roger Haddock murió de fiebre en su casa en Penketh, Lancashire,
a los casi cincuenta y tres años. Él había estado en Holanda el año anterior,
durante el cual yo tuve la oportunidad de hablar con él en privado más de una vez,
y así descubrí en él muchas cualidades Cristianas que eran realmente excelentes;
por tanto, la noticia de su fallecimiento me afectó mucho.
Y debido a que su ministerio, en el que era notable,
estaba más que ordinariamente lleno de materia valiosa en su predicación,
su muerte fue muy lamentada entre las iglesias en
Inglaterra donde había trabajado más en el evangelio.
Su esposa Eleanor, en su testimonio con respecto a él dijo lo siguiente:

[.embedded-content-document.testimony]
--

Mi espíritu ha estado y está doblegado,
bajo un profundo sentido de mi gran pérdida y prueba por la partida de mi querido esposo,
a quien Dios en Su sabiduría le ha placido quitarme;
él era un consuelo para mi vida y un gozo para mis días en este mundo,
habiéndomelo dado Dios con gran misericordia y amorosa bondad;
y con gratitud de corazón lo disfruté, hasta el fin del tiempo que Dios había señalado.
Y ahora ha sido quitado del mundo, junto con todas sus aflicciones y ejercicios,
así como de todas sus labores y fatigas, que eran grandes entre las iglesias de Cristo,
las cuales, junto conmigo, tienen una pérdida no pequeña por su muerte.
Pero, ¿qué diré? Sabio y bueno es el Señor,
quien hace lo que quiere en el cielo y en la tierra,
y entre Sus iglesias y Sus escogidos.
Él puede quebrar y vendar, herir y sanar, matar y hacer vivir de nuevo,
para que los vivos vean Sus maravillas y magnifiquen Su poder en todo,
a través de todo y sobre todo, quien es Dios eterno, bendito para siempre.
Amén.

--

Luego en su testimonio da cuenta de la vida de él, y de cómo en su juventud,
él había sido para ella un fiel instructor en la piedad,
y finalmente se había convertido en su esposo.
Después de una descripción de la vida de él,
y de sus muchos viajes en el ministerio del evangelio para edificar y animar las iglesias,
dice también, que aunque su amor por ella estaba por encima de las cosas visibles,
como el mejor de los placeres que él tenía en este mundo, aun así,
ella no era demasiado querida para él como para renunciar a servir a la verdad de Dios.
Por tanto, dice,

[.embedded-content-document.testimony]
--

Yo fui hecha una bendición para él, cada día más agradable que el anterior.
Él a menudo lo expresaba; y él verdaderamente fue así para mí cada día,
de todas las formas y en todos los sentidos.
Ninguna lengua ni pluma puede expresar la plenitud
del consuelo y del gozo que teníamos en Dios,
y el uno en el otro.
Sin embargo, encontramos que a Dios le complace con respecto a los que Él ha amado,
probarlos en sus más íntimos y queridos deleites,
para que sea manifestado cuán amado fue Él por encima de todo,
y que ningún don debe ser preferido por encima del Dador,
sino que Él debe ser todo en todos, quien es y ha de venir, Dios bendito por los siglos.
Verdaderamente teníamos gran cuidado y vigilancia uno sobre el otro,
y sobre nuestros propios espíritus, para ver que nuestro amor, aunque grande,
estuviera limitado y mantenido dentro de su propio ámbito, siendo la verdad su origen,
su Alfa y Omega.
Y aunque le ha placido a Dios probarme, al quitarme tan grande bendición para mí,
de seguro que es, para que yo esté más cerca de Él,
para que tenga Su amor siempre en mi memoria, que Él es quien da y quita,
y para que yo bendiga Su nombre en todas las cosas.
Mi alma se esfuerza por seguir siempre Sus pisadas de negación al yo en todas las cosas,
para poder terminar mi carrera en este mundo para la gloria de Dios, como lo hizo Él,
y tener mi parte en esa mansión de gloria eterna con Él en los cielos.
Y aunque mi porción sea estar por un tiempo en este mundo de aflicciones,
aun así tengo esperanza en la inmortalidad y en la bienaventuranza eterna,
cuando mi tiempo en este mundo se acabe.

--

Así escribió; pero para evitar la redundancia, aquí me interrumpo.
Luego, dando ella cuenta de la vida y ministerio de su esposo, menciona,
que por estar lejos de casa no había estado presente en su muerte;
pero que se habían despedido uno del otro antes,
y se habían separado con gran amor y con mutuos suspiros
anhelantes ante Dios por el bienestar del otro.
Y concluye con estas palabras: "`Aunque no vi su partida, he visto en qué se fue,
y que estaba lleno de celo y fervor en el amor de Dios y en la vida de justicia.
Por tanto, en pura sumisión a la voluntad de Dios,
concluyo este breve y verdadero relato de mi digno y querido esposo,
cuyo nombre y recuerdo son benditos,
y vivirán y serán de grato olor en los corazones de los justos a través de las edades.`"
Con este testimonio, transmitió Eleanor el recuerdo de su amado compañero a la posteridad.

Al no encontrar más acontecimientos notables en este año, paso a 1697,
en el que se firmó un tratado de paz entre Inglaterra, Francia y Holanda.
Y aunque muchos pensaron que sería duradero,
entre el clero de los papistas había quienes tenían otra opinión al respecto;
de lo cual este dístico^
footnote:[Composición poética o estrofa de dos versos que expresan un concepto completo.]
falso fue una evidencia, que al ser enviado desde Flandes por un clérigo de Gante,
a Holanda, cayó primero en mis manos:

[verse]
____
Prospicimus modo quod durabunt Fcedera longo
Tempore, nee nobis pax cito diffugiet.
____

Que puede traducirse al español así:
"`Prevemos ahora que la confederación durará mucho tiempo,
y que la paz no se nos escapará rápidamente.`"
Sin embargo, si uno lee este dístico al revés queda así:

[verse]
____
Diffugiet cito pax nobis, nee tempore longo
Fcedera durabunt, quod modo prospicimus.
____

Y tiene un sentido totalmente contrario, a saber: "`La paz pronto volará de nosotros,
y el pacto no durará mucho; lo cual ya prevemos.`"

Al ser firmada esta paz,
los habitantes de Inglaterra compitieron entre sí para felicitar a su rey por ello,
quien entonces era reconocido como rey de Gran Bretaña por el rey francés Luis XIV.
Y puesto que los magistrados de las ciudades,
los directores y miembros de las universidades,
y personas de todas las sociedades y persuasiones se dirigieron al rey,
los Cuáqueros también redactaron una carta que le presentaron al rey,
y que era como sigue:

[.embedded-content-document.address]
--

[.letter-heading]
Al rey William III sobre Inglaterra, etc.

[.blurb]
=== El reconocimiento agradecido del pueblo comúnmente llamado Cuáqueros, humildemente presenta:

[.salutation]
Sea de complacencia al rey,

Que viendo que el altísimo Dios,
que reina en los reinos de los hombres y nombra sobre ellos a quien Él quiere,
por Su dominante poder y providencia te ha colocado
en dominio y dignidad sobre estos reinos;
y que por Su divino favor te ha preservado y liberado
notablemente de muchos grandes y notables peligros,
y bondadosamente ha vuelto la calamidad de la guerra
en la deseada misericordia de la paz,
de corazón deseamos que nosotros y todos los demás interesados seamos verdaderamente
sensibles y humildemente agradecidos a Dios Todopoderoso por ello,
para que la paz sea una bendición duradera y perpetua.

Y ahora, oh rey, que el Dios de paz te ha traído de regreso a salvo,
es motivo de gozo para los que Le temen,
oír tu buena y razonable decisión de efectivamente desalentar la obscenidad e inmoralidad,
sabiendo que la justicia es lo que enaltece a una nación. Y así como el rey se
ha inclinado tiernamente a dar alivio y libertad de consciencia a sus súbditos
de diferentes persuasiones (de cuyos favores hemos participado en gran medida),
así estimamos nuestro deber conmemorar y reconocer con gratitud lo mismo;
rogándole fervientemente al Todopoderoso Dios que ayude al rey
a llevar adelante todas sus justas y buenas inclinaciones,
para que sus días aquí sean felices y pacíficos,
y en la otra vida participe de una corona duradera que nunca se desvanecerá.

[.signed-section-closing]
Londres, 7 del mes once llamado enero de 1697.

--

Esta carta que fue firmada y presentada al rey por George Whitehead, Thomas Lower,
Daniel Quare, John Vaughton, John Edge y Gilbert Latey,
fue favorablemente recibida y aceptada por el príncipe;
quien dio pruebas fehacientes de que no le guardaba mala
voluntad a nadie por diferencias de opinión en religión,
si eran personas honestas;
de lo cual puede servir de evidencia que tanto su
relojero como la nodriza del joven duque de Gloucester,
eran de la persuasión de los Cuáqueros.

Creo que fue a principios del año 1698,
que se presentó en el Parlamento un proyecto de ley para restringir la libertad de prensa,
y como los llamados Cuáqueros percibieron que esto podría ser perjudicial,
redactaron las siguientes observaciones y las entregaron a los miembros del Parlamento:

[.embedded-content-document.address]
--

[.blurb]
=== Algunas observaciones humildemente ofrecidas por el pueblo llamado Cuáqueros, en relación con el proyecto de ley para restringir la libertad de prensa.

Impedir la impresión y publicación de libros sediciosos o de traición contra el gobierno,
o panfletos escandalosos que se inclinan al vicio y a la inmoralidad,
es la sabiduría de todos los buenos gobernantes,
y debe ser el deseo de todos los hombres buenos.

Pero creemos,
que limitar los libros religiosos a una licencia
(donde las persuasiones toleradas son muchas),
es completamente inseguro para todas las persuasiones, excepto para la del licenciante,^
footnote:[El que concede permiso o autorización a otros.]
quien por este proyecto de ley tiene poder de permitir lo que él juzgue sano y ortodoxo,
o de rechazar lo que considere hereje, sedicioso u ofensivo.

La historia y la experiencia han enseñado cómo el oscuro término "`herejía`" ha sido
utilizado y extendido contra los Cristianos mártires primitivos y famosos reformadores.
Tampoco debe olvidarse la razón por la que el escrito __De Haeretico Comburendo__^
footnote:[_De Haeretico Comburendo_ (Año 2 de Enrique IV,
c.15) fue una ley aprobada por el Parlamento bajo
el reinado de Enrique IV de Inglaterra en 1401,
que castigaba a los herejes con la hoguera.
Esta ley fue uno de los estatutos de censura religiosa
más estrictos jamás promulgados en Inglaterra.]
fue abolido.

De hecho,
no es extraño que hombres doctos de la misma iglesia discrepen en sus
opiniones con respecto a varios textos de las Sagradas Escrituras;
y cuando estas opiniones se presenten ante el licenciante,
es incierto si el mundo recibirá impresas las mejores opiniones o no.

Las diferentes comprensiones que los hombres tienen de varias partes de las Escrituras,
dan origen a diferentes persuasiones, las cuales, sin embargo,
hacen de las Escrituras la prueba de sus doctrinas;
y puesto que estas diferencias de opinión son toleradas por el gobierno,
creemos que se debe dejar a todos la libertad de defender sus doctrinas de las tergiversaciones,
prejuicios o errores de otros,
sin ser sujetas a la censura de un licenciante que es de una persuasión religiosa diferente.

Por lo tanto,
humildemente esperamos que no se promulgue una ley que reduzca la tolerancia,
la cual nosotros agradecidamente disfrutamos bajo el favor de este gobierno,
así como del anterior.

--

Estas observaciones, junto con otras que se ofrecieron,
tuvieron tal efecto que el proyecto de ley fue retirado.

Por este tiempo los escritos de Antoinette Bourignon no sólo fueron traducidos al inglés,
sino también publicados en Londres.
Esto disgustó a muchos clérigos,
y se contrató a un autor para que escribiera contra ellos,
quien además escribió ampliamente contra los Cuáqueros.
Tituló su libro [.book-title]#La Serpiente en la Hierba,# pero ocultó su propio nombre;
aunque después se descubrió que se trataba de un párroco depuesto,
que se había negado a prestar el juramento de lealtad al rey William.
Este hombre, con el fin de hacer odiosos a los Cuáqueros,
tomó y recopiló muchas cosas de sus escritos, pero mutiló tanto las expresiones de ellos,
omitiendo varias palabras importantes y saltándose otras partes,
que dieron un significado muy distinto al pretendido por los autores.
A esto añadió relatos de varias cosas que habían sucedido (según dijo) entre los Cuáqueros.
Algunos de ellas eran ficticias y meras falsedades,
pero también sacó a relucir cosas que nunca habían sido aprobadas por los Cuáqueros,
como el caso de James Nayler (descrito antes en su debido lugar);
a pesar de que James Nayler dio públicamente notables muestras de verdadero arrepentimiento.

Entre las falsedades del autor,
estaba la afirmación de que los Cuáqueros no permitían que
en sus escuelas los niños leyeran las Sagradas Escrituras.
La falsedad de esto se puso de manifiesto de manera muy evidente,
mediante el certificado de un asistente francés en una de sus escuelas en Wandsworth,
cerca de Londres, quien no era Cuáquero;
así como también por el testimonio de algunos vecinos que era personas notables,
y que declararon que la Biblia era leída diariamente
por los estudiantes en la citada escuela,
comenzando con Génesis y continuando hasta el final de Apocalipsis; y luego,
de Génesis de nuevo.
También se expusieron claramente las citas falsas de este autor, demostrando,
que si alguien fuera tan malicioso,
por medio de su método podría insinuar a partir del Salmo 14:1,
que las Sagradas Escrituras declaran que "`no hay Dios;`" simplemente
porque esas palabras se encuentran efectivamente en ellas.

George Whitehead y Joseph Wyeth respondieron ampliamente a este libro venenoso;
una obra que requirió más esfuerzo y trabajo que talento,
para revisar las múltiples citas de muchos autores,
y para demostrar la injusticia y falta de sinceridad de [.book-title]#La Serpiente en la Hierba.#
Ahora bien, dado que muchos estaban muy dispuestos a creer las falsedades de este libro,
junto con las propagadas en los panfletos del apóstata Francis
Bugg (quien se había pasado a la iglesia de Inglaterra),
este año se publicó de nuevo un libro de John Crook (quien todavía estaba vivo,
aunque tenía más de ochenta años),
que había sido publicado por primera vez treinta y cinco años antes, en el año 1663.
El título de este libro era [.book-title]#Principios de la Verdad Acerca de Cristo Hombre,
Su Sufrimiento, Muerte, Resurrección, Fe en Su Sangre, la Imputación de Su Justicia, etc.#
De esto se desprendía que los sentimientos de los Cuáqueros con
respecto a estos puntos no sólo eran ortodoxos en ese momento,
sino que habían sido así desde sus primeros días.

Al hacer mención de nuevo de John Crook,
de quien he hablado varias veces en esta historia,
procedo ahora a mencionar algo sobre su deceso,
puesto que él partió de esta vida en el año 1699.
Dejó por escrito la siguiente exhortación o advertencia a sus hijos y nietos,
escrita apenas dos meses antes de su muerte:

[.embedded-content-document.letter]
--

[.salutation]
Queridos hijos,

Debo dejarlos en una época perversa,
pero los encomiendo a la medida de gracia de Dios en el interior de ustedes,
la cual han recibido por Jesucristo;
y en la medida que la amen y atiendan sus enseñanzas,
la encontrarán ser un consejero que los instruirá en el camino eterno,
y los guardará de los caminos de los impíos.

He visto mucho en mis días,
y he observado que el temor del Señor Dios siempre ha resultado ser la mejor porción,
y que los que caminaban en él eran las únicas personas felices,
tanto en esta vida (mientras se mantuvieron fieles) como cuando llegaban a la muerte,
aunque encontraran muchas dificultades en su paso.
Por experiencia puedo afirmar,
que los caminos de santidad le ofrecen más consuelo y paz verdaderos al alma recta,
que los más grandes placeres de este mundo; los primeros alcanzan el corazón y el alma,
mientras que los deleites de este mundo no son más que un espectáculo y una apariencia,
que se desvanecen como un sueño; y cualquiera que crea lo contrario de ellos,
ciertamente encontrará que no son más que vanidades mentirosas.
Por eso el apóstol con valentía les hizo la pregunta a los convertidos romanos:
"`¿Pero qué fruto teníais de aquellas cosas de las cuales ahora os avergonzáis?
Porque el fin de ellas es muerte`" (Romanos 6:21).

Por tanto, queridos hijos, enamórense de la santidad,
sean compañeros de ella y de los que caminan en ella.
Pueden encontrar brotes de ella saliendo de la semilla santa en sus corazones;
y en la medida que se ocupen del hombre interior,
la luz les manifestará sus impulsos en pos de Dios,
los cuales yo sentí desde mis años tiernos,
aunque no los entendí tan claramente hasta que escuché la verdad declarada.

Les aconsejo que mantengan una consciencia pura,
tanto para con Dios como para con el hombre;
porque si sus consciencias están contaminadas,
la hipocresía y formalidad los privará de todo sentimiento
placentero de la presencia de Dios;
y entonces, la muerte y la sequedad serán la miserable porción de ustedes.

Tengan cuidado de cómo emplean su precioso tiempo,
porque de toda palabra ociosa hay que dar cuenta, aunque pocos lo consideren;
pero se dice que las bromas necias y la vana conversación contristan al Espíritu de Dios;
lean Efesios 4:29-30. Aprovechen su tiempo en oración y ejercicios religiosos,
etc. y sean diligentes en sus ocupaciones lícitas;
porque "`el deseo del perezoso le mata.`"
(Proverbios 21:25)

Tengan cuidado con las compañías que frecuentan,
porque un hombre es comúnmente conocido por las compañías que tiene,
tanto como por cualquier otra cosa externa.
Sean vigilantes de sus comportamientos en compañía,
porque he hallado que un comportamiento sabio y sobrio añade
mucho a la reputación y crédito de un hombre en el mundo.

Préstenle atención a la luz y a sus descubrimientos del bien y del mal,
para que no ignoren las artimañas de Satanás;
porque en vano se tenderá la red ante los ojos del ave,
porque la vigilancia los hará amar el estado retirado.
Cuánto más verdadera y perfectamente se conozca y se entienda un hombre,
mejor discernimiento tendrá de otros hombres; como al principio,
cuando estaba más en uso el profundo silencio de toda carne,
el espíritu de discernimiento era más común y rápido, que desde que se ha descuidado.
Por lo tanto, asegúrense de pasar algún tiempo, en los momentos convenientes,
esperando en Dios en silencio, aunque sea desagradable para la carne;
porque yo he tenido más consuelo y confirmación en
la verdad en mi retiro interno en silencio,
que de todas las palabras que he escuchado de otros,
aunque muchas veces he sido refrescado por éstas también.

Amen las Sagradas Escrituras, prefiéranlas a todos los demás libros,
y tengan cuidado de leerlas con un temor santo sobre sus espíritus,
no sea que sus imaginaciones pongan interpretaciones sobre ellas para perjuicio de ustedes.
Sino ejerciten la fe en la promesa de Cristo, quien ha dicho:
"`Mi Espíritu tomará de lo mío, y os lo hará saber.`"

Manténganse fieles a las reuniones religiosas entre los amigos;
pero vigilen sus afectos para que no hagan acepción de personas,
sino reciban el poder y la vida de la verdad de quienquiera que venga.
Y no tomen en cuenta el cosquilleo de sus afectos,
sino la demostración de la verdad a sus entendimientos y consciencias,
porque ésta permanecerá cuando las palabras hayan terminado,
y todos los destellos de los afectos se hayan desvanecido y terminado en nada.

Ámense verdaderamente unos a otros,
manifestando su amor con buenos consejos y ayudándose mutuamente en todas las ocasiones;
sean buenos ejemplos para todos aquellos con los que conversan,
especialmente con sus hijos y con los de sus propias familias.
No toleren el orgullo ni la vanidad, sino repréndanlos;
recordando que mientras sus familias estén bajo su gobierno,
deberán dar cuenta a Dios del cumplimiento de su deber para con ellas.

Finalmente, tengan siempre presente el fin de ustedes,
y vivan como si estuvieran muriendo,
sin saber cuán pronto se terminarán sus días en este mundo.
Y mientras vivan aquí, no desprecien los castigos del Señor, cualesquiera que sean.
Yo he sido afligido desde mi juventud, tanto interna como externamente,
pero el Dios a quien he servido proveyó para mí,
cuando todos mis parientes externos me abandonaron,
y ninguno de ellos me dio algo con lo cual comenzar en este mundo.
Digo esto para que sepan que les dejaré más externamente,
incluso al más pequeño de ustedes, de lo que me dejaron todos mis parientes.
No necesito mencionar esta aguda aflicción que me aqueja en mi vejez,
la cual está más allá de toda expresión, porque ustedes la conocen en alguna medida;
pero yo no podría haberme ido sin ella, como me lo ha mostrado el Señor,
porque he visto Sus maravillas en las profundidades.
Por lo tanto, repito, no desprecien las aflicciones,
sino abrácenlas como mensajeros de paz para sus almas,
aunque sean desagradables para la carne.

Les encomiendo estas cosas por verdadero amor a sus almas,
sabiendo lo poco que la mente vana del hombre considera
un consejo como éste que dejo tras de mí. Sin embargo,
por medio de este consejo muestro mi verdadero amor por todos ustedes,
deseando que Dios ponga Su bendición sobre él, a quien los encomiendo a todos,
mis queridos hijos, y así termino mis días,

[.signed-section-closing]
Vuestro amoroso padre y abuelo,

[.signed-section-signature]
John Crook.

[.signed-section-context-close]
Hertford, el primero del primer mes de 1699.

--

La aguda aflicción de la que él habla en este escrito era más que una sola enfermedad;
porque las piedras en los riñones, la gota y los cólicos lo atacaban a veces duramente,
y aunque esto había durado mucho tiempo, aun así siempre se comportó pacientemente.
No obstante, su dolor era a veces tan violento,
que a menudo se le oía decir que si no fuera porque
sentía y experimentaba el poder interior del Señor,
no habría podido subsistir bajo tan grandes dolores.
El de las piedras en los riñones era el mayor, el cual continuó con él hasta su fin;
y sin embargo, nunca se le oyó pronunciar ninguna palabra desagradable,
o exclamar impacientemente, sino que cuando el extremo de sus ataques pasaba,
entonces expresaba su gozo y paz interior, y así alababa al Señor.

Él tenía un excelente don para explicar los misterios de las Sagradas Escrituras,
de modo que era semejante a Apolos, de quien encontramos registrado,
que era "`varón elocuente, poderoso en las Escrituras.`"
Y por su predicación celosa y eficaz, cuando estaba en el vigor de su vida,
muchos fueron convencidos de la verdad.
En sus últimos días dijo en algunas ocasiones,
que el horno de aflicción era de buena utilidad para
purgar la escoria y la parte terrenal en nosotros.
Y bajo la pena y dolor que tenía por algunos de sus hijos,
a veces se consolaba a sí mismo con estas palabras de David:
"`No es así mi casa para con Dios; sin embargo, él ha hecho conmigo pacto perpetuo,
ordenado en todas las cosas, y será guardado.`"

En su vejez muchas veces se le oyó decir:
"`Muchos de los ancianos se han ido a su larga morada,
y nosotros también nos apresuramos tras ellos.
Ellos se alejaron antes que yo, y yo, que deseo irme, no puedo.
Bien, pronto será mi turno también.`" Parecía regocijarse
al considerar que el tiempo de su disolución,
cuando estaba libre de sus fuertes dolencias, se aproximaba rápidamente.
Sin embargo,
en la última parte de su vida a menudo parecía tan fuerte en la guerra espiritual,
que algunos pensaron que habría podido decir con Caleb:
"`Todavía estoy tan fuerte como el día que Moisés me envió; cual era mi fuerza entonces,
tal es ahora mi fuerza para la guerra, y para salir y para entrar.`"
Unas tres semanas antes de su muerte, aunque estaba débil de cuerpo,
dijo poderosamente y de manera profética: "`La verdad debe prosperar,
la verdad prosperará, pero un tiempo de prueba debe venir primero,
y después la gloria del Señor aparecerá cada vez más.`" Continuó en un estado
de ánimo tranquilo y verdaderamente Cristiano hasta el último momento de su vida,
y partió el 26 del mes llamado abril, a los ochenta y dos años, en su casa en Hertford,
donde había vivido por muchos años. Yo lo conocí en Inglaterra,
y también estuvo en Holanda, así que no hablo de alguien que fuera desconocido para mí.

Por denigrar la doctrina de los Cuáqueros,
George Keith gozaba tanto del favor del clero Episcopal,
que empezó a servirles como vicario,
después de ser ordenado por el obispo de Londres alrededor del año 1700.
Y puesto que esto parecía extraño y sorprendente para muchos,
alguien (de qué persuasión religiosa no lo sé) hizo una recopilación
de sus sentimientos críticos contra la iglesia nacional y su clero,
y lo que él contaba de sus ritos y ceremonias en libros
y documentos que había publicado muchos años antes;
a lo cual el autor le dio el título:
[.book-title]#Mr. George Keith`'s Account of the National Church and Clergy,
Humbly Presented to the Bishop of London.#^
footnote:["`Relato del Sr. George Keith sobre la Iglesia Nacional y el Clero,
Humildemente Presentado al Obispo de Londres`"]
A esto fueron añadidas algunas preguntas que G. Keith había escrito en una ocasión,
sobre lo que es llamado el sacramento de la cena del Señor. Este relato
fue entonces publicado en la imprenta y presentado al obispo de Londres,
finalizando con estas palabras del apóstol: "`Porque si las cosas que destruí,
las mismas vuelvo a edificar, transgresor me hago.`"

El año siguiente, 1701, murió en Francia el rey James.
Mencioné antes cómo este infeliz príncipe, después de haber ascendido al trono,
cayó súbitamente por su conducta apresurada y por
su ardiente deseo de introducir el papismo en Inglaterra,
y cómo todos sus esfuerzos por recuperar su reino perdido resultaron ineficaces.
En septiembre, estando en misa, fue atacado de repente por una enfermedad,
la cual se agravó tanto, que al cabo de uno o dos días vomitó sangre,
y todos los remedios que se usaron fueron inútiles.
Si lo que se escribió por ese tiempo en París es verdad,
él declaró que perdonaba a todos los hombres que le habían hecho mal,
y el 16 del citado mes murió en St. Germain, Francia, donde tenía su corte.

Por este tiempo, el rey William regresó de Holanda,
donde había estado debido a nuevos problemas provenientes de Francia.
Y dado que la sucesión de la corona de Inglaterra fue establecida en la línea Protestante,
el rey fue felicitado por ello con muchas cartas de sus súbditos.
Y al oír que un horrible complot contra su vida había sido descubierto,
los llamados Cuáqueros también pensaron que era su deber dirigirse a él,
con un reconocimiento agradecido por sus favores.
Así lo hicieron, con una carta presentada al rey en diciembre, por George Whitehead,
William Mead y Francis Camfield.

[.embedded-content-document.letter]
--

[.letter-heading]
Al rey William III sobre Inglaterra, etc.

[.blurb]
=== Carta humildemente presentada por el pueblo comúnmente llamado Cuáqueros:

[.salutation]
Sea de complacencia al rey,

Que nosotros, tus fieles súbditos,
sinceramente expresamos nuestra alegría por tu regreso seguro a tu pueblo;
al tener grandes motivos para amarte, honrarte y orar por ti,
como un príncipe a quien creemos que Dios ha promovido
y establecido para los buenos fines del gobierno,
bajo cuyo reino nosotros disfrutamos misericordias y favores;
particularmente el de libertad a las consciencias tiernas en la adoración religiosa,
como un medio apropiado para unificar a tus súbditos Protestantes en interés y afecto.

Por esta gran misericordia no podemos sino humildemente estar agradecidos a Dios,
y renovar nuestro agradecido reconocimiento al rey,
a quien Dios por Su omnipotente poder ha preservado
notablemente y ha hecho ejemplar en prudencia,
así como también en bondad hacia otros reyes y príncipes,
por lo que tu recuerdo será celebrado en la posteridad.

También estamos constreñidos a bendecir al Señor,
porque Él ha frustrado manifiestamente los maliciosos y
traicioneros planes de tus adversarios y de la nación,
tanto contra el establecimiento legítimo de tu trono,
como contra el verdadero interés de tus súbditos Protestantes.

Y le rogamos al Todopoderoso Dios que bendiga los buenos
planes y justos emprendimientos del rey y su gran consejo,
para el bien de su pueblo y para obtener una paz firme y duradera con Europa.
Que Él te siga haciendo, oh rey, una bendición para estas naciones,
estableciendo tu trono en misericordia y verdad,
dándote un reinado largo y próspero sobre nosotros,
y en la otra vida una gloriosa inmortalidad.
Esta es, y será, la ferviente oración de nosotros, tus sinceros y fieles súbditos.

Firmada en nombre y por designación del citado pueblo, en una reunión en Londres,
el octavo mes de 1701.

--

Después de que esta carta le fue leída al rey, fue favorablemente recibida,
y él les agradeció a los que la habían presentado y les respondió: "`Yo los he protegido,
y los protegeré.`" Luego la llevó con él a su recámara
y la leyó de nuevo (como se entendió después),
y la elogió. Sin embargo, al mantener el documento con él algunos días,
sin hacerlo público en la Gaceta, algunos periodistas franceses en Londres,
falsificaron una carta muy ridícula en nombre de
los Cuáqueros y la enviaron al otro lado del mar.
Los periodistas franceses en Holanda estaban muy
dispuestos a publicar semejante disparate ficticio,
aunque las expresiones usadas eran tan excesivamente bruscas y mal educadas,
que no habrían podido ser dirigidas a un rey,
excepto por aquellos que fueran bastante insolentes
como para burlarse públicamente de la corona,
algo de lo que los Cuáqueros nunca había sido culpables.
Pero después de unos pocos días, el rey hizo pública la verdadera carta,
y entonces todos pudieron ver cuán vergonzosamente
habían expuesto su malicia los periodistas franceses.

Finalizado este año, llegó 1702,
el año que trajo también el fin de la vida del rey William.

A la muerte del rey de España, el rey francés no sólo había colocado a su nieto,
el duque de Anjou, en el trono de ese reino,
sino que también había reconocido al pretendido príncipe de Gales^
footnote:[James Francis Edward Stuart, apodado el Viejo Pretendiente,
era el hijo católico del rey James II.]
como rey de Inglaterra, buscando alcanzar de esta manera la corona del rey William.
Entonces,
William aprovechó la ocasión para hacer alianzas
para su seguridad con otros príncipes y potentados.
De esto dio aviso al Parlamento que sesionaba en ese entonces,
el cual le prometió ayudarlo en la medida de sus posibilidades
y mantener la sucesión de la corona en la línea Protestante.
Se redactó también una declaración de "`rechazo solemne`" en la
que se decía que el anteriormente citado príncipe pretendiente,
que entonces permitía que se le llamara James III, rey de Inglaterra,
etc. no tenía derecho a la corona de dicho reino,
ni de ninguno de los dominios que pertenecían a éste.
Ahora, aunque todo esto tenía el objetivo de mantener y ayudar al legítimo rey William,
él no vivió para ver el efecto de esto,
porque su tiempo estaba próximo a expirar y su reloj de arena casi se había agotado,
como pronto se manifestó.

Por este tiempo, en el mes llamado marzo,
el rey William salió de cacería en un caballo que nunca antes había montado,
el caballo se cayó y al mismo tiempo el rey se quebró la clavícula.
La fractura se fijó pronto y parecía que todo iba bien,
pero como el rey había soportado muchas fatigas y dificultades,
había estado físicamente débil durante algún tiempo,
de modo que esta dolorosa caída pareció provocarle una enfermedad
que se agravó rápido y le puso fin a su vida.
Pero antes de su partida, hizo una buena obra más para los Cuáqueros.
Sabiendo que estaba a punto de expirar el plazo de siete años que les habían
concedido para que la declaración de ellos fuera aceptada en lugar de un juramento,
le solicitaron al rey y al Parlamento que dicha ley
continuara y fuera confirmada por una nueva,
lo cual obtuvieron;
porque el rey siempre se mostró dispuesto a favorecerlos como sus súbditos pacíficos;
y muchos miembros notables del Parlamento estaban entonces bien dispuestos hacia ellos.
Acto seguido la ley fue renovada,
conteniendo una prórroga de dicha concesión por un espacio de once años, la cual,
después de una madura consideración fue finalmente aprobada,
dado que el rey había nombrado varios comisionados,
quienes el tres de marzo le dieron el consentimiento real en la Cámara de los Lores,
porque por razones de su enfermedad, William no podía presentarse en el trono.

También mandó un mensaje al Parlamento,
recomendando unir los dos reinos de Inglaterra y Escocia en uno,
habiendo sido ya nombrados comisionados en Escocia para
que se reunieran con los ingleses para este asunto.
Pero el tiempo mostró que él no llevaría a término esta obra,
dado que la realización de ella estaba reservada para su sucesor.
Y aunque parecían haber ciertas esperanzas de que se recuperaría,
pues había estado caminando un poco en su jardín para tomar el aire,
después se sentó y se resfrió, lo cual fue seguido de fiebre,
y su enfermedad se agravó tanto, que el siguiente Primer-día,
el ocho del mes llamado marzo, murió en Kensington,
para gran aflicción de todos sus fieles súbditos.
En efecto, tal fue la pena por la muerte de este excelente príncipe,
que cuando llegaron las noticias de ella a Holanda,
causaron un abatimiento general y arrancaron lágrimas de muchos ojos; pues tal vez,
ningún rey haya sido más querido que él en estos últimos tiempos.
El día antes de su fallecimiento,
había dado el consentimiento real al proyecto de ley del
"`rechazo solemne`" al príncipe pretendiente de Gales,
y la noche siguiente, sintiendo que se aproximaba la muerte,
mandó a llamar a la princesa Anne, hermana de su fallecida esposa, la reina Mary.
Y después de pedirle que se quedara un tiempo con él, la abrazó tiernamente,
y se despidió de ella deseándole lo mejor.
Entonces mandó a buscar al arzobispo de Canterbury,
y su entendimiento continuó bien hasta el final,
con evidentes señales de piedad y entrega a la voluntad de su Creador,
y casi a las ocho de la mañana, entregó su espíritu a Aquel de quien lo había recibido,
habiendo llegado a sus cincuenta y dos años, y reinado como rey más de trece.

En la tarde la princesa Ana fue proclamada reina de Inglaterra, Escocia,
Francia e Irlanda, etc.,
y el Parlamento le prometió ayudarla a mantener las alianzas que ya estaban establecidas,
o debían establecerse, con potencias extranjeras.
Esto lo aceptó la reina con mucha satisfacción,
y confirmó a los ministros y altos funcionarios en sus respectivos cargos.
También escribió a los Estados Generales de los Países Bajos,
que mantendría la alianza hecha con dichos Estados por el difunto rey, su cuñado.

El cuerpo del rey, que estaba delgado y muy demacrado, fue abierto después de su muerte,
y muchas de sus partes internas parecían sanas, especialmente el cerebro; sin embargo,
en general, se encontró poca sangre en el cuerpo, pero en los pulmones,
que estaban muy adheridos a la pleura, había más que en todas las demás partes.
Su corazón estaba firme y fuerte,
pero se pensó que una inflamación en el lado izquierdo de sus pulmones,
habría sido la causa directa de la muerte del rey,
porque él había sido asmático por mucho tiempo.

Era de mediana estatura; su cara delgada y alargada; sus ojos eran muy buenos,
rápidos y penetrantes; sus manos muy finas y blancas.
No hablaba mucho, pero era de pensamientos sólidos; de memoria fuerte y mente serena,
rápido de comprensión y no dado a la opulencia, sino de un comportamiento sobrio.
A menudo daba evidencia de una devota atención al oír el nombre de Dios;
y aún en medio de los peligros ponía mucha confianza en la divina Providencia.
Así de valiente e intrépido era, pero sin temeridad;
porque donde juzgaba que su presencia era necesaria,
iba sin temor allí. Era un gran amante de la caza,
siendo ésta su más placentera diversión,
lo que lo hizo más apto para soportar las fatigas de la guerra.
Era accesible y escuchaba favorablemente a todo el mundo,
y a los que hablaban con él los trataba con moderación. Tal era su devoción,
que a menudo se retiraba en privado,
cuando algunos pensaban que estaba ocupado en otros asuntos.
Muchos habían concebido esperanzas de que este gran príncipe,
en aquella coyuntura crítica, viviría todavía algo más, pero su obra estaba hecha;
y Dios ha mostrado muy notablemente desde entonces
que Él no está limitado a ningún instrumento,
y la reina que sucedió en el trono, después dio pruebas de eso al mundo.
Su cuerpo fue enterrado el 12 del mes llamado abril, hacia medianoche,
en la capilla del rey Enrique VII, en la abadía de Westminster.

Fue por el favor de este rey, holandés de nacimiento,
que los Cuáqueros (así llamados) fueron aceptados como un pueblo libre;
de modo que ahora ellos ven cumplida la verdad de lo que algunos
de sus amigos fallecidos habían predicho proféticamente,
a saber: Que no estaba en poder de sus enemigos desarraigarlos, sino que Dios,
a Su debido tiempo, obraría su liberación.

Así hemos visto desde qué débiles principios se tuvo que levantar este pueblo,
y cómo se incrementó y llegó a ser un gran pueblo contra toda oposición,
de lo que al principio parecía haber muy pocas probabilidades,
como se ha visto al inicio de esta historia.
Y remontándonos un poco antes de esta fecha,
podemos ver lo mismo en un testimonio de George Fox que se publicó después de su muerte,
en la colección de sus epístolas:

[.embedded-content-document.epistle]
--

Cuando el Señor me envió por primera vez en el año 1643,
fui enviado como un cordero inocente y joven en años,
entre hombres en la naturaleza de lobos, perros, osos, leones y tigres,
al mundo que el diablo había hecho como un desierto.
Fui enviado a volver a las personas de las tinieblas a la luz, con la que Cristo,
el segundo Adán, las ha iluminado; para que ellas puedan ver a Cristo, su camino a Dios,
con el Espíritu de Dios que Él ha derramado sobre toda carne,
y para que con Él puedan tener entendimiento, conocer las cosas de Dios,
y conocerlo a Él y a Su Hijo Jesucristo, quien es la vida eterna;
y así puedan adorar y servir al Dios vivo, su Hacedor y Creador,
que cuida a todos y es Señor de todos;
y para que con la luz y Espíritu de Dios puedan conocer las Escrituras,
que fueron entregadas por el Espíritu de Dios en los santos;
hombres y mujeres santos de Dios.

Y cuando muchos comenzaron a ser vueltos a la luz, que es la vida en Cristo;
y cuando el Espíritu de Dios les dio entendimiento para encontrar la senda del Justo,
la luz resplandeciente, entonces los lobos, los perros, dragones, osos, leones, tigres,
bestias salvajes y aves de presa, rugieron y chillaron contra los corderos, ovejas,
palomas e hijos de Cristo, y estuvieron listos a devorarlos a ellos y a mí,
y a despedazarnos.
Pero el brazo y el poder del Señor me preservaron,
aunque muchas veces estuve en peligro de muerte,
y muy a menudo fui echado en calabozos y prisiones,
y llevado a rastras delante de magistrados.
Pero todas estas cosas ayudaron a bien.
Y cuánto más era echado en prisiones externas,
más personas salían de sus prisiones espirituales
e internas a través de la predicación del evangelio.
Pero los sacerdotes y profesantes estaban tan enfurecidos,
y agitaban a las personas rudas y profanas a tal furia,
que yo apenas podía caminar en las calles o ir por los caminos,
sin que con frecuencia estuvieran listos a hacerme daño. Pero Cristo,
que tiene todo el poder en el cielo y en la tierra,
los restringió y limitó tanto con Su poder, que mi vida fue preservada,
aunque muchas veces estuve cerca de ser asesinado.

¡Oh, las cargas y tribulaciones que sufrí en aquel tiempo!
Mi vida con frecuencia estaba oprimida bajo los espíritus
de los profesantes y maestros sin vida,
y de los profanos.
Además de esto, los problemas que tuve después con los descarriados,
apóstatas y falsos hermanos,
que eran como muchos Judas traicionando la verdad y la semilla fiel y escogida de Dios,
y haciendo que se hablara mal del camino de la verdad.
Pero el Señor los destruyó, asoló y confundió, de modo que ninguno resistió mucho tiempo,
porque el Señor los destruyó o los redujo a nada,
y Su verdad floreció y Su pueblo en ella, para alabanza de Dios,
quien es el vengador de Sus escogidos.

[.signed-section-signature]
G+++.+++ Fox

--

G+++.+++ Fox entonces,
habiendo sido el primero de los Cuáqueros que predicó y proclamó
a Cristo en Inglaterra como "`la luz que alumbra a todo hombre
que viene a este mundo,`" a pesar de toda la oposición,
ganó muchos partidarios en un corto tiempo (como hemos visto en esta historia),
por lo que varios otros comenzaron a predicar la misma doctrina.
Y muchos de estos primeros predicadores eran como "`hijos del trueno,`" pues testificaban
de la luz de Cristo que resplandecía en las consciencias de los hombres,
y proclamaban que el día del Señor había amanecido, y que aún se manifestaría más,
para destruir los antiguos edificios de las invenciones e instituciones humanas;
pero confirmar lo que había sido anteriormente sentido y disfrutado
por las verdaderas operaciones del Espíritu de Dios,
en los corazones de muchas personas.

Por su poderosa manera de predicar arrepentimiento,
muchos fueron despertados de un sueño de descuidada seguridad,
y llegaron a ver que sus coberturas eran demasiado cortas,
y que todavía no estaban cubiertos con el verdadero vestido de bodas.
Y muchos que habían llevado una vida ruda,
fueron tan tocados en sus corazones por estos celosos predicadores, que clamando,
"`¿qué debemos hacer para ser salvos?,`" fueron llevados al arrepentimiento y a la conversión;
y así, de salvajes y rudos llegaron a ser tranquilos y sobrios.
Y así como al principio muchos de estos primeros
predicadores corrían como un poderoso torrente,
y parecían aptos para trillar y moler las montañas y las piedras,
y derribar los cedros altos, y lavar toda oposición; así también hubo otros,
que como hijos de consolación,
proclamaban buenas nuevas para las almas hambrientas y sedientas, tanto así,
que algunos dijeron: "`Ahora se predica de nuevo el evangelio eterno.`"

Y fue realmente notable,
que aunque estos promulgadores de la doctrina de la luz interior brillando
en los corazones de los hombres eran despreciables e incultos,
muchas personas de renombre, no sólo los que estaban en la magistratura,
sino también muchos predicadores de diversas persuasiones,
fueron tan tocados en el corazón por su predicación viva,
que no sólo recibieron su doctrina,
sino que con el paso del tiempo llegaron a ser celosos publicadores de ella,
y así se recogió una gran cosecha.
En efecto, a veces, incluso hombres de grandes cualidades e ingenio agudo,
fueron profundamente golpeados por la predicación sencilla y poco atractiva;
de los cuales,
Isaac Penington (mencionado más de una vez en esta historia) es un ejemplo notable,
como puede verse en un relato de sí mismo, escrito de su puño y letra,
y hallado entre sus documentos después de su muerte,
en el que habla de la siguiente manera:

[.embedded-content-document.paper]
--

Yo he sido un hombre de tristeza y aflicción desde mi infancia,
uno que ha sentido necesidad del Señor y ha llorado
en busca de Él. Fui separado por Él del amor,
naturaleza y espíritu de este mundo y vuelto en espíritu hacia Él,
casi desde que puedo recordar.

En la consciencia de mi estado de perdición, busqué al Señor, leí las Escrituras,
vigilé mi propio corazón, clamé al Señor por lo que sentía que me hacía falta,
bendije Su nombre por lo que misericordiosamente había hecho por mí y depositado en mí, etc.
Me entregué, de acuerdo con mi entendimiento,
a la práctica fiel de lo que leía en las Escrituras,
y me sentí contento por encontrar oprobio,
oposición y diferentes tipos de sufrimientos que
el Señor se agradaba en permitirme experimentar.
No puedo sino decir, que el Señor fue bueno conmigo, porque me visitó, me enseñó,
me ayudó y testificó Su aceptación de mí muchas veces,
para frescura y gozo de mi corazón delante de Él.

Pero mi alma no estaba satisfecha con lo que encontraba, ni podía estarlo,
pues era más vivificada y más presionada en mi espíritu
en pos de un conocimiento más completo,
seguro y satisfactorio.
Yo añoraba el sentido, la vista y el deleite de Dios,
tal como se testifica en las Escrituras que habían
sido sentidos y disfrutados en tiempos antiguos.
Claramente vi que se había producido una interrupción en el fluir,
y que quedábamos cortos del poder,
la vida y la gloria de las que los primeros cristianos participaron.
Nosotros no teníamos el Espíritu de la misma manera, no estábamos en la fe,
ni caminábamos ni vivíamos en Dios, como ellos lo hicieron.
Ellos habían sido acercados al Monte Sion, a la Jerusalén celestial, etc.,
mientras que nosotros apenas teníamos un conocimiento
literal o una percepción de lo que eran esas cosas.
Entonces vi que el curso total de la religión entre nosotros era, en su mayor parte,
sólo palabras, en comparación con lo que ellos habían sentido, disfrutado,
poseído y vivido.

Esta consciencia me enfermó el corazón y me hizo clamar profundamente a Dios,
escudriñar cuidadosamente las Escrituras y esperar en Dios,
todo con el fin de poder recibir el sentido y el entendimiento puro de ellas,
desde la luz y en la luz, y por medio de la ayuda de Su Espíritu.
Lo que el Señor depositó en mí en ese estado,
lo recuerdo delante de Él con agradecimiento hasta este día,
porque Él era entonces mi Dios, compasivo y vigilante,
aunque todavía no me había enseñado cómo fijar mi mente en Él,
y permanecer en Él. Luego fui conducido (de verdad fui conducido,
no corrí por mí mismo) a separarme de la adoración del mundo y a reunirme con una sociedad;
porque tanto las Escrituras como el Espíritu de Dios me dieron testimonio.
Hay un recuerdo y un testimonio en mi corazón hasta este día,
de lo que experimentamos entonces, y de la guía y la ayuda que sentimos.
Sin embargo, faltaba algo y equivocamos nuestro camino.
Porque donde debimos presionar hacia adelante en Espíritu y poder,
nos corrimos demasiado hacia la letra y la forma.
Y aunque el Señor nos ayudó de muchas maneras,
en esto estaba contra nosotros y trajo oscuridad, confusión y dispersión sobre nosotros.
Yo estaba profundamente quebrantado y ensombrecido,
y a veces me quedaba quieto por largo tiempo en ese estado de tinieblas,
lamentándome y clamando secretamente al Señor de noche y de día. Otras
veces corría buscando lo que pudiera aparecer o brotar en otros,
pero nunca me topé con algo en lo que hubiera la menor respuesta para mi corazón,
salvo en un pueblo, quienes tenían un toque de la verdad,
pero nunca le dije mucho a ninguno de ellos,
ni los sentí en absoluto capaces de alcanzar mi condición.

Al fin, después de muchas aflicciones, andanzas y dolorosos ruegos,
me encontré con algunos de los escritos de este pueblo llamado Cuáqueros,
a los que les eché una mirada ligera y desdeñosa,
como si quedaran muy cortos de aquella sabiduría, luz,
vida y poder que yo anhelaba y buscaba.
En algún momento después de eso, tuve la oportunidad de reunirme con algunos de ellos,
y unos pocos fueron movidos por el Señor (ahora entiendo que fue así) a venir a verme.
Recuerdo claramente como ellos alcanzaron la vida de Dios en mí desde el puro principio,
la cual respondió a sus voces y provocó que brotara en mí un gran amor por ellos.
Aun así,
en mis razonamientos con ellos y en las disputas en mi mente con respecto a ellos,
yo estaba muy lejos de aceptar que ellos conocieran verdaderamente al Señor,
o que vinieran en esa vida y poder que mi condición necesitaba, y mi alma esperaba.
De hecho, cuánto más conversaba con ellos, más me parecía en mi entendimiento y razón,
que yo los superaba y los aplastaba bajo mis pies como una generación pobre, débil,
tonta y despreciable.
Sentía que tenían una pizca de la verdad en ellos y algunos deseos sinceros hacia Dios,
pero que estaban muy lejos de un entendimiento claro
y completo del camino y voluntad de Dios.
Ese era el efecto de casi todas las conversaciones con ellos.
Ellos seguían alcanzando mi corazón y yo los sentía en un lugar secreto en mi alma,
lo cual hacía que mi amor hacia ellos continuara, e incluso,
que en algunas ocasiones se incrementara.
Sin embargo, yo sentía que cada día mi entendimiento los superaba más, y en consecuencia,
cada día los menospreciaba más.

Después de mucho tiempo me invitaron a escuchar a uno de ellos,
como me habían invitado a menudo, pues ellos, con tierno amor, seguían compadeciéndome,
y sentían mi carencia de lo que ellos poseían. Hubo una respuesta en mi corazón,
y yo fui con temor y temblor y con deseos ante el Altísimo,
(quien está sobre todo y todo lo sabe),
de no recibir nada como verdad que no fuera de Él, ni resistir nada que fuera de Él,
sino de inclinarme delante de la aparición del Señor mi Dios y ante ninguna otra.
Y en efecto, cuando llegué sentí la presencia y el poder del Altísimo entre ellos,
y que palabras de verdad provenientes del Espíritu de verdad,
llegaban a mi corazón y a mi consciencia,
y ponían al descubierto mi estado ante la presencia del Señor. Sí,
y no sólo sentí palabras y demostraciones desde afuera,
sino también que lo que estaba muerto cobraba vida y que la semilla se levantaba,
al punto de que mi corazón,
en la certeza de la luz y en la claridad de su verdadero sentido dijo: "`¡Este es Él,
no hay otro! ¡Este es a quien he esperado y buscado desde
mi infancia! ¡Aquel que ha estado cerca de mí siempre,
y que a menudo ha engendrado vida en mi corazón! ¡A quien no conocía claramente,
ni cómo recibirlo o morar con Él.`" Y entonces, en esta consciencia,
en el ardor y quebrantamiento de mi espíritu, me rendí al Señor para ser Suyo,
tanto en la espera de una mayor revelación de Su semilla en mí,
como para servirle en la vida y poder de Su semilla.

Con lo que me topé después de esto en mis aflicciones,
en mi espera y en mis ejercicios espirituales, no debe ser pronunciado.
Sólo puedo decir en términos generales, que me topé con la fuerza misma del infierno.
El cruel opresor rugió sobre mí y me hizo sentir la amargura de su esclavitud,
mientras tenía algún poder sobre mí. Sí, yo sentía al Señor lejos de mí,
y lejos de la voz de mi clamor como para ayudarme.
Me encontré además con profundas sutilezas y artimañas,
que tenían como fin engañarme con esa sabiduría que
parece capaz de hacernos sabios en las cosas de Dios,
aunque en realidad es una tontería y una trampa para el alma,
pues intenta llevarla de regreso al cautiverio donde prevalecen las trampas del enemigo.
Externamente me encontré con la oposición de mi querido padre, mi familia, mis siervos,
la gente y los gobernantes del mundo, por ninguna otra causa sino por temerle a Dios,
adorarlo como Él requería de mí, e inclinarme ante Su Semilla, la cual es Su Hijo;
quien debe ser adorado por hombres y ángeles para siempre.
El Señor mi Dios lo sabe, delante de quien mi corazón y mis caminos están,
y me preservó en amor por ellos, en medio de todo lo que sufrí por causa de ellos,
y aún me preserva.
¡Bendito sea Su puro y santo nombre!

Tal vez algunos quieran saber qué he encontrado finalmente.
Mi respuesta es: "`He encontrado a la semilla.`"
Entiende esta palabra y estarás satisfecho y no preguntarás más. He encontrado a mi Dios.
He encontrado a mi Salvador, y Él no se ha presentado sin Su salvación,
sino que debajo de Sus alas he sentido caer las gotas sanadoras sobre mi alma.
He encontrado el verdadero conocimiento, el conocimiento de vida, el conocimiento vivo,
el conocimiento que es vida; el conocimiento que tiene la verdadera virtud en él,
y en el que se ha gozado mi alma en la presencia
del Señor. He encontrado al Padre de la Semilla,
y en la Semilla lo he sentido ser mi Padre.
Allí he visto Su naturaleza, Su amor, Su compasión, Su ternura, lo cual ha derretido,
vencido y cambiado mi corazón delante de Él. He encontrado la fe de la Semilla,
la que ha hecho y hace lo que la fe del hombre jamás podrá hacer.
He encontrado el verdadero nacimiento,
el nacimiento que es heredero del reino y hereda el reino.
He encontrado el verdadero espíritu de oración y súplica que triunfa en el Señor,
y extrae de Él lo que la condición necesita;
en el que el alma Lo busca siempre en la voluntad,
tiempo y forma que son aceptables para Él. ¿Qué más diré? He encontrado la verdadera paz,
la verdadera justicia, la verdadera santidad, el verdadero reposo del alma,
la morada eterna en la que el redimido habita.
Sé que todo esto es verdadero, en Aquel que es verdadero, y que no soy capaz de dudar,
disputar o razonar en mi mente acerca de esto, según permanezca ahí,
donde se ha recibido la plena seguridad y satisfacción.
También sé muy bien y con claridad de espíritu,
dónde están las dudas y las disputas, y dónde están la certeza y la plenitud,
y que en la tierna misericordia del Señor soy preservado fuera de lo uno,
y dentro de lo otro.

El Señor sabe que no digo estas cosas de manera jactanciosa,
y que preferiría estar hablando de mi nadedad, mi vacío,
mi debilidad y mis múltiples enfermedades, las cuales siento más que nunca.
El Señor ha quebrantado la parte del hombre en mí; soy un gusano,
nadie delante de Él. No tengo fuerza para hacer algo bueno o útil para Él;
ni puedo vigilarme o preservarme a mí mismo.
Diariamente siento que no puedo mantener viva mi propia alma,
y que soy más débil delante de los hombres, sí, más débil en mi propio espíritu,
es decir, en mí mismo, como nunca lo he sido.
Sin embargo, no puedo sino pronunciar alabanza a mi Dios,
porque siento Su brazo extendido hacia mí,
y que la debilidad que siento en mí no es pérdida,
sino ganancia delante de Él. Escribo estas cosas no teniendo un fin propio,
absolutamente no, sino porque esta mañana sentí que se me requería,
y en sumisión y sujeción a mi Dios me entregué a la tarea,
dejándole el éxito y servicio de esto a Él.

[.signed-section-signature]
I+++.+++ Penington.

[.signed-section-context-close]
Aylesbury, 10 del mes tercero, 1667.

--

Por la manera en que concluye podemos ver la humildad de la mente de este amigo,
quien cuando escribió esto, ya estaba muy avanzado en el camino de piedad,
y había vivido varios años en comunión con los llamados Cuáqueros.
Ahora, aunque es deber de todo hombre no envanecerse de sí mismo, aun así es cierto,
que los hombres de refinado ingenio, por encima de todos los demás,
tienen la necesidad de continuar verdaderamente humildes y de no confiar en ello,
ya que la confianza en la agudeza de ingenio más
bien ha apartado a muchos del camino de la verdad,
que llevado a él. De hecho, ha ocasionado la caída de muchos;
pero se desprende claramente del relato de arriba,
que Isaac Penington se esforzaba por continuar en la verdadera humildad.
Era un hombre de temperamento muy compasivo, y sin embargo, valiente en las adversidades.
También sufrió no poco por causa de la religión,
soportando muchos encarcelamientos largos y tediosos;
los cuales fueron más duros para él, porque al ser de una constitución débil,
el frío y las privaciones le hicieron más daño. No obstante, él nunca desmayó,
sino que continuó firme hasta el fin de su vida, que fue a finales del año 1679,
cuando partió en un piadoso estado de ánimo.

Por el relato anterior,
parece evidente que I. Penington estaba buscando
muy fervientemente el verdadero camino de salvación,
incluso antes de alcanzar una perfecta quietud de mente; sin embargo,
en ese tiempo no faltaba quienes hubieran podido serle verdaderamente útiles,
ofreciéndole buenos y sanos consejos; entre ellos estaba John Crook,
cuyas experiencias constituyen una parte no pequeña de esta historia.
Puesto que todavía existe una carta de John Crook escrita a Isaac Penington,
en la que no sólo le habla muy eficazmente a su condición interior,
sino que para su instrucción y aliento,
le relata también las grandes dificultades y tentaciones que él mismo había enfrentado,
no puedo omitir insertarla aquí. Porque de las cartas
francas y sinceras entre amigos cercanos,
en general podemos descubrir muy claramente su estado
interno y también sus cualidades externas.
Esta carta es como sigue:

[.embedded-content-document.letter]
--

[.salutation]
Querido Amigo,

Mi dulce y tierno amor te saluda, en ese amor del que tuve mi ser,
y del que nacieron todos los hijos de mi Padre;
los que han nacido de arriba y son herederos de la herencia eterna.
¡Oh,
cuán dulces y agradables son los pastos en los que
mi Padre hace que todas Sus ovejas se alimenten!
Hay una variada abundancia en Sus pastos, leche para los bebés,
alimento sólido para los de edad madura,
y vino para refrescar a los que están a punto de desfallecer; es decir,
el vino del reino que alegra el corazón cuando se
está a punto de desfallecer a causa de las debilidades.
Estoy seguro de que ninguno puede estar tan cansado, sin que Él cuide de ellos;
ni a punto de desmayar, sin que Él ponga Su brazo bajo sus cabezas;
ni tan acosados con enemigos por todo lado, sin que Él se levante y los disperse;
ni tan cargado, sin que Él se fije y suavemente los conduzca,
y no los deje atrás ante el lobo despiadado.
Porque son Suyos, y Su vida es el precio de la redención de ellos;
y Su sangre el precio del rescate de ellos; y si son tan jóvenes que no pueden seguir,
Él los lleva en Sus brazos, y cuando no pueden sentir nada moviéndolos tras Él,
Su corazón los anhela.
Así de tierno es este buen Pastor en pos de todo Su rebaño.

Yo puedo atestiguarlo,
porque yo era como uno de los que alguna vez han
andado descarriados y vagando por estériles riscos,
donde fui desgarrado por zarzas y punzado por espinos;
algunas veces pensando que estaba en el camino, otras veces que el camino era otro,
y concluyendo por último, que todos estaban fuera del camino.
Y entonces vino sobre mí un amargo lamento, y un llanto, por falta de un guía;
porque cuando trataba de saber qué pasaba y dónde estaba,
era demasiado difícil para mí. Entonces pensé en aventurarme por algún
camino en el que fuera más probable encontrar a un Dios perdido,
y oraría con los que oraban, ayunaría con los que ayunaban,
lloraría con los que lloraban, por si de alguna manera llegaba a descansar;
aun así no lo encontré, hasta que llegué a ver la candela encendida en mi propia casa,
y mi corazón barrido de los pensamientos e imaginaciones, de mi propio querer y correr,
y fui llevado a morir a todos ellos, a no prestarles atención,
sino a vigilar contra ellos, para no dejar que mi mente se prostituyera en pos de ellos.
Allí moré por un tiempo, como en una tierra desolada y deshabitada,
donde me sentaba sólo como un gorrión en la azotea de una casa,
y era perseguido para arriba y para abajo como una perdiz en los montes.
No podía descansar en ninguna parte,
sin que algún deseo o pensamiento me siguiera los
talones y me intranquilizara de noche y de día;
hasta que llegué a conocer a Aquel en quien hay reposo y no hay ocasión de tropiezo;
en quien el diablo no tiene lugar.
Él se convirtió para mí en el lugar de refugio de las tormentas y tempestades.
Entonces mis ojos llegaron a ver a mi Salvador, y mi dolor empezó a desaparecer,
y Él fue hecho para mí el todo en todo, mi sabiduría, mi justicia, mi santificación;
Aquel en quien estaba, y estoy completo,
para la alabanza de las riquezas de Su gracia y bondad que permanecen para siempre.

Por tanto, no te desanimes, tú que eres zarandeado con tempestades;
ni desmayes en ti mismo,
porque ves que poderosas huestes de enemigos se levantan
contra ti y te asedian por todas partes.
Porque nadie ha sido tan asediado, probado y tentado como lo fue la verdadera Semilla,
que fue "`varón de dolores, experimentado en quebranto.`"
Mantente quieto en tu mente y deja que las olas pasen, ola tras ola,
y no te inquietes por ellas,
ni te abatas como si nunca fuera a ser de otra manera contigo.
El dolor viene en la noche, pero el gozo viene en la mañana,
y los días de tu lamento terminarán, y Dios echará fuera al acusador para siempre.
Por esta razón fui afligido y no consolado, y con este fin tentado y probado,
para que a su debido tiempo yo pudiera decir una palabra
a los que son tentados y afligidos como yo lo fui una vez,
como se me dijo en aquel día cuando la tristeza yacía pesadamente sobre mí. Por tanto,
no te desconsueles,
ni le prestes atención a los razonamientos y disputas en tu propio corazón,
ni a los temores que se levantan de ellos.
Antes bien, sé fuerte en la fe, creyendo en la luz que te permite verlos,
y sabrás que Su gracia te basta, y que Su poder se perfecciona en tu debilidad.
Y así,
más bien preferirás gloriarte en tus debilidades para que Su poder repose sobre ti,
que en tus fervientes deseos de librarte de ellas.
Y por estas cosas llegarás a vivir en la vida de Dios,
hallarás gozo en Dios y gloria en la tribulación,
cuando hayas aprendido a estar contento en todas las condiciones;
y es a través de pruebas y profundos ejercicios como se aprende esta lección.

Te he escrito estas cosas en amor a ti,
siendo de alguna manera consciente de tu condición,
y de las muchas trampas a las que estás expuesto diariamente.
Vela, por tanto, para que no caigas en tentación,
y que mi Dios y Padre te guarde en los brazos de amor eterno, por encima de todo,
hasta el fin y para Su alabanza.
Amén.

[.signed-section-signature]
John Crook

--

John Crook había sido un hombre notable en el mundo,
no sólo porque había sido juez de paz, como se ha dicho en su debido lugar,
sino también porque era un hombre de buen intelecto.
Sin embargo, su celo por lo que creía que era la verdad era tal,
que llegó a estar dispuesto a soportar el oprobio del mundo,
para así poder disfrutar de la paz con Dios.
Y aunque era un hombre de estudios,
la mayoría de los primeros predicadores de la doctrina sostenida por los llamados Cuáqueros,
eran personas de poca importancia en el mundo; y sin embargo,
eran tan poderosos en su predicación,
que muchos se volvieron a la verdadera piedad por ella.

Algunos han sido alcanzados por las palabras de penitentes moribundos;
porque han habido notables ejemplos de jóvenes, hijos de padres honestos,
quienes habiendo caminado por el camino ancho,
lamentaron muy fervientemente sus descarríos en su lecho de muerte, y declararon,
que si le placía a Dios levantarlos de allí,
no se avergonzarían más de la despreciada manera de los Cuáqueros,
ni temerían ninguna burla o persecución,
sino que le servirían al Señor en rectitud y con todo su corazón. Éstos,
arrepentidos con lágrimas por sus transgresiones, han experimentado,
después de grandes agonías, que Dios no quiere la muerte de los pecadores,
sino que se arrepientan y vivan en eterna felicidad.

De varios casos similares, sólo mencionaré uno,
el de una joven doncella en Londres llamada Susanna Withrow,
cuya madre era de la sociedad de los Cuáqueros, pero su padre no.
Ella se quejó mucho en su lecho de muerte de su excesiva rebeldía y comportamiento vano.
"`Ah,`" le dijo a su madre,
"`cuántas veces me has dicho que el Señor contenderá contra nosotros;
y ahora ha llegado el día. El orgullo y la desobediencia fueron los frutos
malditos que produje cuando era oyente en la iglesia pública.
Cuántas veces me adorné tan bien como pude a la moda de ellos, y sin embargo,
despreciaban mis vestidos y decían: '`¡Con qué poco gusto te has vestido;
no estás a la moda para nada!`' Entonces, al llegar a la casa el día sábado,
me iba directamente a mi habitación y trancaba la puerta, y cambiaba todos mis encajes,
y así iba a su adoración por la tarde, vestida según la moda de ellos,
y entonces los complacía.`" En otro momento dijo: "`¡Oh,
si yo pudiera tener un poco más de tiempo para ir al campo y caminar por los bosques
para buscar al Señor! ¡Qué importancia tienen las casas lujosas y los vestidos de seda!
¡Acuérdate de Aquel que se sentaba en el suelo y llevaba un vestido sin costura,
nuestro bendito y santo Señor,
quien subía a los montes a orar y se retiraba a jardines y lugares desolados!
No he hecho nada por el Señor, pero Él lo ha hecho todo por mí; por eso deseo vivir,
para poder vivir una vida santa y justa, para que mi ciudadanía esté en el cielo,
aunque mi cuerpo esté aquí en la tierra.
¡Cómo invitaría y advertiría entonces a otros a no gastar
su precioso tiempo adornándose a sí mismos como Jezabel,
arreglándose y pintándose y rizando sus cabellos! ¡Oh, la vida Cristiana es otra cosa!
No debemos darnos la libertad de pensar nuestros propios pensamientos,
mucho menos de realizar tales abominaciones.`"

Estuvo varios días en fuerte lucha y conflicto de espíritu,
y en ferviente oración a Dios, de manera tal,
que cuando alguien quería desviar su atención un poco, ella lo rechazaba diciendo:
"`No debo permitir que ni un solo pensamiento vague, porque si me muevo,
seré sacada de mi vigilancia y entonces el tentador
prevalecerá.`" Continuando en este conflicto,
al fin concibió algunas esperanzas de perdón,
y siendo así fortalecida por la misericordia, le dijo al Señor:

[.embedded-content-document.prayer]
--

¡Oh, ¿qué puede decir mi alma de Tu poder?! Te busqué, pero no te encontré;
toqué fuerte la puerta, pero nadie me abrió. Porque mis pecados se erguían como montañas,
de modo que no podía acercarme a Ti. Yo quería orar fervientemente ante Ti,
pero no podía. Así permanecí varios días y noches, luchando por la vida,
pero no podía encontrar nada; entonces dije: "`No hay misericordia para mí.`" Luego dije:
"`Nunca Te dejaré; si perezco,
pereceré aquí. Nunca dejaré de clamar a Ti.`" Y entonces oí una voz decir:
"`Jacob luchó toda la noche antes de obtener la bendición.`" ¡Entonces Tu Palabra, oh,
Señor, fue fuerte para mi alma!
Luego mi corazón de piedra fue quebrado en pedazos,
y el espíritu de oración y súplica fue derramado sobre mí. Y ahora
puedo cantar como cantó David de la misericordia y del juicio:
"`A Ti, oh Señor, cantaré con un corazón desgarrado,
y con mi boca en el polvo Te cantaré alabanzas, mi bendito Salvador.`"

--

Ella se esforzó por continuar en este estado, y una vez oró por su padre, Robert Withrow,
parte de cuya oración fue: "`Señor, no te acuerdes de sus ofensas,
deja que caigan sobre mí. Que sea fácil para él;
haz que sus amigos sean enemigos para él,
para que Tú puedas tener misericordia de él. Sus tentaciones son grandes, Señor;
llévalo a través de ellas.
No dejes que perezca con el mundo, sino sostenlo sobre este mundo.
¿Se permitirá que un poco de tierra de este mundo aleje su mente de Ti? Oh, Señor,
que su mente se fije en las cosas de arriba;
fija su mente en Ti.`" Así oró esta joven doncella por su padre, fervientemente,
habiendo alcanzado ella misma una plena certeza de su salvación,
de modo que una vez le dijo al Señor: "`Oh, Tú amado de mi alma, qué diré de Ti,
pues eres demasiado maravilloso para mí. Alabado seas.`"
Y después, al percibir que su fin se aproximaba, le dijo a su madre:
"`Tengo que entregar este cuerpo,
el Señor no me confiará más tiempo en este mundo presente y perverso.
Soy feliz.
Oh Salvador mío, mi alma Te ama entrañablemente; Tu amor es mejor que el vino.
Salvador mío, mi Santo, qué glorioso eres.
He visto Tu gloria.
Estoy sobrecogida por Tu dulce rostro.
¡Qué hermoso eres!
Mi corazón está embelesado con las dulces sonrisas de Tu glorioso rostro.
Oh, ven, ven, ¿por qué Te detienes?
Estoy lista, estoy lista.`"
Luego se quedó un rato muy quieta, y así partió de esta vida, sin suspiros ni gemidos,
lo cual ocurrió alrededor del año 1677.

Estas personas moribundas han sido a veces los medios
para incitar a otros a la verdadera piedad,
por lo que llegaron a unirse al pueblo llamado Cuáqueros,
y aunque este pueblo con el tiempo llegó a ser muy numeroso, aun así,
al principio había pocos obreros en el ministerio de la palabra.
Pero estos,
recomendándose unos a otros a prestar diligente atención
a la Palabra de Dios en sus corazones,
y a tenerla en cuenta como su Maestro, a menudo se reunían y celebraban asambleas,
sentados con tal recogimiento de mente, estando vueltos internamente a Dios,
que las lágrimas resbalaban por sus mejillas,
para el asombro de muchos de los que los miraban.
Algunos, sólo por contemplar su recogimiento ante el Señor,
llegaron a ser tan efectivamente alcanzados,
que también se unieron a ellos y frecuentaban sus reuniones.
Entre tanto,
muchos de éstos fueron cada vez más confirmados en
sus mentes al esperar silenciosamente en el Señor,
y sus entendimientos llegaron a estar tan abiertos,
que con el paso del tiempo llegaron a ser instrumentos
aptos e idóneos para exhortar a otros a la piedad.
Y entre éstos, varias mujeres también encontraron que era su deber predicar el evangelio.

Muchos que en algún momento fueron muy hostiles con los Cuáqueros,
llegaron a unirse a ellos en la fe.
Entre otros, estaba un tal Christopher Bacon, en Somersetshire, quien por el año 1656,
entró en una reunión, no con la intención de ser edificado ahí,
sino para burlarse y sacar a su esposa de allí. No obstante,
fue tan alcanzado por la viva exhortación que escuchó,
que no sólo se convenció de la verdad predicada ahí,
sino que con el tiempo él mismo se convirtió en un celoso predicador,
y fue valiente en los sufrimientos.
Una vez, que fue capturado en una reunión en Glastonbury y llevado ante el obispo Mew,
en Wells, quien lo llamó rebelde por reunirse en contra de las leyes del rey,
Christopher (quien había sido anteriormente soldado del rey) le dijo:
"`¿Me llamas rebelde?
Quiero que sepas que yo he arriesgado mi vida por el rey en el campo,
cuando gente como tú se escondía detrás de los arbustos.
De esta manera le cerró la boca al obispo, quien no esperaba tal respuesta,
y por eso estuvo dispuesto a librarse de él.

Un ejemplo similar de una conversación inesperada se vio también en William Gibson,
a quien yo conocí bien, y que en la época de las guerras civiles,
siendo soldado en Carlisle, él y tres más,
habiendo oído que estaba convocada una reunión de Cuáqueros en esa ciudad,
acordaron ir y lastimar al predicador, cuyo nombre era Thomas Holmes; pero Gibson,
al oírlo declarar poderosamente la verdad, quedó tan afectado por su testimonio,
que se paró cerca de él para defenderlo, por si alguien se presentaba para lastimarlo,
y él mismo,
después se convirtió en un celoso predicador de esa verdad de la que estaba convencido.

A estos casos puedo agregar el de cierto trompetista,
que entrando en una reunión de Cuáqueros, empezó a tocar su trompeta de manera insolente,
con el fin de ahogar la voz del que predicaba.
Esto, sin embargo, tuvo el efecto contrario y avivó más el celo del predicador,
de modo que continuó como si nada le estorbara.
Al fin, el trompetista, para recobrar su aliento se vio obligado a dejar de soplar,
pero estando gobernado aún por un espíritu maligno,
después de un descanso comenzó a tocar de nuevo, pero sin importar qué hiciera,
no pudo desviar al predicador de su discurso,
aunque impidió que el auditorio escuchara lo que se decía. De esta manera se cansó tanto,
que se vio obligado a descansar de nuevo, por lo que, a pesar de su perversa voluntad,
oyó lo que el predicador decía, que era tan penetrante,
que fue profundamente afectado por ello,
y estallando en lágrimas confesó su crimen y se convirtió en un verdadero penitente.
Una notable evidencia de la verdad de lo dicho por el apóstol:
"`Así que no depende del que quiere, ni del que corre,
sino de Dios que tiene misericordia.`"

Entre los que en contra de su intención entraron en comunión con los llamados Cuáqueros,
puede ser contado también el juez Anthony Pearson,
quien (como ha sido mencionado en su lugar) fue tan alcanzado por G. Fox en Swarthmore,
que llegó a ser uno de sus seguidores.
Esto es cierto; sin embargo, antes de ese momento,
James Nayler ya lo había convencido algo de la doctrina
sostenida por el pueblo llamado Cuáqueros.
Porque cuando Nayler,
por una acusación de blasfemia fue llamado a comparecer en las sesiones de Appleby,
en el mes llamado enero de 1652,
encontró al citado juez Pearson sentado en el tribunal como uno de sus perseguidores.
Y Pearson, después de hacerle varias preguntas,
recibió respuestas tan acertadas de J. Nayler,
que fue en gran medida convencido de la verdad sostenida por Nayler y sus amigos.

Por lo que ha sido relatado aquí,
puede verse cuán inesperadamente entraron algunos en sociedad con los llamados Cuáqueros;
y podrían darse más ejemplos de esto si fuera necesario.
Porque he conocido a algunos, que siendo de temperamento bullicioso,
fueron tan impactados por el terror del Señor,
que se convirtieron en un espíritu tranquilo y de conducta inofensiva.
Y aunque antes no toleraban la menor provocación,
ahora soportaban toda injuria y burla con una mente ecuánime e imperturbable,
porque el temor de Dios había hecho una impresión tan profunda en ellos,
que tenían cuidado de no pecar contra Dios por un comportamiento airado e impetuoso.
Y así, continuando en una vida temerosa y de reverente temor,
crecieron en la verdadera piedad,
al punto de que predicaban con sus vidas piadosas
tan bien como otros lo hacían con palabras.

De esta manera se incrementó el número de su sociedad.
Pero luego, como ha sido relatado, surgieron graves sufrimientos,
pues los sacerdotes no podían soportar ver que sus oyentes los dejaran.
Por tanto, fue espoleada la turba furiosa, y entre los magistrados había muchos,
que siendo de un temperamento feroz,
usaron toda su fuerza para desarraigar a los profesantes
de la luz (como eran llamados al principio),
y para suprimir y sofocar su doctrina.
Pero todo esto resultó en vano, como se desprende abundantemente de esta historia,
aunque casi no había cárceles en Inglaterra donde
no se encerraran a algunas de estas personas;
además del saqueo de bienes y crueles azotes, etc.
No obstante, todo esto fue soportado con un coraje más que ordinario,
y sin oponer resistencia, a pesar de que muchos de ellos habían sido valientes soldados,
que a menudo habían matado a sus enemigos en el campo de batalla sin reparar en el peligro.

Al considerar esta firmeza inquebrantable,
me parece que ha habido algunos entre este pueblo--cuyo don era
soportar valientemente la persecución por una buena causa,
y quienes, tal vez,
en un tiempo de tranquilidad no habrían sido tan buenos Cristianos como
demostraron ser bajo estos sufrimientos--que se asemejaban a la manzanilla,
que cuanto más se presiona y se frota, más admirable crece y más fuerte huele.
Porque al ser así oprimidos,
se hallaron bajo la necesidad de continuar vigilando y velando,
y siguieron el consejo del rey Salomón:
"`Sobre toda cosa guardada guarda tu corazón.`" Esto hizo
que amaran más que a sus vidas lo que juzgaban ser la verdad,
y los provocó a ser cuidadosos,
no fuera que (como la iglesia de Éfeso) habiendo perdido su primer amor,
fuera quitado su candelero de su lugar.
Así se incrementó su amor mutuo,
y no valoraron sus propias vidas cuando la aflicción de sus consciencias competía con él.

Habiendo pasado por muchas adversidades, con una paciencia incansable y duradera,
y habiéndose convertido en un gran pueblo conocido con el nombre de Cuáqueros,
fueron finalmente,
por la generosa clemencia del rey William III y el favor del Parlamento,
declarados una sociedad Cristiana,
que en adelante sería tolerada en el reino como Protestantes disidentes,
con libertad para realizar su adoración religiosa en público sin perturbaciones.
