== Capítulo XXIV

[.section-date]
1702-1717

[.chapter-synopsis]
* Carta de los Amigos a la reina cuando subió al trono
* Carta de la Reunión Anual a la reina cuando declaró que mantendría el Ley de Tolerancia
* Relato de la vida y muerte de Margaret Fox
* G. Keith y los frutos de la apostasía
* Doctrina de los Amigos sobre la Luz y algunos relatos de sus testimonios
* Muerte y carácter de Anne Camm
* Unión de Inglaterra y Escocia
* Carta de la Reunión Anual a propósito de la unión
* G. Whitehead y la reina
* Carta de Samuel Crisp, clérigo convertido en Cuáquero
* Evan Jevan relata su cambio
* Carta de los Cuáqueros en Londres, a propósito de la renovada promesa de la reina de mantener la tolerancia
* Manifestación contra un proyecto de ley para impedir el crecimiento del cisma
* Muerte de la reina
* Proclamación del rey George
* Carta de los Cuáqueros al rey
* Discursos de G. Whitehead al rey y al príncipe
* El rey George favorable a los Amigos
* Carta de la Reunión Anual en Londres en 1717
* Conclusión.

La reina Anne,^
footnote:[La reina Anne, (1665-1714), hija de James II y hermana menor de la reina Mary,
fue reina de Inglaterra, Escocia e Irlanda del 8 de marzo de 1702 a 1 de agosto de 1714.]
habiendo ascendido al trono y tomado en sus manos las riendas del gobierno,
recibió felicitaciones de todas partes;
y el pueblo llamado Cuáqueros no se consideró menos obligado
que otros de condolerse por la muerte del rey,
y de manifestarle su afecto a la reina.
Por lo tanto, redactaron una carta,
y cuando algunos de ellos (de quienes George Whitehead era
uno) fueron a presentarla el 11 del mes llamado abril,
fueron presentados por el duque de Marlborough y el duque de Ormond.
La carta era la siguiente:

[.embedded-content-document.address]
--

[.salutation]
Sea de complacencia para la reina,

Nosotros, tus pacíficos súbditos,
no podemos sino sentirnos profundamente afectados por la pérdida
sufrida por la muerte de nuestro difunto rey William III,
a quien Dios hizo instrumento de mucho bien para nuestras naciones.
Fue un príncipe que en verdad deseaba ser el padre común de su pueblo, y como tal,
por su gran ejemplo, así como también por precepto,
se esforzó por unirlos en interés y afecto,
y promovió y confirmó la libertad legal para las consciencias tiernas,
por todo lo cual su reino fue adornado, para renombre de su memoria.

Y habiéndole placido al omnisciente Dios, el que dispone los reinos,
preservarte para suceder el gobierno de estas naciones,
y de esa mantener y consumar aquellas grandes obras tan felizmente comenzadas,
nosotros humildemente te felicitamos por tu ascenso libre y pacífico al trono,
desde donde observamos la excelente declaración de la reina,
manifestando su cuidado para el bien de todo su pueblo, y por tanto,
no hay duda de que nosotros, tus súbditos disidentes Protestantes,
participaremos de su favor y protección real.

Nosotros sinceramente declaramos, que con la ayuda de la gracia de Dios,
conforme a nuestro deber Cristiano, siempre demostraremos nuestro buen afecto,
lealtad y fidelidad a la reina y a su gobierno.
Y de corazón oramos que la sabiduría de Dios la dirija,
y que Su bendición esté sobre la reina y su gran consejo,
para la supresión del vicio y la inmoralidad, y para la promoción de la piedad,
paz y caridad, para la gloria de Dios y beneficio de estas naciones.

Qué el Rey de reyes haga largo y glorioso tu reino,
y además de estas bendiciones temporales, oramos también por tu felicidad eterna.

[.signed-section-signature]
Firmado en nombre y por designación del pueblo antes mencionado,
en la reunión en Londres, el 10 del segundo mes de 1702.

--

Esta carta fue muy favorablemente recibida por la reina, y después de que le fue leída,
ella respondió: "`Les agradezco la carta y les aseguro mi protección.`"

Había pasado escasamente un mes después de esto,
cuando Inglaterra le declaró la guerra a Francia,
la cual Holanda también había declarado contra esa corona, unos días antes.
No mucho después de esto se celebró en Londres la
Reunión Anual General de los llamados Cuáqueros,
en la que se consideró oportuno agradecerle a la reina su declaración
de que mantendría la ley de tolerancia en favor de los disidentes.
Por tanto, dicha asamblea redactó una carta, la cual es como sigue:

[.embedded-content-document.address]
--

[.letter-heading]
A la reina Anne, sobre Inglaterra, etc.

[.blurb]
=== El humilde y agradecido reconocimiento del pueblo comúnmente llamado Cuáqueros, de su Reunión Anual en Londres, el 30 del tercer mes llamado mayo de 1702

[.salutation]
Sea de complacencia para la reina,

Nosotros, tus súbditos pacíficos y obedientes,
habiéndonos reunido procedentes de la mayor parte de tus dominios en nuestra
habitual reunión anual (para la promoción de la piedad y de la caridad),
y estando profundamente afectados por tu libre y noble resolución
en tu último discurso en la prórroga del Parlamento,
de preservar y mantener la ley de tolerancia para
el alivio y tranquilidad de todo tu pueblo,
no podemos sino, en gratitud,
considerarnos comprometidos a agradecerle al Todopoderoso Dios por esa influencia favorable,
y a renovar y rendir nuestros humildes y sinceros reconocimientos a la reina por esto,
asegurándole, en nombre de todos nuestros amigos,
nuestro sincero afecto y Cristiana obediencia.

Y le rogamos a Dios, fuente de sabiduría y bondad,
que dirija todos tus consejos y acciones, para que la rectitud que exalta a una nación,
y la misericordia y la justicia que establecen un reino, sea el carácter de tu reinado,
y las bendiciones de estos reinos bajo él.

[.signed-section-signature]
Firmado por el designio y en nombre de la mencionada reunión.

--

De los que presentaron esta carta, William Penn fue el que la entregó,
y a la reina le plació hablar con él de manera muy amable,
no sólo recibiendo dicha carta favorablemente, sino después de leída,
dándole la siguiente amable respuesta: "`Señor Penn,
estoy tan complacida de que lo que he dicho es de su satisfacción,
que usted y sus amigos pueden estar seguros de mi protección.`"^
footnote:[Según el Registro,
esto parece ser más la sustancia que las palabras exactas de la respuesta.]

Este año murió Margaret, la viuda de G. Fox, a los casi ochenta y siete años,
según me parece por un relato de su yerno, Dr. Thomas Lower,
en el que encuentro que ella nació en Marsh-Grange, en la parroquia de Dalton,
Lancashire.
Su padre se llamaba John Askew, un caballero de una antigua familia,
de buena posición y famoso por su piedad y caridad.
Su hija Margaret había sido religiosa desde su juventud,
y se casó antes de haber cumplido los dieciocho años con Thomas Fell de Swarthmore,
quien habiendo sido educado como abogado, se convirtió en juez de paz,
y después de haber sido miembro de varios Parlamentos,
fue nombrado vicecanciller del condado de Lancaster, y con el tiempo juez,
siendo muy apreciado por su justicia, sabiduría, moderación y misericordia.

En el año 1652, George Fox llegó por primera vez a la casa del juez,
cuando él no estaba en casa, y por medio de sus exhortaciones alcanzó tanto a la familia,
que un sacerdote, junto con algunos caballeros,
fueron y le dijeron al juez Fell que a su esposa
y a su familia les había sucedido un gran desastre,
pues habían sido seducidos y convertidos en Cuáqueros.
Esto le fue tan odiosamente presentado, que le preocupó en gran manera.
Pero al regresar a la casa y ser recibido muy amablemente
por su esposa como era su costumbre,
pronto se dio cuenta de que el sacerdote había intentado
hacerle creer falsedades y que tuviera prejuicios.
No mucho después de esto, George Fox tuvo la oportunidad de hablar con él,
lo que le produjo tal satisfacción que reconoció que lo que se decía era la verdad;
y su esposa ordenó que se preparara una cena para su amigo
G+++.+++ Fox y para los que estaban con él. Un tiempo después,
cuando el juez Fell escuchó que Margaret y sus amigos
estaban preguntándose donde podrían tener sus reuniones,
él le dijo a Margaret que podían reunirse en su sala, y así lo hicieron.
Y aunque él mismo no entraba en la habitación, aun así,
cuando se celebraba una reunión solía sentarse en una silla tan cerca de ella,
que aunque no podía ser visto por nadie, podía oír lo que se predicaba,
y le agradaba tanto, que después de oír a George Fox,
no se sabe si alguna vez volvió a frecuentar la iglesia pública.
Y aunque nunca entró en plena sociedad con los Cuáqueros, los favoreció,
y varias veces detuvo la malicia de los perseguidores, cuando estuvo en su poder hacerlo.

Después de haber estado casado veintiséis años con Margaret,
y haber tenido nueve hijos con ella, murió en 1658,
dejando tras sí un hijo y siete hijas.

Después de quedar viuda,
Margaret no desperdició ninguna oportunidad de servir a sus amigos.
En el año 1660, cuando el rey Charles II fue restaurado,
apenas habían pasado dos semanas desde su llegada,
cuando ella fue a Londres y habló varias veces con ese príncipe,
pidiéndole que hiciera cesar los sufrimientos de sus amigos.
Y con este mismo fin, no sólo le escribió cartas al rey,
sino también a los duques de York y Gloucester, a la reina madre,
a la princesa de Orange y a la reina de Bohemia.
Y después de haber estado casi quince meses en Londres,
finalmente prevaleció sobre el rey,
de modo que sus amigos que estaban en prisión fueron
puestos en libertad por proclamación. Pero después,
cuando la persecución comenzó otra vez,
ella fue de nuevo a hablar con el rey y con el duque de York, en Hampton Court.
En el año 1664, por negarse a jurar,
fue confinada en el castillo de Lancaster y retenida por varios años;
porque debido a su gran servicio a la iglesia, era muy envidiada, así como George Fox,
con quien se casó unos once años después de la muerte de su primer esposo, el juez Fell.
Pero no mucho después de su matrimonio,
fue encarcelada de nuevo y continuó un año en la cárcel,
estando enferma la mayor parte del tiempo,
y después fue multada varias veces por predicar.

A los setenta años, habló por última vez con el rey;
pero ella no fue recibida tan favorablemente como antes,
porque él parecía un tanto enojado.
Por tanto,
ella le escribió y se quedó en Londres con la esperanza de recibir una respuesta;
pero el rey fue arrebatado sorpresivamente por la muerte.
Después de esto habló con el rey James y también le escribió. Y finalmente,
después de una vida laboriosa y piadosa, partió piadosamente a una edad avanzada,
como ya se ha dicho, habiendo pronunciado durante el tiempo de su enfermedad,
muchos excelentes dichos,
por los que parece que estaba preparada para la muerte y que anhelaba partir.
Ella fue una celosa predicadora, y también escribió mucho.
Entre otras de sus publicaciones estaba un libro titulado,
[.book-title]#The Call of the Jews out of Babylon,#^
footnote:[[.book-title]#El Llamado de los Judíos a Salir de Babilonia.#]
que dedicó al famoso Manasseh Ben Israel,
y (ya que sería responsable de ello ante Dios) le
encargó hacer que fuera leído entre sus hermanos.
Este libro, que William Ames tradujo al holandés,
también fue impreso en esa lengua mientras su primer esposo todavía estaba vivo.

El mismo año que ella murió, George Keith,
que entonces predicaba de un lado a otro según los obispos pensaban conveniente,
fue bajo las órdenes de ellos a Nueva Inglaterra, Nueva York y Pennsylvania,
porque parece que imaginaba que en esos lugares ganaría
muchos partidarios entre los Cuáqueros.
Pero se quedó muy corto en su objetivo, porque incluso en Pennsylvania,
donde muchos de los Bautistas anteriormente se habían puesto del lado de él,
en ese momento lo miraron con desdén y lo rechazaron por usar la sotana de clérigo;
y como les pareció que era un gran apóstata,
no tuvo posibilidad de entrar o de ser estimado ahí. Después de algún tiempo,
habiendo regresado a Inglaterra, se ganaba la vida en la parroquia de Edburton,
en Sussex, por unas 120£ al año. Ahora bien,
aunque los Episcopales parecían tener grandes expectativas
de que Keith suprimiría la doctrina de los Cuáqueros,
aun así, todos sus esfuerzos resultaron vanos.
Porque sin importar lo que algunos puedan pensar,
es cierto y se desprende claramente de esta historia,
que ellos se convirtieron en un gran pueblo, de una manera muy extraordinaria,
y que todos los proyectos e intentos de desarraigarlos
fueron anulados y quedaron en nada.
Y es a partir de esta consideración, según creo,
que muchos de los llamados Cuáqueros en su predicación
pronunciaban estas palabras de Balaam:
"`Porque contra Jacob no hay agüero, ni adivinación contra Israel,`"^
footnote:[Números 23:23]
como yo mismo he oído muchas veces.
Al fin,
la fuerza y el poder de sus violentos opositores fueron
quebrantados por el favor del rey William III;
y su sucesora, la reina Anne,
ha confirmado favorablemente la libertad de consciencia y adoración
que les fue concedida a los Cuáqueros por la ley del Parlamento.
Por tanto, ahora podemos mirarlos como un pueblo libre,
y como una sociedad tolerada por la autoridad suprema; y así,
yo podría terminar esta historia ahora, en cuanto al significado del título.

Pero antes de concluir, tengo la intención de decir algo concerniente a su doctrina,
de la cual se ha hecho mención varias veces en esta obra, a saber:
Que su principal principio,
en el que difieren de la generalidad de las sociedades Cristianas modernas es,
que todo hombre es alumbrado con una medida de la luz Divina, según el evangelista Juan,
que en el primer capítulo,
hablando de Cristo--como Aquel que era desde la eternidad
con el Padre--lo llama la Palabra,
y dice que la Palabra era Dios, que todas las cosas fueron hechas por Él,
que en Él estaba la vida y que la vida era la luz de los hombres.
El evangelista dice de Juan el Bautista, quien fue enviado por Dios,
que él no era la luz, sino que había sido enviado para dar testimonio de esa luz;
y que esa era la luz verdadera que "`alumbra a todo hombre que viene al mundo.`"
De esto se desprende que los Cuáqueros no han acuñado una frase nueva,
sino que han hecho uso únicamente de las palabras expresas de las Sagradas Escrituras.
No ignoro que durante la gran apostasía,
la gente en general no haya entendido esto claramente; sin embargo,
esto no debe parecer extraño, porque el evangelista expresamente dice:
"`La luz en las tinieblas resplandece, mas las tinieblas no la comprendieron.`"
Pero para aclarar esta doctrina un poco más, puede servir de información,
que los Cuáqueros creen que esta luz es la misma que el apóstol Pablo llama,
"`la gracia de Dios que trae salvación y se ha manifestado
a todos los hombres;`" y con respecto a su operación dice:
"`enseñándonos que, renunciando a la impiedad y a las concupiscencias mundanas,
vivamos en este presente mundo, sobria, justa y piadosamente.`"^
footnote:[Tito 2:11-12]

Lo anterior se menciona brevemente en relación con
los diversos nombres de esta luz divina.
Y ahora, para que quede más claro lo que significa esta frase:
"`Presten atención a la Luz,`" nosotros entendemos,
que cada uno debe tener en cuenta el consejo de la luz en su alma,
y así aprender a temer a Dios, a odiar el orgullo, la arrogancia y todo mal camino;
lo cual engendrará en nosotros tal temor reverencial hacia Dios,
que no nos atreveremos a hacer nada que sepamos con
certeza que le desagradará a Él. Esto,
efectivamente, es el primer paso a la piedad; por eso,
tanto David como Salomón dijeron que el temor de Dios era el principio de la sabiduría;
es decir, el temor que se le debe a Él,
acompañado de prudencia y precaución. Y en la medida que perseveramos en este temor,
somos enseñados y capacitados para servirle al Señor con
santidad y justicia todos los días de nuestras vidas.

Pero, en vista de que sólo podemos hacer esto por la gracia de Dios,
es absolutamente necesario que le prestemos atención a ella;
y por eso debemos pedirle a Dios continuamente Su ayuda.
Pero esto me lleva a otro punto,
sobre el cual la gente generalmente tiene fuertes conceptos;
porque todo tipo de Cristiano concuerda en que nosotros debemos orar a menudo a Dios,
pero muchos se equivocan grandemente en la forma y naturaleza de la oración.
Porque algunos creen que cumplen con este deber de orar a Dios,
cuando por las mañanas y por las noches, y en otros momentos determinados del día,
repiten o recitan algunas formas de oración,
y no parecen considerar que los hombres deben "`orar siempre, y no desmayar.`"^
footnote:[Lucas 18:1]
Y que el apóstol Pablo exhorta a "`orad sin cesar.`"^
footnote:[1 Tesalonicenses 5:17]
Y él mismo explica qué significa esto con estas palabras:
"`Orando en todo tiempo con toda oración y súplica en el Espíritu;`"^
footnote:[Efesios 6:18]
lo cual claramente muestra que esta oración no consiste
en una continua repetición de palabras,
sino en respiraciones piadosas y devotas a Dios,
elevadas en el alma por el Espíritu de Cristo,
rogándole que nos guarde siempre en Su temor y consejo,
ya que tenemos constante necesidad de Su apoyo.
Y así, orando con fe, recibimos respuesta a nuestras respiraciones en alguna medida,
aunque no siempre tan pronto como deseamos.
Pero no debemos desmayar,
y nuestra oración debe ser de una sincera creencia y respiración del corazón;
de lo contrario, oramos mal y no recibimos,
en conformidad con lo dicho por el apóstol Santiago: "`Pedís, y no recibís,
porque pedís mal.`"^
footnote:[Santiago 4:3]

Pero, ¡oh,
qué artimañas y engaños han sido inventados por el enemigo del alma del hombre,
para mantenerlo alejado de este continuo estado de
oración!--aunque Cristo dice muy expresamente:
"`Velad y orad, para que no entréis en tentación;`"^
footnote:[Mateo 26:41; Marcos 14:38]
y "`Lo que a vosotros digo, a todos lo digo: Velad.`"^
footnote:[Marcos 13:37]
Y con respecto a la instrucción que podemos cosechar de estas palabras,
Él no implica una continua vigilia externa sin dormir,
sino una vigilancia de la mente que Salomón recomienda con estas palabras:
"`Con toda diligencia guarda tu corazón.`"^
footnote:[Proverbios 4:23, LBLA]
Ahora bien,
aunque nuestra constitución no nos permite una incesante
continuidad en el más profundo retiro mental,
aun así es cierto, que cuánto más fervientemente volvemos nuestras mentes a Dios,
más son guardadas del mal.
Y el hombre que persevera en este ejercicio piadoso,
está en menos peligro de caer en el orgullo espiritual,
ya que encuentra que su preservación está en la verdadera
humildad y en la continua dependencia en Dios.
Y si en algún momento se separa de ahí, y se considera suficientemente a salvo,
y que ya no necesita caminar prudentemente en el temor como hizo alguna vez,
entonces ya está atrapado y se ha desviado en alguna medida de su Guía espiritual;
es decir, se ha salido de aquello que le mostraba sus transgresiones,
y lo afligía mientras estaba en el mal camino.
Y esta es "`la manifestación del Espíritu,`" que
el apóstol dice "`le es dada a cada uno para provecho.`"^
footnote:[1 Corintios 12:7]

Ahora bien,
llamar a este don o principio--que reprende a los hombres por el mal y consecuentemente
lo descubre--"`Luz,`" no conlleva ningún absurdo,
especialmente si consideramos que este nombre a menudo
se encuentra en los escritos sagrados.
Las malas acciones son llamadas por el apóstol "`obras de las tinieblas,`" y dice:
"`Pero todas las cosas que son reprobadas, son hechas manifiestas por la luz,
porque lo que manifiesta todo, es la luz.`"^
footnote:[Efesios 5:13 RVG]
Por lo que claramente parece, que los Cuáqueros no han acuñado una nueva frase,
sino únicamente seguido el lenguaje de las Escrituras.
Y que ellos no son el único pueblo que ha declarado esta luz,
podría ser probado a partir de muchos otros autores de gran estima, si se requiriera.

En cuanto a los juramentos, ellos juzgan ilícito prestar juramento;
y la razón puede verse abundantemente en esta historia a partir de una multitud de ejemplos.

También creen que hacer la guerra es inconsistente con el Cristianismo puro,
y estiman que los seguidores de Cristo son conducidos por Su precepto,
"`volverán sus espadas en rejas de arado,
y sus lanzas en hoces...ni se adiestrarán más para la guerra,`" según
la predicción del profeta en Isaías 2:4. Cristo el autor de nuestra fe,
a quien se nos manda mirar, expresamente dice: "`Mi reino no es de este mundo;
si mi reino fuera de este mundo, mis servidores pelearían.`" Y el apóstol, en Santiago 4,
nos da a entender que las guerras y pleitos vienen de las pasiones.
Y ellos creen que al recibir el Espíritu de Cristo en sus almas,
y ser completamente guiados por Él, la enemistad y las pasiones,
raíz de las guerras y los pleitos, llegan a ser destruidas y permanece Su amor,
por el cual ellos no sólo se aman unos a otros sinceramente,
sino que también pueden amar a sus enemigos y orar por ellos,
así como también por los que los odian y persiguen por Su nombre,
no devolviendo mal por mal, sino bien por mal.
Y ellos creen que este es el espíritu del Cordero que prevalecerá y que debe vencer,
y por lo tanto, juzgan que no es lícito hacer la guerra.
Y creen que en estas creencias sinceras,
pueden ser tolerados con toda seguridad por cualquier gobierno civil,
no sólo porque están dispuestos y preparados para pagar los impuestos al César,
sino también porque aunque no pueden pelear _por_ el gobierno,
tampoco pueden pelear _contra_ él.

En cuanto a la espada de la magistratura,
ellos en ninguna forma afirman que sea ilícito que los Cristianos sean magistrados;
porque decirlo implicaría que los magistrados no pueden ser verdaderos Cristianos;
a quienes ellos verdaderamente honran, sabiendo que la magistratura es ordenanza de Dios.
Pero aunque ellos creen que este oficio es consistente con la religión Cristiana,
por lo general piensan que es más seguro para ellos no buscarlo.

No consideran que los diezmos a los sacerdotes sean la manutención del evangelio,
dado que nuestro Salvador les dijo en términos expresos a Sus discípulos:
"`De gracia recibisteis, dad de gracia.`"
Sin embargo,
ellos no extienden esto al punto de prohibirles a los que han impartido sus dones espirituales,
recibir dones temporales si están en la necesidad de ello,
siempre que tal manutención del ministro del evangelio sea libre y no forzado;
y que además, no consista en un salario fijo,
que convierta el ministerio del evangelio en una forma de ganarse la vida.
Consideran que esto está muy por debajo de la dignidad del oficio ministerial,
el cual debe ser realizado puramente por amor a Dios y a nuestro prójimo,
y no con algún interés de ganancia secular.

La forma ordinaria de mostrar respeto u honor
en la conducta común es algo de lo que ellos también tienen escrúpulos;
porque creen que darles la misma señal externa de
respeto a los hombres que le es dada a Dios,
es decir, descubrirse la cabeza (sin ninguna buena razón), es inapropiado.
Ellos estiman de la misma manera el dar títulos aduladores de honor,
ya que Cristo reprendió muy severamente los saludos
en las plazas y ser llamados por los hombres Rabí,
Rabí, diciéndoles:
"`No se llamen Rabí;`" cuyo título de aquella época puede ser comparado
con los títulos modernos de "`maestro,`" o "`señor.`" Por tanto,
Cristo también dice: "`¿Cómo pueden creer, cuando reciben gloria los unos de los otros?`"
Sin embargo, ellos limitan esto únicamente a la conversación común entre iguales;
porque un sirviente puede llamar a su amo por ese título,
y los súbditos pueden referirse a los magistrados por el título de su oficio.
Estos títulos honoríficos pueden decirse conforme a la verdad,
mientras que los otros no son más que mera adulación,
inventada para gratificar y reverenciar el orgullo de los hombres.
Además, también creen que es inconsistente con la verdadera sobriedad de un Cristiano,
llamarse a sí mismo "`su humilde servidor,`" etc.,
ante alguien que no tiene un verdadero señorío sobre él;
porque creen que no es posible ser demasiado cautelosos al hablar,
dado que nuestro Salvador dice: "`De toda palabra ociosa que hablen los hombres,
de ella darán cuenta en el día del juicio.`"
También declinan la moda común de los saludos,
pensando que es más seguro no imitar en esto la costumbre común. En cambio,
encuentran más afín con la sencillez del Cristianismo,
saludarse unos a otros dándose la mano,
o por medio de otras atenciones inocentes e inofensivas,
que son señales de amistad y respeto,
y que pueden ser mostradas sin darle al hombre lo que le pertenece a Dios.

Así como los Cuáqueros testifican en contra de los saludos comunes y vanos,
así también están en contra de los juegos de azar, de obras de teatro tontas, de bromas,
de todas las recreaciones pecaminosas y sin provecho, y de beber proponiendo brindis,
todo lo cual creen que es contrario a la exhortación del apóstol: "`Si, pues,
coméis o bebéis, o hacéis otra cosa, hacedlo todo para la gloria de Dios.`"

También se apartan de la forma común en su método de matrimonio,
porque no encuentran en el Antiguo Testamento,
que la unión de una pareja en matrimonio haya sido el oficio de un sacerdote;
ni que en el evangelio haya habido un predicador entre los Cristianos nombrado para eso.
Por tanto, es costumbre de ellos,
que cuando alguno tiene la intención de contraer matrimonio,
primero debe obtener el consentimiento de los padres o cuidadores;
luego debe informar a las respectivas reuniones de hombres y mujeres su intención;
y después de una debida indagación, y de que todas las cosas parecen claras,
en una reunión pública solemnemente se toman uno al otro en matrimonio,
con la promesa de amor y fidelidad, y de no dejarse antes de que la muerte los separe.
Luego se redacta un certificado de esta unión,
mencionando los nombres y distinciones de las personas así unidas,
el cual es primero firmado por ellas mismas,
y luego es firmado por los que están presentes como testigos.

En el entierro de sus muertos,
ellos mantienen en mente el recato y se esfuerzan por evitar toda pompa.
Entre ellos no se aprueba el uso de una vestimenta o hábito en particular como duelo,
porque creen que el duelo que es lícito,
puede ser mostrado suficientemente al mundo por medio
de un comportamiento modesto y sobrio.

En cuanto al bautismo en agua y la cena externa,
aunque ellos no usan las señales externas,
que testifican de Cristo como la sustancia que ha venido,
aun así no juzgan a otros que las usan consciente y devotamente.
No niegan que el bautismo en agua fuera usado por algunos en la iglesia primitiva;
pero consideremos a quiénes se les administraba, es decir,
a los que venían de los judíos o de los gentiles a la sociedad Cristiana.
Y el bautismo era tanto una ceremonia judía como la circuncisión,
porque según el relato de Maimónides,^
footnote:[Moisés ben Maimón, comúnmente conocido como Maimónides,
fue un conocido filósofo judío de la Edad Media.
Véase Vid.
John Leusdcn Philog.
Hebrseo-mixt, Dissertat.
xxi. de Proselyt.
Sect. 1. pag. mihi 144.]
un gentil que deseaba ser recibido en el pacto de los judíos,
tuvo que ser bautizado además de circuncidado, con lo cual se convirtió en un prosélito.
A partir de lo cual se desprende evidentemente,
que el bautismo no reemplazó la circuncisión,
como a menudo se ha insistido para persuadir al ignorante.
No obstante, en el tiempo de los apóstoles,
para hacer de uno un verdadero y real miembro de la iglesia de Dios,
se requería el bautismo del Espíritu como lo principal;
lo que hizo a Juan el Bautista decir:
"`Yo a la verdad os bautizo en agua para arrepentimiento;
pero el que viene tras mí os bautizará en Espíritu Santo y fuego.`"^
footnote:[Mateo 3:11]
Y el apóstol Pedro señala que "`el bautismo que ahora corresponde nos salva,
no quitando las inmundicias de la carne,
sino como testimonio de una buena conciencia delante de Dios.`"^
footnote:[1 Pedro 3:21]
Este fue el bautismo del que Dios, a través del profeta Ezequiel,
habló con respecto a Israel: "`Y yo os tomaré de las naciones,
y os recogeré de todas las tierras,
y os traeré a vuestro país. Esparciré sobre vosotros agua limpia,
y seréis limpiados de todas vuestras inmundicias,`" etc.

Es una objeción común, que Cristo mismo fue bautizado con agua,
y que a nosotros se nos requiere seguir Sus pisadas.
Pero considérese que Él también fue circuncidado,
aunque ni lo uno ni lo otro era necesario para Su propio perfeccionamiento;
pero fue hecho por nuestra causa,
para mostrarnos que nuestros corazones deben ser circuncidados, es decir,
deben ser separados de todas las malas y carnales inclinaciones y lujurias.
Y por el bautismo que Él permitió que le fuera administrado,
se nos indica que nosotros debemos ser bautizados con Su bautismo espiritual.
Y si se objeta que Cristo le dijo a Nicodemo: "`De cierto, de cierto te digo,
que el que no naciere de agua y del Espíritu,
no puede entrar en el reino de Dios;`" se puede responder,
que si esto se entiende como una referencia al agua externa,
la consecuencia será que el bautismo con agua es de tan absoluta necesidad,
que si alguien fuera privado de él, sería excluido del cielo; lo cual,
aunque es una doctrina que creen los papistas, creo que pocos Protestantes lo dirán;
ni siquiera Juan Calvino^
footnote:[Vid. Calvino, Epist. 184. and 229.]
era de esa opinión. También es digno de considerar, que Juan el Bautista dijo,
que Cristo bautizaría con fuego; por lo que se desprende que tanto el agua como el fuego,
como referencias al bautismo, son expresiones metafóricas;
porque ambas sirven para limpiar y purificar, aunque de diferente manera.

Ahora bien, aunque algunos bautizaron con agua, aun así debe considerarse,
que si el mandamiento de Cristo a Sus discípulos: "`Id, y enseñad a todas las naciones,
bautizándoles en el +++[+++Gr. dentro del]
nombre del Padre, y del Hijo,
y del Espíritu Santo,`" hubiera estado totalmente relacionado con el bautismo con agua,
habría sido muy extraño que Pablo, aquel eminente apóstol de los gentiles,
no se creyera comisionado para administrar dicho bautismo.
Porque aunque consideraba que no era inferior en nada a los más eminentes apóstoles,
también dice en términos expresos: "`Pues no me envió Cristo a bautizar,
sino a predicar el evangelio.
Doy gracias a Dios de que a ninguno de vosotros he bautizado, sino a Crispo y a Gayo,
etc.`"
Y sin embargo dice que hay "`un Señor, una fe,
un bautismo,`" el cual era el bautismo del Espíritu.
El mismo apóstol dice también: "`Porque todos los que habéis sido bautizados en Cristo,
de Cristo estáis revestidos;`" y esto no puede tener relación con el bautismo con agua,
porque muchos que han recibido el bautismo externo, nunca se han revestido de Cristo,
ni se han conformado a Su imagen.

A esto se puede añadir, que si el mandamiento de bautizar en Mateo 28:19,
se ceñía literalmente a bautizar con agua, entonces,
¿por qué no se entienden como igualmente literales las palabras de nuestro
Salvador cuando le habla a Pedro acerca del lavamiento de pies:
"`Si no te lavare, no tendrás parte conmigo;`" y a Sus discípulos: "`Pues si yo,
el Señor y el Maestro, he lavado vuestros pies,
vosotros también debéis lavaros los pies los unos a los
otros`"? Mucho más podría ser dicho de este tema,
pero dado que Robert Barclay ha tratado este asunto ampliamente,
el lector puede referirse a su [.book-title]#Apología de la Verdadera Teología Cristiana.#

Con respecto a la cena externa, se puede decir con verdad,
que esa fue la Pascua que Cristo guardó al comer el cordero pascual;
que era igualmente una ceremonia judaica,
la que casi todos los Cristianos toman ahora como una figura o sombra.
Pero el uso moderno de la cena externa en memoria de los sufrimientos de Cristo,
¿no es también una figura de Su cena espiritual con el alma?
¿No parece absurdo que una figura o sombra sea el cumplimiento de otra?
La pascua no era la evocación de otra señal que estaba por venir,
sino el recordatorio de la muerte del primogénito en Egipto,
y de la preservación de Israel y de sus primogénitos.
Además, encontramos que los apóstoles, "`partiendo el pan en las casas,
comían juntos con alegría y sencillez de corazón;`" lo cual implica una comida habitual.

Y ciertamente,
hacen bien los que en sus comidas recuerdan diariamente a Cristo y sus sufrimientos,
porque de la cena espiritual, que es lo requerido,
debe ser partícipe todo verdadero Cristiano; y esto no va a suceder, a menos que,
estando atentos, le abramos la puerta de nuestros corazones a Cristo y lo dejemos entrar.
Consideremos también, que al igual que el cuerpo, el alma necesita comida todos los días,
y que si se priva de ella, desfallecerá,
languidecerá y llegará a ser incapaz de hacer el bien; y es por eso,
que nuestro Señor les recomendó a Sus discípulos orar por el pan de cada día. Ahora bien,
que esto tenía relación principalmente con el maná espiritual,
el pan que desciende del cielo, se desprende del dicho de Cristo: "`Trabajad,
no por la comida que perece, sino por la comida que a vida eterna permanece.`"
Además de esto, el apóstol nos dice, que "`el reino de Dios no es comida ni bebida,
sino justicia, paz y gozo en el Espíritu Santo.`"
Y el autor de Hebreos dice: "`Porque buena cosa es afirmar el corazón con la gracia,
no con viandas, que nunca aprovecharon a los que se han ocupado de ellas.`"

Todo esto al ser debidamente considerado por los llamados Cuáqueros,
les ha impedido el uso de esas ceremonias.
Porque el hombre que a través de la gracia ha llegado a ser verdaderamente espiritual,
no tiene necesidad de ceremonias o medios externos de los cuales depender,
sino que se siente animado a confiar en la gracia
divina interna y a depender sólo de Dios,
caminando continuamente en reverente vigilancia delante de Él. Y así,
aferrándose a las enseñanzas directas de Cristo en su corazón,
se acerca confiadamente al trono de la gracia,
y con plena certidumbre de fe se hace partícipe de la salvación.

Pero dejo este asunto para decir algo también con
respecto a la manera de adoración de los Cuáqueros.
Es usual entre ellos cuando se reúnen en sus asambleas,
pasar algún tiempo en devoto silencio y retiro de mente,
internamente orando con respiraciones puras a Dios,
lo cual ellos generalmente llaman esperar en el Señor. Y si bajo este ejercicio espiritual
alguno se siente movido por Dios a decir algo a modo de doctrina o exhortación,
lo hace, y a veces más de uno, pero siempre ordenadamente, uno tras otro.
Y parece que esto era habitual en la iglesia apostólica primitiva, por lo que dice Pablo:
"`Y si algo le fuere revelado a otro que estuviere sentado, calle el primero.
Porque podéis profetizar todos uno por uno.`"^
footnote:[1 Corintios 14:30-31]
Y el mismo apóstol explica lo que significa profetizar bajo el nuevo pacto,
con estas palabras: "`Pero el que profetiza habla a los hombres para edificación,
exhortación y consolación.`"^
footnote:[1 Corintios 14:3]
Sin embargo, que nadie piense que esta libertad de hablar es tan ilimitada,
que cualquiera que tiene la capacidad de decir algo puede hacerlo libremente en la congregación,
porque el que hable ahí, por supuesto, también deberá tener una vida buena, honesta,
santa y sana en doctrina.
Y si con el paso del tiempo,
la persona encuentra en sí misma una carga del Señor de viajar en el ministerio,
y desea un certificado de su solidez en doctrina y vida ordenada,
puede adquirirlo de la congregación donde reside.
Y en definitiva, el predicador mismo debe haber experimentado la obra de santificación,
antes de estar calificado para instruir a otros en el camino de ella;
porque un mero conocimiento cerebral no puede hacer esto eficazmente.
A veces en sus reuniones hay una oración pública antes de predicar,
y la predicación a menudo concluye con una oración.

Ahora bien, la predicación entre ellos no se limita únicamente al sexo masculino,
como sí sucede entre otros;
porque ellos creen que las mujeres a quienes el Señor ha dotado para el ministerio evangélico,
pueden ejercitar sus dones entre ellos para la edificación;
porque ¿quién se atreverá a decirle al Señor: "`Qué haces,`"^
footnote:[Daniel 4:35]
cuando Él, por medio de Su apóstol, ha dicho: "`No apaguéis al Espíritu`"?^
footnote:[1 Tesalonicenses 5:19]
Ellos no ignoran que el mismo apóstol les dijo a los de Corinto:
"`Vuestras mujeres callen en las iglesias.`"
Ahora, la palabra "`vuestras`" parece llevar aquí un énfasis junto con ella,
siendo aplicable principalmente a las mujeres corintias; pero no insisto en esto.
Sin embargo, parece por lo que sigue,
que esta amonestación se hace con respecto a las mujeres que todavía están en ignorancia,
ya que se dice: "`Si quieren aprender alguna cosa,`" es decir,
si quieren ser más instruidas con respecto a algún punto doctrinal:
"`Pregunten en casa a sus maridos.`"
Por lo que, este dicho parece tener relación con las mujeres,
que ya fuera por indiscreción o curiosidad,
o a partir de un deseo de ser vistas como personas que tienen algo que decir,
hacían preguntas a toda la iglesia, y por esto causaban más confusión que edificación:
"`Porque vergonzoso es que +++[+++tal]
mujer hable en la iglesia;`" y el precepto del apóstol es:
"`Pero hágase todo decentemente y con orden.`"
Además, debe considerarse que estas palabras:
"`Vuestras mujeres callen,`" hacen referencia también
a la sujeción que las mujeres deben a sus esposos,
porque ahí también se dice, que las mujeres "`estén sujetas a sus maridos.`"
Esto lo explica más el apóstol en una de sus epístolas a Timoteo, donde dice:
"`La mujer aprenda en silencio, con toda sujeción. Porque no permito a la mujer enseñar,
ni usurpar autoridad sobre el varón.`"

Ahora,
que el apóstol no les prohíbe absolutamente a las
mujeres hablar para la edificación de la iglesia,
se desprende de sus propias palabras cuando dice:
"`Mas toda mujer que ora o profetiza no cubierta su cabeza, deshonra su cabeza.`"
Aquí les da a las mujeres instrucción de cómo comportase cuando profetizan;
y qué quiere decir él con profetizar, lo explica en la misma epístola,
como ya ha sido mencionado, donde dice: "`Mas el que profetiza,
habla a los hombres para edificación, y exhortación,
y consolación;`" y que "`el que profetiza, edifica a la iglesia.`"
Porque aunque profetizar bajo el antiguo pacto a menudo
parece implicar una predicción de lo que estaba por venir,
también es cierto que los antiguos profetas eran predicadores;
y según el lenguaje del Nuevo Testamento,
es evidente que profetizar es principalmente predicar bajo la influencia del Espíritu.

Ahora podemos entender fácilmente, qué eran las cuatro hijas de Felipe,
quienes profetizaban;^
footnote:[Hechos 21:9]
y qué tipo de sierva de la iglesia era Febe;^
footnote:[Romanos 16:1]
y "`Trifena y a Trifosa, las cuales trabajan en el Señor;`" y "`Pérsida,
la cual ha trabajado mucho en el Señor.`"^
footnote:[Romanos 16:12]
Cuán significativamente llama el apóstol a Priscila y Aquila,
sus colaboradores en Cristo Jesús. Y en Filipenses 4:3 vemos
qué quiere decir con "`colaboradores`" en ese sentido,
donde habla de "`aquellas mujeres que trabajaron juntamente conmigo en el evangelio.`"
Habiendo considerado debidamente todo esto,
los llamados Cuáqueros piensan que es ilícito prohibir a las mujeres predicar
cuando el Señor las ha dotado y son de una vida y conducta piadosas;
ya que se ve suficientemente,
que en la iglesia primitiva ellas no estaban excluidas de ese servicio.
Y como en aquellos días, así en los nuestros,
se ha manifestado claramente que algunas mujeres piadosas
tienen un muy excelente don para la edificación de la iglesia.
Todo lo cual es para la gloria de Dios, quien no hace acepción de personas,
y se complace en usar instrumentos débiles para proclamar Su alabanza.

En cuanto a cantar las palabras de David en los Salmos,
como estas no se ajustan al estado y condición de las asambleas mixtas,
ellos no usan la manera acostumbrada y formal de cantar en las iglesias,
de lo cual no hay precepto ni precedente en el Nuevo Testamento.

Con respecto a la resurrección,
su creencia es ortodoxa y en concordancia con los testimonios de las Sagradas Escrituras;
pero debido a que ellos juzgan muy inapropiado decir que nosotros
resucitaremos con los mismos e idénticos cuerpos que tenemos ahora,
sus opositores los han acusado falsamente de negar la resurrección;
aunque creen plenamente este dicho del apóstol:
"`Si sólo en esta vida esperamos en Cristo,
somos los más miserables de todos los hombres.`"^
footnote:[1 Corintios 15:19]
Y en cuanto a las características de los cuerpos con los que resucitaremos, Pablo dice:
"`Se siembra cuerpo natural, resucitará cuerpo espiritual.`"^
footnote:[1 Corintios 15:44]
"`Mas,`" dice el mismo apóstol, "`nuestra ciudadanía está en el cielo,
de donde también esperamos al Salvador, el Señor Jesucristo;
el cual transformará nuestro cuerpo vil, para que sea semejante a su cuerpo glorioso,
según el poder con el cual puede también sujetar a sí todas las cosas.`"^
footnote:[Filipenses 3:21]
Por lo tanto,
ellos han considerado más seguro no tratar de determinar con qué tipo de cuerpos resucitaremos,
siempre que tengamos la firme creencia de que habrá una resurrección de los muertos.
Porque de tal determinación se pueden levantar muchas dificultades,
que de otro modo se evitan; y por eso, ellos también les han dicho a sus antagonistas:
"`La resurrección de Cristo es, en efecto, un argumento para nuestra resurrección,
pero ¿será válido argumentar a partir de esto,
que porque el cuerpo de Cristo (que estaba libre de pecado y no
se corrompió en la tumba) resucitó igual al que fue sepultado;
entonces nuestros cuerpos, que admiten corrupción,
deben también resucitar iguales a los sepultados?`"
No, porque al insistir rígidamente en este punto, caemos en muchas dificultades.
¿Quién se atrevería a decir,
que cuando las personas mueren y son sepultadas alrededor de los noventa años,
en la resurrección sus cuerpos serán los mismos decrépitos cuerpos que fueron sepultados?
¿O qué un niño no nacido que muere,
será resucitado con un cuerpo tan pequeño como el que tenía entonces?
Por tanto, para evitar semejantes disparates,
ellos piensan que es mejor no permitir que el ingenio humano se extienda demasiado,
muy especialmente porque el apóstol dice:
"`No sean altivos en su pensar;`" y le aconseja al
hombre que "`no tenga más alto concepto de sí,
que el que debe tener.`"

Ahora, en cuanto al gobierno de la iglesia,
tanto para velar por la conducta ordenada de los miembros, cuidar de los pobres,
viudas y huérfanos indigentes,
como para investigar los matrimonios celebrados entre ellos,
tienen reuniones específicas semanales, o cada dos semanas, o mensuales,
según el tamaño de las iglesias.
También tienen reuniones trimestrales en cada condado,
donde se presentan asuntos que no pueden resolverse bien en las reuniones específicas.
A estas reuniones no sólo llegan los ministros y ancianos,
sino también otros miembros que son conocidos por su conducta sobria;
y lo que se acuerda en ellas, se registra en un libro de la asamblea.
Además de estas reuniones, se celebra anualmente en Londres una asamblea general,
en la llamada Semana de Pentecostés;
no por alguna observación supersticiosa que tengan los Cuáqueros
por esa época más que por cualquier otro momento,
sino porque en esa época del año el alojamiento en general se acomoda mejor.

A esta reunión anual, que a veces se prolonga por cuatro, cinco o más días,
llegan los que son enviados de todas las iglesias de esta sociedad en el mundo,
para dar cuenta del estado de las iglesias particulares;
lo cual desde algunos lugares es hecho sólo por escrito.
Y de esta reunión anual es enviada una epístola general a todas las iglesias,
comúnmente impresa;
y a veces también son enviadas epístolas particulares a las respectivas iglesias.
De esta manera, cada año se puede saber en qué condición están las iglesias;
y en dicha epístola, se recomienda en general, una vida y conducta piadosas,
junto con el debido cuidado de la educación de los
niños. Y si en algún lugar los pobres tienen necesidad,
entonces sus necesidades son suplidas por otros que tienen en abundancia, o a veces,
por una colecta extraordinaria.

En cuanto al nombre por el que son distinguidos de las otras sociedades religiosas, es,
como es bien sabido,
"`Cuáqueros;`" pero ya que este nombre les fue dado
en escarnio (como ha sido dicho en su debido lugar),
ellos no lo asumen más que para ser distinguidos de otros;
pero el nombre por el que ellos se llaman entre sí es, Amigos.
Y en esto tienen el ejemplo de los Cristianos primitivos, como se ve en Hechos 27:3,
donde se dice que Julio trató a Pablo humanamente,
y "`le permitió que fuese a los amigos, para ser atendido por ellos.`"
Y en 3 Juan 14 leemos: "`Los amigos te saludan.
Saluda tú a los amigos por nombre.`"
Ahora, este nombre Amigos, es tan común entre los Cuáqueros en Inglaterra,
que otras sociedades también los conocen y a veces los llaman por ese nombre.

Según encuentro, en el año 1705, Anne, la esposa de Thomas Camm,
murió a edad muy avanzada;
y habiendo ya hecho mención de ella por el nombre Anne Audland,
diré algo más antes de describir su salida.
Era hija de Richard Newby, y nació en el año 1627 en la parroquia de Kendal,
en Westmoreland.
Fue bien educada, y cuando llegó a la madurez,
conversaba mucho con la gente más religiosa de la época.
Por el año 1650, se casó con John Audland, y a principios de 1652,
ambos fueron convencidos de la verdad que G. Fox predicaba;
y al siguiente año les comenzaron a predicar la misma doctrina a otros.

Por esto, al año siguiente, Anne fue enviada a prisión en el pueblo de Aukland,
en el condado de Durham,
donde tuvo oportunidad de hablarle a la gente a través de la ventana,
lo cual hizo de manera tan conmovedora, que varios fueron afectados con su testimonio.
Después de ser liberada, viajó por todo el país y tuvo un buen servicio,
pero no mucho después fue enviada a prisión de nuevo, acusada de haber blasfemado.
Por esta causa fue juzgada en Banbury, en Oxfordshire,
y la acusación redactada contra ella contenía el cargo de haber dicho:
"`Dios no vivió;`" cuando ella sólo había dicho que las palabras verdaderas
podrían ser una mentira en la boca de algunos que las dijeran,
alegando lo dicho por el profeta Jeremías: "`Y aunque digan: Vive Jehová;
ciertamente juran falsamente`" (Jeremías 5:2). El
juez ante el cual ella compareció se portó moderadamente,
observando cuán sabiamente respondía ella a sus preguntas con modesta
osadía. Algunos de los magistrados del tribunal que buscaban su destrucción,
percibieron que no podrían obtener su propósito (porque
se había divulgado que ella sería quemada),
por lo que se dispusieron a influir al jurado y a prejuiciarlo.
Esto tuvo el efecto de que la acusaran de un delito menor;
lo que hizo que uno de los presentes dijera:
"`Es ilegal acusarla de una cosa y condenarla de otra,`" ya que ellos
debían haberla declarado culpable o no culpable del asunto imputado en
la acusación. Aunque el juez se había conducido discretamente,
tenía deseos de complacer a los magistrados que eran enemigos de ella; y por eso,
ante su negativa de dar una fianza por buen comportamiento,
fue enviada a prisión de nuevo;
aunque se le oyó decir al juez que ella debió ser liberada.
La prisión a la que fue enviada era un lugar asqueroso, varios escalones bajo tierra;
al lado de lo que era una alcantarilla común, que a veces apestaba mucho,
y de la que salían ranas y sapos que se arrastraban hasta
su habitación. Allí fue retenida por casi ocho meses,
pero ella se mostraba contenta, estando persuadida de que sufría así por causa del Señor.

Su esposo John Audland, murió a principios del año 1664 como se ha dicho antes,
y dos años después ella se casó con Thomas Camm, también ministro del evangelio.
Vivió muy retirada, pasando mucho de su tiempo en soledad,
y ejercitándose casi todos los días en la lectura
de las Sagradas Escrituras y otros libros edificantes.
Su esposo sufrió un encarcelamiento de tres años en Kendal, y uno de casi seis en Appleby.
Por tal razón, llegó a estar muy familiarizada con las adversidades;
pero todo esto la animó a avanzar más en la verdadera piedad,
y se convirtió en una notable maestra en la iglesia,
al tener un extraordinario don para declarar la verdad.
Y sin embargo, era muy modesta y humilde, tanto,
que sin importar cuánto tuviera para declarar,
raramente se presentaba a predicar en grandes reuniones,
donde sabía que había hombres calificados para ese servicio;
y se afligía cuando percibía que algunas de su sexo se adelantaban en esas ocasiones.
Por tanto, ella les advertía que fueran cautelosas,
aunque no dejaba de alentar al bien a todas, y procuraba no apagar al Espíritu en nadie.
Así continuó,
en una vida virtuosa hasta el fin de sus días. Una vez se enfermó tanto en Bristol,
que se pensó que estaba al borde de la muerte.
Entonces exhortó a los que estaban a su lado a valorar su tiempo,
y a prepararse para sus propios finales, "`como Dios,`" dijo,
"`me ha inclinado a hacerlo, de modo que disfruto de una indecible paz aquí,
con la plena seguridad del reposo eterno y de la felicidad en el mundo venidero.`"

Ella, sin embargo, se recuperó de esa enfermedad; y cuando finalmente llegó su muerte,
que ocurrió en su lugar de habitación cerca de Kendal, no estaba menos preparada,
sino que dijo: "`Bendigo al Señor, estoy preparada para mi cambio.
Tengo plena seguridad de la salvación eterna y de la corona de gloria,
por medio de mi amado Señor y Salvador Jesucristo.`"
Pronunció muchas otras excelentes palabras durante el tiempo de su enfermedad;
y cuando se acercaba a su fin, algunos de sus amigos le preguntaron si los reconocía,
y ella les dijo: "`Sí, reconozco a cada uno de ustedes.
Tengo mi entendimiento tan claro como siempre; y cómo podría ser de otra manera,
dado que mi paz está hecha con Dios por medio del Señor Jesucristo.
No tengo turbación en mi mente, por tanto,
mi entendimiento y mi juicio están bien y claros;
pero permanecer bajo aflicción de cuerpo y de mente,
sentir punzadas en el cuerpo hasta la muerte, y no tener paz con Dios--¡oh,
eso sería intolerable de sobrellevar!

Ella le aconsejó a su esposo que se liberara del estorbo
de las cosas de este mundo después de su muerte,
para que él pudiera atender el ministerio del evangelio con más libertad, y dijo:
"`Adviértele a todos, pero especialmente a los ricos,
que se mantengan bajos y que no sean altivos,
porque la humildad y la santidad son el emblema de
nuestra profesión.`" Un poco antes de su partida,
le sobrevinieron algunos desvanecimientos, pero reanimándose dijo: "`Estaba contenta,
pensando que me iba a mi descanso eterno sin turbación. Tengo una visión
y una garantía del descanso eterno con Dios en el mundo venidero.`"
Poco después dijo: "`Creo que me he debilitado y me he enfriado.
Mis manos y pies están muy fríos, sin embargo, mi corazón es muy fuerte.
Debo enfrentarme a punzadas más agudas de las que he sentido hasta ahora.
Este dolor es difícil para la carne y sangre, pero hay que soportarlo poco tiempo;
la tranquilidad y el descanso eternos están cerca.
Estoy contenta de ver la muerte tan cerca de mí.`" Un poco después,
viendo a algunos de sus amigos llorando les dijo: "`No se preocupen,
porque todo está bien.
Sólo tengo que enfrentarme a la muerte, y su aguijón ya está totalmente eliminado.
La tumba no tiene victoria, y mi alma asciende por encima de toda tristeza y dolor.
Por tanto, déjenme ir libremente a mi mansión celestial; no me perturben en mi paso.
Amigos míos, vayan a la reunión; que yo no estorbe los asuntos del Señor,
sino que sean lo más importante, y hechos por todos ustedes fielmente,
para que al final reciban sus recompensas; porque la mía está segura.
No he sido negligente; mi jornada está cumplida.`"

Sintiendo después que sus dolores aumentaban,
oró pidiéndole al Señor que la ayudara a través de la agonía de la muerte;
y poco después dijo: "`¡Dios mío, Dios mío, no me has abandonado,
bendito sea Tu nombre para siempre.
Oh, bendito Salvador mío,
quien sufriste por mí y por toda la humanidad grandes
dolores en tu cuerpo santo en la cruz,
acuérdate de mí, Tu pobre sierva, en esta mi grande aflicción corporal.
Mi confianza está en Ti, mi querido Señor. Ven, ven querido Señor Jesús, ven rápidamente;
recibe mi alma, a Ti la entrego; ayúdame ahora en mis amargas punzadas!`"
Entonces su esposo oró a Dios para que se complaciera en facilitarle el paso.
Y ella no tuvo más punzadas,
sino que poco a poco sus respiraciones se hicieron más cortas, y no dijo mucho más,
excepto:
"`Fue bueno dejarle todo al Señor.`" Durmió en el Señor el 30 de noviembre de 1705,
a los 79 años. Así partió Anne Camm de esta vida, y su esposo dijo después,
que él consideraba una gran bendición haberla tenido por esposa; porque, en efecto,
ella fue una excelente mujer,
y por la misma razón he descrito su final más detalladamente.

Habiendo ya relatado lo que me pareció notable y de importancia
con respecto al levantamiento y progreso del pueblo llamado Cuáqueros,
creo que lo que he escrito puede ser suficiente para cumplir
el propósito que implica el título de esta historia.
Por tanto, sólo añadiré unos pocos sucesos, y luego concluiré.

Muchos años antes, en el tiempo del rey James I,
se hicieron esfuerzos para unir a Inglaterra con Escocia en un solo reino,
pero todo fue en vano.
El rey William III también intentó hacer lo que se podía para ese propósito,
pero su vida no le permitió llevar la obra a la perfección. Sin embargo,
a principios del año 1707, durante el reinado de la reina Anne,
finalmente se acordó y se estableció el asunto, y se concluyó que en adelante,
estos dos reinos debían unirse en uno y llamarse
Gran Bretaña. En la primera parte del año 1708,
Escocia fue amenazada con una invasión por parte del pretendido príncipe de Gales;
pero fracasó en el intento y su plan terminó en nada.
Ahora bien, dado que por fin se había consumado la unión de Escocia con Inglaterra,
y se había establecido por ley la sucesión de la corona en la línea Protestante,
la reina fue felicitada por ese motivo con una gran cantidad de cartas;
y los llamados Cuáqueros también se consideraron
obligados a testificar su afecto a la princesa,
como lo hicieron con la siguiente carta:

[.embedded-content-document.address]
--

[.letter-heading]
A Anne, Reina de Gran Bretaña, etc.

[.blurb]
=== La agradecida y humilde carta del pueblo comúnmente llamado Cuáqueros, de su Reunión Anual en Londres, este día 28 del tercer mes, llamado mayo, de 1708.

Nosotros,
teniendo buenas razones para conmemorar las múltiples misericordias
de Dios concedidas a este reino unido de Gran Bretaña,
creemos nuestro deber hacer nuestros humildes reconocimientos,
primero a la Divina Majestad, y luego a la reina,
por la libertad que disfrutamos bajo su amable y favorable gobierno.
Nuestros sinceros deseos y oraciones son al Todopoderoso Dios,
(quien hasta hoy ha frustrado los planes maliciosos y malvados de sus enemigos,
tanto extranjeros como domésticos) que Él llene el corazón
de la reina y los de su gran consejo de Su divina sabiduría,
tan eficazmente, que la rectitud,
justicia y moderación--que son los ornamentos del reino de la reina,
y los que enaltecen a una nación--se puedan incrementar y ser promovidas.

Y aprovechamos esta oportunidad para asegurarle a la reina una vez más,
nuestro sincero afecto hacia el presente gobierno establecido,
y que como pueblo en nuestros respectivos lugares,
conforme a nuestros pacíficos principios, por la gracia de Dios,
probaremos con toda fidelidad ser súbditos fieles y obedientes a la reina.
Como tal, concluimos con oraciones fervientes al Señor de los ejércitos,
que tras un reinado en esta vida próspero, seguro y largo, tú, oh, reina,
seas bendecida con una corona de gloria eterna.

--

Esta carta fue firmada por catorce miembros en nombre de la reunión,
a quienes también se les comisionó presentarla.
Pero al entenderse que la reina prefería que se le presentara en privado, sólo siete,
entre ellos George Whitehead y Thomas Lower, entraron con ella,
y fueron presentados por el secretario principal de estado, Boyle.
Cuando G. Whitehead presentó la carta, dijo:
"`Sinceramente le deseamos a la reina salud y felicidad.
Hemos venido para presentar una carta redactada en nuestra reunión anual, la cual,
nos hubiera gustado presentar más temprano y oportunamente, pero no se pudo,
porque nuestra reunión no se celebró sino hasta la semana pasada; por tanto,
esperamos que la reina acepte nuestra carta favorablemente en este momento.`"
Entonces, mientras G. Whitehead le entregaba la carta, la reina dijo: "`Léela,
por favor.`"
Con lo cual, él la tomó y la leyó; y la reina respondió:
"`Te agradezco muy amablemente tu carta,
y te aseguro mi protección. Puedes contar con eso.`"

A lo cual G. Whitehead replicó: "`Reconocemos con gratitud que Dios,
por Su poder y especial providencia,
ha preservado y defendido a la reina contra los designios malignos de sus enemigos,
habiendo hecho a la reina un instrumento notable
para el bien de esta nación y reino de Gran Bretaña,
al mantener la tolerancia y la libertad que disfrutamos con respecto a nuestras consciencias,
contra la persecución. Esta libertad,
basada en el deseo del difunto rey de unir los súbditos Protestantes en interés y afecto,
está ahora más establecida y fortalecida por la unión de Gran Bretaña;
porque en la unión está la fuerza y la estabilidad de un reino, y sin unión,
ningún reino o pueblo puede estar seguro, sino que permanece débil e inestable.
Que la sucesión de la corona esté establecida en la línea Protestante,
debe ser necesariamente muy aceptable para todos los verdaderos súbditos Protestantes.
Y ahora, oh, reina,
nuestro sincero deseo es que el Señor te guarde y defienda para el futuro,
el resto de tus días,
y te ayude en todos tus cuidados y preocupaciones por la
seguridad y bien de esta nación y reino de Gran Bretaña,
y que el Señor te bendiga y preserve hasta el fin.`"

A esto la reina respondió: "`Gracias por tus palabras y por tu carta;
y puedes estar seguro de que me encargaré de protegerte.`"

G+++.+++ Whitehead respondió:
"`El Señor bendiga y prospere a la reina y todas sus buenas intenciones.`"
Y entonces él y sus amigos se retiraron.

Disfrutando al fin la libertad de realizar su adoración religiosa pública y sin perturbaciones,
los sucesos más notables que los Cuáqueros en Inglaterra encontraban entonces,
eran las publicaciones de sus enemigos, quienes por ignorancia o envidia,
continuaban presentándolos como personas que mantenían sentimientos heterodoxos.
Pero como no dejaban de responder a sus acusadores por escrito,
los ojos de muchos fueron abiertos, y algunos se acercaron a ellos.
Y aunque en algunas ocasiones sucedió,
que algunos de la iglesia nacional lograron exitosamente atraer
a alguien que había nacido y que había sido educado entre los Cuáqueros,
quien se inclinó a una mayor libertad y a ser estimado por el mundo,
también ha habido otros de la iglesia Episcopal, que por ninguna consideración terrenal,
sino meramente por un convencimiento de sus mentes,
han entrado en sociedad con los Cuáqueros,
sin temor a hacer profesión pública de su religión. Esto
puede mostrarse por dos cartas que insertaré aquí;
la primera es de Samuel Crisp, un clérigo de la iglesia Episcopal,
quien hizo el siguiente relato de su cambio a uno de sus parientes más cercanos.

[.embedded-content-document.letter]
--

[.salutation]
Mi querido Amigo,

La semana pasada recibí una carta tuya enviada por tu tío Bolton;
había una gran cantidad de expresiones amables en ella,
y también en la de tu hermana Clopton.
Yo me siento muy agradecido con ambos y con toda la familia,
por muchas y repetidas bondades;
y si el cuidado de mi escuela no me hubiera absorbido tanto tiempo,
habría aprovechado la oportunidad para responder
la carta de mi querido amigo antes de ahora,
y por ese motivo mi retraso será más excusable.

La noticia que has oído de mi último cambio es realmente cierta--no puedo ocultarlo,
pues es de lo que me glorío--y no fue ninguna esperanza
de ventaja temporal lo que me indujo a ello,
sino un sincero amor a la verdad y una consideración pura por el bien de mi propia alma.
Tampoco puedo estar suficientemente agradecido con Dios,
por haberme permitido vivir para ver este glorioso día,
y por no haberme cortado en medio de mis pecados
y provocaciones contra Él. Él es paciente con nosotros,
pues no quiere que ninguno perezca, sino que todos lleguemos al arrepentimiento.

Él me ha sacado de las formas y sombras de la religión, y me ha hecho ver,
de manera más ilustre, lo que es la _vida_ y la _sustancia_ de ella, pues me encontró,
en algún grado, fiel a esa medida de luz y conocimiento que Él me había otorgado,
mientras estaba en comunión con la iglesia de Inglaterra.
Y así, recientemente, mientras esperaba humildemente en Él,
Le plació darme a conocer mayores y más profundos misterios de Su reino.
Y puedo decir con seguridad,
que a diario encuentro por experiencia (mientras me mantengo bajo
y retirado hacia ese don puro que Él ha plantado dentro de mí),
que las cosas se me aclaran cada vez más,
y que la verdad brilla y prevalece grandemente sobre el reino de las tinieblas;
y que si yo ahora le diera la espalda a manifestaciones
como estas y me enredara otra vez con el yugo de esclavitud,
ciertamente afligiría al Espíritu Santo,
y Él podría justamente retirar Sus tiernas operaciones,
y nunca más regresar a ayudarme ni a consolarme.
Porque Dios no puede ser burlado; la religión es algo muy serio y de peso.
No se debe jugar con el arrepentimiento ni con la salvación;
ni debemos posponer volvernos a Dios hasta nuestro propio tiempo, ocio o conveniencia;
sino que debemos amar y estimar la más pequeña aparición de Cristo,
y no menospreciar el día de las pequeñeces,
sino abrazar la primera oportunidad de seguir a Cristo en cualquiera de Sus mandamientos.
Cuando Él habla, es con tal fuerza y autoridad que no podemos quedarnos para protestar,
discutir, o hacer preguntas,
porque a menos que seamos tan obstinados como para cerrar nuestros ojos contra el sol,
debemos necesariamente confesar la verdad de Su doctrina y abrazarla inmediatamente.

Por tanto, el haber vivido por varias semanas en Londres,
más privada y retiradamente de lo habitual, ayunando dos o tres veces a la semana,
y algunas veces más,
y dedicando mi tiempo a la lectura de las Escrituras y a la oración a Dios,
fue una buena preparación para que mi mente recibiera
la verdad que Él estaba a punto de darme a conocer.
Lamentaba los errores de mi vida pasada,
y deseaba alcanzar un más excelente grado de santidad
que el que había encontrado en la iglesia de Inglaterra.
En ese retiro religioso, Dios vio las respiraciones de mi alma,
cuán sincero era y cuán rendido estaba a Él cuando
estaba sólo. Yo necesitaba que Él me hiciera libre,
y que le hablara paz y consuelo a mi alma que estaba
afligida y cansada por la carga de mi pecado.
Porque aunque yo me había conformado estrictamente
a las órdenes y ceremonias de la iglesia de Inglaterra,
y me había guardado de caer en pecados grandes o
escandalosos (el temor del Todopoderoso me preservaba),
no tenía ese reposo y esa satisfacción en mí mismo que tanto deseaba y anhelaba.
Descubrí, tras examinar mi estado y mi condición ante Dios,
que las cosas no estaban bien conmigo.

Yo sabía que tener una conducta sobria y convincente
ante los ojos del mundo era un logro fácil.
Un buen temperamento natural, más la ventaja de una amplia educación,
dotarán a un hombre rápidamente de las habilidades para eso,
de modo que puede llegar a ser considerado santo y muy espiritual,
cuando tal vez todavía esté en cadenas de oscuridad,
en hiel de amargura y en la atadura misma de la iniquidad.
Si ese tipo de justicia hubiera servido, quizás,
yo mismo habría podido quedar tan bien de ese modo como cualquier otro; ¡pero ay!,
rápidamente vi el vacío y la insatisfacción de esas cosas.
En realidad, es una cubierta que no nos protegerá, ni nos esconderá,
de la ira del Todopoderoso cuando venga a juzgarnos.
No es el temperamento natural de un hombre, ni su educación,
lo que lo hace un buen Cristiano; esa no es la justicia que el evangelio requiere,
ni es la "`verdad en lo íntimo`" que Dios exige.
El corazón y los afectos deben ser limpiados y purificados
antes de que podamos ser aceptables para Dios;
por lo tanto,
para mí era muerte pensar en descansar en una apariencia formal de santidad,
una cubierta en la que vi (para mi tristeza) que
una gran cantidad de personas se habían envuelto,
y que estaban durmiendo segura y tranquilamente, soñando con la felicidad del paraíso,
como si el cielo ya fuera de ellos y no necesitaran preocuparse más por
la religión. No podía albergar una opinión tan peligrosa como esta,
porque entonces sería tentado a descansar en el camino,
mientras todavía viajaba hacia la Tierra Prometida.

Mientras viví en comunión con la iglesia nacional,
creo que hice un pequeño progreso en la vida santa,
y que mediante la ayuda de Dios debilité a algunos de mis enemigos espirituales.
Le doy gracias a Dios, y en verdad puedo decir, que mientras usé las oraciones de ellos,
lo hice con celo y sinceridad, en Su temor y pavor; pero aun así,
no cesaba de suplicarle fervientemente en privado que me mostrara algo más excelente,
que yo pudiera obtener una victoria completa sobre todos mis deseos y pasiones,
y pudiera perfeccionar la justicia delante de Él. Porque yo veía que una
gran cantidad de pecados y debilidades me acompañaban diariamente,
y aunque con frecuencia hacía propósitos de abandonar esos pecados,
las tentaciones eran demasiado fuertes para mí;
de modo que a menudo tenía razones para quejarme junto con el apóstol,
en la amargura de mi alma:
"`¡Miserable de mí! ¿Quién me librará de este cuerpo de muerte?`"
¿Quién me hará libre y me dará fuerza para triunfar sobre el pecado,
el mundo y el diablo--para complacer a mi Dios en todo,
y para que no haya el menor pensamiento, palabra o movimiento, gesto o acción,
sino lo que es exactamente conforme a Su santísima voluntad,
como si Lo viera de pie delante de mí,
y como si fuera a ser juzgado por Él en el próximo minuto,
por el pensamiento de mi corazón? ¡Oh, divina vida! ¡Oh,
seráfica alma! ¡Ojalá yo pudiera permanecer siempre aquí! Porque aquí no hay reprensiones,
ni dolor, ni arrepentimiento;
pues a la derecha de Dios hay perfecta paz y un río inefable de gozo.
¡Ojalá pudiéramos imitar la vida de Jesús,
y ser completamente preparados para toda buena palabra y obra!
Esta era la frecuente respiración de mi alma a Dios cuando estaba en el campo,
pero más especialmente,
después de haber dejado mi nuevo cargo de capellán
y tomado un alojamiento privado en Londres.
En ese retiro (espero poder decirlo sin jactancia), fui muy devoto y religioso,
y encontré en él gran consuelo y refrigerio del Señor,
quien me dejó ver la belleza de la santidad.
En efecto, la dulzura que se levanta de una vida humillada y llevada a la muerte,
fue en ese momento muy placentera a mi paladar,
y me regocijé en ella más que en todos los deleites y placeres del mundo.

Y entonces,
le plació a Dios mostrarme que si yo en verdad quería vivir
una vida tan estricta y santa como la que adorna el evangelio,
debía dejar la comunión con la iglesia de Inglaterra;
pero yo no sabía aún qué camino coger,
ni a cuál cuerpo de hombres debía unirme que fueran
más ortodoxos y más fieles en sus vidas.
En cuanto a los llamados Cuáqueros,
yo era tan ajeno a ellos que nunca había leído ni uno de sus libros,
ni recuerdo haber conversado con ningún hombre de esa sociedad en toda mi vida.
Creo que había uno en Foxly mientras yo era cura parroquial, pero nunca vi al hombre,
aunque fui varias veces a su casa con el propósito de hablar con él,
y sacarlo de su locura y salvaje fanatismo,
como yo entonces ignorantemente pensaba que era.
En cuanto a las creencias y prácticas de los Cuáqueros,
yo sabía que en todas partes se hablaba contra ellas;
porque aquel que quería parecer más inteligente e ingenioso que el resto,
los escogía como objeto de sus bromas y burlas profanas.
De esta manera se divierten los hombres y entretienen a su compañía,
porque un Cuáquero no es sino otro nombre para '`tonto`' o '`loco,`' y escasamente
se menciona alguna vez sino con menosprecio y desdén. En cuanto a la burla,
confieso que nunca fui muy amigo de ella; sin embargo, pensaba,
que si todo lo que se les imputaba a los Cuáqueros era cierto,
eran de las peores personas que alguna vez habían aparecido en el mundo,
y me preguntaba cómo podían llamarse a sí mismos cristianos,
pues me habían dicho que ellos negaban los artículos fundamentales de la fe santa,
por la que yo siempre había tenido la más alta veneración y estima.
Y además, yo siempre había vivido a una gran distancia de ese pueblo,
y era muy celoso en la adoración de la iglesia de Inglaterra,
y en toda ocasión hablaba muy honorablemente de ella, e incluso,
estaba contento de sufrir unas pocas inconveniencias por ese motivo,
como es bien sabido por ti.
Sin embargo, mi padre todavía me consideraba inclinado hacia los Cuáqueros,
y hace algunos años le dijo a un amigo que temía que me volviera un fanático.
Y mientras estaba en la escuela de Bungan, me envió dos libros para que yo los leyera,
escritos contra los Cuáqueros, uno de los cuales era de John Faldo;
quien ha sido suficientemente expuesto por William Penn.

Un día,
mientras vivía en Londres en la forma retirada y privada de la que acabo de hablar,
caminando muy humildemente ante los ojos de Dios,
y teniendo la oportunidad de reflexionar sobre mi vida pasada,
tuve la oportunidad de entrar en una librería,
y casualmente le eché un vistazo a las obras de Robert Barclay.
Como había oído en el campo que él era un hombre de gran importancia entre los Cuáqueros,
tuve la intención de ver cuáles eran sus principios, y qué defensa podían hacer de ellos;
porque yo realmente pensaba, que este pueblo no podía ser tan tonto y ridículo,
ni sostener opiniones tan horribles, como el autor de [.book-title]#The Snake#^
footnote:[Este libro,
[.book-title]#The Snake in the Grass# (La Serpiente en la Hierba)
fue publicado anónimamente en el año 1696.
El autor fue empleado por algunos miembros del clero,
para hacer que los Amigos y sus principios fueran odiosos para el mundo.
Sus tergiversaciones fueron refutadas y sus astutos artificios puestos de manifiesto,
por Joseph Wyeth y George Whitehead en un libro titulado [.book-title]#A Switch for the Snake.#
__(Un Golpe para la Serpiente)__]
y algunos otros nos querían hacer creer.
Me llevé a Barclay conmigo a casa, y lo leí por completo en una semana,
excepto un pequeño tratado al final, que omití al considerarlo muy filosófico.

No obstante,
pronto leí lo suficiente como para convencerme de
mi propia ceguera e ignorancia en las cosas de Dios.
Pues al leerlo, descubrí que una luz irrumpía en mi mente,
y me refrescaba y consolaba poderosamente en aquel estado pobre,
bajo y humilde en el que estaba entonces; porque yo, en verdad estaba entonces,
y había estado durante un tiempo considerable, muy hambriento y sediento de justicia,
y por tanto, recibí la verdad con toda solicitud.
Fue como un bálsamo para mi alma,
y como lluvias para la tierra sedienta y reseca por el calor
y la sequía. Este autor expone las cosas tan claramente,
y las prueba con tal ingenio y destreza de conocimiento,
y me abrió las Escrituras con tal claridad, que sin pararme a criticar, disputar,
levantar argumentos u objeciones,
o consultar con '`sangre y carne,`' me rendí en seguida a Dios;
y llorando de gozo porque había encontrado un tesoro tan grande,
le agradecí muchas veces con lágrimas en los ojos
por tan bondadosa visitación de Su amor,
y que se hubiera complacido misericordiosamente a
mirar hacia mí cuando mi alma clamaba por Él. Y así,
aunque antes había tenido grandes dudas y aflicción
de mente al no saber qué camino tomar,
ahora encontraba que el sol irrumpía tan poderosamente sobre mí,
que las nubes estaban siendo dispersadas.
Ahora estaba completamente convencido en mi propia mente,
del camino que debía seguir y a qué pueblo me debía unir.

Así que dejé inmediatamente la comunión con la iglesia de Inglaterra,
y fui a la reunión en Gracechurch-street.
Después de leer a Barclay, leí algunos otros libros de ese tipo,
entre los cuales estaba una excelente pieza, aunque en un pequeño volumen,
llamada [.book-title]#No Cross, No Crown.#^
footnote:[[.book-title]#No Cruz, No Corona,# por William Penn]
Continué leyendo y frecuentando reuniones por varias semanas seguidas,
pero no dejé que nadie supiera lo que estaba haciendo.
George Whitehead fue el primer hombre con el que conversé; y eso,
varias semanas después de haber comenzado a leer
a Barclay y de asistir a las reuniones de los Amigos.
Por él llegué a conocerlos mejor; y cuánto más avanzaba,
más me gustaba la sencillez de ellos, y la decencia y simplicidad de sus conductas.
No usan las ceremonias y saludos de la iglesia de Inglaterra,
pero se dan la mano libremente,
y conversan como hermanos y hermanas que han brotado de la misma Semilla real,
y han sido hechos reyes y sacerdotes para Dios.
¡Oh, el amor,
la dulzura y el tierno afecto que he visto entre este pueblo! "`En esto,`" dice Cristo,
"`conocerán todos que sois mis discípulos, si tuviereis amor los unos con los otros.`"
"`Vestíos, pues,`" dice el apóstol, "`como escogidos de Dios, santos y amados,
de entrañable misericordia, de benignidad, de humildad, de mansedumbre, de paciencia.`"

Y así, mi querido amigo, te he dado cuenta de mis procedimientos en este asunto.
En cuanto a mi estado físico, si deseas saber cuál es,
puedo informarte que mi salud está tan bien como siempre,
y bendigo a Dios porque tengo suficiente comida y vestido para mí,
de manera que no carezco de ninguna cosa externa.
En realidad, tengo las necesidades y las comodidades de la vida,
así que no nos agobiemos con el cuidado de las vanidades y trivialidades de ella.
Poseamos nuestros vasos en santificación y honor;
y así como llevamos nuestras mentes a una perfecta sujeción a toda la voluntad de Dios,
llevemos nuestros cuerpos en la forma de vida más simple y natural.
Contentémonos con el menor número de cosas,
y no busquemos gratificar nuestros apetitos carnales,
ni seguir las costumbres e indulgencias de los hombres; busquemos más bien,
cómo gobernar nuestros intereses y placeres terrenales, de tal manera,
que podamos llevar mayor gloria a Dios, mayor salud y paz a nuestras propias almas,
y hacer el mayor servicio a la Verdad.
Y si este es nuestro objetivo, entonces,
ciertamente nos bastará una muy pequeña porción de las cosas de este mundo.
Viendo que somos Cristianos, debemos, por tanto,
perseguir con ahínco aquellas cosas que nos acercan a Dios.
Porque todo lo que es más que una necesidad, parece ser una carga para el alma,
cuyo deseo es respirar en una vasija pura,
para así tener un sentido vivo y saborear todas las bendiciones,
tanto del mundo superior como del inferior.

Tú sabes, mi querido amigo, que la religión es algo muy serio.
El arrepentimiento es una gran obra,
y una preciosa alma inmortal es de más valor que diez mil mundos que perecen,
con toda la pompa y la gloria de ellos.
Por tanto, tengamos valor y seamos valientes por la verdad en la tierra.
No nos contentemos con un nombre y una profesión de la piedad,
sino vengamos a la vida y al poder de esta,
sin renunciar nunca a nuestra esperanza de obtener la victoria.
Nosotros tenemos un poco de fuerza de Dios; seamos fieles a Él y Él nos dará más fuerza,
para que así veamos al enemigo de nuestra paz caer delante de nosotros,
y nada sea imposible para nosotros.
Digo, amigo mío, seamos fieles a esa medida de luz y conocimiento que Dios nos ha dado,
para ser beneficiados y edificados por ella en la vida espiritual.
Y en la medida que Dios vea que somos diligentes
y fieles para obrar con la fuerza que hemos recibido,
Él nos iluminará más y más,
y veremos el fin de esas formas y sombras de religión en las que vivíamos antes.
Pero si Él ve que buscamos descansar en esas sombras,
o que nos volvemos fríos e indiferentes en la búsqueda de santidad,
corriendo hacia conceptos y especulaciones,
y que tenemos más disposición a disputar y a tener la apariencia de aprendizaje y sutileza,
que a llevar una vida santa y devota,
entonces es justo que Dios nos deje en un estado carnal y contaminado.
De esta manera continuaremos sólo en el atrio exterior,
donde nos complaceremos contemplando la belleza y los ornamentos de un santuario mundano,
pero nunca experimentaremos la eliminación del velo,
ni el ser llevados por la sangre de Jesús al lugar santísimo,
el único lugar donde hay verdadera paz con Dios y reposo para el alma cansada.
Podría decir mucho sobre este tema, si el tiempo o la libertad me lo permitieran.

En cuanto a una respuesta más detallada a tu carta, no tengo tiempo ahora para darla,
pero deseo que por el momento esta respuesta general sea suficiente.
Y si consideras las cosas en su naturaleza pura,
y no permites que el prejuicio de la educación te influya,
sino que en temor y humildad escudriñas la verdad por ti mismo,
encontrarás que no hay necesidad de otra respuesta para tu carta que la que ya he dado.
Porque al esperar en Dios y buscarlo diligentemente,
encontrarás una respuesta en tu propio corazón; y esta será más completa,
clara y satisfactoria que la que yo, o cualquier otro hombre viviente,
pueda intentar darte.
Pues verdaderamente deseo que tú,
junto con todos los de corazón sincero en la iglesia de Inglaterra,
lleguen a experimentar el omnipotente poder de Dios que los salva y redime de todo yugo;
y puedan claramente ver "`el fin de aquello que había de ser abolido,`"^
footnote:[2 Corintios 3:13]
y llegar al deleite de las cosas espirituales y celestiales.
En verdad, Dios sabe que esta es la oración diaria y profundo anhelo de mi alma.

Hasta que pueda ser más específico, si te place,
puedes comunicar esto a los demás y hacerles saber que estoy bien,
y agradéceles sus amables cartas.
Recordemos orar unos por otros con todo fervor,
para que podamos mantenernos perfectos en toda la voluntad de Dios.
Mi alma dice, Amén.

[.signed-section-closing]
Tu más afectuoso amigo y siervo en Jesús,

[.signed-section-signature]
Samuel Crisp

--

[.offset]
Es también notable la siguiente carta, o relato de un tal Evan Jevans.

[.embedded-content-document.letter]
--

Ya que le ha placido a la divina bondad dotarme de razón,
le doy gracias de corazón a la excelentísima Majestad,
que el siguiente beneficio de Su buena voluntad haya sido darme vida y
ser en aquella parte del mundo donde he tenido la libertad de usarla;
especialmente en la escogencia de mi persuasión religiosa,
y en la manera de devolverle mi reconocimiento.
Deseo que todos los que tienen alguna pretensión religiosa,
hagan uso de esta noble facultad (en sujeción a la voluntad
divina) para determinar su elección en este gran asunto,
y no dejen que la religión con que fueron educados sea necesariamente la de su
opinión. Si las personas fueran verdaderamente sabias para con su propia salvación,
y no se rindieran tan perezosamente a la conducta de otros guías--considerando
así más su comodidad que su seguridad--no sólo serían más capaces
de dar razón de la esperanza que está en ellos,
sino que mostrarían más corazón en sus devociones, más caridad en su religión,
y más piedad en sus conductas de lo que actualmente hacen.

Hace algún tiempo,
cuando fui visitado por la mano castigadora del Señor
por mi pecado y desobediencia a Su santa voluntad,
luché bajo gran aflicción de mente y angustia de espíritu.
Y aunque era más constante que muchos en mi asistencia
a las oraciones públicas de la iglesia,
estricto en mi observación de sus ceremonias,
y excesivamente frecuente en el uso de la devoción privada,
aun así mi carga aumentaba y empeoraba.

En esta condición miserable e infeliz me encontraba,
cuando estando en la casa de un pariente que había regresado
providencialmente de Pennsylvania a su país natal,
me topé con la [.book-title]#Apología# de los Cuáqueros de Robert Barclay;
por cuya lectura fui muy persuadido de sus principios.
Y al volver mi mente hacia el don divino en el interior (según la doctrina de ellos),
me dio victoria en gran medida sobre nuestro común enemigo,
al desterrar mis desordenadas imaginaciones y devolverme a mi firmeza anterior.
En realidad, recibí tal satisfacción y consuelo para mi afligida alma en ese momento,
que en seguida dejé la iglesia de Inglaterra y me uní en sociedad con ellos.
Y ahora estoy aún más confirmado en mi cambio,
especialmente en lo que se refiere a la adoración de nuestro Creador,
porque no sólo es más concordante con las Escrituras de Verdad, sino que,
en mi propia experiencia, el cielo nos ha dado muchas veces seguridad de aprobación,
coronando poderosamente nuestras reuniones con la presencia del Altísimo.
Espero que nadie me envidie esta misericordia, sólo porque no la recibí por su ministerio.
Si lo hace,
tengo razones para sospechar que su caridad no es verdaderamente de amplitud Cristiana,
ya que nuestro bendito Redentor no aprobó tales estrecheces
en Sus discípulos en un caso similar.

¡Oh, que yo nunca olvide la misericordia del Señor para con mi alma,
quien tuvo compasión de mí cuando me revolcaba en mi sangre,
y les dijo a los huesos secos: "`Vivan`"! ¡Oh,
que todos los que son visitados por la mano castigadora de su Hacedor,
se lo tomen en serio y consideren su propio bienestar
y salvación! Deseo con todo mi corazón,
que los que luchan bajo esta ansiedad mental,
tomen ánimo y esperen en la misericordia del Señor,
debido a Su bondad y larga paciencia conmigo.
Soy un monumento viviente de esto,
y espero seguir siéndolo mientras Él me conceda estar aquí. Si estas líneas llegan
a las manos de alguno que está afligido y angustiado como yo lo estuve,
tengo (a través de la misericordia) un efectivo remedio que prescribirte:
Vuelve tu mente a la gracia de Dios en el interior de tu propio corazón,
desiste de tus propias imaginaciones, quédate quieto,
y tranquilamente ríndete a Su santa voluntad; y así encontrarás salud para tu alma,
refrigerio para tu espíritu,
y la dulce consolación del Señor en tu propio corazón. En efecto,
encontrarás tu lamento convertido en alegría, y tu pesadez en gozo.
Esta ha sido mi experiencia de la bondad del Santo de Israel,
quien aborrece el pecado y la iniquidad, y por eso te lo recomiendo.

En cuanto a tu acusación de que yo he "`renunciado
al pacto bajo el que yo y todo Cristiano debe estar,
de abandonar al diablo y todas sus obras,`" estoy tan lejos
de albergar el pensamiento de abandonar ese deber,
que me considero completamente obligado a cumplirlo.
Y si debo afirmar,
que a través de la gracia de Dios y Su ayuda (porque de otro modo sé que no podría hacerlo),
el cumplimiento de este pacto es posible,
no encuentro ninguna razón por la que deba ser considerada falsa doctrina en un Cuáquero,
más de lo que es en un eclesiástico.

En cuanto a "`abandonar esa iglesia y ministerio por los que el Hijo de Dios bajó del
cielo para establecer,`" no estoy consciente de ninguna culpa en ese sentido.
Porque yo creo que Cristo mismo es la cabeza de nuestra iglesia,
y estoy convencido de que Su Espíritu y Su gracia son lo que ordena nuestro ministerio.

Y en cuanto a tu última pregunta,
puedo hacerte saber que mi anterior condición desesperada y desolada
ha sido cambiada a un dulce disfrute de la bondad de Dios,
desde mi unión a este reprochado pueblo.
No puedo ocultar la bondad del Señor,
no vaya a ser que Él retire Sus misericordias de mí.

No hubo ningún interés secular que corrompiera mi decisión en este cambio.
De hecho, es evidente para muchos que prefería rechazarlo.
Porque lo que yo necesitaba era paz con Dios mi hacedor, y misericordia para mi alma,
y habiendo encontrado finalmente la perla de gran precio,
me separé de todo para comprarla.

--

De este relato se desprende que, con su cambio de persuasión religiosa,
el escritor no pretendía nada más que la tranquilidad
de su mente y la salvación de su alma.

Ahora debo mencionar que en el año 1710, en su discurso al Parlamento,
la reina declaró de nuevo que mantendría la tolerancia y la libertad de consciencia,
por lo que muchos le escribieron cartas;
y el pueblo llamado Cuáqueros también estimó su deber
mostrar su agradecido reconocimiento por este favor,
lo que hicieron mediante la siguiente carta.

[.embedded-content-document.address]
--

[.letter-heading]
A la Reina Anne de Gran Bretaña, etc.

[.blurb]
=== La humilde y agradecida carta del pueblo llamado Cuáqueros, en y alrededor de la ciudad de Londres, en nombre de sí mismos y del resto de los de su persuasión.

Cuando consideramos el interés real de la reina de proteger nuestra libertad religiosa,
y la renovada seguridad del trono de su resolución Cristiana de mantener
la tolerancia permitida por la ley a los de consciencia escrupulosa,
y su tierno cuidado de que la misma sea trasmitida a la
posteridad en la sucesión Protestante de la casa de Hanover,
nos vemos agradecidamente obligados a reconocer su bondad en esto,
y aprovechamos esta ocasión para asegurarle a la reina nuestro deber y afecto,
y conducta pacífica bajo su gobierno, como es nuestro principio,
y ha sido siempre nuestra práctica.

De corazón deseamos que nuestros conciudadanos súbditos dejen de lado toda animosidad,
y en un espíritu de amor y mansedumbre,
se esfuercen por superarse unos a otros en virtud y amor universal.

Que el Dios Todopoderoso misericordiosamente se complazca en defenderte y bendecirte, oh,
reina, y te guíe mediante Su consejo en un largo y próspero reinado aquí,
para después recibirte en la gloria, es la sincera oración de tus fieles súbditos.

--

A esta carta la reina le plació responder: "`Les agradezco su carta,
y pueden contar con mi protección.`" La animosidad mencionada en esta carta hacía
referencia a una división que había empezado a crecer por un cambio del ministerio.
Pero como esto está fuera de mi mira, no me meteré en ello.

En el año 1712, murió Richard Cromwell, hijo de Oliver el protector,
a la edad de noventa años. Este hombre había visto grandes cambios durante su vida,
habiendo sido él mismo por un tiempo, el supremo gobernante de Inglaterra,
como se ha mencionado en su debido lugar.

Y aunque no pretendo relatar muchos más sucesos, porque me apresuro hacia la conclusión,
aun así creo que vale la pena agregar el siguiente caso.

En la primavera del año 1713,
hubo un pleito relacionado con la [.book-title]#Ley Contra el Conformismo Ocasional.#^
footnote:[[.book-title]#La Ley Contra el Conformismo Ocasional,#
fue una ley creada para evitar que los disidentes y los católicos
romanos asistieran "`ocasionalmente`" a la iglesia nacional,
con el único propósito de hacerse elegibles para ocupar un cargo público.]
Sucedió que mientras un tal John Penry (juez de paz de Allborough,
en el condado de Suffolk) se dirigía a la iglesia parroquial,
entendió en el camino que no se iba a celebrar ningún servicio ahí en ese momento,
pero al oír que en el lugar había una reunión de Cuáqueros, fue a ella.
Al ser informado un tal Wall, alguacil del lugar,
se imaginó que al citado juez no se le permitía ir allí por la ley antes mencionada.
Por tanto, al pensar que podría ganar algo con ello,
consiguió testigos para que declararan que el juez Penry había estado en la reunión;
y después le dijo de manera jactanciosa: "`¡Te atrapé!`" A esto el juez replicó:
"`Me atendré a ello.`"
Entonces el alguacil entabló su pleito en nombre de uno que vivía por allí de caridad.
Cuando se alegó el caso en las sesiones del tribunal, el juez,
que era el barón Salathiel Lovel, declaró que el significado de la mencionada ley,
no hacía referencia a nadie que periódicamente fuera a la reunión de los disidentes,
sino a los que pretendían conformarse a la iglesia de Inglaterra,
para así calificarse para un oficio,
sin haber cambiado verdaderamente su religión. Pero este era un caso completamente diferente,
porque el mismo sacerdote de la parroquia dio un certificado
declarando que dicho juez era un buen miembro de la iglesia.
De aquí se desprende que el pleito era por mera malicia;
y los testigos (o informantes) se vieron en tal aprieto,
que no se atrevieron a buscar un veredicto del jurado,
por temor a que fueran condenados a pagar cargos, y por tanto, dejaron caer el asunto.

El siguiente año, 1714, la reina estuvo varias veces enferma,
y había mucha división entre el pueblo,
pues se había presentado un proyecto de ley en el Parlamento llamado:
_Ley para Evitar el Crecimiento del Cisma;_
y el partido predominante estaba muy activo buscando la aprobación de dicha ley.
Dicho proyecto pretendía privar a los disidentes Protestantes de tener escuelas privadas,
otorgando esa libertad sólo a miembros de la iglesia Episcopal,
o al menos a los que fueran autorizados por ellos, por lo que se topó con gran oposición,
y se publicaron muchas razones en contra.
El pueblo llamado Cuáqueros también le ofreció a
la legislatura varias objeciones en su contra.
Pero cualquiera que fuera la objeción, dicho proyecto finalmente fue aprobado,
y fue confirmado con el asentimiento real.
Esto le dio oportunidad a los Cuáqueros de agregar en la conclusión de su epístola impresa,
de su Reunión Anual en Londres, la siguiente advertencia y exhortación:
"`Parece que en este momento se cierne sobre nosotros una nube que amenaza tormenta.
Por tanto, velemos y oremos todos,
y retirémonos a nuestra fortaleza en nuestra Roca
y Cimiento espiritual que permanece segura;
para que nuestro Dios continúe defendiéndonos,
ayudándonos y bendiciéndonos como Su pueblo especial,
hasta el final de nuestros días y tiempo aquí,
y para el pleno goce del reino y gloria celestiales en el más allá.`"

A mediados del verano de este año murió Sophia,
viuda y princesa electoral de Brunswick Lunenburg,
en quien se había establecido la sucesión de la corona de Gran
Bretaña. Escasamente dos meses después de su fallecimiento,
también murió la reina Anne, quien después de haber sufrido por un largo tiempo,
finalmente fue arrebatada por la muerte el primero de agosto,
el mismo día que la _Ley para Evitar el Crecimiento del Cisma_ tomó efecto.

Ese mismo día, fue proclamado nuevo rey de Gran Bretaña, George,
príncipe elector de Brunswick Lunenburg;
quien al retornar a Inglaterra un tiempo después,
hizo su entrada a Londres el 20 de septiembre.
No mucho después de su arribo,
declaró en el consejo que mantendría la tolerancia en favor de los disidentes Protestantes.
Con lo cual, le fueron presentadas muchas cartas de felicitación,
y el tercer día de octubre el pueblo llamado Cuáqueros también le presentó su carta,
que fue entregada por George Whitehead y unos cuarenta de sus amigos,
habiendo sido presentados por lord Townsend,
uno de los principales secretarios de estado.
No sólo estaba presente el rey, sino muchos de los nobles y otros,
y al presentarle la carta al rey G. Whitehead dijo:
"`Hemos venido en nombre del pueblo llamado Cuáqueros,
para presentarle al rey George nuestra carta y reconocimiento.
Ojalá sea aceptada favorablemente.`"
Al presentársela al rey, G. Whitehead dijo: "`Uno de nosotros puede leerla para el rey.`"
Con lo cual, la recibió de nuevo y la entregó a Joseph Wyeth,
quien leyó en voz alta de la siguiente manera:

[.embedded-content-document.address]
--

[.letter-heading]
A George Rey de Gran Bretaña, etc.

[.blurb]
=== La humilde carta del pueblo comúnmente llamado Cuáqueros.

[.salutation]
Gran Príncipe,

Habiéndole placido al Todopoderoso Dios privar a
estos reinos de nuestra difunta y amable reina,
con gran humildad nos acercamos a tu presencia real,
con corazones verdaderamente agradecidos con la divina Providencia por tu arribo seguro,
junto con tu hijo el príncipe,
y para tu feliz e ininterrumpido ascenso a la corona de estos reinos; porque,
para el gozo universal de tus fieles súbditos,
esto le ha asegurado al pueblo la sucesión Protestante,
y disipado los justos temores que teníamos de perder esas libertades religiosas
y civiles que nos fueron concedidas por ley en el reino de William III;
cuya memoria mencionamos con gran gratitud y afecto.
También nos sentimos obligados a reconocer agradecidamente
tu pronta y bondadosa declaración en el consejo,
en la que has manifestado tu justa opinión del estado de tu pueblo,
que esperamos hará que todas las clases de tus súbditos se sientan tranquilas.

Y como es conocido que nuestro principio es vivir en paz bajo el gobierno,
así esperamos que siempre sea nuestra práctica, y mediante la ayuda de Dios,
mostrarnos ser, con sincero afecto, tus fieles y obedientes súbditos.

¡Qué el maravilloso Consejero y gran Preservador de los hombres,
guíe al rey por medio de Su divina sabiduría; lo proteja mediante Su poder;
le dé salud y largura de días aquí, y eterna felicidad en la otra vida.
Qué Él bendiga a su descendencia real,
para que nunca deje de adornar el trono con un sucesor dotado de piedad y virtud!

--

Al rey le plació dar esta bondadosa respuesta a la carta:
"`Estoy muy satisfecho con las expresiones de deber que declaran en su carta,
y pueden estar seguros de mi protección.`"

Después de que la carta fue leída, G. Whitehead habló en este sentido: "`Te apreciamos,
rey George, y de corazón te deseamos salud y felicidad, y también a tu hijo el príncipe.
El rey William III fue un feliz instrumento para ponerle fin a la persecución,
al promover la tolerancia,
que al estar destinada a unir a los súbditos Protestantes del rey en interés y afecto,
ha tenido hasta ahora el efecto de hacerlos más amables entre sí,
de lo que eran en los tiempos pasados de persecución,
incluso entre las diferentes persuasiones.
Deseamos que el rey tenga mayor conocimiento de nosotros y de nuestra inocencia;
y que esté seguro de que llevar una vida pacífica y tranquilla en toda piedad y honestidad,
bajo el rey y su gobierno, es conforme a nuestro principio y práctica.`"

Después de que G. Whitehead habló, se le preguntó el nombre, a lo cual respondió:
"`George Whitehead.`"
Y teniendo en su mente ver al hijo del rey también,
y dándoselo a entender a un lord que era un caballero en los aposentos del príncipe,
se abrió paso para ello.
Así, pues, G. Whitehead junto con algunos de sus amigos, tuvieron acceso al príncipe.
Ellos fueron introducidos por uno de los caballeros del príncipe al aposento,
donde el príncipe los recibió; y luego G. Whitehead le dijo en esencia lo que sigue:
"`Tomamos como un favor que se nos permita ver al príncipe de Gales,
y estamos realmente muy contentos de verte.
Tras entregar nuestra carta al rey, su majestad tu padre,
y tener deseos de visitarte en verdadero amor,
deseamos muy sinceramente salud y felicidad para ustedes dos;
y que si le place a Dios que sobrevivas a tu padre y llegues al trono,
disfrutes tranquilidad y paz.
Estoy persuadido de que si el rey tu padre, y tú mismo,
están a favor de que se mantenga inviolable la tolerancia de libertad de consciencia,
Dios los apoyará. ¡Qué la elección de sabiduría del rey Salomón,
sea la elección de ustedes,
junto con la integridad y compasión hacia los oprimidos del santo Job!
Y que el estado del gobernante justo encomendado por el rey David, sea el de ustedes,
a saber: '`El que gobierna a los hombres será justo, gobernando en el temor de Dios.
Y será como la luz de la mañana cuando sale el sol, la mañana sin nubes;
como el resplandor tras la lluvia que hace brotar la hierba de la tierra.`'`"^
footnote:[2 Samuel 23:3-4]

[.offset]
Este discurso fue favorablemente escuchado por el príncipe.

No mucho después de la llegada del rey, murió el Dr. Gilbert Burnet, obispo de Salisbury,
el renombrado autor de [.book-title]#History of the Reformation in England.#^
footnote:[[.book-title]#Historia de la Reforma en Inglaterra.#]
Él, en general, se había mostrado moderado,
y había escrito muy claramente contra la persecución en materia de fe,
especialmente en su [.book-title]#Apology for the Church of England;#^
footnote:[[.book-title]#Apología de la Iglesia de Inglaterra.#]
impresa por primera vez en Holanda en el 1688, y después también en Inglaterra,
en la que entre otras cosas decía:
"`No negaré que muchos de los disidentes sufrieron
grandes penalidades en muchas partes de Inglaterra.
No lo puedo negar, y estoy seguro de que nunca lo justificaré. Y diré audazmente esto,
que si la iglesia de Inglaterra, después de haber salido de esta tormenta,
vuelve a prestarle atención al mal genio de algunos hombres amargados,
será abandonada tanto por Dios como por los hombres,
y pondría al cielo y a la tierra contra ella.`"

Finalizado este año, paso a 1715.
En el mes llamado mayo,
casi había expirado el plazo de la ley sobre la solemne afirmación de los Cuáqueros;
y se resolvió en el Parlamento que se debía presentar
un proyecto de ley para prolongar ese plazo.
Así, el 7 del citado mes,
un proyecto de ley fue consecuentemente presentado en la Cámara de los Comunes,
leído la primera vez, cinco días después la segunda vez, y luego aprobado.
Y mientras que la ley anterior estaba limitada a un número de años,
esta vez la limitación fue omitida, de manera que la ley era perpetua.
Tras avanzar hasta ahí,
el proyecto fue finalmente aprobado en la Cámara de los Comunes y enviado a los Lores,
de donde fue devuelta con esta adición:
Que ese favor también debía ser extendido a la parte norte de Gran Bretaña,
conocida por el nombre de Escocia,
y a las otras plantaciones pertenecientes a la corona de Gran Bretaña, por cinco años,
porque la ley anterior no había llegado aún tan lejos.

Esta enmienda fue acordada por la Cámara de los Comunes el 13 del mencionado mes,
y al final de dicho mes, fue confirmada por el asentimiento real.
De esta manera quedaron nuevamente protegidos los Cuáqueros,
contra las graves repercusiones que de otra manera habrían podido esperar,
por su negativa a prestar juramento.
Como el rey George se había mostrado favorable a ellos en todas las ocasiones,
no dejaron de reconocer con agradecimiento su bondad,
como se desprende de la epístola general de su asamblea anual,
donde expresan su gratitud con las siguientes palabras:

[.embedded-content-document.address]
--

El Señor nuestro Dios, quien por amor a Su heredad,
a menudo ha reprendido y limitado las embravecidas olas del mar, bendito sea Su nombre,
ha dispersado misericordiosamente la nube que amenazaba tormenta,
que últimamente parecía cernirse sobre nosotros.
Esto, junto con el favor que Dios nos ha concedido ante los ojos del rey y del gobierno,
para el libre disfrute de nuestras libertades religiosas y civiles,
es motivo de verdadero agradecimiento a Él. Y humildemente orar al Todopoderoso
Dios por la seguridad y defensa del rey y de los que están en autoridad,
es ciertamente nuestro deber Cristiano, así como también,
caminar inofensivamente como y pueblo agradecido.

--

De esta manera manifestaron su agradecimiento por el favor que disfrutaban;
y como este pueblo ahora disfrutaba tanto de libertad como de tranquilidad,
los otros súbditos también fueron mantenidos en sus derechos bajo un gobierno gentil,
de modo que ninguno de los que se comportaban como súbditos pacíficos,
tenía razones para temer.
Y sin embargo,
en muchos lugares en Inglaterra todavía había grandes convulsiones y tumultos,
y algunos exaltados clérigos eran un instrumento no pequeño en esto; a raíz de lo cual,
se levantó una rebelión abierta,^
footnote:[La Batalla de Preston (9-14 de noviembre de 1715),
fue la batalla final del levantamiento Jacobita de 1715,
en un intento de poner a James Francis Edward Stuart
en el trono británico en lugar de George I.]
pero los rebeldes fueron finalmente derrotados cerca de Preston por las fuerzas del rey.

Antes de concluir este año,
debo decir que el rey francés Luis XIV no vivió para ver el final de esto,
porque el primero de septiembre,
después de haber padecido por un largo tiempo una enfermedad maligna,
murió a los 77 años; tras haber señalado al hijo de su hermano, el duque de Orleans,
como regente del reino de Francia.

Esta muerte pareció en alguna medida alterar los designios
del Viejo Pretendiente (James Francis Edward Stuart),
quien, no obstante, a principios del año 1716 llegó a Escocia procedente de Francia,
con la esperanza de entrar en Inglaterra desde allí. Este intento, sin embargo, fracasó,
y sus fuerzas fueron derrotadas por las del rey.
La opinión común era que él había confiado principalmente en la ayuda de Francia,
la cual le fue negada por esa corte, aunque parecía que él había contado con ella.
Luego permaneció por un tiempo en Gran Bretaña,
después de que sus fuerzas fueron vencidas, pero al no ver manera de invadir el trono,
al final regresó a Francia, y después de un tiempo también se le hizo salir de ahí,
para el gozo de muchos habitantes de Inglaterra; porque se pensaba que los rebeldes,
al verse privados de su jefe, terminarían los disturbios.

Así permaneció el rey George sobre su trono,
y habiéndoles asegurado solemnemente a los llamados Cuáqueros su protección,
ellos continuaron disfrutando la debida libertad de los súbditos que se
comportan pacífica y debidamente bajo el gobierno colocado sobre ellos,
y por tanto,
no dejan de exhortarse unos a otros a mostrar su agradecimiento al Todopoderoso Dios,
y a orar por el rey,
como ha sido mostrado ya en una de las epístolas de su reunión anual.
Y como en esta historia ya se han mencionado varias veces
las epístolas de la asamblea anual a sus iglesias en particular,
he pensado adecuado insertar aquí la del año 1717, que es como sigue:

[.embedded-content-document.epistle]
--

[.blurb]
=== Epístola de la Reunión Anual en Londres, Celebrada del Día 10 al Día 14 del Mes Cuatro, de 1717. Para las Reuniones Mensuales y Trimestrales de los Amigos en Gran Bretaña, y en Otros Lugares.

Nuestro saludo, en el amor de Cristo Jesús nuestro bendito Señor,
se extiende libremente a ustedes,
cuyo tierno cuidado y misericordia para con esta nuestra asamblea anual,
reconocemos humilde y agradecidamente, por el amor,
la buena voluntad y la tierna misericordia manifestados entre nosotros,
en el poder y bondad divinos del Señor nuestro Dios,
y en el servicio de Su iglesia y pueblo.

Verdaderamente nos consuela entender que existe tal acuerdo y unión general
entre todos los Amigos con nuestras epístolas anteriores de consejo,
recomendando que el amor verdadero y universal, la unidad,
la paz y el buen orden se procuren y mantengan fervientemente
entre nosotros como un pueblo peculiar,
escogido por el Señor de entre el mundo,
para dar testimonio fiel de Su santo nombre y verdad en todos los aspectos;
y para que se vigile y se evite todo lo que es contrario, tales como las luchas,
discordias, contenciones y disputas tendientes a las divisiones.
En efecto, esto debe ser completamente suprimido y dejado de lado,
como la luz y el justo juicio de la Verdad lo requiere.

¡Oh,
qué todas las iglesias y congregaciones de los fieles
sean movidas por el Espíritu del amado Hijo de Dios,
a orar fervientemente por la prosperidad de Su iglesia y pueblo en todo el mundo,
para que Sion pueda brillar cada vez más en la hermosura de la santidad,
para la gloria y alabanza del Rey de gloria!

Los amigos y hermanos que han venido de las varias reuniones trimestrales en esta nación,
nos han dado un buen informe de la prosperidad de la verdad, y que los amigos,
en general, están en amor y unidad unos con otros.
Además, por varias epístolas de amigos en North Carolina, Jersey, Pennsylvania, Maryland,
Barbados, Holanda, Escocia, Irlanda y Gales que han sido leídas en esta reunión;
como también por relatos verbales dados por varios amigos que han
viajado últimamente por muchas partes de América y otros lugares,
hemos recibido relatos consoladores del estado de
la verdad y de los amigos en esas partes;
por lo que somos animados a esperar que la verdad prevalezca en muchos lugares,
y crezca en los amigos una preocupación por la prosperidad de ella,
y haya una inclinación en muchos a oír la verdad declarada.

Según los informes presentados este año,
encontramos que las multas impuestas sobre los Amigos en Inglaterra y Gales,
ascienden a cinco mil doscientas noventa libras, principalmente por diezmos,
salarios de los sacerdotes y honorarios de las "`casas del campanario;`" y que,
a pesar de que cuatro Amigos han sido liberados este último año,
todavía permanecen veinte Amigos en prisión por esos motivos.

Aconsejamos que los Amigos en todos los lugares permanezcan fieles,
en mantener un tierno cuidado en guardar nuestro testimonio Cristiano contra los diezmos,
estando plenamente persuadidos de que Dios ha llamado
a Su pueblo a esto en nuestros días;
y viendo por experiencia diaria, que los que no son fieles en esto,
aumentan con ello los sufrimientos de amigos honestos,
y estorban su propio crecimiento y prosperidad en la más bendita verdad.

Con respecto a la crianza de los hijos de los Amigos,
por la que esta reunión ha tenido a menudo preocupación,
pensamos que es nuestro deber recomendarles que tengan cuidado en preservar a los niños
en la sencillez del habla y del vestido que es adecuado a nuestra santa profesión;
y también, que no pierdan ninguna oportunidad, ni escatimen ningún esfuerzo,
para instruirlos con respecto a la luz o semilla de la verdad que profesamos;
para que así, al ser sensibles a sus operaciones en ellos mismos,
no sólo encuentren sus espíritus suavizados y tiernos,
y hechos aptos para recibir las impresiones de la imagen divina, sino también,
para que se encuentren bajo la necesidad de ser fieles en
las varias ramificaciones de nuestro testimonio Cristiano.
Y así como esto será más beneficioso para ellos,
al ser los frutos de sus propias convicciones,
también es la manera más efectiva de propagar lo mismo en todas las iglesias de Cristo.
Y sabiendo que hay tiempos y estaciones particulares en las que sus espíritus
están más dispuestos a que esas cosas sean impresas sobre ellos,
así deseamos que todos los padres,
y los demás que se ocupan de la supervisión de la juventud,
esperen en el temor de Dios a saberse divinamente calificados para ese servicio,
para que en Su sabiduría, aprovechen cada oportunidad que el Señor ponga en sus manos.
Y por la presente advertimos y aconsejamos a los Amigos en todas partes,
que huyan de toda aparición del mal, que se mantengan alejados del orgullo,
y de seguir las modas y costumbres vanas de este mundo,
como es recomendado en la epístola de 1715.

Y así como siempre nos preocupamos por recomendar el amor,
la armonía y la unidad en las iglesias de Cristo en todas partes, nosotros,
como un medio para efectuar lo mismo,
fervientemente deseamos que los Amigos se esfuercen por experimentar
sus propios espíritus sujetos al Espíritu de Verdad;
para que de este modo, siendo bautizados en un solo cuerpo,
sean verdaderamente uno en el fundamento del amor y de la unidad,
y se esfuercen por encontrar una mayor cercanía entre sí en espíritu.
Esta es la verdadera manera de experimentar una reconciliación completa,
dondequiera que haya, o haya existido, alguna diferencia de comprensión. Y así,
los Amigos serán preservados en esa dulzura de espíritu que es, y será para siempre,
el vínculo de la verdadera paz en todas las iglesias de Cristo.

Finalmente, queridos Amigos y hermanos,
tengan cuidado de caminar irreprensiblemente en amor y paz entre ustedes,
y para con todos los hombres en caridad Cristiana;
y permanezcan humildemente agradecidos con el Señor, nuestro muy misericordioso Dios,
por el favor que Él nos ha concedido ante los ojos del rey y del gobierno civil,
en el disfrute pacífico de nuestras libertades religiosas y Cristianas bajo ellos;
y confiamos que el Dios de paz estará con ustedes hasta el fin.

[.signed-section-closing]
La gracia de nuestros Señor Jesucristo sea con sus espíritus.
Amén.

[.signed-section-closing]
Firmado por, en nombre y por orden de esta reunión,

[.signed-section-signature]
Benjamin Bealing

--

Por esta epístola,
mis lectores pueden juzgar algo de las otras epístolas que son
enviadas desde la reunión anual de los llamados Cuáqueros,
a las reuniones particulares de su sociedad en todas partes.
Vemos por esto, que dan cuenta de la condición de sus iglesias particulares,
y que recomiendan fervientemente el amor y la unidad entre sus hermanos,
junto con otras virtudes Cristianas, y especialmente una buena crianza de sus hijos,
además de otros asuntos que juzgan adecuados y necesarios.
Con esta epístola aquí insertada, terminaré mi obra,
habiendo realizado así mi plan e intención, a saber,
hacer un relato claro y circunstancial del levantamiento de esta sociedad religiosa,
la cual, como hemos visto, brotó de un bajo comienzo hacia un gran incremento y progreso.
En efecto, ahora se ha extendido más lejos,
a pesar de la violenta oposición y la más grave severidad,
que tan a menudo han puesto en práctica sus enemigos para suprimirlos y desarraigarlos,
aunque todo ha sido en vano.
Ahora ellos disfrutan una ininterrumpida libertad para realizar
su ejercicio público de adoración a Dios,
ya que su religión es permitida por ley;
libertad que en ninguna forma han obtenido oponiendo resistencia,
sino únicamente por una sufrida paciencia, un comportamiento pacífico,
y la debida fidelidad al gobierno puesto sobre ellos.
Así que ahora ven claramente, que Dios no abandona a los que no lo abandonan a Él,
según lo que en otro tiempo el profeta Azarías le dijo al rey Asa,
y a toda Judá y Benjamín:
"`El Señor estará con ustedes mientras ustedes estén con Él. Y si lo buscan,
se dejará encontrar por ustedes; pero si lo abandonan,
Él los abandonará`" (2 Crónicas 15:2).

Habiendo cumplido así lo que me propuse con este relato histórico, lo concluyo aquí,
para la alabanza y gloria del Altísimo, quien me ha dado vida y habilidad,
después de una larga y difícil labor, para llevar esta historia a un fin adecuado.
