== Los Sufrimientos de Catharine Evans y Sarah Cheevers

En el año 1658, Catherine Evans y Sarah Cheevers,
habiendo sido persuadidas en sus mentes de viajar a Alejandría,
fueron en barco de Inglaterra a Leghorn en Italia,
y tras pasar treinta y un días entre Plymouth y Leghorn,
finalmente desembarcaron a salvo en esa ciudad.
Allí encontraron a algunos de sus compatriotas y amigos,
y se quedaron varios días repartiendo muchos libros cuando la ocasión lo permitía.
También hablaron con personas de varios niveles sin ser molestadas por ninguno.
Ahí obtuvieron pasaje en un barco holandés con destino a Alejandría, o Scanderoon,
pero el capitán del barco, al estar en compañía de otro que iba para Malta,
fue también ahí, aunque no tenía negocios en ese lugar;
pero antes de que llegaran a Malta, Catherine cayó en tal angustia de mente que exclamó:
"`¡Oh, tenemos una terrible copa que tomar en ese lugar!`"
Al entrar en el puerto y estando en la cubierta del barco,
mirando a la gente que estaba parada en los muros, dijo en su corazón:
"`¿Nos van a destruir?
Si nos rendimos al Señor, Él es suficiente para librarnos de sus manos,
pero si desobedecemos a nuestro Dios, ninguno de estos podrá librarnos de Su mano.`"
Y así les fue quitado todo temor al hombre.

Al día siguiente, el Primer-día,
fueron a la orilla donde el cónsul Inglés las recibió y les preguntó a qué habían venido.
Ellas respondieron lo que les pareció que era conveniente y le dieron algunos libros.
Entonces él les dijo que en ese lugar estaba la Inquisición,
e invitándolas amablemente a su casa,
les dijo que todo lo que él tenía estaba al servicio de ellas mientras
estuvieran ahí. Ellas aceptaron la invitación y fueron con él,
y muchos llegaron a verlas, a los que ellas llamaron al arrepentimiento,
de modo que varios se mostraron atentos.
Cerca de la noche regresaron al barco y al día siguiente fueron de nuevo a la ciudad,
y yendo donde el gobernador,
él les dijo que tenía una hermana en el convento que deseaba verlas.
Entonces fueron al convento y hablaron con las monjas y les dieron libros.
Uno de los sacerdotes, que las llevó a la capilla,
quería que se inclinaran frente al altar mayor, pero ellas se negaron,
afligiéndose por la idolatría que ahí se cometía. Después de esto
regresaron a la casa del cónsul donde se quedaron varias semanas.

Durante ese tiempo,
una vez entraron en uno de los lugares de culto en el tiempo de la adoración,
y Catherine, de pie en medio del pueblo, le dio la espalda al altar mayor,
y arrodillándose,
levantó la voz en oración al Señor. El sacerdote que oficiaba se quitó su sobrepelliz^
footnote:[Prenda larga y amplia,
de tela blanca y fina y con las mangas muy anchas que lleva sobre la sotana el sacerdote]
y se arrodilló cerca de ella hasta que Catherine terminó. Entonces él extendió
la mano hacia ellas para que se acercaran y le ofreció una moneda a Catherine,
que al tomarla como la marca de la bestia, la rechazó. En seguida,
puso la moneda en la mano de Sarah, pero ella se la devolvió,
y le mostró la cartera para que él viera que ella tenía para dar,
si alguien tenía necesidad, y que hasta ahora ella no tenía falta de nada.
Luego les preguntó si ellas eran Calvinistas o Luteranas.
Ellas respondieron: "`No.`" Les preguntó si ellas irían a Roma para ver al papa.
Al negarlo, les preguntó si eran católicas, a lo que dijeron,
que ellas eran verdaderas cristianas, siervas del Dios vivo.
Pero como todavía no habían aprendido mucho del idioma que se hablaba ahí,
se expresaron muy deficientemente, en parte con palabras y en parte con señas,
lo mejor que pudieron, y muchos de los que las rodeaban quedaron asombrados;
al final se marcharon pacíficamente.

Un tiempo después fueron de nuevo a una '`casa de la misa`', cuando el sacramento,
como lo llaman ellos, era administrado.
Había muchas luces y una gran opulencia, y afligiéndose debido a la idolatría,
estuvieron cerca de tres cuartos de hora llorando y temblando, especialmente Catherine.
Esto impactó tanto a la congregación que algunos se alejaron de ellas por temor.
Finalmente se fueron, pero aún bajo tal temblor recorrieron la calle tambaleándose,
de modo que se convirtieron en un espectáculo para todos los que las veían.

Catherine y Sarah estuvieron cerca de tres meses en la casa del cónsul inglés,
y al estar él bajo sospecha por esa razón,
no hizo lo que podía haber hecho para salvarlas, porque en cierto sentido,
las había entregado a la Inquisición,
aunque por juramento estaba obligado a proteger a todos los ingleses ahí. Mientras tanto,
las mantuvo en su casa y no les permitió que se fueran al extranjero,
aunque el gobernador le había dicho que él podría
dejarlas ir para que se dedicaran a sus asuntos.
"`Porque,`" dijo él, "`ellas son mujeres honestas.`"
El cónsul también podría haberlas dejado libres,
antes que cayeran bajo el poder de la vara negra.
Percibiendo ellas que algo para su perjuicio se estaba agitando,
y haciendo cuentas de que una prisión sería su destino,
le expresaron que ellas sospechaban de él,
y le dijeron que Pilato les había hecho un servicio a los judíos, y sin embargo,
se había lavado las manos en inocencia.
Sabiéndose descubierto, les pidió una señal que demostrara que eran mensajeras de Dios,
y ellas le dieron a entender que lo siguiente serviría de señal:
Que a ellas les iría bien, pero que a él no le iría bien.

Después de esto sucedió que la Inquisición envió a buscarlas.
Ese mismo día la esposa del cónsul les llevó algo de comer, pero al pasar junto a ellas,
Catherine fue golpeada, como si hubiera recibido una flecha en el corazón,
y le pareció oír una voz diciendo: "`Ella ha logrado su propósito.`"
Entonces Catherine no quiso probar la comida, sino que se apartó y lloró mucho.
El cónsul la llamó y le dijo que la Inquisición había mandado a buscarlas,
al recibir órdenes de Roma, pero que él esperaba que ellas fueran liberadas.
Esto, sin embargo, no era cierto,
porque él sabía (como ellas entendieron más tarde) que se había
preparado una habitación para ellas en la prisión de la Inquisición.

No había pasado mucho tiempo antes de que el canciller,
el cónsul y uno con la vara negra llegaran a buscarlas,
y las llevaran delante del señor inquisidor.
Él les preguntó si habían cambiado de opinión,
porque parece que esto se les había exigido anteriormente,
pero ellas respondieron que no, y que no abandonarían la Verdad.
Luego les preguntó acerca de esa nueva luz de la que ellas hablaban.
Ellas contestaron que no era una nueva luz,
sino la misma de la que los profetas y apóstoles dieron testimonio.
Entonces les preguntó cómo se había perdido esa luz desde los tiempos primitivos.
Ellas contestaron que no se había perdido, que los hombres todavía la tenían en ellos,
pero que no la conocían por causa de la noche de
la apostasía que se había extendido sobre las naciones.
Entonces les dijo que si cambiaban de opinión y hacían lo que se les había dicho,
que lo dijeran, o de lo contrario, las tratarían a su antojo.
Pero las dos mujeres, indicando que no cambiarían de religión, dijeron:
"`Hágase la voluntad del Señor.`" Entonces el señor
inquisidor se levantó y se fue con el cónsul,
dejándolas ahí,
y el hombre con la vara negra y el guarda las cogieron y
las metieron en una habitación interior de la Inquisición,
la cual sólo tenía dos pequeños agujeros en ella para luz y aire.
Este lugar estaba tan extremadamente caliente,
que parecía que la intención de ellos era sofocarlas, como podemos ver a continuación.

No mucho después fueron llevadas delante de los inquisidores
para ser interrogadas más a fondo.
No sólo les preguntaron sus nombres, sino también los nombres de sus esposos y padres,
y cuántos hijos tenían, y por qué estaban ahí. A lo que ellas respondieron,
que eran siervas del Dios vivo y que estaban allí para llamarlos al arrepentimiento.
Al día siguiente las llamaron de nuevo, pero esta vez las interrogaron por separado.
Cuando le preguntaron a Sarah si ella era una verdadera Católica,
ella dijo que era una verdadera Cristiana, que adoraba a Dios en Espíritu y en Verdad.
Luego le mostraron un crucifijo y le pidieron que jurara que diría la verdad.
A lo cual ella dijo, que diría la verdad, pero que no juraría,
porque Cristo había mandado: "`No juréis en ninguna manera.`"

El cónsul inglés que también estaba presente, trató de persuadirla a que jurara,
y le dijo que nadie le haría daño. Como Sarah tenía algunos libros con ella,
se los quitaron, y le preguntaron por qué llevaba ella esos libros,
a lo que ella respondió, porque ellas no podían hablar su idioma.
Luego le preguntaron qué era George Fox.
Ella respondió: "`Un ministro.`"
Además, le preguntaron de nuevo, por qué estaba ahí. Ella replicó,
para hacer la voluntad de Dios,
según había sido movida por el Señor. La siguiente pregunta fue,
cómo le había aparecido el Señor. A lo cual respondió: "`Por medio de Su Espíritu.`"
Y al preguntarle si ella había visto Su presencia y oído Su voz, su respuesta fue,
que ella había oído Su voz y visto Su presencia.
Entonces le preguntaron, qué le había dicho Él. Ella respondió,
que Él le había pedido que cruzara los mares para hacer Su voluntad.
Esto hizo que le preguntaran,
cómo había sabido ella que era el Señor quien le había pedido esto.
A lo que ella respondió, que Él le había indicado que Su presencia viva la acompañaría,
y que ella lo encontraba cumpliendo Su promesa,
porque ella sentía efectivamente Su presencia viva.
Después de esto se fueron.

Dos días después de esto llegaron los inquisidores y llamaron a Catherine,
y ofreciéndole el crucifico,
le dijeron que los magistrados le ordenaban jurar que diría la verdad.
A lo que ella dijo que diría la verdad, porque era testigo de Dios, pero que no juraría,
dado que Uno mayor que los magistrados había dicho: "`No juréis en ninguna manera.
Pero sea vuestro hablar: Sí, sí; no, no; porque lo que es más de esto, procede del mal.`"
Entonces ellos le dijeron: "`Debes obedecer al juez y él te ordena jurar.`"
Ella objetó: "`Yo obedeceré al juez, pero si debo jurar, haré algo injusto,
porque el Justo (Cristo) dijo:
'`No juréis en ninguna manera`'.`" Entonces le preguntaron si ella
reconocía al Cristo que había muerto en Jerusalén. Ella respondió:
"`Nosotras reconocemos al mismo Cristo y a ningún otro; Él es el mismo ayer,
hoy y por los siglos.`"
A continuación le preguntaron,
qué haría en Jerusalén. Ella respondió que no sabía que debía ir ahí,
pero que había intentado ir a Alejandría. "`¿A hacer qué?,`" le preguntaron ellos.
La respuesta de ella fue: "`La voluntad de Dios; y si el Señor abriera mi boca,
llamaría a la gente al arrepentimiento, les declararía el día del Señor,
y dirigiría sus mentes de las tinieblas a la luz.`"
También le preguntaron si ella había visto al Señor; y ella respondió:
"`Dios es espíritu, y Él es discernido espiritualmente.`"

Ahora bien,
aunque de las respuestas de estas mujeres muy poco podía ser tomado para culparlas,
las mantuvieron encerradas, lo que pareció afligir al cónsul inglés,
pues llegó donde ellas con lágrimas en sus ojos y les dijo,
que estaba tan dolido por ellas como por su propia carne.
Pues parece que él había recibido algo por entregarlas,
lo que voluntariamente habría devuelto,
si de ese modo hubiera podido obtener su libertad.
Sin embargo, un temor servil lo había poseído y nunca tuvo paz mientras vivió.

Algunos días después de esto, llegaron un magistrado, dos frailes,
el hombre con la vara negra, un escriba y el guarda de la inquisición para interrogarlas.
Ellos les pidieron nuevamente que juraran, pero respondieron como antes,
que Cristo había dicho: "`No juraréis en ninguna manera`";
y que el apóstol Santiago había encargado lo mismo.
Entonces el magistrado les preguntó si dirían la verdad, y ellas dijeron:
"`Sí.`" En seguida les preguntó si creían en el credo,
a lo que ellas dijeron que sí creían en Dios, y en Jesucristo,
y que había nacido de la virgen María y sufrido en Jerusalén bajo Poncio Pilatos,
que se había levantado de los muertos al tercer día y ascendido a Su Padre,
y que vendría a juzgar tanto a los vivos como a los muertos.
Les preguntó además, cómo creían en la resurrección, y ellas respondieron,
que creían que los justos y los injustos se levantarían, conforme a las Escrituras.
Lo siguiente que preguntó fue: "`¿Creen ustedes en los santos y les oran a ellos?`"
Su respuesta fue: "`Nosotras creemos en la comunión de los santos,
pero no les oramos a ellos, sino sólo a Dios en el nombre de Jesús.`"

Su siguiente pregunta fue, si ellas creían en la iglesia Católica, y ellas respondieron,
que ellas creían en la verdadera iglesia de Cristo,
"`pero la palabra católica,`" dijeron, "`no la hemos leído en las Escrituras.`"
También les preguntó si ellas creían en el purgatorio.
"`No, sino en el cielo y el infierno,`" le respondieron.
Entonces uno de los frailes, que era inglés dijo,
que a ellos se les mandaba a orar por los muertos,
y puesto que los que estaban en el cielo no tenían necesidad,
y para los que estaban en el infierno no había redención,
entonces debía haber un purgatorio.
Entonces él les preguntó, si ellas creían en el santo sacramento, a lo que respondieron,
que nunca habían leído la palabra sacramento en las Escrituras.
El fraile replicó: "`Donde ustedes leen en sus biblias santificación,
en las nuestras es sacramento.`"
Él dijo que el santo sacramento de ellos era el pan y el vino,
que ellos convertían en carne y sangre de Cristo, por virtud de Cristo.
"`Entonces,`" dijeron las mujeres, "`ustedes obran milagros,
pues la virtud de Cristo es la misma que era cuando Él convirtió
el agua en vino en las bodas de Caná.`" El fraile dijo:
"`Si nosotros no comemos la carne y bebemos la sangre del Hijo de Dios,
no tenemos vida en nosotros.`"
Ellas respondieron: "`La carne y la sangre de Cristo son espirituales,
y nosotras nos alimentamos de ello diariamente,
porque lo que ha sido engendrado de Dios en nosotras,
no puede vivir sin comida espiritual,
más de lo que pueden hacerlo nuestros cuerpos temporales sin comida temporal.`"
Entonces dijo: "`Ustedes nunca oyen misa.`"
"`Pero,`" dijeron ellas, "`nosotras oímos la voz de Cristo,
el único que tiene palabras de vida eterna y que es suficiente para nosotras.`"
Él replicó: "`Ustedes son herejes y paganas,`" a lo que ellas respondieron:
"`Herejes son los que viven en pecado y maldad, y paganos los que no conocen a Dios.`"

Luego se les preguntó quién era la cabeza de la iglesia de ellas, a lo que respondieron:
"`Cristo.`"
Además se les preguntó qué era George Fox, ellas dijeron: "`Él es un ministro de Cristo.`"
Al ser interrogadas si él las había enviado, la respuesta de ellas fue:
"`No. El Señor nos movió a venir.`"
Entonces el fraile dijo: "`Ustedes están engañadas y no tienen la verdadera fe,
aunque tengan todas las virtudes.`"
Ellas replicaron: "`La fe es el fundamento del que proceden las virtudes.`"
Después se les dijo que si tomaban el santo sacramento podrían obtener su libertad,
de lo contrario, el papa no las dejaría ir ni por un millón de piezas de oro,
sino que perderían sus almas y sus cuerpos también. A esto ellas dijeron:
"`El Señor ha provisto para nuestras almas,
y nuestros cuerpos son libremente entregados para servirle a Él.`"
Luego se les preguntó si no creían que el matrimonio era un sacramento,
y ellas respondieron que era una ordenanza de Dios.
También se les preguntó si creían que los hombres podían perdonar pecados,
y la respuesta de ellas fue, que nadie podía perdonar pecados, sino sólo Dios.

Después de otro intercambio de palabras las mujeres preguntaron:
"`¿En qué les hemos hecho daño para que nos mantengan
prisioneras todos los días de nuestra vida?
Nuestra sangre inocente será requerida de sus manos.`"
El fraile dijo que él tomaría la sangre de ellas sobre sí mismo.
Ellas respondieron:
"`Llegará el momento en el que encontrarás que tienes
suficiente sobre ti mismo sin ella.`"
Entonces se les dijo que el papa era el vicario de Cristo,
y que lo que él hacía era para el bien de sus almas.
A esto ellas respondieron:
"`El Señor no ha encomendado la carga de nuestras almas al papa, ni a ustedes tampoco,
porque Él las ha tomado en posesión Suya.
¡Gloria sea a Su nombre por siempre!`"
Entonces se les dijo que debían ser obedientes.
Ellas contestaron que ellas eran obedientes al gobierno del Espíritu o luz de Cristo.
El fraile dijo: "`Nadie tiene la verdadera luz sino los católicos,
la luz que ustedes tienen es el espíritu del diablo.`"
Pero ellas dijeron:
"`¡Ay de aquellos que maldicen a Jesús! ¿Puede el
diablo dar poder sobre el pecado y la iniquidad?
Eso destruiría su reino.`"
"`Todos se ríen y se burlan de ustedes,`" dijo el fraile.
"`Pero,`" respondieron ellas, "`¿qué será de los burladores?`"
"`Eso no importa,`" dijo él,
"`ustedes se apresuran a predicar y no tienen la verdadera fe.`"
Ellas respondieron: "`La verdadera fe se sostiene en una consciencia pura,
vacía de ofensa hacia Dios y los hombres.
Todos tienen la verdadera fe que cree en Dios y en Jesucristo a quién Él ha enviado,
pero los que dicen que creen y no guardan Sus mandamientos, son mentirosos,
y la fe no está en ellos.`"

El fraile confesó que eso era cierto,
aunque las molestaba continuamente con amenazas para que se convirtieran.
Para este fin fueron encerradas en una habitación tan caliente,
que se dijo que era imposible que pudieran vivir mucho tiempo en ella.
Cuando se acostaban en la cama las picaban tantos mosquitos, que sus caras se hincharon,
como si se hubieran enfermado de viruela, por lo que muchos empezaron a temerles;
y el fraile le dijo a Sarah que él divisaba un espíritu malo en la cara de ella.

En otro momento que estaban siendo interrogadas,
les preguntaron cuántos de sus amigos habían salido
al ministerio y a qué partes del mundo.
Ellas respondieron lo que sabían,
y se les dijo que todos los que entraran en el territorio donde el papa tenía poder,
nunca regresaría. Pero ellas dijeron que el Señor era suficiente para ellos,
como lo había sido para los tres muchachos en el horno de fuego,
y que su confianza estaba en Dios.
Como Catherine estaba enferma, le preguntaron porque se veía así,
y si el espíritu de ella estaba débil.
Ella respondió: "`No, mi cuerpo está débil porque no he comido nada.`"
Al oír esto, el fraile le ofreció una licencia para que comiera carne,
porque estaban en la Cuaresma de ellos,
pero ella la rechazó y dijo que no podía comer nada.
Después se fue a la cama, y permaneció ahí noche y día por doce días seguidos,
ayunando y sudando, pues estaba muy afligida y su agonía era grande.

Después de permanecer diez días allí, llegaron donde ella dos frailes, el canciller,
el hombre con la vara negra, un médico y el guarda.
Uno de los frailes le ordenó a Sarah que saliera de la habitación,
y luego sacó de la cama la mano de Catherine, y dijo:
"`¿Es tan grande el demonio en ti que no puedes hablar?`"
A lo que ella respondió: "`Apártate de mí hacedor de iniquidad,
el poder del Señor está sobre mí, ¿y tú Lo llamas demonio?`"
Entonces él tomó su crucifijo para golpearla en la boca,
y ella le preguntó que si esa era la cruz que había
crucificado a Pablo al mundo y el mundo a Pablo.
Este fraile ignorante dijo que lo era.
Pero ella negó eso y dijo:
"`El Señor me ha hecho testigo para Él contra todos los hacedores de iniquidad.`"
Él entonces le ordenó que obedeciera y quiso golpearla, a lo que ella dijo:
"`¿Me vas a golpear?`"
Al decir él que sí lo haría, ella añadió:
"`Entonces estás fuera de la doctrina de los apóstoles,
porque ellos nunca golpearon a nadie.
Niego que seas uno de los enviados en el nombre del Señor.`" A esto él le respondió,
que él le había llevado un médico por caridad, y ella dijo:
"`El Señor es mi médico y salud salvadora.`"

El fraile, cada vez más enojado dijo, que sería azotada,
descuartizada y quemada esa noche en Malta,
y su amiga también. Pero ella le dijo modestamente que no tenía temor,
porque el Señor estaba a su lado, y que él no tenía poder sino el que había recibido,
y que si no usaba su poder para el mismo fin para el que el Señor se lo había dado,
Él lo juzgaría. Ante estas palabras todos quedaron mudos y se marcharon.
Luego el fraile se dirigió a Sarah y le dijo que Catherine
lo había llamado hacedor de iniquidad.
"`¿Lo hizo?,`" dijo Sarah,
"`¿estás libre de pecado?.`" A lo que él respondió que sí. "`Entonces,`" contestó Sarah,
"`ella te ha agraviado.`"

A última hora de la tarde,
algo se proclamó en la puerta de la prisión con el golpe de un tambor,
y a primera hora de la mañana algunos regresaron con un tambor y armas.
A mí me parece que eso fue hecho con el propósito de atemorizar a estas pobres mujeres,
y hacerlas creer que serían ejecutadas, pues, en realidad, no esperaban algo diferente,
ya que por varias semanas habían creído que serían llevadas a la hoguera.
Pero ellas estaban plenamente entregadas y rendidas
a lo que el Señor se complaciera en permitir.
Entre tanto, como Catherine continuaba enferma, el fraile regresó con el médico,
pero ella le dijo que no podía tomar nada a menos que sintiera la libertad.
Entonces él dijo que ellas nunca saldrían de esa habitación mientras vivieran,
y pretendiendo ser amable con ellas añadió:
"`Ustedes pueden agradecerle a Dios y a mí que sus condiciones no son peores,
porque pudieron haber sido peores.`"
Entonces respondieron, que si ellas hubieran muerto,
habrían muerto tan inocentes como cualquier siervo del Señor. El fraile,
volviéndose a Sarah,
le pidió que se fijara en el tormento que sufriría Catherine a la hora de la muerte,
diciendo que miles de demonios vendrían a llevarse su alma al infierno.
Pero Sarah le dijo que ella no le temía a tal cosa.
Él le preguntó a Catherine si no creía correcto que
los ancianos de la iglesia oraran por los enfermos.
Ella dijo: "`Sí, cuando son movidos por el Espíritu del Señor.`" Entonces,
él cayó sobre sus rodillas y comenzó a aullar y a
desear que cayeran sobre él toda clase de males,
si no tenía la fe verdadera.
Entre tanto, el médico estaba enfurecido porque ella no se había inclinado ante él.

Mientras Catherine estaba enferma, Sarah no estaba exenta de gran aflicción,
pues le dolía ver a su querida compañera tan enferma,
y ella fácilmente previó que si Catherine moría sus
propios sufrimientos serían más pesados.
Sin embargo, ella estaba rendida a la voluntad del Señor,
y no resentía en lo más mínimo que Catherine llegara al reposo eterno.
Pero con el tiempo Catherine empezó a recuperarse, y al tener hambre y comer,
se sintió renovada.
Pero la habitación donde estaban encerradas estaba tan excesivamente caliente,
que a menudo se veían obligadas a levantarse de la cama y recostarse
cerca del hueco de la puerta para recibir aire y tener aliento.
El calor era muy grande, porque no sólo venía de afuera,
sino también de adentro de la cárcel, y las afectó tanto que la piel se les resecó,
se les cayó el pelo y se desmayaban con frecuencia.
Sus aflicciones eran tan grandes, que cuando era de día deseaban la noche,
y cuando era de noche deseaban el día. Sí,
debido a la debilidad humana deseaban la muerte,
y comían su pan llorando y mezclaban su bebida con lágrimas.

Una vez,
que los frailes acudieron a verla con un médico diciéndole que era una obra de caridad,
Catherine les preguntó: "`¿Nos mantienen en esta habitación tan caliente para matarnos,
y luego nos traen un doctor para mantenernos más tiempo vivas?`"
A esto el fraile dijo que el inquisidor perdería la cabeza si él las sacaba de ahí,
y que era mejor mantenerlas ahí que matarlas.
Entonces ellas le escribieron al inquisidor y le expusieron su inocencia,
y también dijeron, que si era la sangre de ellas lo que buscaban,
podían tomarla de cualquier otra forma,
así como también sofocándolas en esa habitación caliente.
Pero esto enfureció tanto al inquisidor,
que mandó al fraile a quitarles sus plumas y tinteros,
(y ya les habían quitado sus biblias).
Ellas le preguntaron la razón por la que les eran quitados sus bienes; se les respondió:
"`Todo es nuestro y sus vidas también, si así lo deseamos.`"
Entonces ellas preguntaron, cómo habían perdido el derecho de sus vidas, y se les dijo:
"`Por traer libros y papeles.`"
Ellas replicaron, que si había algo en ellos que no fuera cierto,
que ellos podían escribir contra eso.
Pero el fraile dijo:
"`Nosotros no les escribimos a tontos y asnos que no saben el verdadero
latín.`" Además se les dijo que el inquisidor las quería separar,
porque Catherine estaba débil y debía ir a una habitación más fresca,
ero que SSarahdebía permanecer ahí. Entonces Catherine tomó a Sarah por el brazo y dijo:
"`El Señor nos ha unido y ¡ay de aquellos que nos separen!
Preferiría morir aquí con mi amiga, que separarme de ella.`"
Esto impresionó tanto al fraile que se fue y no regresó por cinco semanas,
y la puerta de esa habitación no fue abierta en todo ese tiempo.

Pasado ese tiempo, los frailes regresaron para separarlas,
pero Catherine estaba enferma y con un sarpullido de pies a cabeza.
Ellos enviaron a buscar un médico, y este les dijo que ellas debían tener aire,
o de lo contrario debían morir.
Esto le fue dicho al inquisidor y él ordenó que se abriera la puerta seis horas al día;
pero diez semanas después fueron separadas,
lo cual fue una aflicción tan gravosa para ellas,
que declararon que la muerte misma no les habría sido tan difícil.
Los frailes decían que ellas se corrompían una a la otra,
y que estando separadas se inclinarían y someterían. Pero estos hombres se vieron decepcionados,
porque las mujeres eran más fuertes después que antes,
al ser adaptadas por el Señor a cada condición. Antes de que fueran separadas,
los frailes les habían llevado un azote pequeño de
cuerdas de cáñamo y les preguntaron si deseaban tenerlo,
y les dijeron que los monjes los usaban para azotarse a sí mismos hasta sangrar.
Pero las mujeres dijeron que eso no podía alcanzar al diablo,
porque él se sentaba en el corazón. Luego los frailes dijeron:
"`Toda la gente de Malta está a favor de ustedes,
y si cambiaran y se hicieran Católicas todos las aceptarían.`" Pero ellas respondieron:
"`El Señor nos ha transformado en lo que no cambia.`"
Ellos dijeron: "`Todas nuestras mujeres santas están orando por ustedes,
y si se convierten serán honradas por todo el mundo.`"
Ellas replicaron: "`El mundo yace en maldad,
y nosotras hemos rechazado todo honor y toda gloria del mundo.`"
Los frailes añadieron: "`También serán honradas por Dios, pero si no,
serán odiadas por todos.`"
"`Esto,`" dijo una de las mujeres, "`es una muestra evidente de Quién somos siervas,
porque el siervo no es mayor que su Señor.`"

Un Primer día, los frailes llegaron y les ordenaron arrodillarse con ellos para orar.
Ellas expresaron que ellas sólo podían orar cuando eran movidas por el Señor. Entonces
los frailes les ordenaron una segunda vez y luego se arrodillaron al lado de la cama,
y oraron según su manera.
Tras hacerlo les dijeron a las mujeres:
"`Hemos probado sus espíritus y ahora sabemos de qué espíritu son.`"
Pero ellas les dijeron que no podían saber eso,
a menos que sus mentes se volvieran a la luz de Cristo en sus consciencias.
Entonces, el fraile inglés enfureciéndose les mostró su crucifijo y les ordenó mirarlo,
pero ellas le dijeron: "`El Señor dice:
No te harás imagen de ninguna cosa arriba en el cielo, o abajo en la tierra,
o en el agua debajo de la tierra.
No te inclinarás ante ellas ni las adorarás, porque yo el Señor tu Dios,
soy Dios celoso.`"
El fraile al ver a Sarah hablarle tan audazmente pidió los grilletes para encadenarla.
Entonces ella bajó la cabeza y le dijo: "`No sólo mis manos y pies,
sino también mi cuello por el testimonio de Jesús.`" El fraile aparentemente
apaciguado dijo que él les haría cualquier bien que pudiera,
porque vio que lo que ellas hicieron no había sido con malicia.
Los frailes con frecuencia les decían:
"`Si ustedes cedieran un poquito serían puestas en libertad, pero no quieren ceder nada,
sino estar contra todo.`"
A lo que ellas respondían, que harían cualquier cosa que obrara para la gloria de Dios.

Mientras estuvieron encarceladas ahí,
sucedió que la casa de la Inquisición fue construida nueva o reparada,
lo que tomó cerca de un año y medio.
Durante ese tiempo, algunas personas importantes fueron a ver la construcción,
lo que les dio oportunidad a estas mujeres de hablarles
y declarar la Verdad en el nombre del Señor.

Ahora bien,
aunque ellas eran amenazadas por los frailes por predicar la luz de Cristo tan audazmente,
no sólo los magistrados, sino también el señor inquisidor,
se empezaron a mostrar más moderados con ellas,
y dieron la orden de que se les dieran plumas,
tinta y papel para que escribieran a Inglaterra.
Algunos parecían inclinados a ponerlas en libertad,
pero los frailes trabajaban fuertemente contra eso,
pues habían trabajado cerca de tres cuartas parte del año para separarlas,
antes de conseguirlo.
Y cuando finalmente lo habían logrado,
le dijeron a Catherine que ellas nunca se volverían a ver las caras.

Mientras tanto, Catherine estaba enferma y casi no tenía apetito, y no quería comer nada,
sino lo que le fuera ofrecido por Sarah.
Y,
tras decírsele a uno de los frailes que ella necesitaba que alguien
le lavara la ropa y le preparara algo de comida caliente,
él mandó a buscar a Sarah para saber si ella lo haría por Catherine,
y Sarah dijo que sí lo haría. Por este medio oyeron
una de la otra todos los días por varias semanas.
Una vez un fraile le dijo a Catherine:
"`Tú puedes liberarte de tu miseria cuando quieras,
porque puedes hacerte Católica y tener la libertad de ir adonde quieras.`"
Ella le dijo: "`Así tendría un nombre de que vivía, cuando estaba muerta.
Ustedes ya tienen suficientes católicos,
y si se esforzaran por llevar a algunos de ellos a la luz en sus consciencias,
entonces temerían y no pecarían.`" Este fraile estaba tan ansioso,
que dijo que perdería uno de sus dedos si ella y Sarah se volvían Católicas.
Pero ella dijo: "`Babilonia es la ciudad que se construye con sangre,
pero Sión es redimida con juicio.`"

Se emplearon muchos medios para apartarlas de sus convicciones,
y en una ocasión trataron de poner persuadirla de que pusiera una pintura a la
cabecera de su cama como representación. Pero ella dijo con aborrecimiento:
"`¡Qué! ¿Crees que me hace falta un becerro para adorar?
¿Caminan ustedes por la regla de las Escrituras?`"
A lo que el fraile respondió: "`Sí, lo hacemos, pero también tenemos tradiciones.`"
Ella replicó:
"`Si sus tradiciones derogan o discrepan de los fundamentos de la doctrina de Cristo,
de los profetas y de los apóstoles,
las niego en el nombre del Señor.`" Pero él afirmó que no lo hacían. Entonces ella preguntó
qué regla tenían ellos para quemar a los que no podían unirse a ellos por causa de consciencia.
Él respondió: "`San Pablo lo hizo peor, porque él los entregaba al diablo,`" y añadió,
que ellos juzgaban condenados a todos los que no eran de su fe.
Entonces ella objetó varios de los ritos supersticiosos de la iglesia de Roma,
y también mencionó la prohibición del matrimonio, "`que,`" dijo ella,
"`es doctrina de demonios,
según lo dicho por el apóstol.`"

Al ser puesto en aprietos, él le dijo que San Pedro había sido el primer papa de Roma,
y que había edificado un altar ahí,
y que el papa era su sucesor y podía hacer lo que quisiera.
Pero ella refutó eso con buena razón. Él, entonces,
se jactó de la antigüedad de su iglesia,
pero ella expresó que la iglesia a la que ella pertenecía era aún más antigua:
"`Porque nuestra fe es desde el principio,`" dijo ella,
"`y Abel era de nuestra iglesia.`"
El fraile viéndose perdido y que ya no podía resistir a Catherine,
se fue adonde Sarah y habló con ella en los mismos términos,
y ella también le dijo que Abel era de su iglesia.
A lo que él dijo: "`Abel era Católico,`" y sobrepasándose dijo:
"`Y Caín y Judas también.`" A lo que Sarah respondió: "`Si eso es cierto,
entonces el diablo es Católico y yo no lo seré. No
me convertiré aunque me partas en pedazos.
Creo que el Señor me haría capaz de soportarlo.`"

En otro momento, el citado fraile, cuyo nombre era Malaquías,
volvió adonde Catherine y le dijo que si ella estaba dispuesta a ser Católica,
que debía decirlo, de otro modo,
la tratarían severamente y nunca más vería el rostro de Sarah,
sino que moriría sola y mil demonios se llevarían su alma al infierno.
Entonces ella le preguntó si él era el mensajero de Dios para ella.
Él respondió: "`Sí.`" "`¿Por qué?,`" preguntó ella, "`¿cuál es mi pecado,
o en qué he provocado al Señor para que me envíe semejante mensaje?`"
"`¿Es?,`" dijo el fraile: "`porque no quieres ser católica.`"
Después de lo cual ella dijo: "`Te rechazo a ti y también rechazo el mensaje,
y al espíritu que habla en ti,
porque el Señor nunca habló así.`" Él enfureciéndose le dijo que
le pondría un montón de cadenas donde no viera el sol ni la luna.
Ella dando a entender cuán rendida estaba dijo,
que él no podría separarla del amor de Dios que es en Cristo Jesús,
la pusiera donde la pusiera.
Y al agregar él que la entregaría al diablo, ella prosiguió:
"`No les temo a todos los demonios del infierno,
el Señor es mi guardián. Aunque tuvieras la Inquisición,
con todos los países de alrededor de tu lado, y yo estuviera sola, no les temo.
Y si fueran miles más, el Señor está a mi derecha;
y lo peor que pueden hacer es matar el cuerpo,
no pueden tocar mi vida más de lo que el diablo pudo tocar la de Job.`"

Entonces el fraile dijo que ella nunca saldría viva
de la habitación. A lo que ella valientemente respondió:
"`El Señor es suficiente para librarme, pero ya sea que lo quiera o no,
no abandonaré la Fuente viva para beber de cisternas rotas.
Y ustedes no tienen ninguna ley para retenernos aquí,
sino la ley que tuvo Acab para la viña de Nabot.`"
El fraile, maldiciéndose e invocando sus dioses salió corriendo,
y mientras tiraba de la puerta dijo: "`¡Quédate aquí, miembro del diablo!`"
Y ella dijo: "`Los miembros del diablo hacen las obras del diablo;
y los ayes y plagas del Señor caerán sobre ellos por eso.`"

Luego, el fraile fue y le contó al inquisidor de esto, y el inquisidor se rio de él,
y antes de que volviera,
Catherine había sido sacada de esa habitación. Cuando fue adonde ella,
llevó con él a uno de los hombres del inquisidor y dos buenas gallinas,
y dijo que el señor inquisidor se las había enviado en amor a ella.
Ella respondió que recibía su amor,
pero no se mostró muy dispuesta a aceptar las gallinas,
dando a entender que estaba dispuesta a pagar por ellas,
pues no quería ser carga de nadie mientras tuviera su propio dinero.
El fraile, quien al parecer quería que pusieran su dinero a sus pies,
dijo que ellas no debían contar nada como propio,
porque en los tiempos primitivos los cristianos vendían
sus posesiones y ponían el dinero a los pies de los apóstoles.
Además dijo: "`No te faltará nada, aunque gastemos mil coronas.
Pero eres orgullosa,
porque no quieres coger las gallinas que el inquisidor te envió por caridad.`"
Entonces Catherine preguntó: "`¿Qué clase de caridad es esta,
dado que me mantiene prisionera?`"
Él respondió que era por el bien de sus almas que él las mantenía prisioneras; y añadió:
"`Si no hubieran ido a predicar, habrían podido ir donde quisieran.`"
Ella respondió: "`Nuestras almas están fuera del alcance del inquisidor.
Pero, ¿por qué se extiende tu amor hacia nosotras más que a tu propia gente?
Pues ellos cometen toda forma de pecados de los que no puedes acusarnos.
¿Por qué no los metes en la casa de la Inquisición y les mandas que se conviertan?`"

Entonces él le dijo: "`Tú no tienes la verdadera fe`";
y mostrándole su crucifijo le preguntó si ella pensaba que él lo adoraba.
Ella le preguntó:
"`¿Qué haces entonces con él?`" Y él respondió que era una
representación. Ella replicó que eso no representaba a Cristo,
pues Él era la imagen expresa de la gloria de Su Padre, que es luz y vida.
"`Pero,`" continuó ella, "`si puedes poner vida en cualquiera de tus imágenes,
entonces tráela y muéstramela.
¿Qué representación tenía Daniel en el foso de los leones,
o Jonás en el vientre de la ballena?
Ellos clamaron al Señor y Él los libró.`" El fraile,
que no podía soportar oírla hablar tanto contra los ídolos,
dijo que ella hablaba como un loca, y agregó: "`Te entregaré al diablo.`"
Ella sin temor a eso, dijo: "`Entrega lo tuyo,
yo soy del Señor.`" Entonces él se puso de pie y dijo:
"`Haré contigo lo que los apóstoles hicieron con Ananías y Safira.`"
Entonces ella, poniéndose también de pie, dijo: "`Te rechazo en el nombre del Señor,
el Dios vivo; tú no tienes poder sobre mí.`"

El fraile se fue con las gallinas adonde Sarah y le dijo que Catherine estaba enferma,
y que el señor inquisidor había mandado dos gallinas,
y que Catherine estaría encantada de comer un trozo si ella preparaba una en ese momento,
y la otra el día siguiente.
Sarah, que no era menos prudente y cautelosa que Catherine,
y no estaba dispuesta a recibir ese regalo antes de saber lo que podría ser conveniente,
le respondió lo mismo que Catherine.
Entonces, llevándose de nuevo las gallinas dijo:
"`Ustedes desean fervientemente ser quemadas,
porque así le harían creer al mundo que aman tanto a Dios como para sufrir de esa manera.`"
Oyendo Catherine eso dijo: "`Yo no deseo ser quemada, pero si el Señor me llama a eso,
creo que Él me dará poder para padecerlo por Su Verdad,
y si cada cabello de mi cabeza fuera un cuerpo,
yo podría ofrecerlos todos por el testimonio de Jesús.`"

El fraile regresó después y le preguntó nuevamente a Catherine,
si ella no había sido inspirada por el Espíritu Santo a ser Católica
desde que había llegado a la casa de la Inquisición. Ella dijo:
"`No.`" Pero él arguyendo lo contrario dijo:
"`Tú eres de las que llaman al Espíritu de Dios, Espíritu del diablo.`"
"`No,`" respondieron ellas (que aunque estaban separadas podían oírse una a la otra),
"`el Espíritu de Dios en nosotras resiste al diablo,
y la inspiración del Espíritu Santo no se realiza en la voluntad del hombre,
ni en el tiempo del hombre, sino en la voluntad y tiempo de Dios.`"
Discutieron más acerca de este asunto, y luego,
pidiendo sus biblias que les habían quitado,
él les dijo que nunca las verían de nuevo porque eran falsas.

Así, a menudo eran molestadas y presionadas por los frailes,
que por lo general llegaban de dos en dos, aunque a veces solo uno.
Uno de ellos con frecuencia levantaba su mano para golpearlas, pero nunca lo hizo,
pues como ellas no se dejaban mover por el miedo, se avergonzaba,
y luego decía que ellas eran buenas mujeres y que les haría todo el bien que pudiera.
Como en efecto hacía, pues algunas veces trabajaba para ellas,
y decía que era por amor a Dios y que ellas debían agradecerle por eso.
A lo que ellas respondían: "`Los que hacen algo para Dios,
no buscan una recompensa del hombre.`"
En una ocasión esto lo enojó tanto,
que dijo que ellas eran las peores de todas las criaturas,
y que serían tratadas peor que los Turcos, Armenios y Luteranos.
A lo que una de ellas dijo: "`La vida pura siempre ha sido contada como lo peor,
y si sufrimos somos del Señor y podemos confiar en Él. Haz lo que quieras con nosotras,
no tememos ninguna mala noticia.
Estamos establecidas y cimentadas en la Verdad, y cuánto más nos persigan,
más fuertes nos haremos.`"
Ellas en verdad experimentaban esto, según lo indicaban en sus cartas,
aunque estuvieron separadas una de la otra un año.

Sucedió en una ocasión, que un inglés que vivía ahí,
habiendo oído que Sarah estaba en una habitación con una ventana que daba a la calle,
subió por la pared y le habló unas pocas palabras,
pero fue violentamente jalado y echado en prisión para ser juzgado por su vida.
Él era uno de los que ellos habían tomado de los Turcos,
y le habían hecho Católico romano.
Los frailes fueron donde ellas para saber si él les había llevado alguna carta.
Ellas dijeron: "`No.`" Catherine ni siquiera lo había visto, sin embargo,
les dijeron que era probable que lo ahorcaran.
Sarah le dio información a Catherine de esto escribiéndole una pocas líneas
(porque parece que en ese momento ya no podían oírse una a la otra),
y le dijo que ella pensaba que los frailes ingleses
eran los principales actores de este asunto.

Esto entristeció a Catherine y le escribió a Sarah de nuevo (porque
ellas tenían una forma privada de escribirse una a la otra).
En esta carta, después de su saludo,
le dijo a Sarah que podía estar segura de que los frailes eran los principales actores,
pero que ella creía que el Señor preservaría a ese pobre inglés por Su amor,
y que se sentía movida a buscar al Señor por él con lágrimas,
y que deseaba que ella le enviara algo él una vez al día, si el guarda lo llevaba.
También le dijo que se sentía embargada por el amor de Dios por el alma de ella,
y que su Amado era "`señalado entre diez mil,`" y
que no le temía al rostro de ningún hombre,
aunque podía sentir sus flechas.
Además,
le indicaba que tenía la expectativa del regreso de ellas sanas y salvas a Inglaterra.
Y en la conclusión de la carta,
le pidió a Sarah que tuviera cuidado de ser tentada con dinero.

Pero esta carta (por cuál medio, nunca lo supieron), llegó a manos del fraile inglés,
quien la tradujo al italiano y se la entregó al señor inquisidor.
Luego,
fue con el asistente del inquisidor donde Catherine y le mostró los dos documentos,
y le preguntó si ella podía leer el que estaba en inglés. "`Sí,`" dijo ella,
"`yo lo escribí.`" "`¡Ah, sí!,`" dijo él. "`Y,
¿qué es lo que dices de mí aquí?`" "`Nada más que lo que es cierto,`" replicó ella.
Entonces él dijo: "`¿Dónde está el papel que envió Sarah?
Entrégalo o de lo contrario buscaré en tu baúl y en cualquier otro lugar.`"
Ella indicándole que buscara donde quisiera, él le dijo:
"`Debes decirme quién te trajo tinta, o de lo contrario, serás encadenada al momento.`"
Ella le respondió que no había hecho más que lo que
era justo y correcto a los ojos de Dios,
y que lo que ella sufriera por esa razón, sería por la Verdad.
Luego él dijo: "`Por amor a Dios, dime qué escribió Sarah.`"
Ella le dijo algo de lo que había escrito, y que lo que había dicho era verdad.
"`Pero,`" respondió él,
"`tú dices que era probable que nosotros las tentáramos con dinero.`"

Entonces el asistente cogió la tinta de Catherine y la tiró, y se fueron;
y el pobre inglés fue liberado la mañana siguiente.
De ahí se fueron donde Sarah y le dijeron que Catherine
honestamente lo había confesado todo,
y que lo mejor sería que ella confesara también. Ellos la amenazaron con una soga,
que le quitarían la cama y el baúl, y el dinero también. A lo que Sarah dijo,
que era posible que ya no pudiera enviarle a Catherine nada más,
pero luego le preguntó al asistente, si él era un ministro de Cristo o un magistrado.
Que si era un magistrado, él podía tomar su dinero, pero que ella no se lo daría. Él,
enfureciéndose, dijo que ella estaba poseída, a lo que ella replicó: "`Si es así,
entonces es con el poder de una vida indestructible.`"

Así, de vez en cuando sufrían asalto tras asalto, y a veces sucedía también,
que los que llegaban a verlas eran golpeados en el corazón,
lo cual ofendía a los frailes.
Finalmente el dinero casi se les había acabado,
pues a veces lo habían utilizado para comer.
Los frailes les dijeron que ellas habrían podido guardar el dinero para otros servicios,
porque ellos las habrían mantenido mientras estuvieran prisioneras.
A esto ellas respondieron que no habrían podido guardar
el dinero y haber sido carga para otros.
Sucedió entonces que perdieron el apetito y comieron poco por tres o cuatro semanas,
hasta que finalmente se vieron obligadas a ayunar por varios días seguidos.
Esto hizo que los frailes dijeran que era imposible
que alguien viviera con tan poca comida como ellas.
Luego se les dijo que el señor inquisidor había dicho
que ellas podían tener lo que quisieran,
a lo que respondieron, que no estaban en sus propias voluntades ayunar,
sino que debían esperar a conocer la mente del Señor; lo que Él quería que hicieran.
Así continuaron debilitándose, especialmente Sarah,
que al comprender que su muerte estaba cerca,
se vistió como deseaba ser depositada en la tumba.
Ambas estaban tan débiles que no podían ponerse ni quitarse la ropa,
y eran incapaces de arreglar sus camas,
y aunque deseaban estar juntas en una misma habitación, los frailes no lo permitieron.
En esta condición concluyeron que era probable que murieran,
pero el cielo había dispuesto otra cosa.

Por ese entonces, Catherine, que estaba siendo ejercitada en súplica al Señor,
mientras oraba que le placiera a Él ponerle fin a la prueba
de ellas de la manera que le pareciera bien a Sus ojos,
creyó oír una voz que decía: "`No morirán.`" Ella tomó esto como una voz celestial,
y a partir de ese momento se sintieron refrescadas con la presencia viva del Señor,
para gran gozo y consuelo de ambas,
de modo que sintieron la libertad para comer de nuevo.
Entonces se les proporcionó buena comida,
pero aún tenían temor de comer algo que en algún sentido pudiera ser considerado impuro.
Por tanto, clamaron al Señor diciendo:
"`Preferimos morir que comer algo que esté contaminado o sea impuro.`"
Entonces Catherine entendió que se le había dicho de parte del Señor:
"`Puedes comer tan libremente,
como si hubieras trabajado por ello con tus propias manos.`"
Y Sarah, que a veces trabajaba para otros en la casa de la Inquisición,
fue persuadida de que se le había dicho por inspiración:
"`Tú comerás el fruto de tus manos, y serás bendecida.`"
Y así comieron, y por ocho o diez días obtuvieron todo lo que pidieron.

Pero un tiempo después de esto, fueron tan afligidas por falta de comida,
que esto les hizo más daño que el ayuno.
Sin embargo, al ser conservadas con vida, un fraile dijo:
"`El Señor las mantiene vivas mediante Su gran poder,
porque Él desea que sean Católicas.`"
A esto ellas respondieron: "`Un día será conocido que el Señor tenía otro fin en esto.`"
Pero los frailes les dijeron claramente que no había redención para ellas.
Después de lo cual ellas dijeron:
"`En el Señor hay misericordia y abundante redención,`" y les advirtieron
que tuvieran cuidado de no "`ser hallados luchando contra Dios.`"
Los frailes respondieron: "`Ustedes son unas insensatas.`"
"`Entonces lo somos,`" replicaron ellas, "`las insensatas del Señor;
y los tales son queridos y preciosos ante Sus ojos.`"
Entonces los frailes, mostrándoles sus coronillas afeitadas,
dijeron que ellos eran los insensatos del Señor, y señalando sus vestidos,
dijeron que ellos los usaban por amor a Dios para que el mundo se riera de ellos.

Por este tiempo uno de los frailes hizo lo que pudo para enviar a Catherine a Roma,
y al no conseguirlo, dijo que irían los dos.
Pero como esto tampoco surtió efecto,
el fraile fue enviado allí con un documento que contenía acusaciones contra Catherine.
Pero, Catherine, al enterarse del contenido de la carta,
le habló celosamente al escriba y pronunció ayes contra todas esas mentiras,
y lo desafió en el nombre del Señor. Antes de que el fraile
partiera le dijo a Sarah que Catherine era bruja,
y que ella sabía qué se hacía en otros lugares.
Dijo esto, porque una vez que le había dicho un montón de mentiras a Catherine,
ella le dijo que ella tenía un Testigo de Dios en ella que era fiel y verdadero,
y que ella le creía a ese Testigo más que a las palabras de él.

Después que se fue, llegó a verla el cónsul inglés,
y llevaba con él un dólar enviado por el capitán de un barco que había llegado de Plymouth.
Ella le dijo que recibía el amor de su compatriota, pero que no podía recibir su dinero.
Entonces él le pregunto qué haría ella si no tomaba el dinero, a lo que ella respondió:
"`El Señor es mi porción, y por tanto, no me hará falta ninguna cosa buena.
Nosotras estuvimos en tu casa cerca de quince semanas,
¿viste alguna causa de muerte o cautiverio en nosotras?`"
Y al responder él que no,
ella le indicó que en cierto sentido él había sido cómplice del encarcelamiento de ellas,
y que él no ignoraba la intención. "`Tú sabías,`" dijo ella,
"`que una habitación estaba preparada para nosotras en la Inquisición,
y si no hubiéramos sido mantenidas vivas por el gran poder Dios,
hace mucho tiempo que habríamos muerto.`"
Tratando de excusarse dijo: "`¿Cómo habría podido evitarlo?`"
Entonces ella le recordó lo que había sucedido en la casa de él mientras estuvieron ahí,
y cómo los habían llamado al arrepentimiento y los habían advertido.
A lo que él respondió: "`Sea como sea, les irá bien.`"
Luego ella le recordó que él había requerido una señal de
ellas que demostrara que eran siervas del Señor Dios,
y le preguntó si no era cierto lo que ellas le habían dicho:
"`Tú eres un condenado y eres culpable ante Dios, sin embargo, arrepiéntete,
si puedes encontrar lugar para ello.`"
Mientras ella le hablaba así,
al cónsul le temblaban los labios y se le estremecía todo el cuerpo,
por lo que apenas podía mantenerse en pie,
y aunque era un hombre muy apuesto y en la flor de su vida,
se veía como alguien que se estaba muriendo.
Esta era señal suficiente para toda la ciudad,
si la hubieran tenido debidamente en cuenta.

Como Catherine rechazó la moneda, el cónsul se fue adonde Sarah con el dinero,
pero ella también le dijo que no podía tomarla,
pero que si él tenía una carta para ellas, se sentiría libre de recibirla.
Él dijo que no tenía ninguna y le preguntó si necesitaba algo, a lo que ella respondió:
"`El Señor es mi Pastor, no me hace falta ninguna cosa buena; pero anhelo mi libertad.`"
Él, no queriendo desalentarla le dijo: "`La tendrás en un tiempo.`"
Pero él no vivió para verlo,
porque la siguiente vez que oyeron hablar de él estaba muerto.

Mientras el fraile estaba en Roma,
se les dijo que también iban a ser enviadas ahí. De hecho,
hubo una gran agitación al respecto,
pero parece que no pudieron ponerse de acuerdo en el asunto.
Mientras tanto, Catherine y Sarah permanecían separadas,
pues había cinco puertas entre ellas con barras y cerraduras.
Sin embargo, Sarah a veces encontraba una oportunidad,
fuera por descuido del guarda o porque era hecho a propósito,
para acercarse hasta donde podía ver a Catherine, y aunque los frailes las vigilaban,
ella a menudo llegaba a la puerta de Catherine por la noche.
Pero en una ocasión la descubrieron y la encerraron nuevamente, sin embargo,
no mucho tiempo después las puertas volvieron a quedar abiertas,
de modo que ellas se sentaban a la vista la una de la otra.

A veces, personas de varias naciones, eran llevadas como prisioneras a la Inquisición,
y los frailes y otros hombres importantes,
se esforzaban a su manera por hacerlos cristianos.
Y ellas, por su parte, a menudo mostraban los errores del papismo y declaraban la Verdad,
por la cual estaban dispuestas a sufrir la muerte, si les era requerida;
pero esto fue tomado muy mal.
Al fin sucedió que dos ingleses llegaron a la ciudad
y trataron de obtener la libertad de ellas,
pero fue en vano.
Sin embargo,
poco después los magistrados mandaron por ellas y les preguntaron
si estaban enfermas o si les hacía falta algo;
y al decirles que podían escribir a Inglaterra,
le ordenaron al escriba que les diera tinta y papel.

No mucho después llegaron un tal Francis Steward, capitán de barco,
y un fraile de Irlanda, y ambos se esforzaron mucho por obtener su liberación;
y sus amigos en Inglaterra no escatimaron en nada que pudiera procurarles la libertad.
Pero esta no estaba en poder de los magistrados,
pues el inquisidor dijo que él no podía ponerlas en libertad sin una orden del papa.
No obstante,
Catherine y Sarah fueron llevadas a la sala de la corte y el cónsul inglés les preguntó,
si ellas estaban dispuestas a regresar a Inglaterra.
Ellas dijeron: "`Sí, si es la voluntad de Dios.`"
El capitán del barco, que también estaba ahí,
les habló con lágrimas en los ojos y les contó lo que él había hecho a favor de ellas,
pero que había sido en vano.
"`Es el inquisidor,`" dijo él, "`quien no las dejará salir libres,
porque ustedes han predicado entre estas personas.`"
Ellas dijeron que ellas habían dado testimonio de la Verdad,
y que estaban dispuestas a sellarlo con su sangre.
Él respondió, que si ellas eran puestas en libertad,
él les daría los pasajes gratis y proveería para ellas.
Y ellas le respondieron que su amor era bien aceptado
por el Señor. También les ofreció dinero,
pero ellas rehusaron tomarlo.

Luego, ellas le hicieron un relato de su encarcelamiento y sufrimientos,
y que no podían cambiar sus convicciones religiosas
aunque fueran reducidas a cenizas o picadas en pedacitos.
El fraile acercándose dijo que ellas no trabajaban, pero esto no era cierto,
porque ellas tenían trabajo propio y trabajaban como podían. También
le dijeron que el trabajo y negocio de ellas estaba en Inglaterra.
Él confesando que eso era cierto,
dijo que ellas habían sufrido suficiente y por mucho tiempo,
y que deberían obtener su libertad en un corto tiempo,
pero que necesitaban una orden del papa.
Mientras tanto, al capitán le afligía no poder obtener la libertad de ellas,
y marchándose, oró que Dios las consolara.
Ellas le rogaron al Señor que lo bendijera y lo preservara para vida eterna,
y que nunca dejara que él se fuera sin una bendición de Él por su amor,
pues él había arriesgado su propia vida, al esforzarse por obtener la libertad de ellas.

Después que él se fue, se encontraron con un peor trato.
El inquisidor llegó y las miró con ira,
pues parece que la eliminación de sus vidas estaba de nuevo sobre la mesa,
y sus puertas fueron cerradas por muchas semanas.
Después de un tiempo, el inquisidor regresó a la torre donde ellas se sentaban,
y Sarah lo llamó y le pidió que les abrieran las puertas
para bajar el patio a lavar sus ropas.
Él entonces ordenó que las puertas fueran abiertas una vez a la semana,
y no mucho después eran abiertas todos los días. Ya que se había
dicho que ellas no podían ser liberadas sin permiso del papa,
Sarah le dijo: "`Si somos prisioneras del papa, apelamos al papa.
Envíanos, pues, a él.`" Pero los que tenían su domicilio en la Inquisición,
especialmente los frailes, eran enemigos mortales de ellas,
aunque las habrían alimentado a veces con lo mejor de sus provisiones,
y les habrían dado botellas enteras de vino, si ellas lo hubieran recibido.
Pero esto las molestaba tanto, que se negaban a comer y a beber con ellos,
al considerarlos sus feroces perseguidores.

Una vez llegaron dos o tres barcos ingleses al puerto, y el cónsul inglés al contarles,
dijo que había hecho todo lo que había podido por ellas,
pero que no las dejarían ir a menos que se convirtieran en católicas, y por tanto,
ellas todavía debían sufrir encarcelamiento.
Antes que Sarah supiera que estos barcos habían llegado,
ella los había visto durante la noche en un sueño,
y había oído una voz diciendo que ellas no podían irse todavía.
Cuando los barcos se fueron,
mandaron a buscar a las mujeres y les preguntaron si querían convertirse en católicas,
y ellas respondieron:
"`Nosotras somos verdaderas cristianas y hemos recibido el Espíritu de Cristo.`"
Uno de los magistrados les mostró la cruz,
y ellas le dijeron que ellas tomaban la cruz de Cristo cada día, la cual era,
el poder de Dios para crucificar el pecado y la iniquidad.
Sabiendo que había un fraile, quien, según les había dicho el capitán,
se había tomado grandes molestias por ellas,
y no viéndolo ahí (pues el que las favorecía secretamente
estaba ausente) les dijeron a los que estaban presentes:
"`Uno de sus padres nos ha prometido nuestra libertad`"; pero esto no sirvió de nada.
Sin embargo, ellas aceptaban la amabilidad de él,
y después le dijeron que él nunca tendría motivo para arrepentirse.

Una vez un fraile fue a donde ellas y les dijo:
"`Es la voluntad de Dios que ustedes sean mantenidas aquí,
o de lo contrario no podríamos retenerlas.`"
A lo que Catherine respondió: "`El Señor permite que los hombres malvados hagan maldades,
pero Él no quiere que ellos las hagan.
Él permitió que Herodes decapitara a Juan el Bautista, pero Él no quería que lo hiciera;
Él permitió que Esteban fuera apedreado y que Judas traicionada a Cristo,
pero Él no quería que ellos lo hicieran; porque si fuera así,
Él no los habría condenado por eso.`"
El fraile les preguntó: "`¿Somos nosotros entonces, hombres perversos?`"
Ella respondió: "`Los hombres perversos son los que obran maldad.`"
"`Pero,`" dijo él, "`ustedes no tienen la verdadera fe.`"
Y ella respondió: "`Por la fe estamos firmes y por el poder de Dios somos sostenidas.
¿Piensas que es por nuestro propio poder y santidad
que somos guardadas de una vana manera de vivir,
y del pecado y la maldad?`"
Entonces al decir él que era por el orgullo de ellas, Catherine le dijo:
"`Nosotras nos podemos gloriar en el Señor, pues éramos hijas de ira,
igual que los demás,
pero el Señor nos vivificó cuando estábamos muertas mediante la palabra viva de Su gracia,
y nos ha lavado, limpiado y santificado en alma y espíritu--en parte,
según nuestras medidas, y proseguimos hacia lo que es perfecto.`"
Él dijo: "`Ustedes son buenas mujeres,
pero aun así no hay redención para ustedes a menos que sean católicas.`"
En una ocasión los frailes les dijeron:
"`Ustedes pueden convertirse en católicas y conservar su propia religión,
y no será sabido a menos que sean llevadas delante de un juez.`"
A lo que ellas respondieron: "`¿Qué, y profesar un Cristo del que nos avergonzamos?`"

Algunos de los que iban a verlas las compadecían por no convertirse en católicas,
pero otros les mostraban su odio gritando que ellas debían ser quemadas, y vociferando:
__"`Fuoco, fuoco.`"__
(Fuego, fuego) Mientras permanecían separadas una de la otra,
Catherine a menudo se preocupaba mucho por Sarah y temía que la atraparan,
pues uno de los frailes solía acosarla con palabras aduladoras.
Pero ambas continuaron firmes,
y con frecuencia se sentían embargadas del gozo y consolación
que sentían del Señor. Catherine contó en una de sus cartas,
que una vez el espíritu de oración había estado sobre ella,
pero que había tenido miedo de hablarle al Señor por temor
a decir una palabra que no le agradara a Él. Y que entonces,
le había sido respondido de parte del Señor: "`No temas, hija de Sión,
pide lo que quieras y Yo te lo concederé; lo que tu corazón desee.`"
Pero Catherine no deseó nada del Señor sino lo que fuera para la gloria de Él,
ya fuera su libertad o cautiverio, vida o muerte;
y en esta rendición ella fue hallada acepta ante el Señor.

A veces ellas hablaban tan eficazmente a los que llegaban a verlas,
que no podían refutarlas, y eran obligados a confesar que Dios estaba con ellas.
Sin embargo, otros hacían un ruido horrible y gritaban:
"`Jesús María,`" y se alejaban corriendo como si hubieran sido golpeados por el temor.
La celda de Catherine estaba tan cerca de la calle
que podía ser escuchada por los que pasaban,
y en algunas ocasiones era movida a llamarlos al arrepentimiento
y a volverse a la luz con la que eran iluminados,
la cual los podía sacar de todos sus caminos y obras de maldad,
para servir al Dios vivo y verdadero en espíritu y en verdad.
Esto alcanzó a algunos de manera tal, que suspiraban y gemían y se quedaban a escucharla,
pero no podían hacerlo por mucho tiempo porque estaba estrictamente prohibido.
No obstante,
algunos de los que pasaban por ahí hacia sus '`casas de adoración`' eran tan perversos,
que lanzaban piedras a la ventana de Catherine y con frecuencia
hacían un ruido lastimero y aullaban como perros.
Así eran acosadas, tanto desde el exterior como desde el interior por los frailes,
quienes las amenazaban ferozmente por el atrevido
testimonio de ellas contra la idolatría. Una vez,
que ellos le mostraron a Sarah un cuadro de la virgen
María y de su bebé pintado en una pared,
y le pidieron que lo mirara, Sarah, para mostrar su celo contra la adoración a los ídolos,
zapateo con su pie y dijo: "`Malditas todas las imágenes,
todos los hacedores de imágenes y los que se postran para adorarlas.`"

Sucedió que unos barcos franceses y españoles llegaron a unirse
a los caballeros de Malta para pelear contra los turcos.
Sarah, al oír esto dijo: "`¡Dios está enojado!
No salgan para matarse unos a otros.
Cristo no vino para destruir la vida, sino para salvarla.`"
Ella le dijo esto a muchos que estaban persuadidos de obtener la victoria,
pero sucedió lo contrario, porque su flota fue golpeada por los turcos,
y regresaron con grandes daños.

En una ocasión, un fraile fue a ver a Catherine y le preguntó, por qué ella no trabajaba.
Entonces ella le preguntó: "`¿Qué trabajo haces tú?`" Él respondió: "`Yo escribo.`"
Entonces Catherine respondió: "`Yo también escribiré, si tú me traes pluma,
papel y tinta.`"
Él, que no estaba dispuesto a que ella escribiera le dijo:
"`Pablo trabajó cuando estaba en Roma,
y tejiendo tú podrías ganar unos tres medios peniques al día.`" Ella le dijo:
"`Si nosotras pudiéramos tener ese privilegio entre ustedes,
el que tuvo Pablo en Roma bajo el César (que era un príncipe pagano),
trabajaríamos y no seríamos carga para nadie.
Pues él vivió por dos años en su propia casa alquilada,
predicando el evangelio y la doctrina del Señor Jesucristo.`"

Ella también le preguntó, si él conocía la guerra santa de Dios.
"`Y si la conoces,`" dijo ella,
"`entonces no ignoras que nosotras no podemos estar sin
labor día y noche;`" esto detuvo la boca del fraile.
Además, era bien sabido que ellas no pasaban el tiempo ociosamente,
pues tejían medias para los que eran serviciales con ellas.
También hacían vestidos para los prisioneros pobres y remendaban sus propias ropas;
pero no estaban dispuestas a trabajar para los frailes.
Estos hombres a veces iban a ver a Catherine, se arrodillaban,
y querían que ella repitiera delante de ellos lo que ellas hablaban,
pero ella se rehusaba a hacerlo, aunque esto los enfurecía más.

Estos y otros hechos similares la afligían tanto, que una vez,
angustiada de espíritu clamó a Dios diciendo:
"`¡Mejor me fuera morir que vivir así!`" Pues al ser casi continuamente
obligada a testificar contra la idolatría y la superstición,
ella habría estado dispuesta a rendir su vida por el testimonio contra ella,
si le hubiera sido requerido.
Y cuando en una ocasión los frailes le dijeron que Sarah iba a ser llevada a Roma,
mientras que ella debía permanecer en Malta, se afligió tanto,
que con súplica le preguntó al Señor si Él no la consideraba digna de
ir a Roma también y ofrecer su vida ahí por el testimonio de Jesús,
porque si ella tenía la libertad de escoger,
prefería ir que regresar sin Sarah a Inglaterra.

En otro momento, cuando les fue dicho que sus Biblias eran falsas,
Catherine le preguntó al fraile que lo había dicho: "`¿Por qué son falsas?`"
Él respondió, porque los libros de los Macabeos no estaban en ellas.
Ella respondió, que aunque algo hiciera falta, el resto aún podía seguir siendo bueno,
pero que si algo era añadido, entonces la Biblia estaba corrompida.
Esto golpeó algunos agregados que ella había visto en las Biblias ahí. Luego él le preguntó
si ella no creía que todos debían inclinarse ante el nombre de Jesús,
al responder ella que sí, él dijo:
"`Jesús,`" y le pidió que se arrodillara o se inclinara.
Entonces ella le dijo,
que todo su corazón y su cuerpo estaban inclinados ante el nombre de Jesús,
pero que ella no se inclinaría por la voluntad de él. "`El
que se aparta de la iniquidad (continuó ella),
se inclina delante del nombre de Jesús, pero el que vive en pecado y maldad,
no se postra delante del Hijo de Dios.`"
Entonces él dijo que él y sus compañeros estaban en el mismo poder,
y que eran guiados por el mismo Espíritu que los apóstoles.
Esto hizo que ella le preguntara,
porqué entonces ellos abusaban de ese poder y usaban armas carnales.
Él respondió que ellos no lo hacían,
porque tanto su Inquisición como sus cadenas y grilletes eran espirituales.
Luego él le preguntó si ella no pensaba que todos
los que no eran de su persuasión estaban condenados.
Ella respondió: "`No, Cristo no nos ha enseñado así,
porque aquellos que hoy están en estado de condenación, si al Señor le place,
pueden ser llamados mañana a salir de ella.`"
Entonces él dijo: "`Nosotros pensamos que ustedes están condenadas,
y todos lo que no son de nuestra creencia.`"
A lo cual ella respondió: "`El juicio del hombre no nos hace daño.`"

A veces algunos llegaban a la prisión en sus días "`santos`"
y les preguntaban a las mujeres qué día era,
y ellas al no estar familiarizadas con esos santos respondían: "`No sabemos.`"
Cuando los otros les decían, que ese día era el día de tal o cual santo,
y que dicho santo las castigaría esa noche por no haber guardado su día, respondían:
"`Nosotras sabemos que los santos estaban en paz con nosotras,
y que por eso no les tememos.`"
En otra ocasión un fraile llegó y les dijo que faltaban diecisiete días para Navidad,
y que la virgen María había concebido ese día. Sobre lo cual Catherine hizo notar,
que eso en verdad era muy extraño,
que ella portara un niño sólo diecisiete días. Tales
y similares sucesos la afligían mucho,
cuando consideraba la gran oscuridad en la que estaban esas personas.
Y una vez, mientras clamaba al Señor en oración,
que parecía que todo el trabajo y la labor de ellas era infructuoso,
percibió esta respuesta: "`No te aflijas, aunque Israel no se reúna,
la Semilla de Malta se incrementará en multitud; eso que han sembrado no morirá,
sino que vivirá.`"

Después de que Catherine y Sarah habían estado encarceladas en Malta cerca de tres años,
llegó un hombre llamado Daniel Baker,
quien hizo lo que pudo para obtener la libertad de ellas,
y también fue a ver al inquisidor, pero todo fue en vano.
Porque parece que el inquisidor exigía que algunos comerciantes ingleses en Leghorn,
o en Messina, se comprometieran a pagar cuatro mil dólares^
footnote:[Moneda que circulaba en varios países de Europa,
diferente al dólar actual de Estados Unidos.]
para que ellas fueran liberadas, y nunca regresaran a esos lugares.
Pero ellas no estaban dispuestas a entrar en esos términos,
ya que no sabían lo que el Señor de un momento a otro podría requerir de ellas.
Daniel, al ver que no podía obtener la libertad de ellas de esa manera,
se ofreció a ser encarcelado en lugar de ellas, y como no se aceptó fue aún más allá,
y expresó que estaba dispuesto a dar su vida por la libertad de Catherine y Sarah,
si no había otro modo de que su libertad fuera comprada.
¡Gran amor, en verdad, del que son hallados muy pocos ejemplos!

Al oír ellas de esto, fueron tocadas con gran admiración. Mientras tanto,
Daniel Baker encontró la manera de que unas cartas les fueran entregadas,
y él mismo les escribió también,
tanto para consolarlas como para exhortarlas a la constancia.
Finalmente, también halló los medios para hablar con ellas; pues una vez,
mientras estaban en los portones de la prisión,
llegó ante ellas y las saludó con estas palabras:
"`Todo el cuerpo de los elegidos de Dios, queridas hermanas, reconoce sus testimonios.
Ustedes son un sabor dulce para el Señor y Su pueblo.`"
A lo que una de ellas respondió, que era una pena para ellas no poder ser más útiles.
Esto hizo que el corazón de él se derritiera con piedad y compasión,
considerando la maravillosa misericordia del Señor
al preservarlas sin desmayar en esa dura prueba.
Y ellos, viéndose unos a otros a la distancia a través de las rejas de hierro,
en ese momento fueron mutuamente refrescados.
Tiempo después ellas le escribieron y le manifestaron, con las más tiernas expresiones,
lo mucho que apreciaban su gran amor,
y también le enviaron cartas para sus amigos y familiares en Inglaterra.
Él no dejó de escribirles en respuesta durante su estancia,
que fue en la primera parte del año 1662; sin embargo,
se vio forzado a dejarlas en prisión ahí. Pero el momento de su rescate se acercaba,
el cual fue llevado a cabo por instancias de George Fox y Gilbert Latey,
al escribirle al señor Aubigny.

Antes de que Daniel Baker llegara a Malta,
se les había dicho a ellas que si se convertían al catolicismo podrían vivir en Malta.
A lo que ellas respondieron, que ellas eran verdaderas Católicas.^
footnote:[La palabra Católico significa "`universal o general,`" y originalmente
fue usada para referirse a la iglesia universal o mundial de Cristo.
A lo largo de los siglos,
el término lentamente se convirtió en sinónimo de la iglesia
de Roma (o papista).]
Uno de los magistrados les dijo,
que si no se hacían católicas,
tendrían que sufrir un largo encarcelamiento por orden del papa, (sin embargo,
no era cierto que tal orden existiera).
También se les dijo, que si besaban la cruz serían liberadas,
y entonces podrían estar en la casa del cónsul inglés hasta
que se ofreciera una oportunidad de ser llevadas a Inglaterra.
Entre tanto,
ellas habían oído que el papa había dado la orden de que fueran llevadas
a Inglaterra sin causarles ningún daño. Pero sea como fuere,
ellas fueron guardadas en contentamiento,
y resueltamente dijeron que no besarían la cruz, ni comprarían su libertad a ese precio.

Parece que el cónsul pretendía obtener alguna ventaja
monetaria por la liberación de ellas,
porque les dijo que el inquisidor había dicho,
que si alguien ofrecía garantías de tres o cuatro
mil dólares a pagar si ellas volvían alguna vez,
serían puestas en libertad.
Esto también se lo dijo a Daniel Baker, y añadió,
que si nadie se comprometía como garante debían morir en prisión,
y que esa era la orden del papa.
Después de la partida de Daniel Baker,
se envió un mensaje a algunos comerciantes ingleses con respecto a tal compromiso,
pero ninguno pareció dispuesto a aceptarlo.
Y las prisioneras estaban tan lejos de desearlo, que hablaron contra esa idea.
Sin embargo, había muchos buscando obtener la libertad de ellas,
mostrándose a sí mismos dispuestos a comprometerse con lo que fuera razonable;
pero todos los esfuerzos fueron en vano.

Una vez ellas ayunaron tres días, y aunque era la estación fría,
se sentaron en el piso con muy poca ropa, sin medias ni zapatos,
y no tenían más que cenizas sobre sus cabezas.
Cuando los inquisidores vieron esto se maravillaron grandemente,
y Sarah comenzó a hablar con gran celo en contra de la superstición
e idolatría. Y cuando el tiempo de su ayunó acabó,
Catherine compuso lo siguiente:

[verse]
____
Himno a Dios

¡Toda alabanza a Aquel que no me ha dejado,
ni de Su mente me ha sacado,
ni Su misericordia de mí ha cerrado,
hasta donde he hallado!

¡Infinita gloria, loor y alabanzas,
sean dadas a Su nombre,
Quien ha dado a conocer en nuestras jornadas,
su fuerza y noble renombre!

¡Oh, nadie es al Cordero semejante,
del que resplandece brillante Su belleza!
¡Oh, que Su santo nombre se exalte,
Su majestad y fuerza!

¡Al único Dios mi alma alaba,
a la fuente pura y clara,
cuya corriente cristalina el exterior alcanza,
y lejos y cerca lava!

¡Los manantiales de eternidad,
muy puros y dulces son,
brotan sin cesar,
para a mi novio encontrar!

¡Mi dulce y querido Amado,
Su voz es para mí,
más que toda la gloria del mundo,
o que los tesoros que pueda descubrir!

¡Él es la gloria de mi vida,
mi gozo y mi placer.
Dentro del seno de Su amor,
me cercó de día y hasta el anochecer!

¡Él me preserva limpia y pura,
dentro de Su habitación,
donde yo con Él estoy segura,
y salva de toda equivocación!

¡Qué mi alma te alabe Señor!
¡Qué te alabe con gozo y paz!
¡Qué mi espíritu y mi mente día y noche,
te alaben sin cesar!

¡Oh, magnifiquen Su majestad,
Su fama y renombre,
Cuya morada es alta en Sión,
la gloria de Su corona!

¡Oh, alabanzas, alabanzas a nuestro Dios!
¡Canten alabanzas a nuestro Rey!
¡Oh, enseñen a la gente en el extranjero,
Sus alabanzas cantar!

¡Una canción brillante de gloria a Sión,
una que muy claro brille.
Oh, manifiéstenla ante la visión,
de las naciones lejos y cerca!

¡Qué Dios tenga Su debida gloria,
Su honor y Su fama
Qué todos Sus santos canten de nuevo,
las alabanzas a Su nombre!
____

Después de que Catherine cantó tan gozosamente,
se fue al pozo del patio y tomó mucha agua a la vista de los prisioneros,
y Sarah también lo hizo; pues estaban muy sedientas.
Sarah, además, se lavó la cabeza con agua fría,
y los prisioneros les gritaban en su lengua:
"`Ustedes se matarán y se irán al infierno.`"
Pero ellas ni le temían a eso, ni se enfermaron,
y se convirtieron en una maravilla para los demás.

Alrededor de medio año después de la partida de Daniel Baker,
entró en el corazón de Catherine, que si ella hablaba con el inquisidor,
él les concedería la libertad, y no había pasado mucho tiempo después de eso,
cuando él acudió a la sala de la corte de la Inquisición. Al enterarse de su llegada,
ellas solicitaron hablar con él y les fue concedido, y al ser admitidas en su presencia,
le dijeron que ellas no habían agraviado ni defraudado a nadie, y que sin embargo,
habían sufrido inocentemente casi cuatro años por causa de la consciencia, etc.
Después de esto,
el inquisidor fue muy cortés con ellas y les prometió la libertad en pocos días,
diciéndoles que enviaría a buscar al cónsul y lo
haría comprometerse a pagar 500 dólares por ellas,
si alguna vez regresaban.
Y que en el caso de que el cónsul se negara,
enviaría un recado al papa en Roma pidiéndole permiso para ponerlas en libertad,
sin ninguna obligación.

No muchos días después, el inquisidor llegó con su teniente, el canciller y otros,
y después de un discurso,
les preguntó si estaban dispuestas a regresar a sus esposos e hijos,
si esa fuera la voluntad de Dios.
A lo cual respondieron, que era la intención de ellas hacerlo en la voluntad de Dios.
En seguida fueron liberadas,
y el inquisidor se despidió muy cortésmente de ellas y les deseó un próspero regreso
a su país. De igual manera hicieron los magistrados y los oficiales inferiores,
sin exigir un penique por honorarios o asistencia.
Sin embargo, en su propia libertad, ellas le dieron algo al guardián y a algunos pobres.

Puestas así en libertad,
se arrodillaron y oraron a Dios que no les tomara
en cuenta lo que ellos les habían hecho,
porque ellos no las conocían. Y luego fueron entregadas en manos del cónsul,
quien les dijo que él se había comprometido por ellas para que fueran liberadas,
pero ellas nunca pudieron encontrar que eso fuera cierto.
Catherine y Sarah estuvieron once semanas en la casa del cónsul,
antes de poder obtener un pasaje a Inglaterra.
Mientras tanto, Catherine,
estando bajo una gran preocupación debido a un juicio
que sentía que era inminente sobre la ciudad,
les escribió un documento a los gobernantes de Malta en el que decía,
que el 25 del mes llamado Agosto,
había venido sobre ella de parte del Señor escribirles en Su nombre lo siguiente:

[.embedded-content-document.letter]
--

Mi ira está encendida contra ustedes y Mi juicio está establecido entre ustedes,
debido a la dureza de sus corazones e incredulidad.
Yo, el Señor, que no deseo la muerte de ningún hombre,
sino que todos regresen a Mí y vivan,
he enviado a Mis siervas entre ustedes (contrario a su voluntad y sin
el conocimiento de ellas) para advertirles del mal que vendría sobre ustedes.
¡Porque todos los impíos serán llevados a juicio!
En verdad, Yo estableceré a Mi amado Hijo sobre Su trono,
y Él gobernará en Su regio poder y reinará en Su real majestad,
Cuyo derecho está sobre todo.
Él establecerá en todos los lugares Su propio gobierno espiritual,
un gobierno justo y una adoración pura en Espíritu y en Verdad.
¡Nada puede detener al Señor!
Si ustedes no oyen a Mis siervas que hablan Mis palabras,
a quienes han probado por casi cuatro años,
cuyas vidas han sido inofensivas e inmaculadas,
y han estado entre ustedes en inocencia pura, entonces,
Yo traeré sobre ustedes ay sobre ay, y juicio sobre juicio,
hasta que los vivos no puedan sepultar a los muertos.
Mi boca ha hablado esto y Mi celo lo hará,
y la mano de cada hombre estará sobre sus lomos por causa del dolor,
porque el día de la recompensa ha llegado.
Pero si oyen a Mis siervas que hablan en Mi nombre,
y se vuelven en sus mentes a la luz en sus consciencias que convence de todo mal,
y rechaza todos los pensamientos, palabras y actos del mal, entonces,
Yo derramaré mi Espíritu sobre ustedes,
y pronto serán curados de sus enfermedades y sanados de su dolor.

--

Esto y más escribió, y se lo entregó al cónsul para que se lo diera al '`gran maestre`'^
footnote:[El _gran maestre_ es la máxima autoridad de una orden,
con un poder casi absoluto, tanto en lo militar, como en lo político o lo religioso.]
y al resto de los gobernadores, pero el cónsul al no estar complacido con esto,
la amenazó con encarcelarla de nuevo.
Qué sucedió con el documento, no lo sé,
pero el 8 de Octubre hubo grandes truenos y relámpagos
que incendiaron y volaron una de las casas de pólvora,
aproximadamente a una milla de la ciudad, y otra casa de pólvora fue derribada.
En la ciudad, cinco casas se vinieron abajo,
la mayoría de las ventanas de vidrio de los palacios y otras casas se quebraron,
las puertas se despegaron de sus bisagras,
las paredes se rompieron y la ciudad entera fue terriblemente sacudida,
tanto que al ser medianoche, un lamento atravesaba toda la ciudad y las campanas sonaban.
Al pie de la cama donde Catherine y Sarah dormían,
había una ventana de vidrio que también se quebró,
pero ellas no recibieron ninguna herida,
aunque la casa se sacudió tanto que ellas estaban muy asustadas y temblando.
Sin embargo, tras estando entregadas al Señor para vivir o morir,
el temor pronto fue quitado de ellas y se convirtió en gozo en
el Señor. Cuando llegó la mañana el cónsul fue adonde ellas,
y estando quietas y en silencio, preguntó si habían muerto.
Mientras él aún hablaba, otros entraron contando lo que había sucedido en la ciudad,
y él les contó que incluso los barcos en el puerto habían sido dañados.
Entonces ellas dijeron: "`¡Un ay ha pasado, y he aquí viene otro rápidamente,
si ustedes no se arrepienten!`"

Algunos días después de esto, Sarah ayunó,
sentándose en el piso con ceniza sobre su cabeza, y con su cuello y hombros descubiertos,
y le habló al cónsul para que le pidiera al '`gran maestre`' que proclamara un ayuno,
e hiciera que el pueblo se reuniera a esperar en el Señor, con sus mentes vueltas a Él,
para que apartara Sus juicios de ellos, porque la hora de Sus juicios había llegado,
en la que la ramera pintada debía ser desnudada y recibir la copa de temblor
de la mano del Señor. El cónsul llevó este mensaje a los magistrados,
y los frailes dijeron que las mujeres tenían buenas intenciones.
Un tiempo después llegó el inquisidor y hablando con ellas les dijo:
"`La intención de ustedes es buena, pero el diablo las ha engañado.`"
Ellas le preguntaron si el diablo podía dar poder sobre el pecado, a lo que él dijo,
que el diablo podía transformarse en una imagen de luz.
Ellas asintieron a esto, sin embargo dijeron,
que él no podía esconderse de los hijos de luz,
aunque los que estaban en oscuridad no pudieran discernirlo.
Él no pudo soportar oír esto y se fue, y el cónsul, que estaba presente,
se afanó contra ellas para encerrarlas de nuevo, pero fue en vano.
Luego muchos murieron en el pueblo por una fiebre violenta,
pero no puedo decir si algún otro desastre siguió la predicción de ellas.^
footnote:[Es interesante señalar, que poco después de esta época,
Malta sufrió la peor epidemia de peste de la historia de la isla.
En diciembre de 1675 se produjo un brote de peste
bubónica que se prolongó hasta agosto de 1676,
y provocó aproximadamente 11.300 muertes;
alrededor de una sexta parte de la población de la isla.
La mayoría de las muertes se produjeron en las zonas urbanas, incluyendo la capital,
La Valeta, y las Tres Ciudades,
que tuvieron una tasa de mortalidad de alrededor del 41+++%+++. Bartholomeo dal Pozzo (1637-1722),
conocido historiador contemporáneo de la Orden de San Juan,
comenzó su descripción de este brote afirmando,
"`la venganza divina ordenó el castigo de la peste por nuestros pecados.`"]

Al fin, llegó una fragata del rey de Inglaterra llamada el Zafiro,
comandada por el capitán Samuel Titswel, quien acogió a Sarah y a Catherine,
junto con algunos caballeros de Malta.
Entre ellos estaba el hermano del inquisidor,
quien a menudo le hablaba al capitán para que a las mujeres
no les faltara nada de lo que había en el barco,
y a ellas les dijo que si regresaban a Malta no serían tan perseguidas.
Al capitán le dijo: "`Si ellas van al cielo de una manera y nosotros de otra,
todos nos encontraremos al final.`"
Pero ellas le respondieron que Cristo Jesús, la luz del mundo,
era el único camino al Padre.

Un tiempo después de haber partido de Malta, llegaron a Leghorn,
donde los comerciantes les mostraron gran amabilidad,
y les enviaron vino y otras cosas para que se refrescaran,
y también les ofrecieron dinero, pero ellas no quisieron aceptarlo.
De ahí llegaron a Tánger,
lugar que le pertenecía al rey de Inglaterra por
su matrimonio con la hija del rey de Portugal.
Este lugar estaba entonces sitiado por los moros, sin embargo,
Catherine y Sarah entraron al pueblo,
y muchos acudieron en masa a la casa donde ellas se alojaban,
porque exhortaban valientemente al pueblo a apartarse de la maldad.
También fueron a ver al gobernador,
quien fue cortés con ellas y tomó la amonestación amablemente,
y prometió seguir su consejo.
Él quiso darles dinero, pero ellas no lo tomaron, aunque sí aceptaron su amor,
porque él había ordenado que ninguno de la guarnición las maltratara,
ni de palabra ni de hecho, bajo pena de severo castigo.
Sin embargo,
parecía que los portugueses e irlandeses estaban
suficientemente dispuestos a hacerles daño.

Estando ellas inclinadas a salir y hablarles a los moros,
le pidieron al gobernador que las dejara ir,
pero él les dijo que ellas sólo podían esperar de esa gente salvaje,
una muerte cruel o prisiones para siempre.
Y aunque le manifestaron que ellas creían que el Señor las guardaría,
ya que estaban persuadidas de que Él les pedía ir a los moros,
el gobernador de manera amistosa les impidió ir.
Detenidas así, entendieron que el Señor había aceptado la buena voluntad de ellas,
y cuando volvieron a embarcarse (aunque en otro barco),
varios tomaron transporte con ellas por creer, que por causa de ellas,
tendrían una travesía segura.
El capitán y los demás que iban en el barco se comportaron muy cortésmente con ellas,
y aunque se toparon con tempestades, al final llegaron seguros a Inglaterra.

Catherine relató después, que mientras estaba en la Inquisición,
por muchos días seguidos había estado a la espera de ser quemadas en la hoguera.
Por ese tiempo vio en un sueño durante la noche,
una habitación grande y un gran fuego de leña en la chimenea,
y observó a alguien sentado en una silla junto al fuego, en forma de siervo,
a quien ella tomó como el Hijo del Dios eterno.
También vio a un niño varón muy amistoso y hermoso,
sentado en un sillón directamente sobre el fuego
(que no parecía tener más de nueve meses de edad,
y no tenía más ropa que un lino pequeño y fino alrededor de la parte superior),
y que el fuego ardía alrededor; sin embargo, el niño jugaba y estaba feliz.
Entonces ella quiso cogerlo por temor a que se quemara,
pero el que estaba sentado en la silla le pidió que lo dejara en paz.
Luego, al volverse vio a un ángel,
y el que estaba sentado en la silla finalmente le pidió que cogiera al niño,
lo cual hizo,
y vio que no había sufrido ningún daño. Al despertar le contó el sueño a Sarah,
y le pidió que no temiera, porque las huestes celestiales las seguían.

He recogido el relato de lo que les sucedió a estas
mujeres en Malta de varios documentos y cartas,
que no mucho después de su regreso a casa fueron publicados en forma impresa.
Y como en la publicación no se guardó el orden debido, y se mencionaron muchas cosas,
que para evitar la redundancia he dejado pasar,
puede que yo sin intención haya perdido en uno u otro caso,
el orden o la secuencia del tiempo,
pero aun así creo que los hechos no están distorsionados.
Ahora, para darle una idea al lector del ánimo de estas mujeres y de sus sufrimientos,
insertaré algunas de sus cartas.
Entre las que les escribieron a sus amigos en Inglaterra estaba la siguiente:

[.embedded-content-document.letter]
--

Oh, queridos y amados amigos, padres, ancianos y pilares de la casa espiritual de Dios,
y hermanos y hermanas en el Señor Jesucristo,
en la medida del amor y vida de nuestro Dios,
los saludamos a todos y los abrazamos en lo que es eterno.
Nos regocijamos grandemente y glorificamos el nombre de nuestro Padre celestial,
por habernos considerado dignas de participar de
la muerte y sufrimientos de Su bendito Hijo con ustedes.

Aunque somos las más pequeñas del rebaño de Dios,
somos del verdadero rebaño del que Cristo Jesús es el pastor.
Él ha tenido tan tierno cuidado sobre nosotras,
como ha tenido sobre todos los corderos que ha llamado en el día de Su poder.
Él nos ha llevado a través y sobre grandes aflicciones,
como a muchos otros de nuestros hermanos y sufrientes por Su nombre; en burlas, mofas,
escarnios, críticas, azotes, contradicciones, peligros en la tierra, peligros en el mar,
pruebas ardientes, crueles amenazas, aflicciones de corazón, dolores de alma,
calores y fríos, ayunos y vigilias, temores internos y luchas externas,
terribles tentaciones y persecuciones,
pavorosos encarcelamientos y bofetadas de Satanás. Sin embargo,
en todas estas pruebas el Señor ha sido muy misericordioso con nosotras,
y no se ha apartado, ni ha permitido que Su fidelidad nos falle,
sino que nos ha sostenido y nos ha guardado de desmayar en medio de nuestro apuro.

Nosotras no teníamos a nadie más ante quien hacer nuestro clamor,
sino ante el Señor únicamente; ni podíamos esperar una gota de misericordia,
favor o refrigerio,
sino lo que Él destilaba de Su presencia viva y obra por Su propia fuerza.
Porque cerca de un año estuvimos sentadas, una en una habitación y la otra en otra,
como búhos en el desierto y personas abandonadas en lugares solitarios.
Pero entonces,
disfrutábamos la presencia del Señor y contemplábamos el resplandor de Su gloria,
y los veíamos a ustedes, amigos queridos,
en la luz de Jesús. Contemplábamos su orden y la
firmeza de su fe y amor para con todos los santos,
y éramos refrescadas en todos los de corazón fiel;
y sentíamos el flujo de amor y vida que fluía de los corazones
de los que estaban completamente unidos a la fuente,
y nos hicimos sensibles al beneficio de sus oraciones.

¡Oh, las tristezas, los lamentos, las lágrimas que hemos experimentado!
Pero "`los que sembraron con lágrimas,
con regocijo segarán.`" La verdadera tristeza engendra verdadero gozo,
y la verdadera cruz trae verdadera corona.
Pues cuando abundaban nuestras tristezas, el amor de Dios sobreabundaba.
Cuánto más profunda era la tristeza, más grande era el gozo; cuánto más grande la cruz,
más pesada la corona.

Queridos amigos y hermanos, no se maravillen de que Israel no se haya reunido;
nuestro juicio queda en el Señor, y también nuestras obras.
No ha sido por falta de esfuerzo laborioso, ni de dolor,
ni de amor por las almas de ellos,
porque nos habríamos contentado con ser alimentadas con hierba del suelo,
si así hubiéramos tenido la libertad de compartir con ellos.
Porque de no ser por la gran oposición,
nos habrían seguido como pollitos tras la gallina; tanto grandes como pequeños. ¡Pero,
oh, los encrespados mares y las furiosas y espumosas olas;
los vientos tormentosos y las inundaciones:
las profundas aguas y las altas montañas y colinas; las duras piedras,
los caminos ásperos y las sendas tortuosas; los altos cedros, los fuertes robles,
las árboles sin fruto y corruptos que ponen obstáculos en el suelo,
y estorban para que la Semilla justa no sea sembrada,
ni las plantas nobles sean plantadas! ¡Oh,
ellos les cierran el reino a los sencillos de corazón
y esconden de los inocentes la llave del conocimiento;
no entran en el reino, ni se lo permiten a los que desean entrar!

En su lugar, incitan a los magistrados a desarrollar armas carnales,
con la intención de evitar que el Señor reciba Su herencia, y despojar a Su Hijo,
el heredero de todo, para que no tenga morada entre ellos,
ni una habitación cerca de ellos.
Pero Su luz pondrá al descubierto sus tinieblas,
y Su resplandor quemará todas sus abominaciones, y desfigurará su belleza,
manchará su gloria, su pompa y su orgullo,
para que eso perezca como los higos fuera de tiempo, caiga como la flor del campo,
y se marchite como la hierba sobre el terrado.
¡Oh, el vientre del infierno, las fauces de Satanás,
todo el misterio de la iniquidad está en apogeo,
y todas las formas de abominaciones que hacen desolación,
están donde no deben estar y son amparadas por una ley, contra la que nadie debe hablar,
ni caminar en contra, bajo pena de muerte!

¡Pero alabanzas a nuestro Dios, que nos llevó a declarar contra ello día a día! ¡Oh!
Los guías ciegos, los espíritus de seducción que hacen que la gente se equivoque,
que obligan a las personas a adorar a la bestia y su imagen,
a tener su marca en sus frentes y en sus manos,
a inclinarse ante cuadros y paredes pintadas,
a adorar las cosas de sus propias manos y caer ante lo que sus propios dedos han moldeado.
Ellos no les permiten mirar hacia Sión, bajo pena de muerte, ni caminar hacia Jerusalén,
bajo pena de ser quemados en la hoguera,
sino permanecer en Babel y creer lo que sea que digan o declaren ser la verdad.

¡Oh!
Los caminos, las adoraciones, las modas, formas, costumbres, tradiciones,
observaciones e imaginaciones que han atraído en sus oscuras adivinaciones,
para mantener a la pobre gente en ceguera e ignorancia,
para que perezcan por falta de conocimiento,
y sean corrompidos porque el camino de la Verdad no es dado a conocer entre ellos.
Todos ellos están en las muchas formas, y fuera del único camino verdadero y vivo.
De hecho, sus caminos son tantos y tan monstruosos, que son indescriptibles.
Sin embargo,
el Señor nuestro Dios ha encendido un fuego en medio
de ellos que consumirá todas las formas,
modas, costumbres y tradiciones de los hombres, y quemará los cardos, los espinos,
la cizaña, el rastrojo, los árboles infructuosos y los corruptos.
Marchitará todos los frutos, las obras y labores de los hombres malvados e impíos,
con la plaga de Su iracunda indignación,
y esparcirá a todos Sus enemigos con los torbellinos de Su disgusto.

--

Esta carta fue firmada por ambas, aunque es posible que Catherine fuera la escritora.
Ella también le escribió una carta de exhortación al inquisidor Católico en Malta,
y otra al fraile Malaquías. Entre las cartas que ella les escribió a su esposo e hijos,
cuento la siguiente como realmente digna de ser entregada a la posteridad:

[.embedded-content-document.letter]
--

Para las manos de John Evans, mi querido y precioso esposo, y a mis tiernos hijos,
quienes son más queridos y preciosos para mí que la niña de mis ojos.

Queridísimo y fiel esposo, amigo, y hermano, engendrado por mi Padre eterno,
de la Semilla inmortal del pacto de luz,
vida y bendición. Tengo unidad y comunión contigo día y noche,
para mi gran refrigerio y continuo consuelo.
¡Alabanzas, alabanzas sean dadas a nuestro Dios para siempre,
quien nos ha unido en lo que ni el mar ni la tierra pueden separar o dividir!

Mi querido corazón,
mi alma te saluda sinceramente a ti y a mis queridos y preciosos hijos,
quienes son queridos y preciosos en la luz del Señor,
para tu gozo infinito y mi eterno consuelo.
¡Gloria a nuestro Señor Dios eternamente, quien los ha llamado con llamamiento santo,
y ha hecho que Su belleza resplandezca sobre ustedes en el día de Su poder,
en el que está preparando Su tesoro y uniendo a Sus
fieles en el vínculo del amor y salvación eternos,
entre quienes Él los ha contado por Su gracia gratuita.
En esta, les suplico, queridos corazones, en el temor del Señor,
que permanezcan en sus medidas según la manifestación
de la revelación del Hijo de Dios en ustedes.
Mantengan diligente vigilancia sobre cada pensamiento, palabra y acto,
y dejen que sus mentes permanezcan continuamente en la luz,
donde descubrirán las trampas y cebos de Satanás, y serán preservados de sus trampas,
redes y pozos, para que no sean esclavizados por él a su antojo.

¡Oh, mi querido esposo e hijos,
cuán a menudo he derramado mi alma ante el Padre eterno por ustedes,
con ríos de lágrimas noche y día,
para que sean guardados puros y limpios ante los ojos de nuestro Dios,
incrementando sus talentos como vírgenes prudentes, teniendo aceite en sus vasijas,
con sus lámparas ardiendo, vestidos con la larga y blanca túnica de justicia,
listos para entrar a la recámara, cenar con el Cordero,
y ser alimentados en el banquete de manjares suculentos,
donde sus almas pueden ser nutridas, refrescadas, consoladas y satisfechas,
y nunca tener hambre de nuevo!

Mis queridos corazones, ustedes no carecen de enseñanza;
ustedes están en la tierra de bendición,
en la que fluye leche y miel entre los mayordomos fieles,
cuyas bocas están abiertas de par en par a la justicia,
para declarar los eternos misterios del reino perpetuo,
de las interminables alegrías y de la gloria eterna,
donde todo los dispuestos y obedientes entrarán y serán bendecidos para siempre.

Mis queridos corazones, las promesas del Señor son grandes,
y '`todas son sí y Amén`' para los que temen Su nombre.
Él consolará a los dolientes en Sión,
y hará que los abatidos se regocijen en Jerusalén a causa de las buenas nuevas.
Los que carguen la cruz con paciencia, llevarán la corona con gozo,
pues es a través de la longanimidad y paciente espera,
que se obtiene la corona de vida e inmortalidad.
El Señor ha ejercitado mi paciencia y me ha tratado hasta el extremo,
para Su alabanza y mi consuelo eterno;
Quien no ha dejado de proporcionarnos todo en Su propio y debido tiempo.
En realidad, nosotras somos testigos de que Él puede aderezar una mesa en el desierto,
tanto espiritual como temporal.
¡Oh, el infinito amor de nuestro Dios, quien es perpetua fuente de todo refrigerio vivo,
y cuyos arroyos cristalinos nunca dejan de correr hacia toda alma
sedienta que respira en pos de los manantiales de vida y salvación!

En nuestra más profunda aflicción,
cuando yo esperaba que cada respiración fuera la última, no podía, sin embargo,
desear no haber atravesado el mar,
porque sabía que había sido la voluntad de mi Padre eterno para probarme,
junto con mi querida y fiel amiga.
En todas las aflicciones y miserias, el Señor recordó la misericordia,
y no nos dejó ni nos abandonó, ni permitió que Su fidelidad nos fallara,
sino que hizo que las dulces gotas de Su misericordia destilaran sobre nosotras,
y que el resplandor de Su glorioso semblante brillara en nuestros corazones,
y nunca dejó de concedernos revelaciones y visiones.

¡Oh,
¿cómo puedo explicar la plenitud del amor de Dios hacia
nuestras almas?! ¡Ninguna lengua puede expresarlo,
ningún corazón puede concebirlo, ninguna mente puede comprenderlo! ¡Oh, el embeleso,
el arrebato, el glorioso y resplandeciente semblante de nuestro Señor Dios,
quien es nuestra plenitud en el vacío, nuestra fuerza en la debilidad,
nuestra salud en la enfermedad, nuestra vida en la muerte, nuestro gozo en la tristeza,
nuestra paz en la inquietud, nuestra alabanza en la pesadez,
nuestro poder en todas las necesidades! ¡Sólo Él es un Dios pleno para nosotras,
y para todos los que confían en Él! Él nos ha vaciado y purgado de nosotras mismas,
y nos ha edificado por completo sobre un fundamento seguro, la roca de los siglos,
Jesucristo, la Luz del mundo, en Él que ni los encrespados mares,
ni las embravecidas y espumosas olas, ni los vientos tormentosos, pueden movernos,
aunque golpeen con vehemencia.

¡Gloria, honor y alabanza sean dadas a nuestro Dios por siempre,
quien a partir de Sus tesoros eternos nos llena de Sus riquezas eternas
día a día! Él nutre nuestras almas con lo más selecto de Sus misericordias,
alimenta nuestros cuerpos con Su buena creación,
y alivia todas nuestras necesidades plenamente.
¡Alabanzas, alabanzas sean dadas sólo a Él, quien es nuestra porción eterna,
nuestra confianza y nuestro regocijo,
a quien servimos aceptablemente con reverencia y piadoso temor;
porque nuestro Dios es fuego consumidor!

Oh, mi querido esposo y mis preciosos hijos,
puede que sientan los flujos de amor y vida que fluyen
como un río hacia cada uno de ustedes,
desde un corazón que está completamente unido a la fuente.
Mis oraciones son por ustedes día y noche sin cesar,
suplicándole al Señor Dios de poder que derrame Sus tiernas misericordias sobre ustedes,
los guarde en Su temor puro, incremente su fe, los confirme en toda justicia,
y los fortalezca al creer en el nombre del Señor Dios Todopoderoso,
para que sean establecidos como el Monte de Sión, que jamás podrá ser conmovido.
Mantengan sus almas sin mancha del mundo,
y ámense fervientemente unos a otros con corazón puro.
Sírvanse unos a otros en amor, edifíquense unos a otros en lo Eterno,
sobrelleven los unos las cargas de los otros por el bien de la Semilla,
y cumplan así la ley de Dios.
Esta es la palabra del Señor para ustedes, mis amados.

Amados corazones, los encomiendo a las manos del Todopoderoso, quien habita en lo alto,
y a la Palabra de Su gracia en ustedes,
quien es capaz de edificarlos para vida eterna y perpetua salvación. Por mí,
quien soy tu amada y preciosa esposa y cónyuge, en el matrimonio del Cordero,
en el lecho sin mancilla,

[.signed-section-signature]
C+++.+++ E.

[.postscript]
====

Mi amada compañera de yugo en la obra de nuestro Dios, cariñosamente te saluda.
Saluda con cariño a nuestros preciosos amigos en todo lugar.
Creo que volveremos a ver sus rostros con alegría.`"

====

[.signed-section-context-close]
Escrito en la Inquisición en Malta, en el mes Once, de 1661.

--

[.offset]
La siguiente carta fue escrita por Sarah a su esposo, Henry Cheevers y a sus hijos.

[.embedded-content-document.letter]
--

Mi querido esposo, mi amor y mi vida están rendidos al servicio del Dios vivo,
y a la obediencia de Su llamado puro en la medida de la manifestación de Su amor, luz,
vida y Espíritu de Cristo Jesús, Su unigénito Hijo,
a quien Él ha hecho manifiesto en mí y en miles más mediante el resplandor de Su aparición,
para ponerle fin al pecado y a Satanás,
y sacar a la luz la inmortalidad a través de la predicación del evangelio eterno,
por medio del Espíritu de profecía,
que es derramado sobre los hijos e hijas del Dios vivo, según Su propósito;
para el cual Él me ha escogido, a mí que soy la más pequeña de todos.
Pero Dios, que es rico en misericordia,
por amor a Su propio nombre ha pasado por alto mis ofensas,
y me ha considerado digna de llevar testimonio de Su santo nombre,
ante los poderosos hombres de la tierra.
¡Oh, el amor del Señor a mi alma!
Mi lengua no puede expresar, ni ha entrado en el corazón del hombre concebir,
las cosas que Dios ha preparado para los que le temen.

Por tanto, mi alma respira anhelante a mi Dios por ti y por mis hijos de noche y de día,
para que sus almas sean unidas a la luz del Señor Jesús,
sean trasladadas del reino de Satanás al reino de Dios,
donde podemos disfrutarnos unos a otros en la vida eterna,
y donde ni el mar ni la tierra pueden separarnos.
En esta luz y vida los saludo, mi querido esposo y amados hijos,
deseando que abracen el amor de Dios,
al hacer que Su verdad se manifieste muy claramente entre ustedes.
De la que yo soy testigo, es decir,
de la fuente eterna que ha sido abierta por los mensajeros
de Cristo que les predican la palabra de Dios,
a tiempo y fuera de tiempo, indicándoles donde pueden encontrar a su Salvador,
para purgarlos y limpiarlos de sus pecados, y reconciliarlos con Su Padre,
y tener unidad con Él y con todos los santos en la luz,
y ser conciudadanos en el reino de gloria,
reposo y paz que Cristo ha comprado para los que lo aman y le obedecen.
¿Qué provecho tiene ganar el mundo entero, y perder sus almas?
Busquen primero el reino de Dios y Su justicia,
y todas las otras cosas les serán añadidas.
Porque la piedad es una gran ganancia,
pues tiene promesa de esta vida presente y de la venidera; la cual se cumple en mí,
que he gustado el amor infinito y las misericordia del Señor para con mi alma.

Y desde el movimiento del mismo amor y vida oro por ti,
mi querido esposo y mis queridos hijos.
Mi querido amor los saluda a todos; mis oraciones a Dios son por todos ustedes,
para que sus mentes sean unidas a la luz con la que son iluminados,
y yo pueda disfrutarlos en lo que es eterno, y tener comunión con ustedes en el Espíritu.
"`El que se une al Señor, un espíritu es con él,`" un corazón, una mente, un alma,
para servirle al Señor en un mismo consentimiento.
No puedo expresar por medio de la pluma o del papel el gran amor de Dios,
al cumplir Sus misericordiosas promesas para conmigo en el desierto,
tras haber sido puesta en prisión por la verdad de
Dios para permanecer allí todos los días de mi vida;
al ser examinada, probada, interrogada bajo pena de muerte,
entre los enemigos de Dios y Su verdad; al estar mi vida en peligro,
hasta que el Señor los sojuzgó y sometió mediante Su poderosa fuerza,
e hizo que nos alimentaran y quisieran darnos dinero y ropa; y sin embargo,
el Señor engalanó ricamente nuestra mesa en el desierto.
Se acerca el día del Señor en el que Él descubrirá toda obra de las tinieblas,
por muy secreta que sea;
porque la luz de Jesucristo la hará manifiesta en cada consciencia.
En efecto, el Señor arrancará todas las cubiertas que no sean de Su propio Espíritu.
El Dios de paz sea con todos ustedes.
Amén.

[.signed-section-closing]
Escrito en la prisión de la Inquisición por,

[.signed-section-signature]
Sarah Cheevers.

--

Tanto ella como Catherine escribieron varias otras cartas a sus esposos y familiares,
pero como gran parte de mi relato fue extraído de ellas, las paso por alto.
Sin embargo, por medio de estas que inserté,
uno puede ver que ellas no eran mujeres de temperamento lento,
sino inteligentes y alegres.

[.offset]
En una carta de Sarah a sus amigos en Irlanda, encontré estas palabras:

[.embedded-content-document.letter]
--

Mi vida está rendida al servicio del Señor. Ataduras, cadenas, cerrojos, hierros,
puertas dobles y la muerte misma,
es demasiado poco por el testimonio de Jesús y por la Palabra de Dios.
Por tanto, es un sacrificio razonable con tal que la Semilla sea reunida.
Los lazos y las aflicciones suceden en el evangelio de Cristo.
Los que quieran vivir piadosamente en Cristo Jesús, deben sufrir persecución.

--

[.offset]
Catherine escribe en una carta dirigida a Daniel Baker,

[.embedded-content-document.letter]
--

El tiempo es demasiado poco para que yo pueda revelar
la vigésima parte de los terribles pruebas.
Sin embargo, cada vez que fuimos llevadas a alguna prueba,
el Señor quitó todo temor de nosotras, multiplicó nuestras fuerzas,
y nos dio poder y osadía para defender la Verdad del Señor Jesús,
y sabiduría de palabras para tapar la boca de los detractores.
Pero entonces ellos decían, que nosotras no teníamos la verdadera fe,
pero que teníamos todas las virtudes.
Estimado hermano, ora por nosotras, para que no caigamos ni fallemos,
para que nuestros enemigos no tengan ninguna ventaja de gozarse y decir,
que nosotras servimos a un Dios que no puede servirnos,
y que invocamos a un Dios que no puede librarnos; como si nosotras fuéramos como ellos,
para invocar piedras, cuadros, paredes pintadas y cosas muertas, que no pueden oír,
ver ni hablar.
Te suplicamos que les cuentes a todos nuestros queridos amigos, padres y ancianos,
los pilares de nuestro edificio espiritual,
junto con el resto de nuestros hermanos Cristianos,
que deseamos sus oraciones porque tenemos necesidad de ellas.

--

[.offset]
Ellas concluyen esta carta con el siguiente poema:

[verse]
____
¡Cuán fuerte y poderoso es nuestro Rey,
para todos los que en Él creen!
Él los guarda de los que los quieren lazar,
y a la fuerza los quieren desgarrar.

En nosotros los que sufrimos por la Semilla,
nuestros corazones están heridos y sangran,
al ver la opresión y la crueldad,
de los hombre que niegan Tu Verdad.

En fuertes prisiones y profundas mazmorras
sólo a Dios clamamos y lloramos.
Nuestras penas nadie las puede aprender ni leer,
sino los que nuestro camino han de recorrer.

Pero Aquel cuya belleza brillante resplandece
El que vuelve las tinieblas en luz,
hace que los cedros se inclinen y los robles se doblen,
ante el que es enviado para el mismo fin.

Él es una fuente pura y clara,
Sus cristalinos arroyos corren lejos y cerca,
para limpiar a todo el que a Él se acerca,
Para ser sanado de su pecado.

Todos aquellos que pacientemente permanecen,
y nunca se desvían ni se descarrían,
el Señor los librará de toda
opresión, cautiverio y esclavitud.
____

Ellas compusieron varios otros, que cayeron en las manos de sus enemigos,
y le fueron dadas copias de estos al inquisidor.
Y ahora las dejo.
