== Los Sufrimientos de Catharine Evans y Sarah Cheevers

En el año de 1658, Catharine Evans y Sarah Cheevers,
habiendo sido persuadidas en sus mentes de viajar a Alejandría,
salieron de Inglaterra a Leghorn en Italia,
y tras pasar treinta y un días entre Plymouth y Leghorn,
finalmente llegaron a salvo a esa ciudad.
Ahí encontraron a algunos de sus compatriotas y amigos y se quedaron varios días,
repartiendo muchos libros cada vez que se ofrecía la ocasión. Ellas también
hablaron con personas de varios niveles sin ser molestadas por ninguno.
De ahí obtuvieron pasaje en un barco holandés con destino a Alejandría, o Scanderoon,
pero el dueño de la nave al estar en compañía con otro barco que iba para Malta,
fue también ahí, aunque no tenía negocios en ese lugar.
Antes de que llegaran a Malta, Catharine cayó en tal angustia de mente que exclamó:
"`¡Oh, tenemos una terrible copa que tomar en ese lugar!`"
Al entrar en el puerto y estando en la cubierta del barco,
mirando a la gente que estaba parada en los muros, ella dijo en su corazón:
"`¿Nos destruirán? Si nos rendimos al Señor,
Él es suficiente para librarnos de sus manos, pero si desobedecemos a nuestro Dios,
ninguno de estos podrá librarnos de Su mano.`"
Y así todo temor al hombre fue quitado de ellas.

Al día siguiente, el Primer-día de la semana,
fueron a la orilla donde el cónsul Inglés las conoció
y les preguntó para qué habían venido.
Ellas respondieron lo que pensaron que era conveniente y le dieron algunos libros.
Entonces él les dijo que en ese lugar estaba la inquisición;
amablemente las invitó a su casa y les dijo que todo lo que él
tenía estaba al servicio de ellas mientras estuvieran ahí. Ellas
aceptando la invitación fueron y muchos llegaron a verlas,
a quienes ellas llamaron al arrepentimiento, de modo que varios se mostraron atentos.
Cerca de la noche regresaron al barco y al día siguiente fueron de nuevo a la ciudad,
y yendo donde el gobernador,
él les dijo que tenía una hermana en el convento que deseaba verlas.
Entonces fueron al convento y hablaron con las monjas y les dieron libros.
Uno de los sacerdotes, quien las llevó a la capilla,
quería que se inclinaran frente al altar mayor, pero ellas se rehusaron,
afligiéndose por la idolatría que ahí se cometía. Después de eso
regresaron a la casa del cónsul donde se quedaron varias semanas.

En una ocasión, durante ese tiempo,
fueron a uno de los lugares de adoración en el tiempo de la adoración,
y Catharine estando en medio del pueblo, le dio la espalda al altar mayor,
se arrodilló y levantó la voz en oración al Señor.
El sacerdote que oficiaba se quitó su sobrepelliz^
footnote:[Prenda larga y amplia,
de tela blanca y fina y con las mangas muy anchas que lleva sobre la sotana el sacerdote]
y se arrodilló cerca de ella hasta que Catharine terminó. Entonces él extendió
la mano hacia ellas para que se acercaran y le ofreció una moneda a Catharine,
que al tomarla como la marca de la bestia,
la rechazó. Entonces él puso la moneda en la mano de Sara,
pero ella se la devolvió y le mostró la cartera,
para que él viera que ella tenía para dar, si alguien tenía necesidad,
y que hasta ahora ella no tenía falta de nada.
Entonces él les preguntó si ellas eran Calvinistas o Luteranas.
Ellas respondieron: "`No.`" Les preguntó si ellas irían a Roma, donde el Papa.
Ellas se negaron.
Les preguntó si eran católicas, a lo que dijeron, que ellas eran verdaderas cristianas,
siervas del Dios vivo.
Pero dado que aún no habían aprendido mucho del idioma que se hablaba ahí,
se expresaron muy deficientemente,
en parte con palabras y en parte con señas lo mejor que pudieron,
y muchos de los que las rodeaban quedaron asombrados; al final, se fueron pacíficamente.

Un tiempo después fueron de nuevo a una '`casa de la misa,`' cuando el sacramento,
como lo llaman ellos, era administrado.
Había muchas luces y una gran opulencia, y afligiéndose debido a la idolatría,
estuvieron cerca de tres cuartos de hora llorando y temblando, especialmente Catharine.
Esto impactó tanto a la congregación que algunos se alejaron de ellas por temor.
Finalmente se fueron, pero aún bajo tal temblor recorrieron la calle tambaleándose,
de modo que ellas se convirtieron en un espectáculo para todos los que las veían.

Ellas estuvieron cerca de tres meses en la casa del cónsul Inglés,
y él al estar bajo sospecha por esa razón,
no hizo lo que podía haber hecho para salvarlas, porque en cierto sentido,
las había entregado a la inquisición,
aunque por juramento estaba obligado a proteger a todo los ingleses ahí.
Mientras él las mantuvo en su casa no permitió que se fueran al extranjero,
aunque el gobernador le había dicho que él podría
dejarlas ir para que se dedicaran a sus asuntos.
"`Porque,`" dijo él, "`ellas son mujeres honestas.`"
El cónsul también podría haberlas dejado libres,
antes que cayeran bajo el poder de la vara negra.
Percibiendo ellas que algo para su perjuicio se estaba agitando,
y haciendo cuentas de que una prisión sería su destino,
le expresaron que ellas sospechaban de él,
y le dijeron que Pilato le haría un servicio a los judíos, y a pesar de todo,
se lavaría las manos en inocencia.
Sabiéndose descubierto, requirió una señal de ellas, si eran mensajeras de Dios.
Ellas le dieron a entender que lo siguiente podría servir de señal:
Que a ellas les iría bien, pero que no le iría bien a él.

Después de esto sucedió que la inquisición envió a buscarlas.
Ese día la esposa del cónsul les llevó algunos víveres, pero cuando ella pasó,
Catharine fue golpeada, como si hubiera recibido una flecha en el corazón,
y le pareció oír una voz diciendo: "`Ella ha logrado su propósito.`"
Luego Catharine no quiso probar la comida, sino que se apartó y lloró mucho.
El cónsul habiéndola llamado le dijo, que la inquisición había mandado a buscarlas,
al recibir cartas de Roma, pero que él esperaba que ellas fueran puestas en libertad,
lo cual, no era cierto,
porque él sabía (como ellas entendieron más tarde) que había una
habitación preparada para ellas en la prisión de la inquisición.

No había pasado mucho tiempo antes de que llegaran el canciller,
el cónsul y uno con la vara negra, quienes las llevaron delante del señor inquisidor.
Él les preguntó si habían cambiado de opinión,
porque parece que ellas habían sido requeridas antes, pero ellas respondieron:
"`No,`" y que no abandonarían la verdad.
Luego les preguntó acerca de esa nueva luz de la que ellas hablaban.
Ellas contestaron que no era una luz nueva,
sino la misma de la que los profetas y apóstoles dieron testimonio.
Luego preguntó cómo había llegado a perderse esa luz desde los tiempos primitivos.
Ellas contestaron que no estaba perdida, que los hombres todavía la tenían en ellos,
pero que no la conocían por causa de la noche de
la apostasía que se había extendido sobre las naciones.
Entonces les preguntó si ellas cambiarían de opinión y harían lo que ellos querían,
que deberían decirlo, de lo contrario, las usarían como a ellos les placiera.
Pero ellas indicando que no cambiarían dijeron:
"`Qué se haga la voluntad del Señor.`" Entonces él
se levantó y se fue con el cónsul dejándolas ahí,
y el hombre con la vara negra y el guarda las tomaron y
las pusieron en una habitación interior en la inquisición,
la cual sólo tenía dos pequeños agujeros en ella para luz y aire.
Este lugar estaba tan extremadamente caliente,
que parecía que la intención de ellos era sofocarlas, como podemos ver a continuación.

No mucho después fueron llevadas delante de los inquisidores para ser más examinadas.
No sólo les preguntaron sus nombres, sino también los nombres de sus esposos y padres,
y cuántos hijos tenían. También les preguntaron por
qué habían ido ahí. A lo que ellas respondieron,
que ellas eran siervas del Dios vivo, y que habían ido para llamarlos al arrepentimiento.
El día siguiente las llamaron de nuevo, pero esta vez las examinaron por separado.
Al preguntársele a Sara si ella era una verdadera católica,
dijo que ella era una verdadera cristiana, que adoraba a Dios en Espíritu y en Verdad.
Luego le extendieron un crucifijo y querían que ella jurara que hablaría la verdad.
A lo cual ella dijo, que hablaría la verdad, pero que no juraría,
porque Cristo había mandado: "`No juréis en ninguna manera.`"

El cónsul Inglés que estaba presente,
se esforzó para persuadirla a que jurara y le dijo que nadie le haría
daño. Como Sara tenía algunos libros con ella se los quitaron y le preguntaron,
por qué llevaba ella esos libros, a lo que ella respondió,
porque ellas no podían hablar el idioma de ellos.
Luego le preguntaron qué era George Fox.
Ella respondió: "`Un ministro.`"
Además le preguntaron, por qué había ido ahí. Ella replicó,
para hacer la voluntad de Dios,
según había sido movida por el Señor. La siguiente pregunta fue,
cómo le había aparecido el Señor. A lo cual respondió: "`Por medio de Su Espíritu.`"
Y al preguntarle si ella había visto Su presencia y oído Su voz, su respuesta fue,
que ella había oído Su voz y visto Su presencia.
Entonces le preguntaron, qué le había dicho Él. Ella respondió,
que Él requería de ella que fuera por los mares a hacer Su voluntad.
Esto les hizo preguntar,
cómo sabía ella que era el Señor quien había requerido esto de ella.
A lo que ella respondió,
que desde que Él le había indicado que Su presencia viva iría junto con ella,
lo hallaba cumpliendo Su promesa, porque ella sentía Su presencia viva.
Después de esto se fueron.

Dos días después los inquisidores llegaron y llamaron
a Catharine y ofreciéndole el crucifico,
le dijeron que los magistrados le ordenaban jurar que iba a decir la verdad.
A lo que ella dijo que diría la verdad, porque ella era testigo de Dios,
pero que no juraría, dado que uno mayor que los magistrados dijo:
"`No juréis en ninguna manera.
Pero sea vuestro hablar: Sí, sí; no, no; porque lo que es más de esto, procede del mal.`"
Entonces ellos dijeron: "`Debes obedecer al juez y él te ordena jurar.`"
Ella objetó: "`Yo obedeceré la justicia, pero si debo jurar haré algo injusto,
porque el Justo (Cristo) dijo:
'`No juréis en ninguna manera`'.`" Entonces le preguntaron si ella
reconocía al Cristo que había muerto en Jerusalén. Ella respondió:
"`Nosotras reconocemos al mismo Cristo y a ningún otro; Él es el mismo ayer,
hoy y por los siglos.`"
Lo siguiente que le preguntaron fue,
qué haría ella en Jerusalén. Ella respondió que no sabía que debía ir ahí,
pero que había intentado ir a Alejandría. Ellos preguntaron
qué haría ahí. La respuesta de ella fue:
"`La voluntad de Dios,`" y añadió, "`si el Señor abre mi boca,
debo llamar a la gente al arrepentimiento,
declararles el día del Señor y dirigir sus mentes de las tinieblas a la luz.`"
También le preguntaron, si ella había visto al Señor;
ella respondió que Dios era espíritu y era discernido espiritualmente.

Ahora bien,
aunque de las respuestas de estas mujeres muy poco podía ser tomado para culparlas,
las mantuvieron encerradas, lo que pareció afligir al cónsul Inglés,
porque él llegó donde ellas con lágrimas en sus ojos
y dijo que estaba dolido en cuanto a su propia carne,
pues parece que él había recibido algo por entregarlas,
lo que voluntariamente habría devuelto,
si de ese modo hubiera podido obtener su libertad.
Sin embargo, un temor servil lo poseía y nunca tuvo paz mientras vivió.

Algunos días después de esto, llegaron un magistrado, dos frailes,
el hombre con la vara negra, un escriba y el guarda de la inquisición para examinarlas.
Nuevamente se les pidió que juraran, pero ellas respondieron como antes,
que Cristo había dicho:
"`No juraréis en ninguna manera,`" y que el apóstol Santiago había encargado lo mismo.
Entonces el magistrado les preguntó si ellas dirían la verdad, ellas dijeron:
"`Sí.`" En seguida les preguntó si creían en el credo,
a lo que ellas dijeron que ellas creían en Dios y en Jesucristo,
quien nació de la virgen María y sufrió en Jerusalén bajo Poncio Pilatos,
se levantó de los muertos al tercer día y ascendió a Su Padre,
y vendría a juzgar tanto a los vivos como a los muertos.
Les preguntó además, cómo creían en la resurrección, y ellas respondieron,
que ellas creían que los justos y los injustos se levantarían,
de acuerdo a las Escrituras.
Lo siguiente que preguntó fue: "`¿Creen ustedes en los santos y les oran a ellos?`"
A cuya pregunta respondieron: "`Nosotras creemos en la comunión de los santos,
pero no les oramos a ellos, sino sólo a Dios en el nombre de Jesús.`"

Su siguiente pregunta fue, si ellas creían en la iglesia Católica, y ellas respondieron,
que ellas creían en la verdadera iglesia de Cristo,
"`pero la palabra católica,`" dijeron, "`no la hemos leído en las Escrituras.`"
También les preguntó si ellas creían en el purgatorio, a lo que ellas dijeron: "`No,
sino en el cielo y el infierno.`"
Entonces uno de los frailes, que era un Inglés,
dijo que a nosotros se nos había ordenado orar por los muertos,
pues los que estaban en el cielo no tenían necesidad
y para los que estaban en el infierno no había redención,
y que por lo tanto, debía haber un purgatorio.
Les preguntó si ellas creían en el santo sacramento, a lo que respondieron,
que ellas nunca habían leído la palabra sacramento en las Escrituras.
El fraile replicó: "`Donde ustedes leen en sus biblias santificación,
es sacramento en las nuestras.`"
Él dijo que el santo sacramento de ellos era el pan y el vino,
lo cual ellos convertían en carne y sangre de Cristo por virtud de Cristo.
"`Entonces,`" dijeron las mujeres, "`ustedes obran milagros,
pues la virtud de Cristo es la misma que era cuando Él convirtió
el agua en vino en las bodas de Caná.`" El fraile dijo:
"`Si nosotros no comemos la carne y bebemos la sangre del Hijo de Dios,
no tenemos vida en nosotros.`"
Ellas respondieron:
"`La carne y la sangre de Cristo son espirituales
y nosotras nos alimentamos de ello diariamente,
porque lo que es engendrado de Dios en nosotras no puede vivir más sin comida espiritual,
de lo que pueden hacerlo nuestros cuerpos temporales sin comida temporal.`"
Entonces él dijo: "`Ustedes nunca oyen misa.`"
"`Pero nosotras oímos la voz de Cristo,
el único que tiene palabras de vida eterna y que
es suficiente para nosotras,`" dijeron ellas.
Él dijo: "`Ustedes son herejes y paganas,`" a lo que ellas respondieron:
"`Herejes son los que viven en pecado y maldad, y paganos los que no conocen a Dios.`"

Luego se les preguntó quién era la cabeza de la iglesia de ellas, a lo que respondieron:
"`Cristo.`"
Además se les preguntó qué era George Fox, ellas dijeron: "`Él es un ministro de Cristo.`"
Al ser interrogadas si él las había enviado, la respuesta de ellas fue:
"`No. El Señor nos movió a venir.`"
Entonces el fraile dijo: "`Ustedes están engañadas y no tienen la fe,
aunque tienen todas las virtudes.`"
Ellas replicaron: "`La fe es el fundamento del que proceden las virtudes.`"
Después se les dijo que si ellas tomaban el santo sacramento podrían obtener su libertad,
de lo contrario, el Papa no las dejaría ir por millones de oro,
sino que perderían sus almas y sus cuerpos también. A esto ellas dijeron:
"`El Señor ha provisto para nuestras almas y nuestros cuerpos son
libremente entregados para servirle a Él.`" Luego se les preguntó
si ellas no creían que el matrimonio era un sacramento,
y ellas respondieron que era una ordenanza de Dios.
También se les preguntó si ellas creían que los hombres podían perdonar pecados,
y la respuesta de ellas fue que nadie podía perdonar pecados, sino sólo Dios.

Después de otro intercambio de palabras las mujeres preguntaron:
"`¿En qué les hemos hecho daño para que nos mantengan
prisioneras todos los días de nuestra vida?
Nuestra sangre inocente será requerida de sus manos.`"
El fraile dijo que él tomaría la sangre de ellas sobre sí mismo.
Ellas respondieron que llegaría el tiempo en el que él iba
a encontrar que tenía suficiente sobre sí mismo sin ella.
Entonces se les dijo que el Papa era el vicario de Cristo
y que lo que él había hecho era para el bien de sus almas.
A esto ellas respondieron:
"`El Señor no ha encomendado la carga de nuestras almas al Papa, ni a ustedes tampoco,
porque Él las ha tomado en posesión Suya.
¡Gloria sea a Su nombre por siempre!`"
Entonces se les dijo que debían ser obedientes.
Ellas contestaron que ellas eran obedientes al gobierno del Espíritu o luz de Cristo.
El fraile dijo: "`Nadie tiene la verdadera luz sino los católicos,
la luz que ustedes tienen es el espíritu del diablo.`"
"`¡Ay de aquellos (dijeron ellas) que maldicen a Jesús!
¿Puede el diablo dar poder sobre el pecado y la iniquidad?
Eso destruiría su reino.`"
"`Todos se ríen y se burlan de ustedes.`"
"`Pero,`" dijeron ellas, "`¿qué será de los burladores?`"
"`Eso no importa,`" dijo él,
"`ustedes se apresuran a predicar y no tienen la verdadera fe.`"
Ellas respondieron: "`La verdadera fe se sostiene en una consciencia pura,
vacía de ofensa hacia Dios y los hombres.
Todos tienen la verdadera fe, creen en Dios y en Jesucristo a quién Él envió,
pero los que dicen que creen y no guardan sus mandamientos,
son mentirosos y la fe no está en ellos.`"

El fraile confesó que eso era cierto,
aunque él les resultaba muy fastidioso porque continuamente
las amenazaba para hacerlas convertirse.
Para este fin fueron encerradas en una habitación tan caliente que se dijo,
que era imposible que pudieran vivir mucho tiempo en ella.
Cuando se acostaban en la cama las picaban tantos mosquitos, que sus caras se hincharon,
como si se hubieran enfermado con viruela, por lo que muchos empezaron a temerles,
y el fraile le dijo a Sara que él divisaba un espíritu malo en la cara de ella.

En otro momento que estaban siendo examinadas les preguntaron,
cuántos de sus amigos habían salido al ministerio y a qué partes.
Ellas respondieron lo que sabían. Y se les dijo que todo el que se atreviera a entrar
en el territorio del Papa no regresaría. Pero ellas dijeron que el Señor era tan suficiente
para ellas como lo había sido para los muchachos en el horno de fuego,
y que su confianza estaba en Dios.
Estando Catharine enferma le preguntaron porque se veía así,
que si el espíritu de ella estaba débil.
Ella respondió: "`No, mi cuerpo está débil porque no como carne.`"
Al oír esto, el fraile le ofreció una licencia para que comiera carne,
porque estaban en la Cuaresma de ellos,
pero ella la rechazó y dijo que no podía comer nada.
Y yendo luego a la cama, permaneció ahí noche y día por doce días seguidos,
ayunando y sudando, pues estaba muy afligida y su agonía era grande.

Después de diez días fueron donde ellas dos frailes, el canciller,
el hombre con la vara negra, un médico y el guarda.
Uno de los frailes le ordenó a Sara que saliera de la habitación
y luego sacó de la cama la mano de Catharine y dijo:
"`¿Es tan grande el demonio en ti que no puedes hablar?`"
A lo que ella respondió: "`Apártate de mí hacedor de iniquidad,
el poder del Señor está sobre mí, ¿y tú Lo llamas demonio?`"
Entonces él tomó un crucifijo para golpearla en la boca,
y ella le preguntó que si esa era la cruz que había crucificado
a Pablo para el mundo y al mundo para Pablo.
Ese fraile ignorante dijo que sí. Pero ella lo negó y dijo:
"`El Señor me ha hecho testigo para Él contra todos lo que hacen iniquidad.`"
Él entonces le ordenó que obedeciera y quiso golpearla, a lo que ella dijo:
"`¿Me vas a golpear?`"
Al decir él que sí lo haría, ella añadió: "`Estás fuera de la doctrina de los apóstoles,
porque ellos nunca golpearon.
Yo niego que seas uno de los que fueron en el nombre del Señor.`" A lo que él le respondió,
que él le había llevado un médico por caridad, y ella dijo:
"`El Señor es mi médico y salud salvadora.`"

El fraile enojándose más dijo que ella debía ser azotada,
descuartizada y quemada esa noche en Malta,
y su compañera también. Pero ella le dijo modestamente que no tenía temor,
que el Señor estaba a su lado y que él no tenía poder sino el que había recibido,
y que si él no lo usaba para el fin para el cual el Señor se lo había dado,
Él lo juzgaría. Ante estas palabras todos quedaron mudos y se fueron.
Luego el fraile fue donde Sara y le dijo que Catharine lo había llamado hacedor de iniquidad.
"`¿Lo hizo?,`" dijo Sara,
"`¿Estás sin pecado?.`" A lo que él respondió que sí. "`Entonces,`" contestó Sara,
"`ella te ha agraviado.`"

A última hora en la tarde algo fue proclamado en
la puerta de la prisión golpeando un tambor,
y temprano en la mañana algunos llegaron con un tambor y armas.
A mí me parece que eso fue hecho con el propósito de atemorizar a estas pobres mujeres,
y hacerlas creer que serían llevadas a la muerte.
Pues en realidad, ellas no esperaban algo diferente,
tras haber pasado varias semanas esperando ser quemadas en la hoguera.
Pero ellas estaban plenamente entregadas y rendidas
a lo que el Señor se complaciera en permitir.
Entre tanto, Catharine continuaba enferma y el fraile llegó de nuevo con un doctor.
Pero ella le dijo que no podía tomar nada a menos que sintiera la libertad.
Entonces él dijo que ellas nunca saldrían de esa habitación mientras vivieran,
y pretendiendo ser amable con ellas añadió:
"`Ustedes pueden agradecerle a Dios y a mí que sus condiciones no son peores,
porque pudieron haber sido peores.`"
Después ellas dijeron que si hubieran muerto,
habrían muerto tan inocentes como alguna vez murieron los siervos del
Señor. Él entonces dijo que estaba bien que ellas fueran inocentes,
y volviéndose a Sara le pidió que se fijara en qué
tormento debía estar Catharine a la hora de la muerte,
diciendo que miles de demonios se llevarían su alma al infierno.
Pero Sara le dijo que ella no le temía a tal cosa.
Él le preguntó a Catharine si no creía que era conveniente
que los ancianos de la iglesia oraran por los enfermos.
Ella dijo: "`Sí,
cuando son movidos por el Espíritu del Señor.`" Entonces él cayó sobre
sus rodillas y aullaba y deseaba que cayeran sobre él toda clase de males,
si no tenía la fe verdadera.
Mientras tanto, el doctor estaba enfurecido porque ella no se había inclinado ante él.

Mientras Catharine estaba enferma, Sara no estaba exenta de gran aflicción,
pues le dolía ver a su querida compañera tan enferma,
y ella fácilmente previó que si Catharine moría sus
propios sufrimientos serían más pesados.
Sin embargo,
ella estaba rendida a la voluntad del Señor y no guardaría
el menor rencor si Catharine reposaba eternamente.
Pero con el tiempo Catharine empezó a mejorar y a tener hambre,
y al comer se fortaleció. Pero la habitación donde estaban encerradas estaba
tan excesivamente caliente que a menudo se veían obligadas a levantarse de la
cama y recostarse cerca del hueco de la puerta para recibir aire y tener aliento.
El calor era muy grande, porque no sólo venía de afuera, sino también de adentro,
y las afectó tanto que la piel se les resecó,
se les cayó el pelo y se desmayaban con frecuencia.
Sus aflicciones eran tan grandes que cuando era de día deseaban la noche,
y cuando era de noche deseaban el día. Sí,
debido a la debilidad humana deseaban la muerte,
y comían su pan llorando y mezclaban su bebida con lágrimas.

Una vez Catharine les preguntó a los frailes (que acudieron
a verla con un médico diciéndole que era una obra de caridad):
¿Nos mantienen ustedes en esta habitación tan caliente para matarnos
y luego nos traen un doctor para mantenernos más tiempo vivas?
A esto el fraile dijo que el inquisidor perdería la cabeza si él las sacaba de ahí,
y que era mejor mantenerlas ahí que matarlas.
Entonces ellas le escribieron al inquisidor y presentaron su inocencia delante de él,
y también dijeron, que si era de la sangre de ellas de lo que estaban sedientos,
podrían tomarla de cualquier otra forma,
como también sofocándolas en esa habitación caliente.
Pero esto lo enfureció tanto que mandó al fraile a quitarles sus tinteros,
sus biblias (habiéndoles sido quitadas antes).
Ellas le preguntaron por qué les eran quitados sus bienes, a lo que él respondió:
"`Todo es nuestro y sus vidas también, si queremos.`"
Entonces ellas le preguntaron, cómo habían perdido el derecho de sus vidas,
a lo que se les dijo: "`Por traer libros y papeles.`"
Ellas replicaron, que si había algo en ellos que no fuera cierto,
ellos podían escribir contra eso.
A esto el fraile dijo que ellos despreciaban escribirles a tontos y a asnos que no sabían
el verdadero latín. Además se les dijo que el inquisidor las quería separadas,
porque Catharine estaba débil y debía ir a una habitación más fresca,
pero que Sara debía permanecer ahí. Entonces Catharine tomó a Sara por el brazo y dijo:
"`El Señor nos ha unido y ¡ay de aquellos que nos separen!
Preferiría morir aquí con mi amiga que separada de ella.`"
Esto impresionó tanto al fraile que se fue y no volvió más por cinco semanas,
y la puerta de esa habitación no fue abierta todo ese tiempo.

Entonces los frailes llegaron de nuevo a separarlas,
pero Catharine estaba enferma y con un sarpullido de pies a cabeza.
Ellos enviaron a buscar un doctor y este dijo que ellas debían tener aire o de otro modo,
debían morir.
Esto le fue dicho al inquisidor y él ordenó que la puerta estuviera
abierta seis horas al día. Pero diez semanas después fueron separadas,
lo que fue una aflicción tan gravosa para ellas,
que declararon que la muerte misma no les habría sido tan difícil.
Los frailes decían que ellas se corrompían una a la otra y que estando separadas,
se inclinarían y someterían. Pero ellos mismos se vieron decepcionados,
porque las mujeres eran más fuertes después que antes,
al ser adaptadas por el Señor a cada condición. Antes de que fueran
separadas los frailes les habían llevado un azote pequeño de cuerdas
de cáñamo y les preguntaron si lo querían tener,
y les dijeron que eran usados para azotarse a sí mismos hasta sangrar.
Pero las mujeres dijeron que eso no podía alcanzar al diablo,
porque él se sentaba en el corazón. Luego los frailes dijeron:
"`Toda la gente de Malta está por ustedes,
si ustedes fueran católicas todos las aceptarían.`" Pero ellas respondieron:
"`El Señor nos ha transformado en lo que no cambia.`"
Ellos dijeron: "`Todas nuestras mujeres santas están orando por ustedes,
y si se convierten serán honradas por todo el mundo.`"
Ellas replicaron:
"`El mundo yace en maldad y hemos rechazado todo honor y toda gloria del mundo.`"
A esto dijo el fraile: "`También serán honradas por Dios,
pero ahora son odiadas por todos.`"
"`Esto,`" dijo una de las mujeres, "`es una muestra evidente de quién somos siervas.
El siervo no es mayor que su Señor.`"

Un día, el Primer día de la semana,
los frailes fueron y les ordenaron arrodillarse con ellos para orar.
Ellas expresaron que ellas podían orar,
pero sólo cuando eran movidas por el Señor. Entonces los frailes
les ordenaron una segunda vez y se arrodillaron al lado de la cama,
y oraron según la manera de ellos, habiéndolo hecho les dijeron a las mujeres:
"`Hemos probado sus espíritus y ahora sabemos de qué espíritu son.`"
Pero ellas les dijeron que no podían saber eso,
a menos que sus mentes se volvieran a la luz de Cristo en sus consciencias.
Entonces, el fraile Inglés enfureciéndose les mostró su crucifijo y les ordenó mirarlo,
pero ellas le dijeron: "`El Señor dice:
No te harás imagen de ninguna cosa arriba en el cielo, o abajo en la tierra,
o en el agua debajo de la tierra.
No te inclinarás ante ellas ni las adorarás, porque yo el Señor tu Dios,
soy Dios celoso.`"
El fraile al ver a Sara hablarle tan audazmente pidió los grilletes para encadenarla.
Entonces ella bajó la cabeza y le dijo: "`No sólo mis manos y pies,
sino mi cuello también por el testimonio de Jesús.`" El fraile aparentemente
apaciguado dijo que él les haría cualquier bien que pudiera,
porque vio que lo que ellas hicieron no fue con malicia.
Los frailes iban con frecuencia y les decían:
"`Si ustedes quisieran ceder un poquito serían puestas en libertad,
pero no quieren ceder nada, sino estar contra todo.`"
A lo que ellas respondieron que ellas querían hacer
cualquier cosa que obrara para la gloria de Dios.

Mientras estuvieron encarceladas ahí,
sucedió que la casa de la Inquisición fue construida nueva o reparada,
lo que tomó cerca de un año y medio.
Durante ese tiempo algunos de los grandes fueron a menudo a ver la construcción,
lo que les brindó a estas mujeres la oportunidad de hablarles
y declarar la Verdad en el nombre del Señor. Ahora,
aunque ellas eran amenazadas por los frailes por predicar la luz de Cristo tan audazmente,
no sólo los magistrados, sino también el señor inquisidor,
se volvieron más moderados hacia ellas y se dio la orden de que les dieran plumas,
tinta y papel para que escribieran a Inglaterra.
Ellos parecían inclinados a ponerlas en libertad,
pero los frailes trabajaron fuertemente contra eso,
y se habían esforzado por cerca de tres cuartas parte del
año para separarlas antes de poder llevarlo a cabo.
Cuando finalmente lo lograron,
le dijeron a Catharine que ellas nunca se volverían a ver las caras.

Mientras tanto, Catharine estaba enferma y casi no tenía estómago para comer,
y no tenía pensado comer algo que no le fuera ofrecido por Sara.
Habiéndosele dicho a uno de los frailes que ella necesitaba que
alguien le lavara la ropa y le preparara algo de comida caliente,
él mandó a buscar a Sara para saber si ella lo haría por Catharine;
Sara dijo que sí lo haría. Por ese medio ellas, por algunas semanas,
oyeron una de la otra cada día. Una vez el fraile le dijo a Catharine:
"`Tú puedes liberarte de tu miseria cuando quieras,
puedes hacerte católica y tener la libertad de ir adonde quieras.`"
Ella le dijo: "`Por tanto, tendría un nombre de que vivía, cuando estaba muerta.
Ustedes tienen suficientes católicos ya.
Esfuércense por llevar a algunos de ellos a la luz en sus consciencias,
para que le teman a Dios y no pequen más.`" Pero él estaba tan ansioso
que dijo que perdería uno de sus dedos si ella y Sara se volvían católicas.
Entonces ella le dijo que Babilonia había sido construida con sangre,
pero que Sión fue redimida con juicio.

Muchas formas se usaron para desviarlas.
Una vez querían persuadirla de poner una pintura a la cabeza de su cama,
usada como una representación. Pero ella dijo, como con aborrecimiento: "`¡Qué,
¿crees que me hace falta un becerro para adorar?! ¿Caminas por la regla de las Escrituras?`"
A lo que el fraile respondió: "`Sí, lo hacemos, pero también tenemos tradiciones.`"
Ella replicó:
"`Si sus tradiciones anulan o se oponen a los fundamentos de la doctrina de Cristo,
de los profetas y de los apóstoles,
las niego en el nombre del Señor.`" Pero él afirmó que no lo hacían. Entonces ella preguntó
qué regla tenían ellos para quemar a los que no podían unirse a ellos por causa de consciencia.
Él respondió: "`San Pablo lo hizo peor, porque él los entregaba al diablo,`" y añadió,
que ellos juzgaban a todo condenado que no era de su fe.
Entonces ella objetó varios de los ritos supersticiosos de la iglesia de Roma,
y también mencionó la prohibición del matrimonio, lo cual, dijo ella,
es doctrina de demonios, según lo dicho por el apóstol.

Al ser puesto en aprietos,
él le dijo que San Pedro era el Papa de Roma y que él había construido un altar ahí,
y que el Papa era su sucesor y podía hacer lo que quisiera.
Pero ella refutó esto con buena razón. Él, entonces,
se jactó de la antigüedad de su iglesia,
pero ella expresó que la iglesia de la que ella era miembro, era aún más antigua:
"`Porque nuestra fe era desde el principio,`" dijo ella,
"`y Abel era de nuestra iglesia.`"
El fraile viéndose perdido y que ya no podía resistir a Catharine,
se fue adonde Sara y habló con ella en los mismos términos, y ella también le dijo:
"`Abel era de nuestra iglesia.`"
A lo que él dijo: "`Abel era católico,`" y exagerando dijo:
"`Y Caín y Judas también.`" A lo que Sara respondió:
"`Entonces el diablo era católico y yo no seré una.
No me convertiría aunque me partieras en pedazos.
Yo creo que el Señor me haría capaz de soportarlo.`"

En otro momento dicho fraile, cuyo nombre era Malaquías,
volvió adonde Catharine y le dijo que si ella estaba dispuesta a ser católica lo dijera,
de otro modo, la tratarían severamente y nunca más vería el rostro de Sara,
sino que moriría sola y mil demonios se llevarían su alma al infierno.
Entonces ella le preguntó si él era el mensajero de Dios para ella.
Él respondió: "`Sí.`" "`¡Entonces, ¿cuál es mi pecado?!,`" dijo ella.
"`¿En qué he provocado al Señor para que me envíe semejante mensaje?`"
El fraile respondió: "`Porque no has querido hacerte católica.`"
Después de lo cual ella dijo: "`Te rechazo a ti y también rechazo el mensaje,
y al espíritu que habla en ti,
porque el Señor nunca ha hablado así.`" Él enfureciéndose le dijo que
le pondría un montón de cadenas donde no viera el sol ni la luna.
Ella dando a entender cuán entregada estaba dijo,
que él no podría separarla del amor de Dios que es en Cristo Jesús,
la pusiera donde la pusiera.
Al agregar él que la entregaría al diablo, ella reanudó:
"`No temo a todos los demonios del infierno,
el Señor es mi guardián. Aunque tuvieras la inquisición,
con todos los países a su alrededor de tu lado y yo estuviera sola, no les temo.
Si ellos fueran miles más, el Señor está a mi mano derecha,
y lo peor que pueden hacer es matar el cuerpo,
no pueden tocar mi vida más de lo que el diablo pudo tocar la de Job.`"
Entonces el fraile dijo que ella nunca saldría viva
de la habitación. A lo que ella valientemente respondió:
"`El Señor es suficiente para librarme, pero ya sea que lo quiera o no,
no abandonaré la fuente viva para beber de cisternas rotas.
Ustedes no tienen ninguna ley para mantenernos aquí,
sino la ley que tuvo Acab para la viña de Nabot.`"
El fraile maldiciendo e invocando sus dioses huyó, y mientras tiraba de la puerta dijo:
"`Permanece aquí, miembro del diablo.`"
A lo que ella dijo: "`Los miembros del diablo hacen las obras del diablo,
y los ayes y plagas del Señor estarán sobre ellos por eso.`"

Luego, el fraile fue y se lo contó al inquisidor, quien se rió de él,
y antes de que volviera de nuevo,
Catharine había sido sacada de esa habitación. Cuando fue adonde ella,
se llevó con él uno de los hombres del inquisidor y dos buenas gallinas,
y dijo que el señor inquisidor las había enviado en amor a ella.
Ella respondió que recibía su amor, pero aún así,
no se mostró muy dispuesta a aceptar las gallinas.
Ella expresó que estaba dispuesta a pagar por ellas,
no queriendo estar a expensas de nadie mientras tuviera lo propio.
El fraile, quien al parecer quería que ellas depositaran su dinero a los pies de él dijo,
que ellas no debían contar nada como propio,
porque en los tiempos primitivos los cristianos vendían
sus posesiones y ponían el dinero a los pies de los apóstoles.
Además dijo: "`No te faltará nada, aunque debamos gastar mil coronas.
Pero eres orgullosa, porque no tomarás las gallinas que el inquisidor envió por caridad.`"
Ella entonces preguntó qué clase de caridad era esa, puesto que las mantenía prisioneras.
Él respondió que era por el bien de sus almas que él las mantenía prisioneras, y añadió:
"`Si no hubieras ido a predicar, habrías podido ir donde quisieras.`"
Ella respondió: "`Nuestras almas están fuera del alcance del inquisidor.
¿Por qué se extiende tu amor hacia nosotras más que hacia tu propia familia?
Pues ellos cometen toda forma de pecados de los que no puedes acusarnos.
¿Por qué no los pones en la inquisición y les mandas que se conviertan?`"

Entonces él dijo: "`Tú no tienes la verdadera fe`";
y mostrándole su crucifijo le preguntó si ella pensaba que él lo adoraba.
Ella le preguntó qué hacía entonces con él,
a lo que él respondió que era una representación.
Ella replicó que eso no representaba a Cristo,
porque Él era la expresa imagen de la gloria de Su Padre, la cual es luz y vida.
"`Pero,`" continuó ella, "`si puedes poner vida en cualquiera de tus imágenes,
entonces tráemela.
¿Qué representación tenía Daniel en el foso de los
leones o Jonás en el vientre de la ballena?
Ellos le clamaron al Señor y Él los libró.`" El fraile,
que no podía soportar oírla hablar tanto contra los ídolos,
dijo que ella hablaba como un loca y agregó: "`Te entregaré al diablo.`"
Ella no temiendo esto dijo: "`Entrega lo tuyo,
yo soy del Señor.`" Entonces él se puso de pie y dijo:
"`Te haré como hicieron los apóstoles con Ananías y Safira.`"
Ella poniéndose de pie también dijo: "`Te rechazo en el nombre del Señor, el Dios vivo;
tú no tienes poder sobre mí.`"

Entonces se fue con las gallinas adonde Sara y le dijo que Catharine estaba enferma,
y que el señor inquisidor había mandado dos gallinas,
y que ella estaría muy contenta de comer un pedazo de una,
si ella le aderezaba una de ellas para el momento y la otra para el día siguiente.
Sara que no era menos prudente y cautelosa que Catharine,
y no estaba dispuesta a recibir ese regalo antes de saber lo que podría ser conveniente,
le respondió como lo había hecho Catharine.
Entonces se llevó de nuevo las gallinas diciendo:
"`Ustedes desean fervientemente ser quemadas,
porque así le harían creer al mundo que aman tanto a Dios como para sufrir de esa manera.`"
Oyendo Catharine eso dijo: "`Yo no deseo ser quemada, pero si el Señor me llama a eso,
yo creo que Él me dará el poder para padecerlo por Su Verdad,
y si cada cabello de mi cabeza fuera un cuerpo,
yo podría ofrecerlos todos por el testimonio de Jesús.`"

El fraile, regresando después,
nuevamente le preguntó a Catharine si ella no había sido inspirada por el Espíritu
Santo a ser católica desde que había llegado a la inquisición. Ella dijo:
"`No.`" Pero él manteniendo lo contrario dijo:
"`Tú eres de las que llaman al Espíritu del Espíritu Santo, el Espíritu del diablo.`"
"`No,`" respondieron ellas (que aunque estaban separadas podían oírse una a la otra),
"`el Espíritu del Espíritu Santo en nosotras resistirá al diablo,
y la inspiración del Espíritu Santo no es obrada
en la voluntad del hombre ni en el tiempo del hombre,
sino en la voluntad y tiempo de Dios.`"
Hubo más discusión acerca de este asunto, y luego,
al preguntar ellas por sus biblias (que les habían sido quitadas),
él les dijo que nunca las verían de nuevo porque eran falsas.

Así, ellas a menudo eran molestadas e importunadas por los frailes,
quienes generalmente llegaban dos a la vez, aunque a veces solo uno.
Uno de ellos con frecuencia levantaba su mano para golpearlas, pero nunca lo hizo,
pues ellas al no reaccionar con temor se desconcertaba,
y luego decía que ellas eran buenas mujeres y que les haría algún bien.
Como en efecto, él algunas veces trabajó para ellas,
decía que era por amor a Dios y que ellas debían agradecerle por eso.
A lo que ellas respondían,
que aquellos que habían hecho algo para Dios no habían buscado una recompensa del hombre.
Una vez esto lo enojó tanto que dijo que ellas eran las peores de todas las criaturas,
y que debían ser tratadas peor que los Turcos, Armenios y Luteranos.
A lo que una de ellas dijo: "`La vida pura siempre ha sido contada como lo peor,
y si sufrimos somos del Señor y podemos confiar en Él. Haz lo que quieras con nosotras,
no tememos ninguna mala noticia.
Estamos establecidas y fundamentadas en la Verdad, y cuánto más nos persigan,
más fuertes crecemos.`"
Ellas en verdad experimentaron esto, según lo indican en sus cartas,
aunque estuvieron separadas una de la otra un año.

Una vez los frailes fueron donde Sara y le dijeron
que si ella quería podía salir de la celda,
y no hablar ni hacer nada.
Al decir ella que quería según esos términos,
le dijeron que regresarían la mañana siguiente.
Pero Sara percibió el engaño, por tanto,
cuando llegaron resolvió no salir para evitar la trampa,
aunque los frailes se estaban comportando amigablemente,
y le decían que el señor inquisidor había dicho que si les hacía falta lino, lana,
medias, zapatos y dinero que ellos se los darían.

En una ocasión sucedió que un Inglés que vivía ahí,
habiendo oído que Sara estaba en una habitación con una ventana al lado de la calle,
subió por la pared y le habló unas pocas palabras,
pero fue violentamente jalado y echado en prisión entre la vida y la muerte.
Él era uno de los que ellos habían tomado de los Turcos y convertido en un papista.
Los frailes fueron donde ellas para saber si él les había llevado alguna carta.
Ellas dijeron: "`No.`" Catharine ni siquiera lo había visto, sin embargo,
les dijeron que era probable que lo ahorcaran.
Sara le dio información a Catharine de esto escribiéndole una pocas líneas
(porque parece que ellas no podían oírse una a la otra en ese entonces),
y le dijo que ella pensaba que los frailes Ingleses
eran los actores principales de este asunto.

Esto entristeció a Catharine y le escribió a Sara de nuevo (porque
ellas tenían una forma privada de escribirse una a la otra).
En esta carta, después de su saludo,
le dijo a Sara que ella podía estar segura de que los frailes eran los actores principales,
pero que ella creía que el Señor preservaría a ese pobre Inglés por Su amor.
Que ella había buscado al Señor por él con lágrimas y que
deseaba que ella le enviara algo una vez al día,
si el guarda lo llevaba.
Que ella misma estaba embargada por el amor de Dios por
su propia alma y que su Amado era el Principal de diez mil,
y que ella no le temía al rostro de ningún hombre aunque sentía sus flechas.
Además, que ella tenía la expectativa del regreso de ellas a Inglaterra.
Y en la conclusión le pidió a Sara que estuviera atenta, si era tentada con dinero.

Pero esta carta (por cuál medio, nunca lo supieron), llegó a manos del fraile Inglés,
quien la tradujo al italiano y se la entregó al señor inquisidor.
Luego,
fue con el asistente del inquisidor donde Catharine y le mostró los dos documentos,
y le preguntó si ella podía leer el que estaba en inglés. "`Sí,`" dijo ella,
"`yo lo escribí.`" "`Oh, ¿tú lo hiciste?,`" dijo él. "`Y,
¿qué es lo que dices de mí aquí?`" "`Nada sino lo que es cierto,`" replicó ella.
Entonces él dijo: "`¿Dónde está el papel que envió Sara?
Entrégalo o de lo contrario buscaré en tu baúl y en cualquier otro lugar.`"
Ella entonces le indicó que buscara donde quisiera.
Él le dijo que ella debía decirle quién le había
traído tinta o debería ser encadenada al momento.
Ella le respondió que no había hecho nada,
sino lo que era justo y correcto ante los ojos de Dios,
y que lo que ella sufriera por esa razón, sería para el bien de la Verdad.
Que ella no se entrometería con los pobres trabajadores.

Luego él dijo: "`Por amor a Dios, dime que escribió Sara.`"
Ella le dijo algo, y dijo que lo que le había dicho era verdad.
"`Pero,`" respondió él, "`tú dices más, que nosotros no la tentáramos con dinero.`"
Y esto de hecho sucedió después. El asistente entonces
tomó la tinta de Catharine y la tiró y así se fueron.
El pobre Inglés fue liberado la mañana siguiente.
Ellos yéndose para donde Sara le dijeron que Catharine había confesado honestamente
todo y que era mejor que ella confesara también. Ellos la amenazaron con un cabestro,
que le quitarían la cama y el baúl y el dinero también. A lo que Sara dijo,
que era posible que ya no pudiera enviarle a Catharine nada más. Sara
le preguntó al asistente si él era un ministro de Cristo o un magistrado.
Que si era un magistrado, dijo ella, él podía tomar su dinero,
pero que ella no se lo daría. Él, enfureciéndose, dijo que ella estaba poseída,
a lo que ella replicó, que si era así,
entonces sería por el poder de una vida indestructible.

Así, ellas ocasionalmente sufrían muchos asaltos, pero a veces sucedía también,
que los que llegaban a verlas eran golpeados en el corazón,
lo cual ofendía a los frailes.
Al fin el dinero de ellas empezó a terminarse,
por haberlo utilizado a veces para comprar víveres.
Los frailes les habían dicho que podían guardarlo para otros servicios,
porque ellos debían mantenerlas mientras las tuvieran prisioneras.
A esto ellas habían dicho que no podían guardar el dinero y ser carga para otros.
Esto resultó en que perdieron el apetito y comieron poco por tres o cuatro semanas,
hasta que finalmente se vieron obligadas a ayunar por varios días seguidos.
Esto hizo que los frailes dijeran que era imposible que las personas pudieran
vivir con tan poca comida como ellas lo hacían. Luego se les dijo que
el señor inquisidor había dicho que ellas podían tener lo que quisieran,
a lo que respondieron, que no estaba en sus propias voluntades ayunar,
que debían esperar para conocer la mente del Señor; lo que Él quería que ellas hicieran.
Así continuaron debilitándose, especialmente Sara,
que al comprender que su muerte estaba cerca,
cubrió su cabeza como si yaciera en la tumba.
Ambas estaban tan débiles que no podían ponerse ni quitarse la ropa,
y eran incapaces de arreglar sus camas.
Si bien deseaban estar juntas en una misma habitación, los frailes no lo permitieron.
En esta condición concluyeron que estaban por morir,
pero el cielo había provisto lo contrario.

Por ese tiempo Catharine, que estaba siendo ejercitada en súplicas al Señor,
mientras le rogaba que a Él le placiera ponerles fin a las pruebas
de ellas de la manera que le pareciera buena a Sus ojos,
creyó oír una voz diciendo:
"`Ustedes no morirán.`" Ella tomó esto como una voz celestial,
y a partir de ese momento se sintieron refrescadas con la presencia viva del Señor,
para gran gozo y consuelo de ambas.
Entonces se sintieron libres para comer de nuevo y se les proporcionaron buenos víveres.
Sin embargo, aún tenían temor de comer algo que en algún sentido,
pudiera ser considerado impuro.
Por tanto, clamaron al Señor diciendo:
"`Preferimos morir que comer algo que esté contaminado o sea impuro.`"
Entonces Catharine entendió que le había sido dicho de parte del Señor:
"`Pueden comer tan libremente, como si ustedes lo hubieran hecho con sus propias manos.`"
Sara, que a veces había trabajado para otros en la casa de la inquisición,
fue persuadida de que se le había dicho por inspiración:
"`Tú comerás el fruto de tus manos y serás bendecida.`"
Y así comieron, y por ocho o diez días obtuvieron todo lo que pidieron.

Pero después fueron tan estrechadas por falta de comida, que les dolió más que el ayuno.
Sin embargo, al ser preservadas vivas un fraile dijo:
"`El Señor las mantiene vivas mediante Su gran poder,
porque ellas tienen que ser católicas.`"
A esto ellas respondieron, que un día se conocería que el Señor tenía otro fin en esto.
Pero los frailes les dijeron claramente que no había redención para ellas.
Después de lo cual ellas dijeron que en el Señor había misericordia y abundante redención,
y les advirtieron que tuvieran cuidado de "`ser hallados luchando contra Dios.`"
Los frailes respondieron: "`Ustedes son mujeres necias.`"
"`Entonces lo somos,`" replicaron ellas,
"`las necias del Señor. Y los necios son queridos y preciosos ante Sus ojos.`"
Entonces los frailes, mostrándoles sus coronillas afeitadas,
dijeron que ellos eran los necios del Señor, y señalando sus vestidos,
dijeron que ellos los usaban por amor a Dios para que el mundo se riera de ellos.

Por este tiempo uno de los frailes hizo lo que pudo para enviar a Catharine a Roma,
y al no tener éxito dijo que deberían ir los dos.
Pero como esto tampoco surtió efecto,
el fraile fue enviado a la cárcel con un documento
que contenía la acusación contra Catharine.
Pero ella hablándole celosamente al escriba,
pronunciaba ayes contra la acusación y la desafiaba en el nombre del Señor.
Antes de que el fraile se fuera le dijo a Sara que Catharine era bruja,
y que ella sabía qué se hacía en otros lugares.
Él dijo esto porque una vez diciéndole a Catharine un montón de mentiras,
ella le había dicho que ella tenía un Testigo de Dios en ella, que era fiel y verdadero,
y que ella le creía a este Testigo.

Después que se fue,
el cónsul Inglés llegó donde ella con un dólar enviado
por el capitán de un barco que había llegado de Plymouth.
Ella le dijo que recibía el amor de su compatriota, pero que no podía recibir su dinero.
Entonces él le pregunto qué haría ella si no tomaba el dinero, a lo que ella respondió:
"`El Señor es mi porción, y por tanto, no me hará falta ninguna cosa buena.
Nosotras estuvimos en tu casa cerca de quince semanas,
¿viste en nosotras alguna razón para la muerte y el cautiverio?
Y al decir él que no,
ella le indicó que en cierto sentido él había sido cómplice del encarcelamiento de ellas,
y que él no ignoraba la intención. "`Tú sabías,`" dijo ella,
"`que una habitación estaba preparada para nosotras en la inquisición,
y si no fuera porque hemos sido mantenidas vivas por el gran poder Dios,
habríamos muerto hace mucho tiempo.`"
Esforzándose por excusarse él dijo: "`¿Cómo pude haber ayudado?`"
Entonces ella le recordó lo que había sucedido en la casa de él mientras estuvieron ahí,
y cómo los habían llamado al arrepentimiento y los habían prevenido.
Y que él había dicho: "`Sea como sea, les irá bien.`"
Entonces ella le recordó cómo él había requerido una señal de ella,
si es que eran siervas del Señor Dios.
Le preguntó si no era cierto que ellas le habían dicho:
"`Tú eres una persona condenada y permaneces culpable ante Dios, sin embargo,
arrepiéntete, si puedes encontrar un lugar.`"
Mientras ella le hablaba así,
al cónsul le temblaban los labios y se le estremecía todo el cuerpo,
por lo que apenas podía mantenerse sobre las piernas,
y aunque era un hombre bien parecido y en la flor de su vida,
ahora se veía como alguien que languidecía. Esta era señal suficiente para toda la ciudad,
si la hubieran tomado debidamente en cuenta.

Como Catharine había rechazado la moneda, el cónsul se fue adonde Sara con el dinero,
pero ella también le dijo que no podía tomarla, pero que si tenía una carta para ellas,
ella se sentiría libre de recibirla.
Él dijo que no tenía ninguna y le preguntó si le hacía falta algo,
a lo que ella respondió que el Señor era su Pastor
y que no le faltaría ninguna cosa buena;
pero que anhelaba su libertad.
Él, no queriendo desalentarla le dijo: "`La tendrás en un tiempo.`"
Pero él no vivió para verlo,
porque la siguiente vez que oyeron hablar de él estaba muerto.

Mientras el fraile estaba en Roma,
les fue dicho que ellas también iban a ser enviadas ahí. De hecho,
hubo una gran operación al respecto,
pero parece que no pudieron ponerse de acuerdo en el asunto.
Mientras tanto Catharine y Sara permanecían separadas,
pues había cinco puertas entre ellas con cerraduras y barras.
Sin embargo,
Sara a veces encontraba una oportunidad (fuera por
descuido del guarda o porque era hecho a propósito),
para ir adonde podía ver a Catharine, y cuanto más las vigilaban los frailes,
aún así ella iba a la puerta de Catharine por la noche.
Pero en una ocasión la descubrieron y la encerraron nuevamente, sin embargo,
no mucho tiempo después las puertas fueron abiertas de nuevo,
para que se sentaran a la vista la una de la otra.

A veces eran llevadas como prisioneras a la inquisición personas de varias naciones,
y los frailes y otros grandes hombres se esforzaban a su manera para hacerlos cristianos.
Entonces estas mujeres a menudo mostraban los errores
del catolicismo y declaraban la Verdad,
por la cual estaban dispuestas a sufrir la muerte, si les era requerida;
pero esto fue tomado muy mal.
Al fin sucedió que dos hombres Ingleses llegaron a esa ciudad
y trataron de obtener la libertad de ellas,
pero fue en vano.
Poco después,
los magistrados mandaron por ellas y les preguntaron
si estaban enfermas o si les hacía falta algo,
y diciéndoles que podrían escribir a Inglaterra,
le ordenaron al escriba que les diera tinta y papel.

No mucho después llegaron un tal Francis Steward, capitán de un barco,
y un fraile de Irlanda, quienes se esforzaron mucho por obtener su liberación;
y sus amigos en Inglaterra no habían escatimado en nada que pudiera procurarles la libertad.
Pero el tiempo para esta no había llegado aún. El citado capitán
y el nuevo cónsul Inglés se esforzaron mucho por lograr su libertad,
pero no estaba en poder de los magistrados,
pues el inquisidor dijo que él no podía ponerlas en libertad sin una orden del Papa.
No obstante,
Catharine y Sara fueron llevadas a la sala de la corte y el cónsul Inglés les preguntó,
si ellas estaban dispuestas a regresar a Inglaterra.
Ellas dijeron que sí, que ellas podrían si era la voluntad de Dios.
El capitán del barco, que también estaba ahí,
les habló con lágrimas en sus ojos y les contó lo que él había hecho a favor de ellas,
pero que había sido en vano.
"`Es el inquisidor,`" dijo él, "`quien no las dejará salir libres;
ustedes han predicado entre estas personas.`"
Ellas dijeron que ellas habían testificado de la Verdad
y que estaban dispuestas a mantenerla con su sangre.
Él respondió que si ellas eran puestas en libertad,
él les daría los pasajes gratis y proveería para ellas.
Y ellas le respondieron que aceptaban su amor del Señor,
tanto como si las hubiera llevado.
También les ofreció dinero, pero ellas rehusaron tomarlo.

Entonces ellas le relataron de su encarcelamiento y sufrimientos,
y que no podían cambiar sus mentes aunque fueran reducidas a cenizas o picadas en pedacitos.
Entonces, el fraile acercándose dijo que ellas no trabajaban, pero esto no era cierto,
porque ellas tenían trabajo propio y trabajaban como podían. También
le dijeron que el trabajo y negocio de ellas estaba en Inglaterra.
Él confesando que eso era cierto dijo,
que ellas habían sufrido suficiente y por mucho tiempo,
y que deberían obtener su libertad dentro de un corto tiempo,
pero que necesitaban una orden del Papa.
Mientras tanto,
el capitán estaba afligido porque no había podido
obtener la libertad de ellas y tenía que irse.
Él oró que Dios las consolara,
y ellas que el Señor lo bendijera y lo preservara para vida eterna.
Que nunca dejara que él ni lo suyo se fuera sin una bendición de Él, por su amor,
pues él se había aventurado en extremo en ese lugar,
al esforzarse por obtener la libertad de ellas.

Después que él se fue, se encontraron con un peor trato,
y llegando el inquisidor las miró con indignación,
pues la eliminación de sus vidas estaba en pie de nuevo
y sus puertas estuvieron cerradas por muchas semanas.
Después de un tiempo, el inquisidor regresó a la torre donde ellas se sentaban,
y Sara lo llamó y le pidió que les abrieran la puerta
para bajar al patio a lavar sus ropas.
Él entonces ordenó que la puerta fuera abierta una vez a la semana,
y no mucho después era abierta cada día. Ya que se había dicho
que ellas no podían ser liberadas sin la licencia del Papa,
Sara le dijo: "`Si nosotras somos prisioneras del Papa, apelamos al Papa.
Mándanos, por tanto, a donde él.`" Pero los que tenían su domicilio en la inquisición,
especialmente los frailes, eran enemigos mortales de ellas,
aunque a veces las habrían alimentado con lo mejor de sus
alimentos y les habrían dado botellas enteras de vino,
si ellas lo hubieran recibido.
Esto los molestaba en extremo, que ellas rechazaran comer y beber con ellos;
lo cual ellas hacían, porque ellas los consideraban feroces perseguidores.

Una vez llegaron dos o tres barcos ingleses al puerto,
y el cónsul Inglés contándoles de esto dijo,
que él había hecho lo que había podido por ellas,
pero que no las dejarían ir a menos que se convirtieran en católicas, y por tanto,
ellas todavía debían sufrir encarcelamiento.
Antes que Sara supiera que estos barcos habían llegado
ella los había visto durante la noche en un sueño,
y había oído una voz diciendo que ellas no podían
irse todavía. Cuando los barcos se fueron,
ellas fueron mandadas a buscar y les preguntaron si querían convertirse en católicas,
a lo que respondieron que ellas eran verdaderas cristianas
y que habían recibido el Espíritu de Cristo.
Uno de los magistrados les mostró la cruz;
ellas le dijeron que ellas tomaban la cruz de Cristo cada día,
la cual era el poder de Dios para crucificar el pecado y la iniquidad.
Sabiendo que había un fraile, quien, según les había contado el capitán,
se había tomado grandes molestias por ellas,
y no viéndolo ahí (pues el que las favorecía secretamente estaba ausente),
dijeron a los que estaban presentes:
"`Uno de sus padres nos ha prometido nuestra libertad.`"
Pero esto no sirvió de nada.
Sin embargo, ellas aceptaban la amabilidad de él,
y después le dijeron que él nunca tendría motivo para arrepentirse.

Un fraile una vez fue a donde ellas y les dijo:
"`Es la voluntad de Dios que ustedes sean mantenidas aquí,
o de lo contrario no podríamos retenerlas.`"
A lo que Catharine respondió: "`El Señor permite que hombres perversos hagan maldad,
pero Él no quiere que ellos las hagan.
Él permitió que Herodes decapitara a Juan el Bautista,
pero Él no quería que él lo hiciera;
Él permitió que Esteban fuera apedreado y que Judas traicionara a Cristo,
pero Él no quería que ellos lo hicieran; porque si fuera así,
Él no los habría condenado por eso.`"
Entonces el fraile les preguntó: "`¿Somos nosotros entonces, hombres perversos?`"
Ella respondió: "`Los hombres perversos son los que obran maldad.`"
"`Pero,`" dijo él, "`ustedes no tienen la verdadera fe.`"
Y ella respondió: "`Por fe estamos firmes y por el poder de Dios somos sostenidas.
¿Piensas que es por nuestro propio poder y santidad
que somos guardadas de una conducta vana,
del pecado y la maldad?`"
Entonces al decir él que era por el orgullo de ellas, Catharine le dijo:
"`Nosotras podemos gloriarnos en el Señor, pues una vez fuimos hijas de ira,
así como otros,
pero el Señor nos ha vivificado cuando estábamos muertas
mediante la palabra viva de Su gracia y nos ha lavado,
limpiado y santificado en alma y espíritu, en parte, de acuerdo a nuestra medida,
y proseguimos adelante hacia eso que es perfecto.`"
Él dijo: "`Ustedes son buenas mujeres,
pero aún así no hay redención para ustedes a menos que sean católicas.`"

Esta era la vieja lección de los frailes, quienes en otro momento les dijeron:
"`Ustedes pueden convertirse en católicas y conservar su propia religión,
y no será sabido que son católicas a menos que sean llevadas delante de un juez.`"
A lo que ellas respondieron:
"`¡¿Qué? ¿Qué profesemos un Cristo del que tendríamos que avergonzarnos?!`" Algunos
de los que venían a verlas las compadecían por no convertirse en católicas,
pero otros les mostraban su odio al gritar que ellas debían ser quemadas, o vociferar:
"`_Fuoco, fuoco._`"
(Fuego, fuego)

Mientras permanecían separadas una de la otra,
Catharine a menudo se preocupaba mucho por Sara y temía que pudiera ser atrapada,
pues uno de los frailes solía acosarla con palabras aduladoras.
Pero ambas continuaron firmes,
y con frecuencia se sentían embargadas por el gozo
y la consolación que sentían en el interior.
Catharine contó en una de sus cartas,
que una vez el espíritu de oración había estado sobre ella,
pero que había tenido miedo de hablarle al Señor por temor
a decir una palabra que no le agradara a Él. Y que entonces,
le había sido respondido de parte del Señor: "`No temas, hija de Sión,
pide lo que quieras y Yo te lo concederé; lo que tu corazón desee.`"
Pero Catharine no deseó nada del Señor sino lo que fuera para la gloria de Él,
ya fuera su libertad o cautiverio, su vida o muerte;
y en esta rendición ella fue hallada acepta ante el Señor.

A veces ellas hablaban tan eficazmente a los que llegaban a verlas que no podían refutarlas,
y eran obligados a confesar que Dios estaba con ellas.
Sin embargo, otros hacían un ruido horrible y gritaban:
"`Jesús María,`" y se alejaban corriendo como si hubieran sido golpeados por el temor.
La celda de Catharine estaba tan cerca de la calle
que podía ser escuchada por los que pasaban,
y en algunas ocasiones era movida a llamarlos al arrepentimiento
y a volverse a la luz con la que eran iluminados,
la cual los podía sacar de todos sus caminos y obras de maldad,
para servir al Dios vivo y verdadero en espíritu y en verdad.
Esto alcanzó a algunos tanto, que suspiraban y gemían y se quedaban a escucharla,
pero no mucho después se prohibió so pena de gran sufrimiento.
No obstante,
algunos de los que pasaban por ahí hacia sus '`casas de adoración`' eran tan perversos,
que lanzaban piedras a la ventana de Catharine y con frecuencia
hacían un ruido lastimero y aullaban como perros.
Así eran ellas acosadas, tanto desde el exterior como desde el interior por los frailes,
quienes las amenazaban ferozmente por su atrevido
testimonio contra la idolatría. Una vez,
que ellos le mostraron a Sara un cuadro de la virgen
María y de su bebé pintado en una pared,
y querían que ella los mirara, Sara,
para mostrar su celo contra la adoración a los ídolos, zapateo con su pie y dijo:
"`Malditas todas las imágenes,
todos los hacedores de imágenes y los que caen para adorarlas.`"

Sucedió que unos barcos franceses y españoles llegaron a unirse
con los caballeros de Malta para pelear contra los turcos.
Sara, al oír esto dijo: "`¡Dios está enojado! ¡Dios está enojado!
No salgan para matarse unos a otros.
Cristo no vino para destruir la vida, sino para salvarla.`"
Ella le dijo esto a muchos que estaban persuadidos de obtener la victoria,
pero cayeron derrotados, pues su flota fue golpeada por los turcos,
y regresaron con gran daño. Un fraile yendo una vez adonde Catharine le preguntó,
por qué ella no trabajaba.
Entonces ella preguntó: "`¿Qué trabajo haces tú?`" Él respondió: "`Yo escribo.`"
A esto ella respondió: "`Yo también escribiré, si tú me traes pluma, papel y tinta.`"
Él, que no estaba dispuesto a que ella escribiera le dijo,
que San Pablo había trabajado en Roma,
y que ella tejiendo podría obtener aproximadamente
tres medios peniques al día. Ella le dijo:
"`Si nosotras pudiéramos tener ese privilegio entre ustedes,
el que tuvo Pablo en Roma bajo el César, quien era un príncipe pagano,
trabajaríamos y no seríamos carga para nadie.
Pues él vivió en una casa alquilada por dos años,
predicando el evangelio y la doctrina del Señor Jesucristo.`"
Ella también le preguntó, si él experimentaba la guerra santa de Dios.
"`Y si la experimentas,`" dijo ella,
"`entonces no ignoras que nosotras estamos en prueba día y noche.`"
Esto detuvo la boca del fraile.
Además de que era bien sabido que ellas no pasaban el tiempo ociosamente,
porque tejían medias para los que eran serviciales con ellas,
hacían vestidos para los prisioneros pobres y remendaban sus propias ropas.
Sin embargo, no estaban dispuestas a trabajar para los frailes,
quienes a veces iban adonde Catharine,
se arrodillaban y querían que ella repitiera lo que
decían. Pero ella se rehusaba a hacerlo,
aunque provocaba que estos hombres se enfurecieran.
Tales y similares hechos la afligían tanto,
que una vez en angustia de espíritu clamó a Dios:
"`Mejor me fuera morir que vivir así.`" Pues al ser casi continuamente
obligada a testificar contra la idolatría y superstición,
ella habría estado dispuesta a rendir su vida por el testimonio contra ella,
si le hubiera sido requerido.
Cuando en una ocasión los frailes le dijeron que Sara iba a ser llevada a Roma,
mientras que ella debía permanecer en Malta, esto la afligió tanto,
que con súplica le preguntó al Señor,
si Él no la consideraba digna de ir a Roma también
y de ofrecer su vida ahí por el testimonio de Jesús,
porque si ella tenía la libertad de escoger,
prefería ir que regresar sin Sara a Inglaterra.

En otro momento, cuando les fue dicho que sus Biblias eran falsas,
Catharine le preguntó al fraile que lo había dicho: "`¿En qué son falsas?`"
Él dijo que los libros de los Macabeos no estaban en ellas.
Ella respondió que aunque algo pudiera hacer falta, aún así el resto podría ser bueno,
pero que si algo era añadido, entonces la Biblia estaba corrompida.
Esto golpeó algunos agregados que ella había visto en las Biblias ahí. Luego él le preguntó
si ella no creía que todos debían inclinarse ante el nombre de Jesús,
al responder ella que sí, él dijo:
"`Jesús,`" y le pidió que se arrodillara o se inclinara.
A lo que ella respondió,
que su corazón y todo su cuerpo estaban inclinados ante el nombre de Jesús,
pero que ella no se inclinaría por la voluntad de él o de nadie
más. "`El que se aparta de la iniquidad (continuó ella),
se inclina delante del nombre de Jesús, pero el que vive en pecado y maldad,
no se postra delante del Hijo de Dios.`"
Entonces él dijo que él y sus compañeros estaban en el mismo poder,
y que eran guiados por el mismo Espíritu que los apóstoles.
Lo que la hizo preguntar, el porqué entonces,
ellos abusaban de ese poder y usaban armas carnales.
Él respondió que ellos no lo hacían,
porque tanto su inquisición como sus cadenas y grilletes eran espirituales.
Luego él le preguntó si ella no pensaba que todos
los que no eran de su persuasión estaban malditos.
Ella respondió: "`No, Cristo no nos ha enseñado así,
porque aquellos que hoy están en estado de condenación, si al Señor le place,
pueden ser llamados mañana a salir de ella.`"
Entonces él dijo: "`Nosotros pensamos que ustedes están malditas,
y todos lo que no son de nuestra creencia.`"
A lo cual ella respondió: "`El juicio del hombre no nos hace daño.`"

A veces algunos llegaban a la prisión en sus días
"`santos`" y les preguntaban qué día era.
Ellas al no estar familiarizadas con esos santos respondían: "`No sabemos.`"
Cuando los otros les decían, que ese día era el día de tal o cual santo,
y que dicho santo las castigaría esa noche por no haber guardado su día,
respondían que ellas sabían que los santos estaban en paz con ellas
y que por eso no les temían. En otra ocasión un fraile llegó y
les dijo que faltaban diecisiete días para Navidad,
y que la virgen María había concebido ese día. Sobre lo cual Catharine hizo notar,
que eso en verdad era muy singular,
que ella portara un niño sólo diecisiete días. Tales
y similares sucesos la afligían mucho,
cuando consideraba la gran oscuridad en la que estaban esas personas.
Y mientras clamaba al Señor en oración,
que parecía que todo el trabajo y la labor de ellas era infructuosa,
percibió esta respuesta: "`No te aflijas, aunque Israel no esté reunido,
la semilla de Malta se incrementará en multitud; eso que han sembrado no morirá,
sino que vivirá.`"

Después de que Catharine y Sara habían estado en prisión en Malta cerca de tres años,
llegó un hombre llamado Daniel Baker,
quien hizo lo que pudo (y hasta fue a ver al inquisidor)
para obtener la libertad de ellas,
pero todo fue en vano.
Porque el inquisidor exigía que algunos comerciantes ingleses en Leghorn, o en Messina,
se comprometieran a pagar cuatro mil dólares^
footnote:[Moneda que circulaba en varios países de Europa,
diferente al dólar actual de Estados Unidos]
para que ellas fueran liberadas, y nunca regresaran a esos lugares.
Pero ellas no estaban dispuestos a entrar en esos términos,
ya que no sabían lo que el Señor de un momento a otro podría requerir de ellas.
Daniel, al ver que no podía obtener la libertad de ellas de esta manera,
se ofreció a ser encarcelado en lugar de ellas, y al no ser aceptado fue aún más allá,
y expresó que estaba dispuesto a poner su vida por la libertad de Catharine y Sara,
si no había otro modo de que su libertad fuera comprada.
¡Gran amor, en verdad, del que muy pocos ejemplos son hallados!
Al oír ellas de esto, fueron tocadas con gran admiración. Mientras tanto,
él encontró la manera de que unas cartas les fueran entregadas,
y él mismo les escribió también,
tanto para consolarlas como para exhortarlas a la constancia.
Finalmente, también halló los medios para hablar con ellas; por un momento,
mientras estaban de pie en los portones de la prisión,
él llegó ante ellas y las saludó con estas palabras: "`Justas y muy amadas de Dios,
todo el cuerpo de los elegidos reconoce y respalda sus testimonios.
Ustedes son un sabor dulce para el Señor y Su pueblo.`"
A lo que una de ellas respondió, que era una pena para ellas no poder ser más útiles.
Esto hizo que el corazón de él se derritiera con piedad y compasión,
considerando la maravillosa misericordia del Señor
al preservarlas sin desmayar en esa dura prueba.
Y viéndose unos a otros a la distancia, a través de las rejas de hierro,
fueron mutuamente refrescados en ese momento.
Después ellas le escribieron a él y le declararon, con las más tiernas expresiones,
cuán altamente valoraban su gran amor,
y también le enviaron cartas para sus amigos y familiares en Inglaterra.
Él no dejó de escribirles en respuesta durante su estancia,
que fue en la primera parte del año 1662,
pero se vio forzado a dejarlas en prisión ahí. Sin embargo,
el momento de su rescate se acercaba,
el cual fue llevado a cabo por instancias de George Fox y Gilbert Latey,
al escribirle al señor Aubigny, como ya ha sido dicho.

Un tiempo antes de que Daniel Baker llegara a Malta,
se les había dicho a ellas que si se convertían al catolicismo podrían vivir en Malta.
A lo que ellas respondieron, que ellas eran cristianas verdaderas.
Uno de los magistrados dijo, que si ellas no se hacían católicas,
sufrirían un largo encarcelamiento por orden del Papa.
Sin embargo, no era cierto que tal orden existiera.
También se les dijo,
que si ellas besaban la cruz serían liberadas y podrían
estar en la casa del cónsul Inglés,
hasta que se les ofreciera la oportunidad de ser llevadas a Inglaterra.
Entre tanto,
ellas habían oído que el Papa había dado la orden de que fueran
llevadas a Inglaterra sin causarles ningún daño. Como fuera,
ellas fueron guardadas en contentamiento y resueltamente dijeron que no besarían la cruz,
ni comprarían su libertad a ese precio.
Parece que el cónsul aspiraba a algún beneficio por la liberación de ellas,
porque les dijo que el inquisidor había dicho,
que si alguien se comprometía a pagar tres o cuatro mil dólares y ellas nunca volvían,
serían puestas en libertad (esto también se lo había dicho a Daniel Baker).
Y añadió, que si nadie se comprometía debían morir en prisión,
que esa era la orden del Papa.
Después de la partida de Daniel Baker,
se envió un mensaje a algunos comerciantes ingleses con respecto a tal compromiso,
pero nadie pareció dispuesto a participar en él,
y las prisioneras estaban tan lejos de desearlo, que hablaron contra eso.
Sin embargo, había muchos buscando obtener la libertad de ellas,
mostrándose a sí mismos dispuestos a comprometerse con lo que fuera razonable;
pero todos los esfuerzos fueron en vano.

Una vez ellas ayunaron tres días, y aunque era la estación fría,
se sentaron en el piso con muy poca ropa, sin medias ni zapatos,
y no tenían más que cenizas sobre sus cabezas.
Al ver esto los inquisidores se maravillaron grandemente,
y Sara comenzó a hablar con gran celo en contra de la superstición
e idolatría. Cuando el tiempo de su ayunó acabó,
Catharine compuso lo siguiente:

[.centered]
=== Himno para Dios

[verse]
____
¡Toda alabanza a Aquel que no me ha dejado,
ni de Su mente me ha sacado,
ni Su misericordia de mí ha cerrado,
hasta donde he hallado!

¡Infinita gloria, loor y alabanzas,
sean dadas a Su nombre,
Quien ha dado a conocer en nuestras jornadas,
su fuerza y noble renombre!

¡Oh, nadie es al Cordero semejante,
del que resplandece brillante Su belleza!
¡Oh, que Su santo nombre se exalte,
Su majestad y fuerza!

¡Al único Dios mi alma alaba,
a la fuente pura y clara,
cuya corriente cristalina el exterior alcanza,
y lejos y cerca lava!

¡Los manantiales de eternidad,
muy puros y dulces son,
brotan sin cesar,
para a mi novio encontrar!

¡Mi dulce y querido Amado,
Su voz es para mí,
más que toda la gloria del mundo,
o que los tesoros que pueda descubrir!

¡Él es la gloria de mi vida,
mi gozo y mi placer.
Dentro del seno de Su amor,
me cercó de día y hasta el anochecer!

¡Él me preserva limpia y pura,
dentro de Su habitación,
donde yo con Él estoy segura,
y salva de toda equivocación!

¡Qué mi alma te alabe Señor!
¡Qué te alabe con gozo y paz!
¡Qué mi espíritu y mi mente día y noche,
te alaben sin cesar!

¡Oh, magnifiquen Su majestad,
Su fama y renombre,
Cuya morada es alta en Sión,
la gloria de Su corona!

¡Oh, alabanzas, alabanzas a nuestro Dios!
¡Canten alabanzas a nuestro Rey!
¡Oh, enseñen a la gente en el extranjero,
Sus alabanzas cantar!

¡Una canción brillante de gloria a Sión,
una que muy claro brille.
Oh, manifiéstenla ante la visión,
de las naciones lejos y cerca!

¡Qué Dios tenga Su debida gloria,
Su honor y Su fama
Qué todos Sus santos canten de nuevo,
las alabanzas a Su nombre!
____

Después de que Catharine cantó esto gozosamente,
se fue al pozo del patio y tomó mucha agua a la vista de los prisioneros,
al igual que Sara, pues estaban muy sedientas.
Sara, además,
se lavó la cabeza con agua fría mientras los prisioneros les gritaban en su lengua:
"`Ustedes se matarán a sí mismas y se irán al infierno.`"
Pero ellas ni temían esto ni se enfermaron,
y se convirtieron en un milagro para los demás.

Aproximadamente después de medio año de la partida de Daniel Baker,
entró en el corazón de Catharine, que si ella hablaba con el inquisidor,
él les concedería la libertad.
No mucho después de que él llegó a la sala de la corte, y al saber de su llegada,
ellas solicitaron hablar con él y les fue concedido.
Al ser admitidas en su presencia le dijeron,
que ellas no habían agraviado ni defraudado a nadie, y que sin embargo,
habían sufrido inocentemente casi cuatro años por causa de la consciencia, etc.
Después de esto,
el inquisidor fue muy cortés con ellas y les prometió la libertad en pocos días.
Dijo que enviaría a buscar al cónsul e intentaría hacer que se comprometiera
a pagar 500 dólares si ellas alguna vez regresaban.
Y que en el caso de que el cónsul se negara,
enviaría un recado al Papa en Roma pidiéndole que las pusieran
en libertad sin ninguna obligación de parte de ellas.

No muchos días después, el inquisidor llegó con su teniente, el canciller y otros,
y después de un discurso, les preguntó si querían regresar a sus esposos e hijos,
si esa fuera la voluntad de Dios.
A lo cual ellas respondieron,
que era la intención de ellas hacerlo así en la voluntad de Dios.
En seguida fueron liberadas y el inquisidor se despidió muy cortésmente
de ellas y les deseó un próspero regreso a su país. De igual manera
hicieron los magistrados y los oficiales inferiores,
no requiriendo de ellas un penique por honorarios o asistencia.
Sin embargo, en su propia libertad,
ellas le dieron algo al guardián y a algunos hombres pobres.

Al ser de esta manera liberadas,
se arrodillaron y oraron a Dios que no les tomara
en cuenta lo que ellos les habían hecho,
porque ellos no las conocían. Entonces fueron entregadas en manos del cónsul,
quien les dijo que él se había comprometido por ellas para que fueran liberadas,
pero ellas nunca pudieron encontrar que eso fuera cierto.
Catharine y Sara estuvieron once semanas en la casa del cónsul,
antes de que pudieran obtener un pasaje desde ahí. Mientras tanto, Catharine,
estando bajo una gran preocupación debido a un juicio inminente sobre la ciudad,
escribió un documento a los gobernantes de Malta, en el que decía,
que el 25 del mes llamado Agosto,
había venido sobre ella de parte del Señor escribirles en Su nombre lo siguiente:

"`Mi ira está encendida contra ustedes y mi juicio está establecido entre ustedes,
debido a la dureza de sus corazones e incredulidad.
Yo, el Señor, que no deseo la muerte de ningún hombre,
sino que todos regresen a Mí y vivan,
he enviado a mis siervas entre ustedes (contrario a la voluntad y sin
el conocimiento de ellas) para advertirles del mal que vendría sobre ustedes.
¡Porque todos los impíos serán llevados a juicio!
Yo estableceré a Mi amado Hijo sobre Su trono y Él gobernará en Su regio poder,
y reinará en Su real majestad, Cuyo derecho está sobre todo.
Él establecerá en todos los lugares Su propio gobierno espiritual,
Su mando justo y Su adoración pura en Espíritu y en Verdad.
No hay nada que pueda detener al Señor que dice: Si no oyen a mi sierva,
quien habla mi palabra, a la que ustedes probaron por casi cuatro años,
cuya vida ha sido inofensiva e inmaculada, y ha estado entre ustedes en inocencia pura,
entonces yo traeré ay sobre ay, y juicio sobre juicio sobre ustedes,
hasta que los vivos no puedan sepultar a los muertos.
Mi boca ha hablado esto y mi celo lo hará,
y la mano de cada hombre estará sobre sus lomos por causa del dolor,
porque el día de la recompensa ha llegado.
Pero si oyen a mi sierva quien habla en Mi nombre,
y se vuelven en sus mentes a la luz en sus consciencias,
la cual convence de todo mal y rechaza todos los pensamientos, palabras y actos del mal,
entonces Yo derramaré mi Espíritu sobre ustedes,
y pronto serán curados de sus enfermedades y sanados de su dolor.`"

Esto y más escribió ella,
y se lo entregó al cónsul para que se lo diera al gran maestro y al resto de los gobernadores.
Pero el cónsul no estaba complacido con esto, y la amenazó con encarcelarla de nuevo.
No encuentro qué sucedió con el documento, sino esto,
que el 8 de Octubre hubo grandes truenos y relámpagos
que incendiaron y volaron una de las casas de pólvora,
aproximadamente a una milla de la ciudad, y otra casa de pólvora fue derribada.
En la ciudad, cinco casas se vinieron abajo,
la mayoría de las ventanas de vidrio de los palacios y otras casas se quebraron,
las puertas se despegaron de sus bisagras,
las paredes se rompieron y la ciudad entera fue terriblemente sacudida,
tanto que al ser medianoche, un lamento atravesaba toda la ciudad y las campanas sonaban.
Al pie de la cama donde Catharine y Sara dormían,
había una ventana de vidrio que también se quebró,
pero ellas no recibieron ninguna herida,
aunque la casa se sacudió tanto que ellas estaban muy asustadas y temblando.
Sin embargo, al haberse entregado al Señor para vivir o morir,
el temor pronto fue quitado de ellas y se convirtió en gozo en
el Señor. Cuando llegó la mañana el cónsul fue adonde ellas,
y estando quietas y en silencio, él preguntó si habían muerto.
Mientras él aún hablaba, otros entraron contando lo que había sucedido en la ciudad,
y él les contó que incluso los barcos en el puerto habían sido dañados.
Entonces ellas dijeron: "`¡Un ay ha pasado,
y he aquí otro viene rápidamente si ustedes no se arrepienten!`"

Unos días después Sara ayunó (sentándose en el piso con ceniza sobre su cabeza,
y su cuello y hombros descubiertos),
y le habló al cónsul para que le pidiera al gran maestro que proclamara un ayuno,
e hiciera que el pueblo se reuniera a esperar en el Señor, con sus mentes vueltas a Él,
para que Él apartara Sus juicios de ellos.
Porque la hora de Sus juicios había llegado,
en los que la ramera pintada sería desnudada y recibiría la copa de temblor
de la mano del Señor. El cónsul llevó este mensaje a los magistrados y
los frailes dijeron que la mujer tenía una buena intención. En algún momento
después llegó el inquisidor y hablando con ellas les dijo:
"`La intención de ustedes es buena, pero el diablo las ha engañado.`"
Ellas le preguntaron si el diablo podía dar poder sobre el pecado, a lo que él dijo,
que el diablo podía transformarse en una imagen de luz.
Ellas asintieron a esto, sin embargo dijeron,
que él no podía esconderse de los hijos de luz,
aunque los que estaban en oscuridad no podían discernirlo.
Él no pudo soportar oír esto y se fue, y el cónsul, que estaba presente,
trabajó contra ellas para encerrarlas de nuevo, pero fue en vano.
No mucho después muchos murieron en el pueblo por una fiebre violenta.
Si algún otro desastre siguió la predicción de ellas, no puedo decirlo.

Por fin, una fragata del rey de Inglaterra llamada el Zafiro,
llegó comandada por el capitán Samuel Titswel, quien las acogió,
junto con algunos caballeros de Malta.
Entre ellos estaba el hermano del inquisidor,
quien a menudo le hablaba al capitán para que no
les faltara nada de lo que había en el barco.
También les dijo a ellas que si regresaban a Malta no serían perseguidas.
Al capitán le dijo: "`Si ellas van al cielo de una manera y nosotros de otra, aún así,
todos nos encontraremos al final.`"
Pero ellas le respondieron que Cristo Jesús, la luz del mundo,
era el único camino al Padre.

Después de un tiempo de haber partido de Malta, llegaron a Leghorn,
donde los comerciantes les mostraron gran amabilidad,
les enviaron vino y otras cosas para que se refrescaran, y también les ofrecieron dinero,
pero ellas no estuvieron dispuestas a aceptarlo.
De ahí llegaron a Tánger,
lugar que le pertenecía al rey de Inglaterra por
su matrimonio con la hija del rey de Portugal.
Este lugar estaba sitiado por los moros en ese momento, sin embargo,
Catharine y Sara entraron al pueblo y muchos acudieron
en masa a la casa donde ellas estaban alojadas,
porque ellas valientemente exhortaban al pueblo a salir de la maldad.
Ellas también fueron adonde el gobernador, que fue cortés con ellas,
y recibió en buena parte sus amonestaciones y les prometió seguir su consejo.
Él quería darles dinero, pero ellas no lo tomaron, aunque sí aceptaron su amor,
porque él había mandado que ninguno de la guarnición abusara de ellas,
de palabra ni de hecho, bajo pena de severo castigo.
Aún así,
los portugueses e irlandeses estaban suficientemente listos para
hacerles daño. Estando ellas inclinadas a salir adonde los moros,
le pidieron al gobernador que las dejara ir,
pero él les dijo que ellas sólo podían esperar de esa gente salvaje,
una muerte cruel o un cautiverio para siempre.
Y aunque ellas le indicaron que ellas creían que el Señor las guardaría,
ya que estaban persuadidas de que se les requería ir a los moros; con todo,
el gobernador de manera amigable les impidió ir.
Al ser detenidas, entendieron que el Señor había aceptado la buena voluntad de ellas.
Cuando subieron a bordo de nuevo, aunque en otro barco,
varios tomaron transporte con ellas,
pues tenían la creencia de que por causa de ellas tendrían una travesía segura.
El capitán y otros que estaban en el barco se comportaron muy cortésmente con ellas,
y aunque se toparon con tempestades, al final llegaron seguros a Inglaterra.

Catharine después relató, que mientras estaba en la inquisición,
y por muchos días seguidos a la espera de que fueran quemadas,
vio en un sueño durante la noche, un cuarto grande y un gran fuego en la chimenea,
y observó a uno sentado en una silla al lado del fuego, en forma de siervo,
a quien ella tomó como el Hijo del Dios eterno.
De igual manera, vio a un amable y bien favorecido niño varón,
sentado en un sillón sobre el fuego (que no parecía tener más de nueve meses de edad,
y no tenía más ropa que un lino pequeño y fino alrededor de la parte superior),
y el fuego ardiendo alrededor; sin embargo, el niño jugaba y estaba feliz.
Entonces ella quiso cogerlo por temor a que se quemara,
pero el que estaba sentado en la silla le pidió que lo dejara en paz.
Luego,
volviéndose vio a un ángel y el que estaba sentado
en la silla le pidió a ella que tomara al niño,
lo cual hizo,
y vio que no había sufrido ningún daño. Al despertar le
contó el sueño a Sara y le pidió que no tuviera temor,
ya que la hueste celestial las seguía.

He recopilado este relato de lo que les sucedió a estas mujeres en Malta,
a partir de varios documentos y cartas, los cuales,
no mucho después de su regreso a casa fueron publicados en letra impresa.
Y como no se observó ningún orden ahí y se mencionaron muchas cosas,
las cuales he dejado pasar para evitar la redundancia,
puede que yo haya casualmente perdido, en uno u otro caso,
el orden o la secuencia del tiempo,
pero creo que los hechos reales no han sido alterados.
Ahora, para darle una idea al lector del ánimo de estas mujeres y de sus sufrimientos,
insertaré algunas de sus cartas.
Entre las que escribieron a sus amigos en Inglaterra estaba la siguiente:

"`Oh, queridos y amados amigos, padres y ancianos, pilares de la casa espiritual de Dios;
hermanos y hermanas en el Señor Jesucristo, en la medida del amor y vida de nuestro Dios,
los saludamos a todos y los abrazamos en lo que es eterno.
Nos regocijamos grandemente y glorificamos el nombre de nuestro Padre celestial,
por habernos considerado dignas de participar de
la muerte y sufrimientos de Su bendito Hijo con ustedes.
Aunque somos las más pequeñas del rebaño de Dios, aún así, somos del verdadero redil,
del que Cristo Jesús es el pastor.
Él ha tenido tan tierno cuidado sobre nosotras,
como ha tenido sobre cualquiera de Sus corderos que ha llamado en el día de Su poder.
Él nos ha llevado a través y sobre tan grandes aflicciones,
como a la mayoría de nuestros hermanos y sufrientes por Su nombre; en burlas, mofas,
escarnios, críticas, azotes, desdichas, peligros en la tierra, peligros en el mar,
pruebas de fuego, crueles amenazas, aflicción de corazón, dolor de alma, calores y fríos,
ayunos y vigilias, temores internos y luchas externas,
terribles tentaciones y persecuciones,
pavorosos encarcelamientos y bofetadas de Satanás. Sin embargo,
en todas estas pruebas el Señor ha sido muy misericordioso con nosotras y no se ha apartado,
ni permitido que Su fidelidad nos fallara,
sino que nos ha sostenido y nos ha guardado de desmayar en medio de nuestro apuro.
Nosotras no teníamos a otro ante quien gemir, sino ante el Señor únicamente,
ni podíamos tener expectativa de una gota de misericordia, favor o refrigerio,
sino de lo que Él destilaba de Su presencia viva y obraba mediante Su propia fuerza.
Porque cerca de un año estuvimos sentadas, una en una habitación y la otra en otra,
como búhos en el desierto y personas abandonadas en lugares solitarios.
Entonces disfrutamos la presencia del Señor y contemplamos el resplandor de Su gloria,
y los vimos a ustedes, amigos queridos,
en la luz de Jesús. Contemplamos su orden y la firmeza
de su fe y amor para con todos los santos,
y fuimos refrescadas en todo corazón fiel;
y sentimos el flujo de amor y vida que fluye de los corazones
de los que fueron unidos por completo a la fuente,
y hechas sensibles del beneficio de sus oraciones.

"`¡Oh, las tristezas, los lamentos, las lágrimas!
Pero "`los que sembraron con lágrimas,
con regocijo segarán.`" La verdadera tristeza engendra verdadero gozo,
y la verdadera cruz, verdadera corona.
Pues cuando abundaban nuestras tristezas, el amor de Dios sobreabundaba.
Cuánto más profunda era la tristeza, más grande era el gozo.
Cuánto más grande la cruz, más pesada la corona.

"`Queridos amigos y hermanos, no se maravillen de que Israel no esté reunido,
nuestro juicio queda en el Señor y también nuestro trabajo.
Pues no ha sido por falta de esfuerzo laborioso, ni dolor, ni amor a las almas de ellos,
porque pudimos habernos contentando con ser alimentadas con la hierba del suelo,
si así hubiéramos obtenido libertad de compartir con ellos.
Porque si no hubiera sido por la gran oposición, ellos nos habrían seguido,
como pollitos tras la gallina; tanto grandes como pequeños. ¡Oh!
Los encrespados mares y las furiosas y espumosas olas.
Los vientos tormentosos y las inundaciones.
Las profundas aguas y las altas montañas y colinas.
Las duras piedras, los caminos ásperos y las sendas tortuosas.
Los altos cedros, los fuertes robles,
los árboles sin fruto y corruptos que ponen obstáculos en el suelo,
y estorban para que la Semilla justa no sea sembrada,
ni las plantas nobles sean plantadas.
¡Oh!
Ellos cierran el reino a los sencillos de corazón
y esconden de los inocentes la llave del conocimiento.
Ellos mismos no entran en el reino, ni les permiten que entren,
sino que incitan a los magistrados a desarrollar armas carnales,
con la intención de evitar que el Señor tome para Sí su herencia,
y de esta manera despojar a Su Hijo, al que es heredero de todo.
A fin de que no tenga un lugar de habitación entre ellos,
ni una habitación cerca de ellos,
porque Su luz pondría al descubierto las tinieblas de ellos,
Su resplandor quemaría todas sus abominaciones, desfiguraría su belleza,
mancharía su gloria, su pompa y su orgullo, que perecería como los higos fuera de tiempo,
caería como la flor del campo y se marchitaría como la hierba sobre el terrado.
¡Oh!
El vientre del infierno, las fauces de Satanás,
todo el misterio de la iniquidad está en apogeo.
Toda forma de abominación desoladora se encuentra
donde no debe y es amparada por una ley,
contra la que nadie debe hablar ni caminar en contradicción, bajo pena de muerte.

"`¡Pero alabanzas a nuestro Dios,
porque Él nos llevó a declarar contra ella día a día! ¡Oh!
Los guías ciegos, los espíritus de seducción que hacen que la gente se equivoque,
que los obligan a adorar a la bestia y Su imagen,
a tener su marca en sus frentes y en sus manos,
a inclinarse ante cuadros y paredes pintadas,
a adorar las cosas de sus propias manos y caer ante lo que sus propios dedos han moldeado.
Ellos no les permiten mirar hacia Sión, bajo pena de muerte, ni caminar hacia Jerusalén,
bajo pena de ser quemados en la hoguera,
sino permanecer en Babel y creer lo que sea que digan o hacen que sea verdad.
¡Oh!
Los caminos, las adoraciones, las modas, formas, costumbres, tradiciones,
observaciones e imaginaciones que han arrastrado en sus oscuras adivinaciones,
para mantener a la pobre gente en ceguera e ignorancia,
para que perezcan por falta de conocimiento y sean corrompidos,
porque el camino de la Verdad no es conocido entre ellos.
Todos ellos están de muchas maneras, fuera del único camino verdadero y vivo,
y sus caminos son tantos y tan monstruosos, que son impracticables.
Sin embargo, el Señor nuestro Dios,
ha encendido un fuego en medio de ellos que consumirá todas las formas, modas,
costumbres y tradiciones de los hombres.
Quemará los cardos, espinos, cizaña, rastrojo y árboles infructuosos y corruptos.
Arruinará todos los frutos, obras y labores de los hombres malvados e impíos,
con la plaga de Su iracunda indignación,
y esparcirá a todos Sus enemigos con el torbellino de Su disgusto.
Ellos no conocen las Escrituras;
sus Biblias harían que cualquier corazón honesto llore al contemplarlas,
debido a la corrupción.`"

Esta carta fue firmada por ambas, aunque es posible que Catharine fuera la escritora.
Ella también escribió una carta de exhortación al inquisidor papista en Malta y otra
al fraile Malaquías. Entre las cartas que ella les escribió a su esposo e hijos,
cuento la siguiente como realmente digna de ser entregada a la posteridad:

[.embedded-content-document.letter]
--

[.salutation]
Para las manos de John Evans, mi querido y precioso esposo, y a mis tiernos hijos,
quienes son más queridos y preciosos para mí que la niña de mis ojos:

Muy querido y fiel esposo, amigo y hermano,
engendrado por mi Padre eterno de la Semilla inmortal, del pacto de luz,
vida y bienaventuranza.
Tengo unidad y comunión contigo día y noche, para mi gran refrigerio y continuo consuelo.
¡Alabanzas, alabanzas sean dadas a nuestro Dios para siempre,
quien nos ha unido en lo que ni el mar ni la tierra pueden separar o dividir!

Mi querido corazón,
mi alma te saluda sinceramente a ti y a mis queridos y preciosos hijos,
quienes son queridos y preciosos en la luz del Señor,
para tu gozo infinito y mi eterno consuelo.
¡Gloria a nuestro Señor Dios eternamente,
quien los ha llamado con llamamiento santo y ha hecho que
Su belleza resplandezca sobre ustedes en el día de Su poder!
En este,
Él está preparando Su tesoro y uniendo a Sus fieles
en el vínculo del amor y salvación eternos,
entre quienes Él los ha contado por Su gracia gratuita, en la que les suplico,
queridos corazones, en el temor del Señor, que permanezcan en sus medidas,
de acuerdo a la manifestación de la revelación del Hijo de Dios en ustedes.
Mantengan diligente vigilancia sobre cada pensamiento, palabra y acto,
y dejen que sus mentes permanezcan continuamente en la luz,
donde descubrirán las trampas y cebos de Satanás. Así serán guardados fuera de sus trampas,
redes y pozos, para que no sean esclavizados por él a su voluntad.
¡Oh, mi querido esposo e hijos,
cuán a menudo he derramado mi alma ante el Padre eterno por ustedes,
con ríos de lágrimas noche y día,
para que sean guardados puros y limpios ante los ojos de nuestro Dios.
Para que mejoren sus talentos como las vírgenes prudentes,
y tengan aceite en sus vasijas y sus lámparas ardiendo.
Para que se vistan con la larga y blanca túnica de justicia,
listos para entrar a la recámara y cenar con el Cordero,
y ser alimentados en el banquete de manjares suculentos, donde sus almas son nutridas,
refrescadas, consoladas y satisfechas, y nunca tienen hambre de nuevo!

Mis queridos corazones, ustedes no carecen de enseñanza;
ustedes están en la tierra de bendición, en la que fluye leche y miel,
entre los mayordomos fieles, cuyas bocas están abiertas para justicia,
para declarar los misterios eternos del reino perpetuo,
de las alegrías interminables y de la gloria eterna.
Donde entrará y será bendecido para siempre todo el que esté dispuesto y es obediente.

Mis queridos corazones, las promesas del Señor son grandes,
y todas son Sí y Amén para los que temen Su nombre.
Él consolará a los dolientes en Sión y hará que los abatidos se regocijen en Jerusalén,
a causa de las buenas nuevas.
Los que carguen la cruz con paciencia llevarán la corona con gozo,
pues es a través de perseverantes y pacientes esperas,
que la corona de vida e inmortalidad llega a ser obtenida.
El Señor ha ejercitado mi paciencia y me ha tratado hasta el extremo,
para Su alabanza y mi consuelo eterno;
Él no nos ha faltado en nada en Su propio y debido tiempo.
Nosotras somos testigos de que Él puede aderezar una mesa en el desierto,
tanto espiritual como temporal.
¡Oh, el infinito amor de nuestro Dios, quien es perpetua fuente de todo refrigerio vivo,
y cuyos arroyos cristalinos nunca dejan de correr hacia toda alma
sedienta que respira en pos de los manantiales de vida y salvación!

En nuestra más profunda aflicción, cuando creía que cada respiración fuera la última,
no podía desear no haber venido,
porque yo sabía que había sido llevada por la voluntad de mi Padre para probarme,
con mi querida y fiel amiga.
En todas las aflicciones y miserias, el Señor nos recordó la misericordia,
y no nos dejó ni nos abandonó, ni permitió que Su fidelidad nos fallara.
Más bien hizo que las dulces gotas de Su misericordia destilaran sobre nosotras,
que el resplandor de Su glorioso semblante brillara en nuestros corazones,
y nunca nos faltó en revelaciones o visiones.
¡Oh,
cómo puedo explicar la plenitud del amor de Dios
hacia nuestras almas! ¡Ninguna lengua puede expresarlo,
ningún corazón puede concebirlo, ninguna mente puede comprenderlo! ¡Oh, el embeleso,
el arrebato, el glorioso, resplandeciente y brillante semblante de nuestro Señor Dios,
quien es nuestra plenitud en el vacío, nuestra fuerza en la debilidad,
nuestra salud en la enfermedad, nuestra vida en la muerte, nuestro gozo en la tristeza,
nuestra paz en la inquietud, nuestra alabanza en la pesadez,
nuestro poder en toda necesidad o necesidades! ¡Sólo Él es un Dios pleno,
para nosotras y para todos los que confíen en Él! Él nos ha vaciado de nosotras mismas,
nos ha librado de nosotras mismas y nos ha edificado
por completo sobre un fundamento seguro,
la roca de los siglos, Jesucristo, la Luz del mundo.
En Él, ni los encrespados mares, ni las embravecidas y espumosas olas,
ni los vientos tormentosos, aunque golpeen con vehemencia, pueden movernos.
¡Gloria, honor y alabanza sean dadas a nuestro Dios por siempre,
quien a partir de Sus tesoros eternos nos ha llenado de Sus riquezas eternas
día a día! Él nutrió nuestras almas con la más selecta de Sus misericordias,
alimentó nuestros cuerpos con Su buena creación,
y alivió todas nuestras necesidades plenamente.
¡Alabanzas, alabanzas sean dadas sólo a Él, quien es nuestra porción eterna,
nuestra confianza y nuestro regocijo,
a quien servimos aceptablemente con reverencia y piadoso temor;
porque nuestro Dios es fuego consumidor!

Oh, mi querido esposo y mis preciosos hijos,
ustedes pueden experimentar las emisiones de amor y vida
que fluyen como un río hacia cada una de sus almas,
desde un corazón que está completamente unido a la fuente.
Mis oraciones son por ustedes día y noche, sin cesar,
suplicándole al Señor Dios de poder que derrame Sus tiernas misericordias sobre ustedes,
los guarde en Su temor puro,
incremente la fe de ustedes a fin de que sean confirmados en toda justifica,
los fortalezca al creer en el nombre del Señor Dios Todopoderoso,
para que sean establecidos como el Monte de Sión y nunca sean movidos.
Mantengan sus almas sin mancha del mundo, y ámense unos a otros entrañablemente,
de corazón puro.
Sírvanse unos a otros en amor, edifíquense unos a otros en el Eterno,
sobrelleven los unos las cargas de los otros por
el bien de la Semilla y cumplan así la ley de Dios.
Esta es la palabra del Señor para ustedes, mis amados.

Amados corazones, los encomiendo a las manos del Todopoderoso, quien habita en lo alto,
y a la Palabra de Su gracia en ustedes,
quien es capaz de edificarlos para vida y eterna salvación. Por mí,
quien soy tu amada y preciosa esposa y cónyuge, en el matrimonio del Cordero,
en el lecho sin mancilla,

[.signed-section-signature]
C+++.+++ E.

[.signed-section-context-close]
Escrito en la Inquisición en Malta, en el mes 11, del año 1661

[.postscript]
Mi amada compañera de yugo en la obra de nuestro Dios, cariñosamente te saluda.
Saluda con cariño a nuestros preciosos amigos en todo lugar.
Creo que veré sus rostros de nuevo con gozo.

--

[.offset]
La siguiente carta fue escrita por Sara a su esposo, Henry Cheevers y a sus hijos.

[.embedded-content-document.letter]
--

[.salutation]
Mi querido esposo,

Mi amor y mi vida están rendidos al servicio del
Dios vivo y a la obediencia de Su llamado puro,
en la medida de la manifestación de Su amor, luz, vida y Espíritu de Cristo Jesús,
Su unigénito Hijo.
A quien Él ha hecho manifiesto en mí, y en miles, mediante el resplandor de Su aparición,
para ponerle fin al pecado y a Satanás,
y sacar a la luz la inmortalidad a través de la predicación del evangelio eterno,
por medio del Espíritu de profecía,
el cual es derramado sobre los hijos e hijas del Dios vivo, según Su propósito;
para el cual Él me ha escogido, a mí que soy la más pequeña de todos.
Pero Dios, que es rico en misericordia, por amor a Su propio nombre,
ha pasado por alto muchas ofensas y me ha considerado
digna de llevar testimonio de Su santo nombre,
ante poderosos hombres de la tierra.
¡Oh, el amor del Señor para con mi alma!
Mi lengua no puede expresar, ni ha entrado en el corazón del hombre,
concebir las cosas que Dios ha guardado para los que le temen.

Por tanto, mi alma respira anhelante a mi Dios por ti y por mis hijos,
noche y día. Para que sus almas sean unidas a la luz del Señor Jesús,
a fin de que sean trasladados del reino de Satanás al reino de Dios,
donde podemos disfrutarnos unos a otros en la vida eterna,
y donde ni el mar ni la tierra pueden separarnos.
En dicha luz y vida los saludo, mi querido esposo y amados hijos,
deseando que abracen el amor de Dios,
y que Él haga que Su verdad se manifieste muy claramente entre ustedes.
De lo cual yo soy testigo, es decir,
de la fuente eterna que ha sido abierta por los mensajeros de Cristo,
quienes les predican la palabra de Dios, a tiempo y fuera de tiempo,
dirigiéndolos donde puedan encontrar a su Salvador,
para que purguen y sean limpiados de sus pecados,
sean reconciliados con Su Padre y tengan unidad con Él y con todos los santos en luz,
y para que puedan ser conciudadanos en el reino de gloria, reposo y paz,
que Cristo ha comprado para los que lo aman y le obedecen.
¿Qué provecho tiene para un hombre ganar el mundo entero si pierde su alma?
Busquen primero Su reino y Su justicia, y todas las otras cosas les serán añadidas.
Porque la piedad para todo aprovecha,
pues tiene promesa de esta vida presente y de la venidera, la cual se cumple para mí,
que he gustado el amor y las misericordia infinitas del Señor en mi alma.
El movimiento del mismo amor y de la misma vida anhelo para ustedes,
mi querido esposo y mis queridos hijos.
Mi querido amor los saluda a todos.
Mis oraciones a Dios son por todos ustedes,
para que sus mentes sean unidas en la luz con la que son iluminados,
y yo pueda disfrutarlos en lo que es eterno y tener comunión con ustedes en espíritu.
El que es unido al Señor es un espíritu, un corazón, una mente, un alma,
para servirle al Señor de común consentimiento.
No puedo por medio de pluma y papel expresar el gran amor de Dios,
al cumplir Sus misericordiosas promesas para mí en el desierto,
al estar en prisión por la verdad de Dios y permanecer todos los días de mi vida,
siendo buscada, probada, examinada y bajo pena de muerte,
entre los enemigos de Dios y Su verdad.
Al estar en peligro por mi vida,
hasta que el Señor los sojuzgó y sometió por Su poderosa fuerza,
e hizo que nos alimentaran y quisieran darnos dinero y ropa; sin embargo,
el Señor engalanó nuestra mesa ricamente en el desierto.
El día del Señor está apareciendo,
en el que Él descubrirá toda obra de las tinieblas
sin importar cuán secretamente se haga.
La luz de Cristo Jesús lo pondrá de manifiesto en cada consciencia;
el Señor desgarrará todas las cubiertas que no son de Su propio Espíritu.
El Dios de paz sea con todos ustedes.
Amén.

[.signed-section-closing]
Escrito en la prisión de la Inquisición por,

[.signed-section-signature]
Sara Cheevers

--

Tanto ella como Catharine escribieron varias otras cartas a sus esposos y familiares,
pero como gran parte de mi relato fue extraído de ellas, las deje pasar.
Sin embargo, por medio de estas que inserté,
uno puede ver que ellas no eran mujeres de temperamento ingenuo,
sino ingeniosas y alegres.

[.offset]
En una carta de Sara a sus amigos en Irlanda, encontré estas palabras:

[.embedded-content-document.letter]
--

Mi vida está rendida al servicio del Señor: ataduras, cadenas, pernos, hierros,
puertas dobles y la muerte misma,
es demasiado poco por el testimonio de Jesús y por la palabra de Dios.
Por tanto, es un sacrificio razonable con tal que la Semilla sea reunida.
Los lazos y las aflicciones suceden en el evangelio de Cristo.
Los que quieran vivir piadosamente en Cristo Jesús, deben sufrir persecución.

--

[.offset]
Catharine escribe en una carta dirigida a Daniel Baker,

[.embedded-content-document.letter]
--

El tiempo es demasiado poco para que yo revele
la vigésima parte de las terribles pruebas.
Sin embargo, cada vez que fuimos llevadas a alguna prueba,
el Señor quitó todo temor de nosotras, multiplicó nuestras fuerzas,
y nos dio poder y osadía para abogar por la Verdad del Señor Jesús,
y sabiduría de palabras para tapar la boca de los detractores.
Pero entonces decían que nosotras no teníamos la verdadera fe,
pero que teníamos todas las virtudes.
Estimado hermano, ore por nosotras, que no caigamos ni fallemos,
para que nuestros enemigos no tengan ninguna ventaja de gozarse y decir,
que nosotras servimos a un Dios que no puede servirnos,
y que invocamos a un Dios que no puede liberarnos.
Como si nosotras fuéramos como ellos, que recurrimos a los cepos,
e invocamos a las piedras, cuadros, paredes pintadas y cosas muertas, que no pueden oír,
ver ni hablar.
Te suplicamos que le cuentes a todos nuestros queridos amigos, padres y ancianos,
los pilares de nuestro edificio espiritual,
junto con el resto de nuestros hermanos cristianos,
que deseamos sus oraciones porque tenemos necesidad de ellas.

--

[.offset]
Ellas concluyen esta carta con el siguiente poema:

[verse]
____
¡Cuán fuerte y poderoso es nuestro Rey,
para todos los que en Él creen!
Él los guarda de los que los quieren lazar,
y a la fuerza los quieren desgarrar.

En nosotros los que sufrimos por la Semilla,
nuestros corazones están heridos y sangran,
al ver la opresión y la crueldad,
de los hombres que niegan Tu Verdad.

En fuertes prisiones y profundas mazmorras
sólo a Dios clamamos y lloramos.
Nuestras penas nadie las puede aprender ni leer,
sino los que nuestro camino han de recorrer.

Pero Aquel cuya belleza brillante resplandece
El que vuelve las tinieblas en luz,
hace que los cedros se inclinen y los robles se doblen,
ante el que es enviado para el mismo fin.

Él es una fuente pura y clara,
Sus cristalinos arroyos corren lejos y cerca,
para limpiar a todo el que a Él se acerca,
Para ser sanado de su pecado.

Todos aquellos que pacientemente permanecen,
y nunca se desvían ni se descarrían,
el Señor los librará de toda
opresión, cautiverio y esclavitud.
____

Ellas compusieron varios otros que cayeron en las manos de sus enemigos,
y copias de ellos le fueron dados al inquisidor.
Y ahora las dejo.
